### ISSUE TITLE
Shouldn't .where() pass the attributes of DataArrays and DataSets? 

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1009]
Everything is in the title! I think it should, if possible.

**Comment by shoyer** [comment]
Yes, I agree. `.fillna()` should also preserve attributes.

**Comment by fmaussion** [comment]
With a `keep_attrs` keyword, like `.mean()`, or always?

Since we are at it: what was the rationale behind not keeping the attributes per default everywhere?

**Comment by shoyer** [comment]
I think we can keep attributes always for this operations.

The line I tried to draw was:
- For operations that rearrange/manipulate existing data, keep attributes
- For operations that do computation to produce new data, drop attributes

**Comment by fmaussion** [comment]
OK, that makes sense. It gives me some trouble with the geoloc accessor I am working on, but that's another story. 

I'll try to put a PR together soon.
