### ISSUE TITLE
'levels' tick labels for discrete colormaps

### ISSUE THREAD

**Issue by paulvija** [pydata/xarray#1015]
Hi there,

'levels' tick labels for discrete colormaps works fine for 10 intervals and tend to shorten by itself beyond 10. This behavior may exist to make colorbar exceeding 10 intervals look tidy.

However, for **discrete** colormaps it will be good to label the ticks for all intervals as they can be any number and not uniform.
xray.**version** = '0.8.2'

Please see the screenshots attached for a better understanding.

Thanks,
Vijay Paul
![image](https://cloud.githubusercontent.com/assets/12703555/18734627/6bba1b54-80ca-11e6-9121-d3138cc71af1.png)

![image](https://cloud.githubusercontent.com/assets/12703555/18734553/bf405c1c-80c9-11e6-8efa-6aa7db1afad3.png)
![image](https://cloud.githubusercontent.com/assets/12703555/18734557/ca46f530-80c9-11e6-8c6c-4c0c1985ab41.png)

**Comment by shoyer** [comment]
Agreed, this would be nice. See also #920.

**Comment by fmaussion** [comment]
Note that currently the colorbar labelling logic is handed over entirely to matplotlib, so its mpl which decides upon this. With the ``cbar_kwargs`` argument you can control this at your whish, so I'm not sure we have to change anything:

```python
from matplotlib import pyplot as plt
import xarray as xr

data = xr.DataArray(np.arange(12).reshape((3, 4))*10 + 10)
levels = np.append(np.arange(10)*10 + 10, 115)

f, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14, 4))

data.plot(ax=ax1, levels=levels)
data.plot(ax=ax2, levels=levels, cbar_kwargs={'ticks':levels})
data.plot(ax=ax3, levels=levels, cbar_kwargs={'ticks':levels, 'spacing':'proportional'})
plt.tight_layout()
```
![cb](https://cloud.githubusercontent.com/assets/10050469/18742313/c72b2832-80b3-11e6-9ded-1c21875047c8.png)

**Comment by paulvija** [comment]
**cbar_kwargs works well for my purpose. Thanks for the help.** 
Can this usage be shown in the documentation, at least mentioning that colorbar intervals can be placed at our wish or this comes under matplotlib?

**Comment by shoyer** [comment]
@paulvija @fmaussion either of you interested in putting together a PR? :)

**Comment by paulvija** [comment]
PR?

Date: Thu, 22 Sep 2016 18:50:52 -0700

**Comment by shoyer** [comment]
Sorry, PR is github short hand for "pull request". See
http://pandas.pydata.org/pandas-docs/stable/contributing.html for guidance.

**Comment by paulvija** [comment]
Got it! Thanks, I am keen to contribute with a short example.

Date: Thu, 22 Sep 2016 19:00:05 -0700

**Comment by paulvija** [comment]
Got it! Thanks, I am keen to contribute with a short example.

**Comment by dcherian** [comment]
Should we set `cbar_kwargs` to contain `{'ticks':levels, 'spacing':'proportional'}` when `levels` is specified or only have this as a documentation fix?

**Comment by fmaussion** [comment]
I think a doc example would be enough. For example in the gallery? http://xarray.pydata.org/en/latest/auto_gallery/index.html

**Comment by paulvija** [comment]
Sorry this documentation job slipped out of my radar, @shoyer - if still keen I can contribute to the documentation?

**Comment by shoyer** [comment]
Yes, documentation would be welcome here.
