### ISSUE TITLE
Extract value for given time latitude and longitude

### ISSUE THREAD

**Issue by slharris** [pydata/xarray#1025]
I would like to loop through a list of dates, latitudes and longitudes and extract the maximum daily temperature from an hourly dataset of netcdf files. This appears more difficult than I thought it would be because I cannot seem to use the given latitude and longitude (even though I know the latitude and longitude matching the grid point). 

ds = xray.open_mfdataset('/DATA/WRF/*/*/*Temp.nc')
ds_variable=ds['Temp']
dailymax=ds_variable.resample('D', dim='time', how='max')

MaxTempattime=dailymax.sel(time='2015-02-01') 
MaxTempatpoint=MaxTempattime.isel(latitude=-39.1495, longitude=140.848) #this is where the problem occurs

print MaxTempatpoint.values

I see 'slice' can take a given latitude and longitude but I can't set a range for each of the thousands of points I need. Should I be using some type of index for latitude and longitude?
Any feedback on the best approach for extracting a value at a given time, latitude and longitude will be greatly appreciated.

**Comment by fmaussion** [comment]
Hi @slharris ,

Note that ``.isel()`` is for integer indexing while ``.sel()`` is for indexing by value (probably what you want).

if you want a range of values you should give a slice as argument, as indicated in the [documentation](http://xarray.pydata.org/en/stable/indexing.html#indexing-with-labeled-dimensions): e.g. ``.sel(longitude=slice(34, 67))``

(PS: when you report a problem it would be useful to also post the error message, which is more informative than "#this is where the problem occurs")

**Comment by slharris** [comment]
Thanks for your response.
I am not wanting a range of values that is why I don't want to use slice - I just want the value at the given time, latitude and longitude. 

If I use .isel() I receive an 'Assertion Error' on this line:
MaxTempatpoint=MaxTempattime.isel(latitude=-39.14952469, longitude=140.84791565)

and if I use .sel() I receive a 'Key Error' -  KeyError: -39.14952469  on this line:
MaxTempatpoint=MaxTempattime.sel(latitude=-39.14952469, longitude=140.84791565)

I haven't pasted entire error message because I am assuming the issue I am having is simple?? 

Should I some how convert the latitude and longitude to a different data type and then access? Or is there some way of accessing an index for the latitude and longitude?
Any feedback will be greatly appreciated.

**Comment by fmaussion** [comment]
Without knowing how your data looks like it's difficult to say, but maybe you are getting a ``KeyError`` because of floating point precision issues. Maybe the keyword ``method='nearest'`` will be useful to you?

See the doc for other examples: http://xarray.pydata.org/en/stable/indexing.html#nearest-neighbor-lookups

**Comment by slharris** [comment]
Brilliant - thank you!

**Comment by fmaussion** [comment]
Glad that it worked out for you. Maybe you can close this issue?
