### ISSUE TITLE
multidim groupby on dask arrays: dask.array.reshape error

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#1026]
If I try to run a groupby operation using a multidimensional group, I get an error from dask about "dask.array.reshape requires that reshaped dimensions after the first contain at most one chunk".

This error is arises with dask 0.11.0 but NOT dask 0.8.0.

Consider the following test example:

``` python
import dask.array as da
import xarray as xr

nz, ny, nx = (10,20,30)
data = da.ones((nz,ny,nx), chunks=(5,ny,nx))
coord_2d = da.random.random((ny,nx), chunks=(ny,nx))>0.5
ds = xr.Dataset({'thedata': (('z','y','x'), data)},
                coords={'thegroup': (('y','x'), coord_2d)})
# this works fine
ds.thedata.groupby('thegroup')
```

Now I rechunk one of the later dimensions and group again:

``` python
ds.chunk({'x': 5}).thedata.groupby('thegroup')
```

This raises the following error and stack trace

```
ValueError                                Traceback (most recent call last)
<ipython-input-16-1b0095ee24a0> in <module>()
----> 1 ds.chunk({'x': 5}).thedata.groupby('thegroup')

/Users/rpa/RND/open_source/xray/xarray/core/common.pyc in groupby(self, group, squeeze)
    343         if isinstance(group, basestring):
    344             group = self[group]
--> 345         return self.groupby_cls(self, group, squeeze=squeeze)
    346 
    347     def groupby_bins(self, group, bins, right=True, labels=None, precision=3,

/Users/rpa/RND/open_source/xray/xarray/core/groupby.pyc in __init__(self, obj, group, squeeze, grouper, bins, cut_kwargs)
    170             # the copy is necessary here, otherwise read only array raises error
    171             # in pandas: https://github.com/pydata/pandas/issues/12813>
--> 172             group = group.stack(**{stacked_dim_name: orig_dims}).copy()
    173             obj = obj.stack(**{stacked_dim_name: orig_dims})
    174             self._stacked_dim = stacked_dim_name

/Users/rpa/RND/open_source/xray/xarray/core/dataarray.pyc in stack(self, **dimensions)
    857         DataArray.unstack
    858         """
--> 859         ds = self._to_temp_dataset().stack(**dimensions)
    860         return self._from_temp_dataset(ds)
    861 

/Users/rpa/RND/open_source/xray/xarray/core/dataset.pyc in stack(self, **dimensions)
   1359         result = self
   1360         for new_dim, dims in dimensions.items():
-> 1361             result = result._stack_once(dims, new_dim)
   1362         return result
   1363 

/Users/rpa/RND/open_source/xray/xarray/core/dataset.pyc in _stack_once(self, dims, new_dim)
   1322                     shape = [self.dims[d] for d in vdims]
   1323                     exp_var = var.expand_dims(vdims, shape)
-> 1324                     stacked_var = exp_var.stack(**{new_dim: dims})
   1325                     variables[name] = stacked_var
   1326                 else:

/Users/rpa/RND/open_source/xray/xarray/core/variable.pyc in stack(self, **dimensions)
    801         result = self
    802         for new_dim, dims in dimensions.items():
--> 803             result = result._stack_once(dims, new_dim)
    804         return result
    805 

/Users/rpa/RND/open_source/xray/xarray/core/variable.pyc in _stack_once(self, dims, new_dim)
    771 
    772         new_shape = reordered.shape[:len(other_dims)] + (-1,)
--> 773         new_data = reordered.data.reshape(new_shape)
    774         new_dims = reordered.dims[:len(other_dims)] + (new_dim,)
    775 

/Users/rpa/anaconda/lib/python2.7/site-packages/dask/array/core.pyc in reshape(self, *shape)
   1101         if len(shape) == 1 and not isinstance(shape[0], Number):
   1102             shape = shape[0]
-> 1103         return reshape(self, shape)
   1104 
   1105     @wraps(topk)

/Users/rpa/anaconda/lib/python2.7/site-packages/dask/array/core.pyc in reshape(array, shape)
   2585 
   2586     if any(len(c) != 1 for c in array.chunks[ndim_same+1:]):
-> 2587         raise ValueError('dask.array.reshape requires that reshaped '
   2588                          'dimensions after the first contain at most one chunk')
   2589 

ValueError: dask.array.reshape requires that reshaped dimensions after the first contain at most one chunk
```

I am using the latest xarray master and dask version 0.11.0. Note that the example works _fine_ if I use an earlier version of dask (e.g. 0.8.0, the only other one I tested.) This suggests an upstream issue with dask, but I wanted to bring it up here first.

**Comment by shoyer** [comment]
This was an intentional change -- see https://github.com/dask/dask/pull/1469

Previously, we created lots of teeny tasks, which tended to negate any out of core benefits. The problem is that reshape promises an order to the elements it reshape which tends to split across existing chunks of dask arrays.

We could work around this in xarray by adding custom logic to `stack` for keeping chunks together when reshaping, but we can't do this upstream in dask because we need to make sure we keep all the arrays aligned.

**Comment by rabernat** [comment]
> We could work around this in xarray by adding custom logic to stack for keeping chunks together when reshaping

If you give me a few hints about how to approach this, I can try a PR. I need this rather urgently for an ongoing project.

**Comment by shoyer** [comment]
It would look something like this: 

1. Verify that `chunks` are the same on all dask arrays to be stacked.
2. Use `np.ravel` with `map_blocks` to flatten each block independently.
3. Construct the appropriate (non-sorted) MultiIndex to label the flattened elements.

**Comment by byersiiasa** [comment]
Hi @rabernat and @shoyer 
I have come across same issue while re-running some old code now uxing xarray 0.9.1 / dask 0.11.0. Was there any workaround or solution?

Issue occurs for me when trying to unstack 'allpoints', e.g.
```
mle = stacked.dis.groupby('allpoints').apply(combogev)
dsmle = mle.unstack('allpoints')
```

Thanks

**Comment by shoyer** [comment]
@byersiiasa can you share what `stacked.dis` looks like?

**Comment by byersiiasa** [comment]
```
<xarray.DataArray 'dis' (time: 30, allpoints: 259200)>
array([[  9.969210e+36,   9.969210e+36,   9.969210e+36, ...,   9.969210e+36,
          9.969210e+36,   9.969210e+36],
       [  9.969210e+36,   9.969210e+36,   9.969210e+36, ...,   9.969210e+36,
          9.969210e+36,   9.969210e+36],
       [  9.969210e+36,   9.969210e+36,   9.969210e+36, ...,   9.969210e+36,
          9.969210e+36,   9.969210e+36],
       ..., 
       [  9.969210e+36,   9.969210e+36,   9.969210e+36, ...,   9.969210e+36,
          9.969210e+36,   9.969210e+36],
       [  9.969210e+36,   9.969210e+36,   9.969210e+36, ...,   9.969210e+36,
          9.969210e+36,   9.969210e+36],
       [  9.969210e+36,   9.969210e+36,   9.969210e+36, ...,   9.969210e+36,
          9.969210e+36,   9.969210e+36]])
Coordinates:
  * time       (time) datetime64[ns] 1971-01-01 1972-01-01 1973-01-01 ...
  * allpoints  (allpoints) MultiIndex
  - lon        (allpoints) float64 -179.8 -179.8 -179.8 -179.8 -179.8 -179.8 ...
  - lat        (allpoints) float64 89.75 89.25 88.75 88.25 87.75 87.25 86.75 ...
```

**Comment by shoyer** [comment]
That array is loaded in numpy already - can you share the dask version?

**Comment by byersiiasa** [comment]
I have been re-running that script  you helped me with in Google groups:
https://groups.google.com/forum/#!searchin/xarray/combogev%7Csort:relevance/xarray/nfNh40Zt3sU/WfhavtXgCAAJ

do you mean the delayed object from within the function?
perhaps `<bound method Array.visualize of dask.array<from-va..., shape=(11L,), dtype=float64, chunksize=(11L,)>>`

or perhaps
`Delayed('fit-3767d9ad6cfa517555b5800b3b5f4e41')`

I am going to keep trying with different versions of dask since this 0.9.0 doesn't seem to behave it did previously.

**Comment by shoyer** [comment]
@byersiiasa What matters for dask's `reshape` is the array shape and chunk shape, all of which you should see when you print a dask.array (or xarray.DataArray containing one). What is the size of the chunking along time and allpoints?

**Comment by byersiiasa** [comment]
So, not sure if this is helpful but I'll leave these notes here just in case.

- 0.11.0 - similar problem to @rabernat above
**- 0.10.1 - seems to work fine for what I wanted  (delayed)**
- 0.9.0 - appeared to work ok, but actually I'm not convinced it was parallelising the tasks. And also resulted in massive memory issues
- 0.14.0 - another problem, can't remember what but issue to do with delayed I think.

**Comment by byersiiasa** [comment]
@shoyer No chunking as the dataset was quite small (360x720x30).  Also, the calculation is along the time dimension so this effectively disappears for each lat/lon. Hence initial surprise why it was coming up with this chunk/reshape issue since I thought all it has to do is unstack 'allpoints'

 If I print one of the dask arrays from within the function
```
print sT
dask.array<from-va..., shape=(11L,), dtype=float64, chunksize=(11L,)>
```
This is 11L because the calculation returns 11 values per point to an xr.Dataset.

Others have no chunks because they are single values (for each point)
```
print p_value
dask.array<from-va..., shape=(), dtype=float64, chunksize=()>
```
Only returns one value per point
The object returned (xr.Dataset) from the .apply function comes out with chunks:
`mle.chunks
 Frozen(SortedKeysDict({'allpoints': (1, 1, 1, 1, 1......(allpoints)....., 1, 1), 'T': (11L,)}))`

and looks like:
```
<xarray.Dataset>
Dimensions:            (T: 11, allpoints: 259200)
Coordinates:
  * T                  (T) int32 1 5 10 15 20 25 30 40 50 75 100
  * allpoints          (allpoints) MultiIndex
  - allpoints_level_0  (allpoints) float64 40.25 40.25 40.25 40.25 40.25 ...
  - allpoints_level_1  (allpoints) float64 22.75 23.25 23.75 24.25 24.75 ...
Data variables:
    xi                 (allpoints) float64 -0.6906 -0.6906 -0.6906 -0.6906 ...
    mu                 (allpoints) float64 9.969e+36 9.969e+36 9.969e+36 ...
    sT            (allpoints, T) float64 9.969e+36 9.969e+36 9.969e+36 ...
    KS_p_value         (allpoints) float64 3.8e-12 3.8e-12 3.8e-12 3.8e-12 ...
    sigma              (allpoints) float64 5.297e-24 5.297e-24 5.297e-24 ...
    KS_statistic       (allpoints) float64 0.6321 0.6321 0.6321 0.6321 ...
```

**Comment by shoyer** [comment]
This is what I was looking for:

> `Frozen(SortedKeysDict({'allpoints': (1, 1, 1, 1, 1......(allpoints)....., 1, 1), 'T': (11L,)}))`

So in this case (where the chunk size is already 1), dask.array.reshape could actually work fine and the error is unnecessary (we don't have the exploding task issue). So this could potentially be fixed upstream in dask.

For now, the best work-around (because you don't have any memory concerns) is to "rechunk" into a single block along the last axis before reshaping, e.g., `.chunk(allpoints=259200)` or `.chunk(allpoints=1e9)` (or something arbitrarily large).

**Comment by byersiiasa** [comment]
Thanks - this is working well.

Reverting back to xarray 0.8.2 and dask 0.10.1 seems to be a combination that worked well for this particular task using delayed.

**Comment by mrocklin** [comment]
Fixed upstream, I think, in https://github.com/dask/dask/pull/2089

**Comment by mrocklin** [comment]
(along with now supporting many other reshape options)

**Comment by rabernat** [comment]
We should check if this issue is resolved.

**Comment by shoyer** [comment]
Indeed, it looks like this works now. Extending the example from the first post:
```
In [3]: ds.chunk({'x': 5}).thedata.groupby('thegroup').mean()
Out[3]:
<xarray.DataArray 'thedata' (thegroup: 2)>
dask.array<shape=(2,), dtype=float64, chunksize=(1,)>
Coordinates:
  * thegroup  (thegroup) object False True
```
