### ISSUE TITLE
Extra arguments in templated doc strings are not being replaced properly

### ISSUE THREAD

**Issue by pwolfram** [pydata/xarray#1033]
For example, at http://xarray.pydata.org/en/stable/generated/xarray.Dataset.prod.html?highlight=prod, _func_ should actually be _prod_:

![screenshot 2016-10-03 13 48 07](https://cloud.githubusercontent.com/assets/4295853/19051376/09bf41fa-8970-11e6-903d-f10530aef61d.png)

**Comment by shoyer** [comment]
Yeah, I noticed this but never had time to dig into it.

**Comment by dcherian** [comment]
Fixed now
