### ISSUE TITLE
convert xarray dataset to local timezone

### ISSUE THREAD

**Issue by slharris** [pydata/xarray#1036]
Can I convert an xarray dataset to a different timezone?
I have tried using similar steps that I would use in pandas to convert from UTC to 'Australia/Sydney'. I have pasted below some of these steps, along with a small section of the dataset I am working with.
Any feedback will be greatly appreciated.

ds = xray.open_mfdataset('/DATA/WRF/*/*/*T_SFC.nc')
                 
import pytz                                                     
ds_utc = ds['time'].tz_localize(pytz.UTC)
au_tz = pytz.timezone('Australia/Sydney')
ds_local = ds_utc.astimezone(au_tz)

<xray.Dataset>
Dimensions:    (latitude: 106, longitude: 193, time: 17520)

Coordinates:
  * latitude   (latitude) float32 -39.2 -39.1495 -39.099 -39.0486 -38.9981 ...
  * longitude  (longitude) float32 140.8 140.848 140.896 140.944 140.992 ...
  * time       (time) datetime64[ns] 2009-01-01 2009-01-01T01:00:00 ...

Data variables:
    T_SFC      (time, latitude, longitude) float64 13.83 13.86 13.89 13.92 ...

Attributes:
    creationTime: 1431922712
    creationTimeString: Sun May 17 21:18:32 PDT 2015
    Conventions: COARDS

**Comment by shoyer** [comment]
Do any of the `tz_localize` or `astimezone` lines work? If so, that would surprise me. We do not have any methods related to timezone support in xarray.

That said, it *should* **probably** work (not tested) to manipulate `ds['time'].to_index()` as a pandas Index and then save it back in an xarray Dataset.

**Comment by slharris** [comment]
Thank you  - ds['time'].to_index() seems to work but I am having trouble replacing the UTC time in the ds with the converted local time in my new ds. I am using .update() because I want to override the original time. However, the time does not seem to have been changed following this step.

import pandas as pd
import xray
import pytz   

ds = xray.open_mfdataset('/DATA/WRF/*/*/*T_SFC.nc')               

time=ds['time'].to_index()
                                           
time_utc = time.tz_localize(pytz.UTC)
au_tz = pytz.timezone('Australia/Sydney')
time_local = time_utc.tz_convert(au_tz)

#convert pandas datetimeindex to a series and then series to xarray dataarray and then to xray dataset
local_series=time_local.to_series()
local_da=xray.DataArray.from_series(local_series)
local_ds=xray.DataArray.to_dataset(local_da)

#create a new dataset that replaces/updates the UTC time in the original dataset with the local time from the newly created dataset (in pandas)
new_ds=ds.update(local_ds)
