### ISSUE TITLE
DataArray.diff dim argument should be optional as is in docstring

### ISSUE THREAD

**Issue by smartass101** [pydata/xarray#1040]
The dosctring of `DataArray.diff` lists the `dim` arg as optional, [but it isn't](https://github.com/pydata/xarray/blob/fbb4f0618eade20981bd5cfb9771b82fd88a8db5/xarray/core/dataarray.py#L1468). IMHO it should indeed be optional as it is quite convenient to apply `diff` to 1D signals without specifying the dimension.

**Comment by shoyer** [comment]
Seems reasonable to me. Want to put together a PR?

**Comment by dcherian** [comment]
@smartass101 I was about to open an issue for this. Looks like you have already solved it. Wanna open a PR?

**Comment by keewis** [comment]
this is still relevant. Should we update the docstring or the implementation? If we choose the latter we might be able to pick the commit by @smartass101 (or he might open a PR for it if he's still around?)

**Comment by max-sixty** [comment]
I'm low confidence keener on a consistent API that doesn't depend on the number of dimensions, rather than saving a kwarg, so would vote +0.1 on retaining the implementation and changing the docstring, such that it's required to pass a dimension name even with one dimension.

**Comment by dcherian** [comment]
I agree.

**Comment by smartass101** [comment]
These days I mostly use `.differentiate('coord')` anyways, so I'm also for updating the docstring.
