### ISSUE TITLE
to_dataset lossy

### ISSUE THREAD

**Issue by tdimiduk** [pydata/xarray#1047]
I am looking at saving a DataArray to netcdf. This appears to require turning into a dataset. However, the conversion to and from datasets appears to be lossy.

d = DataArray(...)
n = d.to_dataset().to_array()

looses attrs and the name of the DataArray gets moved to a "variable" coordinate. 

I can manually add the attrs to the created dataset, but it seems like they should either be transfered by default, or have an option to preserve them. Is there a reason this is not done?

**Comment by fmaussion** [comment]
If you don't use ``to_array()`` but simply acces the variable everything is fine:

```python
import xarray as xr
da = xr.DataArray([1, 2, 3], name='da', attrs={'myattr':3})
da.to_dataset().da
<xarray.DataArray 'da' (dim_0: 3)>
array([1, 2, 3])
Coordinates:
  * dim_0    (dim_0) int64 0 1 2
Attributes:
    myattr: 3
```

**Comment by tdimiduk** [comment]
Ah thanks. Would you be be interested in a pull request to make that more clear in the docs?

**Comment by shoyer** [comment]
Sure, improvements to the docs are always welcome!

Note that in the next release of xarray we will have a `DataArray.to_netcdf` method (and `open_dataarray`).

**Comment by tdimiduk** [comment]
Oh, that will be excellent. When is that coming out?

**Comment by shoyer** [comment]
I'm trying to get a couple of big PRs (#1017 and #1028) into the next major release. So probably 2-4 weeks.
