### ISSUE TITLE
xarray.Dataset.var - xarray.DataArray.var - does it have ddof=1 parameter?

### ISSUE THREAD

**Issue by chiaral** [pydata/xarray#1050]
It is not clear from the description whether ddof = 1 is available and/or if it is set to 0.
(https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.var.html)

for large samples, 1 or 0 don't make a lot of difference, but it would be good to know whether it uses N-1 or N.

**Comment by shoyer** [comment]
Good question. Setting `ddof` should work. It's passed on to `nanvar` from NumPy or bottleneck, both of which default to `ddof=0`.

**Comment by sjvrijn** [comment]
In [`core/nanops.py`](https://github.com/pydata/xarray/blob/master/xarray/core/nanops.py) there are some explicit defaults of `ddof=0` within xarray, but I'm not sure if those are always used or if there are also cases where `var` (or `std`) are directly passed on to numpy/bottleneck/dask.

I'm considering two different options to clarify this:

1. Add a docstring section on the `ddof` parameter specifying it uses `ddof=0` as default for the reduction methods that use it, i.e. `var` and `std`. Possibly just copied from numpy's [`var`](https://numpy.org/doc/stable/reference/generated/numpy.var.html) page.
2. Refer to numpy's documentation page in the docstring of all reduction methods for further reference.

Both would require some logic in [`core/ops.py`](https://github.com/pydata/xarray/blob/master/xarray/core/ops.py): either to check for which reduce methods need a `ddof` paragraph, or to create the proper url (which has to adjust `min` and `max` to `np.amin` and `np.amax` respectively)

Is there any clear preference from anyone about this?

**Comment by max-sixty** [comment]
Thanks for finding that @sjvrijn 

I don't have a view on what we should use, so I would vote to defer to numpy (and pandas, [which also seems to use 1](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.std.html)), referencing that documentation to the extent xarray isn't changing anything.

But others probably have a stronger view on which `ddof` we should use?
