### ISSUE TITLE
to_netcdf Documentation

### ISSUE THREAD

**Issue by chiaral** [pydata/xarray#1051]
I found this SO thread reply very helpful when I had to create some netcdf files with many attributes.

http://stackoverflow.com/questions/22933855/convert-csv-to-netcdf/28914767#28914767

I thought to bring it to your attention. 

The documentation on http://xarray.pydata.org/en/stable/io.html#netcdf
could use a more detailed example and this is very clear.

**Comment by shoyer** [comment]
If you have concrete suggestions for improving the IO docs page (even if only to add a link to that StackOverflow post), a PR would be greatly appreciated!

You can find the source code for that doc page here:
https://github.com/pydata/xarray/blob/master/doc/io.rst

**Comment by chiaral** [comment]
I will be happy to add these info to the documentation.
