### ISSUE TITLE
API: are indexes public API?

### ISSUE THREAD

**Issue by chris-b1** [pydata/xarray#1054]
Usecase -  I have a `DataArray` that will be passed into a numba function and need to pass in some slices.  Very simplified example:

```python
from numba import njit
@njit
def f(arr, slc1, slc2):
    return arr[slc1].max() - arr[slc2].min()

da = xr.DataArray([1., 2., 3.], coords={'key': ['a', 'b', 'c']})
```

Right now I'm accessing the underlying indexes to get slices, like so:

```python
f(da.values, 
  da.indexes['key'].slice_indexer('a', 'b'), 
  da.indexes['key'].slice_indexer('c', 'c'))

Out[52]: -1.0
```
First question, am I missing some obviously better way to do this?  Of course in this example I could just pass in sliced values, but in my actual usecase the data has higher dimensions and I use the slice multiple times across multiple arrays.

More broadly, should the underlying indexes be thought of as an implementation detail (e.g. could be swapped out with something else) or is it more-or-less an API guarantee that I'll get a `pandas` Index here?

**Comment by shoyer** [comment]
Yes, `DataArray.indexes` is public API, as is the `DataArray.to_index()` method. If it's not listed in the API docs, that should be fixed. (It does look like it's missing.)

It is *possible* that at some point in the future we may allow alternative indexes, e.g., stored on disk or over a network. But I have no such plans and in any case this would certainly require explicitly opting in.
