### ISSUE TITLE
kwarg defaults (join="inner") for DataArray._binary_ops()

### ISSUE THREAD

**Issue by chunweiyuan** [pydata/xarray#1059]
Currently the default is join="inner".  However, there can be applications where the majority of binary operations require join="outer", not "inner".

Would it be advisable to place these default values in some config object the user can set at the beginning of the run script?  Or perhaps one already exists but I've failed to locate it.

**Comment by shoyer** [comment]
Yes, we could make this a configurable option (currently it is not). See `xarray.set_options` for some related machinery.

**Comment by chunweiyuan** [comment]
Thanks.  I will soon submit a pull request from my fork.  Which branch should it go to?  It seems that many people submit pull requests to master here.

**Comment by shoyer** [comment]
We submit PRs to master. Please also be sure to update Dataset binary ops,
too.

**Comment by chunweiyuan** [comment]
Yup, did that.  Thank you.  Will request to have you as a reviewer.  Much obliged.
