### ISSUE TITLE
Indexing turns 1D coordinates into scalar coordinates

### ISSUE THREAD

**Issue by chunweiyuan** [pydata/xarray#1067]
Starting with

`arr = xr.DataArray(np.arange(0, 7.5, 0.5).reshape(3, 5),dims=('x', 'y'))`

This will drop the index on x:

`arr[0, :]`

but this won't:

`arr[slice(0,1), :]`

While the laymen would expect them both to return the same thing.  Is there a reason to this design choice, or could I file a PR for it?

**Comment by shoyer** [comment]
This is intentional -- it matches the behavior of numpy.
