### ISSUE TITLE
xarray-cartopy broken?

### ISSUE THREAD

**Issue by suvarchal** [pydata/xarray#1071]
running the cartopy example in the docs leads to bunch of errors that are hard to decode, I tried in my two different conda environments issue seems to be the same.

Example:

```
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

air = (xr.tutorial
       .load_dataset('air_temperature')
       .air
       .isel(time=0))
ax = plt.axes(projection=ccrs.Orthographic(-80, 35))
ax.set_global()
air.plot.contourf(ax=ax, transform=ccrs.PlateCarree())
ax.coastlines()
plt.savefig('cartopy_example.png')
```

 
Error in callback <function post_execute at 0x7f984d50a050> (for post_execute):
TypeError                                 Traceback (most recent call last)
miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.pyc in post_execute()
    145             def post_execute():
    146                 if matplotlib.is_interactive():
--> 147                     draw_all()
    148 
..........
miniconda2/lib/python2.7/weakref.pyc in setdefault(self, key, default)
    446 
    447     def setdefault(self, key, default=None):
--> 448         return self.data.setdefault(ref(key, self._remove),default)
    449 
    450     def update(self, dict=None, **kwargs):

TypeError: unhashable type: 'MultiLineString'

**Comment by ocefpaf** [comment]
That is unrelated to `xarray`. It is a `cartopy`/`shapely` bug due to version mismatch. If you update both that should work.

**Comment by suvarchal** [comment]
ooh yaa that fixed it, which version couples to who was not obvious, in the end what worked was installing cartopy from conda-forge repository.
Thanks

**Comment by ocefpaf** [comment]
> which version couples to who was not obvious

Sorry, this is an old issue that I had in the back of my head but I do not remember the versions :grimacing: but a general update should get you going.

>  in the end what worked was installing cartopy from conda-forge repository.

:+1:
