### ISSUE TITLE
Fascinating bug in contourf

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1078]
Can someone reproduce this or is it just me?

```python
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
import cartopy.crs as ccrs

nlats, nlons = (241, 480)
lats = np.linspace(90, -90, nlats, dtype=np.float32)
lons = np.linspace(-180, 180-0.75, nlons, dtype=np.float32)
l1, l2 = np.meshgrid(lons, lats)
data = xr.DataArray(l1 + l2, [('latitude',  lats), ('longitude', lons)])

f = plt.figure()

ax1 = plt.subplot(2, 1, 1, projection=ccrs.Robinson())
data.plot.contourf(ax=ax1, transform=ccrs.PlateCarree());
ax1.coastlines(color='grey'); ax1.gridlines();

data += 180  # this is the line causing the problem

ax2 = plt.subplot(2, 1, 2, projection=ccrs.Robinson())
data.plot.contourf(ax=ax2, transform=ccrs.PlateCarree());
ax2.coastlines(color='grey'); ax2.gridlines();

plt.show()
```
Gives:
![figure_1](https://cloud.githubusercontent.com/assets/10050469/19986783/5780a530-a218-11e6-8b6f-6c1267b23472.png)

**Comment by dopplershift** [comment]
I'm willing to be this is related: SciTools/cartopy#811

What do you get for `ax2.get_extent()`?

**Comment by fmaussion** [comment]
Thanks @dopplershift ! I get: ``(-0.05, 0.05, -0.05, 0.05)``

Indeed, this is very similar: closing this as this has nothing to do with xarray. This is annoying though, as I don't see how I can explain this to my class next Tuesday ;-)

**Comment by dopplershift** [comment]
Set the extent manually with `ax.set_extent([lon0, lon1, lat0, lat1], crs=ccrs.PlateCarree())` or just `ax.set_global()`. It's essentially just a glitch with auto-zoom.
