### ISSUE TITLE
Issue a warning when overwriting attributes with accessors instead of erroring

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1082]
On the mailing list, @rabernat wrote:

> Also, how can I interactively develop an accessor? If I try to
re-register under the same name, I get the error
AccessorRegistrationError: cannot register accessor <class
'__main__.ExchAccessor'> under name 'exch' for type <class
'xarray.core.dataset.Dataset'> because an attribute with that name
already exists.

In #1080, @smartass101 suggests:

> Btw, perhaps it might be better to (perhaps optionally) issue a warning when overriding an existing class attribute during registering instead of completely refusing to do so.

I think this is a good idea, and would nicely solve @rabernat's problem (which might be your problem, too). We could add a new keyword argument (e.g., `allow_override=True` or `warn=True` to `register_*_accessor`) which switches to this new mode.

Should it be the default behavior? It is also possible that warnings instead of errors are enough in general.

**Comment by smartass101** [comment]
I vote for warning by default. Raising an error brings more inconvenience than it's worth.
Remember to warneach time, not just on first code run.

On November 6, 2016 2:11:54 PM GMT+01:00, Stephan Hoyer <notifications@github.com> wrote:
>On the mailing list, @rabernat wrote:
>
>> Also, how can I interactively develop an accessor? If I try to
>re-register under the same name, I get the error
>AccessorRegistrationError: cannot register accessor <class
>'__main__.ExchAccessor'> under name 'exch' for type <class
>'xarray.core.dataset.Dataset'> because an attribute with that name
>already exists.
>
>In #1080, @smartass101 suggests:
>
>> Btw, perhaps it might be better to (perhaps optionally) issue a
>warning when overriding an existing class attribute during registering
>instead of completely refusing to do so.
>
>I think this is a good idea, and would nicely solve @rabernat's problem
>(which might be your problem, too). We could add a new keyword argument
>(e.g., `allow_override=True` or `warn=True` to `register_*_accessor`)
>which switches to this new mode.
>
>Should it be the default behavior? It is also possible that warnings
>instead of errors are enough in general.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pydata/xarray/issues/1082

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
