### ISSUE TITLE
Always use absolute paths

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#1085]
This would avoid a mismatch between clients and workers when using dask.distributed

```python
In [2]: os.path.abspath('my-local-path')
Out[2]: '/home/mrocklin/my-local-path'
```

**Comment by shoyer** [comment]
This is for imports, or files opened with open_dataset?

**Comment by mrocklin** [comment]
Open_dataset, but you're right, we should probably resolve this on the serialization code on the Dask side regardless.

**Comment by shoyer** [comment]
Fixed by https://github.com/pydata/xarray/pull/1128
