### ISSUE TITLE
Reindex twice efficiently

### ISSUE THREAD

**Issue by gdbaldw** [pydata/xarray#1091]
The goal is to re-index using a 10 year series of daily dates. A brute force Python loop method is outlined below. Is there a better way?

Let the DataArray have 3 Coordinates:
  location: (4000 locations)
  sample: (10 samples) 0,1,2,3,4,5,6,7,8,9
  attributes: (2 attributes) date, temp

Each location has a different set of 'date' values. Using brute force, one could Python loop through the 4000 locations:
  1) reindex each location to its 'date' attribute, then drop 'date'
  2) reindex this new DataArray using the 10 year series, with padding
  3) append this new array to a {location: DataArray} dictionary.

Then, construct a DataSet from the dictionary, and then a DataArray from the DataSet.

Thank you,
Doug

**Comment by shoyer** [comment]
I don't quite understand. Can you clarify the result you are looking for? An example might help.

**Comment by gdbaldw** [comment]
In [0]: time_index = pd.date_range('2016-01-01', periods=9)

In [1]: times = pd.DataFrame(time_index.values.reshape((3,3)))

In [2]: temps = pd.DataFrame(np.random.rand(9).reshape((3,3)))

In [3]: da = xr.DataArray(pd.Panel({'temp': temps, 'time': times}), dims=['attribute', 'location', 'period'], coords={'attribute': ['temp', 'time'], 'location': ['A', 'B', 'C'], 'period': [0,1,2]})

In [4]: da
Out[4]: 
```
<xarray.DataArray (attribute: 2, location: 3, period: 3)>
array([[[0.41722482311431086, 0.07097390567736572, 0.4962422826507019],
        [0.20179200059206603, 0.5117838751300646, 0.8247891470231844],
        [0.5320816512771056, 0.46738142114882975, 0.1949627102506386]],

       [[Timestamp('2016-01-01 00:00:00'),
         Timestamp('2016-01-02 00:00:00'), Timestamp('2016-01-03 00:00:00')],
        [Timestamp('2016-01-04 00:00:00'),
         Timestamp('2016-01-05 00:00:00'), Timestamp('2016-01-06 00:00:00')],
        [Timestamp('2016-01-07 00:00:00'),
         Timestamp('2016-01-08 00:00:00'), Timestamp('2016-01-09 00:00:00')]]], dtype=object)
Coordinates:
  * attribute  (attribute) |S4 'temp' 'time'
  * location   (location) |S1 'A' 'B' 'C'
  * period     (period) int64 0 1 2
```

> The brute force solution is to execute the following command for each (of potentially 1000s) of locations, and then reassemble into one DataArray containing all of the locations. (Note that the above  dict ordering for the Panels is random. To recreate, 'time' and 'temp' attributes may need to be reversed.)

In [5]: da.sel(location='A').assign_coords(time = da.sel(location='A', attribute='time').to_series()).swap_dims({'period': 'time'}).drop('period').drop('time', dim='attribute').reindex(time=time_index, method='pad')
Out[5]: 
```
<xarray.DataArray (attribute: 1, time: 9)>
array([[0.41722482311431086, 0.07097390567736572, 0.4962422826507019,
        0.4962422826507019, 0.4962422826507019, 0.4962422826507019,
        0.4962422826507019, 0.4962422826507019, 0.4962422826507019]], dtype=object)
Coordinates:
  * attribute  (attribute) |S4 'temp'
    location   |S1 'A'
  * time       (time) datetime64[ns] 2016-01-01 2016-01-02 2016-01-03 ...
```

In [6]: da.sel(location='B').assign_coords(time = da.sel(location='B', attribute='time').to_series()).swap_dims({'period': 'time'}).drop('period').drop('time', dim='attribute').reindex(time=time_index, method='pad')
Out[6]: 
```
<xarray.DataArray (attribute: 1, time: 9)>
array([[nan, nan, nan, 0.20179200059206603, 0.5117838751300646,
        0.8247891470231844, 0.8247891470231844, 0.8247891470231844,
        0.8247891470231844]], dtype=object)
Coordinates:
  * attribute  (attribute) |S4 'temp'
    location   |S1 'B'
  * time       (time) datetime64[ns] 2016-01-01 2016-01-02 2016-01-03 ...
```

In [7]: da.sel(location='C').assign_coords(time = da.sel(location='C', attribute='time').to_series()).swap_dims({'period': 'time'}).drop('period').drop('time', dim='attribute').reindex(time=time_index, method='pad')
Out[122]: 
```
<xarray.DataArray (attribute: 1, time: 9)>
array([[nan, nan, nan, nan, nan, nan, 0.5320816512771056,
        0.46738142114882975, 0.1949627102506386]], dtype=object)
Coordinates:
  * attribute  (attribute) |S4 'temp'
    location   |S1 'C'
  * time       (time) datetime64[ns] 2016-01-01 2016-01-02 2016-01-03 ...

```

**Comment by shoyer** [comment]
OK, this makes more more sense now.

My first suggestion is to put your two attributes `temp` and `time` in different variables in an `xarray.Dataset`. That way, they can each have a homogeneous dtype (not `dtype=object`) which is pretty essential to getting reasonable performance with xarray/numpy.

More generally, I'm not sure this data is well suited for xarray, because your time labels can't be easily expressed in 1D. It might make more sense to flatten the data into a tabular structure, e.g., a pandas.DataFrame with columns `['temp', 'time', 'period', 'location']` and do a multi-dimensional pandas groupby, something like `df.groupby(['location', pandas.Grouper(key='time', freq='1MS')]).temp.first()` to pull out the first value of temp in each location/month.

**Comment by gdbaldw** [comment]
OK. Thank you for xarray, and for offering helpful suggestions.
