### ISSUE TITLE
Fix "allowed failures" Travis-CI builds for pydap and dev versions of netCDF4 and pandas

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1109]
These are useful for catching changes upstream before they turn into bugs for xarray users, but they are currently failing for spurious reasons.

If someone has time to investigate and fix these, that would be great!

**Comment by jhamman** [comment]
I've just opened #2736 to close this issue. In actuality, this issue could be closed as is because:

1) The pydap and netcdf4 builds were removed in #2661 
2) The pandas dev build is passing in recent travis builds
