### ISSUE TITLE
Unable to decode time axis on rasm file

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1111]
```python
import xarray as xr
import netCDF4

print(xr.__version__)  # 0.8.2-50-g57facab
print(netCDF4.__version__) # 1.2.4

ds = xr.tutorial.load_dataset('rasm')
/home/mowglie/Documents/git/xarray/xarray/conventions.py:389: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  result = decode_cf_datetime(example_value, units, calendar)
```

I'll have a closer look.

**Comment by fmaussion** [comment]
This is due to the [0] here: https://github.com/pydata/xarray/blob/master/xarray/conventions.py#L386

Since the units of time are ``days since 0001-01-01`` this raises an error. Any reason why this 0 is here?

**Comment by shoyer** [comment]
Added in https://github.com/pydata/xarray/pull/984

Looks like the original intent was to check 0 only if other dates were *not* found. So this should probably be fixed.
