### ISSUE TITLE
`DataArray.rename` of a coordinate array fails to rename the coordinate name of it's own coordinate

### ISSUE THREAD

**Issue by burnpanck** [pydata/xarray#1116]
The documentation of `DataArray.rename` states that it renames the name of the DataArray and/or associated coordinates. However, if a name happens to be simultaneously the name of the array and of a coordinate, it only renames the array. This situation particularly arises when one tries to create a renamed coordinate to use on a different (new) array/dataset, as in that case the name of the only dimension of the coordinate array is the name of the array itself.

**Comment by shoyer** [comment]
Yes, this seems like a bug, thanks for pointing it out!
