### ISSUE TITLE
Creating a `Dataset` with a coordinate given by a `DataArray` may create an invalid dataset

### ISSUE THREAD

**Issue by burnpanck** [pydata/xarray#1120]
Consider this:
```
import xarray as xr
import numpy as np
ds = xr.Dataset(
    data_vars=dict(
        v = ('y',np.r_[0:10]),
    ),
    coords=dict(
        y=xr.DataArray(np.r_[:10]/10,dims='x'),
    ),
)
```
The dataset `ds` will end up having dimensions `('x', 'y')` because of the coordinate `y` having dimensions `('x',)`.
This seems to violate some of the internal assumptions (`ds.indexes['y'].name` turns out to be `'x'`),
consequently `ds.sel(y=0)` will throw an exception (`ValueError: cannot use a dict-like object for selection on a dimension that does not have a MultiIndex`).

I came across this situation when trying to generate a dataset with a coordinate that is a copy of another pre-existing coordinate, but under a different name. My expectation was that the coordinate would be renamed (doing so manually also doesn't work out of the box due to #1116). Of course that is not the only possible interpretation of the construct above, arguably it should raise an exception instead (which is what `DataArray` currently does in the corresponding case).

**Comment by shoyer** [comment]
I think this should raise an error, so I'm marking this as a bug. It's perfectly valid to construct a coordinate with arbitrary dimensions in xarray, but it should not be possible to use such variables as dimension names.

**Comment by jhamman** [comment]
@shoyer - do you think this fix belongs in `merge_core` or `merge_data_and_coords`?

**Comment by shoyer** [comment]
@jhamman Probably in `merge_core`, which is used inside `Dataset.__setitem__` as well as `Dataset.__init__`.
