### ISSUE TITLE
unstack raises error when there is only one dimension stacked

### ISSUE THREAD

**Issue by floogit** [pydata/xarray#1126]
I am aware that `stack()`/`unstack()` is meant to be used for combining/splitting
multiple dimensions. Still, I wonder if it should throw an error when used
on a dataset with only one dimension:

```
ds = xr.Dataset()
ds['var'] = xr.DataArray(np.array([3., 4.]), dims=('dim1'))
ds_s = ds.stack(z=['dim1'])
ds_s.unstack('z')
ValueError: cannot unstack a dimension that does not have a MultiIndex
```

I stumbled upon this when implementing a stack-groupby-apply-unstack pattern on a dataset
which normally has more than one dimension to stack, but sometimes might contain only one.
I can circumvent this quite easily by checking if there is only one dimension to stack and not
using stack/unstack then, but I somehow expected it to work without treating this case in a special
way.

**Comment by shoyer** [comment]
I agree, this is annoying. Unfortunately, pandas does not have support a MultiIndex with one level, so it's not obvious how we would represent such objects in xarray's data model. If we simply treated `ds.stack(z=['dim1'])` as a rename operation, then we wouldn't know how to do `unstack('z')`.

One option would be to use a normal `pandas.Index` where `Index.name` differs from the name of the dimension on the `xarray.Variable`, though it might be cleaner/more-obvious using our own wrapper class of some sort. I think this would be relatively sane, but it would require adjustments throughout the codebase in every place where we use a `MultiIndex`.

**Comment by fujiisoup** [comment]
It is already fixed.
