### ISSUE TITLE
pipe, apply should call maybe_wrap_array, possibly resolve dim->axis

### ISSUE THREAD

**Issue by smartass101** [pydata/xarray#1130]
While `pipe` and `Dataset.apply`  (btw, why not call them both the same?) specify that they expected `DataArray` returning functions, it would be very convenient to have them call `maybe_wrap_array` anyways. 

I've often tried piping functions which at first looked like ufuncs only to find out that they forgot to call `__array_wrap__` (I'm looking at you `np.angle`). The extra call to `maybe_wrap_array` is cheap, does not break anything and would be very useful. It would greatly enlarge the set of functions that can be readily applied to `DataArray` objects without any need for writing function wrappers (motivated  in part by #1080).

Since many such functions expect an `axis` argument, some syntax  for `dim -> axis` resolution could be also added. I see some options

1) check if axis argument is a string and coerce it to a number, something like
```python
axis = kwargs.get('axis')
if axis is not None:
    if isinnstance(axis, str):
        kwargs['axis'] = darray.get_axis_num(axis)
```

Simple, but specifying `axis='smth'` is not very explicit and may mean something else for certain funcs, it assumes a lot about function signatures.

2) similar to 1., but only if both `dim` and `axis='dim'` are specified. Still possible conflict of specific meaning, but less likely.

```python
if kwargs.get('axis') == 'dim':
    kwargs['axis'] = darray.get_axis_num(kwargs['dim'])
```

Other coding might be possible.

3) use some syntax similar to `pipe((f, 'arg2', ('axis', dim)), *args, **kwargs)`, but that's getting complicated and less readable.

Let me know what you think and perhaps you'll come up with some nicer syntax for dim-> axis resolution.

**Comment by shoyer** [comment]
On `Dataset`, `.pipe` and `.apply` work differently -- `pipe` passes the entire Dataset whereas `apply` passes each of the variables in turn.

I'm OK with calling `maybe_wrap_array` in `DataArray.apply`, but I'd rather not adjust `DataArray.pipe`, which is intentionally very simple.

**Comment by shoyer** [comment]
As for `dim`/`axis`, my inclination would be to unilaterally remap any `dim` keyword argument to `.apply` to `axis` using the `get_axis_num`. Something like:
```
dim = kwargs.pop('dim', None)
if dim is not None:
    if 'axis' in kwargs:
        raise ValueError('cannot set both `dim` and `axis`')
    kwargs['axis'] = self.get_axis_num(dim)
```

In the unlikely event your function takes a `dim` argument that should not be remapped, you can pass in a lambda or `functools.partial` instead.

**Comment by smartass101** [comment]
> ... rather not adjust DataArray.pipe, which is intentionally very simple.

It would be just one extra call to a funciton which is very simple. As I [commented](https://github.com/pydata/xarray/issues/1074#issuecomment-261495282) in #1074, I think it makes more sense to have `pipe` wrap arrays, because otherwise the pipe-chain might get broken, whereas with `apply` I'd be ok with it behaving as the python apply function which simply applies a function and nothing more. But `maybe_wrap_array` is simple and does not break anything, it wraps it only when it's safe.

> In the unlikely event your function takes a dim argument

I think that could be quite likely as one might want to apply a DataArray-compatible function. This would force users to remember which type of "function applier" to use for a given function and might be confusing.

**Comment by shoyer** [comment]
> But maybe_wrap_array is simple and does not break anything, it wraps it only when it's safe.

It's safe in the sense that the `xarray.DataArray` contains the information from the numpy array, but it's not safe in terms of a stable type signature.

> I think that could be quite likely as one might want to apply a DataArray-compatible function. This would force users to remember which type of "function applier" to use for a given function and might be confusing.

I think this is unavoidable. It's impossible to design a single entry point that works smoothly for both use cases.

**Comment by shoyer** [comment]
Closing this in favor of https://github.com/pydata/xarray/issues/1130
