### ISSUE TITLE
.rolling(...).count() ?

### ISSUE THREAD

**Issue by MaximilianR** [pydata/xarray#1138]
Should `.count()` be available on `.rolling` objects?

```python
>       sample_count = array.rolling(**windows).count() - 1.0
E       AttributeError: 'DataArrayRolling' object has no attribute 'count'
```

**Comment by shoyer** [comment]
Yes, I don't see why not?

**Comment by MaximilianR** [comment]
OK will try and do a PR this week. Got a few others to get in first but this should be short

**Comment by MaximilianR** [comment]
@shoyer should this do `.notnull().rolling().sum()`, or is there a specific rolling count function out there that would be better?

**Comment by shoyer** [comment]
That looks like about the best we could do.

**Comment by jhamman** [comment]
@MaximilianR - that is the best we can do.`bottleneck` doesn't have a `move_count` function so we will need to operate on the rolling object ourselves.
