### ISSUE TITLE
sel with method 'nearest' fails with AssertionError

### ISSUE THREAD

**Issue by j08lue** [pydata/xarray#1140]
The following fails

```python
def test_sel_nearest():
    """Test `sel` with method='nearest'"""
    # create test data
    times = pd.date_range('2000-01-01', periods=4)
    foo = xr.DataArray([1,2,3,4], coords=dict(time=times), dims='time')
    
    # works
    expected = foo.sel(time='2000-01-01')
    
    # fails
    assert foo.sel(time='2000-01-01', method='nearest') == expected
```

with an `AssertionError` in [`xarray/core/variable.py`](https://github.com/pydata/xarray/blob/v0.8.2/xarray/core/variable.py#L379):

```
C:\Users\uuu\AppData\Local\Continuum\Miniconda2\lib\site-packages\xarray\core\dataarray.pyc in sel(self, method, tolerance, **indexers)
    623             self, indexers, method=method, tolerance=tolerance
    624         )
--> 625         return self.isel(**pos_indexers)._replace_indexes(new_indexes)
    626 
    627     def isel_points(self, dim='points', **indexers):

C:\Users\uuu\AppData\Local\Continuum\Miniconda2\lib\site-packages\xarray\core\dataarray.pyc in isel(self, **indexers)
    608         DataArray.sel
    609         """
--> 610         ds = self._to_temp_dataset().isel(**indexers)
    611         return self._from_temp_dataset(ds)
    612 

C:\Users\uuu\AppData\Local\Continuum\Miniconda2\lib\site-packages\xarray\core\dataset.pyc in isel(self, **indexers)
    910         for name, var in iteritems(self._variables):
    911             var_indexers = dict((k, v) for k, v in indexers if k in var.dims)
--> 912             variables[name] = var.isel(**var_indexers)
    913         return self._replace_vars_and_dims(variables)
    914 

C:\Users\uuu\AppData\Local\Continuum\Miniconda2\lib\site-packages\xarray\core\variable.pyc in isel(self, **indexers)
    539             if dim in indexers:
    540                 key[i] = indexers[dim]
--> 541         return self[tuple(key)]
    542 
    543     def _shift_one_dim(self, dim, count):

C:\Users\uuu\AppData\Local\Continuum\Miniconda2\lib\site-packages\xarray\core\variable.pyc in __getitem__(self, key)
    377         # orthogonal indexing should ensure the dimensionality is consistent
    378         if hasattr(values, 'ndim'):
--> 379             assert values.ndim == len(dims), (values.ndim, len(dims))
    380         else:
    381             assert len(dims) == 0, len(dims)

AssertionError: (0, 1)
```

It does not matter which type the dimension has that is indexed:

```python
def test_sel_nearest_int():
    """Test `sel` with method='nearest'"""
    bar = xr.DataArray([1, 2, 3, 4], coords=dict(dummy=range(4)), dims='dummy')
    
    # works
    expected = bar.sel(dummy=3)
    
    # fails
    assert bar.sel(dummy=3, method='nearest') == expected
```

This is on Miniconda for Windows 64 bit with conda-forge and IOOS builds and
* xarray=0.8.2
* pandas=0.19.1
* numpy=1.11.2

Why might this be? Am I doing something wrong?

**Comment by shoyer** [comment]
Sorry for the delay getting back to you.

I'm having trouble reproducing this on OS X. I assume you're running Python 2? Maybe this is a Windows thing? I'm a little baffled here.

One thing that would be very helpful is a pull request with a test case that fails our continuous integration tests (which include testing Windows).

**Comment by j08lue** [comment]
Yes, this is Python 2. :flushed: Let's see what Travis & Co say.

**Comment by JamesSample** [comment]
Hi j08lue,

Just wondering if you ever figured this out? I'm having exactly the same issue on 64-bit Windows 10, using WinPython 2.7 and the following:

xarray 0.9.1
Pandas 0.19.1
Numpy 1.11.2

If I've understood the comments [here ](https://github.com/pydata/xarray/pull/1184) correctly, it sounds as though others are struggling to reproduce the problem - even on Windows - so presumably it's something strange with our installations?

**Comment by j08lue** [comment]
@JamesSample Thanks for restoring my credibility a bit here... But, no, I did not figure this out yet.

Appveyor apparently does not have the combination Windows 64 bit + Python 2.7 (https://ci.appveyor.com/project/jhamman/xarray-injyf/build/1.0.659), maybe that is why it does not reproduce the error?

**Comment by JamesSample** [comment]
@j08lue Thanks for your response - that's interesting. I'm not familiar with Appveyor and hadn't realised what builds were being used.

As a test, I've just installed 32-bit WinPython 2.7 and xarray (still on my 64-bit Windows 10 machine) and everything works fine, so this does appear to be a specific issue with xarray and 64-bit Python 2.7.

**Comment by j08lue** [comment]
@JamesSample excellent work confirming the limited scope.

I am quite sure that the issue is with this line: https://github.com/pydata/xarray/blob/v0.9.1/xarray/core/variable.py#L375-L376

```
        dims = tuple(dim for k, dim in zip(key, self.dims)
                     if not isinstance(k, (int, np.integer)))
```

When you run the test case I added in #1184, you will see that, inside `__getitem__`, `key` is a tuple with an empty array inside (`key = (np.array(0, dtype=np.int64),)`). 

With that value,
```
isinstance(key[0], (int, np.integer))
```
is `False` on 64 bit Windows and so `dims=('time',)`, which has length 1.

But `values = self._indexable_data[key]` gives a zero-dimension array, such that `values.ndim == 0`...

I am unable to tell which of the two sides of the `assertion` expression is unexpected...

**Comment by shoyer** [comment]
Sounds like we need to add 64-bit Python 2.7 on Windows to our build matrix!

And also a more robust check for integer types in variable.py.

**Comment by joschkazj** [comment]
I've just run into the same issue with the `AssertionError` on Windows 7 x64 with Python v2.7, netcdf4 1.2.4, numpy 1.11.3, pandas 0.19.2, **xarray 0.8.2 and 0.9.1** (all packages from Anaconda repo).

Downgrading pandas to 0.18.1 solved the problem for me.

**Comment by shoyer** [comment]
Just for reference (I don't develop on Windows), do we need to test both 32 and 64 bit Windows installs? It's not a big deal to add another configuration to the build matrix, but currently we only test Python 2.7 on 32-bit and 3.6 on 64-bit: https://github.com/pydata/xarray/blob/v0.9.1/appveyor.yml
