### ISSUE TITLE
"ncdump -h" like repr?

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1150]
Sometimes it could be useful to have a view of all variables attributes at a glance. For example, this is the repr for ERA-Interim energy fluxes data:

```
(...)
Data variables:
    slhf     (month, latitude, longitude) float64 0.02852 0.02852 0.02852 ...
    tsr      (month, latitude, longitude) float64 -0.0001912 -0.0001912 ...
    strd     (month, latitude, longitude) float64 166.6 166.6 166.6 166.6 ...
    strc     (month, latitude, longitude) float64 -66.23 -66.23 -66.23 ...
    tisr     (month, latitude, longitude) float64 0.0 0.0 0.0 0.0 0.0 0.0 ...
    ssrd     (month, latitude, longitude) float64 -0.0003951 -0.0003951 ...
    ssrc     (month, latitude, longitude) float64 0.0 0.0 0.0 0.0 0.0 0.0 ...
    str      (month, latitude, longitude) float64 -40.65 -40.65 -40.65 ...
    ttr      (month, latitude, longitude) float64 -171.5 -171.5 -171.5 ...
    tsrc     (month, latitude, longitude) float64 0.0 0.0 0.0 0.0 0.0 0.0 ...
    sshf     (month, latitude, longitude) float64 10.46 10.46 10.46 10.46 ...
    ssr      (month, latitude, longitude) float64 0.0 0.0 0.0 0.0 0.0 0.0 ...
    ttrc     (month, latitude, longitude) float64 -174.9 -174.9 -174.9 ...
(...)
```
This is what my students will see when they explore the dataset for the first time. It could be nice to have a utility function (e.g. ``dumph`` or something) which would have a style closer to ``ncdump -h``:

```
(...)
	double ttr(month, latitude, longitude) ;
		ttr:least_significant_digit = 2L ;
		ttr:units = "J m**-2" ;
		ttr:long_name = "Top net thermal radiation" ;
		ttr:standard_name = "toa_outgoing_longwave_flux" ;
	double tsrc(month, latitude, longitude) ;
		tsrc:least_significant_digit = 2L ;
		tsrc:units = "J m**-2" ;
		tsrc:long_name = "Top net solar radiation, clear sky" ;
	double sshf(month, latitude, longitude) ;
		sshf:least_significant_digit = 2L ;
		sshf:units = "J m**-2" ;
		sshf:long_name = "Surface sensible heat flux" ;
		sshf:standard_name = "surface_upward_sensible_heat_flux" ;
	double ssr(month, latitude, longitude) ;
		ssr:least_significant_digit = 2L ;
		ssr:units = "J m**-2" ;
		ssr:long_name = "Surface net solar radiation" ;
		ssr:standard_name = "surface_net_downward_shortwave_flux" ;
	double ttrc(month, latitude, longitude) ;
		ttrc:least_significant_digit = 2L ;
		ttrc:units = "J m**-2" ;
		ttrc:long_name = "Top net thermal radiation, clear sky" ;
(...)
```

Or is there something like this already?

**Comment by shoyer** [comment]
I don't think anything like this currently exists.

I agree that some way to conveniently summarize attributes would be nice to have. See also #244.

**Comment by jhamman** [comment]
I think something like this would be quite useful. This is most applicable to the `Dataset` and I can see a new method for printing this info. What would we call that method?

- Pandas has a `df.head` and I think this is technically information stored in the header of the netcdf file, so `ds.head()` could work but pandas prints out some number of rows as well.
- Maybe just `ds.info()` which is simple enough and self-explanatory, also no confusion with `df.head()` which returns a `DataFrame`. 
- I don't really like the `*dump*` alternatives since they will be pretty close to the `pickle.dump`.

**Comment by shoyer** [comment]
pandas already has a (rarely used) `DataFrame.info()` method, which is a little different:
```
In [3]: df = pd.DataFrame({'x': [1, 2, 3], 'y': ['a', 'b', 'c'], 'z': [-1, -2, -3]})

In [4]: df
Out[4]:
   x  y  z
0  1  a -1
1  2  b -2
2  3  c -3

In [5]: df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
x    3 non-null int64
y    3 non-null object
z    3 non-null int64
dtypes: int64(2), object(1)
memory usage: 152.0+ bytes
```
(most of that information is already in `Dataset.__repr__`)

I might pick a name that including a specific reference to attributes for this, maybe `attr_info()`?

**Comment by fmaussion** [comment]
Another idea would be to simply add the variables attrs to the current ``__repr__`` (i.e no need for a new function).

I'm getting slightly off-topic, but I am also in favor or removing the data values from the repr altogether, as it creates problems and is not really useful (I think). See also:
https://github.com/pydata/xarray/issues/1044
https://github.com/pydata/xarray/issues/820

and other issues mentioning repr : https://github.com/pydata/xarray/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20repr
