### ISSUE TITLE
Scalar coords seep into index coords

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#1152]
Is this by design? I can't put any sense in it
```
>> a = xarray.DataArray([1, 2, 3], dims=['x'], coords={'x': [1, 2, 3], 'y': 10})
>> a.coords['x']
<xarray.DataArray 'x' (x: 3)>
array([1, 2, 3])
Coordinates:
  * x        (x) int64 1 2 3
    y        int64 10
```

**Comment by fmaussion** [comment]
I think it's fine. Coordinates sometimes need to be defined by paired coords too:

```python
import xarray as xr
import numpy as np
lon, lat = np.meshgrid(np.linspace(-20, 20, 5), np.linspace(0, 30, 4))
da = xr.DataArray(np.arange(20).reshape(4, 5), dims=['y', 'x'],
                  coords = {'lat': (('y', 'x'), lat),
                            'lon': (('y', 'x'), lon)})
da.isel(x=2)['lat']
<xarray.DataArray 'lat' (y: 4)>
array([  0.,  10.,  20.,  30.])
Coordinates:
    lon      (y) float64 0.0 0.0 0.0 0.0
    lat      (y) float64 0.0 10.0 20.0 30.0
  * y        (y) int64 0 1 2 3
    x        int64 2
```

**Comment by shoyer** [comment]
So this definitely was intentional, according to the principle that coordinates are shared between everything in a Dataset/DataArray.

I agree that doesn't always make sense -- sometime coordinates really only describe the data variable(s), so keeping them around on coordinates merely because they contain the appropriate dimensions is inappropriate.

**Comment by fmaussion** [comment]
> sometime coordinates really only describe the data variable(s)

Yes. What I meant with my yesterday's late night answer is that keeping the coordinates around could be most useful when using irregular coordinates...

**Comment by MaximilianR** [comment]
Tangentially connected this - should a `DataArray` always have a `.variables` attribute? When would / wouldn't it?

Currently, it may or may not. And its coords may or may not be DataArrays, which makes the tree of objects seemingly complicated (maybe it needs to be?). But it means we're special-casing some of the checks in https://github.com/pydata/xarray/pull/1147

```python
(Pdb++) a
<xarray.DataArray 'xy' (x: 3)>
array([-0.04729734,  0.08287289,  0.13965946])
(Pdb++) a.variables
*** AttributeError: 'DataArray' object has no attribute 'variables'
(Pdb++) a.variable
<xarray.Variable (x: 3)>
array([-0.04729734,  0.08287289,  0.13965946])
```

**Comment by shoyer** [comment]
@MaximilianR Let me help clarify:

- Currently, DataArray does not have a `.variables` attributes.
- The state of a DataArray is stored in the form of variables in  `._variable` (an `xarray.Variable`) and `._coords` (of type `OrderedDict[Any, xarray.Variable]`).
- From a user facing API, you can get access to these variables via `.variable` and `.coords.variables` (I don't know if the later is clearly documented, but if not it should be).

So the "infinite tree of DataArrrays" only applies if you are accessing them directly via `.coords`, and under the covers data is represented in a pretty sane way.

**Comment by MaximilianR** [comment]
Thanks. I was mistaken.

The "infinite tree" was causing some of the tests back at #1147 to do weird things (pytest seems not to handle infinite recursion responsibly). But it makes sense

**Comment by crusaderky** [comment]
Working as intended according to the maintainer. Apologies for not closing this sooner.
