### ISSUE TITLE
netCDF reading is not prominent in the docs

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#1154]
Just opening an issue to highlight what I think is a problem with the docs.

For me, the primary use of xarray is to read and process existing netCDF data files. @shoyer's  popular [blog post](https://www.continuum.io/content/xray-dask-out-core-labeled-arrays-python) illustrates this use case extremely well.

However, when I open the [docs](http://xarray.pydata.org/), I have to dig quite deep before I can see how to read a netCDF file. This could be turning away many potential users. The stuff about netCDF reading is hidden under "Serialization and IO". Many potential users will have no idea what either of these words mean.

IMO the solution to this is to reorganize the docs to make reading netCDF much more prominent and obvious.

**Comment by shoyer** [comment]
The challenge here is that xarray has two big audiences (netCDF users and non-netCDF users), for which the right approach is very different. I tried to avoid being too netCDF specific in the docs to avoid turning off folks who aren't familiar with it. This is not to say that they would appreciate learning more about netCDF, but I know that an overemphasis on domain specific file formats can turn off others quickly.

So we almost need two separate introduction/tutorial pages, one for people who know netCDF and one for people who don't.

**Comment by fmaussion** [comment]
See also: https://github.com/pydata/xarray/issues/768#issuecomment-187226020

**Comment by shoyer** [comment]
@fmaussion yes, that's a really good point -- the intro for users who don't know netCDF should end with a call to arms about how great netCDF is :).

**Comment by rabernat** [comment]
@shoyer I definitely see your point!

**Comment by fmaussion** [comment]
Partly addressed via https://github.com/pydata/xarray/pull/1169

I'll leave the issue opened in case someone wants to add a more comprehensive netCDF doc later on

**Comment by jhamman** [comment]
Closing based on the recent documentation updates (e.g. #2430) and older PRs like #1169.
