### ISSUE TITLE
Problem passing 'norm' when plotting a faceted figure

### ISSUE THREAD

**Issue by jbusecke** [pydata/xarray#1159]
I am not sure if this is a bug or user error by me.

I am basically trying to pass a SymLogNorm to all plots in a faceted plot, but it has no effect.
It works when I just plot a single axis. 
Below I reproduced the effect with an example dataset.

Matplotlib version: 1.5.1
xarray version: 0.8.2

```python
import xarray as xr
import matplotlib as mpl

# Here the passed 'norm=' keyword has the desired effect
da1 = xr.DataArray(np.random.exponential(size=[10,10]))

plt.figure()
da1.plot()

plt.figure()
da1.plot(norm=mpl.colors.SymLogNorm(0.1))


# In the faceted plot this has no effect
da2 = xr.DataArray(np.random.exponential(size=[10,10,4]))

plt.figure()
da.plot(x='dim_0',y='dim_1',col='dim_2',col_wrap=2)

plt.figure()
da.plot(x='dim_0',y='dim_1',col='dim_2',col_wrap=3,norm=mpl.colors.SymLogNorm(0.1))
```

**Comment by fmaussion** [comment]
Yes, I think this is a bug. I have tried a fix in https://github.com/pydata/xarray/pull/1160

**Comment by fmaussion** [comment]
Thanks for the report @jbusecke !

**Comment by jbusecke** [comment]
Thanks for the quick fix @fmauisson ! Much appreciated.
