### ISSUE TITLE
User warning / more transparent _FillValue interface for .to_netcdf()

### ISSUE THREAD

**Issue by laliberte** [pydata/xarray#1163]
Since many tools (for example ``cdo``) do not work well with ``NaN`` values, the default missing value setting for the ``.to_netcdf()`` method is not well-suited to enable optimal data reuse.

One option would be to add a ``fill_value=NaN`` option to ``.to_netcdf()`` and output a warning message whenever ``NaN``s are written to netCDF: ``'The data being written to netCDF includes missing values (NaN) that are often not easily handled by other netCDF softwares. It is strongly encouraged to coerce missing data to a valid yet large floating point value (for example, 1e20 for float) by calling .to_netcdf(..., fill_value=1e20)'.``

**Comment by shoyer** [comment]
I'm a little surprised that CDO cannot handle a NaN `_FillValue` -- are you sure this is actually the case? If so, it might be worth raising the issue with the CDO developers.

But actually, xarray currently does not even set `_FillValue` by default, though you can do this yourself on a per-variable basis [by setting `encoding`](http://xarray.pydata.org/en/stable/io.html#scaling-and-type-conversions). I think it would be reasonable to default to a `_FillValue` of NaN for floating point dtypes if that would help third party tools, given that that is how xarray's data model works (any other default choice would run the risk of over-writing user data).

**Comment by laliberte** [comment]
I'm pretty sure that of over many versions of CDO NaNs are not properly handled. For example, all the ``setmiss*`` commands have a very hard time with NaN's. 

I have been using the ``encoding`` option but I find it not very intuitive and kind of cumbersome when there are many variables.

I think you're right that actually putting ``_FillValue = NaN`` in the variable attribute might be enough to solve most issues with third parties. If it still does not work, then it would be reasonable to raise this issue with each one of the third parties.

**Comment by shoyer** [comment]
Fixed by #1165
