### ISSUE TITLE
Inconsistent behaviour for xarray.DataArray.rename

### ISSUE THREAD

**Issue by magonser** [pydata/xarray#1177]
Hi,

thanks for creating `xarray`, I like it a lot. However I want to ask, why the behaviour of `xarray.DataArray.rename` is so incosistent:

```python
import xarray as xr
x = xr.DataArray([1, 2, 3], dims=('a',), coords={'a': [1, 2, 3]}, name='a')
x.rename({'a': 'b'})
```

renames the name of `x` not the coordinate! Could you explain the behaviour to me? I do not understand it, or consider it as inconsistent. 

Thanks, Markus

**Comment by shoyer** [comment]
On `master`, I see:
```
In [5]: x = xr.DataArray([1, 2, 3], dims=('a',), coords={'a': [1, 2, 3]}, name='a')

In [6]: x
Out[6]:
<xarray.DataArray 'a' (a: 3)>
array([1, 2, 3])
Coordinates:
  * a        (a) int64 1 2 3

In [7]: x.rename({'a': 'b'})
Out[7]:
<xarray.DataArray 'b' (b: 3)>
array([1, 2, 3])
Coordinates:
  * b        (b) int64 1 2 3
```

So it renames both `x` *and* it's coordinate.

I agree that this is inconsistent and surprising. Using a dictionary should never rename the `name` of a `DataArray`. This is an inadvertent legacy of the previous (outdated) design of the DataArray class, which used a `Dataset` for holding its contents.

A fix for this would be very welcome.
