### ISSUE TITLE
Should we deprecate the compat and encoding constructor arguments?

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#1188]
In https://github.com/pydata/xarray/pull/1170#discussion_r94078121, @shoyer writes:

> ...I would consider deprecating the encoding argument to DataArray instead. It would also make sense to get rid of the compat argument to Dataset.
>
> These extra arguments are not part of the fundamental xarray data model and thus are a little distracting, especially to new users.

@pydata/xarray and others, what do we think about deprecating the `compat` argument to the `Dataset`  constructor and the `encoding` arguement to the `DataArray` (and `Dataset` via #1170).

**Comment by fmaussion** [comment]
I don't have an opinion on ``compat`` (seems somehow unrelated to netCDF and https://github.com/pydata/xarray/issues/1170?), but I am +1 on ``encode``. I always use ``encode`` when writing a dataset to disk, not at construction.

**Comment by clarkfitzg** [comment]
I haven't used these arguments in the constructors. But I don't find them distracting either.

**Comment by max-sixty** [comment]
Compat is removed; is there a basis for keeping `encoding`?

**Comment by shoyer** [comment]
We still have `compat` as an argument to `Dataset.__ini__`.

I think we should probably deprecate it. I've never used it, and if you really want that high a level of control you can easily substitute using merge() instead.
