### ISSUE TITLE
way to apply functions to subplots when faceting

### ISSUE THREAD

**Issue by vnoel** [pydata/xarray#1202]
When plotting maps with cartopy, it is common to request plotting additional information over the map, e.g. coastlines using `ax.coastlines()`.

When faceting maps (as in issue #1201), AFAICS there is no way to add coastlines to each of the faceted subplots. I do not know if or how this can be done, but in my view not being able to do it severely limits the interest of faceting when dealing with maps.

**Comment by vnoel** [comment]
I have found in issue #604 a example of how to do this. I have submitted in issue #1203 a change to the docs.

**Comment by fmaussion** [comment]
closed via https://github.com/pydata/xarray/pull/1203
