### ISSUE TITLE
Consider adding the docs to the distributed tarball

### ISSUE THREAD

**Issue by ghisvail** [pydata/xarray#1209]
Linux distributions such as Debian usually source upstream Python code from PyPI. In order to produce the accompanying documentation package, I would need the source of the documentation to be distributed in future uploaded tarballs. To achieve this, please consider adding a `recursive-include docs *` entry to the `MANIFEST.in` file of the project.

Thanks,
Ghis

**Comment by shoyer** [comment]
Does your build process include running the doc build itself (e.g., using sphinx) or would you also like the generated HTML files/images?

My main concern with bundling in docs is that the source tarball on pypi would increase from ~300KB to ~9MB. But most folks installing directly from PyPI are probably using the wheel anyways, so maybe this is not such a serious concern after all.

**Comment by ghisvail** [comment]
The build process does run Sphinx so only the source suffices. You don't need to ship a build of the documentation.

Indeed wheels should be the preferred mean of installation.
