### ISSUE TITLE
__repr__ of 2D coordinates

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1211]
This is a minor issue (sorry to be so picky about the repr ;) )

Small 2D coordinates are represented in a weird way:

```python
In [1]: import xarray as xr

In [2]: a = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])

In [3]: da = xr.DataArray(a, dims=['y', 'x'],  coords={'xy':(['y', 'x'], a)})

In [4]: da
Out[4]: 
<xarray.DataArray (y: 2, x: 3)>
array([[ 1.1,  2.2,  3.3],
       [ 4.4,  5.5,  6.6]])
Coordinates:
    xy       (y, x) float64 1.1 2.2 3.3 4.4 5.5 6.6
  o y        (y) -
  o x        (x) -
```

This line here:

```
Coordinates:
    xy       (y, x) float64 1.1 2.2 3.3 4.4 5.5 6.6
```
Is a bit confusing as it flattens the coordinates. It's not a big deal though, just something to keep in mind maybe.

**Comment by shoyer** [comment]
I'm definitely open to alternatives, but the flattened repr does have the virtue of being one of the simplest and most readable options for displaying N-d arrays on a single line.

**Comment by fmaussion** [comment]
> the flattened repr does have the virtue of being one of the simplest and most readable options for displaying N-d arrays on a single line.

Agreed, I was being picky. Closing this.
