### ISSUE TITLE
Why ufuncs module not included in top-level namespace

### ISSUE THREAD

**Issue by spencerahill** [pydata/xarray#1216]
I.e. there is no `from . import ufuncs` in `__init__.py`.  Is this deliberate?

If it was included, one could access them after `import xarray as xr` via e.g. `xr.ufuncs.sin` rather than having to do separately e.g. `from xarray.ufuncs import sin`.

Sorry if I'm missing something obvious here.

**Comment by shoyer** [comment]
There's no particular reason for this, it's just not a use case that I thought of. Feel free to put together a PR!

**Comment by spencerahill** [comment]
Great, see #1219.
