### ISSUE TITLE
Testing functions should be moved to a separate `xarray.testing` module

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1218]
These functions are in the `test` module, which isn't imported by default because it requires `pytest`, which we only require for testing. Hence the API docs are currently broken:
http://xarray.pydata.org/en/latest/api.html#testing

If we move these to a separate `testing` module (i.e., a `testing.py` file), we can make `xarray.testing.assert_xarray_equal` just work after `import xarray` (maybe rename it to just `xarray.testing.assert_equal` to avoid the redundant `xarray`).

To avoid confusion, we might rename the `test` directory to `tests`.

cc @MaximilianR @fmaussion in case either of you want to take a look at this -- it should probably be a blocker for 0.9.0.

**Comment by fmaussion** [comment]
yes, correct. The easiest fix would be to install pytest on RTD (assuming that all users using the xarray testing functions  also have pytest installed) but this is not ideal.

 @MaximilianR let me know if you have time to do this, otherwise I'll have a look later this week

**Comment by MaximilianR** [comment]
+1 on `tests` over `test`.

However much I love pytest, minimizing dependencies is a good goal.

I think we could put the testing functions in `testing.py` but the `skipif` functions in `xr.tests.__init__.py`, and then not require pytest?

**Comment by MaximilianR** [comment]
@fmaussion I'm unfortunately v busy for a while, if you could take this one that would be awesome...

**Comment by shoyer** [comment]
> I think we could put the testing functions in testing.py but the skipif functions in xr.tests.__init__.py, and then not require pytest?

Yes, agreed!
