### ISSUE TITLE
`set_index` converts string-dtype to object-dtype

### ISSUE THREAD

**Issue by gerritholl** [pydata/xarray#1238]
'Dataset.set_index' apparently changes a `<U1` dtype into an `object`-dtype, as illustrated below: 

```
In [108]: ds = xarray.Dataset({"x": (("a", "b"), arange(25).reshape(5,5)+100), "y": ("b", arange(5)-100)}, {"a": arange(5), "b": arange(5)*2, "c": (("a",), list("ABCDE"))})

In [109]: print(ds)
<xarray.Dataset>
Dimensions:  (a: 5, b: 5)
Coordinates:
  * b        (b) int64 0 2 4 6 8
    c        (a) <U1 'A' 'B' 'C' 'D' 'E'
  * a        (a) int64 0 1 2 3 4
Data variables:
    x        (a, b) int64 100 101 102 103 104 105 106 107 108 109 110 111 ...
    y        (b) int64 -100 -99 -98 -97 -96

In [110]: print(ds.set_index(a='c'))
<xarray.Dataset>
Dimensions:  (a: 5, b: 5)
Coordinates:
  * b        (b) int64 0 2 4 6 8
  * a        (a) object 'A' 'B' 'C' 'D' 'E'
Data variables:
    x        (a, b) int64 100 101 102 103 104 105 106 107 108 109 110 111 ...
    y        (b) int64 -100 -99 -98 -97 -96
```

**Comment by shoyer** [comment]
`PandasIndexAdapter` contains some logic for preserving dtypes but it looks like didn't hook that up to `set_index` machinery.

**Comment by gerritholl** [comment]
Is this a bug in `pandas`?  I'm probably a rare breed in being an xarray user who has not used pandas.

**Comment by shoyer** [comment]
No, [pandas uses `dtype=object` to represent strings](http://stackoverflow.com/questions/21018654/strings-in-a-dataframe-but-dtype-is-object). We paper over this in some cases in xarray because it's convenient to get objects with the original dtype back from `array.data`.

**Comment by max-sixty** [comment]
Thanks @gerritholl 

More broadly: is this reasonable to fix, given how much we rely on pandas' indexing, given that pandas converts string arrays to object dtype?

**Comment by shoyer** [comment]
I think this will eventually get fixed "for free" as part of the explicit indexes refactor.

**Comment by mathause** [comment]
still relevant
