### ISSUE TITLE
wrong decoding of loaded dataset from nc-file

### ISSUE THREAD

**Issue by SpghttCd** [pydata/xarray#1244]
Hello
I just upgraded from xarray 0.7.0 to 0.9.0 and noticed that the data in the variables are decoded wrong in the newer version. With `ds = xr.open_dataset(filename.nc)` in 0.7.0, the resulting dataset was correctly displayed as
```python
<xarray.Dataset>
Dimensions:  (D1: 3601, X: 5, Z: 5)
Coordinates:
  * D1       (D1) float64 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 ...
  * Z        (Z) float64 1.0 2.0 3.0 4.0 5.0
  * X        (X) float64 -2.0 -1.0 0.0 1.0 2.0
Data variables:
    Brad     (D1, Z, X) float64 -1.592 0.44 3.032 5.408 4.428 -0.68 0.432 ...
    Btan     (D1, Z, X) float64 -13.33 -12.1 -10.68 -7.524 -4.032 -5.44 ...
    Bax      (D1, Z, X) float64 11.97 12.3 11.7 7.86 3.14 6.112 6.188 5.524 ...
    T        (D1, Z, X) float64 26.79 27.23 26.87 26.75 27.42 27.85 27.19 ...
```
With 0.9.0 the same file shows up the following way
```python
<xarray.Dataset>
Dimensions:  (D1: 3601, X: 5, Z: 5)
Coordinates:
  * D1       (D1) float64 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 ...
  * Z        (Z) float64 1.0 2.0 3.0 4.0 5.0
  * X        (X) float64 254.0 255.0 0.0 1.0 2.0
Data variables:
    Brad     (D1, Z, X) float64 32.83 32.77 32.77 57.02 58.94 58.98 58.98 ...
    Btan     (D1, Z, X) float64 33.29 1.835 22.81 16.38 23.33 65.27 15.47 ...
    Bax      (D1, Z, X) float64 11.97 12.3 11.7 7.86 3.14 6.112 6.188 5.524 ...
    T        (D1, Z, X) float64 1.19 1.63 1.27 1.15 1.82 2.25 1.59 1.37 1.33 ...
```
The first thing I guessed was some problem with the decoding according to CF-conventions - but this behaviour is independent from if I used CF-conventions-conform compressing via scale and add_offset or not.
Note that both file versions for testing (float64 and integer-compressed) were written with xarray 0.7.0

I hope I didn't miss some important changes between 0.7.0 and 0.9.0, but imho there's no related topic in the changelog, which told me what's the reason here.

**Comment by shoyer** [comment]
Can you report what the raw dataset looks like, either with `ncdump -h` or `xr.open_dataset(filename).info()` (on xarray v0.9)?

**Comment by SpghttCd** [comment]
Of course (ncdump -h):
```
netcdf \15_m_erster\ Test_360_d01 {
dimensions:
        D1 = 3601 ;
        Z = 5 ;
        X = 5 ;
variables:
        double D1(D1) ;
                string D1:units = "┬░" ;
        double Z(Z) ;
                string Z:units = "mm" ;
        double X(X) ;
                string X:units = "mm" ;
        double Brad(D1, Z, X) ;
                string Brad:units = "mT" ;
        double Btan(D1, Z, X) ;
                string Btan:units = "mT" ;
        double Bax(D1, Z, X) ;
                string Bax:units = "mT" ;
        double T(D1, Z, X) ;
                string T:units = "degC" ;
}
```
I can add the before mentioned integer compressed version, too, if needed. But there's no difference regarding the issue and it's a little longer of course.

**Comment by shoyer** [comment]
Are you sure that the only difference is the version of xarray? This feels like a difference in the underlying libraries -- xarray doesn't do any decoding for data that is stored as doubles without scale and add_offset.

If you're using netCDF4-python to read the data (which is the default), could you please check the versions of netCDF4-python, libnetcdf and hdf5? That would help track down if this is an xarray issue or an issue with an underlying library..

**Comment by SpghttCd** [comment]
No, you're right. I think almost everything changed, because the jump to 0.9.0 happened because of the switch to the latest WinPython-Distribution.
What I can read out is the version of netCDF4 in Python, which was 1.2.2 in the former WinPython-package and now is 1.2.7 in the latest.
But regarding your question about libnetcdf and hdf5 I think I don't understand enough: are these also python libraries? hdf5 isn't there, only h5py which I thought was an alternative, not a requirement to netcdf4, and libnetcdf I cannot find at all...

**Comment by shoyer** [comment]
@SpghttCd These are underlying C libraries used by netCDF4-python. For example, on my machine:
```
In [1]: import netCDF4

In [2]: netCDF4.__hdf5libversion__
Out[2]: '1.8.17'

In [3]: netCDF4.__netcdf4libversion__
Out[3]: '4.4.1'
```

Please check if you get different data just using `netCDF4`, in which case we can report the issue upstream.

**Comment by SpghttCd** [comment]
Ok, understood. I'll check these two library versions tomorrow. What I already did was opening the nc-file via `netCDF4.Dataset (filename)` - but this one just loads without respecting scale and offset, so I received only the integer data. Will repeat this test with the float64-file tomorrow, too.

**Comment by SpghttCd** [comment]
Hello,
by comparing different files with different encodings I have to admit that I cannot reproduce the issue named in the title. In contrast, the erroneous behaviour seems to explicitly origin from my implementation of scale- and offset encoding  and in no way from any library- or distribution-version.
I definitely thought I checked that first - so sorry for opening an issue on that here and however thanks for helping out.

**Comment by SpghttCd** [comment]
Ok I was _not_ sleeping while reporting this issue... :-)
Just if others examine the same problems - or perhaps someone can explain to me...:
The reason for strange data in loaded nc-files was as far as I can see because I saved the same file in different versions - although already loaded - and then loaded again. This seems to me is not a good idea. Perhaps things even went worse because I had two instances of Spyder running, happily switching from one to the other saving and loading the file in order to find problems dependent on library versions.
But the problem was just this whole procedure itself.
The only thing I still don't really know now is what exactly is forbidden or what is the recommended kind of handling - as saving and loading again is imo not an unconventional or unusual part of a workflow...

**Comment by shoyer** [comment]
Just to be clear -- you overrode the file on disk while you had it open in another session? Indeed, that is definitely not a recommended workflow, so I'm not surprised things broke. An error would have been friendlier than silent corruption, but maybe the netcdf devs have reasons for this behavior.

Xarray loads data from disk lazily by default, so if you want to overwrite the data on disk you should call `.load()` or `.compute()` first. But generally, I recommend always creating new files. Treating data files as immutable makes it much harder to accidentally overwrite the wrong data.

**Comment by SpghttCd** [comment]
Ok - thanks for clarification.
I remember the `NC_SHARE` flag for the open function in the netcdf-C-api...
But I also think your advice is reasonable.
