### ISSUE TITLE
Positional indexing with a large float32 coordinate.

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1246]
The positional indexing fails if the coordinate is large **np.float32** array.
The minimum working example is 

> da_float64 = xr.DataArray(np.random.randn(1000000), 
>                        coords={'Time': np.linspace(0.0,1.0,1000000).astype(np.float64)})
> da_float64.loc[0.2:0.3] # This works fine
> 
> da_float32 = xr.DataArray(np.random.randn(1000000), 
>                        coords={'Time': np.linspace(0.0,1.0,1000000).astype(np.float32)})
> da_float32.loc[0.2:0.3] # This causes a kernel freeze.

With a smaller sized DataArray, both works.

> da_float32.to_pandas()

also freezes the kernel.

Are these a pandas's issue?

I used Python 3.5 and xarray 0.8.2.

**Comment by shoyer** [comment]
What version of pandas and what operating system are you using?

This is *likely* an upstream issue in pandas but I'm not entirely certain. I can't reproduce this behavior on my computer.

For reporting this to pandas, it would be helpful if you could reproduce this issue only using pandas, e.g., `pandas.Series(np.random.randn(1000000), np.linspace(0.0,1.0,1000000).astype(np.float32))`.

**Comment by fujiisoup** [comment]
@shoyer , Thank you for your comment.

I used pandas 0.18.1 but if update to 0.19.2, then the problem solves!
Thank you very much.
