### ISSUE TITLE
Slice on netcdf dataset has transient lazy indexing problem

### ISSUE THREAD

**Issue by rustychris** [pydata/xarray#1253]
I am trying to open a netcdf dataset off an ERDDAP server, slice out a subset of times, and run further manipulations on the result.  This snippet:

```
import xarray as xr

remote_ds=xr.open_dataset("http://sfbaynutrients.sfei.org/erddap/tabledap/usgs_sfb_nutrients")
# Doesn't break if the slice is [10:20], [10:9000], [183039:183049]
# Only get the behavior when the slice is large-ish and far from the beginning
sliced_ds=remote_ds.isel(s=slice(183039, 191509, None))

print(sliced_ds['s.Distance_from_station_36'][:10])
print(sliced_ds['s.Distance_from_station_36'][:10])
print(remote_ds['s.Distance_from_station_36'][:10])
print(xr.version.version)
```

Yields the following output:
```
<xarray.DataArray 's.Distance_from_station_36' (s: 10)>
array([ 119.080002,  119.080002,  119.080002,  119.080002,  114.93    ,
        114.93    ,  114.93    ,  114.93    ,  110.07    ,  110.07    ], dtype=float32)
Dimensions without coordinates: s
<xarray.DataArray 's.Distance_from_station_36' (s: 10)>
array([ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.66,  1.66,  1.66,  1.66], dtype=float32)
Dimensions without coordinates: s
<xarray.DataArray 's.Distance_from_station_36' (s: 10)>
array([ 119.080002,  119.080002,  119.080002,  119.080002,  114.93    ,
        114.93    ,  114.93    ,  114.93    ,  110.07    ,  110.07    ], dtype=float32)
Dimensions without coordinates: s
0.9.1
```

(I've omitted attributes for brevity - the printed attributes are identical for all 3).

The issue is that the first time I print or copy data from sliced_ds, it ignores the slice and displays the un-sliced data.  The exact same print statement, a second time, gives the correct values.  For reference, I've also printed the first 10 elements of the unsliced data, to show that they agree with the first, erroneous, print result.  The behavior is not limited to print statements -- a deep copy sliced_ds will also show this issue.

System: linux, kubuntu.  python=anaconda 3.5.1. numpy=1.10.4, xarray 0.9.1.

As a workaround, I can call sliced_ds.copy(deep=True) twice and the second time around it's okay.

**Comment by shoyer** [comment]
Have you found similar behavior when loading from a netCDF file, or does it seem to require a remote dataset?

Can you try loading the dataset with `cache=False` in `open_dataset`?

**Comment by rustychris** [comment]
I tried the same snippet on a local copy of the dataset (via `remote_ds.to_netcdf('local.nc')`).  The behavior is not evident with the local dataset.

`cache=False` did not change the behavior (for either remote or local datasets).

**Comment by shoyer** [comment]
OK, my guess is that this is an upstream issue in [netCDF4-C](https://github.com/unidata/netcdf-c)'s DAP reader. Neither xarray nor netCDF4-python contain any logic the works differently on local vs remote files.

**Comment by rustychris** [comment]
Ok.  I'll poke around in that direction.  For the record, I'm using netCDF4 1.2.4.
