### ISSUE TITLE
selecting a point from an irregular grid?

### ISSUE THREAD

**Issue by guziy** [pydata/xarray#1258]
HI:

I was wondering if I have a dataarray based on 2d lon and lat fields is it possible to select values for selected lon and lat pairs?

Here is the schema of my DataArray:

```python
vardict = {
            "coords": {
                "t": {"dims": "t", "data": dates},
                "lon": {"dims": ("x", "y"), "data": self.lons},
                "lat": {"dims": ("x", "y"), "data": self.lats},
            },
            "dims": ("t", "x", "y"),
            "data": data_list,
            "name": varname_internal
        }
```

Is it possible to do smth like

```python
timeseries = da.sel(lon=-110, lat=65)
```

Cheers

**Comment by jhamman** [comment]
This is not currently possible but we've been discussing it and its just waiting for someone to implement it.  

xref: https://github.com/pydata/xarray/issues/475
