### ISSUE TITLE
GroupBy like API for resample

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1269]
Since we wrote `resample` in xarray, pandas updated resample to have a groupyby-like API (e.g., `df.resample('24H').mean()` vs. the old `df.resample('24H')` that uses the mean by default).

It would be nice to redo the xarray resample API to match, e.g., `ds.resample(time='24H').mean()` vs `ds.resample('time', '24H')`. This would solve a few use cases, including grouped-resample arithmetic, iterating over groups and (mostly) take care of the need for `pd.TimeGrouper` support (https://github.com/pydata/xarray/issues/364). If we use `**kwargs` for matching dimension names, this could be done with a minimally painful deprecation cycle.

**Comment by darothen** [comment]
Let me dig into this a bit right now. My analysis project for this afternoon was already going to require digging into pandas' resampling in more depth anyways.

**Comment by darothen** [comment]
Assuming we want to stick with `pd.TimeGrouper` under the hood, the only sticking point I've come across so far is how to have the resulting `Data{Array,set}GroupBy` object "remember" the resampling dimension, e.g. if you have multi-dimensional data and want to compute time means you have to call

``` python
ds.resample(time='24H').mean('time')
```

or else `mean` will operate across all dimensions. Any thoughts, @shoyer?

**Comment by MaximilianR** [comment]
Would be great to test for these sorts of issues if we redo this: https://github.com/pydata/xarray/issues/1269

**Comment by MaximilianR** [comment]
>the only sticking point I've come across so far is how to have the resulting Data{Array,set}GroupBy object "remember" the resampling dimension

I think an interface like `ds.resample(time='24H').mean()` would be much better. We could do that with a wrapper of `pd.TimeGrouper` that also had a `dim` field. Or inheritance 😨

**Comment by darothen** [comment]
@MaximilianR Oh, the interface is easy enough to do, even maintaining backwards-compatibility (already have that working). I was considering going the route done with [GroupBy](https://github.com/pydata/xarray/blob/93d6963315026f87841c7cf39cc39bb78f555345/xarray/core/groupby.py#L165) and the classes that compose it, like [DatasetGroupBy](https://github.com/pydata/xarray/blob/93d6963315026f87841c7cf39cc39bb78f555345/xarray/core/groupby.py#L586)... basically, we just record the wanted resampling dimension and inject the grouping/resampling operations we want. Also adds the ability to specialize methods like `.first()` and `.last()`, which is done under the current implementation.

*But*.... if there's a simpler way, that might be preferable!

**Comment by shoyer** [comment]
I think this could be done with minimal GroupBy subclasses to supply the
default dimension argument for aggregation functions. All the machinery on
groupby should already be there.
