### ISSUE TITLE
DataArray doesnt use bottleneck implementation on rolling variance

### ISSUE THREAD

**Issue by d-chambers** [pydata/xarray#1276]
It appears that the DataArray is not using the bottleneck move_var when calling var on a rolling object but it does for std. I have attached some simple benchmarks to demonstrate. 

python version 3.6
pandas version 0.19.2
xarray version 0.9.1
bottleneck version 1.2.0

```python
import numpy as np
import xarray as xr
import bottleneck
import pandas as pd

data = np.random.rand(10000)

# xarray setup
ar = xr.DataArray(data, dims=['time'])
xrol = ar.rolling(time=30)

# pandas setup
df = ar.to_pandas()
prol = df.rolling(30)
```

```python
# xray std profile
%time _ = xrol.std()
```

    CPU times: user 0 ns, sys: 0 ns, total: 0 ns
    Wall time: 209 µs

```python
# xray var profile
%time _ = xrol.var()
```

    CPU times: user 8.69 s, sys: 132 ms, total: 8.82 s
    Wall time: 8.52 s

```python
# pandas std profile
%time _ = prol.std()
```

    CPU times: user 0 ns, sys: 0 ns, total: 0 ns
    Wall time: 1.13 ms

```python
# pandas var profile
%time _ = prol.var()
```

    CPU times: user 0 ns, sys: 0 ns, total: 0 ns
    Wall time: 617 µs

```python
# bottleneck std profile
%time _ = bottleneck.move_std(data, 30)
```

    CPU times: user 0 ns, sys: 0 ns, total: 0 ns
    Wall time: 138 µs

```python
# bottleneck var profile
%time _ = bottleneck.move_var(data, 30)
```

    CPU times: user 0 ns, sys: 0 ns, total: 0 ns
    Wall time: 143 µs

**Comment by shoyer** [comment]
Indeed, `var` is not in the list of ops for which we use bottleneck:
https://github.com/pydata/xarray/blob/7e0abe5542168b2aafbda18fe5db62f39b5df498/xarray/core/ops.py#L53-L55

Looks like `median` would also be a good one to add.

Maybe @jhamman recalls why we don't use bottleneck for these?

**Comment by jhamman** [comment]
@shoyer and @d-chambers - 

Take a look at #1278. The issue here was that we had not kept up with bottleneck's improvements and in 1.1, they added `move_var`. I think my PR should remedy this.
