### ISSUE TITLE
Current doc builds are broken

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1280]
This is a RTD problem so out of our control, but I'll leave this issue opened until it is resolved.

See RTD issue: https://github.com/rtfd/readthedocs.org/issues/2651

**Comment by spencerahill** [comment]
FYI this appears to have just been fixed on the RTD end: https://github.com/rtfd/readthedocs.org/issues/2651#issuecomment-284922193

**Comment by fmaussion** [comment]
Yes indeed: https://readthedocs.org/projects/xray/builds/5120176/

Interesting how the RTD folks managed this.
