### ISSUE TITLE
description of xarray assumes knowledge of pandas

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#1282]
The first sentence a potential new user reads about xarray is 
> xarray (formerly xray) is an open source project and Python package that aims to bring the labeled data power of pandas to the physical sciences, by providing N-dimensional variants of the core pandas data structures.

Now imagine you had never heard of pandas (like most new Ph.D. students in physical sciences). You would have no idea how useful and powerful xarray was.

I would propose modifying these top-level descriptions to remove the assumption that the user understands pandas. Of course we can still refer to pandas, but a more self-contained description would serve us well.

**Comment by shoyer** [comment]
Agreed!

Here's what @jhamman and I wrote in the abstract for [our paper](https://github.com/jhamman/xarray_paper/blob/master/jors_xarray.tex) on Xarray:

> Xarray is an open source project and Python package that provides a toolkit and data structures for N-dimensional labeled arrays. Our approach combines an application programming interface (API) inspired by pandas with the Common Data Model for self-described scientific data. Key features of the Xarray package include label-based indexing and arithmetic, interoperability with the core scientific Python packages (e.g., pandas, NumPy, Matplotlib), out-of-core computation on datasets that don't fit into memory, a wide range of serialization and input/output (I/O) options, and advanced multi-dimensional data manipulation tools such as group-by and resampling. Xarray, as a data model and analytics toolkit, has been widely adopted in the geoscience community but is also used more broadly for multi-dimensional data analysis in physics, machine learning and finance.

Probably something like that first sentence is a better high level description.

**Comment by byersiiasa** [comment]
I agree as I was in this situation of jumping straight into xarray (and Python) having never used pandas.  As for other key points that could be emphasised:

- , the concept of label-based indexing was new to me and may be something you may want to add more emphasis on in the Page 1 description? (I see it is already nicely explained in the paper in referecend to np.ndarrays.)
- the automatic plotting with Matplotlib is super

**Comment by rabernat** [comment]
Closed by #2430 #2657.
