### ISSUE TITLE
Spurious .DS_Store files in PyPI tarball

### ISSUE THREAD

**Issue by ghisvail** [pydata/xarray#1283]
Please make sure that future release tarballs on PyPI are free from undesirable files.

In `xarray-0.9.1.tar.gz`:
```shell
find . -name .DS_Store
./doc/.DS_Store
./doc/examples/.DS_Store
./doc/_static/.DS_Store
```

Cheers,
Ghis

**Comment by MaximilianR** [comment]
Thanks - PR into `.gitignore` would be welcome!

**Comment by ghisvail** [comment]
You meant `MANIFEST.in` right?

**Comment by shoyer** [comment]
Oops, thanks for catching this!
