### ISSUE TITLE
Groupby method on larger files fails unless explicitly load data in 0.9.1

### ISSUE THREAD

**Issue by koglin** [pydata/xarray#1287]
Below x is from a 4.2GB file opened with engine='h5netcdf'.  The following groupby method was working without explicit load() before in v0.8.2, but now fails unless explicitly load either the entire object or the var of interest.

```Python-traceback
In [52]: x.EBeam_ebeamPhotonEnergy.groupby('step').mean()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-e0f4fcacc6a2> in <module>()
----> 1 x.EBeam_ebeamPhotonEnergy.groupby('step').mean()

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/common.pyc in wrapped_func(self, dim, axis, skipna, keep_attrs, **kwargs)
     17                              keep_attrs=False, **kwargs):
     18                 return self.reduce(func, dim, axis, keep_attrs=keep_attrs,
---> 19                                    skipna=skipna, allow_lazy=True, **kwargs)
     20         else:
     21             def wrapped_func(self, dim=None, axis=None, keep_attrs=False,

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/groupby.pyc in reduce(self, func, dim, axis, keep_attrs, shortcut, **kwargs)
    577         def reduce_array(ar):
    578             return ar.reduce(func, dim, axis, keep_attrs=keep_attrs, **kwargs)
--> 579         return self.apply(reduce_array, shortcut=shortcut)
    580 
    581 ops.inject_reduce_methods(DataArrayGroupBy)

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/groupby.pyc in apply(self, func, shortcut, **kwargs)
    521         applied = (maybe_wrap_array(arr, func(arr, **kwargs))
    522                    for arr in grouped)
--> 523         return self._combine(applied, shortcut=shortcut)
    524 
    525     def _combine(self, applied, shortcut=False):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/groupby.pyc in _combine(self, applied, shortcut)
    525     def _combine(self, applied, shortcut=False):
    526         """Recombine the applied objects like the original."""
--> 527         applied_example, applied = peek_at(applied)
    528         coord, dim, positions = self._infer_concat_args(applied_example)
    529         if shortcut:

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/utils.pyc in peek_at(iterable)
    112     """
    113     gen = iter(iterable)
--> 114     peek = next(gen)
    115     return peek, itertools.chain([peek], gen)
    116 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/groupby.pyc in <genexpr>((arr,))
    520             grouped = self._iter_grouped()
    521         applied = (maybe_wrap_array(arr, func(arr, **kwargs))
--> 522                    for arr in grouped)
    523         return self._combine(applied, shortcut=shortcut)
    524 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/groupby.pyc in reduce_array(ar)
    576         """
    577         def reduce_array(ar):
--> 578             return ar.reduce(func, dim, axis, keep_attrs=keep_attrs, **kwargs)
    579         return self.apply(reduce_array, shortcut=shortcut)
    580 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/variable.pyc in reduce(self, func, dim, axis, keep_attrs, allow_lazy, **kwargs)
    902         if dim is not None:
    903             axis = self.get_axis_num(dim)
--> 904         data = func(self.data if allow_lazy else self.values,
    905                     axis=axis, **kwargs)
    906 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/variable.pyc in data(self)
    263             return self._data
    264         else:
--> 265             return self.values
    266 
    267     @data.setter

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/variable.pyc in values(self)
    304     def values(self):
    305         """The variable's data as a numpy.ndarray"""
--> 306         return _as_array_or_item(self._data)
    307 
    308     @values.setter

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/variable.pyc in _as_array_or_item(data)
    180     TODO: remove this (replace with np.asarray) once these issues are fixed
    181     """
--> 182     data = np.asarray(data)
    183     if data.ndim == 0:
    184         if data.dtype.kind == 'M':

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    480 
    481     """
--> 482     return array(a, dtype, copy=False, order=order)
    483 
    484 def asanyarray(a, dtype=None, order=None):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/indexing.pyc in __array__(self, dtype)
    415 
    416     def __array__(self, dtype=None):
--> 417         self._ensure_cached()
    418         return np.asarray(self.array, dtype=dtype)
    419 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/indexing.pyc in _ensure_cached(self)
    412     def _ensure_cached(self):
    413         if not isinstance(self.array, np.ndarray):
--> 414             self.array = np.asarray(self.array)
    415 
    416     def __array__(self, dtype=None):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    480 
    481     """
--> 482     return array(a, dtype, copy=False, order=order)
    483 
    484 def asanyarray(a, dtype=None, order=None):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/indexing.pyc in __array__(self, dtype)
    396 
    397     def __array__(self, dtype=None):
--> 398         return np.asarray(self.array, dtype=dtype)
    399 
    400     def __getitem__(self, key):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    480 
    481     """
--> 482     return array(a, dtype, copy=False, order=order)
    483 
    484 def asanyarray(a, dtype=None, order=None):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/indexing.pyc in __array__(self, dtype)
    371     def __array__(self, dtype=None):
    372         array = orthogonally_indexable(self.array)
--> 373         return np.asarray(array[self.key], dtype=None)
    374 
    375     def __getitem__(self, key):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    480 
    481     """
--> 482     return array(a, dtype, copy=False, order=order)
    483 
    484 def asanyarray(a, dtype=None, order=None):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/indexing.pyc in __array__(self, dtype)
    371     def __array__(self, dtype=None):
    372         array = orthogonally_indexable(self.array)
--> 373         return np.asarray(array[self.key], dtype=None)
    374 
    375     def __getitem__(self, key):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/xarray/core/utils.pyc in __getitem__(self, key)
    418 
    419     def __getitem__(self, key):
--> 420         return self.array[key]
    421 
    422     def __repr__(self):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/h5netcdf/core.pyc in __getitem__(self, key)
     96 
     97     def __getitem__(self, key):
---> 98         return self._h5ds[key]
     99 
    100     def __setitem__(self, key, value):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/conda-bld/h5py_1484088818009/work/h5py-2.7.0rc2/h5py/_objects.c:3185)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/conda-bld/h5py_1484088818009/work/h5py-2.7.0rc2/h5py/_objects.c:3143)()

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in __getitem__(self, args)
    472 
    473         # Perform the dataspace selection.
--> 474         selection = sel.select(self.shape, args, dsid=self.id)
    475 
    476         if selection.nselect == 0:

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/h5py/_hl/selections.pyc in select(shape, args, dsid)
     70         elif isinstance(arg, np.ndarray):
     71             sel = PointSelection(shape)
---> 72             sel[arg]
     73             return sel
     74 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.2.1/lib/python2.7/site-packages/h5py/_hl/selections.pyc in __getitem__(self, arg)
    210         """ Perform point-wise selection from a NumPy boolean array """
    211         if not (isinstance(arg, np.ndarray) and arg.dtype.kind == 'b'):
--> 212             raise TypeError("PointSelection __getitem__ only works with bool arrays")
    213         if not arg.shape == self.shape:
    214             raise TypeError("Boolean indexing array has incompatible shape")

TypeError: PointSelection __getitem__ only works with bool arrays

In [55]: x.EBeam_ebeamPhotonEnergy.load().groupby('step').mean()
Out[55]: 
<xarray.DataArray 'EBeam_ebeamPhotonEnergy' (step: 65)>
array([ 9045.704225,  9045.543454,  9044.706383,  9048.093055,  9045.000397,
        9043.704296,  9047.318191,  9047.263165,  9044.936176,  9045.865424,
        9041.683054,  9043.722705,  9044.589087,  9044.032681,  9045.478713,
        9043.710082,  9042.061361,  9043.566752,  9045.868629,  9042.725552,
        9043.797367,  9042.54982 ,  9042.713473,  9042.841264,  9042.689603,
        9043.722533,  9045.750076,  9046.675932,  9045.879081,  9047.069358,
        9044.710387,  9044.921831,  9044.884213,  9045.407495,  9043.409401,
        9044.276054,  9050.751243,  9042.902832,  9045.744036,  9042.485437,
        9042.760976,  9044.195124,  9042.054604,  9042.274026,  9042.602458,
        9045.287399,  9044.173708,  9043.708038,  9043.264793,  9047.872945,
        9044.193639,  9044.424931,  9044.065687,  9043.453713,  9045.404021,
        9042.907949,  9045.248006,  9045.170088,  9045.345617,  9046.065199,
        9045.846606,  9041.401112,  9042.031974,  9043.363107,  9041.911583])
Coordinates:
  * step     (step) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
```

**Comment by shoyer** [comment]
Hmm. Is this using the exact same version of h5py?

**Comment by koglin** [comment]
Looking back I see that before I would generally use dropna('time') before groupby.  Without dropna I get the same error with xarray 0.8.2 and either h5py 2.5.0 or 2.6.0.    

The following give the same result:
x.EBeam_ebeamPhotonEnergy.dropna('time').groupby('step').mean()
x.EBeam_ebeamPhotonEnergy.load().groupby('step').mean()

Note that even when I dropna on the dataset and then save and reload the data I see the same behavior, so the issue does not seem to simply be handling NA values.  

Looking closer at the example I gave, I do see that our build has an inconsistency in which h5py is used.  It looks like h5netcdf is compiled using h5py-2.7.0rc2, but h5py imports as 2.6.0.  So this might just be related to our build.

In [21]: from h5netcdf import core

In [22]: core._NC_PROPERTIES
Out[22]: u'version=1|h5netcdfversion=0.3.1|hdf5libversion=1.8.18'

In [24]: core.h5py.__version__
Out[24]: '2.6.0'

I see it noted that h5py 2.6.0 passes tests in h5netcdf which other versions may not.  I do not have a version with h5py 2.6.0 consistently used conveniently available.   If it is believed that explicitly or implicitly loading data is not necessary, then I can try getting a consistent build with h5py 2.6.0, since this would be a convenient, although not strictly necessary, feature. 

Note that in an earlier release where everything looks to be h5py 2.5.0, I get similar error without explicit load() of data.  Below is a slightly different example with h5py 2.5.0 of using where method instead of groupby.

In [1]: from h5netcdf import core

In [2]: core.h5py.__version__
Out[2]: '2.5.0'

In [3]: core._NC_PROPERTIES
Out[3]: u'version=1|h5netcdfversion=0.3.1|hdf5libversion=1.8.17'

In [4]: import PyDataSource

In [5]: x = PyDataSource.open_h5netcdf(exp='mfx11116',run=25, subfolder='temp')

In [6]: x.step.where(abs(x.step-5)<2, drop=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-f13d4f4e92e7> in <module>()
----> 1 x.step.where(abs(x.step-5)<2, drop=True)

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/common.pyc in where(self, cond, other, drop)
    572                                             for adim in np.nonzero(clipcond.values)]))
    573             outcond = cond.isel(**clip)
--> 574             outobj = self.sel(**outcond.indexes)
    575         else:
    576             outobj = self

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/coordinates.pyc in __getitem__(self, key)
    245     def __getitem__(self, key):
    246         if key in self:
--> 247             return self._variables[key].to_index()
    248         else:
    249             raise KeyError(key)

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/variable.pyc in to_index(self)
   1165         # basically free as pandas.Index objects are immutable
   1166         assert self.ndim == 1
-> 1167         index = self._data_cached().array
   1168         if isinstance(index, pd.MultiIndex):
   1169             # set default names for multi-index unnamed levels so that

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/variable.pyc in _data_cached(self)
   1088     def _data_cached(self):
   1089         if not isinstance(self._data, PandasIndexAdapter):
-> 1090             self._data = PandasIndexAdapter(self._data)
   1091         return self._data
   1092 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/indexing.pyc in __init__(self, array, dtype)
    437     """
    438     def __init__(self, array, dtype=None):
--> 439         self.array = utils.safe_cast_to_index(array)
    440         if dtype is None:
    441             if isinstance(array, pd.PeriodIndex):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/utils.pyc in safe_cast_to_index(array)
     56         if hasattr(array, 'dtype') and array.dtype.kind == 'O':
     57             kwargs['dtype'] = object
---> 58         index = pd.Index(np.asarray(array), **kwargs)
     59     return index
     60 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    480 
    481     """
--> 482     return array(a, dtype, copy=False, order=order)
    483 
    484 def asanyarray(a, dtype=None, order=None):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/indexing.pyc in __array__(self, dtype)
    353     def __array__(self, dtype=None):
    354         array = orthogonally_indexable(self.array)
--> 355         return np.asarray(array[self.key], dtype=None)
    356 
    357     def __getitem__(self, key):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/conventions.pyc in __getitem__(self, key)
    394     def __getitem__(self, key):
    395         return decode_cf_datetime(self.array[key], units=self.units,
--> 396                                   calendar=self.calendar)
    397 
    398 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/conventions.pyc in decode_cf_datetime(num_dates, units, calendar)
    124     netCDF4.num2date
    125     """
--> 126     num_dates = np.asarray(num_dates, dtype=float)
    127     flat_num_dates = num_dates.ravel()
    128     if calendar is None:

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    480 
    481     """
--> 482     return array(a, dtype, copy=False, order=order)
    483 
    484 def asanyarray(a, dtype=None, order=None):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/indexing.pyc in __array__(self, dtype)
    353     def __array__(self, dtype=None):
    354         array = orthogonally_indexable(self.array)
--> 355         return np.asarray(array[self.key], dtype=None)
    356 
    357     def __getitem__(self, key):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/xarray/core/utils.pyc in __getitem__(self, key)
    393 
    394     def __getitem__(self, key):
--> 395         return self.array[key]
    396 
    397     def __repr__(self):

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/h5netcdf/core.pyc in __getitem__(self, key)
     96 
     97     def __getitem__(self, key):
---> 98         return self._h5ds[key]
     99 
    100     def __setitem__(self, key, value):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/conda-bld/h5py-2.5.0_1474173302699/work/h5py-2.5.0/h5py/_objects.c:3032)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/conda-bld/h5py-2.5.0_1474173302699/work/h5py-2.5.0/h5py/_objects.c:2990)()

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in __getitem__(self, args)
    429 
    430         # Perform the dataspace selection.
--> 431         selection = sel.select(self.shape, args, dsid=self.id)
    432 
    433         if selection.nselect == 0:

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/h5py/_hl/selections.pyc in select(shape, args, dsid)
     77         elif isinstance(arg, np.ndarray):
     78             sel = PointSelection(shape)
---> 79             sel[arg]
     80             return sel
     81 

/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.0.8/lib/python2.7/site-packages/h5py/_hl/selections.pyc in __getitem__(self, arg)
    215         """ Perform point-wise selection from a NumPy boolean array """
    216         if not (isinstance(arg, np.ndarray) and arg.dtype.kind == 'b'):
--> 217             raise TypeError("PointSelection __getitem__ only works with bool arrays")
    218         if not arg.shape == self.shape:
    219             raise TypeError("Boolean indexing array has incompatible shape")

TypeError: PointSelection __getitem__ only works with bool arrays

In [7]: x.load().step.where(abs(x.step-5)<2, drop=True)
Out[7]: 
<xarray.DataArray 'step' (time: 725)>
array([ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,

**Comment by dcherian** [comment]
Please reopen with a reproducible example if this is still an issue.
