### ISSUE TITLE
python 3.6 tests break with bottleneck installed

### ISSUE THREAD

**Issue by maxim-lian** [pydata/xarray#1294]
Installing 3.6 environment (from the ci path in xarray): tests pass on master
Then installing bottleneck: 3 tests in test_dataarray.py fail on master

I can debug further unless anyone has a view

**Comment by jhamman** [comment]
@MaximilianR - can you try testing with this branch: https://github.com/pydata/xarray/pull/1278

I'm guessing the errors you're getting are related.

**Comment by maxim-lian** [comment]
Fixed
