### ISSUE TITLE
Wrap bottleneck for fast moving window aggregations

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#130]
Like pandas, we should wrap [bottleneck](https://github.com/kwgoodman/bottleneck) to create fast moving window operations and missing value operation that can be applied to xray data arrays.

As xray is designed to make it straightforward to work with high dimensional arrays, it would be particularly convenient if bottleneck had fast functions for N > 3 dimensions (see kwgoodman/bottleneck/issues/84) but we should wrap bottleneck regardless for functions like rolling_mean, rolling_sum, rolling_min, etc.

**Comment by shoyer** [comment]
Wrapping bottleneck for operations like `nanmean` was fixed in #304.

**Comment by shoyer** [comment]
Some further thoughts:

- I would probably implement these as methods on `Dataset`/`DataArray` (e.g., `ds.rolling_mean(dim='time', window=5)` instead of functions. This is different from pandas, but seems slightly more in line with how everything else in pandas/xray operates.
- I don't have a strong opinion whether we use the name `rolling` (like pandas) or `moving`/`move` (like bottleneck). Maybe rolling is slightly more obvious?
- These functiosn from bottleneck could be easily extended to work on dask arrays by using using ghost: http://dask.pydata.org/en/latest/ghost.html

**Comment by shoyer** [comment]
There's been some related discussion about a better API for the rolling aggregation functions in pandas recently: https://github.com/pydata/pandas/pull/10702

**Comment by jhamman** [comment]
closed via #668
