### ISSUE TITLE
git version label yields version in violation of PEP 440

### ISSUE THREAD

**Issue by gerritholl** [pydata/xarray#1300]
When an `xarray` installation does not match a released version ,it has a version number like `0.9.1-28-g769f120`.

This violates [PEP 440](https://www.python.org/dev/peps/pep-0440/), which leads to multiple problems:

* `pip install --update` will revert `xarray` back to `0.9.1`, because it does not recognise that `0.9.1-28-g769f120 > 0.9.1`
* packages with an `xarray` dependencies will be considered not satisfied.  Running a script through `setuptools` `load_entry_point` fails with `pkg_resources.ContextualVersionConflict: (xarray 0.9.1-28-g769f120 (/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages), Requirement.parse('xarray>=0.8')`

Instead, the version number above should be written as `0.9.1+r10345` or so, which would satisfy PEP 440 and not cause problems with `pip` or `setuptools`.

**Comment by shoyer** [comment]
Yes, we should update this. Our current logic for determining git versions is in `setup.py` and was originally copied from pndnas, but we really should consider updating to use what dask and pandas now use, which is versioneer.

**Comment by dopplershift** [comment]
👍  to versioneer. I've found it really easy to use.
