### ISSUE TITLE
Create `xarray.Dataset` from a `netCDF4.Dataset` object

### ISSUE THREAD

**Issue by andreas-h** [pydata/xarray#1304]
For some applications, it would be nice if it were possible to create an `xarray.Dataset` from a `netCDF4.Dataset`, so that the following code would work:

    with Dataset(filename) as nc:
        ds = xr.open_dataset(nc)

**Comment by fmaussion** [comment]
I also needed something like this but @shoyer decided [against this change](https://github.com/pydata/xarray/pull/1060#issuecomment-256109866) until there is a cleaner datastore API.

A (very) dirty workaround it to subclass ``xarray.backends.NetCDF4DataStore`` and redefine ``__init__`` to accept netcdf datasets as argument:

```
class _NetCDF4DataStore(NetCDF4DataStore):
    """Just another way to init xarray's datastore."""
    def __init__(self, filename, mode='r', format='NETCDF4', group=None,
                 writer=None, clobber=True, diskless=False, persist=False,
                 ds=None):
        import netCDF4 as nc4
        if format is None:
            format = 'NETCDF4'
        if ds is None:
            ds = nc4.Dataset(filename, mode=mode, clobber=clobber,
                             diskless=diskless, persist=persist,
                             format=format)
        with close_on_error(ds):
            self.ds = _nc4_group(ds, group, mode)
        self.format = format
        self.is_remote = False
        self._filename = filename
        super(NetCDF4DataStore, self).__init__(writer)

nc = netCDF4.Dataset(filename)
ds = xr.open_dataset(_NetCDF4DataStore(filename, ds=nc))
```

**Comment by shoyer** [comment]
This does seem like a reasonable thing to do in the advanced API. I would suggest adding another constructor in the form of a `classmethod`, maybe `from_dataset`?

**Comment by andreas-h** [comment]
Sounds good. However, maybe `from_ncdataset` would avoid possible name confusion given that there's a `Dataset` in both xarray and netCDF4? On the other hand, at least in this context one of the options wouldn't make sense ... What do you think?

**Comment by shoyer** [comment]
Yes, `from_ncdataset` would be better.

**Comment by shoyer** [comment]
This was fixed by https://github.com/pydata/xarray/pull/1508
