### ISSUE TITLE
xarray vs Xarray vs XArray

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1306]
Yes, this is a little silly, but do we have a preferred capitalization for the proper name?

We mostly stick to "xarray" in the docs but "Xarray" or "XArray" is arguably a little more readable and grammatically correct.

**Comment by fmaussion** [comment]
I guess that every package goes through this discussion ;-) (see e.g. [here](http://matplotlib.1069221.n5.nabble.com/Capitalization-of-Matplotlib-td44913.html) for matplotlib).

I like xarray because it is the same as the python package. However, for aesthetic reasons I capitalize Xarray when used for titles or at the beginning of a sentence...

**Comment by MaximilianR** [comment]
I vote `xarray`, because that's the package name, and (I think) the pronunciation is pretty clear without needing capitalization

**Comment by spencerahill** [comment]
>I capitalize Xarray when used for titles or at the beginning of a sentence

I agree with this: lower case unless beginning of a sentence or in a title.  If you capitalize the "A" too, then there's more of a discrepancy between the uncapitalized version and the capitalized one.

**Comment by jhamman** [comment]
I've been seeing "XArray" more and more. I think my week preference is "Xarray"... 

`numpy` is typically spelled "NumPy" and that doesn't lead to confusion.

**Comment by byersiiasa** [comment]
Just to add another complication, previously the package was `xray` and the shorthand typically used was and still is `xr`, e..g. `xr.open_dataset()`.
Are/have there beein any thoughts or discussions on whether `xa` would be more fitting?

**Comment by shoyer** [comment]
> Are/have there beein any thoughts or discussions on whether xa would be more fitting?

Let's not open that can of worms :). I actually usually import the package as `xarray` these days, since I like the explicitness, and due to xarray's extensive methods it's rare to need to use many functions on one line (as one does for numpy).

I am also weekly in favor of "Xarray" for the proper name, if only to avoid "XArray". But I don't know if I care enough to update all the docs.

**Comment by rabernat** [comment]
I am teaching xarray / XArray / Xarray in class tommorrow.

How should I spell it!?!? 😝

**Comment by fmaussion** [comment]
I vote for ``xarray``!

Good luck with your lecure! You probably already have all what you need, but here are some examples from my climate lecture from last years if you are interested: https://github.com/fmaussion/teaching/tree/master/legacy/ws_2016

**Comment by rabernat** [comment]
Your lectures look great!

I am trying to do something similar with physical oceanography:
https://github.com/rabernat/intro_to_physical_oceanography
not nearly as complete as yours!

The xarray lecture, however, is for a course in research computing:
https://rabernat.github.io/research_computing/

**Comment by maxim-lian** [comment]
Was this decided?

**Comment by shoyer** [comment]
Closing this. We use "xarray" in the middle of sentences and "Xarray" at the start.
