### ISSUE TITLE
Allow attributes entries to be a dictionary on store to netcdf

### ISSUE THREAD

**Issue by gyger** [pydata/xarray#1307]
Allow an entry in the attrs attribute to be a dictionary when stored to netcdf.
I am not sure if it is not possible to store dicts in netcdf file, but perhaps something similar to a path separator could be used to create a hierarchy.

**Comment by shoyer** [comment]
Sadly NetCDF does not support hierarchical attributes.

One option would be to convert your attributes into a string with `repr` and then evaluate them using `ast.literal_eval`. That would at least keep them human readable in the underlying files.

Or you could try pickle, but that won't be compatible across different platforms/netCDF readers.

**Comment by fmaussion** [comment]
Yes, or use JSON maybe? 

In all cases I don't think that there is something to do on the xarray side...

**Comment by gyger** [comment]
Thank you, then I will close the suggestion.
