### ISSUE TITLE
Image related methods

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1323]
Currently I'm using xarray to handle multiple images (typically, a sequence of images),
and I feel it would be convenient if xarray supports image related functions.

There may be many possibilities, but particular methods I want to have in xarray are
1. xr.open_image(File)  
 Currently, I open image by PILLOW, convert to np.ndarray, extract its attributes, then construct xr.DataArray  from them.
If I can do it by 1 line, it would be very great.

2. xr.DataArray.expand_dims(dim)
I want to add additional channel dimension to grey scale images (size [W x H] -> [W x H x 1]),
in order to pass them into convolutional neural network, which usually accepts 4-dimensional tensor [Batch x W x H x channel]. 

Image (possibly also video?) is naturally high-dimensional and 
I guess it would fit xarray's concept.
Is this sufficiently broad interest?

**Comment by shoyer** [comment]
> xr.open_image(File)

What metadata would you get from images? `[row, column, channel]` for a typical color image? I guess this would usually follow skimage's [coordinate conventions](http://scikit-image.org/docs/dev/user_guide/numpy_images.html#coordinate-conventions)

If we added this, we would want to defer all the image reading out to an external library such as skimage, e.g., by leveraging [`skimage.io.imread`](http://scikit-image.org/docs/dev/api/skimage.io.html)

> `xr.DataArray.expand_dims(dim)`

You're definitely not the first person to ask about this:
http://stackoverflow.com/questions/34987972/expand-dimensions-xray

Yes, this would definitely be welcome in some form.

**Comment by fujiisoup** [comment]
@shoyer  Thank you for the comment.

> What metadata would you get from images? 

I'm currently use tag data in tiff files. I guess some people may use exif metadata in jpg files.

> If we added this, we would want to defer all the image reading out to an external library

Yes, I agree.
skimage is the best candidate?
I did not know much about skimage, but this library looks great.

open_image method is possibly overkill...? 
I will keep this issue just open for a while until similar request comes out.

> You're definitely not the first person to ask about this:

My second request seems more general.
I will post it as a separate issue.

**Comment by ebo** [comment]
When I open up a tiff file, it only shows a few attributes.  I have some images which have extensive provenance metadata.  How do you access them?

eg:
  NITF_CSEXRA_SENSOR=PAN
  NITF_PIAIMC_SENSNAME=QB02
  ...

**Comment by jhamman** [comment]
@ebo - I think your issue falls more in line with what was discussed in #1582. Can you read over that issue and perhaps comment there?

**Comment by scollis** [comment]
Hey Devs and Users... Just about to embark on a project where I want to populate an X-Array data set with a set of images.. Did this progress? Just trying to save an hour building my own hook to skimage

**Comment by ebo** [comment]
On Jun 22 2018 10:10 AM, Scott wrote:
> Hey Devs and Users... Just about to embark on a project where I want
> to populate an X-Array data set with a set of images.. Did this
> progress? Just trying to save an hour building my own hook to skimage

I have not built hooks into skimage.  If you get that to work I would 
if you could share with me 8-)  I'm not fully sure of how to make that 
work in production, but I would be glad to help test.

**Comment by dschneiderch** [comment]
I am looking at using xarray for managing image data. it looks like the equivalent of an xr.open_image hasn't been developed so consider this a vote in favor 👍
