### ISSUE TITLE
extract values at nearest point with multidimensional latitude and longitude field

### ISSUE THREAD

**Issue by jinhuanz** [pydata/xarray#1325]
How do I extract values at a specific latitude and longitude point when latitude/longitude values are 2-D array?

I have a dataset with the following coordinates:

> Dimensions:              (x: 6165, y: 5801)
> Coordinates:
>   * y                    (y) float64 0.0 3e+03 6e+03 9e+03 1.2e+04 1.5e+04 ...
>   * x                    (x) float64 0.0 3e+03 6e+03 9e+03 1.2e+04 1.5e+04 ...
>     latitude             (y, x) float64 10.16 10.17 10.17 10.18 10.19 10.19 ...
>     longitude            (y, x) float64 78.99 79.01 79.03 79.05 79.08 79.1 ...

I want to extract value for at a specific latitude and longitude point and the exact latitude/longitude value is not in the coordinates. Then I started with calculate the distance between two point on Earth, and then get the (x_idx, y_idx) by minimize the distance. However, CPU and time costing is a result because of the large size of data.

I'm wondering is there any other ways could make it less costing?

**Comment by shoyer** [comment]
The right solution is to use a KDTree. We've discussed possible syntax for this in https://github.com/pydata/xarray/issues/475 but nobody has implemented it yet. Russ Rew wrote a nice overview article on using KDTree in http://www.unidata.ucar.edu/blogs/developer/entry/accessing_netcdf_data_by_coordinates
