### ISSUE TITLE
Add 'count' as option for how in dataset resample

### ISSUE THREAD

**Issue by czr137** [pydata/xarray#1327]
All of the usual aggregations are included in `resample`, but 'count' is missing.
At present, `how='count'` fails because the function doesn't accept the kwarg `skipna` that is being passed to it.

**Comment by darothen** [comment]
I saw your PR #1328 on this, but just a heads up that there is an open issue #1269 and pull-request #1272 to re-factor the resampling API to match the GroupBy-like API used by pandas. `count()` works without any issues on my feature branch.

I've been extremely busy but can try to carve out some more time in the near future to settle some remaining issues on that PR, which would resolve this issue too.

**Comment by czr137** [comment]
Thanks for the heads-up @darothen. I browsed the issues to make sure I wasn't duplicating anything, but I must have overlooked the pull request you mentioned.
I have used a lambda function in the interim, so it is no issue if this addition waits until your pull-request is merged in.
