### ISSUE TITLE
Functions for converting to and from CDAT cdms2 variables

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#133]
Apparently CDAT has a number of useful modules for working with weather and climate data, especially for things like computing climatologies (related: #112). There's no point in duplicating that work in xray, of course (also, climatologies may be too domain specific for xray), so we should make it possible to use both xray and CDAT interchangeably. 

Unfortunately, I haven't used CDAT, so it not obvious to me what the right interface is. Also, CDAT seems to be somewhat difficult (impossible?) to install as a Python library, so it may be hard to setup automated testing.

CC @DamienIrving

**Comment by aashish24** [comment]
:+1: @DamienIrving others, let us know if you need any help! This is really awesome stuff.

**Comment by shoyer** [comment]
@aashish24 This has been in the last few xray releases -- I'd love to get some feedback on it, I don't think it's gotten much use yet (I don't use cdat).

**Comment by aashish24** [comment]
Sure..we will give it a try soon and report back. I guess what would help is some documentation and may be a blog. What you think?

**Comment by shoyer** [comment]
This is technically documented, but barely :)
http://xray.readthedocs.org/en/stable/generated/xray.DataArray.from_cdms2.html#xray.DataArray.from_cdms2
http://xray.readthedocs.org/en/stable/generated/xray.DataArray.to_cdms2.html#xray.DataArray.to_cdms2

See here for a minimal example of converting to a cdms2 variable:
https://github.com/xray/xray/blob/eed58d5cb4274f262e77277bc8fcf394a9fae77c/xray/test/test_dataarray.py#L1272
