### ISSUE TITLE
Deprecate indexing with non-aligned DataArray objects

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1333]
Currently, we strip labels from DataArray arguments to `[]` / `.loc[]` / `.sel()`/ `.isel()`. But this will break when we finally add indexing with alignment (https://github.com/pydata/xarray/issues/974).

We could start raising deprecation warnings now so users can stop relying on this functionality that will change.

**Comment by jhamman** [comment]
@shoyer / @fujiisoup  - can this be closed now?

**Comment by shoyer** [comment]
Yes, we decided not to do this.
