### ISSUE TITLE
Chunking and dask memory errors

### ISSUE THREAD

**Issue by pwolfram** [pydata/xarray#1338]
What is the standard way of sub-chunking to prevent dask memory errors?   For large dataset files there could be a dimension, say `nCells`, that is large enough to fill RAM.  If this occurs, is there an automatic mechanism to prevent out-of-memory errors in dask or is the user's responsibility to specify maximum chunk sizes on their own?

**Comment by shoyer** [comment]
Currently it's the user's responsibility to choose appropriate chunk sizes for their workflow and available memory. Dask doesn't provide any functionality to help with this, though perhaps it could. You might raise an issue on the Dask issue tracker.

**Comment by pwolfram** [comment]
Thanks @shoyer.  This is what I was thinking but I just wanted to double check.  Feel free to close the issue if you would like- I'll move this to dask issues.
