### ISSUE TITLE
Some XArray key names don't group nicely

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#1343]
Some XArray loading functions provide keys that don't adhere to dask conventions used for naming.  

We can solve this in XArray by using names like `'load-' + dask.base.tokenize(stuff)` or in dask by trying to identify and avoid names like these.  It might be wise to attempt both.  I expect that this will be easier to solve in XArray (though that's also in my own self interest :))

![image](https://cloud.githubusercontent.com/assets/306380/24522302/26575ca2-155d-11e7-98cc-f4a7108a2249.png)

**Comment by shoyer** [comment]
Yes, this would be easy to fix, e.g., by setting `name_prefix='open_dataset-'` on this line:
https://github.com/pydata/xarray/blob/f2a50158beba112e521548bea63fdf758b327235/xarray/backends/api.py#L250

In my defense, I think this code predates dask naming conventions ;).

**Comment by mrocklin** [comment]
Yeah, also in your defense I don't think we've ever documented them :)
