### ISSUE TITLE
Dask Persist

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#1344]
It would be convenient to load constituent dask.arrays into memory as dask.arrays rather than as numpy arrays.  This would help with distributed computations where we want to load a large amount of data into distributed memory once and then iterate on the full xarray dataset repeatedly without reloading from disk every time.

We can probably solve this from either side:

1.  XArray could make a `.persist` method that replaced all of its dask.arrays with a persisted version of that array

```python
import dask

dset.x, dset.y, dset.z = dask.persist(dset.x, dset.y, dset.z)
```

2.  We could look into the Dask duck type solution again https://github.com/dask/dask/pull/1068

cc @shoyer @jcrist @rabernat @pwolfram

**Comment by shoyer** [comment]
I'm happy with either or both of these solutions.

**Comment by rabernat** [comment]
since we already have `.load()`, I think adding `.persist()` directly to xarray is the simplest way to go. Ideally xarray users should be able to avoid interacting directly with the dask api. (It's a beautiful api, don't get me wrong! but new users are easily overwhelmed by multiple interacting packages.)

**Comment by mrocklin** [comment]
We do eventually want to support some sort of duck typing.  This way people can do things like the following while still benefiting from shared intermediates:

    x, y, z = dask.persist(my_df, my_arrray, my_xarray)

But this may not happen as quickly as a `.persist` method.  Also we've added `.persist` to the Base dask collections class, so it's part of the standard dask API at this point.

**Comment by rabernat** [comment]
In this example, are x, y and z dask objects or xarray objects?

**Comment by shoyer** [comment]
> In this example, are x, y and z dask objects or xarray objects?

I think the idea is that they are mixed types, e.g., a dask-dataframe, a dask-array and an xarray Dataset or DataARray.
