### ISSUE TITLE
Creating a 2D DataArray

### ISSUE THREAD

**Issue by JoyMonteiro** [pydata/xarray#1351]
Hello,

I think I'm missing something simple here. I tried looking at the documentation, but no luck.
I'm trying to create DataArrays whose coordinates are two dimensional as follows

```python
from xarray import DataArray
import numpy as np

x_physical = DataArray(np.ones((2,2)),
                       dims = ['x_logical', 'y_logical'])

y_physical = DataArray(np.ones((2,2)),
                       dims = ['x_logical', 'y_logical'])

new_array = DataArray(np.zeros((2,2)), dims=['x_logical','y_logical'], coords=[x_physical, y_physical])
```
trying to follow the multidimensional example in the docs.

This gives me a 
ValueError: 'x_logical' has more than 1-dimension and the same name as one of its dimensions ('x_logical', 'y_logical'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.

I have tried multiple variants of this:

* replace ``x/y_logical`` in the arguments to creating ``new_array`` with something else, which gives me a
ValueError: dimensions ('x',) must have the same length as the number of data dimensions, ndim=2

and some other variants which in hindsight make no sense.

Is there something I'm missing, and is creating multidimensional DataArrays documented somewhere?

TIA,
Joy

**Comment by JoyMonteiro** [comment]
Also, I recall this is new functionality. What minimum version must I use to use 2D coordinates? That is, once I get the right syntax, that is ;)

**Comment by rabernat** [comment]
There is no such thing as a "multidimensional DataArray" in the xarray data model. DataArrays can have "non-dimension coordinates" which can be used for things like grouping. 

This would work
```python
new_array = DataArray(np.zeros((2,2)), dims=['x_logical','y_logical'])
new_array.coords['x_physical'] = x_physical
new_array.coords['y_physical'] = y_physical
new_array.groupby('x_physical').mean()
```

I don't know how to do this as a one-liner. Probably easier to create a Dataset rather than DataArray for this purpose
```python
ds = xr.Dataset({'testdata': (('y_logical', 'x_logical'), np.zeros((2,2)))},
                 coords={'x_physical': (('y_logical', 'x_logical'), np.ones((2,2))),
                         'y_physical': (('y_logical', 'x_logical'), np.ones((2,2)))})
```

**Comment by JoyMonteiro** [comment]
Thanks, Ryan. This is for CliMT, where the model arrays are DataArrays, so it would not make sense to use a Dataset. I think option 1 will make more sense.

**Comment by rabernat** [comment]
Why not combine all your model arrays into a single Dataset? Since they almost certainly share coordinates, this would make sense.

**Comment by JoyMonteiro** [comment]
The DataArrays we use are a thin wrapper over xarray's to allow conversion into desired units. If we used Dataset, then we lose this functionality unless we subclass Dataset too. Overall, using a simple dictionary suits our purposes better.
