### ISSUE TITLE
concat automagically outer-joins coordinates

### ISSUE THREAD

**Issue by j08lue** [pydata/xarray#1354]
I would like to concatenate two netCDF files that have `float64` coordinate variables. I thought the coordinate values were the same, but in fact they differ by something in the order of `1e-14`. 

Using `open_mfdataset` or `concat` to merge the datasets, I get a completely different output shape than the two input files have.

This is because `concat` is somewhere performing an outer join on the coordinates. Now I am wondering where else in my workflows this might happen without my notice...

It would be awesome if there was an option to change this behaviour on `concat`, `open_mfdataset`, and `auto_combine`. I would actually rather make these functions **fail if any dimension other than the concatenation dimension differs**.

Note: This could also be a special case, because
```python
>>> (ds1.lon == ds2.lon).all()
<xarray.DataArray 'lon' ()>
array(True, dtype=bool)
```
while
```python
>>> (ds1.lon.values == ds2.lon.values).all()
False
```

Maybe an interface change could be considered together with that discussed in #1340?

**Comment by shoyer** [comment]
This only happens in `concat`.

`merge`, which happens automatically in many operations, e.g., to decide which coordinates propagate, has different behavior: it automatically drops conflicting coordinate values.

Anyways, I agree: we should try to make this more explicit. We might still keep the "magical" version of concat around, but we should certainly expose the fully explicit version as public API.

**Comment by shoyer** [comment]
https://github.com/pydata/xarray/pull/1330 will help, in so far as it adds a `join='exact'` option that can disable automatic alignment. We would just need to make the `join` argument used internally in `align` inside `xarray.concat` part of the public API for concat.

**Comment by wqshen** [comment]
I also have this problem.

I have a list of dataset with all same shaped array at different time, while each have a different coordinate. (Each dataset is centered in the tropical cyclone center, with a same radius width buffer.)

I use xr.concat to concat them along time dimension, this function auto outer-joins coordinates, which makes the final dataset have a larger-shape, but i just want the original dataset shape.

Any solution ?

**Comment by darothen** [comment]
@wqshen, a workaround until a more complete modification to `align` is available would be to explicitly copy/set the coordinate values on your arrays before using `xr.concat()`. Alternatively, if it's as simple as stacking along a new tailing axis, you could stack via dask/numpy and then construct a new `DataArray` passing the coordinates explicitly.

**Comment by shoyer** [comment]
I think the right solution here is to relabel the coordinates on each of the datasets that you are concatenating. The alternative behavior here is xarray raising an error in the case of conflicting coordinate labels.

**Comment by j08lue** [comment]
Thanks for reminding me, stalte bot, this is still relevant to me. 

I think your proposed solution @shoyer would solve this issue perfectly: expose `align`'s `join` parameter in the `concat` function - and please also in `open_mfdataset`. Would you like a PR for this?

**Comment by shoyer** [comment]
Sure, we would welcome a PRs for this.
