### ISSUE TITLE
Bug: open_dataarray does not pass properly its parameters to open_dataset

### ISSUE THREAD

**Issue by NotSqrt** [pydata/xarray#1359]
Hi,

There's now a `autoclose` parameter to the `open_dataset` function.
But `open_dataarray` uses positional arguments only, so now the arguments are no longer at their place, and `engine`, for instance, can't be specified.

Thanks !

**Comment by shoyer** [comment]
Indeed, this is unfortunate -- thanks for the report!

We'll probably issue a bug fix release soon to fix this and a few other issues that have come up with v0.9.2.

CC @pwolfram
