### ISSUE TITLE
Move/read coordinate as data variable - xarray.Dataset 

### ISSUE THREAD

**Issue by acocac** [pydata/xarray#1369]
Hi,
I just started to use xarray as part of my geospatial analyses. I just wonder if there is an option in xarray.Dataset to move certain items assigned as coordinates to data variables. 

<xarray.Dataset>
Dimensions:     (accuracy: 41, classes: 41, data: 41, pattern: 41, repetition: 41, score: 41, wsizes: 41)
Coordinates:
  * score       (score) float64 0.1306 0.3237 0.3688 0.4264 nan 0.3835 ...
  * wsizes      (wsizes) int64 4 4 4 4 4 4 7 7 7 7 7 7 10 10 10 10 10 10 13 ...
  * classes     (classes) |S5 '5-9' '1-5-9' '1-5-9' '1-5-9' '5-9' '5-9' ...
  * pattern     (pattern) |S1 'l' 'c' 'g' 'f' 'r' 'd' 'd' 'c' 'f' 'l' 'g' ...
  * repetition  (repetition) int64 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 ...
  * accuracy    (accuracy) float64 0.9584 0.9053 0.868 0.8519 0.9943 0.8467 ...
  * data        (data) float64 0.9584 0.9053 0.868 0.8519 0.9943 0.8467 ...
Data variables:
    *empty*

I use xarray.Dataset from a dictionary and even some items from the dictionary were correctly read as coordinates, others items weren't such as "accuracy" and "score".

Thank you.

**Comment by spencerahill** [comment]
Sounds like [http://xarray.pydata.org/en/stable/generated/xarray.Dataset.reset_coords.html#xarray.Dataset.reset_coords](Dataset.reset_coords) is what you're looking for.

**Comment by max-sixty** [comment]
Closing, please reopen for any flups
