### ISSUE TITLE
Dataset.combine_first() coordinates attribute

### ISSUE THREAD

**Issue by dimitryx2017** [pydata/xarray#1373]
Hi guys!

Thanks for the great job you are doing!

Here is a possible bug in the `Dataset.combine_first()` method (I'm using xarray 0.9.2 with Python 3.5.2). 

The Dataset/DataArray coordinates are correctly treated if specified without commas, e.g. (as seen with ncdump):  ``MyVar:coordinates = "alt lat lon" ; ``.  In this case _lon, lat_, and _alt_ are recognized as the Dataset's (and its DataArrays') `.coords`.

However, the `Dataset.combine_first() `method only treats coordinates correctly if specified with commas, i.e., `MyVar:coordinates = "alt, lat, lon"`.

**Comment by shoyer** [comment]
The `coordinates` attribute should only matter when you're reading data from disk, so I'm a little mystified about how this could come up. I don't think we interpret the comma separated form, unless that's read as `["alt,", "lat,", "lon,"]`.

Can you come up with a simple, reproducible example?
