### ISSUE TITLE
open_mfdataset and add time dimension

### ISSUE THREAD

**Issue by snowman2** [pydata/xarray#1380]
I am working with the Grib2 format and the time is buried in the attributes of the variables:
```python
import pandas as pd
import xarray as xr

path_to_file = 'hrrr.t01z.wrfsfcf00.grib2'
with xr.open_dataset(path_to_file, engine='pynio') as xd:
    print(pd.to_datetime(xd['TMP_P0_L1_GLC0'].attrs['initial_time'], format="%m/%d/%Y (%H:%M)"))
```

I would like to take advantage of how to use the concatenation methods here:
http://xarray.pydata.org/en/stable/io.html#id6

However, there is currently no time dimension. Is there a way to concatenate the files together while adding a new time dimension and variable? Will this use dask arrays?

**Comment by spencerahill** [comment]
open_mfdataset has a 'concat_dim' optional keyword argument where you can specify the name of a new dimension that you want to concatenate your files over.  You can read more about this in the [API reference on open_mfdataset](http://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html#xarray.open_mfdataset).

You could then overwrite the coordinate of that new dimension with your desired time coordinate.
Does that help?

**Comment by shoyer** [comment]
You can use the `preprocess` argument to `open_mfdataset` to create a new dimension from the attribute value.

**Comment by snowman2** [comment]
Thank you @spencerahill and @shoyer. That was brilliant.

Here is the solution:
```python
path_to_files = '*.grib2'
def extract_date(ds):
    for var in ds.variables:
        if 'initial_time' in ds[var].attrs.keys():
            return ds.assign(time=pd.to_datetime(ds[var].attrs['initial_time'],
                                                 format="%m/%d/%Y (%H:%M)"))

with xr.open_mfdataset(path_to_files,
                       concat_dim='time',
                       preprocess=extract_date,
                       engine='pynio') as xd:
    print(xd)
```
