### ISSUE TITLE
Verify xarray works with bottleneck 1.2

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1401]
This is somewhat time sensitive:
https://github.com/kwgoodman/bottleneck/issues/168

**Comment by fmaussion** [comment]
Looks good to me: https://travis-ci.org/pydata/xarray/jobs/230642161

(see the test-bn-master branch)

**Comment by shoyer** [comment]
@fmaussion can you make a PR adding this as an optional build to our test matrix?

**Comment by fmaussion** [comment]
Sure. Have to go now but will do that later today
