### ISSUE TITLE
.equals() on a coordinate takes attributes into comparison

### ISSUE THREAD

**Issue by chunweiyuan** [pydata/xarray#1420]
Is the following the right behavior?
```
>>> da = xr.DataArray(range(3), [('x', range(2000, 2003))])
>>> ws = xr.DataArray([1 for i in range(3)], [('x', range(2000, 2003))])
>>> da.coords['x'].equals(ws.coords['x'])
True
>>> da['some_attr'] = 0
>>> da.coords['x'].equals(ws.coords['x'])
False
```
I'm just trying to see if the coordinates are the same, but somehow the dataarray's attribute becomes part of the comparison.  I'd expect that in `.identical()`, but not in `.equals()`.

**Comment by shoyer** [comment]
`da['some_attr'] = 0` sets a non-dimension coordinate, not an attribute, so this is working as intended. Though I can see why we might want to change `.equals()` to ignore these: `x.equals(y)` is generally intended to be equivalent to `(x == y).all()`.

**Comment by chunweiyuan** [comment]
I'm just having a hard time wrapping my head around the definitions here.  `da['some_attr'] = 0` sets a point coordinate, and this point coordinate shows up in `da.coords`, but not `da.dims`, because `da.dims` only pertains to indexing coordinates.  Why is this point coordinate attached to every other coordinate then?  In other words, why would `da.coords['x']` contain `some_attr` as well?

Somehow it just doesn't feel right intuitively for some point dimension to mess up my comparison between two 1-D coordinates, but I might be missing some important use cases here.

**Comment by shoyer** [comment]
> Why is this point coordinate attached to every other coordinate then? In other words, why would da.coords['x'] contain some_attr as well?

The rule we currently use to propagate coordinates is to keep all other coordinates whose dimensions are contained in the dimensions of the coordinate, i.e., coordinates are presumed to describe not only the data-array, but an entire shared coordinate system. This is the same rule we use for choosing which coordinates to put on a DataArray when indexing a Dataset.

I'm certainly open to alternatives if we can find a simple way to express this.

**Comment by chunweiyuan** [comment]
This is getting close to the fundamental paradigm of xarray.  Would it entail some massive code migration (and user protests) if we change how we express `da.coords['x']`(by removing point coordinates)?

I'm thinking of a new API that compares only the values and indexing coordinates between two objects, but struggle to come up with a simple, descriptive name........

**Comment by shoyer** [comment]
If the new rule significantly better, then breaking changes are certainly possible (in a major release). But for bars should be high: it needs to be worth potential turmoil when users update their code.

For example, we could argue that `x.equals(y)` should be equivalent to `bool((x == y).all())` (aside from NaNs), and note that in the docs.

I'm not sure what rule we could use for dropping scalar coordinates in particular. Adding an exception to the rules for only scalar coordinates would be a non-starter. The only alternative rule that seems at all sensible is that indexed coordinates only have the minimal set of coordinates (i.e., equivalent to calling `.reset_coords(drop=True)`).
