### ISSUE TITLE
Huge memory use when using FacetGrid

### ISSUE THREAD

**Issue by mangecoeur** [pydata/xarray#1424]
When plotting a time series of maps using faceting, my memory use jumps by  over 3x, from about 4GB to 14GB.

Using macOS, Python 3.6, xarray 0.9.5, jupyter notebook.

**Comment by fmaussion** [comment]
How many maps? 

I don't think that xarray can do much about this problem though...

**Comment by mangecoeur** [comment]
16 maps, although like you say, I'm not sure if this is coming from xarray or matplotlib

**Comment by rabernat** [comment]
Is your xarray dataset chunked?

**Comment by shoyer** [comment]
You're using cartopy? If you're plotting a basemap of some sort, that might make a large difference in the memory usage.

A full code example would certainly be heplful here.

**Comment by mangecoeur** [comment]
Dataset isn't chunked, and yes I am using cartopy to draw coastlines following the example in the docs:

```python
p = heatwaves_pop.plot(x='longitude', y='latitude', col='time', 
                       col_wrap=3, cmap='RdBu_r', vmin=-v_both, vmax=v_both,
                    size=2,
                 subplot_kws=dict(projection=crs.PlateCarree())
                      )
for ax in p.axes.flat:
    ax.coastlines()
```

where `heatwaves_pop` is calculated from a bunch of other xarray datasets. What surprised me was that they should all have been loaded into memory so I did not expect further increase in memory use.
