### ISSUE TITLE
inconsistent behavior in stack/unstack along one dimension

### ISSUE THREAD

**Issue by d-chambers** [pydata/xarray#1431]
I am using Ubuntu 16, python 3.6, and xarray 0.9.1

A DataArray can be stacked along one dimension, but when unstack is called a ValueError is raised. It seems that either unstack should work, or calling stack should also raise a ValueError.  

```python
import xarray as xr

dims = ['a', 'b']
coords = {'a': range(2), 'b':range(2)}
values = [[0, 0], [0, 0]]

dar = xr.DataArray(values, coords, dims)

stacked = dar.stack(z=('a',))  # this works

unstack = stacked.unstack('z')  # this raises ValueError

```

**Comment by fujiisoup** [comment]
Hi @d-chambers

I am currently working for more consistent `MultiIndex` behaviour in #1412 .
I will take a look also for `stack`-`unstack` behavior.

**Comment by shoyer** [comment]
Agreed, this does seem inconsistent. Thanks for the report!

**Comment by mathause** [comment]
This works with current master - so it can probably be closed? @d-chambers? (I think there is a error in the example - shouldn't it be `unstack = stacked.unstack('z')`?)

**Comment by d-chambers** [comment]
Yes, fixed the example. This seems to be fixed now, closing. Thanks again!
