### ISSUE TITLE
v0.9.6 release

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1441]
I plan to issue this in within the next few days, after merging #1260 (Rasterio support) and #1439 (pydap fix). Let me know if there's anything else critical to get in.

CC @pydata/xarray

**Comment by shoyer** [comment]
Done! See http://xarray.pydata.org/en/stable/whats-new.html

**Comment by fmaussion** [comment]
Any roadmap for the next major release? Will this be a ``0.10.0`` then?

**Comment by shoyer** [comment]
So far, I've been saving major version numbers for breaking changes. But they are also useful to signal large advances in functionality, even if they don't break compatibility.
