### ISSUE TITLE
Should an `apply` method exist for `DataArray` similar to the definition for `Dataset`?

### ISSUE THREAD

**Issue by pwolfram** [pydata/xarray#1450]
The method `apply` is defined for `Dataset`.  Is there a design reason why it is not defined for `DataArray`?  In general I think it would be good to have calculation methods apply to both `Dataset` and `DataArray` as possible but am thinking I'm missing a key design element here.

**Comment by fmaussion** [comment]
Probably a duplicate of https://github.com/pydata/xarray/issues/1074 ?

**Comment by shoyer** [comment]
Yes, see discussion in #1074

**Comment by pwolfram** [comment]
Thanks @fmaussion and @shoyer, sorry about the duplicated issue...
