### ISSUE TITLE
writing datasets derived from netCDF4 with compression fails

### ISSUE THREAD

**Issue by matt-long** [pydata/xarray#1458]
When I read a file with netCDF4 compression into a Dataset, a subsequent call to write the dataset using `to_netcdf` fails.

For instance, using data from the POP model, I can convert output to netCDF4 using NCO
```
$ ncks --netcdf4 --deflate 1 $file nc4-test.nc
```

Then in Python:
```
ds = xr.open_dataset('nc4-test.nc',decode_times=False,decode_coords=False)
ds.to_netcdf('test-out.nc')
```

The write fails with: 
```
  File "netCDF4/_netCDF4.pyx", line 2263, in netCDF4._netCDF4.Dataset.createVariable (netCDF4/_netCDF4.c:18764)
  File "netCDF4/_netCDF4.pyx", line 3235, in netCDF4._netCDF4.Variable.__init__ (netCDF4/_netCDF4.c:31564)
RuntimeError: NetCDF: Bad chunk sizes.
```
If I include `format = NETCDF3_64BIT`, the write completes.

This seems like a bug.

Example dataset: ftp://ftp.ucar.edu/pub/cgd/mclong/misc/nc4-test.nc

**Comment by shoyer** [comment]
Thanks for the report, I can reproduce this behavior, so I'm marking this as a bug. For completeness I've attached your file below:
[test-out.nc.zip](https://github.com/pydata/xarray/files/1082186/test-out.nc.zip)

**Comment by shoyer** [comment]
This looks related to https://github.com/pydata/xarray/issues/1225

**Comment by shoyer** [comment]
This works now
