### ISSUE TITLE
Dataset.to_dataframe loads dask arrays into memory

### ISSUE THREAD

**Issue by Zac-HD** [pydata/xarray#1462]
`to_dataframe` should return a Dask Dataframe, instead of eagerly loading data.  This is probably pretty easy to implement ([thanks to dask](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.from_dask_array)), but will require some care to ensure that no intermediate results (or indices!) are loaded.  We should also check the `to_series` method.

**Comment by jmunroe** [comment]
Today, I find myself in need exact functionality.  Assuming no one else is working on it, I'll give a shot at trying to fix this.

**Comment by shoyer** [comment]
Closing this in favor of https://github.com/pydata/xarray/issues/1093
