### ISSUE TITLE
Dataset.rename shouldn't complain when the name-dict re-uses column names.

### ISSUE THREAD

**Issue by newt0311** [pydata/xarray#1477]
Consider what happens when somebody does ds.rename({'a': 'b', 'b': 'a'}). The current rename code will throw an error even though this operation is completely well defined and the current rename implementation actually handles this case correctly (except for the bad sanity check).

What this function should really check for is the there are no name collisions in the resulting dataset.

Currently we have the following code (in: [dataset.py:1527](https://github.com/pydata/xarray/blob/master/xarray/core/dataset.py#L1527)): `if v in self and k != v`

I propose that we replace it with `if name in variables` just before line 1541 with an appropriate throw.

There is one problem that this can cause: right now, it is possible to overwrite variables silently. For example ds.rename({'a': 'd', 'b': 'd'}) will work and silently drop one of the columns (assuming 'd' doesn't exist in ds). My proposed changes will make the rename function throw in this case. I think the new behavior is "more correct" especially since the column dropped is pretty much random if the name_dict is a normal dictionary and the person can always use a del or something. However it is not backwards compatible which might be a concern.

Thoughts?

Thanks.
-- PG

PS. xarray is great. Thanks for writing it.

**Comment by shoyer** [comment]
Yes, these both sound like bugs and should be fixed. I don't see any use case for `ds.rename({'a': 'd', 'b': 'd'})` as I'm breaking it (I think it should already give an error).

A pull request to fix these would be greatly appreciated!

**Comment by newt0311** [comment]
I'll submit one later today.

-- PG.

**Comment by newt0311** [comment]
PR submitted.

FWIW: I was only able to find this bug thanks to [hypothesis](http://hypothesis.works/). I was testing my own code when this bug popped up in my tests. If I get time I'll see if I can add in some tests myself.

-- PG.
