### ISSUE TITLE
Time Dimension, Big problem with methods 'groupby' and 'to_netcdf'

### ISSUE THREAD

**Issue by rpnaut** [pydata/xarray#1480]
My problem is that I would like to use the easy functionality of the xarray-library in python, but I run into problems with the time dimension in case of aggregating data and in case of writing netcdf.
I am using pandas version 0.17.1 and xarray 0.9.6.

I have opened a dataset, which contains daily data over the year 2013:  `datset=xr.open_dataset(filein).`

The contents of the file are:
```
<xarray.Dataset>
Dimensions:       (bnds: 2, rlat: 228, rlon: 234, time: 365)
Coordinates:
  * rlon          (rlon) float64 -28.24 -28.02 -27.8 -27.58 -27.36 -27.14 ...
  * rlat          (rlat) float64 -23.52 -23.3 -23.08 -22.86 -22.64 -22.42 ...
  * time          (time) datetime64[ns] 2013-01-01T11:30:00 ...
Dimensions without coordinates: bnds
Data variables:
    rotated_pole  |S1 ''
    time_bnds     (time, bnds) float64 1.073e+09 1.073e+09 1.073e+09 ...
    ASWGLOB_S     (time, rlat, rlon) float64 nan nan nan nan nan nan nan nan ...
Attributes:
    CDI:                       Climate Data Interface version 1.7.0 (http://m...
    Conventions:               CF-1.4
```
When I use now the groupby method to compute the monthly means, the time dimension is destroyed:

```
datset.groupby('time.month').mean('time')
<xarray.Dataset>
Dimensions:    (bnds: 2, month: 12, rlat: 228, rlon: 234)
Coordinates:
  * rlon       (rlon) float64 -28.24 -28.02 -27.8 -27.58 -27.36 -27.14 ...
  * rlat       (rlat) float64 -23.52 -23.3 -23.08 -22.86 -22.64 -22.42 -22.2 ...
  * month      (month) int64 1 2 3 4 5 6 7 8 9 10 11 12
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (month, bnds) float64 1.074e+09 1.074e+09 1.077e+09 1.077e+09 ...
    ASWGLOB_S  (month, rlat, rlon) float64 nan nan nan nan nan nan nan nan ...

```

Now I have instead of a time dimension a month dimension with values from 1 to 12. Is this a side effect of the 'mean' - function? As long as i do not use this mean function, the time variable is retained.

The examples given in the documentation seems to have a different behaviour. That is, the timestamps are retained and the first date of each month is used.

It seems to be impossible to reinvent my old time dimension. 

- Method A: I have tried to create my own time variable with `endresult.assign_coords(time=pd.date_range(start='2013-01',end='2014-01',freq='M'  ` . That perfectly gives me a new coordinate with the correct dates. Afterwards, I have to swap the dimensions from month to time. It was only possible by changing the dimension of the coordinate 'time' to the dimension of the coordinate 'month'. However, the netcdf file contained wrong dates as output, i.e. values from 1 to 12. Thus the first time step was at 31-January 2013 and the next one day later and the next one day later and so on. If I add the attributes 'calendar' and 'units' to the time-coordinate, then the output seems to be correct but type int64 is not readable by programs like ncview.
- Method B: Create the own time variable by using pandas and then converting the datetime64-dates to the usual python datetime-object. Further, the datetime-object is converted to numbers with the netcdf4.datetime.date2num method. Further, I assign this numbers to the time-coordinate and add the encoded attributes for units and calendar. However, the encoded units are not writen to the netcdf-data. So I have to add them with an external program like ncatted.

How to improve method A und B in order to have a correct time stamp in my nc-file.

**Comment by byersiiasa** [comment]
As far as I know I can imagine this is the intended functionality.

> The examples given in the documentation seems to have a different behaviour. That is, the timestamps are retained and the first date of each month is used.

I cannot find where this is the case, apart from when using `.resample`. Could you put a link to the doc page?

The issue is perhaps more with the example that you present (of only 1 year data) and expected behaviour. Normally groupby('time.month') would be applied to multiple years of data. i.e. group data by month and find the monthly averages for Jan-Dec for 30 years of data, e.g. a climatology.

And so in this case it absolutely makes sense to keep the months as 1 to 12, or something similar (perhaps 'Jan','Feb'etc). Applying a datestring of the first day of the month wouldn't make sense because which year would you choose when you have 30 years of data?

If you do want a time series of monthly means, then `.resample` is the function you want and it will give you the datestamps in the format that you desire.

**Comment by jhamman** [comment]
@rpnaut - @byersiiasa is correct. It sounds like you want 

```Python
datset.resample('MS', dim='time', how='mean')
```

The month labels (`1, 2, 3, ...`) come from pandas TimeGrouper and this is functionality we will want to keep around.

**Comment by rpnaut** [comment]
You are so right. I did not realize that there is the resample method, which hopefully can also be combined with the 'apply' functionality. 
The documentation I mentioned was from "nicolasfauchereau.github.io/climatecode/posts/xray" (look at In[24] and In[25]. As I understand he is getting monthly data out of groupby-method and in his example the "time" survives. It seems to be that the functionality of groupby-month changed during the years, because the groupby-method in Nicolas's example did not aggregate same calendar month to one time stamp.

**Comment by rabernat** [comment]
> As I understand he is getting monthly data out of groupby-method and in his example the "time" survives. It seems to be that the functionality of groupby-month changed during the years, because the groupby-method in Nicolas's example did not aggregate same calendar month to one time stamp.

There has been no change in xarray's groupby behavior. Nicolas' example would work with today's code. When you call `datset.groupby('time.month').mean('time')`, you remove the time dimension by aggregating over it. If you had applied a different (non-reducing) function to the group (e.g. `datset.groupby('time.month').apply(lambda x : x**2)`, you would preserve the time dimension.
