### ISSUE TITLE
Matrix cross product in xarray

### ISSUE THREAD

**Issue by peteron30** [pydata/xarray#1484]
Hi 
I am  new to xarray and need some advice on one task. I need to do a cross product calculation using variables from a netcdf file and write the output to a new netcdf file. I feel this could be done using netcdf-python and pandas, but I hope to use xarray to simplify the task. My code will be something like this:
ds = xr.open_dataset(NC_FILE)
var1 = ds['VAR1']
var2 = ds['VAR2']
var3 = ds['VAR3']
var4 = ds['VAR4']

var1-4 above will have dimensions [latitude, longitude]. I will use var1-4 to generate a matrix of dimensions [Nlat, Nlon, M], something like: [var1, var1-var2, var1-var3, (var1-var2)*np.cos(var4)] (here, M=4).

My question here is, how do I build this matrix in xarray Dataset? Since this matrix will be eventually used to cross product with another matrix (pd.DataFrame) of dimensions [M, K], is it better to convert var1-4 to pd.DataFrame first?

Following code will be like this:
matrix =  [var1, var1-var2, var1-var3, (var1-var2)*np.cos(var4)] # Nlat x Nlon x M
factor = pd.read_csv(somefile) # M x K
result = pd.DataFrame.dot(matrix,factor) # Nlat x Nlon x K
result2 = xr.Dataset(result)
result2.to_netcdf(outfile)

Can someone show me the correct code to build the Nlat x Nlon x M matrix? Can the cross product be done in xr.Dataset to avoid conversion to and from pd.DataFrame?

Thank you,
Xin

**Comment by shoyer** [comment]
To combine variables in a list into a new xarray object, you need to call `xarray.concat` on them, e.g., `xarray.concat([var1, var1-var2, var1-var3, (var1-var2)*np.cos(var4)], 'new_dim')`.

**Comment by peteron30** [comment]
Thanks. the result dataarray from xr.concat keeps the same name as var1, although it is in fact a new dataarray object. How can this be fixed?
The name disappear after applying an bool index using where method.

**Comment by shoyer** [comment]
.rename('new_name') on the combined array is probably the simplest.

**Comment by peteron30** [comment]
How do I make dot product (np.dot or pandas.dataframe.dot) between two DataArrays?
X has dimensions [dim_0, dim_1, dim_2], Y has dimensions [dim0, dim3].
result should have dimensions [dim_1, dim2, dim3].
result = np.dot(X,Y) 
OR, result = pd.DataFrame.dot(X,Y)
In both cases, error "shapes are not aligned" occurred.

**Comment by peteron30** [comment]
Just saw xr.DataArray.dot(). PROBLEM SOLVED.
