### ISSUE TITLE
`axis` keyword ignored when applying `np.squeeze` to `DataArray`

### ISSUE THREAD

**Issue by tondieker** [pydata/xarray#1487]
Thank you all for creating xarray, I'm a new user and I love it! 

I believe I came across a bug. It appears the axis keyword is ignored when applying `np.squeeze` to a `DataArray`. Here is an illustration:

```
import numpy as np
import xarray as xr

test = np.random.random((1,10,1))
np.squeeze(test, axis=0).shape
# (10, 1)
np.squeeze(xr.DataArray(test), axis=0).shape
# (10,)
np.__version__
# '1.13.0'
xr.__version__
# '0.9.6'
```

**Comment by shoyer** [comment]
This is (somewhat) expected. Basically, you should use the `DataArray.squeeze()` method instead.

The long story is that some but not all NumPy functions define themselves by (attempting) to call methods, e.g., `np.squeeze(array)` -> `array.squeeze()`.

`squeeze` is a special and somewhat surprising case. [Apparently](https://github.com/numpy/numpy/blob/v1.13.0/numpy/core/fromnumeric.py#L1143-L1201) `np.squeeze(array, axis)` -> `array.squeeze(axis)` -> `array.squeeze()` if the `axis` argument isn't handled. But we didn't bother to define an `axis` argument for `DataArray.squeeze()`, so this results in an error.

I suppose we could fix this by defining an `axis` argument, like we do for some methods like `.mean()`. But the short answer is that using xarray methods should be preferred.

**Comment by tondieker** [comment]
Yes, I did realize there are workarounds and `DataArray.squeeze()` is the preferred one. 

In my mind this is a kind of incompatibility problem and it would be nice to fix this. I had existing numpy code, and later decided to add dimension and coordinate labels using `xarray`. I was under the impression that `xarray.DataArray`s behave the same as `numpy.ndarray`s when applying numpy functions, so that I didn't have to change any of my code. 

At least for `np.squeeze` this is not the case. Perhaps there are other functions for which a similar issue arises. If you don't think this kind of compatibility is desired then it would be good to address this in the documentation.

**Comment by shoyer** [comment]
>  I was under the impression that xarray.DataArrays behave the same as numpy.ndarrays when applying numpy functions, so that I didn't have to change any of my code.

We do attempt to make this work when feasible, but unfortunately it isn't always the case. In this case I do think this is doable, so I'm marking this issue as "Contributions welcome."

**Comment by floriankrb** [comment]
Yes, @shoyer is right : Looking at the numpy code, this array.squeeze(axis) -> array.squeeze() is happening. 
```
1256     try:                                                                                                                                                                                                                                 
1257         # First try to use the new axis= parameter                                                                                                                                                                                       
1258         return squeeze(axis=axis)                                                                                                                                                                                                        
1259     except TypeError:                                                                                                                                                                                                                    
1260         # For backwards compatibility                                                                                                                                                                                                    
1261         return squeeze()    
```

I added the `axis` parameter in xarray and this fixed the problem.


```
PYTHONPATH=$HOME/sandbox/dev/xarray python -c 'import numpy as np ; import xarray as xr ; test = np.random.random((1,10,1)) ; print(np.squeeze(test, axis=0).shape); print(np.squeeze(xr.DataArray(test), axis=0).shape, np.__version__, xr.__version__) '
(10, 1)
(10, 1)      1.13.1     0.10.0+dev64.gd554ece

```
