### ISSUE TITLE
Bug or not?  Loading netcdf into xr.DataArray is in bytes

### ISSUE THREAD

**Issue by jolespin** [pydata/xarray#1501]
I wrote a wrapper to construct `xr.DataArrays`, it is loading as bytes?  Is there a way to avoid this?

![image](https://user-images.githubusercontent.com/9061708/28943718-ab1ae468-7854-11e7-9dcb-ac99bbe0b552.png)

**Comment by shoyer** [comment]
1. Are you using python 2 or 3?
2. Are you using scipy or netCDF4 to read/write this data? (The default engine changes depending upon which you have installed)

**Comment by jolespin** [comment]
I'm using Python 3.6.2 and the newest stable Xarray.  I left the engine as the default.  Is there an engine that will load the strings in unicode? Thanks

**Comment by shoyer** [comment]
I'm not 100% sure it will work properly here, but try installing the netCDF4-Python library: http://unidata.github.io/netcdf4-python/

The default engine is scipy if you don't have netcdf4 installed. And unfortunately scipy is somewhat hampered by the lack of a single byte (ASCII) string dtype in NumPy, so it uses bytes for everything.

We could (and perhaps should) potentially fix this in a wrapper on the xarray side. It was easy to ignore these issues back when most people were using Python 2 but that's no longer the case.
