### ISSUE TITLE
A problem about xarray.concat

### ISSUE THREAD

**Issue by wqshen** [pydata/xarray#1505]
Hi, today i use xr.concat to concat my wrf model splitted netcdf datasets, in this model output data, it typically has two kinds of meshgrid, includes one stagged meshgrid and mass meshgrid, different variables have located on the different kind of grid.

For example, below is some variables in a dataset, some have dimension `west_east` and other take `west_east_stag`,
```
    MAPFAC_M               (Time, south_north, west_east) float32 1.06697 ...
    MAPFAC_U               (Time, south_north, west_east_stag) float32 1.06697 ...
    MAPFAC_V               (Time, south_north_stag, west_east) float32 1.06698 ...
    MAPFAC_MX              (Time, south_north, west_east) float32 1.06697 ...
    MAPFAC_MY              (Time, south_north, west_east) float32 1.06697 ...
    MAPFAC_UX              (Time, south_north, west_east_stag) float32 1.06697 ...
    MAPFAC_UY              (Time, south_north, west_east_stag) float32 1.06697 ...
    MAPFAC_VX              (Time, south_north_stag, west_east) float32 1.06698 ...
    MF_VX_INV              (Time, south_north_stag, west_east) float32 0.937228 ...
    MAPFAC_VY              (Time, south_north_stag, west_east) float32 1.06698 ...
```
i want concat along dimension `west_east` and `west_east_stag`, so that these piece of datasets can be concatenate fully. When i use xr.concat to concatenate these datasets,  the argument `dim` can just use one dimension ?

Is it possible to concat with multiple independent dimensions, like following,
```python
xr.concat([ds_col_0, ds_col_1, ds_col_2], dim=['west_east', 'west_east_stag'])
```

**Comment by darothen** [comment]
How exactly is your WRF output split? It's not clear exactly what you want to do... is it split along different tiles such that indices [1, ..., m] are in `ds_col_0`, [m+1, ..., p] are in `ds_col_1`, and [p+1, ..., n] are in `ds_col_2`? Or is each dataset a different vertical level? Or a different timestep?

I'm not sure that `xr.concat` will even work if you pass **dim** a list of dimensions. It's only designed to concatenate along one dimension at a time; if you pass a pandas Index or a DataArray as the argument for **dim**, then it will create a new dimension in the dataset and use the values in that argument as the coordinates - so you have to exactly match the number Datasets or DataArrays in the first argument.

**Comment by wqshen** [comment]
Yeah, what i want is exactly you've understood, these files are splitted in space into many tiles. 
When i look into the internal `xarray.concat` code, i also found it is impossible at present. 
To do this, some codes should be modified and i don't think this function extension is necessary to `xarray`.

Also, thanks to you !
