### ISSUE TITLE
Support for basic math (multiplication, difference) on two xarray-Datasets

### ISSUE THREAD

**Issue by rpnaut** [pydata/xarray#1506]
Lets assume one has loaded two datasets 'datmod' and 'datref' containing daily data over one year. Data look like:

``` Dimensions:       (bnds: 2, rlat: 228, rlon: 234, time: 365)
Coordinates:
  * rlon          (rlon) float64 -28.24 -28.02 -27.8 -27.58 -27.36 -27.14 ...
  * rlat          (rlat) float64 -23.52 -23.3 -23.08 -22.86 -22.64 -22.42 ...
  * time          (time) datetime64[ns] 2013-01-01T11:30:00 ...
Dimensions without coordinates: bnds
Data variables:
    rotated_pole  |S1 ''
    time_bnds     (time, bnds) float64 1.073e+09 1.073e+09 1.073e+09 ...
    ASWGLOB_S     (time, rlat, rlon) float64 nan nan nan nan nan nan nan nan ... 
```

Now I want to compute a more complex metric as the temporal correlation and combine it with the functionality of groupby or resample, i.e. determine the temporal correlation for each month seperately. So, starting with
```
def anomaly(x):
    return x - x.mean('time')

a = datref.groupby('time.month').apply(anomaly)
b = datmod.groupby('time.month').apply(anomaly)
```
gives me the anomalies for each time step with respect to monthly means. However, for the nominator of the correlation (the denominator is not discussed here) the elementwise multiplication is needed:
```
corr = a*b 
```
and later on this product is grouped monthly and averaged over time. The problem is that the product 'a*b' gives an dataset with missing variables
```
<xarray.Dataset>
Dimensions:  (rlat: 228, rlon: 234, time: 0)
Coordinates:
  * time     (time) datetime64[ns] 
  * rlon     (rlon) float64 -28.24 -28.02 -27.8 -27.58 -27.36 -27.14 -26.92 ...
  * rlat     (rlat) float64 -23.52 -23.3 -23.08 -22.86 -22.64 -22.42 -22.2 ...
Data variables:
    month    (time) int64 
``` 

I can overcome the problem by doing something like `corr=a[varname].data - b[varname.data]`. But then I have an numpy.array which does not support groupby- and aggregation-functionality, i.e. I must clone the dataset 'datmod' and replace all the data with data of 'corr'. Then I can use again Dataset-aggregation functionality.

Is there a way to overcome the problem of elementwise multiplication (as well as subtraction) or should such a feature be added in the future?

**Comment by shoyer** [comment]
Elementwise operations are supported between datasets, but only on aligned coordinates. In this case, it looks like there is no overlap for the "time" labels on each dataset -- maybe the dates are the same but the times differ slightly?

**Comment by rpnaut** [comment]
A first check of your theory (shoyer) reveals that if the time stamps are exectly the same, i.e. the date and the time is equal for each time step in the two netcdf-files, then the operation is working sucessfully. 

I think it is very consequent to allow elementwise operations only on datasets with not only the same shape of dimensions and coordinates but also with the same values for dimensions, spatial coordinates and times. I only have to find a way to harmonize both datasets for time values prior operations with xarray ( a hard task considering model and evaluation data).

**Comment by shoyer** [comment]
> A first check of your theory (shoyer) reveals that if the time stamps are exectly the same, i.e. the date and the time is equal for each time step in the two netcdf-files, then the operation is working sucessfully.

Glad that worked!

> I only have to find a way to harmonize both datasets for time values prior operations with xarray ( a hard task considering model and evaluation data).

We have a few tools that might be useful here:
- Resampling: http://xarray.pydata.org/en/stable/time-series.html#resampling-and-grouped-operations
- Nearest neighbor lookups with `reindex`: http://xarray.pydata.org/en/stable/indexing.html#nearest-neighbor-lookups
