### ISSUE TITLE
open_dataset leading to NetCDF: file not found

### ISSUE THREAD

**Issue by kthyng** [pydata/xarray#1510]
Hi all. I have been using xarray.read_dataset(url) to read in netCDF model output from a thredds server in a script run every 30 minutes for months now. It normally works unless there is something wrong with the url. However, in the last few days, it cannot find the file anymore even though when I read it in with netCDF4, it works.

loc = 'http://barataria.tamu.edu:8080/thredds/dodsC/NcML/oof_archive_agg'
import netCDF4 as netCDF
d = netCDF.Dataset(loc)  # this works
import xarray as xr
ds = xr.open_dataset(loc)  # this doesn't work as of the last couple of days

This is a problem on both my Linux workstation (xarray version 0.9.5, Python 3.5.2) and my Mac (xarray version 0.9.6, Python 3.5.0rc4). Anyone have an idea what could have changed here?

**Comment by ocefpaf** [comment]
Something is not OK when parsing `ocean_time`.

If you do d['ocean_time'][:] on your example with netCDF4 you'll get the same error as `xarray`.

**Comment by petacube** [comment]
Kristen, i had opened your threads dataset with panoply and tried to plot variables
it opens dataset ok but when it queries it gives me an error about ocean time variable
so nothing to do with xarray or dask - its data got corrupted somehow

**Comment by petacube** [comment]
if you pick up variable which does not have ocean_time as dimension
panoply plots ok and i would expect dask/xarray will work fine that too. 

so maybe you want to explicitly query for variable(s) not connected to ocean_time. 

also talk to provider of the dataset and tell them the something wrong with ocean_time dimension. 


Stanislav

**Comment by kthyng** [comment]
Huh! Weird! I had tried accessing a particular value of `u` with netCDF as a test and it had worked fine and hadn't worried about it after that. I just now tried `ocean_time` and it works for particular indices (like `d['ocean_time'][0]`), but as you said doesn't work if I put in `d['ocean_time'][:]`.

Thanks for everyone's help, I'll work on the thredds end of things.
