### ISSUE TITLE
Question: dask array indexing + replacing values

### ISSUE THREAD

**Issue by hurricanemolina** [pydata/xarray#1518]
Thank you all for all you do with xarray, it is incredibly helpful. 

I have a question and am a relatively new user so please correct me if I am misunderstanding concepts below:

Currently, I want to replace the dask array values for a dataset variable in a dimension (`u`) with values of another data array of appropriate shape:

`random_diff.diffs.values[u,:,:] = temp_diff`

But believe that the dataset dask array is being loaded into memory when I do above -- which is in a loop where my max `u` is 20,000 -- so this takes some time since it seems to be reloading with every `u`. 

I have tried to `concat` the values into a new dataset instead of replacing, but it gets slowed down as `u` grows in size. `update` is a dataset method and don't quite understand how/if that would help here.

My current solution is to convert the dask array values into regular numpy arrays and then do the index value updating loop. Is there a way to do this that I am not familiar with and without having to load the numpy array into memory?

Here is an example of what I would like to do:

`diffs = np.zeros((self.n_samples, init_data_to_file.shape[1], init_data_to_file.shape[2]))`
`random_diff = xr.Dataset({'diffs': (['time','x','y'], diffs)})`
`for u in xrange(self.n_samples):`
`    ...computations...`
`    random_diff.diffs.values[u,:,:] = temp_diff`

Here is what I am currently doing:

`data_to_file = np.asarray(init_data_to_file)`
`diffs = np.zeros((self.n_samples, data_to_file.shape[1], data_to_file.shape[2]))`
`for u in xrange(self.n_samples):`
`...computations...`
`diffs[u,:,:] = temp_diff`

**Comment by shoyer** [comment]
Indeed, you can't update the values of dask arrays with indexing.

Try `dask.array.stack()` (or `xarray.concat` on xarray objects) for a way to stack a list of dask arrays into a new dask array, e.g., `dask.array.stack(self.n_samples * [temp_diff], axis=0)`, supposing you've constructed `temp_diff` as a dask array.

**Comment by hurricanemolina** [comment]
Will try them out -- Thank you very much for your suggestions.
