### ISSUE TITLE
Pass arguments to dask.compute()

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#1523]
I work with a very large dask-based algorithm in xarray, and I do my optimization by hand before hitting compute(). In other cases, I need using multiple dask schedulers at once (e.g. a multithreaded one for numpy-based work and a multiprocessing one for pure python work).

This change proposal (which I'm happy to do) is about accepting \*args, \*\*kwds parameters in all .compute(), .load(), and .persist() xarray methods and pass them verbatim to the underlying dask compute() and persist() functions.

**Comment by shoyer** [comment]
Yes, this sounds like a great idea to me!

**Comment by crusaderky** [comment]
Working on it now

**Comment by jhamman** [comment]
@crusaderky - did you make any progress here? I also have a feature branch that I started on the plane a few days back...

**Comment by crusaderky** [comment]
@jhamman I finished the implementation I have to write the unit tests this weekend

**Comment by crusaderky** [comment]
@jhamman 's implementation is far more complete than mine, I pass the trophy :)
