### ISSUE TITLE
Index variables loaded from dask can be computed twice

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1533]
as reported by @crusaderky  in #1522

**Comment by crusaderky** [comment]
Still valid in xarray 0.13

```python
import xarray
import numpy
import dask.array

def kernel():
    print("Kernel invoked!")
    return numpy.array([100, 200])

data = dask.array.Array(name='foo', dask={('foo', 0): (kernel, )}, chunks=((2,),), dtype=float)
ds = xarray.Dataset(coords={'z': ('z', data)})
```
output:
```
Kernel invoked!
Kernel invoked!
```

**Comment by dcherian** [comment]
Nice example!

I tracked this down to
1. `as_variable` being called when extracting the index. This seems sensible.
    https://github.com/pydata/xarray/blob/21705e61503fb49f000186c0d556e5623bd5ac82/xarray/core/merge.py#L413-L420
2. `as_variable` being called again in the `expand_variable_dicts` call in `merge_core` (should be avoided):
https://github.com/pydata/xarray/blob/21705e61503fb49f000186c0d556e5623bd5ac82/xarray/core/merge.py#L493-L497

We need to replace the appropriate objects in `aligned` with IndexVariables from `indexes` if `indexes is not None`.

**Comment by shoyer** [comment]
We should probably merge my merging refactor before doing much more on
this...

**Comment by dcherian** [comment]
Haha I thought it was already in!

**Comment by dcherian** [comment]
Adding 
``` python
if not isinstance(coords, Frozen):
    coords.update(indexes)
```
before the `merge_core` call fixes this. Not sure if its right.

https://github.com/pydata/xarray/blob/283b4feba601e9838ed538106b2091d0b8264c77/xarray/core/merge.py#L455-L462
