### ISSUE TITLE
Need small updates of docs

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1541]
found some outdated parts in docs

+ In FAQ related to [pandas N-dimensional panel](http://xarray.pydata.org/en/stable/faq.html#why-is-pandas-not-enough)
It is deprecated and the description may be better to change.

+ In FAQ related to [Zendo](http://xarray.pydata.org/en/stable/faq.html#how-should-i-cite-xarray)
The link of the badge is outdated.

**Comment by shoyer** [comment]
Agreed, these do need updating!

**Comment by Zac-HD** [comment]
I'll take this one on 😄 

I've also spotted a few things in the sphinx config that could be updated - adding Numba to the intersphinx mapping, pointing at python /3/ instead of /3.5/ docs, using ISO8601 date formats - and will keep an eye out for others.
