### ISSUE TITLE
Testing: Failing tests on py36-pandas-dev

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#1542]
We currently have 7 failing tests when run against the pandas development code ([travis](https://travis-ci.org/pydata/xarray/jobs/270511674)).

Question for @shoyer - can you take a look at these and see if we should try to get a fix in place prior to v.0.10.0? It looks like Pandas.0.21 is slated for release on Sept. 30.

**Comment by shoyer** [comment]
It looks like two issues here:

-[ ] Something related to `resample`
-[ ] Something related to `isnull`/`isna`

I'll start digging when we I have time. Let's mark this as a 0.10 blocker for now, until we figure out what's going on.

**Comment by MaximilianR** [comment]
potentially (but supposed to be warnings only) https://github.com/pandas-dev/pandas/pull/16972

**Comment by shoyer** [comment]
Fixes for both of these are up for review in #1548 and #1549.

**Comment by jhamman** [comment]
closed via #1548 and #1549.
