### ISSUE TITLE
exit code 137 when using xarray.open_mfdataset

### ISSUE THREAD

**Issue by jamesstidard** [pydata/xarray#1561]
While using the `xarray.open_mfdataset` I get a `exit code 137 SIGKILL 9` killing my process. I do not get this while using a subset of the data though. I'm also providing a chunks argument.

Does anyone know what might be causing this? Could it be the computer is completely running out of memory (RAM + SWAP + HDD)? Unsure what's causing this as I get no stack trace just the `SIGKILL`.

Thanks.

**Comment by jhamman** [comment]
@jamesstidard -

Can you provide something closer to a ["minimum, complete, verifiable example"](https://stackoverflow.com/help/mcve). As it is, any number of things could be causing the problem you describe.

**Comment by shoyer** [comment]
Running out of memory seems like the most likely culprit to me, at least if you're running a recent version of xarray (we used to have some issues with insufficient locking when reading HDF5 files).

Try opening a smaller number of files to see if that gives any clues.

**Comment by jamesstidard** [comment]
Increasing the chunk sizes seemed to resolve this issue. I was loading readings over time on the world as 360x180xT was tryin to rechunk them to 1x1xT.
