### ISSUE TITLE
0.8.2 incompatible with pandas 0.20.1 ?

### ISSUE THREAD

**Issue by kefirbandi** [pydata/xarray#1563]
This issue may be related to #1386   

I hope this part of the stacktrace is sufficient to demonstrate my point:

File "C:\src\validation\main\risk_reporting\data_access\db_model.py", line 246, in get_data
    ds = ds.groupby('pvshort').apply(select_latest_pv)
  File "C:\Anaconda2\lib\site-packages\xarray\core\common.py", line 345, in groupby
    return self.groupby_cls(self, group, squeeze=squeeze)
  File "C:\Anaconda2\lib\site-packages\xarray\core\groupby.py", line 226, in __init__
    unique_values, group_indices = unique_value_groups(group, sort=sort)
  File "C:\Anaconda2\lib\site-packages\xarray\core\groupby.py", line 34, in unique_value_groups
    inverse, values = pd.factorize(ar, sort=sort)
  File "C:\Anaconda2\lib\site-packages\pandas\core\algorithms.py", line 552, in factorize
    values = _ensure_arraylike(values)
  File "C:\Anaconda2\lib\site-packages\pandas\core\algorithms.py", line 166, in _ensure_arraylike
    values = lib.list_to_object_array(values)
TypeError: Argument 'obj' has incorrect type (expected list, got DataArray)

**Comment by fmaussion** [comment]
xarray V0.8.2 was released on Aug 19, 2016 and pandas v0.20.1 on May 5, 2017

Any reason why you need to stick to 0.8.2?

**Comment by kefirbandi** [comment]
Actually I just saw that the requirement for xarray 0.8.2 is: pandas >= 0.15.0, I don't know whether it is possible to specify: 0.19.1>=pandas>=0.15.0.

Just ran into this issue when wanted to install packages for some newcomers in our company.

But actually we solved the issue by adding strict version requirement for both xarray and pandas. (We need these versions because we have some pickled files using these formats which we need to read. Until I find the time to get rid of them.)

**Comment by fmaussion** [comment]
xarray's development is independent from pandas', and at the time xarray v0.8.2 was released (2016), nobody could predict what going to happen with pandas in 2017.

So yes, if you need to stick to v0.8.2, strict version requirement is the only way to go.

**Comment by fmaussion** [comment]
To address your pickle issue you might consider one of the other serialization options for xarray data structures, for example NetCDF: http://xarray.pydata.org/en/stable/io.html#netcdf
