### ISSUE TITLE
Allow rasterio_open to be used on in-memory rasterio objects? 

### ISSUE THREAD

**Issue by cwerner** [pydata/xarray#1575]
After I open and reproject a GTiff to WGS84 I want to place the bands into a xarray Dataset object. As I try to reduce disc writes as possible I work with a rasterio in-memory object.

As far as I can see it is currently not possible to pass a rasterio In-Memory object to the rasterio_open function, right? Is there a workaround for this or du I have to build the dataset from scratch?

If it's currently not possible I'd like to suggest this as a future addition.

[and thanks for your great xarray module]

**Comment by jhamman** [comment]
This is not currently supported but could be. Similar functionality was recently added to the netCDF4-python backend in #1508.
