### ISSUE TITLE
Support for unsigned data

### ISSUE THREAD

**Issue by forman** [pydata/xarray#1579]
The "old" NetCDF 3 format doesn't have explicit support for unsigned integer types and therefore a recommendation/convention exists to set the variable attribute `_Unsigned='true'`, see NetCDF docs, section [Unsigned Data](http://www.unidata.ucar.edu/software/netcdf/docs/BestPractices.html#bp_Unsigned-Data).

Are there any plans to interpret the `_Unsigned` attribute?

I'd really like to help out, but I fear I still don't know enough about dask to provide an efficient PR for that. 

My workaround is to manually convert the variables in question which are of type `int8`, same data as mentioned in #1576:

    unsigned_var = signed_int8_var & 0xff

which results in an `int16`, which is ok but still 1 byte more than the desired `uint8`.

**Comment by jhamman** [comment]
Didn't https://github.com/pydata/xarray/pull/1453 add this?

**Comment by forman** [comment]
Yes, so this is a duplicate of https://github.com/pydata/xarray/issues/1444, sorry!

When can we expect 0.9.7 with the fix?

**Comment by shoyer** [comment]
We are trying to get everything together for a big 0.10 release, so it will be a bit longer. I don't have a timeframe yet, but hopefully in a week or two!
