### ISSUE TITLE
Rasterio tags are not accessible through open_rasterio

### ISSUE THREAD

**Issue by maaleske** [pydata/xarray#1582]
# The problem
When opening an ENVI file directly using rasterio, (some) metadata from the header file is available through `tags()`:
```python
import rasterio
src = rasterio.open(file)
src.tags() # dict of metadata for the whole array
src.tags(1) # same for band 1
```
Opening the same file through `open_rasterio`, the metadata is not carried through to the returned DataArray, neither as attributes nor as coordinates (which is the use case I'm interested in, since the metadata usually contains corresponding wavelengths for the bands).

## Solutions?
I don't know what kind of data `tags()` might contain in general. For my use case, parsing the tags for each band as coordinates is necessary at some point. It might be better generally if the tags are stored as an attribute and munged afterwards, but this is complicated by the fact that there's tags for the whole file as well as for separate bands.

**Comment by fmaussion** [comment]
Note that the rasterio object is available via the (undocumented) ``_file_obj`` attribute. So a quick workaround for you would simply be:

```python
ds = xr.open_rasterio(file)
ds._file_obj.tags()
```
This makes me wonder if it wouldn't be easier for xarray to make the ``file_obj`` public API and don't care about all the possible special cases...

@shoyer @jhamman thoughts?

**Comment by jhamman** [comment]
> I don't know what kind of data tags() might contain in general.

I'm not apposed to decoding the values that are in tags as part of the rasterio backend. @maaleske, perhaps you can do some research to let us know what types of values the tags method is going to return.

@fmaussion - I'm not entirely apposed to this. It may require a bit of effort to make sure modifying the file object as part of the public API doesn't do nasty things.

**Comment by maaleske** [comment]
@jhamman, I did some looking around. The rasterio [documentation on tags](https://mapbox.github.io/rasterio/topics/tags.html) does not reveal much and points to the only slightly less unhelpful [GDAL data model documentation](http://www.gdal.org/gdal_datamodel.html). There seem to be both namespaces containing file format specific data, and general namespaces which contain data parsed from the format specific namespaces. The format namespaces/domains are mentioned in the [GDAL raster format documentation](http://www.gdal.org/frmt_various.html), but don't really tell much of the type of data stored.

For ENVI files, there seems to already be three different kinds of return values depending on the exact call:

 - `tags()`  returns a dict full of strings created from the wavelength info in the header file:
   `{'Band_1':'450 nm', 'Band_2':'452', ..., 'wavelength_units':'nm'}`

 - `tags(b)` returns a dict containing the info for the band `b` in a slightly different format: 
   `{'wavelength':450.00, 'wavelength_units':'nm'}`

 - `tags(ns='ENVI')` returns a dict of string values, containing all the fields in the header file in their original form:
   ```python
   {'Description':'file.dat', 
    'wavelength':'{450, 452, ...}', 
    'fwhm':'{3.0, 3.0, ...}',
    etc.}
   ```
 -  Other namespaces I tried seemed to return only empty dicts.

It's a bit puzzling why only the wavelength information (and not even the corresponding FWHM info) is parsed to the default namespace, given that it's not listed as having any well defined semantics in the GDAL docs.

**Comment by jhamman** [comment]
This is still a bit confusing. Maybe we should open a discussion/issue with the rasterio team.

**Comment by maaleske** [comment]
Had some more time to look at this. It seems rasterio just passes the the info returned by GDAL, since looking at the files using gdalinfo reveals exactly the same data (with only wavelengths parsed for each band, etc). Apparently gdalinfo can (since GDAL 1.11) also list the available metadata domains (namespaces) in the file, or output all the metadata given the domain 'all'. These don't seem yet to be implemented in rasterio.
