### ISSUE TITLE
Equivalent of numpy.insert for DataSet / DataArray?

### ISSUE THREAD

**Issue by willirath** [pydata/xarray#1596]
Is there a simple way of inserting, say, a time-step in an `xarray.DataArray`?

## Background

I have a year of gridded daily data with a few missing time steps. Each existing time step is represented by a file on disk.  (To be specific: For 2016, there should be 366 files, but there are only 362.) In many cases, it would be nice to be able to just add masked data whereever a day is missing from the original data.

**Comment by darothen** [comment]
@willirath is your time data equally spaced? If so, you should be able to use the new version of `DataArray.resample()` available on the master (and scheduled for the 0.10.0 release) which supports upsampling/infilling. 

Should work something like this, assuming each timestep is a daily value on the **time** axis:

``` python
ds = xr.open_mfdataset("paths/to/my/data.nc")

ds_infilled = ds.resample(time='1D').asfreq()
```

That should get you nans wherever your data is missing.

**Comment by willirath** [comment]
Does exactly what I need.  Thanks!

**Comment by willirath** [comment]
Shoud I provide a minimal real-world-example?

**Comment by darothen** [comment]
@willirath Never hurts!

**Comment by willirath** [comment]
Not really minimal but shows a real use:
 
> ```python
> from pathlib import Path
> import matplotlib.pyplot as plt
> import xarray as xr
> 
> # create data path
> daily_data_path = Path("/obs_data/") / "ASCAT" / "v1.x.x" / "data/Daily/Netcdf"
> 
> # get data files and open mf dataset
> data_files_2016 = daily_data_path.glob("2016/??/??/*.nc")
> raw_data_set = xr.open_mfdataset(data_files_2016).isel(latitude=300,
>                                                        longitude=0)
> 
> # Resample with filling gaps by NaN's and shift to match original time axis
> infilled_data_set = raw_data_set.resample(time="1D").asfreq()
> infilled_data_set.time.data += (raw_data_set.time.data[0] -
>                                 infilled_data_set.time.data[0])
> 
> # extract wind speeds
> rws = raw_data_set.wind_speed
> iws = infilled_data_set.wind_speed.rename("resampled_wind_speed")
> 
> # and plot (with a slight offset to be able to distinguish the lines)
> 
> fig, ax = plt.subplots(2, 1)
> 
> (iws+1).plot(ax=ax[0]);
> rws.plot(ax=ax[0]);
> ax[0].legend(["resampled", "original"], loc=0, ncol=2);
> 
> (iws+1).sel(time=slice("2016-08-01", "2016-10-01")).plot(ax=ax[1]);
> rws.sel(time=slice("2016-08-01", "2016-10-01")).plot(ax=ax[1]);
> ```
> 
>  ![infilled_resample](https://user-images.githubusercontent.com/5700886/30932359-86ca9d9e-a3c7-11e7-981f-2ada466545e9.png)
> 
> Note the gaps that are more clearly visible in the lower panel.
