### ISSUE TITLE
Add _ipython_key_completions_ to xarray.Dataset

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1628]
We could use to enable autocompletion for dictionary access like `ds['temp` -> `ds['temperature']`
http://ipython.readthedocs.io/en/stable/config/integrating.html#tab-completion

**Comment by fujiisoup** [comment]
Oh. It is what I have been looking for!

xarray's attribute-like data access, e.g. `ds.temperature`, was introduced for the purpose?
This type of data access is convenient but sometimes conflicts to the original attributes, e.g. `T` cannot be accessed like this.

Can we gradually deprecate this after implementing `_ipython_key_completions_()`?

**Comment by fujiisoup** [comment]
I am trying to implement this inside `AttrAccessMixin` class.
I am wondering if the following is a designed behavior.

```python
In [1]: import xarray as xr
   ...: da = xr.DataArray([0, 1, 2], dims=['x'], attrs={'foo': 'brabra'})
   ...: da
   ...: 
Out[1]: 
<xarray.DataArray (x: 3)>
array([0, 1, 2])
Dimensions without coordinates: x
Attributes:
    foo:      brabra

In [2]: da.foo
Out[2]: 'brabra'
```

An attribute `foo` can be accessed only by attribute-style, but not `__getitem__` style, `da[foo]`.

**Comment by shoyer** [comment]
> This type of data access is convenient but sometimes conflicts to the original attributes, e.g. T cannot be accessed like this.

The Dataset `T` property for transpose should be deprecated -- but that's a separate matter:
https://github.com/pydata/xarray/issues/1232

> Can we gradually deprecate this after implementing _ipython_key_completions_()?

I am hesitant to deprecate this since it is so widely used. But you're right that this serves the main use cases.

> An attribute foo can be accessed only by attribute-style, but not `__getitem__` style, `da[foo]`.

That's correct. Attribute-style access was always intended as fall-back for convenience purposes, but `__getitem__` (for programmatic access) is intentionally stricter.

**Comment by fujiisoup** [comment]
> That's correct. Attribute-style access was always intended as fall-back for convenience purposes, but __getitem__ (for programmatic access) is intentionally stricter.

OK.
Sent a PR.
