### ISSUE TITLE
Option to include units in .plot()

### ISSUE THREAD

**Issue by jbusecke** [pydata/xarray#1630]
I find myself editing the label on the colorbar of xarray plots often to include the units of the plotted variable.
Would it be possible to extract the value of DataArray.attrs['units] (if present) and add it to the colorbar label?

Given an example DataArray with name='temperature' and attrs['units']='deg C', the current colorbar label says 'temperature'.

A 'plot_units' keyword could possibly be used like this for example:

```python
da.plot(plot_units=True)
```
Then the colorbar label should be 'temperature [deg C]'.

**Comment by dcherian** [comment]
Can be closed.

**Comment by fujiisoup** [comment]
closed via #2151
