### ISSUE TITLE
seaborn.apionly module is deprecated

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#1633]
Xarray is using the apionly module from seaborn which is now raising this warning:

```Python
...python3.6/site-packages/seaborn/apionly.py:6: UserWarning: As seaborn no longer sets a default style on import, the seaborn.apionly module is deprecated. It will be removed in a future version.
  warnings.warn(msg, UserWarning)
```

I think the only places we use seaborn are here:

https://github.com/pydata/xarray/blob/2949558b75a65404a500a237ec54834fd6946d07/xarray/plot/utils.py#L76-L87

This shouldn't a difficult fix if/when we decide to change it.

xref: https://github.com/mwaskom/seaborn/pull/1216

**Comment by shoyer** [comment]
This is a little annoying, but basically we just have to silence the warning here, with a fall-back to importing directly from seaborn.
