### ISSUE TITLE
Rasterio backend broken with rasterio=1.0a10

### ISSUE THREAD

**Issue by ceholden** [pydata/xarray#1641]
The latest alpha of rasterio (`1.0a10`) breaks the xarray backend (tested against `xarray=0.9.6`) because it expects either a `tuple` or `rasterio.windows.Window` passed as the `window` keyword argument to `read`. Tuples get converted to a `Window` in the latest alpha, but xarray currently passes the window as a list. Simply converting the window argument to a tuple fixes the backend ([see here for the fix I'm proposing](https://github.com/ceholden/xarray/commit/8dc7e748e1af273ed13f0d3dacc48a80e4741c21)).

Somewhat related, the CI services are currently testing against `rasterio=0.36` while this backend was originally tested against one of the 1.0 alphas. The cause is the `rasterio-feedstock` repo switched the development alpha releases to be distributed on the `conda-forge/label/dev` channel, instead of the regular `conda-forge` channel. Switching to the development channel for `1.0a10` should cause this issue to manifest itself on the CI services.

Happy to address these (and add to whats-new, etc) in the same or separate issues/PRs, depending on what you think makes sense. Thanks for all your work!

**Comment by jhamman** [comment]
@ceholden - thanks for looking into this. If you can open a PR with your proposed changes, we can iterate on the implementation there.

**Comment by fmaussion** [comment]
See [here](https://github.com/conda-forge/rasterio-feedstock/pull/36) for the discussion about rasterio's alpha releases

I'm not following rasterio's development cycle enough to understand what's going on, but the V1 alpha releases are out since such a long time that everybody is using them -- although they are still changing quite a lot, obviously.
