### ISSUE TITLE
da.plot.pcolormesh fails when there is a datetime coordinate

### ISSUE THREAD

**Issue by gerritholl** [pydata/xarray#1661]
`da.plot.pcolormesh`, where `da` is a `DataArray`, fails with `TypeError: invalid type promotion` when one of the coordinates is a datetime array:

```
$ cat mwe.py
#!/usr/bin/env python3.6

import xarray
import numpy

da = xarray.DataArray(
    numpy.arange(3*4).reshape(3,4),
    dims=("x", "y"),
    coords={"x": [1,2,3],
            "y": [numpy.datetime64(f"2000-01-{x:02d}")
                  for x in range(1, 5)]})

da.plot.pcolormesh()
$ ./mwe.py
Traceback (most recent call last):
  File "./mwe.py", line 13, in <module>
    da.plot.pcolormesh()
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/plot/plot.py", line 547, in plotmethod
    return newplotfunc(**allargs)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/plot/plot.py", line 500, in newplotfunc
    **kwargs)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/plot/plot.py", line 667, in pcolormesh
    primitive = ax.pcolormesh(x, y, z, **kwargs)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/matplotlib/__init__.py", line 1710, in inner
    return func(ax, *args, **kwargs)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5636, in pcolormesh
    coords = np.column_stack((X, Y)).astype(float, copy=False)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 353, in column_stack
    return _nx.concatenate(arrays, 1)
TypeError: invalid type promotion
```

**Comment by gerritholl** [comment]
I'm quite sure it worked in the past, but trying old versions of `xarray` yields the same error, so either my memory is wrong, or this started failing due to changes in dependencies.

**Comment by gerritholl** [comment]
Never mind, this is in matplotlib.  See https://github.com/matplotlib/matplotlib/issues/9577.

**Comment by gerritholl** [comment]
Actually, it isn't in matplotlib really.  It's xarrays responsibility after all.  To plot with pcolormesh, one needs to convert the date axis using datenum, see https://stackoverflow.com/a/27918586/974555 .  When plotting with xarray, that is out of control of the user, so there must be some step within xarray to prepare this.  What I still don't know is why my code (not this MWE, but my actual code) worked several months ago but not now.

**Comment by gerritholl** [comment]
The problem is triggered by a recent change in pandas.  I'm currently bisecting pandas to see where it is but it's a little slow due to the compilation at every step.

**Comment by gerritholl** [comment]
This happens after: https://github.com/pandas-dev/pandas/commit/2310faa109bdfd9ff3ef4fc19a163d790d60c645

**Comment by TomAugspurger** [comment]
Pandas used to register a matplotlib converter for datetimes on import. I’ll take a closer look in a bit.

**Comment by gerritholl** [comment]
@TomAugspurger  Is it [this one](https://github.com/pandas-dev/pandas/commit/2310faa109bdfd9ff3ef4fc19a163d790d60c645#diff-c9442f0523e6449da9fa54834fb120fcL9)?

**Comment by TomAugspurger** [comment]
Yep, that was the change.

The fix is to explicitly register the converters before plotting:

```python
from pandas.tseries import converter
converter.register()
```

**Comment by shoyer** [comment]
Thanks @gerritholl and @TomAugspurger for your help figuring this out.

See #1669 for a fix.
