### ISSUE TITLE
Could a DataArrayRolling object compute an arbitrary function on rolling windows?

### ISSUE THREAD

**Issue by ziofil** [pydata/xarray#1666]
What I'd like to do is something of this kind

#### Code Sample, a copy-pastable example if possible

```python
da = xr.DataArray(range(10))
r = da.rolling(dim_0=2)

def func(x, axis, **kwargs):
    return x/x[-1] # for example

# This is the desired functionality
generator = r.map(func)
func_on_window = generator.next() # each time this is called, the rolling object returns func(window,...)
```

#### Desired output
```python
generator.next()
# [0,1]
generator.next()
# [0.5,1]
generator.next()
# [0.6666...,1]
...
```

This would be extremely useful to pipe data directly into a neural network for instance.

**Comment by shoyer** [comment]
You can iterate through a rolling object as a generator, e.g.,
```
In [6]: for k, v in r:
   ...:     print(k.item(), v.values)
   ...:
0 [ True]
1 [0 1]
2 [1 2]
3 [2 3]
4 [3 4]
5 [4 5]
6 [5 6]
7 [6 7]
8 [7 8]
9 [8 9]
```
Does this help?

Note that something weird seems to be going on with the first time window. I don't know why it's a boolean. @jhamman any idea what's going on?

**Comment by jhamman** [comment]
@shoyer - this is really odd. Its probably coming from https://github.com/pydata/xarray/blob/master/xarray/core/rolling.py#L149-L150 but I don't remember exactly what/why we're trying to accomplish here.

**Comment by ziofil** [comment]
I didn't know I could just iterate through it! Thank you. It's very fast too.

**Comment by jhamman** [comment]
@ziofil - We don't support indexing on the rolling iterator at the moment. You could just grab the windows you want in this way:

```Python
w1 = 2
w2 = 7
for i, (k, v) in enumerate(r):
    if i > w1 and i <= w2:
        print(k.item(), v.values)

3 [2 3]
4 [3 4]
5 [4 5]
6 [5 6]
7 [6 7]
```

By the way, I think we'd be happy to see some feature development on this front if you are interested in developing the rolling objects out further.

**Comment by ziofil** [comment]
I'd love to, I can take a look at the code, but I'm afraid my skills are not up to the task yet...

**Comment by seth-p** [comment]
I think what is needed are `DataArrayRolling.apply` and `DatasetRolling.apply` (like `DataArrayGroupBy.apply` and `DatasetGroupBy.apply`). The problem with the `reduce` methods is that they are memory-inefficient.

**Comment by fujiisoup** [comment]
Maybe we need a better API similar to Groupby.apply, but it can be doable by [`construct` method](http://xarray.pydata.org/en/stable/generated/xarray.core.rolling.DataArrayRolling.construct.html#xarray.core.rolling.DataArrayRolling.construct) that gives another DataArray with windowed dimension attached to the last position. 

We can apply any function on this constructed DataArray.

**Comment by seth-p** [comment]
Separately, maybe `apply_ufunc` should accepts `Rolling` objects?

**Comment by seth-p** [comment]
The problem I have with `Rolling.construct` is the same that I have with `Rolling.reduce`: it's very (potentially) memory-inefficient.

**Comment by seth-p** [comment]
I think there are actually a couple different ways `Rolling.apply` could work, but this seems like one possible way:

```
from xarray.core.utils import maybe_wrap_array
from xarray.core.combine import concat


def rolling_apply(rolling, func, *args, **kwargs):
    applied = [maybe_wrap_array(label, func(arr, *args, **kwargs)) for label, arr in rolling]
    combined = concat(applied, dim=rolling.obj.coords[rolling.dim])
    return combined
```

**Comment by seth-p** [comment]
> construct method does not allocate that large array in memory. It uses the strided trick and therefore consumers only the order of 1000x1000x1000.

Ah. I didn't realize that. Good to know.

What I'm actually looking to do is a rolling weighted regression.  I have three DataArrays:
- observations, dims=('date', 'dim1', 'dim2')
- variables, dims=('date', 'dim1', 'dim2', 'var')
- weights, dims=('date', 'dim1', 'dim2')

I want to calculate a regression_coefficients DataArray with dims=('date', 'var'), where for each date it has the weighted regression coefficients calculated over the trailing N dates (over 'dim1' and 'dim2'). One way would be to put the three DataArrays in a Dataset, and then use a newly-defined `Dataset.rolling().apply()`. Another way would be to use an enhanced version of `apply_ufunc()` that can take `Rolling` objects. But now that I know that `DataArrayRolling.construct()` won't kill my machine, I'll try `apply_ufunc()` with the three `DataArrayRolling.construct()` objects. I'd welcome other suggestions.

**Comment by seth-p** [comment]
Also, the following code seems to do what I want:

```
def apply_func_rolling(func, *args, **kwargs):
    # determine rolling parameters, and remove them from kwargs
    apply_func_kwargs = {'input_core_dims', 'output_core_dims', 'vectorize', 'join', 'dataset_join',
                         'keep_attrs', 'exclude_dims', 'dataset_fill_value', 'kwargs', 'dask',
                         'output_dtypes', 'output_sizes'}
    min_periods = kwargs.pop('min_periods', None)
    center = kwargs.pop('center', False)
    dim = xr.core.utils.either_dict_or_kwargs(kwargs.pop('dim', None),
                                              {k: v for k, v in kwargs.items()
                                               if k not in apply_func_kwargs},
                                              'apply_func_rolling')
    if len(dim) != 1:
        raise ValueError("precisely one rolling dimension must be specified")
    rolling_dim = list(dim.keys())[0]
    kwargs.pop(rolling_dim)
    temp_rolling_dim = '__temp__{}__'.format(rolling_dim)
    # change input_core_dims rolling_dim values to temp_rolling_dim
    input_core_dims = kwargs.get('input_core_dims', None)
    if input_core_dims:
        kwargs['input_core_dims'] = [[(temp_rolling_dim if (dim_ == rolling_dim) else dim_)
                                      for dim_ in dims_] for dims_ in input_core_dims]
    # change exclude_dims rolling_dim values to temp_rolling_dim
    exclude_dims = kwargs.get('exclude_dims', None)
    if exclude_dims:
        kwargs['exclude_dims'] = [[(temp_rolling_dim if (dim_ == rolling_dim) else dim_)
                                   for dim_ in dims_] for dims_ in exclude_dims]
    # call apply_func() with rolling-constructed objects
    return xr.apply_ufunc(func,
                          *[(arg.rolling(dim=dim, min_periods=min_periods, center=center).
                             construct(temp_rolling_dim) if (rolling_dim in arg.dims) else arg)
                            for arg in args],
                          **kwargs)
```
