### ISSUE TITLE
Coverage badge on README

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1678]
I saw the coverage badge on our README with only 75% (true value 95%), which may be caused by github page caching.

Similar issues seem frequently reported, e.g. https://github.com/codecov/support/issues/218
Maybe we can improve this, though it would be difficult to test...

![image](https://user-images.githubusercontent.com/6815844/32254448-2631fae4-bee4-11e7-9c3e-f4731a9496a5.png)

**Comment by fujiisoup** [comment]
Note that it is not reproducible, because it may depend on my browser cache. 
But I guess this could happen also in other user's browser.

**Comment by shoyer** [comment]
I agree this is annoying (due to transient build failures). A hard refresh in my browser seems to fix it.

**Comment by jhamman** [comment]
Anything we want to do here? This doesn't seem like it would be specific to the coverage badge. I would image the status of these badges is not as important to most users as the link they provide to the docs/coveralls/travis sites.

**Comment by fujiisoup** [comment]
@jhamman 
If very low coverage badge is sometimes shown, this may degrade xarray's reliance for new users... I saw some solutions in the link above, but it is hard to check it would be working.  

Anyway, I will close this.
