### ISSUE TITLE
Serializing attrs

### ISSUE THREAD

**Issue by mullenkamp** [pydata/xarray#1681]
I'm running Windows 10, Python 2.7, and xarray version 0.9.6

Using this dictionary for a Dataset attribute:
```python
from xarray import Dataset

crs = {u'ellps': u'GRS80',
 u'k': 0.9996,
 u'lat_0': 0,
 u'lon_0': 173,
 u'no_defs': True,
 u'proj': u'tmerc',
 u'units': u'm',
 u'x_0': 1600000,
 u'y_0': 10000000}

ds = Dataset()
ds.attrs['crs'] = crs
```

When attempting to serialize the dataset attribute, I get the 

```
TypeError "Invalid value for attr: {u'lon_0': 173, u'k': 0.9996, u'ellps': u'GRS80', u'y_0': 10000000, u'no_defs': 'True', u'proj': u'tmerc', u'x_0': 1600000, u'units': u'm', u'lat_0': 0} must be a number string, ndarray or a list/tuple of numbers/strings for serialization to netCDF files"
```

This used to work in previous versions.

I then convert it to a list of tuples via crs.items(), and it successfully saves the netcdf.
But when I then open the netcdf back up, the list of tuples become one long concatenated string.
I'm guessing the core netcdf library has become more restrictive, but it would be nice to fully clarify what can be serialized or not.

Thanks

**Comment by shoyer** [comment]
Which netCDF library were you using? I don't think netCDF as a file format has ever supported maps as attributes.

For example, looking at [the spec](http://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html), attributes can be a variable-length array of any scalar type (this is specifically for netCDF3, but the rules for netCDF4 are similar):
```
     attr         = name  nc_type  nelems  [values ...]
     nc_type      = NC_BYTE   |
                    NC_CHAR   |
                    NC_SHORT  |
                    NC_INT    |
                    NC_FLOAT  |
                    NC_DOUBLE
```

In practice, I believe Python APIs (including xarray's various netCDF backends) usually decode single values to scalars.

**Comment by mullenkamp** [comment]
Thanks for the reply.
I'm currently using netcdf4 version 1.2.2, which seems slightly old but that's the default conda package.
Ok, so just to clarify...
The TypeError is correct in stating that each attribute value must be "a number, string, ndarray or a list/tuple of numbers/strings"?
Those are the only options, correct?

Thanks again.

**Comment by shoyer** [comment]
Yes, I think that's correct.
