### ISSUE TITLE
Roundtrip serialization of coordinate variables with spaces in their names

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1689]
If coordinates have spaces in their names, they get restored from netCDF files as data variables instead:
```
>>> xarray.open_dataset(xarray.Dataset(coords={'name with spaces': 1}).to_netcdf())
<xarray.Dataset>
Dimensions:           ()
Data variables:
    name with spaces  int32 1
````

This happens because the CF convention is to indicate coordinates as a space separated string, e.g., `coordinates='latitude longitude'`.

Even though these aren't CF compliant variable names (which cannot have strings) It would be nice to have an ad-hoc convention for xarray that allows us to serialize/deserialize coordinates in all/most cases. Maybe we could use escape characters for spaces (e.g., `coordinates='name\ with\ spaces'`) or quote names if they have spaces (e.g., `coordinates='"name\ with\ spaces"'`?

At the very least, we should issue a warning in these cases.

**Comment by fmaussion** [comment]
I would be in favour of issuing a warning only and discourage using spaces in variable names altogether.

**Comment by shoyer** [comment]
> I would be in favour of issuing a warning only and discourage using spaces in variable names altogether.

Even if we eventually implement this in some form, adding the warning would certainly be a good place to start.

**Comment by crusaderky** [comment]
Still valid in xarray 0.13, netcdf4-1.4.3.2

**Comment by kmuehlbauer** [comment]
Current state of affairs:

```python
xr.open_dataset(xr.Dataset(coords={'name with spaces': 1}).to_netcdf())
```
```python
SerializationWarning: coordinate 'name with spaces' has a space in its name, which means it cannot be marked as a coordinate on disk and will be saved as a data variable instead
  xr.open_dataset(xr.Dataset(coords={'name with spaces': 1}).to_netcdf())
```

Shall we close here or are there any actions which should be taken?

**Comment by kmuehlbauer** [comment]
Please reopen, if still relevant.
