### ISSUE TITLE
Regression: dropna() on lazy variable

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1694]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import xarray as xr

a = np.random.randn(4, 3)
a[1, 1] = np.NaN
da = xr.DataArray(a, dims=('y', 'x'), coords={'y':np.arange(4), 'x':np.arange(3)})
da.to_netcdf('test.nc')

with xr.open_dataarray('test.nc') as da:
    da.dropna(dim='x', how='any')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-37-8d137cf3a813> in <module>()
      8 
      9 with xr.open_dataarray('test.nc') as da:
---> 10     da.dropna(dim='x', how='any')

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/xarray/core/dataarray.py in dropna(self, dim, how, thresh)
   1158         DataArray
   1159         """
-> 1160         ds = self._to_temp_dataset().dropna(dim, how=how, thresh=thresh)
   1161         return self._from_temp_dataset(ds)
   1162 

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/xarray/core/dataset.py in dropna(self, dim, how, thresh, subset)
   2292             raise TypeError('must specify how or thresh')
   2293 
-> 2294         return self.isel(**{dim: mask})
   2295 
   2296     def fillna(self, value):

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/xarray/core/dataset.py in isel(self, drop, **indexers)
   1291         coord_names = set(variables).intersection(self._coord_names)
   1292         selected = self._replace_vars_and_dims(variables,
-> 1293                                                coord_names=coord_names)
   1294 
   1295         # Extract coordinates from indexers

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/xarray/core/dataset.py in _replace_vars_and_dims(self, variables, coord_names, dims, attrs, inplace)
    598         """
    599         if dims is None:
--> 600             dims = calculate_dimensions(variables)
    601         if inplace:
    602             self._dims = dims

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/xarray/core/dataset.py in calculate_dimensions(variables)
    111                 raise ValueError('conflicting sizes for dimension %r: '
    112                                  'length %s on %r and length %s on %r' %
--> 113                                  (dim, size, k, dims[dim], last_used[dim]))
    114     return dims
    115 

ValueError: conflicting sizes for dimension 'y': length 2 on <this-array> and length 4 on 'y'
```
#### Problem description

See above. Note that the code runs when:
- data is previously read into memory with `load()`
- the `DataArray` is stored without coordinates (this is strange)
- `dropna` is applied to `'y'` instead of `'x'`

#### Expected Output

This used to work in v0.9.6

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-38-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0rc1-5-g2a1d392
pandas: 0.21.0
numpy: 1.13.3
scipy: 1.0.0
netCDF4: 1.3.0
h5netcdf: None
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.4
matplotlib: 2.1.0
cartopy: 0.15.1
seaborn: 0.8.1
setuptools: 36.6.0
pip: 9.0.1
conda: None
pytest: 3.2.3
IPython: 6.2.1
sphinx: 1.6.5
</details>

**Comment by fujiisoup** [comment]
@fmaussion 
Thanks for the report.
PR #1693 seems to solve this, but not found the cause yet. I will investigate.

**Comment by fmaussion** [comment]
> PR #1693 seems to solve this, but not found the cause yet.

Yes I wondered about this, but it looked like another issue since the traceback is very different. Thanks for all this work @fujiisoup !

**Comment by fujiisoup** [comment]
The seems multicausal.

+ One reason is #1688, will be fixed in #1693.
+ The other cause is that `MemoryCachedArray` still stores bare `np.ndarray`, although it should be wrapped by `NumpyIndexingAdapter` in [here](https://github.com/pydata/xarray/blob/master/xarray/core/indexing.py#L409)
I thought this was fixed #1676.

**Comment by fujiisoup** [comment]
Sent a fix in #1693

**Comment by fmaussion** [comment]
Closed via https://github.com/pydata/xarray/pull/1693

**Comment by fmaussion** [comment]
@fujiisoup did you test it my code in #1693 ?

It still doesn't work for me locally

**Comment by fmaussion** [comment]
(sorry these internal stuffs are causing such a trouble :()

**Comment by fujiisoup** [comment]
@fmaussion 
Oh, really?
In my environment, the current master works without problems.
But I did not include the very code you suggested in the test suit...

I will add the test and check in travis.

**Comment by fujiisoup** [comment]
I sent a PR just adding your particular code in the test suit.
The particular test passed also in travis. 

I think something goes wrong in your environment. Probably `__pycache__` issue?

**Comment by fmaussion** [comment]
My apologies! It's my mistake. I think I was using the old-beta :-(
