### ISSUE TITLE
Multiple methods fail on a DataArray with scalar dimension

### ISSUE THREAD

**Issue by suyashbire1** [pydata/xarray#1709]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import xarray as xr
a = np.arange(20).reshape(1,2,2,5)
coords = dict(t=0, z=np.arange(2), y=np.arange(2), x=np.arange(5))
b = xr.DataArray(a,dims=['t', 'z', 'y', 'x'],coords=coords)
b.squeeze() # Throws ValueError: dimension 't' already exists as a scalar variable

coords = dict(t=[0], z=np.arange(2), y=np.arange(2), x=np.arange(5))
c = xr.DataArray(a,dims=['t', 'z', 'y', 'x'],coords=coords)
c.squeeze()  # This works!
```
#### Problem description

Besides `squeeze`, a number of other methods like `drop` fail on `DataArray b`. Since, scalar dimensions are not dropped, it is almost impossible to do anything useful like `plot`, `concat`, etc with `b`. All these methods fail with `ValueError: dimension 't' already exists as a scalar variable`.

#### Expected Output
In my opinion, `b` and `c` should behave in the same way. It would just involve converting the scalar dimensions into lists. Is this behavior a bug or by design?

#### Output of ``xr.show_versions()``
0.9.6

**Comment by shoyer** [comment]
Thanks for the report.

This should actually raise an error at construction time for the DataArray. Variables with names matching dimensions are special in xarray: they are required to be 1D arrays with length matching the dimension size.

**Comment by suyashbire1** [comment]
Glad I could help.
