### ISSUE TITLE
open_dataarray docs still contains *args, **kwargs

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#1757]
I noticed the [open_dataset](http://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html) docs provides the full input parameters whereas, [open_dataarray](http://xarray.pydata.org/en/stable/generated/xarray.open_dataarray.html) docs still lists `*args, **kwargs`
If you point me to where this is created I can change it, if the change is preferred

**Comment by fujiisoup** [comment]
Hi, raybellwaves,

I think `open_dataarray` also should provide the full input parameters.
This is written [here](https://github.com/pydata/xarray/blob/master/xarray/backends/api.py#L316).

**Comment by jhamman** [comment]
@raybellwaves - can you explain what specific problem the current `open_dataarray` signature is causing? The `*args` and `**kwargs` appear to be correctly passed onto the `open_dataset` call.

**Comment by raybellwaves** [comment]
@jhamman it was just a quick comparison with the docs online between open_dataset and open_dataarray. I was just a 2 second copy and paste in my PR

**Comment by fujiisoup** [comment]
I think this is a documentation issue.

From the user side, it would be easier to understand if the arguments of this function are explicitly listed;
auto-completion or function help in Ipython would also work.

But from the developer side, the explicit arguments will increase the risk of bugs.

Personally, I prefer the explicit function arguments, but I will not oppose the decision by the group.
