### ISSUE TITLE
xarray mean generates unstable dask name (hash)

### ISSUE THREAD

**Issue by estebanag** [pydata/xarray#1774]
#### Code Sample

```python
import dask.array as da
import xarray as xr
import numpy as np

# create dask array
x = da.ones((5, 5), chunks=(2, 2))

# create xarray array
x2 = xr.DataArray(x, dims=['d1', 'd2'])

# print dask name after taking mean
x = x.mean(axis=0)
print(x.name)

# print dask name after taking mean
x2 = x2.mean(dim='d1')
print(x2.data.name)

# confirm both functions do the same
print(np.allclose(x.compute(), x2.data.compute()))
```
#### Problem Description
Running the above sample three times outputs:
```
mean_agg-aggregate-9716da6e38d695dbff18f713d787e614
mean_agg-aggregate-02c33c19e6209edbe409749388d2f9f0
True

mean_agg-aggregate-9716da6e38d695dbff18f713d787e614
mean_agg-aggregate-2f59be8ef8c35336717fdcd7744bd167
True

mean_agg-aggregate-9716da6e38d695dbff18f713d787e614
mean_agg-aggregate-822994428d6b4cdea8e5c134711e5609
True
```
which shows the dask name (hash) generated using the xarray mean is unstable.

#### Expected Output
For processing large datasets, it's convenient to have a stable hash name in order to save intermediate results or compare them among developers. 
> Current workaround: unwrap dask array and recreate xarray array.

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.8.0-58-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0
pandas: 0.21.0
numpy: 1.13.3
scipy: 0.19.1
netCDF4: None
h5netcdf: None
Nio: None
bottleneck: None
cyordereddict: None
dask: 0.16.0
matplotlib: 2.1.0
cartopy: None
seaborn: None
setuptools: 38.2.3
pip: 9.0.1
conda: None
pytest: None
IPython: 6.2.1
sphinx: None
</details>

**Comment by shoyer** [comment]
Does `dask.array.nanmean()` have a stable name? That's the function we actually use under the covers in xarray.

**Comment by estebanag** [comment]
Indeed, `dask.array.nanmean()` doesn't have a stable name. I will raise the issue in the dask rep.
