### ISSUE TITLE
AttributeError: 'PydapArrayWrapper' object has no attribute 'shape'

### ISSUE THREAD

**Issue by kuchaale** [pydata/xarray#1775]
#### Code Sample, a copy-pastable example if possible
See my code [here](https://gist.github.com/kuchaale/422a37851113ad0a52b28bc14d296674)

#### Problem description
I received `AttributeError: 'PydapArrayWrapper' object has no attribute 'shape'` when I tried to open `PydapDataStore`. However, everything works when I use `pydap` instead of `xarray`.

#### Expected Output
`xarray.Dataset` object

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-38-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0
pandas: 0.21.0
numpy: 1.13.3
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: None
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.4
matplotlib: 2.1.0
cartopy: 0.15.1
seaborn: 0.8.1
setuptools: 36.6.0
pip: 9.0.1
conda: None
pytest: None
IPython: 6.2.1
sphinx: None

</details>

**Comment by shoyer** [comment]
Thanks for the report, this seems like a bug.

(This sneaked into our release because we only have an integration test for pydap, but it isn't required to pass because it accesses an external resource.)

**Comment by mrpgraae** [comment]
I got the same error when doing `ds = xr.open_dataset(url, engine='pydap')` using xarray 0.10.0,
but when i install directly from master i don't get the error. So it might have been fixed already.

**Comment by fujiisoup** [comment]
I got the same error with the current master.
And actually, this bug seems to be caused by my fix in #1676.

I thought just adding `shape` attribute to `PydapArrayWrapper` would solve this bug, but it actually brings another error...
