### ISSUE TITLE
ValueError on empty selection with dask based DataArrays

### ISSUE THREAD

**Issue by duncanwp** [pydata/xarray#1778]
#### Code Sample, a copy-pastable example if possible

```python
import xarray as xr
import numpy as np

da = xr.DataArray(np.random.rand(15), dims=['latitude'], coords={'latitude':np.linspace(90, -90, 15)})

# This gives an empty latitude slice
print(da.sel(latitude=slice(20, 60)))
# After converting the DataArray to dask...
da=da.chunk()
# ...this throws a ValueError due to 'conflicting sizes'
print(da.sel(latitude=slice(20, 60)))
```
#### Problem description

I would expect the dask based DataArray to return an empty slice just as the numpy one does. 

Although arguably it would be nicer if both returned the latitude values between 20 and 60 - regardless of the direction of the coordinate. Perhaps the sel method could check whether the coordinate is increasing or decreasing?

#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here
xarray version: 0.9.6
numpy version: 1.13.3
dask version: 0.15.4
</details>

**Comment by shoyer** [comment]
Thanks for the report. This is a bug in dask (https://github.com/dask/dask/issues/2994), which is computing the wrong size for the resulting array.

**Comment by dcherian** [comment]
Upstream issue is fixed and example works now.
