### ISSUE TITLE
DataArray.plot raises exception if contents are all NaN

### ISSUE THREAD

**Issue by Zac-HD** [pydata/xarray#1780]
#### Code Sample, a copy-pastable example if possible

```python
xr.DataArray(np.full((2, 2), 0)).plot.imshow()  # works
xr.DataArray(np.full((2, 2), np.nan)).plot.imshow()  # doesn't
```
#### Problem description

If you try to plot a `DataArray` which is entirely filled with `NaN`, you get an exception.  This is *really, really* annoying for people doing satellite image analysis, especially with timeseries where just one step might be very cloudy.

#### Expected Output

Plot of the array extent, entirely in the missing-value colour as for partially-missing data.

#### Output of ``xr.show_versions()``

Confirmed on Windows/Linux/OSX, Xarray 0.9.6 and 0.10.0; sample show_versions below.  It's a pretty obvious error though in failing to handle the no-non-missing-data case when determining data range.

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-696.10.3.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
LOCALE: en_AU.UTF-8

xarray: 0.10.0
pandas: 0.20.3
numpy: 1.13.3
scipy: 0.19.1
netCDF4: 1.3.1
h5netcdf: None
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.3
matplotlib: 2.1.0
cartopy: None
seaborn: 0.8.0
setuptools: 36.5.0.post20170921
pip: 9.0.1
conda: 4.3.30
pytest: 3.2.1
IPython: 6.1.0
sphinx: 1.6.3
</details>

**Comment by fmaussion** [comment]
Yes, I agree. We inherited the logic from seaborn, which also has this problem:

```python
In [2]: import seaborn as sns
In [3]: import numpy as np
In [4]: a = np.zeros((2, 2)) * np.NaN
In [6]: sns.heatmap(a)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-9ef15135ade2> in <module>()
----> 1 sns.heatmap(a)

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/seaborn/matrix.py in heatmap(data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, linewidths, linecolor, cbar, cbar_kws, cbar_ax, square, xticklabels, yticklabels, mask, ax, **kwargs)
    515     plotter = _HeatMapper(data, vmin, vmax, cmap, center, robust, annot, fmt,
    516                           annot_kws, cbar, cbar_kws, xticklabels,
--> 517                           yticklabels, mask)
    518 
    519     # Add the pcolormesh kwargs here

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/seaborn/matrix.py in __init__(self, data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, cbar, cbar_kws, xticklabels, yticklabels, mask)
    166         # Determine good default values for the colormapping
    167         self._determine_cmap_params(plot_data, vmin, vmax,
--> 168                                     cmap, center, robust)
    169 
    170         # Sort out the annotations

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/seaborn/matrix.py in _determine_cmap_params(self, plot_data, vmin, vmax, cmap, center, robust)
    205         calc_data = plot_data.data[~np.isnan(plot_data.data)]
    206         if vmin is None:
--> 207             vmin = np.percentile(calc_data, 2) if robust else calc_data.min()
    208         if vmax is None:
    209             vmax = np.percentile(calc_data, 98) if robust else calc_data.max()

~/.pyvirtualenvs/py3/lib/python3.5/site-packages/numpy/core/_methods.py in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation minimum which has no identity

```

Will try to submit a fix later today

**Comment by fmaussion** [comment]
Actually I changed my mind a little bit ;-). Matplotlib won't plot all NaNs images either:

```python
import numpy as np
import matplotlib.pyplot as plt

a = np.full((2, 2), np.NaN)
plt.imshow(a)  
plt.show()  # raises an error
```
So we have to decide if it's worth to add a bunch of logic in xarray to handle these cases or if it's the user's responsibility to check the data before plotting.

**Comment by Zac-HD** [comment]
I'd argue that Xarray should handle these cases - it already does for lower dimensions, eg `xr.DataArray(np.full(1, np.nan)).plot()` works, and this would be really nice for exploratory analysis as well as consistency.

This is sufficiently annoying to my research group that I'm willing to write the patch, if that helps!  I also have some ideas for tests using Hypothesis to ferret out some other problems - for example there's a similar failure if plotting an array with size one in some dimension.

**Comment by fmaussion** [comment]
> I'm willing to write the patch, if that helps! 

Yes, thanks! The best place to start would be to add a regression test to `Common2dMixin` (https://github.com/pydata/xarray/blob/master/xarray/tests/test_plot.py#L560). 

I investigated a bit and it seems that in the case of all nan data you would probably have to force `add_colorbar` to False and do other things for matplotlib to accept your all nan data.

**Comment by Zac-HD** [comment]
> I investigated a bit and it seems that in the case of all nan data you would probably have to force add_colorbar to False and do other things for matplotlib to accept your all nan data.

I don't *need* to do this, but I'd like to for another feature (`imshow` RGB images) - the question is how!  Passing `add_colorbar=False` to `plot.imshow` just gives me errors, and I can't find anywhere in the internals where this would be valid either - it always gets passed through to the matplotlib Artist and then an exception.

**Comment by shoyer** [comment]
@fmaussion what version of matplotlib are you using? imshow with all NaNs works for me on matplotlib 1.5.2 (yes, we're stuck in the dark ages). This might be a  regression in matplotlib.

**Comment by fmaussion** [comment]
> imshow with all NaNs works for me on matplotlib 1.5.2 

ups yes, I might have been confused by the warning, but it does work with latest mpl yes. The warning says:

```
In [1]: import numpy as np

In [2]: import matplotlib.pyplot as plt

In [3]: a = np.full((2, 2), np.NaN)

In [4]: plt.imshow(a)  
Out[4]: <matplotlib.image.AxesImage at 0x7f6e2a8ba710>

In [5]: plt.show()
/home/mowglie/.pyvirtualenvs/py3/lib/python3.5/site-packages/matplotlib/colors.py:897: UserWarning: Warning: converting a masked element to nan.
  dtype = np.min_scalar_type(value)
/home/mowglie/.pyvirtualenvs/py3/lib/python3.5/site-packages/numpy/ma/core.py:748: UserWarning: Warning: converting a masked element to nan.
  data = np.array(a, copy=False, subok=subok)
```
