### ISSUE TITLE
Any idea to speed up the open_mfdataset for reading many many big netCDF files?

### ISSUE THREAD

**Issue by wqshen** [pydata/xarray#1788]
I have several WRFout files for 20-year climate simulations, when i  use open_mfdataset to read them, it takes me 10 - 20 minutes to finish on my server.

Is there a way to speed up this process? 
Multiprocessing ??

**Comment by shoyer** [comment]
Try changing the `coords` argument to list the explicit coordinates that should be concatenated together. (We should probably change this argument name: it makes more sense on `concat` than `open_mfdataset`.)

**Comment by jhamman** [comment]
@wqshen - can you report the versions of xarray/dask that you are using (the original issue template had examples of how to do this)?

**Comment by jhamman** [comment]
Closed via #1981
