### ISSUE TITLE
BUG: set_variables in backends.commons loads target dataset

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#1798]
#### Problem description

In #1609 we (I) implemented a fix for appending to datasets with existing variables. In doing so, it looks like I added a regression wherein the `variables` property on the `AbstractWritableDataStore` is repeatedly queried. This property calls `.load()` on the underlying dataset.

This was discovered while diagnosing some problems with the zarr backend (#1770, https://github.com/pangeo-data/pangeo/issues/48#issuecomment-353223737). 

I have a potential fix for this that I will post once the tests pass.

cc @rabernat, @mrocklin

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: 20f957db105a9348b0f7d2dac076c17c31cbccee
python: 3.6.0.final.0
python-bits: 64
OS: Darwin
OS-release: 17.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0+dev18.g4a9c1e3
pandas: 0.21.0
numpy: 1.13.3
scipy: 0.19.1
netCDF4: 1.3.0
h5netcdf: 0.5.0
Nio: None
zarr: 2.1.4
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.4
distributed: 1.19.3
matplotlib: 2.0.2
cartopy: 0.15.1
seaborn: 0.8.1
setuptools: 33.1.0.post20170122
pip: 9.0.1
conda: None
pytest: 3.2.3
IPython: 5.2.2
sphinx: 1.6.3
</details>

**Comment by shoyer** [comment]
Oh my... this is a good reason why we should get ride of properties that do non-trivial computation.
