### ISSUE TITLE
Empty DataArray should have a length of 0

### ISSUE THREAD

**Issue by mcdevitts** [pydata/xarray#1807]
```python
dr = xr.DataArray(())
len(dr)
```

When evaluating the length of an empty DataArray, instead of evaluating as zero, it raises a TypeError. Most other container classes (lists, dicts, ndarrays) all evaluate with a zero length when empty. I would expect and prefer that this class evaluate its length as zero when empty.

<details>
xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

xarray: 0.10.0
pandas: 0.21.1
numpy: 1.13.3
scipy: 1.0.0
netCDF4: None
h5netcdf: None
Nio: None
bottleneck: None
cyordereddict: None
dask: None
matplotlib: None
cartopy: None
seaborn: None
setuptools: 38.2.5
pip: 9.0.1
conda: None
pytest: None
IPython: 6.2.1
sphinx: None

</details>

**Comment by shoyer** [comment]
Thanks for the report.

Creating a DataArray with a tuple actually creates a scalar (0-dimensional array):
```
In [40]: dr = xr.DataArray(())

In [41]: dr
Out[41]:
<xarray.DataArray ()>
array((), dtype=object)

In [42]: dr.shape
Out[42]: ()
```
We then raise a `TypeError` when calculating the length of an empty DataArray, which is consistent with NumPy.

In contrast, if you make an empty DataArray with an empty list, you do get a 1D dimensional length 0 array:
```
In [54]: dr = xr.DataArray([])

In [55]: len(dr)
Out[55]: 0

In [56]: dr.shape
Out[56]: (0,)
```

**Comment by shoyer** [comment]
I agree that it is a little surprising that we create a scalar array for tuples instead of 1D array like NumPy. To be honest, I'm not entirely sure why we do that, but looking in git history suggests it had something to do with making it easier to support `pandas.MultiIndex` (which has scalar values given by tuples).

**Comment by mcdevitts** [comment]
You're absolutely correct about the ndarray behavior; I was mistaken.

I mostly have the built-in python types in mind when looking for a length of 0. Now that I think of it, I've hit this same issue with ndarrays. I'm not sure what the "right" behavior would be here, since I'm not sure why the ndarrays behave differently than the base python types.

**Comment by shoyer** [comment]
0-dimensional numpy array don't have a length because it isn't entirely clear what that would mean. In many cases, NumPy treats them as equivalent to Python scalars (e.g., `float`), which doesn't have a defined length.
