### ISSUE TITLE
data_array.<tab> reads data

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#1810]
#### Code Sample, a copy-pastable example if possible

```python
ds = xarray.open_dataset(...)
da = ds.variables['...']
da.<tab>
```
#### Problem description

This starts reading data.  I don't know why.  I'm using XArray against a FUSE system that is both expensive (it's targetting Google Cloud Storage) and also has logging. I can see that auto-completion immediately starts a lot of file reading on the file system.

#### Output of ``xr.show_versions()``

<details>

```python
# Paste the output here xr.show_versions() here
>>> xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-42-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0
pandas: 0.21.0
numpy: 1.13.3
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: 0.5.0
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.16.0
matplotlib: None
cartopy: None
seaborn: None
setuptools: 36.6.0
pip: 9.0.1
conda: 4.3.29
pytest: 3.3.1
IPython: 6.2.1
sphinx: None
```

</details>

**Comment by mrocklin** [comment]
Operationally this is both inefficient for me in terms of bandwidth and actually results in crashing my pod (although this is likely more FUSE's fault than XArray's)

**Comment by fujiisoup** [comment]
What version of IPython and jedi are you using?
If it is the same issue to #1727,
updating jedi to 0.11 would solve this bug.

**Comment by mrocklin** [comment]
'6.2.1'  and '0.10.2' respectively.  I'll try updating Jedi and report back.  Thank you for the pointer and rapid response @fujiisoup !

**Comment by mrocklin** [comment]
Confirmed that this resolved the issue.  Thanks all!
