### ISSUE TITLE
Change of file encoding when opening

### ISSUE THREAD

**Issue by sehnem** [pydata/xarray#1818]
I am using xarray to modify goes-16 netCDF files. I open the file, and create a new file with the same structure and attributes, but with a selected area of the data.

When I try to run this file I am having trouble with the library that I use to read the data which uses h5netcdf as library to read the data. I found that the error if because of the string encoding and changes in the netCDF C library.

My question is about xarray default behavior, should it change the encoding when opening the file?

And about a possible solution, do I have to change the encoding of any string attribute, one by one?

Here is my code

```python
xnc = xr.open_dataset(file)
xnc = xnc.sel(y=xnc.Rad.y.values[y_l:y_r], x=xnc.Rad.x.values[x_l:x_r])
xnc.to_netcdf(nfile, format='NETCDF4_CLASSIC')
nfiles.append(nfile)
```

**Comment by shoyer** [comment]
Can you be more specific about how the string encoding changed and what your preferred behavior would be? Maybe the share results of `ncdump -h` on the input and output files?

**Comment by sehnem** [comment]
I could not see any usefull information in the dumps, anyway, here is a link to them, they are to long to post here.
Input file: https://goo.gl/QAheot
Output file: https://goo.gl/H7CFbg

The error that I get with the output netCDF is:
> OSError: Unable to read attribute (no appropriate function for conversion path)
 I also tried to use `h5netcdf` as reader and writer, but neither of them worked.

**Comment by shoyer** [comment]
Ah, gotcha. To fix this, you can either use h5netcdf to write your netCDF data (using `engine='h5netcdf'`) or update the netCDF C library to version 4.5.0 or later (this was fixed by https://github.com/Unidata/netcdf-c/pull/316).

**Comment by sehnem** [comment]
It worked with the netCDF C version 4.5.0.
Thanks!
