### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#1830]
When do we want to drop Python 2 support for Xarray. For reference, Pandas has a stated drop date for Python 2 of the end of 2018 (this year) and Numpy is slightly later and includes an incremental depreciation, final on Jan. 1, 2020.

We may also consider signing this pledge to help make it clear when/why we're dropping Python 2 support: http://www.python3statement.org/

xref: https://github.com/pandas-dev/pandas/issues/18894, https://github.com/numpy/numpy/pull/10006, https://github.com/python3statement/python3statement.github.io/issues/11

**Comment by shoyer** [comment]
My inclination would be to follow the lead of pandas here, since it's unlikely to make sense to update xarray without its dependencies. So I guess end of 2018 makes sense?

**Comment by jhamman** [comment]
I've just put up a PR on the python3statement repo. I've tentatively also listed 2019-01-01 as a possible target for Xarray 1.0, coincident with dropping Python2, but am now thinking we may need a larger discussion before that comes to any certainty. Anyhow, please take a look at https://github.com/python3statement/python3statement.github.io/pull/102.

**Comment by shoyer** [comment]
My inclination would be to save 1.0 until xarray's data model is stable, which probably means after https://github.com/pydata/xarray/issues/1603. If the timing works out for dropping Python 2 support that would be great, but I wouldn't want to force it.

**Comment by jhamman** [comment]
@pydata/xarray - any objections to the timeline here? We will need to close this before https://github.com/python3statement/python3statement.github.io/pull/102 can be merged.

**Comment by shoyer** [comment]
I don't object to the timeline, but I don't think we're ready to commit to supporting Python 2 for all 0.X releases and stopping it with 1.0. The particular version number feels premature to me.

**Comment by jhamman** [comment]
Great. No argument there. I'll adjust the PR on the python3statement to reflect that.

**Comment by fmaussion** [comment]
I fully agree with the proposed changes!
