### ISSUE TITLE
Slow performance of rolling.reduce

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1831]
#### Code Sample, a copy-pastable example if possible

```python
In [1]: import numpy as np
   ...: import xarray as xr
   ...: 
   ...: da = xr.DataArray(np.random.randn(1000, 100), dims=['x', 'y'],
   ...:                   coords={'x': np.arange(1000)})
   ...: 

In [2]: %%timeit
   ...: da.rolling(x=10).reduce(np.sum)
   ...: 
2.04 s ± 8.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
#### Problem description

In `DataArray.rolling`, we index by `.isel` method for every window, constructing huge number of `xr.DataArray` instances. This is very inefficient.

Of course, we can use bottleneck methods if available, but this provides only a limited functions.
(This also limits possible extensions of rolling, such as ND-rolling (#819), window type (#1142), strides (#819).)

I am wondering if we could skip any sanity checks in our `DataArray.isel -> Variable.isel` path in indexing.
Or can we directly construct a single large `DataArray` instead of a lot of small `DataArray`s?

**Comment by jhamman** [comment]
@fujiisoup - I think this is a great idea. As you've noted, the `reduce` implementation in about as naive as it comes (#668). While the `__iter__` method should continue to return DataArray objects, the `reduce` method can be optimized.

**Comment by shoyer** [comment]
Yes, I think the stride tricks version would be a significant improvement. See this numpy PR for discussion/examples: https://github.com/numpy/numpy/pull/31

**Comment by fujiisoup** [comment]
Thanks for the information.
I will look into the issue.
 
I think the sliding-and-stack method itself would be also handy.
Will start from this.
