### ISSUE TITLE
COMPAT: MultiIndex checking is fragile

### ISSUE THREAD

**Issue by jreback** [pydata/xarray#1833]
https://github.com/pydata/xarray/blob/master/xarray/core/dataset.py#L2755

checking for a MI via 
```
if hasattr(idx, 'levels'):
    # is a MI
```

should be changed to
```
if idx.nlevels > 1:
    # is a MI
```

see [here](https://github.com/pandas-dev/pandas/issues/3268#issuecomment-357925936). This is not currently implemented but good to get ahead of this hard to detect usage of the API.

**Comment by shoyer** [comment]
Thanks for the heads up. 

For our purposes, I think it would actually be just fine to use `isinstance(idx, pd.MultiIndex)` here.
