### ISSUE TITLE
Add simple array creation functions for easier unit testing

### ISSUE THREAD

**Issue by nbren12** [pydata/xarray#1839]
When I am writing unit tests for routines that involve `DataArray` objects many lines of code are devoted to creating mock objects. Here is an example of a unit test I recently wrote to test some code which computes the fluid derivative of a field given the velocity. 
```python
def test_material_derivative():

    dims = ['x', 'y', 'z', 'time']
    coords = {dim: np.arange(10) for dim in dims}
    shape = [coords[dim].shape[0] for dim in coords]

    f = xr.Dataset({'f': (dims, np.ones(shape))}, coords=coords)
    f = f.f

    one = 0 *f +1
    zero = 0*f


    md = material_derivative(zero, one, zero, f.x + 0*f)
    np.testing.assert_array_almost_equal(md.values, 0)

    md = material_derivative(one, zero, zero, f.x + 0*f)
    np.testing.assert_array_almost_equal(md.isel(x=slice(1,-1)).values,
                                         one.isel(x=slice(1,-1)).values)

    md = material_derivative(zero, one, zero, f.y + 0*f)
    np.testing.assert_array_almost_equal(md.isel(y=slice(1,-1)).values,
                                         one.isel(y=slice(1,-1)).values)

    md = material_derivative(zero, zero, one, f.z + 0*f)
    np.testing.assert_array_almost_equal(md.isel(z=slice(1,-1)).values,
                                         one.isel(z=slice(1,-1)).values)
```

As you can see, I devote many lines to initializing a 4D data array of all ones, where all the coordinates are `np.arange(10)` objects. It isn't too hard to do this once, but it gets pretty annoying to do many times, especially when I forget how the DataArray and Dataset constructors work. Now, I can do something like `xr.DataArray(np.ones(...))`, but I would still have to initialize the coordinates if I use them.

In any case, having some sort of functions like `xr.ones`, `xr.zeros`, and `xr.rand` which initialize the coordinates and data would be very nice.

**Comment by shoyer** [comment]
What would use suggest for the signature of a function like `xr.ones`?

I think the main reason why we don't have these helpers is that `xr.DataArray(np.ones(3, 4), dims=['x', 'y'])` is nearly as succinct 

I suppose we could possibly do better now that newer versions of Python (3.6+) guarantee order for keyword arguments, so we could have something like `xr.ones(x=3, y=4)`.

**Comment by nbren12** [comment]
I guess the main reason barrier for me is initializing the coordinates quickly, which `xr.DataArray(np.ones(3, 4), dims=['x', 'y'])` doesn't do. 

> xr.DataArray(np.ones(3, 4), dims=['x', 'y'])

Something like the following would work for me:

```python
def ones(shape, dims=None):
    """Create DataArray of ones with initialized coordinates

    Parameters
    ----------
    shape : tuple
        shape of the array
    dims : list of str, optional
        list of dimensions with same length as shape. The default will be
        dim_0, dim_1,...,etc
    coordinate_initializer : optional
        function which returns the appropriate coordinates. The signature for
        this function must be coordinate_initializer(dim, dim_length). The
        default is to initialize all the coordinates with
        ``np.arange(dim_length)``
    """
    pass
```
