### ISSUE TITLE
Customization of XArray Columns

### ISSUE THREAD

**Issue by achapkowski** [pydata/xarray#1853]
#### Problem description

Hello,

I created a custom Series in pandas' that has function on it not normal to a normal pd.Series.  Can you create custom columns in xarray?  Are there any examples of that? 
Thanks

**Comment by maxim-lian** [comment]
Can you give more detail on your question? I don't understand "that has function on it not normal to a normal pd.Series"

**Comment by achapkowski** [comment]
@maxim-lian sure.  

I extended a pd.Series like this:

```
class PolygonSeries(pd.Series):

    def convex_hull(self, tol=.00001):
        # do stuff not normal to pandas
        return result
```

Can I do the same thing in xarray for a given column?  I can have different types of Series in Pandas' like object, int64, etc... and I can also have custom series objects as well (shown above).  Is there an x-array series that I can extend to match the pd.Series I created?

**Comment by maxim-lian** [comment]
You can inherit from a `Dataset` or `DataArray`, and returns results that way - we do that a lot. That's the level of granularity that we use (and regardless, there isn't a `Series` object in xr)

**Comment by jhamman** [comment]
@achapkowski - can you take a look at our documentation on [Extending xarray](http://xarray.pydata.org/en/latest/internals.html#extending-xarray) and let us know if that is sufficient to have us close this issue?
