### ISSUE TITLE
swap_dims should support dimension names that are not existing variables

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1855]
#### Code Sample, a copy-pastable example if possible

```python
input_ds = xarray.Dataset({'foo': ('x', [1, 2])}, {'x': [0, 1]})
input_ds.swap_dims({'x': 'z'})
```
#### Problem description

Currently this results in the error `KeyError: 'z'`

#### Expected Output

We now support dimensions without associated coordinate variables. So `swap_dims()` should be able to create new dimensions (e.g., `z` in this example) even if there isn't already a coordinate variable.

**Comment by dcherian** [comment]
I think we already have this as `ds.rename_dims`?

**Comment by keewis** [comment]
I think `rename_dims` does something different: it renames a dimension if the new name does not exist (if it exists, it does something strange, see #3438), while `swap_dims` creates a new dimension and moves the old dimension to `coords` (or `data_vars`?).

**Comment by keewis** [comment]
we should, however, clearly define the use cases of `swap_dims` and `rename_dims`. Right now, the docs are not clear on the difference between them.
