### ISSUE TITLE
Weird looking plots from combined DataArrays

### ISSUE THREAD

**Issue by gajomi** [pydata/xarray#1862]
I am trying to figure out how to plot 2 dimensional data from multiple data arrays that share common coordinates. My first guess was to throw the data arrays into a dataset and call a plot method, but it seems that is unsupported (perhaps with good reason). My second idea was to  trying to "merge" the data arrays into a single one and then call the plot method. Here is what I get:

```python
N = 2**6
x, y = range(N), range(N)
n = int(N/4)
A, B = np.random.rand(n,n), np.random.rand(n,n)

xrA = xr.DataArray(A, dims=('x','y'), coords={'x':x[:n],'y':y[:n]})
xrB = xr.DataArray(B, dims=('x','y'), coords={'x':x[-n:],'y':y[-n:]})

xrAB = xrA.combine_first(xrB)

dataarrays = [xrA,xrB,xrAB]

fig,axs = plt.subplots(1,3,figsize=(15,4))
for ax,data in zip(axs,dataarrays):
    data.plot(ax=ax)
```

![image](https://user-images.githubusercontent.com/244887/35463660-9aaa9880-02a6-11e8-95f5-2a13c00fb25e.png)

I was not expecting to see the funny looking artifacts extending from the edges of the region with non nan data. A slightly more elaborate version with three non nan regions shows similar behavior:
```
xrC = xr.DataArray(C, dims=('x','y'), coords={'x':x[15:n+15],'y':y[-n-10:-10]})

xrABC = xrA.combine_first(xrB).combine_first(xrC)

fig,ax = plt.subplots(figsize=(5,5))
xrABC.plot(ax=ax)
```

![image](https://user-images.githubusercontent.com/244887/35463861-bb704136-02a7-11e8-9693-79be0b582cf4.png)

Is this a bug or a feature? If not a bug, how should I go about plotting my array data so that nan regions look as such?

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0
pandas: 0.20.3
numpy: 1.13.0
scipy: 0.18.1
netCDF4: None
h5netcdf: None
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.3
matplotlib: 2.0.0
cartopy: None
seaborn: 0.8.0
setuptools: 36.5.0.post20170921
pip: 9.0.1
conda: 4.4.6
pytest: 3.2.1
IPython: 6.1.0
sphinx: 1.6.3

</details>

**Comment by shoyer** [comment]
I'm not 100% sure if we're doing the right thing here or not :).

The fundamental issue here is that your coordinates are not evenly spaced:
```
>>> xrAB
<xarray.DataArray (x: 32, y: 32)>
array([[ 0.805096,  0.339439,  0.889917, ...,       nan,       nan,       nan],
       [ 0.796546,  0.465788,  0.022211, ...,       nan,       nan,       nan],
       [ 0.075146,  0.261747,  0.029072, ...,       nan,       nan,       nan],
       ..., 
       [      nan,       nan,       nan, ...,  0.297032,  0.707947,  0.617284],
       [      nan,       nan,       nan, ...,  0.673249,  0.507685,  0.807462],
       [      nan,       nan,       nan, ...,  0.68973 ,  0.786864,  0.04618 ]])
Coordinates:
  * y        (y) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 48 49 50 51 52 ...
  * x        (x) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 48 49 50 51 52 ...
```

Notice the jump from 15 to 48. Without coordinate values in between, what should xarray assume for the intermediate values? Here we seem to be treating the function as piece-wise constant.

Probably the simplest way to fix this is to start with an all NaN array of the appropriate size. This yields a sensible looking plot:
```python
empty = xr.DataArray(np.full((N, N), np.nan), [('x', x), ('y', y)])
xrAB = empty.combine_first(xrA).combine_first(xrB)
xrAB.plot()
```
![download 47](https://user-images.githubusercontent.com/1217238/35465772-4e3d4d82-02b3-11e8-81b6-5a572f34db32.png)

**Comment by gajomi** [comment]
>Without coordinate values in between, what should xarray assume for the intermediate values?

I guess I had imagined it would not try to plot those intermediate values. 

I think the behavior makes sense in 1d (pandas does the same linear interpolation I think)
```
xrYsum = xrAB.sum(dim = 'x')
xrYsum.plot()
```
![image](https://user-images.githubusercontent.com/244887/35489187-5e40eb94-0448-11e8-8068-f47415b2d833.png)
but in 2d it seems weird. Is there are common use case where this interpolation is desirable? Perhaps its just my ignorance speaking, but it feels like the behavior violates the principle of least astonishment, especially in light of the fact that irregular grids are one of the main use cases for xarray with explicit support in the [docs]( http://xarray.pydata.org/en/stable/plotting.html#multidimensional-coordinates). 

>Probably the simplest way to fix this is to start with an all NaN array of the appropriate size.

👍 

I'd be happy to take a stab at implementing plotting that gives (by default or through an option) a result equivalent to the last plot you made if you imagine xarray users would find it useful.

**Comment by fmaussion** [comment]
Note that this is related to https://github.com/pydata/xarray/issues/1852 . xarray currently makes assumptions about the coordinates (monotonically ascending / descending, more or less -but not strictly- evenly spaced), which are very sensible in the geosciences but which become less true when the data becomes messy as in these two cases. 

Here again I think that it will be hard to find a generic solution which will work same for all 2d graphics (contourf, imshow and pcolormesh), but I would be happy for any suggestion you have. At the very least we should raise an error or warning (similar to https://github.com/pydata/xarray/issues/1852)

**Comment by shoyer** [comment]
> I think the behavior makes sense in 1d (pandas does the same linear interpolation I think)

I'm not so sure it makes sense in 1D, either. Most of the time I've wished that large gaps were replaced with empty gaps. I've learned to be suspicious of long straight lines.

One option would be to add a `max_spacing` argument to `plot()` that indicates a maximum "valid" spacing to plot continuously over. If a gap is larger than the spacing, then it would plotted empty instead.

Potentially we could even default to some heuristic choice for `max_spacing`, but I'm not sure exactly what that heuristic would be.

I'm also not entirely sure how to implement `max_spacing` for pcolormesh, contour or line plots. I suspect it would be impossible to do for imshow (but that's OK, imshow is only for completely regular data).

**Comment by gajomi** [comment]
A max_spacing argument sounds interesting, but definitely makes me think I need to meditate for awhile on the scope of raised issue. A basic semantic distinction of importance here is where the coordinates are "point like", or represent the centers of intervals of some volume or something else entirely (e.g., in the case of non-interval or float data). Depending on what they represent you might want to plot one thing or another.
