### ISSUE TITLE
BUG: ds['...'].sel(...).values throws exception for a ds loaded from file

### ISSUE THREAD

**Issue by seth-p** [pydata/xarray#1864]
```python
import xarray as xr
ds = xr.Dataset(data_vars={'foo': xr.DataArray([1.], dims='abc', coords={'abc': ['a']})})
ds.to_netcdf(path='ds.nc', engine='h5netcdf')
ds1 = xr.open_dataset('ds.nc', engine='h5netcdf')
# ds1['foo'].values  # uncomment to eliminate exception
ds1['foo'].sel(abc=['a']).values  # throws "TypeError: PointSelection __getitem__ only works with bool arrays"
```
#### Problem description

Accessing the DataArray's `.sel()` before `.values` leads to `TypeError: PointSelection __getitem__ only works with bool arrays`.
Accessing the DataArray's `.values` before the `.sel().values` eliminates the error.

#### Expected Output
array([ 1.])

#### Output of ``xr.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

xarray: 0.10.0
pandas: 0.22.0
numpy: 1.13.3
scipy: 1.0.0
netCDF4: None
h5netcdf: 0.5.0
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.16.1
matplotlib: 2.1.2
cartopy: None
seaborn: 0.8.1
setuptools: 38.4.0
pip: 9.0.1
conda: 4.3.33
pytest: 3.3.2
IPython: 6.2.1
sphinx: 1.6.6

**Comment by shoyer** [comment]
Thanks for the report.

This is arguably an h5py bug (https://github.com/h5py/h5py/issues/992), but we can work around it in xarray.
