### ISSUE TITLE
Documentation is inaccessible via HTTPS

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/xarray#1873]
Looks like the link [here](https://xarray.pydata.org/en/stable/) gives an invalid certificate error. It seems the PyData domain incorrectly just forwards the HTTPS traffic to RTD, rather than tunneling and substituting its own certificate.

**Comment by jhamman** [comment]
Does anyone have experience configuring https certificates with either pydata.org or RTD?

**Comment by hameerabbasi** [comment]
I have experience with Nginx, which PyData uses (according to some HTTP headers).

**Comment by shoyer** [comment]
It looks like Dask has HTTPS configured properly for dask.pydata.org, so hopefully it's a simple fix for xarray, too. @mrocklin do you know how this was set up?

**Comment by mrocklin** [comment]
Not really, no.  I tend to push these upstream to either Anaconda's IT or NumFOCUS.  cc @aterrel

**Comment by aterrel** [comment]
Hello if you find troubles with pydata.org definitely send mail to web@pydata.org

In this case, which is completely different from the Dask cask, xarray.pydata.org is registered as a cname to read the docs. While pydata.org does serve via Nginx subdomains do not point to that server.

Read the docs is serving a security certificate with itself as the domain authority. The browser correctly recognizes that this is not the correct certificate for a custom domain, (only really good for things like: https://readthedocs.org/projects/xray/)

If there is a desire to serve a https from the xdata.pydata.org, I can set up a certificate on cloudflare which will terminate the https request and forward the http request to readthedocs. As Dask has found there is a bug somewhere that redirects some pages on read the docs from https to http, but we can cross that bridgw when we get there.

**Comment by hameerabbasi** [comment]
xref pydata/sparse#103

**Comment by shoyer** [comment]
I don't particularly care about HTTPS for serving docs, but I think the desire is mostly to avoid scary looking error messages. If you could mirror the dask setup for xarray and sparse via cloudflare that would be appreciated.

**Comment by aterrel** [comment]
Okay I'll turn on the HTTPS proxy service. Let me know if you notice anything unexpected.

**Comment by jhamman** [comment]
This seems to be working, @hameerabbasi - can you confirm and close if things look okay on your end.

**Comment by jhamman** [comment]
Thanks @aterrel!

**Comment by hameerabbasi** [comment]
Things look fine now. :-)
