### ISSUE TITLE
DEP: drop Python 2.7 support

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#1876]
The timeline for dropping Python 2.7 support for new Xarray releases is the end of 2018.

This issue can be used to track the necessary documentation and code changes to make that happen. 

xref: #1830

**Comment by fmaussion** [comment]
Thanks! The [practicalities](http://www.python3statement.org/practicalities/) page from the python3statement is a good start.

What I heard from other projects is that we shouldn't *actively* remove cross-compatible code. We could simply stop testing on py2 and not care about cross-compatibility anymore.

**Comment by jhamman** [comment]
A practical change we need to make prior to dropping python 2 is to move the Python 2 test suite to Python 3. A number of Xarray's optional dependencies are still pinned to Python 2 so there will be a few hiccups there:

- PyNIO: A Python 3 compatible release is forthcoming, see https://github.com/NCAR/pynio/issues/17.
- CDAT: I'm not sure if there is Python 3 support yet. The conda-forge build only has Py2. 

Ideally, we can just map the py2 tests directly to py3:

- `py27-min` --> `py35-min`
- `py27-cdat+iris+pynio` --> py36-cdat+iris+pynio

We may also consider dropping this test all together and putting cdat/iris/pynio in the standard `py36` test.
