### ISSUE TITLE
xarray tutorial at SciPy 2018?

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#1882]
It would be great to hold an xarray tutorial at SciPy 2018. Xarray has matured a lot recently, and it would be great to raise awareness of what it can do among the broader scipy community.

From the [conference website](https://scipy2018.scipy.org/ehome/299527/648139/):
> Tutorials should be focused on covering a well-defined topic in a hands-on manner. We want to see attendees coding! We encourage submissions to be designed to allow at least 50% of the time for hands-on exercises even if this means the subject matter needs to be limited. Tutorials will be 4 hours in duration. In your tutorial application, you can indicate what prerequisite skills and knowledge will be needed for your tutorial, and the approximate expected level of knowledge of your students (i.e., beginner, intermediate, advanced).

I'm curious if anyone was already planning on submitting a tutorial. If not, let's put together a team. @jhamman has indicated interest in participating in, but not leading, the tutorial. Anyone else interested?

xref pangeo-data/pangeo#97

**Comment by benbovy** [comment]
I plan to attend SciPy this year and I'd be happy to join in.

**Comment by rabernat** [comment]
What is needed is someone to lead the tutorial team (including submitting the application). You will clearly have help from @jhamman and @benbovy in presenting the tutorial. You will also get a stipend of $1000!

 I can't volunteer because I'm not sure I'll even be able to attend the conference.

**Comment by jhamman** [comment]
If I can get some help putting together the materials, I can lead tutorial. @kmpaul and I are already preparing an Xarray tutorial for April ([link](https://sea.ucar.edu/event/atmospheric-data-analysis-dask-and-xarray)) so really we just need to adapt what we come up with for that to be useful for Scipy.

**Comment by mjbrodzik** [comment]
I would be happy to assist.  I have asked for travel funds to attend SciPy this year, but have not yet gotten approval.  Even if I can't go I could assist with review of materials if you are interested in feedback. If I can go, I could certainly work as a tutorial helper.

**Comment by ktyle** [comment]
Although not active on the Xarray github, I am an early adopter and active user of the software and am looking for a good excuse to go to scipy for the first time ...I would be glad to assist!

**Comment by jhamman** [comment]
I submitted an abstract for an xarray tutorial today. More information to come as we get closer to the conference but for now the title: ***Xarray for Scalable Scientific Data Analysis***. Stay tuned!

**Comment by gajomi** [comment]
> Xarray for Scalable Scientific Data Analysis

Nice title! 

I know xarray has its origins and most of its current users in the earth science domains, and so I would expect much of the core of an xarray tutorial to involve various geo* flavored data, but since SciPy has attendees from so many different backgrounds it could be useful to try to survey the scope of work being done with xarray right now. I imagine there must be other users in astronomy, physics, biology and perhaps even quantitative civics/demography that could have interesting snippets to share. 

For my part, I am using xarray to work with microscopy data in a biological context, and would be happy to share a snippet or two.

**Comment by rabernat** [comment]
I don't think xarray has caught on in astronomy and I'm curious why. From an outsider's perspective, it seems ideal for astronomy data.

Maybe because they already have things like astropy and yt?

**Comment by jhamman** [comment]
@jakevdp - do you know of any astronomy applications of xarray?

**Comment by jakevdp** [comment]
I've not seen any... I think the main reason is that the field embraced Python years before xarray was created, so there were already workable solutions in place.

**Comment by fujiisoup** [comment]
My colleague in astronomy said that his common data format was a set of few images taken with long exposure time and he didn't need to take care of *big data* until recently. I am not sure it is generally true for astronomy field.
However, one of the recent streams in astrophysics is definitely the combination of the statistics and the huge amount of measurements, such as thousands of images constantly taken by telescopes. I suspect xarray could play more role also in this field (I am also an outsider though...).

**Comment by fujiisoup** [comment]
For my part, I am working in the nuclear fusion field, where we have many kinds of high-dimensional measurement data. The size of each measurement is not so huge, but we have huge kinds of data taken on different coordinates. xarray also fits such situation.
(I am also happy to share my snippest but my data is not big and I am not sure this fits the tutorial concept.)

xarray certainly helps me a lot, but I don't hear any usages of xarray around me. It might be a historical reason (many are still using a comersial software  such as IDE). I think there is a certain *market* also in my field.

**Comment by GiorgioBalestrieri** [comment]
@jhamman will your tutorial at UCAR be available online at some point? Are you still planning to present at SciPy 2018? I'm not part of the dev team but I really think it would be great to have a proper video with a tutorial and the related repo. It would really help getting people aware of/excited about xarray!

**Comment by jhamman** [comment]
@GiorgioBalestrieri - Yes. Both tutorials will be made available. Stay tuned!

**Comment by rabernat** [comment]
Bummer Joe! It sounds like you had a great proposal, but maybe the instructions for the tutorial abstract weren’t clear enough in terms of the detail required.

We should not get discouraged and instead set our sights on other opportunities (including scipy 2019) for presenting xarray tutorials. Recent comments on the mailing list suggest that a comprehensive xarray tutorial is something our community really needs.

**Comment by fmaussion** [comment]
I'm actually impressed by the quality and number of reviews, good for Scipy!

I feel particularly concerned about:

> The tool can be tricky to use right, and the documentation can be sparse in some places.

I would hope to meliorate this whenever possible.
