### ISSUE TITLE
Whether should we follow pandas or numpy if they have different API?

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1886]
In working with #1883, I noticed that our (and numpy's) `std` and `var` work differently from pandas.
Pandas assumes `ddof=1` [as default](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.std.html), while we assume `ddof=0`.
Do we want to match these behaviors to pandas?

```python
In [1]: import numpy as np
   ...: import xarray as xr
   ...: da = xr.DataArray([0, 1, 2], dims='x', name='da')

In [2]: da.std()
Out[2]: 
<xarray.DataArray 'da' ()>
array(0.816496580927726)

In [3]: da.to_dataframe().std()
Out[3]: 
da    1.0
dtype: float64

In [4]: da.std(ddof=1)
Out[4]: 
<xarray.DataArray 'da' ()>
array(1.0)
```

**Comment by fujiisoup** [comment]
I also noticed that panda's `argmin` and `argmax` behave differently from those of `numpy`.
I think we should follow pandas because **the extension of pandas** is our core concept.
Currently, our `argmin` and `argmax` behave as those of numpy.

**Comment by maxim-lian** [comment]
Re the `argmin` / `argmax` - I think pandas is changing: https://github.com/pandas-dev/pandas/issues/16830

**Comment by shoyer** [comment]
I think a distinction between `argmin`/`idxmin` is useful -- and it seems that pandas is likely to restore this in the future as well.

The difference between `ddof=0` and `ddof=1` has never mattered to me. I suppose it probably does make more sense for us to follow pandas here (it's what we usually do), but I don't know if it's worth the trouble of changing it.

**Comment by fujiisoup** [comment]
Thanks.
I did not notice pandas issue. OK. I will follow numpy's API for argmin/argmax.

> The difference between ddof=0 and ddof=1 has never mattered to me

Me neither.
> but I don't know if it's worth the trouble of changing it.

OK. Agreed. I keep the current API.
