### ISSUE TITLE
Zarr keys include variable name

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#1894]
When using open_zarr on a dataset with many variables the keynames include the variable name, like 

    ('zarr-temperature-1234', 1, 3, 2)

In the distributed scheduler these keynames get shortened to prefixes like `zarr-temperature` and used both for scheduling heuristics (all keys with the same prefix are expected to take similar-ish amounts of time) and for diagnostics, such as in the progress bar plot below:

![image](https://user-images.githubusercontent.com/306380/35920009-9f1fbeda-0be4-11e8-8f3f-061387bdb149.png)

We may want to avoid including the variable name into the keyname here in order to avoid breaking these out into several groups.  Instead you might consider putting the variable name within the key as another member of the tuple like the following:

    ('zarr-1234', 'temperature', 1, 3 ,2)

**Comment by jhamman** [comment]
I think the relevant lines here are:

https://github.com/pydata/xarray/blob/1d3239982db9778e89a48fe55b01d0a525673a7a/xarray/backends/zarr.py#L484-L486

This should be an easy fix.
