### ISSUE TITLE
Failure in test_cross_engine_read_write_netcdf3

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#1909]
Two unit tests are failing in the latest git master:
- GenericNetCDFDataTest.test_cross_engine_read_write_netcdf3
- GenericNetCDFDataTestAutocloseTrue.test_cross_engine_read_write_netcdf3

Both with the message:

```
xarray/tests/test_backends.py:1558: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
xarray/backends/api.py:286: in open_dataset
    autoclose=autoclose)
xarray/backends/netCDF4_.py:275: in open
    ds = opener()
xarray/backends/netCDF4_.py:199: in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
netCDF4/_netCDF4.pyx:2015: in netCDF4._netCDF4.Dataset.__init__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   OSError: [Errno -36] NetCDF: Invalid argument: b'/tmp/tmpwp675lnc/temp-1069.nc'

netCDF4/_netCDF4.pyx:1636: OSError
```

Attaching conda list: [conda.txt](https://github.com/pydata/xarray/files/1722111/conda.txt)

**Comment by shoyer** [comment]
Thanks for the report. Can you share the output of `xr.show_versions()`?

**Comment by crusaderky** [comment]
INSTALLED VERSIONS
------------------
commit: 5a07e3a367c7afef3095046a4f73f8cfa4968aeb
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-32-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.0+dev59.g33660b7
pandas: 0.22.0
numpy: 1.14.0
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: 0.5.0
h5py: 2.7.1
Nio: None
zarr: 2.1.4
bottleneck: None
cyordereddict: None
dask: 0.17.0
distributed: 1.21.0
matplotlib: 2.1.2
cartopy: None
seaborn: None
setuptools: 38.4.0
pip: 9.0.1
conda: 4.4.10
pytest: 3.3.2
IPython: 6.2.1
sphinx: None

**Comment by jhamman** [comment]
@crusaderky - I'm working through some old issues. If you are still seeing this error, please feel free to reopen this issue. I'm guessing all the backend refactors this year have fixed whatever was going on here.
