### ISSUE TITLE
Pynio tests are being skipped on TravisCI

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#1910]
#### Problem description

Currently on Travis, the Pynio tests are being skipped. The `py27-cdat+iris+pynio` is supposed to be running tests for each of these but it is not. 

https://travis-ci.org/pydata/xarray/jobs/341426116#L2429-L2518

I can't look at this right now in depth but I'm wondering if this is related to #1531.

reported by @WeatherGod

**Comment by WeatherGod** [comment]
Zarr tests and pydap tests are also being skipped

**Comment by WeatherGod** [comment]
Looking through the travis logs, I do see that pynio is getting installed.

**Comment by jhamman** [comment]
Zarr should be getting skipped; we're waiting on a zarr's 2.2 release. Pydap may be getting skipped because it requires network access.
