### ISSUE TITLE
Not compatible with PyPy and dask.array.

### ISSUE THREAD

**Issue by tlechauve** [pydata/xarray#1935]
Hi,

#### Problem description
With a fresh pypy2 installation, i installed dask and xarray then tried to import xarray but it failed. According to the logs dask trigger a "weak reference" exception.

- Dask works by himself (with or without xarray installed)
- Without installing dask, xarray works.
- But both installed xarray don't work.

#### Question
Is there a compatibility problem with PyPy ? With the standard python everything works, but i have performance issues.

#### Example

```bash
$ pip install dask[array]
   ... OK
$ pip install xarray
   ... OK
$ pypy -c "import dask"
  ... OK
$ pypy -c "import xarray"
Traceback (most recent call last):
  File "<module>", line 1, in <module>
  File "/opt/pypy/site-packages/xarray/__init__.py", line 18, in <module>
    from .backends.api import (open_dataset, open_dataarray, open_mfdataset,
  File "/opt/pypy/site-packages/xarray/backends/__init__.py", line 6, in <module>
    from .common import AbstractDataStore
  File "/opt/pypy/site-packages/xarray/backends/common.py", line 31, in <module>
    GLOBAL_LOCK = Lock()
  File "/opt/pypy/site-packages/dask/utils.py", line 771, in __init__
    SerializableLock._locks[self.token] = self.lock
  File "/opt/pypy/lib-python/2.7/weakref.py", line 131, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/opt/pypy/lib-python/2.7/weakref.py", line 304, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'thread.lock' object

```

Thanks for your help

**Comment by shoyer** [comment]
It's exciting to see people testing xarray with PyPy! Once we get this working, we should consider adding a continuous integration test.

The specific problem here seems to be `dask.SerializableLock`, which xarray initializes upon import:
https://github.com/dask/dask/blob/de6c2a49d76066abb51085570816322f063fc5c5/dask/utils.py#L737

I think this could be reproduced with something like the following using only the standard library:
```
import weakref
import threading

lock = threading.Lock()

locks = weakref.WeakValueDictionary()
locks['foo'] = lock
```

This works with CPython, but maybe not with pypy.

CC @mrocklin in case he has any ideas. Otherwise if my code to reproduce works, I would suggest reporting this upstream to PyPy.

**Comment by mrocklin** [comment]
+1 on reporting upstream if convenient

**Comment by tlechauve** [comment]
@shoyer you are right !

```
Python 2.7.8 (2.4.0+dfsg-3, Dec 20 2014, 13:30:46)
[PyPy 2.4.0 with GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import weakref
>>>> import threading
>>>> lock = threading.Lock()
>>>> locks = weakref.WeakValueDictionary()
>>>> locks['foo'] = lock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pypy/lib-python/2.7/weakref.py", line 108, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/usr/lib/pypy/lib-python/2.7/weakref.py", line 274, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'thread.lock' object
```

**Comment by tlechauve** [comment]
Reported https://bitbucket.org/pypy/pypy/issues/2689/_threadlock-is-not-weakrefable

**Comment by benbovy** [comment]
> With the standard python everything works, but i have performance issues.

Can I ask what kind of performance issues do you have? I don't have much experience with PyPy, I'm just curious on cases where using xarray with PyPy represents a real advantage over using it with CPython.

**Comment by tlechauve** [comment]
HI @benbovy,

Actually its not really an issue and its not related to xarray, i'm using [falcon](https://falconframework.org) to make a REST API which provide netCDF data with xarray/dask.

According to falcon [benchmarks](https://falconframework.org/#sectionBenchmarks), pypy has better performance. But maybe in this case i should use CPython.

**Comment by jhamman** [comment]
@tlechauve - If your REST API is open source, would you mind sharing a link? I'd be interested to see what you're up to.

**Comment by tlechauve** [comment]
@jhamman I'm working on a light/python version of Thredds.  it's not planned for now to be Open-source but i will think about it when a stable version will be available.

**Comment by dopplershift** [comment]
@tlechauve One way or another, I'm sure @lesserwhirls would be interested to hear your thoughts on THREDDS.

**Comment by lesserwhirls** [comment]
Sounds interesting!

**Comment by jhamman** [comment]
I'm going to close now seeing that the upstream/pypy issue has been closed.

@tlechauve - please keep us updated on the pypy integration of xarray and the development of your REST API.
