### ISSUE TITLE
building doc is failing for the release 0.10.1

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1944]
I found the following page fails
http://xarray.pydata.org/en/stable/examples/weather-data.html

**Comment by shoyer** [comment]
Oops. See https://github.com/pydata/xarray/pull/1945.

**Comment by fujiisoup** [comment]
There is another collapse in missing value section
http://xarray.pydata.org/en/stable/computation.html#missing-values

**Comment by jhamman** [comment]
I'm also seeing a failure here: http://xarray.pydata.org/en/latest/dask.html

**Comment by shoyer** [comment]
OK, so apparently we need to adjust our doc build so it clearly fails when an expected error is encountered.

**Comment by fujiisoup** [comment]
Update a fix also for the dask section.

**Comment by benbovy** [comment]
Also here: http://xarray.pydata.org/en/latest/io.html#zarr

I guess this one will be fixed soon with the next zarr release.

**Comment by fujiisoup** [comment]
Reopened as zarr page is still failed.

**Comment by benbovy** [comment]
Apparently, the next zarr release is planned for [next Monday](https://github.com/zarr-developers/zarr/issues/242#issuecomment-369744434). Also because zarr support is experimental, I don't think we need to fix anything on the xarray side, just wait for the next zarr release.

**Comment by fujiisoup** [comment]
The zarr page is now built suceessfully
