### ISSUE TITLE
Adding NCL colortables to xarray

### ISSUE THREAD

**Issue by serazing** [pydata/xarray#1948]
I really like [NCL colortables](https://www.ncl.ucar.edu/Document/Graphics/color_table_gallery.shtml) and I use them along with matplotlib. I have all the tables stored in a JSON file and a function to convert them into matplotlbi cmaps. 

I was thinking to add them to xarray so one could call these colormaps as:

```python
 xarray.cm.cmapname
```
or 

```python
 xarray.plot.cm.cmapname
```

Let me know if someone is interested in this option, for which I could send a pull request.

**Comment by shoyer** [comment]
Unfortunately, I don't think this is a good fit for xarray. We try to restrict ourselves to functionality that is (1) domain agnostic and (2) based around data processing. Color tables are pretty outside our focus.

**Comment by jhamman** [comment]
@serazing - I wonder if pushing this functionality upstream to matplotlib/cartopy/seaborn would be a better fit?

**Comment by serazing** [comment]
Alright, this might be a better idea. I'll try to suggest this functionality to matplotlib first.

**Comment by jhamman** [comment]
Thanks @serazing. I'm going to close this for now but feel free to reopen if there is more to discuss down the road.
