### ISSUE TITLE
numpy 1.11 support for apply_ufunc

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1956]
I noticed the failing in rtd 
http://xarray.pydata.org/en/stable/computation.html#missing-values
is because it still uses numpy=1.11 which does not support `signature` argument for `np.vectorize`.

This can be easily fixed (just bumping up numpy's version on rtd), 
but as our minimum requirement is numpy==1.11, we may need to take care of this in `xr.apply_ufunc`.

**Comment by shoyer** [comment]
I think we should just add an better error message about a newer version of NumPy being required. Backporting the changes to `np.vectorize` would also be pretty easy (see https://github.com/numpy/numpy/pull/8054).
