### ISSUE TITLE
Should we be testing against multiple dask schedulers?

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#1971]
Almost all of our unit tests are against the dask's default scheduler (usually dask.threaded). While it is true that beauty of dask is that one can separate the scheduler from the logical implementation, there are a few idiosyncrasies to consider, particularly in xarray's backends. To that end, we have a few tests covering the integration of the distributed scheduler with xarray's backends but the test coverage is not particularly complete. 

If nothing more, I think it is worth considering tests that use the threaded, multiprocessing, and distributed schedulers for a larger subset of the backends tests (those that use dask).

*Note, I'm bringing this up because I'm seeing some failing tests in #1793 that are unrelated to my code change but do appear to be related to dask and possibly a different different default scheduler ([example failure](https://travis-ci.org/pydata/xarray/jobs/349955403#L6606-L6764)).*

**Comment by shoyer** [comment]
Huh, that's interesting. Yes, I suppose should at least consider parametric tests using both dask's multithreaded and distributed schedulers. Though I'll note that for test we actually set the default scheduler to dask's basic non-parallelized get, for easier debugging:
https://github.com/pydata/xarray/blob/54468e1924174a03e7ead3be8545f687f084f4dd/xarray/tests/__init__.py#L87

For #1793, the key thing would be to ensure that we run the tests in the isolated context without changing the default scheduler.

**Comment by mrocklin** [comment]
FWIW most of the logic within the dask collections (array, dataframe, delayed) is only tested with `dask.local.get_sync`.  This also makes the test suite much faster.

Obviously though for things like writing to disk it's useful to check different schedulers.

**Comment by Karel-van-de-Plassche** [comment]
Seems like the distributed scheduler is the advised one to use in general, so maybe some tests could be added for this one. For sure for diskIO, would be interesting to see the difference.


http://dask.pydata.org/en/latest/setup.html
```
Note that the newer dask.distributed scheduler is often preferable even on single workstations. It contains many diagnostics and features not found in the older single-machine scheduler. The following pages explain in more detail how to set up Dask on a variety of local and distributed hardware.
```

**Comment by jhamman** [comment]
Closing this now. The distributed integration test module seems to be covering our IO use cases well enough. I don't think we need to do anything here at this time.
