### ISSUE TITLE
Tests are failing caused by zarr 2.2.0

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#1979]
#### Problem description
Tests are failing due to the release of zarr 2.2.0

Travis's log
https://travis-ci.org/pydata/xarray/jobs/351566529

**Comment by rabernat** [comment]
This is the same as #1955, although now the error is on the non-allowed failures.

**Comment by rabernat** [comment]
It should be fixed by #1793, but could also be fixed by a two-line PR like this

https://github.com/jhamman/xarray/blob/3c2ffbf5b85299a59e0fa12fdec8dff03346527f/xarray/backends/zarr.py#L344-L345
