### ISSUE TITLE
dataArray is much slow than pandas panel when get/set value,is it nomral ? or i writh code in wrong way ?

### ISSUE THREAD

**Issue by Chaos2020** [pydata/xarray#1987]
#### Code with Panel@pandas 0.22
```python
for item, frame in pnDayMA.iteritems():   ## 5000 items with 1000 data for each item
     #print("Caculating EMA for "+ item )
     frame=pnD.loc[item,:,'CLOSE'].dropna()
     indata= frame.values
     d = frame.index
     pnDayMA.loc[item,d,'EMA3'] = talib.EMA(indata,timeperiod=3)
     pnDayMA.loc[item,d,'EMA5'] = talib.EMA(indata,timeperiod=5)
```

#### Code with DataArray@xarray 0.10.1
```python
for item in list(xD.get_index('CODE')):
    #print("Caculating EMA for "+ item )
    try:
        f=xD.loc[item,:,'CLOSE'].dropna(dim='DATE')
        indata=f.values
        f_date=list(f.get_index('DATE'))
        xDayMA.loc[item,f_date,'EMA3']  =talib.EMA(indata,timeperiod=3)
        xDayMA.loc[item,f_date,'EMA5']  =talib.EMA(indata,timeperiod=5)
```
`
#### Problem description

with those code, Panel solution is 50% faster than xarray
Is it normal ? or I use xarray in wrong way ?
thanks for any comments

**Comment by fujiisoup** [comment]
Can you show / upload an example data for the comparison?
Assignment of xarray is not super efficient, as we check several things.
I guess removing a loop may improve the efficiency (but not yet checked).

```python
# Assuming xD.dims == ('x', 'y', 'z')
indata_ema3 = [talib.EMA(indata.values, timeperiod=3) 
               for indata in xD.sel(z='CLOSE').transpose('x', 'y')]
indata_ema5 = [talib.EMA(indata.values, timeperiod=5) 
               for indata in xD.sel(z='CLOSE').transpose('x', 'y')]

xDayMA.loc[xD['CODE'], f['DATE'], 'EMA3'] = indata_ema3
xDayMA.loc[xD['CODE'], f['DATE'], 'EMA5'] = indata_ema5
```

**Comment by Chaos2020** [comment]
Attached is profile files generated by cProfile , FYI

[panel.py.profile.zip](https://github.com/pydata/xarray/files/1809505/panel.py.profile.zip)
[xarray.zip](https://github.com/pydata/xarray/files/1809506/xarray.zip)

**Comment by fujiisoup** [comment]
It looks our indexing takes a long time.
Please consider assigning values at once not by each.
In order to make the vectorized assignment, you can pass vectors as indexers of `.loc[]`.

**Comment by shoyer** [comment]
To my knowledge, no effort has gone into optimizing up this code path. I would not be surprising if it could be significantly sped up. But I agree with @fujiisoup that it is much more efficient do to vectorized assignment/indexing.

**Comment by Chaos2020** [comment]
so Pandas.Panel with vectorized assignment/indexing is the still the faster way , right ?

**Comment by fujiisoup** [comment]
Though I am not familiar with the core logic of pandas.Panel, our assignment should be as fast as the assignment of np.ndarray (because we use it internally), except for the overhead that is called only once.

Also, pandas are deprecating Panel and recommend to use `MultiIndex` or `xarray` for high dimensional data.
see https://pandas.pydata.org/pandas-docs/stable/dsintro.html#deprecate-panel

**Comment by shoyer** [comment]
Vectorized assignment/indexing will be much faster for both xarray.DataArray and pandas.Panel, enough so that I suspect it will no longer be a performance bottleneck.  I don't know which would be faster.

**Comment by Chaos2020** [comment]
I tried vectorized assignment,  with pandas  and xarray
yes, it speed up a lot.( 140s ==> 40s)

and xarray win this time (38s vs 44s,  more than 10% faster than pandas)
so yes, i used xarray in wrong way
thansk a lot , guys
