### ISSUE TITLE
Inconsistent type conversion when doing numpy.sum gvies different results

### ISSUE THREAD

**Issue by MattEttus** [pydata/xarray#1989]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
np.sum(x).data

and 

np.sum(x.data)

give different values when x.data is type float32.  
```
#### Problem description
For my arrays, this results in a ~1% error for the two versions.  np.sum(x).data is apparently promoting the float32 array to float64 before summing.

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Expected Output
 @davidh-ssec
#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here
Strangely, it says: AttributeError: module 'xarray' has no attribute 'show_versions'
Perhaps I am on a very old version?
</details>

**Comment by davidh-ssec** [comment]
Example:

```
import numpy as np
import xarray as xr
a = xr.DataArray(np.random.random((rows, cols)).astype(np.float32), dims=('y', 'x'))
In [65]: np.sum(a).data
Out[65]: array(499858.0625)

In [66]: np.sum(a.data)
Out[66]: 499855.19

In [67]: np.sum(a.data.astype(np.float64))
Out[67]: 499855.21635645436

In [68]: np.sum(a.data.astype(np.float32))
Out[68]: 499855.19
```

I realized after making this example that nansum gives expected results:
```
a = xr.DataArray(np.random.random((rows, cols)).astype(np.float32), dims=('y', 'x'))
In [83]: np.nansum(a.data)
Out[83]: 500027.81

In [84]: np.nansum(a)
Out[84]: 500027.81

In [85]: np.nansum(a.data.astype(np.float64))
Out[85]: 500027.77103802469

In [86]: np.nansum(a.astype(np.float64))
Out[86]: 500027.77103802469
```

**Comment by shoyer** [comment]
> Strangely, it says: AttributeError: module 'xarray' has no attribute 'show_versions' Perhaps I am on a very old version?

Yes, you're using a version of xarray prior to 0.10.

What value are you using for `rows`/`cols` in your example?

Note that due to a quirk of NumPy, `np.sum(a)` actually corresponds to `a.sum()`. For xarray, `a.sum()` skips NaNs by default, so it's equivalent to `np.nansum()` or `bottleneck.nansum()` (if bottleneck is installed).

**Comment by davidh-ssec** [comment]
@shoyer In my examples `rows = cols = 1000`.

**Comment by fujiisoup** [comment]
I notice that bottleneck does the dtype conversion.
I think in your environment bottleneck is installed.

```python
In [9]: np.sum(a)  # equivalent to a.sum(), using bottleneck
Out[9]: 
<xarray.DataArray ()>
array(499943.21875)

In [10]: np.sum(a.data)  # numpy native
Out[10]: 499941.53

In [11]: a.sum(dim=('x', 'y'))  # multiple dims calls native np.sum
Out[11]: 
<xarray.DataArray ()>
array(499941.53, dtype=float32)
```

It might be an upstream issue.
