### ISSUE TITLE
sel(method='nan') option filling missing values with NaN

### ISSUE THREAD

**Issue by frexvahi** [pydata/xarray#1990]
#### Rationale

I would find it helpful to be able to specify "give me NaNs when the selector is not in the corresponding coordinate rather than raising an IndexError". This could go as a method option e.g. `method='nan'`.

```python
>>> data.dims
 ('time', 'feature')
>>> time_array.dims
 ('base_time', 'offset')
>>> data.sel(time=time_array, method='nan')
 <array with NaNs in place of missing times>
```

Currently I work around the problem by appending a row to the `data` array with time coordinate `NaT` and all values `NaN`, then replacing missing times from `time_array` with `NaT`. However, this gives a FutureWarning from xarray/core/duck_array_ops.py:138: ` In the future, 'NAT == x' and 'x == NAT' will always be False.`

If this is something you would like to see then I could have a go at making a pull request for this.

**Comment by shoyer** [comment]
This is exactly what the `.reindex()` method is design for. You can use it like sel, but it gives the appropriate NaN/NaT value instead of raising an error.

**Comment by frexvahi** [comment]
I tried `.reindex()` and got `ValueError: IndexVariable objects must be 1-dimensional`

**Comment by shoyer** [comment]
> so allowing reindex with a two-dimensional selector would be another solution.

Yes, we want to support that. See https://github.com/pydata/xarray/issues/1553.

We're already written most of the underlying machinery, so it should be pretty easy to add now. There are some backwards compatibility concerns with adjusting this for 1D arrays prior to a breaking release (see [this warning](https://github.com/pydata/xarray/blob/e1dc51572e971567fd3562db0e9f662e3de80898/xarray/core/alignment.py#L350-L356)), but I don't see any reason why we can't enable this for higher dimensional indexers right now.

**Comment by frexvahi** [comment]
OK, that should solve my problem. I will go on using the NaT hack for now and refer back here as and when that stops working because `NaT != NaT`
