### ISSUE TITLE
We should have a expository section in the docs about rolling-window operations

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1991]
Right now `DataArray.rolling()` is only documented in the API docs.

Maybe somewhere in the "Time series data" section would be an appropriate place to add it?

**Comment by fujiisoup** [comment]
We have a small section [here](http://xarray.pydata.org/en/stable/computation.html#rolling-window-operations), but it might be much better if we have more examples.

**Comment by shoyer** [comment]
OK, I don't know how I missed that!
