### ISSUE TITLE
can't do in-place clip() with DataArrays.

### ISSUE THREAD

**Issue by WeatherGod** [pydata/xarray#1997]
#### Code Sample, a copy-pastable example if possible
Where `foo` is a DataArray, there doesn't seem to be a nice way to use `clip()` in-place.
```python
foo.clip(0, None, out=foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    foo.clip(0, None, out=foo)
  File "/rd22/scratch/broot/Programs/xarray/xarray/core/dataarray.py", line 1726, in func
    **kwargs))
  File "/rd22/scratch/broot/Programs/xarray/xarray/core/ops.py", line 205, in func
    return _call_possibly_missing_method(self, name, args, kwargs)
  File "/rd22/scratch/broot/Programs/xarray/xarray/core/ops.py", line 192, in _call_possibly_missing_method
    return method(*args, **kwargs)
TypeError: output must be an array
```
You get a similar exception if you do `np.clip(foo, ..., out=foo)`.

#### Problem description
Note the docstring for `DataArray.clip()`:
```
Help on method clip in module xarray.core.ops:

clip(self, *args, **kwargs) method of xarray.core.dataarray.DataArray instance
    a.clip(min=None, max=None, out=None)
    
    Return an array whose values are limited to ``[min, max]``.
    One of max or min must be given.
    
    Refer to `numpy.clip` for full documentation.
    
    See Also
    --------
    numpy.clip : equivalent function
```
So, the docstring advertises support for `out`.

**Comment by shoyer** [comment]
Hmm. We currently just blindly copy the docstring/method from NumPy here. We should probably update this to clarify that we don't support `out`.

**Comment by WeatherGod** [comment]
MaskedArrays had a similar problem, IIRC, because it was blindly copying the NDArray docstrings. Not going to be easy to do, though.

"we don't support `out`": Is that a general rule for xarray? Any notes on how to do what I want for clip? The function this was in was supposed to be general use (ndarrays and xarrays).

**Comment by fmaussion** [comment]
> "we don't support out": Is that a general rule for xarray?

Not really, but the tendency is to go towards getting rid of inplace operations altogether.  ```np.clip(foo, 0, 0.2, out=foo.values)``` will do what you want though.

**Comment by max-sixty** [comment]
Closing as `inplace` generally removed, reopen if I'm missing something
