### ISSUE TITLE
How to using the two-dimensional array as the attribute of an object 

### ISSUE THREAD

**Issue by lyw615** [pydata/xarray#1999]
#### Code Sample, a copy-pastable example if possible
In my imagination，it's liking the format:
```python
# Your code here
class A():
         ......
a= A(...,array[][])
```
#### Problem description
The array[][] stores int numbers.But i don't know how to achieve it with python codes.Any resolution will be apprecited
[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here

</details>

**Comment by shoyer** [comment]
I'm a little confused. What specifically are you hoping to achieve here? `array[][]` is not valid Python syntax.

**Comment by lyw615** [comment]
I want to use 2d-array to store  some numbers  of attribute  which is meaningful for  my  object.The usage  liking  "array[][]"  just mean its function  which is same as the  function  of  2d-array    "array[][]"   in C language

**Comment by lyw615** [comment]
The point is how to create the 2d-array when defining the attributes of  an object or a class  in python

**Comment by shoyer** [comment]
Please read through our docs on xarray data-structures (http://xarray.pydata.org/en/stable/data-structures.html) to see if that answers your question. You could potentially store a 2D array as coordinates. But I'm still not quite sure what you're trying to achieve here, or how exactly it relates to xarray.

**Comment by lyw615** [comment]
Sorry,there is little relationship to xarray.Just because i think you could also resolve the problem

**Comment by shoyer** [comment]
StackOverflow is a better place for general programming questions.

**Comment by lyw615** [comment]
I am from China.Recently,i can't  visit the website  by  climbing over the internet wall.Because there are important conferences
