### ISSUE TITLE
What is the recommended way to do proper compression/ scaling of vars?

### ISSUE THREAD

**Issue by cwerner** [pydata/xarray#2005]
#### Code Sample, a copy-pastable example if possible

```python
                   if level == 'HIGH':
                        ctype = 'i4'
                    else:
                        ctype = 'i2'
                    max_int = np.iinfo(ctype).max
                    min_val = ds[data_var].min().values
                    max_val = ds[data_var].max().values
                    offset_ = min_val

                    if max_val - min_val == 0:
                        scale_ = 1.0
                    else:
                        scale_ = float(max_int / (max_val - min_val))

```
#### Problem description

Using i2 I mostly get proper output. However, when I try to use i4 or i8 I don't get anything resembling my input...
I write to file with format='NETCDF4_CLASSIC'

My DataArray encoding is:
```python
ENCODING = dict(dtype=ctype, add_offset=offset_, scale_factor=scale_, zlib=True, _FillValue=-9999)
ds[data_var] = ds[data_var].astype(ctype) #, casting='unsafe') 
ds[data_var].extra.update_encoding(ENCODING)
```

extra is added to DataArray like so:
```python
@xr.register_dataarray_accessor('extra')
class TileAccessor(object):
    def __init__(self, xarray_obj):
        self._obj = xarray_obj

    def update_encoding(self, *args, **kwargs):
        """Update the encoding in a xarray DataArray"""
        def _update_encoding(obj, *args, **kwargs):
            obj.encoding.update(*args, **kwargs)
            return obj
        self._obj.pipe(_update_encoding, *args, **kwargs)
```
#### Expected Output

Not sure if one is supposed to use types other than i2 for compressed storage? Or is my approach wrong?

#### Output of ``xr.show_versions()``

<details>
xarray: 0.10.0
pandas: 0.22.0
numpy: 1.14.2
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: None
Nio: None
bottleneck: None
cyordereddict: None
dask: None
matplotlib: 2.1.2
cartopy: None
seaborn: 0.8.1
setuptools: 38.5.2
pip: 9.0.1
conda: None
pytest: 3.4.2
IPython: 6.2.1
sphinx: None
</details>

**Comment by shoyer** [comment]
You gave lots of codes examples, but it's not clear to me yet how it all fits together.

Can you put it into a single code example that I can run to reproduce your problem? A minimum, complete and verifiable example would be best: https://stackoverflow.com/help/mcve

**Comment by cwerner** [comment]
Maybe it's a misconception of mine how compression with add_offset, scale_factor works? 

I tried using i2 dtype (```ctype='i2'```)and only scale_factor (no add_offset) and this looks ok. However, when I switch to i4/i8 type I get strange data in the netCDFs (I write with NETCDF4_CLASSIC if this matters?)...
Is it not possible to use a higher precision integer type for add_offset/ scale_factor encoding to get a better precision of scaled values?

About the code samples: sorry, just copied them verbatim from my script. The first block is the logic to compute the scale and offset values, the second is the enconding application using the decorator-based extension to neatly pipe encoding settings to an data array...

Doing a minimal example at the moment is a bit problematic as I'm traveling...
