### ISSUE TITLE
Is it possible to disable datetime64 encoding?

### ISSUE THREAD

**Issue by kmpaul** [pydata/xarray#2013]
I'm wondering if it is possible to disable Xarray's datetime encoding (i.e., storing it as a datetime64)?  Since Xarray does not (currently) deal with units of other kinds of data, I would assume that it is possible to ignore the time units and read it (from NetCDF, for example) in its "original" form?  Am I correct?  If so, how to "disable datetime encoding"?

**Comment by jhamman** [comment]
@kmpaul - you are looking for either the `decode_cf=False` or the `decode_times=False` options in `open_dataset`: http://xarray.pydata.org/en/latest/generated/xarray.open_dataset.html#xarray.open_dataset

**Comment by kmpaul** [comment]
Oh, good grief!  I looked at that documentation the just yesterday and I completely missed that! 

Sorry.  I'm getting old.
