### ISSUE TITLE
multiple facetgrid.map calls screw up colorbar

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#2024]
#### Code Sample, a copy-pastable example if possible

This code 
```python
da = xr.DataArray(np.random.randn(10, 20, 8))

hdl = da.plot(col_wrap = 4, row='dim_2')
```

yields this image:
![image](https://user-images.githubusercontent.com/2448579/38048698-ea91b60e-327a-11e8-8e7b-8a7544b8d6c8.png)

Then, running this:
```
def mark_point(color='k'):
    plt.plot(10, 4, 'ko')

hdl.map(mark_point)
```

gives

![image](https://user-images.githubusercontent.com/2448579/38048731-0913dd32-327b-11e8-9b9d-be998e9448aa.png)

#### Problem description

Calling `facetgrid.map` calls `facetgrid._finalize_grid` which calls `tight_layout` which screws up the colorbar (eventually).

Quoting https://matplotlib.org/users/tight_layout_guide.html#colorbar
> If you create a colorbar with the colorbar() command, the created colorbar is an instance of Axes, not Subplot, so tight_layout does not work. With Matplotlib v1.1, you may create a colorbar as a subplot using the gridspec.

So the solution could involve writing a custom colorbar function.
#### Output of ``xr.show_versions()``

<details>
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0+dev86.g9abf5ad
pandas: 0.22.0
numpy: 1.14.2
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: 0.5.0
h5py: 2.7.1
Nio: None
zarr: 2.2.0
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.2
distributed: 1.21.4
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 39.0.1
pip: 9.0.1
conda: 4.3.34
pytest: 3.4.2
IPython: 6.2.1
sphinx: 1.7.1
</details>

**Comment by shoyer** [comment]
Hmm. I wonder if it helps to use `add_colorbar=False` and then manually add the colorbar afterwards with the `add_colorbar()` method on the facetgrid object?

**Comment by dcherian** [comment]
There's a bigger issue:

```
shape = (3, 5, 2, 2)
d = xr.DataArray(np.linspace(0, 1, num=np.prod(shape)).reshape(shape), 
                 dims=['y', 'x', 'columns', 'rows'],
                 coords={'y': np.arange(shape[0]),
                         'x': np.arange(shape[1]),
                         'columns': np.arange(shape[2]),
                         'rows': np.arange(shape[3])})
d.y.attrs['units'] = 'yunits'
d.x.attrs['units'] = 'xunits'
d.columns.attrs['units'] = 'cunits'
d.rows.attrs['units'] = 'runits'
```

`g = d.plot(x='x', y='y', col='columns', row='rows')`
![image](https://user-images.githubusercontent.com/2448579/45944886-b8695080-c026-11e8-85fb-35ebd28314f5.png)

`g.map(lambda col, row: plt.plot(col, row, 'wo'), 'columns', 'rows')`
Note that the colorbar and axes-labels are now screwed up.
![image](https://user-images.githubusercontent.com/2448579/45944887-bb644100-c026-11e8-8a22-9b6c30220834.png)

After #2435, the result is good.
![image](https://user-images.githubusercontent.com/2448579/45944896-bdc69b00-c026-11e8-8b5d-ce33198ee9cf.png)
