### ISSUE TITLE
Documentation on assign a value and vectorized indexing

### ISSUE THREAD

**Issue by chiaral** [pydata/xarray#2055]
I was trying to assign a value to a dataset and kept getting no error but also not getting what I wanted.

I then was directed to the Warning at the end of the [Assigning values with indexing](http://xarray.pydata.org/en/stable/indexing.html#assigning-values-with-indexing) and I realized I wasted a lot of time on something that is not possible. 

So I am suggesting a few improvements (some might be feasible, some might not):

A) I am not sure if it is possible, but maybe add a proper error to such thing - try to assign values when using any of the indexing methods - would be great. 
B) if A is not possible, maybe in the [DataArray page](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html) you should repeat the Warning. In this second page, in fact, you state: "Select or assign values by integer location (like numpy) : x[:10] or by label (like pandas): x.loc['2014-01-01'] or x.sel(time='2014-01-01')." Which I think it's in contradiction, or at least it's not crystal clear.
C) you should add to the text of the Warning to use vectorized indexing, so people know how to fix the issue.  
D) Also for the [vectorized indexing page](http://xarray.pydata.org/en/stable/indexing.html#vectorized-indexing), an example using .sel could help. For example, something like the following, which I think it should work (using your same dataArray within the vectorized indexing help) 
```
ind_x = da.x==0

ind_y = da.y=='c'

da[ind_x, ind_y] =30

```
E) If I am completely off in the solution that i used in the code above, then add an example that takes care of this. In your examples you use 0s and 1s, which is not what you want to do if you have multiple lat and lon and time coordinates that you want to use correctly.

I hope I made some sense..

**Comment by shoyer** [comment]
> A) I am not sure if it is possible, but maybe add a proper error to such thing - try to assign values when using any of the indexing methods - would be great.

Yes, totally agreed that this would be ideal, but unfortunately I don't think this is possible. Pandas attempted something with its SettingWithCopy warnings, but in most cases I think those just add noise and warm about something that isn't actually a problem.

> B) if A is not possible, maybe in the DataArray page you should repeat the Warning. 

I don't know if it makes sense on the overview page for DataArray, but we should definitely repeat it on the doc page for `DataArray.sel`:
http://xarray.pydata.org/en/stable/generated/xarray.DataArray.sel.html

> C) you should add to the text of the Warning to use vectorized indexing, so people know how to fix the issue.

Yes, agreed!

D) Also for the vectorized indexing page, an example using .sel could help. For example, something like the following, which I think it should work (using your same dataArray within the vectorized indexing help)

Yes, I think we should add an example of using vectorized indexing for assignment.

We already have some examples of using it with `.sel()` further down the page, but I agree that label-based indexing should probably be more strongly emphasized: http://xarray.pydata.org/en/stable/indexing.html#more-advanced-indexing

**Comment by chiaral** [comment]
Regarding B) 

I think that the current text can lead to confusion:

> Select or assign values by integer location (like numpy): x[:10] or by label (like pandas): x.loc['2014-01-01'] or x.sel(time='2014-01-01').

because selecting and assigning are discussed together. I think that should be fixed too.

**Comment by shoyer** [comment]
> because selecting and assigning are discussed together. I think that should be fixed too.

Agreed, it is confusingly worded. I missed that when I reread it earlier.

If you're interested in tackling any of these issues, pull requests would be gratefully accepted!  See here for guidelines:
http://xarray.pydata.org/en/stable/contributing.html#contributing-to-the-documentation

**Comment by chiaral** [comment]
I finally had the time to try out this SO suggestion on assigning on multiple dimensions as well (imaging being in need to modify the forcing of a model for a selected area) and it works. These are quite peculiar ways (at least for people not deep into xarray...) to assign values; I am compiling a list of them which IMHO should be added somewhere in the help. I will post them here for discussion, and to make sure they are indeed the most correct way to do it!

**Comment by chiaral** [comment]
For example, using the tutorial data:

```
ds = xr.tutorial.load_dataset('air_temperature')
#add an empty 2D dataarray
ds['empty']= xr.full_like(ds.air.mean('time'),fill_value=0)
#modify one grid point, using where() or loc()
ds['empty'] = xr.where((ds.coords['lat']==20)&(ds.coords['lon']==260), 100, ds['empty'])
ds['empty'].loc[dict(lon=260, lat=30)] = 100
#modify an area with where() and a mask 
mask = (ds.coords['lat']>20)&(ds.coords['lat']<60)&(ds.coords['lon']>220)&(ds.coords['lon']<260)
ds['empty'] = xr.where(mask, 100, ds['empty'])
#modify an area with loc()
lc = ds.coords['lon']
la = ds.coords['lat']
ds['empty'].loc[dict(lon=lc[(lc>220)&(lc<260)], lat=la[(la>20)&(la<60)])] = 100
```

these are examples that I am pretty sure are not on the website, they are I think common in climate scientists workflow, and that it took me quite a while to figure out. I was using a boolean dataarray as well as in the SO example, slowing down my work of quite a bit.

Do they make sense? I can try and add them to the documentation at [Assigning Values with indexing](http://xarray.pydata.org/en/stable/indexing.html#assigning-values-with-indexing) , or is there another place that is more relevant?

**Comment by shoyer** [comment]
@chiaral Yes, I think that would be a good place to add the example of assigning with `.loc`.

The `where` example might be better added to the section on where: http://xarray.pydata.org/en/v0.10.3/indexing.html#masking-with-where

**Comment by shoyer** [comment]
Actually, on further consideration it is probably best to organize the narrative documentation by task/goal (user need), rather than xarray's internal organization of methods (the API docs are for this). So integrating this in the section on "Assigning values with indexing" makes sense for both of these.

Feel free to reorganize the existing material. I think showing how to assign with `.loc` is more important than combined indexing with in-place arithmetic, for example.
