### ISSUE TITLE
Warning on supplying a Dataset to the Dataset constructor

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#2056]
```python

In [1]: import xarray as xr

In [3]: ds=xr.Dataset({'a':xr.DataArray([1,2,3])})

In [4]: xr.Dataset(ds)
/Users/maximilian/drive/workspace/xarray/xarray/core/dataset.py:373: FutureWarning: iteration over an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Iterate over the Dataset.variables property instead to preserve existing behavior in a forwards compatible manner.
  both_data_and_coords = [k for k in data_vars if k in coords]
Out[4]:
<xarray.Dataset>
Dimensions:  (dim_0: 3)
Dimensions without coordinates: dim_0
Data variables:
    a        (dim_0) int64 1 2 3
```
#### Problem description

Currently we run `both_data_and_coords = [k for k in data_vars if k in coords]`, where `data_vars` is the first arg to the constructor. So, when `data_vars` is a `Dataset`, we'll raise a warning.

More importantly: this raises the question of how we should handle `xr.Dataset(ds)`
Currently we retain the `coords`, but discard `attrs`. That seems arbitrary?
I'd have to check, but when we change `__iter__` to only reference `data_vars`, we may also discard `coords`

I don't have a strong view. If you think that `Foo(foo)` should always return `foo` (which is often the case in pandas), then we should retain the full object.
If you think that `foo` is supplied to the `data_vars` arg, then retaining only the `data_vars` seems reasonable

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: a9d1f3a36229636f0d519eb36a8d4a7c91f6e1cd
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.2+dev31.g0a24429
pandas: 0.22.0
numpy: 1.14.2
scipy: 1.0.0
netCDF4: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.2
distributed: None
matplotlib: 2.1.2
cartopy: None
seaborn: 0.8.1
setuptools: 39.0.1
pip: 9.0.3
conda: None
pytest: 3.5.0
IPython: 6.3.0
sphinx: None
</details>

**Comment by shoyer** [comment]
Hmm. This warning message is slightly unfortunate indeed.

> Currently we retain the coords, but discard attrs. That seems arbitrary?

Agreed!

> I don't have a strong view. If you think that Foo(foo) should always return foo (which is often the case in pandas), then we should retain the full object.

Yes, we could defensibly go either way here.

Generally, I don't think this is an important invariant, and it certainly doesn't make sense for every type. But maybe it does make sense for `Dataset`, given that we do do so for `DataArray`:
https://github.com/pydata/xarray/blob/a9d1f3a36229636f0d519eb36a8d4a7c91f6e1cd/xarray/core/dataarray.py#L205-L223

(But to be clear, this wasn't a terribly careful design decision for DataArray, either.)

**Comment by max-sixty** [comment]
Closing with 0.11 release
