### ISSUE TITLE
__contains__ does not work with DataArray

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#2062]
#### Code Sample, a copy-pastable example if possible

```python
>>> da = xr.DataArray([0, 1, 2], dims='x')
>>> 0 in da
( warning omitted )
False
>>> 0 in da.values
True
```

#### Problem description

`__contains__` should work as np.ndarray does.

#### Expected Output

```python
>>> 0 in da
True
```

**Comment by shoyer** [comment]
Indeed, that's what the omitted warning says:
```
In [6]: 0 in da
/Users/shoyer/miniconda3/envs/xarray-py36/bin/ipython:1: FutureWarning: xarray.DataArray.__contains__ currently checks membership in DataArray.coords, but in xarray v0.11 will change to check membership in array values.
  #!/Users/shoyer/miniconda3/envs/xarray-py36/bin/python
Out[6]: False
```

https://github.com/pydata/xarray/issues/1267 is the tracking issue.

Note also that NumPy's `__contains__` has its own issues: https://github.com/numpy/numpy/issues/3016

**Comment by fujiisoup** [comment]
I just noticed that I did not read the warning at all ot oTL.
Closing.
