### ISSUE TITLE
open_mfdataset can't handle many files

### ISSUE THREAD

**Issue by pgierz** [pydata/xarray#2066]
#### Code Sample, a copy-pastable example if possible

It appears as if the `open_mfdataset` cannot handle many files (many here = 1200) 

```python
ensemble = xr.open_mfdataset("/scratch/simulation_database/incoming/Eem125-S2/output/Eem125-S2_echam5_main_mm_26*.nc")

OSError                                   Traceback (most recent call last)
<ipython-input-4-038705c4f255> in <module>()
----> 1 ensemble = xr.open_mfdataset("/scratch/simulation_database/incoming/Eem125-S2/output/Eem125-S2_echam5_main_mm_26*.nc")

~/anaconda3/lib/python3.6/site-packages/xarray/backends/api.py in open_mfdataset(paths, chunks, concat_dim, compat, preprocess, engine, lock, data_vars, coords, **kwargs)

~/anaconda3/lib/python3.6/site-packages/xarray/backends/api.py in <listcomp>(.0)

~/anaconda3/lib/python3.6/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, autoclose, concat_characters, decode_coords, engine, chunks, lock, cache, drop_variables)

~/anaconda3/lib/python3.6/site-packages/xarray/backends/netCDF4_.py in open(cls, filename, mode, format, group, writer, clobber, diskless, persist, autoclose)

~/anaconda3/lib/python3.6/site-packages/xarray/backends/netCDF4_.py in _open_netcdf4_group(filename, mode, group, **kwargs)

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno 24] Too many open files: b'/scratch/simulation_database/incoming/Eem125-S2/output/Eem125-S2_echam5_main_mm_260001.nc'
```
#### Problem description

Often, climate simulations produce more than one output file per model component (generally 1 per saved time output, e.g. months, years, days, or something else). It would be good to access all of these as one object, rather than having to combining them by hand before with e.g. `cdo` or some other tool.

#### Expected Output

`ensemble` variable definition gives me back 1 object  😄 

#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-144-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0
pandas: 0.20.3
numpy: 1.13.3
scipy: 0.19.1
netCDF4: 1.3.1
h5netcdf: 0.5.0
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.3
matplotlib: 2.1.0
cartopy: 0.16.0
seaborn: 0.8.0
setuptools: 36.5.0.post20170921
pip: 9.0.1
conda: 4.5.1
pytest: 3.2.1
IPython: 6.1.0
sphinx: 1.6.3
</details>

**Comment by jhamman** [comment]
@pgierz - this use case motivated the development of the `autoclose` feature. Can you give that a try?

```Python
ensemble = xr.open_mfdataset("/scratch/.../*nc, autoclose=True)
```

**Comment by pgierz** [comment]
That seemed to do the trick. Would it be worthwhile to consider putting the default value of `autoclose=True` in the method definition, or would that induce other problems?

**Comment by pgierz** [comment]
I’d be happy taking a shot at contributing an error catch for that. I assume that wouldn’t be too difficult, right?

**Comment by rabernat** [comment]
@pgierz, thanks for volunteering! We would love to see a PR from you. I agree that this should be a pretty simple fix. The error gets raised here I believe:
https://github.com/pydata/xarray/blob/master/xarray/backends/api.py#L565-L566

As is often the case, creating a test for this will probably be harder than resolving the issue itself!

**Comment by jhamman** [comment]
I'm fine with the solution of a better error message but it may end up being easier said than done. IIRC, there are some OS specific behaviors here and I'm not sure if you'll always get an `OSError` that so plainly says: `Too many open files`.

**Comment by dcherian** [comment]
Closing since `autoclose` is not an option any more.
