### ISSUE TITLE
BUG: assigning a DataArray to a Dataset can override unrelated coordiantes

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2068]
#### Code Sample, a copy-pastable example if possible

From StackOverflow: https://stackoverflow.com/questions/49947109/why-does-assigning-xr-ones-like-to-a-dataset-variable-change-unrelated-coordin
```python
import xarray as xr
import numpy as np

A, B, C = 2, 3, 4

ds = xr.Dataset()
ds.coords['source'] = (['a', 'b', 'c'], np.random.random((A, B, C)))
ds.coords['unrelated'] = (['a', 'c'], np.random.random((A, C)))

print('INITIAL:', ds['unrelated'], '\n')

# do 'ones_like' manually
ds['dest-1'] = (['a', 'b'], np.ones((A, B)))

print('AFTER dest-1:', ds['unrelated'], '\n')

ds['dest-2'] = xr.ones_like(ds['source'].isel(c=0))

print('AFTER dest-2:', ds['unrelated'], '\n')
```
Output:
```
INITIAL: <xarray.DataArray 'unrelated' (a: 2, c: 4)>
array([[0.185851, 0.962589, 0.772985, 0.570292],
       [0.905792, 0.865125, 0.412361, 0.666977]])
Coordinates:
    unrelated  (a, c) float64 0.1859 0.9626 0.773 0.5703 0.9058 0.8651 ...
Dimensions without coordinates: a, c

AFTER dest-1: <xarray.DataArray 'unrelated' (a: 2, c: 4)>
array([[0.185851, 0.962589, 0.772985, 0.570292],
       [0.905792, 0.865125, 0.412361, 0.666977]])
Coordinates:
    unrelated  (a, c) float64 0.1859 0.9626 0.773 0.5703 0.9058 0.8651 ...
Dimensions without coordinates: a, c

AFTER dest-2: <xarray.DataArray 'unrelated' (a: 2)>
array([0.185851, 0.905792])
Coordinates:
    unrelated  (a) float64 0.1859 0.9058
Dimensions without coordinates: a
```

#### Problem description

Assigning a variable shouldn't implicitly override unrelated existing coordinates.

#### Expected Output

dest-1 and dest-2 should be the same.

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.111+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.3
pandas: 0.22.0
numpy: 1.14.2
scipy: 0.19.1
netCDF4: None
h5netcdf: None
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: 2.1.2
cartopy: None
seaborn: 0.8.1
setuptools: 39.0.1
pip: 9.0.3
conda: None
pytest: None
IPython: 5.5.0
sphinx: None
</details>

**Comment by fujiisoup** [comment]
I am wondering what is the correct behavior here, i.e. which coordinate should prioritize if there is a coordinate conflict between assigned and assigning objects.

A simpler example is
```python
ds = xr.Dataset({}, coords={'c1': ('x', [0, 1, 2])})
a = xr.DataArray([0, 1, 2], dims='x', coords={'c1': ('x', [2, 1, 2])})
ds['a'] = a  # ds['c1'] is overwritten by a['c1'] 
```

My thought is
+ Drop non-dimensional coordinates of the assigning object (`a` in the above example) if there is a conflict.
+ Raise an error if dimensional-coordinate conflicts.

Which is similar to our indexing rule.

**Comment by shoyer** [comment]
We currently reindex objects that are assigned into an existing dataset, so `ds[name] = dataarray` is equivalent to `ds[name] = dataarray.reindex_like(ds)`. This guarantees that dimension coordinates can't conflict.

I agree that the right solution is that conflicting coordinates on the object being assigned should drop. The model is that the object being assigned to takes precedence.
