### ISSUE TITLE
apply_ufunc can generate an invalid object.

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#2075]
#### Code Sample, a copy-pastable example if possible

`apply_ufunc` can generate an invalid object if the size of the array is changed by ufunc,

```python
In [1]: import numpy as np
   ...: import xarray as xr
   ...: 
   ...: da = xr.DataArray([1, 2, 3], dims=['x'], coords={'x': [0, 0.5, 1]})
   ...: 
   ...: def tile(x):
   ...:     return np.tile(da, [2])
   ...: 
   ...: tiled = xr.apply_ufunc(tile, da, input_core_dims=[['x']], 
   ...:                        output_core_dims=[['x']])
   ...: tiled
   ...: 
Out[1]: 
<xarray.DataArray (x: 6)>
array([1, 2, 3, 1, 2, 3])
Coordinates:
  * x        (x) float64 0.0 0.5 1.0
```

In the above example, `tiled.shape = (6, )` but `tiled['x'].shape = (3,)`.
I think we need a sanity check and drop coordinate if necessary.

#### Problem description

Any of our function should not generate invalid xarray objects.

#### Expected Output

```python
Out[1]: 
<xarray.DataArray (x: 6)>
array([1, 2, 3, 1, 2, 3])
Dimensions without coordinates: x
```

or raise an Error.

#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-119-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.3+dev2.ga0bdbfb
pandas: 0.22.0
numpy: 1.14.0
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: None
h5py: None
Nio: None
zarr: 2.1.4
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.1
distributed: 1.21.1
matplotlib: 2.1.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 38.4.0
pip: 9.0.1
conda: None
pytest: 3.3.2
IPython: 6.2.1
sphinx: 1.7.1

</details>

**Comment by JiaweiZhuang** [comment]
Looks like the same problem as #1931

**Comment by fujiisoup** [comment]
Oops. this was just a duplicate. closing
