### ISSUE TITLE
No file error message using open_mfdataset

### ISSUE THREAD

**Issue by DarrenRay** [pydata/xarray#2077]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here

</details>

**Comment by DarrenRay** [comment]
I am linking to an opendapp server which works fine using xarray.open_dataset(url) on individual files, but I get an error message saying:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Anaconda2\lib\site-packages\xarray\backends\api.py", line 561, in open_mfdataset
    raise IOError('no files to open')
IOError: no files to open

when using xarray.open_mfdataset(url) 

url="http://opendap.bom.gov.au:8080/thredds/dodsC/agcd/tmax/anomaly/r005/01day/"+yr+"/*.nc"

I am using Anaconda. I have updated everything:
xr.show_versions()
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_AU
LOCALE: None.None

xarray: 0.10.3
pandas: 0.20.3
numpy: 1.14.2
scipy: 0.17.1
netCDF4: 1.2.2
h5netcdf: None
h5py: 2.6.0
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.17.2
distributed: 1.21.6
matplotlib: 1.5.1
cartopy: 0.15.0
seaborn: 0.7.1
setuptools: 23.0.0
pip: 9.0.1
conda: 4.4.10
pytest: 2.9.2
IPython: 4.2.0
sphinx: 1.4.1

**Comment by DarrenRay** [comment]
sorry: yr is a string ie "2018" 
ie url="http://opendap.bom.gov.au:8080/thredds/dodsC/agcd/tmax/anomaly/r005/01day/2018/*.nc"

**Comment by jhamman** [comment]
Thanks for the report. Looking at `open_mfdataset`:

https://github.com/pydata/xarray/blob/99b457ce5859bd949cfea4671db5150c7297843a/xarray/backends/api.py#L558-L564

you'll see we are using `glob` to expand the path names. This is not likely to work for URLs. I'm not 100% sure if it is even possible to do a path expansion on OpenDAP datasets. 

If you can do the expansion yourself, that would be the easiest workaround.

**Comment by shoyer** [comment]
Indeed, glob does not work for URLs.

However, we could (and should) improve this error message, to clarify what's going on here. Actually, we should probably raise an error message is `paths` is a string starting with `http://` or `https://` before trying glob.
