### ISSUE TITLE
Should `DataArray.to_netcdf` warn if `self.name is None`?

### ISSUE THREAD

**Issue by willirath** [pydata/xarray#2081]
Currently, `to_netcdf()` will write files  containing a variable named `__xarray_dataarray_variable__` if `self.name is None`.

Should there be a warning to at least notifies the user that it would be a good idea to pick a decent variable name?

**Comment by shoyer** [comment]
I would lean against this, even though I agree of course that for portability it's better to pick a descriptive variable name.

A major audience for `DataArray.to_netcdf()` is xarray users who are new to netCDF and may not use Dataset objects at all, but want an easy way to serialize a DataArray to disk. For these users, such a warning would be spurious.
