### ISSUE TITLE
searching is broken on readthedocs

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#2082]
Searches return no results for me. For example:
http://xarray.pydata.org/en/latest/search.html?q=xarray&check_keywords=yes&area=default

**Comment by shoyer** [comment]
Hmm, I have no idea what went wrong. I filed an issue upstream: https://github.com/rtfd/readthedocs.org/issues/4026

**Comment by shoyer** [comment]
This appears to have been resolved.
