### ISSUE TITLE
Output depends on order in a sum

### ISSUE THREAD

**Issue by TobiasLe** [pydata/xarray#2086]
#### Code Sample

```python
import xarray as xr

a = xr.DataArray([[1, 2], [3, 4], [5, 6]], dims=["dim1", "dim2"])
print(a)

print(a + a[0, :])  # returns the result I would expect
print(a[0, :] + a)  # retruns the transposed result

```
#### Problem description
When two arrays are added with broadcasting, the result depends on the order how they are added. Technically there is nothing wrong about it as long as you access the data only via the dimension names. However, I still think this behavior is somehow confusing and unnecessarily breaks the analogy to numpy.

#### Expected Output
```sh
<xarray.DataArray (dim1: 3, dim2: 2)>
array([[1, 2],
       [3, 4],
       [5, 6]])
Dimensions without coordinates: dim1, dim2

<xarray.DataArray (dim1: 3, dim2: 2)>
array([[2, 4],
       [4, 6],
       [6, 8]])
Dimensions without coordinates: dim1, dim2

<xarray.DataArray (dim2: 2, dim1: 3)>
array([[2, 4, 6],
       [4, 6, 8]])
Dimensions without coordinates: dim2, dim1
```
#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-38-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.2
pandas: 0.19.2
numpy: 1.14.2
scipy: 1.0.1
netCDF4: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: 0.7.1
setuptools: 39.0.1
pip: 9.0.3
conda: None
pytest: 3.5.0
IPython: 5.3.0
sphinx: None

</details>

**Comment by shoyer** [comment]
This is indeed intended behavior. It's true that it's not commutative (`a + b` differs from `b + a`)  but I think it's about the best we an do in this case.

Do you have any suggested alternatives? In principle we could sort dimension names, but consider cases like `('y',) + ('x', 'z')`. Should we insert the dimension `'y'` in the middle, so the result is `('x', 'y', 'z')`? What about `('y',') + ('z', 'x')` or even `('z', 'x') + ('z', 'x')` -- would we sort the existing dimensions?

I think the most important features of our rule for combining different dimension names are that (1) it's a clear generalization of the behavior for matching dimensions and (2) it's simple and easily understood.

**Comment by TobiasLe** [comment]
Thanks for the reply!
Wouldn't my example in your notation be more something like:
``('x', 'y') + ('y',)`` results in a ``('x', 'y')`` array while
``('y',) + ('x', 'y')`` results in a ``('y', 'x')`` array

In such cases I would suggest to always keep the order of dimensions of the array which is not broadcasted.

**Comment by shoyer** [comment]
What about cases like `('x', 'y') + ('y', 'z')` vs `('y', 'z') + ('x', 'y')` where both arrays are broadcast?

**Comment by TobiasLe** [comment]
Ah ok. I did not think about such cases and did not really understand your previous post because I did not know such additions were even possible. Coming from numpy I assumed you could not do such things but of course if dimensions are labeled such additions become possible. 

Maybe it would be a good solution to internally sort the arrays according to the number of dimensions in decreasing order before they are added in the same way as they are added now. Arrays with the same number of dimensions would stay in the order as they are. For example:

``('y',) + ('x',)`` results in ``('y', 'x')`` (the order of arrays before summation is not changed because they have an equal number of dimensions)

``('y',) + ('x', 'y')`` is sorted internally according to the number of dimensions. Then ``('x', 'y') + ('y',)`` is calculated and results in ``('x', 'y')`` and gives the same result es the sum of equivalent numpy arrays would.

for ``('x', 'y') + ('y', 'z')`` nothing would change by sorting because they both have the same number of dimensions.

``('z',) + ('x', 'y')`` would be sorted to ``('x', 'y') + ('z',)`` and result in ``('x', 'y', 'z')``

**Comment by shoyer** [comment]
I haven't proved it, but I think one of advantage of current rule is that it is associative. That is, `a + (b + c)` has the same dimension order as `(a + b) + c`. That's definitely not true if we sort arrays by the number of dimensions first. For example, consider the dimensions resulting from `('y',) + ('x',) + ('x', 'y')` and `('x', 'y') + ('y',) + ('x',)`.

**Comment by TobiasLe** [comment]
I still think its unfortunate that the behavior is different compared to numpy but probably you are right and the current solution makes most sense. Thanks!
