### ISSUE TITLE
strftime and/or format support for DatetimeAccessor

### ISSUE THREAD

**Issue by dopplershift** [pydata/xarray#2090]
There's no easy way currently to control the conversion to string of time values/series. For this purpose, Panda's own `.dt` attribute has an implementation of [strftime](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.dt.strftime.html).

Is there interest in adding similar functionality to xarray?

**Comment by shoyer** [comment]
Sure, I think we would be happy to copy almost any method from `.dt` in pandas to xarray.
