### ISSUE TITLE
Drop win-32 platform CI from appveyor matrix?

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#2094]
Conda-forge has dropped support for 32-bit windows builds (https://github.com/conda-forge/cftime-feedstock/issues/2#issuecomment-385485144). Do we want to continue testing against this environment? The point becomes moot after #1876 gets wrapped up in ~7 months. 

xref: https://github.com/pydata/xarray/pull/1252

**Comment by keewis** [comment]
there's something wrong with the bot, this is not stale but closed

**Comment by max-sixty** [comment]
Yup, I just reported. It does act up occasionally! 

Though it is nice to not have to go through the 550 issue backlog, and mostly rely on it to notify & clean the dead ones...
