### ISSUE TITLE
Avoiding duplicate time coordinates when opening multiple files

### ISSUE THREAD

**Issue by brey** [pydata/xarray#2108]
When opening multiple netCDF files with xr.open_mfdataset(nfiles), if the files have a duplicate time stamp (e.g. when they are a product of a restart and continue process) the final xarray dataset has duplicate time coordinates like,

<xarray.DataArray 'time' (time: 39)>
array(['2010-02-01T00:00:00.000000000', '2010-02-01T01:00:00.000000000',
       '2010-02-01T02:00:00.000000000', '2010-02-01T03:00:00.000000000',
       '2010-02-01T04:00:00.000000000', '2010-02-01T05:00:00.000000000',
       '2010-02-01T06:00:00.000000000', '2010-02-01T07:00:00.000000000',
       '2010-02-01T08:00:00.000000000', '2010-02-01T09:00:00.000000000',
       '2010-02-01T10:00:00.000000000', '2010-02-01T11:00:00.000000000',
       **'2010-02-01T12:00:00.000000000', '2010-02-01T12:00:00.000000000'**,
       '2010-02-01T13:00:00.000000000', '2010-02-01T14:00:00.000000000',
       '2010-02-01T15:00:00.000000000', '2010-02-01T16:00:00.000000000',
       '2010-02-01T17:00:00.000000000', '2010-02-01T18:00:00.000000000',
       '2010-02-01T19:00:00.000000000', '2010-02-01T20:00:00.000000000',
       '2010-02-01T21:00:00.000000000', '2010-02-01T22:00:00.000000000',
       '2010-02-01T23:00:00.000000000', '2010-02-02T00:00:00.000000000',
       '2010-02-02T00:00:00.000000000', '2010-02-02T01:00:00.000000000',
       '2010-02-02T02:00:00.000000000', '2010-02-02T03:00:00.000000000',
       '2010-02-02T04:00:00.000000000', '2010-02-02T05:00:00.000000000',
       '2010-02-02T06:00:00.000000000', '2010-02-02T07:00:00.000000000',
       '2010-02-02T08:00:00.000000000', '2010-02-02T09:00:00.000000000',
       '2010-02-02T10:00:00.000000000', '2010-02-02T11:00:00.000000000',
       '2010-02-02T12:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2010-02-01 2010-02-01T01:00:00 ...

Is there a way to avoid this either while reading or afterwards by dropping the non unique time coordinates?

**Comment by brey** [comment]
To partially answer my issue, I came up with the following post-processing option

1. get the index of the duplicate coordinate values
        val,idx = np.unique(arr.time, return_index=True) 

2. trim the dataset
        arr = arr.isel(time=idx)
 
Maybe this can be integrated somehow...

**Comment by shoyer** [comment]
The pandas `duplicated()` method might be more convenient than using `np.unique()`, e.g., you could equivalently write:
`arr.sel(time=~arr.indexes['time'].duplicated())`

I think we would be open to adding duplicated() to xarray, too, if you or someone else is interested in making a pull request.

**Comment by brey** [comment]
Thanks @shoyer. Your approach works better (one line) plus is consistent with the xarray-pandas shared paradigm. Unfortunately, I can't spare the time to do the PR right now. I haven't done it before for xarray and it will require some time overhead. Maybe someone with more experience can oblige.

**Comment by brey** [comment]
I am adding here a comment to keep it alive. In fact, this is more complicated than it seems because in combining files with duplicate times one has to choose how to merge i.e keep first, keep last or even a combination of the two.

**Comment by max-sixty** [comment]
Is this now fixed by `drop_duplicates`? https://docs.xarray.dev/en/stable/generated/xarray.DataArray.drop_duplicates.html
