### ISSUE TITLE
keep_attrs=True does not work `apply_ufunc` with xr.Variable

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#2114]
#### Code Sample, a copy-pastable example if possible

`keep_attrs=True` works nice for xr.DataArray, but it is neglected for `xr.Variable`

```python
In [2]: import numpy as np
In [3]: import xarray as xr
In [4]: da = xr.DataArray([0, 1, 2], dims='x', attrs={'foo': 'var'})
In [5]: func = lambda x: x*2
In [6]: xr.apply_ufunc(func, da, keep_attrs=True, input_core_dims=[['x']], outpu
   ...: t_core_dims=[['z']])
Out[6]: 
<xarray.DataArray (z: 3)>  # attrs are tracked for xr.DataArray
array([0, 2, 4])
Dimensions without coordinates: z
Attributes:
    foo:      var

In [7]: xr.apply_ufunc(func, da.variable, keep_attrs=True, input_core_dims=[['x'
   ...: ]], output_core_dims=[['z']])
Out[7]: 
<xarray.Variable (z: 3)>  # attrs are dropped
array([0, 2, 4])
```
#### Problem description
`keep_attrs=True` should work also with `xr.Variable`

#### Expected Output
```python
<xarray.Variable (z: 3)>  # attrs are dropped
array([0, 2, 4])
Attributes:
    foo:      var
```

**Comment by fujiisoup** [comment]
Is it an intended behavior? The implementation looks that it is designed so.

I thought that `attrs` is originally an attribute of `xr.Variable` not of `xr.DataArray`, `keep_attrs` should be valid also for this object.

**Comment by shoyer** [comment]
I think I just forgot to implement this when I wrote `apply_ufunc`.
