### ISSUE TITLE
use CF conventions to enhance plot labels

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#2135]
Elsewhere in xarray we use CF conventions to help with automatic decoding of datasets. Here I propose we consider using [CF metadata conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch03s03.html) to improve the automatic labelling of plots. If datasets declare `long_name`, `standard_name`, and `units` attributes, we could use these instead of the variable name to label the relevant axes / colorbars. This feature would have helped me avoid several past mistakes due to my failure to examine the `units` attribute (e.g. data given in cm when I assumed m).

#### Code Sample, a copy-pastable example if possible

Here I create some data with relevant attributes

```python
import xarray as xr
import numpy as np
ds = xr.Dataset({'foo': ('x', np.random.rand(10),
                         {'long_name': 'height',
                          'units': 'm'})},
                coords={'x': ('x', np.arange(10),
                              {'long_name': 'distance',
                               'units': 'km'})})
ds.foo.plot()
```

![image](https://user-images.githubusercontent.com/1197350/40079941-7b7d338a-5857-11e8-8f6e-abd530c29ac8.png)

#### Problem description

We have neglected the variable attributes, which would provide better axis labels.

#### Expected Output

Consider this instead:
```python
def label_from_attrs(da):
    attrs = da.attrs
    if 'long_name' in attrs:
        name = attrs['long_name']
    elif 'standard_name' in attrs:
        name = attrs['standard_name']
    else:
        name = da.name
    if 'units' in da.attrs:
        units = ' [{}]'.format(da.attrs['units'])
    label = name + units
    return label
ds.foo.plot()
plt.xlabel(label_from_attrs(ds.x))
plt.ylabel(label_from_attrs(ds.foo))
```
![image](https://user-images.githubusercontent.com/1197350/40079995-abbabbee-5857-11e8-8296-905bc8545cd1.png)

I feel like this would be a sensible default. But it would be a breaking change. We could make it optional with a keyword like `labels_from_attrs=True`.

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.111+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.3+dev13.g98373f0
pandas: 0.22.0
numpy: 1.14.3
scipy: 1.0.1
netCDF4: 1.3.1
h5netcdf: 0.5.1
h5py: 2.7.1
Nio: None
zarr: 2.2.1.dev2
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.4
distributed: 1.21.8
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 39.1.0
pip: 9.0.1
conda: 4.3.29
pytest: 3.5.1
IPython: 6.3.1
sphinx: None
</details>

**Comment by shoyer** [comment]
Default labels are intended more for convenience than anything else. For publication/production purposes, I suspect labels are almost always been explicitly set, anyways.

So I think this convention makes sense. Let's just document it directly in the plotting docs, maybe even by including your `label_from_attrs()` function to make it fully explicit. That way non-weather/climate users can also make use of it, without referring to the full CF conventions spec.

**Comment by rabernat** [comment]
It would take me some time to wrap my head around the plotting code again, and as a result I don't anticipate having time to work on this any time soon.

I know @dcherian has been digging into the plotting functions a lot. I imagine that he would be able to implement this much faster than I would. Just leaving that suggestion out there... ;)

Obviously this is not an urgent issue.

**Comment by dcherian** [comment]
I can do it. are we agreed that `long_name`, `standard_name`, and `units` are the attributes we want to follow? I think we should also add support for upper-case versions of these (I think I've seen those in the wild)
