### ISSUE TITLE
Exposing/documenting CFTimeIndex as public API

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2140]
I think we expose `CFTimeIndex` as public API, as either `xarray.CFTimeIndex` or `xarray.coding.CFTimeIndex`. Otherwise the only way to make this thing is by putting cftime datetime objects into an xarray object, and/or users will start importing it from `xarray.coding.cftimeindex`.

We should also add it to the API docs, for which it will need at least a minimally informative docstring, too.

CC @spencerkclark @jhamman

**Comment by shoyer** [comment]
Potentially it would also make sense to add a specialized constructor that is an alias for wrapping `cftime.num2date` in a `CFTimeIndex`, but we can save that for later.

**Comment by spencerkclark** [comment]
Great, thanks @jhamman
