### ISSUE TITLE
Upstream changes in Dask

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#2143]
Hi All, 

There are a couple changes coming in dask that might affect XArray code:

1.  We're replacing the `get=dask.threaded.get` keyword with `scheduler='threads'`
2.  We're replacing `dask.set_options(...)` with `dask.config.set(...)` 

Both of the old systems will still work, at least for a version or two, but we plan to remove them in the future.  I thought I'd bring these changes up here so that we can plan a clean deprecation within XArray.  These are also both not yet released, so both features are still up for discussion if this community has additional constraints.

**Comment by shoyer** [comment]
Thanks for the heads up. As far as I can tell from a quick search, the only time we use either of these directly currently is in our test suite. `xarray.Dataset.compute()` and the like forward `**kwargs` directly on to dask, so switching from `get=` to `scheduler=` should not require any intervention on our part.
