### ISSUE TITLE
[REGRESSION] to_netcdf doesn't accept dtype=S1 encoding anymore

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#2149]
In xarray 0.10.4, the dtype encoding in to_netcdf has stopped working, *for all engines*:
```
>>> import xarray
>>> ds = xarray.Dataset({'x': ['foo', 'bar', 'baz']})
>>> ds.to_netcdf('test.nc', encoding={'x': {'dtype': 'S1'}})
[...]

xarray/backends/netCDF4_.py in _extract_nc4_variable_encoding(variable, raise_on_invalid, lsd_okay, h5py_okay, backend, unlimited_dims)
    196         if invalid:
    197             raise ValueError('unexpected encoding parameters for %r backend: '
--> 198                              ' %r' % (backend, invalid))
    199     else:
    200         for k in list(encoding):

ValueError: unexpected encoding parameters for 'netCDF4' backend:  ['dtype']
```
I'm still trying to figure out how the regression tests didn't pick it up and what change introduced it.

@shoyer I'm working on this as my top priority. Do you agree this is serious enough for an emergency re-release? (0.10.4.1 or 0.10.5, your choice)

**Comment by crusaderky** [comment]
1. this is limited to dtype=S1. There's auto tests implemented for dtype=f4 and dtype=int16 (https://github.com/pydata/xarray/blob/master/xarray/tests/test_backends.py#L729-L756), and those work fine.
```
ds = xarray.Dataset({'x': [1, 2]})
ds.to_netcdf('test.nc', encoding={'x': {'dtype': 'f4'}})
```
2. the bug can be worked around by setting the dtype on the variable directly - for which there is an automated test specific for S1 (https://github.com/pydata/xarray/blob/master/xarray/tests/test_backends.py#L333-L343):
```
ds = xarray.Dataset({'x': ['foo', 'bar', 'baz']})
ds['x'].encoding['dtype'] = 'S1'
ds.to_netcdf('test.nc')
```

**Comment by crusaderky** [comment]
@shoyer found the culprit: https://github.com/crusaderky/xarray/commit/3c8935e537e6ec05a83dbe372bfe45d88308d665
Still need to understand why if you set the encoding directly on the variable it works though.

**Comment by crusaderky** [comment]
@shoyer I'm struggling to understand your change - help would be appreciated.

**Comment by shoyer** [comment]
I just got off an airplane (without internet), but I'll try to look into this shortly.

I guess I shouldn't be surprised that https://github.com/pydata/xarray/commit/3c8935e537e6ec05a83dbe372bfe45d88308d665 was the source of this bug -- it was pretty big refactor :(.
