### ISSUE TITLE
groupby should not squeeze out dimensions

### ISSUE THREAD

**Issue by aurghs** [pydata/xarray#2157]
#### Code Sample

```python
arr = xr.DataArray(
    np.ones(3), 
    dims=('x',), 
    coords={
        'x': ('x', np.array([1, 3, 6])),
    }
)
list(arr.groupby('x'))

[(1, <xarray.DataArray ()>
  array(1.)
  Coordinates:
      x        int64 1), 
(3, <xarray.DataArray ()>
  array(1.)
  Coordinates:
      x        int64 3), 
(6, <xarray.DataArray ()>
  array(1.)
  Coordinates:
      x        int64 6)]
```
#### Problem description

The dimension _x_ disappear. I have done some tests and it seems that this problem raise only with strictly ascending coordinates.
For example in this case it works correctly:

```python
arr = xr.DataArray(
    np.ones(3), 
    dims=('x',), 
    coords={
        'x': ('x', np.array([2, 1, 0])),
    }
)
list(arr.groupby('x'))

[(0, <xarray.DataArray (x: 1)>
  array([1.])
  Coordinates:
    * x        (x) int64 0), 
(1, <xarray.DataArray (x: 1)>
  array([1.])
  Coordinates:
    * x        (x) int64 1), 
(2, <xarray.DataArray (x: 1)>
  array([1.])
  Coordinates:
    * x        (x) int64 2)]
```

#### Expected Output

```python
arr = xr.DataArray(
    np.ones(3), 
    dims=('x',), 
    coords={
        'x': ('x', np.array([1, 3, 6])),
    }
)
list(arr.groupby('x'))

[(1, <xarray.DataArray (x: 1)>
  ar1ay([1.])
  Coordinates:
    * x        (x) int64 1), 
(3, <xarray.DataArray (x: 1)>
  array([1.])
  Coordinates:
    * x        (x) int64 3),
 (6, <xarray.DataArray (x: 1)>
  array([1.])
  Coordinates:
    * x        (x) int64 6)]
```

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-41-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.4
pandas: 0.22.0
numpy: 1.14.3
scipy: 1.1.0
netCDF4: 1.3.1
h5netcdf: None
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.17.4
distributed: 1.21.8
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: None
setuptools: 38.4.1
pip: 10.0.1
conda: None
pytest: 3.5.1
IPython: 6.2.1
sphinx: 1.7.4

</details>

**Comment by shoyer** [comment]
This was intentional behavior, but I agree that it is probably a mistake.

You can disable it by setting `squeeze=False` in groupby(), e.g., 
```
arr = xr.DataArray(
    np.ones(3), 
    dims=('x',), 
    coords={
        'x': ('x', np.array([1, 3, 6])),
    }
)
list(arr.groupby('x', squeeze=False))

[(1, <xarray.DataArray (x: 1)>
  array([1.])
  Coordinates:
    * x        (x) int64 1), (3, <xarray.DataArray (x: 1)>
  array([1.])
  Coordinates:
    * x        (x) int64 3), (6, <xarray.DataArray (x: 1)>
  array([1.])
  Coordinates:
    * x        (x) int64 6)]
```

This default behavior can be convenient sometimes because of fewer extra dimensions to worry about. In principle, squeezing makes sense if the grouped coordinate has all unique values, but here we aren't even doing that (I don't know why).

I have two suggested fixes:
- `squeeze=True` should only rely on unique values. Otherwise this really is nearly impossible to predict.
- We should deprecate `squeeze=True` as the default value, and change this default behavior in the next major release.

**Comment by Sibgatulin** [comment]
Not sure if this is a good issue for it. If I am not mistaken, `squeeze` is deprecated not only for `DataArray` but also for `Dataset`? If so, perhaps [the documentation of the latter](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.groupby.html) should be updated too. Besides not mentioning deprecation, it currently also states incorrect default value for squeeze.

**Comment by max-sixty** [comment]
Thanks @Sibgatulin . A PR to remove it from the docs would be very welcome (marking as deprecated is fine too, but often easier to just remove it from the docs once...)

**Comment by Sibgatulin** [comment]
Thanks for quick reply @max-sixty. I opened a [tiny PR](https://github.com/pydata/xarray/pull/9625) to fix the docstring. 
I hesitated dropping `squeeze` from the decstring as it would then diverge from the function signature. And changing the latter would be, perhaps, a fair bit more invasive.
