### ISSUE TITLE
keepdims=True for xarray reductions

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2170]
For operations where arrays are aggregated but then combined, the `keepdims=True` option for NumPy aggregations is convenient.

We should consider supporting this in xarray as well. Aggregating a DataArray/Dataset with `keepdims=True` (or maybe `keep_dims=True`) would remove all original coordinates along aggregated dimensions and return a result with a dimension of size 1 without any coordinates, e.g.,
```
>>> array = xr.DataArray([1, 2, 3], dims='x', coords={'x': ['a', 'b', 'c']})
>>> array.mean(keepdims=True)
<xarray.DataArray (x: 1)>
array([2.])
Dimensions without coordinates: x
```

In case, `array.mean(keepdims=True()` is equivalent to `array.mean().expand_dims('x')` but in general this equivalent does not hold, because the location of the original dimension is lost.

Implementation-wise, we have two options:
1. Pass on `keepdims=True` to NumPy functions like `numpy.mean()`, or
2. Implement `keepdims=True` ourselves, in `Variable.reduce()`.

I think I like option 2 a little better, because it places fewer requirements on aggregation functions. For example, functions like `bottleneck.nanmean()` don't accept a `keepdims` argument.

**Comment by seth-p** [comment]
I second this request.

The following may not be optimal, but seems to work for me as a `keepdims=True` version of `reduce()`:
```
    def dim_preserving_reduce(self, func, dim=None, axis=None, label=None, keep_attrs=False, **kwargs):
        if axis is not None:
            dim = np.take(self._obj.dims, axis, mode='wrap')
        dims = dim if isinstance(dim, (list, tuple)) else [dim]
        dims_coords = {dim: [lab] for dim, lab in zip(dims, (label if isinstance(label, list) else [label]))}
        return self._obj.reduce(func, dim=dims, keep_attrs=keep_attrs, **kwargs). \
            expand_dims(dims, axis=[self._obj.dims.index(dim) for dim in dims]). \
            assign_coords(**dims_coords)
```

**Comment by aldanor** [comment]
Please!

It's really painful in some cases where `keepdims` option is not available, tons of unneeded boilerplate required to mimic the same thing.

**Comment by shoyer** [comment]
Pull requests would be very welcome here.
