### ISSUE TITLE
Errors on pycharm completion

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#2172]
#### Code Sample, a copy-pastable example if possible
```python
# execute:
import numpy as np
import xarray as xr

sample_data = np.random.uniform(size=[2,2000,10000])
x = xr.Dataset({"sample_data": (sample_data.shape, sample_data)})

x2 = x["sample_data"]

# now type by hand:
x2.

```
![grafik](https://user-images.githubusercontent.com/1200058/40391100-8849318e-5e17-11e8-9bf8-f38bba24aa3d.png)

#### Problem description
I'm not completely sure if it's a xarray problem, but each time I enter [some dataset]**.** (note the point) inside PyCharm's python console, I get a python exception instead of some autocompletion.

#### Expected Output
![grafik](https://user-images.githubusercontent.com/1200058/40391316-1e8027d4-5e18-11e8-8f3d-47ba586a2dad.png)

#### Output of ``xr.show_versions()``

<details>
/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.16.9-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

xarray: 0.10.4
pandas: 0.22.0
numpy: 1.14.3
scipy: 1.0.1
netCDF4: None
h5netcdf: 0.5.1
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: None
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 39.2.0
pip: 10.0.1
conda: None
pytest: None
IPython: 6.3.1
sphinx: None
</details>

**Comment by shoyer** [comment]
Thanks for the report. This is definitely a bug, calling `dir()` on an xarray object should never raise an error:
```python
import numpy as np
import xarray as xr

sample_data = np.random.uniform(size=[2,2000,10000])
x = xr.Dataset({"sample_data": (sample_data.shape, sample_data)})
x2 = x["sample_data"]
dir(x2)
```
Results in:
```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-39db0ce27e1d> in <module>()
----> 1 dir(x2)

/usr/local/lib/python3.6/dist-packages/xarray/core/common.py in __dir__(self)
    195         """
    196         extra_attrs = [item
--> 197                        for sublist in self._attr_sources
    198                        for item in sublist
    199                        if isinstance(item, basestring)]

/usr/local/lib/python3.6/dist-packages/xarray/core/dataarray.py in _attr_sources(self)
    494     def _attr_sources(self):
    495         """List of places to look-up items for attribute-style access"""
--> 496         return self._item_sources + [self.attrs]
    497 
    498     @property

/usr/local/lib/python3.6/dist-packages/xarray/core/dataarray.py in _item_sources(self)
    499     def _item_sources(self):
    500         """List of places to look-up items for key-completion"""
--> 501         return [self.coords, {d: self[d] for d in self.dims},
    502                 LevelCoordinatesSource(self)]
    503 

/usr/local/lib/python3.6/dist-packages/xarray/core/dataarray.py in <dictcomp>(.0)
    499     def _item_sources(self):
    500         """List of places to look-up items for key-completion"""
--> 501         return [self.coords, {d: self[d] for d in self.dims},
    502                 LevelCoordinatesSource(self)]
    503 

/usr/local/lib/python3.6/dist-packages/xarray/core/dataarray.py in __getitem__(self, key)
    471         else:
    472             # xarray-style array indexing
--> 473             return self.isel(**self._item_key_to_dict(key))
    474 
    475     def __setitem__(self, key, value):

TypeError: isel() keywords must be strings
```

**Comment by shoyer** [comment]
The source for this issue appears to be that you're using integers as dimension names:
```
>>> x
<xarray.Dataset>
Dimensions:      (2: 2, 2000: 2000, 10000: 10000)
Dimensions without coordinates: 2, 2000, 10000
Data variables:
    sample_data  (2, 2000, 10000) float64 0.8346 0.7321 0.00948 0.04605 ...
```

We do try to support arbitrary hashable values as dimensions names for most operations, but you will have better luck in general using strings.
