### ISSUE TITLE
Formatting error in conjunction with pandas.DataFrame

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#2173]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
import xarray as xr

sample_data = np.random.uniform(size=[2,2000,10000])
x = xr.Dataset({"sample_data": (sample_data.shape, sample_data)})
print(x)

df = pd.DataFrame({"x": [1,2,3], "y": [2,4,6]})
x["df"] = df
print(x)
```
![grafik](https://user-images.githubusercontent.com/1200058/40392190-0e333486-5e1b-11e8-9fcb-08b05eb40cb5.png)

#### Problem description
Printing a xarray.Dataset results in an error when containing a pandas.DataFrame

#### Expected Output
Should print string representation of Dataset

#### Output of ``xr.show_versions()``

<details>
/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.16.9-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

xarray: 0.10.4
pandas: 0.22.0
numpy: 1.14.3
scipy: 1.0.1
netCDF4: None
h5netcdf: 0.5.1
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: None
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 39.2.0
pip: 10.0.1
conda: None
pytest: None
IPython: 6.3.1
sphinx: None

</details>

**Comment by shoyer** [comment]
This is a manifestation of the same issue as https://github.com/pydata/xarray/issues/2172: you are using integers as dimension names, which we don't support very well.

In this case, you end up with mixed integers/strings as dimension names, which means our internal use of `sorted()` in `repr(x)` fails.

**Comment by max-sixty** [comment]
Closed by #2174

**Comment by keewis** [comment]
I can reproduce this on master so there's still more to do to fix this. Maybe we could try sorting using the `str` representation of the dimension names?

**Comment by keewis** [comment]
This works:
```diff
iff --git a/xarray/core/utils.py b/xarray/core/utils.py
index 1126cf30..355fb552 100644
--- a/xarray/core/utils.py
+++ b/xarray/core/utils.py
@@ -453,7 +453,7 @@ class SortedKeysDict(MutableMapping[K, V]):
         del self.mapping[key]
 
     def __iter__(self) -> Iterator[K]:
-        return iter(sorted(self.mapping))
+        return iter(sorted(self.mapping, key=str))
 
     def __len__(self) -> int:
         return len(self.mapping)
```
But maybe it is too naive?

**Comment by keewis** [comment]
let's continue this in #5148
