### ISSUE TITLE
[Feature Request] Visualizing dimensions

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#2175]
Hi, I'm curious how you created your logo:
![grafik](https://user-images.githubusercontent.com/1200058/40421311-c4d18d62-5e8b-11e8-94f4-b217f51b61b0.png)

I'd like to create visualizations of the dimensions in my dataset similar to your logo.
Having a functionality simplifying this task would be a very useful feature in xarray.

**Comment by Hoeze** [comment]
In general, I'd work with data "lego blocks".
Visualizations up to three dimensions would be self-explaining.
One block = scalar, a row of blocks = vector, a plane of blocks = matrix, a cuboid of blocks = 3D array.

Different variables can then be aligned along each dimension.

More than three dimensions could be handled by placing multiple cuboid-blocks (like the blue and pink cuboid in the logo).

The relational sizes of different dimensions should be chosen carefully, maybe with some non-linear scaling?
Or we could simply put points in the middle of large dimensions:
![grafik](https://user-images.githubusercontent.com/1200058/40441983-cf095670-5ec2-11e8-89cb-d872034e57ca.png)
(just an illustration, drawing in 3D with libreoffice draw is hard...)

**Comment by TomNicholas** [comment]
> I gave it up as it was too hard for me to create 3D figures with LaTex

There is a 3dtikz package I think?

Is this issue now superceded by the [discussion going on in #1820](https://github.com/pydata/xarray/pull/1820#issuecomment-509646268)?
