### ISSUE TITLE
Dataset.to_netcdf() cannot create group with engine="h5netcdf"

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#2177]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
import xarray as xr

sample_data = np.random.uniform(size=[2,2000,10000])
x = xr.Dataset({"sample_data": (("x", "y", "z"), sample_data)})

df = pd.DataFrame({"x": [1,2,3], "y": [2,4,6]})
x["df"] = df
print(x)

# not working:
x.to_netcdf("test.h5", group="asdf", engine="h5netcdf")
# working:
x.to_netcdf("test.h5", group="asdf", engine="netcdf4")

```
![grafik](https://user-images.githubusercontent.com/1200058/40453490-a45c3352-5ee5-11e8-8afb-bf939e57d1a5.png)

#### Problem description

h5netcdf does not allow creating groups

#### Expected Output

should save data to "test.h5"

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.16.9-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

xarray: 0.10.4
pandas: 0.22.0
numpy: 1.14.3
scipy: 1.0.1
netCDF4: 1.3.1
h5netcdf: 0.5.1
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: None
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 39.2.0
pip: 10.0.1
conda: None
pytest: None
IPython: 6.3.1
sphinx: None

</details>

**Comment by jhamman** [comment]
Thanks for the report. This does seem like a bug in the h5netcdf backend.
