### ISSUE TITLE
if 10% of ds meets criteria then count

### ISSUE THREAD

**Issue by slharris** [pydata/xarray#2178]
Can I please have help in calculating the total number of days that 10% of my dataset (on each day) is equal to or greater than a given value (e.g. 35). I will then use the where function and loop this through a number of regions and periods but first need help figuring out how to apply the 10% condition. 
Any help will be greatly appreciate.
Sarah

#open dataset
ds=xr.open_mfdataset('/DATA/WRF/sample10years/*/*/*FFDI.nc')

#select period
fireseason=ds['FFDI'].sel(time=slice('2008-09-01', '2009-05-01'))

#resample to daily max
dailymax=fireseason.resample(time='1D').max('time')

#count number of days with dailymax>=35 if at least 10% of that day meets that criteria
dailycountTOTAL = (if 10% of dailymax >= 35).count()

**Comment by shoyer** [comment]
Something like this should work: `((dailymax >= 35).mean(other_dims) > 0.1).sum('time')`, where `other_dims` indicates the other dimensions of your dataset (e.g., `('latitude', 'longitude')`).

**Comment by slharris** [comment]
Thank you that solved my issue
