### ISSUE TITLE
Allow all dims-as-kwargs methods to take a dict instead

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#2188]
Follow up to https://github.com/pydata/xarray/pull/2174

Pasting from https://github.com/pydata/xarray/pull/2174#issuecomment-392111566

- [x] stack
- [x] shift
- [x] roll
- [x] set_index
- [x] reorder_levels
- [x] rolling
- [ ] resample (not yet, we still support old behavior for the first positional arguments with a warning)

...potentially `rename` (I often trip myself up on that)?

**Comment by fujiisoup** [comment]
> ...potentially rename (I often trip myself up on that)?

Me too.
Similarly, `chunks` also?

**Comment by max-sixty** [comment]
Edited above - courtesy of @fujiisoup https://github.com/pydata/xarray/pull/2373, all done apart from resample

**Comment by keewis** [comment]
this should have been closed by #2541.
