### ISSUE TITLE
Parallel non-locked read using dask.Client crashes

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [pydata/xarray#2190]
I'm trying to parallelize my code using Dask. Using their `distributed.Client()` I was able to do computations in parallel. Unfortunately, it seems ~60% of the time is spend in a file lock. As I'm only reading data and doing computations in memory, I should be able to work without a lock, so I tried to pass `lock=False` to `open_dataset`.  Unfortunately this crashes my code. A minimal reproducible example can be found below:

``` python
import xarray as xr
import dask.array as da
from dask.distributed import Client
from IPython import embed

# First generate a file with random numbers
rng = da.random.RandomState()
shape = (10, 10000)
chunks = (10, 10) 
dims = ['y', 'z']
x = rng.standard_normal(shape, chunks=chunks)
da = xr.DataArray(x, dims=dims, name='x')
da.to_netcdf('test.nc')

# Open file without a lock
client = Client(processes=False)
ds = xr.open_dataset('test.nc', chunks=dict(zip(dims, chunks)), lock=False)

# This will crash!
print((ds['x'] * ds['x']).compute())
```
Crashes with (sometimes)
``` python
distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x7ffb69033c50>, key=BasicIndexer((slice(None, None, None), slice(None, None, None)))))), (slice(0, 10, None), slice(5710, 5720, None)))
kwargs:    {}
Exception: RuntimeError('NetCDF: HDF error',)
```
And usually just with `terminated by signal SIGSEGV (Address boundary error)`

#### Output of ``xr.show_versions()``

<details>
``` python
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.16.9-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: 
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.2
pandas: 0.20.3
numpy: 1.14.0
scipy: 0.19.1
netCDF4: 1.4.0
h5netcdf: None
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.17.5
distributed: 1.21.8
matplotlib: 2.1.2
cartopy: None
seaborn: 0.8.1
setuptools: 38.5.1
pip: 10.0.1
conda: None
pytest: 3.4.0
IPython: 6.3.1
sphinx: 1.6.4
```
</details>

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here

</details>

**Comment by shoyer** [comment]
Unfortunately HDF5 doesn't support reading or writing files (even different files) in parallel via the same process, which is why xarray by default adds a lock around all read/write operations from NetCDF4/HDF5 files. So I'm afraid this is expected behavior.

You might have better luck using dask-distributed multiple processes, but then you'll encounter other bottlenecks with data transfer.

**Comment by Karel-van-de-Plassche** [comment]
@shoyer Thanks for your answer. Too bad. Maybe this could be documented in the 'dask' chapter? Or maybe even raise a warning when using open_dataset with `lock=False` on a netCDF4 file?

Unfortunately there seems to be some conflicting information floating around, which is hard to spot for a non-expert like me. It might of course just be that xarray doesn't support it (yet). For example:

- python-netcdf4 support parallel read: https://github.com/Unidata/netcdf4-python/issues/536
- python-netcdf4 MPI parallel write/read: https://github.com/Unidata/netcdf4-python/blob/master/examples/mpi_example.py http://unidata.github.io/netcdf4-python/#section13
- Using h5py directly (not supported by xarray I think): http://docs.h5py.org/en/latest/mpi.html
- Seems to suggest multiple read is fine: https://github.com/dask/dask/issues/3074#issuecomment-359030028

> You might have better luck using dask-distributed multiple processes, but then you'll encounter other bottlenecks with data transfer.

I'll do some more experiments, thanks for this suggestion. I am not bound to netCDF4 (although I need the compression, so no netCDF3 unfortunately), so would moving to Zarr help improving IO performance? I'd really like to keep using xarray, thanks for this awesome library! Even with the disk IO performance hit, it's still more than worth it to use it.

**Comment by shoyer** [comment]
Indeed, HDF5 supports parallel IO, but only with MPI. Unfortunately that
didn't work with Dask, at least not yet.

Zarr is certainly worth a try for performance. The motivation for zarr
(rather than HDF5) was performance with distributed reads/writes,
especially with cloud storage.

**Comment by max-sixty** [comment]
In an effort to reduce the issue backlog, I'll close this, but please reopen if you disagree
