### ISSUE TITLE
Subplots overlap each other using plot() and cartopy

### ISSUE THREAD

**Issue by malmans2** [pydata/xarray#2192]
When subplots are narrow (e.g., small lon range and large lat range), they overlap each other. 
I'm not sure, but I think that `box-forced` in ``ax.set_aspect('equal', 'box-forced')`` would fix the problem (#1397). However, `box-forced` is deprecated since Matplotlib 2.2 and I can't figure out how to fix this.

```python
import xarray as xr
import cartopy.crs as ccrs
```
```python
ds  = xr.tutorial.load_dataset('air_temperature')
ds  = ds.sel(lon = slice(250,  300))
air = ds['air']
transform  = ccrs.PlateCarree()
projection = ccrs.Mercator(air.lon.values.mean(), air.lat.values.min(), air.lat.values.max())
```
```python
p = air.isel(time=[0,1]).plot(transform   = transform, 
                              aspect      = ds.dims['lon']/ds.dims['lat'], 
                              col         = 'time', 
                              col_wrap    = 1, 
                              subplot_kws = {'projection': projection})
for ax in p.axes.flat:
    ax.set_extent((air.lon.values.min(), air.lon.values.max(), 
                   air.lat.values.min(), air.lat.values.max()),
                  crs = transform)
    ax.set_aspect('equal', 'box-forced')
```
![subplots_mercator](https://user-images.githubusercontent.com/22245117/40626432-8eb3b95e-6286-11e8-962e-904bb6718117.png)

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-514.21.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

xarray: 0.10.4
pandas: 0.20.2
numpy: 1.12.1
scipy: 0.19.1
netCDF4: 1.2.4
h5netcdf: 0.5.1
h5py: 2.7.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.2
distributed: 1.18.1
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.7.1
setuptools: 39.1.0
pip: 9.0.1
conda: 4.5.4
pytest: 3.1.2
IPython: 6.1.0
sphinx: 1.6.2

</details>

**Comment by kmuehlbauer** [comment]
Can't reproduce with recent xarray/matplotlib/cartopy. Looks like this has been resolved.

```python
import xarray as xr
import cartopy.crs as ccrs
ds  = xr.tutorial.load_dataset('air_temperature')
ds  = ds.sel(lon = slice(250,  300))
air = ds['air']
transform  = ccrs.PlateCarree()
projection = ccrs.Mercator(air.lon.values.mean(), air.lat.values.min(), air.lat.values.max())
p = air.isel(time=[0,1]).plot(transform   = transform, 
                              aspect      = ds.dims['lon']/ds.dims['lat'], 
                              col         = 'time', 
                              col_wrap    = 1, 
                              subplot_kws = {'projection': projection})
for ax in p.axs.flat:
    ax.set_extent((air.lon.values.min(), air.lon.values.max(), 
                   air.lat.values.min(), air.lat.values.max()),
                  crs = transform)
    ax.set_aspect('equal', 'box')
```
![subplot_issue](https://user-images.githubusercontent.com/5821660/235105075-117e54da-6902-42a9-8607-efb736fc0693.png)

Please reopen, if this is still an issue.
