### ISSUE TITLE
Conversion to and from Iris fails

### ISSUE THREAD

**Issue by tv3141** [pydata/xarray#2201]
#### Code Sample

```python
import numpy as np
import xarray as xr
from iris.coords import DimCoord
from iris.cube import Cube

def test_from_iris_no_var_name():
    latitude = DimCoord(np.linspace(-90, 90, 4), standard_name='latitude')
    cube = Cube([0, 0, 0, 0], dim_coords_and_dims=[(latitude, 0)])
    xr.DataArray.from_iris(cube)
# ValueError: Coordinate latitude has no var_name attribute.

def test_to_iris_non_numeric_coord():
    data = np.random.rand(3)
    locs = ['IA', 'IL', 'IN']
    da = xr.DataArray(data, coords=[locs], dims=['space'])
    xr.DataArray.to_iris(da)
# ValueError: The points array must be numeric.

def test_to_iris_non_monotonic_coord():
    data = np.random.rand(3)
    locs = [0, 2, 1]
    da = xr.DataArray(data, coords=[locs], dims=['space'])
    xr.DataArray.to_iris(da)
# ValueError: The points array must be strictly monotonic.
```
#### Problem description

Each of the tests above fails.

#### Expected Output

First test: Use `standard_name` or something else if `var_name` is not set.
Second/third tests: Fallback to `AuxCoord` if `DimCoord` is too strict.

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-5-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.4
pandas: 0.23.0
numpy: 1.14.3
scipy: 1.1.0
netCDF4: 1.3.1
h5netcdf: 0.5.1
h5py: 2.8.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.5
distributed: 1.21.8
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: None
setuptools: 39.1.0
pip: 10.0.1
conda: None
pytest: 3.5.1
IPython: None
sphinx: None
</details>

**Comment by shoyer** [comment]
Thanks for the report. Yes, it would be nice to fix these cases.
