### ISSUE TITLE
Build timeouts on ReadTheDocs

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2209]
A significant fraction of our [doc builds](https://readthedocs.org/projects/xray/builds/) have started running up against ReadTheDocs's 900 second timeout for builds:
<img width="827" alt="screen shot 2018-06-01 at 8 49 41 am" src="https://user-images.githubusercontent.com/1217238/40850163-c13c1368-6578-11e8-8125-d54b60b7859b.png">

Investigating a few of these, it seems that the main culprit is installing/downloading conda packages in the `conda env create` and `conda install` steps. In some cases, these take over 700 seconds combined, leaving little time for Sphinx, which on its own takes only a couple minutes (but RTD runs it three times for some reason).

**Comment by ocefpaf** [comment]
> Notice that it took 411 seconds to run `conda env create`!

If you are using `conda-forge` bare in mind that our package index is huge and `conda` is not very smart about it. We are looking into possible solution. Pinging @pelson who have some ideas in mind on how to address this problem.

**Comment by pelson** [comment]
> Pinging @pelson who have some ideas in mind on how to address this problem.

The ideas relate to the fetching of the index, which will take orders of magnitude less time than the resolve and download stages in ``conda``. They aren't entirely unrelated though, as a smaller index (the proposal) would result in fewer options for the conda solver to have to work through. No matter what we do, caching the binaries will have the same impact, though it is a challenge to cache sensibly without having a *really* large cache... You may find that caching an environment.yaml actually has more of an impact than caching the binaries themselves (i.e. this means you continue to download the binaries each time, but don't do a conda resolve each time).

**Comment by fmaussion** [comment]
Closed via https://github.com/rtfd/readthedocs.org/issues/4432
