### ISSUE TITLE
Remove bundled viridis colormap

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2211]
We currently bundle the viridis colormap with xarray:
https://github.com/pydata/xarray/blob/1c37d9ce526fecb9fdab2c82b3f46be06f55a128/xarray/plot/utils.py#L15-L26
https://github.com/pydata/xarray/blob/master/xarray/plot/default_colormap.csv

This is unnecessary these days and adds a small amount of packaging complexity. It's not unreasonable to expect at least matplotlib 1.5.x, which comes with viridis installed.

**Comment by jhamman** [comment]
+1.  Do you want me to add this to my minimum versions update (#2204)?

**Comment by shoyer** [comment]
@jhamman sure, that sounds great!

**Comment by jhamman** [comment]
Done in be637d7.

**Comment by jhamman** [comment]
closed via #2204
