### ISSUE TITLE
xarray.Dataset.sel(time='2007-04-12') returns unexpected time dimension

### ISSUE THREAD

**Issue by hans-permana** [pydata/xarray#2213]
#### Code Sample
![image](https://user-images.githubusercontent.com/7643370/40920453-e4952098-680c-11e8-8f9c-148b39a8f591.png)
![image](https://user-images.githubusercontent.com/7643370/40920483-ff212e7a-680c-11e8-9d30-c581ac1a38ae.png)
![image](https://user-images.githubusercontent.com/7643370/40920502-0a197ab2-680d-11e8-855c-73524e996d75.png)

#### Problem description

The current behaviour of xarray.Dataset.sel when selecting time is that it returns a 3D array with the time dimension has a length of 0. 

#### Expected Output

I expect that no time dimension is returned. This behaviour is as expected in xarray.Dataset.isel (look at the Jupyter Notebook screenshot above). 

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

xarray: 0.10.3
pandas: 0.19.0
numpy: 1.11.3
scipy: 1.1.0
netCDF4: 1.2.2
h5netcdf: 0.2.2
h5py: 2.6.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.14.1
distributed: 1.21.8
matplotlib: 2.2.2
cartopy: None
seaborn: 0.8.1
setuptools: 27.2.0.post20161106
pip: 9.0.1
conda: None
pytest: 3.6.0
IPython: 6.4.0
sphinx: None

</details>

**Comment by jhamman** [comment]
@hans-permana - thank you for the report. Can you try to reproduce this behavior with xarray version 0.10.6 (released last week)?

**Comment by hans-permana** [comment]
@jhamman - yes I can reproduce this also in 0.10.6. 

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

xarray: 0.10.6
pandas: 0.19.0
numpy: 1.11.3
scipy: 1.1.0
netCDF4: 1.2.2
h5netcdf: 0.2.2
h5py: 2.6.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.14.1
distributed: 1.21.8
matplotlib: 2.2.2
cartopy: None
seaborn: 0.8.1
setuptools: 27.2.0.post20161106
pip: 9.0.1
conda: None
pytest: 3.6.0
IPython: 6.4.0
sphinx: None

</details>

**Comment by shoyer** [comment]
At first glance, this does look broken. Can you reproduce this with self-contained dummy data? see
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by hans-permana** [comment]
@shoyer I created a [notebook ](https://github.com/esa-esdl/esdl-core/blob/master/notebooks/xarray_2213.ipynb) to reproduce this issue with self-contained dummy data and I think I know when this issue occurs. 

In both cases (my original application and in the notebook example), the time dimension of the DataArray comes with time. When selecting it using **_.sel_**, when time is specified with date and time, the returned DataArray is rightly 2D. However, when the time selection includes only the date (when calling xarray.Dataset.sel), the return includes an unexpected time dimension. In the notebook example, the time dimension is 1 because it could find the right date whereas in my application, time dimension is 0 because it could not find the queried date. I am not sure what is the expected behaviour here.

**Comment by shoyer** [comment]
@hans-permana your example shows a different issue: indexing with a date string yields a time dimension of length 1, rather than squeezing it out (as is the case for datetime strings). This behavior is actually expected/consistent with pandas, although I agree that it is surprising.

**Comment by forman** [comment]
> @hans-permana your example shows a different issue: indexing with a date string yields a time dimension of length 1, rather than squeezing it out 

Nope, look at the screenshot again, the dimension is zero. The very similar issue (if not same) remains and should be considered a bug:

![image](https://user-images.githubusercontent.com/206773/67270122-475dcc00-f4b8-11e9-938f-350b396904de.png)

If I now use `sel()` with a date string without time component, I get a 3D array with zero time dimension:
 
![image](https://user-images.githubusercontent.com/206773/67270196-796f2e00-f4b8-11e9-9851-768019d7798b.png)

However, if I use `sel()` with a date string *with* time component, I get the expected 2D array:

![image](https://user-images.githubusercontent.com/206773/67270563-3497c700-f4b9-11e9-99b0-f5a2336c56ba.png)


#### Output of ``xr.show_versions()``

<details>
python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 26 Stepping 5, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.14.0
pandas: 0.25.2
numpy: 1.16.4
scipy: 1.2.1
netCDF4: 1.5.0.1
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: 2.3.2
cftime: 1.0.3.4
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.0.22
cfgrib: None
iris: None
bottleneck: None
dask: 2.6.0
distributed: 2.6.0
matplotlib: 3.0.3
cartopy: None
seaborn: None
numbagg: None
setuptools: 41.0.1
pip: 19.0.3
conda: None
pytest: 4.4.2
IPython: 7.4.0
sphinx: 2.0.1
</details>

**Comment by max-sixty** [comment]
Closing as stale / no MCVE, please open a new issue with one if this is still a problem
