### ISSUE TITLE
Simplify graph of DataArray.chunk()

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#2214]
```
>>> dict(xarray.DataArray([1, 2]).chunk().__dask_graph__())
{
    ('xarray-<this-array>-7e885b8e329090da3fe58d4483c0cf8b', 0): (<function dask.array.core.getter(a, b, asarray=True, lock=None)>, 'xarray-<this-array>-7e885b8e329090da3fe58d4483c0cf8b', (slice(0, 2, None),)),
    'xarray-<this-array>-7e885b8e329090da3fe58d4483c0cf8b': ImplicitToExplicitIndexingAdapter(array=NumpyIndexingAdapter(array=array([1, 2])))
}
```
There is no reason why this should be any more complicated than da.from_array:
```
>>> dict(da.from_array(np.array([1, 2]), chunks=2).__dask_graph__())
{
    ('array-de932becc43e72c010bc91ffefe42af1', 0): (<function dask.array.core.getter(a, b, asarray=True, lock=None)>, 'array-original-de932becc43e72c010bc91ffefe42af1', (slice(0, 2, None),)),
    'array-original-de932becc43e72c010bc91ffefe42af1': array([1, 2])
}
```
da.from_array itself should be simplified - see twin issue https://github.com/dask/dask/issues/3556

**Comment by shoyer** [comment]
The different is `ImplicitToExplicitIndexingAdapter(array=NumpyIndexingAdapter(array=array([1, 2])))` vs `array([1, 2])`.

In principle, I agree. The challenge here is that xarray, unlike dask, keep very careful track of what types of indexing an array supports. This is important for working with various array storage systems, some of which support many types of indexing and some of which do not.

We should certainly add a short-cut that skips applying `ImplicitToExplicitIndexingAdapter` if `data` is a `numpy.ndarray`, though:
https://github.com/pydata/xarray/blob/bc52f8aa64833d8c97f9ef5253b6a78c7033f521/xarray/core/variable.py#L816-L822

**Comment by dcherian** [comment]
fixed on master.
