### ISSUE TITLE
let the user specify figure dpi when plotting

### ISSUE THREAD

**Issue by vnoel** [pydata/xarray#2216]
when using a DataArray `plot` function, it is already possible to specify the figure size and aspect ratio. 

I think it would make sense to also be able to specify the dpi, e.g. `x.plot(dpi=109)`. It would save one call to `plt.figure()`.

**Comment by shoyer** [comment]
Does pandas support setting DPI like this?

**Comment by vnoel** [comment]
Apparently not. 
https://stackoverflow.com/questions/48227792/how-to-change-dpi-of-my-pandas-dataframe-plot

**Comment by dcherian** [comment]
Don't think we need yet another plot kwarg.
