### ISSUE TITLE
to_netcdf broken encoding: dtype='S1' + chunksizes

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#2219]
```
xarray.Dataset({'x': ['foo', 'bar', 'baz']}).to_netcdf(
    'foo.nc', engine='h5netcdf',
    encoding={'x': {'dtype': 'S1', 'zlib': True, 'chunksizes': (2, )}})

ValueError: "chunks" must have same rank as dataset shape
```
Same with ``engine='netcdf4'``. The issue is present in 0.10.6 as well as in 0.10.3.
The problem is obviously that dtype=S1 changes the shape of the variable before passing it to the backend, but while doing so doesn't also change an eventual chunksizes setting.

The workaround is to omit chunksizes or set it to True.

**Comment by shoyer** [comment]
It looks like this version works:
```
xarray.Dataset({'x': ['foo', 'bar', 'baz']}).to_netcdf(
    'foo.nc', engine='h5netcdf',
    encoding={'x': {'dtype': 'S1', 'zlib': True, 'chunksizes': (2, 3)}})
```

I suppose we could update chunksizes to accept both versions? Or just clearly document this behavior?

**Comment by crusaderky** [comment]
IMHO the trick that alters the shape of the array is strictly an implementation detail which should not be exposed to the end user. If the implementation of xarray alters the shape of the variable, it should as well alter anything that relies on it.

**Comment by max-sixty** [comment]
As part of keeping our issue count <1000, closing as unlikely to inspire change, please reopen if anyone disagrees
