### ISSUE TITLE
Add axis scaling kwargs to DataArray.plot()

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#2224]
It would be useful to add the boolean kwargs `logx`, `logy`, `loglog` to `DataArray.plot()` just as in `pandas.DataFrame.plot()`

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html#pandas.DataFrame.plot

**Comment by shoyer** [comment]
Let's add `logx` and `logy`, but not the redundant `loglog`. It's easy enough to write `logx=True, logy=True`.

**Comment by dcherian** [comment]
Actually do we want to make it more general by saying `xscale='log'` or `xscale='symlog'` or `xscale='linear'`?

**Comment by shoyer** [comment]
Yeah, that's probably a better approach.
