### ISSUE TITLE
duplicate coord names in DataArray constructor

### ISSUE THREAD

**Issue by tv3141** [pydata/xarray#2226]
#### Code Sample

```python
>>> import numpy as np
>>> import xarray as xr
>>> da = xr.DataArray(np.zeros((2,3)), coords=[('unknown', [1, 2]), ('unknown', [0, 90, 180])])
>>> da
<xarray.DataArray (unknown: 3)>
array([[0., 0., 0.],
       [0., 0., 0.]])
Coordinates:
  * unknown  (unknown) int64 0 90 180
>>> da.dims
('unknown', 'unknown')
>>> da.coords
Coordinates:
  * unknown  (unknown) int64 0 90 180
>>> da.sel(unknown=90)
ValueError: conflicting sizes for dimension 'unknown': length 2 on <this-array> and length 3 on 'unknown'

```
#### Problem description

The DaraArray constructor creates an invalid DataArray given duplicate coordinate names. 

#### Expected Output

The DaraArray constructor should raise an Exception given duplicate coordinates names.

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-5-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.4
pandas: 0.23.0
numpy: 1.14.3
scipy: 1.1.0
netCDF4: 1.3.1
h5netcdf: 0.5.1
h5py: 2.8.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.5
distributed: 1.21.8
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: None
setuptools: 39.1.0
pip: 10.0.1
conda: None
pytest: 3.5.1
IPython: None
sphinx: None
</details>

**Comment by fujiisoup** [comment]
Thanks for raising an issue.
It looks similar to #1499.

> The DaraArray constructor should raise an Exception given duplicate coordinates names.

Agreed.
Do you mind to send a fix for this?
