### ISSUE TITLE
resample monthly to seasonal docstring example is wrong

### ISSUE THREAD

**Issue by edoddridge** [pydata/xarray#2232]
The doc string for `resample` contains an example for calculating a seasonal average from monthly values:

https://github.com/pydata/xarray/blob/9c8005937556211a8bf28a946744da3768846c5a/xarray/core/common.py#L620-L637

But running the code in the docstring gives different output:

```python
>>> da = xr.DataArray(np.linspace(0, 11, num=12),
                   coords=[pd.date_range('15/12/1999',
                           periods=12, freq=pd.DateOffset(months=1))],
                   dims='time')
>>> da
<xarray.DataArray (time: 12)>
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
Coordinates:
  * time     (time) datetime64[ns] 1999-12-15 2000-01-15 2000-02-15 ...

>>> da.resample(time="Q-DEC").mean()
<xarray.DataArray (time: 5)>
array([ 0. ,  2. ,  5. ,  8. , 10.5])
Coordinates:
  * time     (time) datetime64[ns] 1999-12-31 2000-03-31 2000-06-30 ...
```
#### Problem description

The difference is undesirable. Furthermore, the user is probably after seasonal averages computed for DJF, MAM, JJA, and SON, which is not what the example code produces. The example produces averages for JFM, AMJ, JAS, and OND.

Changing to

```
da.resample(time="Q-NOV").mean()
``` 
produces three month averages that align with the expected seasons.

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 17.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.2
pandas: 0.22.0
numpy: 1.14.2
scipy: 1.0.1
netCDF4: 1.3.1
h5netcdf: None
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.2
distributed: 1.21.5
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 38.4.0
pip: 10.0.1
conda: None
pytest: 3.3.2
IPython: 6.2.1
sphinx: 1.7.2
</details>

**Comment by chiaral** [comment]
I think that if the correct way should be to use 'QS-DEC' and not 'Q-NOV'  - and this was definitely true. However I run also 0.10.2 - not sure if it was fixed in the latest versions.

**Comment by shoyer** [comment]
Hmm. This may have changed upstream in pandas. Certainly an updated docstring would be appreciated!

**Comment by edoddridge** [comment]
Cool. I'll put in a PR with new one.
