### ISSUE TITLE
Failing test with dask_distributed

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#2238]
Some tests related to dask/distributed are failing in travis.
They are raising a `TypeError: can't pickle thread.lock objects`.

Could anyone help to look inside?

See the travis's log for the current master:
https://travis-ci.org/pydata/xarray/builds/392530577

**Comment by shoyer** [comment]
My best guess is that our logic for getting the default scheduler and/or lock is failing with the latest dask release (0.18):
https://github.com/pydata/xarray/blob/66be9c5db7d86ea385c3a4cd4295bfce67e3f25b/xarray/backends/common.py#L34-L81

Perhaps @jhamman can take a look?

**Comment by shoyer** [comment]
This import no longer works: `from dask.utils import effective_get`

I'm raising an issue in the dask tracker...

**Comment by mrocklin** [comment]
We can add this back in.  I anticipate having to do a bugfix release within a week or two.  Long term you probably want to do the following:

```python
from dask.utils import get_scheduler
actual_get = get_scheduler(get=get, collections=[collection])
￼```

**Comment by jhamman** [comment]
Thanks folks for sorting this out while I was away. I'm happy to take on switching to dask's `get_scheduler`.

**Comment by shoyer** [comment]
@jhamman sounds good! it would be also be good to xfail the failing tests with dask 0.18.0
