### ISSUE TITLE
Slow performance with isel on stacked coordinates

### ISSUE THREAD

**Issue by nbren12** [pydata/xarray#2241]
#### Code Sample

```python
>>> a = xr.DataArray(np.random.rand(64,64,64), dims=list('xyz')).chunk({'x':8, 'y': 8})
>>> b = a.stack(b=['x', 'y'])
>>> %timeit b.isel(b=0).load()
3.81 ms ± 24.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
>>> %timeit a.isel(x=0, y=0).load()
822 µs ± 3.68 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> np.allclose(b.isel(b=0).values, a.isel(x=0, y=0).values)
True
```
#### Problem description

I have noticed some pretty significant slow downs when using dask and stacked indices. As you can see in the example above, selecting the point x=0, y=0 takes about 4 times as long when the x and y dimensions are stacked together. This big difference only appears when `.load` is called. Does this mean it's a dask issue?

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 17.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: en_US.UTF-8

xarray: 0.10.7
pandas: 0.22.0
numpy: 1.13.3
scipy: 1.0.0
netCDF4: 1.3.0
h5netcdf: 0.4.2
h5py: 2.7.1
Nio: None
zarr: 2.2.0
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.1
distributed: 1.21.1
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 39.1.0
pip: 9.0.1
conda: None
pytest: 3.5.1
IPython: 6.2.1
sphinx: 1.6.5
</details>

**Comment by maxim-lian** [comment]
On that thread, quick shout out for https://github.com/joerick/pyinstrument, which I've found very intuitive for working out where in the stack is taking time; particularly when a function higher in the stack is calling fast functions many times

**Comment by nbren12** [comment]
Thanks for the tips everyone. From the dask issue above, it appears that `dask.reshape` does not respect the boundaries of chunks. Therefore, pulling the first chunk of the stacked array requires pulling several chunks from the original un-reshaped data. This is a bit odd because the first chunk of the stacked array could just be a reshaped version of the first chunk from the unstacked array.
