### ISSUE TITLE
Unable to set invalid_netcdf=True

### ISSUE THREAD

**Issue by rparini** [pydata/xarray#2243]
Saving an invalid netcdf file with h5netcdf in the following way
```python
import xarray as xr
a = xr.DataArray([[1.1, 2.2], [3.1, 4.5]], attrs={'myattr':True})
a.to_netcdf('test.nc', engine='h5netcdf')
```
gives the future warning: 
`
FutureWarning: boolean dtypes are supported by h5py, but not part of the NetCDF API. You are writing an HDF5 file that is not a valid NetCDF file! In the future, this will be an error, unless you set invalid_netcdf=True.
`
so I would expect to be able to instead do
```python 
a.to_netcdf('test.nc', engine='h5netcdf', invalid_netcdf=True)
```
but `to_netcdf` has no such argument.
```
TypeError: to_netcdf() got an unexpected keyword argument 'invalid_netcdf'
```
I suppose `invalid_netcdf=True` needs to be passed to the h5netcdf backend but I'm not sure how to do that from here and this doesn't seem to be mentioned directly in the xarray documentation.

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.7
pandas: 0.22.0
numpy: 1.14.5
scipy: 0.19.0
netCDF4: 1.3.1
h5netcdf: 0.5.0
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.17.5
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 39.2.0
pip: 10.0.1
conda: None
pytest: 3.2.3
IPython: 6.2.1
sphinx: 1.6.4
</details>

**Comment by shoyer** [comment]
Yes, it would be add `invalid_netcdf=True` to the `to_netcdf()` method, or to make a separate `to_hdf5()` method that does this. (Probably the former is better, to discourage using this unless necessary.)

We would just need to thread this option through to `h5netcdf.File`:
https://github.com/pydata/xarray/blob/73b476e4db6631b2203954dd5b138cb650e4fb8c/xarray/backends/h5netcdf_.py#L66

**Comment by kmuehlbauer** [comment]
@shoyer Is there any news on this?

**Comment by dcherian** [comment]
@kmuehlbauer a pull request would be welcome if you have the time

**Comment by shoyer** [comment]
We could potentially use put this in `Dataset.encoding`

**Comment by kmuehlbauer** [comment]
@shoyer So that we can extract it in `..backends.api.to_netcdf` and feed it to `store = store_open(target, mode, format, group, **kwargs)` via `kwargs`?
