### ISSUE TITLE
ValueError raised for non-monotonic or NaN coordinate values

### ISSUE THREAD

**Issue by wmay** [pydata/xarray#2250]
#1885 introduced a check, `_is_monotonic`, to pcolormesh plots. This check raises an error when trying to plot datasets with non-monotonically sorted coordinates, or with NaN coordinates.

#### Example

```python
import xarray as xr
ds = xr.open_dataset('ruc2_130_20110612_0700_001.nc')
ds['RH_P0_L4_GLC0'].plot(x='gridlon_0', y='gridlat_0')
```

(You can get the data file [here](http://pireds.asrc.cestm.albany.edu/~xcite/ruc2_130_20110612_0700_001.nc).)

#### Problem

Many geographical datasets have non-monotonic latitude/longitude coordinates, and some have NaN coordinates at grid locations where data is not collected. xarray should plot them. As of xarray 0.10.0, before this pull request was merged, xarray correctly plotted datasets with non-monotonic coordinates or NaN coordinates.

#### Expected Output

![non_monotonic](https://user-images.githubusercontent.com/4205859/41879186-8142bb36-78a6-11e8-8a97-7100ecde7070.png)

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.14.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-23-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

xarray: 0.10.7
pandas: 0.23.1
numpy: 1.14.2
scipy: 1.1.0
netCDF4: 1.4.0
h5netcdf: 0.6.1
h5py: 2.8.0
Nio: 1.5.0
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.18.1
distributed: 1.22.0
matplotlib: None
cartopy: None
seaborn: None
setuptools: 39.2.0
pip: 10.0.1
conda: 4.5.4
pytest: None
IPython: None
sphinx: None
</details>

**Comment by fmaussion** [comment]
Thanks for the report! Will have a look.

**Comment by fmaussion** [comment]
> Many geographical datasets have non-monotonic latitude/longitude coordinates,  

Note that this is not what xarray requests here. The term ``is_monotonic`` is misleading: it means "monoticaly increasing or decreasing" , not "regularly spaced"

**Comment by wmay** [comment]
Thanks for the response, @fmaussion. I'm using the same formal mathematical definition of monotonic as the `_is_monotonic` function. The example I provided is non-monotonic in that sense. You can clearly see, going from left to right on the plot from xarray 0.10.0, that the latitude increases, and then decreases. Therefore the coordinates are non-monotonic on that axis.

That plot is impossible to create with the current version of xarray. I can't imagine that was the intended purpose of this pull request. It seems obvious to me that monotonicity is not the correct test to apply here. My personal opinion is that no test is needed, since it's not xarray's responsibility to reorganize people's data. But at least the monotonicity test needs to be changed, because it's breaking plots for valid data sets.

**Comment by fmaussion** [comment]
Yes OK. For now you can do is: 

``ds['RH_P0_L4_GLC0'].plot(x='gridlon_0', y='gridlat_0', infer_intervals=False)``

The plot will be slightly wrong (pcolormesh need intervals), but at least something shows up (and this wrong plot was the default for a long time in xarray). I have to think a little more about the implications of #1885 for irregular lon-lat grids - I'm pretty sure we're not testing this properly in the test suite.

**Comment by wmay** [comment]
Thanks for the tip, I was having a lot of trouble working around this.
