### ISSUE TITLE
netcdf roundtrip fails to preserve the shape of numpy arrays in attributes

### ISSUE THREAD

**Issue by hmaarrfk** [pydata/xarray#2251]
#### Code Sample
```python
import numpy as np
import xarray as xr

a = xr.DataArray(np.zeros((3, 3)), dims=('y', 'x'))
a.attrs['my_array'] = np.arange(6, dtype='uint8').reshape(2, 3)

a.to_netcdf('a.nc')
b = xr.open_dataarray('a.nc')
b.load()
assert np.all(b == a)
print('all arrays equal')

assert b.dtype == a.dtype
print('dtypes equal')

print(a.my_array.shape)
print(b.my_array.shape)
assert a.my_array.shape == b.my_array.shape
```
#### Problem description
I have some metadata that is in the form of numpy arrays. 
I would think that it should round trip with netcdf.

#### Expected Output
equal shapes inside the metadata

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.16.15-300.fc28.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.7
pandas: 0.23.0
numpy: 1.14.4
scipy: 1.1.0
netCDF4: 1.4.0
h5netcdf: 0.6.1
h5py: 2.8.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.5
distributed: 1.21.8
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 39.2.0
pip: 9.0.3
conda: None
pytest: 3.6.1
IPython: 6.4.0
sphinx: 1.7.5

</details>

**Comment by fmaussion** [comment]
> I have some metadata that is in the form of numpy arrays.

The short answer is: storing arrays (or other objects) as attributes is not easy. When you do so, xarray has to convert them at serialization, and the roundtrip (especially regarding the shape) cannot be achieved because it isn't in the datamodel of NetCDF.

What is it you are storing as 2D arrays? Would a coordinate variable be an option?

**Comment by shoyer** [comment]
If I remember correctly, netCDF intentionally does not support multi-dimensional array attributes. I'm not sure why it silently changes shape, though. An error message would seem much more user-friendly to me. Possibly this is worth raising on the netCDF4 issue tracker: https://github.com/unidata/netcdf4-python

**Comment by hmaarrfk** [comment]
@shoyer, @fmaussion thank you for your answers. I'm OK with this issue being closed. I'm no expert on netcdf4, so I don't know if I could express the issue in a concise manner there.

**Comment by shoyer** [comment]
I filed a bug report for netCDF4-Python: https://github.com/Unidata/netcdf4-python/issues/841
