### ISSUE TITLE
autoclose=True is not implemented for the h5netcdf backend

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#2253]
Hi, are there any plans to enable `autoclose=True` for h5netcdf?
I'd like to use "open_mfdataset" for 15.000 files, which is not possible with `autoclose=False`.

#### Error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-43f56b648d8a>", line 16, in <module>
    autoclose=True
  File "/usr/local/lib/python3.6/dist-packages/xarray/backends/api.py", line 624, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/usr/local/lib/python3.6/dist-packages/xarray/backends/api.py", line 624, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/usr/local/lib/python3.6/dist-packages/xarray/backends/api.py", line 331, in open_dataset
    **backend_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/xarray/backends/h5netcdf_.py", line 84, in __init__
    raise NotImplementedError('autoclose=True is not implemented '
NotImplementedError: autoclose=True is not implemented for the h5netcdf backend pending further exploration, e.g., bug fixes (in h5netcdf?)
```

#### Output of ``xr.show_versions()``

<details>
>>> xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-23-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

xarray: 0.10.7
pandas: 0.23.1
numpy: 1.14.5
scipy: 1.1.0
netCDF4: 1.4.0
h5netcdf: 0.5.1
h5py: 2.8.0
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.17.5
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: 0.8.1
setuptools: 39.2.0
pip: 9.0.1
conda: None
pytest: None
IPython: 6.4.0
sphinx: None

</details>

**Comment by shoyer** [comment]
When we implemented this originally, we couldn't figure out how to get the `autoclose=True` tests passing for h5netcdf. They can still be found in `test_backends.py`, but I think they are being automatically skipped.

If you (or anyone else) is interested in looking into this, you are welcome to give it a try! It's even possible that autoclose=True *does* actually work with h5netcdf on real datasets if you remove that error, even though we couldn't get the test suite passing.

**Comment by Hoeze** [comment]
OK, maybe I'll look into it when I got some spare time.
It's currently the only point where I use netcdf4, so if opening a lot of files would also work with h5netcdf, I could delete this dependency.
