### ISSUE TITLE
[bug] Exception ignored in generator object Variable

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#2263]
```
X is an xr.DataArray of shape (2000, 100), idx is a np.ndarray vector of shape (500,).
Now I'd like to fetch:
```python
X[idx].values
```

#### Problem description

During this, the following warning pops up:
```
Exception ignored in: <generator object Variable._broadcast_indexes.<locals>.<genexpr> at 0x7fcdd479f1a8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xarray/core/variable.py", line 470, in <genexpr>
    if all(isinstance(k, BASIC_INDEXING_TYPES) for k in key):
SystemError: error return without exception set

```
#### Expected Output
No error

#### Possible solution:
Each time I execute: `all(not isinstance(k, Variable) for k in key)` the error pops up at a Tuple Iterator.
Changing this to `all([not isinstance(k, Variable) for k in key])` solves the problem.

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-23-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

xarray: 0.10.7
pandas: 0.23.1
numpy: 1.14.5
scipy: 1.1.0
netCDF4: 1.3.1
h5netcdf: 0.5.1
h5py: 2.8.0
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.17.5
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: 0.8.1
setuptools: 39.2.0
pip: 9.0.1
conda: None
pytest: None
IPython: 6.4.0
sphinx: None
</details>

**Comment by fmaussion** [comment]
Thanks for the report! 

I'm afraid I don't fully understand the problem. Do you think that you can come up with a [minimal bug report example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)?

**Comment by Hoeze** [comment]
I tried to, but I'm not sure whats the root cause of this problem.
This problem occures as part of my Tensorflow input pipeline (it's called by a py_func) and it's hard to reproduce without Tensorflow.

Maybe this helps?
![grafik](https://user-images.githubusercontent.com/1200058/42213839-2dde0f62-7eba-11e8-837f-fbe0a39f2ee8.png)

It might also be possible that this is some problem with python itself or some multithreading issue.
I just found this issue which exactly describes my problem:
https://github.com/ContinuumIO/anaconda-issues/issues/8737

There's also the hint that this problem only occurs in debug mode.
Actually, I'm always running my unit tests in debug mode, that's why I did not realize this.

Having that said, it's maybe not worth to change this in xarray and wait for a python solution to this.
However, since two brackets would solve this issue, it might not be too invasive to simply fix this one line :)

**Comment by shoyer** [comment]
Can you share what `X` and `X._data` look like?

My *guess* is that this is a bug of some sort in a lower level library like NumPy or TensorFlow. This sort of error is basically impossible to trigger unless you are using the CPython C-API directly, which we don't do in xarray. Xarray itself is pure Python.

**Comment by Hoeze** [comment]
There is no X._data, but X.values is a simple ndarray.

I pickled X and idx:
[unit_test.zip](https://github.com/pydata/xarray/files/2162950/unit_test.zip)

**Comment by shoyer** [comment]
Oops, I meant `X.variable._data`

**Comment by Hoeze** [comment]
```
>>> X.variable._data
array([[  3478.,   9079.,  51928., ...,  34312.,  11081.,  79157.],
       [  6976.,  14495.,  64495., ...,  30606.,  12816., 157080.],
       [  4260.,  10066.,  47271., ...,  47332.,  14947., 118562.],
       ...,
       [ 12976.,   9201.,  31295., ...,  22093.,   8846.,  96991.],
       [  7033.,   8238.,  22521., ...,  20476.,   9051.,  67057.],
       [ 13566.,  10308.,  28916., ...,  15529.,   7426.,  84852.]],
      dtype=float32)
>>> type(X.variable._data)
<class 'numpy.ndarray'>
```

**Comment by shoyer** [comment]
Sorry, I'm stumped.

**Comment by Hoeze** [comment]
Thank you very much for trying to help :)

It's no big problem at the moment, as it only comes up when I'm debugging.
If this should really get a big problem I'll try to publish a test script here.

**Comment by dcherian** [comment]
@Hoeze let's reopen this when you have a reproducible example. Thanks.
