### ISSUE TITLE
Some simple broadcast_dim method?

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#2267]
I've already found xr.broadcast(arrays).
However, I'd like to just add a new dimension with a specific size to one DataArray.
I could not find any simple option to do this.

If there is no such option: 
- add a size parameter to DataArray.expand_dims?
- DataArray.broadcast_dims({"a": M, "b": N})?

**Comment by fmaussion** [comment]
Is [exand dims](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.expand_dims.html) not what you are looking for?

**Comment by Hoeze** [comment]
No, I'd like something like np.tile

**Comment by Hoeze** [comment]
As an explanation:
I'd like to change my program to only use lazy / chunked calculations in order to save RAM.

I recognized that np.broadcast_to converts the DataArray into a numpy one.
Therefore I needed some xarray way to solve this.

I tried:
```python
DataArray.expand_dims("new_dim").isel("new_dim", np.repeat(0, target_dim_size))
```
but this really looks ugly and I'm not sure about the performance implications of this.

**Comment by shoyer** [comment]
We could add an optional `size` argument to `expand_dims`, with a default value of 1.

**Comment by Hoeze** [comment]
@shoyer so there is no direct xarray equivalent to np.broadcast_to?

**Comment by shoyer** [comment]
We have `xarray.Variable.set_dims`, but that's only in the low-level variable API.

**Comment by shoyer** [comment]
let's continue the repeated dimension discussion over in https://github.com/pydata/xarray/issues/1378

**Comment by dcherian** [comment]
This should be fixed by the latest `expand_dims`
