### ISSUE TITLE
A special function for unpickling old xarray object?

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#2269]
I noticed that some users experiencing troubles to restore xarray objects that is created xarray < 0.8.

Is there any possibility to add a function to support unpickling old object, such as 
`xr.unpickle_legacy(file, version)`?
We previously recommended using pickle to store xarray objects (at least for the short term use, maybe).

xref (private repo)
gafusion/OMFIT-source#2652

**Comment by fujiisoup** [comment]
Some additional explanations

I was consulted by an onwer of a project that is using xarray inside it, 
the way to load xarray objects that is **pickled** with older-version xarray.

They does not recommend to use pickle, but some users actually do this and have troubles to restore old pickled files.

In partiular, xarray renamed `Coordinate` to `IndexVariable` in some point between v0.7 to v0.8.
There might be another module/class name changes too, and 
these result in the (uninformed) error
```python
UnpicklingError: NEWOBJ class argument isn't a type object
```

What I would like to propose here is to provide a workaround to unpickle old xarray objects.
The function would look like
```python
def unpickle_legacy(filename):
    """
    Unpickle old xarray objects.
    """
    class RenamingUnpickler(pickle.Unpickler):
        def find_class(self, module, name):
             if name == 'Coordinate':
                 name = 'IndexVariable'
             return super().find_class(module, name)

    with open(filename, 'rb') as f:
        return RenamingUnpickler(f).load()
```
for all the previous releases.

Continuously supporting such a function might be an additional task, 
but it will emphasize the robustness of our project.

Any comments are welcome.

**Comment by shoyer** [comment]
If you're interested in maintaining/implementing this, I would be supportive.

Personally, I am reluctant to work on this because I value being able to refactor xarray internals without added friction. We are [pretty clear](http://xarray.pydata.org/en/stable/io.html#pickle) in the docs that pickle isn't supported for long term storage, so this is a problem they somewhat brought upon themselves.

**Comment by jhamman** [comment]
My 2 cents. I would be reluctant to find this in Xarray anytime soon. This just seems like its going to be a hard thing to maintain. Perhaps, after the data model and api have really stabilized, this would make sense, but it strikes me as something that is going to be more work than its worth to maintain. Afterall, we can rountrip xarray datasets to a number of stable file formats.

**Comment by fujiisoup** [comment]
@jhamman 

>  Perhaps, after the data model and api have really stabilized, this would make sense, but it strikes me as something that is going to be more work than its worth to maintain. 

Agreed.

In my experience, surprisingly many people (including my students) are using pickle without notifying its potential risk.
Is it too redundant to issue a warning when xarray object is being pickled (maybe in __getstate__ method)?
It is annoying for the short term usage by advanced users though.
