### ISSUE TITLE
Failed documentation on pydata.org

### ISSUE THREAD

**Issue by rainwoodman** [pydata/xarray#2274]
#### Code Sample, a copy-pastable example if possible

See, http://xarray.pydata.org/en/stable/plotting.html#id4

The example below "Faceting also works for line plots." is broken.

**Comment by jhamman** [comment]
Thanks for the report. This seems to have been fixed in master (http://xarray.pydata.org/en/latest/plotting.html#id4) but we haven't issued another release to trigger a rebuild of the stable docs.
