### ISSUE TITLE
IPython crash after xarray.opendataset : free():invalid next size (fast)

### ISSUE THREAD

**Issue by Scheibs** [pydata/xarray#2275]
I tried to open a 40 Mo netcdf file with `xarray.open_dataset()` but i got a Ipython crash with `free():invalid next size (fast)`
it's works fine with smaller files ( 10 Mo) , and it's works with the 40 Mo file on my other computer (Windows RAM 32Gb)

This is some informations about my configuration : 

<details open><summary><code>`conda info`</code></summary><p>

```  active environment : None
          conda version : 4.5.7
    conda-build version : 3.0.19
         python version : 2.7.13.final.0
       base environment : /local01/appli/anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          http://conda.binstar.org/mutirri/linux-64
                          http://conda.binstar.org/mutirri/noarch
                          http://repo.continuum.io/pkgs/free/linux-64
                          http://repo.continuum.io/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch

               platform : linux-64
             user-agent : conda/4.5.7 requests/2.14.2 CPython/2.7.13 Linux/3.16.0-4-amd64 debian/8 glibc/2.19
```
</p></details>
<details open><summary><code>`lscpu`</code></summary><p>

```
RAM : 64 GB
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               1297.781
CPU max MHz:           3200.0000
CPU min MHz:           1200.0000
BogoMIPS:              4789.90
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-5,12-17
NUMA node1 CPU(s):     6-11,18-23

```
</p></details>

**Comment by Scheibs** [comment]
This error appears immediately when i write <code>xr.open_dataset(f)</code> on Ipython console :

<code>An error ocurred while starting the kernel
*** Error in `/local01/appli/anaconda2/bin/python': free(): invalid next size (fast): 0x0000000003086710 ***</code>
</p></details>
<details open><summary><code>xr.show_versions()
</code></summary><p>

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-4-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.iso885915
LANG: fr_FR@euro
LOCALE: None.None

xarray: 0.10.7
pandas: 0.20.3
numpy: 1.13.1
scipy: 0.19.1
netCDF4: 1.2.4
h5netcdf: 0.6.1
h5py: 2.7.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.18.1
distributed: 1.22.0
matplotlib: 2.0.2
cartopy: None
seaborn: None
setuptools: 36.4.0
pip: 9.0.1
conda: 4.5.7
pytest: 3.2.1
IPython: 5.3.0
sphinx: 1.6.3
```
</p></details>

**Comment by Scheibs** [comment]
I updated the netcdf4 librairie and it's works. Thanks

**Comment by dkobashi** [comment]
I am having the same problem. How can I update netCDF4 library? Thanks in advance. -DJ

**Comment by shoyer** [comment]
@dkobashi how did you install Python?

**Comment by dkobashi** [comment]
I use Anaconda python.

My conda version is as follow
               platform : linux-64
          conda version : 4.3.32
       conda is private : False
      conda-env version : 4.3.32
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4

I attach xarray.show_versions() at the bottom.  I see it uses the same version as the other on the post.
I also attach the error I got below.

*** Error in `/home/dj/anaconda2/envs/roms/bin/python': free(): invalid next size (fast): 0x0000556928b744e0 ***

 A funny thing is that I have no problem getting the data using netCDF4-python. The file size of the data is big (50-100GB. netCDF4 format), but again I was able to get the data with netCDF4-python. So I guess I need to update netCDF4-python, but I don't know how.

Thanks,

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.14.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-34-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

xarray: 0.10.8
pandas: 0.21.0
numpy: 1.13.3
scipy: 1.0.0
netCDF4: 1.2.4
h5netcdf: None
h5py: 2.7.0
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.16.0
distributed: 1.20.0
matplotlib: 2.2.2
cartopy: 0.15.0
seaborn: 0.9.0
setuptools: 36.5.0.post20170921
pip: 18.0
conda: None
pytest: None
IPython: 5.4.1
sphinx: None

**Comment by shoyer** [comment]
@dkobashi  `conda update netcdf4` should do it for you

**Comment by dkobashi** [comment]
Your suggestion did not work. I got the following. Is there any other way to update netcdf4 without messing up the dependencies of other python tools? Thanks, -DJ
```
~$ conda update netcdf4
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at ~/anaconda2/envs/roms:
#
netcdf4                   1.2.4               np113py27_0
