### ISSUE TITLE
xarray: dimension attributes gone after adding variable?

### ISSUE THREAD

**Issue by lukasbrunner** [pydata/xarray#2276]
#### Code Sample, a copy-pastable example if possible

```python
import xarray as xr
ds = xr.Dataset(coords={'dim': ('dim', [0], {'units': 'unit'})})
# ds['var'] = xr.DataArray([0])  # this does not change anything
# print(ds.dim)  # print 1
ds['var'] = xr.DataArray([0], dims='dim')
# print(ds.dim)  # print 2
```
#### Problem description

The unit of the dimension is gone after adding a variable depending on the dimension:

```python
# print 2
<xarray.DataArray 'dim' (dim: 1)>
array([0])
Coordinates:
  * dim      (dim) int64 0
```

For me at least this is unexpected behaviour for sure?? Is there a reason for this or is it a bug?

#### Expected Output

Dimension with a unit, like:

```python
# print 1
<xarray.DataArray 'dim' (dim: 1)>
array([0])
Coordinates:
  * dim      (dim) int64 0
Attributes:
    units:    unit
```

#### Output of ``xr.show_versions()``

<details>

.../.conda/envs/my_p3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.104-39-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.7
pandas: 0.22.0
numpy: 1.14.3
scipy: 1.1.0
netCDF4: 1.3.1
h5netcdf: 0.5.0
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.17.2
distributed: 1.21.5
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 39.0.1
pip: 9.0.3
conda: None
pytest: 3.5.0
IPython: 6.3.1
sphinx: 1.7.2

</details>

**Comment by shoyer** [comment]
Thanks for the report. This looks related to https://github.com/pydata/xarray/issues/2245 (possibly its the same issue).

**Comment by shoyer** [comment]
Closing this in favor of https://github.com/pydata/xarray/issues/2245, though this is a really nice simple example.
