### ISSUE TITLE
Broken link in doc

### ISSUE THREAD

**Issue by yohai** [pydata/xarray#2295]
The link to the external blogpost about xarray and dask, that was fixed in https://github.com/pydata/xarray/pull/1573,  is broken again. Is it available somewhere?

**Comment by shoyer** [comment]
Maybe we should stick to the link from my personal website: http://stephanhoyer.com/2015/06/11/xray-dask-out-of-core-labeled-arrays/

Corporate blogs seem to have quite a short half-life...
