### ISSUE TITLE
Timeouts errors on readthedocs

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#2306]
We are reaching the 900s build time limit on readthedocs more often than not (https://readthedocs.org/projects/xray/builds/). I have the same problem with all of my OS projects. 

The bottleneck is the conda environment installation, which took  457s on the latest failed build. I'm going to try to spare some time in a subsequent PR, but we might have to get in touch with the RTD people to get more build time.

**Comment by fmaussion** [comment]
This is actually a bigger problem since the last point releases did not build correctly: http://xarray.pydata.org/en/v0.10.8/ 
http://xarray.pydata.org/en/v0.10.7/

**Comment by shoyer** [comment]
See also https://github.com/pydata/xarray/issues/2209

Recently I've only been able to get builds to complete successfully after repeatedly restarting them.

**Comment by fmaussion** [comment]
closing in favor of https://github.com/pydata/xarray/issues/2209
