### ISSUE TITLE
Pick a certain time 

### ISSUE THREAD

**Issue by ameanijon** [pydata/xarray#2307]
I have a variable with time, lon and lat dimensions. 

I can specify longitude (`uu = u.where(u.longitude >= 30)`), similarly with latitude, but I'm struggling to specify a certain date/time.

Printing the time gives the following output:
```
>>> print u.time
<xarray.DataArray 'time' (time: 8)>
array(['2018-04-01T00:00:00.000000000', '2018-04-01T06:00:00.000000000',
       '2018-04-01T12:00:00.000000000', '2018-04-01T18:00:00.000000000',
       '2018-04-02T00:00:00.000000000', '2018-04-02T06:00:00.000000000',
       '2018-04-02T12:00:00.000000000', '2018-04-02T18:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2018-04-01 2018-04-01T06:00:00 ...
Attributes:
    long_name:  time
```

I've tried naming the date by a number like `uu = u.where(u.time >= 4)` but it gives `TypeError: invalid type promotion`, and it's not very useful when using a dataset with a huge time dimension. 

I'd just like some help figuring out the syntax for specifying days/times.

**Comment by fmaussion** [comment]
Hi @ameanijon , for me it's not clear what you mean with "specify longitude" in your post above. The command ``u.where(u.longitude >= 30)`` will mask out data, not select (or "pick") them as you write in your title. 

Selecting data is called "indexing" in xarray and you'll find examples in the documentation here: http://xarray.pydata.org/en/stable/indexing.html  (also with time)

**Comment by ameanijon** [comment]
@fmaussion thank you! Think I got a bit confused
