### ISSUE TITLE
ds.mean() deletes non numeric variables

### ISSUE THREAD

**Issue by lukasbrunner** [pydata/xarray#2311]
#### Code Sample, a copy-pastable example if possible

```python
import xarray as xr
ds = xr.Dataset(
    coords={'dim': range(5)},
    data_vars={'data': 'string'})
print(ds.mean('dim'))  # print 1
```
#### Problem description

I know one should probably not use strings as variables but since the possibility exists I use it every now and again because I find it convenient. However recently I encountered a somewhat strange case when taking the mean.

Calculating the mean over a dimension deletes all non-numeric variables even if they do not depend on the given dimension. Variables not depending on the dimension over which the mean is taken should be untouched I think? 

```python
# print 1
<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
```

#### Expected Output

I would expect the variable 'data' to still be in the dataset.

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------

commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.138-59-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.7
pandas: 0.22.0
numpy: 1.14.3
scipy: 1.1.0
netCDF4: 1.3.1
h5netcdf: 0.5.0
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.17.2
distributed: 1.21.5
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 39.0.1
pip: 9.0.3
conda: None
pytest: 3.5.0
IPython: 6.3.1
sphinx: 1.7.2

</details>

**Comment by shoyer** [comment]
This was changed somewhat recently by https://github.com/pydata/xarray/pull/2156. The way the logic works now, we try to reduce *all* data variables whether or not they include the relevant dimension.

The issue with the old behavior (which did keep non-numeric variables in these cases) is that some aggregations don't always preserve scalar values. Variance and standard deviation are two examples that come to mind off-hand:
```
>>> np.var(2)
0.0
```

**Comment by lukasbrunner** [comment]
Thanks for your reply and the explainer! I took me about 15min of thinking (its still early in the morning) until I realized my mistake ':) After a mean (var/std) call you expect the dataset to only contain means (variances/stds) no matter of the dimensions involved, right?! 
My original thought was that 'data' in my example should not be touched at all since it is independent of the dimension I was handling.
