### ISSUE TITLE
Assigning new values to a dataset variable modifies original object

### ISSUE THREAD

**Issue by WestonAnderson** [pydata/xarray#2319]
#### Code Sample
```python
import xarray as xr
import numpy as np

empty = np.zeros([8,10,10])
ds = xr.Dataset(
           {'var1':(['d1','d2','d3'],empty),
            'var2':(['d1','d2','d3'],empty),      
            'var3':(['d1','d2','d3'],empty)},
            coords = {'d1': range(8),
                      'd2': range(10),
                      'd3': range(10)})

print(ds)

ds['var1'][0,:,:] = 5

print(ds)
print(empty)
```
#### Problem description
I want to initialize a dataset using an empty array for a series of variables, then assign values to some of the variables. The problem is that xarray modifies the object that I initialized the variables with, so I can't use the same empty array. So in this example, instead of only modifying "var1", the above code instead modifies the original "empty" array, and the other variables ("var2" and "var3") are also modified.

I wouldn't expect this. I expected that once I created a dataset the new variables would be copies of "empty" rather than pointers to "empty"

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.4.final.0
python-bits: 64
OS: Darwin
OS-release: 17.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.7
pandas: 0.21.0
numpy: 1.13.3
scipy: 1.0.0
netCDF4: 1.2.4
h5netcdf: None
h5py: 2.7.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.16.0
distributed: 1.20.0
matplotlib: 2.1.0
cartopy: None
seaborn: None
setuptools: 36.5.0.post20170921
pip: 9.0.1
conda: 4.5.8
pytest: 3.2.5
IPython: 6.2.1
sphinx: 1.6.3

</details>

**Comment by fmaussion** [comment]
Thanks for the report!

> I expected that once I created a dataset the new variables would be copies of "empty" rather than pointers to "empty"

Most people would disagree here: having views instead of copies is a huge advantage for memory saving and other optimizations. By the way, this is how assignment in python works:

```python
empty = [0, 0, 0]
a = empty
a[1] = 9  # <- will change empty
```

In order to make a copy you'll have to specify this yourself (or use xarray's [zeros_like](http://xarray.pydata.org/en/stable/generated/xarray.zeros_like.html#xarray.zeros_like)):

```python
ds = xr.Dataset(
           {'var1':(['d1','d2','d3'],empty.copy()),
            'var2':(['d1','d2','d3'],empty.copy()),      
            'var3':(['d1','d2','d3'],empty.copy())},
            coords = {'d1': range(8),
                      'd2': range(10),
                      'd3': range(10)})
```

**Comment by WestonAnderson** [comment]
I completely agree that it's more sensible to make them pointers rather than to make a deep copy, but I was thinking about datasets differently. I considered this similar to creating a netCDF with the netCDF package. 

Maybe make the point that assigning as I did creates pointers not deep copies more clear in the documentation? (http://xarray.pydata.org/en/stable/data-structures.html)

**Comment by fmaussion** [comment]
> Maybe make the point that assigning as I did creates pointers not deep copies more clear in the documentation?

Yes! Would you like to try to submit a pull-request to do so?
