### ISSUE TITLE
znetcdf:  h5netcdf analog for zarr? 

### ISSUE THREAD

**Issue by rsignell-usgs** [pydata/xarray#2323]
I've been making good use of the zarr backend via `xr.open_zarr`, but with the National Water Model datasets I've been working with lately, it would be really handy to be able to open them with `xr.open_mfdataset(filelist, engine='znetcdf')` so that we could more easily create xarray datasets from the assemblage of overlapping forecast data files. 

So just as we have [h5netcdf](https://github.com/shoyer/h5netcdf) "Pythonic interface to netCDF4 via h5py", we could have "z5netcdf", a "Pythonic interface to netCDF4 via Zarr". 

I see that @shoyer previously had this idea: https://github.com/pydata/xarray/issues/1223#issuecomment-274230041 and also @rabernat https://github.com/pydata/xarray/pull/1528#issuecomment-325226495 thinks it would be a good idea, so I'm just piling on from a user perspective!

**Comment by shoyer** [comment]
z5 is the name of another library that reads/writes zarr files, so let's not copy that: https://github.com/constantinpape/z5 😀

We could indeed work on getting zarr support in open_mfdataset, but that's really independent of factoring out zarr/netCDF support into a separate project. I don't recall off hand why zarr has the separate function for opening it -- it may have something to do with using different decoders than netCDF files.

**Comment by rsignell-usgs** [comment]
@shoyer, if we a `znetcdf` library like `h5netcdf` we could get `mf_dataset` "for free" though, right?  
Zarr definitely has more and different compression options than NetCDF -- does that make this concept problematic?

**Comment by shoyer** [comment]
> if we a znetcdf library like h5netcdf we could get mf_dataset "for free" though, right?

We would still need an adapter layer in xarray, although it could be a little smaller.

Basically, we would need to make `open_zarr()` a special case of `open_dataset()`. In principle, I think this is totally doable, though there are a few options for open_dataset that we haven't ported over to open_zarr yet (e.g., caching).
