### ISSUE TITLE
dimensions of interpolated output at single location depends on whether a scalar or list is provided

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#2327]
See below, in the first the output has no dimension but has a co-ordinate.

#### Code Sample, a copy-pastable example if possible

```python
da = xr.DataArray([1, 2, 3], dims='a', coords={'a': [1, 2, 3]})
da.interp(a=1.5)
```
```
<xarray.DataArray ()>
array(1.5)
Coordinates:
    a        float64 1.5
```

while 
```python
da.interp(a=[1.5])
```
```
<xarray.DataArray (a: 1)>
array([1.5])
Coordinates:
  * a        (a) float64 1.5
````

I think the latter should be the answer always. It's surprising to lose a dimension on interpolating... 

The fix should occur here, I think: https://github.com/pydata/xarray/blob/f281945fcacbfc1dbaa48fb15546fae5317bdda8/xarray/core/dataset.py#L1330

Changing that to `np.atleast_1d` breaks tests though :/
@fujiisoup

**Comment by shoyer** [comment]
The intention was for `interp()` to give identical results to `sel()` if the all the indexed points are exactly found in the original dataset, i.e., following the same [indexing rules](http://xarray.pydata.org/en/stable/indexing.html#indexing-rules).

**Comment by dcherian** [comment]
Oh, I see.

It makes sense with multi-dimensional arrays but for 1D arrays, the dimension-less output looks funny for both `sel` and `interp`.

```
<xarray.DataArray ()>
array(1.5)
Coordinates:
    a        float64 1.5
```
