### ISSUE TITLE
Spurious "Zarr requires uniform chunk sizes excpet for final chunk."

### ISSUE THREAD

**Issue by jacobtomlinson** [pydata/xarray#2335]
#### Problem description

Using xarray 0.10.7 I'm getting the following error when trying to write out a zarr.

```
ValueError: Zarr requires uniform chunk sizes excpet for final chunk. Variable ((3, 3, 3, 3), (3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2), (1, 1, 1), (100, 100, 100, 100, 100, 100), (100, 100, 100, 100, 100, 100, 100, 100)) has incompatible chunks. Consider rechunking using `chunk()`.
```

Those chunks look fine to me, only one has an inconsistent chunking and it's the final chunk in the second index. Seems related to #2225.

**Comment by jhamman** [comment]
I think this was closed in #2228 and should be in 0.10.8.

**Comment by jacobtomlinson** [comment]
Great! We are still on 0.10.7 so I'll update and give it another go.

**Comment by jacobtomlinson** [comment]
Yup seems fine in 0.10.8.
