### ISSUE TITLE
DataArray.plot.pcolormesh() issue when specifying 2D x and y

### ISSUE THREAD

**Issue by mnlevy1981** [pydata/xarray#2338]
#### Code Sample, a copy-pastable example if possible

I created a notebook to highlight the issue:
https://github.com/mnlevy1981/xarray-issue/blob/master/xarray-example.ipynb

It's in a self-contained repository, including a YAML file so conda can create an environment with matplotlib, jupyterlab, and xarray... but assuming those packages are in your environment

```
$ git clone https://github.com/mnlevy1981/xarray-issue.git
$ cd xarray-issue
$ jupyter lab
```

You should be able to run through the `xarray-example.ipynb` notebook and recreate the problematic plot.

#### Problem description

When specifying a 2D coordinate for x and y, it looks like `plot.pcolormesh()` is doing some weird interpolation across the domain. The problem might be that the `TLONG` variable (providing longitude) is not being specified as cyclic or periodic?

#### Expected Output

A plot where `TLAT` and `TLONG` provide lat / lon (rather than using `nlat` and `nlon`) and the continents are clearly visible as white / missing values.

#### Output of ``xr.show_versions()``

<details>
>>> xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.8
pandas: 0.23.3
numpy: 1.14.3
scipy: 1.1.0
netCDF4: 1.4.0
h5netcdf: 0.6.1
h5py: 2.8.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.18.2
distributed: 1.22.0
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 40.0.0
pip: 18.0
conda: None
pytest: None
IPython: 6.5.0
sphinx: None
</details>

**Comment by dcherian** [comment]
xref: https://github.com/pangeo-data/pangeo/issues/351

This is a matplotlib `pcolormesh` issue. It can't handle non-monotonic co-ordinates (or at least handles them funnily sometimes).

`plt.pcolormesh(ds.TLONG, ds.TLAT, ds.SSH)`
![image](https://user-images.githubusercontent.com/2448579/43617311-28d88e42-9676-11e8-8739-6393864d022a.png)

And `TLONG`, `TLAT` are:
![image](https://user-images.githubusercontent.com/2448579/43617299-1b7cc506-9676-11e8-83e6-0a92585b05e3.png)

I think your only option is to use cartopy.

**Comment by mnlevy1981** [comment]
I had been hesitant to use cartopy because my initial attempt introduced a seam of missing values down the center of the plot, but I figured out how to shift that to the boundary of the plot and am happy with how this looks:

https://github.com/mnlevy1981/cartopy-issue/blob/master/cartopy-example.ipynb

Thanks for pointing out the issue resides in the matplotlib routine rather than the xarray wrapper, I may submit an issue over there but at least I have something that works now.
