### ISSUE TITLE
apply_ufunc silently neglects arguments if `len(input_core_dims) < args`

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#2341]
From [SO](https://stackoverflow.com/questions/51680659/disparity-between-result-of-numpy-gradient-applied-directly-and-applied-using-xa/51690873#51690873)

In the following script, the second argument is silently neglected,
```python
da = xr.DataArray(np.random.randn(4, 3), coords={'x': [5, 7, 9, 11]}, dims=('x', 'y'))
xr.apply_ufunc(np.gradient, da, da.coords['x'].values, kwargs={'axis': -1},
               input_core_dims=[['x']], output_core_dims=[['x']],
               output_dtypes=[da.dtype])
```
This is because we need to the same number of `input_core_dims` to the number of arguments,

https://github.com/pydata/xarray/blob/56381ef444c5e699443e8b4e08611060ad5c9507/xarray/core/computation.py#L535-L538

The correct scipt might be
`input_core_dims=[['x']]` -> `input_core_dims=[['x'], []]`.

I think we can raise a more friendly error if the size of `input_core_dims` are wrong.

EDIT:
Or we can automatically insert an empty tuple or `None` for non-xarray object?
`input_core_dims` for non-xarray object sounds a little strange.

**Comment by shoyer** [comment]
👍 we should definitely raise an informative error message here rather than silently dropping the argument in `zip`.
