### ISSUE TITLE
Be able to define whether file(s) on disk are opened read-only or read-write

### ISSUE THREAD

**Issue by AndyGabey** [pydata/xarray#2345]
From a testing point of view, it would be helpful to explicitly specify whether to open the source file(s) on disk as read-only or read-write in open_dataset() and open_mfdataset(). It'd also be a nice backstop for anybody concerned about data corruption from unexpected behaviour.

**Comment by shoyer** [comment]
`open_dataset` and `open_mfdataset` *never* open files for read-write. To write data to files with xarray, you have to use `to_netcdf()`.

Arguably, these functions would be better named `read_dataset`. I think we stuck with `open_dataset` because the reading is done in a lazy fashion.
