### ISSUE TITLE
Failing test for python=3.6 dask-dev

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#2352]
Recently, dask renamed `dask.ghost` to `dask.overlap`. We use them around `rolling`.
For the patch, see #2349 .

BTW, there is another faling test in python=2.7 dev, claiming that 
> iris and pynio which gives various errors of arrays not being equal for test_to_and_from_cdms2_sgrid and test_to_and_from_cdms2_ugrid

Is anyone working on this?
If not, I think we can temporally skip these tests for python 2.7.

**Comment by shoyer** [comment]
> If not, I think we can temporally skip these tests for python 2.7.

Yes, please mark these as xfail!

See https://github.com/pydata/xarray/issues/2332

**Comment by shoyer** [comment]
I think dask could have deprecated `ghost` more cleanly. See my comment in https://github.com/dask/dask/pull/3830.

**Comment by fujiisoup** [comment]
Closes via #2349
