### ISSUE TITLE
Animated plots - a suggestion for implementation

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#2355]
**It'd be awesome if one could animate the plots xarray creates using matplotlib just by specifying the dimension over which to animate the plot.**

This would allow for rapid visualisation of time-evolving data and could potentially be very powerful (imagine a grid of faceted 2d plots, all evolving together over time). I know that there are already some libraries which can create animated plots of xarray data (e.g. Holoviews), but I think that it's within xarray's scope (#2030) to add another dimension to its default matplotlib-style plotting capabilities.

**How?**

I saw this new package for making it easier to animate matplotlib plots using the funcanimation module: [animatplot](https://github.com/t-makaro/animatplot). It essentially works by wrapping matplotlib commands like `plt.imshow()` to instead return "blocks". These blocks can then be animated by feeding them into an `animation` class. An introductory script to plot line data can be found [here](https://animatplot.readthedocs.io/en/latest/tutorial/getting_started..html), but basically has the form

```python
import animatplot as amp
import matplotlib.pyplot as plt

X, Y = load_data_somehow
block = amp.blocks.Line(X, Y)
anim = amp.Animation([block])

anim.save_gif("animated_line") 
plt.show()
```

which creates a basic gif like this: ![animated line gif](https://user-images.githubusercontent.com/35968931/43885402-a3373002-9b6d-11e8-9b3d-f4e588a71a22.gif)

I think that it might be possible to integrate this kind of animation-plotting tool by adding an optional dimension argument to xarray's plotting methods, which if given causes the function to call the wrapped animatplot plotting command instead of the bare matplotlib one. It would then return the corresponding "block" ready to be animated. Using the resulting code might only require a few lines to create an impressive visualisation:

```python
turb2d = xr.load_dataset("turbulent_fluid_data.nc")

block = turb2d["density"].plot.imshow(animate_over='time')
anim = Animation([block])

anim.save_gif("fluid_density.gif") 
plt.show()
``` 

![n_over_time](https://user-images.githubusercontent.com/35968931/43887058-83d4161c-9b72-11e8-978d-fcb8e071a37a.gif)

**What would need changing?**

If we take the `da.plot.imshow()` example, then the way I'm imagining this would be done is to add the optional argument `animate_over` to the `plot_2d` decorator, and use it to choose between returning the matplotlib artist (as it does currently) or the "block". It would also mean altering the logic inside `plot_2d` and `imshow` to account for the fact you would be calling this on a 3D dataarray instead of a 2D one.

I wanted to ask about this before delving into the code too much or submitting a pull request, in case  there is some problem with the idea. What do you think?

**Comment by fujiisoup** [comment]
I personally like this idea, as I often want to make an animated plot. How do any @pydata/xarray members think?

**Comment by fischcheng** [comment]
I want this feature, and the way you proposed is very elegant! The last time I made an animation, I needed to output each frames to .png and packed them as a movie file using imagemagick. I would love to see this feature realized!!

**Comment by dcherian** [comment]
I would love this feature. It is definitely a common use case in the Earth sciences.

**Comment by shoyer** [comment]
This looks pretty handy to me, too!

What are the advantages of returning a "block" rather than an animation object consisting of a single block? I don't entirely understand why animatplot adds a notion of blocks in addition to matplotlib's axis.

**Comment by t-makaro** [comment]
Matplotlib's axis is a place to plot stuff. Animatplot's blocks are "things" that are to be animated. Multiple blocks can be attached to a single axis like [multiple lines](https://animatplot.readthedocs.io/en/latest/gallery/sq_well..html) or a [pcolormesh + quiver plot](https://animatplot.readthedocs.io/en/latest/gallery/vector_plot..html). Right now, all of the blocks animate data, but in the future there will be blocks that animate annotations or modify some axis settings. 

Maybe you'll prefer to return an animation with a single block, but if you return the block then you can combine it with more blocks. You could animate two imshow's side by side. Now, I believe that matplotlib does have the ability to attach multiple animations to a single figure, but that could cause issues with syncing, and animatplot's controls would likely (read should) control each animation individually.

**Comment by shoyer** [comment]
Xarray's plotting APIs general work for *either* figure or axis level plotting. But they don't handle explicit subplots -- for those use cases it usually makes sense to switch into matplotlib for more control.

My inclination is in xarray we should return `Animation` objects, from which the `blocks` attribute could be extracted if need be for further customization with animatplot. Most plotting methods will return an animation consisting of a single blocks, but some of these would actually return multiple blocks (e.g., for plotting multiple lines at once).

**Comment by TomNicholas** [comment]
> we should return Animation objects

So if you made a 2D animated plot, you would return an instance of an animation object, from which you can also get the blocks for the imshow, the colorbar, the title etc. 

That would be neater for single plots, but if you wanted to create an [animation with two plots](https://animatplot.readthedocs.io/en/latest/tutorial/blocks..html), you would need something like:

``` python
turb2d = xr.load_dataset("turbulent_fluid_data.nc")

# Create individual animations
imshow_animation, imshow_blocks = turb2d["density"].plot.imshow(animate_over='time')
line_animation, line_blocks = turb2d["density"].mean(dim='z').plot.line(animate_over='time')

# Create animation with both plots on same figure
anim = amp.Animate(imshow_blocks, line_blocks)

# Save the combined gif
anim.save_gif("fluid_density.gif") 
plt.show()

```
However the initialisation of the `Animation` object is when the animation is actually created, so you would create 3 animations with that code! Is this actually what you mean or have I misunderstood?

**Comment by t-makaro** [comment]
Yes, this would have created 3 animations. Matplotlib requires a reference to an animation to be held. So,
```
del imshow_animation
del line_animation
```
should effectively remove the 2 additional animations. Though this is cumbersome. 

You might be able to add blocks in an existing animation by:
```
anim.blocks.append(extra_block)
```
since the animation object stores the blocks as a list, but this is currently undocumented and circumvents the check to ensure that all blocks are the same length. (I haven't tested it, but so long as the added block is at least as long as the other blocks it should work.)

Another thing to consider is that animations also take an optional "Timeline" which holds the values of time at each frame of the animation, which can be displayed using the timeline_slider method. Though, I think I have an idea for a title block.... (lots of ideas on the go for the next release of animatplot).

From what I understand of xarray, the timeline object can be constructed using coords. If you return blocks, the you may want to return this timeline object.

I'd probably lean towards xarray returning the animation. In that case, the internal implementation may want to create a new matplotlib figure for each of the animation.
