### ISSUE TITLE
Subclassing xarray.Dataset Autovivification: creation of empty dictionaries

### ISSUE THREAD

**Issue by AdelIbr1995** [pydata/xarray#2358]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import xarray
class NestedDict(xarray.Dataset):
    
    def __getitem__(self, keys):
        # Let's assume *keys* is a list or tuple.                             
        if not isinstance(keys, str):
            try:
                node = self
                for key in keys:
                    # node = xarray.Dataset.__getitem__(node, key)
                    try:
                        node = node[key]
                    except TypeError:
                        pass
                return node or 0 # STM: return 0 instead of empty xarray.Dataset if entry key is nonexistent - makes computations easier... but careful!
            except TypeError:
            # *keys* is not a list or tuple.                              
                pass
        return xarray.Dataset.__getitem__(self, keys)
#        try:
#            return xarray.Dataset.__getitem__(self, keys)
#        except KeyError:
#            return None
            #raise KeyError(keys)
    def __setitem__(self, keys, value):
        # Let's assume *keys* is a list or tuple.  
        if not isinstance(keys, str):
            try:
                node = self
                for key in keys[:-1]:
                    try:
                        node = xarray.Dataset.__getitem__(node, key)
                    except KeyError:
                        node[key] = type(self)()
                        node = node[key]
                return xarray.Dataset.__setitem__(node, keys[-1], value)
            except TypeError:
                # *keys* is not a list or tuple.                              
                pass
        print(self,keys, value)
        xarray.Dataset.__setitem__(self, keys, value)
    
    def __missing__(self, key):
        value = self[key] = type(self)()
        return value

```
#### Problem description
In order to improve the implementation of the data I wanted to test Xarray package. Initially, the NestedDict subclass inherits all the characteristics of the dict () class. So, instead of crashing because of keys that do not exist Python creates empty dictionaries. Examples of output:

(NestedDict)>>> (executing lines 1 to 47 of "toolclasses.py")
(NestedDict)>>> toto=NestedDict()
(NestedDict)>>> toto['A']=2
(NestedDict)>>> toto['A']=2
(NestedDict)>>> toto['N']
{}
(NestedDict)>>> toto
{'A': 2, 'N': {}}
(NestedDict)>>> toto['N1']['N2']['N3']
{}
(NestedDict)>>> toto
{'A': 2, 'N': {}, 'N1': {'N2': {'N3': {}}}}
(NestedDict)>>> toto['a1']['a2']['a3']=3456
(NestedDict)>>> toto
{'A': 2, 'N': {}, 'N1': {'N2': {'N3': {}}}, 'a1': {'a2': {'a3': 3456}}}
(NestedDict)>>> toto[['b1','b2','b3']]=3456
(NestedDict)>>> toto
{'A': 2, 'N': {}, 'N1': {'N2': {'N3': {}}}, 'a1': {'a2': {'a3': 3456}}, 'b1': {'b2': {'b3': 3456}}}
(NestedDict)>>> titi=['b1','b2','b3']
(NestedDict)>>> titi[:-1]
['b1', 'b2']

On the other hand, when the NestedDict class inherits the properties of xarray.Dataset, this method of creating empty dictionaries does not work and gives the following errors:

(__getitem__)>>>tata=NestedDict()

(__getitem__)>>>tata['CNG']
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "C:\Users\user\Documents\Etudes\FSIM\toolclasses.py", line 19, in __getitem__
return xarray.Dataset.__getitem__(self, keys)
File "c:\users\user\anaconda3\lib\site-packages\xarray\core\dataset.py", line 880, in __getitem__
return self._construct_dataarray(key)
File "c:\users\user\anaconda3\lib\site-packages\xarray\core\dataset.py", line 783, in _construct_dataarray
self._variables, name, self._level_coords, self.dims)
File "c:\users\user\anaconda3\lib\site-packages\xarray\core\dataset.py", line 73, in _get_virtual_variable
ref_var = variables[ref_name]
KeyError: 'CNG'

(__getitem__)>>>tata['CNG']=NestedDict()
<xarray.NestedDict>
Dimensions: ()
Data variables:
*empty* CNG <xarray.NestedDict>
Dimensions: ()
Data variables:
*empty*

(__getitem__)>>>tata['CNG','toto','dsl']=NestedDict()
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "C:\Users\user\Documents\Etudes\FSIM\toolclasses.py", line 33, in __setitem__
node = xarray.Dataset.__getitem__(node, key)
File "c:\users\user\anaconda3\lib\site-packages\xarray\core\dataset.py", line 880, in __getitem__
return self._construct_dataarray(key)
File "c:\users\user\anaconda3\lib\site-packages\xarray\core\common.py", line 176, in __getattr__
(type(self).__name__, name))
AttributeError: 'DataArray' object has no attribute '_construct_dataarray'

Maybe somebody know how deal with it ? Is ther any athor methodes to create emplty dictionary which allows avoid AttributeError ?

**Comment by fmaussion** [comment]
> Maybe somebody know how deal with it ? 

Before going into more details, are you sure that subclassing is the right path for you? In xarray we recommend to use composition over inheritance: maybe an accessor would do what you need?  See http://xarray.pydata.org/en/latest/internals.html#extending-xarray

**Comment by AdelIbr1995** [comment]
@fmaussion Thank you for the answer ! I've never used accessors but I will study some documentation and will try it. But still even if it's preferably use comppostion I don't see where the error comes from in subclassing with xarray because with dict() this methode of autovivification works.
