### ISSUE TITLE
Using dask.distributed  causes xr.open_mfdataset(..., parallel=True) to fail (MergeError). 

### ISSUE THREAD

**Issue by ntlewis** [pydata/xarray#2359]
#### Code Sample, a copy-pastable example if possible

Note, the below function is provided for as much context as possible, but is designed to load files from a particular file path (on my machine). 

```python
import xarray as xar
import os
import time
from dask.distributed import Client, LocalCluster

def open_experiment(base_dir, exp_folder_name, start_file, end_file, file_name):
    """Simple function to open netcdf files as one dataset object in xarray"""

    # compile list of netcdf file paths 
    base_dir = os.environ['GFDL_DATA']
    #base_dir = '/Users/Neil/gv3/isca_data'
    #base_dir = '/Volumes/ext_drive/seasons_research'
    folder_list = ['run%04d' % m for m in range(start_file, end_file+1)] 
    files = [base_dir + '/' + exp_folder_name+ '/' + folder_list[i] + '/' + file_name for i in range(len(folder_list))]
    files_exist=[os.path.isfile(s) for s in files]
    if not(all(files_exist)):
        raise EOFError('EXITING BECAUSE OF MISSING FILES', [files[elem] for elem in range(len(files_exist)) if not files_exist[elem]])

    n_files = end_file - start_file + 1 # number of files to open 
    cluster = LocalCluster(n_workers=n_files, threads_per_worker=1)
    client = Client(cluster, processes=True)
    #print(client)
    start = time.clock()
    ds = xar.open_mfdataset(files, decode_times=False, parallel=True, autoclose=True, concat_dim='time')  
    client.close()
    end = time.clock()
    print('LOADING:', end-start)

    return ds

```
#### Problem description

The above method allows me to open two files, i.e. `files=['file1.nc','file2.nc']`, however adding another (i.e. 3 files or more) causes the following error (e.g. `files=['file1.nc','file2.nc','file3.nc']`:

```Traceback (most recent call last):
  File "plot_seasonal_evol.py", line 34, in <module>
    surface_temperature, doy = af.seasonal('t_surf', base_dir, experiments, start, end, 'atmos_monthly.nc')
  File "/scratch/nl290/ShareCode/plotting/analyse_functions_neil.py", line 177, in seasonal
    ds = open_experiment(base_dir, exp, start, end, file)
  File "/scratch/nl290/ShareCode/plotting/analyse_functions_neil.py", line 34, in open_experiment
    ds = xar.open_mfdataset(files, decode_times=False, parallel=True, concat_dim='time')  
  File "/scratch/nl290/envs/isca_env/lib/python2.7/site-packages/xarray/backends/api.py", line 642, in open_mfdataset
    data_vars=data_vars, coords=coords)
  File "/scratch/nl290/envs/isca_env/lib/python2.7/site-packages/xarray/core/combine.py", line 439, in auto_combine
    merged = merge(concatenated, compat=compat)
  File "/scratch/nl290/envs/isca_env/lib/python2.7/site-packages/xarray/core/merge.py", line 522, in merge
    variables, coord_names, dims = merge_core(dict_like_objects, compat, join)
  File "/scratch/nl290/envs/isca_env/lib/python2.7/site-packages/xarray/core/merge.py", line 440, in merge_core
    variables = merge_variables(expanded, priority_vars, compat=compat)
  File "/scratch/nl290/envs/isca_env/lib/python2.7/site-packages/xarray/core/merge.py", line 164, in merge_variables
    merged[name] = unique_variable(name, variables, compat)
  File "/scratch/nl290/envs/isca_env/lib/python2.7/site-packages/xarray/core/merge.py", line 83, in unique_variable
    % (name, out, var))
xarray.core.merge.MergeError: conflicting values for variable u'ps' on objects to be combined:
first value: <xarray.Variable (time: 720, lat: 64, lon: 128)>
dask.array<shape=(720, 64, 128), dtype=float32, chunksize=(180, 64, 128)>
Attributes:
    long_name:      surface pressure
    units:          pascals
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
second value: <xarray.Variable (time: 720, lat: 64, lon: 128)>
dask.array<shape=(720, 64, 128), dtype=float32, chunksize=(540, 64, 128)>
Attributes:
    long_name:      surface pressure
    units:          pascals
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
```

This does not happen if I do not use the distributed scheduler (i.e. remove all reference to Client, LocalCluster, etc.), and instead `ds` is returned as expected. 

#### Expected Output

The output of `xr.open_mfdataset` when no call to `dask.distributed` has been made (i.e. default scheduler has been used). That is, I assume using the distributed scheduler should not have any bearing on the results of `xr.open_mfdataset`?

#### Question

Is this a bug with xr.open_mfdataset, or am I using the above features (`dask.distibuted`, `xr.open_mfdataset`) incorrectly?

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.142-1.el6.elrepo.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: None.None

xarray: 0.10.8
pandas: 0.20.3
numpy: 1.13.1
scipy: 0.19.1
netCDF4: 1.2.4
h5netcdf: None
h5py: 2.7.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.15.2
distributed: 1.18.1
matplotlib: 2.0.2
cartopy: None
seaborn: None
setuptools: 36.4.0
pip: 9.0.1
conda: None
pytest: None
IPython: None
sphinx: None

</details>

**Comment by jhamman** [comment]
This is an interesting error. A few thoughts...

- The only difference that I can see in the two variables is the dask chunk size. I don't think this should cause an issue but it would be worth looking into.
- If you can distill this down into a self contained example, it would make it much easier to dig into on our end.
- just an fyi, `distributed.Client()` will create a local cluster for you so you can skip the LocalCluster step in your example.

**Comment by ntlewis** [comment]
@jhamman Just wondering whether you had been able to look at the above? Could this be considered a bug?

**Comment by jhamman** [comment]
@ntlewis - I have not. It is difficult to sort out what is going wrong in your case. Can I ask you to spend a bit more time boiling down the problem? Ideally, something that we can test with some synthetic data.

You may also try a few options with the `data_vars` kward to `open_mfdataset`.
