### ISSUE TITLE
Indexing dataset with dimension name stored in python variable

### ISSUE THREAD

**Issue by Scheibs** [pydata/xarray#2361]
I try to work with some netCDF file who can have various dimensions names like NTime0, NTime1 ...
Is there a way to indexing dataset with dimension name stored in python variable ?

```python
timesel = ['2017-08-09','2017-01-10']
for dim in ds.dims :
    if dim.find("Time")>=0 :
        ds = ds.sel(dim=timesel)
**ValueError: dimensions or multi-index levels ['dim'] do not exist**
```

**Comment by spencerkclark** [comment]
Yes, it is possible to do this through dictionary unpacking, e.g. `ds = ds.sel(**{dim: timesel})`.
