### ISSUE TITLE
Passing origin keyword to DataArray.plot.imshow does not behave as expected

### ISSUE THREAD

**Issue by georgegeddes** [pydata/xarray#2379]
#### Code Sample
```python
from numpy import arange
from xarray import DataArray
import matplotlib.pyplot as plt

a = DataArray(arange(100).reshape((10,10)), dims=('x', 'y'))

print('a[0, 0] ==', a.loc[0, 0])

for origin in ('upper', 'lower'):
    a.plot.imshow(size=2, origin=origin)
    plt.title('origin=%s' % origin)
plt.show()
```
#### Problem description

The 'upper' case should plot the [0,0] block in the top left, and 'lower' should plot it in the bottom left, but the actual behavior is opposite. Passing origin='lower' also fails to flip the y-axis labels.

![upper](https://user-images.githubusercontent.com/10374429/44538938-c39c2a00-a6d0-11e8-9f52-7135c0e66c3c.png)

![lower](https://user-images.githubusercontent.com/10374429/44538941-c72fb100-a6d0-11e8-8a71-3f446cc84a89.png)

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.3-arch1-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.7
pandas: 0.23.1
numpy: 1.13.3
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: None
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.18.1
distributed: 1.22.0
matplotlib: 2.2.2
cartopy: None
seaborn: 0.8.1
setuptools: 39.2.0
pip: 10.0.1
conda: 4.5.10
pytest: 3.6.2
IPython: 6.4.0
sphinx: 1.7.5

</details>

**Comment by dcherian** [comment]
After #2396 

![image](https://user-images.githubusercontent.com/2448579/45035884-b429c300-b078-11e8-940e-a390d77c11db.png)

![image](https://user-images.githubusercontent.com/2448579/45035900-bee45800-b078-11e8-93fb-df0eccc0de8b.png)

I'm not sure what I did that exchanged the x- and y- labels
