### ISSUE TITLE
Why are there two compute calls for plot?

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#2390]
Anecdotally I find that when I call `.plot()` on a dataset object that holds dask arrays `compute` gets called twice.  Why is this?  I'm curious if this is something that should be resolved.

**Comment by mrocklin** [comment]
Sorry, I meant `plot.imshow()`

**Comment by rabernat** [comment]
My guess is that this is happening because there is first a call to get the bounds on the data (vmin, vmax). 

Does the double compute still happen if you specify vmin and vmax in the call to `.plot()`?

**Comment by shoyer** [comment]
We should probably call `compute()` on xarray objects immediately upon entering a plot method. My guess is that this happens because we rely upon coercing with `np.asarray()` or `DataArray.values` to get numpy arrays in xarray plotting methods.
