### ISSUE TITLE
Accessing variables starting with digits

### ISSUE THREAD

**Issue by aolt** [pydata/xarray#2402]
It could be something obvious, I wonder how one can access arrays starting with digits?

For example:
```
In [13]: ds
Out[13]: 
<xarray.Dataset>
Dimensions:                (g0_lat_1: 721, g0_lon_2: 1440, initial_time0_hours: 744)
Coordinates:
  * g0_lat_1               (g0_lat_1) float32 90.0 89.75 89.5 89.25 89.0 ...
  * g0_lon_2               (g0_lon_2) float32 0.0 0.25 0.5 0.75 1.0 1.25 1.5 ...
  * initial_time0_hours    (initial_time0_hours) datetime64[ns] 2008-01-01 ...
Data variables:
    10U_GDS0_SFC           (initial_time0_hours, g0_lat_1, g0_lon_2) float32 ...
    initial_time0          (initial_time0_hours) |S0 ...
    initial_time0_encoded  (initial_time0_hours) float64 ...


In [15]: ds.10U_GDS0_SFC
  File "<ipython-input-15-25d1b782289d>", line 1
    ds.10U_GDS0_SFC
        ^
SyntaxError: invalid syntax
```
<details>
In [14]: xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-33-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: None.None

xarray: 0.10.8
pandas: 0.23.3
numpy: 1.14.5
scipy: 1.1.0
netCDF4: 1.4.0
h5netcdf: 0.6.1
h5py: 2.8.0
Nio: 1.5.0
zarr: 2.2.0
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.18.2
distributed: 1.22.0
matplotlib: None
cartopy: None
seaborn: None
setuptools: 40.0.0
pip: 18.0
conda: 4.5.11
pytest: None
IPython: 5.8.0
sphinx: None
</details>

**Comment by max-sixty** [comment]
You need to use the dict syntax if it's not a valid attribute name - e.g. `ds['10UGD']`

Thanks for the question. Closing but please reopen if unclear / post more questions. (And we're all on StackOverflow too)
