### ISSUE TITLE
Achieving square aspect for Facetgrid heatmaps

### ISSUE THREAD

**Issue by andymcarter** [pydata/xarray#2406]
```python
import xarray as xr
import numpy as np
%matplotlib inline

array = xr.DataArray(np.random.rand(20,5,2,1), dims=['a', 'b', 'c', 'd'])
array.plot(x='a', y='b', col='c')
```
![image](https://user-images.githubusercontent.com/22293319/45207708-9dee5380-b280-11e8-9e63-4cc633a19f09.png)

#### Problem description

How can I force these heatmap cells into squares rather than rectangles? I'm aware that it is possible to pass kwargs through to Seaborn's FacetGrid, but setting `square=True` or `subplot_kws={'square":True}` both raise `AttributeError: Unknown property square`.

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.8
pandas: 0.23.4
numpy: 1.15.1
scipy: 1.1.0
netCDF4: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.18.2
distributed: 1.22.1
matplotlib: 2.2.3
cartopy: None
seaborn: 0.9.0
setuptools: 40.2.0
pip: 10.0.1
conda: 4.5.11
pytest: 3.7.3
IPython: 6.5.0
sphinx: 1.7.7

</details>

**Comment by dcherian** [comment]
```
g = array.plot(x='a', y='b', col='c')
[axis.set_aspect('equal') for axis in g.axes.ravel()]
```
![image](https://user-images.githubusercontent.com/2448579/45213224-8c26a380-b2b4-11e8-8932-392b3b6653be.png)

Is this what you want?

I don't know that we need to add `square=True` as a supported argument but consistency with seaborn could be a good thing I guess. Thoughts?

**Comment by jbusecke** [comment]
I like the idea. I would prefer `aspect_square=True` to be more clear.

**Comment by dcherian** [comment]
Thoughts on having `axis_aspect` as the kwarg name?

**Comment by jbusecke** [comment]
I would prefer `axis_aspect` to allow other than square aspects.

**Comment by dcherian** [comment]
In that case, #2427 is ready to review

**Comment by dcherian** [comment]
Closing since PR didn't get traction, plot has too many kwargs and it's easy to do this otherwise.
