### ISSUE TITLE
plot.line does not accept non-dimension coordinates

### ISSUE THREAD

**Issue by davidlow** [pydata/xarray#2407]
plot.line does not accept non-dimension coordinates
(https://stackoverflow.com/questions/52103604/xarray-plot-line-with-non-dimensional-coordinate/52190961#52190961)

```python
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

# Setup data array, from http://xarray.pydata.org/en/stable/plotting.html#multidimensional-coordinates
lon, lat = np.meshgrid(np.linspace(-20, 20, 5), 
                       np.linspace(0, 30, 4))
lon += lat/10
lat += lon/10
da = xr.DataArray(np.arange(20).reshape(4, 5), dims=['y','x'],
                     coords = {'lat': (('y', 'x'), lat),
                               'lon': (('y', 'x'), lon)})

# plot in terms of y,x, the dimensional coordinate
fig,ax = plt.subplots()
da.plot.pcolormesh('y','x') 

# plot in terms of lon, lat, the non-dimensional coordinate
fig, ax = plt.subplots()
da.plot.pcolormesh('lon', 'lat')

# plot lines in terms of x,y, the dimensional coordinate
fig, ax = plt.subplots()
da.plot.line(x='x')

# plot lines in terms of lon, lat?
da.plot.line(x='lon') #gives error

```
#### Problem description

It would be nice if I could plot line cuts through 2D data with a non-dimensional coordinate.  It is possible with 2D plotting.  

#### Output of ``xr.show_versions()``
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.3-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.8
pandas: 0.23.3
numpy: 1.15.0
scipy: 1.1.0
netCDF4: 1.4.0
h5netcdf: 0.6.1
h5py: 2.8.0
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: 0.9.0
setuptools: 40.0.0
pip: 18.0
conda: None
pytest: None
IPython: 6.4.0
sphinx: None

```

<details>
# Paste the output here xr.show_versions() here

</details>

**Comment by dcherian** [comment]
#2408 has some kind of solution. It needs tests and error checking. 

It's hard to choose which dimension you want on the x-axis (i.e. do we provide matplotlib with `darray` or `darray.T`), so I've added a `transpose` kwarg for manual control (see examples below).

`da.plot.line(y='lon', hue='lat')`

![image](https://user-images.githubusercontent.com/2448579/45264608-d185d500-b45c-11e8-9f84-6f0afa0eefe5.png)

`da.plot.line(y='lon', hue='lat', transpose=True)`

![image](https://user-images.githubusercontent.com/2448579/45264614-dcd90080-b45c-11e8-9b9b-51a25a03a418.png)

Do people think this is a good idea?

**Comment by shoyer** [comment]
I'm not sure about `transpose` argument here. It feels a little out of place with the rest of xarray's plotting API which is more declarative based on dimension/variable names. Maybe the color could be based on a dimension coordinate name instead, e.g., `da.plot.line(x='lon', hue='y')`?

**Comment by shoyer** [comment]
We also might separate repeated lines from coloring, e.g., with a dedicated keyword argument like `repeat` or `join`.

**Comment by dcherian** [comment]
With the latest commit,#2408 requires that `hue` be a dimension name for 2D co-ordinates. 

`da` is
```
<xarray.DataArray (y: 4, x: 5)>
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])
Coordinates:
    lat      (y, x) float64 -2.0 -1.0 0.0 1.0 2.0 ... 28.3 29.3 30.3 31.3 32.3
    lon      (y, x) float64 -20.0 -10.0 0.0 10.0 20.0 ... -7.0 3.0 13.0 23.0
Dimensions without coordinates: y, x
```

![image](https://user-images.githubusercontent.com/2448579/45925097-f2185980-bf49-11e8-9709-2cd1b4dfe866.png)

![image](https://user-images.githubusercontent.com/2448579/45925098-f3498680-bf49-11e8-946a-3e27ed97050f.png)

I'm not sure what to do about the legend though. @davidlow What would be a useful legend for this plot? @shoyer your second solution might be cleaner with `hue='lat', join='x'` and we build a legend with `darray[hue]`.

**Comment by davidlow** [comment]
I'm not really sure about legends either @dcherian.  I think it makes sense to pick whatever the coordinate of whatever was chosen in `hue` (or `join` in @shoyer solution).

**Comment by dcherian** [comment]
@davidlow #2408 requires that `hue` be a dimension for 2D co-ordinates, so there's no way to know. I'm inclined to leave it at this and let the user apply their own custom legend.
