### ISSUE TITLE
datetime parser different between 32bit and 64bit installations

### ISSUE THREAD

**Issue by mullenkamp** [pydata/xarray#2411]
I just noticed that my 64bit Python 3.6 installation with xarray does not parse the datetimes correctly from a netcdf, while the 32bit version seems to work fine. There seems to be some kind of offset.

Since I can't attach a netcdf to this issue, here's a link to an example netcdf file:
https://drive.google.com/open?id=1WhtWmN1ZBpbsfu7q7hGy2le-nujInfkI

This seems to happen for both 0.10.7 and 0.10.8.
The datetime values should be hourly.

Thanks!

```python
import xarray as xr

ms1 = xr.open_dataset(nc)
print(ms1.time)
```

**Comment by shoyer** [comment]
Hi @mullenkamp -- could you kindly share the output of `xr.show_versions()` for both the working and non-working installs?

**Comment by mullenkamp** [comment]
I'm very sorry. It turns out that it was an old dependency issue with the 64bit version. I thought I had updated both...but they were not...
