### ISSUE TITLE
manually specify chunks in open_zarr

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#2423]
Currently, `open_zarr` has two possible chunking behaviors. `auto_chunk=True` (default) creates dask chunks corresponding with zarr chunks. `auto_chunk=False` creates no chunks. But what if you want to manually specify the chunks, as with `open_dataset(chunks=...)`. `open_zarr` could easily support this, but it does not currently.

Note that this is *not* the same as calling `.chunk()` post dataset creation. That operation is very inefficient, since it begins from a single global chunk for each variable.

**Comment by andersy005** [comment]
Is it not the case that this issue was fully addressed by #2530 ?

**Comment by dcherian** [comment]
Looks like it. Thanks!
