### ISSUE TITLE
Stickler-ci

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#2428]
The last time stickler had a look at our PRs is 8 days ago (https://github.com/pydata/xarray/pull/2415) : https://stickler-ci.com/repositories/26661-pydata-xarray

It looks like their bot is broken: https://github.com/stickler-ci

This is not very trustworthy - we could consider switching to https://pep8speaks.com/ maybe

**Comment by fujiisoup** [comment]
I set up pep8speaks. 
It is now working for every new PR, **without** merging #2462. 

See settings > Integrations and Services
https://github.com/pydata/xarray/settings/installations

I am not yet sure whether it matches to our requirement. Let's see how well it works for a few weeks :)

**Comment by max-sixty** [comment]
Weirdly, it's still working on `pandas-gbq` fine: https://github.com/pydata/pandas-gbq/pull/225
