### ISSUE TITLE
Documentation Review Request for Arviz

### ISSUE THREAD

**Issue by canyon289** [pydata/xarray#2429]
Hello,
This isn't an issue with Xarray, I just wasn't sure of how to generally contact the Xarray devs other than a github Issue.

Arviz would like to add some light documentation to introduce our users to xarray. We wanted to reach out to see if xarray devs wanted to review it before we "publish" it to our docs.

There's no obligation of course, we just wanted to ensure we proactively ask for your feedback if you wanted to provide an opinion.

Notebook
https://github.com/arviz-devs/arviz/blob/2b95e70dce7cf4f3c1bc41bcc030b1bf1b579359/doc/notebooks/XarrayforArviZ.ipynb

Pull request
https://github.com/arviz-devs/arviz/pull/256

**Comment by jhamman** [comment]
Thanks for sharing. Its nice to see xarray's being used in this way. 

I gave your notebook a quick skim. I would suggest changing some of the nomenclature:

- netcdf --> NetCDF
- xarray.DataSet --> xarray.Dataset
- Data Variables --> data variables

and a few possible typos:

- In xarray terminology Data Variable --> In xarray's terminology, data variables
- netcd documentation --> netcdf4-python documentation
- netcd usage in xarray --> NetCDF usage in xarray

**Comment by canyon289** [comment]
Great! I'll make the changes. Thank you very much for the feedback

**Comment by max-sixty** [comment]
Looks good @canyon289 !

I thought we'd decided to use Xarray rather than xarray, but the docs have xarray throughout. @jhamman is my memory serving me poorly? I could do a find / replace on the docs if it's correct

**Comment by jhamman** [comment]
@max-sixty - Xarray when it used at the beginning of a sentence, otherwise just xarray. I must admit, I probably am not super consistent on this point though.

**Comment by max-sixty** [comment]
OK!

**Comment by shoyer** [comment]
Two minor comments:
- "xarray" is the name of the package, not a particular type, so it's strange to read "an xarray" or "xarray". I would use an "xarray object" or "xarray dataset" instead.
- If you're relying on netCDF4 groups, you might also mention that netCDF4 is built on top of HDF5, which many of your users may be familiar with from other contexts.

**Comment by canyon289** [comment]
Thank you for the additional feedback. It's been incorporated into a pull request
