### ISSUE TITLE
LooseVersion check on xarray in tests seems unstable

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#2468]
There's an elegant check against the xarray version to decide whether to run a test, so the test 'comes online' at 0.12: https://github.com/pydata/xarray/blob/638b251c622359b665208276a2cb23b0fbc5141b/xarray/tests/test_dataarray.py#L2029

But unfortunately, this seems very unstable in tests, because without a release, `LooseVersion` can't interpret the strings correctly (e.g.  `LooseVersion ('0.10.9+29.g33d9391a')`)
- A lot of the time it raises: https://travis-ci.org/max-sixty/xarray/jobs/437913418#L1036
- Occasionally it runs the test, failing to return that we're prior to 0.12: https://travis-ci.org/max-sixty/xarray/jobs/437914645#L5036

Here's the bug in the python issue tracker: https://bugs.python.org/issue14894

Is that synopsis correct? Should we attempt to take another approach? I'll disable it in my current check so tests can pass, but lmk thoughts.

**Comment by shoyer** [comment]
cc @fujiisoup 

It sounds like we should mark this as xfail and/or delete this test for now, or we could trim the last part of the version string before putting it into `LooseVersion`.
