### ISSUE TITLE
'module' object has no attribute 'AxisError'

### ISSUE THREAD

**Issue by am-thyst** [pydata/xarray#2483]
Just upgraded all of my packages through `conda update --all` and then got this error when importing xarray:

```python
Traceback (most recent call last):
  File "/var/spool/torque/mom_priv/jobs/63530.rdf-xcat.SC", line 11, in <module>
    import xarray as xr
  File "/nerc/n02/n02/amethyst/.conda/envs/my_root/lib/python3.4/site-packages/xarray/__init__.py", line 10, in <module>
    from .core.alignment import align, broadcast, broadcast_arrays
  File "/nerc/n02/n02/amethyst/.conda/envs/my_root/lib/python3.4/site-packages/xarray/core/alignment.py", line 11, in <module>
    from .indexing import get_indexer_nd
  File "/nerc/n02/n02/amethyst/.conda/envs/my_root/lib/python3.4/site-packages/xarray/core/indexing.py", line 11, in <module>
    from . import duck_array_ops, nputils, utils
  File "/nerc/n02/n02/amethyst/.conda/envs/my_root/lib/python3.4/site-packages/xarray/core/duck_array_ops.py", line 22, in <module>
    from . import dask_array_compat
  File "/nerc/n02/n02/amethyst/.conda/envs/my_root/lib/python3.4/site-packages/xarray/core/dask_array_compat.py", line 47, in <module>
    AxisError = np.AxisError
AttributeError: 'module' object has no attribute 'AxisError'

```

May be relevant, when I do `conda list`, I get two versions of xarray:
```
xarray                    0.10.9                    <pip>
xarray                    0.8.2                    py34_0
```

**Comment by max-sixty** [comment]
Thanks for the issue @am-thyst 

Could you uninstall both, and then reinstall?

If that doesn't work, please could you follow the steps on the default issue around listing dependencies?

**Comment by jhamman** [comment]
It also looks like you are running a pretty old version of python (3.4). We recently dropped support for this version of Python. 

These sorts of things are often easiest to debug with the output of `xr.show_versions()`.

**Comment by am-thyst** [comment]
@max-sixty @jhamman thanks for your replies, I uninstalled both versions of xarray that I had, tried (unsuccessfully `# All requested packages already installed.`) to update Python, then reinstalled xarray via `conda install -c anaconda xarray`, to which the import worked but gave:
```python
/nerc/n02/n02/amethyst/.conda/envs/my_root/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  return f(*args, **kwds)
```
The version of xarray installed is 0.8.2, which just won't seem to update to a newer version. Could be something to do with the fact I'm using Miniconda? Anyway, as long as it works for now. Is this likely to cause problems for me along the line?

**Comment by am-thyst** [comment]
@fmaussion Thank you, I'm trying this now. I actually just came back to this thread to edit my original reply - xarray 0.8 won't cut it for me because I need to use features from 0.10

That `conda update --all` really took me a few steps backwards! Hopefully the new environment will work better.
