### ISSUE TITLE
Dataset.copy docstring has a typo

### ISSUE THREAD

**Issue by georgegeddes** [pydata/xarray#2490]
The docstring of [Dataset.copy](https://github.com/pydata/xarray/blob/9f4474d657193f1c7c9aac25bb2edf94755a8593/xarray/core/dataset.py#L715-L730) states that the default of deep is True, but in the code it is False.

**Comment by jhamman** [comment]
@georgegeddes - thank for the report. Mind submitting a quick fix to the docstring?
