### ISSUE TITLE
geotif affine coordinate transformation

### ISSUE THREAD

**Issue by kbefus** [pydata/xarray#2497]
#### Code Sample, a copy-pastable example if possible

Just a spot in the documentation that will help future users load geotiff coordinates, especially for rotated rasters (current example assumes no rotation for extracting x-y pairs). Didn't want to make a whole branch just for this.

```python
# Documentation for xarray.open_rasterio (line 172 in code)
transform = Affine(*da.attrs['transform'])
# should be
transform = Affine.from_gdal(*da.attrs['transform'])

```
#### Problem description

Returns correct coordinates rather than incorrect coordinates (jump strangely in Y direction).

**Comment by fmaussion** [comment]
Thanks! See https://github.com/pydata/xarray/pull/2498 

(Note that GitHub allows to edit files online and does the branching / PR stuff for you, so that small fixes like this can be done exclusively online.)
