### ISSUE TITLE
isel slows down computation significantly after open_dataset

### ISSUE THREAD

**Issue by apatlpo** [pydata/xarray#2504]
isel significantly slows down a simple mean calculation:

```python
ds = xr.open_dataset(grid_dir_nc+'Depth.nc', chunks={'face':1})
print(ds)
% time print(ds.Depth.mean().values)
```
leads to:
```
<xarray.Dataset>
Dimensions:  (face: 13, i: 4320, j: 4320)
Coordinates:
  * i        (i) int64 0 1 2 3 4 5 6 7 ... 4313 4314 4315 4316 4317 4318 4319
  * j        (j) int64 0 1 2 3 4 5 6 7 ... 4313 4314 4315 4316 4317 4318 4319
  * face     (face) int64 0 1 2 3 4 5 6 7 8 9 10 11 12
Data variables:
    Depth    (face, j, i) float32 dask.array<shape=(13, 4320, 4320), chunksize=(1, 4320, 4320)>
1935.0237
CPU times: user 241 ms, sys: 16.9 ms, total: 258 ms
Wall time: 1.05 s
```

```
ds = xr.open_dataset(grid_dir_nc+'Depth.nc', chunks={'face':1})
ds = ds.isel(i=slice(None,None,4),j=slice(None,None,4))
% time print(ds.Depth.mean().values)
```
leads to:
```
1935.0199
CPU times: user 9.43 s, sys: 819 ms, total: 10.3 s
Wall time: 2min 57s
```

Is this expected behavior?

#### Output of ``xr.show_versions()``
I am using latest xarray version (`pip install  https://github.com/pydata/xarray/archive/master.zip`)

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.2.3.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0+unknown
pandas: 0.23.4
numpy: 1.15.3
scipy: 1.1.0
netCDF4: 1.4.1
h5netcdf: None
h5py: None
Nio: None
zarr: 2.2.0
cftime: 1.0.1
PseudonetCDF: None
rasterio: None
iris: None
bottleneck: None
cyordereddict: None
dask: 0.19.2
distributed: 1.23.2
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: None
setuptools: 40.2.0
pip: 10.0.1
conda: None
pytest: None
IPython: 6.5.0
sphinx: None
</details>

**Comment by apatlpo** [comment]
additional information about the file:

```
(equinox) [pontea@visu01 LLC4320]$ ncdump -sh grid_nc/Depth.nc
netcdf Depth {
dimensions:
        i = 4320 ;
        j = 4320 ;
        face = 13 ;
variables:
        int64 i(i) ;
                i:standard_name = "x_grid_index" ;
                i:axis = "X" ;
                i:long_name = "x-dimension of the t grid" ;
                i:swap_dim = "XC" ;
                i:_Storage = "contiguous" ;
                i:_Endianness = "little" ;
        int64 j(j) ;
                j:standard_name = "y_grid_index" ;
                j:axis = "Y" ;
                j:long_name = "y-dimension of the t grid" ;
                j:swap_dim = "YC" ;
                j:_Storage = "contiguous" ;
                j:_Endianness = "little" ;
        int64 face(face) ;
                face:standard_name = "face_index" ;
                face:_Storage = "contiguous" ;
                face:_Endianness = "little" ;
        float Depth(face, j, i) ;
                Depth:_FillValue = NaNf ;
                Depth:standard_name = "ocean_depth" ;
                Depth:long_name = "ocean depth" ;
                Depth:units = "m" ;
                Depth:coordinate = "XC YC" ;
                Depth:_Storage = "chunked" ;
                Depth:_ChunkSizes = 1, 480, 480 ;
                Depth:_Endianness = "little" ;

// global attributes:
                :_SuperblockVersion = 0 ;
                :_IsNetcdf4 = 1 ;
                :_Format = "netCDF-4" ;
}
```

**Comment by shoyer** [comment]
I think this is basically a netCDF4-Python issue. It is definitely a known issue that some complex indexing operations can be more expensive when done on netCDF4-Python arrays rather than in-memory NumPy arrays.

The easy work-around is to write something like `ds.load()` first to load the data into memory. Unfortunately this is hard to fix in general because there is a tradeoff in terms of memory usage. 

The other option is to try another netCDF4 backend engine, e.g., install h5netcdf and set `engine='h5netcdf'`.
