### ISSUE TITLE
groupby fails on generic ndarray functions

### ISSUE THREAD

**Issue by d-chambers** [pydata/xarray#2508]
This seems related to #326.

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import xarray as xr

da = xr.DataArray(np.random.randint(0, 1, (10, 10, 3)),  dims=['row', 'col', 'time'])

da.groupby('time').apply(np.linalg.norm)
```
#### Problem description

I would expect xarary to know how to apply generic numpy functions along specified axis. However, it currently raises the following exception:

```python

AttributeError                            Traceback (most recent call last)
<ipython-input-22-5451ed1f09ee> in <module>()
----> 1 da.groupby('time').apply(np.linalg.norm)

~/anaconda3/lib/python3.7/site-packages/xarray/core/groupby.py in apply(self, func, shortcut, **kwargs)
    514         applied = (maybe_wrap_array(arr, func(arr, **kwargs))
    515                    for arr in grouped)
--> 516         return self._combine(applied, shortcut=shortcut)
    517 
    518     def _combine(self, applied, shortcut=False):

~/anaconda3/lib/python3.7/site-packages/xarray/core/groupby.py in _combine(self, applied, shortcut)
    519         """Recombine the applied objects like the original."""
    520         applied_example, applied = peek_at(applied)
--> 521         coord, dim, positions = self._infer_concat_args(applied_example)
    522         if shortcut:
    523             combined = self._concat_shortcut(applied, dim, positions)

~/anaconda3/lib/python3.7/site-packages/xarray/core/groupby.py in _infer_concat_args(self, applied_example)
    289 
    290     def _infer_concat_args(self, applied_example):
--> 291         if self._group_dim in applied_example.dims:
    292             coord = self._group
    293             positions = self._group_indices

AttributeError: 'numpy.float64' object has no attribute 'dims'


```

#### Expected Output

a data array whit a time coordinate of size 3 (ie same shape as ``da.groupby('time').mean()``)

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-138-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.9
pandas: 0.23.4
numpy: 1.15.1
scipy: 1.1.0
netCDF4: 1.4.1
h5netcdf: 0.6.2
h5py: 2.8.0
Nio: None
zarr: None
cftime: 1.0.1
PseudonetCDF: None
rasterio: None
iris: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.19.1
distributed: 1.23.1
matplotlib: 2.2.3
cartopy: None
seaborn: 0.9.0
setuptools: 40.2.0
pip: 18.1
conda: 4.5.11
pytest: 3.8.0
IPython: 6.5.0
sphinx: 1.7.9

</details>

**Comment by shoyer** [comment]
You can use `xarray.apply_ufunc()` for these sort of problems, but `groupby.apply()` expects the result to be returned as a xarray object.

**Comment by dcherian** [comment]
I guess we could have `GroupBy.apply_raw`?

**Comment by dcherian** [comment]
I agree with just using `apply_ufunc`.
