### ISSUE TITLE
Dataset-wide _FillValue

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#2510]
I'm looking at a netCDF file that has the variable
```
	float T_20(time, depth, lat, lon) ;
		T_20:name = "T" ;
		T_20:long_name = "TEMPERATURE (C)" ;
		T_20:generic_name = "temp" ;
		T_20:FORTRAN_format = "f10.2" ;
		T_20:units = "C" ;
		T_20:epic_code = 20 ;
```

and global attributes
```
// global attributes:
		:platform_code = "8n90e" ;
		:site_code = "8n90e" ;
		:wmo_platform_code = 23007 ;
		:array = "RAMA" ;
		:Request_for_acknowledgement = "If you use these data in publications or presentations, please acknowledge the GTMBA Project Office of NOAA/PMEL. Also, we would appreciate receiving a preprint and/or reprint of publications utilizing the data for inclusion in our bibliography. Relevant publications should be sent to: GTMBA Project Office, NOAA/Pacific Marine Environmental Laboratory, 7600 Sand Point Way NE, Seattle, WA 98115" ;
		:Data_Source = "Global Tropical Moored Buoy Array Project Office/NOAA/PMEL" ;
		:File_info = "Contact: Dai.C.McClurg@noaa.gov" ;
		:missing_value = 1.e+35f ;
		:_FillValue = 1.e+35f ;
		:CREATION_DATE = "13:05 28-JUL-2017" ;
		:_Format = "classic" ;

```

#### Problem description

In this case the `_FillValue` and `missing_value` attributes are set for the entire dataset and not each individual variable. `decode_cf_variable` thus fails to insert NaNs.

I'm not sure that this is standards-compliant but is this something we could support?

**Comment by shoyer** [comment]
I'm pretty sure this isn't CF conventions compliant :). We could definitely do this in theory but I'm not sure it's worth the trouble. You could also fix this in a preprocessing step (i.e., by setting `decode_cf=False`, manually copying the attributes and then using `xarray.decode_cf()`).

**Comment by dcherian** [comment]
That's an easy enough solution. Thanks.

**Comment by jhamman** [comment]
AFAIK, storing the fill value in the global attributes does not follow any widely adopted convention (e.g. CF). Certainly *possible* to support but since we decode one variable at a time, I'm not sure our current approach would work. I think we'd need to know if there is a convention for this or if this particular dataset is just improperly formatted.

**Comment by jhamman** [comment]
Hmmm, my notifications are coming though with quite the lag today. I just saw @shoyer's comment. Sounds like we're all on the same page.
