### ISSUE TITLE
How to add coordinates to new dimensions while using xarray.apply_ufunc?

### ISSUE THREAD

**Issue by ShankhaNag** [pydata/xarray#2526]
Hi,
Please consider the following code:
```
import xarray as xr
class A:
   def __init__(self, x):
      self.x = x

da = xr.DataArray([A(5), A(9)], coords = [('a', ['a1', 'a2'])])
da2 = xr.apply_ufunc(lambda y: np.atleast_1d(y)[0].x, da, output_core_dims=[('b')], vectorize=True)
```
Output:
```
In [53]: da
Out[53]: 
<xarray.DataArray (a: 2)>
array([<__main__.A instance at 0x7f0dfa812a28>,
       <__main__.A instance at 0x7f0dfa41fb00>], dtype=object)
Coordinates:
  * a        (a) |S2 'a1' 'a2'

In [57]: da2
Out[57]: 
<xarray.DataArray (a: 2, b: 4)>
array([[5, 5, 5, 5],
       [9, 9, 9, 9]])
Coordinates:
  * a        (a) |S2 'a1' 'a2'
Dimensions without coordinates: b
```

Then if we do:
```
da2['b'] = ['b1', 'b2', 'b3', 'b4']
```

Then:
```
da2
Out[55]: 
<xarray.DataArray (a: 2, b: 4)>
array([[5, 5, 5, 5],
       [9, 9, 9, 9]])
Coordinates:
  * a        (a) |S2 'a1' 'a2'
  * b        (b) |S2 'b1' 'b2' 'b3' 'b4'
```

How to get the final solution with just _apply_ufunc_?

**Comment by ShankhaNag** [comment]
As a further clarification I think the above problem can be thought of comprising of two steps:
(1) applying a function to each element of the **foo**'s data which adds on a dimension to **foo**'s data.
(2) name the new dimension **e** with coordinates **e1**, **e2**, **e3**.

**Comment by shoyer** [comment]
> How to get the final solution with just apply_ufunc?

You can't. If you want to insert new coordinates, you should just use xarray's normal API for that (either assignment or `.assign_coords()`).

At one in the development of `apply_ufunc()` I think I had a feature like this, but it didn't do anything beyond what you can do by assigning  the coordinate yourself, and `apply_ufunc` already has a lot of options.

**Comment by ShankhaNag** [comment]
Ohk, your code your rules!

Thanks for the response :)
