### ISSUE TITLE
display_width doesn't apply to dask-backed arrays

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#2528]
The representation of dask-backed arrays in xarray's `__repr__` methods results in very long lines which often overflow the desired line width. Unfortunately, this can't be controlled or overridden with `xr.set_options(display_width=...)`. 

#### Code Sample, a copy-pastable example if possible

```python
import xarray as xr
xr.set_options(display_width=20)
ds = (xr.DataArray(range(100))
      .chunk({'dim_0': 10})
      .to_dataset(name='really_long_long_name'))
ds
```

```
<xarray.Dataset>
Dimensions:                (dim_0: 100)
Dimensions without coordinates: dim_0
Data variables:
    really_long_long_name  (dim_0) int64 dask.array<shape=(100,), chunksize=(10,)>
```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Expected Output

We need to decide how to abbreviate dask arrays with something more concise. I'm not sure the best way to do this. Maybe
```
   really_long_long_name  (dim_0) int64 dask chunks=(10,)
```

**Comment by shoyer** [comment]
As of #3211, we no longer include the redundant `shape` in short reprs for dask arrays.

So I'm going to close this, though of course further improvements to the short repr would be welcome!
