### ISSUE TITLE
to_dataframe() excessive memory usage

### ISSUE THREAD

**Issue by guygriffiths** [pydata/xarray#2534]
#### Code Sample, a copy-pastable example if possible

```python
import xarray as xr
from glob import glob

# This refers to a large multi-file NetCDF dataset
file_list = sorted(glob('~/Data/**/**/*.nc'))

dataset = xr.open_mfdataset(file_list,
                            decode_times=True,
                            autoclose=True,
                            decode_cf=True,
                            cache=False,
                            concat_dim='time')

# At this point, the total RAM used by the python process is ~1.4G

# Select a timeseries at a single point
# This is near instantaneous and uses no additional memory
ts = dataset.sel({'lat': 10, 'lon': 10}, method='nearest')

# Convert that timeseries to a pandas dataframe.
# This is where the actual data reading happens, and reads the data into memory
df = ts.to_dataframe()
# At this point, the total RAM used by the python process is ~10.5G
```
#### Problem description

Despite the fact that the resulting dataframe only has a single lat/lon point's worth of data, a huge amount of RAM is used.  I can get (what appears to be) an identical pandas DataFrame by changing the final line to:

```python
df = (ts * 1.0).to_dataframe()
```
which reduces the total RAM to ~2.2G (i.e. 0.6G additional RAM for that single line vs 9G additional RAM).  No type conversion is taking place (i.e. `ts` and `ts * 1.0` both have identical data types)

#### Expected Output

I would expect that `to_dataframe()` would require the same amount of memory whether or not it was multiplied by 1.0.  I'm aware there could be a good reason for this, but it took me by surprise somewhat.

#### Output of ``xr.show_versions()``

<details>

commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.7
pandas: 0.23.1
numpy: 1.13.3
scipy: 0.17.0
netCDF4: 1.4.1
h5netcdf: None
h5py: None
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.19.0
distributed: None
matplotlib: 1.5.1
cartopy: None
seaborn: 0.8.1
setuptools: 20.7.0
pip: 18.0
conda: None
pytest: None
IPython: 2.4.1
sphinx: None

</details>

**Comment by sgdecker** [comment]
Here is another example:
```
import xarray as xr
ncdata = xr.open_dataset('https://thredds.ucar.edu/thredds/dodsC/nws/metar/ncdecoded/files/Surface_METAR_20200411_0000.nc')
df = ncdata.to_dataframe()
```

Output is:
```
Traceback (most recent call last):
  File "bug.py", line 4, in <module>
    df = ncdata.to_dataframe()
  File "/home/decker/miniconda3/envs/met212/lib/python3.8/site-packages/xarray/core/dataset.py", line 4399, in to_dataframe
    return self._to_dataframe(self.dims)
  File "/home/decker/miniconda3/envs/met212/lib/python3.8/site-packages/xarray/core/dataset.py", line 4385, in _to_dataframe
    data = [
  File "/home/decker/miniconda3/envs/met212/lib/python3.8/site-packages/xarray/core/dataset.py", line 4386, in <listcomp>
    self._variables[k].set_dims(ordered_dims).values.reshape(-1)
MemoryError: Unable to allocate array with shape (117819, 5021) and data type |S64
```

If I'm doing the math right, xarray is trying to allocate roughly 35 GB even though this NetCDF file is only on the order of 50 MB in size.

Output of `xr.show_versions()`
<details><summary>Details</summary>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.1 | packaged by conda-forge | (default, Jan  5 2020, 20:58:18) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.31-1-MANJARO
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.3

xarray: 0.14.1
pandas: 0.25.3
numpy: 1.17.5
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.1.2
cartopy: 0.17.0
seaborn: None
numbagg: None
setuptools: 45.1.0.post20200119
pip: 19.3.1
conda: None
pytest: 5.3.4
IPython: 7.11.1
sphinx: None
```

</details>

**Comment by max-sixty** [comment]
Sorry these didn't get responses. It's possible that `to_dataframe` is doing some unstacking that's causing huge arrays to be allocated. I don't doubt these examples are real — though the `* 1` example above is very surprising — but we do need reproducible examples to engage.

Please reopen or start a new issue with a reproducible example, thanks.
