### ISSUE TITLE
Request:  Add support for the ERDDAP griddap request

### ISSUE THREAD

**Issue by rmendels** [pydata/xarray#2539]
xarray already supports OPenDAP requests,  and the ERDDAP service is being installed in many places,  and while an ERDDAP server can function as an OPeNDAP server, and its syntax is very close to the OpeNDAP syntax,  ERDDAP/griddap has the advantage that requests can be made in coordinate space.

Moreover,  it would not have to be coded from scratch,  ERDDAPy (https://github.com/pyoceans/erddapy) already has the code, it would be more of a question on how to integrate it.  The ERDDAP service can return both netcdf or .dds files if that makes it easier to integrate.

Thanks.

**Comment by jhamman** [comment]
Thanks @rmendels. I agree `erdappy` seems like good fit for an xarray backend. Its probably worth taking a close look at the pydap backend (https://github.com/pydata/xarray/blob/master/xarray/backends/pydap_.py). The biggest challenge with writing these remote backends is developing a stable test harness. 

cc @ocefpaf

**Comment by ocefpaf** [comment]
> I agree `erdappy` seems like good fit for an xarray backend.

Note that `erddapy` is not really a "client" it is a URL builder that leverages ERDDAP's RESTful Web Services and [`pandas`](https://github.com/pyoceans/erddapy/blob/55bf891dfa3b91fd895820f1c76ae8b7ee271e63/erddapy/erddapy.py#L161-L173) or [`xarray`](https://github.com/pyoceans/erddapy/blob/55bf891dfa3b91fd895820f1c76ae8b7ee271e63/erddapy/erddapy.py#L175-L184) to download data.

@rmendels and @jhamman please correct me if I'm wrong below:

The main advantage of ERDDAP, as @rmendels mention above, is that one can make  requests in coordinate space. However, I don't think there is an OPeNDAP response for that a sliced request in ERDDAP, just the "full data". Also, `xarray` can already ingest an OPeNDAP URL and lazily slice it using high level coordinate space syntax. (At the cost of load the coordinates but that is 99% of the time fast enough.)

The alternative would be to use the netCDF response but that means we would need to download the file and load it with `xarray`, which does not really justify a new backend IMO. (I do that in a very [inelegant way in erddapy](https://github.com/pyoceans/erddapy/blob/55bf891dfa3b91fd895820f1c76ae8b7ee271e63/erddapy/utilities.py#L149-L160).)

The download limitation exists in any of the "file format" responses in ERDDAP, making the OPeNDAP the best choice. So, unless we can figure out a way for ERDDAP to serve the "sliced" URL as OPeNDAP, I believe the best we can do already exists :grimacing:
