### ISSUE TITLE
Include filename or path in open_mfdataset

### ISSUE THREAD

**Issue by jsignell** [pydata/xarray#2550]
When reading from multiple files, sometimes there is information encoded in the filename. For example in these grib files the time: `./ST4.2018092500.01h`, `./ST4.2018092501.01h`. It seems like a generally useful thing would be to allow the passing of a `kwargs` (such as `path_as_coord` or something) that would define a set of coords with one for the data from each file. 

I think the code change would be small:

```python 
if path_as_coord:
    ds = ds.assign_coords(path=file_name)
```

In use it would be like: 

```python
>>>xr.open_mfdataset(['./ST4.2018092500.01h', './ST4.2018092501.01h'], engine='pynio', concat_dim='path')
<xarray.Dataset>
Dimensions:               (x: 881, y: 1121, time: 2)
Coordinates:
    lat             (x, y) float32 23.116999 ... 45.618984
    lon             (x, y) float32 -119.023 ... -59.954613
  * path            (path) <U20 './ST4.2018092500.01h' './ST4.2018092501.01h'
Dimensions without coordinates: x, y
Data variables:
    var_0  (time, x, y) float32 dask.array<shape=(2, 881, 1121), chunksize=(1, 881, 1121)>
    var_1   (time, x, y) float32 dask.array<shape=(2, 881, 1121), chunksize=(1, 881, 1121)>
```

For context I have implemented something similar in dask: https://github.com/dask/dask/pull/3908

**Comment by dcherian** [comment]
There is a preprocess argument. You provide a function and it is run on every file.

**Comment by jsignell** [comment]
> There is a preprocess argument. You provide a function and it is run on every file.

Yes but the input to that function is just the ds, I couldn't figure out a way to get the filename from within a preprocess function. This is what I was doing to poke around in there:

```python
def func(ds):
    import pdb; pdb.set_trace()

xr.open_mfdataset(['./ST4.2018092500.01h', './ST4.2018092501.01h'], 
                   engine='pynio', concat_dim='path', preprocess=func)
```

**Comment by jhamman** [comment]
@jsignell - perhaps not a very pretty solution but we do save the source of each variable in the encoding dictionary.

```python
ds['varname'].encoding['source']
```

Presumably, you could unpack this via a preprocess step.

**Comment by shoyer** [comment]
Hmm. It really seems like the `preprocess` function should pass in the file-name along with the dataset.

**Comment by jhamman** [comment]
@shoyer and @jsignell - I'd also be happy to see this added to the preprocess function. Ideally the function signature would look like:

```python
def preprocess(ds, filename=None):
    ...
    return ds
```

This would avoid a breaking change and allow us to add additional kwargs at a later date if need be.

**Comment by dcherian** [comment]
Hmm... Sorry @jsignell. I thought preprocess passed the filename too.

**Comment by jsignell** [comment]
Maybe we can inspect the `preprocess` function like this:

```python
>>> preprocess = lambda a, b: print(a, b)
>>> preprocess .__code__.co_varnames
('a', 'b')
```

This response is ordered, so the first one can always be `ds` regardless of its name and then we can look for special names (like `filename`) in the rest.

From this answer: https://stackoverflow.com/a/4051447/4021797

**Comment by shoyer** [comment]
The danger with inspecting user provided functions is that it's pretty
fragile, e.g., it fails if you use provide a signature like *args, **kwargs
(which can happen pretty easily with decorators). Probably the best option
is to come up with a new keyword argument to replace "preprocess" and to
deprecate the current preprocess (if we can think of another good name). We
could also do a deprecation cycle with FutureWarning, but that's pretty
painful.

**Comment by dcherian** [comment]
A dirty fix would be to add an attribute to each dataset.

**Comment by jsignell** [comment]
>A dirty fix would be to add an attribute to each dataset.

I thought @jhamman was suggesting that already exists, but I couldn't find it: https://github.com/pydata/xarray/issues/2550#issuecomment-437157299

**Comment by dcherian** [comment]
True, maybe we should track down why that isn't happening with your dataset

**Comment by jsignell** [comment]
Ah I don't think I understood that adding `source` to encoding was a new addition. In latest master (`'0.11.0+3.g70e9eb8`) this works fine:

```python
def func(ds):
    var = next(var for var in ds)
    return ds.assign(path=ds[var].encoding['source'])

ds = xr.open_mfdataset(['./air_1.nc', './air_2.nc'], concat_dim='path', preprocess=func)
```

I do think it is misleading though that after you've concatenated the data, the `encoding['source']` on a concatenated var seems to be the first path. 

```python
>>> ds['air'].encoding['source'] 
'~/air_1.nc'
```

I'll close this one though since there is a clear way to access the filename. Thanks for the tip @jhamman!

**Comment by shoyer** [comment]
I'm not sure `.encoding['source']` should really be relied upon -- it wasn't really an intentional API decision. But I guess it's harmless enough to include it...

**Comment by jsignell** [comment]
Should I add a test that expects `.encoding['source']` to ensure its continued presence?

**Comment by shoyer** [comment]
Yes, that sounds great! Potentially this would be a good opportunity for a
doc update, too.

**Comment by jsignell** [comment]
Having started writing a test, I now think that `encoding['source']` is backend specific. Here it is implemented in netcdf4: https://github.com/pydata/xarray/blob/70e9eb8fc834e4aeff42c221c04c9713eb465b8a/xarray/backends/netCDF4_.py#L386 but I don't see it for pynio for instance: https://github.com/pydata/xarray/blob/70e9eb8fc834e4aeff42c221c04c9713eb465b8a/xarray/backends/pynio_.py#L77-L81

Is this something that we want to mandate that backends provide?

**Comment by shoyer** [comment]
> Is this something that we want to mandate that backends provide?

I think it would be better to do this systematically, e.g., inside `xarray.open_dataset()`. We would need to verify that `filename_or_obj` is provided as a string, but if so we could add it into `encoding` on the Dataset object.
