### ISSUE TITLE
HDF Errors since xarray 0.11

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#2551]
(EDIT: sorry for unexpected early posting)

I just wanted to open this issue here, just to see if it has some resonance in other projects.

We are getting new unexpected HDF Errors in our test suite which are definitely due to the recent xarray update (reverting to 0.10.9 solves the problem).

The error is the famous (and very informative):

```
[Errno -101] NetCDF: HDF error: 
```

I have not been able to create a MWE yet, but it has something to do with read -> close -> append workflows on netcdf4 files (the error happens at the "append" step). Possibly multiprocessing also plays a role, but I can't be sure yet. 

I will try to find a way to reproduce this with a simple example, but this might take a while...

**Comment by shoyer** [comment]
Oh my -- sorry about that!

Thinking about this a little more, I guess this should not be too surprising since I don't think we have any dask integration tests that cover appending to existing files. Maybe a good place to start would be adding one of those, e.g., adapted from this existing test:
https://github.com/pydata/xarray/blob/575e97aef405c9b473508f5bc0e66332df4930f3/xarray/tests/test_distributed.py#L66

**Comment by fmaussion** [comment]
> I am slightly regretting not doing a release candidate here,

I should be better placed than anyone to anticipate and test more frequently on master :roll_eyes: 

So this reproduces the problem on my machine and [travis](https://travis-ci.org/pydata/xarray/builds/453229051?utm_source=github_status&utm_medium=notification). Note the misplaced computation out of the `with` block:

```python
import xarray as xr
import numpy as np
import netCDF4
import os

try:
    os.remove('test.nc')
except OSError:
    pass

thick = np.zeros((180, 200), np.float32)

ds = xr.Dataset()
ds['thick'] = (('y', 'x'), thick)
ds.to_netcdf('test.nc')

with xr.open_dataset('test.nc') as ds:
    dummy = ds.thick.isel(x=('z', [1, 3, 4]), y=('z', [7, 2, 1]))
    
dummy.min()  # this is the issue

with netCDF4.Dataset('test.nc', 'a') as nc:
    nc.variables['thick'][:] = thick  
```

I guess this was actually a bug in our code, but for some reason it worked fine earlier. I'm not sure if this requires action on the xarray side in the end...

**Comment by shoyer** [comment]
@fmaussion Yep, that looks a bug on your end. Were you using `autoclose=True` before? If so, that could have hidden the issue, because exiting the `with` block didn't use to actually close the file in that case.

**Comment by fmaussion** [comment]
> Yep, that looks a bug on your end. Were you using autoclose=True before?

No, the exact same piece of code works without error with xarray prev 0.11. Closing this now!

**Comment by fmaussion** [comment]
Actually I have to ask: why is it possible to to an operation on a closed dataset? What is happening under the hood which creates this error and wasn't earlier?

**Comment by shoyer** [comment]
My best guess is that `ds.thick.isel(x=('z', [1, 3, 4]), y=('z', [7, 2, 1]))` previously loaded data into memory (and cached it) but now operates lazily.

**Comment by fmaussion** [comment]
>  but now operates lazily.

If so, how does the dataset access the data if the file is closed? Shouldn't it raise an error instead?

**Comment by shoyer** [comment]
Previously the indexing operation would sometimes return a NumPy array. Now it's always lazy, so accessing the dataset when the file is closed fails.

Perhaps we should raise our own error though instead of just passing things through to netCDF4.

**Comment by dcherian** [comment]
"Perhaps we should raise our own error though instead of just passing things through to netCDF4"

This seems like a good idea
