### ISSUE TITLE
Xarray equivalent of np.place or df.map(mapping)?

### ISSUE THREAD

**Issue by ahuang11** [pydata/xarray#2568]
```python
# numpy version
x = np.array([0, 1])
np.place(x, x == 0, 1)

# pandas version
pd.Series([0, 1]).map({0: 1, 1: 1})

# current workaround
ds = xr.Dataset({'test': [0, 1]})
np.place(ds['test'].values, ds['test'].values == 0, 1)

```
#### Problem description

Is there a built in method to map values like 0 to 1?

#### Expected Output
returns `[1, 1]`

**Comment by ahuang11** [comment]
I guess I'm thinking about more complex cases such as changing 0 -> 50, 1 -> 29, 2 -> 10

```
ds = xr.Dataset({'test': [0, 1, 2]})
ds.where((ds != 1) & (ds != 2), 50)
```

Thoughts on simplifying this?

**Comment by shoyer** [comment]
I would divide this into two steps: (1) write a function that does this on NumPy arrays and (2) apply it to xarray using `apply_ufunc`, e.g.,

```python
import numpy as np
import xarray as xr

def remap(array, mapping):
    return np.array([mapping[k] for k in array.ravel()]).reshape(array.shape)

ds = xr.Dataset({'test': ('t', [0, 1, 2])})
xr.apply_ufunc(remap, ds, kwargs=dict(mapping={0: 50, 1: 29, 2: 10}))
```
outputs:
```
<xarray.Dataset>
Dimensions:  (t: 3)
Dimensions without coordinates: t
Data variables:
    test     (t) int64 50 29 10
```

**Comment by ahuang11** [comment]
Thanks for the quick replies! Is there interest in making this a built-in function? If so, I can help contribute a PR.

**Comment by shoyer** [comment]
I would lean slightly against adding a dedicated method for this (but could be convinced if others are interested). Usually we copy pandas or numpy APIs, but `DataFrame.map` is a not a great name -- `map` means too many other things (e.g., consider the buildin `map`).

It might make sense to copy the design of `numpy.select` instead: https://docs.scipy.org/doc/numpy/reference/generated/numpy.select.html

e.g., you could write something like `xarray.select([ds < 0, ds < 10], [5, 10], default=15)`

**Comment by max-sixty** [comment]
Agree that `map` is not a good name (and I find the pandas API difficult in this area - each time I'm looking up what relabel / rename / map / select / filter does)

How about `match` / `switch` / `case`?

We would definitely use this. I agree it'd probably be used less in xarray than in pandas; though I'm keen to expand the API, in a deliberate and careful way, to some of the traditional pandas use-cases (but a small vote among many)

**Comment by ewineteer** [comment]
Has any progress been made on adding a builtin function for this? Thanks.

**Comment by ahuang11** [comment]
No, not from me at least.

**Comment by ahuang11** [comment]
If I were to make a PR, where would this method reside? Would it be under dataset.py and dataarray.py? Also, would I simply call np.select inside the method, and if so, how would I add support for dask?

My minimal example atm:
```
import xarray as xr
import numpy as np
import hvplot.xarray

ds = xr.tutorial.open_dataset('air_temperature').isel(time=0)

ds['air_cats'] = (
    ('lat', 'lon'),
    np.select([ds['air'].values >= 273.15, ds['air'].values < 273.15], ['above freezing', 'below freezing'])
)
ds.hvplot('lon', 'lat', hover_cols=['air_cats'])
```
![image](https://user-images.githubusercontent.com/15331990/89741988-90890780-da5b-11ea-9a96-01fd923e2eec.png)

**Comment by dcherian** [comment]
There's a longer discussion in #6377 so let's close this.
