### ISSUE TITLE
np.clip() executes eagerly

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#2570]
#### Example:
```python
x = xr.DataArray(np.random.uniform(size=[100, 100])).chunk(10)
x
```
> <xarray.DataArray (dim_0: 100, dim_1: 100)>
> dask.array<shape=(100, 100), dtype=float64, chunksize=(10, 10)>
> Dimensions without coordinates: dim_0, dim_1
> 

```python
np.clip(x, 0, 0.5)
```
> <xarray.DataArray (dim_0: 100, dim_1: 100)>
> array([[0.264276, 0.32227 , 0.336396, ..., 0.110182, 0.28255 , 0.399041],
>        [0.5     , 0.030289, 0.5     , ..., 0.428923, 0.262249, 0.5     ],
>        [0.5     , 0.5     , 0.280971, ..., 0.427334, 0.026649, 0.5     ],
>        ...,
>        [0.5     , 0.5     , 0.294943, ..., 0.053143, 0.5     , 0.488239],
>        [0.5     , 0.341485, 0.5     , ..., 0.5     , 0.250441, 0.5     ],
>        [0.5     , 0.156285, 0.179123, ..., 0.5     , 0.076242, 0.319699]])
> Dimensions without coordinates: dim_0, dim_1

```python
x.clip(0, 0.5)
```
> <xarray.DataArray (dim_0: 100, dim_1: 100)>
> dask.array<shape=(100, 100), dtype=float64, chunksize=(10, 10)>
> Dimensions without coordinates: dim_0, dim_1

#### Problem description
Using np.clip() directly calculates the result, while xr.DataArray.clip() does not.

**Comment by shoyer** [comment]
I don't think we can fix this with the current version of NumPy, unfortunately -- `np.clip` isn't a NumPy ufunc, so it always executes eagerly.

NumPy 1.16 or 1.17 will include support for `__array_function__` (see http://www.numpy.org/neps/nep-0018-array-function-protocol.html), which will let us fix this.

**Comment by max-sixty** [comment]
In an effort to reduce the issue backlog, I'll close this, but please reopen if you disagree

**Comment by Hoeze** [comment]
@max-sixty IMHO this issue should be kept open:
1) it is still not fixed
2) it can be fixed with an upcoming version of NumPy

I'd rather add some TODO tag or similar to this issue

**Comment by max-sixty** [comment]
As discussed it #8508, we're not going to implement `__array_function__` for our types unfortunately. 

If there's some way of doing it in a more sustainable way than I could envisage — options at #8508, then we can, and we can re-open....
