### ISSUE TITLE
When is transpose not lazy?

### ISSUE THREAD

**Issue by djhoese** [pydata/xarray#2576]
#### Code Sample, a copy-pastable example if possible

```python
import xarray as xr
import dask.array as da 
from dask.diagnostics import ProgressBar
a = xr.DataArray(da.zeros((3, 5, 5), chunks=(1, 2, 2)), dims=('bands', 'y', 'x'))

with ProgressBar():
    b = a.transpose('y', 'x', 'bands')
# dask does not show a progress bar due to no computation

with ProgressBar():
    b = a.transpose('y', 'x', 'bands')
    b.compute()
# dask computes the array (since we told it to) and we see a progress bar

```

#### Question

The [documentation for transpose](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.transpose.html) says that it is not lazy. Is this only in certain situations? By not lazy does it mean that when the data is computed that the transpose task will require all data to be loaded at once (one large chunk) or does it mean that the transpose operation will immediately compute the transposed array? My test above does not seem to compute the data when `transpose` is called.

Or is the documentation just outdated?

**Comment by shoyer** [comment]
Transpose on arrays stored with dask is definitely always lazy. The docs are out of sync here -- I think this language predates the use of dask into xarray!

The language is referring to cases where you're loading data from disk with `open_dataset()` without using dask. Indexing is lazy in those cases, but not transpose.
