### ISSUE TITLE
Deprecated autoclose option

### ISSUE THREAD

**Issue by pwolfram** [pydata/xarray#2592]
In updated versions of xarray we are getting a deprecation error for `autoclose`, e.g., at https://github.com/MPAS-Dev/MPAS-Analysis/pull/501/.  

A look through the issues is not transparent as to this reason and this issue is to collect the high-level information on this change.  

Is there an alternative use that should be considered instead?

**Comment by jhamman** [comment]
@pwolfram - this option was deprecated in the last release following https://github.com/pydata/xarray/pull/2261. Xarray now uses a LRU cache to manage open file handles. This can be configured via a global option:  `xarray.set_options(file_cache_maxsize=...)`.

If I recall correctly, you were part of the early LRU cache conversations. 

release notes on the subject: http://xarray.pydata.org/en/stable/whats-new.html#breaking-changes

**Comment by pwolfram** [comment]
@jhamman, LRU is much better.  The api-change on our size is to replace `autoclose=True` with `file_cache_maxsize=A_REASONABLE_BIG_NUMBER`, correct?

**Comment by jhamman** [comment]
@pwolfram - Thats right. We currently default to a fairly small number (128):

https://github.com/pydata/xarray/blob/3ae93ac31ce122fc10b089f3b92b8c20e8b218c9/xarray/core/options.py#L18

**Comment by pwolfram** [comment]
Thanks @jhamman!  @xylar, I'm thinking `file_cache_maxsize=1200` would be a good default (100 years of monthly files) that could be modified via the config files we use.
