### ISSUE TITLE
When use groupby to convert monthly array into yearly array by mean (dim=time), does xr consider the weights of each month or just take average?

### ISSUE THREAD

**Issue by liyaojun** [pydata/xarray#2594]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here

</details>

**Comment by spencerkclark** [comment]
It just takes the average.

However if you have an array of weights, it is straightforward to use groupby to take a weighted mean:
```python
import numpy as np
import pandas as pd
import xarray as xr

times = pd.date_range('2001', periods=36, freq='MS')
da = xr.DataArray(range(36), [('time', times)])
weights = times.shift(1, 'MS') - times
weights = xr.DataArray(weights, [('time', times)]).astype('float')

annual_means = ((da * weights).groupby('time.year').sum('time') / 
                weights.groupby('time.year').sum('time'))
```

Note this assumes that your DataArray does not contain missing values.  If your array has missing values, you might want to use something like this:
```python
annual_means = ((da * weights).groupby('time.year').sum('time') / 
                weights.where(~np.isnan(da)).groupby('time.year').sum('time'))
```
