### ISSUE TITLE
Pad method

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2605]
It would be nice to have a generic `.pad()` method to xarray objects based on numpy.pad and dask.array.pad.

In particular,`pad` with `mode='wrap'` could solve several use-cases related to periodic boundary conditions: https://github.com/pydata/xarray/issues/1005 , https://github.com/pydata/xarray/issues/2007. For example, `ds.pad(longitude=(0, 1), mode='wrap')` to add an extra point with periodic boundary conditions along the `longitude` dimension.

It probably makes sense to linearly extrapolate coordinates along padded dimensions, as long as they are regularly spaced. This might use heuristics and/or a keyword argument.

I don't have a plans to work on this in the near term. It could be a good project of moderate complexity for a new contributor.

**Comment by mark-boer** [comment]
Has some1 started working on this? I thought I might give it a try ;-)

**Comment by jhamman** [comment]
@mark-boer - I don't think so. Give it a go!

**Comment by dcherian** [comment]
@mark-boer Note that we have a `Variable.pad_with_fill_value` method and some other padding code in `rolling` and `coarsen` that could be consolidated.

**Comment by mark-boer** [comment]
@dcherian Thx! I found the `Variable.pad_with_fill_value` already, but I will also have a look at rolling and coarsen.

I have some questions related to this issue, I hope this is the correct place to ask those:

Dask added the pad method in version 1.7.0 according to its documentation. What is the minimum version of Dask that should be supported, I found Dask=1.2 is the continuous integration requirements.

Also, how should I handle implementation differences between numpy and Dask? E.g. in the current version of Dask and numpy I'm using: `mode="mean"` converts an array of integers to floats in Dask, but in numpy it keeps it an array of integers.

**Comment by dcherian** [comment]
You can copy over `dask.array.pad` to `dask_array_compat.py` and do something like

``` python
if LooseVersion(dask_version) >= LooseVersion("1.7.0"):
    pad = dask.array.pad
else:
    # copied from dask.array
    def pad(...):
        ...
```

> mode="mean" converts an array of integers to floats in Dask, but in numpy it keeps it an array of integers.

That's weird. Open an issue at the dask repo with an example?

Feel free to open an in-progress PR. Thanks for working on this.

**Comment by dcherian** [comment]
Also see #3587

**Comment by mark-boer** [comment]
I will create a WIP pull request tommorow.

**Comment by lanougue** [comment]
Hi,
I was looking to some xarray padding function and get this issue.
For the moment, I made a function of my own based on numpy.pad and xr.apply_ufunc
When possible, it also pad associated coordinates. If it can be of any help here...
Here it is:
```
def xpad(ds, dims={}):
    """
    Padding of xarray. Coordinate are linearly padded if original coordinates are evenly spaced. Otherwise, no new coordinates are affected to padded axis.
    Padded dimension is named with prefix 'padded_'
    
    Args:
        ds (xarray): xarray
        dims (dict): keys are dimensions along which to pad and values are padding tuple (see np.pad). (ex {'pulse:(10,0)})
        
    Returns:
        (xarray) : same as input with padded axis. 
    """
    mypad = [(0,0) for n in ds.dims if n not in dims.keys()]
    mypad+=list(dims.values())
    padded_ds = xr.apply_ufunc(np.pad, ds, mypad,input_core_dims=[list(dims.keys()),[]], output_core_dims=[['padded_'+d for d in dims.keys()]], keep_attrs=True)
    
    for var, ext in dims.items():
        dvar = np.diff(ds[var])
        if np.allclose(dvar, dvar[0]):
            dvar = dvar[0]
            left_bound, right_bound  = (np.min(ds[var]).data, np.max(ds[var]).data) if dvar>0. else (np.max(ds[var]).data, np.min(ds[var]).data)
            extended_var = np.append(ds[var].data, np.max(ds[var]).data+np.arange(1,ext[1]+1)*dvar)
            extended_var = np.append(np.min(ds[var]).data+np.arange(-ext[0],0)*dvar, extended_var)
            padded_ds = padded_ds.assign_coords(**{'padded_'+var:extended_var})
        else:
            print('Coordinates {} are not evenly spaced, padding is impossible'.format(var))
    return padded_ds
```

**Comment by lanougue** [comment]
Ho, sorry... I just see the PR...
