### ISSUE TITLE
DataArray concat with tolerance

### ISSUE THREAD

**Issue by davidbrochart** [pydata/xarray#2644]
I would like to concatenate many `DataArray` whose dimension coordinates are almost aligned, allowing for some offset in the coordinates:

```python
import xarray as xr
da1 = xr.DataArray([[0, 1], [2, 3]], coords=[[0, 1], [0, 1]], dims=['x', 'y'])
da2 = xr.DataArray([[4, 5], [6, 7]], coords=[[1.1, 2.1], [1.1, 2.1]], dims=['x', 'y'])
da = xr.concat([da1, da2], 'z', method='nearest', tolerance=0.2) # doesn't exist yet
da
```
 
And I would get:

```
<xarray.DataArray (z: 2, x: 3, y: 3)>
array([[[ 0.,  1., nan],
        [ 2.,  3., nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan,  4.,  5.],
        [nan,  6.,  7.]]])
Coordinates:
  * x        (x) float64 0 1 2.1
  * y        (y) float64 0 1 2.1
Dimensions without coordinates: z
```

@jhamman suggested to use `reindex_like` in this [StackOverflow question](https://stackoverflow.com/questions/54007495/concatenating-dataarray-with-tolerance-in-xarray/54010432#54010432), but it doesn't produce the union of coordinates, so I cannot chain them like this:

```python
da2 = da2.reindex_like(da1, method='nearest', tolerance=0.2)
```

Is there another work around? Do you think it would be worth having this feature in `concat`?

**Comment by shoyer** [comment]
This feature would certainly be welcome in some form.

`xarray.concat` uses `xarray.align` internally for alignment, which in term relies upon methods like `pandas.Index.union` to determine result coordinates. So to make this work well, we basically need some form of "approximate unions".

We've been discussing exactly this over in https://github.com/pydata/xarray/issues/2217. I would encourage you to take a look!

**Comment by davidbrochart** [comment]
Thanks @shoyer. Unfortunately PR https://github.com/pandas-dev/pandas/pull/22043 has been put on hold.

**Comment by dcherian** [comment]
Closing in favour of #2217
