### ISSUE TITLE
getting this error when using from_dataframe: cannot handle a non-unique multi-index

### ISSUE THREAD

**Issue by cliffrunner** [pydata/xarray#2646]
I am trying to convert a dataframe to an xarray. The functions I am using are df.to_xarray() and xr.DataSet.from_dataframe()

But I am getting `Exception: cannot handle a non-unique multi-index` for both cases.

here is the first couple rows of my dataframe. It is an multi-index dataframe. 
![image](https://user-images.githubusercontent.com/41877666/50656526-217f2f00-0f59-11e9-8dde-0f0730dd991e.png)

Thank you very much.

**Comment by shoyer** [comment]
I answered this on stackoverflow: https://stackoverflow.com/questions/54028365/what-does-this-mean-xarray-error-cannot-handle-a-non-unique-multi-index/54028628#54028628
