### ISSUE TITLE
DataArray computations should handle missing values correctly

### ISSUE THREAD

**Issue by andreas-h** [pydata/xarray#265]
Maybe I'm just missing something ... but shouldn't

```
xray.DataArray(np.asarray([1., np.nan]), coords=[[1, 2]], dims=["X"]).mean()
```

return `1` instead of `nan`?  Or how is calculations with missing values supposed to work?

I'm running xray 0.3.0.

**Comment by shoyer** [comment]
Note: this is fixed in the newly released v0.4.
