### ISSUE TITLE
Implement quarterly frequencies for cftime 

### ISSUE THREAD

**Issue by tlogan2000** [pydata/xarray#2663]
Currently cftime offsets have no options for quarterly frequencies (QS-DEC ... etc) as in xarray/pandas 
see : http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases

@jwenfai has recently worked extensively to implement xarray/cftime resampling (https://github.com/pydata/xarray/pull/2593)  but this will remain limited as quarterly frequencies are currently not supported under xarray/coding/cftime_offsets.py

**Comment by spencerkclark** [comment]
Yes, these would be a welcome addition 👍.
