### ISSUE TITLE
Xarray fails to build with bottleneck on Travis CI

### ISSUE THREAD

**Issue by Zeitsperre** [pydata/xarray#2664]
I'm currently having trouble building a project built on xarray (https://github.com/Ouranosinc/xclim/pull/139). Problems seem to have arose during the holidays as even our previously stable master branch is now failing.

We believe the issue is due to incompatibilities with bottleneck and/or numpy which seem to pop up every now and then. **The build seems to only fail when run via Travis CI**. Running tests via `tox` locally does not raise errors. Fixes from other issues similar to this haven't been successful (such as #1294). I've attempted the following: 
- manually upgrading pip before install
- adjusting the base versions of xarray, bottleneck and numpy prior to installation
- reinstalling bottleneck after xarray is installed

```python
tests/test_checks.py:4: in <module>
    import xarray as xr
.tox/py36/lib/python3.6/site-packages/xarray/__init__.py:14: in <module>
    from .core.extensions import (register_dataarray_accessor,
.tox/py36/lib/python3.6/site-packages/xarray/core/extensions.py:6: in <module>
    from .dataarray import DataArray
.tox/py36/lib/python3.6/site-packages/xarray/core/dataarray.py:9: in <module>
    from . import computation, groupby, indexing, ops, resample, rolling, utils
.tox/py36/lib/python3.6/site-packages/xarray/core/rolling.py:457: in <module>
    inject_bottleneck_rolling_methods(DataArrayRolling)
.tox/py36/lib/python3.6/site-packages/xarray/core/ops.py:357: in inject_bottleneck_rolling_methods
    f = getattr(bn, bn_name)
E   AttributeError: module 'bottleneck' has no attribute 'move_sum'
------------------------------- Captured stderr --------------------------------
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

```

I believe this could be a bug in either xarray or in Travis CI. Help appreciated. :)

**Comment by shoyer** [comment]
can you share how you install things on Travis?

**Comment by Zeitsperre** [comment]
That certainly is the error. The workaround identified for it is good enough for now. Thanks!
