### ISSUE TITLE
install documentation and test framework slightly inconsistent

### ISSUE THREAD

**Issue by bnlawrence** [pydata/xarray#2679]
#### Problem description

I am following the install instructions here: http://xarray.pydata.org/en/stable/installing.html

If I do the base conda install, followed by the unit tests `(using pytest, not py.test) then by default not all the dependencies _for the tests_ are installed. In particular, `scipy` and `matplotlib` lead to test failures. 

I appreciate these are listed as optional dependencies, but I think it'd be better then if the tests were split into core and optional. If I was coming to this as a naive user (i'm not) , I might find it peculiar that the test framework fails (maybe if I was that naive I wouldn't be running the tests).

Anyway, an observation to do with what you want. Clearly low priority.

**Comment by max-sixty** [comment]
Thanks for the issue @bnlawrence 

That's not good - do you have a snippet of the tests that fail? The intent is to skip tests which don't have the dependencies, but sounds like something isn't skipped

**Comment by keewis** [comment]
using
```sh
conda create -n xarray-2679 python=3.8 pytest xarray
conda activate xarray-2679
python -m pytest
```
I can't reproduce this. Maybe we fixed this when we introduced the `py36-bare-minimum` CI?

Feel free to reopen or open a new issue if you disagree.
