### ISSUE TITLE
Close stale issues?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#2681]
As discussed with @jhamman , I've been attempting to manually close / follow up on stale issues & PRs, given we had 500+ issues

Any thoughts on doing this automatically with https://github.com/probot/stale? 

This could ask for an affirmation after an issue has been uncommented for a year, and then close a month later if there's no response

**Comment by shoyer** [comment]
Thanks for taking the lead here! I'd be happy to give the bot a try.
