### ISSUE TITLE
Travis failing on segfault at print_versions

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#2683]
master is breaking on both the docs and python3.6 `print_versions`: https://travis-ci.org/pydata/xarray/jobs/479834129

```
/home/travis/.travis/job_stages: line 104:  3514 Segmentation fault      (core dumped) python xarray/util/print_versions.py
The command "python xarray/util/print_versions.py" failed and exited with 139 during .
```

Has anyone seen this before? I can't replicate locally, but I likely don't have the same dependencies

**Comment by jhamman** [comment]
This is unfortunate and indeed tricky to diagnose. My guess is there is a spurious bad build somewhere in anaconda land causing this error. Let's wait a day or so to see if things resolve on their own, if now, there are other options for figuring out the offending library.

**Comment by benbovy** [comment]
xref: https://github.com/conda-forge/rasterio-feedstock/issues/98

**Comment by max-sixty** [comment]
Does nyone have an idea whether this will be resolved in a couple of days? Otherwise I can try and put a temporary fix in (there's one described in that issue, but I don't have experience with conda so can't assess whether it's likely to be successful)
