### ISSUE TITLE
Implementation of CRS storage in rasterio with PROJ.4 & WKT

### ISSUE THREAD

**Issue by snowman2** [pydata/xarray#2723]
Continuation of the discussion from #2722 to move onto implementation details.

**Comment by snowman2** [comment]
Tag: @fmaussion @djhoese

**Comment by fmaussion** [comment]
Sorry for being late on this one. Yes, I agree that the "coordinate attribute" is worth a try.

To avoid redundancy in the name one could name the coord variable attributes simply `wkt` and `proj4`, like:

```
<xarray.DataArray 'crs' ()>
array(0)
Coordinates:
    crs          int64 0
Attributes:
    wkt:  PROJCS["UTM Zone 15, Northern Hemisphere",GEOGCS["WGS 84",D...
    proj4: +proj=...
```

**Comment by snowman2** [comment]
@fmaussion just a ping for what are your thoughts are for next steps on this?

**Comment by snowman2** [comment]
Going to close this as it is over a year old.

For reference, WKT support is in `rioxarray`.
https://corteva.github.io/rioxarray/stable/examples/crs_management.html

**Comment by dcherian** [comment]
@snowman2 @djhoese It'd be nice to update our docs to link to rioxarray and other relevant packages. (e.g. here https://xarray.pydata.org/en/stable/io.html#rasterio).

Adding an example on doing these manipulations would also be very welcome.

**Comment by snowman2** [comment]
> Adding an example on doing these manipulations would also be very welcome.

What types of manipulations are you thinking about? Reprojection? Export to geotiff? Clip? Reading in files?

**Comment by fmaussion** [comment]
I think we should seriously consider removing all rasterio logic in xarray and make rioxarray an optional dependency to read geotiff files with xarray.

**Comment by dcherian** [comment]
@snowman2 Any/all of those "common operations" sounds good. We don't have a single geoTIFF example: https://xarray.pydata.org/en/stable/examples.html so at this point anything would be a big improvement

> I think we should seriously consider removing all rasterio logic in xarray and make rioxarray an optional dependency to read geotiff files with xarray.

:+1: Though maybe we should wait till the backends refactor is done so that things are a little more easy.

**Comment by snowman2** [comment]
@dcherian Maybe a link to these examples in that section then?
https://corteva.github.io/rioxarray/stable/examples/examples.html
