### ISSUE TITLE
Line plot with x=coord putting wrong variables on axes

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#2725]
When I try to plot the values in a 1D DataArray against the values in one of its coordinates, it does not behave at all as expected: 

```python
import numpy as np
import matplotlib.pyplot as plt
from xarray import DataArray

current = DataArray(name='current', data=np.array([5, 8, 14, 22, 30]), dims=['time'],
                    coords={'time': (['time'], np.array([0.1, 0.2, 0.3, 0.4, 0.5])),
                            'voltage': (['time'], np.array([100, 200, 300, 400, 500]))})

print(current)

# Try to plot current against voltage
current.plot.line(x='voltage')
plt.show()
```
Output:

```
<xarray.DataArray 'current' (time: 5)>
array([ 5,  8, 14, 22, 30])
Coordinates:
  * time     (time) float64 0.1 0.2 0.3 0.4 0.5
    voltage  (time) int64 100 200 300 400 500
```
![incorrect_current_plot](https://user-images.githubusercontent.com/35968931/51924149-683f3800-23e4-11e9-8957-81d32da43117.png)

#### Problem description

Not only is `'voltage'` not on the x axis, but `'current'` isn't on the y axis either!

#### Expected Output

Based on the documentation (and common sense) I would have expected it to plot voltage on the x axis and current on the y axis.

(using a branch of xarray which is up-to-date with master)

**Comment by TomNicholas** [comment]
@dcherian I'm assuming this is an issue somewhere in #1926?

**Comment by dcherian** [comment]
Thanks @TomNicholas. Here's the diff that gets it working (minus error-checking & tests). I can't get to it until tonight so if you have the time to go ahead and send in a PR, please do so.


![image](https://user-images.githubusercontent.com/2448579/51927707-09100200-23a9-11e9-882d-573307ea5203.png)

**Comment by TomNicholas** [comment]
Done @dcherian , including tests, in #2726 .
