### ISSUE TITLE
Unable to construct indexVariable.

### ISSUE THREAD

**Issue by ahmedshaaban1** [pydata/xarray#2733]
Hi, 
I am trying to reproduce the index-variable with the same data, dims, attributes, yet I got the following 
error message

```python-traceback
Traceback (most recent call last):

  File "<ipython-input-180-c993b3a40ff6>", line 4, in <module>
    latPP=xr.IndexVariable(latP.data,latP.dims,latP.attrs)

  File "/linuxapps/anaconda/lib/python2.7/site-packages/xarray/core/variable.py", line 1618, in __init__
    fastpath)

  File "/linuxapps/anaconda/lib/python2.7/site-packages/xarray/core/variable.py", line 263, in __init__
    self._dims = self._parse_dimensions(dims)

  File "/linuxapps/anaconda/lib/python2.7/site-packages/xarray/core/variable.py", line 424, in _parse_dimensions
    % (dims, self.ndim))

ValueError: dimensions (90.0, 87.5, 85.0, 82.5, 80.0, 77.5, 75.0, 72.5, 70.0, 67.5, 65.0, 62.5, 60.0, 57.5, 55.0, 52.5, 50.0, 47.5, 45.0, 42.5, 40.0, 37.5, 35.0, 32.5, 30.0, 27.5, 25.0, 22.5, 20.0, 17.5, 15.0, 12.5, 10.0, 7.5, 5.0, 2.5, 0.0, -2.5, -5.0, -7.5, -10.0, -12.5, -15.0, -17.5, -20.0, -22.5, -25.0, -27.5, -30.0, -32.5, -35.0, -37.5, -40.0, -42.5, -45.0, -47.5, -50.0, -52.5, -55.0, -57.5, -60.0, -62.5, -65.0, -67.5, -70.0, -72.5, -75.0, -77.5, -80.0, -82.5, -85.0, -87.5, -90.0) must have the same length as the number of data dimensions, ndim=0
```

The file is on Box drive. 
https://app.box.com/s/vc8m9c9blue3svbm9v7fy0xg1rkthut0
```
tmp_file = xr.open_dataset('olr.day.mean.nc')
latP  = tmp_file.variables['lat']
latPP=xr.IndexVariable(latP.data,latP.dims,latP.attrs)
```

#### Output of ``xr.show_versions()``

<details>
xarray: 0.10.7
pandas: 0.23.1
numpy: 1.14.5
scipy: 1.1.0
netCDF4: 1.4.0
</details>

**Comment by shoyer** [comment]
Hi @ahmedshaaban1 -- the short answer is you mixed up the order of the constructor arguments. This should be `xr.IndexVariable(latP.dims,latP.data,latP.attrs)`

Note that normally you shouldn't need to create `IndexVariable` objects directly -- they are public API, but rather low level. Usually I recommend sticking to Dataset/DataArray objects:
http://xarray.pydata.org/en/stable/internals.html#variable-objects

**Comment by ahmedshaaban1** [comment]
Thanks a lot @shoyer . It works. Regarding to the `IndexVariable` object, I found that the latP in the file that I am opening is a `IndexVariable` object, so I just did the same when I thought to write it.  
Thanks

**Comment by shoyer** [comment]
Generally you'll want to access variables in a Dataset directly as DataArray objects, e.g., `tmp_file['lat']`. `.variables` is the low level API.
