### ISSUE TITLE
1000x performance regression in transpose from disk between libnetcdf 4.6.1 and 4.6.2

### ISSUE THREAD

**Issue by coroa** [pydata/xarray#2747]
Having generated `test.nc` as the two-dimensional array from
```python
import numpy as np
import xarray as xr

a = np.random.random((1000, 100))
ds = xr.Dataset({'foo': xr.DataArray(a, [('x', np.arange(1000)), ('y', np.arange(100))])})
ds.to_netcdf('test.nc')
```

I am seeing a huge performance regression from libnetcdf=4.6.1
```python
In [2]: ds = xr.open_dataset('test.nc') 
   ...: %time np.asarray(ds['foo'].transpose('y', 'x')) 
   ...:                                                                                                                
CPU times: user 2.58 ms, sys: 191 µs, total: 2.77 ms
```
in a conda environment created by
```
conda create -n mwe-fast 'libnetcdf=4.6.1' netcdf4 xarray ipython
```
to the environment created by 
```
conda create -n mwe-slow 'libnetcdf=4.6.2' netcdf4 xarray ipython
```
```python
In [5]: ds = xr.open_dataset('test.nc') 
   ...: %time np.asarray(ds['foo'].transpose('y', 'x')) 
   ...:                                                                                                                
CPU times: user 4.09 s, sys: 12 ms, total: 4.11 s
```

Loading into memory mitigates the regression (on `mwe-slow`):
```python
In [2]: ds = xr.open_dataset('test.nc') 
   ...: %time np.asarray(ds['foo'].load().transpose('y', 'x')) 
   ...:                                                                                                                
CPU times: user 1.12 ms, sys: 80 µs, total: 1.2 ms
```

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS on the working environment `mwe-fast`
------------------

commit: None
python: 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:33:04) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.19.0-2-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8
libhdf5: 1.10.3
libnetcdf: 4.6.1

xarray: 0.11.3
pandas: 0.24.1
numpy: 1.15.4
scipy: None
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
setuptools: 40.7.3
pip: 19.0.1
conda: None
pytest: None
IPython: 7.2.0
sphinx: None

INSTALLED VERSIONS  on the broken environment `mwe-slow`
------------------
commit: None
python: 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:33:04) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.19.0-2-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.11.3
pandas: 0.24.1
numpy: 1.15.4
scipy: None
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
setuptools: 40.7.3
pip: 19.0.1
conda: None
pytest: None
IPython: 7.2.0
sphinx: None

</details>

**Comment by mathause** [comment]
Is this fixed upstream?

**Comment by shoyer** [comment]
Yes, it looks like this was fixed in https://github.com/Unidata/netcdf4-python/pull/872.
