### ISSUE TITLE
document defaults for optional arguments to open_dataset, open_mfdataset

### ISSUE THREAD

**Issue by klindsay28** [pydata/xarray#2752]
It would be useful if the docs for [`open_dataset`](https://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html#xarray.open_dataset) and [`open_mfdataset`](https://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html#xarray.open_mfdataset) listed the default values of optional arguments (where there is a default).

For example, the docs for [`open_dataset`](https://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html#xarray.open_dataset) do not list the defaults for `decode_times` and `decode_coords`, and the docs for [`open_mfdataset`](https://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html#xarray.open_mfdataset) do not list the defaults for `data_vars` and `coords`.

**Comment by jhamman** [comment]
@klindsay28 - thanks for opening an issue. We're always trying to improve our documentation. However, When I look at the docs for these two functions, I see the defaults for `decode_coords=True`,  `decode_times=True`, `data_vars='all'`, and `coords='different'`.

**Comment by dcherian** [comment]
@klindsay28 The top line shows the function signature which has the defaults listed. 

`xarray.open_dataset(filename_or_obj, group=None, decode_cf=True, mask_and_scale=None, decode_times=True, autoclose=None, concat_characters=True, decode_coords=True, engine=None, chunks=None, lock=None, cache=None, drop_variables=None, backend_kwargs=None)`

I agree that this is confusing.

**Comment by klindsay28** [comment]
Thanks for the quick responses @jhamman and @dcherian. I had focused on the descriptive text below the function signature, which mentions defaults for some, but not all arguments. I now realize that I need to also examine the function signature in the docs. Sorry for the noise.

**Comment by jhamman** [comment]
@klindsay28, if you're up for it, we'd be happy to accept some changes to these docstrings to improve consistency between the signature and doc string.

**Comment by shoyer** [comment]
One thing I'll mention is that we often try *not* to specify defaults in both docstrings and function signatures, because this can lead to the defaults getting out of sync. This leads to only putting defaults in the function signature itself, because that part is tested by the code.
