### ISSUE TITLE
docs clarity for notnull() etc

### ISSUE THREAD

**Issue by benjimin** [pydata/xarray#2760]
Some problems with the documentation for `xarray.DataArray.notnull`:

1. The current stable ([v0.11.3](http://xarray.pydata.org/en/v0.11.3/generated/xarray.DataArray.notnull.html)) docs appear broken and provide no prose explanation of the function, input parameters, or return value.
2. The previous ([v0.9.6](http://xarray.pydata.org/en/v0.9.6/generated/xarray.DataArray.notnull.html)) docs describe the function as a _replacement for numpy.isfinite / -numpy.isnan_. Which is it? (`isfinite` and `isnan` are not equivalent in `numpy`; and from the code I suspect it may invoke `pandas.notnull` instead.)
3. The docs unhelpfully give the signature as `DataArray.notnull(*args, **kwargs)`, but I think this function is actually an instance method that takes no positional nor keyword arguments.

It seems like the function is monkey-patched (duck-punched?) onto the class rather than explicitly defined anywhere, so it isn't immediately obvious to me where to best clarify this documentation.

**Comment by shoyer** [comment]
`notnull()` is definitely a wrapper for `pandas.notnull()`.

Yes, the monkey-patching in `xarray.core.ops` (and the lack of a docstring) is unfortunate. It would be nice to replace that with a normal method definition, so it's more obvious what's going on and we can fix these docs.

**Comment by shoyer** [comment]
To clarify, I think the old docstring was copied from pandas. `notnull(x)` is basically equivalent to `np.isfinite(x) & ~np.isnan(x)`.
