### ISSUE TITLE
PyPi (v11.3) build behind master branch. cftime resampling not working

### ISSUE THREAD

**Issue by tlogan2000** [pydata/xarray#2762]
A pypi  xarray install (v 11.3) gives an error when resampling ncfiles with cftime calendars 
An install from github/master however works fine.

11.3 release notes seem to indicate that it should include the cftime resampling PR

**Comment by dcherian** [comment]
> 11.3 release notes seem to indicate that it should include the cftime resampling PR

I don't see this at http://xarray.pydata.org/en/stable/whats-new.html. You must be looking at the latest version (http://xarray.pydata.org/en/latest/whats-new.html)

You'll have to wait for 0.12.0 (which should be soon) or install from master as you have.

**Comment by tlogan2000** [comment]
ok thanks, sorry for the confusion I was looking directly at commits for release 11.3 on github
https://github.com/pydata/xarray/releases

**Comment by dcherian** [comment]
No problem, thanks for checking! :+1:
