### ISSUE TITLE
Upgrade xarray version on Cheyenne

### ISSUE THREAD

**Issue by edougherty32** [pydata/xarray#2764]
Hi all, 

This is probably fairly simple but I can find an answer anywhere: how do I upgrade my version of xarray that I use on the Cheyenne supercomputer? I currenlty am using v0.10.9 and would like to upgrade to the latest version (v0.11.3). 

Thanks.

**Comment by max-sixty** [comment]
Hi @edougherty32, thanks for the question

This might be a question for the Cheyenne team more than xarray. If you're on a traditional setup, you can use `pip install -U xarray` to upgrade, or the equivalent `conda` if you're using that

**Comment by edougherty32** [comment]
Thanks @max-sixty. 

 I tried `pip install -U xarray==0.11.3`, but I receive the following messages:

`Collecting xarray==0.11.3`

And the error message:
`Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x2aaab1f67c88>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/xarray/`

```
 Could not find a version that satisfies the requirement xarray==0.11.3 (from versions: )
No matching distribution found for xarray==0.11.3
```

**Comment by rabernat** [comment]
You would need to run that command from the login node. The compute nodes
don't have access to the network, so they can't download.

**Comment by edougherty32** [comment]
Thanks @rabernat . That did the trick!
