### ISSUE TITLE
Exporting xarray dataset to netcdf results in all nans

### ISSUE THREAD

**Issue by edougherty32** [pydata/xarray#2765]
Hi all, 

I am trying to export an xarray dataset to a netcdf file. The dataset looks like this:

```
<xarray.Dataset>
Dimensions:  (south_north: 1015, west_east: 1359)
Coordinates:
    XLAT     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    XLONG    (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
Dimensions without coordinates: south_north, west_east
Data variables:
    var0     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    var1     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    var2     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    var3     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    var4     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    var5     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    var6     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    var7     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
    var8     (south_north, west_east) float32 dask.array<shape=(1015, 1359), chunksize=(1015, 1359)>
```

Where each variable represents a different flood event at a specific time and location. 

I export the dataset in the following manner:'
`concat_floods_all.to_netcdf(path='/glade/work/doughert/flooddata/St4_sflood_hybrid_ep_accum_CTRL.nc', mode='w', format='NETCDF4', compute=False)`

The netcdf file is able to export fine, but when I read in the file:
`grid_accum = xr.open_dataset('/glade/work/doughert/flooddata/St4_sflood_hybrid_ep_accum_CTRL.nc' )`

All the variables and coordinates are nans, despite this not being the case before exporting as a netcdf. 

For example, for var0, prior to exporting, its maximum value is
`np.nanmax(concat_floods_all['var0'].values)`
`59.98288`

But after exporting, all the values are nans and I am returned a maximum value of nan for var0:
```
print(np.nanmax(grid_accum['var0'].values))
nan
/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: All-NaN slice encountered
  """Entry point for launching an IPython kernel.

```

Does anyone have an idea how to fix all the values for both the variables and coordinates being turned to nans upon exporting to a netcdf file?

**Comment by dcherian** [comment]
I don't have much experience with dask stuff, but how about setting `compute=True` in your `to_netcdf()` stuff.

**Comment by edougherty32** [comment]
Thanks, @dcherian . 
However, I have 523 variables, each 1015x1359 grid cells, so it would take up too much memory to set `compute=True`.

**Comment by edougherty32** [comment]
I figured out the problem–I had to convert dask arrays in my dataset to numpy arrays using:

`concat_floods_all_ar = concat_floods_all.load()`

Before exporting to the netcdf file.
