### ISSUE TITLE
Should xarray allow assigning a masked constant?

### ISSUE THREAD

**Issue by gerritholl** [pydata/xarray#2772]
Currently, `ds['a'] = ((), ma.masked)` where `ds` is an `xarray.Dataset` gives `ValueError: Could not convert tuple of form (dims, data[, attrs, encoding]): ((), masked) to Variable.`, whereas `ds['a'] = (), ma.MaskedArray(0.0, True)` works (it sets the indicated value to NaN).  Should assigning `ma.masked` be equivalent to assigning `ma.MaskedArray(0.0, True)`, or are there good reasons for the difference in behaviour?

**Comment by shoyer** [comment]
One possible issue is that we don't know the dtype for `ma.masked`. This means we don't know *which* sentinel missing value to replace it with.

Consider this in the context of our current logic for dealing with masked arrays:
https://github.com/pydata/xarray/blob/17fa64f5314aa898f262a73fdc00d228ec380968/xarray/core/variable.py#L171-L178

**Comment by max-sixty** [comment]
Closing as stale but please reopen if sufficiently pressing.
