### ISSUE TITLE
Applying the stack function to DataArray resulted in data type changes on coordinates

### ISSUE THREAD

**Issue by grassland-curing-cfa** [pydata/xarray#2774]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# My source xarray.DataArray `da` is:

<xarray.DataArray (time: 744, latitude: 106, longitude: 193)>
dask.array<shape=(744, 106, 193), dtype=float64, chunksize=(2, 106, 193)>
Coordinates:
  * latitude   (latitude) float32 -39.2 -39.149525 ... -33.950478 -33.9
  * longitude  (longitude) float32 140.8 140.84792 140.89584 ... 149.95209 150.0
  * time       (time) datetime64[ns] 2017-01-01 ... 2017-01-31T23:00:00

I applied stack() to it:

`da_stacked = da.stack(z=['time', 'latitude', 'longitude'])`

```
#### Problem description

This resulted in latitude and longitude changed from float32 to float64 and their data precision lost.

Now the da_stacked becomes:

<xarray.DataArray (z: 15220752)>
dask.array<shape=(15220752,), dtype=float64, chunksize=(40916,)>
Coordinates:
  * z          (z) MultiIndex
  - time       (z) datetime64[ns] 2017-01-01 2017-01-01 ... 2017-01-01
  - latitude   (z) float64 -39.2 -39.2 -39.2 -39.2 ... -39.2 -39.2 -39.2 -39.2
  - longitude  (z) float64 140.8 140.8 140.9 140.9 ... 142.0 142.1 142.1 142.2

How can I keep the coordinates as same as the source DataArray object while applying the stack function?

**Comment by fujiisoup** [comment]
We are using pandas MultiIndex under the hood and pandas does not have `Float32Index` but only 'Float64Index'. The lower precision float arrays are always cast to float64.

I think it would be probably difficult to add float32 support for the MultiIndex anytime soon...

**Comment by shoyer** [comment]
That said, xarray could keep around a float32 array along with the float64 index. This is likely to be possible soon as part of the “explicit indexes” refactor (https://github.com/pydata/xarray/issues/1603).

**Comment by max-sixty** [comment]
Closing as stale but please reopen if sufficiently pressing.
