### ISSUE TITLE
Improved inference of names when concatenating arrays

### ISSUE THREAD

**Issue by Zac-HD** [pydata/xarray#2775]
#### Problem description

Using the name of the first element to concatenate as the name of the concatenated array is only correct if all names are identical.  When names vary, using a clear placeholder name or the name of the new dimension would avoid misleading data users.

This came up for me recently when stacking several bands of a satellite image to produce a faceted plot - the resulting colorbar was labelled "blue", even though that was clearly incorrect.

A similar process is probably also desirable for aggregation of units across concatenated arrays - use first if identical, otherwise discard or error depending on the `compat` argument.

#### Code Sample, a copy-pastable example if possible

```python
ds = xr.Dataset({
    k: xr.DataArray(np.random.random((2, 2)), dims="x y".split(), name=k) 
    for k in "blue green red".split()
})
# arr.name == "blue", could be "band" or "concat_dim"
arr = xr.concat([ds.blue, ds.green, ds.red], dim="band")
# label of colorbar is "blue", which is meaningless
arr.plot.imshow(col="band")
```

![image](https://user-images.githubusercontent.com/12229877/52989142-3276f780-3456-11e9-940a-dd97778736cb.png)

One implementation that would certainly be nice for this use-case (though perhaps not generally) is that concatenating `DataArray`s along an entirely new dimension with unique array names and `dim` passed a string could create a new Index as well, as `pd.Index([a.name for a in objs], name=dim)`.

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
libhdf5: 1.10.3
libnetcdf: 4.4.1.1

xarray: 0.11.2
pandas: 0.23.1
numpy: 1.14.5
scipy: 1.2.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: 3.0.2
cartopy: None
seaborn: 0.9.0
setuptools: 40.6.2
pip: 10.0.1
conda: None
pytest: 4.2.0
IPython: 6.4.0
sphinx: 1.8.0

</details>

I'd be happy to write a PR for this if it would be accepted.

**Comment by shoyer** [comment]
Indeed, this seems broken to me. I think we should use the same heuristic we use for naming the result of operations with `apply_ufunc`:
https://github.com/pydata/xarray/blob/cd8e370e63f82deeaf4fc190f5c1d90463067368/xarray/core/computation.py#L119-L128
