### ISSUE TITLE
groupby with non-scalar coordinate

### ISSUE THREAD

**Issue by kefirbandi** [pydata/xarray#2786]
#### Code Sample

```python
import numpy as np
import xarray as xr

def noop(da):
    return da

def expd(da):
    return da.expand_dims(['A'])

na=np.array([[1,2],[3,4]])
xa=xr.DataArray(na,dims=['A','B'])

# This works:
r1 = xa.groupby('A').apply(noop)
print("!!!!")

# This doesn't:
r2 = xa.groupby('A').apply(expd)
```
#### Problem description

Is this intended behavior? The reason I would need this is to be able to increase the size of each group.

#### Expected Output

I expect r1 to be equivalent to r2

**Comment by dcherian** [comment]
This is broken because you're expanding along the grouped dimension `A`.

Changing it to `expand_dims(['C'])` works
```
<xarray.DataArray (A: 2, B: 2, C: 1)>
array([[[1],
        [2]],

       [[3],
        [4]]])
Dimensions without coordinates: A, B, C
```

If you want to preserve the dimension `A` with length 1 in each group use 
```
r2 = xa.groupby('A', squeeze=False)
```

I don't know that we should do anything here?
