### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Khalilsqu** [pydata/xarray#2794]
Can I assing multiple names to the same dimension? say I have 2 dimensional data and I want for example dim_0 to have multiple names a, b, c, d, etc., each with differecnt coordinates while dim_1 only have one name. or can I use multiindexing along one dimension?

Thanks in advance.

**Comment by max-sixty** [comment]
Great to see you solved it. 

StackOverflow is a good resource for these and some of the developers are fairly active there
