### ISSUE TITLE
Stalebot is being overly aggressive

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2797]
E.g., see https://github.com/pydata/xarray/issues/1151 where stalebot closed an issue even after another comment.

Is this something we need to reconfigure or just a bug?

cc @pydata/xarray

**Comment by max-sixty** [comment]
I'll look into it now

**Comment by max-sixty** [comment]
It looks like it's a (seemingly uncommon) bug. 
Given the bug, someone needs to remove the label, rather than only comment on the issue

In the meantime, we can:
- Do nothing
- Change the message to request removing the label
- Disable the bot until this is resolved

Thoughts?

**Comment by max-sixty** [comment]
While we're here - any other feedback / suggested config changes? 

We're down from ~530 to ~400 issues, and inspired a couple PRs along the way. There is some cost in swatting the marked issues though. 
We were planning to move the time-to-stale to one year, from two.

**Comment by max-sixty** [comment]
I haven't seen this reoccur. Limited sample (though a handful of true negatives)

**Comment by shoyer** [comment]
Thank you, slate-bot! I think we can let this one expire now 🤣

**Comment by max-sixty** [comment]
lol. I just re-logged-in a couple of days ago, since it seemed to have slept on us. Maybe the personal affront brought it back.
