### ISSUE TITLE
future warning: deprecation in set_index

### ISSUE THREAD

**Issue by Khalilsqu** [pydata/xarray#2798]
#### Code Sample, a copy-pastable example if possible
```

seismic = xr.DataArray(data.T, coords={'shots' : ('traces', shot),'channel' : ('traces', channel)},
                      dims=['twt', 'traces'])

seismic = seismic.set_index(traces=['shots', 'channel'])
```
I keep getting this warning message 
```

C:\Miniconda3\lib\site-packages\xarray\core\dataset.py:167: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  idx = pd.MultiIndex(labels=labels, levels=levels, names=names)
```
A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Output of ``xr.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
libhdf5: None
libnetcdf: None

xarray: 0.11.3
pandas: 0.24.1
numpy: 1.15.4
scipy: 1.2.0
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: 3.0.2
cartopy: None
seaborn: 0.9.0
setuptools: 40.6.3
pip: 18.1
conda: 4.6.7
pytest: None
IPython: 7.2.0
sphinx: None
<details>
# Paste the output here xr.show_versions() here

</details>

**Comment by andreas-h** [comment]
When I look at current master, it seems this is already fixed

xarray 0.11.3:

https://github.com/pydata/xarray/blob/d58e0769c7d600d5c8c3c2fb52aa28856c4d3290/xarray/core/dataset.py#L167

master:

https://github.com/pydata/xarray/blob/9c0bbf744a5235b4187f87de49175e6776d813cb/xarray/core/dataset.py#L179

**Comment by max-sixty** [comment]
Yes, fixed, thanks
