### ISSUE TITLE
Cache datasets in XDG directories

### ISSUE THREAD

**Issue by QuLogic** [pydata/xarray#2815]
#### Problem description

The default directory for caching datasets is currently `~/.xarray_tutorial_data`:
https://github.com/pydata/xarray/blob/225868d232219440b188956531d5764ff4cd1b53/xarray/tutorial.py#L15

This doesn't follow the XDG standard on Linux, and AFAIK isn't actually invisible on Windows.

#### Expected Output

It would be better if this followed the XDG standard, i.e., `~/.cache/xarray_tutorial_data` (or some other places if you've set some environment variables) and something like `%LOCALAPPDATA%` on Windows. There are packages like [appdirs](https://pypi.org/project/appdirs/) that handle all this for you.

**Comment by shoyer** [comment]
Contributions would be very welcome here.

I would be happy to vendor a copy of appdirs to handle this.

**Comment by shoyer** [comment]
Or even just picking some better, platform specific defaults would be an improvement.

**Comment by dcherian** [comment]
I think `pooch` handles this for us now.
