### ISSUE TITLE
Support for ordered metadata

### ISSUE THREAD

**Issue by jzmcke** [pydata/xarray#2820]
#### Problem description

Currently, there is an assumption with xarray that metadata is not intrinsic to to the ordered nature of the database, and is contained in the .attrs structure. There are some types of metadata (e.g. python dictionaries) that describe an individual property of each piece of data in the data array but cannot be used in conjunction with numpy. It would be convenient to have a mechanism to order this metadata according to the same coordinate system used to layout the data.

It may be that it requires a variation of a DataArray format that does not support all of the lovely numpy mathematics (untouched in Dataset manipulation too), but still can perform all the necessary ordering and alignment that you get with indexing and slicing, albeit with a performance hit.

I am interested if there is a need for this elsewhere, or is this already solved with the current xarray API? Currently I can achieve the intended by initialising it with an array of dictionaries and retrieving them using my_data_array.sel(coords).item(0)... However I am unsure if this was the intended design and is not a heavily advertised interface.

**Comment by shoyer** [comment]
Can you give a concrete example of this kind of metadata?

**Comment by jzmcke** [comment]
I sure can try! I have a collection of time-domain measurement data. These are databased according to (for argument's sake: 'sample', 'angle' and 'level'. However, there is more information associated with each time domain measurement than just the angle and level. Namely, I wish to store information related to how you can automatically analyse the data inside that time-domain segment. I wish to do deconvolutions, harmonic analysis etc, all which can be done if there is certain information known about the time-domain signal that is stored along the 'sample' dimension.

To serve this purpose, I have created an xarray DataArray of python dictionaries (there may be a better way?). It has dimensions 'angle' and 'level' just like the time-domain measurements, and therefore can be added to a Dataset alongside the time measurements. This dictionary literally serves as a list of python arguments to an analysis function that can analyse specifically the time-domain series at each 'level' and 'angle'.

I am finding this structure to work well, if not an advertised use-case of xarray. That said, I am unable to use particular features like netcdf serialization since it does not like serializing numpy arrays of dictionaries, and I therefore need to use my own cumbersome format to store this structured metadata.

**Comment by max-sixty** [comment]
Closing as stale but please reopen if sufficiently pressing.
