### ISSUE TITLE
DOC: Broken links from generated documentation to github

### ISSUE THREAD

**Issue by hannasv** [pydata/xarray#2821]
This is the link that is used when i click on the "Edit on Github" button in the documentation. 
https://github.com/pydata/xarray/blob/stable/doc/generated/xarray.DataArray.std.rst 

I wish to access the implementation of Dataset.std() because I am not able to reproduce the results when I calculate the sample standard deviation. Based on the formula below. 

STD = sqrt( sum( x - x.mean() )**2 / (n-1) )

**Comment by shoyer** [comment]
Thanks for the report on the broken links. Unfortunately I'm sure yet how to fix these -- I doubt our docstring links have ever worked on readthedocs.

As for you other issue, xarray uses the default `ddof` parameter from numpy:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html

You should be set it by passing `ddof` as a keyword argument, e.g., `ds.std(ddof=1)`.

**Comment by zdgriffith** [comment]
I just went through a bunch of the doc pages and the "Edit on Github" link now works on all of them...I think this issue could be closed?

**Comment by dcherian** [comment]
yeah it works for pages like `whats-new.rst` but not for pages in the `/generated/` folder which is reasonable I guess.

This issue seems to be about linking to source code from the API reference (I think) which would be a really nice addition. Maybe take a look at adding https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html?

**Comment by dcherian** [comment]
Or maybe https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html?

**Comment by max-sixty** [comment]
Pinning this, would be great if anyone wants to have a go. It's a shame to have the link for doc contributions -- maybe our most important place for contributions, particularly from new contributors -- be broken.

**Comment by keewis** [comment]
`linkcode` could work, but we could also help `sphinx_rtd_theme` (which is what adds the `Edit on Github` link) to find the correct url. See e.g. [scanpydoc's template based implementation](https://icb-scanpydoc.readthedocs-hosted.com/en/latest/scanpydoc.rtd_github_links.html#scanpydoc.rtd_github_links.github_url) ([source code](https://github.com/theislab/scanpydoc/blob/master/scanpydoc/rtd_github_links.py))
