### ISSUE TITLE
multiple reference times

### ISSUE THREAD

**Issue by aragong** [pydata/xarray#2827]
#### problem when reference time change between months

I'm having some problems creating a subset form some netcdfs. Mainly I have to open some netcdfs from a global database, make an spatial and temporal subset and create a new netcdf to store the information in my local machine.

The problem appears when my temporal range goes from one month to another one. I load de dataset ussing ds = xr.open_mfdataset() everything is ok and i obtain a variable ds.time.values with all the correct times. The problem is when i tried to export this information to a new one netcdf. I use the comand ds.to_netcdf(filename, mode='w') but the resulting netcdf presents a mistake in the time values. it takes the reference time of the first netcdf but it doesn't have into account that the netcdf's of the following month have a diferent reference time.

I suposse that i'm missing something, Any idea?

**Comment by rabernat** [comment]
Without more details, it's very hard to answer your question.

Could you please share the output of `ds.info()` for each of the datasets, plus the full code you are writing, plus the full output of `xr.show_versions()`?

**Comment by aragong** [comment]
Thank you for your answer @rabernat, i totally agree, more information is requiered but afortunately I found my stupid mistake. 

I was duplicating some files in my file_list variable driving crazy to the xr.open_mfdataset().
I solve this issue with this line and now xarray works properly:
    # Delete repeated elements
    file_list=list(dict.fromkeys(file_list))

Thank you!
