### ISSUE TITLE
updated NumFOCUS donation link 

### ISSUE THREAD

**Issue by lisamartin72** [pydata/xarray#2829]
Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-xarray/index.html

Please update your website accordingly. : )

Thanks, 

Lisa Martin
NumFOCUS

**Comment by dcherian** [comment]
Stephan already did that :) see 55b8fe9
