### ISSUE TITLE
xarray 0.12.0 Fails To Import On Python 3.5.2

### ISSUE THREAD

**Issue by ancantus** [pydata/xarray#2830]
#### Error Code Example

Problem was discovered when xarray was pulled in via a pip dependency.

```python
import xarray
```
#### Problem description

xarray seems to now use `typing.ClassVar` which is unavailable in python 3.5.2

#### Output of ``import xarray``
<details>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$VENV_PATH/lib/python3.5/site-packages/xarray/__init__.py", line 26, in <module>
    from .coding.cftime_offsets import cftime_range
  File "$VENV_PATH/lib/python3.5/site-packages/xarray/coding/cftime_offsets.py", line 46, in <module>
    from typing import ClassVar, Optional
ImportError: cannot import name 'ClassVar'
</details>

#### Suggested Solution

- Remove ``typing.ClassVar`` from xarray
- Updated ``setup.py`` for 0.12.0 to reflect new python version requirement for the package.

**Comment by max-sixty** [comment]
Thanks @ancantus! Sorry for that.

Python 3.5.3 does [support `ClassVar`](https://docs.python.org/3/library/typing.html#typing.ClassVar), which is how it passed our tests. That was [released](https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-3-final) 2017-01-17. So this shouldn't be too common.

We should have specified in `setup.py`. I'll do a PR now.

@shoyer do you think we need to do anything immediately re PyPI?

**Comment by shoyer** [comment]
Thanks for the report. We should fix xarray on Python 3.5.0.

Probably the simplest thing to do would be to guard the import in a `typing.TYPE_CHECKING` block and replace `ClassVar[something]` in the code with `'ClassVar[something]'`. So you'll need at least Python 3.5.3 to do type checking of xarray, but it won't be required for users.

**Comment by max-sixty** [comment]
Great, made that change. (my search didn't turn up any references to `ClassVar` outside the comments, so only did the guard)

**Comment by ancantus** [comment]
Thanks! Came up for me cause the Ubuntu LTS Xenial uses Python 3.5.2 as its default installed version.

**Comment by dcherian** [comment]
Closed by #2831
