### ISSUE TITLE
xarray.concat docstring confuses PyCharm type detection

### ISSUE THREAD

**Issue by gimperiale** [pydata/xarray#2869]
PyCharm inspects docstrings to figure out the return type of functions. In the case of xarray.concat(), it believes it is 'type'; this causes it to prominently highlight the user code as an error:

![pycharm](https://user-images.githubusercontent.com/47244312/55621389-415f0280-5795-11e9-9882-ae158f5ca5a2.png)

**Comment by max-sixty** [comment]
Do we know why it thinks it's `type`?

**Comment by gimperiale** [comment]
@max-sixty because of this https://github.com/pydata/xarray/blob/c33dab237a0aca316b7f6d4ba10857829a895a25/xarray/core/combine.py#L73

**Comment by shoyer** [comment]
Interesting, we could definitely fix this.

Actually, I suspect the ideal situation would be to use type annotations -- then PyCharm should not need to inspect the docstrings at all.

**Comment by crusaderky** [comment]
@shoyer indeed. I'll start working on type annotations straight away.

**Comment by crusaderky** [comment]
#2877 doesn't fix it... More pulls will be needed
