### ISSUE TITLE
Custom fill value for align, reindex and reindex_like

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2876]
It would be nice to be able to specify a custom fill value other than NaN for alignment/reindexing, e.g.,
```
>>> xr.DataArray([0, 0], [('x', [1, 2])]).reindex(x=[0, 1, 2, 3], fill_value=-1)
<xarray.DataArray (x: 4)>
array([-1, 0, 0, -1])
Coordinates:
  * x        (x) int64 1 2 3 4
```

This should be pretty straightforward, simplify a matter of adding a `fill_value` keyword argument to the various interfaces and passing it on to `Variable.__getitem_with_mask` inside `xarray.core.alignment.reindex_variables()`.

**Comment by zdgriffith** [comment]
Hi, I'm a recent convert to xarray looking to start contributing - this seems like a good issue to dip my toes in.  If there's no one currently working on this I'm happy to take it up.

**Comment by rabernat** [comment]
Fantastic, welcome @zdgriffith! Our documentation has a page on [http://xarray.pydata.org/en/latest/contributing.html](contributing) which I encourage you to read through.

Once you have your local development environment set up and your fork cloned, the next step is to start exploring the source code and figuring out where changes need to be made. At that point, you can post any questions you have here and we will be happy to give you some guidance.
