### ISSUE TITLE
pytest output on travis is too verbose

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#2880]
I have to scroll over an immense amount of passing tests on travis before I can get to the failures. ([example](https://travis-ci.org/pydata/xarray/jobs/515490337)) This is pretty annoying.

The amount of tests in xarray has exploded recently. This is good! But maybe we should turn off `--verbose` in travis.

What does @pydata/xarray think?

**Comment by shoyer** [comment]
Agreed. 9000 lines of output is too much!

I think I originally turned this on to make it more obvious what the culprit is if/when tests stall, but that doesn't happen very often.
