### ISSUE TITLE
drop all but specified data_variables/coordinates as a convenience function

### ISSUE THREAD

**Issue by jbusecke** [pydata/xarray#2884]
I often work with datasets that consist out of a lot of data_variables and coordinates.
Often I am only concerned about a subset of variables, and for convenience drop all but a selected list of variables with a little snippet like this:

#### Code Sample, a copy-pastable example if possible
```python
def xr_keep(obj, varlist):
    """drop all data_vars exept the ones provided in `varlist` """
    obj = obj.copy()
    drop_vars = [a for a in obj.data_vars if a not in varlist]
    return obj.drop(drop_vars)
```

I would love to have this functionality available as a DataArray/Dataset function. It could look something like `da_slim = da.drop_all_but(['var1, 'var3'])`. Would this be of interest to people here? Then I could try to put in a PR.

**Comment by spencerkclark** [comment]
Something that is currently possible, though perhaps not super well-documented, is `ds.get(['var1', 'var3'])`.  This will select only `'var1'` and `'var3'` from the Dataset and omit any others.

**Comment by dcherian** [comment]
`ds[['var1', 'var3']]` also works AFAIR.

@jbusecke Can you send in a PR to update the  docs? https://xarray.pydata.org/en/stable/data-structures.html#dataset

**Comment by dcherian** [comment]
`I often work with datasets that consist out of a lot of data_variables and coordinates.`

I'm pretty sure there's an issue request somewhere to add `keep_vars` to the `open_*dataset` functions if you wanted to tackle that too :)

**Comment by jbusecke** [comment]
Wow. Thats awesome. Had no clue about it. I will put in a PR for the docs for sure. Might take a bit though. 
Ill also take a look at the `keep_vars` option.

**Comment by jbusecke** [comment]
Ok I have submitted a PR for the `xarray.Dataset.get` function.

@dcherian, I was not able to find that issue you mentioned. I would certainly be interested to have a look in the future.
