### ISSUE TITLE
Add broadcast_like?

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#2885]
What do you think of adding `da.broadcast_like(a)`?

This would be equivalent to `xr.broadcast(a, da)[1]`

**Comment by shoyer** [comment]
Sounds good to me!

**Comment by fujiisoup** [comment]
Can it be simply `da.broadcast(a)` or is it confusing?

**Comment by shoyer** [comment]
> Can it be simply `da.broadcast(a)` or is it confusing?

I think that would be a little confusing -- it's not clear whether the result should include a broadcast version of only `da` or also `a`.

**Comment by dcherian** [comment]
Yeah `broadcast_like` would be less confusing and the similarity to `reindex_like` and `interp_like` is really nice.

**Comment by fujiisoup** [comment]
That makes sense. Convinced.
