### ISSUE TITLE
Expose use_cftime option in open_zarr

### ISSUE THREAD

**Issue by spencerkclark** [pydata/xarray#2886]
`use_cftime` was recently added as an option to `decode_cf` and `open_dataset` to give users a little more control over how times are decoded (#2759).  It would be good if it was also available for `open_zarr`.  This perhaps doesn't have quite the importance, because `open_zarr` only works for single data stores, so there is no risk of decoding times to different types (e.g. as there was for `open_mfdataset`, #1263); however, it would still be nice to be able to silence serialization warnings that result from decoding times to cftime objects in some instances, e.g. #2754.

**Comment by Geektrovert** [comment]
Hey, can I work on this issue? I'm still new to this so a little heads up would be very nice!

**Comment by spencerkclark** [comment]
Absolutely - I think this should be as simple as adding a `use_cftime` argument to [`open_zarr`](https://github.com/pydata/xarray/blob/7b76f163394a35c9cd8013e835e9d0b2050fd9a6/xarray/backends/zarr.py#L440), threading its value through as an argument to the call to [`conventions.decode_cf`](https://github.com/pydata/xarray/blob/7b76f163394a35c9cd8013e835e9d0b2050fd9a6/xarray/conventions.py#L466) here:
https://github.com/pydata/xarray/blob/7b76f163394a35c9cd8013e835e9d0b2050fd9a6/xarray/backends/zarr.py#L542-L545

 and adding a test to make sure it works.

For more general tips on contributing to xarray, see the contributing guide [here](http://xarray.pydata.org/en/stable/contributing.html).

**Comment by Geektrovert** [comment]
Couldn't figure out how to implement the tests

**Comment by Geektrovert** [comment]
@naomi-henderson, I was working on this. But lately, I have been quite busy so I haven't implemented the tests yet. You can fix it if you wish to.

**Comment by max-sixty** [comment]
@spencerkclark @dcherian for transparency I unpinned this to make room for the broken docs -> github link. Feel free to unpin the build warnings if this is still top-of-mind
