### ISSUE TITLE
Dependency issue when building docs according to instructions

### ISSUE THREAD

**Issue by jbusecke** [pydata/xarray#2893]
#### Code Sample, a copy-pastable example if possible

I was following the instructions to build the docs [locally](https://xarray.pydata.org/en/latest/contributing.html#how-to-build-the-xarray-documentation), using `xarray/ci/requirements-py36` as test environment.

When running `make html` in the `xarray/doc` folder, I get this:
```
xarray: 0.12.1+9.gfad6d624.dirty, /Users/juliusbusecke/Work/CODE/PYTHON/xarray/xarray/__init__.py

Extension error:
Could not import extension IPython.sphinxext.ipython_directive (exception: No module named 'IPython')
make: *** [html] Error 2
(test_env)
```
After installing ipython with `conda install ipython`, the build works properly. 

Should this line `conda install -c conda-forge sphinx sphinx_rtd_theme sphinx-gallery numpydoc` be updated to:
`conda install -c conda-forge sphinx sphinx_rtd_theme sphinx-gallery numpydoc ipython` ?

Or am I overlooking something?

**Comment by dcherian** [comment]
There is an `environment.yml` file in the `doc` folder that contains `ipython`, so yes that line should be fixed. PR? :)
