### ISSUE TITLE
Journal of Open Research Software

### ISSUE THREAD

**Issue by DamienIrving** [pydata/xarray#290]
I'm envisaging that people (including myself in the future) might like to cite xray in their journal papers (along with the other software packages and libraries that they used). I was therefore wondering if you have thought about writing a paper about xray for the [Journal of Open Research Software](http://openresearchsoftware.metajnl.com/)? This would be a great way for you to get academic credit for the hard work you've put into it, and would also make it very easy for authors to cite.

**Comment by hainm** [comment]
@shoyer supposed Zenodo will last long. I myself prefer to publish software in a journal or conference.

Hai
