### ISSUE TITLE
xr.dot result differs from np.dot

### ISSUE THREAD

**Issue by lkugler** [pydata/xarray#2907]
#### Code Sample
Hi, shouldn't the result of xr.dot be equivalent to np.dot?
In np.dot I get values of ~280, and for xr.dot I get ~1100:

```python
<xarray.DataArray 'models' (model name: 4)>
array([283.6939  , 283.129198, 284.671649, 284.01668 ])
Coordinates:
    valid_time  datetime64[ns] 2019-03-15T19:00:00
    lat         float64 45.89
    lon         float64 4.683
  * model name  (model name) |S5 'apple' 'juice' 'banana' 'milk'

<xarray.DataArray 'weights' (models: 4)>
array([0.308999, 0.191562, 0.049474, 0.449983])
Coordinates:
    lat      float64 45.89
    lon      float64 4.683
Dimensions without coordinates: models
```
Now the calculation:
```python
np.dot(models.values, weights_da.values)
283.7847051563903

xr.dot(weights_da, models, dims=['models', 'model name'])
<xarray.DataArray ()>
array(1135.532891)
Coordinates:
    lat         float64 45.89
    lon         float64 4.683
    valid_time  datetime64[ns] 2019-03-15T19:00:00

```
#### Problem description

What's going on below the surface? I mean if I create the array by hand (not from the file) I can't reproduce this. I don't think it's related to the file (as the values from the file work with numpy.dot). Something related to dask? Doing np.dot on the whole array (not just this piece here) results in a MemoryError.
I'm 

Thanks for any advice!

EDIT: I also tested it on python 3.7.3. xarray 0.11.3. Same result.

#### Output of ``xr.show_versions()``

<details>
In [23]: xr.show_versions()
/home/py_user/miniconda2/envs/v0/lib/python2.7/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-143-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8" 
LOCALE: None.None

xarray: 0.10.9
pandas: 0.23.4
numpy: 1.16.2
scipy: 1.2.1
netCDF4: 1.4.2
h5netcdf: 0.7.1
h5py: 2.8.0
Nio: None
zarr: None
cftime: 1.0.3.4
PseudonetCDF: None
rasterio: None
iris: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 1.1.4
distributed: 1.26.0
matplotlib: 2.2.3
cartopy: None
seaborn: 0.9.0
setuptools: 40.8.0
pip: 19.0.3
conda: None
pytest: None
IPython: 5.8.0
sphinx: None

</details>

**Comment by dcherian** [comment]
You have two different dimensions here; and xarray is broadcasting so those two statements are not equal i.e. both `weights` and `models` end up being 2D arrays which are then operated upon by `dot`.

How about `xr.dot(weights_da.rename({'models': 'model name'}), models)`?

**Comment by dcherian** [comment]
Here's some relevant documentation: https://xarray.pydata.org/en/stable/computation.html#broadcasting-by-dimension-name

**Comment by lkugler** [comment]
Sooo many thanks for this ultrafast response. You're correct. What I didn't know was that the dimensions to multiply have to have the same names. I thought I could sum over different coordinates indicating the names within the `dims` keyword, but the implementation makes totally sense now. To summarize: 
Dimensions to sum over have to have the same name and the same ordering of the coordinate values (else f.e. a `ValueError: indexes along dimension 'model name' are not equal ` is raised)

But shouldn't there be an error message if one specifies dimensions to `dims` that are not in both of the dataarrays?

**Comment by dcherian** [comment]
automatic broadcasting is an extremely useful feature of xarray: See https://xarray.pydata.org/en/stable/computation.html#broadcasting-by-dimension-name for examples.

> What I didn't know was that the dimensions to multiply have to have the same names. 

If the dimensions don't have the same name; xarray "broadcasts" both variables so that they each have both dimensions and then does the arithmetic operation you ask it to.

> I thought I could sum over different coordinates indicating the names within the dims keyword, but the implementation makes totally sense now. To summarize:

This is correct but you're misunderstanding the applicability here (I think).

> But shouldn't there be an error message if one specifies dimensions to dims that are not in both of the dataarrays?

No, broadcasting is a feature.
