### ISSUE TITLE
docs questions from new user

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#2909]
A relatively new user here gave me an incomplete list of things they found to be confusing in the docs:

-  ~What is xarray's data model?~ opened #2913 
- [x] What is split-apply-combine?
- [x] What are dummy dimensions and `np.newaxis`

- [x] quick-overiew: Index so that you extract a subset!

- [ ] too many references to pandas!
- [x] do I need to know pandas to use xarray?
- [ ] what is the difference between attrs and encoding? How do I use them properly/correctly?
- [ ] why `isnull` and `dropna`: why `dropna` instead of `dropnull`
- [x] `compute` docstring doesn't mention computation!
- [x] compute vs persist vs load: what's the difference
- [ ] do I get parallelization for free?
  - [ ] do I start a dask cluster first?
  - [x] dask page links to shoyers blog but that doesn't explicitly start a cluster.

I'm crossing out things that I've started to fix.

**Comment by fmaussion** [comment]
>  too many references to pandas!

This is a tricky one. In the beginning we wanted people to come from pandas to xarray. It was kind of assumed that everybody uses and loves pandas, therefore will also use and love xarray. (my own experience). 

But do we have to build the docs for non-pandas users as well? It could make quite a few things redundant with the pandas documentation...

**Comment by TomNicholas** [comment]
> But do we have to build the docs for non-pandas users as well? It could make quite a few things redundant with the pandas documentation...

I personally think we should. I think there are a very large number of numpy users who don't use pandas or any labelled data libraries at all, who cannot be assumed to know what Pandas does. I definitely didn't understand what the references to Pandas meant when I first read xarray's documentation, and everyone else in my field seems to fit in this category at least...
