### ISSUE TITLE
Keyword argument support for drop()

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2910]
Currently, to drop labels along an existing dimension, you need to write something like: `ds.drop(['a', 'b'], dim='x)`.

It would be nice if keyword arguments were supported, e.g., `ds.drop(x=['a', 'b'])`. This would make `drop()` more symmetric with `sel()`.

**Comment by gwgundersen** [comment]
Created PR https://github.com/pydata/xarray/pull/3128 to add support for this feature.
