### ISSUE TITLE
Plotting tripolar dataset in xarray

### ISSUE THREAD

**Issue by fabienpaulot** [pydata/xarray#2915]
I am trying to plot a tripolar grid dataset using xarray/cartopy.

I can plot it fine using matplotlib/cartopy

ds = xr.open_dataset('ocean_hgrid.nc')
xcntr = ds['x'][1::2,1::2]
ycntr = ds['y'][1::2,1::2]

test=xr.open_dataset('xarray_test.nc')

ax = plt.axes(projection=proj)
cs=plt.contourf(xcntr,ycntr,test['nh4_stf'],transform=data_crs,cmap='coolwarm',vmin=-4.5e-9,vmax=4.5e-9)
plt.colorbar(cs)

I would like to achieve the same result in xarray. I have tried the following
proj=ccrs.PlateCarree()
data_crs=ccrs.PlateCarree()
ax = plt.axes(projection=proj)
test['nh4_stf'].plot.contourf(ax=ax, transform=ccrs.PlateCarree())
and 
test['nh4_stf'].plot.pcolormesh(x=xcntr,y=ycntr,ax=ax,transform=ccrs.PlateCarree())

but this does not work (the second option crashes).
Is there a way to pass xcntr,ycntr?

datasets can be found on 
ftp://ftp.gfdl.noaa.gov/pub/Fabien.Paulot/xarray/

Thank you very much and congratulations to the developers for this amazing tool

xarray.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 2.6.32-696.30.1.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US
LOCALE: en_US.ISO8859-1
libhdf5: 1.10.3
libnetcdf: 4.6.1

xarray: 0.11.3
pandas: 0.24.2
numpy: 1.16.2
scipy: 1.2.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: 2.8.0
Nio: None
zarr: None
cftime: 1.0.3.4
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
cyordereddict: None
dask: 1.1.5
distributed: 1.27.0
matplotlib: 3.0.3
cartopy: 0.16.0
seaborn: 0.9.0
setuptools: 41.0.0
pip: 19.0.3
conda: None
pytest: None
IPython: 7.4.0
sphinx: 2.0.1

**Comment by rabernat** [comment]
You will need to add the `x` and `y` keyword arguments to contour. See the example from the xarray docs: http://xarray.pydata.org/en/latest/examples/multidimensional-coords.html

Could you also include the output of `print(test)`?

**Comment by fabienpaulot** [comment]
Thanks 

`print(test)`

<xarray.Dataset>
Dimensions:  (xh: 720, yh: 576)
Coordinates:
  * xh       (xh) float64 -299.8 -299.2 -298.8 -298.2 ... 58.75 59.25 59.75
  * yh       (yh) float64 -77.91 -77.72 -77.54 -77.36 ... 89.47 89.68 89.89
Data variables:
    nh4_stf  (yh, xh) float32 nan nan nan nan nan nan ... nan nan nan nan nan


I am getting an error if I pass `x` and `y`

`test['nh4_stf'].plot.contourf(x=xcntr,y=ycntr,ax=ax,transform=ccrs.PlateCarree())`
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by spencerkclark** [comment]
Thanks @fabienpaulot  -- this could probably use a better error message.  The arguments passed to `x` and `y` must be dimension or coordinate names of the DataArray rather than DataArrays themselves.  In your case you can assign `xcntr` and `ycntr` as coordinates of `test` and then plot:

```python
test = test.assign_coords(x=xcntr.rename({'nxp': 'xh', 'nyp': 'yh'}),
                          y=ycntr.rename({'nxp': 'xh', 'nyp': 'yh'}))
test['nh4_stf'].plot.contourf(x='x', y='y', ax=ax, transform=ccrs.PlateCarree())
```

The renaming is necessary so the dimension names match that of `test`.

**Comment by fabienpaulot** [comment]
Perfect. Thanks for the clear explanation.
 This fixes my issue.
Fabien
