### ISSUE TITLE
Windowed read in open_rasterio 

### ISSUE THREAD

**Issue by grinsted** [pydata/xarray#2918]
Rasterio supports reading small subsets of big files with the window argument. It would be nice if xarray open_rasterio could support that too. 

Rasterio documentation: https://rasterio.readthedocs.io/en/stable/topics/windowed-rw.html

And here I use this feature (but i would like to use xarrray instead): https://github.com/grinsted/pyimgraft/blob/master/geoimread.py

**Comment by fmaussion** [comment]
Xarray already supports this, the syntax is that of xarray though. We read the files lazily, then access only what you select, e.g.:

```python
import os
import urllib.request
import matplotlib.pyplot as plt
import xarray as xr

# Download the file from rasterio's repository
url = 'https://github.com/mapbox/rasterio/raw/master/tests/data/RGB.byte.tif'
urllib.request.urlretrieve(url, 'RGB.byte.tif')

# Read the data
da = xr.open_rasterio('RGB.byte.tif')
da[:, 400:600, 400:600].plot.imshow();
```

(or [any other indexing](http://xarray.pydata.org/en/stable/indexing.html) operation)

**Comment by fmaussion** [comment]
> (or any other indexing operation)

Correction: only the windowed operations can be done lazily, the other ones will fail unless you load the data first.

**Comment by grinsted** [comment]
Really nice. Thank you. Feel free to close this issue. 

Note: rasterio can read directly from http. e.g. this works: 
```
import xarray as xr
da = xr.open_rasterio('https://github.com/mapbox/rasterio/raw/master/tests/data/RGB.byte.tif')
da[:, 400:600, 400:600].plot.imshow()
```
