### ISSUE TITLE
Will DataArray have a 'agg' method like dataframe?

### ISSUE THREAD

**Issue by About9** [pydata/xarray#2926]
Sometimes I need to define my own aggregation methods. I can not find such an implementation like dataframe.agg() in the xarray API. It will be very useful.

Thank you.

**Comment by shoyer** [comment]
`DataFrame.agg` supports [quite a few](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.agg.html) different forms of input. Which ones do you care about?

**Comment by About9** [comment]
For me, I think any forms of input might be needed in the future. It will be very flexible if I can define them all by myself.

**Comment by max-sixty** [comment]
Closing as stale, please reopen with fuller examples of what we'd want if there's still demand
