### ISSUE TITLE
Data variables empty with to_zarr / from_zarr on s3 if 's3://' in root s3fs string

### ISSUE THREAD

**Issue by birdsarah** [pydata/xarray#2927]
I apparently have a bad habit of prepending my s3 strings with 's3://' (see #2740)

To reproduce:

```python
import numpy as np
import xarray as xr
import s3fs
s3 = s3fs.S3FileSystem(**options)
store = s3fs.S3Map(root='bucket/store.zarr', s3=s3)
# Create and write
a = xr.DataArray(np.random.randn(2, 3))
a.to_dataset(name='data').to_zarr(store)
# Read back in
a = xr.open_zarr(store)
print(a)
```
Actual Result:
```
<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
```
Expected Result: my dataset, which I can then get the DataArray with `a['data']`

If the 's3://' is not there everything works as expected.

I will add that the fact that it at least opens now means I believe we can close #2740.

xarray version 0.12.1
zarr version 2.3.1
s3fs version 0.2.1

**Comment by jendrikjoe** [comment]
I am seeing the same behaviour. 
For me, writing with a prepended s3:// is no issue though (even appending to zarr works when using the related PR). 
Only opening cannot cope with the prepended s3://.

**Comment by shoyer** [comment]
All xarray does is directly pass the `store` object on to `zarr.open_group()` or `zarr.open_consolidated()`. So this must be an issue with s3fs or zarr -- we have literally no logic related to parsing s3 filenames in xarray.

**Comment by TomAugspurger** [comment]
Spoke with @martindurant about this today. The mapping should probably strip the protocol from the `root` provided by the user. Tracking in https://github.com/intake/filesystem_spec/issues/56 (this issue can probably be closed).
