### ISSUE TITLE
Implicit conversion from int to float tampers with values when int is not representable as float

### ISSUE THREAD

**Issue by floogit** [pydata/xarray#2945]
```python
ds = xr.Dataset()
val = 95042027804193144 
ds['var1'] = xr.DataArray(val)
ds_1 = ds.where(ds.var1==val)

print(ds_1.var1.dtype)
dtype('float64')
print(int(ds_1.var1))
95042027804193152
```
#### Problem description
As described in #2183, int values are converted to float in `where()`, also when there are no NaNs in the data. This is a serious issue for the case when the int64 number is not representable as float64, as is the case in the example above. The resulting numbers are then actually different from the original numbers, without any warning.

#### Expected Output
I guess this is hard to fix. At a minimum, `where()` should probably not cast to float when there are no NaNs (which would already fix our use case). I would also rather expect an error instead of silently changing the values of a variable. 

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
python-bits: 64
OS: Linux
OS-release: 4.19.0-0.bpo.2-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.8.18
libnetcdf: 4.4.1.1

xarray: 0.12.1
pandas: 0.24.2
numpy: 1.15.4
scipy: 1.2.1
netCDF4: 1.2.8
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: 0.36.0
cfgrib: 0.9.6.post1
iris: None
bottleneck: 1.2.1
dask: 1.1.4
distributed: None
matplotlib: 3.0.3
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 39.2.0
pip: 19.0.3
conda: None
pytest: 4.4.1
IPython: 7.5.0
sphinx: None

</details>

**Comment by shoyer** [comment]
You can avoid this by setting a `other` in where explicitly, e.g., `ds.where(ds.var1 == val, other=-1)`.

Unfortunately I don't see any good way to fix this short of NumPy support for an integer dtype with missing values. If we disabled automatic casting from integer to float values when NaNs could be introduced, then lots of operations would just fail instead.
