### ISSUE TITLE
Un-subsetted NetCDF plot results in an empty plot

### ISSUE THREAD

**Issue by lbesnard** [pydata/xarray#2961]
#### Code Sample, a copy-pastable example if possible

Hi I put together a gist showing my issue
https://gist.github.com/lbesnard/c1edb9b23d0e7a37486422407cc8bbc1

```python
import intake
import xarray as xr
import s3fs
fs = s3fs.S3FileSystem(anon=True)

all_files = fs.ls('imos-data/IMOS/SRS/SST/ghrsst/L3S-1m/day/2018/')
small_file_path = all_files[6] 
ds_single = xr.open_dataset(fs.open(small_file_path),engine='h5netcdf')

ds_single.sea_surface_temperature.plot()
```
#### Problem description

Plotting an un-subsetted NetCDF results in an empty plot. There is no error message, warning ...

However, if I create a subset, it works (although this is really slow, while other tools such as ncBrowse are pretty much instant at giving a plot back)
#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-45-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.12.1
pandas: 0.24.2
numpy: 1.16.3
scipy: 1.2.1
netCDF4: 1.5.1.2
pydap: None
h5netcdf: 0.7.1
h5py: 2.9.0
Nio: None
zarr: 2.3.1
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: 1.0.22
cfgrib: None
iris: 2.2.0
bottleneck: None
dask: 1.2.2
distributed: 1.28.0
matplotlib: 3.0.3
cartopy: 0.17.0
seaborn: None
setuptools: 39.2.0
pip: 10.0.1
conda: 4.6.14
pytest: None
IPython: 7.5.0
sphinx: None

</details>

**Comment by shoyer** [comment]
How large is `ds_single.sea_surface_temperature.shape`?

To determine whether this is a plotting issue or a data reading issue, I would try loading dataset into memory first, e.g,. `ds_single.load()`. Does that operation appear to work properly?

**Comment by lbesnard** [comment]
Sorry for the late reply.

The shape is not that big  
```python
ds_single.sea_surface_temperature.shape                                                                                                                                                                                               
Out[6]: (1, 4500, 6000)
```

```ds_single.load()``` seems to be performing fine.

**Comment by shoyer** [comment]
OK, so this sounds like an issue with data loading. My guess is that h5py's handling of arbitrary file-objects just isn't very efficient when coupled with s3fs for some reason, though it really shouldn't be entirely failing. You may need more caching and/or look-ahead buffering to get reasonable performance, e.g., as noted here http://matthewrocklin.com/blog/work/2018/02/06/hdf-in-the-cloud. Maybe s3fs supports this? It's probably worth asking on either the s3fs or h5py issue trackers.

**Comment by lbesnard** [comment]
I actually did try with a local file rather than using s3fs and I had similar results

**Comment by shoyer** [comment]
> I actually did try with a local file rather than using s3fs and I had similar results

Can you clarify? Is it broken or does the plot work properly with a local file?

**Comment by lbesnard** [comment]
> Can you clarify? Is it broken or does the plot work properly with a local file?

The plot is completely blank, apart of a title and a colourbar.

this code does't use s3fs, opendap ... and should run on any machine showing the isue:
```python
import xarray as xr
import requests
import io
import netCDF4

file_url = 'https://s3-ap-southeast-2.amazonaws.com/imos-data/IMOS/SRS/SST/ghrsst/L3S-1m/day/2018/20180630152000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1m_day.nc'
res = requests.get(file_url)
content = io.BytesIO(res.content)
nc4_ds = netCDF4.Dataset('test', memory=res.content)
    
store = xr.backends.NetCDF4DataStore(nc4_ds)
ds_single = xr.open_dataset(store)

ds_single.sea_surface_temperature.plot()
```

**Comment by dcherian** [comment]
I downloaded that file with wget, loaded and plotted it. It takes a while but it works fine. 

`plot` uses `pcolormesh` by default; `imshow` seems to work a lot quicker. Your example code also works here :confused: 

Try `ds_single.sea_surface_temperature.plot.imshow()`

![image](https://user-images.githubusercontent.com/2448579/58212689-e9308100-7cac-11e9-9431-73037a6241d0.png)

**Comment by lbesnard** [comment]
@dcherian 
Thanks. I actually ran ```ds_single.sea_surface_temperature.plot.imshow()``` but got an error
```
ValueError: A 3-dimensional array was passed to imshow(), but there is no dimension that could be color.  At least one dimension must be of size 3 (RGB) or 4 (RGBA), and not given as x or y.
```

Anyway, I tried running the above code directly in **ipython**. I just added the following (since it doesn't seem possible to directly call  ```show()``` from xarray):
```python
import matplotlib.pyplot as plt 
plt.show() 
```

and it worked ! ... 
I was running this snippet of code on a Jupyter notebook running this version
```
Server Information:

You are using Jupyter notebook.

The version of the notebook server is: 5.7.8
The server is running on this version of Python:

Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

Current Kernel Information:

Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.
```

So now I don't know if it's a bug from Jupyter that should be signaled directly to them, or if it's xarray not communicating properly with Jupyter

**Comment by dcherian** [comment]
Yeah you need a `squeeze` before imshow. Sorry.

`xarray` just wraps matplotlib so these seems like funny interaction between matplotlib and jupyter. I'll close this issue but feel free to re-open if it looks like an xarray bug.
