### ISSUE TITLE
`where` function mis-broadcasts and alters data type on dataset

### ISSUE THREAD

**Issue by bradyrx** [pydata/xarray#2969]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np

# generate data
dateVar = np.arange('2005-02', '2005-06', dtype='datetime64[D]')
t = len(dateVar)
floatVar = np.random.rand(t, 100)
indexVar = np.arange(100)
intVar = np.random.randint(1, high=10, size=(t, 100))

# create dataset
A = xr.DataArray(floatVar, dims=['time', 'N'])
A.name = 'floatVar'
B = xr.DataArray(indexVar, dims=['N'])
B.name = 'indexVar'
C = xr.DataArray(intVar, dims=['time', 'N'])
C.name = 'intVar'
D = xr.DataArray(dateVar, dims=['time'])
D.name = 'dateVar'
ds = xr.merge([A,B,C,D])
print(ds)

<xarray.Dataset>
Dimensions:   (N: 100, time: 120)
Dimensions without coordinates: N, time
Data variables:
    floatVar  (time, N) float64 0.4223 0.5019 0.8522 ... 0.9338 0.5833 0.09859
    indexVar  (N) int64 0 1 2 3 4 5 6 7 8 9 10 ... 90 91 92 93 94 95 96 97 98 99
    intVar    (time, N) int64 9 2 3 6 8 4 8 7 6 4 2 6 ... 3 1 8 3 8 3 5 3 1 6 7
    dateVar   (time) datetime64[ns] 2005-02-01 2005-02-02 ... 2005-05-31

# apply where function
ds.where(ds.indexVar > 50, drop=True)

<xarray.Dataset>
Dimensions:   (N: 49, time: 120)
Dimensions without coordinates: N, time
Data variables:
    floatVar  (time, N) float64 0.3381 0.04735 0.464 ... 0.5571 0.5297 0.8106
    indexVar  (N) float64 51.0 52.0 53.0 54.0 55.0 ... 95.0 96.0 97.0 98.0 99.0
    intVar    (time, N) float64 5.0 2.0 9.0 5.0 5.0 1.0 ... 1.0 6.0 5.0 4.0 3.0
    dateVar   (time, N) datetime64[ns] 2005-02-01 2005-02-01 ... 2005-05-31
```
#### Problem description

This is motivated by a use-case of dimensions (Time, nParticle) for a Lagrangian particle simulation. In the above code snippet, I filter by some condition on `indexVar` (e.g., some type of particle).

For variables that contain the same dimension as the one in `indexVar` (N), it broadcasts fine and there's no dimension changes. In the case of `dateVar`, which only has dimension `time`, there is a dim expansion to add N. 

Further, data-types are changed (`indexVar` and `intVar` from `int64` to `float64`). In my use-case, a variable of type `S64` was converted to `O`.

So the two major issues here:
1. `where` mis-broadcasts certain variables by adding the filtered dimension (in this case `N` to `dateVar`). It should instead ignore variables that don't contain the variable being filtered.
2. `where` changes data-types of variables after the filter is applied.

#### Expected Output

```python
<xarray.Dataset>
Dimensions:   (N: 49, time: 120)
Dimensions without coordinates: N, time
Data variables:
    floatVar  (time, N) float64 0.3381 0.04735 0.464 ... 0.5571 0.5297 0.8106
    indexVar  (N) int64 51 52 53 54 55 ... 95 96 97 98 99
    intVar    (time, N) int64 5 2 9 5 5 1 ... 1 6 5 4 3
    dateVar   (time) datetime64[ns] 2005-02-01 2005-02-02 ... 2005-05-31
```

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.12.1
pandas: 0.24.2
numpy: 1.16.3
scipy: 1.2.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: 1.2.2
distributed: 1.28.0
matplotlib: 3.0.3
cartopy: 0.17.0
seaborn: None
setuptools: 41.0.1
pip: 19.1.1
conda: None
pytest: 4.5.0
IPython: 7.5.0
sphinx: None
</details>

**Comment by dcherian** [comment]
1. This has been reported before e.g. #1234 . I think we need a kwarg to control this behaviour. You can avoid this here by making `dateVar` a coordinate which seems logical in this case.
`ds = ds.rename({'dateVar': 'time'}).set_coords('time')`

2. This is because `where` fills in NaNs which is not representable by variables with int datatype. 
    So xarray casts the variable to float. I guess we could avoid this when `drop=True` but not when `drop=False`. You can fix this partially by setting `indexVar` to be a co-ordinate which again seems logical in this case.


```
ds = (ds.rename({'dateVar': 'time', 
                 'indexVar': 'N'})
      .set_coords(['time', 'N']))

print(ds)

ds.where(ds.N > 50, drop=True)
```

gives me

```
<xarray.Dataset>
Dimensions:   (N: 100, time: 120)
Coordinates:
  * N         (N) int64 0 1 2 3 4 5 6 7 8 9 10 ... 90 91 92 93 94 95 96 97 98 99
  * time      (time) datetime64[ns] 2005-02-01 2005-02-02 ... 2005-05-31
Data variables:
    floatVar  (time, N) float64 0.2382 0.9297 0.5391 ... 0.9527 0.6448 0.08718
    intVar    (time, N) int64 9 5 7 9 9 3 3 2 2 8 4 1 ... 8 9 1 8 1 8 9 5 7 4 4

<xarray.Dataset>
Dimensions:   (N: 49, time: 120)
Coordinates:
  * N         (N) int64 51 52 53 54 55 56 57 58 59 ... 92 93 94 95 96 97 98 99
  * time      (time) datetime64[ns] 2005-02-01 2005-02-02 ... 2005-05-31
Data variables:
    floatVar  (time, N) float64 0.5974 0.09831 0.3858 ... 0.9527 0.6448 0.08718
    intVar    (time, N) float64 3.0 8.0 7.0 5.0 4.0 4.0 ... 9.0 5.0 7.0 4.0 4.0
```

`intVar` has still been converted to float so you'll need to fix that manually.

**Comment by bradyrx** [comment]
Thanks for the feedback and link to the other issue. I wasn't sure what to search to find other issues on this. The coordinate transformation seems like the most straightforward approach.
