### ISSUE TITLE
Confusing handling of NetCDF coordinates

### ISSUE THREAD

**Issue by djhoese** [pydata/xarray#2976]
#### Code Sample, a copy-pastable example if possible

I'm currently trying to figure out why some coordinates of a netcdf file are included in the resulting Dataset object and why some are not. I've tried looking at the `open_dataset` source code and think I'm kind of stuck.

To reproduce:

Download GOES-16 ABI L1b NetCDF file from (click the link to have google redirect you to the actual file):

    https://storage.cloud.google.com/gcp-public-data-goes-16/ABI-L1b-RadC/2019/140/18/OR_ABI-L1b-RadC-M6C01_G16_s20191401801336_e20191401804109_c20191401804156.nc?_ga=2.44800740.-1513329882.1547344783

```python
import xarray as xr
a = xr.open_dataset('OR_ABI-L1b-RadC-M6C01_G16_s20191401801336_e20191401804109_c20191401804156.nc')
print(a.coords)
```

Results in:

```
In [5]: a['Rad'].coords                                                                                                                                                                     
Out[5]: 
Coordinates:
    t        datetime64[ns] ...
  * y        (y) float32 0.151844 0.151788 0.151732 ... -0.151788 -0.151844
  * x        (x) float32 -0.151844 -0.151788 -0.151732 ... 0.151788 0.151844
    y_image  float32 ...
    x_image  float32 ...
```

Even though `ncdump -h <file>.nc` shows:

```
variables:
        short Rad(y, x) ;
                ...
                Rad:coordinates = "band_id band_wavelength t y x" ;
                ...
```

and:

```
a.coords
```

shows:

```
Coordinates:
    t                          datetime64[ns] ...
  * y                          (y) float32 0.151844 0.151788 ... -0.151844
  * x                          (x) float32 -0.151844 -0.151788 ... 0.151844
    y_image                    float32 ...
    x_image                    float32 ...
    band_id                    (band) int8 ...
    band_wavelength            (band) float32 ...
    t_star_look                (num_star_looks) datetime64[ns] ...
    band_wavelength_star_look  (num_star_looks) float32 ...
```

#### Problem description

I would have expected the `'Rad'` variable/DataArray to include the `band_id` and `band_wavelength` coordinate variables but **not** the `x_image` and `y_image` variables since they are not listed in the NetCDF variables `coordinates` attribute.

Can someone summarize the rules on how xarray came up with these coordinates? Or is this a bug?

#### Output of ``xr.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 18.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.12.1
pandas: 0.24.2
numpy: 1.14.3
scipy: 1.2.1
netCDF4: 1.5.0.1
pydap: None
h5netcdf: 0.7.1
h5py: 2.9.0
Nio: None
zarr: 2.3.1
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: 1.0.22
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: 1.1.5
distributed: 1.26.1
matplotlib: 3.0.3
cartopy: 0.17.0
seaborn: None
setuptools: 41.0.0
pip: 19.0.3
conda: None
pytest: 4.4.0
IPython: 7.4.0
sphinx: 2.0.1
```

</details>

**Comment by shoyer** [comment]
Xarray merges together coordinates from all data variables into a Dataset. As far as xarray is concerned, if you're a coordinate of one data variable, you're a coordinate of every data variable.

**Comment by djhoese** [comment]
Ok, but then why are coordinates that exist in the Dataset and in the netcdf variable's 'coordinates' attribute not listed in the DataArray for that variable?

**Comment by shoyer** [comment]
Can you print what the whole Dataset looks like?

**Comment by shoyer** [comment]
Looking more carefully, Rad doesn't include the "band_id" coordinate because "band_id" includes a "band" dimension, which isn't found on the Rad variable.

**Comment by shoyer** [comment]
Here's where you can find the logic for subsetting coordinates, by the way: https://github.com/pydata/xarray/blob/0811141e8f985a1f3b95ead92c3850cc74e160a5/xarray/core/dataset.py#L983-L986

**Comment by djhoese** [comment]
> Rad doesn't include the "band_id" coordinate because "band_id" includes a "band" dimension, which isn't found on the Rad variable.

Ah, that's what I was looking for! Ok, that makes sense. To be as generic as possible xarray is using the dimensions to determine if a coordinate "belongs" to a variable rather than the "coordinates" attribute of that variable. I can live with that. Thanks for the explanation and the link to that part of the code.
