### ISSUE TITLE
xr.open_mfdataset(): unexpected wildcard behavior

### ISSUE THREAD

**Issue by sridge** [pydata/xarray#2984]
#### Code Sample

```python
import xarray as xr
import numpy as np

# create test data
x = np.ones((3,3))
y = np.ones((3,3))
z = np.ones((3,3))

x = xr.DataArray(x,name='var1')
y = xr.DataArray(y,name='var2')
z = xr.DataArray(z,name='var3')

x.to_netcdf('test_output_1.nc')
y.to_netcdf('test_output_2.nc')
z.to_netcdf('file_to_ignore.nc') # we don't want this file in this dataset

ds = xr.open_mfdataset('./test_output_*.nc')
```
#### This dataset includes the unwanted file ('file_to_ignore.nc'):
```
<xarray.Dataset>
Dimensions:  (dim_0: 3, dim_1: 3)
Dimensions without coordinates: dim_0, dim_1
Data variables:
    var1     (dim_0, dim_1) float64 dask.array<shape=(3, 3), chunksize=(3, 3)>
    var2     (dim_0, dim_1) float64 dask.array<shape=(3, 3), chunksize=(3, 3)>
    var3     (dim_0, dim_1) float64 dask.array<shape=(3, 3), chunksize=(3, 3)>
```
#### Problem description

If I use the star wildcard, open_mfdataset() will add all netCDF files in the directory to the dataset, no matter where I place the wildcard. This results in files being included in the dataset, that should have been excluded. This is an issue I would be happy help to resolve!

#### Expected Output
```
<xarray.Dataset>
Dimensions:  (dim_0: 3, dim_1: 3)
Dimensions without coordinates: dim_0, dim_1
Data variables:
    var1     (dim_0, dim_1) float64 dask.array<shape=(3, 3), chunksize=(3, 3)>
    var2     (dim_0, dim_1) float64 dask.array<shape=(3, 3), chunksize=(3, 3)>
```

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.6.3.el7.centos.plus.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.2
libnetcdf: 4.6.1

xarray: 0.12.0
pandas: 0.23.0
numpy: 1.14.3
scipy: 1.1.0
netCDF4: 1.4.0
pydap: None
h5netcdf: None
h5py: 2.7.1
Nio: None
zarr: None
cftime: 1.0.0b1
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: 0.17.5
distributed: 1.21.8
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 39.1.0
pip: 10.0.1
conda: None
pytest: 3.5.1
IPython: 6.4.0
sphinx: 1.7.4

</details>

**Comment by TomNicholas** [comment]
Thanks for the clear example of the problem!

So I just tried your example on my machine and got the expected output... I can't seem to replicate your bug!

I'm not using all the same library versions as you but I'm not sure why this would be inconsistent between environments...
`open_mfdataset()` is just using `glob.glob` [under the hood](https://github.com/pydata/xarray/blob/0811141e8f985a1f3b95ead92c3850cc74e160a5/xarray/backends/api.py#L711), I assume you've tried just globbing the wildcard in your environment? i.e. 

```python
from glob import glob
print(glob('./test_output_*.nc'))
```

**Comment by sridge** [comment]
Oof this is embarassing, there's no bug here! When I was coding up the test I wrote that last file as "test_output_3.nc", and then forgot it was in that directory. Turns out the original code that motivated me to submit this issue wasn't working because of a filename. Lesson learned, using wildcards can be risky
