### ISSUE TITLE
`xr.open_dataset` with `pydapdatastore` raises `too many indices for array` error

### ISSUE THREAD

**Issue by cocoaaa** [pydata/xarray#2993]
Hi, 
I'm trying to use xarray.open_dataset() to open password-protected Opendap files. I was able to create a valid `pydap.cas session`and `xr.backends.PydapDataStore` object. However, when I pass them to `xr.open_dataset()` method, I get the `IndexError: too many indices for array
` error.  My dataset has a single time point.  I'm wondering if this may be related to this previous issue(#476).  Could you help me sort out this issue?  Thank you!

```python
# OpenDAP authroization
from netrc import netrc
username, _, pw = netrc().hosts['urs.earthdata.nasa.gov']

#OPENDAP client
from pydap.client import open_url
from pydap.cas.urs import setup_session

url = ('https://hydro1.gesdisc.eosdis.nasa.gov/opendap/hyrax/FLDAS/'
       'FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190401.001.nc')

session = setup_session(username, pw, check_url=url)
store = xr.backends.PydapDataStore.open(url, session=session)
ds = xr.open_dataset(store)
```
#### Problem description
![image](https://user-images.githubusercontent.com/8037983/58441113-13f74c80-8094-11e9-9166-626ed4bc8e08.png)

---
### Update: 
On the other hand, I was able to read in the data using the `store.get_variable()` method directly, but no coordinate metadata are read.
![image](https://user-images.githubusercontent.com/8037983/58441479-566e5880-8097-11e9-802c-b2efa221f533.png)

Also, 
the `store` object's `dimension` attribute doesn't seem to exist:
![image](https://user-images.githubusercontent.com/8037983/58441837-3ee49f00-809a-11e9-9875-cc9751760e1e.png)

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1 | packaged by conda-forge | (default, Feb 18 2019, 01:42:00) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.11.6.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.12.1
pandas: 0.24.2
numpy: 1.16.3
scipy: 1.3.0
netCDF4: 1.5.1.2
pydap: installed
h5netcdf: None
h5py: 2.9.0
Nio: None
zarr: 2.3.1
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: 1.0.22
cfgrib: None
iris: None
bottleneck: None
dask: 1.2.2
distributed: 1.28.1
matplotlib: 3.1.0
cartopy: 0.17.0
seaborn: None
setuptools: 41.0.1
pip: 19.1
conda: None
pytest: 4.5.0
IPython: 7.1.1
sphinx: None

</details>

**Comment by shoyer** [comment]
Hmm. There very well may be an xarray bug here, but unfortunately I don't have a good way to test this without a username/password for site.

**Comment by cocoaaa** [comment]
I see, you can open a new account on EARTHDATA (by NASA) easily [here](https://urs.earthdata.nasa.gov/).

**Comment by mullenkamp** [comment]
I would also like to see if this issue could be looked at. I'm also trying to query the NASA server. This used to work in previous versions of xarray.
Thanks.

**Comment by mullenkamp** [comment]
After a little bit of testing, I've found out that setting decode_cf=False reads it in without an error.

**Comment by max-sixty** [comment]
Closing as stale / no MCVE
