### ISSUE TITLE
xr.Dataset.drop

### ISSUE THREAD

**Issue by markusritschel** [pydata/xarray#2994]
Currently, `drop` throws an error if one of the labels doesn't exist. It would be nice to have a parameter in the drop method for optionally ignoring errors like in the pandas.DataFrame.
From the pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html):

> errors : {‘ignore’, ‘raise’}, default ‘raise’
>     If ‘ignore’, suppress error and only existing labels are dropped.

**Comment by shoyer** [comment]
This sounds fine to me. Any interest in putting together a pull request? See http://xarray.pydata.org/en/stable/contributing.html for guidance.

(It might also make sense to put this in xarray's `drop_dims` as well, for consistency)
