### ISSUE TITLE
numpy.fromfunction equivalent?

### ISSUE THREAD

**Issue by Georacer** [pydata/xarray#2997]
Hello everyone!

I want to evaluate a multidimensional function over its coordinates for a given range.
For example, given coordinate names x, y, z, I want to evaluate f(x,y,z) for all coordinate triplets.

Currently, I am using numpy's `fromfunction` to do this, albeit awkwardly:
Since `fromfunction` provides integer index coordinates and also requires vectorized functions, I use something like:
```python
fl_env = np.fromfunction(  # Function must support vector inputs
        np.vectorize(build_fe_element, excluded=('axes_list', 'trimmer')), fl_env_dimension, 
        axes_list=axes_list, trimmer=trimmer)
```
where:
**axes_list**: is a list of lists with all the axes ticks values
**trimmer**: is a parameter to my custom function
**build_fe_element**: is the function I wish to run
**fl_env_dimension**: is the argument to `fromfunction` which tells it the dimensions over which to iterate

Does `xarray` support something similar, but with direct access to the coordinate values? I haven't been able to find anything similar.

Thanks in advance,
George

**Comment by shoyer** [comment]
@jcmgray's xyzpy solves this problem pretty well: https://xyzpy.readthedocs.io/en/latest/generate.html

We could consider putting a version of this xarray itself, but as you tell from xyzpy there are a number of overlapping use-cases, so this feature is actually complex. For now, it might make sense to just add an example to the docs (somewhere on the "Computation" page) of how to use xyzpy.

If we *did* want to add something like this to xarray, for parallel computing I would want to use dask (for consistency and composability). But then there are some messy issues, like how (if at all) we try to figure out what the variables/coordinates on a result Dataset should look like, if we are computing the entire Dataset in a lazy fashion.

**Comment by Georacer** [comment]
Okay. I'm not familiar enough with xarray's goals or how broadcasting works on numpy, so I won't push this.
I'm happy to construct it manually through bare numpy, where I provide the axes coordinate lists as arguments to a constructor function and let numpy.fromfunction produce the array.
Then, I pass this ndarray to xarray.

This issue was more of a question. Consider this closed.

**Comment by dpole** [comment]
> If we _did_ want to add something like this to xarray, for parallel computing I would want to use dask (for consistency and composability). But then there are some messy issues, like how (if at all) we try to figure out what the variables/coordinates on a result Dataset should look like, if we are computing the entire Dataset in a lazy fashion.

Just to let you know, I found this page while facing exactly this case-of-use
