### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by TomekTrzeciak** [pydata/xarray#2998]
https://github.com/pydata/xarray/releases marks v0.11.2 as the latest release, rather than v0.12.1. Is this intended?

**Comment by max-sixty** [comment]
Good spot @TomekTrzeciak 

That's not intended. 0.12.1 is at least [tagged](https://github.com/pydata/xarray/releases/tag/v0.12.1). Anyone know why GH doesn't treat it as a release?

**Comment by TomekTrzeciak** [comment]
@max-sixty, you can see 0.12.1 under releases section by clicking 'show newer tags', but 0.11.2 is still marked as the latest. I suspect it's down to annotated vs. lightweight tags and how github interprets them. It seems like annotated tags are preferred for releases.

**Comment by dcherian** [comment]
It appears that you can mark a tag as "release" on this page: https://github.com/pydata/xarray/tags . Since we missed a few tags, I don't know if we should move directly to 0.12.1 or mark the intermediate tags as releases too.

**Comment by max-sixty** [comment]
I'll do it for 0.12.1 so at least the latest is correct - any objections? (will do it this eve EST)

**Comment by max-sixty** [comment]
I think we need to ensure we do this step in future: https://github.com/pydata/xarray/blob/master/HOW_TO_RELEASE#L40

Closing the issue for now; thanks posting it @TomekTrzeciak

**Comment by max-sixty** [comment]
FYI I just did this for 0.12.3, which didn't show a 'release' on GH

**Comment by shoyer** [comment]
Hmm.. I wonder if we can just tell GitHub somehow to automatically treat tags as releases. It's a little annoying to have to do it separately.

**Comment by max-sixty** [comment]
I do wince a bit reading the full checklist - could we write a script to do most of this? I'm happy to help.

Are there any projects that do this well? e.g. a script with `release_script.py --version=0.12.4`

Someone mentioned Hypothesis, which[ releases on every merge to master ](https://github.com/HypothesisWorks/hypothesis/blob/23b3a50d36d93ea31c1a2220f065e3e4e77af1b9/hypothesis-python/docs/development.rst#release-policy)- though I wonder whether it makes merging to master more 'expensive'.
