### ISSUE TITLE
median on dask arrays

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#2999]
Dask has updated it's percentile, quantile implementation: https://github.com/dask/dask/pull/4677

Can we now update our median method to work with dask arrays?

**Comment by carolinarias** [comment]
Is anyone working on adding the median method?

**Comment by shoyer** [comment]
Yes, we could do this as long as we’re careful to default to the new algorithms. See also https://github.com/pydata/xarray/issues/1524#issuecomment-514002753

**Comment by stsievert** [comment]
I have a median method over in https://github.com/dask/dask/pull/3819
