### ISSUE TITLE
plot.pcolormesh fails with shading='gouraud'

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#3002]
`xarray.plot.pcolormesh()` fails when you pass the `matplotlib.pyplot.pcolormesh()` keyword argument `shading='gouraud'` to it.

#### Code Sample, a copy-pastable example if possible

```python
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

lon, lat = np.meshgrid(np.linspace(-20, 20, 5), np.linspace(0, 30, 4))
lon += lat/10
lat += lon/10

da = xr.DataArray(np.arange(20).reshape(4, 5), dims=['y', 'x'],
                  coords = {'lat': (('y', 'x'), lat),
                            'lon': (('y', 'x'), lon)})

da.plot.pcolormesh('lon', 'lat', shading='gouraud')
plt.show()
```

#### Problem description

This gives an error:

```
Traceback (most recent call last):
  File "mwe.py", line 17, in <module>
    da.plot.pcolormesh('lon', 'lat', shading='gouraud')
  File "/home/tegn500/Documents/Work/Code/xarray/xarray/plot/plot.py", line 721, in plotmethod
    return newplotfunc(**allargs)
  File "/home/tegn500/Documents/Work/Code/xarray/xarray/plot/plot.py", line 662, in newplotfunc
    **kwargs)
  File "/home/tegn500/Documents/Work/Code/xarray/xarray/plot/plot.py", line 864, in pcolormesh
    primitive = ax.pcolormesh(x, y, z, **kwargs)
  File "/home/tegn500/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/__init__.py", line 1805, in inner
    return func(ax, *args, **kwargs)
  File "/home/tegn500/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5971, in pcolormesh
    X, Y, C = self._pcolorargs('pcolormesh', *args, allmatch=allmatch)
  File "/home/tegn500/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5559, in _pcolorargs
    C.shape, Nx, Ny, funcname))
TypeError: Dimensions of C (4, 5) are incompatible with X (6) and/or Y (5); see help(pcolormesh)
```

#### Expected Output

This should give almost the same image as in the documentation, just with smoother shading:

![Figure_1](https://user-images.githubusercontent.com/35968931/59049474-f68a6580-887f-11e9-83db-697c38acdf5e.png)

**Comment by dcherian** [comment]
I found this on googling: https://github.com/matplotlib/matplotlib/issues/8422

**Comment by TomNicholas** [comment]
Oh thanks @dcherian ! 

That's confusing because this works:

```python
plt.pcolormesh(da['lon'].values, da['lat'].values, da.values, shading='gouraud')
```

but it looks like matplotlib is the problem, I'll close this.

**Comment by dcherian** [comment]
This might be an `infer_interval_breaks` issue?

**Comment by TomNicholas** [comment]
I tried
```python
da.plot.pcolormesh('lon', 'lat', shading='gouraud', infer_intervals=True)
```
but got the same error unfortunately.

**Comment by johnomotani** [comment]
I had the same problem. I found that
```
da.plot.pcolormesh('lon', 'lat', shading='gouraud', infer_intervals=False)
```
does work. Would be nice if `shading='gouraud'` worked by default though.

I guess the problem is that 'gouraud' needs the coordinate positions at the grid points, and I assume `infer_intervals=True` is creating coordinate values at the grid-cell corners (so an n x m DataArray is plotted using coordinates with lengh (n+1) and (m+1). I haven't looked into what `infer_intervals` actually does though. Would it be safe to just turn it off if `shading='gouraud'` is used?

**Comment by FilipeFcp** [comment]
Oh... I saw this comment, but I tried with `infer_interval = True` not `False`. Yes, it works with `False`.

I think we can pass the `shading` argument trough - `plot_field` -> `plot_field_monitor_data` -> `plot_scalar_array` -> `field_data.plot`. Or create a `**args` in `plot_scalar_array` and input it into `field_data.plot`.
