### ISSUE TITLE
<Xarray error with basic function. What am I missing?

### ISSUE THREAD

**Issue by mpkwright** [pydata/xarray#3003]
def var_loc_series(data, variable):
    ds = data
    print(ds)
    clim_var = ds[str(variable)]
    print(clim_var) 

This is throwing a KeyError: '<xarray' error. I assume the solution is simple, but doing all of the exact same things outside of the function gives no errors. Help?

"Data" is a merged Xarray of 3 NetCDF datasets, which works perfectly fine outside of this function.

**Comment by max-sixty** [comment]
Hi @mpkwright - as per the issue template, we'd need a reproducible example in order to look at this further

**Comment by max-sixty** [comment]
Closing but please reopen if you have a reproducible example. SO is also good for user questions.
