### ISSUE TITLE
Assigning values to a subset of a dataset

### ISSUE THREAD

**Issue by AdrianSosic** [pydata/xarray#3015]
Hi, can somebody tell me what is the "correct" way to manipulate a subset of the data contained in a Dataset? 

Consider the following example:
```
import numpy as np
import xarray as xr

shape = (3, 2)
da1 = xr.DataArray(np.zeros(shape), dims=('x', 'y'), coords=dict(x=[1, 2, 3], y=[4, 5]), name='var1')
da2 = xr.DataArray(np.zeros(shape), dims=('x', 'y'), coords=dict(x=[1, 2, 3], y=[4, 5]), name='var2')
```

I can easily change the value of variable 1 at a given coordinate in the first DataArray using the following syntax:
```
da1.loc[dict(x=1, y=4)] = 1
```

However, if I merge both DataArrays into a single Dataset and want to change both variables at the same time, there seems to be no straightforward solution:
```
ds = xr.merge([da1, da2])
ds.loc[dict(x=1, y=4)] =  ... <-- what to write here?
```

The only solution I could come up with is to modify the two values separately, but this is neither very elegant nor scales with the number of variables:
```
ds['var1'].loc[dict(x=1, y=4)] = 2
ds['var2'].loc[dict(x=1, y=4)] = 3
```

All I could find in the docs about this issue is:
> Using indexing to assign values to a subset of dataset (e.g., ds[dict(space=0)] = 1) is not yet supported.

If not by indexing, what other (more compact) way exists? A potential solution might be to create a separate Dataset and then use the `update` method, but this seems overly complicated, too.

**Comment by shoyer** [comment]
One easy work around is to loop over the variables in a Dataset, e.g.,
```
for da in ds.values():
    da.loc[dict(x=1, y=3)] = 1
```
It's a little ugly but it works.

I don't think there's a more compact way to do this in general. In some cases the `where()` function/method can be a good option, e.g., `ds.where((ds.x == 1) & (ds.y == 4), 1)`.

"not yet supported" basically means that there's no reason why it isn't supported, other than that nobody has bothered to implement it yet. Xarray tends to get new features when users implement them :).

**Comment by AdrianSosic** [comment]
Thanks for the quick reply! I really like the xarray package and hope that someone will add this functionality in the future since it would significantly improve the usability in certain situations. I am unfortunately not yet experienced enough with the package to take care of it myself - perhaps at a later point in time... For the time being, I will therefore stick with the above solutions ;)
