### ISSUE TITLE
Add example for multi-dimensional coordinate regridding using xESMF to documentation

### ISSUE THREAD

**Issue by jaard** [pydata/xarray#3021]
I was happy to discover recently that 1-D interpolation on dimension coordinates is now implemented in xarray. This functionality is well illustrated in the documentation (http://xarray.pydata.org/en/stable/interpolation.html).

Regridding of data on multi-dimensional coordinates, however, is still an open problem (see https://github.com/pydata/xarray/issues/486, https://github.com/pydata/xarray/issues/1822 and also xgcm/xgcm#68). There appears to be a way of performing this operation using xESMF instead, which is not included in either the xESMF or the xarray documentation. I haven't figured it out yet myself, but the comments on the issues above suggest to me that it's possible.

The kind of advanced regridding operation is a fairly common use-case, i.e. for interpolating ocean model data from sigma-levels to z-levels. Therefore, as long as this functionality is not handled by xarray directly, I think there should be an example of or a reference to a possible workaround using xESMF in the xarray documentation.

**Comment by max-sixty** [comment]
As part of keeping our issue count <1000, closing as unlikely to inspire change, please reopen if anyone disagrees

In this case, contributions welcome!
