### ISSUE TITLE
MODIS(MYD06_L2) file concatenation using xarray

### ISSUE THREAD

**Issue by redwanwalid** [pydata/xarray#3031]
I try to open multiple MODIS files (MYD06_L2) using xarray (xr.open_mfdataset).

I can open a single file or may be some files but i am not able to open many files or one day file as they have different dimensions.

d06 = xr.open_mfdataset(M06_2040, concat_dim= 'None', parallel=True)
['Cloud_Mask_1km'][:,:,:,0].values
Here M06_2040 is the directory of the files

I end up with the following error:

ValueError: arguments without labels along dimension 'Cell_Along_Swath_1km:mod06' cannot be aligned because they have different dimension sizes: {2040, 2030}

MYD06_L2.A2016152.0000.061.2018059082330.hdf
MYD06_L2.A2016152.0005.061.2018059081943.hdf

**Comment by max-sixty** [comment]
Do you have a reproducible example?

**Comment by TomNicholas** [comment]
@redwanwalid if you can't give a reproducible example, then can you please open each file individually and print them so we can see what the structure of your data is? i.e. just

```python
ds1 = xr.open_dataset(filepath1)
ds2 = xr.open_dataset(filepath2)
print(ds1)
print(ds2)
```
