### ISSUE TITLE
Feature Request: Additional parallel IO format support: ASDF, ph5, or similar

### ISSUE THREAD

**Issue by k-a-mendoza** [pydata/xarray#3035]
#### Problem description

Currently, Xarray supports reading/writing a variety of dataformats. Geoscience data in particular is a stated use-case domain. However, in the documentation, it seems as though geoscience mostly refers to hydrologic and atmospheric data. 

It would be very useful to more domains of geoscience if xarray also supported read/writes to formats encountered regularly in geophysics, either something like [ph5](https://github.com/PIC-IRIS/PH5/), [ASDF](http://seismicdata.github.io/pyasdf/index.html), or the like. Already projects like [obsplus](https://github.com/niosh-mining/obsplus) deliver some xarray->seismic formats -> xarray functionality, but have yet to venture into the parallel read/write operations that make xarray so attractive. 

I am not sure what the overhead would be in adapting xarray to use these existing packages, or in creating common interfaces for use with these packages.

**Comment by TomNicholas** [comment]
It should be possible to implement a new backend in xarray now - we've already done it for multiple file formats.

However, I suspect that if we completed the [project](https://github.com/pydata/xarray/projects/3) to provide a [Flexible API for Storage Backends](https://github.com/pydata/xarray/issues/1970), then the path to this would become simpler. At the moment each new storage format has to be special-cased within xarray code itself (e.g. zarr), but we want to get to a position where that I/O responsibility is delegated out to other libraries, probably via an [entrypoint](https://github.com/pydata/xarray/pull/3166). Then it would be much easier (and quicker) to develop the necessary interfaces for the formats you mention.

**Comment by dcherian** [comment]
See https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html and https://tutorial.xarray.dev/advanced/backends/backends.html for adding a new backend
