### ISSUE TITLE
Pipe Operator?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#3050]
I realize this is a topic primed for bike-shedding, so I've held off suggesting, but here goes...

Is there any interest in a pipe operator to make xarray syntax easier?
Our internal code has much code like:

```python

delinq_c = (
    base_ds['delinq_comp_array']
    # lots of `pipe` lines!
    .pipe(lambda x: x - base_ds['delinq_comp_array'].mean('fsym_id'))
    .pipe(lambda x: x / delinq_diff)
    .pipe(lambda x: x * 2)
)

```

...with lots of new lines starting with `.pipe`. The [fluent](https://en.wikipedia.org/wiki/Fluent_interface) code is great for sequences of logic, but the requirement to have `.pipe` on each line adds verbosity.

The addition of a pipe operator would allow for:

```python

delinq_c = (
    base_ds['delinq_comp_array']
    >> lambda x: x - base_ds['delinq_comp_array'].mean('fsym_id')
    >> lambda x: x / delinq_diff
    >> lambda x: x * 2
)

```

This requires (ab)using an existing python operator, such as `>>` (bitshift operator) or `|` (or operator). Airflow uses `>>`, Beam (and bash) use `|`. While xarray doesn't allow either to be used, other libraries might incorrectly assume their presence implies they work consistently with those definitions.

Python has explicitly not added this, nor reduced the character count of `lambda x:`, so this would be somewhat a dissent from their standards, and introduce potential confusion to completely new xarray users.

I remember some discussions at pandas on similar topics. I can't find them all, but here's an issue re adding the `X` term https://github.com/pandas-dev/pandas/issues/13133

**Comment by shoyer** [comment]
I also use `.pipe` very heavily in my own code, so I appreciate the motivation here. That said, I've been pretty happy with writing `.pipe()`.

Both `>>` and `|` are already operators in xarray/numpy, which complicates using them for another purpose. `>>` for bitshift may be unusual, but `|` is definitely widely used for elementwise `or`.
