### ISSUE TITLE
Remove remaining usage of pandas Panel

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/xarray#3057]
There is still some usage of `pd.Panel` (just accessing the name in the pandas namespace for isinstance check), eg:

https://github.com/pydata/xarray/blob/a78e0f6ce7c0cc48f746a122c79f1bcf903efd51/xarray/core/merge.py#L18

We are currently removing Panel from pandas (https://github.com/pandas-dev/pandas/pull/27101), so that breaks xarray (and statsmodels). For that reason, we are going to keep an empty class so that the above use case doesn't directly break. But it would still be good to remove that usage (or only add it for pandas versions below 0.25.0)

**Comment by shoyer** [comment]
Thanks for the heads up! This will be fixed in https://github.com/pydata/xarray/pull/3058
