### ISSUE TITLE
Method chaining on magic methods?

### ISSUE THREAD

**Issue by hsharrison** [pydata/xarray#3081]
Apologies if this has been discussed, I couldn't find it.

In pandas and xarray I prefer a method-chaining style, and with pandas this is now very well supported. However, xarray is missing a number of simple methods. I often find myself having to use magic methods like `__eq__` directly to avoid breaking the chain. Is there any reason not to do

    class DataArray:
        ...
        eq = __eq__
        gt = __gt__
        ge = __ge__
        lt = __lt__
        le = __le__
        add = __add__
        subtract = __sub__
        multiply = __mul__
        divide = __div__
        pow = __pow__
        # etc.

Probably it is more complicated than this, but hopefully it communicates the idea.

**Comment by shoyer** [comment]
I usually use the `pipe` method with a `lambda` for this, e.g., `array.pipe(lambda x: x + 1)`.

I'm not entirely sure it's worth adding in dedicated methods into the DataArray namespace for this.

**Comment by hsharrison** [comment]
That's fair. If this hasn't come up before, it must not be bothering too many people. Maybe I'll write a `DataArray.op` accessor.
