### ISSUE TITLE
Codecov bot comments?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#3098]
ref https://github.com/pydata/xarray/pull/3090#issuecomment-510323490

Do we want the bot commenting on the PR, at least while the early checks are wrong? People can always click on `Details` in the Codecov check (e.g. https://codecov.io/gh/pydata/xarray/compare/8f0d9e5c9909c93a90306ed7cb5a80c1c2e1c97d...ab6960f623017afdc99c34bcbb69b402aea3f7d4/diff) to see a full report.

Happy to PR to disable, lmk

**Comment by shoyer** [comment]
I have one more config tweak that I want to try before removing the comment: https://github.com/pydata/xarray/pull/3122

**Comment by shoyer** [comment]
Yeah, that didn't work. Codecov still seems to be ignorant of the status of Azure checks, so let's turn the comment off.
