### ISSUE TITLE
Append to zarr redundant with mode='a'

### ISSUE THREAD

**Issue by davidbrochart** [pydata/xarray#3100]
When appending to a zarr store, we need to set `append_dim=dim_name` but also `mode='a'`. Any reason to also specify the writing mode? I think it should automatically be set to `'a'` if `append_dim is not None`.

**Comment by shoyer** [comment]
This sounds reasonable to me.

**Comment by davidbrochart** [comment]
@shikharsg, @jendrikjoe and @rabernat might be interested too.

**Comment by shikharsg** [comment]
Looks good to me
