### ISSUE TITLE
The name of the conda environment in the contributing guide is generic

### ISSUE THREAD

**Issue by zdgriffith** [pydata/xarray#3107]
In the [contributing guide](http://xarray.pydata.org/en/stable/contributing.html#creating-a-python-environment), you are instructed to make an environment `test_env`:

```
# Create and activate the build environment
conda env create -f ci/requirements/py36.yml
conda activate test_env

# or with older versions of Anaconda:
source activate test_env

# Build and install xarray
pip install -e . 
```

I think having the name be `xarray_test_env` would be clearer for people new to working with conda environments and using multiple projects.

**Comment by rabernat** [comment]
I am 👍 on this. I often run into conda env conflicts related to this generic name.

PR welcome if you would like to change it. You will probable need to edit our CI as well.

https://github.com/pydata/xarray/blob/master/ci/azure/install.yml#L31-L34

**Comment by mmartini-usgs** [comment]
seconded the name xarray_test_env since you do use xarray_docs for the docs environment

**Comment by zdgriffith** [comment]
@mmartini-usgs good point - it looks like `xarray-docs` so maybe just `xarray-tests`?  I can definitely make a PR.
