### ISSUE TITLE
In the contribution instructions, the py36.yml fails to set up

### ISSUE THREAD

**Issue by mmartini-usgs** [pydata/xarray#3109]
#### Code Sample, a copy-pastable example if possible
conda env create -f ci/requirements/py36.yml
#### Problem description
In the contribution instructions, the py36.yml fails to set up, so the test environment does nto get created

#### Expected Output
A test environment

#### Output of ``xr.show_versions()``
Environment fails to build,  cannot be resolved.

<details>

</details>
 The fix is to change 

`conda env create -f ci/requirements/py36.yml`

to

`conda env create -f ci/requirements/py37.yml`

on this page:  http://xarray.pydata.org/en/latest/contributing.html

**Comment by shoyer** [comment]
Hi @mmartini-usgs -- thanks for the report here! What platform are you on? We use this environment in our continuous integration tests for Linux and Mac OS X, so it should work at least on those platforms.

Ideally we would switch the recommendation in our contributor docs to a setup that we are sure works on all of Windows/Mac/Linux, though. Or at least we could point to a different environment in our docs for Windows users.

Right now we use a different environment for Windows tests, though to be honest I'm not entirely sure why! Likely there are some optional dependencies not available on Windows.
https://github.com/pydata/xarray/blob/8da3f67ea583e0588291162067229b2f3ce2993e/azure-pipelines.yml#L43

**Comment by mmartini-usgs** [comment]
Hello @shoyer,
I hit this following your most excellent "how to contribute" page during the SciPy sprints, and it turns out to be a function of my local setup - so isn't really an issue.  Others in the room did not have trouble with it.  @rabernat explained the situation.  So perhaps close this and leave the explanation for others that might hit it.  The py37.yml build worked for me on Windows.
