### ISSUE TITLE
Allow GRIB data as an example dataset

### ISSUE THREAD

**Issue by zbruick** [pydata/xarray#3118]
Need to add support for other files than netCDF in `load_dataset`, namely for GRIB data, which a PR will be coming to fix shortly.

**Comment by zbruick** [comment]
And I would think support for `.zarr` and `.hdf` files may also be useful at some point down the road. While there are many ugly ways to do this, the cleanest way that @StephanSiemen and myself have thought of is to make `load_dataset` as general as possible, which would break the current examples by requiring the full file name, including the extension in `load_dataset`. Thoughts on this? @rabernat

**Comment by rabernat** [comment]
I know how to do this and will soon submit a PR to fix it.

**Comment by rabernat** [comment]
> make `load_dataset` as general as possible, which would break the current examples by requiring the full file name, including the extension in `load_dataset`

The solution is to check whether `name` has an extension or not. If no extension, then we append `.nc`.

**Comment by dcherian** [comment]
Closed by #3121
