### ISSUE TITLE
selecting only october to march from monthly data using xarray

### ISSUE THREAD

**Issue by mada0007** [pydata/xarray#3124]
I have array of monthy data. I want to select monthly values starting from october to march like this 
my data = starts from [1950-01,1950-02,1950-03,  ...]

this is what I want 
selection = [1950-10, 1950-11, 1950-12, 1960-1,1960-2, 1960-3, ...] # notice it continues to 1960 

thanks

**Comment by dcherian** [comment]
You want something like `data.where(data.time.dt.month.isin([1,2,3,10,11,12]), drop=True)` I think

**Comment by mada0007** [comment]
Hi yes except that selected series start are ordered from 1,2,3,10,11,12, 1, 2, 3, 10,11, 12 in that order. 
what I really want is 10,11,12, 1,2,3 10,11,12,1,2,3  the first 1,2,3 in the data must be igored so from 10,11,12 the next 1,2,3 should start from the following year

Thanks

**Comment by spencerkclark** [comment]
I normally use something like this, which results in the equivalent of @dcherian's suggestion, but is a bit more direct:
```python
data = data.sel(time=data.time.dt.month.isin([1, 2, 3, 10, 11, 12]))
```
@mada0007 you can then subset in time to truncate the time series further afterwards:
```python
result = data.sel(time=slice('1950-04', '1960-04'))
```

**Comment by dcherian** [comment]
Nice! I should use sel more

**Comment by mada0007** [comment]
Hi, the problem here is that I have multiple netcd files and the dats vary accros time. 

is there any other way to do this ?

**Comment by dcherian** [comment]
If you use `data = xr.open_mfdataset(...)`, the above solution will work

**Comment by mada0007** [comment]
Thanks to all, it works!

**Comment by NayanTalmale** [comment]
@dcherian  and @mada0007 
Could u plz tell me that how to join that data after selecting Oct-March.
Basically, I want to say whenever I am plotting a time series of this selected monthly data. My time time series is not continuous.
Kindly plz let me know.  I am attaching a plot for the reference.
[Example.pdf](https://github.com/pydata/xarray/files/6815777/Example.pdf)

**Comment by max-sixty** [comment]
@NayanTalmale  please open a discussion with a reproducible example
