### ISSUE TITLE
Plotting with 2d coordinates, error in transposed coordinate

### ISSUE THREAD

**Issue by hetland** [pydata/xarray#3138]
This is similar to issue #1503, but specifically deals with requiring the correct order of dimensions for plotting 2d coordinates. An example of the issue is:

```
# create an example dataset
dates = pd.date_range('2000-01-01', '2001-12-31', name='time')
times = dates - dates[0]

x = np.linspace(0, 10, 101)

h = np.linspace(3, 7, 101)
s = np.linspace(0, 1, 51)
z = s[:, np.newaxis] * h[np.newaxis, :]

data = (np.sin(x) * np.cos(z)) * np.cos(np.asarray(times.days[:, np.newaxis, np.newaxis]))

# create an xarray dataset

ds = xr.Dataset({'data': (('time', 's', 'x'), data)}, 
                {'time':dates, 'x':x, 's':s, 'z':(('s', 'x'), z)})
ds.coords['zt'] = ds.z.transpose()
```
plotting with `z` and `zt` should give the same results, since the dimensions are clearly labeled and other than the order of the dimensions, they are exactly the same. 

This works:
```
ds.data[0].plot(x='x', y='z')
```

This does not:
```
ds.data[0].plot(x='x', y='zt')
```

Broadcasting, e.g., does not give a similar error. Specifically, this is true:
```
np.allclose((ds.data * ds.zt).values, (ds.data * ds.z).values)
```

**Comment by shoyer** [comment]
Thanks for the report.

I *think* should be relatively straightforward to fix, assuming that the underlying maptlotlib plotting functions handle 2D coordinates.

For reference, here's the full error traceback:
```
ValueError                                Traceback (most recent call last)
<ipython-input-6-8d3b2b196427> in <module>()
----> 1 ds.data[0].plot.pcolormesh(x='x', y='zt')

3 frames
/usr/local/lib/python3.6/dist-packages/xarray/plot/plot.py in plotmethod(_PlotMethods_obj, x, y, figsize, size, aspect, ax, row, col, col_wrap, xincrease, yincrease, add_colorbar, add_labels, vmin, vmax, cmap, colors, center, robust, extend, levels, infer_intervals, subplot_kws, cbar_ax, cbar_kwargs, xscale, yscale, xticks, yticks, xlim, ylim, norm, **kwargs)
    697         for arg in ['_PlotMethods_obj', 'newplotfunc', 'kwargs']:
    698             del allargs[arg]
--> 699         return newplotfunc(**allargs)
    700 
    701     # Add to class _PlotMethods

/usr/local/lib/python3.6/dist-packages/xarray/plot/plot.py in newplotfunc(darray, x, y, figsize, size, aspect, ax, row, col, col_wrap, xincrease, yincrease, add_colorbar, add_labels, vmin, vmax, cmap, center, robust, extend, levels, infer_intervals, colors, subplot_kws, cbar_ax, cbar_kwargs, xscale, yscale, xticks, yticks, xlim, ylim, norm, **kwargs)
    583         # check if we need to broadcast one dimension
    584         if xval.ndim < yval.ndim:
--> 585             xval = np.broadcast_to(xval, yval.shape)
    586 
    587         if yval.ndim < xval.ndim:

/usr/local/lib/python3.6/dist-packages/numpy/lib/stride_tricks.py in broadcast_to(array, shape, subok)
    180            [1, 2, 3]])
    181     """
--> 182     return _broadcast_to(array, shape, subok=subok, readonly=True)
    183 
    184 

/usr/local/lib/python3.6/dist-packages/numpy/lib/stride_tricks.py in _broadcast_to(array, shape, subok, readonly)
    127     it = np.nditer(
    128         (array,), flags=['multi_index', 'refs_ok', 'zerosize_ok'] + extras,
--> 129         op_flags=[op_flag], itershape=shape, order='C')
    130     with it:
    131         # never really has writebackifcopy semantics

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (101,) and requested shape (101,51)
```

**Comment by dcherian** [comment]
Thanks @hetland, good to see you here.

I think this is probably easy to fix by using `xr.broadcast` to broadcast things before extracting the numpy arrays. Can you send in a PR?

**Comment by hetland** [comment]
I posted an issue to hvplot.xarray (
https://github.com/pyviz/hvplot/issues/244) where hvplot does *not* do the
right thing. But matplotlib (and hence also xarray.plot) do the right thing.

On Wed, Jul 17, 2019 at 6:40 PM Deepak Cherian <notifications@github.com>
wrote:

> Thanks @hetland
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hetland&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=T-gqCqhnaasy1XvN-p7wEw&m=lYvy351ebI1zHRWmzq6wpEjUIodwAqOPjEHPdhrnt74&s=7y9VzsWhKiPnJtrkl28cE3aKOFnZn3A8y1m8aDlBbck&e=>,
> good to see you here.
>
> I think this is probably easy to fix by using xr.broadcast to broadcast
> things before extracting the numpy arrays. Can you send in a PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pydata_xarray_issues_3138-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAT2YFVIUFYCH6SJD6QFBO3P76UVRA5CNFSM4IESVD3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2G4PNQ-23issuecomment-2D512608182&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=T-gqCqhnaasy1XvN-p7wEw&m=lYvy351ebI1zHRWmzq6wpEjUIodwAqOPjEHPdhrnt74&s=ZMfEYrmiIqELTnEsLhdTmX84GQzpHrW3AcGCYix6pok&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAT2YFUEC7RTCML5UOPCBBLP76UVRANCNFSM4IESVD3A&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=T-gqCqhnaasy1XvN-p7wEw&m=lYvy351ebI1zHRWmzq6wpEjUIodwAqOPjEHPdhrnt74&s=qz9PhAwicJx-Z8yEFMVwM06TdQiAe0toEP2C6cUF2Yw&e=>
> .
>


-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob
