### ISSUE TITLE
Unable to run example for xarray.DataArray.to_unstacked_dataset

### ISSUE THREAD

**Issue by TalfanBarnie** [pydata/xarray#3148]
Hello,

When I try to run the example for 
[xarray.DataArray.to_unstacked_dataset](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.to_unstacked_dataset.html#xarray.DataArray.to_unstacked_dataset)

I get the error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/talfan/anaconda3/envs/to_unstacked/lib/python3.7/site-packages/xarray/core/dataset.py", line 2915, in to_stacked_array
    "dimensions {}.".format(dims)
ValueError: All variables in the dataset must contain the dimensions ('x',).

when running the line
`stacked = data.to_stacked_array("z", ['y'])`

This is my setup:

> pip freeze
certifi==2019.6.16
numpy==1.16.4
pandas==0.25.0
python-dateutil==2.8.0
pytz==2019.1
six==1.12.0
xarray==0.12.3+20.g9afe4d0c

Any idea what might be going wrong?

Many thanks for your help!

**Comment by shoyer** [comment]
There's a typo in the docstring example. It should be `data.to_stacked_array("z", ['x'])`.

**Comment by shoyer** [comment]
cc @nbren12

**Comment by nbren12** [comment]
Huh, it looks like that change in the API that happened in the last stages of the PR didn't make it into the example docs. I will try to submit a PR fixing that sometime soon.

**Comment by nbren12** [comment]
Actually, the docs seem correct: https://github.com/pydata/xarray/blob/8da3f67ea583e0588291162067229b2f3ce2993e/xarray/core/dataset.py#L2895

Am I missing something here?

**Comment by TalfanBarnie** [comment]
The correction works, many thanks. The incorrect version is still on http://xarray.pydata.org/en/stable/, maybe that needs to be updated somehow?

**Comment by nbren12** [comment]
Could you link the specific page that is wrong?

**Comment by TalfanBarnie** [comment]
It's here:

http://xarray.pydata.org/en/stable/generated/xarray.DataArray.to_unstacked_dataset.html#xarray.DataArray.to_unstacked_dataset

Under examples the line that reads:

 `stacked = data.to_stacked_array("z", ['y'])`

should read

`data.to_stacked_array("z", ['x'])`

Thanks for looking into it!

**Comment by nbren12** [comment]
Okay. it looks like the docstring for `to_unstacked_dataset` is in fact incorrect:

https://github.com/pydata/xarray/blob/77a31e56d221245ff7dc10041bf0ca34cab91897/xarray/core/dataarray.py#L1654

I will can submit a PR fixing that soon.

**Comment by keewis** [comment]
it looks like this should have been closed by #4408
