### ISSUE TITLE
da.interp() does not allow extrapolation

### ISSUE THREAD

**Issue by raspstephan** [pydata/xarray#3172]
I used `da.interp()` to interpolate from one vertical coordinate to another. The target coordinate has points that lie outside the source coordinate. `scipy.interpolate.interp1d()` extrapolates such points if `fill_value=None`. 

However, `da.interp()` sets such points to NaN even if `fill_value=None`. After some source code digging I found the following behavior in `ScipyInterpolator(BaseInterpolator)`: 

```python
...
        if fill_value is None and method == 'linear':
            fill_value = np.nan, np.nan
        elif fill_value is None:
            fill_value = np.nan

        self.f = interp1d(xi, yi, kind=self.method, fill_value=fill_value,
                          bounds_error=False, assume_sorted=assume_sorted,
                          copy=copy, **self.cons_kwargs)
```

Why does xarray not allow the user to extrapolate?

**Comment by dcherian** [comment]
According to https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html you need to set `fill_value='extrapolate'`?

**Comment by raspstephan** [comment]
Thanks, I looked at an old scipy version. This solved the problem.
