### ISSUE TITLE
type annotations make docs confusing

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3178]
The annotations make this signature basically unreadable to anyone not familiar with them. 

![image](https://user-images.githubusercontent.com/2448579/62378906-57a78000-b535-11e9-97ab-4c068fc58d1e.png)

Is there a way to hide them in the documentation? Or at least change formatting so it's clearer what the function arguments are?

**Comment by DocOtak** [comment]
Perhaps the [sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints) extension?

The docs suggest it will remove the types from the method signatures and put them in the in `:param:` parts. I haven't used or tested myself.

**Comment by dcherian** [comment]
Thanks @DocOtak. Are you interested in trying it out?

**Comment by DocOtak** [comment]
@dcherian sure, I'll try it right now with the xarray docs

**Comment by shoyer** [comment]
If we can't get that sphinx extension to work (I'm not sure if it will handle NumPy style docstrings), another option might to be define type aliases for the longer types, e.g., `data_vars: DataVars`. That would at least cut down on the noise.

**Comment by DocOtak** [comment]
So the plugin seems to "just works" in that it remove these data type annotation, it doesn't seem to put them anywhere. I can probably put the docs I built somewhere if you all want to look at them. Here is a screen shot of the "Dataset" class, first one is just the extension, second screenshot also has the napoleon extension enabled. Main difference is how the "parameters" appear.
<img width="738" alt="sphinx_dtype" src="https://user-images.githubusercontent.com/868027/62386026-72fd9580-b50b-11e9-9afd-f813da4e4ca7.png">
<img width="740" alt="sphinx_dtype_napoleon" src="https://user-images.githubusercontent.com/868027/62386036-7a24a380-b50b-11e9-8697-82024eb31259.png">

**Comment by dcherian** [comment]
Some research suggests we need to enable `sphinx.ext.napoleon` before  `autodoc-typehints` and it should move the type annotations to the docstring: https://stackoverflow.com/questions/49540656/how-to-automatically-add-parameter-types-in-sphinx-documentation

**Comment by dcherian** [comment]
Have you enabled `napoleon_use_param`? (https://stackoverflow.com/questions/49540656/how-to-automatically-add-parameter-types-in-sphinx-documentation)

> Add 'sphinx_autodoc_typehints' to the extensions list in conf.py after 'sphinx.ext.napoleon', and make sure you also add napoleon_use_param = True to conf.py.

**Comment by DocOtak** [comment]
So I think why it isn't putting the types anywhere in the docs is because they already exist (at least for this Dataset `__init__` that we are looking at).

The relevant part of the code in the extension appears to be this https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L333:L338

It's looking for `:param name:` and I think things with types are already `:param type name:` with napoleon enabled, so it doesn't find anything to replace. Without napoleon enabled, the `:param name:` fields are not present since it is "raw" numpy doc style.

**Comment by DocOtak** [comment]
Suspicions confirmed. I removed the type parts in the docstrings. The attached is the result which I think is *way* less readable:
<img width="733" alt="sphinx_dtype_napoleon2" src="https://user-images.githubusercontent.com/868027/62388251-a511f600-b511-11e9-9487-cba01c93c178.png">

**Comment by shoyer** [comment]
I would be OK with stripping type hints entirely. Our long type annotations are mostly useful for tooling. The short annotations from our numpy-style docstrings are definitely more readable for humans.

**Comment by dcherian** [comment]
+1 I like the style with Napoleon enabled. It even fixes #3056.

**Comment by shoyer** [comment]
Yes, this is great! Please send a PR when you're ready :)

**Comment by DocOtak** [comment]
So I made a PR for just removing the type annotations, turns out it is built in to autodoc. Enabling napoleon seems to be less "clean". While it doesn't actually conflict with `numpydoc` it does appear to "compete" with it. It only really seemed to affect the autowrapped ufunc documentation. I'm going to do a separate "enable napoleon" PR

**Comment by DocOtak** [comment]
See #3180 for the `napoleon` enabling PR.

**Comment by dcherian** [comment]
Looks like this isn't fully fixed

![image](https://user-images.githubusercontent.com/2448579/69183043-18b03100-0b0a-11ea-91b6-84dfb673a7f6.png)

**Comment by DocOtak** [comment]
Any recollection as to if these ever worked as expected? Looks like between landing this change and doing the 0.14 release, the sphinx version bumped from 2.1.2 to 2.2.0 which included some changes to autodoc... This PR might be of interest https://github.com/sphinx-doc/sphinx/pull/6592 but it is not immediately obvious to me how/if this could have broken things.

**Comment by crusaderky** [comment]
I tried using sphinx-autodoc-typehints in my own project but I'm getting a gazillion of errors.
TypeVars don't work, Optional doesn't work, Literal doesn't work, intersphinx doesn't work (https://github.com/agronholm/sphinx-autodoc-typehints/issues/119), possibly more (the error log is just too long). :(
