### ISSUE TITLE
RTD build failing

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3182]
Looks like our RTD builds have been failing for the last 3 days.

```
The HTML pages are in _build/html.
/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.7/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.7/site-packages/sphinx/application.py", line 380, in build
    self.events.emit('build-finished', None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 313, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Examples expected to fail, but not failing:
Please remove these examples from
sphinx_gallery_conf['expected_failing_examples']
/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/latest/doc/gallery/plot_rasterio.pyin your conf.py file
/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/latest/doc/gallery/plot_rasterio_rgb.py
-------------------------------------------------------------------------------

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 313, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Examples expected to fail, but not failing:
Please remove these examples from
sphinx_gallery_conf['expected_failing_examples']
/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/latest/doc/gallery/plot_rasterio.pyin your conf.py file
/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/latest/doc/gallery/plot_rasterio_rgb.py
-------------------------------------------------------------------------------
```

**Comment by DocOtak** [comment]
More information here: https://sphinx-gallery.github.io/configuration.html#don-t-fail-the-build-on-exit

**Comment by DocOtak** [comment]
Has anyone with access tried just wiping the env? https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

Specifically, when I was testing locally my rasterio was not importing, but at some point in the past, had run successfully. I was able to fix by removing the `auto_gallery` dir from the docs dir.

**Comment by DocOtak** [comment]
So it looks more like a conda channel mixing problem to me now. Perhaps just bumping rasterio to 1.0.24?

**Comment by max-sixty** [comment]
Thanks @DocOtak, how would you feel about bumping rasterio in a PR? Would be great if we can get this working again.

**Comment by DocOtak** [comment]
@max-sixty I made a PR which bumps rasterio.

Something else to consider is enabling channel_priority strict in the conda environment. When I had enabled that in local testing, the conda solver was unable to create the requested environment. It seemed the requested rasterio version was no longer on conda-forge (though maybe under the cf201901 label?). Though if I recall, there was also a mismatch between the requested pandas and python versions when strict was enabled.

It seems the trade off is where you want the failure to occur, either in making the environment in conda, or when some package stops working.

**Comment by DocOtak** [comment]
Seems the docs are still failing to build, except this time it is being killed due to too much resource consumption.

**Comment by dcherian** [comment]
All green! and the docstrings look great!

Thanks @DocOtak :clap: :clap:

![image](https://user-images.githubusercontent.com/2448579/62580574-f6b1dc00-b895-11e9-9876-6a7a2e9befcf.png)

**Comment by max-sixty** [comment]
Thanks a lot @DocOtak !

**Comment by shoyer** [comment]
Thanks indeed!
