### ISSUE TITLE
template docstrings for join, data_vars, coords etc.

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3214]
What do you think about using templates to construct docstrings for `align`, `concat`, `open_mfdataset`, `merge`, `combine_nested` etc. These share a lot of the same kwargs and it's a little painful to find all the places that need to have updated docstrings.

**Comment by max-sixty** [comment]
I'm -0 on overhauling. I find when _developing_, looking up a method and seeing the docstring is v helpful, and the quasi-metaprogramming of templates makes that more difficult. (I find I need to start `ipython` and look up the docstring with `method?`)

But we should balance that against the annoyance and error is repetition. e.g. here, the compat argument has two slightly different descriptions (both correct, but not efficient to write it twice):
https://github.com/pydata/xarray/blob/master/xarray/core/dataset.py#L3393
https://github.com/pydata/xarray/blob/master/xarray/core/merge.py#L522

To the extent we can reduce the number of methods, (e.g. use the same method for DataArray & Dataset, referring to an `'object'` in the docstring), that's even better. But not always possible.

If there's a severe case we could start on and assess the overlap, I'm +0.2

**Comment by dcherian** [comment]
> the quasi-metaprogramming of templates makes that more difficult. 

:+1:
