### ISSUE TITLE
merge_asof functionality

### ISSUE THREAD

**Issue by fjanoos** [pydata/xarray#3218]
Would it be possible to add some functionality to xarray merge that mimics pandas merge_asof ? This would be very useful when aligning timeseries dataarrays where the two arrays are misaligned.

Thanks.

**Comment by max-sixty** [comment]
I think this would be good. It would need to be implemented outside of python (cython / numba / etc) given the performance requirements. I'm not sure whether we could borrow the pandas functionality and apply it to multi-dimensional arrays.

Assuming we'd need to write our own, xarray doesn't have any cython dependencies, so I think it would be best in a separate and optional package. These could go in numbagg. 
It's non-trivial work, so someone would have to have a strong need for it.

**Comment by shoyer** [comment]
How is merge_asof different from using reindex with method='pad'?

**Comment by fjanoos** [comment]
Reindexing can cause a massive and unnecessary inflation in the size of a
dataset.

Assume for example we have two datasets sampled daily going over multiple
years - except that the time of day at which they are sampled is different
and varying day to day.

Trying to line these up with reindex + forward fill would require
upsampling the right dataframe to the least common multiple of their
sampling periods which in the limit could be nanoseconds.

**Comment by fjanoos** [comment]
As of now, a simple workaround would be to do these tasks in pandas and
switch back and forth.

A couple of years ago - before pandas had pd.merge_asof - I had implemented
a version of this logic in numba when working with numpy arrays.
It was blazingly fast - and if there is interest I can try to dig it up ? I
would need some help  making it work for xarrays and publishing it into the
master branch.

**Comment by max-sixty** [comment]
> How is merge_asof different from using reindex with method='pad'?

Yes this is right! Mea culpa. We can already use the pandas reindexing for the 1D case (which should cover your case @fjanoos ?)

@fjanoos can you confirm this is what you're looking for?

```python


In [4]: da=xr.DataArray(list('abcdefghil'), dims=['x'],coords=dict(x=range(10)))

In [8]: da.reindex(x=[0,2.5,2.6,2.7,5,6.2], method='nearest')
Out[8]:
<xarray.DataArray (x: 6)>
array(['a', 'd', 'd', 'd', 'f', 'g'], dtype='<U1')
Coordinates:
  * x        (x) float64 0.0 2.5 2.6 2.7 5.0 6.2

```

**Comment by fjanoos** [comment]
That looks correct. Let me try and revert back to you
