### ISSUE TITLE
Minimum versions for optional libraries

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#3222]
In CI there are:

- tests for all the latest versions of all libraries, mandatory and optional (py36, py37, py37-windows)
- tests for the minimum versions of the mandatory libraries only (py35-min)

There are no tests for legacy versions of the optional libraries.

Today I tried downgrading dask in the py37 environment to dask=1.1.2, which is 6 months old...

**...it's a bloodbath.** 383 errors of the most diverse kind.

In the codebase I found mentions to much older minimum versions: installing.rst mentions dask >=0.16.1, and Dataset.chunk() even asks for dask>=0.9.

It think we should add CI tests for old versions of the optional dependencies.
What policy should we adopt when we find an incompatibility? How old a library should be not to bother fixing bugs and just require a newer version? I personally would go for an aggressive 6 months worth' of backwards compatibility; less if the time it takes to fix the issues is excessive.
The tests should run on py36 because py35 builds are becoming very scarce in anaconda.

This has the outlook of being an exercise in extreme frustration. I'm afraid I personally hold zero interest towards packages older than the latest available in the anaconda official repo, so I'm not volunteering for this one (sorry).

I'd like to hear other people's opinions and/or offers of self-immolation... :)

**Comment by shoyer** [comment]
> Today I tried downgrading dask in the py37 environment to dask=1.1.2, which is 6 months old...

Yikes, we should fix this.

It has not been hard to ensure that older version of NumPy and pandas work. The key thing is CI tests that verify things as PR goes in. If work-arounds for old versions are hard, then we bump minimum required dependencies.

Probably the best place to start would be adding a CI build with pinned versions of the oldest required versions that works today, and then looking if there are simple fixes that will let us downgrade project like dask. It's not worth a huge effort, but it's not very user friendly for everything to broken with old versions of optional dependencies either.

**Comment by crusaderky** [comment]
How does this sound as a rolling policy?
- **Python**: latest 2 major versions published in official anaconda releases (as opposed to just the conda repository), plus the latest major version available version in conda-forge. Latest available minimum versions. This today translates to =3.6 and =3.7 (with no minor versions, so actually 3.6.7 and 3.7.4); 3.8 to be added as soon as conda-forge rebuilds its own stack with it.
- **numpy, pandas**: latest major version at least 1 year old; latest available minor version (which may be newer than 1 year old). Today this translates to numpy=1.15, pandas=0.23.
- **all other non-NEP18 packages**: 6 months old major versions, unless you can think of other packages that are particularly painful to upgrade
- **NEP18 packages** (sparse, pint, etc.): very latest available only, at least until the technology has reasonably matured across the whole ecosystem. This extends to dask when used to wrap NEP18 arrays.
- **In all cases**: older versions than those stated by the above policy can remain officially supported indefinitely, but only as long as doing so can be achieved trivially and doesn't slow development down.

**Comment by shoyer** [comment]
it would be nice to try to follow the guidelines in NEP-29: https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by crusaderky** [comment]
@shoyer that sounds sensible, but only covers python and numpy. What about the rest?

**Comment by crusaderky** [comment]
Revised proposal (in parenthesis: minimum version if this policy were to be applied right now):

* **Python:** NEP-29; 42 months (>=3.6)
* **numpy:** NEP-29; 24 months (>=1.14)
* **pandas:** 24 months (>=0.20)
* **scipy:** 24 months (>=0.19)
* **NEP18 packages** (sparse, pint, etc.): very latest available only, at least until the technology has reasonably matured across the whole ecosystem. This extends to dask when used in conjunction with any of these packages. numpy >=1.17. A very recent version of pandas may also be required if necessary.
* **all other packages:** 6 months or the latest available in the anaconda (not conda-forge) repository if it exists, whatever is older.

*Note:* patch versions are not pinned. This means that the minimum python version that is guaranteed to work is actually 3.6.7 or 3.6.9, not 3.6.0.

What are people's thoughts?

It may also be a cool idea to write a script that parses the requirements yml files and generates .rst documentation out of them.

**Comment by crusaderky** [comment]
I slightly misinterpreted NEP-29. The above should be rectified:

**pandas:** 24 months (>=0.21)
**scipy:** 24 months (>=1.0)

**Comment by shoyer** [comment]
Thanks for putting this together -- this looks good to me!

We can revise if any of they cause us trouble. In particular, pandas has the most stability issues, so it might be a little annoying to try to maintain two years of support.

**Comment by dcherian** [comment]
We should add this stuff to a doc page.

**Comment by max-sixty** [comment]
Overall this is awesome, thanks @crusaderky 

One minor question: do we need to support 24 months of pandas & scipy releases? These change their API faster than numpy, and I can't imagine there's a wide audience for people that a) need the very latest xarray and b) are using pandas released in 2017. 
I would vote to dramatically cut that, to something like the last two minor releases or 6 months. But could imagine two-three minor releases or 12 months being more palatable.

**Comment by shoyer** [comment]
I think targeting 12 months of support for SciPy/pandas would be a
reasonable goal.

**Comment by crusaderky** [comment]
Ok, bumping pandas to >=0.24 and scipy to >=1.2

**Comment by crusaderky** [comment]
scipy 1.1 and 1.2 break numpy 1.14 due to a conflict on openblas. We're stuck with 1.0 at least until the next numpy upgrade.
