### ISSUE TITLE
xr.DataArray.where sets valid points to nan when using several dask chunks

### ISSUE THREAD

**Issue by climachine** [pydata/xarray#3225]
#### MCVE Code Sample

I am trying to randomly delete a fraction of a xr.DataArray ([see identical StackOverflow question](https://stackoverflow.com/questions/56686562/xr-dataarray-where-sets-valid-points-to-nan-when-using-several-dask-chunks)) and subsequently access only the values from the original dataset data that were deleted.

This works fine as long as the data is not stored in dask arrays or in only one dask array. As soon as I define chunks smaller than the total size of the data, the original values are set to nan.

```python
data = xr.DataArray(np.arange(5*5*5.).reshape(5,5,5), dims=('time','latitude','longitude'))
data.to_netcdf('/path/to/file.nc')
#data = xr.open_dataarray('/path/to/file.nc', chunks={'time':5}) # produces expected output
data = xr.open_dataarray('/path/to/file.nc', chunks={'time':2}) # produces observed output 

def set_fraction_randomly_to_nan(data, frac_missing):
    np.random.seed(0)
    data[np.random.rand(*data.shape) < frac_missing] = np.nan
    return data

data_lost = xr.apply_ufunc(set_fraction_randomly_to_nan, data.copy(deep=True),
                           output_core_dims=[['latitude','longitude']], 
                           dask='parallelized',
                           input_core_dims=[['latitude','longitude']], 
                           output_dtypes=[data.dtype], kwargs={'frac_missing': 0.5})

print(data[0,-4:,-4:].values)
# >>
# [[ 6.  7.  8.  9.]
# [11. 12. 13. 14.]
# [16. 17. 18. 19.]
# [21. 22. 23. 24.]]

print(data.where(np.isnan(data_lost),0)[0,-4:,-4:].values)
```

#### Expected Output
expected output of the last line: keep all values where `np.isnan(data_lost)` is True and set rest to zero

```python
[[ 6.  0.  0.  9.]
[ 0.  0.  0. 14.]
[16.  0.  0.  0.]
[ 0. 22.  0. 24.]]
```

#### Problem Description

observed output of the last line: set all values where `np.isnan(data_lost)` is True to nan and set rest to zero

```python
[[nan  0.  0. nan]
[ 0.  0.  0. nan]
[nan  0.  0.  0.]
[ 0. nan  0. nan]]
```

#### Output of ``xr.show_versions()``
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.138-59-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

xarray: 0.10.2
pandas: 0.22.0
numpy: 1.14.2
scipy: 1.0.1
netCDF4: 1.3.1
h5netcdf: 0.5.0
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.17.2
distributed: 1.21.5
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 39.0.1
pip: 9.0.3
conda: None
pytest: 3.5.0
IPython: 6.3.1
sphinx: 1.7.2
</details>

**Comment by shoyer** [comment]
There isn't really a notion of "deep copying" a dask array. Dask assumes that everything you apply to a  dask array is a pure function (though this isn't directly enforced), so if you map a mutating function over the blocks of a dask array you could potentially get undefined behavior (especially likely in the context of distributed computing). So when you tell xarray to deep copy a dask array, it currently just makes a normal copy.

I agree this a little counterintuitive, but it isn't obvious to me exactly what the right fix would look like.  Perhaps we could start raising an error or warning in this case?

For your specific problem, the fix is to do the copy *inside* mapped function, e.g.,
```python
def set_fraction_randomly_to_nan(data, frac_missing):
    np.random.seed(0)
    data = data.copy()
    data[np.random.rand(*data.shape) < frac_missing] = np.nan
    return data
```

**Comment by usr34598** [comment]
Thanks for looking into this! I agree this is an unexpected or at least under-documented behaviour of dask arrays.
