### ISSUE TITLE
Dict-like argument support for assign_coords()

### ISSUE THREAD

**Issue by gwgundersen** [pydata/xarray#3231]
Often the xarray API supports [either a `dict` or `kwargs`](https://github.com/pydata/xarray/blob/master/xarray/core/utils.py#L257), and it seems like this should be consistent as often as possible. With `assign_coords`, this works as expected:

```python
>>> dims = ["x", "y"]
>>> coords = {"fruit": ("x", ["apple", "banana"])}
>>> arr = xr.DataArray([[1,2,3],[4,5,6]], dims=dims, coords=coords)
>>> arr.assign_coords(color=("x", ["red", "yellow"]))
<xarray.DataArray (x: 2, y: 3)>
array([[1, 2, 3],
       [4, 5, 6]])
Coordinates:
    fruit    (x) <U6 'apple' 'banana'
    color    (x) <U6 'red' 'yellow'
Dimensions without coordinates: x, y
```

Since `assign_coords` works with keyword arguments, I would expect it to also work with a `dict`, similar to `sel`, `drop`, etc. But it does not:

```python
>>> arr.assign_coords({"color": ("x", ["red", "yellow"])})
*** TypeError: assign_coords() takes 1 positional argument but 2 were given
```

**Comment by max-sixty** [comment]
Definitely we could add this. There's an issue somewhere for rolling this functionality out - I think we've done 90% of the methods.

**Comment by shoyer** [comment]
Yes, we should definitely do this.

**Comment by gwgundersen** [comment]
Okay, I'll finish https://github.com/pydata/xarray/pull/3128 first and then tackle this.
