### ISSUE TITLE
aggregation functions treat duck arrays differently depending on dtype

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#3241]
While working on #3238, I tried replacing `np.arange` with `np.linspace` to create test arrays:
```python
>>> ureg = pint.UnitRegistry()
>>> # with int values
>>> array = np.arange(10).astype(int) * ureg.m
>>> np.max(array)
<Quantity(9, 'meter')>
>>> np.max(xr.DataArray(data=array))  # works as expected
<xarray.DataArray ()>
<Quantity(9, 'meter')>
>>> # now with floats
>>> array = np.arange(10).astype(float) * ureg.m
>>> np.max(array)
<Quantity(9.0, 'meter')>
>>> np.max(xr.DataArray(data=array))  # unit information is lost
<xarray.DataArray ()>
array(9.)
```
Judging by the build logs of #3238, this seems to be the case for all aggregation functions except from `np.median` and of course those that return booleans or indices.

**Comment by keewis** [comment]
This seams to be an issue with pint and is worked on in hgrecco/pint#764: using that PR instead of the version available in conda-forge makes all functions fail with a `TypeError` regardless of dtype.

So I guess this can be closed?

**Comment by keewis** [comment]
now that I hit this issue using the example from #3238 again, this seems to be a bug in xarray. For reference, this is the mentioned example that fails even with a pint version with `__array_function__`:
```python
>>> xr.DataArray(data=np.arange(10).astype(int) * ureg.m).median()
<xarray.DataArray ()>
<Quantity(4.5, 'meter')>
>>> xr.DataArray(data=np.arange(10).astype(int) * ureg.m).median()
<xarray.DataArray ()>
array(4.5)
```

**Comment by shoyer** [comment]
@keewis could you clarify that example? Both those examples appear to be the same code, with different results!

**Comment by keewis** [comment]
that's true. I edited it, the float version should fail.

**Comment by shoyer** [comment]
Can you try merging in the latest version of xarray master into your branch? I think this issue was fixed just recently by https://github.com/pydata/xarray/pull/3254. When I test this myself, both versions seem to do the right thing:
```
In [5]: xr.DataArray(data=np.arange(10).astype(float) * ureg.m).median()
Out[5]:
<xarray.DataArray ()>
<Quantity(4.5, 'meter')>

In [6]: xr.DataArray(data=np.arange(10).astype(int) * ureg.m).median()
Out[6]:
<xarray.DataArray ()>
<Quantity(4.5, 'meter')>
```

**Comment by keewis** [comment]
you're right, after merging the issue is gone for me, too.
