### ISSUE TITLE
Adding a time componenent to coordinates in DataArray

### ISSUE THREAD

**Issue by Foxhound013** [pydata/xarray#3272]
I'm struggling to get an irregular grid with a time component saved to a DataArray. I was able to sucessfuly create the DataArray with just lat and long (drop the time from the coords dictionary in the example below). I sincerely apologize if this is a simple error. I wasn't sure if there was an issue with how I was doing it or if there is a quirk in how xarray handles assigning three coordinates.

```python
date = datetime(2019,6,1,0,0)
da = xr.DataArray(data['value'], dims=['y','x', 'time'],
                 coords = {'lon': (('y','x'), data['lon']),
                          'lat': (('y','x'), data['lat']),
                          'time': (('time'), date)},
                 name = 'vis')

```
My data looks like the following

```
{'lat': array([[37.72836284, 37.7259804 , 37.72358804, ..., 37.1939274 ,
         37.18990579, 37.18587449],
        [37.75523415, 37.75285082, 37.75045756, ..., 37.22059837,
         37.21657525, 37.21254244],
        [37.78210555, 37.77972132, 37.77732717, ..., 37.24726939,
         37.24324477, 37.23921045],
        ...,
        [42.21245809, 42.20992438, 42.20738011, ..., 41.64414688,
         41.6398708 , 41.63558442],
        [42.23925968, 42.23672505, 42.23417986, ..., 41.67074312,
         41.6664655 , 41.66217758],
        [42.26606033, 42.26352478, 42.26097868, ..., 41.6973384 ,
         41.69305924, 41.68876977]]),
 'lon': array([[-89.37781714, -89.34384358, -89.30987225, ..., -83.74187993,
         -83.70840055, -83.67492485],
        [-89.37481006, -89.34082405, -89.30684028, ..., -83.73683568,
         -83.70334439, -83.66985679],
        [-89.37180076, -89.3378023 , -89.30380607, ..., -83.73178775,
         -83.69828455, -83.66478504],
        ...,
        [-88.8428479 , -88.80666246, -88.77047971, ..., -82.84535914,
         -82.80977027, -82.77418584],
        [-88.83943278, -88.80323323, -88.76703638, ..., -82.83964168,
         -82.8040394 , -82.76844156],
        [-88.83601497, -88.79980131, -88.76359034, ..., -82.8339198 ,
         -82.7983041 , -82.76269284]]),
 'value': array([[34300., 35200., 35900., ..., 20400., 20100., 18900.],
        [34600., 34600., 35200., ..., 20700., 20400., 19500.],
        [33000., 32700., 34000., ..., 19500., 19300., 19800.],
        ...,
        [27700., 27400., 27700., ..., 26000., 20800., 19900.],
        [28100., 27900., 27900., ..., 23500., 19900., 19100.],
        [28100., 27500., 27400., ..., 20600., 18700., 18000.]],
       dtype=float32),
 'x': 596,
 'y': 1222,
 'valid': datetime.datetime(2019, 6, 1, 0, 0)}
```

#### Expected Output
I had expected to get a DataArray with three dimensions (lat, lon, and time).

#### Problem Description
Running my code above gives me the error . . . 
**ValueError: Could not convert tuple of form (dims, data[, attrs, encoding]): ('time', datetime.datetime(2019, 6, 1, 0, 0)) to Variable.**
It works if I don't include the time coordinate or dimension. It's a single time that I'm attempting to include in the DataArray.

**Comment by shoyer** [comment]
You have two issues:
- `'time': (('time'), date)` indicates that `date` is 1D (corresponding to the single "time" dimension), but you're passing in a scalar.
- `xr.DataArray(data['value'], dims=['y','x', 'time'], ...)` indicates that `data['value']` is 3D, but you're passing in a 2D array.

Instead, you could write:
```
date = datetime(2019,6,1,0,0)
da = xr.DataArray(data['value'], dims=['y','x'],
                 coords = {'lon': (('y','x'), data['lon']),
                          'lat': (('y','x'), data['lat']),
                          'time': ((), date)},
                 name = 'vis')
```
This would give you a 2D array, to which you could add the extra "time" with `expand_dims`.

Or you could convert `data['value']` and `date` into higher dimensional arrays, in which case your original version would work.

**Comment by Foxhound013** [comment]
Okay, that makes sense! Thank you so much for your help!

Out of curiosity, would you recommend this approach for building up a dataarray dataset? Every file that I open into a dataarray is from a single time slice and I had planned to combine them all into a single dataset with multiple time steps.
