### ISSUE TITLE
Change the label size and tick label size of colorbar

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#3275]
#### MCVE Code Sample

```python
# Your code here
import xarray as xr

airtemps = xr.tutorial.open_dataset('air_temperature')
air = airtemps.air - 273.15
air2d = air.isel(time=500)
air2d.plot.pcolormesh(add_colorbar=True, add_labels=True,
                      cbar_kwargs=dict(orientation='horizontal',
                      pad=0.15, shrink=1, label='Temperature ($^{\circ}$C)'))
```

#### Expected Output
![image](https://user-images.githubusercontent.com/30388627/64117609-3225c480-cdc8-11e9-8eb7-b573e8035119.png)

#### Problem Description

Is it possible to change the label size and ticks label size of colorbar?
`size` and `labelsize` don't work in `cbar_kwargs`.

#### Output of ``xr.show_versions()``
<details>
# Paste the output here xr.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7 (default, Feb 28 2019, 07:28:18) [MSC v.1900 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.12.1
pandas: 0.24.2
numpy: 1.16.3
scipy: 1.2.1
netCDF4: 1.5.1.1
pydap: None
h5netcdf: None
h5py: 2.9.0
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: 1.0.22
cfgrib: None
iris: None
bottleneck: None
dask: 1.2.0
distributed: 1.27.1
matplotlib: 3.1.1
cartopy: 0.17.0
seaborn: None
setuptools: 41.0.1
pip: 19.1
conda: None
pytest: None
IPython: 7.6.1
sphinx: None
</details>

**Comment by dcherian** [comment]
In that case, you will have to pass `add_colorbar=False` and create your own colorbar.

**Comment by zxdawn** [comment]
@dcherian Thanks! Figure out now:

```
import xarray as xr
import matplotlib.pyplot as plt

airtemps = xr.tutorial.open_dataset('air_temperature')
air = airtemps.air - 273.15
air2d = air.isel(time=500)

im = air2d.plot.pcolormesh(add_colorbar=False)
cb = plt.colorbar(im, orientation="horizontal", pad=0.15)
cb.set_label(label='Temperature ($^{\circ}$C)', size='large', weight='bold')
cb.ax.tick_params(labelsize='large')
```
![image](https://user-images.githubusercontent.com/30388627/64118164-a9a82380-cdc9-11e9-80e5-7a61f4591734.png)

**Comment by dcherian** [comment]
@zxdawn you are welcome.

The other thing you could do is set the relevant `rcParams` and then xarray's automatic colorbars will look the way you want them to.

**Comment by zxdawn** [comment]
@dcherian Can't find how to do that by `rcParams`. Could you give a simple example?

**Comment by dcherian** [comment]
What I meant was you can set the defaults using rcParams (https://matplotlib.org/users/customizing.html#matplotlib-rcparams). However there doesn't seem to be an rcParams for colorbars :(. Looks like you'll have to make the colorbar manually.

**Comment by RylanSchaeffer** [comment]
Is there still no rcParams for colorbars?

**Comment by Ricbrag** [comment]
Hi all, I'm trying to use these tricks to increase the tick label of an imshow horizontal colorbar but, I'm getting error (1) on:
set add_colorbar=False

If I do not try to set add_colorbar=False I got error (2) on:
cb.ax.tick_params(labelsize=20)

Test example:
a=np.random.rand(10,10)
im=plt.imshow(a,add_colorbar=False)
cb=plt.colorbar(im,orientation='horizontal').set_label(label='Label',size=20,weight='bold')
cb.ax.tick_params(labelsize='large')

Error(1): AttributeError: Unknown property add_colorbar
Error(2): AttributeError: 'NoneType' object has no attribute 'ax'

Any suggestions?

**Comment by Ricbrag** [comment]
I solve my problem using matplotlib.rcParams to change xtick.labelsize (that controls also the horizontal colorbar  tick).
Still don't know how to decouple the axis tick size from colorbar tick size.
here is the code:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rcParams['xtick.labelsize'] = 20
mpl.rcParams['ytick.labelsize'] = 20
a=np.random.rand(10,10)
im=plt.imshow(a)
cb=plt.colorbar(im,orientation='horizontal').set_label(label='Label',size=20,weight='bold')
plt.show()

**Comment by aaraney** [comment]
@Ricbrag something like this should work:

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

a=np.random.rand(10,10)
im=plt.imshow(a)
cb=plt.colorbar(im,orientation='horizontal').set_label(label='Label',size=20,weight='bold')

im.figure.axes[0].tick_params(axis="both", labelsize=5)
im.figure.axes[1].tick_params(axis="x", labelsize=20)

plt.show()
```
![image](https://user-images.githubusercontent.com/39420640/121986071-e9a08680-cd63-11eb-93b1-c46dff37e704.png)

**Comment by manudie** [comment]
Is there a possility to create a colorbar and change the font family?

**Comment by Ricbrag** [comment]
Work nicely! Thanks!
