### ISSUE TITLE
Deprecation cycles to finish for xarray 0.13

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#3280]
Clean-ups we should definitely do:
- [x] remove deprecated options from `xarray.concat` (deprecated back in July 2015!): https://github.com/pydata/xarray/blob/79dc7dc461c7540cc0b84a98543c6f7796c05268/xarray/core/concat.py#L114-L144 (edit by @max-sixty )
- [x] argument order in `DataArray.to_dataset` (also from July 2015) https://github.com/pydata/xarray/blob/41fecd8658ba50ddda0a52e04c21cec5e53415ac/xarray/core/dataarray.py#L491 (edit by @max-sixty )
- [x] remove the warning back reindex with variables with different dimensions (from 2017). This could either be replaced by replacing dimensions like `sel` or by simply raising an error for now and leaving replacing dimensions for later: https://github.com/pydata/xarray/pull/1639): https://github.com/pydata/xarray/blob/79dc7dc461c7540cc0b84a98543c6f7796c05268/xarray/core/alignment.py#L389-L398 (edit by @max-sixty )
- [x] remove `xarray.broadcast_array`, deprecated back in 2016 in https://github.com/pydata/xarray/commit/52ee95f8ae6b9631ac381b5b889de47e41f2440e (edit by @max-sixty )
- [x] remove `Variable.expand_dims` (deprecated back in August 2017), whose implementation actually looks like it's already broken: https://github.com/pydata/xarray/blob/41fecd8658ba50ddda0a52e04c21cec5e53415ac/xarray/core/variable.py#L1232-L1237 (edit by @max-sixty )
- [x] stop supporting a list of colors in the `cmap` argument (dating back to at least v0.7.0): https://github.com/pydata/xarray/blob/d089df385e737f71067309ff7abae15994d581ec/xarray/plot/utils.py#L737-L745 (edit by @max-sixty )
- [x] push the removal of the `compat` and `encoding` arguments from `Dataset`/`DataArray` back to 0.14. These were only deprecated 7 months ago in https://github.com/pydata/xarray/pull/2703. (edit by @max-sixty )

Clean-ups to consider:
- [x] switch the default reduction dimension of groupby and resample? (https://github.com/pydata/xarray/pull/2366) This has been giving a FutureWarning since v0.11.0, released back in November 2018. We could also potentially push this back to 0.14, but these warnings are a little annoying...
- [x] deprecate `auto_combine` (#2616) only since 29 June 2019, so that should be pushed.

**Comment by mathause** [comment]
> stop supporting a list of colors in the `cmap` argument

I am a bit worried about the 3rd last item on your list. I currently still rely on this behavior because the alternative does not work for me, see  #3284.

**Comment by shoyer** [comment]
> > stop supporting a list of colors in the `cmap` argument
> 
> I am a bit worried about the 3rd last item on your list. I currently still rely on this behavior because the alternative does not work for me, see #3284.

OK, we should put this off until the alternative works! But I do think we want to stop overloading `cmap` in an incompatible way.

**Comment by max-sixty** [comment]
@shoyer I edited your comment to check-off the ones in #3292, hope that's OK. (would be good to have a system from GH that didn't involve free editing of others' comments!)

**Comment by max-sixty** [comment]
I think all the 'must-dos' are done

**Comment by dcherian** [comment]
> > stop supporting a list of colors in the `cmap` argument
> 
> I am a bit worried about the 3rd last item on your list. I currently still rely on this behavior because the alternative does not work for me, see #3284.

Does your PR mean that we can go forward with the deprecation then?

**Comment by mathause** [comment]
Yes, fine for me.

**Comment by dcherian** [comment]
We were also planing to deprecate `auto_combine` for 0.13 but we've been warning about that only since 29 June, 2019 so that should be pushed to 0.14. I've added this to the list.

**Comment by shoyer** [comment]
Yeah, there's also some question about if combine_nested() and
combine_by_coords() really solve all the use-cases of auto_combine(). For
example, a bunch of files that don't contain the concatenated dimension and
have different variables can be combined automatically by auto_combine()
but not  combine_by_coord().

**Comment by dcherian** [comment]
#3313 and #3314 should be looked over by someone who knows the `auto_combine` and `groupby` code.
