### ISSUE TITLE
Add hypothesis support to related projects

### ISSUE THREAD

**Issue by rdturnermtl** [pydata/xarray#3289]
The [hypothesis-gufunc](https://pypi.org/project/hypothesis-gufunc/0.0.5rc2/) project recently added hypothesis strategies for generating xarray data structures in version 0.0.5rc2.  It should be linked to in the related projects page.  It currently uses xarray as a package extra and must be installed as
```
pip install hypothesis-gufunc[xarray]==0.0.5rc2
```
The documentation is [here](https://hypothesis-gufunc.readthedocs.io/en/latest/).

**Comment by dcherian** [comment]
Thanks @rdturnermtl , can you send in a PR to add this package?
