### ISSUE TITLE
Drop 3.5 after 0.13?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#3293]
I just saw https://numpy.org/neps/nep-0029-deprecation_policy.html, which suggests dropping 3.5 support earlier this year (though NEP is dated to this July)

Ofc, existing xarray versions would still work with 3.5, only upgrades would require the new version (which I know everyone knows, but reinforces we don't need to wait for _everyone_ to move off 3.5)

**Comment by crusaderky** [comment]
As somebody who's maintained conda in a large corporate environment, I can confirm that upgrading major version of python is a couple day's work at worst.
I'm strongly in favour of a rolling policy for maintaining the last 2 versions of python supported by the official anaconda release package (as opposed to just the repo).

**Comment by shoyer** [comment]
To clarify — the proposal is to drop support for Python 3.5 in the upcoming 0.13 release? Or later, in 0.14? I’d be happy to go ahead and do it now... it would be nice to be able to rely on dict iteration order and f-strings.

**Comment by crusaderky** [comment]
Getting rid of all the ordereddicts is a colossal change, and IMHO this release is already way too large...

**Comment by crusaderky** [comment]
(that said I'm perfectly happy to have 0.14 one week after 0.13!)

**Comment by max-sixty** [comment]
I wasn't initially suggesting for 0.13 but not opposed to it

What about releasing 0.13 and then dropping 3.5? That way any 3.5 users have an up-to-date version and we can have a master on 3.6 very soon

**Comment by max-sixty** [comment]
> (that said I'm perfectly happy to have 0.14 one week after 0.13!)

What are the semver rules for underlying versions? If we drop 3.5 support, do we need a minor version increase to 0.14, or is a patch release to 0.13.1 OK?

**Comment by shoyer** [comment]
> Getting rid of all the ordereddicts is a colossal change, and IMHO this release is already way too large...

I agree, I was suggesting simply dropping support for Python 3.5 without other associated changes -- those can come later.

**Comment by shoyer** [comment]
> > (that said I'm perfectly happy to have 0.14 one week after 0.13!)
> 
> What are the semver rules for underlying versions? If we drop 3.5 support, do we need a minor version increase to 0.14, or is a patch release to 0.13.1 OK?

We don't really have strict rules about this, but I think it's friendlier to keep major version bumps of xarray's dependencies to major xarray releases (i.e., 0.13 or 0.14).
