### ISSUE TITLE
[Docs] parameters + data type broken

### ISSUE THREAD

**Issue by Hoeze** [pydata/xarray#3296]
Hi, since this is already present some time and I could not find a corresponding issue:

The documentation format seems to be broken. Parameter name and data type stick together:
![image](https://user-images.githubusercontent.com/1200058/64545044-59304900-d328-11e9-8553-ccce87d239f4.png)
Source: http://xarray.pydata.org/en/stable/generated/xarray.apply_ufunc.html

**Comment by dcherian** [comment]
This is fixed on master. If you change stable to latest in your link, it will look better. We should've backported those fixes to stable...

**Comment by Hoeze** [comment]
Thanks @dcherian!
