### ISSUE TITLE
swap dimensions with multi-dimensional coordinates

### ISSUE THREAD

**Issue by pascalgross** [pydata/xarray#3299]
Hi,
This is a usage question. I've got some GRIB weather data, loaded with cfgrib into xarray.

```
<xarray.Dataset>
Dimensions:            (x: 421, y: 461)
Coordinates:
    time               datetime64[ns] 2015-05-10T12:00:00
    step               timedelta64[ns] 00:00:00
    heightAboveGround  int64 10
    latitude           (y, x) float64 44.77 44.77 44.77 ... 56.14 56.14 56.14
    longitude          (y, x) float64 2.976 3.011 3.046 ... 19.75 19.8 19.84
    valid_time         datetime64[ns] 2015-05-10T12:00:00
Dimensions without coordinates: x, y
Data variables:
    u10                (y, x) float32 ...
    v10                (y, x) float32 ...
    si10               (y, x) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             edzw
    GRIB_centreDescription:  Offenbach
    GRIB_subCentre:          255
    Conventions:             CF-1.7
    institution:             Offenbach
```

The dimension is x,y. If I want to export this to GeoTIFF using rioxarray, I get the wrong results as the dimensions should be latitude/longitude, not x/y. Is there any way to "transform" the data or something like this.

**Comment by max-sixty** [comment]
I think you're looking for `.rename`. If not, could you post a MCVE as per the issue template please?

**Comment by pascalgross** [comment]
I don't see how .rename would work for me - could you give me an example?

Expected result is something like:
```
<xarray.Dataset>
Dimensions:            (latitude: 421, longitude: 461)
Coordinates:
    time               datetime64[ns] 2015-05-10T12:00:00
    step               timedelta64[ns] 00:00:00
    heightAboveGround  int64 10
    latitude           float64 44.77 44.77 44.77 ... 56.14 56.14 56.14
    longitude          float64 2.976 3.011 3.046 ... 19.75 19.8 19.84
```

**Comment by jthielen** [comment]
Based on your input and expected result, I would guess that you are looking to regrid your data from the x/y curvilinear grid of your GRIB weather data to a new rectilinear (lon/lat) grid?

If so, I would suggest using xESMF ([example here](https://xesmf.readthedocs.io/en/latest/notebooks/Curvilinear_grid.html)), since [xarray itself does not appear to support this type of interpolation yet](https://github.com/pydata/xarray/issues/2281). As an example, given the dimension names you currently have and expect in the output, your code could look something like the following:

```python
import xesmf as xe

# ...load data...

ds_xy_grid = ds_xy_grid.rename(latitude='lat', longitude='lon')
ds_out = xr.Dataset({'lat': (['lat'], np.linspace(44.77, 56.14, 421)),
                     'lon': (['lon'], np.linspace(2.976, 19.84, 461)})
regridder = xe.Regridder(ds_xy_grid, ds_out)
ds_lonlat_grid = regridder(ds_xy_grid)
ds_lonlat_grid = ds_lonlat_grid.rename(lat='latitude', lon='longitude')
```

**Comment by pascalgross** [comment]
@jthielen Thank you! This is pretty much what I was looking for. 

If someone else sees this: your line
`regridder = xe.Regridder(ds_xy_grid, ds_out)` is missing the method e.g. `regridder = xe.Regridder(ds_xy_grid, ds_out, 'bilinear')`
