### ISSUE TITLE
`ds.load()` with local files stalls and fails, and `to_zarr` does not include `store` in the dask graph

### ISSUE THREAD

**Issue by abarciauskas-bgse** [pydata/xarray#3306]
#### MCVE Code Sample

Below details a scenario where reading local netcdf files (shared via EFS) to create a zarr store is not calling `store` as part of the dask graph. I discovered it looks like this may actually be related to `concatenate`

I include a commented option where I try using files over https and this works (does store data on S3), but of course the open dataset calls are slower.

`ds.to_zarr` and `ds.load()` will both stall and eventually returning many instances of:

```
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://192.168.62.40:37233'], ('concatenate-2babafa03313bcf979ae6ca3a8e16aad', 1, 10, 13)
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://192.168.62.40:37233'], ('concatenate-2babafa03313bcf979ae6ca3a8e16aad', 0, 6, 30)
```

```python
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import xarray as xr
from dask.distributed import Client, progress
import s3fs
import zarr
import datetime

# In[16]:


import datetime

chunks = {'lat': 1000, 'lon': 1000}
base = 2018
year = base
ending = '090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'
days_of_year = list(range(152, 154))
file_urls = []

for doy in days_of_year:
    date = datetime.datetime(year, 1, 1) + datetime.timedelta(doy - 1)
    date = date.strftime('%Y%m%d')
    file_urls.append('./{}/{}/{}{}'.format(year, doy, date, ending))

print(file_urls)
ds = xr.open_mfdataset(file_urls, chunks=chunks, combine='by_coords', parallel=True)
ds


# In[21]:


# This works fine
# base_url = 'https://podaac-opendap.jpl.nasa.gov:443/opendap/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR/v4.1/'
# url_ending = '090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc?time[0:1:0],lat[0:1:17998],lon[0:1:35999],analysed_sst[0:1:0][0:1:17998][0:1:35999]'
# year = 2018
# days_of_year = list(range(152, 154))
# file_urls = []

# for doy in days_of_year:
#     date = datetime.datetime(year, 1, 1) + datetime.timedelta(doy - 1)
#     date = date.strftime('%Y%m%d')
#     file_urls.append('{}/{}/{}/{}{}'.format(base_url, year, doy, date, url_ending))

# #file_urls
# ds = xr.open_mfdataset(file_urls, chunks=chunks, parallel=True, combine='by_coords')
# ds


# In[ ]:

# Write zarr to s3
myS3fs = s3fs.S3FileSystem(anon=False)
zarr_s3 = 'aimeeb-datasets-private/mur_sst_zarr14'
d = s3fs.S3Map(zarr_s3, s3=myS3fs)
compressor = zarr.Blosc(cname='zstd', clevel=5, shuffle=zarr.Blosc.AUTOSHUFFLE)
encoding = {v: {'compressor': compressor} for v in ds.data_vars}
ds.to_zarr(d, mode='w', encoding=encoding)

```

#### Expected Output

Expect the call `to_zarr` to produce a graph with `store`

#### Problem Description

The end result should be a zarr store on S3

#### Output of ``xr.show_versions()``

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.14.128-112.105.amzn2.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.12.3
pandas: 0.25.0
numpy: 1.16.4
scipy: 1.3.0
netCDF4: 1.5.1.2
pydap: None
h5netcdf: None
h5py: 2.9.0
Nio: None
zarr: 2.3.2
cftime: 1.0.3.4
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.0.24
cfgrib: None
iris: None
bottleneck: None
dask: 2.2.0
distributed: 2.2.0
matplotlib: 3.1.1
cartopy: 0.17.0
seaborn: 0.9.0
numbagg: None
setuptools: 41.0.1
pip: 19.2.1
conda: None
pytest: None
IPython: 7.7.0
sphinx: None
```

**Comment by abarciauskas-bgse** [comment]
Update: I've made some progress on determining the source of this issue. It seems related to the source dataset's variables. When I use 2 opendap urls with 4 parameterized variables things work fine

Using 2 urls like:

```
https://podaac-opendap.jpl.nasa.gov:443/opendap/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR/v4.1/2002/152/20020601090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc?time[0:1:0],lat[0:1:17998],lon[0:1:35999],analysed_sst[0:1:0][0:1:17998][0:1:35999],analysis_error[0:1:0][0:1:17998][0:1:35999],mask[0:1:0][0:1:17998][0:1:35999],sea_ice_fraction[0:1:0][0:1:17998][0:1:35999]
```

I get back a dataset :

```
<xarray.Dataset>
Dimensions:         (lat: 17999, lon: 36000, time: 2)
Coordinates:
  * lat             (lat) float32 -89.99 -89.98 -89.97 ... 89.97 89.98 89.99
  * lon             (lon) float32 -179.99 -179.98 -179.97 ... 179.99 180.0
  * time            (time) datetime64[ns] 2018-04-22T09:00:00 2018-04-23T09:00:00
Data variables:
    analysed_sst    (time, lat, lon) float32 dask.array<shape=(2, 17999, 36000), chunksize=(1, 1000, 1000)>
    analysis_error  (time, lat, lon) float32 dask.array<shape=(2, 17999, 36000), chunksize=(1, 1000, 1000)>
Attributes:
    Conventions:                CF-1.5
    title:                      Daily MUR SST, Final product
```

however if I omit the parameterized data variables using urls such as:

```
https://podaac-opendap.jpl.nasa.gov:443/opendap/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR/v4.1/090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc
```

I get back an additional variable:

```
<xarray.Dataset>
Dimensions:           (lat: 17999, lon: 36000, time: 2)
Coordinates:
  * lat               (lat) float32 -89.99 -89.98 -89.97 ... 89.97 89.98 89.99
  * lon               (lon) float32 -179.99 -179.98 -179.97 ... 179.99 180.0
  * time              (time) datetime64[ns] 2018-04-22T09:00:00 2018-04-23T09:00:00
Data variables:
    analysed_sst      (time, lat, lon) float32 dask.array<shape=(2, 17999, 36000), chunksize=(1, 1000, 1000)>
    analysis_error    (time, lat, lon) float32 dask.array<shape=(2, 17999, 36000), chunksize=(1, 1000, 1000)>
    mask              (time, lat, lon) float32 dask.array<shape=(2, 17999, 36000), chunksize=(1, 1000, 1000)>
    sea_ice_fraction  (time, lat, lon) float32 dask.array<shape=(2, 17999, 36000), chunksize=(1, 1000, 1000)>
    dt_1km_data       (time, lat, lon) timedelta64[ns] dask.array<shape=(2, 17999, 36000), chunksize=(1, 1000, 1000)>
Attributes:
    Conventions:                CF-1.5
    title:                      Daily MUR SST, Final product
```

In the first case (with the parameterized variables) I achieve the expected result (data is stored on S3). In the second case (no parameterized variables), `store` store is never included in the graph the workers seem to stall.

**Comment by rabernat** [comment]
@aidanheerdegen - thanks so much for posting this issue! I think a lot of people run into these sorts of problems, so it's useful to have an example on the issue tracker.

These problems can unfortunately be very hard to debug. If other developers can quickly reproduce your exact same error on their own systems, then we can try to dig deeper. However, I can't run the code you shared. If I paste it into a notebook, I get
```
FileNotFoundError: [Errno 2] No such file or directory: b'/home/jovyan/cmip6-bot/2018/153/20180602090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'
```
Your example requires your files, which I don't have. I noticed some later examples point to a podaac opendap sever, commented out with the comment
```
# This works fine
# base_url = 'https://podaac-opendap.jpl.nasa.gov:443/opendap/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR/v4.1/'
```
but I couldn't tell if I was supposed to run that part or not.

So unfortunately I have to ask you for some tweaks to your question.
Could you either:
1. edit this example so that it points to an opendap server or other globally accessible endpoint on the internet? OR
1. replace the real data with synthetically generated data (e.g. use `dask.random.random` to create arrays instead of loading from disk)

Although 2 is a pain, it actually usually helps surface bugs by removing part of the I/O.

Thanks again for your contribution.

**Comment by abarciauskas-bgse** [comment]
@rabernat good points. One thing I'm not sure of how to make reproducible is calling a remote file store, since I think it usually requires calling to a write-protected cloud storage provider. Any tips on this?

I have what should be an otherwise working example here: https://gist.github.com/abarciauskas-bgse/d0aac2ae9bf0b06f52a577d0a6251b2d - let me know if this is an ok format to share for reproducing the issue.

**Comment by rabernat** [comment]
Does the problem only arise when writing to s3fs? Or can you reproduce it writing to a local Zarr directory store?

**Comment by abarciauskas-bgse** [comment]
I recall this also happening when storing locally but I can't reproduce that at the moment since the kubernetes cluster I am using now is not a pangeo hub and not setup to use EFS.

**Comment by rabernat** [comment]
What if you just use a dask local cluster, rather than a distributed cluster? Then you can just write to a local directory.

And what if you don’t use a distributed cluster at all, just the threaded scheduler?

In my experience with these problems, by systematically removing layers of complexity from the scenario, we often come to the root of the issue

**Comment by abarciauskas-bgse** [comment]
Thanks @rabernat. I tried what you suggested (with a small subset, the source files are quite large) and it seems to work on smaller subsets, writing locally. Which leads me to suspect trying to run the same process with larger datasets might be overloading memory, but I can't assert the root cause yet. This isn't blocking my current strategy so closing for now.
