### ISSUE TITLE
Linear algebra support

### ISSUE THREAD

**Issue by weipeng1999** [pydata/xarray#3322]
Share we support linear algebra? 
Thank you for your hardworking, I'm so happy that we do not need to rember the damned "axis number" in normal situations. But sometime we should still use the functions of linear algebra like LUdepart or determinant.  
Follow is the codes to explain some personal idea of new functions API. 
#code 
```
>>>Adata = np.random.randn(4,4,7)
>>>A = DataArray(Adata, dims=('x','y','z')) 
>>>L, U = LUdepart(A, dims1='x',  dims2='y',newdims='a') 
```
#result 
```
>>> L
DataArray(x:4, z:7, a: 4)
...
>>> U
DataArray(y:4, z:7, a: 4)
... 
>>>L@U == A
True
```
I think other essential linear algebra function in numpy can be wraped by this way so that we will can use their named axis version.  Do you have any suggestions? 
Finally,  thankyou again for your work.

**Comment by crusaderky** [comment]
Hi @weipeng1999 ,
could you link the reference implementation in numpy/scipy?

I think this would be niche-ish. I would personally try to keep xarray free of functionality that only a tiny fraction of the users actually use - particularly when such functionality can be implemented with a trivial wrapper by the users themselves.
e.g. at the moment we have exactly one scipy function being wrapped, and that's linear interpolation which is useful to a lot of people.

I think this falls into a more general discussion on how niche a function must be in order to be excluded from the library - @shoyer what's your opinion?

Regardless, I would like to point you to <https://xarray-extras.readthedocs.io> which is a module that I created exactly for this kind of cases (PRs are welcome).

**Comment by max-sixty** [comment]
Somewhat related: https://github.com/pydata/xarray/pull/2766

**Comment by weipeng1999** [comment]
> Hi @weipeng1999 ,
> could you link the reference implementation in numpy/scipy?
> 
> I think this would be niche-ish. I would personally try to keep xarray free of functionality that only a tiny fraction of the users actually use - particularly when such functionality can be implemented with a trivial wrapper by the users themselves.
> e.g. at the moment we have exactly one scipy function being wrapped, and that's linear interpolation which is useful to a lot of people.
> 
> I think this falls into a more general discussion on how niche a function must be in order to be excluded from the library - @shoyer what's your opinion?
> 
> Regardless, I would like to point you to https://xarray-extras.readthedocs.io which is a module that I created exactly for this kind of cases (PRs are welcome).

I try to do it but I realize that I am a totally greenfinger
here is a little example for QRdepart
I think I have long way to make it commitable
`import numpy as np
import xarray as xr
from scipy.linalg import qr as sci_qr

def _check_dims(dK,Q_dims,R_dims,new_dims)->bool:
    if new_dims in dK:      raise KeyError
    if Q_dims == R_dims:    raise KeyError
    return True

def qr(A:xr.DataArray,Q_dims,R_dims,new_dims)->(xr.DataArray,xr.DataArray):
    #get the axis
    aQ,aR = A.get_axis_num([Q_dims,R_dims])
    #dK is dict of the other dims out of caculation
    dK = dict(A.sizes)
    _check_dims(dK,Q_dims,R_dims,new_dims)
    dK.pop(Q_dims); dK.pop(R_dims)
    # reshape A 
    # so that we can easily iterate A
    a = A.values
    a = np.moveaxis(a,[aQ,aR],[-2,-1])
    a = a.reshape(-1,*a.shape[-2:])
    # caculate to get q,r
    nK,nQ,nR = a.shape
    q = np.zeros((nK,nQ,nQ))
    r = np.zeros((nK,nQ,nR))
    for i,m in enumerate(a):
        v1,v2 = sci_qr(a[i])
        q[i],r[i] = v1,v2
    q = q.reshape(*tuple(dK.values()),nQ,nQ)
    r = r.reshape(*tuple(dK.values()),nQ,nR)
    # rename the croods 
    # to avoid wrong index
    fit = lambda k: k + '_' if k == new_dims else k
    # get coords for R,Q
    Q_coords = {fit(k):c for k,c in A.coords.variables.items() if R_dims not in c.dims}
    R_coords = {fit(k):c for k,c in A.coords.variables.items() if Q_dims not in c.dims}
    # craft the result
    Q = xr.DataArray(q,dims=(*dK,Q_dims,new_dims),coords=Q_coords)
    R = xr.DataArray(r,dims=(*dK,new_dims,R_dims),coords=R_coords)
    return Q,R

A = xr.DataArray(
    np.random.rand(3,4,5),
    dims=('x','y','z'),
    coords={
        'a':('x',[1,2,3]),
        'b':('y',[1,2,3,4]),
        'c':43
    },
    attrs={
        'l':20,
        'm':(('x','y'),np.arange(12).reshape(3,4)),
    },
)
# print(A.attrs)
Q,R = qr(A,'x','y','a')
print(Q.sizes)
print(R[{'z':0}])
print(Q.dot(R,dims='a').sizes)
print(Q.dot(R,dims='a').coords)
print((Q.dot(R,dims='a') - A < 1E-10).all())`

**Comment by weipeng1999** [comment]
> Hi @weipeng1999 ,
> could you link the reference implementation in numpy/scipy?
> 
> I think this would be niche-ish. I would personally try to keep xarray free of functionality that only a tiny fraction of the users actually use - particularly when such functionality can be implemented with a trivial wrapper by the users themselves.
> e.g. at the moment we have exactly one scipy function being wrapped, and that's linear interpolation which is useful to a lot of people.
> 
> I think this falls into a more general discussion on how niche a function must be in order to be excluded from the library - @shoyer what's your opinion?
> 
> Regardless, I would like to point you to https://xarray-extras.readthedocs.io which is a module that I created exactly for this kind of cases (PRs are welcome).

```
import numpy as np
import xarray as xr
from scipy.linalg import qr as sci_qr

def _check_dims(dK,Q_dims,R_dims,new_dims)->bool:
    if new_dims in dK:      raise KeyError
    if Q_dims == R_dims:    raise KeyError
    return True

def qr(A:xr.DataArray,Q_dims,R_dims,new_dims)->(xr.DataArray,xr.DataArray):
    #get the axis
    aQ,aR = A.get_axis_num([Q_dims,R_dims])
    #dK is dict of the other dims out of caculation
    dK = dict(A.sizes)
    _check_dims(dK,Q_dims,R_dims,new_dims)
    dK.pop(Q_dims); dK.pop(R_dims)
    # reshape A 
    # so that we can easily iterate A
    a = A.values
    a = np.moveaxis(a,[aQ,aR],[-2,-1])
    a = a.reshape(-1,*a.shape[-2:])
    # caculate to get q,r
    nK,nQ,nR = a.shape
    q = np.zeros((nK,nQ,nQ))
    r = np.zeros((nK,nQ,nR))
    for i,m in enumerate(a):
        v1,v2 = sci_qr(a[i])
        q[i],r[i] = v1,v2
    q = q.reshape(*tuple(dK.values()),nQ,nQ)
    r = r.reshape(*tuple(dK.values()),nQ,nR)
    # rename the croods 
    # to avoid wrong index
    fit = lambda k: k + '_' if k == new_dims else k
    # get coords for R,Q
    Q_coords = {fit(k):c for k,c in A.coords.variables.items() if R_dims not in c.dims}
    R_coords = {fit(k):c for k,c in A.coords.variables.items() if Q_dims not in c.dims}
    # craft the result
    Q = xr.DataArray(q,dims=(*dK,Q_dims,new_dims),coords=Q_coords)
    R = xr.DataArray(r,dims=(*dK,new_dims,R_dims),coords=R_coords)
    return Q,R

A = xr.DataArray(
    np.random.rand(3,4,5),
    dims=('x','y','z'),
    coords={
        'a':('x',[1,2,3]),
        'b':('y',[1,2,3,4]),
        'c':43
    },
    attrs={
        'l':20,
        'm':(('x','y'),np.arange(12).reshape(3,4)),
    },
)
# print(A.attrs)
Q,R = qr(A,'x','y','a')
print(Q.sizes)
print(R[{'z':0}])
print(Q.dot(R,dims='a').sizes)
print(Q.dot(R,dims='a').coords)
print((Q.dot(R,dims='a') - A < 1E-10).all())
```

**Comment by shoyer** [comment]
I think the way to write something like an LU decomposition would be to use xarray's `apply_ufunc`, which in theory could wrap `scipy.linalg. lu_factor` in one line.

I don't know if this could/should live in xarray proper. We tend to have pretty high standards, which slows development.

**Comment by OriolAbril** [comment]
Would there be any interest in an "xarray linalg library"? Something library of that sort would be really useful to ArviZ and our users, I'll probably write some very basic functions myself on a minimal library or add them to ArviZ directly, but if there are other people interested we can try to find synergies and get something more general. 

In our case, 99% of the time we want to "batch" over the `chain` and `draw` dimensions. So things as simple as:

```
def xarray_dot(a, b, dim=None):
    if dim is None:
        a_dims = set(a.dims)
        b_dims = set(b.dims)
        dim_set = a_dims.intersection(b_dims) - {"chain", "draw"}
        if len(dim_set) == 1:
            dim = dim_set.pop()
        else:
            ValueError
    if not isinstance(dim, str):
        raise ValueError
    return xr.apply_ufunc(
        np.einsum,
        "...i,...i",
        a,
        b,
        input_core_dims=[[], [dim], [dim]]
    )
```

are already extremely useful. 

Being able to invert, cholesky... without using `apply_ufunc` would be convenient (even more so if we define some conventions, i.e. I generally use `dim` and `dim bis` for covariance matrices so they have shape `chain, draw, ..., dim, dim bis`. 

In our case, being able to `ds.transpose("dim1", "dim2")` and have it ignore `chain, draw` would also be convenient, which is probably a very ArviZ specific situation, but maybe there are other libraries/people that commonly have some batch dimensions, even if they use different names for them or if the user chooses those names freely.

**Comment by dcherian** [comment]
>  "xarray linalg library"? 

Thanks @OriolAbril . This sounds like a nice xarray-contrib repo if it's general enough. Note that we do have `xarray.dot` https://xarray.pydata.org/en/stable/generated/xarray.dot.html

**Comment by OriolAbril** [comment]
Great, thanks for the offer :smile: I think I'll start with a minimal repo back at ArviZ and see how much of that can be used more generally. I probably should have named the example above `arviz_dot` instead. I definitely want to be able to do  `arviz_dot(a, b)` and have it work automatically because in most ArviZ cases we do have all the information we need for this to be possible. We'll therefore definitely need a higher ArviZ layer, but I think an xarray-linalg would be a great base on which to build and we can keep both in different files/modules so it can be split easily.

I also commented here as I thought it was the most related issue, many of the functions I have in mind are related to linalg, but we'll probably have some other functions too.

**Comment by OriolAbril** [comment]
I have created a library for easier linear algebra with xarray: https://xarray-einstats.readthedocs.io/en/latest/. 

It currently has:
* wrappers for many `numpy.linalg` functions
* wrappers for `scipy.stats` distributions plus a few functions
* wrappers for [einops]() functions
* a `numba.guvectorize`-decorated version of `numpy.histogram` for dataarrays

I have mostly added wrappers for things I personally use, also trying to not overlap with xr-scipy nor xarray-extras, so it might not make much sense as a group, but the modules are completely independent between them and could be reorganized into independent packages or merged into existing ones.

Feedback very welcome!

**Comment by dcherian** [comment]
Closing in favour of xarray-einstats
