### ISSUE TITLE
Memory usage of `da.rolling().construct`

### ISSUE THREAD

**Issue by fjanoos** [pydata/xarray#3332]
If I were to do   `data_array.rolling( time=1000 ).construct('temp_time')` - what is going on under hood ? Does it make a 1000 phyiscal copies of the original dataarray - or is it only returning a view ? I feel like it's the latter - but I'm seeing a memory spike (about 20-30% increase in total process memory consumption) when I use it -  so there might be something else going on ?
Any ideas / pointers would be appreciated. Thanks!

**Comment by dcherian** [comment]
It should be returning a view.

**Comment by shoyer** [comment]
It uses a view for allocating the initial result, but I think applying boundary conditions means that we end up doing a copy.

**Comment by jbphyswx** [comment]
Is there any way to get around this? The window dimension combined with the `For window size x, every chunk should be larger than x//2`  requirement means that for a large moving window I'm getting O(100GB) chunks that do not fit in memory at compute time. I can, of course, rechunk other dimensions, but that is expensive and substantially slower. I also suspect this becomes practically infeasible on machines that have little memory. Regardless, mandatory O(n^2) memory usage with window size seems less than ideal.

My workaround has been to just implement my own slicing via for loop and then call reduction operations on the resultant dask arrays as normal... Perhaps there is something I missed along the way but I couldn't find anything in open or past issues to aid in resolving this. Thanks!

**Comment by shoyer** [comment]
The loop via slicing is not a terrible option. The trick construct() uses with views only really makes sense with NumPy arrays, not with dask.

There are also true streaming moving window algorithms that work very well for computing various statistics (e.g., mean and variance). These are implemented in bottleneck (e.g., `move_mean`) and could be wrapped in xarray if desired for methods like `rolling(...).mean()`. These aren't implemented in dask yet, though.

**Comment by dcherian** [comment]
so it's pad then view, so a copy of the *original* array is made, not the strided array.

https://github.com/pydata/xarray/blob/735a3590ea4df70e1e5be729162df2f8774b3879/xarray/core/nputils.py#L149-L151
