### ISSUE TITLE
Define aligning, broadcasting, merging, concatenating, combining in new glossary

### ISSUE THREAD

**Issue by gwgundersen** [pydata/xarray#3355]
Over at https://github.com/pydata/xarray/pull/3352, we're working on a new page describing key Xarray terminology for https://github.com/pydata/xarray/issues/2410. Since it's already a big PR, and we may need to iterate on the definitions a few times, this issue is for extending the glossary once that PR is merged. Some terms are to add are: **aligning**, **broadcasting**, **merging**, **concatenating**, **combining**.

**Comment by TomNicholas** [comment]
Happy to help with this!
