### ISSUE TITLE
user-friendly additions for dask usage

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3363]
Any thoughts on adding

1. `.chunksize` or `.nbytes_chunk`
2. `.ntasks` : this would be `len(obj.__dask_graph__())`

**Comment by crusaderky** [comment]
I'd rather transparently invoke data's method instead. This has bonus points considering the variety of NEP18-compatible xarray can now wrap.

```python
class DataArray:
    def __getattr__(self, item):
        try:
            return getattr(self._variable._data, item)
        except AttributeError:
        pass
        ...
```
although that may cause a lot of not-niceness with methods that return a new array, which will become accidentally un-wrapped.
Also unsure how such a system should behave on Dataset (probably shouldn't be there at all).

**Comment by max-sixty** [comment]
To what extent is asking people to call `da.data.chunksize` reasonable? Is the extra indirection all we'd we saving? (I don't use dask so this might seem naive)

**Comment by shoyer** [comment]
I think it's totally reasonable to ask people to write `da.data.chunksize`.

I would prefer to reserve writing wrappers for cases where we do some additional xarray-specific stuff, e.g., wrapping the result back in an xarray object. Even then, if we need more than a few wrappers I would consider putting them in an accessor namespace, e.g., `da.dask.chunksize`.
