### ISSUE TITLE
CI offline?

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#3366]
Azure pipelines is not being triggered by PRs this morning. See https://github.com/pydata/xarray/pull/3358 and https://github.com/pydata/xarray/pull/3365.

Last run was 12 hours ago.

**Comment by spencerahill** [comment]
Indeed, looks like Azure is having some problem: https://status.dev.azure.com/ 

Pipelines (in US only) listed as "degraded"

**Comment by spencerahill** [comment]
Looks like its back up and running now
