### ISSUE TITLE
Define a process to test the readthedocs CI before merging into master

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#3369]
This is an offshoot of #3358.

The readthedocs CI has a bad habit of failing even after the Azure Pipelines job "Docs" has succeeded.

After major changes that impact the documentation, and before merging everything into master, it would be advisable to explicitly verify that RTD builds correctly.

So far I tried to
1. create my own readthedocs project, https://readthedocs.org/projects/crusaderky-xarray/
2. point it to my fork https://github.com/crusaderky/xarray/
3. enable build for the branch I want to merge

This is currently failing because of an issue with versioneer, which incorrectly sets ``xarray.__version__`` to ``0+untagged.111.g6d60700``.
This in turn causes a failure in a minimum version check in ``pandas.DataFrame.to_xarray()`` on pandas>=0.25.

In the master RTD project https://readthedocs.org/projects/xray/, I can instead read ``xarray: 0.13.0+20.gdd2b803a``.

So far the only workaround I could find was to downgrade pandas to 0.24 in ``ci/requirements/doc.yml``.

**Comment by dcherian** [comment]
Maybe switch away from versioneer? https://github.com/pydata/xarray/issues/2853

**Comment by max-sixty** [comment]
We've had success with `setuptools_scm` internally, though not without any issues—in particular it has to be built in a git repo. Assuming that's the case, it requires very little maintainence. 

Anything I'm missing? I haven't used it in an OSS project

**Comment by crusaderky** [comment]
I've been using setuptools-scm in multiple other projects and it's great!
