### ISSUE TITLE
Add xr.unify_chunks top level method

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3371]
This should handle multiple DataArrays and Datasets. 

Implemented in #3276 as `Dataset.unify_chunks` and `DataArray.unify_chunks`

**Comment by max-sixty** [comment]
Should we have a separate namespace for backend-specific functions? Or we're coupled to dask enough that we may as well add to the top level?

**Comment by dcherian** [comment]
OK with either

**Comment by shoyer** [comment]
I think we are coupled enough to dask that we may as well add a top-level method/function.

I would lean towards `xarray.unify_chunks` rather than Dataset/DataArray methods for consistency with `xarray.align` and `xarray.broadcast`.

**Comment by dcherian** [comment]
But unlike `align` it makes sense to unify chunks of a dataset or dataarray because two variables may be chunked differently along the same dimension.
