### ISSUE TITLE
Dataset.to_netcdf netcdf4 bytes

### ISSUE THREAD

**Issue by gareth-j** [pydata/xarray#3372]
I understand that the `Dataset.to_netcdf` function will return bytes if no `path` is passed but will use the scipy backend for NetCDF creation and only supports version 3. Has anyone found a way of getting a NetCDF version 4 file as bytes?

**Comment by shoyer** [comment]
I agree this would be nice to have. In principle, this could be done with either netCDF4's diskless datasets (https://unidata.github.io/netcdf4-python/netCDF4/index.html#section15) or h5py/h5netcdf's support for Python file-like objects (http://docs.h5py.org/en/stable/high/file.html#python-file-like-objects).

**Comment by gareth-j** [comment]
OK, I'll have a go at a PR for this

**Comment by kmuehlbauer** [comment]
Dupe of #23.
