### ISSUE TITLE
implement normalize_token

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3378]
See https://github.com/pydata/xarray/pull/3276#discussion_r332113438

**Comment by dcherian** [comment]
How should this be implemented?

**Comment by crusaderky** [comment]
https://docs.dask.org/en/latest/custom-collections.html#implementing-deterministic-hashing

```python
@normalize_token.register(Dataset)
def tokenize_dataset(ds):
    return (Dataset, ds._variables, ds._coord_names, ds._attrs)

@normalize_token.register(DataArray)
def tokenize_dataarray(da):
    return (DataArray, ds._variable, ds._coords, ds._name)

@normalize_token.register(Variable)
def tokenize_variable(v):
    # Note: it's v.data, not v._data, in order to cope with the 
    # wrappers around NetCDF and the like
    return (Variable, v._dims, v.data, v._attrs)

# This is only a minor optimization: don't convert pd.Index to np.ndarray
@normalize_token.register(IndexVariable)
def tokenize_indexvariable(v):
    return (IndexVariable, v._dims, v._data.array, v._attrs)
```

You'll need to write a dummy normalize_token for when dask is not installed.

Unit tests:
- running tokenize() twice on the same object returns the same result
- changing the content of a data_var (or the variable, for DataArray) changes the output
- changing the content of a coord changes the output
- attrs, name, and dimension names change the output
- whether a variable is a data_var or a coord changes the output
- dask arrays aren't computed
- non-numpy, non-dask NEP18 data is not converted to numpy
- works with xarray's fancy wrappers around NetCDF and the like
