### ISSUE TITLE
Memory crash when assigning values with vectorized indexing

### ISSUE THREAD

**Issue by HamedAlemo** [pydata/xarray#3388]
#### Problem Description
I'm trying to assign values to a large DataArray using some vectorized indices (as explained in http://xarray.pydata.org/en/stable/indexing.html#assigning-values-with-indexing) but I get a memory problem. After doing several tests I noticed that there is a difference between `da[ind_x, ind_y]=new_value` and `da.values[ind_x, ind_y]=new_value`. The former (which is the method described in the doc) takes significantly more time and memory, while the latter works as good as numpy indexing.

The sample code below shows the difference between the two versions. Our challenge is that with larger arrays version 1 goes out of memory.

#### Code Sample
```python
# generate sample data array
data = np.random.randint(0, 17000, size=(50, 10, 45, 45), dtype='int16')
xr_da = xr.DataArray(data, dims=('t', 'band', 'y', 'x'))
# generate sample indices
x_i = np.random.randint(0, 45, 100, dtype='int16')
y_i = np.random.randint(0, 45, 100, dtype='int16')
band_i = np.random.randint(0, 10, 100, dtype='int16')
```

version 1:
```python
%timeit -n 10 xr_da[:, band_i, y_i, x_i]=0
```
```
17.1 s ± 260 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

version 2
```python
%timeit -n 10 xr_da.values[:, band_i, y_i, x_i]=0
```

```
66.9 µs ± 20 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Darwin
OS-release: 18.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.9
pandas: 0.24.2
numpy: 1.16.5
scipy: 1.3.1
netCDF4: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
PseudonetCDF: None
rasterio: None
iris: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: 2.2.3
cartopy: None
seaborn: None
setuptools: 40.6.2
pip: 19.0.3
conda: None
pytest: None
IPython: 7.4.0
sphinx: None
</details>

**Comment by shoyer** [comment]
These are performing two very different operations, corresponding to the difference between Xarray and NumPy's indexing behavior. Compare `xr_da[:, band_i, y_i, x_i].shape` vs `xr_da.values[:, band_i, y_i, x_i].shape`:
- The Xarray version is selecting the union of all matching indices. The result is a 4D array of shape `(50, 100, 100, 100)`.
- The NumPy version is selecting the intersection of all matching indices. The result is a 2D array of shape `(50, 100)`. Unsurprisingly, this is much faster.

You can achieve the later behavior if you want with xarray, but you have to index with DataArray objects with matching dimensions. See http://xarray.pydata.org/en/stable/indexing.html#vectorized-indexing for more details.

**Comment by HamedAlemo** [comment]
Stephan, 
Thanks for the clarification, it's very helpful to understand the different indexing mechanisms.
