### ISSUE TITLE
"How Do I..." formatting issues

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#3397]
@dcherian 
The new page http://xarray.pydata.org/en/stable/howdoi.html (#3357) is somewhat painful to read on readthedocs. The table goes out of the screen and one is forced to scroll left and right non stop.

Maybe a better alternative could be with Sphinx definitions syntax (which allows for automatic reflowing)?

```rst
How do I ...
============
Add variables from other datasets to my dataset?
    :py:meth:`Dataset.merge`
```
(that's a 4 spaces indent)

**Comment by max-sixty** [comment]
Hmmm. Here's what I see on a 15" Macbook on firefox—only fills about 2/3 of the screen horizontally. What's your setup @crusaderky ?

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5635139/66792612-85ab2800-eec7-11e9-97b1-518eb3eef424.png">

**Comment by dcherian** [comment]
Yeah, looks find on firefox on linux:
![image](https://user-images.githubusercontent.com/2448579/66848042-e8ea9800-ef63-11e9-9f06-907aad1ce22b.png)

I made changes to `style.css` in that PR to make it wrap: https://github.com/pydata/xarray/pull/3357/files

**Comment by shoyer** [comment]
It looks OK to me in Chrome, too.

**Comment by crusaderky** [comment]
Can't reproduce anymore. HTML inspection shows a wealth of external hrefs to readthedocs.org - CSS, javascript, etc. Most likely a transitory problem there.
