### ISSUE TITLE
With sel_points deprecated, how do you replace it?

### ISSUE THREAD

**Issue by cwerner** [pydata/xarray#3399]
#### MCVE Code Sample

```python
import numpy as np
import xarray as xr
da = xr.DataArray(np.arange(16).reshape((4,4)), coords=[('lat', [40,45,50,55]), ('lon', [5,10,15,20])])

points = da.sel_points(lat=[40.1, 42.3, 39.78], lon=[7.1, 6.2, 13.2], method='nearest')
for p in points:
    print(p)

```

#### Expected Output
This works fine < 0.13, but is now deprecated. I don't know (and cannot find an example in the docs) how one would replicate this with vectorised indexing?!?

I have to iterate over the returned points  as each will be exported into an XML element.
Note, that in my real code I work with a xr.Dataset with many variables instead of a simple 2d xr. DataArray)

#### Problem Description

I think this deprecation and the current docs will trip a lot of users using sel_points/ isle_points.

Any example how to replace the code with the current API is highly appreciated!

#### Output of ``xr.show_versions()``
<details>
# Paste the output here xr.show_versions() here
</details>

**Comment by fmaussion** [comment]
Hi, the docs is here: http://xarray.pydata.org/en/stable/indexing.html#more-advanced-indexing

So your example would read:

```python
import numpy as np
import xarray as xr
da = xr.DataArray(np.arange(16).reshape((4,4)), coords=[('lat', [40,45,50,55]), ('lon', [5,10,15,20])])

points = da.sel(lat=xr.DataArray([40.1, 42.3, 39.78], dims='z'), 
                lon=xr.DataArray([7.1, 6.2, 13.2], dims='z'), 
                method='nearest')
```

Arguably, the "more advanced indexing" title could be renamed to something more explicit.

**Comment by cwerner** [comment]
Great!

Seems I was simply missing the new dim *z* in my attempts. Could not translate to the new format... Thanks a bunch!!!
