### ISSUE TITLE
Allow ellipsis in place of xr.ALL_DIMS?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#3414]
@crusaderky had a [good idea](https://github.com/pydata/xarray/issues/1081#issuecomment-540477534) to allow ellipsis (`...`) as a placeholder for 'other dims' in transpose.

What about using it as a placeholder for `xr.ALL_DIMS` in groupby etc operations? I find it nicer than custom sentinel values, and I think should be fairly low-confusion—thoughts?

**Comment by dcherian** [comment]
Sounds great to me

**Comment by shoyer** [comment]
+1 for setting `ALL_DIMS = ...`. That's much more ergonomic.
