### ISSUE TITLE
Attributes are dropped after `clip` even if `keep_attrs` is True

### ISSUE THREAD

**Issue by mraspaud** [pydata/xarray#3433]
#### MCVE Code Sample

```python
import xarray as xr
import numpy as np

arr = xr.DataArray(np.ones((5, 5)), attrs={'units': 'K'})
xr.set_options(keep_attrs=True)
arr
# <xarray.DataArray (dim_0: 5, dim_1: 5)>
# array([[1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.]])
# Dimensions without coordinates: dim_0, dim_1
# Attributes:
#     units:    K

arr.clip(0, 1)
# <xarray.DataArray (dim_0: 5, dim_1: 5)>
# array([[1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1.]])
# Dimensions without coordinates: dim_0, dim_1

```

#### Expected Output
I would expect the attributes to be kept

#### Problem Description
`keep_attrs` set to `True` doesn't seem to be respected with the `DataArray.clip` method.

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1062.1.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.6.2

xarray: 0.14.0
pandas: 0.25.1
numpy: 1.17.0
scipy: 1.3.0
netCDF4: 1.5.1.2
pydap: None
h5netcdf: 0.7.4
h5py: 2.10.0
Nio: None
zarr: 2.3.2
cftime: 1.0.3.4
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.0.28
cfgrib: None
iris: None
bottleneck: None
dask: 2.6.0
distributed: 2.6.0
matplotlib: 3.1.1
cartopy: 0.17.0
seaborn: None
numbagg: None
setuptools: 41.4.0
pip: 19.3
conda: None
pytest: 5.0.1
IPython: 7.8.0
sphinx: 2.2.0
</details>

**Comment by dcherian** [comment]
Thanks @mraspaud 

`clip` and other injected functions need to be updated to obey `keep_attrs` (also see https://github.com/pydata/xarray/issues/3348)

https://github.com/pydata/xarray/blob/72be873857a0a56659c905ce491ca1f94b44fd5c/xarray/core/ops.py#L321-L349

Are you up for sending in a PR?

**Comment by mraspaud** [comment]
Sure! What do you reckon the default should be ? False for backwards compatibility ?

**Comment by mraspaud** [comment]
ooh, maybe I answered too fast. I hadn't really looked at the code yet... but let's see:
f I understand correctly, in the function you cited, the functions get wrapped and include in the current `cls`. So I would need to fix the wrapper itself (`_func_slash_method_wrapper`) so that the attrs get copied and applied to the resulting array. However, do we have a guarantee that the wrapped functions are actually returning something that can have a `.attrs` ?

**Comment by dcherian** [comment]
I don't think so. You'll have to check which functions are used to inject methods on groupby, resample and rolling objects (at least)

**Comment by mraspaud** [comment]
Ok, then I probably won't have the time to dig into this for now, sorry. If someone else with better knowledge of the code can work on this it would probably be for the best.
