### ISSUE TITLE
1D DataArray

### ISSUE THREAD

**Issue by berceanu** [pydata/xarray#3478]
I can’t seem to find any examples for building a 1D DataArray y with one coordinate x, that would be the representation of y = f(x).

**Comment by keewis** [comment]
does this do what you described?
```python
da = xr.DataArray(name="y", data=[0, 1, 2], dims="x", coords={"x": list("abc")})
```
where only `data` is required

**Comment by berceanu** [comment]
Yes, this does the trick! On a related note, can I define the coords of a N-d array to be DataArrays themselves? Let me exemplify. Rather than doing this:

```python
    radiation = xr.DataArray(
        data=spectrum,
        dims=["k", "theta", "phi"],
        coords=dict(
            k=spectrum.grid.k, theta=spectrum.grid.theta, phi=spectrum.grid.phi
        ),
        attrs=dict(long_name="radiation", units="units"),
    )
    radiation.k.attrs["units"] = "units"
    radiation.theta.attrs["units"] = "rad"
    radiation.phi.attrs["units"] = "rad"
```
I would like to first define `k`, `theta` and `phi` separately, together with their associated units, and then pass them on when constructing the 3D `radiation` DataArray.

**Comment by jhamman** [comment]
> On a related note, can I define the coords of a N-d array to be DataArrays themselves

Yes, just replace `k=spectrum.grid.k` with `k=xr.DataArray(...)`

**Comment by berceanu** [comment]
Without specifying any dims or coords for `k`, right?

**Comment by jhamman** [comment]
No, you'd want to specify the dims that are associated with the k coordinate.

**Comment by jhamman** [comment]
No, you'd want to specify the dims that are associated with the k coordinate.

**Comment by berceanu** [comment]
But k is just a one dimensional array. Do you mean
k=xr.DataArray(...dims='k')
