### ISSUE TITLE
geo raster accessor

### ISSUE THREAD

**Issue by shaharkadmiel** [pydata/xarray#3482]
Hi, I have put together a very [simple package](https://github.com/shaharkadmiel/rasterx) that provides a universal `read` function for reading various raster formats including of course netCDF but also any other format that gdal or rasterio can recognize. This read function can also handle merging several tiles into one dataset.

In addition, the package provides a `.geo` dataset accessor that currently adds trimming functionality to extract a geographical subset of the data.

I plan to also add reprojection and spatial resampling methods which will wrap either rasterio functionality or directly use gdal's api.

I hope this is of interest to the geosciences community and perhaps even a broader community.

Contributions and any other input from others is of course welcome.

Have a quick look at the [**Demo section**](https://github.com/shaharkadmiel/rasterx#demo) in the readme file to get some ideas as to what this package can do for you.

**Comment by dcherian** [comment]
Looks like the discussion is at https://github.com/corteva/rioxarray/issues/4 now
