### ISSUE TITLE
Sum over multiple dimension breaks for groupby object (since Xarray 0.14.0)

### ISSUE THREAD

**Issue by shofer16450** [pydata/xarray#3488]
#### MCVE Code Sample

```python
import xarray
import pandas as pd

time = pd.date_range('1950-01-01', '1960-12-31', freq='D')
length = len(time)

x = np.arange(0,100,2) # x coords
y = np.arange(0,200,2) # y coords
data = np.random.rand(3,length,100,50)
mask = np.random.rand(100,50)
ds = xr.Dataset({'SMB': (['TIME', 'Y21_199', 'X10_105'],  data[0,:,:,:]),
                 'RU':  (['TIME', 'Y21_199', 'X10_105'],  data[1,:,:,:]),
                 'ME':  (['TIME', 'Y21_199', 'X10_105'],  data[2,:,:,:])},
                 coords={'X10_105': (['X10_105'], x),
                         'Y21_199': (['Y21_199'], y),
                         'TIME': time})

# THIS FAILS
early = ((ds.SMB.loc['1950':'1955']*mask).groupby('TIME.dayofyear')
         .sum(dim=[xr.ALL_DIMS]))

 # THIS FAILS AS WELL
early = ((ds.SMB.loc['1950':'1955']*mask).groupby('TIME.dayofyear')
        .sum(dim=['X10_105','Y21_199','TIME']))

# THIS PRODUCES EXPECTED BEHAVIOR
early = ((ds.SMB.loc['1950':'1955']*mask).groupby('TIME.dayofyear')
        .sum('TIME').sum('X10_105').sum('Y21_199'))

```

#### Expected Output
<xarray.DataArray 'SMB' (dayofyear: 366)>

#### Problem Description
Yesterday I updated to the latest version of xarray and now the sum(dim=['dim1','dim2',..] over a groupby('TIME.dayofyear') object yields an error, despite it working with my older version of xarray
```python
error cannot reduce over dimension ['X10_105', 'Y21_199', 'TIME']. expected either xarray.ALL_DIMS to reduce over all dimensions or one or more of ('TIME', 'Y21_199', 'X10_105').
```
which is weird given that I'm providing all of the dimensions that are in the dataset. I've tried changing the order of the dimension, using ```xr.ALL_DIMS``` as suggested by the error message. The only workaround for me at the moment is to sequentially sum over the intended dimensions, which works for some reason.

#### Output of ``xr.show_versions()``
<details>
commit: None
python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-66-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.6.2

xarray: 0.14.0
pandas: 0.25.3
numpy: 1.17.3
scipy: 1.2.1
netCDF4: 1.5.1.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.7.1
iris: None
bottleneck: None
dask: 1.1.5
distributed: 1.26.1
matplotlib: 3.0.3
cartopy: 0.17.0
seaborn: 0.9.0
numbagg: None
setuptools: 41.0.1
pip: 19.2.1
conda: None
pytest: None
IPython: 7.7.0
sphinx: None

</details>

**Comment by shofer16450** [comment]
Potential change in behavior due to the following?

```The default behaviour of reducing across all dimensions for DataArrayGroupBy objects has now been properly removed as was done for DatasetGroupBy in 0.13.0 (GH3337). Use xarray.ALL_DIMS if you need to replicate previous behaviour. Also raise nicer error message when no groups are created (GH1764). By Deepak Cherian.```

**Comment by keewis** [comment]
to get the `ALL_DIMS` example working, try
```python
early = ((ds.SMB.loc['1950':'1955']*mask).groupby('TIME.dayofyear')
         .sum(dim=xr.ALL_DIMS))
```
(don't put `ALL_DIMS` in a list)

I think that your second example fails because of a bug in `DatasetGroupBy`.

**Comment by dcherian** [comment]
Thanks for filing the issue @shofer16450 . This is a bug and is fixed on master. Hopefully we can release soon.
