### ISSUE TITLE
Pseudonetcdf engine with Mfdataset using multiple csv files 

### ISSUE THREAD

**Issue by ArmanAttaran** [pydata/xarray#3503]
Hello,
I am attempting to open about 50 csv, each represents monthly data and I would like to open them all in xarray. 
unfortunately it is not working and I have included the code and error, any help would be appreciated it 

````
 import xarray as xr

xr.open_mfdataset('C:/Users/*.csv', concat_dim="time",
                  data_vars='minimal', coords='minimal', compat='override',engine='pseudonetcdf',
                  backend_kwargs={'format': 'csv'})

```
DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  file, _ = self._acquire_with_cache_info(needs_lock)
```

**Comment by dcherian** [comment]
This looks like you need to specify some more `backend_kwargs`. https://github.com/barronh/pseudonetcdf/issues might be a better place to ask this question.

**Comment by ArmanAttaran** [comment]
Thank you !!!! i'll post it
