### ISSUE TITLE
xr.plot infers sequential colormap on diverging levels

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#3524]
#### MCVE Code Sample

```python
import numpy as np
import xarray as xr

data = np.random.randn(10, 10)
data = np.abs(data)

da = xr.DataArray(data)

# returns a diverging colormap
da.plot(vmax=2, center=0, extend="both")

# returns a sequential colormap
da.plot(levels=[-2, -1, 0, 1, 2], extend="both")



```

![tst](https://user-images.githubusercontent.com/10194086/68801234-f32fad00-065b-11ea-81c8-b7d0efbf57c4.png)

#### Expected Output

A diverging colormap, maybe?

#### Problem Description
I was surprised by getting the viridis colormap until I realised that my data must all be positive and the colormap is infered from the data and not from levels. However, when specifying the range via `vmax=2, center=0` it is not inferred from the data.

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.12.14-lp151.28.25-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.14.0+44.g4dce93f1
pandas: 0.25.2
numpy: 1.17.3
scipy: 1.3.1
netCDF4: 1.5.0.1
pydap: None
h5netcdf: 0.7.4
h5py: 2.9.0
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: 1.2.0
PseudoNetCDF: None
rasterio: 1.0.22
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: 2.6.0
distributed: 2.6.0
matplotlib: 3.1.1
cartopy: 0.17.0
seaborn: 0.9.0
numbagg: None
setuptools: 41.4.0
pip: 19.3.1
conda: None
pytest: 5.2.2
IPython: 7.9.0
sphinx: 2.2.1

</details>

**Comment by dcherian** [comment]
hmm... it's also weird if you specified `vmax=2, vmax=-2`. For some reason, auto-inferred colormaps are disabled in that case.

Here's where you should look if you want to jump in :)
https://github.com/pydata/xarray/blob/810345c4564a2bc15bf1b4c7ba4c4840238f1e82/xarray/plot/utils.py#L141-L154

**Comment by shoyer** [comment]
It might be worth taking a look at updating our heuristics. They were originally copied from seaborn, but seaborn has since updated them to something a little different.
