### ISSUE TITLE
Creating conda environment as described in the contributing guidelines gives ResolvePackageNotFound error

### ISSUE THREAD

**Issue by r-beer** [pydata/xarray#3549]
#### MCVE Code Sample

Following the [contributing to xarray guidelines](http://xarray.pydata.org/en/stable/contributing.html#creating-a-python-environment) I tried to create the xarray-test environment as follows:
```bash
# Create and activate the build environment
conda env create -f ci/requirements/py36.yml
```

#### Expected Output
Creates conda environment, such that `conda activate xarray-tests` can be used to activate it.

#### Problem Description

The creation of the conda environment fails, indicating `ResolvePackageNotFound ` error:
```bash
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - pynio
  - cdms2
```

After some searching I tried to first create the conda environment and subsequently updating it

```bash
conda env update -f ci/requirements/py36.yml
```
but this resulted in the same error:

```bash
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - pynio
  - cdms2
```

#### Output of ``xr.show_versions()``
Doesn't make sense for this issue, does it?

**Comment by crusaderky** [comment]
Those packages don't exist on Windows. You need to use ``py37-windows.yml`` instead. I'll update the documentation to clarify.

**Comment by r-beer** [comment]
Thanks for the fast response @crusaderky!
