### ISSUE TITLE
doc\environment.yml not found

### ISSUE THREAD

**Issue by r-beer** [pydata/xarray#3556]
#### MCVE Code Sample

I would like to contribute to the xarray documentation.

Therefore, I tried to install the `xarray-docs` environment as described in the [contributing guidelines](http://xarray.pydata.org/en/stable/contributing.html#requirements):
```bash
# Create and activate the docs environment
conda env create -f doc/environment.yml
```

#### Expected Output

Creates the `xarray-docs` environment such that it can be activated.

#### Problem Description

```bash
EnvironmentFileNotFound: '...\xarray\doc\environment.yml' file not found
```

#### Output of ``xr.show_versions()``

**xarray: 0.14.1+11.ga4d04466**

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: 4.6.1

xarray: 0.14.1+11.ga4d04466
pandas: 0.25.3
numpy: 1.17.3
scipy: 1.3.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.1.1
cartopy: None
seaborn: None
numbagg: None
setuptools: 41.6.0.post20191030
pip: 19.3.1
conda: None
pytest: 5.2.4
IPython: 7.9.0
sphinx: None
</details>

**Comment by dcherian** [comment]
Hi @r-beer looks like it has moved to `ci/requirements/doc.yml`. Can you fix that as part of your docs update? :)

**Comment by jthielen** [comment]
I think this was already updated in https://github.com/pydata/xarray/pull/3410? Here's what I see in the contributing guidelines:

![](https://screenshotscdn.firefoxusercontent.com/images/65ee33ef-b93f-4d6f-b082-bd27a7da82c4.png)

**Comment by r-beer** [comment]
> 
> 
> I think this was already updated in #3410? Here's what I see in the contributing guidelines:
> 
> ![](https://camo.githubusercontent.com/b7872888b93c16cc02a4a985b3d93ffcfba3fed4/68747470733a2f2f73637265656e73686f747363646e2e66697265666f7875736572636f6e74656e742e636f6d2f696d616765732f36356565333365662d623933662d346436662d623038322d6264323761376461383263342e706e67)

Ok, thanks for the information. I followed the official guidelines, but will double-check with the dev version from now on.

**Comment by jthielen** [comment]
@r-beer That's strange, could it be a browser cache issue? I took the screenshot from the stable version of the docs (http://xarray.pydata.org/en/stable/contributing.html#requirements).

**Comment by r-beer** [comment]
> 
> 
> @r-beer That's strange, could it be a browser cache issue? I took the screenshot from the stable version of the docs (http://xarray.pydata.org/en/stable/contributing.html#requirements).

Indeed, I deleted the cache and the documentation refreshed. Thanks!

**Comment by r-beer** [comment]
PS: Environment creation worked flawlessly. It's a pleasure to get into xarray contribution, thanks to you guys! 😃
