### ISSUE TITLE
environment file for binderized examples

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3563]
Our examples now have binder links! e.g. https://xarray.pydata.org/en/latest/examples/ERA5-GRIB-example.html

but this is suboptimal because we aren't defining an environment so the only things that get installed are the packages that xarray requires : numpy & pandas. We need to at least add cfgrid, matplotlib, cftime, netCDF4 to get all the examples to work out of the box.

**Comment by ocefpaf** [comment]
@dcherian it is very experimental but [`nbrr`](https://github.com/pyoceans/nbrr) can probably help you setup the `environment.yaml` file with a single command.

**Comment by scottyhq** [comment]
Awesome @dcherian ! I like the approach of defining a binder environment then pulling the examples directory into the binder session with [nbgitpuller](https://github.com/jupyterhub/nbgitpuller). There are options for where to store the binder environment config (1) master branch .binder, 2) a new branch called 'binder', or 3) even a separate repo... maybe pydata/xarray-binder-env - see https://github.com/scottyhq/repo2docker-githubci  ?

**Comment by max-sixty** [comment]
Not in reference to this exact issue, but the binder functionality is really awesome! Well done!

**Comment by mrocklin** [comment]
You're probably already aware, but https://examples.dask.org and https://github.com/dask/dask-examples might be a nice model to look at.

**Comment by dcherian** [comment]
Thanks all. Now we just need some one to volunteer to do this :)

**Comment by jhamman** [comment]
See https://github.com/pydata/xarray/pull/3568 for a basic environment that should do the trick. Going forward, I think it would be nice to split these out into a separate repo. Let's save that for https://github.com/pydata/xarray/issues/2378.
