### ISSUE TITLE
Drawing only one contour in FacetGrid

### ISSUE THREAD

**Issue by kuchaale** [pydata/xarray#3569]
#### MCVE Code Sample

```python
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr

x, y = np.meshgrid(np.arange(12), np.arange(12))
z = xr.DataArray(np.sqrt(x**2 + y**2))
z2 = xr.DataArray(np.sqrt(x**2 + y**2)+1)
ds = xr.concat([z,z2], dim = 'time')
ds['time'] = [0,1]

f, ax = plt.subplots()
ds[0].plot.contour(ax = ax, levels=[4], colors=['k'])
f, ax = plt.subplots()
ds[1].plot.contour(ax = ax, levels=[4], colors=['k'])
ds.plot.contour(col = 'time', levels=[4], colors=['k'])
```

#### Output
![obrazek](https://user-images.githubusercontent.com/6815953/69541063-8f28b500-0f88-11ea-805c-8478f49a0fd2.png)

#### Expected Output
![obrazek](https://user-images.githubusercontent.com/6815953/69546120-6528c000-0f93-11ea-8873-71cab41eaade.png)

#### Problem Description
While drawing only one contour was fixed some time ago ([#866](https://github.com/pydata/xarray/issues/866)), single contour plots in FacetGrid do not work for me.

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-65-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.2
libnetcdf: 4.6.3

xarray: 0.14.1
pandas: 0.24.2
numpy: 1.17.3
scipy: 1.2.1
netCDF4: 1.5.1.2
pydap: installed
h5netcdf: 0.7.4
h5py: 2.9.0
Nio: None
zarr: 2.3.2
cftime: 1.0.3.4
nc_time_axis: 1.2.0
PseudoNetCDF: None
rasterio: 1.0.5
cfgrib: 0.9.6.2
iris: None
bottleneck: 1.2.1
dask: 2.6.0
distributed: 2.6.0
matplotlib: 3.0.3
cartopy: 0.16.0
seaborn: 0.9.0
numbagg: None
setuptools: 41.0.1
pip: 19.3.1
conda: None
pytest: 4.4.1
IPython: 7.1.1
sphinx: 2.0.1
</details>

**Comment by dcherian** [comment]
Thanks for the report. I'll mark this as a bug. PRs welcome!
