### ISSUE TITLE
DataArray.transpose cannot handle Ellipsis

### ISSUE THREAD

**Issue by DerWeh** [pydata/xarray#3583]
While the documentation about [reshaping](http://xarray.pydata.org/en/stable/reshaping.html#reordering-dimensions) indicates that an Ellipsis can be used for `DataArray.transpose`, this is actually not the case:

```python
    def transpose(self, *dims: Hashable, transpose_coords: bool = None) -> "DataArray":
        if dims:
            if set(dims) ^ set(self.dims):
                raise ValueError(
                    "arguments to transpose (%s) must be "
                    "permuted array dimensions (%s)" % (dims, tuple(self.dims))
                )
```

On a site note, as long as `transpose_coords` defaults to `None`, it should be at least stated in the doc string that its current default is equal to `False`.

#### Output of ``xr.show_versions()``
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.16.0-10-amd64
machine: x86_64
processor:
byteorder: little
LC_ALL:
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.14.0
pandas: 0.25.0
numpy: 1.16.4
scipy: 1.3.0
netCDF4: None
pydap: None
h5netcdf: 0.7.4
h5py: 2.9.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.3.0
distributed: 2.3.0
matplotlib: 3.0.3
cartopy: None
seaborn: None
numbagg: None
setuptools: 41.0.1
pip: 19.1.1
conda: 4.7.11
pytest: 5.0.1
IPython: 7.5.0
sphinx: 2.2.1

</details>

**Comment by shoyer** [comment]
Good catch! We should fix this. `data_array.transpose(...)` should be valid (basically a no-op).

**Comment by keewis** [comment]
I think that's because the docs you link to refer to 0.14.1 while you have 0.14.0 installed. The support for Ellipsis is a recent addition; `data_array.transpose(...)` should work.

**Comment by max-sixty** [comment]
As @keewis states, you need to upgrade xarray. Unless I'm missing something, that behavior is valid:

```python


In [25]: da.transpose(...)
Out[25]:
<xarray.DataArray (x: 2, y: 2)>
array([[ 1.,  2.],
       [nan, nan]])
Dimensions without coordinates: x, y
```

**Comment by max-sixty** [comment]
Please reopen if necessary, cheers @DerWeh

**Comment by DerWeh** [comment]
I am very sorry, I didn't realize that there had been a new release. Everything is fine after updating.

**Comment by keewis** [comment]
your remark concerning the documentation not being clear about the default value of `transpose_coords` is still valid, though. It is used as a boolean, so the current default (which is `None` until the deprecation cycle is completed) evaluates to `False`. I think we should update the documentation?

**Comment by max-sixty** [comment]
No stress @DerWeh ! Please keep putting issues in; most of the time it'll be us :)

Agreed @keewis
