### ISSUE TITLE
Autocomplete in registered accessors

### ISSUE THREAD

**Issue by rdoyle45** [pydata/xarray#3614]
At present if you use `register_dataset_accessor()` or `register_dataarray_accessor()`, ipython can not autocomplete to function within that accessor. For example:

#### MCVE Code Sample

```python
import xarray as xr

@xr.register_dataset_accessor('geo')
class GeoAccessor:
    def __init__(self, xarray_obj):
        self._obj = xarray_obj

    @property
    def center(self):
        # return the geographic center point of this dataset
        lon = self._obj.latitude
        lat = self._obj.longitude
        return (float(lon.mean()), float(lat.mean()))

    def plot(self):
        # plot this array's data on a map, e.g., using Cartopy
        pass

```

#### Expected Output

It would be good if in ipython when pressing TAB `data.geo.c ` would autocomplete to `data.geo.center()`.   

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.5 (default, Oct 17 2019, 12:16:48) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
python-bits: 64
OS: Linux
OS-release: 5.3.12-300.fc31.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_IE.UTF-8
LOCALE: en_IE.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.3

xarray: 0.14.1
pandas: 0.25.3
numpy: 1.17.4
scipy: 1.2.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.9.0
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.9.0
distributed: None
matplotlib: 3.1.2
cartopy: None
seaborn: None
numbagg: None
setuptools: 42.0.2
pip: 19.1.1
conda: None
pytest: None
IPython: 7.10.1
sphinx: None
</details>

**Comment by benbovy** [comment]
That would be great if it could work in ipython and elsewhere too (e.g., IDEs, etc.). I guess it might be worth having a look at [jedi](https://github.com/davidhalter/jedi) and see if this could be easily fixed.

**Comment by keewis** [comment]
This already works for me in a IPython shell (`jedi 0.15.1`, `ipython 7.9.0`):
```python
In [1]: import xarray as xr 
   ...: import numpy as np                                                                                                                                                                                                      

In [2]: @xr.register_dataset_accessor("geo")  
   ...: class GeoAccessor:  
   ...:     def __init__(self, xarray_obj):  
   ...:         self._obj = xarray_obj  
   ...:       
   ...:     @property  
   ...:     def center(self):  
   ...:         # return the geographic center point of this dataset  
   ...:         lon = self._obj.latitude  
   ...:         lat = self._obj.longitude  
   ...:         return (float(lon.mean()), float(lat.mean()))  
   ...:    
   ...:     def plot(self):  
   ...:         # plot this array's data on a map, e.g., using Cartopy  
   ...:         pass 
   ...:                                                                                                                                                                                                                         

In [3]: ds = xr.Dataset( 
   ...:     data_vars={"a": (("latitude", "longitude"), np.linspace(0, 1, 5 * 10).reshape(5, 10))}, 
   ...:     coords={"latitude": np.arange(5), "longitude": np.arange(10)}, 
   ...: )                                                                                                                                                                                                                       

In [4]: # ds.geo.c<TAB>:
   ...: ds.geo.center
Out[4]: (2.0, 4.5)
```
Am I missing something?

**Comment by rdoyle45** [comment]
I can reproduce your first code perfect fine in ipython, with autocomplete. However, we're defining an accessor in ipython. It seems if an accessor is used in a module and that module imported to ipython the autocomplete doesn't work. It's like ipython can't "see" the functions in the accessor's class until runtime.

**Comment by keewis** [comment]
that works for me, too. I moved the accessor code into a file, then imported it:
```python
In [1]: import xarray as xr
   ...: import numpy as np
   ...: import custom_accessor

In [2]: ds = xr.Dataset(
   ...:     {"a": (("latitude", "longitude"), np.linspace(0, 1, 5 * 10).reshape(5, 10))},
   ...:     coords={"latitude": np.arange(5), "longitude": np.arange(10)},
   ...: )

In [3]: # ds.geo.c<TAB>
   ...: ds.geo.center
Out[3]: (2.0, 4.5)
```
It also works with the builtin `str`, `dt` and `plot` `DataArray` accessors (just not if I'm trying to access the `DataArray`s from a `Dataset` as described above).

**Comment by rdoyle45** [comment]
You are right. The autocomplete does work. I had a problem in my script.

**Comment by benbovy** [comment]
Autocomplete indeed works in ipython, but it doesn't seem to work for accessors in my emacs configuration (`lsp-mode` / `lsp-python-ms` / `python-language-server`). I haven't checked in VSCode / LSP. I'll investigate this later, it's likely an issue external to xarray.
