### ISSUE TITLE
applying ufunc over lon and lat 

### ISSUE THREAD

**Issue by mada0007** [pydata/xarray#3632]
I am trying to apply ufunc to my code to speed it up. Currently I am looping over lon and lat and it takes ages. After long reads I came up with this though am still not sure where I a going wrong. Suggestions and Ideas would be very helpful to get me going. thanks

``` python
def get_grps(s, thresh=-1, Nmin=3):
    """
    Nmin : int > 0
        Min number of consecutive values below threshold.
    """
    s = pd.Series(s)
    m = np.logical_and.reduce([s.shift(-i).le(thresh) for i in range(Nmin)])
    if Nmin > 1:
        m = pd.Series(m, index=s.index).replace({False: np.NaN}).ffill(limit=Nmin-1).fillna(False)
    else:
        m = pd.Series(m, index=s.index)

    # Form consecutive groups
    gps = m.ne(m.shift(1)).cumsum().where(m)

    # Return None if no groups, else the aggregations
    if gps.isnull().all():
        return [0]
    else:
        d = s.groupby(gps).agg([list, sum, 'size']).reset_index(drop=True)

        data = np.sum((d['size']))

        return data
```

     obj is 3d data of shape (324x180x360) (time,lat,lon) 

``` python
def consec_events(obj):

      time_nums = xr.DataArray(obj['time'].values.astype(np.float),
                             dims='time',
                             coords={'time': obj['time']},
                             name='time_nums')
       trend = xr.apply_ufunc(get_grps,time_nums, obj,
                           vectorize=True,
                           input_core_dims=[['time'], ['time']],
                           output_core_dims=[[]],
                           output_dtypes=[np.float],
                           dask='parallelized',output_sizes={'ntime':time_nums.shape[0]})

    return trend

results = consec_events(spi)
```

### ERROR IS HERE

```
...  File "/Users/mada0007/anaconda3/envs/RESEARCH_QUESTION_TWO/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2157, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)
  File "/Users/mada0007/anaconda3/envs/RESEARCH_QUESTION_TWO/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2221, in _vectorize_call_with_signature
    output[index] = result
ValueError: setting an array element with a sequence.
```

I am relatively new to apply this and I have been reading quite a lot. I would appreciatiate if I can be corrected on how to properly apply this over time dimension of my data and get resulting 2d array for each lon and lat?

**Comment by dcherian** [comment]
I would use `%debug` and inspect what `index` and `result` look like. It's hard to debug without a minimal example.

**Comment by mada0007** [comment]
hi dcherian, I have tried that without any success. I was how to really apply the unfunc on a function to work over time for a 3D gridded dataset?

**Comment by mada0007** [comment]
I just check the shape of the output is 180 x 360 and results is [0]

output.shape = (180, 360)
result = [0]

**Comment by mada0007** [comment]
I found the solution, apparent results is stored as a list event thought its just a single number and then the program interprets this as having more than one element which cant be store in output. 

Solution was to convert results into numpy array in the original code and then it works.

The code is still not as fast as I would wish though.

**Comment by mathause** [comment]
Maybe the code here does something similar to what you want:

https://github.com/pydata/xarray/blob/f2b2f9f62ea0f1020262a7ff563bfe74258ffaa1/xarray/core/missing.py#L17

``` python
import numpy as np
import xarray as xr
from xarray.core import missing as xrmissing

data = [0, -2, -2, -2, 0, -2, -2, 0]
da = xr.DataArray(data, coords=dict(time=np.arange(8)), dims=["time"])
dlt = da < 0
xrmissing._get_nan_block_lengths(dlt.where(~ dlt), "time", dlt.time)

```
