### ISSUE TITLE
Ipcc srex regions updated 

### ISSUE THREAD

**Issue by mada0007** [pydata/xarray#3650]
There has been updated to IPCC srex regions which has not yet been implemented in xarray I think.

In particular I am looking for how I can subset this new cordinate for CENTRAL africa 

AFRICA;Central-Africa;CAF; 8,-10.0;  8,0;   15.0,14.7;   27.0,14.7;   27.0,-10.0;;;;;;;;;

Values on the right are longitudes and values on the left are lattitudes respectively.

**Comment by mathause** [comment]
Has there ever been an implementation of regions in xarray? What are you refering to?

Also there has not been any change to the SREX regions. There are, however, new regions defined for the IPCC AR6 report - do you mean them? Have a look here: https://github.com/mathause/regionmask/pull/61 (disclaimer: I am the author of the package).
