### ISSUE TITLE
How to handle 2d latitude and longitude coordinates within DataArray creation

### ISSUE THREAD

**Issue by meteoDaniel** [pydata/xarray#3661]
#### MCVE Code Sample

```python
frames_z.shape -> (25, 1100, 900)
grid[:, :, 1].shape -> (1100, 900)
grid[:, :, 0].shape -> (1100, 900)

xarray.DataArray(frames_z, coords={'time': timestamps, 'latitude':grid[:, :, 1],'longitude': grid[:, :, 0]}, dims=['time', 'latitude', 'longitude']) 

```

#### Expected Output
Array with latitude and longitude as coordinates. 

#### Problem Description

 I am receiving following error message: 

```
MissingDimensionsError: cannot set variable 'latitude' with 2-dimensional data without explicit dimension names. Pass a tuple of (dims, data) instead.
```
And I tried several ways of defining coords and dims but it always fails. 
#### Output of ``xr.show_versions()``
<details>
# Paste the output here xr.show_versions() here
xarray==0.11.3

</details>

**Comment by meteoDaniel** [comment]
I got the solution by my own: 

```
xarray.DataArray(self.predicted_frames_z,coords={"time": timestamps, "latitude": (["x","y"], self.grid[:, :, 1]),
                          "longitude": (["x","y"], self.grid[:, :, 0])},
                  dims=["time", "x","y"])
``` 

Would be great to have such an example in the documentation. Can you tell me how to contribute this to the documentation?

**Comment by pierreloicq** [comment]
For people of the future: the doc is here : http://xarray.pydata.org/en/stable/user-guide/data-structures.html
search for this line "As a dictionary with coords across multiple dimensions:"

**Comment by ghossh** [comment]
> I got the solution by my own:
> 
> ```
> xarray.DataArray(frames_z,coords={"time": timestamps, "latitude": (["x","y"], grid[:, :, 1]),
>                           "longitude": (["x","y"], grid[:, :, 0])},
>                   dims=["time", "x","y"])
> ```
> 
> Would be great to have such an example in the documentation. Can you tell me how to contribute this to the documentation?

Thanks. This helped me.
