### ISSUE TITLE
Select on 2 dimensional indices/How to define indices correctly?

### ISSUE THREAD

**Issue by meteoDaniel** [pydata/xarray#3662]
#### MCVE Code Sample

```python
ds = xarray.tutorial.open_dataset('rasm').load() 
ds.sel(yc=50, xc=50, method='nearest') 

```

#### Expected Output
An interpolated timeseries of data closest to 50, 50. 

#### Problem Description

How do I have to define the indices that I can select on multi dimensional indices? 

#### Output of ``xr.show_versions()``
<details>
# Paste the output here xr.show_versions() here
xarray==0.11.3
</details>

**Comment by meteoDaniel** [comment]
Is anybody able to answer this question?

**Comment by dcherian** [comment]
This is not possible right now unfortunately. It should be possible to implement once #1603 is done.

In the mean time, you could use `where` (https://xarray.pydata.org/en/stable/indexing.html#masking-with-where)
