### ISSUE TITLE
rolling.construct alignment

### ISSUE THREAD

**Issue by mark-boer** [pydata/xarray#3671]
Hello xarray team

I was trying to implement functionality similar to Scikit Image's  [view_as_windows](https://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.view_as_windows), but I was having a hard time with the boundary conditions. I understand this request is very similar to rolling with periodic boundary conditions #2007.

#### MCVE Code Sample
```python
>>> arr = xr.DataArray(np.arange(4), dims=("x",))
>>> arr.rolling(x=2).construct("roll_x", stride=2)
<xarray.DataArray (x: 2, roll_x: 2)>
array([[nan,  0.],
       [ 1.,  2.]])
Dimensions without coordinates: x, roll_x
```

#### Expected Output
It would be nice to be able to easily get an output of:
```python
<xarray.DataArray (x: 2, roll_x: 2)>
array([[0., 1.],
       [2., 3.]])
Dimensions without coordinates: x, roll_x
```

#### Possible workarounds
With the upcoming features of pad (#3596) and rolling: periodic (#2011) it is actually not that hard to work around with:

```python
arr.pad(x=(1,0)).rolling(x=2).construct("roll_x", stride=2).isel(x=slice(1,None))
# or
arr.roll(x=-1).rolling(x=2, boundary="periodic").construct("roll_x", stride=2)
```

#### Idea
Would it be possible to add a keyword argument to either `rolling()` or `construct()` that expects an alignment of "left", "right" or "center". I understand that this could break interface copied from Pandas, but I hope it could be useful to others as well.

**Comment by mark-boer** [comment]
Small update:

I was currently using:
```
data = (
    data.rolling(x=window_size ).construct("roll_x")
    .rolling(y=window_size ).construct("roll_y")
    .isel(x=slice(window_size - 1, None, stride), y=slice(window_size - 1, None, stride))
    .stack(n=("x", "y"))
)
```

but this was performing quite badly for larger arrays. However after having a look at `DataArrayRolling` and rewriting this piece of code to the following, performance was good.

```
data = (
    data.rolling(x=window_size ).construct("roll_x")
    .isel(x=slice(window_size - 1, None, stride))
    .rolling(y=window_size ).construct("roll_y")
    .isel(y=slice(window_size - 1, None, stride))
    .stack(n=("x", "y"))
)
```

I saw that `DataArrayRolling.construct()` also uses a slice (`isel`) to create the strided array, so there is not much of a performance penalty of first creating a rolling window with stride 1 and then slicing the data.

However, if you want to add strides to the 'Strided rolling' (#3607) it would be nice to still be able to create rolling windows that start at index 0.

By the way: feel free to close this issue, if you do not see a need for an alignment option.

**Comment by fujiisoup** [comment]
Hi @mark-boer for raising an issue.
I am not sure if I got the point exactly, but the following is similar to what you want?
```python
In [81]: arr = xr.DataArray(np.arange(4), dims=("x",)) 
    ...: arr.rolling(x=2).construct("roll_x").isel(x=slice(1, None, 2))        
Out[81]: 
<xarray.DataArray (x: 2, roll_x: 2)>
array([[0., 1.],
       [2., 3.]])
Dimensions without coordinates: x, roll_x
```

**Comment by mark-boer** [comment]
Hi @fujiisoup, thx for your response. 

That is exactly what I needed and what I used to do. But I mistakenly thought that there was a performance penalty to doing this. But the performance decrease turned out to be  the result of the order in which I rolled and sliced.

**Comment by fujiisoup** [comment]
> But I mistakenly thought that there was a performance penalty to doing this.

Yes, `construct(stride=2)` does exactly the same thing before returning an array.
https://github.com/pydata/xarray/blob/ff75081304eb2e2784dcb229cc48a532da557896/xarray/core/rolling.py#L242
