### ISSUE TITLE
Feature request: How Do I add a new variable to a data set?

### ISSUE THREAD

**Issue by rpgoldman** [pydata/xarray#3678]
A common thing to want to do is to create a new `DataArray` and add it to an existing `Dataset`, but the answer does not seem to appear in the "How Do I?" list.

Thanks!

**Comment by dcherian** [comment]
`ds["name"] = data_array` Also see `Dataset.assign`

A pull request would be very welcome!

**Comment by rpgoldman** [comment]
OK, done. Per my comments, I don't have the ability to build and check the sphinx code, so please check before merging.

**Comment by rpgoldman** [comment]
@dcherian 
I know it's kind of overloading this issue, but if you would also LMK if there's a clean way to do compound querying, the way one can in Pandas, I will also put in something about that.

```
foo = data_array.where(np.logical_and(other_data_array['bar'] == 12, other_data_array['baz'] < 22))
```

...is all I have come up with and this gets bloated and unreadable really quickly if there are multiple conjuncts.  Infix conjunction seems not to work unless I take the `.values` of the data array subsets, which adds its own layer of bloat.

I figure this is something that lots of people will want to do, but it seems a lot harder than `pd.DataFrame.query()`

**Comment by mathause** [comment]
You can shorthen this using parantheses and `&`:

``` python 
sel = (other_data_array['bar'] == 12) & (other_data_array['baz'] < 22)
foo = data_array.where(sel)
```

**Comment by rpgoldman** [comment]
@mathause Thank you! That never occurred to me.

I thought it was something wrong with the way I was using conjunction, but now I believe it was just a matter of operator precedence.
