### ISSUE TITLE
Default reading netCDF3 files with scipy.io instead of netCDF4?

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#368]
In my microbenchmarks, scipy.io appears to be ~3x faster than netCDF4 for reading netCDF3 files:

``` python
ds = xray.Dataset({'foo': (['x', 'y'], np.random.randn(10000, 10000).astype(np.float32))})
ds.to_netcdf('test.nc', engine='scipy')
ds_scipy = xray.open_dataset('test.nc', engine='scipy')
ds_nc4 = xray.open_dataset('test.nc', engine='netcdf4')

%timeit ds_scipy.isel(x=slice(5000)).load_data()
#10 loops, best of 3: 123 ms per loop

%timeit ds_nc4.isel(x=slice(5000)).load_data()
#1 loops, best of 3: 319 ms per loop
```

We might want to switch the default engine to use scipy for reading netCDF3 files. Note that netCDF4 does seem to be a bit faster for _writing_.

**Comment by hainm** [comment]
I am not sure if this bug is solved or not wit scipy netcdf

https://github.com/scipy/scipy/pull/3960

**Comment by shoyer** [comment]
@hainm That bug is fixed in scipy 0.14.1 (see https://github.com/scipy/scipy/issues/3630)

**Comment by hainm** [comment]
ah, great. thanks.

Hai

**Comment by max-sixty** [comment]
Closing as stale, please reopen if still relevant
