### ISSUE TITLE
imshow RGB plot overlaps map borders when using projection

### ISSUE THREAD

**Issue by bask0** [pydata/xarray#3687]
xarry version: '0.14.0'
matplotlib version: '3.1.1'

When I create an RGB plot using `ds.plot.imshow` with a procection, the plot overlaps the map borders:

    import cartopy.crs as ccrs
    import xarray
    import matplotlib.pyplot as plt
    
    ds = xr.load_dataset(...)
    
    ax = plt.subplot(projection=ccrs.Robinson())
    (ds.isel(time=[0, 4, 8])).plot.imshow(robust=True, ax=ax, transform=ccrs.PlateCarree())

[![RGB plot][1]][1]

When using `ds.plot.imshow` with a single layer, the plot looks as expected:

    import cartopy.crs as ccrs
    import xarray
    import matplotlib.pyplot as plt
    
    ds = xr.load_dataset(...)
    
    ax = plt.subplot(projection=ccrs.Robinson())
    (ds.isel(time=0)).plot.imshow(robust=True, ax=ax, transform=ccrs.PlateCarree(), add_colorbar=False)

[![single layer plot][2]][2]

  [1]: https://i.stack.imgur.com/wRdSz.png
  [2]: https://i.stack.imgur.com/3Jb6q.png

**Comment by dcherian** [comment]
Does this work if you use `matplotlib` directly? i.e. `plt.plot(ds.isel(time=[0, 4, 8]).values, ...)`

**Comment by bask0** [comment]
> Does this work if you use `matplotlib` directly? i.e. `plt.plot(ds.isel(time=[0, 4, 8]).values, ...)`

@dcherian Thanks, yes, this works as expected:

ax = plt.subplot(projection=ccrs.Robinson())
ax.imshow(ds.isel(time=[0, 4, 8]).transpose('lat', 'lon', 'time').values[-1::-1, :, :], transform=ccrs.PlateCarree())

[![rgb map][1]][1]

[1]: https://i.stack.imgur.com/iXuGA.png

**Comment by dcherian** [comment]
Thanks, I'm marking this as a bug.

If you have the time, it would be nice if you could look into this and send in a PR.

We do some RGB stuff here:
https://github.com/pydata/xarray/blob/8a650a11d1f859a88cc91b8815c16597203892aa/xarray/plot/plot.py#L632-L642

and `imshow` is here:
https://github.com/pydata/xarray/blob/8a650a11d1f859a88cc91b8815c16597203892aa/xarray/plot/plot.py#L843-L915

**Comment by bask0** [comment]
Thanks, I'll give it a try

**Comment by mathause** [comment]
This happens in matplotlib when you pass an RGBA array. Thus the following should cause the same problem.

``` python
ax = plt.subplot(projection=ccrs.Robinson())
ax.imshow(ds.isel(time=[0, 1, 4, 8]).transpose('lat', 'lon', 'time').values[-1::-1, :, :], transform=ccrs.PlateCarree())
```

I.e. it is an matplotlib or cartopy error. However, xarray always adds an alpha channel internally, see

https://github.com/pydata/xarray/blob/8a650a11d1f859a88cc91b8815c16597203892aa/xarray/plot/plot.py#L901-L903
