### ISSUE TITLE
Feature request: apply_ufunc create dataset from multi-return function

### ISSUE THREAD

**Issue by DancingQuanta** [pydata/xarray#3716]
I wanted to pass a list of variable names to `apply_ufunc` which then be used to convert a returned tuple of DataArrays into a dataset with names from the list.

I could create a PR but I need to ask due to the large possible arguments to and returns from `apply_ufunc` which may not match the use case with returned tuple of DataArrays.

**Comment by shoyer** [comment]
You can do this yourself pretty easily on top of `apply_ufunc`, just by passing the outputs into the `xarray.Dataset` constructor, e.g.,
```python
def apply_ufunc_to_dataset(func, *args, names, **kwargs):
    results = xarray.apply_ufunc(func, *args, **kwargs)
    return xarray.Dataset(dict(zip(names, results)))  
```

Given how complex `apply_ufunc` already is I think it is probably cleaner to leave this extension to user code.
