### ISSUE TITLE
Error during slicing of a dataarray

### ISSUE THREAD

**Issue by ankitesh97** [pydata/xarray#3740]
#### MCVE Code Sample

```python
# Your code here

```
loaded the dataset using 
ds = xr.open_mfdataset(in_fns, decode_times=False, decode_cf=False, concat_dim='time')
#### Problem Description
this my data array (da)
<xarray.DataArray 'QAP' (time: 5184, lev: 30, lat: 64, lon: 128)>
dask.array<concatenate, shape=(5184, 30, 64, 128), dtype=float32, chunksize=(48, 30, 64, 128), chunktype=numpy.ndarray>
Coordinates:
  * lev      (lev) float64 3.643 7.595 14.36 ... 957.5 976.3 992.6
  * lon      (lon) float64 0.0 2.812 5.625 8.438 ... 351.6 354.4 357.2
  * lat      (lat) float64 -87.86 -85.1 -82.31 ... 82.31 85.1 87.86
  * time     (time) float64 365.0 365.0 365.0 ... 707.9 708.0 708.0
Attributes:
    units:      kg/kg
    long_name:  Q after physics

when I am trying to slice it via da[1:]
it throws an error saying 
conflicting sizes for dimension 'time': length 96 on 'this-array' and length 5183 on 'time'

#### Output of ``xr.show_versions()``
version = 0.14.0
<details>
# Paste the output here xr.show_versions() here

</details>

**Comment by max-sixty** [comment]
I'm trying to close issues that aren't active — please reopen with a MCVE if this is still an issue.
