### ISSUE TITLE
The seaborn.apionly entry-point has been removed.

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#3747]
Seaborn [recently dropped](https://github.com/mwaskom/seaborn/releases) the `apionly` entry point (in version 0.10.0).

There is a dedicated `import_seaborn` function 
https://github.com/pydata/xarray/blob/47a6fc0c9b796997996d79d32358585d08021b9c/xarray/plot/utils.py#L24

but it is not used in one place

https://github.com/pydata/xarray/blob/47a6fc0c9b796997996d79d32358585d08021b9c/xarray/plot/utils.py#L146

which now causes test failures

https://dev.azure.com/xarray/xarray/_build/results?buildId=2111&view=ms.vss-test-web.build-test-results-tab&runId=29632&paneView=debug&resultId=108176

Todo: double check if the supported versions of seaborn still require this workaround.

**Comment by mathause** [comment]
The `apionly` entrypoint has been dropped in [seaborn 0.8.0](https://github.com/mwaskom/seaborn/releases/tag/v0.8.0). The minimum seaborn requirement is currently 0.9.0:

https://github.com/pydata/xarray/blob/4c96d53e6caa78d56b785f4edee49bbd4037a82f/ci/requirements/py36-min-all-deps.yml#L45

So I think the `def import_seaborn` function can be dropped.

**Comment by dcherian** [comment]
Thanks @mathause . Are you up for sending in a PR?
