### ISSUE TITLE
isort pre-commit hook does not skip text files

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#3750]
#### MCVE Code Sample

Add arbitrary change to the file `doc/pandas.rst`

``` bash
git add doc/pandas.rst
git commit -m "test"
```

The pre-commit hook will fail.

#### Expected Output
the pre-commit hook to pass

#### Problem Description

running `isort -rc doc/*` will change the following files:
``` bash
        modified:   contributing.rst
        modified:   howdoi.rst
        modified:   internals.rst
        modified:   io.rst
        modified:   pandas.rst
        modified:   quick-overview.rst
```
unfortunately it does not behave properly and deletes/ changes arbitrary lines. Can the pre-commit hook be told to only run on *.py files? On the command line this would be `isort -rc *.py`

**Comment by keewis** [comment]
`pre-commit` allows filtering the files passed to a hook using regular expressions:
```diff
   - repo: https://github.com/timothycrosley/isort
     rev: 4.3.21-2
     hooks:
       - id: isort
+        files: ".+[.]py"
   # https://github.com/python/black#version-control-integration
   - repo: https://github.com/python/black
```
Not sure if this regex is the one we should use, but it does seem to work.

**Comment by mathause** [comment]
You can tell isort to skip files in the `setup.cfg` but this seems to be ignored when doing `isort file` (which is what happens in the pre-commit hook) - see https://github.com/pre-commit/mirrors-isort/issues/9#issuecomment-511434587

So I think adapting `.pre-commit-config.yaml` is the way to go at the moment. (Maybe adapt `setup.cfg` anyway to ensure it does not happen when isort is called with `isort -rc .`).

**Comment by keewis** [comment]
actually, `isort` does support filtering using `--filter-files -sg '*.rst'` which would blacklist `rst` files. Since we don't have just `rst` files, I think that whitelisting is a better approach. Maybe we should use `files: .\.py$`?

**Comment by asottile** [comment]
fwiw, the problem here is the `-2` tag of isort is broken -- you want 4.3.21 which [properly specifies `types: [python]`](https://github.com/timothycrosley/isort/commit/30e15ab8251b682e48a1afe76dd65f7bdf39257b)
