### ISSUE TITLE
pynio package not found

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#3756]
Copied the install instructions from the docs http://xarray.pydata.org/en/stable/installing.html#instructions on my windows machine.
`conda install -c conda-forge xarray cartopy pynio pseudonetcdf`

Got a `PackagesNotFoundError: pynio`

![image](https://user-images.githubusercontent.com/17162724/73945181-e66ccf00-48c1-11ea-9746-e238ce48ae5c.png)

**Comment by keewis** [comment]
It seems `pynio` is not available on windows since it uses NCL which is a unix-only. It is optional, though, so if you don't depend on it you can just not install it. These particular install instructions read like examples to me, but we could probably make that a bit more obvious.
