### ISSUE TITLE
ArviZ Dev Xarray Dev Get Together?

### ISSUE THREAD

**Issue by canyon289** [pydata/xarray#3765]
Hi Xarray folks

I work on ArviZ and am the guy behind this tweet. https://twitter.com/arviz_devs/status/1225998959161663488

We use xarray heavily in ArviZ, its our central data object. We have questions about the current api and plans for the future api, and a number of our core developers were wondering you guys wanted to get together sometime, perhaps at one of the popular conferences like scipy, or probprog, or something like that.

In the meanwhile we've been collecting examples for things we can create reproducible examples for, but are hoping to chat at a higher level as well.
https://github.com/arviz-devs/xarray_examples

Let us know if this sounds interesting. Thanks for all the hard work on xarray

cc @rpgoldman @aloctavodia @OriolAbril @ahartikainen

**Comment by max-sixty** [comment]
I'm keen! Given work schedules, it may be easiest to do at a conference. We could also do a remote meeting.

The repo is ideal prep. The current two examples are good general questions about using Xarray even beyond ArviZ.

And more generally, I'm happy that ArviZ has built on top on xarray, and we're keen to support that!

**Comment by canyon289** [comment]
Thank you @max-sixty. I'm a huge proponent of in person meetings so will see if things fit there first, but if not falling back to remote will be easy!

In order of number of ArviZ devs closeby or present
* Boston for Probprog (Colin, Oriol, Alex, Ravin, Eric)
* PyDataNYC (Colin, probably, Robert Goldman, Ravin if were meeting)
* Scipy (Colin probably, Ravin maybe)
* NumFocus Summit (?)
* PyDataLA (Ravin)
* Pycon (Colin)

Are any of y'all from the xarray side planning to have a critical mass at any of these conferences?

**Comment by TomNicholas** [comment]
The questions you've put up there so far are general, so would make good StackOverflow questions - it would be nice to put them there for ease of finding by users afterwards.

**Comment by max-sixty** [comment]
@TomNicholas we probably do need to be better on SO. I've tried to do more there now I'm not contributing as much. I've found the questions are sometimes difficult to engage with as they're dependent on an external dataset (i.e. much lower quality than those here).

**Comment by canyon289** [comment]
Just to note another note our other questions span more than just code examples for the current API. We really do value xarray tremendously on the ArviZ side and we're looking to expand ArviZ functionality using things that may, or may not, end up in xarray. Since these questions more vague and messy roadmap type questions that don't fit neatly into a git repo with reproducible code, that's where the conference hallway tracks fit in! Hope this makes!

**Comment by dcherian** [comment]
At least three of us will likely be at SciPy this year (me, @jhamman, @rabernat).

That said, it may be best to schedule a call soon-ish just to say hi and hear about the questions you have. And... we get to think about these questions for a while before SciPy.

**Comment by shoyer** [comment]
I’ll probably be at SciPy this year too, at least if my talk(s) get accepted! Would be happy to do a brief call, too.

I know @ColCarroll just joined me at Google, so if he ever makes it out to Mountain View he should hit me up for lunch/coffee. Actually that holds anyone else who works on Python open source for scientific computing, too!

**Comment by canyon289** [comment]
@shoyer Thanks for the offer, I live in Socal and come to the Bay Area often so I will definitely take you up on that offer. Let me know if there's some good way to contact you, I'm assuming Github issues might be inappropriate :)

@dcherian I'll circle back with all the folks in ArviZ and we'll get a proposed agenda. Will post again here within a week

And lastly it sounds like scipy is the front running candidate for a conference. Which now means I really need to submit a talk or tutorial today.......

**Comment by shoyer** [comment]
You can reach me at my github username at gmail.com :).

**Comment by canyon289** [comment]
Hi all,
Quick follow up on this. We had our ArviZ dev meeting last week and we reproduced the consensus that we'd like to chat!

In regards to @dcherian's suggestion for a meeting. I'm thinking mid March (15th to 21st) is far enough out that people's schedules would be free. Can I use this github issue to work with you all to find a good time, (and virtual conference channel?)

**Comment by canyon289** [comment]
Hey all,
Apologies on the delay things have been hectic to say the least.

Does the 25th or the 27th work for you all at 7am PST? The early time for the Americans is to accommodate the devs in Europe. If it does let me know and I can schedule a meeting on Google Hangouts.

**Comment by rpgoldman** [comment]
27th works for me, 25th does not.  Thanks for setting this up.

I have a paid Doodle account, if you would like me to set up a poll instead of doing this here.

**Comment by dcherian** [comment]
+1 to Doodle poll.

**Comment by rpgoldman** [comment]
Doodle poll: https://doodle.com/poll/x6quxzmyu5qxqd98

**Comment by canyon289** [comment]
@rpgoldman Doodle poll would be great if you can create one

**Comment by max-sixty** [comment]
To the extent we can do later in the day, that would be easier for those on US west coast time...

**Comment by rpgoldman** [comment]
@max-sixty I can see about adding other times, if someone wants to propose them, but we might have to just re-poll.

We have always had our meetings early in the morning wrt PT because of people in Europe, I believe.

**Comment by ahartikainen** [comment]
Europe + Asia (India)

**Comment by canyon289** [comment]
It looks like Friday the 27th is the most popular day by a margin of 1. Any dissenters if we schedule the meeting for that day?

Given no response in 24 hours I'll post a google hangouts link

**Comment by canyon289** [comment]
An agenda is available here as well. Feel free to edit, comment , whatever you like
https://docs.google.com/document/d/1inOj9SriMq1CHKCpX4j9hNkvZk_tQv9xsYnqCREdkdo/edit#heading=h.cst6w4xawnaf

**Comment by canyon289** [comment]
Hi all,
Meet details are in the Google sheet. Looking forward to meeting you all tomorrow! 

https://docs.google.com/document/d/1inOj9SriMq1CHKCpX4j9hNkvZk_tQv9xsYnqCREdkdo/edit#heading=h.cst6w4xawnaf

![image](https://user-images.githubusercontent.com/7213793/77647403-95717280-6f23-11ea-956c-c8993e51d03f.png)

**Comment by canyon289** [comment]
@max-sixty @shoyer @dcherian @jhamman  Thanks very much for your time

 Capturing the high level takeaways for posterity

- Sharing concrete examples were beneficial for xarray team
- Conference call was useful for xarray team, primarily because they get to see each other
- Long form self contained github issues are useful for xarray project
- Adding issues to where docs are challenging, or being able to convert ArviZ use case examples into general purpose cookbook docs will be useful
- Doing this every so often sounds like a good idea

More generally from our side it was very helpful to hear the background of why things are they way they are, and get a sense of where they are going. @shoyer I thought your live api building was informative as well.

Notes are in agenda doc
https://docs.google.com/document/d/1inOj9SriMq1CHKCpX4j9hNkvZk_tQv9xsYnqCREdkdo/edit#

Really looking forward to all the changes coming up and certainly, and with much bias, hope the funding comes through.

As far as I can tell this issue "closed" Thanks again

**Comment by max-sixty** [comment]
Thanks @canyon289 ! 

Great to meet you all and I thought really helpful to talk through the cases with everyone. Indeed: having some cases to go over made the time much more productive.

I look forward to keeping the thread going...
