### ISSUE TITLE
New accessor for NeXus file input/output extension

### ISSUE THREAD

**Issue by mpanighel** [pydata/xarray#3771]
Hello and thanks for xarray!

I started developing the [nxarray](https://pypi.org/project/nxarray/) package, which is aimed to bring [NeXus](https://www.nexusformat.org/) input/output capabilities to xarray. Loading is based on [nexusformat](https://github.com/nexpy/nexusformat), returning an xarray dataset, while saving and conversion to NeXus is implemented as xarray accessor 'nxr'.

This issue is primarily informative (as suggested in the wiki for new accessors) but most importantly its aim is to share comments/ideas on the best implementation of such NeXus support (and whether an accessor is the best choice at all).

I know that xarray uses [netCDF](http://xarray.pydata.org/en/stable/io.html#netcdf) as default format, but still NeXus is really spreading in my scientific community and would be great to have an easy interoperability with the powerfulness of xarray.

**Comment by max-sixty** [comment]
Hi @mpanighel, thanks for the issue. 

That sounds interesting. We'd be happy to take a PR to add the package to our related packages. And I'm interested to see the growth of Nexus!

**Comment by dcherian** [comment]
@mpanighel Can you send a PR to add an entry to this list: https://xarray.pydata.org/en/stable/related-projects.html?
