### ISSUE TITLE
Add groupby.pipe?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#3782]
#### MCVE Code Sample

```python
In [1]: import xarray as xr                                                                                                                                         

In [3]: import numpy as np                                                                                                                                          

In [4]: ds = xr.Dataset( 
   ...:       {"foo": (("x", "y"), np.random.rand(4, 3))}, 
   ...:       coords={"x": [10, 20, 30, 40], "letters": ("x", list("abba"))}, 
   ...: )                                                                                                                                                      

In [5]: ds.groupby('letters')                                                                                                                                       
Out[5]: 
DatasetGroupBy, grouped over 'letters' 
2 groups with labels 'a', 'b'.

In [8]: ds.groupby('letters').sum(...) / ds.groupby('letters').count(...)                                                                                           
Out[8]: 
<xarray.Dataset>
Dimensions:  (letters: 2)
Coordinates:
  * letters  (letters) object 'a' 'b'
Data variables:
    foo      (letters) float64 0.4182 0.4995

In [9]: ds.groupby('letters').pipe(lambda x: x.sum() / x.count())                                                                                                   
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-c9b142ea051b> in <module>
----> 1 ds.groupby('letters').pipe(lambda x: x.sum() / x.count())

AttributeError: 'DatasetGroupBy' object has no attribute 'pipe'


```

#### Expected Output

I think we could add `groupby.pipe`, as a convenience?

#### Output of ``xr.show_versions()``
<details>

In [12]: xr.show_versions()                                                                                                                                         

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8 (default, Aug  7 2019, 17:28:10) 
[...]
python-bits: 64
OS: Linux
OS-release: [...]
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.14.1
pandas: 0.25.3
numpy: 1.18.1
scipy: 1.4.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.1.2
cartopy: None
seaborn: 0.10.0
numbagg: None
setuptools: 45.0.0
pip: 20.0.2
conda: None
pytest: 5.3.2
IPython: 7.11.1
sphinx: 2.3.1

</details>

**Comment by dcherian** [comment]
How is this different from `map` or `apply`

**Comment by max-sixty** [comment]
Pipe operates on the whole object, not on each group; consistent with the other objects like Dataset

**Comment by max-sixty** [comment]
I think I see your point @dcherian: given that `groupby.map` also reduces, and there isn't much else you can do with a `groupby`, this probably isn't needed...

**Comment by max-sixty** [comment]
Closing for now. Given almost any useful `groupby` method maps-and-reduces the groups, `map` covers almost all use cases.

(ref https://github.com/pydata/xarray/issues/1251).
