### ISSUE TITLE
open_dataarray(cache=False) still uses cached version of dataarray

### ISSUE THREAD

**Issue by ngreenwald** [pydata/xarray#3785]
#### MCVE Code Sample

```python
# Your code here
import xarray as xr
import numpy as np
import os

# create two different xarrays with different sizes and coords
test_xr1 = xr.DataArray(np.zeros((5, 5, 3)), coords=[range(5), range(5), ["x1", "y1", "z1"]], dims=["1", "2", "3"])
test_xr2 = xr.DataArray(np.zeros((10, 2, 3)), coords=[range(10), range(2), ["x2", "y2", "z2"]], dims=["1", "2", "3"])

# save first xarray, reload it, and inspect coords
test_xr1.to_netcdf("test_xr.xr")
loaded_xr = xr.open_dataarray("test_xr.xr", cache=False)
loaded_xr.coords

Out[13]: 
Coordinates:
  * 1        (1) int64 0 1 2 3 4
  * 2        (2) int64 0 1 2 3 4
  * 3        (3) object 'x1' 'y1' 'z1'

# remove first xarray, save second with the same name, and load it
os.remove("test_xr.xr")
test_xr2.to_netcdf("test_xr.xr")
loaded_xr = xr.open_dataarray("test_xr.xr", cache=False)
loaded_xr.coords

Out[17]: 
Coordinates:
  * 1        (1) int64 0 1 2 3 4
  * 2        (2) int64 0 1 2 3 4
  * 3        (3) object 'x1' 'y1' 'z1'
```

#### Expected Output
Rather than loading the newly created/updated version of the file on disk, the cached version is used

#### Problem Description

If a file ever gets updated on disk and needs to be reloaded, this causes very mysterious bugs. Furthermore, the only workaround I found is to restart the python session. 

#### Output of ``xr.show_versions()``
<details>
# Paste the output here xr.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 18.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: en_US.UTF-8
libhdf5: 1.10.2
libnetcdf: 4.6.3
xarray: 0.12.1
pandas: 0.24.2
numpy: 1.16.3
scipy: 1.2.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: 0.9.0
setuptools: 39.0.1
pip: 9.0.3
conda: None
pytest: 5.3.2
IPython: 7.11.1
sphinx: None
</details>

**Comment by ngreenwald** [comment]
Hey all, just wanted to follow up to see if anyone had suggestions for how to approach this. 

We're running into this issue when we load an xarray, make some changes to it, and then save the modified version. Especially for interactive sessions, this produces bugs that are challenging to track down, as it appears that the previous step has failed, not that the actual loading is the problem.

**Comment by mapazarr** [comment]
@ngreenwald you need to update your version of xarray to 0.12.2 or greater and use the `load_dataarray` method instead of the `open_dataarray` one, in which case, the `cache` option is not necessary. More info here: [http://xarray.pydata.org/en/stable/generated/xarray.load_dataarray.html](http://xarray.pydata.org/en/stable/generated/xarray.load_dataarray.html)

Here your example corrected, showing the expected output:

```python
import xarray as xr
import numpy as np
import os

# create two different xarrays with different sizes and coords
test_xr1 = xr.DataArray(np.zeros((5, 5, 3)),
                        coords=[range(5), range(5), ["x1", "y1", "z1"]],
                        dims=["1", "2", "3"])
test_xr2 = xr.DataArray(np.zeros((10, 2, 3)),
                        coords=[range(10), range(2), ["x2", "y2", "z2"]],
                        dims=["1", "2", "3"])

display(test_xr1.coords)
display(test_xr2.coords)
```
```Out:
Coordinates:
  * 1        (1) int64 0 1 2 3 4
  * 2        (2) int64 0 1 2 3 4
  * 3        (3) <U2 'x1' 'y1' 'z1'

Coordinates:
  * 1        (1) int64 0 1 2 3 4 5 6 7 8 9
  * 2        (2) int64 0 1
  * 3        (3) <U2 'x2' 'y2' 'z2'
```
```python
# save first xarray, reload it, and inspect coords
test_xr1.to_netcdf("test_xr.xr")
loaded_xr = xr.load_dataarray("test_xr.xr")
loaded_xr.coords
```
```Out:
Coordinates:
  * 1        (1) int64 0 1 2 3 4
  * 2        (2) int64 0 1 2 3 4
  * 3        (3) object 'x1' 'y1' 'z1'
```
```python
# remove first xarray, save second with the same name, and load it
os.remove("test_xr.xr")
test_xr2.to_netcdf("test_xr.xr")
loaded_xr = xr.load_dataarray("test_xr.xr")
loaded_xr.coords
```
```Out:
Coordinates:
  * 1        (1) int64 0 1 2 3 4 5 6 7 8 9
  * 2        (2) int64 0 1
  * 3        (3) object 'x2' 'y2' 'z2'
```
