### ISSUE TITLE
RTD failing yet again

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3796]
memory consumption errors as usual.

@keewis I remember you had an idea for using pip instead of conda?

**Comment by keewis** [comment]
we could try moving everything except `cartopy` to the `pip` section in the environment file (`iris` is `scitools-iris` on PyPI). That seems to reduce the maximum memory consumption quite a bit (the `conda-forge` channel has grown almost too much).

**Comment by mathause** [comment]
This did indeed work for my project (regionmask), https://github.com/mathause/regionmask/blob/master/docs/environment_rtd.yml

**Comment by keewis** [comment]
I tried it, but it still fails: https://readthedocs.org/projects/xray/builds/10502148/ We can't use `pip` directly since `cartopy` does not upload wheels and I'd expect the source install to fail.

If we look at the issue tracker of RTD, we can see a lot of issues regarding memory errors, so maybe this is a general issue with `conda` (when using `conda-forge`) and RTD.

**Comment by DocOtak** [comment]
The docs seem to build ok on Azure piplines, is it possible to get the built docs from that and publish somewhere? I do know this is possible with [Travis](https://docs.travis-ci.com/user/deployment/pages/), but haven't actually done it myself since my docs don't (yet?) have a memory problem.

**Comment by keewis** [comment]
yeah, that would probably be the way forward. See #3697 for more discussion.

**Comment by dcherian** [comment]
No luck with pinned versions and the stable build image: https://readthedocs.org/projects/xray/builds/10547287/

**Comment by keewis** [comment]
due to the work of the RTD maintainers, our builds pass again. However, trying to build `stable` still fails, but instead of a memory error we get a sphinx failure: https://readthedocs.org/projects/xray/builds/10609593/

I think we already fixed that in master?
