### ISSUE TITLE
Should we run tests on docstrings?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#3837]
Currently almost none of the docstrings pass running `pytest --doctest-modules xarray/core`, though mostly for easy reasons.

Should we run these in CI?

I've recently started using docstring tests in another project, and they've work pretty well. 

CC @keewis

**Comment by keewis** [comment]
:+1: for running doctest in CI, this should help us keep the examples in sync with the implementation

**Comment by dcherian** [comment]
I second this. It seems to run quite quickly...
