### ISSUE TITLE
open_mfdataset returns `InvalidIndexError: Reindexing only valid with uniquely valued Index objects`

### ISSUE THREAD

**Issue by evanmason** [pydata/xarray#3856]
I am trying to open multiple nc files with `open_mfdataset`.  In the example below I use just the first two files:

```python
ds = open_mfdataset(ncfiles[:2], combine='nested', concat_dim='TIME', data_vars='minimal')
```

where I get the error `InvalidIndexError: Reindexing only valid with uniquely valued Index objects`

The dimensions and coords of the two files are (note the different sizes):

```
Dimensions:             (DEPTH: 1, LATITUDE: 15935, LONGITUDE: 15935, POSITION: 15935, TIME: 15935)
Coordinates:
  LATITUDE            (LATITUDE) float32 29.953 29.953 29.953 ... 25.321 25.25
  LONGITUDE           (LONGITUDE) float32 136.914 136.917 ... 129.905 129.865
  TIME                (TIME) datetime64[ns] 2005-04-25T01:00:00 ... 2016-02-17T03:00:00
Dimensions without coordinates: DEPTH, POSITION
Data variables:
VGTA                (TIME, DEPTH) float32 dask.array<shape=(15935, 1), chunksize=(15935, 1)>
```

and

```
Dimensions:             (DEPTH: 1, LATITUDE: 17578, LONGITUDE: 17578, POSITION: 17578, TIME: 17578)
Coordinates:
  LATITUDE            (LATITUDE) float32 29.985 29.979 ... 41.335 41.349
  LONGITUDE           (LONGITUDE) float32 137.011 137.017 ... 155.051 155.001
  TIME                (TIME) datetime64[ns] 2004-10-25T09:00:00 ... 2016-05-23T09:00:00
Dimensions without coordinates: DEPTH, POSITION
Data variables:
    VGTA                (TIME, DEPTH) float32 dask.array<shape=(17578, 1), chunksize=(17578, 1)>
```

I have tried different combinations of arguments for `combine`, `concat_dim` and `data_vars` without success.  Can anyone show me how to do this?

**Comment by max-sixty** [comment]
Please could you fill out the issue template, if possible including a MCVE, and at least including a stack trace?

**Comment by evanmason** [comment]
Sorry, I'm not sure how to do the issue template.

My data are from [http://marine.copernicus.eu/services-portfolio/access-to-products/?option=com_csw&view=details&product_id=WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001](url)

`from xarray import open_mfdataset`
`from glob import glob`

`ncfiles = sorted(glob("~/GL_TS_DB_?????.nc"))`
`ds = open_mfdataset(ncfiles[:2], combine="nested", concat_dim="TIME", data_vars="minimal")`


Here's the stack trace:


`
ds = open_mfdataset(ncfiles[:2], combine="nested", concat_dim="TIME", data_vars="minimal")`                                                                                                              

`InvalidIndexError                         Traceback (most recent call last)
<ipython-input-134-4ca27894be8c> in <module>
----> 1 ds = open_mfdataset(ncfiles[:2], combine="nested", concat_dim="TIME", data_vars="minimal")

~/VENV_dragonera/lib/python3.5/site-packages/xarray/backends/api.py in open_mfdataset(paths, chunks, concat_dim, compat, preprocess, engine, lock, data_vars, coords, combine, autoclose, parallel, **kwargs)
    787             combined = _nested_combine(datasets, concat_dims=concat_dim,
    788                                        compat=compat, data_vars=data_vars,
--> 789                                        coords=coords, ids=ids)
    790         elif combine == 'by_coords':
    791             # Redo ordering from coordinates, ignoring how they were ordered

~/VENV_dragonera/lib/python3.5/site-packages/xarray/core/combine.py in _nested_combine(datasets, concat_dims, compat, data_vars, coords, ids, fill_value)
    255     combined = _combine_nd(combined_ids, concat_dims, compat=compat,
    256                            data_vars=data_vars, coords=coords,
--> 257                            fill_value=fill_value)
    258     return combined
    259 

~/VENV_dragonera/lib/python3.5/site-packages/xarray/core/combine.py in _combine_nd(combined_ids, concat_dims, data_vars, coords, compat, fill_value)
    178                                                     coords=coords,
    179                                                     compat=compat,
--> 180                                                     fill_value=fill_value)
    181     (combined_ds,) = combined_ids.values()
    182     return combined_ds

~/VENV_dragonera/lib/python3.5/site-packages/xarray/core/combine.py in _combine_all_along_first_dim(combined_ids, dim, data_vars, coords, compat, fill_value)
    198         datasets = combined_ids.values()
    199         new_combined_ids[new_id] = _combine_1d(datasets, dim, compat,
--> 200                                                data_vars, coords, fill_value)
    201     return new_combined_ids
    202 

~/VENV_dragonera/lib/python3.5/site-packages/xarray/core/combine.py in _combine_1d(datasets, concat_dim, compat, data_vars, coords, fill_value)
    212         try:
    213             combined = concat(datasets, dim=concat_dim, data_vars=data_vars,
--> 214                               coords=coords, fill_value=fill_value)
    215         except ValueError as err:
    216             if "encountered unexpected variable" in str(err):

~/VENV_dragonera/lib/python3.5/site-packages/xarray/core/concat.py in concat(objs, dim, data_vars, coords, compat, positions, indexers, mode, concat_over, fill_value)
    117         raise TypeError('can only concatenate xarray Dataset and DataArray '
    118                         'objects, got %s' % type(first_obj))
--> 119     return f(objs, dim, data_vars, coords, compat, positions, fill_value)
    120 
    121 

~/VENV_dragonera/lib/python3.5/site-packages/xarray/core/concat.py in _dataset_concat(datasets, dim, data_vars, coords, compat, positions, fill_value)
    227     datasets = [ds.copy() for ds in datasets]
    228     datasets = align(*datasets, join='outer', copy=False, exclude=[dim],
--> 229                      fill_value=fill_value)
    230 
    231     concat_over, equals = _calc_concat_over(datasets, dim, data_vars, coords)

~/VENV_dragonera/lib/python3.5/site-packages/xarray/core/alignment.py in align(join, copy, indexes, exclude, fill_value, *objects)
    123                         'indexes along dimension {!r} are not equal'
    124                         .format(dim))
--> 125                 index = joiner(matching_indexes)
    126                 joined_indexes[dim] = index
    127             else:

~/VENV_dragonera/lib/python3.5/site-packages/pandas/core/indexes/base.py in __or__(self, other)
   2221 
   2222     def __or__(self, other):
-> 2223         return self.union(other)
   2224 
   2225     def __xor__(self, other):

~/VENV_dragonera/lib/python3.5/site-packages/pandas/core/indexes/base.py in union(self, other, sort)
   2330                 result.extend([x for x in rvals if x not in value_set])
   2331         else:
-> 2332             indexer = self.get_indexer(other)
   2333             indexer, = (indexer == -1).nonzero()
   2334 

~/VENV_dragonera/lib/python3.5/site-packages/pandas/core/indexes/base.py in get_indexer(self, target, method, limit, tolerance)
   2738 
   2739         if not self.is_unique:
-> 2740             raise InvalidIndexError('Reindexing only valid with uniquely'
   2741                                     ' valued Index objects')
   2742 

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

`

**Comment by max-sixty** [comment]
OK. It's difficult to zero in without a reproducible example. It looks like the files's values aren't unique on the dimension you're concatenating on. Could you explore whether you're attempting to concat them in the correct way?

I'll leave this open in case anyone happens to recognize exactly the problem.

**Comment by shoyer** [comment]
The picture of this data from that website is helpful:
![image](https://user-images.githubusercontent.com/1217238/76592200-e14a0380-64af-11ea-993d-7df567585f95.png)

It looks like this is data from satellite swaths. The dataset looks like it's effectively 1D, or maybe 2d including depth.

You'll have to do some preprocessing to make it usable in xarray (e.g., the `proprocess` argument to `open_mfdataset`). In particular, all of latitude/longitude/position/time should be consolidated along a single dimension. I don't know why the dataset provider thought it made sense to use separate dimensions for each variables.

Then you'll want to combine the datasets from multiple files together, either along that existing dimension or a new dimension. This might actually be easier to do outside of `open_mfdataset`, just directly opening each dataset on its own.

At the end of the day, this sort of data probably isn't a great fit for analysis in xarray because it's fundamentally ragged. I would consider starting with a tool like pandas, or see if you can dig up some more specialized tools for working with satellite data, e.g., try the [satpy](https://satpy.readthedocs.io/en/latest/) python library.

**Comment by evanmason** [comment]
Yes, indeed yesterday I opened it up with numpy and netCDF4 Dataset and
that was straightforward.  I'm just starting with xarray, and this is the
first problem I've run into.  I'll give it a try with pandas.  Thanks for
your replies.
