### ISSUE TITLE
Taking too much time in plotting graph after doing groupby

### ISSUE THREAD

**Issue by shalin07** [pydata/xarray#3859]
I'm using xarray to acces CMIP6 data from google cloud dataset. 
```python
df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')
```

Then I'm applying following filter.:
```python
df_cesm = df.query("table_id == 'Amon' & variable_id == 'zg' & experiment_id == 'piControl' & source_id == 'CESM2'")
```
Then I'm opening zarr file:
```python
gcs = gcsfs.GCSFileSystem(token='anon')
ds_cesm = xr.open_zarr(gcs.get_mapper(df_cesm.zstore.values[0]), consolidated=True)
```

Output of the data variable of the above is as follows:
```
zg
(time, plev, lat, lon) float32 dask.array (14400, 19, 192, 288)
```

Then I'm just selecting 50000 plev and doing mean of groupby(month-wise).

```python
ds_cesm_500 = ds_cesm.sel(plev = 50000)
monthly_mean = ds_cesm_500.groupby('time.month').mean()
```
Now when I try to plot for single month like this:
```python
monthly_mean.zg.sel(month = 1).squeeze().plot(figsize = (10,5))
```
It's taking lot of time to plot a graph. I don't know what's happening wrong cause even before when I tried to plot a graph for single date from whole data it was not taking much time. And I have tried this grouby on another data of temperature to check if there is problem with groupby, but there after doing groupby it's plotting temperature quickly. So problem is happening only with plotting zg variable after doing groupby.

**Comment by max-sixty** [comment]
If you reduce the size of the data before the groupby, does that make it fast?

Please could you fill out the original issue template?

**Comment by shalin07** [comment]
@max-sixty when I converted the dask array to dataarray by .load( ) it started plotting the plots fast. Though with other dask array it was working fine without doing any manipulation, I'm not sure what's the problem with this specific one. But now it's working as I want so I'm closing the issue.
