### ISSUE TITLE
xarray.Dataset.from_dataframe link to pandas.DataFrame.to_xarray

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#3895]
Is it worth referencing https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_xarray.html in http://xarray.pydata.org/en/stable/generated/xarray.Dataset.from_dataframe.html?

is the pandas method preferred?

**Comment by max-sixty** [comment]
Yes, for sure worth a reference in `See Also`, if you'd be up for a PR.

The functionality is basically the same: https://github.com/pandas-dev/pandas/blob/v1.0.3/pandas/core/generic.py#L2787-L2868

**Comment by raybellwaves** [comment]
Sure. Can update the docs. but won't be able to for a week or so.

Curious is there is much/any difference? is worth deprecating and pointing maintenance/development to the pandas version instead?

**Comment by max-sixty** [comment]
No strong view on whether it's worth having both. I'm personally more partial to the duplication given they're on different objects. e.g. `Series.todict()` or `dict(Series)`
