### ISSUE TITLE
consecutive time selection

### ISSUE THREAD

**Issue by miniufo** [pydata/xarray#3896]
Not sure if this has been asked.

I have a sea surface temperature (SST) `DataArray` (monthly data) and want to use it to define El Nino.  An El Nino event is defined by a five consecutive 3-month running mean of SST anomalies in the Niño 3.4 region that is above the threshold of 0.5°C.  I know I can use `roll` object to get the 3-month running mean.  But how to meet the requirement of five-consecutive months?  Is there a simple way to do this using xarray's API?

**Comment by max-sixty** [comment]
IIUC, you could have, in order:
- rolling 3 month SST
- bool on whether that's above 0.5
- rolling 5 month count of that
- bool on whether that's equal to 5

**Comment by miniufo** [comment]
That is awesome!  Didn't notice the rolling object has a `count()` method.  The rolling object is more powerful than I think.  Thanks @max-sixty.

**Comment by miniufo** [comment]
Hi @max-sixty, thanks for your kind help.  But I found it works not as I expected.  If the SST has the values `[..., 0, 0, 1, 1, 1, 1, 1, 0, 0, ...]`, then the method you suggested will give `[..., F, F, F, F, T, F, F, F, F, ...]`.  That is only one `True` for a 5 consecutive 1s.  But I would expect five `True` like `[..., F, F, T, T, T, T, T, F, F, ...]`.  Any suggestion?

**Comment by max-sixty** [comment]
OK, that's a bit harder but not impossible. You could take that, run `array.astype(float).where(array).bfill(dim, limit=5)`, or similar? Others will probably have cleaner suggestions...

**Comment by keewis** [comment]
what about this?
```python
In [57]: arr = xr.DataArray( 
    ...:     data=np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0]), 
    ...:     dims="x", 
    ...:     coords={"x": np.arange(24)}, 
    ...: ) 
    ...: ( 
    ...:     arr.pipe(lambda a: a > 0.5) 
    ...:     .rolling(dim={"x": 5}, center=True) 
    ...:     .sum() 
    ...:     .rolling(dim={"x": 5}) 
    ...:     .reduce(lambda a, axis: (a == 5).sum(axis=axis)) 
    ...:     .fillna(0) 
    ...:     .astype(bool) 
    ...: )
Out[57]: 
<xarray.DataArray (x: 24)>
array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True, False, False, False, False, False,  True,
        True,  True,  True,  True, False, False])
Coordinates:
  * x        (x) int64 0 1 2 3 4 5 6 7 8 9 10 ... 14 15 16 17 18 19 20 21 22 23
```

**Comment by miniufo** [comment]
Hi @keewis, this is really a smart way, using `rolling` twice.  I've refactored the code slightly as:
```python
def continuous_meet(cond, count, dim):
    """
    Continuously meet a given condition along a dimension.
    """
    _found = cond.rolling(dim={dim:count},
                          center=True).sum().fillna(0).astype(np.float)
    
    detected = (
        _found.rolling(dim={dim:count}, center=True) 
        .reduce(lambda a, axis: (a == count).any(axis=axis)) 
        .fillna(False) 
        .astype(bool) 
    )
    
    if count % 2 == 0:
        return detected.shift({dim:-1}).fillna(False)
    
    return detected

sst = xr.DataArray(
    np.array(
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
         0., 0., 1., 0., 0., 1., 1., 1., 1., 1.,
         1., 0., 0., 0.]
    ),
    dims="time",
    coords={"time": np.arange(24)},
    name="sst",
)

ElNino = continuous_meet(sst > 0.5, count=5, dim='time')

sst.plot.step(linewidth=3)
sst.where(ElNino).plot.step(linewidth=2)
```
Note that when `count` is a even number, truly centered `rolling` cannot be obtained.  So we need to `shift` the result by -1.  Is this perfect?  I didn't check the performance.

**Comment by keewis** [comment]
sounds good. Minor comment / nit: you don't really need the `astype(np.float)`, the result should already be of dtype `float` since there are missing values after the rolling sum.

I don't know about performance but if it does what you asked for then that's good?

**Comment by miniufo** [comment]
>Minor comment / nit: you don't really need the astype(np.float), the result should already be of dtype float since there are missing values after the rolling sum.

You're right.  That is used for debuging the intermediate results.

Thanks again @keewis @max-sixty.
