### ISSUE TITLE
html repr does not work in Edge browser

### ISSUE THREAD

**Issue by blaylockbk** [pydata/xarray#3898]
Just updated a conda environment and it installed xarray to 0.15.1. I was a bit lost with the new html output because it does not work when Jupyter is running in an Edge browser (not the chromium version). After I switched to Chrome I figured out that the html output was clickable and expanded the data I needed to see.

Display in the Edge browser: sections do not expand when clicked
![image](https://user-images.githubusercontent.com/6249613/77665066-5865aa00-6f3c-11ea-9c4f-f4cc246558cc.png)

Display in the Chrome browser: sections expand when clicked
![image](https://user-images.githubusercontent.com/6249613/77665169-84812b00-6f3c-11ea-879a-dd2ee092e3fd.png)

The text output is so engrained in my programming muscle memory, but I want to try this new html output...Can you add some documentation describing how to use the html output, especially details like browser requirements, what the display should look like, etc.

**Comment by shoyer** [comment]
Thanks for the report!

I know we use some relatively new CSS features to get the HTML repr working, but our intent is definitely for this to work across as many platforms as possible, not just Chrome. I'll double check, but I'm pretty sure the HTML repr works in recent versions of Firefox, too.

Which version of Edge are you using? My understanding was that newer versions of Edge are baed on Chromium (the rendering engine from Chrome).

**Comment by blaylockbk** [comment]
Oh yes, forgot to mention...I'm stuck with the non-chromium version of Edge 44.18362.449.0. (It's a work computer and don't have much browser freedom).

I just tested it on my personal computer (Edge 80.0.361.69) and the html repr works there.

**Comment by benbovy** [comment]
> I know we use some relatively new CSS features to get the HTML repr working

`display: grid` and `display: contents` are the two newest features used in the repr I think. `display: grid` seems [well supported in Edge ](https://caniuse.com/#feat=css-grid), but `display: contents` might [not be well supported in old versions of Edges](https://caniuse.com/#feat=mdn-css_properties_display_contents)?

Unfortunately, I don't think there is an easy workaround for to avoid `display: contents` (given that there is even less support for subgrid).
