### ISSUE TITLE
AttributeError: 'DataArray' object has no attribute 'weighted'

### ISSUE THREAD

**Issue by hoseinmadadi** [pydata/xarray#3901]
I am learning xarray based on pydata's Doc. In Computation section and "Weighted array reductions" sub-section, when I run:
`weighted_prec = prec.weighted(weights)`
` weighted_prec`

Jupyter came back to me below ERROR:

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-49-3893583b4b62> in <module>
      1 import pandas as pd
      2 import numpy as np
----> 3 data.weighted(weights).mean()

C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\common.py in __getattr__(self, name)
    231                     return source[name]
    232         raise AttributeError(
--> 233             "{!r} object has no attribute {!r}".format(type(self).__name__, name)
    234         )
    235 

AttributeError: 'DataArray' object has no attribute 'weighted'

What is my problem?

**Comment by shoyer** [comment]
You probably need to upgrade the version of xarray you’re using. Weighted statistics were a new feature in 0.15.1.

**Comment by hoseinmadadi** [comment]
I tested it in the last version of jupyter:
`xr.__version__`
'0.15.0'

Unfortunately in [anaconda cloud](https://anaconda.org/anaconda/xarray), there is '0.15.0', and `pip install 'xarray==0.15.1' --force-reinstall` did not work.

**Comment by kmuehlbauer** [comment]
@hoseinmadadi You might pull it from `conda-forge` channel until it is available in `default` channel.

**Comment by hoseinmadadi** [comment]
@shoyer and @kmuehlbauer, thanks for your help, it works :)
