### ISSUE TITLE
New rename_vars() method seems to be missing from dataset attributes

### ISSUE THREAD

**Issue by mstrahl** [pydata/xarray#3903]
I tried to use this on a netcdf file that needs to be made CF-compliant.
But:

```pytb
Traceback (most recent call last):
  File "/home/smartmet/bin/hops-raw_to_cf.py", line 28, in <module>
dsm.rename_vars({'soilt_node_1':'stl1','soilt_node_2':'stl2','soilt_node_3':'stl3','soilt_node_4':'stl4','evapo':'e','uz_vol':'swl2','lz_vol':'swl3','snow':'h_snow','snowpack':'w_snow','precip':'tp','tempc':'t','runoff':'ro'})
  File "/home/smartmet/anaconda3/lib/python2.7/site-packages/xarray/core/common.py", line 179, in __getattr__
    (type(self).__name__, name))
AttributeError: 'Dataset' object has no attribute 'rename_vars'
```

I don't see how I should in another way call this rename_vars method.

Thanks for any fix/help

**Comment by keewis** [comment]
I think we dropped `py27` a long time ago and `rename_vars` was added since then. To confirm, could you print your python and xarray version (or the output of `xr.show_versions()`)?

In general, if you can, you should try to use `python >= 3.6`.

**Comment by mstrahl** [comment]
Bummer! That's the issue. We have a conda installation for python2.7 as the HOPS model hasn't been cleaned up for python3...

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 19:04:46) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-72-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: 4.6.1

xarray: 0.11.3
pandas: 0.24.2
numpy: 1.16.4
scipy: 1.2.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: 2.9.0
Nio: None
zarr: None
cftime: 1.0.4.2
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.1
cyordereddict: None
dask: 1.2.2
distributed: 1.28.1
matplotlib: 2.2.3
cartopy: None
seaborn: 0.9.0
setuptools: 44.0.0.post20200106
pip: 19.3.1
conda: 4.8.3
pytest: 4.6.2
IPython: 5.8.0
sphinx: 1.8.5

I did install xarray with pip3 so there it is in order 0.15.1

Sorry for the non-issue issue!

Cheers
Mikko

**Comment by keewis** [comment]
no worries
