### ISSUE TITLE
check index invariants in test_dataset, test_dataarray

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3908]
There are a large number of tests in `test_dataarray.py` and `test_dataset.py` that use the `assert actual.equals(expected)` pattern. 

We should switch these to be `assert_equal(actual, expected)` so that we run the invariant checks:

https://github.com/pydata/xarray/blob/acf7d4157ca44f05c85a92d1b914b68738988773/xarray/tests/__init__.py#L150-L154

Seems like an easy use of regexes for someone that knows them (i.e. not me ;))

**Comment by keewis** [comment]
I'll give it a try

**Comment by keewis** [comment]
unfortunately, I could only find one instance where we can really use the regexp. Among the others, there are a few that test non-xarray structures (like pandas objects) so the process is mostly manual.

**Comment by dcherian** [comment]
Shall I do one file then? `test_dataarray`?

**Comment by keewis** [comment]
go ahead

**Comment by dcherian** [comment]
oops. this seems like a false alarm. Most of these seem to be checking the `.equals` and `.identical` methods or pandas objects as @keewis pointed out. So there isn't much to do?
