### ISSUE TITLE
issues discovered by the all-but-dask CI

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#3921]
After adding the `py38-all-but-dask` CI in #3919, it discovered a few backend issues:
- `zarr`:
  - [x] `open_zarr` with `chunks="auto"` always tries to chunk, even if `dask` is not available (fixed in #3919)
  - [x] `ZarrArrayWrapper.__getitem__` incorrectly passes the indexer's `tuple` attribute to `_arrayize_vectorized_indexer` (this only happens if `dask` is not available) (fixed in #3919)
  - [ ] slice indexers with negative steps get transformed incorrectly if `dask` is not available https://github.com/pydata/xarray/pull/8674
- `rasterio`:
  - ~calling `pickle.dumps` on a `Dataset` object returned by `open_rasterio` fails because a non-serializable lock was used (if `dask` is installed, a serializable lock is used instead)~

**Comment by max-sixty** [comment]
Great finds @keewis !

Any idea why a lock is being serialized at all with a Dataset?

**Comment by keewis** [comment]
I think the lock is used to synchronize the I/O on the `rasterio` file, so we can't really remove it. The failing test states it is a regression test for #2121, but since then the backend code was rewritten. We'd probably need a serializable lock that does not depend on dask (I don't know much about the backend code, though)

**Comment by headtr1ck** [comment]
I think the last remaining item has been fixed by https://github.com/pydata/xarray/pull/7586, but not completely sure.

Then we could close this issue :)

**Comment by keewis** [comment]
I think we'd need to be able to remove this `xfail` first: https://github.com/pydata/xarray/blob/f8127fc9ad24fe8b41cce9f891ab2c98eb2c679a/xarray/tests/test_backends.py#L712-L714 I didn't check, this could be xpassing right now.
