### ISSUE TITLE
Element wise dataArray generation

### ISSUE THREAD

**Issue by apatlpo** [pydata/xarray#3932]
I'm in a situation where I want to generate a bidimensional DataArray from a method that takes each of the two dimensions as input parameters.
I have two methods to do this but neither of these looks particularly elegant to me and I wondered whether somebody would have better ideas.

- **Method 1** : dask delayed

```
x = np.arange(10)
y = np.arange(20)

some_exp = lambda x, y: np.ones((Nstats))
some_exp_delayed = dask.delayed(some_exp, pure=True)

lazy_data = [some_exp_delayed(_x, _y) for _x in x for _y in y]
sample = lazy_data[0].compute()
arrays = [da.from_delayed(lazy_value,
                          dtype=sample.dtype,
                          shape=sample.shape)
          for lazy_value in lazy_data]

stack = (da.stack(arrays, axis=0)
         .reshape((len(x),len(y),sample.size))
        )
ds = xr.DataArray(stack, dims=['x','y','stats'])
```

I tend to prefer this option because it imposes less requirement on the `some_exp` data shape.
That being said it still seems like too many lines of code to achieve such result.

- **Method 2**: apply_ufunc 
 
```
x = np.arange(10)
y = np.arange(20)

ds = xr.Dataset(coords={'x': x, 'y': y})
ds['_y'] = (0*ds.x+ds.y)  # breaks apply_ufunc otherwise
ds = ds.chunk({'x': 1, 'y':1})

# let's say each experiment outputs 5 statistical diagnostics
Nstats = 5
some_exp = lambda x, y: np.ones((1,1,Nstats))

out = (xr.apply_ufunc(some_exp, ds.x, ds._y,
                     dask='parallelized',
                     output_dtypes=[float],
                     output_sizes={'stats': Nstats},
                     output_core_dims=[['stats']])
      )
```
I don't understand why I have to use the dummy variable `ds._y` in this case.
Having to rely on `apply_ufunc` seems like an overkill.

**Comment by fujiisoup** [comment]
Is 
```python
xr.apply_ufunc(some_exp, ds.x, ds._y,
                        dask='parallelized',
                        output_dtypes=[float],
                        output_sizes={'stats': Nstats},
                        output_core_dims=[['stats']], 
                        vectorize=True)
```
what you want?
This gives
```python

<xarray.DataArray (x: 10, y: 20, stats: 5)>
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        ...
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])
Coordinates:
  * x        (x) int64 0 1 2 3 4 5 6 7 8 9
  * y        (y) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
Dimensions without coordinates: stats

In [26]:                                                                        ```

**Comment by apatlpo** [comment]
thanks a lot, your suggestion does help getting rid of the necessity to build the `ds['_y']` variable.
Here is the updated `apply_ufunc` solution:
```
x = np.arange(10*100)
y = np.arange(20*100)

ds = xr.Dataset(coords={'x': x, 'y': y})
# ds = ds.chunk({'x': 1, 'y':1}) # does not change anything

# let's say each experiment outputs 5 statistical diagnostics
Nstats = 5
some_exp = lambda x, y: np.ones((Nstats,))

out = xr.apply_ufunc(some_exp, ds.x, ds.y,
                      dask='parallelized',
                      vectorize=True,
                      output_dtypes=[float],
                      output_sizes={'stats': Nstats},
                      output_core_dims=[['stats']])
```
An inspection of the dask dashboard indicates that the computation is not distributed among workers though. 
How could I make sure this happens?

**Comment by apatlpo** [comment]
sorry closed by accident

**Comment by fujiisoup** [comment]
> An inspection of the dask dashboard indicates that the computation is not distributed among workers though.
> How could I make sure this happens?

Ah, I have no idea...
Are you able to distribute the function `some_exp` without wrapping by xarray?

Within my limited knowledge, it may be better to prepare another function that distributes `some_exp` over the workers and put this another function into `apply_ufunc`, but I am not 100% sure.
Probably there is a better way...

**Comment by apatlpo** [comment]
This sounds like method 1 (with dask delayed) to me.
There may be no faster option, thanks for giving it a thought @fujiisoup

**Comment by apatlpo** [comment]
I'll close this for now as there doesn't seem to be other ideas about this
