### ISSUE TITLE
ENH: Support more of the pandas str accessors

### ISSUE THREAD

**Issue by toddrjen** [pydata/xarray#3940]
Currently pandas supports a lot of str accessors that xarray doesn't.  Many of them have useful functionality.  I think it would be good if the xarray had more of these str accessors.  I would be willing to begin working on this.

There seem to be three categories.  One that has a one-to-one mapping between input and output (so one input element becomes one output element), and one that has a one-to-many mapping (one input element becomes multiple output elements), and one that has a many-to-one mapping (multiple input elements become one output element).  Exactly how the one-to-many mapping should be handling, if at all, is an open issue.  Some of the many-to-one mappings (specifically `join`) would need a dimension argument.

#### One-to-one

- [x] casefold(self)
- [x] normalize(self, form)

#### One-to-many

- [x] extract(self, pat[, flags, expand])
- [x] extractall(self, pat[, flags])
- [x] findall(self, pat[, flags])
- [x] get_dummies(self[, sep])
- [x] partition(self[, sep, expand])
- [x] rpartition(self[, sep, expand])
- [x] rsplit(self[, pat, n, expand])
- [x] split(self[, pat, n, expand])

#### Many-to-one

- [ ] cat(self[, others, sep, na_rep, join])
- [ ] join(self, sep)

**Comment by dcherian** [comment]
This sounds great. Looking forward to those PRa!
