### ISSUE TITLE
removing uneccessary dimension

### ISSUE THREAD

**Issue by lanougue** [pydata/xarray#3946]
Hi Everyone,

Sometimes I generate  DataArray which are invariant along a dimension. I was not able to find a function or a simple workaround to get rid of these dimensions (unless I already know their names). I would like to use something as a combination of "reduce" and "np.allclose". For the moment I use the equivalent code below which works but is not efficent.
Could it be a candidate for a native efficent xarray function? This can drastically reduce memory usage if relevant.
Thanks

```python
ds = xr.DataArray([[1.,2.],[1.,2.]], dims=('x','y'))

dims_to_remove=list()
for d in ds.dims:
    if np.all(ds[{d:0}]==ds): dims_to_remove.append(d)
ds = ds[dict.fromkeys(dims_to_remove,0)]
ds =  ds.squeeze()
```

**Comment by jthielen** [comment]
If allowing for some degree of tolerance, something like this would also be quite useful in geographic coordinate transformations when going from 2D lon/lat auxiliary coordinates to 1D x/y dimension coordinates. Here's an example of what we're currently doing in MetPy for this: https://github.com/Unidata/MetPy/blob/3aa0118ffbda48be2a426dee956183b7cef81f0c/src/metpy/xarray.py#L907-L947

**Comment by TomNicholas** [comment]
Hi @lanougue , thanks for the suggestion!

If I understand correctly, you want to check that all elements are close along one dimension, and if so, then select only one index from that dimension? That seems to me to be two consecutive operations, the first of which is a reduction, and the second is just `.isel`:
```python
da = xr.DataArray([[1.,2.],[1.,2.]], dims=('x','y'))

def reduce_if_constant_along_dim(da, dim):
    constant_along_dim = (da == da.isel(**{dim: 0})).all(dim)

    true = xr.full_like(da, fill_value=True).isel(**{dim: 0}, drop=True)
    if constant_along_dim.equals(true):
        return da.isel(**{dim: 0}, drop=True)
    else:
        return da

print(reduce_if_constant_along_dim(da, dim='x'))
```
```bash
<xarray.DataArray (y: 2)>
array([1., 2.])
```

or are you imagining something that applies the above function to every dim, more like:
```python
def drop_constant_dims(da):
    for dim in da.dims:
        da = reduce_if_constant_along_dim(da, dim)
    return da

print(drop_constant_dims(da))
```
```bash
<xarray.DataArray (y: 2)>
array([1., 2.])
```
There might be a slightly neater way using `reduce` somehow though.

**Comment by TomNicholas** [comment]
@jthielen you should be able to adapt my example to check for being within a tolerance rather than strict equality.

**Comment by TomNicholas** [comment]
If people think this would be useful addition to the API then we could add it - or it could just be a cookbook recipe.

**Comment by dcherian** [comment]
Cookbook seems like a nice place to put it

**Comment by lanougue** [comment]
@TomNicholas ,
Thanks for yor help. That is exactly what I wanted to do but, as you said there is probably a more efficent way to do it.

 @dcherian I needed this function because I sometimes use the groupby_bins() function followed by a concatenantion along a new dimension. This can drastically increase memory due to the multiplication of other variables in a Dataset.
Independantly of my usage, having a function that remove redundant data seems interessant to me. There is probably other combination of function that can accidently duplicate data.

**Comment by dcherian** [comment]
We need to fix groupby to ignore variables that don't have the grouped dimension.

**Comment by max-sixty** [comment]
Closing as stale, please reopen with an updated summary if relevant
