### ISSUE TITLE
Releasing memory?

### ISSUE THREAD

**Issue by johnomotani** [pydata/xarray#3948]
Once `xarray` (or `dask`) has loaded some array into memory, is there any way to force the memory to be released again? Or should this never be necessary?

For example, what would be the best workflow for this case: I have several large arrays on disk. Each will fit into memory individually. I want to do some analysis on each array (which produces small results), and keep the results in memory, but I do not need the large arrays any more after the analysis.

I'm wondering if some sort of `release()` method would be useful, so that I could say explicitly "can drop this DataArray from memory, even though the user might have modified it". My proposed workflow for the case above would then be something like:
```
da1 = ds["variable1"]
result1 = do_some_work(da1) # may load large parts of da1 into memory
da1.release() # any changes to da1 not already saved to disk are lost, but do not want da1 any more

da2 = ds["variable2"]
result2 = do_some_work(da2) # may load large parts of da2 into memory
da2.release() # any changes to da2 not already saved to disk are lost, but do not want da1 any more

... etc.
```

**Comment by lanougue** [comment]
Hi, If results1 is already evaluated, just replace
"da1.release()" with "del da1".
Python should automatically release the memory

**Comment by johnomotani** [comment]
OK, I think I've answered my own question. Looks like `dask` can handle this workflow already, something like:
```
# do_some_work does not call `.load()` or `.compute()` anywhere
result1a, result1b, result1c = dask.compute(do_some_work(ds["variable1"])

result2a, result2b, result2c = dask.compute(do_some_work(ds["variable2"])

... etc.
```

I do still wonder if there might be any case where `.release()` might be useful...

**Comment by johnomotani** [comment]
Thanks @lanougue, but what if I might want to re-load `da1` again later, ie. if `da` came from some Dataset `da = ds["variable"]`, I want to leave `ds` in the same state as just after I did `ds = open_dataset(...)`? Wouldn't `del da` remove `"variable"` from `ds`? Or maybe not free any memory if `ds` still has a reference to the DataArray?

**Comment by dcherian** [comment]
Afaik "release" happens during garbage collection, so deleting things with `del` is the way to go.

I have also been using `cluster.restart()`  to start from scratch

**Comment by johnomotani** [comment]
Thanks @lanougue, @dcherian I think I see the simple answer now: use a deepcopy first, to leave the Dataset as is, then `del` the DataArray when finished with it, e.g.
```
da1 = ds["variable1"].copy(deep=True)
... do stuff with da1 ...
del da1

da2 = ds["variable2"].copy(deep=True)
... do stuff with da2 ...
del da2

... etc.
```

**Comment by johnomotani** [comment]
Sorry for the noise, but at least I will be glad of something to search for next time I forget how to do something like this!
