### ISSUE TITLE
Doc improvement for DataArray.assign_coords

### ISSUE THREAD

**Issue by EtienneCmb** [pydata/xarray#3952]
Hi, first I wanted to say that xarray is a really fantastic library, it saves so many manipulations in my work.

I was looking for a way to add a coordinate to a DataArray and attribute it to a specific dimension. I found that the following syntax was exactly what I was looking for :

```python
da.assign_coords(new_coordinate=('dim_to_use', values))
```

However, the [documentation](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.assign_coords.html#xarray.DataArray.assign_coords) of the method was not referencing this syntax. What do you think?

**Comment by dcherian** [comment]
:+1: can you send in a PR with some add text and an example?

**Comment by EtienneCmb** [comment]
Sure, I'll add it to the doc and example
