### ISSUE TITLE
Masking and preserving int type

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#3955]
When DataArray is masked by `.where()`, the type is converted to `float64`.

But, if we need to use the DataArray ouput from `.where()` in `.isel()`, the dtype should be `int`.
(#3949 )
 

#### MCVE Code Sample
```python
import numpy as np
import xarray as xr

val_arr = xr.DataArray(np.arange(27).reshape(3, 3, 3),
                       dims=['z', 'y', 'x'])

z_indices = xr.DataArray(np.array([[1, 0, 2],
                                  [0, 0, 1],
                                  [-2222, 0, 1]]),
                         dims=['y', 'x'])

fill_value = -2222
sub = z_indices.where(z_indices != fill_value)
indexed_array = val_arr.isel(z=sub)
```

#### Expected Output
```
array([[ 1,  0,  2],
       [ 0,  0,  1],
       [nan,  0,  1]])
```

#### Problem Description
```
  File "E:\miniconda3\envs\satpy\lib\site-packages\xarray\core\indexing.py", line 446, in __init__
    f"invalid indexer array, does not have integer dtype: {k!r}"
TypeError: invalid indexer array, does not have integer dtype: array([[ 1.,  0.,  2.],
       [ 0.,  0.,  1.],
       [nan,  0.,  1.]])
```

Currently, pandas [supports NaN values](https://pandas.pydata.org/pandas-docs/version/0.24/whatsnew/v0.24.0.html#optional-integer-na-support). Is this possible for xarray? or another method around?

**Comment by kmuehlbauer** [comment]
There has been a lot of discussion about the int vs nan problem in the past, here one issue #1194. My question fpr xarray-devs would be too, if there is some idea on adapting to the pandas scheme?

In the time being, you might just go the other way round (`isel` before `where`) and this little hack:

```python
# overwrite fill_values with 0
sub = xr.where(z_indices == fill_value, 0, z_indices)
# isel with sub and mask with where
indexed_array = val_arr.isel(z=sub).where(z_indices != fill_value)
```

**Comment by zxdawn** [comment]
@kmuehlbauer Thanks, Nice trick! It works well for this situation.

**Comment by shoyer** [comment]
I would love to have support for integer NA values in xarray, but I don't think we want to build it into xarray.

Ideally this would either be built into NumPy (i.e., with a custom dtype, which will require some work before its possible) or someone could build an "integer with NA" duckarray, which could implement the various NumPy protocols such as `__array_function__`. The later is a bit less elegant but could be done today with very few changes in xarray changes .

**Comment by dcherian** [comment]
Closing as an upstream issue. We need either numpy to add support or for pandas extensionarrays to support the necssary protocols (#5287)
