### ISSUE TITLE
Why does open_dataset not accept a data_vars argument like open_mfdataset?

### ISSUE THREAD

**Issue by NOAA-CHAMP** [pydata/xarray#3965]
I am attempting to write a generic function to read a list of named variables from a dataset (attempt is to write a generic function that accepts the name of either a GRIB2 or netCDF file). For multiple-file datasets, the "data_vars" kwarg of open_mfdataset is very useful for this, but there seems to be no such argument for open_dataset. I can of course drop variables "by hand", but this seems error prone and I am not clear why it is necessary that it should be this way. Thanks to all!

**Comment by dcherian** [comment]
So that `data_vars` argument controls what variables are concatenated: https://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html so it doesn't do what you think it does.

If you have a list of variables names, you can `ds = xr.open_dataset(...)[varnames]` to subset.
