### ISSUE TITLE
Support static type analysis 

### ISSUE THREAD

**Issue by eric-czech** [pydata/xarray#3967]
As a related discussion to https://github.com/pydata/xarray/issues/3959, I wanted to see what possibilities exist for a user or API developer building on Xarray to enforce Dataset/DataArray structure through static analysis.

In my specific scenario, I would like to model several different types of data in my domain as Dataset objects, but I'd like to be able enforce that names and dtypes associated with both data variables and coordinates meet certain constraints. 

@keewis mentioned an example of this in https://github.com/pydata/xarray/issues/3959#issuecomment-612076605 where it might be possible to use something like a ```TypedDict``` to constrain variable/coord names and array dtypes, but this won't work with TypedDict as it's currently implemented.  Another possibility could be generics, and I took a stab at that in https://github.com/pydata/xarray/issues/3959#issuecomment-612513722 (though this would certainly be more intrusive). 

An example of where this would be useful is in adding extensions through accessors:

```python
@xr.register_dataset_accessor('ext')
def ExtAccessor:
    def __init__(self, ds)
        self.data = ds
    
    def is_zero(self):
        return self.ds['data'] == 0

ds = xr.Dataset(dict(DATA=xr.DataArray([0.0])))
# I'd like to catch that "data" was misspelled as "DATA" and that 
# this particular method shouldn't be run against floats prior to runtime
ds.ext.is_zero() 
```

I probably care more about this as someone looking to build an API on top of Xarray, but I imagine typical users would find a solution to this problem beneficial too.

There is a related conversation on doing something like this for Pandas DataFrames at https://github.com/python/typing/issues/28#issuecomment-351284520, so that might be helpful context for possibilities with ```TypeDict```.

**Comment by crusaderky** [comment]
What you're asking for has two huge blocker dependencies:

- Type annotations for numpy: https://github.com/numpy/numpy/issues/7370
- The ability to define TypedDict-like annotations for a generic MutableMapping subclass. Such a feature should be suggested to the python core devs.

**Comment by dcherian** [comment]
See #6462 also

**Comment by headtr1ck** [comment]
Lets continue the discussion over at https://github.com/pydata/xarray/issues/8199 which is a more generic feature request but should cover this as well.
