### ISSUE TITLE
Rolling.py

### ISSUE THREAD

**Issue by Julai091** [pydata/xarray#3971]
I'm tryng to plot ENSO anomalies using rolling using:

```python
sst_anom_nino34_mean = sst_anom_nino34.mean(dim=('lon', 'lat'))
oni = sst_anom_nino34_mean.rolling(time=3).mean(dim='time')
```

But i get this :

```pytb
C:\Users\Juliana\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Reductions will be applied along the rolling dimension 'time'. Passing the 'dim' kwarg to reduction operations has no effect and will raise an error in xarray 0.16.0.
```
  
This code was working normally, but i had to reinstall Anaconda. I guess something went wrong.

Any clues?

Thank you!

Juliana

**Comment by dcherian** [comment]
The `dim='time'` in `mean()` is redundant because you've already specified `time` in `rolling()`. The message is asking you to remove `dim='time'`

**Comment by Julai091** [comment]
Thank youuu!
