### ISSUE TITLE
load_dataset fails when filename is unicode

### ISSUE THREAD

**Issue by pnsaevik** [pydata/xarray#3974]
It seems like xarray does not handle unicode file names. The error is present even if the unicode characters appear in the parent path.

#### MCVE Code Sample

```python
import xarray as xr
import os
xr.Dataset().to_netcdf('caesar.nc')
os.rename('caesar.nc', 'cæsar.nc')
try:
    xr.load_dataset('cæsar.nc')
    print('Success')
except FileNotFoundError:
    print('File not found')
```

#### Expected Output
'Success'

#### Actual Output
'File not found'

#### Problem Description
xarray does not recognize file names with unicode letters

#### Versions

<details><summary>Output of `xr.show_versions()`</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.7 (default, Mar 23 2020, 23:19:08) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: 4.6.1

xarray: 0.15.1
pandas: 1.0.3
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.1.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.14.0
distributed: 2.14.0
matplotlib: 3.1.0
cartopy: 0.17.0
seaborn: None
numbagg: None
setuptools: 46.1.3.post20200330
pip: 20.0.2
conda: 4.8.3
pytest: 5.4.1
IPython: 7.13.0
sphinx: None

</details>

**Comment by pnsaevik** [comment]
Update: The error does not seem to be present on linux:


INSTALLED VERSIONS
------------------
commit: None
python: 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1062.18.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: 4.6.1

xarray: 0.15.0
pandas: 1.0.1
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.1
dask: 2.10.1
distributed: 2.10.0
matplotlib: 3.1.3
cartopy: 0.17.0
seaborn: 0.10.0
numbagg: None
setuptools: 45.2.0.post20200210
pip: 20.0.2
conda: None
pytest: 5.3.5
IPython: 7.12.0
sphinx: 2.4.0

**Comment by max-sixty** [comment]
This also works on Mac. What system does it not work on — windows?

**Comment by pnsaevik** [comment]
After investigating the issue, it seems to be related to an error in the netcdf library, which in turn is related to an error in the hdf5 library. The relevant issues are

netcdf4: https://github.com/Unidata/netcdf4-python/issues/941
hdf5: https://forum.hdfgroup.org/t/non-english-characters-in-hdf5-file-name/4627/8

Quoting the dev responding in the hdf5 forum:

> I would be thrilled to fix this issue. The problem is that it’s a huge amount of effort with no obvious funding source. Everyone wants this problem to be fixed but nobody wants it fixed so badly that they are willing to pay for an engineer to spend the better part of a year fixing it properly. A lot of people seem to think that we just need to tweak the “open file” code, but that isn’t true. So much stuff in the library is affected by Unicode file names on Windows and doing a hasty job will risk dramatically increasing our technical debt and bug count.
