### ISSUE TITLE
DataArray.to_netcdf breaks in filename-dependent manner

### ISSUE THREAD

**Issue by half-adder** [pydata/xarray#3997]
Writing a DataArray to disk breaks if the filename is `test.nc`. I'm unsure if other names pose a similar problem.

#### MCVE Code Sample

```python
# load data into `imgs`
>>> type(imgs) == xr.core.dataarray.DataArray
True

>>> filename = '/Users/sean/Desktop/test.nc'
>>> imgs.to_netcdf(filename)
>>> xr.open_dataarray(filename)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-132-9eaec208384d> in <module>
      2 filename = '/Users/sean/Desktop/test.nc'
      3 imgs.to_netcdf(filename)
----> 4 xr.open_dataarray(filename)

~/opt/anaconda3/envs/pharedox/lib/python3.7/site-packages/xarray/backends/api.py in open_dataarray(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, autoclose, concat_characters, decode_coords, engine, chunks, lock, cache, drop_variables, backend_kwargs, use_cftime)
    676     if len(dataset.data_vars) != 1:
    677         raise ValueError(
--> 678             "Given file dataset contains more than one data "
    679             "variable. Please read with xarray.open_dataset and "
    680             "then select the variable you want."

ValueError: Given file dataset contains more than one data variable. Please read with xarray.open_dataset and then select the variable you want.

>>> filename = '/Users/sean/Desktop/testing.nc'
>>> imgs.to_netcdf(filename)
>>> xr.open_dataarray(filename)
```
![image](https://user-images.githubusercontent.com/10676434/80130304-f9f11300-855d-11ea-9ba3-1730068a6dca.png)

#### Expected Output
![image](https://user-images.githubusercontent.com/10676434/80129938-70414580-855d-11ea-9f93-a83a878b0be2.png)

#### Problem Description

Saving the DataArray to a file called `test.nc` seems like it generates a DataSet with multiple variables? Or otherwise destroys the expected formatting for `xr.load_datarray`.

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:05:27) 
[Clang 9.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 19.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.3

xarray: 0.15.1
pandas: 1.0.1
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: 0.8.0
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.11.0
distributed: 2.14.0
matplotlib: 3.1.3
cartopy: None
seaborn: 0.10.0
numbagg: None
setuptools: 45.2.0.post20200209
pip: 20.0.2
conda: None
pytest: 5.3.5
IPython: 7.12.0
sphinx: 2.4.3

</details>

**Comment by TomNicholas** [comment]
That's odd - can you get the same error with a reproducible example (i.e. using data that we could also either create or access)?

**Comment by half-adder** [comment]
[data.npy.zip](https://github.com/pydata/xarray/files/4524630/data.npy.zip)

Unzip data.npy.zip into data.npy

```python
data = xr.DataArray(
    np.load('/Users/sean/Desktop/data.npy'),
    dims=('animal', 'timepoint', 'pair', 'wavelength', 'y', 'x')
)
data.to_netcdf('/Users/sean/Desktop/test.nc')
xr.open_dataarray('/Users/sean/Desktop/test.nc')
```
output:
```

**Comment by half-adder** [comment]
I believe this is related to #4042
