### ISSUE TITLE
Add hook to get progress of long-running operations

### ISSUE THREAD

**Issue by cwerner** [pydata/xarray#4000]
Hi. I currently work on a large dataframe that I convert to a Xarray dataset. It works, but takes quite some (unknown) amount of time.
#### MCVE Code Sample

```python
data = pd.DataFrame("huge data frame with time, lat, Lon as multiindex and about 60 data columns ")
dsout = xr.Dataset()
dsout = dsout.from_dataframe(data)
```

#### Expected Output
A progress report/ bar about the operation

#### Problem Description
It would be nice to have some hook or other functionality to tap into the xr.from_dataframe() and return a progress status that I then could pass to tqdm or something similar...

#### Versions
0.15.1

</details>

**Comment by TomNicholas** [comment]
If your operation uses dask then you can use the [dask progress bar](https://docs.dask.org/en/latest/diagnostics-local.html#progress-bar):
```python
from dask.diagnostics import ProgressBar

with ProgressBar:
     result = analyse(ds)
     result.plot()
```
It looks like
```
[########################################] | 100% Completed | 34.5 s
```

This works for any operation which calls `dask.compute`.

**Comment by rabernat** [comment]
Whenever working with big data in xarray, the recommendation is to use dask, as @TomNicholas says.

It would be great if we could go directly from a dask.dataframe to an xarray dataset with dask arrays. Unfortunately this is not supported (yet): https://github.com/dask/dask/issues/6058

I believe our dev time would best be spent working on that integration, rather than building progress bars directly into xarray.

**Comment by jhamman** [comment]
I agree with @rabernat and @TomNicholas that the easiest/best way to get progress information for computation is to use Dask. 

We may want to consider something like a progress metric for a few Xarray operations that we can't offload to third party libraries. I'm mostly thinking of xarray's combine/merge/concat functions as opportunities for Xarray to improve its user experience. Simply telling the user how a task like `open_mfdataset` is progressing could go a long way toward improving the user's toleration for slow/challenging dataset construction operations (e.g. #1385).
