### ISSUE TITLE
Concatenate DataArrays on one dim when another dim has difference sizes

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#4016]
It's impossible to concatenate two arrays on same named dimensions with different sizes.

#### MCVE Code Sample

```python
import xarray as xr
import pandas as pd

a = xr.DataArray([0], dims=['x'])
b = xr.DataArray([1, 2, 3], dims=['x'])
a = a.expand_dims("time")
b = b.expand_dims("time")
a.coords["time"] = pd.DatetimeIndex(['2020-02-14 05:25:10'])
b.coords["time"] = pd.DatetimeIndex(['2020-02-14 05:25:10'])
c = xr.concat([a, b], dim='time')
print(c)
```

#### Expected Output
```
[[0], [1, 2, 3]]
```

#### Problem Description
```
  File "C:\Users\Xin\Desktop\test_github.py", line 10, in <module>
    c = xr.concat([a, b], dim='time')
  File "E:\miniconda3\envs\satpy\lib\site-packages\xarray\core\concat.py", line 135, in concat
    return f(objs, dim, data_vars, coords, compat, positions, fill_value, join)
  File "E:\miniconda3\envs\satpy\lib\site-packages\xarray\core\concat.py", line 455, in _dataarray_concat
    join=join,
  File "E:\miniconda3\envs\satpy\lib\site-packages\xarray\core\concat.py", line 319, in _dataset_concat
    *datasets, join=join, copy=False, exclude=[dim], fill_value=fill_value
  File "E:\miniconda3\envs\satpy\lib\site-packages\xarray\core\alignment.py", line 327, in align
    % (dim, sizes)
ValueError: arguments without labels along dimension 'x' cannot be aligned because they have different dimension sizes: {1, 3}
```

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
libhdf5: 1.10.5
libnetcdf: 4.7.3

xarray: 0.15.1
pandas: 1.0.3
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: 2.4.0
cftime: 1.1.1.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.3
cfgrib: None
iris: None
bottleneck: None
dask: 2.10.1
distributed: 2.14.0
matplotlib: 3.2.1
cartopy: 0.17.0
seaborn: 0.10.0
numbagg: None
setuptools: 46.1.3.post20200325
pip: 20.0.2
conda: None
pytest: None
IPython: 7.13.0
sphinx: 2.4.4

</details>

**Comment by JavierRuano** [comment]
the time is the same. do you have tried to change the second one time index?

**Comment by JavierRuano** [comment]
pandas doesn't have that problem
import pandas as pd
x1=pd.DataFrame([['1','2','3']])
x2=pd.DataFrame([['4','5','6']])
pd.concat([x1,x2],axis=1)

**Comment by zxdawn** [comment]
@JavierRuano The time indexes are same in my real case. Maybe, I have to merge these data if I can't find the solution.

**Comment by dcherian** [comment]
umm... your expected result is a concatenation on `'x'`, which does work...

**Comment by zxdawn** [comment]
@dcherian Sorry. I made a mistake in the expected result. It should be
```
[[0], [1, 2, 3]]
```

**Comment by keewis** [comment]
you should be able to get this to work by assigning coordinates to `x`:
```python
In [7]: a = xr.DataArray([0], dims='x', coords={"x": [0]}) 
   ...: b = xr.DataArray([1, 2, 3], dims='x', coords={"x": [0, 1, 2]}) 
   ...: time = pd.DatetimeIndex(['2020-02-14 05:25:10']) 
   ...: a = a.expand_dims("time").assign_coords(time=time) 
   ...: b = b.expand_dims("time").assign_coords(time=time) 
   ...:  
   ...: c = xr.concat([a, b], dim='time') 
   ...: c
Out[7]: 
<xarray.DataArray (time: 2, x: 3)>
array([[ 0., nan, nan],
       [ 1.,  2.,  3.]])
Coordinates:
  * x        (x) int64 0 1 2
  * time     (time) datetime64[ns] 2020-02-14T05:25:10 2020-02-14T05:25:10
```
Note that `time` does not have unique values which means some operations won't work.
Also, `xarray` can't really do true ragged arrays (i.e. `[[0], [1, 2, 3]]` is not possible), so we use missing values instead

**Comment by zxdawn** [comment]
@keewis Thanks! I will try to apply this method and check the results.

**Comment by JavierRuano** [comment]
I think another solution you could add an aleat microsecond or nanosecond
field ... in the datetime index and the index should be different.
You could test if there are colision in the index (it means the
index<->time is not empty like the sort algorithm, something similar to
https://en.wikipedia.org/wiki/Radix_sort)


It is like the reverse of this solution

https://stackoverflow.com/questions/32827169/python-reduce-precision-pandas-timestamp-dataframe/32827432


Add another coordinate could be overloaded and xarray is very powerful to
extract slice of time
ds.sel(time =slice('2000-06-01', '2000-06-10'))

http://xarray.pydata.org/en/stable/time-series.html#datetime-indexing

I hope it could be useful.

Regards
Javier Ruano
