### ISSUE TITLE
'CFTimeIndex' object has no attribute 'days_in_month'

### ISSUE THREAD

**Issue by blucap** [pydata/xarray#4023]
In the [example](https://xarray.pydata.org/en/stable/examples/monthly-means.html) 'Calculating Seasonal Averages from Timeseries of Monthly Means', running this line in a live session: 

```python
month_length = ds.time.dt.days_in_month
```
Gives this error - apparently because the live session verions needs updating:

---------------------------------------------------------------------------
```AttributeError                            Traceback (most recent call last)
<ipython-input-16-35d62be99c4f> in <module>
----> 1 month_length = ds.time.dt.days_in_month

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/accessor_dt.py in f(self, dtype)
    171                 dtype = self._obj.dtype
    172             obj_type = type(self._obj)
--> 173             result = _get_date_field(self._obj.data, name, dtype)
    174             return obj_type(
    175                 result, name=name, coords=self._obj.coords, dims=self._obj.dims

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/accessor_dt.py in _get_date_field(values, name, dtype)
     76         return map_blocks(access_method, values, name, dtype=dtype)
     77     else:
---> 78         return access_method(values, name)
     79 
     80 

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/accessor_dt.py in _access_through_cftimeindex(values, name)
     30         field_values = _season_from_months(months)
     31     else:
---> 32         field_values = getattr(values_as_cftimeindex, name)
     33     return field_values.reshape(values.shape)
     34 

AttributeError: 'CFTimeIndex' object has no attribute 'days_in_month'
```

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.14.138+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.4

xarray: 0.15.1
pandas: 1.0.3
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.5.3
pydap: installed
h5netcdf: 0.8.0
h5py: 2.10.0
Nio: 1.5.5
zarr: 2.4.0
cftime: 1.1.1.2
nc_time_axis: 1.2.0
PseudoNetCDF: None
rasterio: 1.1.3
cfgrib: 0.9.8.1
iris: 2.4.0
bottleneck: 1.3.2
dask: 2.15.0
distributed: 2.15.2
matplotlib: 3.2.1
cartopy: 0.17.0
seaborn: 0.10.1
numbagg: installed
setuptools: 46.1.3.post20200325
pip: 20.1
conda: None
pytest: None
IPython: 7.11.1
sphinx: None

</details>

**Comment by spencerkclark** [comment]
That's true.  This example currently will only work with xarray master, so in the "latest" version of the docs this will appear broken in the binder environment.  This will be the case for any example which has been updated to use new functionality.

I guess a way to solve this would be to have a separate binder environment for each version of the docs (e.g. "latest" would use xarray master and dependencies compatible with that).  It could be some work to set that up, however.  Others more familiar with how the binderized examples were set up can perhaps comment more.

**Comment by blucap** [comment]
Thanks, belatedly, I realised that the code to create month_length is in the [docs](http://xarray.pydata.org/en/stable/examples/monthly-means.html).

**Comment by spencerkclark** [comment]
Indeed, I suppose I should have said "as written the example in the latest version of the docs will only work with xarray master" :)

In the meantime you may also find the fact that cftime dates now carry a `daysinmonth` attribute helpful:
```
In [1]: import cftime

In [2]: cftime.__version__
Out[2]: '1.1.2'

In [3]: cftime.DatetimeNoLeap(2000, 2, 1).daysinmonth
Out[3]: 28
```
We leverage this in the new `days_in_month` accessor for `CFTimeIndex`.
