### ISSUE TITLE
Visualize task tree

### ISSUE THREAD

**Issue by aaronspring** [pydata/xarray#4025]
While reading this excellent discussion on working with large onetimestep datasets https://discourse.pangeo.io/t/best-practices-to-go-from-1000s-of-netcdf-files-to-analyses-on-a-hpc-cluster/588/10 I asked myself again why we don’t have the task tree visualisation in xarray as we have in dask. 
Is there a technical reason that prevents us from implementing visualize?

This feature would be extremely useful for me. 

Maybe it’s easier to do this for dataarrays first. 

```python
#  ds = rasm Tutorial 
ds = ds.chunk({“time”:2})
ds.visualize()

```

#### Expected Output

Figure of task tree

https://docs.dask.org/en/latest/graphviz.html

#### Problem Description
visualize the task tree only implemented in dask. Now I recreate my xr Problem in dask to circumvent. Nicer would be .visualize() in xarray. 

https://discourse.pangeo.io/t/best-practices-to-go-from-1000s-of-netcdf-files-to-analyses-on-a-hpc-cluster/588/10

**Comment by dcherian** [comment]
`dask.visualize(ds)` should work.

**Comment by aaronspring** [comment]
this is great. thanks for the hint.

**Comment by aaronspring** [comment]
also works: `da.data.visualize()`
