### ISSUE TITLE
plot.pcolourmesh() plotting over NaNs

### ISSUE THREAD

**Issue by KenzaxTazi** [pydata/xarray#4037]
The `plot.pcolourmesh()` function plots overs NaNs to connect two or more clusters of data (see image).

![image](https://dl.dropboxusercontent.com/s/sp9s57zxpza3o7x/Screenshot%202020-04-24%20at%2016.22.38.png?dl=0)

#### MCVE Code Sample

```python

    plt.figure()
    ax = plt.subplot(projection=ccrs.PlateCarree())
    ax.set_extent([70, 83, 30, 38])
    g = UIB_outline.plot(cmap='Blues_r', vmax=-0.5, vmin=-5, add_colorbar=False)
    g.cmap.set_over('white')
    p = da.plot(cmap='magma_r', vmin=1.00, cbar_kwargs={'label': '\n Number of zero points', 'extend':'neither'})
    p.cmap.set_under('white')
    ax.add_feature(cf.BORDERS)
    ax.coastlines()
    ax.gridlines(draw_labels=True)
    ax.set_xlabel('Longitude')
    ax.set_ylabel('Latitude')
    plt.title('Zero points \n \n')
    plt.show()
```

#### Expected Output

By plotting the clusters separately, I can get the desired output. 

![image](https://dl.dropboxusercontent.com/s/lu0zn38vfn6s5rt/Screenshot%202020-05-03%20at%2018.46.18.png?dl=0) 

#### Problem Description
Requires manual separation of the data to get desired plot (not scalable)

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

commit: None
python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:05:27) 
[Clang 9.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 19.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.4

xarray: 0.11.3
pandas: 0.24.2
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.1.1.2
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
cyordereddict: None
dask: 2.14.0
distributed: 2.14.0
matplotlib: 3.2.1
cartopy: 0.17.0
seaborn: 0.10.0
setuptools: 46.1.3.post20200325
pip: 20.1
conda: 4.8.3
pytest: 5.2.2
IPython: 7.13.0
sphinx: None

</details>

**Comment by mathause** [comment]
I haven't had that happening - looks strange. It would be helpful if there was a reproducible example (that does not depend on an unknown dataset).

* What's the repr of the dataset?
* What happens for `da.plot(infer_intervals=False)`?
* Does this also happen outside of a cartopy map?
* Does matplotlib do it correctly? `plt.pcolormesh(ds.lon, da.lat, np.ma.masked_invalid(da.values)`

**Comment by dcherian** [comment]
Thanks @KenzaxTazi Please reopen with a reproducible example.
