### ISSUE TITLE
expanded HTML repr when opening notebook

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#4041]
When I open a notebook, the new HTML repr is "expanded": 

![image](https://user-images.githubusercontent.com/2448579/81222973-bc1bd200-8fd4-11ea-8afb-84d706ae9b56.png)

I'm running
```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.2
ipython          : 7.13.0
ipykernel        : 5.2.0
jupyter client   : 6.1.2
jupyter lab      : 2.1.0
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
```
and see this behaviour with both the notebook and jupyterlab interface; on both chrome and firefox (both on linux).

Is anyone else seeing this?

**Comment by aaronspring** [comment]
me too on Firefox linux

**Comment by jkmacc-LANL** [comment]
Same here, Firefox on a Mac.

**Comment by dcherian** [comment]
Maybe @jsignell can help fix this.

**Comment by jsignell** [comment]
Yeah I can take a look now.

**Comment by jsignell** [comment]
I can't reproduce: 

![image](https://user-images.githubusercontent.com/4806877/81570147-313d2d80-936e-11ea-99aa-6c5df00efd9e.png)

Tried on chrome and firefox on linux. Can you inspect the element in your browser console and see if there is a <style></style> section for the repr? It seems like that might not be getting in properly

**Comment by dcherian** [comment]
Thanks for taking a look @jsignell. Here are some notes I made while trying to reproduce.

1. I cannot reproduce at all locally with the same browsers. This problem may only occur with ssh tunneling. I tunnel to a remote machine; start a jupyter server; and then connect through a tunnel to that server. The next two points are about the remote notebook.

2.  Looks like there is no style attribute (this is from an older notebook with the problem)
![image](https://user-images.githubusercontent.com/2448579/81588679-66ff0800-93a8-11ea-8596-e3ff01302eb4.png)

There are two output cells with reprs, both of which are not styled correctly.

3. Now I run the first cell.
![image](https://user-images.githubusercontent.com/2448579/81589546-0a501d00-93a9-11ea-8073-d4c888c0970a.png)

The first cell looks right (and has a style attribute). The second one has auto-updated and looks OK but is missing the style attribute, as well as the click-to-show-data-values functionality.
![image](https://user-images.githubusercontent.com/2448579/81589310-dc6ad880-93a8-11ea-8b11-1faca7685117.png)

This "auto updating" behaviour is new i.e. wasn't happening last week. I'm on chrome 81 now so maybe all of this is just browser weirdness?

**Comment by jsignell** [comment]
Huh and if you re-run cell 69 does it render correctly? I'm on chrome 80, but if you were seeing this in firefox as well it seems like it's more likely to be a jupyterlab thing.

**Comment by jsignell** [comment]
It seems like the auto-update thing works for css, but not for icons.

**Comment by dcherian** [comment]
Yes the repr works perfectly when re-running these cells. The issue here is when I open an existing notebook with reprs in output cells.

I am on firefox beta :/ but yes it could be a jupyterlab thing.

**Comment by jsignell** [comment]
Does it seem possible that you had originally run it in jlab and then opened it in notebook or vice versa? I've seen html output get kind of messed up under those conditions, but I've never really stopped to debug it thoroughly.

**Comment by dcherian** [comment]
oh yes that is quite likely.

**Comment by jsignell** [comment]
Hmm. Ok. I'm still not sure why the html would get messed up under that scenario though.

**Comment by benbovy** [comment]
Might be explained by https://github.com/pydata/xarray/pull/1820#issuecomment-511236366 ?

**Comment by jsignell** [comment]
Yes that seems like the explanation. Thanks @benbovy! I would expect dask to have the same behavior then since they pass in the style tag in the same way.

**Comment by benbovy** [comment]
Maybe we could use some sort of hack with HTML [hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) attribute and some CSS, in order to show the plain text repr when CSS is not injected... Not ideal but at least it would be better than the HTML repr shown without CSS style.

**Comment by shoyer** [comment]
I’ve seen similar issues with the seeing unformatted CSS in notebooks on Github. I do think some sort of fallback to pure text mode would be great if we could make it work...
