### ISSUE TITLE
RuntimeError: NetCDF: HDF error

### ISSUE THREAD

**Issue by adibratul** [pydata/xarray#4050]
while checking some attributes from a netcdf file with following code 

#### MCVE Code Sample

```python
# Your code here
with xr.open_dataset(s5p_file, group='PRODUCT') as s5p_img_PRO:
    print(s5p_img_PRO)

```

#### Expected Output

a list of metadata should be appread
#### Problem Description

RuntimeError: NetCDF: HDF error
#### Versions
python 3.7 and jupyter notebook 
<details><summary>Output of <tt>xr.show_versions()</tt></summary>

</details>

**Comment by dcherian** [comment]
what is s5p_file? HDF error means your file couldn't be read for one of many reasons: corrupt file  for example.

**Comment by adibratul** [comment]
yes it was corrupted

**Comment by andres-castellano** [comment]
Another cause for this issue could be an unclosed netcdf file.
Specifically if you did something like:

my_file = Dataset('my_file.nc','w')

and did not close it with 

my_file.close()

The ncfile is still open and the HDF library still has a lock on it.
