### ISSUE TITLE
flake8 failure

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#4056]
flake8 is failing on master (https://dev.azure.com/xarray/xarray/_build/results?buildId=2820&view=logs&jobId=a577607c-d99b-546f-eeb4-2341e9a21630&j=a577607c-d99b-546f-eeb4-2341e9a21630&t=7308a173-bf34-5af1-b6d9-30c4d79bebeb) with

```
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/e6322963-dd1c-4887-ba6a-2aa7ec888f4c.sh
./xarray/backends/memory.py:43:32: E741 ambiguous variable name 'l'
./xarray/backends/common.py:244:32: E741 ambiguous variable name 'l'

##[error]Bash exited with code '1'.
Finishing: flake8 lint checks
```

**Comment by keewis** [comment]
this error is a recent addition to `pycodestyle`: https://pycodestyle.pycqa.org/en/latest/developer.html#a1-2020-04-23
