### ISSUE TITLE
Typo in Reading and writing files docs

### ISSUE THREAD

**Issue by clausmichele** [pydata/xarray#4059]
There is a typo in http://xarray.pydata.org/en/stable/io.html#rasterio

`In [35]: rds4326 = rio.rio.reproject("epsg:4326")`

Should instead be

`In [35]: rds4326 = rds.rio.reproject("epsg:4326")`

**Comment by keewis** [comment]
good catch. Would you like to put in a PR fixing that?

**Comment by clausmichele** [comment]
Sure, should I use the master branch or the fix-docs?

**Comment by keewis** [comment]
use `master` and create a new feature branch from there.
