### ISSUE TITLE
xr.plot cannot plot a latitude/longitude subset that it selected successfully

### ISSUE THREAD

**Issue by lucieknor** [pydata/xarray#4086]
I'm trying to plot a time series at a lat/lon from a 3-D dataset. "sel" successfully selects the desired subset, but the .plot() command yields an error: "Plotting requires coordinates to be numeric or dates of type np.datetime64 or datetime.datetime or pd.Interval." lat & lon are both float64 numeric data.

#### MCVE Code Sample

import numpy as np
import xarray as xr
import matplotlib as mpl

source url: http://apdrc.soest.hawaii.edu/thredds/dodsC/las/oisst_avhrrv20/data_apdrc.soest.hawaii.edu_dods_public_data_NOAA_SST_OISST_AVHRR_daily_v2.0.jnl 

ds_sst=xr.open_dataset(fname)
sst=ds_sst.sst

sst.isel(time=-1).plot() # this works

# this is what "sst" looks like: 
<xarray.DataArray 'sst' (time: 5810, latitude: 24, longitude: 26)>
[3625440 values with dtype=float32]
Coordinates:
  * time       (time) object 2004-05-31 00:00:00 ... 2020-04-26 00:00:00
  * latitude   (latitude) float64 19.88 20.12 20.38 20.62 ... 25.12 25.38 25.62
  * longitude  (longitude) float64 198.9 199.1 199.4 199.6 ... 204.6 204.9 205.1
Attributes:
    direction:      IJL
    ioos_category:  Temperature
    long_name:      sea surface temperature [degree c]

```python
# Your code here
sst.sel(latitude=20.38, longitude=199.6, method='nearest').plot()

```

#### Expected Output
# a time series plot at the specified lat/lon 

#### Problem Description

# this runs successfully:
sst_sub=sst.sel(latitude=21, longitude=190, method='nearest')
fig, ax = plt.subplots()
ax.plot(sst_sub)

so the subset is selected, but just cannot be plotted with xarray itself.

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.11.2
pandas: 0.23.4
numpy: 1.16.3
scipy: 1.2.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: 3.0.2
cartopy: None
seaborn: 0.10.1
setuptools: 46.4.0
pip: 18.1
conda: None
pytest: None
IPython: 7.2.0
sphinx: 2.0.1

</details>

**Comment by spencerkclark** [comment]
It looks like the time coordinate is made up of cftime objects.  We added support for plotting DataArrays with such coordinates in xarray version 12.0 through the external [`nc-time-axis`](https://github.com/SciTools/nc-time-axis) package.  Give updating xarray and installing `nc-time-axis` a try and I think this should work.

**Comment by lucieknor** [comment]
Thanks Spencer! I had already reinstalled the most recent version of xarray, but didn’t restart jupyter notebook where I was running it. It now actually works even without the nc-time-axis package. 

Cheers,
________________________________
Lucie Knor | PhD Candidate
Department of Oceanography
University of Hawaiʻi at Mānoa
+1(808)-436-7870

Pronouns: she/her

**Comment by spencerkclark** [comment]
Great, perhaps you had nc-time-axis installed already!  We only added it to `show_versions` at that time too.  I will go ahead and close this issue.
