### ISSUE TITLE
rename_dims to an existing dimension name

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#4093]
```
ds = xr.Dataset({"a": ("x", np.arange(10)), "b": ("y", np.arange(10))})
ds.rename_dims({"x": "y"})
```
```
ValueError: Cannot rename x to y because y already exists. Try using swap_dims instead.
```

This should be possible since both `x` and `y` have the same lengths. 
Thoughts?

For indexed dimensions, should we check that the indexes are equal?

**Comment by keewis** [comment]
When I added the error, my reasoning was that renaming dimensions (choosing a different name for a dimension) should not be mixed with swapping dimensions (using a different dimension for a variable).

see also #3645 and #3438

**Comment by dcherian** [comment]
Ah i didn't think `swap_dims` would work but it does! Thanks.,
