### ISSUE TITLE
`open_rasterio` fails in chunks

### ISSUE THREAD

**Issue by darribas** [pydata/xarray#4106]
I'm trying to process the [NLCD 2016](https://www.mrlc.gov/data/nlcd-2016-land-cover-conus) on a 16GB machine.

I open the file relying on dask:

```python
da = xarray.open_rasterio("NLCD_2016_Land_Cover_L48_20190424.imd",
                          chunks={"x": 15000, "y": 15000}
                         )
```

Then I try to aggregate the array with datashader to visualise and manipulate in memory:

```python
w = 600
h = int(da.shape[2] / da.shape[1])
rtr = ds.Canvas(plot_width=w,
                plot_height=h,
               ).raster(da.sel(band=1))\
                .compute()
```

This starts working but if I monitor progress on a dask.dristributed client, the graph completes all parallel tasks and, it seems, when it needs to "pull together" the results, I start getting workers restarting and eventually fails on memory (or has been running to way too long without much apparent progress, depending on the size of the chunks (I've tried from 4,000 to 100,000, the latest failing on memory earlier on).

Am I missing something on how to specify the chunks or to set it up so it could perform this computation? Any help most appreciated. Also, if this is not the appropriate channel, do let me know, happy to post somewhere else. Thank you very much for the awesome package and the support.

#### Versions

This is run on the [`gds_env:4.0`](https://github.com/darribas/gds_env/releases/tag/v4.0)

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-72-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: None
libnetcdf: None

xarray: 0.15.0
pandas: 1.0.3
numpy: 1.18.1
scipy: 1.4.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.2
cfgrib: None
iris: None
bottleneck: None
dask: 2.11.0
distributed: 2.11.0
matplotlib: 3.1.3
cartopy: None
seaborn: 0.10.0
numbagg: None
setuptools: 45.2.0.post20200209
pip: 20.0.2
conda: 4.7.12
pytest: 5.3.5
IPython: 7.12.0
sphinx: None

</details>

**Comment by dcherian** [comment]
`rioxarray` has this feature: https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray-open-rasterio

xarray's implementation in #2255 has stalled, so we'd welcome a PR if you have the time.

**Comment by darribas** [comment]
I feel out of breadth on my dask/xarray chops but to help (newbie on rasters/mdarrays) but love to see the proposal in #2255 implemented!

I'm closing for now as it seems the core of the question is covered on that discussion, but thanks very much for the quick and useful response! And again, for the awesome library!
