### ISSUE TITLE
Optionally create new figure automatically

### ISSUE THREAD

**Issue by zmoon** [pydata/xarray#4114]
#### Feature request

I think it would be nice to be able to configure (as a runtime option or somesuch) the behavior of the plotting methods if an `ax` is not passed. In settings like the Jupyter Notebook, I would prefer a new figure to be created automatically. I realize that you can achieve this by passing figure size kwargs like `figsize`, but it would be nice if you didn't have to.

Or, is there an easy way to runtime patch `xarray.plot.utils.get_axis` or another function to achieve this?

**Comment by max-sixty** [comment]
Sorry this didn't get a response @zmoon, particularly given your contributions to xarray and the broader community.

That said, I think I get this already, unless I'm misunderstanding?

![Uploading image.png…]()

**Comment by max-sixty** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/5635139/164053732-b9b41716-ac12-4342-9ce6-a4112c5507de.png">

**Comment by zmoon** [comment]
Thanks @max-sixty. I think it was with `%matplotlib widget` (ipympl) that I got the behavior I described. With `%matplotlib inline` (default inline backend) the figures get closed[^1] at the end of a cell, so the two plot commands would have to be in the same cell to get an overlay, which is fine. But with ipympl, this is not the case so you have to be more careful.

<details>
<summary>Example</summary>

![image](https://user-images.githubusercontent.com/15079414/164080131-07a8d5d1-86b5-44d4-811f-ab6f19b1bd0f.png)
</details>

[^1]: You can disable this behavior with `%config InlineBackend.close_figures=False` and get an overlay from plot commands in separate cells, but then you have to manually refresh the plot it seems.

**Comment by headtr1ck** [comment]
I assume this has been resolved then?
If not, feel free to reopen.
