### ISSUE TITLE
DataArray.plot.line color kwarg

### ISSUE THREAD

**Issue by martintb** [pydata/xarray#4115]
matplotlib.colors throws ValueError when a list of colors is passed to xr.DataArray.plot.line

#### MCVE Code Sample
```python
import matplotlib
import matplotlib.colors
import matplotlib.cm
import xarray as xr
import numpy as np

data = np.random.random((10,10))
x = np.arange(0,1.0,0.1)
y = np.arange(0,100,10.0)

norm = matplotlib.colors.Normalize(vmin=y.min(),vmax=y.max())
cmapper = matplotlib.cm.ScalarMappable(norm=norm,cmap=matplotlib.cm.viridis).to_rgba

da = xr.DataArray(data,dims=['x','y'],coords={'x':x,'y':y})
# da.plot.line(x='x',color=cmapper(da.y.values)) #throws ValueError in matplotlib/colors.py
da.to_pandas().plot(color=cmapper(da.y.values))
```

#### Expected Output
![image](https://user-images.githubusercontent.com/6588826/83367358-24ff2b80-a382-11ea-8b97-cd8c74363f8a.png)

#### Problem Description
I need to be able to map coordinate values to colors so that data plotted from different arrays are always aligned in colorspace. Depending on the data, specific y-values may be missing so a simple color cycle doesn't work here unfortunately. Passing a list of colors to pandas.plot seems to work but not for xarray.plot. While the obvious workaround is to cast to pandas, is there something I can do to make this work for xarray?

#### Versions
<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 19.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.3

xarray: 0.15.1
pandas: 1.0.3
numpy: 1.18.4
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.1.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.12.0
distributed: None
matplotlib: 3.2.1
cartopy: None
seaborn: 0.10.1
numbagg: None
setuptools: 47.1.0.post20200528
pip: 20.1.1
conda: None
pytest: None
IPython: 7.13.0
sphinx: None

</details>

**Comment by dcherian** [comment]
`plt.plot(data, color=cmapper(da.y.values))` fails with the same error. You'll have to figure out what pandas is doing here or alternatively what the matplotlib recommended way of doing this is (setting a  cycler?)

**Comment by martintb** [comment]
That's interesting and I really though that syntax worked for plain matplotlib.

Looking [here](https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_matplotlib/core.py#L1073) and [here](https://github.com/pandas-dev/pandas/blob/2428cdda3d9d11031a8efa637e9841f2aa16b490/pandas/plotting/_matplotlib/core.py#L709) it appears that they are manually mapping colors to dataframe columns. I can emulate this to some extent as:

```python
lines = da.plot.line(x='x')
colors = cmapper(da.y.values)
[l.set_color(c) for l,c in zip(lines,colors)]
```

I admit that I haven't read much on cyclers but I don't think they'll work well in my case as I mention above. If my first call to plot has ```np.arange(0,100,10.0)``` and the second ```np.arange(0,100,20.0)```, I still need the colors to correctly match up. Please correct me if there's a better what to do this!

Either way, this appears to be more of a feature request than a bug. I'll close this unless it warrants more discussion.
