### ISSUE TITLE
Mismatched Index Converting Pandas Dataframe to Xarray Dataset

### ISSUE THREAD

**Issue by falcon8241** [pydata/xarray#4119]
I notice this behavior happening in version 0.15.0 afterwards, but no in version 0.10.7.

When converting a Pandas Dataframe to Xaray Dataset using `from_dataframe`, there is a chance that the index will get mismatched.

```
import xarray as xr
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(12), index=pd.MultiIndex.from_product([[0, 1], ['bar', 'foo'], 
                                                                   list('HGD')]))
new_df = df.copy()
new_index = df.index.set_levels(['A', 'D', 'E', 'G', 'H'], level=2)
new_index = new_index.set_codes([4, 3, 1, 4, 3, 1, 4, 3, 1, 4, 3, 1], level=2)
new_df.index = new_index
xr.Dataset.from_dataframe(new_df).to_dataframe()
xr.Dataset.from_dataframe(df).to_dataframe()
```
`df` and `new_df` are intrinsically the same Dataframe, with `new_df` has some unused levels for the multi-index. However, `xr.Dataset.from_dataframe(new_df).to_dataframe()` and `xr.Dataset.from_dataframe(df).to_dataframe()` give different results, with the former has a misaligned index.

It seems the versions of numpy and pandas package do not matter, although I tried both the latest version, and numpy=1.16.2 and pandas=0.23.0

**Comment by dcherian** [comment]
Thanks for the report @falcon8241 . I think this is fixed on master by https://github.com/pydata/xarray/commit/1eedc5c146d9e6ebd46ab2cc8b271e51b3a25959
