### ISSUE TITLE
decode_cf doesn't work for ancillary_variables in attributes

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#4121]
Sometimes we have one attribute called `ancillary_variables` which is a list containing several strings. It would be useful to decode them.

#### MCVE Code Sample

```python
import numpy as np
import xarray as xr
import pandas as pd

temp = 15 + 8 * np.random.randn(2, 2, 3)
precip = 10 * np.random.rand(2, 2, 3)

temp = xr.DataArray(temp, dims=['x', 'y', 'time'])
precip = xr.DataArray(precip, dims=['x', 'y', 'time'])

lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]

temp.attrs['ancillary_variables'] = ['precip']
precip.attrs['ancillary_variables'] = ['temp']

ds = xr.Dataset({'temperature': temp,
                 'precipitation': precip},
                 coords={'lon': (['x', 'y'], lon),
                         'lat': (['x', 'y'], lat),
                         'time': pd.date_range('2014-09-06', periods=3),
                         'reference_time': pd.Timestamp('2014-09-05')})

ds.to_netcdf('test_ancillary_variables.nc', engine='netcdf4')

ds_new = xr.open_dataset('test_ancillary_variables.nc', decode_cf=True)
print(ds_new['temperature'])
```

#### Expected Output
```
......
Attributes:
    ancillary_variables:  [<xarray.DataArray (x: 2, y: 2, time: 3)> ......... ]
```

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.9.0-8-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.4

xarray: 0.15.1
pandas: 1.0.4
numpy: 1.18.4
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: 2.4.0
cftime: 1.1.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.5
cfgrib: None
iris: None
bottleneck: None
dask: 2.14.0
distributed: 2.17.0
matplotlib: 3.2.1
cartopy: 0.18.0
seaborn: None
numbagg: None
setuptools: 47.1.1.post20200529
pip: 20.1.1
conda: None
pytest: None
IPython: None
sphinx: None

</details>

**Comment by jthielen** [comment]
I think this could be a good fit for `cf-xarray` (see https://github.com/xarray-contrib/cf-xarray/issues/5). Although, with that in mind, perhaps a broader discussion on what CF features best fit in `decode_cf` vs. `cf-xarray` would likely be useful at some point?

**Comment by DWesl** [comment]
#2844 moves these variables to `ds.coords` rather than `ds.data_vars`, and allows saving of `ancillary_variables` via the `encoding` attribute.  I'm not sure if that is enough for your application.

**Comment by dcherian** [comment]
:+1: I think we should move this to cf-xarray which already [supports](https://cf-xarray.readthedocs.io/en/latest/selecting.html#associated-variables) interpreting the `ancillary_variables` attribute.
