### ISSUE TITLE
Bug in legend of dataset.plot.scatter

### ISSUE THREAD

**Issue by yohai** [pydata/xarray#4126]
When using Dataset.scatter with hue being a variable of dtype string, the legend turns out to be wrong.
#### MCVE Code Sample
```python
import xarray as xr
import numpy as np
dd = xr.Dataset({'y': (['x'], np.arange(8)),
                 'label': (['x'], list('AABBCCDD'))},
                coords={'x': np.linspace(0,1,8)})
dd.plot.scatter(x='x', y='y', hue='label')
```
Output is (note the legend):
![Figure_1](https://user-images.githubusercontent.com/6164157/83973237-a9572e80-a8ed-11ea-8aea-642dce259b2b.png)

Playing around it seems that it always chooses the first 4 values as the legend labels (note that the order of colors of the points is correct):
```python
import xarray as xr
import numpy as np
dd = xr.Dataset({'y': (['x'], np.arange(8)),
                 'label': (['x'], list('ABBACDDC'))},
                coords={'x': np.linspace(0,1,8)})
dd.plot.scatter(x='x', y='y', hue='label')
```
![Figure_2](https://user-images.githubusercontent.com/6164157/83973242-b96f0e00-a8ed-11ea-899d-72f0f82baf8a.png)

And if there are only 3 labels in total it chooses the first 3:
```python
import xarray as xr
import numpy as np
dd = xr.Dataset({'y': (['x'], np.arange(6)),
                 'label': (['x'], list('ABBACC'))},
                coords={'x': np.linspace(0,1,6)})
dd.plot.scatter(x='x', y='y', hue='label')
```
![Figure_1](https://user-images.githubusercontent.com/6164157/83973353-8e38ee80-a8ee-11ea-9c75-807fc2558dfe.png)

#### Expected Output
Legend in first two plots should read 'ABCD' and last plot 'ABC'

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.15.1
pandas: 0.25.1
numpy: 1.17.2
scipy: 1.3.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.9.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: 2.5.2
distributed: 2.5.2
matplotlib: 3.1.1
cartopy: None
seaborn: 0.9.0
numbagg: None
setuptools: 41.4.0
pip: 19.2.3
conda: 4.8.1
pytest: 5.2.1
IPython: 7.8.0
sphinx: 2.2.0

</details>

**Comment by yohai** [comment]
calling @dcherian for the rescue!

**Comment by phausamann** [comment]
The issue seems to be that the legend labels are overwritten incorrectly [here](https://github.com/pydata/xarray/blob/d9ebcafaddf0bb80052d30f43ca5ea18a5c7229f/xarray/plot/dataset_plot.py#L344). Commenting out that line fixes the problem for me.

**Comment by yohai** [comment]
thanks @dcherian & @phausamann !
