### ISSUE TITLE
Add text in FacetGrid subplots

### ISSUE THREAD

**Issue by pratiman-91** [pydata/xarray#4128]
Adding subplots numbers in the FacetGrid subplots. This will help in the easy generation of scientific publication quality figures.

#### MCVE Code Sample

```python
import xarray as xr

airtemps = xr.tutorial.open_dataset('air_temperature')
air = airtemps['air']
t = air.isel(time=slice(0, 365 * 4, 250))
g_simple = t.plot(x='lon', y='lat', col='time', col_wrap=3)

#adding sub plot number
string = ['a','b','c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']
for i, ax in enumerate(g_simple.axes.flatten()):
    ax.text(0.85, 0.85,'(' + string[i] +')',transform=ax.transAxes, 
            bbox=dict(boxstyle="square", fc="w", ec="k"))

```

#### Expected Output
![Figure 2020-06-08 113841](https://user-images.githubusercontent.com/31694629/83997716-a2c3c800-a97c-11ea-9458-58a46c70f848.png)

#### Problem Description

Currently, there is no argument that can enable the subplot numbers in the FacetGrid subplot. In the case of scientific publications, subplots need to be numbered. The addition of this feature will enable the easy generation of good quality figures. 

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 166 Stepping 0, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: 4.7.3

xarray: 0.15.1
pandas: 1.0.3
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.1.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.16.0
distributed: 2.16.0
matplotlib: 3.1.3
cartopy: 0.17.0
seaborn: 0.10.1
numbagg: None
setuptools: 46.2.0.post20200511
pip: 20.0.2
conda: 4.8.3
pytest: None
IPython: 7.13.0
sphinx: 3.0.3

</details>

**Comment by dcherian** [comment]
Thanks @pratiman-91 . Our goal with the plotting functions to enable easy visualization of datasets, not fully complete scientific plots. For this reason, labelling subplots seems out of scope to me. 

I recommend looking at proplot: https://proplot.readthedocs.io/en/latest/subplots.html#A-b-c-subplot-labels though I have not used it myself. I personally use a utility function that looks a lot like what you came up with.

**Comment by pratiman-91** [comment]
Thanks a lot for the information.
