### ISSUE TITLE
FacetGrid colorbar horizontal orientation 

### ISSUE THREAD

**Issue by pratiman-91** [pydata/xarray#4129]
When using Facetgrid with color orientation as horizontal, the map stretches and looks weird. The expected outcome should create extra space for the colorbar. 

#### MCVE Code Sample

```python
import xarray as xr

airtemps = xr.tutorial.open_dataset('air_temperature')
air = airtemps['air']
t = air.isel(time=slice(0, 365 * 4, 250))
g_simple = t.plot(x='lon', y='lat', col='time', col_wrap=3,
                  cbar_kwargs={'orientation': 'horizontal'})
```
Output: 
![Figure 2020-06-08 114452](https://user-images.githubusercontent.com/31694629/83998615-9e001380-a97e-11ea-9fe3-e309eb3008b8.png)

#### Expected Output
![Figure 2020-06-08 114436](https://user-images.githubusercontent.com/31694629/83998319-f08d0000-a97d-11ea-84cd-ca8cec1db90a.png)

#### Problem Description

The current behavior of the changes the aspect ratio of the subplots. The addition of this feather will enable a better-looking plot and can be directly used for publishing. 

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

</details>

**Comment by dcherian** [comment]
matplotlib's default behaviour for colorbars is to steal space from axes. I'm not sure there's much we can do without making the plotting code a lot more complex. How did you create the second figure?

**Comment by pratiman-91** [comment]
```
import xarray as xr
import matplotlib.pyplot as plt
airtemps = xr.tutorial.open_dataset('air_temperature')
air = airtemps['air']
t = air.isel(time=slice(0, 365 * 4, 250))
g_simple = t.plot(x='lon', y='lat', col='time', col_wrap=3,
                  add_colorbar=False)

mappable = g_simple.axes[0][0].collections[0]
cax = plt.axes([0.05, -0.04, 0.95, 0.04])
cbar1 = plt.colorbar(mappable, cax=cax, orientation='horizontal')
```
here the colobar is plotted using only first plots values.

**Comment by mathause** [comment]
I actually prefer the centering of the first one. Per default matplotlib does not use a fixed aspect ratio. To ensure maps look correct you may have to use cartopy (but that comes with its own set of challenges: https://stackoverflow.com/q/30030328/3010700)

**Comment by pratiman-91** [comment]
Thanks for the information.
