### ISSUE TITLE
Why am I able to load data from a closed dataset?

### ISSUE THREAD

**Issue by rsokl** [pydata/xarray#4131]
I don't understand why I am able to open and close a dataset, but then proceed to read data from said dataset.

I can open a 4 GB dataset and promptly close is, and then still access the data within, which appears to still be loading lazily. Does querying a closed dataset automatically reopen it?

#### MCVE Code Sample

```python
import numpy as np
import xarray as xr

ds = xr.Dataset({"foo": (("x",), np.random.rand(4,))}, coords={"x": [10, 20, 30, 40]})
ds.to_netcdf("tmp_example.nc")
```
```python
>>> data = xr.open_dataset("tmp_example.nc")
>>> data.close()
>>> data.foo
<xarray.DataArray 'foo' (x: 4)>
array([0.894788, 0.017935, 0.696086, 0.827004])
Coordinates:
  * x        (x) int64 10 20 30 40
```

#### Expected Output
Because netCDF data sets are loaded lazily, I would imagine that, having not been touched when opened, that closing the data set would render it inaccessible

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.4.0-166-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.2
libnetcdf: 4.6.1

xarray: 0.15.0
pandas: 1.0.3
numpy: 1.16.3
scipy: 1.4.1
netCDF4: 1.4.1
pydap: None
h5netcdf: None
h5py: 2.8.0
Nio: None
zarr: None
cftime: 1.1.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.14.0
distributed: None
matplotlib: 3.0.3
cartopy: None
seaborn: None
numbagg: None
setuptools: 46.1.3.post20200330
pip: 20.0.2
conda: None
pytest: 5.4.1
IPython: 7.5.0
sphinx: 2.4.4

</details>

**Comment by shoyer** [comment]
> Does querying a closed dataset automatically reopen it?

That's exactly right.

We could conceivably raise an error instead in these situations, since this is probably a case of user error.

**Comment by rsokl** [comment]
Ah, gotchya. Yeah it was quite jarring to see that leaving the `open_dataset` context manager didn't produce any noticeable change in the data accessibility.

In my passing opinion, it seems like it would be best to protect people, especially those who don't understand what context managers do, from themselves and have a closed dataset raise upon being queried. This is how all "closed" objects behave in my experience.

I'll leave this issue open in case there is any useful discussion to host here. But feel free to close it if that is more appropriate.

**Comment by kmuehlbauer** [comment]
This doesn't work when it is opened via netCDF4 and NetCDF4DataStore.

```python
import netCDF4 as nc
import xarray as xr
ncfile = nc.Dataset("tmp_example.nc")
dstore = xr.backends.NetCDF4DataStore(ncfile)
data = xr.open_dataset(dstore)
print(ncfile.isopen())
data.close()
print(ncfile.isopen())
print(data.foo)
```

```
True
False
/home/miniconda/envs/xarray/lib/python3.8/site-packages/xarray/backends/netCDF4_.py in _getitem(self, key)
     83             with self.datastore.lock:
     84                 original_array = self.get_array(needs_lock=False)
---> 85                 array = getitem(original_array, key)
     86         except IndexError:
     87             # Catch IndexError in netCDF4 and return a more informative

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__getitem__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.shape.__get__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable._getdims()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

RuntimeError: NetCDF: Not a valid ID
```

Also in @rsokl's case the `data._file_obj` is `None` after closing. First I thought that caching might be involved, but it doesn't seem the case. 

Nevertheless it seems unusual, that opening a file outside xarray will be closed inside xarray. At least I would not expect it, to be closed. Should I open another issue for this, @shoyer?

**Comment by shoyer** [comment]
> Nevertheless it seems unusual, that opening a file outside xarray will be closed inside xarray. At least I would not expect it, to be closed.

It isn't obvious to me what the right behavior is here. I can see a case for either closing the file (the user did request it to be closed, after all) or leaving it open.

**Comment by kmuehlbauer** [comment]
> It isn't obvious to me what the right behavior is here. I can see a case for either closing the file (the user did request it to be closed, after all) or leaving it open.

Sure, it's heavily depending on use case. But good to know what and where to look for in case anything unusual is going on.

**Comment by shoyer** [comment]
Given the ambiguity, I think it would be reasonable to raise an error when trying to close a file not opened by xarray.

This would be a breaking change, so we if we change this we would need to start by issuing a warning.

**Comment by rsokl** [comment]
Given that the user requested to close it, isn't it unambiguous that it should be closed?

**Comment by kmuehlbauer** [comment]
@rsokl Yes, you're right for your issue. In my comment above I was referring to the case where the file was opened outside xarray.

**Comment by shoyer** [comment]
A user might expect that they can write something like:
```python
with nc.Dataset("tmp_example.nc") as ncfile:
    dstore = xr.backends.NetCDF4DataStore(ncfile)
    with xr.open_dataset(dstore) as data:
        ...
```

Currently this raises an error when the outer context manager exits.

So maybe this is a case for not closing files that were not opened by xarray.

**Comment by rsokl** [comment]
Ah! Gotchya :)
