### ISSUE TITLE
Passing dimensions to data variable attributes

### ISSUE THREAD

**Issue by nathane1** [pydata/xarray#4132]
Hi,

I'm currently using XArray as a basis for analyzing precipitation data on a latitude/longitude grid. Initially, the data was stored within a text file; I converted it into a Pandas dataframe and then an XArray dataset. I can create new dimensions for the dataset itself; however, I want to pass these dimensions on to the data variable stored within the dataset. 

I'm then using rioxarray to clip the dataset based on certain latitude/longitude values. However, I think the problem lies with passing information from the dataset to the variable. My code is below:

```
precip = obs_dataset_full.precip.expand_dims(lon = 350, lat = 450)
obs_dataset_full.rio.set_spatial_dims('lon','lat')
cropped = obs_dataset_full.rio.clip(geometries=cropping_geometries, crs=4326)
```
With the following error resultant:
`DimensionError: x dimension (lon) not found. Data variable: precip`

I can pass the values to the data array with precip, but not to the variable itself. Output of the data array is as follows:

```
xarray.DataArray 'precip' lon: 350 lat: 450 dim_0: 350 dim_1: 451
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0 0.0 0.0 nan
Coordinates:
dim_0
(dim_0)
int64
0 1 2 3 4 5 ... 345 346 347 348 349
dim_1
(dim_1)
int64
0 1 2 3 4 5 ... 446 447 448 449 450
Longitude
(lon)
float64
-465.7 -465.7 ... -438.3 -438.3
Latitude
(lat)
float64
35.04 35.08 35.11 ... 51.52 51.56
Attributes: (0)
```

If anyone has any insight for how to pass the lon/lat dimensions to the data variable, it would be much appreciated!

**Comment by dcherian** [comment]
That error message is confusing.

The dimensions `lat` and `lon` exist but the coordinate labels are named `Longitude` and `Latitude`, which means that `rioxarray` cannot find them. Try `.rename({"Longitude": "lon", "Latitude": "lat"})` before passing to `rioxarray`.

**Comment by nathane1** [comment]
`precip.rename({'Longitude':'lon','Latitude':'lat'})`

I tried the above method and got the exact same error. I don't believe that would've been the problem because an error is being referenced with regards to the dimensions themselves, not the coordinates.

**Comment by dcherian** [comment]
Oh now I see, you've modified `precip` but are calling `obs_dataset_full.rio.`.

So change the first line to `obs_dataset_full["precip"] = ....expand_dims(...)`

**Comment by nathane1** [comment]
I believe this fixed the issue. Thank you!
