### ISSUE TITLE
upstream-dev failure when installing pandas

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#4133]
So after #4124 has been fixed upstream, we now have problems with installing `numpy` / `pandas`:

I'm not sure if I read the [logs](https://dev.azure.com/xarray/xarray/_build/results?buildId=3008&view=logs&j=2280efed-fda1-53bd-9213-1fa8ec9b4fa8&t=00866afd-4354-5206-6011-77c1437bd874) correctly, but it seems `pandas` (or the process to build their wheel, see their `pyproject.toml`) depends on `numpy==1.15.4` which doesn't have a wheel for py38 and thus the source distribution is chosen. I'm not sure why the building the wheel from sdist doesn't work anymore, though.

For reference, see the [logs of the last passing build](https://dev.azure.com/xarray/xarray/_build/results?buildId=3006&view=logs&j=2280efed-fda1-53bd-9213-1fa8ec9b4fa8&t=00866afd-4354-5206-6011-77c1437bd874).

**Comment by dcherian** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
@keewis not sure about the build issue, but we (along with many other projects) recently moved our wheels to upload to https://anaconda.org/scipy-wheels-nightly/. https://anaconda.org/scipy-wheels-nightly/pandas/ does have py38 wheels.

**Comment by TomAugspurger** [comment]
Ah, the (numpy) build failure is because pandas doesn't have a py38 entry in our pyproject.toml. Fixing that now.
