### ISSUE TITLE
xarray.where changes dimension order

### ISSUE THREAD

**Issue by schunkes** [pydata/xarray#4136]
Using xarray.where on a DataArray, changes the order of dimensions, putting the dimension, which was used in the condition in the first place.

This behavior can easily be reproduced with the code examples from [xarray.where](https://xarray.pydata.org/en/stable/generated/xarray.where.html)

#### MCVE Code Sample
```python
import xarray as xr
import numpy as np

y = xr.DataArray(
    0.1 * np.arange(9).reshape(3, 3),
    dims=["lat", "lon"],
    coords={"lat": np.arange(3), "lon": 10 + np.arange(3)},
    name="sst",
)

z = xr.where(y.lon < 1, y, -1)
```

#### Expected Output
```
>>> z
<xarray.DataArray (lat: 3, lon: 3)>
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
Coordinates:
  * lon      (lon) int64 10 11 12
  * lat      (lat) int64 0 1 2
```

#### Actual Output
```
>>> z
<xarray.DataArray (lon: 3, lat: 3)>
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
Coordinates:
  * lon      (lon) int64 10 11 12
  * lat      (lat) int64 0 1 2
```

#### Problem Description
I believe this is problematic behavior, since xr.transpose creates only a view to the reordered array but does not permanently reorder the dimensions again.

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
[Clang 9.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 19.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.UTF-8
libhdf5: None
libnetcdf: None

xarray: 0.15.1
pandas: 1.0.3
numpy: 1.18.4
scipy: 1.3.3
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.1.3
cartopy: None
seaborn: None
numbagg: None
setuptools: 46.3.0.post20200513
pip: 20.1
conda: None
pytest: 5.3.5
IPython: 7.14.0
sphinx: 3.0.3

</details>

**Comment by shoyer** [comment]
Dimensions on the outputs of an xarray operations are picked based on their order of appearance in the arguments.

In this case, I agree that it's somewhat surprising, but putting `lon` first is consistent with the order of dimensions in the function call `xr.where(y.lon < 1, y, -1)`.

If you want to preserve the original dimensions order, one way to achieve this would be to use the `where` _method_ instead, i.e., 
```
>>> y.where(y.lon < 1, -1)
<xarray.DataArray 'sst' (lat: 3, lon: 3)>
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
Coordinates:
  * lat      (lat) int64 0 1 2
  * lon      (lon) int64 10 11 12
```
