### ISSUE TITLE
Fix matplotlib in upstream-dev test config

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#4145]
From @keewis comment in #4138

> I just noticed that the rackcdn.org repository doesn't have matplotlib>=3.2.0, so since about late February we don't test against matplotlib upstream anymore.

**Comment by dcherian** [comment]
Maybe @QuLogic or @dopplershift could point us in the right direction?

**Comment by tacaswell** [comment]
Those wheels are (I think) built from https://github.com/MacPython/matplotlib-wheels/tree/master .  We also use that system to build the wheels we push to pypi, but from the `build-X.Y` branch.  The details of how the travis file needed to be configured changed and we never merged those changes back to master (which we have now done). but the builds are failing with an obscure error ( https://travis-ci.org/github/MacPython/matplotlib-wheels/jobs/697078308 ).

**Comment by tacaswell** [comment]
Thanks to @QuLogic the wheels are building and uploading again.

**Comment by keewis** [comment]
thanks for the quick fix
