### ISSUE TITLE
Working with symmetric matrices

### ISSUE THREAD

**Issue by chrism2671** [pydata/xarray#4158]
Apologies, I'm a newbie here, just moving over from Pandas.

I've got a square symmetric correlation matrix, `n x n`:

![2020-06-15-205923_768x163_scrot](https://user-images.githubusercontent.com/456541/84700523-33853f80-af4b-11ea-9c60-ac47277eeb72.png)

As it's a pairwise matrix, both axis must be `assetCode`.

I'm trying to work out to how to perform matrix operations on this.

Everything errors out when I try and do it:

    z * z
    z @ z

etc:

`ValueError: broadcasting cannot handle duplicate dimensions on a variable: ['assetCode', 'assetCode']
`

I understand the error, but I assume there must be standard way to handle symmetric matrices in `xarray`. What am I doing wrong?

**Comment by max-sixty** [comment]
There may be better ways: my workaround is to have `asset_code` and `asset_code_2`. I think there's been some discussion of allowing the same index on multiple dimensions; but there's inherent complexity in not being able to explicitly refer to a specific dimension.

**Comment by chrism2671** [comment]
Thanks. In the end I decided to just work with vanilla numpy, and keep track of labels separately. Thanks for your help nonetheless.
