### ISSUE TITLE
select range/ slice with method='nearest'

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#418]
It would be nice to support nearest neighbour selection with a slice like so: `ds.sel(lat=slice(30, 50), method='nearest')`. Maybe the `step` has to be disallowed.

Or is there another possibility how to achieve this functionality?

use case:
Often I look at a region with different data sets that don't have the same resolutions. It would be nice to be able to select the closest-matching region with an easy syntax.

**Comment by mathause** [comment]
I did a short hack - not sure if it is of any help...

#420

import xray
temp = 15 + 8 * np.random.randn(20)
lat = np.arange(0, 20)
ds = xray.Dataset({'temperature': ('lat',  temp)}, coords={'lat' : lat})
ds.sel(lat=slice(1.2, 5.9)) # lat = 2 3 4 5
ds.sel(lat=slice(1.2, 5.9), method='nearest') # lat = 1 2 3 4 5 6

**Comment by shoyer** [comment]
`ds.sel(lat=slice(30, 50))` will work to select all values inside interval `[30, 50]` already -- the values don't have to match exactly. This should probably be noted in the docs.

This inconsistency is definitely a little annoying, though -- I don't see any harm in support nearest neighbor lookups for the bounds.

**Comment by shoyer** [comment]
I just clarified this in the docs: http://xray.readthedocs.org/en/stable/indexing.html#nearest-neighbor-lookups

Let me know if that makes sense -- hopefully it's clear now that you actually don't need `method='nearest'` most use cases. As for your hack, I'm reluctant to support `method='nearest'` with label based slicing without the upstream functionality in pandas -- which would need to go in https://github.com/pydata/pandas/blob/be5ad4abcb9d8385110831edd138c1f644fe83ae/pandas/core/index.py#L2457

**Comment by mathause** [comment]
ok thank you for looking at it and the clarification.

**Comment by max-sixty** [comment]
Closing as stale, please reopen if still relevant
