### ISSUE TITLE
to_netcdf very slow for some single character data types

### ISSUE THREAD

**Issue by snbentley** [pydata/xarray#4180]
Hi,

I'm not entirely sure if this is a bug, my misuse, or a feature request. However, I don't think that this is desired behaviour: saving a dataset with single characters in the initial data type is very slow compared to a less desirable alternative.

Example:
make a smaller fake dataset, save it as it is (tester has dtype '<U1'), then change data type and do it again

``` python
import xarray as xr
import numpy as np
import cProfile


ds = xr.Dataset({'tester':('index',np.full((1000000),'.'))},coords = {'index':np.arange(0,1000000)})


cProfile.run("""ds.to_netcdf('somefilename')""")


ds.tester.values = ds.tester.values.astype('|S1')
cProfile.run("""ds.to_netcdf('somefilename')""")
```

I find that the first option takes around 8s and the second around 0.076s. This is a massive difference - my own dataset is much larger than this so I am obliged to save it using the |S1 dtype. However, this is much more difficult to use. I am using this field for quality control flags, and now == '.' doesn't work, so I have to wrap saving and loading these datasets with a function changing the datatype.

So I have a workaround but I don't think it makes sense to be this much slower to save single character strings. I also tried pickling the dataset with '<U1' datatype - that is very fast, but netCDF would be better.

<details><summary>Output of <tt>xr.show_versions()</tt></summary>
python: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-957.27.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.4

xarray: 0.15.1
pandas: 1.0.4
numpy: 1.18.5
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.1.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.18.1
distributed: 2.18.0
matplotlib: 3.2.1
cartopy: None
seaborn: None
numbagg: None
setuptools: 47.1.1.post20200529
pip: 20.1.1
conda: None
pytest: None
IPython: None
sphinx: None

</details>

**Comment by shoyer** [comment]
The profile shows that all the time is spent in the netCDF4 library.

By default, xarray writes string dtypes as variable length strings. That appears to be rather slow in netCDF4, for reasons that aren't clear to me.

One work around is to save the data as fixed-width character data instead, e.g.,
```
ds.to_netcdf('somefilename', encoding={'tester': {'dtype': 'S1'}})
```
Unlike `astype('|S1')`, this version safely encodes the data as UTF-8, so it an handle arbitrary Python strings.

**Comment by snbentley** [comment]
Ah that is a much better compromise - it's still slower for my own much larger dataset but is definitely manageable now. I think that this is what I was trying to find originally when I ended up using |S1.

As the problem was my usage of encoding / netCDF4's slow variable strings and you've given me a good workaround, I'll close this. Thanks for your help!
