### ISSUE TITLE
Keep single-value coordinates as dimensions

### ISSUE THREAD

**Issue by lusewell** [pydata/xarray#4185]
**Why**
Currently, operations like `.sel`, `.isel`, `.unstack` (and many others) will choose to have a non-dimension coordinate when an index would have just a single value in it.  For `.sel` and `.isel` you can avoid this by selecting a single element list, but `.unstack` this becomes a problem. However, given that these methods have a `drop` argument, and `.squeeze(drop=True)` exists to get rid of a dimension, I tend not to ever want the behaviour of the non-dimension coordinate - it no longer aligns on this coordinate when using operators, and to all effects behaves like that coordinate is not there, only remembering it for `concat`.

**Suggested feature**
A global option  (settable via `xr.set_options(...)`) to enforce that any length 1 coordinate is always kept as a dimension.

Ideally I'd like it so that this were the default behaviour, but I imagine the back-compatability problems that would generate would make it too unlikely a feature, but having a global option to change to this behaviour would be good enough.

**Comment by shoyer** [comment]
Could you give an example of the bad behavior for `unstack()`?

I am loathe to add global options because they tend to cause trouble for composability (e.e., you enable the option for your project and then it breaks the library you are using). But at least `unstack()` sounds like a real bug.

**Comment by max-sixty** [comment]
Please reopen with MCVE, thanks
