### ISSUE TITLE
DataArray.sortby is slower than NumPy's argsort

### ISSUE THREAD

**Issue by xlambein** [pydata/xarray#4211]
**Is your feature request related to a problem? Please describe.**

I tried to sort a `DataArray` with `sortby`:

```python
In [1]: import xarray as xr

In [2]: import numpy as np

In [3]: %%timeit
   ...: da = xr.DataArray(np.random.randn(100), coords=[("time", np.arange(100))])
   ...: da.sortby(da)
1.04 ms ± 70.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Out of curiosity, I tried to compare it to NumPy's `argsort` method:

```python
In [4]: %%timeit
   ...: da = xr.DataArray(np.random.randn(100), coords=[("time", np.arange(100))])
   ...: da[np.argsort(da.values, kind="stable")]
467 µs ± 7.24 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

I was surprised to see that the latter was more than twice as fast.

**Describe the solution you'd like**

Since it's possible to sort fast with NumPy, could it be possible for xarray to be as fast?

**Describe alternatives you've considered**

**Additional context**

I'm using xarray version `0.15.1`.

**Comment by shoyer** [comment]
These are really small arrays (100 elements). On small arrays, the overhead of Python tends to dominate over the main computation in NumPy.

If you increase the number of elements to one million or so the runtime gets much closer:
```python
import xarray as xr
import numpy as np

n = 1_000_000
da = xr.DataArray(np.random.randn(n), coords=[("time", np.arange(n))])
%timeit da.sortby(da)  # 200 ms per loop
%timeit da[np.argsort(da.values, kind="stable")]  # 192 ms per loop
```

**Comment by xlambein** [comment]
Interesting, I definitely should've tried that.

In my application I end up having to sort many relatively small DataArrays, which is why I came up with this example.  I can see how that way of using the library is kind-of an outlier, so it might not make sense to try and improve on what the package already does.  Where the speed is critical for me I'll just stick to using numpy.

Thank you :-)
