### ISSUE TITLE
what is the best way to reset an unintentional direct push to the master

### ISSUE THREAD

**Issue by fujiisoup** [pydata/xarray#4218]
I am sorry but I unintentionally pushed my working scripts to xarray.master. 
(I thought it is not allowed and I was not careful.)

What is the best way to reset this?
I'm thinking to do in my local, and force push again, but I'm afraid that I do another wrong thing...

I apologize for my mistake.

**Comment by keewis** [comment]
you could try to undo that by: getting the hash of the latest commit (7bf9df9d75c40bcbf2dd28c47204529a76561a3f right now), then calling
```sh
git reset <hash>
git push -f
```

Since I've been kind of afraid of that mistake as well, I added a git hook that makes git refuse to push to `master` and `stable` on the main repository (use `-n` to override it):
```bash
$ cat .git/hooks/pre-push
#!/usr/bin/env bash

protected_remotes="origin"
protected_branches="master stable"

isin() {
    local list="$1"
    local substring="$2"

    for element in $list
    do
        [[ "$element" == "$substring" ]] && return 0;
    done

    return -1;
}

readonly() {
    remote="$1"
    branch="$2"
    
    isin "$protected_remotes" "$remote" && isin "$protected_branches" "$branch" && return 0;
    return -1;
}

remote="$1"

IFS=" "
while read local_ref local_sha remote_ref remote_sha
do
    branch="$(echo $remote_ref | sed 's#^refs/heads/##g')"
    if readonly "$remote" "$branch"
    then
        echo "cannot push to $remote/$branch"
        exit -1
    fi
done
```

**Comment by fujiisoup** [comment]
Thanks. but it looks the master is protected and I cannot force push.
```
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to this protected branch
To https://github.com/pydata/xarray.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/pydata/xarray.git'
```

**Comment by fujiisoup** [comment]
Maybe I can unprotect the master, but I'm hesitating this action...

**Comment by keewis** [comment]
oh, yeah. Then someone with the appropriate permissions (you? or maybe @shoyer?) has to temporarily remove the branch protection (settings on github), force push, and then add back the branch protection.

**Comment by fujiisoup** [comment]
OK. Done. Thanks.
I'll use your script. Thanks.

And sorry again for my mistake.

**Comment by fujiisoup** [comment]
BTW, is it possible to disallow direct push to master on github?
Maybe we only need to *merge* PRs and but not *push*.

**Comment by keewis** [comment]
see this [SO question](https://stackoverflow.com/questions/46146491/prevent-pushing-to-master-on-github). However, I don't think we should try that since there are a few cases where you still need to push without a PR (releasing, mainly). So I think either a pre-push hook or `git config branch.master.pushRemote no_push` are the best way forward

**Comment by fujiisoup** [comment]
OK, thanks. 
> So I think either a pre-push hook or git config branch.master.pushRemote no_push (but then you also can't push to your own master anymore) are the best way forward

Agreed. I'll use your pre-push hook.
Thanks @keewis .

**Comment by max-sixty** [comment]
No stress @fujiisoup ! Glad this worked out.

We could disable push access and then people can manually re-enable when necessary. But no strong view.

**Comment by max-sixty** [comment]
It looks like @keewis isn't in https://github.com/orgs/pydata/teams/xarray/members so he couldn't change the permissions, can we change that? I think only @shoyer can add people to that team. 

Me and @jhamman seem to be in both that team and added to https://github.com/pydata/xarray/settings/access, which seems redundant (though not causing any bad outcomes either)

**Comment by shoyer** [comment]
As long as you don't force push (which is disabled), I think the preferred option for dealing with accidentally pushed changes is to push a "revert" commit generated from `git revert`

**Comment by shoyer** [comment]
But anyways, this is not a big deal at all! Git makes it very easy to mess things up, but as long as we keep the master branch protected, it's always possible always possible to move forward by reverting changes -- there is no way to lose work.

**Comment by fujiisoup** [comment]
> I think the preferred option for dealing with accidentally pushed changes is to push a "revert" commit generated from git revert

OK, understood.

> but as long as we keep the master branch protected, it's always possible always possible to move forward by reverting changes -- there is no way to lose work.

Then, probably the most dangarous part was when I unprotected the master branch.
I was afraid of messing up the commit history, but it is much better than losing entire commit history...

**Comment by keewis** [comment]
this was actually not that dangerous since everyone who synced the git history before that accident had a full "backup" of the commit history.

Would it make sense to add a section for "people with commit access" to `contributing.rst`? I imagine this could be useful as a reference and for new maintainers...

**Comment by max-sixty** [comment]
> As long as you don't force push (which is disabled), I think the preferred option for dealing with accidentally pushed changes is to push a "revert" commit generated from `git revert`

I think that's the right approach, so closing. Feel free to reopen though
