### ISSUE TITLE
Mask DataArray values outside given range

### ISSUE THREAD

**Issue by luke-gregor** [pydata/xarray#4223]
I did a quick search and couldn't find anything like this. 

I often find that I need to remove values outside of a certain range (i.e. mask values outside a range to NaN). This means I usually use `xr.DataArray.where`. However, this is not easy to do when you're piping operations and the initial array is not equivalent to the modified DataArray you're operating on. 

```python
# this is difficult to do when chaining/piping operations
xda = xda.where((xda > minval) & (xda < maxval))
```

`xr.DataArray.clip` achieves something similar, but does not mask the output. It would be great if `xr.DataArray.clip` or an equivalent could return an array where outside the min and max is the specified value (e.g. NaN). Alternatively, new functions could be added to DataArray as `between`/`outside`.

The first option would be to overload the implementation of `np.clip`, but either way, functionally it would be doing something like in the hacky solution below:

```python
def between(self, min=-np.inf, max=np.inf, return_value=np.NaN):
    xda = self.copy()
    mask = ((xda < min) | (xda > max)).values
    xda.values[mask] = return_value
    return xda
```

**Comment by dcherian** [comment]
How about using `DataArray.clip(...).fillna(..)`?

**Comment by luke-gregor** [comment]
> How about using `DataArray.clip(...).fillna(..)`?

Hmm, perhaps my description is a bit unclear. The function would be analogous to `xr.DataArray.clip`, but instead of clipping to the min/max, returns NaNs

**Comment by keewis** [comment]
you can still use `where` by passing it a function:
```python
xda = xda.where(lambda a: (a > min_value) & (a < max_value), fill_value)
```

**Comment by luke-gregor** [comment]
Neat! didn't think of that :-)

**Comment by keewis** [comment]
we need to update the docstrings, right now the only way to learn about that is by reading the examples.

I'm reopening this to make sure we won't forget.
