### ISSUE TITLE
Missing return type annotations

### ISSUE THREAD

**Issue by eric-czech** [pydata/xarray#4238]
[Dataset.to_dataframe](https://github.com/pydata/xarray/blob/1be777fe725a85b8cc0f65a2bc41f4bc2ba18043/xarray/core/dataset.py#L4536) should have a return type hint like [DataArray.to_dataframe](https://github.com/pydata/xarray/blob/1be777fe725a85b8cc0f65a2bc41f4bc2ba18043/xarray/core/dataarray.py#L2368).

Similarly, can [concat](https://github.com/pydata/xarray/blob/1be777fe725a85b8cc0f65a2bc41f4bc2ba18043/xarray/core/concat.py#L11) have a `Union[Dataset, DataArray]` return type or is it more complicated than that?

**Comment by shoyer** [comment]
Yes, this would be very welcome!

In theory `concat` might be able to use `@overload` to indicate a more precise type, but `Union[Dataset, DataArray]` would be a good start.
