### ISSUE TITLE
Manually drop DataArray from memory?

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#4243]
Is it possible to deliberately drop data associated with a particular DataArray from memory?

Obviously `da.close()` exists, but what happens if you did for example
```python
ds = open_dataset(file)
da = ds[var]
da.compute()  # something that loads da into memory
da.close()  # is the memory freed up again now?
ds.something()  # what about now?
```

Also does calling python's built-in garbage collector (i.e. `gc.collect()`) do anything in this instance?

The context of this question is that I'm trying to resave some massive variables (~65GB each) that were loaded from thousands of files into just a few files for each variable. I would love to use @rabernat 's new [rechunker package](https://github.com/pangeo-data/rechunker) but I'm not sure how easily I can convert my current netCDF data to Zarr, and I'm interested in this question no matter how I end up solving the problem.

I don't currently have a particularly good understanding of file I/O and memory management in xarray, but would like to improve it. Can anyone recommend a tool I can use to answer this kind of question myself on my own machine? I suppose it would need to be able to tell me the current memory usage of specific objects, not just the total memory usage.

(@johnomotani you might be interested)

**Comment by max-sixty** [comment]
I think this will require `del da` (and ensure you're not in an ipython / notebook session which has references to output variables).

**Comment by jhamman** [comment]
@TomNicholas - did you get to the bottom of this? Alright if we close this as stale?
