### ISSUE TITLE
combine_by_coords; proposition for a new option for combine_attrs = 'dim' 

### ISSUE THREAD

**Issue by ACHMartin** [pydata/xarray#4246]
I am combining a list of snapshots having all the same geometry but with different time. Some time information appears in the attributes. I can 'drop' it, but I would prefer keep it and add it using a define dimension (in my case, in time).
I believe for v0.15.1 (the default was to drop it with the default compat='no_conflicts'), I think of this because I got an error on the default combine_attrs = 'no_conflicts' on v0.16.0.

I would like an option of type combine_attrs = {dim: 'time'} or even better only combine_attrs = 'dim' and somehow it finds which dimension it should use.

Thanks

**Comment by dcherian** [comment]
> even better only combine_attrs = 'dim' and somehow it finds which dimension it should use.

This seems magical and quite likely to break in many cases. 

I suggest looping over your dataset and adding an extra dimension before sending the datasets to `combine_*`

**Comment by ACHMartin** [comment]
thank you for the suggestion
