### ISSUE TITLE
RTD PR builds are timing out

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#4249]
See https://readthedocs.org/projects/xray/builds/

There's no useful information in the logs AFAICT: e.g. https://readthedocs.org/projects/xray/builds/11504571/

**Comment by keewis** [comment]
This might be because of a `matplotlib` warning, see my own [RTD setup](https://readthedocs.org/projects/xarray-keewis/builds/11507133/). Not sure why the main build times out while mine fails cleanly.
