### ISSUE TITLE
[community] Backends refactor meeting

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#4253]
In today's dev call, we opted to schedule a separate meeting to discuss the backends refactor that BOpen (@alexamici and his team) is beginning to work on. This issue is meant to coordinate the scheduling of this meeting. To that end, I've created the following Doodle Poll to help choose a time: https://doodle.com/poll/4mtzxncka7gee4mq

Anyone from @pydata/xarray should feel free to join if there is interest. At a minimum, I'm hoping to have @alexamici, @aurghs, @shoyer, and @rabernat there.

_Please respond to the poll by COB tomorrow so I can quickly get the meeting on the books. Thanks!_

**Comment by jhamman** [comment]
Based on the poll above, we'll be meeting at 8a PT on July 28, 2020. https://carbonplan.whereby.com/xarray

**Comment by normanb** [comment]
@jhamman I will attend (if that is ok) as I am interested in how you are refactoring as part of a future TileDB integration into xarray.

**Comment by shoyer** [comment]
As discussed in the last xarray meeting, we'd like to make this a recurring weekly meeting, for most of the duration of the CZI grant.

I'm tentatively thinking 30 minutes but we can adjust if need be.

Here's a doodle with some scheduling options that should work in both the west coast of the US and Europe:
https://doodle.com/poll/tprri5z65vgy792b

**Comment by max-sixty** [comment]
Thanks @shoyer

**Comment by keewis** [comment]
Any updates on this? The poll currently has Thu, Aug 13 8:00-8:30 PDT (17:00-17:30 CEST) as the only scheduling option that suits everyone.

**Comment by shoyer** [comment]
Quick update — BOpen is currently on holiday, so we’re going to start this
up regularly the week of August 24.

**Comment by shoyer** [comment]
I really should have scheduled this already! 

Extrapolating availability from the doodle, let's try for 8am America/Los Angeles this Thursday, Aug 27. @alexamici your team is the most critical group for this, please let me know if that won't work and we can revisit.

@jhamman can you help put this on the calendar?

**Comment by alexamici** [comment]
@shoyer every other Thursday at 8am Los Angeles time works for us in general, but not tomorrow when both @aurghs and myself already made arrangements, sorry!

We have been studying the details of indexing, that lead us to find an embarrassing bug in cfgrib https://github.com/ecmwf/cfgrib/issues/157, and we are now getting into write support.

I think we can do without this week meeting and we will sync on the regular community meeting.

Feel free to set up regular meeting starting next week of in two weeks (alternating with the community meeting seem the easiest).

**Comment by shoyer** [comment]
Should we try for Thursday at 8am Los Angeles next week, that is on September 3?

As long as you are actively working on things, my preference would be to keep a regular weekly check-in so you aren't blocked, and we have time to go into more depth than we would in the regular community meeting.

**Comment by jhamman** [comment]
Hi All! Just getting back from vacation. The regular meeting is now on Xarray's Google Calendar: [link to event](https://calendar.google.com/event?action=TEMPLATE&tmeid=NWtwa3E0bTR1ZGtlcDduajExNXVoODQ4ZDFfMjAyMDA5MDNUMTUwMDAwWiB1Y2FyLmVkdV8yZ2pkNWZ1dWdjajRvbDZpajdrbmo4a3JuOEBn&tmsrc=ucar.edu_2gjd5fuugcj4ol6ij7knj8krn8%40group.calendar.google.com&scp=ALL).

Catch you all next week.

**Comment by alexamici** [comment]
So weekly meeting every Thurday, perfect (cc @aurghs @TheRed86)

**Comment by alexamici** [comment]
@jhamman & @shoyer, unfortunately neither @aurghs nor myself will be available tomorrow, 18 Feb. We can skip this week's meeting or reschedule it, same time but another day. Your call.

**Comment by jhamman** [comment]
closing because we've stopped the regular meeting.
