### ISSUE TITLE
Interpolation along dimension with a single element

### ISSUE THREAD

**Issue by mancellin** [pydata/xarray#4275]
Let me consider a DataArray with a dimension containing a single element:

```python
In [1]: import numpy as np

In [2]: import xarray as xr

In [3]: da = xr.DataArray(np.linspace(0.0, 100.0, 101).reshape(1, 101),
                                      coords=[('x', [1.0]), ('y', np.linspace(0.0, 1.0, 101))])
```

Asking `x=1.0` in `interp` fails.

More precisely, the 2D interpolation returns a NaN
```python
In [5]: da.interp(x=1.0, y=0.4)
/opt/anaconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py:2533: RuntimeWarning: invalid value encountered in true_divide
  (grid[i + 1] - grid[i]))
Out[5]:
<xarray.DataArray ()>
array(nan)
Coordinates:
    x        float64 1.0
    y        float64 0.4
```
and the 1D interpolation returns a `ValueError`:
```python
In [6]: da.interp(x=1.0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-efd4490bc97e> in <module>
----> 1 da.interp(x=1.0)
...
ValueError: x and y arrays must have at least 2 entries
```

I understand why the interpolation is impossible in an array with a single element.

However, this behavior breaks my assumption that `interp` is a superset of `sel`, meaning that it gives the same result as `sel` for all inputs that are valid inputs for `sel` (except for a possible int to float type conversion).

Here, I would expect `da.interp(x=1.0)` to give me the same result as `da.sel(x=1.0)`.

What do you think of this corner case?

**Comment by max-sixty** [comment]
Sorry this never got a response @mancellin . 

Do people think this is an issue? I'm not a regular user of `interp`. Does `sel` & `nearest` cover the case?

**Comment by mancellin** [comment]
No worry, I had actually forgotten about this.
In a more recent version (`2022.3.0`), both 1D and 2D case return the same `ValueError` with a relatively clear message `x and y arrays must have at least 2 entries`.

I'm still proposing that any valid code with `sel` should behave the same with `interp`, and thus that `interp` should work when a dimension has a single entry. But this is a low priority issue with easy workarounds.
