### ISSUE TITLE
Skipna not working in DataArray.rolling.mean 

### ISSUE THREAD

**Issue by mark-boer** [pydata/xarray#4278]
**What happened**:
I tried to calculate a rolling mean or median, ignoring nan's

**Minimal Complete Verifiable Example**:

```python
>>> da = xr.DataArray([1.0, 2, 3, np.nan, 5, 6])
>>> da.rolling(dim_0 = 3).mean(skipna=True)
<xarray.DataArray (dim_0: 6)>
array([nan, nan,  2., nan, nan, nan])
Dimensions without coordinates: dim_0
```

I expected this array to have have no nans. There is a simple workaround that does give the answer I was looking for:

```python
>>> da.rolling(dim_0 = 3).construct("new").mean("new", skipna=True)
<xarray.DataArray (dim_0: 6)>
array([1. , 1.5, 2. , 2.5, 4. , 5.5])
Dimensions without coordinates: dim_0
```

**Anything else we need to know?**:
Love the project ;-)

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.3 (default, May 16 2020, 07:08:28)
[GCC 8.3.0]
python-bits: 64
OS: Linux
OS-release: 4.19.76-linuxkit
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: None
libnetcdf: None

xarray: 0.16.0
pandas: 1.0.5
numpy: 1.19.1
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 46.4.0
pip: 20.1.1
conda: None
pytest: None
IPython: 7.16.1
sphinx: None

</details>

**Comment by dcherian** [comment]
the answer is to specify `min_periods` in `rolling()`: https://xarray.pydata.org/en/stable/generated/xarray.core.rolling.DataArrayRolling.html

It would be nice to allow `skipna` if `min_periods is None` but that might be become confusing.

**Comment by mark-boer** [comment]
Oh good point, after reading the docs, I thought that the `min_periods` was only related to the edges of the array.

**Comment by mark-boer** [comment]
I'll close this issue. Thank you @dcherian. I will have another look at the docs and if anything remains unclear, I'll have a look at adding a note or example.

**Comment by salonisheth-1** [comment]
What if I wanted to keep skipna=False, is there a workaround for that?

**Comment by salonisheth-1** [comment]
I basically want to implement min_periods=1, but I don't want to ignore NAs. If even one of the values is NAN, I want the rolling mean to give me NAN as the result.
