### ISSUE TITLE
failing docs CI

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#4287]
I'm not quite sure why (maybe a `pandas` or `matplotlib` release?), but the docs CI raises a [exception](https://readthedocs.org/projects/xray/builds/11556480/) in `plotting.rst`: https://github.com/pydata/xarray/blob/a081d01df11610adea7a48acee5a71d9eb5ffd16/doc/plotting.rst#L589-L590

there are also sphinx warnings about malformed rst:
```
/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/4286/lib/python3.8/site-packages/pandas/core/base.py:docstring of xarray.CFTimeIndex.max:7: WARNING: Inline strong start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/4286/lib/python3.8/site-packages/pandas/core/base.py:docstring of xarray.CFTimeIndex.min:7: WARNING: Inline strong start-string without end-string.
```
so I guess there was a `pandas` release a few days ago?

Edit: `pandas` 1.1.0 was released yesterday

**Comment by keewis** [comment]
I can confirm that downgrading fixes the build. Not sure what changed, but we should try to extend our plotting tests so we can catch this using the `upstream-dev` CI.

**Comment by dopplershift** [comment]
The exception looks like the identical problem as #4283 .

**Comment by keewis** [comment]
thanks, @dopplershift, the exception does indeed look like #4283.

The warnings are a `sphinx` bug (see sphinx-doc/sphinx#7799), but it will probably take some time until the release of `sphinx` 3.2.0. I guess that means we have to live with these warnings until then? We could use `suppress_warnings`, but that would ignore all warnings about invalid formatting.

**Comment by crusaderky** [comment]
Temporarily pinning pandas=1.0 in https://github.com/pydata/xarray/pull/4296
