### ISSUE TITLE
title bar of docs displays incorrect version

### ISSUE THREAD

**Issue by johnomotani** [pydata/xarray#4289]
**What happened**:
The browser title bar displays an incorrect version when viewing the docs online. See below - title bar says 0.15.1 but actual version in URL is 0.16.0.
![docs-snapshot](https://user-images.githubusercontent.com/3958036/88903135-14b4e100-d24b-11ea-9380-3da51c8e3b99.png)

`http://xarray.pydata.org/en/stable/` also displays 0.15.1 in the title bar, but I guess is actually showing 0.16.0 docs (?), which is confusing!

**Comment by keewis** [comment]
actually, it seems the reason for this is #3567: by not installing, we never call `setuptools_scm` to set the version (it doesn't use the `999` version we use as a fallback either, though, it uses the other version installed: right now `0.16.0`)

**Comment by keewis** [comment]
to fix that, we'd need to install the project using `pip`, but [RTD](https://github.com/readthedocs/readthedocs.org/issues/7345) uses `--upgrade --upgrade-strategy eager` without `--no-deps` which means we wouldn't be able to use version pinning. So I guess we have to wait on RTD?

**Comment by dcherian** [comment]
Thanks for tracking this down @keewis

**Comment by keewis** [comment]
they don't want to add `--no-deps` to the install command (see readthedocs/readthedocs.org#7345), but we can work around that by appending
```yaml
  - pip
  - pip:
    # path to the folder containing setup.py relative to the environment file
    # if I understand it correctly, this feature is only available when using editable installs
    - -e ../..
```
to our environment file (not sure if there's documentation about this, but there's an [example file](https://github.com/conda/conda/blob/master/tests/conda_env/support/advanced-pip/environment.yml)). Something similar should also work with requirements files.
