### ISSUE TITLE
Heavy operations with xarray cause Jupyter to restart (without throwing a crash or error)

### ISSUE THREAD

**Issue by mkleinbort** [pydata/xarray#4301]
**What happened**:

When running a "heavy" computation in xarray.Dataset my Jupiter notebook crashes silently.

**What you expected to happen**:

To either run successfully or raise some kind of warning (at least "Kernel crashed").

**Minimal Complete Verifiable Example**:

```python 

# In Jupyter Lab cell:

import xarray as xr

ds = xr.load_dataarray('data/stocks_snapshot.nc')

# ds.shape = (5159, 7, 97)
# Coordinates:
#   * Date        (Date) datetime64[ns] 1999-12-31 2000-01-03 ... 2020-06-29
#   * Instrument  (Instrument) object 'ACN' 'ATVI' 'ADBE' ... 'XRX' 'XLNX' 'ZBRA'
#   * Indicator   (Indicator) object 'Open' 'High' ... 'Dividends' 'Stock Splits'

ds.rolling({'Date':100}).mean()
```

**Environment**:

Docker container with xarray from python:3.8.5-buster

**Comment by max-sixty** [comment]
While I appreciate that's frustrating, there's not enough information in order to understand what's going on. 
I'm guessing it's an out-of-memory error. 
Do you have a reproducible example?

**Comment by mkleinbort** [comment]
My bad, this turned out to be an issue with my Jupyter Lab configuration and **had nothing to do with xarray**. It was crashing due to an out of memory error, and I was able to reproduce the issue with

```
import numpy as np
dicty = {}
for i in range(int(1e6)):
    print(i)
    dicty[i] = np.random.rand(100_000,100_000)
```
