### ISSUE TITLE
Installing from sources does not install everything

### ISSUE THREAD

**Issue by zerothi** [pydata/xarray#4302]
**What happened**:

When installing from [sources](https://github.com/pydata/xarray/archive/v0.16.0.tar.gz) the package isn't fully installed, e.g. the `core` directory never gets added.
```bash
-rw-r--r-- 1   27K Aug  3 09:43 conventions.py
-rw-r--r-- 1  9.5K Aug  3 09:43 convert.py
-rw-r--r-- 1  2.4K Aug  3 09:43 __init__.py
drwxr-xr-x 1   274 Aug  3 09:43 __pycache__
-rw-r--r-- 1     0 Aug  3 09:43 py.typed
drwxr-xr-x 1    14 Aug  3 09:43 static
-rw-r--r-- 1   12K Aug  3 09:43 testing.py
drwxr-xr-x 1     8 Aug  3 09:43 tests
-rw-r--r-- 1  3.6K Aug  3 09:43 tutorial.py
-rw-r--r-- 1  4.7K Aug  3 09:43 ufuncs.py
```

**Minimal Complete Verifiable Example**:

```bash
wget -o xarray-0.16.0.tar.gz https://github.com/pydata/xarray/archive/v0.16.0.tar.gz
tar xvfz xarray-0.16.0.tar.gz
cd xarray-0.16.0
# this is sadly required since the downloaded file does not contain *any* version information
# setuptools_scm reads PKG-INFO as a last resort when trying to determine the version.
echo 'Version: 0.16.0' > PKG-INFO
python3 setup.py install --prefix=<>
# or
pip3 install -vvv --no-cache-dir --no-deps --no-index --no-build-isolation --compile --prefix=<> .
```

**Anything else we need to know?**:
I think this is quite self-producing. It is just important that one does not do this on a git repo.

Do you need anything else from me?

**Comment by keewis** [comment]
I think this can be easily fixed by replacing `packages = xarray` with `packages = find:` in `setup.cfg`. Not sure if there's a reason why we don't do that already?

**Comment by max-sixty** [comment]
@zerothi would you be up for a PR to make that change?
