### ISSUE TITLE
Improve Dataset documentation

### ISSUE THREAD

**Issue by Illviljan** [pydata/xarray#4345]
**Is your feature request related to a problem? Please describe.**
As a new user I find it difficult to get a new dataset initialized because the necessary parameters are not shown in the docstring. 
I have to google "xarray dataset" to get to http://xarray.pydata.org/en/stable/generated/xarray.Dataset.html to figure it out.

In the figure below xarray.Dataset does not show the necessary parameters in the help pane:
![image](https://user-images.githubusercontent.com/14371165/90313058-aab66000-df09-11ea-9f3a-d2d3f2698b66.png)

Compare to pandas.DataFrame that includes it:
![image](https://user-images.githubusercontent.com/14371165/90313083-e94c1a80-df09-11ea-8013-a7ffe90ab4d8.png)

**Describe the solution you'd like**
Looking at https://github.com/pydata/xarray/blob/master/xarray/core/dataset.py#L428 the `xr.Dataset.__init__.__doc__` does contain the necessary parameters so the suggestion is to simply move or copy that information up one level to` xr.Dataset.__doc__`

For reference pandas does not use a docstring for the __init__ method:
https://github.com/pandas-dev/pandas/blob/v1.1.0/pandas/core/frame.py#L339-L9257

The pandas docs also includes a few simple copy/pasteable examples on how to initialize. So a xarray example would be:
```python
>>> import numpy as np
>>> import xarray as xr
>>> x = np.arange(4)
>>> y = 2*x
>>> ds = xr.Dataset({'y': (['x'], y)},
...                 coords={'x': x})
>>> print(ds)
<xarray.Dataset>
Dimensions:  (x: 4)
Coordinates:
  * x        (x) int32 0 1 2 3
Data variables:
    y        (x) int32 0 2 4 6
```
Or take some examples from http://xarray.pydata.org/en/stable/quick-overview.html#datasets or http://xarray.pydata.org/en/stable/data-structures.html#dataset although I found those  a little bit confusing as they were dependent on previous results or rather complex with many dimensions.

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.15.0
pandas: 1.0.3
numpy: 1.18.1
scipy: 1.4.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.14.0
distributed: 2.22.0
matplotlib: 3.1.3
cartopy: None
seaborn: 0.10.0
numbagg: None
setuptools: 49.2.1.post20200807
pip: 20.2.1
conda: 4.8.3
pytest: 6.0.1
IPython: 7.17.0
sphinx: 3.2.0
C:\ProgramData\Anaconda3\lib\site-packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "

</details>

**Comment by max-sixty** [comment]
Thanks for the feedback; I agree there's more to initializing a Dataset than a DataFrame, and we should make the docs as accessible as possible.

In this specific case, is this a Spyder issue only or more general? IIUC using the `__init__` or the class are both standard for the class docstring

**Comment by Illviljan** [comment]
Yeah, I've read the same thing that either `__init__` or the class can be used. I liked adding it in `__init__` too when I've developed classes because it's consistent with other functions and methods. But now that I'm on the **user side** I think the class docstring is the way to go. Pandas and scipy seems to be pretty consistent with this as well:
* Series - https://github.com/pandas-dev/pandas/blob/v1.1.0/pandas/core/series.py#L139-L4979
* Interpolate- https://github.com/scipy/scipy/blob/v1.5.2/scipy/interpolate/interpolate.py


The Spyder help pane simply reads `xr.Dataset.__doc__` and it would correctly read the `__init__` doc if I I typed out `xr.Dataset.__init__` too, but which users prefers to do that?

**Comment by max-sixty** [comment]
Any idea whether this is a Spyder issue only or more general?

**Comment by Illviljan** [comment]
My opinion is that it is a general issue but maybe that's because I prefer Spyder? Jupyterlab is the other IDE I know that has this functionality it seems to print class and init information. Are there any others?

Checking `pd.DataFrame()` in JupyterLab:
![image](https://user-images.githubusercontent.com/14371165/90343218-9c05a100-e00e-11ea-8ec2-fc6db19065f5.png)

Checking `xr.Dataset()` in JupyterLab:
![image](https://user-images.githubusercontent.com/14371165/90343240-d96a2e80-e00e-11ea-911b-49b1a2a80e9b.png)

**Comment by keewis** [comment]
`python -m pydoc xarray.Dataset` displays `__doc__` and then all methods / attributes / properties and their `__doc__`, so that's not a problem there. As @Illviljan pointed out, `ipython` / `jupyter` display the docstring of `Dataset.__init__` as a special `Init docstring` section.

So I guess this is a "bug" in spyder (and maybe also other IDEs?), but we could work around that using a decorator.

**Comment by Illviljan** [comment]
Creating a decorator for this sounds a bit too fancy compared to just moving the init docstring to the class docstring in my opinion. 

Isn't xarray following the numpy docstring guidelines? Reading up on the numpy guidelines they recommend that the constructor (__init__) should be documented at the class docstring. https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring

And after looking around some more the modules that prefers having init parameters at the class docstring are:
* numpy - https://github.com/numpy/numpy/blob/master/numpy/core/records.py#L98
* scipy  - https://github.com/scipy/scipy/blob/v1.5.2/scipy/interpolate/interpolate.py
* pandas - https://github.com/pandas-dev/pandas/blob/v1.1.0/pandas/core/frame.py#L339-L9257
* dask - https://github.com/dask/dask/blob/master/dask/blockwise.py#L135

**Comment by max-sixty** [comment]
Thanks @keewis , good spot.

That looks right @Illviljan , so unless there's other information, it looks like we should move it to the class.

Is there any reason to keep it on the `__init__`?

**Comment by max-sixty** [comment]
Maybe we keep it focused on one issue, but another oddity — JupyterLab seems to list the signature as `xr.Dataset(*args, **kwds), but the signature is explicit: https://github.com/pydata/xarray/blob/v0.16.0/xarray/core/dataset.py#L468-L475

**Comment by shoyer** [comment]
I don't think it's unusual to document constructor parameters on `__init__`. For example, that's the recommendation of the Google Python style-guide, followed by most Google Python projects (e.g., TensorFlow). So I think Spyder would be improved by documenting `__init__`, too.

That said, I don't have any principled reason for deviating from the NumPy docstring standards here. I also agree that the `Dataset` constructor would be improved by adding usage examples of how to create a Dataset.
