### ISSUE TITLE
Examples combining multiple files

### ISSUE THREAD

**Issue by slharris** [pydata/xarray#436]
Are you able to provide more examples of combining and working with multiple netcdf files. All of the examples appear to be working with the one netcdf file. 
I would like to create time series plots and spatial plots of anomalies of climate data for hundreds of netcdf files separated by month.  
I must admit I am not very experienced but I think xray may be a better option than how I have been processing netcdf files in the past. 
Thanks

**Comment by shoyer** [comment]
Have you tried `xray.open_mfdataset`? All of the examples should work the same with a dataset loaded with that function as from a single file.

In your case, something like the following should work:
```python
# load data
ds = xray.open_mfdataset('path/to/my/files/*.nc')

# calculate anomalies
clim = ds.groupby('time.month').mean('time')
anom = ds.groupby('time.month') - clim

# plot anomalies over time
# (in practice, would probably want to use .sel here to do
# labeled lookups)
anom.temperature.isel(x=0, y=0).to_pandas().plot()
# plot anomalies over space
plt.imshow(anom.temperature.isel(time=0).values)
```

Plotting is currently not so easy as it should be with xray (hence why you see me exporting everything to pandas), but that's something we plan to start work on very soon.

**Comment by j08lue** [comment]
That is actually an excellent demonstration of the power of `xray` for climate data analysis, @shoyer. 

Something like this (including the pandas bridge) should be included in the documentation somewhere, for example under [Why xray?](http://xray.readthedocs.org/en/stable/why-xray.html).

Just a thought...

**Comment by shoyer** [comment]
@j08lue good idea! Right now that page is mostly targeted at non-climate scientists, but it would be nice to include an example for climate scientists, too.

**Comment by max-sixty** [comment]
Closing as stale, please reopen if still relevant
