### ISSUE TITLE
Surprising deepcopy semantics with dtype='object'

### ISSUE THREAD

**Issue by darikg** [pydata/xarray#4362]
```python
from copy import deepcopy
import numpy as np
import xarray as xr

class Dummy: pass

a0 = np.array([Dummy()])
a1 = deepcopy(a0)
print(a0[0] is a1[0])  # False, as expected

x0 = xr.DataArray(a0, dims='dummy')
x1 = deepcopy(x0)
print(x0.values[0] is x1.values[0])  # unexpectedly True
```

I *think* this is a bug, and would be fixed with an extra deepcopy around [here](https://github.com/pydata/xarray/blob/43a2a4bdf3a492d89aae9f2c5b0867932ff51cef/xarray/core/variable.py#L942)

**Comment by shoyer** [comment]
I agree, marking this as a bug. We should use `deepcopy()` recursively on NumPy arrays.

**Comment by mathause** [comment]
@darikg are you interested to send in a PR?

**Comment by darikg** [comment]
Sure! I'll be back in a couple days when I get a chance
