### ISSUE TITLE
warnings from internal use of apply_ufunc

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#4385]
Another follow up from #4060: `quantile` now emits a `FutureWarning`:

**Minimal Complete Verifiable Example**:

```python
xr.DataArray([1, 2, 3]).quantile(q=0.5)
```

```
~/.conda/envs/ipcc_ar6/lib/python3.7/site-packages/xarray/core/variable.py:1866:
FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs``
parameter. It will be removed as direct parameter in a future version.
kwargs={"q": q, "axis": axis, "interpolation": interpolation},
```

We should probably check the warnings in the test suite - there may be others.

**Comment by kmuehlbauer** [comment]
@mathause Then these internal uses should be adapted to the new use of apply_ufunc, right? As I feel somehow committed to #4060 I could work on this.

**Comment by dcherian** [comment]
> Then these internal uses should be adapted to the new use of apply_ufunc, right?

:+1:

> I could work on this.

Only if you have time! No need to feel obligated :) but it should be relatively simple.

**Comment by kmuehlbauer** [comment]
@dcherian Thanks, I'll come up with a PR over the weekend. But this should not block others to take over if this becomes urgent.

**Comment by mathause** [comment]
No worry this is only on master and not in a released version.
