### ISSUE TITLE
Stack: avoid re-chunking (dask) and insert new coordinates arbitrarily

### ISSUE THREAD

**Issue by chrisroat** [pydata/xarray#4389]
The behavior of stack was not quite intuitive to me, and I'd like to understand if this was an explicit technical decision or if it can be changed.

First, with regard to chunking:
```
arr = xr.DataArray(da.zeros((2, 3, 4), dtype=np.int, chunks=(1 ,1, 1)), dims=['z', 'y' ,'x'])
stacked = arr.stack(v=('y', 'x'))
print(stacked)
--
xarray.DataArray 'zeros-6eb2edd0fca7ec97141e1310bd303988' (z: 2, v: 12)>
dask.array<reshape, shape=(2, 12), dtype=int64, chunksize=(1, 4), chunktype=numpy.ndarray>
Coordinates:
  * v        (v) MultiIndex
  - y        (v) int64 0 0 0 0 1 1 1 1 2 2 2 2
  - x        (v) int64 0 1 2 3 0 1 2 3 0 1 2 3
Dimensions without coordinates: z
```

Why did the number of chunks change in this case?  Couldn't the chunksize be (1,1)?

Next, why is it necessary to put the new dimension at the end?  It seems there are often more natural (perhaps just to my naive thought process) placements.  One example would be that same array above, but stacked on the first two dimensions.  I would want the new dimension to be the first dimension (again without the rechunking above).  To accomplish this, I do:

```
arr = xr.DataArray(da.zeros((2, 3, 4), dtype=np.int, chunks=(1 ,1, 1)), dims=['z', 'y' ,'x'])
stacked = arr.stack(v=('z', 'y')).transpose('v', ...).chunk({'v': 1})
print(stacked)
--
<xarray.DataArray 'zeros-6eb2edd0fca7ec97141e1310bd303988' (v: 6, x: 4)>
dask.array<rechunk-merge, shape=(6, 4), dtype=int64, chunksize=(1, 1), chunktype=numpy.ndarray>
Coordinates:
  * v        (v) MultiIndex
  - z        (v) int64 0 0 0 1 1 1
  - y        (v) int64 0 1 2 0 1 2
Dimensions without coordinates: x
```

The dask graph for this last bit insert a rechunk and two transposes, but my intent was not to have any of the underlying chunks change at all.  Here is 1 of 8 pieces of the graph (with optimization off -- optimization combines operations, but doesn't change the topology or the operations):

![out](https://user-images.githubusercontent.com/1053153/91649954-2518d100-ea2e-11ea-83ac-1e1f52d2e11b.png)

Is it technically feasible for stack to avoid rechunking, and for the user to determine where the new dimensions should go?

**Comment by dcherian** [comment]
dask seems to rechunk when reshaping

`dask.visualize(arr.data.reshape((6, 4)))`
![image](https://user-images.githubusercontent.com/2448579/91773442-4fa58e00-ebd6-11ea-8c55-6ed8d10fb586.png)


The core stack operation is here:
https://github.com/pydata/xarray/blob/2acd0fc6563c3ad57f16e6ee804d592969419938/xarray/core/variable.py#L1456-L1478

I think the dimension is at the end for coding convenience...

**Comment by chrisroat** [comment]
There has been some discussion on the dask chunking issue here:
https://github.com/dask/dask/issues/3650
https://github.com/dask/dask/issues/5544

Regarding the position of the inserted variable, it is not related to the chunking.  It seems possible to do this.  Would this be an acceptable change?  If so, the first problem is the signature, as multiple dimensions may be passed in.  :/

**Comment by dcherian** [comment]
Amazing. Thanks @phofl
