### ISSUE TITLE
Dimension attrs lost when creating new variable with that dimension

### ISSUE THREAD

**Issue by dnowacki-usgs** [pydata/xarray#4393]
**What happened**:
When creating a new variable based on an existing dimension, the attrs of the dimension are lost.

**What you expected to happen**:
The attrs should be preserved.

**Minimal Complete Verifiable Example**:

```python
import xarray as xr

ds = xr.Dataset()
ds['x'] = xr.DataArray(range(10), dims='x')
ds['y'] = xr.DataArray(range(len(ds['x'])), dims='x')
ds['x'].attrs['foo'] = 'bar'
print(ds['x']) # attrs of ds['x'] are preserved

print('\n****\n')

ds = xr.Dataset()
ds['x'] = xr.DataArray(range(10), dims='x')
ds['x'].attrs['foo'] = 'bar'
ds['y'] = xr.DataArray(range(len(ds['x'])), dims='x')
print(ds['x']) # attrs of ds['x'] are lost
```

Output of above code:
```
<xarray.DataArray 'x' (x: 10)>
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Coordinates:
  * x        (x) int64 0 1 2 3 4 5 6 7 8 9
Attributes:
    foo:      bar

****

<xarray.DataArray 'x' (x: 10)>
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Coordinates:
  * x        (x) int64 0 1 2 3 4 5 6 7 8 9
```

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
libhdf5: 1.10.5
libnetcdf: 4.7.4

xarray: 0.16.0
pandas: 1.0.3
numpy: 1.19.1
scipy: 1.3.1
netCDF4: 1.5.3
pydap: None
h5netcdf: 0.8.0
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.3
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.18.1
distributed: 2.25.0
matplotlib: 3.2.1
cartopy: 0.18.0
seaborn: 0.10.0
numbagg: None
pint: 0.15
setuptools: 49.6.0.post20200814
pip: 19.2.2
conda: 4.8.4
pytest: 5.4.1
IPython: 7.14.0
sphinx: None
None

</details>

**Comment by dcherian** [comment]
I think this is #2180; see https://github.com/pydata/xarray/issues/2180#issuecomment-391932929 . Basically the RHS is prioritized and the `x` variable gets overwritten with the version of `x` on the RHS. 

You can avoid this by going the Variable route instead of the DataArray route:`ds["y"] = ("x", range(len(ds.x)))` https://xarray.pydata.org/en/stable/data-structures.html#creating-a-dataset

**Comment by dnowacki-usgs** [comment]
Huh, I would not have expected that behavior. To my mind, it seems unwanted, but I don't totally follow the discussion in #2180. Thanks for the heads up.
