### ISSUE TITLE
Get Indices where values along an entire dim are NaN

### ISSUE THREAD

**Issue by aryamansriram** [pydata/xarray#4430]
I am trying to get the indices where the entier dimension as NaN values and use these indices to drop records in another xarray dataset. I tried to use `xr.Dataset.where()` but realized it only masked the dataset. I also tried `xr.Dataset.dropna()` but it only dropped the nan dimensions and did not give me the indices which it dropped. I can manually check for it but I am looking for ways to automate this process.

**Comment by max-sixty** [comment]
@aryamansriram please fill out the issue template, thanks in advance.

**Comment by dcherian** [comment]
This is quite late but I think the  solution  here is `A.where(B.notnull(), drop=True)`. Please reopen if you have more questions
