### ISSUE TITLE
support nd fancy indexing

### ISSUE THREAD

**Issue by hafez-ahmad** [pydata/xarray#4441]
I used indexing in the single dataset but when I tried to concatenate full dataset . NotImplementedError: Don't yet support nd fancy indexing

f2010_1=xr.open_mfdataset('C:/Users/hafez/personal/python_projects/sea_level_gridded/data/2010/*.nc',combine='by_coords',concat_dim='time')
ds = f2010_1.assign_coords(longitude=(((f2010_1.longitude + 180) % 360) - 180)).sortby('longitude')
min_lon = 75.0
min_lat = 2.0
max_lon = 100.0
max_lat = 22.0
mask_lon = (ds.longitude >= min_lon) & (ds.longitude<= max_lon)
mask_lat = (ds.latitude >= min_lat) & (ds.latitude<= max_lat)
cropped_ds = ds.where(mask_lon & mask_lat, drop=True)

error: 
NotImplementedError                       Traceback (most recent call last)
<ipython-input-9-a0698c6d77da> in <module>
      6 mask_lon = (ds.longitude >= min_lon) & (ds.longitude<= max_lon)
      7 mask_lat = (ds.latitude >= min_lat) & (ds.latitude<= max_lat)
----> 8 cropped_ds = ds.where(mask_lon & mask_lat, drop=True)
      9 cropped_ds.to_netcdf('C:/Users/hafez/personal/python_projects/sea_level_gridded/data/2010/2010_full.nc')

c:\users\hafez\miniconda3\lib\site-packages\xarray\core\common.py in where(self, cond, other, drop)
   1243             indexers = {k: np.unique(v) for k, v in nonzeros}
   1244 
-> 1245             self = self.isel(**indexers)
   1246             cond = cond.isel(**indexers)
   1247 

c:\users\hafez\miniconda3\lib\site-packages\xarray\core\dataset.py in isel(self, indexers, drop, missing_dims, **indexers_kwargs)
   1963             var_indexers = {k: v for k, v in indexers.items() if k in var_value.dims}
   1964             if var_indexers:
-> 1965                 var_value = var_value.isel(var_indexers)
   1966                 if drop and var_value.ndim == 0 and var_name in coord_names:
   1967                     coord_names.remove(var_name)

c:\users\hafez\miniconda3\lib\site-packages\xarray\core\variable.py in isel(self, indexers, missing_dims, **indexers_kwargs)
   1072 
   1073         key = tuple(indexers.get(dim, slice(None)) for dim in self.dims)
-> 1074         return self[key]
   1075 
   1076     def squeeze(self, dim=None):

c:\users\hafez\miniconda3\lib\site-packages\xarray\core\variable.py in __getitem__(self, key)
    713         """
    714         dims, indexer, new_order = self._broadcast_indexes(key)
--> 715         data = as_indexable(self._data)[indexer]
    716         if new_order:
    717             data = duck_array_ops.moveaxis(data, range(len(new_order)), new_order)

c:\users\hafez\miniconda3\lib\site-packages\xarray\core\indexing.py in __getitem__(self, key)
   1274     def __getitem__(self, key):
   1275         array, key = self._indexing_array_and_key(key)
-> 1276         return array[key]
   1277 
   1278     def __setitem__(self, key, value):

c:\users\hafez\miniconda3\lib\site-packages\dask\array\core.py in __getitem__(self, index)
   1583 
   1584         out = "getitem-" + tokenize(self, index2)
-> 1585         dsk, chunks = slice_array(out, self.name, self.chunks, index2, self.itemsize)
   1586 
   1587         graph = HighLevelGraph.from_collections(out, dsk, dependencies=[self])

c:\users\hafez\miniconda3\lib\site-packages\dask\array\slicing.py in slice_array(out_name, in_name, blockdims, index, itemsize)
    160 
    161     # Pass down to next function
--> 162     dsk_out, bd_out = slice_with_newaxes(out_name, in_name, blockdims, index, itemsize)
    163 
    164     bd_out = tuple(map(tuple, bd_out))

c:\users\hafez\miniconda3\lib\site-packages\dask\array\slicing.py in slice_with_newaxes(out_name, in_name, blockdims, index, itemsize)
    182 
    183     # Pass down and do work
--> 184     dsk, blockdims2 = slice_wrap_lists(out_name, in_name, blockdims, index2, itemsize)
    185 
    186     if where_none:

c:\users\hafez\miniconda3\lib\site-packages\dask\array\slicing.py in slice_wrap_lists(out_name, in_name, blockdims, index, itemsize)
    228     ]
    229     if len(where_list) > 1:
--> 230         raise NotImplementedError("Don't yet support nd fancy indexing")
    231     # Is the single list an empty list? In this case just treat it as a zero
    232     # length slice

NotImplementedError: Don't yet support nd fancy indexing

**Comment by dcherian** [comment]
Well this is a dask issue.

But you shouldn't use `where` to do this operation.

`ds.sel(longitude=slice(lon_min, lon_max), latitude=slice(lat_min, lat_max))` will do what you want and is a lot more efficient; see https://xarray.pydata.org/en/stable/indexing.html#indexing-with-dimension-names

Please reopen if you have more questions.
