### ISSUE TITLE
CSS_STYLE attribute breaking packages

### ISSUE THREAD

**Issue by Horndev** [pydata/xarray#4447]
The latest version has breaking changes for other packages.  I would not expect this from a minor version increment.

For arviz:
```
  File "/usr/local/lib/python3.6/site-packages/arviz/utils.py", line 670, in <module>
    class HtmlTemplate:
  File "/usr/local/lib/python3.6/site-packages/arviz/utils.py", line 696, in HtmlTemplate
    css_template = f"<style> {xr.core.formatting_html.CSS_STYLE}{specific_style} </style>"
AttributeError: module 'xarray.core.formatting_html' has no attribute 'CSS_STYLE'
```

**Comment by shoyer** [comment]
xref https://github.com/pydata/xarray/pull/4297#issuecomment-696135863

`xarray.core` is not part of our public API. I can see why this could be confusing -- the modules does not use Python's standard underscore prefix -- but this is a fairly well established convention in the scientific Python ecosystem, e.g., you rely upon imports from `pandas.core` or `numpy.core` either.

**Comment by nathdip** [comment]
What is the solution to this issue again? Should I downgrade either arviz or xarray?

**Comment by max-sixty** [comment]
There are a few options over at arviz-devs/arviz#1387 — either downgrade xarray or upgrade arviz to master

**Comment by nathdip** [comment]
Thanks for the help, that worked!
