### ISSUE TITLE
overloaded functions have several signatures in the docs

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#4487]
See

![image](https://user-images.githubusercontent.com/10194086/95106783-3f368500-0739-11eb-80dc-a9572ef98e1e.png)

(http://xarray.pydata.org/en/latest/generated/xarray.concat.html)

Can this be fixed? Or do we actually want to show both?

**Comment by keewis** [comment]
Good catch, @mathause.

I don't think we should show type hints at all (they're not visible in the API pages without `@overload`), that's what the parameter documentation is for. To solve this, I'd look for a configuration setting for `autosummary` / `autodoc` (I think the latter generates the signature) or try to figure out if that's a bug / missing feature in `autodoc`.

**Comment by mathause** [comment]
maybe: https://www.sphinx-doc.org/en/2.0/usage/extensions/autodoc.html#confval-autodoc_typehints can check tomorrow

**Comment by keewis** [comment]
that's already set: https://github.com/pydata/xarray/blob/45aab423b61c99278dd9b4d8a21915647afae623/doc/conf.py#L112 so I guess this is a missing feature for `autodoc`. sphinx-doc/sphinx#7785, maybe?

**Comment by mathause** [comment]
Yes, does sound like the issue. I guess we'll have to wait for upstream...

**Comment by keewis** [comment]
this is fixed in `sphinx=3.3.0`, so updating the pinned version in `doc.yml` should suffice
