### ISSUE TITLE
test_dataarray.py not run in py38-all-but-dask

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#4509]
The `DataArray` tests are skipped in `py38-all-but-dask` - I have no idea why...

See

https://dev.azure.com/xarray/xarray/_build/results?buildId=4028&view=logs&j=15c5a299-0936-5372-ef76-f6800a28dcef&t=b8653be4-abae-5992-d733-6af037900ab6&l=108

`test_dataarray.py` should be just before `test_dataset.py`

**Comment by mathause** [comment]
Ok so we do:

https://github.com/pydata/xarray/blob/db4f03e467d13229512f8f7924dc142db1b9486b/xarray/tests/test_dask.py#L32

and then 

https://github.com/pydata/xarray/blob/db4f03e467d13229512f8f7924dc142db1b9486b/xarray/tests/test_dataarray.py#L45

this also skips all tests in `test_dataarray.py` if dask is not installed...

**Comment by keewis** [comment]
hmm... maybe we should move `raise_if_dask_computes` to `xarray/tests/__init__.py`?
