### ISSUE TITLE
[Proposal] Migrate general discussions from the xarray gitter room to GitHub Discussions

### ISSUE THREAD

**Issue by andersy005** [pydata/xarray#4549]
Currently, xarray has a room on Gitter: https://gitter.im/pydata/xarray. This room works fine for discussions outside of the codebase. However, Gitter has a few disadvantages:

- The contents are not indexed by search engines
- Searching through existing discussions is almost impossible
- Linking to prior conversations in the room is also complicated

A few months ago, GitHub announced [**GitHub discussions**](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/) which is meant to serve as a forum for discussions outside of the codebase. I am of the opinion that GitHub discussions is a better alternative to Gitter. I am wondering if xarray folks would be interested in enabling GitHub discussion on this repo, and migrating general discussions from Gitter to GitHub discussions? 

GitHub Discussions is still in beta, but projects can request early access [here](https://github.community/t/can-one-apply-for-github-discussions-beta/121120/27)

Here is a list of a few projects with beta access:

- https://github.com/vercel/vercel/discussions
- https://github.com/KaTeX/KaTeX/discussions
- https://github.com/vercel/next.js/discussions

**Comment by max-sixty** [comment]
I ... didn't know that there was an xarray Gitter. Currently we direct user questions to SO, which has had middling success.

I just applied for the Discussions beta!

**Comment by shoyer** [comment]
I think Github could be a nice way to consolidate discussions. StackOverflow is a little harder to keep track of, as a separate website. Also SO tends to encourage "complete" answers, which I don't always have time to give.

We used to link to Gitter from the xarray project docs, but stopped doing that after it seemed like maintainers weren't using it -- but maybe that's changed?

**Comment by andersy005** [comment]
Now that https://github.com/pydata/xarray/discussions is live, should we close this issue?

**Comment by max-sixty** [comment]
I'll leave this open for a week or so, so we can evaluate whether we suggest this in favor of SO?

**Comment by keewis** [comment]
since #4578 we're pointing to discussions instead of SO in our issue template chooser, so I'm closing this.
