### ISSUE TITLE
failing upstream-dev polyfit warning test

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#4565]
In `xarray/tests/test_dataset.py::TestDataset::test_polyfit_warnings`, the second call to `polyfit`:
```python
ds.var1.polyfit("dim2", 10, full=True)
```

emits a warning with the current `upstream-dev` `pandas`:
```
xarray/tests/test_dataset.py::TestDataset::test_polyfit_warnings
  .../xarray/core/alignment.py:307: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
    index = joiner(matching_indexes)
```

since the test makes sure only the first call emits a warning (a `np.RankWarning`), the test fails.

**Comment by mathause** [comment]
Our alignment is based on this. So this may have quite some implications. I am surprised there are not more warnings (by number) in the test suite.
