### ISSUE TITLE
drop keyword in ds.rolling(time=7, drop=True).mean()?

### ISSUE THREAD

**Issue by ahuang11** [pydata/xarray#4588]
Should rolling have a drop keyword, similar to squeeze(drop=True)?
```
import xarray as xr
air = xr.tutorial.open_dataset('air_temperature')
air = air.rolling(time=7, drop=True).mean()
```

Equivalent:
```
import xarray as xr
air = xr.tutorial.open_dataset('air_temperature')
air = air.rolling(time=7).mean()
air = air.isel(time=slice(6, None))
```

Actual implementation will require considering min_period / center=True too

**Comment by mathause** [comment]
This is not something I would expect or miss so knowing your use-case would be helpful. Just as a word of caution, the implementation of `rolling` is a bit convoluted, so this may take a bit of effort.

**Comment by dcherian** [comment]
Do you want to avoid the padding?

**Comment by ahuang11** [comment]
Yes I want to drop the padding (remove the nans from the beginning)

**Comment by dcherian** [comment]
Thanks. Closing as duplicate of #2007. I have a solution in progress.
