### ISSUE TITLE
failing nightly CI

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#4603]
It seems the scheduled CI [failed](https://github.com/pydata/xarray/actions/runs/377958693) because no artifacts were uploaded (i.e. the CI passed). Is it possible to skip the `report` job if the `upstream-dev` job passed, or to at least skip all following jobs after we found out that there are no artifacts to download? If not or if that turns out to be too complex we can just ignore the failure.

cc @andersy005

**Comment by andersy005** [comment]
@keewis, when you get a chance, please take a look at #4604
