### ISSUE TITLE
CF compliant variables.

### ISSUE THREAD

**Issue by hetland** [pydata/xarray#461]
Create a new container in variables for CF convention variables. E.g.,

```
ds.salt.cf.x
ds.salt.cf.lon  # (maybe also?)
```

which would pass through ds.salt.x_rho (the x coordinate), or ds.salt.lon_rho.

**Comment by dcherian** [comment]
Looks like metpy has already done this: https://github.com/Unidata/MetPy/blob/3e8341bcd4c8682f8246aaa499f8b5abaab7dceb/metpy/xarray.py#L148

ref: https://stackoverflow.com/questions/53469510/how-to-identify-time-lon-and-lat-coordinates-in-xarray

Shall we ask them to upstream that?

**Comment by shoyer** [comment]
I am happy to keep this in a separate package, but it would be great to reference this prominently in our docs somewhere.
