### ISSUE TITLE
Create a way to calculate computed coordinates

### ISSUE THREAD

**Issue by hetland** [pydata/xarray#462]
Create computed coordinates in a lazy way, given a user defined equation for defining these coordinates.

E.g., 

```
my_depths(params):
    # do the calculation
   return depths
```

Then, link ds.salt.z to my_depths, such that 

```
ds.salt.z
```

returns the depths, calculated on request. Or better, an object that returns values only upon indexing.

See, e.g., 
The equations:
https://github.com/hetland/octant/blob/master/octant/depths.py

One way to do the lazy calculations just in python
https://github.com/hetland/octant/blob/68f51005480c8cb9f83098b0f751b4e8086c11b5/octant/roms.py#L244

**Comment by ocefpaf** [comment]
Just for reference, in case some tries to implement this in xray,  iris has all but one (`ocean_double_sigma_coordinate`) of the ocean dimensionless vertical coordinates.

Code: https://github.com/SciTools/iris/blob/master/lib/iris/aux_factory.py#L772-L1786

CF-conventions: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/cf-conventions.html#dimensionless-v-coord
