### ISSUE TITLE
Link concat info to concat doc string 

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#4620]
Could link http://xarray.pydata.org/en/stable/combining.html#concatenate or add the example to the concat doc string: http://xarray.pydata.org/en/stable/generated/xarray.concat.html

**Comment by keewis** [comment]
thanks for the suggestion, @raybellwaves. 

Linking to the narrative documentation is hard to do because it would either be easily out-of-date or useless when using `python -m pydoc`.

However, we would definitely accept a PR adding to the examples.
