### ISSUE TITLE
Release 0.16.2?

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#4624]
Looking at our [what's new](http://xarray.pydata.org/en/latest/whats-new.html#v0-16-2-unreleased), we have quite a few important new features, as well as significant bug fixes.

I propose we move towards releasing ~0.17.0~ 0.16.2 asap. (I have selfish motives for this, as I want to use the new features in production.) 

We can use this issue to track any PRs or issues we want to resolve before the next release. I personally am not aware of any major blockers, but other devs should feel free to edit this list.

- [ ] #4461 - requires decisions
- [x] #4618 
- [x] #4621 

cc @pydata/xarray

**Comment by dcherian** [comment]
:+1: Doing this now. We decided on `0.16.2` on the biweekly call: https://hackmd.io/Vv6g2ABzTPKbe2MWBQqS1w?view

**Comment by keewis** [comment]
there are a few PRs we might want to include in `0.16.2`: #4618 and #4621. If you wait for a bit I can finish up #4621.

**Comment by dcherian** [comment]
>  If you wait for a bit I can finish up #4621.

OK I'll wait.

**Comment by dcherian** [comment]
Tagged and uploaded to PyPI. RTD is building. 

The announcements are left. Let's do that after the conda-forge PR is merged?

**Comment by dcherian** [comment]
Announcements are done!

**Comment by max-sixty** [comment]
Thanks a lot @dcherian !
