### ISSUE TITLE
.sel(...., method='nearest') fails for large requests. 

### ISSUE THREAD

**Issue by EricKeenan** [pydata/xarray#4630]
A common usage of `xarray` is to retrieve climate model data from the grid cells closest to a weather station. That might look like this

```
import xarray as xr
import numpy as np

ds = xr.tutorial.open_dataset("air_temperature")

# Define taget latitude and longitude
tgt_lat = np.linspace(0, 100, num=10)
tgt_lon = np.linspace(0, 100, num=10)

# Retrieve data at target latitude and longitude
tgt_data = ds['air'].sel(lon=tgt_lon, lat=tgt_lat, method='nearest')
```

My problem is that I am trying subset `ds` to 10 points in space (which is the length of tgt_lat and tgt_lon), but in fact `xarray` retrieves 100 points (10 latitude by 10 longitude). I can get around this by calling `tgt_data = tgt_data.values.diagonal()`. But this results in a non-xarray object. Furthermore, if instead of querying for 10 points in space, I query for 10,000, I run out of memory because `xarray` retrieves 100,000,000 points in space (10,000^2). 

Is there a way to only retrieve the diagonal elements? If not, is this something that should be added?

**Comment by dcherian** [comment]
You should be able to do this with "vectorized indexing": https://xarray.pydata.org/en/stable/indexing.html#vectorized-indexing

**Comment by EricKeenan** [comment]
@dcherian Thanks for pointing me in the right direction. I'm trying to implement this with vectorized indexing, but it seems that my queries need to exactly match the xarray object lat/lon, which is why I tried  `method='nearest'`. Am I missing something?

**Comment by dcherian** [comment]
TO use "vectorized indexing", `tgt_lat` and `tgt_lon` need to be `DataArrays` with a common dimension name that is not a dimenion in `ds`

``` python
import xarray as xr
import numpy as np

ds = xr.tutorial.open_dataset("air_temperature")

# Define taget latitude and longitude
tgt_lat = xr.DataArray(np.linspace(0, 100, num=10), dims="points") # <---
tgt_lon = xr.DataArray(np.linspace(0, 100, num=10), dims="points") # <---

# Retrieve data at target latitude and longitude
tgt_data = ds['air'].sel(lon=tgt_lon, lat=tgt_lat, method='nearest')
tgt_data
```

![image](https://user-images.githubusercontent.com/2448579/100784918-265eee80-33cd-11eb-8c28-fbffdcdffc70.png)

**Comment by EricKeenan** [comment]
👏 👍 I didn't realize I needed to do that. Thanks for letting me know. Problem solved - marking this as closed.

**Comment by keewis** [comment]
this trick is not mentioned in the narrative documentation (or rather: I can't find it), and the docstrings of `isel` and `sel` don't contain any examples at all.

Since I believe it should be documented somewhere I'm reopening this to make sure we don't forget. Also, we would definitely welcome a PR adding this, if you're up for it.

**Comment by EricKeenan** [comment]
I'd be happy to give this a shot. But I'm not sure where to start... Can you point me to an example PR that has done something similar?

**Comment by keewis** [comment]
sure. #4621 added examples for `interp` / `interpolate_na`. For the narrative documentation I don't have a example PR but I think it's fine to just extend the `Vectorized indexing` section (thoughts, @dcherian?).

**Comment by EricKeenan** [comment]
Thanks for sharing! I'll give this a first shot before the end of the year.
