### ISSUE TITLE
Unexpected error when using `weighted`

### ISSUE THREAD

**Issue by jbusecke** [pydata/xarray#4635]
**What happened**:
I just updated to the newest upstream master of xarray to branch of a pull request for #4625 and noticed a strange error in my regular workflow. 

I am working with a dataset `ds_transformed` like this: 

![image](https://user-images.githubusercontent.com/14314623/100770013-c6674880-33ca-11eb-88b4-0b117e8291c8.png)

and when I try to apply a weighted mean with 
```python
transformed_ds.o2.weighted(transformed_ds.dz_t).mean('time')
```

I get the following error, which I do not understand:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-101-b08fde69b74b> in <module>
----> 1 test = transformed_ds.o2.weighted(transformed_ds.dz_t).mean('time')

~/code/xarray/xarray/core/common.py in weighted(self, weights)
    788         """
    789 
--> 790         return self._weighted_cls(self, weights)
    791 
    792     def rolling(

~/code/xarray/xarray/core/weighted.py in __init__(self, obj, weights)
    121             _weight_check(weights.data)
    122 
--> 123         self.obj = obj
    124         self.weights = weights
    125 

TypeError: descriptor 'obj' for 'Weighted' objects doesn't apply to a 'DataArrayWeighted' object
```

Using the synthetic example from #4625 this does not show up. I am wondering if anybody has an idea what could be wrong with my dataset that would cause this error?

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.2.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.16.3.dev2+ga41edc7.d20201201
pandas: 1.1.3
numpy: 1.19.2
scipy: 1.5.2
netCDF4: 1.5.4
pydap: None
h5netcdf: 0.8.1
h5py: 2.10.0
Nio: None
zarr: 2.4.0
cftime: 1.2.1
nc_time_axis: 1.2.0
PseudoNetCDF: None
rasterio: 1.1.3
cfgrib: None
iris: None
bottleneck: None
dask: 2.30.0
distributed: 2.30.0
matplotlib: 3.3.2
cartopy: 0.18.0
seaborn: None
numbagg: None
pint: 0.16.1
setuptools: 49.6.0.post20201009
pip: 20.2.4
conda: None
pytest: 6.1.2
IPython: 7.18.1
sphinx: None

</details>

**Comment by jbusecke** [comment]
Just confirmed that this does not occur when I use v0.16.1.

**Comment by dcherian** [comment]
Do you have ipython autoreload enabled? It usually cannot handle realtime changes to classes...

**Comment by jbusecke** [comment]
That was it. Sorry for the false alarm! Closing this.
