### ISSUE TITLE
to_zarr() produces error when trying to use keyword 'region'

### ISSUE THREAD

**Issue by mloeffelbein** [pydata/xarray#4636]
When executing the code from the v0.16.1 [documentation](https://xray--4035.org.readthedocs.build/en/v0.16.1/io.html#appending-to-existing-zarr-stores) ds.isel(x=slice(0, 10)).to_zarr(path, region={"x": slice(0, 10)}) an error was produced:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: to_zarr() got an unexpected keyword argument 'region'

 Code copied from v0.16.1 [documentation](https://xray--4035.org.readthedocs.build/en/v0.16.1/io.html#appending-to-existing-zarr-stores).

```python
 
import numpy as np
import xarray as xr
import dask.array

dummies = dask.array.zeros(30, chunks=10)
ds = xr.Dataset({"foo": ("x", dummies)})
path = "path/to/directory.zarr"
ds.to_zarr(path, compute=False, consolidated=True)

ds = xr.Dataset({"foo": ("x", np.arange(30))})
ds.isel(x=slice(0, 10)).to_zarr(path, region={"x": slice(0, 10)})
```

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

>>> xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-53-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.4

xarray: 0.16.1
pandas: 1.1.3
numpy: 1.19.2
scipy: 1.5.2
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: None
Nio: 1.5.5
zarr: 2.5.0
cftime: 1.3.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.0
cfgrib: 0.9.8.4
iris: None
bottleneck: 1.3.2
dask: 2.30.0
distributed: 2.30.1
matplotlib: 3.3.2
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 50.3.1.post20201107
pip: 20.2.4
conda: None
pytest: None
IPython: 5.8.0
sphinx: None

</details>

**Comment by keewis** [comment]
that's not actually the documentation of `v0.16.1` but a PR documentation (which should have been removed once #4035 was merged). The `region` keyword argument is new in `v0.16.2`, so you need to upgrade `xarray` to be able to use it.

**Comment by mloeffelbein** [comment]
Thank you.
