### ISSUE TITLE
increase the visibility of the upstream-dev PR CI

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#4670]
We currently have two upstream-dev PR CI: the old pipelines CI and the new github actions CI added together with the scheduled upstream-dev ("nightly") CI. Since we don't need both I think we should disable one of these, presumably the old pipelines CI. 

There's an issue with the CI result, though: since github doesn't have a [icon for "passed with issues"](https://github.com/actions/toolkit/issues/399), we have to choose between "passed" or "failed" as the CI result (neither of which is optimal).

The advantage of using "failed" is that a failure is easily visible, but often the total CI result on PRs is set to "failed" because we didn't get around to fixing bugs introduced by recent changes to dependencies (which is confusing for contributors).

In #4584 I switched the pipelines upstream-dev CI to "allowed failure" so we get a warning instead of a failure. However, github doesn't print the number of warnings in the summary line, which means that if the icon is green nobody checks the status and upstream-dev CI failures are easily missed.

Our new scheduled nightly CI improves the situation quite a bit since we automatically get a issue containing the failures, but that means we aren't able to catch these failures before actually merging. As pointed out in https://github.com/pydata/xarray/issues/4574#issuecomment-725795622 that might be acceptable, though.

If we still want to fix this, we could have the PR CI automatically add a comment to the PR, which would contain a summary of the failures but also state that these failures can be ignored as long as they get the approval of a maintainer. This would increase the noise on PRs, though.

**Comment by shoyer** [comment]
> Our new scheduled nightly CI improves the situation quite a bit since we automatically get a issue containing the failures, but that means we aren't able to catch these failures before actually merging. As pointed out in [#4574 (comment)](https://github.com/pydata/xarray/issues/4574#issuecomment-725795622) that might be acceptable, though.

I agree, I think is probably an acceptable compromise.

Most bugs with upstream-dev occur with _existing_ code in xarray, not new code introduced by a PR.

**Comment by keewis** [comment]
if we all agree on that, I've got two questions left:
- should we keep the pipelines or github actions PR CI (or neither)?
- should any of these be marked as "allowed failure"?

**Comment by keewis** [comment]
now that we fully switched to github and have a PR upstream-dev CI which is skipped unless explicitly requested, the only remaining issue here is that `py38-flaky` reports its errors . This does not seem to
