### ISSUE TITLE
windows test timeout

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#4671]
The windows tests seem to regularly time out after 60 min, which is annoying. All other tests seem to run about twice as fast... There is some stuff we can try (which may or may not help):

- [ ] switch to the newest windows image
- [ ] use mamba to resolve dependencies
- [ ] use matplotlib-base
- [ ] find the slowest tests using `py.test xarray/tests/ --durations=100`
- [ ] de-parametrize tests with a slow setup (if possible)
- [ ] reduce the number of xfails
- [ ] other ideas?

**Comment by kmuehlbauer** [comment]
@mathause You might be able to squeeze things a bit more in the conda env setup using `micromamba`.

**Comment by mathause** [comment]
> You might be able to squeeze things a bit more in the conda env setup using `micromamba`.

Thanks, happy to try. Do you use that somewhere? So I copy the code. However, miniconda is already installed on azure, so I wonder how much it helps.

**Comment by kmuehlbauer** [comment]
It might not be that much on windows, but it still can cut off several minutes, depending on the download size and speed.

I have it running on azure here:
https://github.com/wradlib/wradlib/blob/master/ci/azure/install.yml
It's still needs polishing but works quite well.
