### ISSUE TITLE
.min() crashes when xarray is installed using pip

### ISSUE THREAD

**Issue by felipem775** [pydata/xarray#4674]
**What happened**:
When I try use `.min()` after do a `sel(time=slice(start,end))`, I obtain an error from server.

**What you expected to happen**:
`array(99962.305, dtype=float32)`

**Minimal Complete Verifiable Example**:

```python
from datetime import datetime
import numpy as np
import xarray

datetime_start = datetime(2020,11,26,0,0,0)
datetime_end = datetime(2020,11,28,0,0,0)
np_start = np.datetime64(datetime_start)
np_end = np.datetime64(datetime_end)
[requirements.txt](https://github.com/pydata/xarray/files/5677894/requirements.txt)

opendap_url = 'https://datahub:datahubpassword@ihthredds.ihcantabria.com/thredds/dodsC/datahubTests/Cantabrico_2020112406.nc'
ds = xarray.open_dataset(opendap_url)

ds = ds.sel(time=slice(np_start,np_end))

var_name = "Pressure_surface"
pressure = ds[var_name]

min_value = pressure.min()
print(min_value)

```

**Anything else we need to know?**:
If you use a conda enviroment, it works.
If you remove `ds = ds.sel(time=slice(np_start,np_end))` using a pip enviroment, it works.

**Environment**:
- Linux mint 20
- python 3.8
- xarray[complete]

**Files**:
* [requirements.txt](https://github.com/pydata/xarray/files/5677911/requirements.txt)
* [script.txt](https://github.com/pydata/xarray/files/5677904/script.txt)
* [error.txt](https://github.com/pydata/xarray/files/5677957/error.txt)

**Reproduce**
- Create a new virtualenv and activate it.
- pip install -r [requirements.txt](https://github.com/pydata/xarray/files/5677911/requirements.txt).
- copy [script.txt](https://github.com/pydata/xarray/files/5677904/script.txt) as script.py and run it using `python script.py`
- get errors.
- remove line 13
- run it
- get array

**Comment by max-sixty** [comment]
Hi @felipem775 — this is likely environment related. Please could you include all the details from the issue template, and include a fully reproducible example?

**Comment by felipem775** [comment]
Hi @max-sixty I updated the info. I attached requirements, script and error. If you need something more tell me. Thanks.

**Comment by max-sixty** [comment]
In the issue template there are instructions on using `xr.show_versions`. Please review the link there on how to create an example — it should rely on self-contained data, not using remote data. I get a different error, maybe because `datahubpassword` doesn't work.

```python
~/Library/Caches/pypoetry/virtualenvs/-cyukv0jK-py3.8/lib/python3.8/site-packages/xarray/backends/file_manager.py in _acquire_with_cache_info(self, needs_lock)
    203                     kwargs = kwargs.copy()
    204                     kwargs["mode"] = self._mode
--> 205                 file = self._opener(*self._args, **kwargs)
    206                 if self._mode == "w":
    207                     # ensure file doesn't get overriden when opened again

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -68] NetCDF: I/O failure: b'https://datahub:datahubpassword@ihthredds.ihcantabria.com/thredds/dodsC/datahubTests/Cantabrico_2020112406.nc'
```

**Comment by felipem775** [comment]
Hi @max-sixty 
I'm doing more test and I think the problem is `xarray` lost session when it tries obtain data for `.min()`.
I am going to close this incident and open a new one with the problem I am detecting.

**Comment by felipem775** [comment]
Using `netCDF4==1.5.5.1` doesn't crash
