### ISSUE TITLE
codecov coverage dropped

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#4693]
Looks like something went wrong when #4408 was merged (https://github.com/pydata/xarray/commit/23dc2fc9f2785c348ff821bf2da61dfa2206d283)

![image](https://user-images.githubusercontent.com/2448579/102135305-04298f80-3e15-11eb-9f6f-e44238a414ac.png)

**Comment by mathause** [comment]
Possibly https://pytest-cov.readthedocs.io/en/latest/config.html#caveats

**Comment by mathause** [comment]
`tmpdir.chdir()` is the issue. I think it then gets the paths wrong... But I don't know yet what to do about it.
