### ISSUE TITLE
deprecate open_rasterio in favour of a rioxarray entrypoint?

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#4697]
Now that our backends work is well underway, it seems like a good time to discuss deprecating the `open_rasterio` function and outsourcing it to `rioxarray` (which would then implement support for the new entrypoint).

From @jhamman's [comment](https://github.com/pydata/xarray/issues/4142#issuecomment-642413509)

> There's also the question of where the rasterio backend should live once #1970 is implemented. I think we can make a pretty strong argument that it should move out of xarray and into a 3rd party package. Perhaps rasterio itself, or, more likely something like rio-xarray (cc @snowman2). See #3166 for a demo of how this may work.

> As you can see, there are a few big questions up in the air right now. Work on #1970 will begin this summer so now is a great time to game out the various options for the rasterio backend.

I am in favour of doing this. I see no reason why there should be two slightly divergent versions of the same function, and (anecdotally) the `rioxarray` version seems to be more full-featured and regularly improved.

@pydata/xarray What do you think?

If we agree to do this (and rioxarray agrees), we could put this as a "deliverable" in our NASA proposal. This work would be totally relevant to that call.

Related: #4142

cc @snowman2 @scottyhq @JessicaS11 @WeatherGod

**Comment by snowman2** [comment]
Looks like entrypoint support was added in #4577. What is the timeline for the next release?

> and rioxarray agrees

Is `rioxarray` agreeing to allow the addition of entrypoint support? If so, :+1:

**Comment by keewis** [comment]
> What is the timeline for the next release?

There's no timeline, yet. Since we just released `0.16.2`, maybe in about 2-3 months?

**Comment by snowman2** [comment]
@alexamici added the entrypoint here; https://github.com/corteva/rioxarray/pull/281. It seems xarray 0.18 is required for it to work. Any timeline for the `0.18` release?

**Comment by alexamici** [comment]
@max-sixty I'm +1 on deprecating *xarray* flavour of `open_rasterio`.

BTW, I would rather prefer the next release to be `0.18.0` as the backend changes are both large and user visible (`open_dataset` now accept `**kwargs` that are added to `**backend_kwargs`).

**Comment by max-sixty** [comment]
OK great @alexamici

**Comment by keewis** [comment]
if we deprecate `xr.open_rasterio` we should also do the same for `xr.tutorial.open_rasterio` and get `xr.tutorial.open_dataset("RGB.byte")` to work.

**Comment by keewis** [comment]
Since it comes up pretty often: should we go through with deprecating `open_rasterio` and the builtin `rasterio` backend?
