### ISSUE TITLE
add scatter plot method to dataset

### ISSUE THREAD

**Issue by clarkfitzg** [pydata/xarray#470]
Follow up on original plotting

**Comment by barronh** [comment]
+1

Especially useful when using unstructured spatial datasets like observation stations.

```
import xarray as xr
nstations = 9
data = np.random.random(size = nstations)
longitude = np.random.random(size = nstations) + -90
latitude = np.random.random(size = nstations) + 40
da = xr.DataArray(np.random.random(nstations ), dims = ['station'], coords = dict(longitude = ('station', longitude), latitude = ('station', latitude))
da.scatter(x = 'longitude', y = 'latitude')
```

**Comment by darothen** [comment]
This certainly could be useful, but since this is essentially plotting a vector of data, why not just drop into pandas?

```
df = da.to_dataframe()
# Could reset coordinates if you really wanted
# df = df.reset_index()
df.plot.scatter('longitude', 'latitude', c=da.name)
```

Patching in this rough functionality into the plotting module should be really straightforward, maybe @jhamman has some tips?

**Comment by aidanheerdegen** [comment]
In the absence of a dedicated method, it is possible to obtain a scatterplot with the keyword options to `plot.line()`:
```
rho_so_remap.plot.line(marker='o',linewidth=0.)
```
![unknown](https://user-images.githubusercontent.com/6063709/48986689-415a5080-f16c-11e8-8b98-c3a5b7d16ea0.png)

**Comment by zxdawn** [comment]
@aidanheerdegen Thanks for the code. I suppose it's better to mention this method for DataArray in User Guide. @dcherian 
 Should I create a PR for example like this?

```
air = xr.tutorial.open_dataset("air_temperature")['air']

air.isel(lon=10, lat=[19, 21, 22]).plot.line(x="time", marker='o',linewidth=0.,markersize=1)
```

![image](https://user-images.githubusercontent.com/30388627/152692498-1c142c28-fb0e-4935-8bbf-6dcffa6070ab.png)
