### ISSUE TITLE
OutOfBoundsDatetime error when opening tutorial dataset

### ISSUE THREAD

**Issue by aashish-khub** [pydata/xarray#4712]
Hi 

I tried importing data from the tutorial [here](http://xarray.pydata.org/en/stable/examples/monthly-means.html), specifically in this line:

![image](https://user-images.githubusercontent.com/40303727/102676980-189bbe00-416e-11eb-88fc-0f90c9023c25.png)

But that appears to cause an `OutOfBoundsDatetime: Cannot decode times from a non-standard calendar, 'noleap', using pandas.` error originating in `opt/anaconda3/lib/python3.8/site-packages/xarray/coding/times.py`. I tried troubleshooting but couldn't find much, and I'm not sure if this originates as an issue on my end or in the `xarray/coding/times.py` file, as the output suggests:

![image](https://user-images.githubusercontent.com/40303727/102677077-a37cb880-416e-11eb-8a8e-8ed56e295493.png)

**Comment by mathause** [comment]
I think you are missing the cftime library. The error message could mention this: `"Please install the cftime library, don't set use_cftime to False or use ``decode_cf=False``"` There is a `ModuleNotFoundError` just below - what does it say?

**Comment by mathause** [comment]
Ok it actually tells you at the very end:

```python-traceback
ValueError: unable to decode time units 'days since 0001-01-01' with "calendar 'noleap'".
Try opening your dataset with decode_times=False or installing cftime if it is not installed.
```
so I close this.
