### ISSUE TITLE
mamba on RTD

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#4713]
RTD now supports using mamba instead of conda using a feature flag : https://docs.readthedocs.io/en/latest/guides/feature-flags.html#available-flags

Maybe it's worth seeing if this will reduce docs build time on CI?

**Comment by mathause** [comment]
We could also try to set `CONDA_APPEND_CORE_REQUIREMENTS` - that may also make it faster.

**Comment by keewis** [comment]
> We could also try to set `CONDA_APPEND_CORE_REQUIREMENTS`

it's already set, that's the reason why we can pin `sphinx`.

If we agree this is worth trying, I can ask support to set `CONDA_USES_MAMBA` for us.

**Comment by keewis** [comment]
the mail is out, let's see if this helps

**Comment by mathause** [comment]
Ah I thought we have to pass this via the config file.

> the mail is out, let's see if this helps

thanks!

**Comment by keewis** [comment]
the flag is activated, which reduces the build time by about 6 minutes. They said that they're still testing this feature right now (and that they would appreciate feedback) which means that we have an additional step to install `mamba`. Once they decide the feature is stable enough they will add `mamba` to their docker images, which will reduce the build time by another 1-2 minutes.

**Comment by dcherian** [comment]
Sounds like a win!
