### ISSUE TITLE
to_netcdf() modifies scheduler='single_threaded' behaviour

### ISSUE THREAD

**Issue by patquem** [pydata/xarray#4797]
Hello,

When specifying an xarray saving (with to_netcdf()) the scheduler in '**single_threaded**' mode seems to change temporarly into '**threads**' mode. That is a little bit confusing.
Is it a bug ?
thanks,
Patrick

Hereafter, a short code to reproduce the problem.
 if SAVING is **False**, Profiler returns (WHAT IS EXPECTED) :
![image](https://user-images.githubusercontent.com/16154687/104301149-992cb080-54c7-11eb-816f-fce808442966.png)
if SAVING is **True**, Profiler returns (WHAT IS NOT EXPECTED) :
![image](https://user-images.githubusercontent.com/16154687/104301279-bc576000-54c7-11eb-862e-a9933c441774.png)

```
import numpy as np
import xarray as xr
from dask.diagnostics import Profiler, visualize

SAVING = False

xarr = xr.DataArray(np.random.random((100, 100, 10)), dims=["x", "y", "z"])
xarr = xarr.chunk(chunks={"z": 1})

def interpolate(x):
    z_interp = np.arange(0, 10, 0.5)
    x = x.interp(z=z_interp)
    if SAVING:
        x.to_netcdf("test.nc")
    return x


with Profiler() as prof:
    xarr = interpolate(xarr)
    xarr.compute(scheduler='single-threaded')

visualize([prof])

```

**Environment**:
Windows 10
python 3.7.7
dask : 2020.12.0
xarray : 0.16.1

**Comment by jhamman** [comment]
As you have it written, you are not specifying the `'single-threaded'` scheduler for the `to_netcdf` part of your example. Instead, you are computing the interpolated array with the single-threaded scheduler after using the default scheduler (threaded) to write the netcdf file. There are a few ways to do this though:

You could wrap your full computation with dask.config's context manager:

```python
with dask.config.set(scheduler='single-threaded'):
    with Profiler() as prof:
        xarr = interpolate(xarr)
```

Or you could globally set the scheduler to single-threaded:

```python
dask.config.set(scheduler='single-threaded')
```

Or you could instruct xarray to return a dask delayed object from the to_netcdf call:

```python
...
if SAVING:
    task = x.to_netcdf("test.nc", compute=False)
    task.compute(scheduler='single-threaded')
```

More details on how to control the dask scheduler are available here: https://docs.dask.org/en/latest/setup/single-machine.html

**Comment by patquem** [comment]
Thank you very much jhamman for your answer.
I ignored such differencies between pure computational instructions and 'simple' writing ones in the point of view of the 'scheduler'. Thanks again.
I close the issue.
Patrick
