### ISSUE TITLE
scheduled upstream-dev CI is skipped

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#4801]
The scheduled CI is being skipped since about 6 days ago (which means this is probably due to the merge of #4729, see [this run](https://github.com/pydata/xarray/actions/runs/464816162) before the merge and [this run](https://github.com/pydata/xarray/actions/runs/467551905) after the merge).

This is really strange because `workflow_dispatch` events (for which the CI detection job is also skipped) still work perfectly fine.

Edit: it seems to be because of
https://github.com/pydata/xarray/blob/f52a95cbe694336fe47bc5a42c713bee8ad74d64/.github/workflows/upstream-dev-ci.yaml#L34-L37
if I remove that the scheduled CI runs.

cc @andersy005

**Comment by keewis** [comment]
the trigger also seems to be broken: the action fails because `HEAD^2` apparently is not always a valid ref for pull request events.

**Comment by andersy005** [comment]
@keewis, I think the issue has to do with a typo in this condition:


https://github.com/pydata/xarray/blob/fb67358ceb0c386560e6a6991dd937292ba54d46/.github/workflows/upstream-dev-ci.yaml#L35


The right event name is `schedule` instead of `scheduled`: `github.event_name == 'scheduled'` --> `github.event_name == 'schedule'`

**Comment by keewis** [comment]
Oh, thanks, that makes sense. I'll send in a PR.

**Comment by andersy005** [comment]
> the trigger also seems to be broken: the action fails because HEAD^2 apparently is not always a valid ref for pull request events.

Do you have any thoughts on how to address this?

**Comment by keewis** [comment]
I'm currently experimenting in #4805, but maybe we have to be smarter about how many commits to fetch.
