### ISSUE TITLE
Update Documentation for backend Implementation

### ISSUE THREAD

**Issue by aurghs** [pydata/xarray#4803]
The backend read-support refactor is drawing to a close and we should start to add the documentation to explain how to implement new backends.

We should:
- decide where to put the documentation
- decide a title
- define a brief list of the main points to discuss in the documentation.

For the first point, I suggest putting the documentation in "Internal". 
For the second one, I suggest: "How to add a new backend"

Concerning the third point, in the following there is a list of the topics, that I suggest::
- `BackendEntrypoint` Description (`BackendEntrypoint` is the main interface with xarray, it's a container of functions to be implemented and attributes: `guess_can_open`, `open_dataset`, `open_dataset_parameters`, [`guess_can_write`], [`dataset_writer`])
- How to add the backend as an external entrypoint.
- Description of the function contained in `BackendEntrypoint` to be implemented. In particular, for `open_dataset` we have two option to describe:  
   - No Lazy it returns a dataset containing numpy arrays.
   - Lazy it returns a dataset containing `BackendArrays`: 
 - BackendArrays description:
    - thread-safe `__getitem__`
    - Pickable (use CachingFileManager)
    - indexing.IndexingSupport

**Comment by alexamici** [comment]
Closed by #4810
