### ISSUE TITLE
Upstream dev CI does not show "version info"

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#4808]
Would be nice if it did :-)

e.g. https://github.com/pydata/xarray/runs/1698988952

**Comment by keewis** [comment]
it does: https://github.com/pydata/xarray/runs/1698988952#step:5:1203, it's just that because there's no separate step it is a little bit harder to find.

**Comment by mathause** [comment]
Thanks - still getting used to the new CI...

**Comment by keewis** [comment]
I think we should move it to a new step: if *you* have to ask we can't expect new contributors to find it.
