### ISSUE TITLE
xr.open_dataset can not read hdf file

### ISSUE THREAD

**Issue by fankk18** [pydata/xarray#4851]
**What happened**:
when engine='h5netcdf', I get:
OSError: Unable to open file (file signature not found)

when engine='netcdf4', I get:
RuntimeError: NetCDF: Attempting netcdf-4 operation on netcdf-3 file

This is my hdf file. Everyone can download by this link.
https://drive.google.com/file/d/1Tlu4D3407udUEaeIp8MR-NeyxDa2ze5O/view?usp=sharing

dataall =xr.open_dataset("MOD16A2.A2001001.h13v08.006.2017068140214.hdf",
                         mask_and_scale=True,
                        )

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

commit: None
python: 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 05:05:16) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 4.4.0-19041-Microsoft
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.16.2
pandas: 1.2.0
numpy: 1.19.5
scipy: 1.6.0
netCDF4: 1.5.5.1
pydap: None
h5netcdf: 0.8.1
h5py: 3.1.0
Nio: None
zarr: 2.6.1
cftime: 1.3.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.8
cfgrib: None
iris: None
bottleneck: None
dask: 2.20.0
distributed: 2.20.0
matplotlib: 3.3.3
cartopy: 0.18.0
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20210108
pip: 20.3.3
conda: None
pytest: None
IPython: 7.18.1
sphinx: None

</details>

**Comment by dcherian** [comment]
HI @fankk18 xarray cannot open arbitrary HDF files. You'll need to read with another package and then construct an xarray object manually.
