### ISSUE TITLE
check mypy at the end of some CI runs?

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#4881]
We currently run mypy in the `pre-commit hooks` CI. However, this is done in an environment where no dependencies are installed. Therefore we missed the errors that pop up when running mypy with numpy 1.20 installed. (Please correct my if I misunderstood this). Should we add a new step to our CI and run mypy?

I think we should at least add this to `ubuntu-latest py3.8`. For more complete checks we could also go for ` ubuntu-latest py37-min-all-deps` and `upstream-dev`.

**Comment by keewis** [comment]
> Therefore we missed the errors that pop up when running mypy with numpy 1.20 installed.

that's true, `mypy` won't be able to check for changes in the type hints of dependencies if it is run by `pre-commit`. However, I don't think we should add `mypy` steps to our CI. Instead, I would prefer new jobs (not sure how many, though).

**Comment by mathause** [comment]
> However, I don't think we should add mypy steps to our CI. Instead, I would prefer new jobs (not sure how many, though).

Works for me. I am also fine only testing in the `ubuntu-latest py3.8` environment. I suggested `ubuntu-latest py37-min-all-deps` because we may now need to special-case depending on the numpy version.

https://github.com/pydata/xarray/blob/0b8ec0cfa41b0a0919a3754a8909d64a223de7e6/xarray/core/npcompat.py#L82-L85
