### ISSUE TITLE
xarray.open_mfdataset: 'CFTimeIndex' object has no attribute '_cache'

### ISSUE THREAD

**Issue by JanChytry** [pydata/xarray#4891]
**What happened**:
I was trying to create/open a MFDataset from a list of NetCDF4 files. This failed and threw an error: 'CFTimeIndex' object has no attribute '_cache'. I suspect there might be an issue with time dimension in the files, however, I did not manipulate with them otherwise.

**The dataset**:
This issue was spotted when applying on unzipped file from EURO-CORDEX climate dataset. It is large so I cannot share it here but it can be downloaded for some minimum-capacity setup on Climate Data Store Website: https://cds.climate.copernicus.eu/cdsapp#!/dataset/projections-cordex-domains-single-levels

This is the setup of the dataset seen from the perspective of a programmable API
```python
import cdsapi

c = cdsapi.Client()

c.retrieve(
    'projections-cordex-domains-single-levels',
    {
        'domain': 'europe',
        'experiment': 'rcp_8_5',
        'horizontal_resolution': '0_11_degree_x_0_11_degree',
        'temporal_resolution': 'daily_mean',
        'variable': '2m_air_temperature',
        'gcm_model': 'mpi_esm_lr',
        'rcm_model': 'clmcom_clm_cclm4_8_17',
        'ensemble_member': 'r1i1p1',
        'start_year': '2006',
        'end_year': '2010',
        'format': 'zip',
    },
    'download.zip')

```

It can be clicked in the form here: https://cds.climate.copernicus.eu/cdsapp#!/dataset/projections-cordex-domains-single-levels?tab=form

**Minimal Complete Verifiable Example**:
```python
import xarray

files = [
# several file paths from an unzipped CORDEX ZIP file
]

xarray.open_mfdataset(files)
```

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 (default, Apr  3 2019, 19:16:38) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
python-bits: 64
OS: Linux
OS-release: 4.15.0-1065-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.3

xarray: 0.14.1
pandas: 1.2.1
numpy: 1.17.0
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.2
cfgrib: None
iris: None
bottleneck: None
dask: 2.6.0
distributed: None
matplotlib: 3.1.3
cartopy: None
seaborn: 0.9.0
numbagg: None
setuptools: 45.1.0
pip: 20.0.2
conda: None
pytest: 5.1.3
IPython: 7.4.0
sphinx: None

</details>

**Comment by mathause** [comment]
You have a relatively old version of xarray and cftime and a relatively new version of pandas. Maybe this is creates a problem. (But I don't know). Could you also paste the traceback.

**Comment by JanChytry** [comment]
You're right. Version discrepancy caused the issue. Another remiander we need to tidy up our server. Thanks!
