### ISSUE TITLE
Performance issues with list indexing when using dask

### ISSUE THREAD

**Issue by gabrielelanaro** [pydata/xarray#491]
Hi, I have a ~10GB dataset and I'm trying to slice it "orthogonally". The dataset is a molecular dynamics simulation that describes the motion (coordinates) of atoms in time. What I'd like to do is select specific atoms at specific timeframes. However I'm encountering some performance issues with list indexing using dask arrays.

This is the dataset (it is an h5 file):

```
>>> ds
<xray.Dataset>
Dimensions:       (atom: 88960, constants: 1, frame: 13757, xyz: 3)
Coordinates:
  * frame         (frame) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 ...
  * xyz           (xyz) int64 0 1 2
  * atom          (atom) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 ...
  * constants     (constants) int64 0
Data variables:
    cell_angles   (frame, xyz) float32 90.0 90.0 90.0 90.0 90.0 90.0 90.0 ...
    cell_lengths  (frame, xyz) float32 10.3711 10.3711 10.3711 10.1676 ...
    coordinates   (frame, atom, xyz) float32 1.631 0.239 0.675 1.826 1.514 ...
    time          (frame) float32 0.0 40.0 80.0 120.0 160.0 200.0 240.0 ...
```

And those are the timing for slicing.

```
%time ds.sel(atom=ds.atom % 2 == 0, frame=0).coordinates[0].values
CPU times: user 66.2 ms, sys: 0 ns, total: 66.2 ms
Wall time: 63.8 ms

array([ 1.63100004,  0.23900001,  0.67500001], dtype=float32)
```

```
%time ds.sel(atom=ds.atom % 2 == 0, frame=[0]).coordinates[0, 0].values

CPU times: user 17.6 s, sys: 0 ns, total: 17.6 s
Wall time: 18.6 s
Out[20]:
array([ 1.63100004,  0.23900001,  0.67500001], dtype=float32
```

However, this doesn't seem to happen with regular xray. (and that could be a solution because I can always chunk later when my application makes use of dask arrays).

I also try to build an actual dataset to isolate the error but I wasn't able to do that.

**Comment by shoyer** [comment]
Ultimately, I think this is probably a performance issue with the netCDF4-python library. It's nice that it supports orthogonal indexing, but I've noticed that it can be very slow for indexing a large number of elements at once.

Two work arounds:
1. Try loading your data using dask as an intermediate layer (by specifying the `chunks` argument).
2. Apply your indexing sequentially, and use `.load()` to transfer intermediate results into numpy arrays before doing further fancy indexing.

**Comment by shoyer** [comment]
Ah, I see from the title that you're using dask. What chunk size are you using?

**Comment by gabrielelanaro** [comment]
I tried different settings without much luck but typically I use frame=1000, atom=1000

**Comment by shoyer** [comment]
@mrocklin any idea what is going on here? how would you suggest debugging this?

**Comment by mrocklin** [comment]
Hi all, sorry for the delay.  

Guess 1
------

My first guess is that the optimizations that drill the `0` into the `slice(0, 1000)` aren't working.  E.g. we're building a graph that asks for this

    x[:1000][0]

and we want the optimizations to actually give us this

    x[0]

This works in the case above but might not work in the following case

    x[:1000][0]]

However a quick check at the code shows that I think that we *are* handling this case well.

```python
In [1]: import dask.array as da

In [2]: x = da.arange(100, chunks=10)[4]

In [3]: da.optimize(x.dask, x._keys())
Out[3]: 
{('x_1',): (<function operator.getitem>,
  (<function numpy.core.multiarray.arange>, 0, 10, 1, dtype('int64')),
  (4,))}

In [4]: x = da.arange(100, chunks=10)[[4]]

In [5]: da.optimize(x.dask, x._keys())
Out[5]: 
{('x_2', 0): (<function operator.getitem>,
  (<function numpy.core.multiarray.arange>, 0, 10, 1, dtype('int64')),
  ([4],))}
```

Guess 2
------

Actually I don't have another guess.  I would want to see the problem or something close if possible. 

@gabrielelanaro is it any slower if you use `frame=[0, 1, 2, 3, 4]`?

**Comment by gabrielelanaro** [comment]
Hi @mrocklin , first of all thanks for joining. : )
If we get more frames instead that one the performance is exactly the same (I tested with a "typable" number of frames).

I did some tests by optimizing through cull and fuse, and I was able to plot the execution graphs, I'll post the plots here so we can have some insight on what's happening under the hood. I'll prepare them tomorrow (hopefully)

**Comment by gabrielelanaro** [comment]
What it looks like is that optimization is actually working. 

```python
ind_fast = ds.sel(atom=ds.atom % 2 == 0, frame=0).coordinates[0].data
ind_slow = ds.sel(atom=ds.atom % 2 == 0, frame=[0, 1, 2, 3, 4, 5]).coordinates[0, 0].data

# No optimization
%time ind_fast.compute()
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 2.15 ms
array([ 1.63100004,  0.23900001,  0.67500001], dtype=float32)

%time ind_slow.compute()
CPU times: user 18.3 s, sys: 0 ns, total: 18.3 s
Wall time: 17.2 s
array([ 1.63100004,  0.23900001,  0.67500001], dtype=float32)

# Optimization
ind_fast.dask = da.optimize(ind_fast.dask, ind_fast._keys())
ind_slow.dask = da.optimize(ind_slow.dask, ind_slow._keys())

%time ind_fast.compute()
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 4.73 ms
array([ 1.63100004,  0.23900001,  0.67500001], dtype=float32)

%time ind_slow.compute()
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 2.25 ms
array([ 1.63100004,  0.23900001,  0.67500001], dtype=float32)
```

**Comment by max-sixty** [comment]
Closing as stale, please reopen if still relevant
