### ISSUE TITLE
Times not decoding due to time_reference being in another variable

### ISSUE THREAD

**Issue by kmuehlbauer** [pydata/xarray#4927]
**What happened**:

Decoding of times fails for NetCDF4 CfRadial2 style file due to `time_reference`-string is in another variable.

**What you expected to happen**:

`time_reference` should be extracted from the variable and time should be decoded properly.

**Minimal Complete Verifiable Example**:

```python
# create file with such feature
time = np.arange(10)
time_attrs = dict(standard_name="time",
                  units="seconds since time_reference",
                  calendar="gregorian")
time_ref_attrs = dict(comments="UTC reference date. Format follows ISO 8601 standard.")

ds = xr.Dataset(
    data_vars=dict(
        time=(["time"], time, time_attrs),    
        time_reference=([], '1970-01-01T00:00:00Z', time_ref_attrs),
    ))

ds.to_netcdf("test.nc")

# breaks with the error below
with xr.open_dataset("test.nc") as ds:
    print(ds)

# ad-hoc fix
with xr.open_dataset("test.nc", decode_times=False) as ds:
    tr = ds.time.attrs["units"].split(" ")
    nt = ds[tr[-1]].item()
    ds.time.attrs["units"] = " ".join([*tr[:-1], nt])
    ds = xr.decode_cf(ds)
    print(ds)
```

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/coding/times.py in _decode_cf_datetime_dtype(data, units, calendar, use_cftime)
    142     try:
--> 143         result = decode_cf_datetime(example_value, units, calendar, use_cftime)
    144     except Exception:

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/coding/times.py in decode_cf_datetime(num_dates, units, calendar, use_cftime)
    224         try:
--> 225             dates = _decode_datetime_with_pandas(flat_num_dates, units, calendar)
    226         except (KeyError, OutOfBoundsDatetime, OverflowError):

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/coding/times.py in _decode_datetime_with_pandas(flat_num_dates, units, calendar)
    174 
--> 175     delta, ref_date = _unpack_netcdf_time_units(units)
    176     delta = _netcdf_to_numpy_timeunit(delta)

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/coding/times.py in _unpack_netcdf_time_units(units)
    127     delta_units, ref_date = [s.strip() for s in matches.groups()]
--> 128     ref_date = _ensure_padded_year(ref_date)
    129 

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/coding/times.py in _ensure_padded_year(ref_date)
    102     matches_start_digits = re.match(r"(\d+)(.*)", ref_date)
--> 103     ref_year, everything_else = [s for s in matches_start_digits.groups()]
    104     ref_date_padded = "{:04d}{}".format(int(ref_year), everything_else)

AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-76-da468c6317bb> in <module>
     13 ds.to_netcdf("test.nc")
     14 
---> 15 with xr.open_dataset("test.nc") as ds:
     16     print(ds)
     17 

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, engine, chunks, lock, cache, drop_variables, backend_kwargs, use_cftime, decode_timedelta)
    432         from . import apiv2
    433 
--> 434         return apiv2.open_dataset(**kwargs)
    435 
    436     if mask_and_scale is None:

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/backends/apiv2.py in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, **kwargs)
    266 
    267     overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)
--> 268     backend_ds = backend.open_dataset(
    269         filename_or_obj,
    270         drop_variables=drop_variables,

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/backends/netCDF4_.py in open_dataset(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, group, mode, format, clobber, diskless, persist, lock, autoclose)
    557         store_entrypoint = StoreBackendEntrypoint()
    558         with close_on_error(store):
--> 559             ds = store_entrypoint.open_dataset(
    560                 store,
    561                 mask_and_scale=mask_and_scale,

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/backends/store.py in open_dataset(self, store, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta)
     23         encoding = store.get_encoding()
     24 
---> 25         vars, attrs, coord_names = conventions.decode_cf_variables(
     26             vars,
     27             attrs,

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/conventions.py in decode_cf_variables(variables, attributes, concat_characters, mask_and_scale, decode_times, decode_coords, drop_variables, use_cftime, decode_timedelta)
    510             and stackable(v.dims[-1])
    511         )
--> 512         new_vars[k] = decode_cf_variable(
    513             k,
    514             v,

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/conventions.py in decode_cf_variable(name, var, concat_characters, mask_and_scale, decode_times, decode_endianness, stack_char_dim, use_cftime, decode_timedelta)
    358         var = times.CFTimedeltaCoder().decode(var, name=name)
    359     if decode_times:
--> 360         var = times.CFDatetimeCoder(use_cftime=use_cftime).decode(var, name=name)
    361 
    362     dimensions, data, attributes, encoding = variables.unpack_for_decoding(var)

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/coding/times.py in decode(self, variable, name)
    515             units = pop_to(attrs, encoding, "units")
    516             calendar = pop_to(attrs, encoding, "calendar")
--> 517             dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)
    518             transform = partial(
    519                 decode_cf_datetime,

~/miniconda3/envs/h5py3/lib/python3.9/site-packages/xarray/coding/times.py in _decode_cf_datetime_dtype(data, units, calendar, use_cftime)
    151             "if it is not installed."
    152         )
--> 153         raise ValueError(msg)
    154     else:
    155         dtype = getattr(result, "dtype", np.dtype("object"))

ValueError: unable to decode time units 'seconds since time_reference' with "calendar 'gregorian'". Try opening your dataset with decode_times=False or installing cftime if it is not installed.
```

**Anything else we need to know?**:

I've searched the issues to no avail, also internet search wasn't successful so far. Any pointers welcome.

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.0 | packaged by conda-forge | (default, Oct 14 2020, 22:59:50) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 5.8.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.16.3.dev124+g0a309e07.d20210218
pandas: 1.2.1
numpy: 1.20.0
scipy: 1.6.0
netCDF4: 1.5.4
pydap: None
h5netcdf: 0.10.0
h5py: 3.1.0
Nio: None
zarr: None
cftime: 1.4.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.30.0
distributed: 2.30.1
matplotlib: 3.3.2
cartopy: 0.18.0
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20201009
pip: 20.2.4
conda: None
pytest: 6.1.2
IPython: 7.19.0
sphinx: None

</details>

**Comment by dcherian** [comment]
https://github.com/pydata/xarray/blob/070d8158aab31c6a53efb36f9ea4a57dc6671e43/xarray/conventions.py#L498-L500

Looks like we treat time bounds specially. You could add a helper function to this if condition that rewrites `"seconds since time_reference"` to `"seconds since 1970-01-01T00:00:00Z"` and the rest of the decoding machinery should just work. 

This approach might break round-tripping that file though. Perhaps saving `encoding["units"] = "seconds since time_reference"` fixes that?

**Comment by kmuehlbauer** [comment]
Thanks @dcherian, this looks like a way to try. I'll give it a try.

**Comment by spencerkclark** [comment]
Sorry for chiming in a bit late -- I just want to make sure, is this truly valid under the [CF Conventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#time-coordinate)?  It seems to open the door for ambiguity; e.g. it's a pathological example, but one could imagine a "time_reference" variable named in the form of a date.  In that case what takes precedence when decoding the times, the value of the date in the name, or the value the variable refers to?

**Comment by kmuehlbauer** [comment]
@spencerkclark This is specified in CfRadial1 https://www.eol.ucar.edu/system/files/CfRadialDoc.v1.4.20160801.pdf

**Comment by kmuehlbauer** [comment]
@spencerkclark We might restrict it to just that name `time_reference` over in #4933. WDYT?

**Comment by spencerkclark** [comment]
@kmuehlbauer thanks -- in my reading of the table under Section 4.4.1 (Attributes for time coordinate variable) it seems like the actual value of the date should appear in the units attribute of the time coordinate (matching the "time_reference" or "time_coverage_start" variable is a separate condition).

![Screen Shot 2021-02-20 at 2 13 31 PM](https://user-images.githubusercontent.com/6628425/108606064-d9643600-7385-11eb-91a7-990afc2c0f75.png)

**Comment by kmuehlbauer** [comment]
@spencerkclark The problem is I have exactly these files which have a time attrs units reading "time since time_reference" and a variable "time_reference" with the needed time string. OK, I can use the fix I showed above.

**Comment by spencerkclark** [comment]
Yeah, I understand, these kinds of metadata issues can be frustrating to deal with, especially when things are close to being valid, but not quite.  That said, I'm afraid I would be -1 on adding special logic to handle this to xarray, though I'm open to being convinced if others feel otherwise.  

(The time bounds logic is a bit different, because there are indeed [CF Conventions pertaining to that](http://cfconventions.org/cf-conventions/cf-conventions.html#cell-boundaries)).

**Comment by kmuehlbauer** [comment]
@spencerkclark If it's not exactly standard, it's not standard. So I completely understand your concerns.

I just need to figure out, how to work around this downstream.

**Comment by dcherian** [comment]
Thanks @spencerkclark I missed that those conventions specified that the `units` attribute should include the datetime string.

@kmuehlbauer you could
``` python
ds = xr.open_dataset(..., decode_times=False)
ds = rewrite_time_reference_units(ds)
ds = xr.decode_cf(ds)
```

**Comment by kmuehlbauer** [comment]
@dcherian Thanks, I've thought around the same. But it will be a bit more involved because this will be used in a new `BackendEntrypoint` in a downstream package.

**Comment by kmuehlbauer** [comment]
Closing as "won't fix" due to issue based on non-standard behaviour.

Anyone finding this issue, a workaround is shown in the OP.
