### ISSUE TITLE
netCDF4 DeprecationWarning: tostring() is deprecated. Use tobytes() instead.

### ISSUE THREAD

**Issue by colinahill** [pydata/xarray#4928]
I get the following deprecation warning with xarray 0.16.2

```
...python3.8/site-packages/xarray/backends/netCDF4_.py:411: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  attrs = FrozenDict((k, self.ds.getncattr(k)) for k in self.ds.ncattrs())
```

**Comment by keewis** [comment]
this is a upstream issue: `netcdf4<1.5.4` uses `numpy.tostring` ([changelog](https://github.com/Unidata/netcdf4-python/blob/master/Changelog)), so you should be able to upgrade `netcdf4` to make this warning disappear.
