### ISSUE TITLE
Feature request: xr.set_option('display.max_data_vars', N)

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#4992]
idea discussed here: https://github.com/pydata/xarray/discussions/4991

Copying here

the data_vars method provides a convenient ways to see the varaibles and the formatting (https://github.com/pydata/xarray/blob/master/xarray/core/dataset.py#L484) is nice. However, there are times I would look to see the full variables names not just a subset (12 is the default).

Ideally there would be a setting to toggle to specify the length of the formatter akin to https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html#overview

xr.set_option('display.max_data_vars', N)

**Comment by Illviljan** [comment]
Problem is that xarray is very unresponsive when you're printing many variables, see https://github.com/pydata/xarray/issues/4736. But this should do what you want I believe `xr.set_option("display_max_rows", N)`.

**Comment by raybellwaves** [comment]
Thanks @Illviljan. I missed that issue. Is the syntax above off slightly? Is it in the docs as well?

![Screen Shot 2021-03-04 at 10 03 05 AM](https://user-images.githubusercontent.com/17162724/109983634-04794e80-7cd1-11eb-9abf-856f6b17dec7.png)

**Comment by Illviljan** [comment]
I might have missed adding it in docs. It's here though: https://github.com/pydata/xarray/blob/master/xarray/core/options.py

Ah, it should be xr.set_options(display_max_rows=20)

**Comment by raybellwaves** [comment]
Thanks. Works great. Closing.
