### ISSUE TITLE
add xr.set_options to docs

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#4993]
https://github.com/pydata/xarray/issues/4992#issuecomment-790685921

**Comment by dcherian** [comment]
Its in API reference but not sure if it's anywhere else: https://xarray.pydata.org/en/stable/generated/xarray.set_options.html `display_max_rows` does seem to be missing... PR?

**Comment by keewis** [comment]
it isn't anywhere else, but `api.rst` does contain two links to `set_options`

**Comment by keewis** [comment]
should have been fixed by #5000
