### ISSUE TITLE
Dataset.plot.quiver() docs slightly misleading

### ISSUE THREAD

**Issue by johnomotani** [pydata/xarray#5002]
In the docs for `Dataset.plot.quiver()`
http://xarray.pydata.org/en/latest/generated/xarray.Dataset.plot.quiver.html
the `u` and `v` arguments are labelled as 'optional'. They are required for quiver plots though, so this is slightly confusing. I guess it is like this because the docs are created from a generic `_dsplot()` docstring, so don't know if it's fixable in a sensible way...

**Comment by cspencerjones** [comment]
> PR welcome! 
OK, thanks I will have a go. I'm a bit swamped atm but this seems like a good PR from me, so I'll try to get to it!
