### ISSUE TITLE
Example documentation in open_rasterio

### ISSUE THREAD

**Issue by gabriel-abrahao** [pydata/xarray#5005]
This is my first time submitting an issue, so sorry if doing this wrong.

In the documentation for open_rasterio there's an example on how to generate 2D coordinates from a GeoTiff file using it:

https://github.com/pydata/xarray/blob/37522e991a32ee3c0ad1a5ff8afe8e3eb1885550/xarray/backends/rasterio_.py#L177-L181

However, this method does not really work because the `da.attrs['transform']` attribute is not coded in the GDAL standard, but as `affine.Affine` expects directly (maybe it wasn't so in a previous version. So, at least for me (v0.16.2), getting the affine transformation right is done by simply replacing that line with the simpler:

` transform = Affine(*da.attrs['transform']) `

Again, sorry if this is not how this should be done, I just took a while to figure this out for my application and thought other people might benefit from it. If I can do something to fix it (if it's really broken) please let me know.

**Comment by scottyhq** [comment]
@gabriel-abrahao the docs are outdated and need to be changed. This has been brought up before here https://github.com/pydata/xarray/issues/3185#issuecomment-574215734

You can either do what you suggested or simply `transform = Affine(*da.transform)`
https://github.com/pydata/xarray/blob/12b4480ff2bde696142ca850275cdcc85ca0fbc9/xarray/tests/test_backends.py#L4468

A PR to update the documentation would be welcome. 

cc @snowman2 the docstring for open_rasterio has the same issue currently in rioxarray https://github.com/corteva/rioxarray/blob/63ce87f92835897d46aaa270f5ec07aca4e72cda/rioxarray/_io.py#L653

**Comment by snowman2** [comment]
Thanks for mentioning that. For rioxarray, the fix is:
```python
transform = da.rio.transform()
```
