### ISSUE TITLE
Invalidating cache for remote Pydap dataset?

### ISSUE THREAD

**Issue by jondoesntgit** [pydata/xarray#5017]
I have a remote server where data is continuously being written to a file that is served by Pydap. I'd like to monitor the file on my local computer. Is there a way that I can load up the dataset using xarray, do some calculations, and then at some point ask to download the newest datapoints? I believe that OpenDap servers sends a hash to the client to let the client know if their cache is current, and the clients can choose to redownload all or some of the data if necessary.

**Comment by max-sixty** [comment]
Is this still relevant?

**Comment by jondoesntgit** [comment]
I no longer use pydap in my day-to-day workflow. Feel free to close.
