### ISSUE TITLE
In-place operation on DataArray coordinate throws error but still modifies the coordinate values

### ISSUE THREAD

**Issue by nvaytet** [pydata/xarray#5036]
Example:
```Py
import xarray as xr
import numpy as np
data = np.random.rand(4, 3)
locs = np.arange(3.)
times = np.arange(4.)
foo = xr.DataArray(data, coords=[times, locs], dims=["time", "space"])
foo
```
![Screenshot at 2021-03-15 13-47-22](https://user-images.githubusercontent.com/39047984/111155637-fe1e8880-8594-11eb-854a-efca5414e1f5.png)

When trying to do an in-place modification of the coordinate values
```Py
foo.coords['time'] += 10.
```
I get
```Py
ValueError: Cannot assign to the .values attribute of dimension coordinate a.k.a IndexVariable 'time'. Please use DataArray.assign_coords, Dataset.assign_coords or Dataset.assign as appropriate.
```
However, when looking at the values of the coordinate, they seem to have been modified by the operation:
![Screenshot at 2021-03-15 13-49-12](https://user-images.githubusercontent.com/39047984/111155819-3f169d00-8595-11eb-8481-1ca6bef020d8.png)

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-66-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: None

xarray: 0.16.2
pandas: 1.2.0
numpy: 1.19.4
scipy: 1.5.3
netCDF4: None
pydap: None
h5netcdf: None
h5py: 3.1.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.2.2
cartopy: None
seaborn: None
numbagg: None
pint: 0.16.1
setuptools: 49.6.0.post20201009
pip: 20.3.3
conda: 4.9.2
pytest: 6.1.2
IPython: 7.19.0
sphinx: 3.3.0

</details>

**Comment by shoyer** [comment]
Thanks for the report!

This definitely seems like a bug. I confirmed that it is still present in xarray v0.17.
