### ISSUE TITLE
requires io.IOBase subclass rather than duck file-like

### ISSUE THREAD

**Issue by martindurant** [pydata/xarray#5070]
If you `open_dataset` on a file-like object, you will get the error 
```
TypeError: cannot read the magic number form [sic!]
```
This is because in `xarray.core.utils.read_magic_number`, we have `isinstance(filename_or_obj, io.IOBase)`, which is not necessarily the case for a file-like. I recommend changing this to `hasattr(filename_or_obj, "read")`.

Example:
```
In [1]: import fsspec

In [2]: fs = fsspec.filesystem('file')

In [3]: f = fs.open("201704010000.CHRTOUT_DOMAIN1.comp")

In [5]: import xarray as xr

In [6]: xr.open_dataset(f)
TypeError
```
Where `f` is a `LocalFileOpener`, made to be lazy and defer file opening, so that it can be pickled.

**Comment by martindurant** [comment]
xref https://github.com/pangeo-forge/pangeo-forge/pull/87

**Comment by NowanIlfideme** [comment]
Just ran into this. Unsure whether checking `hasattr` is better than just trying to read the object and catching an error - someone could implement a non-compliant `read` method, which would create other errors.

As a workaround, you could read it into BytesIO and pass the BytesIO instance:

```python
import fsspec
import xarray as xr
from io import BytesIO

of = fsspec.open("example.nc")
with of as f:
    xr.load_dataset(BytesIO(f.read()))
```

Also, [here's the link](https://github.com/pydata/xarray/blob/master/xarray/core/utils.py#L655) to the code. referenced above

Ideally xarray would work with `fsspec` or `pyfilesystem2` out of the box (to parse access URLs, for example).
I've had to fall back to using BytesIO buffers too many times. 😛

**Comment by martindurant** [comment]
>  Unsure whether checking hasattr is better than just trying to read the object and catching an error

Agree, that's fine. An `AttributeError` in this calling function might look weird, though, so you could have both.

> you could read it into BytesIO and pass the BytesIO instance

This is in general a bad idea, since we are wanting to deal with large files, and we have random access capabilities. 

> Ideally xarray would work with fsspec

It does, but this is an edge case of using fsspec for local files; these are normally passed as the filename.
