### ISSUE TITLE
Applying a function on a subset of variables using `map_blocks` is much slower

### ISSUE THREAD

**Issue by malmans2** [pydata/xarray#5071]
**What happened**:
Looks like when I use `map_blocks` with functions that operate on a subset of variables, the computation is much faster if I subsample the dataset first.

**What you expected to happen**:
In the example below, I wouldn't expect such a difference in computation time.

**Minimal Complete Verifiable Example**:

```python
import xarray as xr
ds = xr.tutorial.open_dataset("air_temperature")
ds["foo"] = xr.DataArray(ds["time"].values, dims="time")
ds = ds.chunk(dict(time=1, lon=-1, lat=-1))
```

```python
def func(obj):
    return obj[["foo"]]
```

```python
%%timeit
ds.map_blocks(func).compute()
```

    17.3 s ± 179 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```python
%%timeit
# Subsample the dataset before calling map_blocks
func(ds).map_blocks(func).compute()
```

    5.63 s ± 175 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1062.18.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.17.0
pandas: 1.2.3
numpy: 1.20.1
scipy: 1.6.1
netCDF4: 1.5.6
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.4.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2021.03.0
distributed: 2021.03.0
matplotlib: 3.3.4
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20210108
pip: 21.0.1
conda: None
pytest: 6.2.2
IPython: 7.21.0
sphinx: None

</details>

**Comment by dcherian** [comment]
Yes there is no way of knowing that your function only needs `"foo"` and not `"air"`. The actual function is totally opaque to `map_blocks` so it provides your whole dataset.

Can you send a PR improving the docs on this point?
