### ISSUE TITLE
plot_surface() wrapper

### ISSUE THREAD

**Issue by johnomotani** [pydata/xarray#5084]
Is there an xarray way to make a surface plot, like matplotlib's `plot_surface()`? I didn't see one on a quick skim, but expect it should be fairly easy to add, following the style for `contour()`, `pcolormesh()`, etc.? For the matplotlib version, see https://matplotlib.org/stable/gallery/mplot3d/surface3d.html.

**Comment by TomNicholas** [comment]
I suggested this in #2235 but then never did it... It would be nice though.

**Comment by johnomotani** [comment]
I started working on this, and it seems to be almost trivial, except that `plot_surface()` requires it's `x` and `y` arguments to be 2d arrays. My guess is that I want to special-case the broadcasting in `newplotfunc()` here https://github.com/pydata/xarray/blob/ddc352faa6de91f266a1749773d08ae8d6f09683/xarray/plot/plot.py#L678-L684
but it's not immediately obvious to me how this bit works:
* Why is it only ever `xval` that needs broadcasting? Couldn't the function have been called with a 2d `x` and a 1d `y`?
* Why is it OK to check if `xval.shape[0] == yval.shape[0]`? I'm probably missing something, but don't see how this check can work without referring to the actual dimensions of `x` and `y` - what if the single dimension of x was actually the second dimension of y, but happened to have the same size as the first dimension of `y`?
My first thought was that I just want to do
```
x = x.broadcast_like(z)
y = y.broadcast_like(z)
```
actually, I think this is a bug. I'll make a new issue...
