### ISSUE TITLE
Add example in your wiki.

### ISSUE THREAD

**Issue by JavierRuano** [pydata/xarray#5085]
Add example in wiki our calculation Stagnation index program repository, It is based on xarray with complex functions as ufunc and integration with django and cartopy. It is a Physics faculty UCM project 2020 and the researchers have articles based on that copernicus era5 data.

https://github.com/JavierRuano/ASI_Steady

The website is http://steady-ucm.org

I have created a Example with all necessary dataset 
https://github.com/JavierRuano/ASI_Steady/tree/main/Examples

The example could be here
http://xarray.pydata.org/en/stable/examples.html

Regards
Javier Ruano.

**Comment by max-sixty** [comment]
Hi @JavierRuano — thanks for the issue, and we're very open to adding more to our examples.

I'm looking at https://github.com/JavierRuano/ASI_Steady/blob/main/Examples/AirStagnationIndex_Wang_UCM_Project.ipynb. Currently I can only see one output at the bottom, which means it's not as engaging as it could be — I'm not sure exactly what intermediate users would learn from the example — could you help me understand?

Perhaps refactoring the example like the existing examples, so it more clearly demonstrates what the xarray functions are doing, could make it more helpful and engaging?

**Comment by JavierRuano** [comment]
I think it is interesting the operations over the time axis with numpy reduce, and the ufuncs operations. 
From my point of view there are a lot of pandas and dask users who could learn to use xarray with that example or what they are using netcdf-4 and numpy directly. I have created the example from the library, and it is not problem to change it. But it shows a stagnation calculation, it was the intention. 

But i understand what xarray is climate focused and you know if the topic is interesting and the example is really useful for your project. For me xarray have been very useful.

If you prefer another type of example, we could refactor it.
Regards
Javier Ruano.

**Comment by max-sixty** [comment]
We're keen to continue growing beyond climate, and we're interested in adding more examples. 

My point is that the current structure of the example — at least at the link above — doesn't seem that clear on what it's doing. Maybe have a browse of the examples at http://xarray.pydata.org/en/stable/examples and see how they're structured — there's lots of description and intermediate outputs. Does that make sense?

**Comment by JavierRuano** [comment]
Hi again @max-sixty , thanks for your advice, sure, the outputs have a lot of sense.
I think this new example has the good structure like another examples.
https://github.com/JavierRuano/ASI_Steady/blob/main/Examples/AirStagnationIndex_Wang_Xarray_Example.ipynb


Regards
Javier Ruano.

**Comment by keewis** [comment]
please note that during the refactor we removed the "external examples" section, so we will have to find a different place in the docs for this, or add it back (#5086 tries to merge into `stable`).

**Comment by max-sixty** [comment]
Let's discuss this at our bi-weekly call. I very much appreciate @JavierRuano submitting an example, it would be good to have a place where people can post examples which use xarray.
 
At the moment I think this probably needs some work to align it with canonical xarray, though.

**Comment by JavierRuano** [comment]
Ok, thanks @max-sixty .

**Comment by JavierRuano** [comment]
Shall i close this issue?

**Comment by max-sixty** [comment]
Hi @JavierRuano we discussed this in the dev meeting, thanks for your patience.

We'd like there to be space in the community for people demonstrating how they've used xarray without that necessarily living in the xarray library. That gives practitioners some more freedom and ownership (as our delay here demonstrates, unfortunately), and the xarray library can remain focused. We also thought that the example would need some changes for it to be demonstrating something that the current examples lack.

Have you considered posting it on Medium or a similar platform? If you decide to do something like that. please feel free to send something to the xarray mailing list (or let me know here and I can do it), I'm sure others would be interested.

Is that reasonable? Thanks again for your contribution and patience,
Max

**Comment by JavierRuano** [comment]
Thanks for your quick response, it is true that you have greatly improved the examples 
in the documentation, I do not know to what extent it would solve any lack. 
 The np.ufunc examples seemed insufficient a year ago but you have already solved.
And it is always better to be aware of the improvements that you are introducing 
before writing new documentation. 
Thanks for your attention.
