### ISSUE TITLE
Include data in repository for examples

### ISSUE THREAD

**Issue by clarkfitzg** [pydata/xarray#510]
Right now most of the examples in the documentation have something like this:

```
arr = xray.DataArray(np.random.randn(2, 3),
   ...:                      [('x', ['a', 'b']), ('y', [10, 20, 30])])
```

This feels distracting- it really only needs to be in the documentation for the constructors.

It would be really nice to have one set of realistic example data used throughout the docs. It should be accessible to anyone without requiring domain expertise- lat, long, temperature works fine. Simulated data is fine- avoids licensing issues.

The names should be something reflective of what they represent, and used that way consistently throughout the docs. They should also be easily accessible to the user copying and pasting code from the docs- similar to this:

```
from xray.examples import weather_dset, temp_array
```

@shoyer This will be especially helpful in the plotting I'm working on now.

**Comment by hainm** [comment]
+1 for this. might be

```python
from xray import datafiles
```

**Comment by max-sixty** [comment]
Closing as stale, please reopen if still relevant

`xr.tutorial.open_dataset('air_temperature')` for future reference
