### ISSUE TITLE
to_zarr() fails on time coordinate in append mode

### ISSUE THREAD

**Issue by yt87** [pydata/xarray#5106]
**What happened**:
When the append dimension coordinates are times and the dimension of the first dataset written is 1, consecutive appends forget the hour part of the coordinate.
**What you expected to happen**:
The time coordinate should be set correctly.

**Minimal Complete Verifiable Example**:

```
import pandas as pd
import xarray as xr
reftime = [pd.Timestamp(2021, 2, 21, 0)]
x = [0]
dims = ('reftime', 'x')
d = np.array([['A']])
ds1 = xr.Dataset(data_vars={'v': (dims, d)}, coords={'reftime': reftime, 'x': x})
_ = ds1.to_zarr('foo', mode='w')
reftime = [pd.Timestamp(2021, 2, 21, 6)]
d = np.array([['C']])
ds2 = xr.Dataset(data_vars={'v': (dims, d)}, coords={'reftime': reftime, 'x': x})
_ = ds2.to_zarr('foo', append_dim='reftime')
ds = xr.open_dataset('foo', engine='zarr')
ds.coords['reftime'].values

array(['2021-02-21T00:00:00.000000000', '2021-02-21T00:00:00.000000000'],  # should be 2021-02-21T06:00:00.000000000
      dtype='datetime64[ns]')
```

**Anything else we need to know?**:
When the `reftime` coordinate in the first dataset has dimension 2, the output is correct:
```
import pandas as pd
import xarray as xr
reftime = [pd.Timestamp(2021, 2, 21, 0), pd.Timestamp(2021, 2, 21, 3)]
x = [0]
dims = ('reftime', 'x')
d = np.array([['A'], ['B']])
ds1 = xr.Dataset(data_vars={'v': (dims, d)}, coords={'reftime': reftime, 'x': x})
_ = ds1.to_zarr('foo', mode='w')
reftime = [pd.Timestamp(2021, 2, 21, 6)]
d = np.array([['C']])
ds2 = xr.Dataset(data_vars={'v': (dims, d)}, coords={'reftime': reftime, 'x': x})
_ = ds2.to_zarr('foo', append_dim='reftime')
ds = xr.open_dataset('foo', engine='zarr')
ds.coords['reftime'].values

array(['2021-02-21T00:00:00.000000000', '2021-02-21T03:00:00.000000000',
       '2021-02-21T06:00:00.000000000'], dtype='datetime64[ns]')
```
Increment of a full day works fine:
```
import pandas as pd
import xarray as xr
reftime = [pd.Timestamp(2021, 2, 21, 0)]
x = [0]
dims = ('reftime', 'x')
d = np.array([['A']])
ds1 = xr.Dataset(data_vars={'v': (dims, d)}, coords={'reftime': reftime, 'x': x})
_ = ds1.to_zarr('foo', mode='w')
reftime = [pd.Timestamp(2021, 2, 22, 0)]
d = np.array([['C']])
ds2 = xr.Dataset(data_vars={'v': (dims, d)}, coords={'reftime': reftime, 'x': x})
_ = ds2.to_zarr('foo', append_dim='reftime')
ds = xr.open_dataset('foo', engine='zarr')
ds.coords['reftime'].values

array(['2021-02-21T00:00:00.000000000', '2021-02-22T00:00:00.000000000'],
      dtype='datetime64[ns]')
```
**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 5.10.11-200.fc33.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.17.0
pandas: 1.2.3
numpy: 1.20.2
scipy: 1.6.2
netCDF4: 1.5.6
pydap: None
h5netcdf: 0.10.0
h5py: 3.1.0
Nio: None
zarr: 2.7.0
cftime: 1.4.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.8.5
iris: None
bottleneck: 1.3.2
dask: 2021.04.0
distributed: 2021.04.0
matplotlib: 3.4.1
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20210108
pip: 21.0.1
conda: None
pytest: None
IPython: 7.22.0
sphinx: None

</details>

**Comment by yt87** [comment]
When the time dimension of the dataset being appended to is 1, the inferred unit is "days". This happens on line 318 in file conding/times.py. In this case variable ``timedeltas`` is an empty array and ``np.all`` evaluates to True:
```
np.all(np.array([]) % 1 == 0)
True
```
(which surprised me, by the way). When I forced ``_infer_time_units_from_diff`` to return "hours", the time coordinate in my example is evaluated correctly, so I think this particular code is the cause for the error.

Since the fallback return value is set to "seconds", I would argue that the case of empty ``timedeltas`` should be set to "seconds" as well. Are there alternatives or I should go ahead and create a pull request?

**Comment by dcherian** [comment]
There is a related issue for netCDF. The automagic guessing is not working so you'll need to manually set `.encoding["units"]` to preserve the time resolution you want. See https://xarray.pydata.org/en/stable/io.html#time-units

**Comment by yt87** [comment]
I am closing this issue. It is impossible to guess the proper time unit when dealing with missing data. Setting the attribute explicitly is a better solution.

A minor quibble:  the statement
``ds1.reftime.encoding['units'] = 'hours since Big Bang'`` 
rises an exception
 ``AttributeError: 'NoneType' object has no attribute 'groups'``
It should be
``ValueError: invalid time units: hours since Big Bang``
the same as in the case ``'hours after 1970-01-01'``

**Comment by dcherian** [comment]
Thanks @yt87 can you open a new issue to fix that error message?
