### ISSUE TITLE
auto_combine/open_mfdataset can be very slow sometimes if concat_dim is not provided

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#511]
Through an unfortunate series of events, when `concat_dim` is not provided, it loads into memory the data for the coordinate being concatenated for every dataset in a serial process. This can be very slow if the files are being loaded on a network drive with some latency.

cc @ToddSmall

**Comment by TomNicholas** [comment]
Isn't this closed by #1981?

**Comment by shoyer** [comment]
Probably? It's certainly gone stale at this point.
