### ISSUE TITLE
DataArray to Zarr

### ISSUE THREAD

**Issue by skgbanga** [pydata/xarray#5120]
Currently, there is a way in which a `Dataset` can be stored in zarr and it is described at:
http://xarray.pydata.org/en/stable/io.html?highlight=zarr#zarr

Is there a way to store `DataArray` into zarr directly as well? 

PS: One can always create a Dataset with a single element:
> xr.Dataset({"bar": foo})

where foo is a DataArray to accomplish the above. 

I was wondering if this is the recommended way.

**Comment by max-sixty** [comment]
Hi @skgbanga  — yes that's currently the recommended way.

**Comment by keewis** [comment]
you could also use the [`to_dataset`](https://xarray.pydata.org/en/latest/generated/xarray.DataArray.to_dataset.html) method:
```python
foo.to_dataset()
# or, if foo.name is None
foo.to_dataset(name="bar")
```
