### ISSUE TITLE
Add `BackendEntrypoint` to an easier to find location

### ISSUE THREAD

**Issue by alexamici** [pydata/xarray#5125]
**Is your feature request related to a problem? Please describe.**

I started implementing a few backend plugins following the documentation so I noticed a few easily fixable quirks:

http://xarray.pydata.org/en/latest/internals/how-to-add-new-backend.html

The main one is the `BackendEntrypoint` is found deep into `xarray.backends.common`.

**Describe the solution you'd like**

I suggest to add an easier to find reference:
* `xarray.backends.BackendEntrypoint` would do
* but maybe even `xarray.BackendEntrypoint`. 

**Additional context**

For the simplest plugins `BackendEntrypoint` would be the only import to connect to *xarray*.

See this dummy GDAL plugin: https://github.com/bopen/xarray-gdal/blob/main/xarray_gdal/xarray_plugin.py
But also the *rioxarray* plugin in this PR: corteva/rioxarray/pull/281

**Comment by alexamici** [comment]
Same with `BackendArray` for plugin that want to support lazy loading.

**Comment by shoyer** [comment]
👍  for putting all external API stuff related to backends in the top level `xarray.backends`.

**Comment by alexamici** [comment]
This didn't close automatically, but it is closed by #5127
