### ISSUE TITLE
Add chunks argument to {zeros/ones/empty}_like.

### ISSUE THREAD

**Issue by nbren12** [pydata/xarray#5144]
**Describe the solution you'd like**

We have started using xarray objects as "schema" for initializing zarrs that will be written to using the `region` argument of `to_zarr`. For example,

```
output_schema.to_zarr(path, compute=False)
for region in regions:
    output = func(input_data.isel(region))
    output.to_zarr(path, region=region)
```

Currently, xarray's tools for computing the `output_schema` Dataset are a lacking since rechunking existing datasets can be slow. `dask.array.zeros_like` takes a chunks argument, can we add one here too?

**Describe alternatives you've considered**

`.chunk`

**Comment by max-sixty** [comment]
If https://github.com/pydata/xarray/issues/8251 were solved, we could do:

```python
xr.DataArray().chunk(42).broadcast_like(ds)
```

In the place of that, we can do a hack:

```python
xr.DataArray([1]).chunk(2).broadcast_like(ds).squeeze('dim_0')
```

(where `broadcast_like` can also be adding on dimensions with `.expand_dims` — not sure exactly how you prefer to initialize the arrays)

I would have a preference for using orthogonal methods like `.chunk`, rather than adding more kwargs to methods.

Do you think that works for your case @nbren12 ?

**Comment by dcherian** [comment]
> rather than adding more kwargs to methods.

I think these array creation functions are almost always going to be messy if we want to support all the array types in them. It just happens that there is a dask-specific method. Like we might want to pass `format` for `pydata/sparse` ([example](https://sparse.pydata.org/en/stable/generated/sparse.zeros_like.html))

**Comment by max-sixty** [comment]
> We could accept a `array_like` argument, and pass `**kwargs` to the appropriate library

+1

**Comment by dcherian** [comment]
Wait this was added at some point: https://docs.xarray.dev/en/stable/generated/xarray.zeros_like.html

```
xarray.zeros_like(other, dtype=None, *, chunks=None, chunked_array_type=None, from_array_kwargs=None)
```

**Comment by max-sixty** [comment]
Ha! OK, well, ask and ye shall receive...

(I certainly don't feel strongly enough to suggest removing it...)
