### ISSUE TITLE
PRs cancel CI on push

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#5190]
The `cancel` step doesn't seem to be configured properly, a push to a pull request shouldn't cancel CI on `master`. For reference, here are the logs for two examples: [CI Additional](https://github.com/pydata/xarray/runs/2384577555?check_suite_focus=true), [CI](https://github.com/pydata/xarray/runs/2384577560?check_suite_focus=true).

**Comment by dcherian** [comment]
A push with `skip-ci` also cancels previously running test jobs (previous commit did not have skip-ci).
