### ISSUE TITLE
Probable error using zarr process synchronizer

### ISSUE THREAD

**Issue by josephnowak** [pydata/xarray#5210]
Hi I was trying to use Xarray open_zarr with the Zarr ProcessSynchronizer class and it produces a set of errors, I don't know if those errors are produced because I don't understand the logic of the ProcessSynchronizer or is a simple bug. I have a small code which reproduces the problems, basically, if I put a different path in the Zarr ProcessSynchronizer class all the error disappear but it creates a new folder.

```python
import xarray 
import zarr
import numpy as np


arr = xarray.DataArray(
    data=np.array([
        [1, 2, 7, 4, 5],
        [np.nan, 3, 5, 5, 6],
        [3, 3, np.nan, 5, 6],
        [np.nan, 3, 10, 5, 6],
        [np.nan, 7, 8, 5, 6],
    ], dtype=float),
    dims=['index', 'columns'],
    coords={'index': [0, 1, 2, 3, 4], 'columns': [0, 1, 2, 3, 4]},
)

# If the synchronizer is created using another path the code will work without any error but it creates a new folder,
# that is the correct way to use the process synchronizer?
# synchronizer = zarr.ProcessSynchronizer('dummy_array.sync')

# Using the original path produce a set of weird problems
synchronizer = zarr.ProcessSynchronizer('dummy_array')

# Executing the commented code I obtain: PermissionError: [WinError 5].
# arr.to_dataset(name='data').to_zarr('dummy_array', mode='w', synchronizer=synchronizer, compute=True)

arr.to_dataset(name='data').to_zarr('dummy_array', mode='w', compute=True)

# If this section of the code is uncommented It will throw a different error when xarray.open_zarr being executed
# a = zarr.open_array('dummy_array/data', synchronizer=synchronizer, mode='r')

# PermissionError: [Errno 13] Permission denied
xarray.open_zarr('dummy_array', synchronizer=synchronizer)
```

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: es_ES.cp1252
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.17.0
pandas: 1.1.3
numpy: 1.19.2
scipy: 1.5.2
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: 2.7.1
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.30.0
distributed: 2.30.1
matplotlib: 3.3.2
cartopy: None
seaborn: 0.11.0
numbagg: None
pint: None
setuptools: 50.3.1.post20201107
pip: 21.0.1
conda: 4.10.0
pytest: 6.2.3
IPython: 7.19.0
sphinx: 3.2.1

</details>

**Comment by max-sixty** [comment]
Sorry this didn't get traction a couple of years back.

But the example does seem to work now — so I'll close, but please reopen with any follow-ups.
