### ISSUE TITLE
Add an Cumulative aggregation, similar to Rolling

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#5215]
**Is your feature request related to a problem? Please describe.**

Pandas has a [`.expanding` aggregation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.expanding.html), which is basically rolling with a full lookback. I often end up supplying rolling with the length of the dimension, and this is some nice sugar for that. 

**Describe the solution you'd like**
Basically the same as pandas — a `.expanding` method that returns an `Expanding` class, which implements the same methods as a `Rolling` class.

**Describe alternatives you've considered**
Some options:
– This
– Don't add anything, the sugar isn't worth the additional API.
– Go full out and write specialized expanding algos — which will be faster since they don't have to keep track of the window. But not that much faster, likely not worth the effort.

**Comment by mathause** [comment]
I don't entirely get what the function is supposed to do (even after looking at the pandas docstring) - can you give a an example or two?

**Comment by dcherian** [comment]
IIUC `da.expanding(dim=dim).sum()` is `da.cumsum(dim)` with support for `min_periods` and `center` like `rolling`.

I guess all expanding reductions are basically `numpy.ufunc.accumulate(...)`. The dask versions will be "interesting" to write.
https://github.com/dask/dask/blob/f1f37cae96d5e98f8043ea430539a4fffbe62661/dask/array/reductions.py#L1389-L1413

Like @mathause I find "expanding" confusing. `.accumulate().sum()` or `.cumulative().sum()` sounds much better to me.

**Comment by max-sixty** [comment]
`.cumulative` is great! Much better.

The benefit is that the API surface is reduced — e.g. we can have a `.cumulative().integrate()`, rather than a separate `.cumulative_integrate` (and so on, for each aggregation), from https://github.com/pydata/xarray/pull/5153.

The implementation could be as simple as `da.rolling(dim=da.sizes[dim])`. How compatible would dask be with that? How does it compare to the `numpy.ufunc.accumulate(...)` suggestion?

**Comment by mathause** [comment]
Go for it - we can hardly keep up with reviewing ;-)

**Comment by shoyer** [comment]
I am pretty stoked about the idea of supporting cumulative integrals with the same syntax as other cumulative operations :)
