### ISSUE TITLE
Inconsistencies between 0.17.0 and 0.17.1.dev102+gf455e00f

### ISSUE THREAD

**Issue by chiaral** [pydata/xarray#5257]
Download file:
`!wget https://noaa-gefs-retrospective.s3.amazonaws.com/GEFSv12/reforecast/2000/2000012900/c00/Days%3A1-10/acpcp_sfc_2000012900_c00.grib2`

I work on https://staging.us-central1-b.gcp.pangeo.io/

xarray: 0.17.0
cfgrib: 0.9.9.0

and when I try:

`ds = xr.open_dataset("acpcp_sfc_2000012900_c00.grib2", engine="cfgrib", backend_kwargs={"extra_coords": {"stepRange": "step"}})`

it works. The keyword argument `'extra_coords'` it's new to cfgrib 0.9.9.0 

After installing the latest `xarray` version from master (when I do 
`!pip install git+https://github.com/pangeo-forge/pangeo-forge.git`)
the version becomes
xarray '0.17.1.dev102+gf455e00f'
cfgrib remains the same

when I attempt the same loading:
`ds = xr.open_dataset("acpcp_sfc_2000012900_c00.grib2", engine="cfgrib", backend_kwargs={"extra_coords": {"stepRange": "step"}})`

I get
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-6673e5f2812b> in <module>
----> 1 ds = xr.open_dataset("acpcp_sfc_2000012900_c00.grib2", engine="cfgrib", backend_kwargs={"extra_coords": {"stepRange": "step"}})

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)
    499 
    500     overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)
--> 501     backend_ds = backend.open_dataset(
    502         filename_or_obj,
    503         drop_variables=drop_variables,

TypeError: open_dataset() got an unexpected keyword argument 'extra_coords'
```

**What you expected to happen**:

I expect '0.17.1.dev102+gf455e00f' to work as '0.17.0'

**Comment by shoyer** [comment]
@chiaral thanks for the report, and for testing the development version of Xarray!

@alexamici @aurghs could one of you kindly take at look at this issue? it looks related to the new backend API

**Comment by alexamici** [comment]
@chiaral thanks for spotting this issue! This is actually a bug in *cfgrib* 0.9.9.0 not *xarray*. I'll transfer it to the *cfgrib* repo.

**Comment by alexamici** [comment]
I'll close this issue, @chiaral please follow up on ecmwf/cfgrib#231
