### ISSUE TITLE
Confused about variable declared but not used in DataArray documentation

### ISSUE THREAD

**Issue by canyon289** [pydata/xarray#5320]
The documentation for `xr.DataArray` includes this precipitation variable but it doesnt actually seem to be used anywhere? Was it intended to showcase some functionality or is it superfluous? 

If its not needed can it be removed? Whatever the fix is I'm happy to make a PR (if not im not mistaken!)
http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html#xarray.DataArray

**Edit**
I see it is used in Dataset documentation so now get the intent. I still suggest removing it from `xr.DataArray` as its not used there. 
http://xarray.pydata.org/en/stable/user-guide/data-structures.html

![image](https://user-images.githubusercontent.com/7213793/118420566-fe5e0180-b673-11eb-8788-595ffa89ea48.png)

**Comment by max-sixty** [comment]
Agree it's unnecessary — please feel free to remove it
