### ISSUE TITLE
map_blocks doesn't handle tranposed arrays

### ISSUE THREAD

**Issue by aulemahal** [pydata/xarray#5326]
**What happened**:

I was using `map_blocks` for a complex function which returns an array with a different dimension order than the input. Because of the complexity of the wrapped func, I need to generate a `template` first.

When calling `map_blocks` and loading the result, it passes all checks in `map_blocks` but `Variable` fails when assigning the new data.

**What you expected to happen**:
I expected no failure. Either the result  would have transposed dimensions, or it would have been transposed back to fit with `template`.

**Minimal Complete Verifiable Example**:

```python
import xarray as xr

da = xr.DataArray([[0, 1, 2], [3, 4, 5]], dims=('x', 'y'))

def func(d):
    return d.transpose()

dac = da.chunk()
dac.map_blocks(func, template=dac).load()
```

Traceback:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-0da1b18a36a8> in <module>
      7 
      8 dac = da.chunk()
----> 9 dac.map_blocks(func, template=dac).load()

~/.conda/envs/xclim/lib/python3.8/site-packages/xarray/core/dataarray.py in load(self, **kwargs)
    871         dask.compute
    872         """
--> 873         ds = self._to_temp_dataset().load(**kwargs)
    874         new = self._from_temp_dataset(ds)
    875         self._variable = new._variable

~/.conda/envs/xclim/lib/python3.8/site-packages/xarray/core/dataset.py in load(self, **kwargs)
    799 
    800             for k, data in zip(lazy_data, evaluated_data):
--> 801                 self.variables[k].data = data
    802 
    803         # load everything else sequentially

~/.conda/envs/xclim/lib/python3.8/site-packages/xarray/core/variable.py in data(self, data)
    378         data = as_compatible_data(data)
    379         if data.shape != self.shape:
--> 380             raise ValueError(
    381                 f"replacement data must match the Variable's shape. "
    382                 f"replacement data has shape {data.shape}; Variable has shape {self.shape}"

ValueError: replacement data must match the Variable's shape. replacement data has shape (3, 2); Variable has shape (2, 3)
```
If `func` is made to return `d` (no transpose), the code works.

I actually not sure which behaviour would be the best : a result with transposed dimensions to fit with the wrapped func or to tranpose the result to fit with the template. The latter seems much easier to implement by editing `core/parallel.py` and add the transposition at the end of `_wrapper()` in `map_blocks()`.

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 5.11.16-arch1-1
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: fr_CA.utf8
LOCALE: ('fr_CA', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.17.1.dev99+gc58e2aeb.d20210430
pandas: 1.2.4
numpy: 1.20.2
scipy: 1.6.3
netCDF4: 1.5.6
pydap: installed
h5netcdf: 0.11.0
h5py: 3.2.1
Nio: None
zarr: 2.8.1
cftime: 1.4.1
nc_time_axis: 1.2.0
PseudoNetCDF: installed
rasterio: 1.2.2
cfgrib: 0.9.9.0
iris: 2.4.0
bottleneck: 1.3.2
dask: 2021.04.0
distributed: 2021.04.1
matplotlib: 3.4.1
cartopy: 0.19.0
seaborn: 0.11.1
numbagg: installed
pint: 0.17
setuptools: 49.6.0.post20210108
pip: 21.1
conda: None
pytest: 6.2.3
IPython: 7.22.0
sphinx: 3.5.4

</details>

**Comment by max-sixty** [comment]
Hi @aulemahal !

Does this work with `return d`? Could you add the stack trace?

**Comment by aulemahal** [comment]
Hi @max-sixty, just edited the top comment to include the traceback.

The MWE does work with `return d`.

**Comment by dcherian** [comment]
You should be providing `template = dac.transpose()`. Does it work then? You can also not provide `template` in which case it will infer the right thing.

**Comment by aulemahal** [comment]
Haha, sorry, I didn't explain this properly.

This MWE is just MWE. The use case I have of `map_blocks` is in a decorator. At the moment I write the `map_blocks` call, I do not know if `func` will transpose the result or not. In my case, the template is generated from a list of dimensions to reduce and new dimensions.

I realize this might be an edge case that is too narrow to merit a fix. I expected dimension order not to matter, as it is the case in most of xarray.  Right now, my code wraps  `func` in a another function that performs this tranpose when needed.

**Comment by andersy005** [comment]
> I expected dimension order not to matter, as it is the case in most of xarray. Right now, my code wraps func in a another function that performs this transpose when needed.

Isn't it the case the order matters here because you are providing a template for `map_blocks` to follow? Would your code still work if you were to leave `map_blocks` to do the inference of the output dataset on its own as Deepak pointed out? From the code snippet you provided, it appears that `map_blocks` works without the template 

```python
In [10]: dac.map_blocks(func).load()
Out[10]: 
<xarray.DataArray <this-array> (y: 3, x: 2)>
array([[0, 3],
       [1, 4],
       [2, 5]])
Dimensions without coordinates: y, x
```

**Comment by dcherian** [comment]
> I expected dimension order not to matter, as it is the case in most of xarray. 

Yeah... the `template` is special, it must exactly match what the function returns. In your case, it seems like you know the dimension order. So you can transpose the template object to that dimension order

**Comment by aulemahal** [comment]
Thanks everyone. Just to be clear, I am using `map_blocks` in a rather complicated way (way more than this MWE) and at the moment of the `map_blocks` call, the code doesn't know the dimension order of the output, only the names. Moreover, in this code, the wrapped functions are too complex for `map_blocks` to infer the template. The idea is that all wrapped funcs reduce some dims or add some other (but with known sizes), thus I can construct a template, but the dim order is uncertain.

However, I understand that it is expected from `map_blocks` that the result fits the template, so my expectation was not correct. I'll leave the "workaround" in my code and close this issue. Thanks!
