### ISSUE TITLE
ENH: Add keep_encoding to global options

### ISSUE THREAD

**Issue by snowman2** [pydata/xarray#5336]
**Is your feature request related to a problem? Please describe.**
https://corteva.github.io/rioxarray/stable/getting_started/manage_information_loss.html

Original data:
```python
rds.green.attrs, rds.green.encoding
```
```
({'nodata': 0, 'units': ('DN', 'DN')},
 {'dtype': 'float64',
  'grid_mapping': 'spatial_ref',
  'scale_factor': 1.0,
  'add_offset': 0.0,
  '_FillValue': nan,
  'source': 'netcdf:../../test/test_data/input/PLANET_SCOPE_3D.nc:green'})
```
```python
with xarray.set_options(keep_attrs=True):
    new_ds = rds.green + rds.green
new_ds.attrs, new_ds.encoding
```
```
{'nodata': 0, 'units': ('DN', 'DN')}, {}
```
**Describe the solution you'd like**
```python
with xarray.set_options(keep_attrs=True, keep_encoding=True):
    new_ds = rds.green + rds.green
new_ds.attrs, new_ds.encoding
```
```
({'nodata': 0, 'units': ('DN', 'DN')},
 {'dtype': 'float64',
  'grid_mapping': 'spatial_ref',
  'scale_factor': 1.0,
  'add_offset': 0.0,
  '_FillValue': nan,
  'source': 'netcdf:../../test/test_data/input/PLANET_SCOPE_3D.nc:green'})
```

**Comment by jhamman** [comment]
This seems like a reasonable thing to do. We can likely reuse a lot of the machinery from `keep_attrs` to make this happen. @snowman2 - is this something you would be up to work on?

**Comment by snowman2** [comment]
I am not certain about my availability at the moment. If I get free time, I would be happy to do so. However, if someone else gets started on it first, that would be great as well.

**Comment by max-sixty** [comment]
Now we have `.reset_encoding`, does that supplant this?

I'd generally lean away from global options — increases the cardinality of the library, similar code will act differently based on context, etc.

**Comment by dcherian** [comment]
Yes we are deleting encoding eventually so I'll close this
