### ISSUE TITLE
failing cftime plot tests

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#5344]
This was reported in #5077 and seems to be an upstream issue (see https://github.com/pydata/xarray/issues/5077#issuecomment-808605313):

```
FAILED xarray/tests/test_plot.py::TestCFDatetimePlot::test_cfdatetime_line_plot
FAILED xarray/tests/test_plot.py::TestCFDatetimePlot::test_cfdatetime_pcolormesh_plot
FAILED xarray/tests/test_plot.py::TestCFDatetimePlot::test_cfdatetime_contour_plot
```

In order to get the upsteam-dev CI open new issues for other failing tests on upstream-dev I've `xfail`'ed them in #5343. This should be undone once it is fixed in either `cftime` or `nc-time-axis`.

**Comment by spencerkclark** [comment]
Thanks @keewis; I agree it's good to just `xfail` them for now.

**Comment by aulemahal** [comment]
FYI, I opened SciTools/nc-time-axis#59 to update `nc-time-axis`. Waiting for maintainers to review.
