### ISSUE TITLE
v0.18.2

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#5348]
I'm about to release this as v0.18.2: https://github.com/pydata/xarray/compare/v0.18.1...max-sixty:release-0.18.2?expand=1 given https://github.com/pydata/xarray/issues/5346

Let me know any thoughts @pydata/xarray , thanks

**Comment by max-sixty** [comment]
This is done. Sorry for the regression — mea culpa. 

https://github.com/pydata/xarray/releases/tag/v0.18.2

**Comment by dcherian** [comment]
Thanks for the quick action here, max!
