### ISSUE TITLE
test_cross_engine_read_write_netcdf4 is broken on Python 3 due to some sort of upstream change

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#535]
This has started causing test failures on master.

I had trouble tracking this down, but it seems to be related to a build of hdf5, netCDF4 or the underlying libraries which just became available on conda.

In case anyone else has time for it:
This build worked: https://travis-ci.org/xray/xray/jobs/75633366
This build failed: https://travis-ci.org/xray/xray/jobs/75777788

For now, let's just skip the test and come back to this later.

Possibly related: https://github.com/Unidata/netcdf4-python/issues/448

**Comment by jhamman** [comment]
Here's a diff of the versions that went into each build environment: 

```
$ diff -y worked.txt broken.txt
    curl:            7.38.0-0         			      |	    curl:            7.43.0-1         

    hdf5:            1.8.14-0         			      |	    hdf5:            1.8.15.1-1       

    libnetcdf:       4.3.2-1          			      |	    krb5:            1.13.2-0         

    netcdf4:         1.1.8-np19py34_0 			      |	    libnetcdf:       4.3.3.1-1        
							      >
							      >	    netcdf4:         1.1.9-np19py34_0 
```

given that the failure is in an I/O test, it seems likely that this is coming from `netcdf4`.

**Comment by QuLogic** [comment]
See #1298, where I changed Python 2.7 CI to install `h5netcdf` as well (it seemed to be missing.) This test doesn't work on Python 2 either right now.
