### ISSUE TITLE
Support `range` in `groupby_bins`

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#5358]
Although `groupby_bins` supports setting bins as int, it doesn't support manually setting the range.

Here's an example:

```
from scipy.stats import binned_statistic
import numpy as np
import xarray as xr

# --- scipy method ---
x = np.arange(500)
values = x*50
statistics, _, _ = binned_statistic(x, values, statistic='min', bins=500, range=(0, 500))

# --- xarray method ---
x = xr.DataArray(x)
values = xr.DataArray(values)
x.groupby_bins('dim_0', bins=500).min()
```

I can set `range=(0, 500)` in `binned_statistic`, how can I get the same result using `groupby_bins`?
Is it suitable to add this new feature?
I have also posted a similar [question](https://stackoverflow.com/questions/67630382/apply-scipy-binned-statistic-by-dask) on StackOverflow.

**Comment by dcherian** [comment]
> If bins is an int, it defines the number of equal-width bins in the given range (10 by default). 

So the xarray equivalent would be `bins=np.linspace(0, 500, 500)`. An extra kwarg seems unnecessary.

**Comment by zxdawn** [comment]
@dcherian Thanks! That's simple ;) However, the `groupby_bins` method is a little different from `binned_statistic`.

`binned_statistic`:
> All but the last (righthand-most) bin is half-open. In other words, if bins is [1, 2, 3, 4], then the first bin is [1, 2) (including 1, but excluding 2) and the second [2, 3). The last bin, however, is [3, 4], which includes 4.

`groupby_bins`:
> right (bool, default: True) – Indicates whether the bins include the rightmost edge or not. If right == True (the default), then the bins [1,2,3,4] indicate (1,2], (2,3], (3,4].

So, let's check this shorter example:
```
from scipy.stats import binned_statistic
import numpy as np
import xarray as xr

# --- scipy method ---
x = np.arange(10)
values = x*5
statistics, _, _ = binned_statistic(x, values, statistic='min', bins=10, range=(0, 10))

# --- xarray method ---
x = xr.DataArray(x)
values = xr.DataArray(values)
bin_res = values.groupby_bins('dim_0', bins=np.linspace(0, 10, 10), right=False, include_lowest=True).min()

print('scipy: \n', statistics)
print('xarray: \n', bin_res)
```

Output:
```
scipy: 
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]

xarray: 
 <xarray.DataArray (dim_0_bins: 9)>
array([ 0, 10, 15, 20, 25, 30, 35, 40, 45])
Coordinates:
  * dim_0_bins  (dim_0_bins) object [0.0, 1.111) ... [8.889, 10.0)
```

The scipy method has one more value ...

## Summary

These produce the same results:
```
binned_statistic(x, values, statistic='min', bins=10, range=(0, 10))
values.groupby_bins('dim_0', bins=np.linspace(0, 10, 11), right=False, include_lowest=True).min()
```

Output:
```
scipy: 
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
xarray: 
 <xarray.DataArray (dim_0_bins: 10)>
array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])
Coordinates:
  * dim_0_bins  (dim_0_bins) object [0.0, 1.0) [1.0, 2.0) ... [9.0, 10.0)
```

**Comment by zxdawn** [comment]
@dcherian Has this method been improved in [dask_groupby](https://github.com/dcherian/dask_groupby)? Could you provide a simple example we can follow? I got lost in the dask_groupby documentation ...

**Comment by dcherian** [comment]
No I haven't finished the implementation yet.
