### ISSUE TITLE
Type hints for xr.open_dataset

### ISSUE THREAD

**Issue by adamjstewart** [pydata/xarray#5382]
I've noticed that `xarray` has partial type hinting support. What's the timeline for full type hinting support? In particular, I'm seeing:
```
error: Call to untyped function "open_dataset" in typed context
```
because `xr.open_dataset` does not yet have type hints.

**Comment by shoyer** [comment]
There's no timeline for complete type hinting -- or most other features in xarray, for that matter. Xarray is mostly a volunteer run project that depends on user contributions.

We would certainly welcome the addition of type hints for `open_dataset()`. At the very least, we could clarify that `open_dataset()` return an `xarray.Dataset` object.

**Comment by adamjstewart** [comment]
Good to know, I'll try to add type hints and submit a PR if I get the chance.

**Comment by krishnaap** [comment]
@shoyer how can I contribute to type hinting?

**Comment by max-sixty** [comment]
@krishnaap we'd welcome a Pull Request!
