### ISSUE TITLE
Add xr.open_dataset("file.tif", engine="rasterio") to docs

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#5386]
Kind of related to https://github.com/pydata/xarray/issues/4697 

I see https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html#rioxarray

shows

`ds = xarray.open_dataset("file.tif", engine="rasterio")`

This could be added to

https://xarray.pydata.org/en/latest/user-guide/io.html#rasterio

**Comment by sjvrijn** [comment]
The link to corteva has been added to the rasterio user guide in https://github.com/pydata/xarray/pull/5808, so I think this issue can be closed too.
