### ISSUE TITLE
KeyError when trying to select a list of DataArrays with different name type

### ISSUE THREAD

**Issue by malmans2** [pydata/xarray#5387]
**What happened**:
Looks like I can't select a list of DataArrays with different name type.

**What you expected to happen**:
If this is not a bug, consider raising a more informative error.

**Minimal Complete Verifiable Example**:

```python
import xarray as xr
from xarray import Dataset, DataArray

keys = ["foo", 1]
ds = Dataset()
for key in keys:
    ds[key] = DataArray()
    
ds[keys]
```
```
KeyError: '1'
```

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 5.8.0-53-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.8.0

xarray: 0.18.2
pandas: 1.2.4
numpy: 1.20.3
scipy: None
netCDF4: 1.5.6
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2021.05.0
distributed: 2021.05.0
matplotlib: 3.4.2
cartopy: None
seaborn: None
numbagg: None
pint: 0.17
setuptools: 49.6.0.post20210108
pip: 21.1.2
conda: None
pytest: 6.2.4
IPython: 7.23.1
sphinx: None

</details>

**Comment by keewis** [comment]
that looks like a bug: accessing the variables separately *is* possible.

Somewhat related, we seem to have broken the `repr` of `ds.variables`.

**Comment by dcherian** [comment]
Uh.. isn't this also a bug? 
``` python
import xarray as xr
from xarray import Dataset, DataArray

keys = ("foo", 1)  # note tuple, not list
ds = Dataset()
for key in keys:
    ds[key] = DataArray()
    
ds
```
```
<xarray.Dataset>
Dimensions:  ()
Data variables:
    foo      float64 nan
    1        float64 nan
```

Shouldn't there be just one variable with name `(foo, 1)` since the tuple is `Hashable`?

**Comment by dcherian** [comment]
`ds[1]` and `ds[[1]]` works too

**Comment by malmans2** [comment]
I think `np.asarray` is converting everything to strings:
https://github.com/pydata/xarray/blob/a6a1e48b57499f91db7e7c15593aadc7930020e8/xarray/core/dataset.py#L1488

**Comment by malmans2** [comment]
`np.asarray(key, dtype='O')` fixes the bug, not sure if there's any downside

**Comment by max-sixty** [comment]
> `np.asarray(key, dtype='O')` fixes the bug, not sure if there's any downside

Interesting! It might be worth seeing whether anything breaks.

**Comment by malmans2** [comment]
All tests are passing with `dtype='O'`, although I'm not fully following why `asarray` is needed in the first place.
I'll open a PR so we can start from there...
