### ISSUE TITLE
allow custom 'units' when saving datetimes to netCDF

### ISSUE THREAD

**Issue by andreas-h** [pydata/xarray#540]
when manually setting the `units` attribute of a DataArray containing datetime types, the error

    ValueError: Failed hard to prevent overwriting key 'units'

is raised.

It would be good to allow custom units, because currently the units seem to be `days since FIRST_TIMESTEP`, which leads to different units for different variables within the same Dataset.

**Comment by shoyer** [comment]
We should raise a better error message. You can indeed actually customize this by setting an approach `encoding` on the DataArray, e.g.,
`ds.time.encoding['units'] = 'hours since 1900-01-01T00'

**Comment by shoyer** [comment]
This is now describing on the IO docs page under "encoding"
