### ISSUE TITLE
Does the PyPI release job fire twice for each release?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#5413]
I was attempting to copy the great work here for numbagg and spotted this! Do we fire twice for each release? Maybe that's fine though?

https://github.com/pydata/xarray/actions/workflows/pypi-release.yaml

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/5635139/120264760-517aab80-c253-11eb-85ad-74849cc04e8d.png">

**Comment by andersy005** [comment]
> Do we fire twice for each release? Maybe that's fine though?

Yes, on both `push` and `release` events. The publication to PyPI step is only run for the `release` event though i.e. if one were to push a tag to GitHub, this tag would never be published to PyPI via the GitHub workflow. 

 It's my understanding that 

- We could remove the `push` trigger and only keep the `release` trigger and everything would still work fine. 
- Having the two triggers comes in handy when/if one pushes tags via `git` (for testing purposes). As far as I can remember, @keewis was using the `push` event (via tags) to test the early versions of the workflow.

**Comment by max-sixty** [comment]
Ah I see, thank you for explaining @andersy005 , I see now. This is excellent. 

If we want to split out "Upload to TestPyPI" as its own _job_ (rather than step) — so it's otherwise the same as "Upload to PyPI" but only runs on the tag, I'm happy to make that change.
