### ISSUE TITLE
Retain metadata for each xr.DataArray while concatenating

### ISSUE THREAD

**Issue by muaali** [pydata/xarray#5421]
Problem:
I cannot concatenate images with different metadata as metadata is either lost or overriden. There is no option to retain metadata for each image while performing concatenation. 

Proposed Solution:
User should be able to specify `combine_attrs="retain"` in argument of `xr.concat` to avoid any conflict resolution or over ride behavior.

Example:

```
shape = (150,100)
def create_dummy_xdarray(np_array, metadata):
    az_index = np.arange(0, np_array.shape[0])
    range_index = np.arange(0, np_array.shape[1])
    return xr.DataArray(np_array, coords=[az_index, range_index], dims = ["azimuth", "range"],
                            attrs = metadata)

a1 = np.full(shape, 1, dtype=np.uint16)
a2 = np.full(shape, 2, dtype=np.uint16)
a3 = np.full(shape, 3, dtype=np.uint16)

metadata1 = {"product_file": "A1", "datatype": "type1"}
metadata2 = {"product_file": "A2", "datatype": "type2", "region": "Asia"}
metadata3 = {"product_name": "A3", "datatype": "type3", "customer": "USA"}

array_seq = [a1, a2, a3]
metadata_seq = [metadata1, metadata2, metadata3]

xdarray_list = []

for i, np_array in enumerate(array_seq):
    xdarray = create_dummy_xdarray(np_array, metadata_seq[i]) 
    xdarray_list.append(xdarray)
    xdarray.close()

    
concat_ds = xr.Dataset({"intensity": xr.concat(xdarray_list, dim='band', data_vars='all')})
concat_ds.close()
```
If I print out `concat_ds.intensity[0].attrs` or `concat_ds.intensity[1].attrs` or `concat_ds.intensity[2].attrs` I get the same output which is `{'product_file': 'A1', 'datatype': 'type1'}`. The expected behavior is to retain metadata for each `xr.DataArray` while concatenating.

**Comment by keewis** [comment]
I suspect there's a misconception about `concat`: `concat` combines several `DataArray` objects together into a single `DataArray`. For example, if you had two `DataArray` objects with the dimensions `{"a": 5, "b": 3}` and you concatenate them along a new dimension `"c"`, you'll get a single `DataArray` with the dimensions `{"a": 5, "b": 3, "c": 2}`. Each `DataArray` can only have a single `attrs` dict.

If you don't need to combine all arrays into a big array, you might want to look into adding these objects as separate variables of the same `Dataset`:
```python
intensity = xr.Dataset({arr.name: arr for arr in xdarray_list})  # or use arr.attrs["band"] instead of arr.name
```
as each variable has a separate `attrs` dict.
