### ISSUE TITLE
pandas support when calling xarray.open_rasterio

### ISSUE THREAD

**Issue by jmigueldelgado** [pydata/xarray#5430]
When calling xarray.open_rasterio:
```
import xarray as xr

xds = xr.open_rasterio("https://github.com/mapbox/rasterio/raw/1.2.1/tests/data/RGB.byte.tif")
```
the following error occurs:
> AttributeError: module 'pandas' has no attribute 'Panel'

I am using:

- gdal                      3.1.4            py37h2ec2946_2    conda-forge
- libgdal                   3.1.4                h02eeb80_2    conda-forge
- rasterio                  1.1.8            py37h527b4ca_0    conda-forge
- xarray                    0.12.1                     py_0    conda-forge
- pandas                    1.2.1            py37hdc94413_0    conda-forge
- python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20)  [GCC 9.3.0]
- Linux-4.15.0-143-generic-x86_64-with-debian-buster-sid

I have read [here](https://stackoverflow.com/questions/65600306/module-pandas-has-no-attribute-panel) that xarray only supports pandas 0.25.0. Is this true? Should I downgrade pandas in order to keep using xarray? Is there any chance this gets solved soon?

PS using the module rioxarray yielded the same error.

**Comment by keewis** [comment]
no, you'll have to upgrade `xarray`: `xarray=0.12.1` was released more than two years ago.
