### ISSUE TITLE
Do we need to test python 3.8?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#5431]
**Is your feature request related to a problem? Please describe.**

Currently we test on python 3.7, 3.8, and 3.9; across Linux, Windows, and Mac.

**Describe the solution you'd like**

Is there any reason to test 3.8 on every commit? Is there any code that would work on 3.7 & 3.9 but not on 3.8?

It's no great cost, but getting the pipeline to be faster has (fairly distributed, often unseen) benefits.

**Describe alternatives you've considered**

- I'm not sure whether it's possible to query CI history, and see where failures have shown up? i.e. "which tests, if you never included them, would lead to no change in whether all the tests pass"?
- We could run these as "confirmation" tests on main only
- We could maybe also cut out Mac & Windows 3.7? Less confident about these.

**Comment by shoyer** [comment]
I agree, it probably isn't necessary.
