### ISSUE TITLE
xarray.open_rasterio

### ISSUE THREAD

**Issue by ghost** [pydata/xarray#5434]
Could you please change `xarray.open_rasterio` from `experimental` to `stable` with more faster capability of reading geotiff files (if possible)?
For original array indexing capabilities, I would like to stick in `xarray` than `rioxarray`.
With much respected.
Thank you.

**Comment by dcherian** [comment]
> For original array indexing capabilities

Can you clarify what this means?

**Comment by hickskin** [comment]
Sorry for late response.
I was trying to read a big geotif file as follows.
import xarray as xr
xds = xr.open_rasterio(geotif_file)

My task was to array indexing and to save output into disk.

columns = [8,9,7,100,1050,......, 9000]
rows = [18,19,17,1100,1105,......, 9100]

data = xds.isel(x=xr.DataArray(columns), y=xr.DataArray(rows)) 

np.save('output.npy', data)

When I saw docs on `xr.open_rasterio()`, it mentions it is an experimental now.
So, I'm curious if it could be much faster when it becomes `stable`.

I look forward to see it as `stable` version. 
Thank you so much.
