### ISSUE TITLE
Add Union Operators for Dataset

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#5438]
As of python 3.9, python dictionaries now support being merged via
```python
c = a | b
```
and updated via
```python
c = a |= b
```
see [PEP 584](https://www.python.org/dev/peps/pep-0584/#abstract).

`xarray.Dataset` is dict-like, so it would make sense to support the same syntax for merging. The way to achieve that is by adding new dunder methods to `xarray.Dataset`, something like

```python
def __or__(self, other):
    if not isinstance(other, xr.Dataset):
        return NotImplemented
    new = xr.merge(self, other)
    return new

def __ror__(self, other):
    if not isinstance(other, xr.Dataset):
        return NotImplemented
    new = xr.merge(self, other)
    return new

def __ior__(self, other):
    self.merge(other)
    return self
```

The distinction between the intent of these different operators is whether a new object is returned or the original object is updated.

This would allow things like `(ds1 | ds2).to_netcdf()`

(This feature doesn't require python 3.9, it merely echoes a feature that is only available in 3.9+)

**Comment by shoyer** [comment]
My main concern here is that these binary operators _already_ have a meaning on `xarray.Dataset`, as vectorized operators. In particular, `|` corresponds to `np. bitwise_or`.

Union operators would be convenient, but writing out `merge()` is not really so bad.

**Comment by TomNicholas** [comment]
Oh, I didn't realise that! Forget about this idea then :disappointed:
