### ISSUE TITLE
[community] Flexible indexes meeting

### ISSUE THREAD

**Issue by benbovy** [pydata/xarray#5452]
In addition to the [bi-weekly community developers meeting](https://github.com/pydata/xarray/issues/4001), we plan to have 30min meetings on a weekly basis -- every Tue 8:30-9:00 PDT (17:30-18:00 CEST) -- to discuss the flexible indexes refactor.

Anyone from @pydata/xarray feel free to join!  The first meeting is in a couple of hours.

[Zoom link](https://us05web.zoom.us/j/84894064491?pwd=UDFjUjBVbTFQQ1k2SEJIa0UwRFFjZz09) (subject to change).

[Google calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=OTVsbzRlajE4Y2NyMDg3Nm80bzduamQ1OXNfMjAyMTA2MTVUMTUzMDAwWiBiZW5ib3Z5QG0&tmsrc=benbovy%40gmail.com&scp=ALL)

[Meeting notes](https://hackmd.io/I6u0oA0ISECNl3bwfvIcjA)

**Comment by benbovy** [comment]
Hi everyone, I have an appointment and won't be able to join the meeting later today, sorry. I suggest to skip this one and meet next week.

**Comment by benbovy** [comment]
Hi everyone, I'll take two weeks off starting from next week, so I suggest to meet up again starting from Tue 20th July.

I also added a link to the (raw) meeting notes in my top-level comment.

**Comment by benbovy** [comment]
Hi everyone, I won't be able to join the meeting next week (Tue Aug 17). Let's meet back Tue Aug 24!

**Comment by benbovy** [comment]
Hi everyone, unfortunately I can't join the meeting today. Let's meet next week (Nov 23rd).

**Comment by benbovy** [comment]
Hi everyone, I won't be able to join the meeting tomorrow (Tue Nov 30th). Let's meet next week!

**Comment by sjvrijn** [comment]
The large indexes update is finished, so can this issue be closed?
