### ISSUE TITLE
Add coarsen.construct

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#5454]
Like `Rolling.construct` this would create a new reshaped array with extra dimensions that would usually be reduced over. It would be a light wrapper over `Variable._coarsen_reshape`

It make https://github.com/pydata/xarray/discussions/5119, and #2419 really easy without having to go through a MultiIndex+unstack operation which is somewhat arcane.
``` python
ds.coarsen(time=12).construct(dim="year").rename({"time": "month"})
```

**Comment by shoyer** [comment]
Yes, we should totally do this!

This is a very common operation in machine learning workflows, e.g., in TensorFlow it's `tf.image.extract_patches`.

**Comment by dcherian** [comment]
> ds.coarsen(time=12).construct(dim="year").rename({"time": "month"})

We could incorporate the renaming like this. Thoughts?

``` python
ds.coarsen(time=12).construct(dim={"time": ("month", "year")})
```
