### ISSUE TITLE
Issue on page /generated/xarray.DataArray.T.html

### ISSUE THREAD

**Issue by krishnaap** [pydata/xarray#5478]
what is xarray.DataArray.T? There is no much documentation about it.
When I displayed my relative humidity data-array with objective T, it displayed like below 
`rh.T`
`Out[65]: `
`<xarray.DataArray 'rh' (lev: 33, points: 1)>`
`<Quantity([[ 69.200005]`

There is no explanation about it as well.
http://xarray.pydata.org/en/stable/generated/xarray.DataArray.T.html

**Comment by max-sixty** [comment]
It's `.transpose()`, similar to Numpy. It mostly exists for historical reasons / compatibility.

Let's keep this open since the docs are blank; a PR to fix that would be great.

**Comment by dcherian** [comment]
I thought we deprecated this, didnt we?

**Comment by keewis** [comment]
There has been some discussion about deprecating `DataArray.T` in favor of `DataArray.transpose` in #2509, but as far as I can tell the decision was postponed.

**Comment by krishnaap** [comment]
I really thought xarray.DataArray.T as something like DataArray.values as it giving values!

**Comment by keewis** [comment]
> I really thought xarray.DataArray.T as something like DataArray.values as it giving values!

what do you mean with that? This is what I see:
```python
In [3]: arr = xr.DataArray([[0, 1], [2, 3]])
   ...: arr
Out[3]: 
<xarray.DataArray (dim_0: 2, dim_1: 2)>
array([[0, 1],
       [2, 3]])
Dimensions without coordinates: dim_0, dim_1

In [4]: arr.T
Out[4]: 
<xarray.DataArray (dim_1: 2, dim_0: 2)>
array([[0, 2],
       [1, 3]])
Dimensions without coordinates: dim_1, dim_0

In [5]: arr.transpose()
Out[5]: 
<xarray.DataArray (dim_1: 2, dim_0: 2)>
array([[0, 2],
       [1, 3]])
Dimensions without coordinates: dim_1, dim_0
```

**Comment by krishnaap** [comment]
@keewis I mean I was confused. Its clear now.
