### ISSUE TITLE
DataArray.sum is slower than applying numpy's .sum and re-building DataArray

### ISSUE THREAD

**Issue by lucaslascano** [pydata/xarray#5487]
**What happened**:
I had a DataArray with shape (72, 262, 33, 7, 2, 27) and applied .sum() over three dimensions. I noticed a big spike in memory usage, so I tried converting it to a numpy ndarray, apply .sum() and re-build the DataArray. It outperformed it in time and it didn't have a memory spike.

**What you expected to happen**:
It should be faster and not have a memory spike.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import numpy as np
import xarray as xr

index_a = pd.Index([f'A-{i}' for i in range(72)], name='index_a')
index_b = pd.Index([f'B-{i}' for i in range(262)], name='index_b')
index_c = pd.Index([f'C-{i}' for i in range(33)], name='index_c')
index_d = pd.Index([f'D-{i}' for i in range(7)], name='index_d')
index_e = pd.Index([f'E-{i}' for i in range(2)], name='index_e')
index_f = pd.Index([f'F-{i}' for i in range(27)], name='index_f')

indexes = [index_a, index_b, index_c, index_d, index_e, index_f]

np_array = np.ones(tuple([len(ind) for ind in indexes]))
# Build base DataArray
da = xr.DataArray(np_array, indexes)

dims_to_sum = ['index_b', 'index_c', 'index_d', 'index_e']

# DataArray sum()
%timeit da.sum(dims_to_sum)

def sum_with_np(dataarray, sum_dim_names):
    
    sum_dims_indexes = dataarray.get_axis_num(sum_dim_names)
    np_array_2 = dataarray.values.sum(axis=sum_dims_indexes)

    remaining_dims = [pd.Index(dataarray.coords[dim].values, name=dim)
                          for dim in dataarray.dims if dim not in sum_dim_names]

    return xr.DataArray(np_array_2, remaining_dims)

# Applying numpy sum() and re-building DataArray
%timeit sum_with_np(da, dims_to_sum)
```

**Anything else we need to know?**:
I provided that dimensionality because it performs worse as dimentionality goes up.
Performance:
- DataArray.sum(): 1.37 s ± 107 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
- numpy.sum() and re-building DataArray: 359 ms ± 28.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

I apologize if the example is not short enough. This is my first time creating an issue here. 
I'm not sure if this behaviour is expected because DataArray sum() must do something else I'm not taking account of.
We use xarray at work a lot and we love it (we build financial-economic models and data analytics solutions for companies in Python).

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 5.8.0-55-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: es_ES.UTF-8
LOCALE: es_ES.UTF-8
libhdf5: None
libnetcdf: None

xarray: 0.18.0
pandas: 1.2.4
numpy: 1.20.2
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20210108
pip: 21.1.2
conda: None
pytest: None
IPython: 7.24.1
sphinx: None

</details>

**Comment by dcherian** [comment]
`.sum` uses `nansum` by default which uses a memory copy. For a direct comparison, use `.sum(skipna=False)`.

**Comment by lucaslascano** [comment]
Thanks! That is what I needed.
