### ISSUE TITLE
Add `typing-extensions` to the list of dependencies?

### ISSUE THREAD

**Issue by malmans2** [pydata/xarray#5495]
`typing_extensions` is imported in `xarray/core/npcompat.py` and `xarray/core/utils.py`.

However, `typing-extensions` is not a dependency in `setup.cfg`, and I get the following error when I install with `pip install git+https://github.com/pydata/xarray` using python 3.9:

```python
import xarray
```
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by max-sixty** [comment]
Great spot! We should definitely add that.

I wonder how CI passes, then?

**Comment by malmans2** [comment]
Looks like there isn't an action that only installs `xarray` using `pip`, but dependencies are installed first using conda. Must be in the conda recipe of one of the packages specified in the CI environments?

**Comment by max-sixty** [comment]
Yes, good point.

Would you be up for another PR @malmans2 ?

**Comment by shoyer** [comment]
Can we consider making typing-extensions a fully optional dependency instead?

In particular, typing-extensions 3.10 is a very new version, only from May 2021. This seems overly restrictive, particularly for a dependency that isn't really needed at all at runtime and that we only use for a few type annotations.

**Comment by malmans2** [comment]
@shoyer I added `typing-extensions` in the docs too, so you'd have to remove it from there as well: https://github.com/shoyer/xarray/blob/typing-extensions-optional/doc/getting-started-guide/installing.rst

**Comment by shoyer** [comment]
I made an attempt at making the use of TypeGuard optional, but it doesn't pass mypy yet: https://github.com/pydata/xarray/pull/5624

**Comment by Illviljan** [comment]
Using `typing_extensions` seems to be a nice way to get backwards compatibility with older python versions. 
I can see some typing bugs slipping through rather easily onsidering how picky mypy is and the CI doesn't do mypy checks on all python versions.

**Comment by max-sixty** [comment]
As soon as libraries like Beam allow installing later versions, I would vote to add this back.
