### ISSUE TITLE
Rename master branch -> main

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#5516]
This is a best practice for inclusive projects.

See https://github.com/github/renaming for guidance.

**Comment by keewis** [comment]
who will do that? S

**Comment by keewis** [comment]
the renaming on github and RTD should be done, I'll check the CI now.

**Comment by keewis** [comment]
once binder has been fixed we should be able to close this

**Comment by keewis** [comment]
as far as I can tell, `binder` works now but the environment is missing `pooch`. That's not related to the branch rename, though, so I'll close this.
