### ISSUE TITLE
Time is not correctly saved to disk netcdf 

### ISSUE THREAD

**Issue by guidocioni** [pydata/xarray#5549]
**What happened**:
When trying to write a dataset to netcdf file using the netcdf4 engine time is not saved correctly. 

**What you expected to happen**:
Time to be saved correctly as in the original dataset.

**Minimal Complete Verifiable Example**:

```python
ds.to_netcdf(filename,
             encoding={product_type: {'zlib': True, 'complevel': 9}},
             engine='netcdf4')
```

is giving me the warning
```
SerializationWarning: saving variable time with floating point data as an integer dtype without any _FillValue to use for NaNs
```

xarray Dataset

<img width="709" alt="Screen Shot 2021-06-29 at 11 55 07" src="https://user-images.githubusercontent.com/12760310/123777979-fc24cf00-d8d0-11eb-9a81-f707900e512b.png">

saved on disk (notice time values)

<img width="728" alt="Screen Shot 2021-06-29 at 11 55 54" src="https://user-images.githubusercontent.com/12760310/123778238-30988b00-d8d1-11eb-8581-f236fbb1a062.png">

I cannot see anything special in the time array...is there a limitation because of the compression? 

**Environment**:
<details><summary>Output of <tt>xr.show_versions()</tt></summary>
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-229.1.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.17.0
pandas: 1.2.3
numpy: 1.20.1
scipy: 1.6.3
netCDF4: 1.5.6
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.2
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.3.4
cartopy: 0.18.0
seaborn: 0.11.1
numbagg: None
pint: 0.17
setuptools: 49.6.0.post20210108
pip: 21.1.1
conda: 4.10.2
pytest: None
IPython: 7.21.0
sphinx: None

</details>

**Comment by max-sixty** [comment]
Is this still an issue? Could we have an MCVE if so?
