### ISSUE TITLE
Dataset.transpose support for missing_dims

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#5550]
**Is your feature request related to a problem? Please describe.**
I have a dataset where I do not know which of two dimensions (lets call them `a` and `b`) exists in this dataset (So either it has dims ("a", "other") or ("b", "other")).
I would like to make sure that this dimension is first using transpose, but currently this is only possible using `if` or `try` statements. Just using `ds.transpose("a", "b", "other")` raises a `ValueError arguments to transpose XXX must be permuted dataset dimensions YYY`.

**Describe the solution you'd like**
It would be nice if I could just use `ds.transpose("a", "b", "other", missing_dims="ignore")` similar to how `DataArray.transpose` handles it.

**Describe alternatives you've considered**
Currently I'm also using `ds.map(lambda x: x.transpose("a", "b", "other", missing_dims="ignore"))`, which could (maybe?) replace the current implementation of the transpose.

While at it, `transpose_coords` could also be exposed to Dataset.transpose.

**Comment by max-sixty** [comment]
Sounds good, we'd take a PR for this — seems abberant to have it for `DataArray` but not `Dataset`. 

Any objections?

**Comment by dcherian** [comment]
Another solution is `ds.transpose(..., "other")`

**Comment by max-sixty** [comment]
> Another solution is `ds.transpose(..., "other")`

Yes, this works for the majority of cases (and is a really nice interface). 

It doesn't cover all cases; e.g. we want `a` before `b` and aren't sure whether a or b exist.

**Comment by gcaria** [comment]
I've noticed that `Dataset.transpose` calls `Variable.transpose`, which does not support `missing_dims` either. It is interesting that both `DataArray.transpose` and `Variable.transpose` use `utils.infix_dims`, but only the former takes advantage of its `missing_dims` argument.

https://github.com/pydata/xarray/blob/3d1d134278bbf5cabdd176d42787a05eba23730d/xarray/core/dataarray.py#L2250-L2251

https://github.com/pydata/xarray/blob/3d1d134278bbf5cabdd176d42787a05eba23730d/xarray/core/variable.py#L1407

Should `Dataset` and `Variable` just copy what's done for `DataArray` ?

**Comment by max-sixty** [comment]
> 
> Should `Dataset` and `Variable` just copy what's done for `DataArray` ?

Yes good idea!

**Comment by headtr1ck** [comment]
I'm not sure if "copy" is the best way to do it.
Since `DataArray` and `Dataset` just use `Variable.transpose` would it not make more sense to implement this functionality into `Variable.transpose` and just let `Data{set,Array}.transpose` pass on these arguments?
