### ISSUE TITLE
Release v0.19?

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#5588]
Yesterday in the dev call we discussed the need for another release. Not sure if this should be a bugfix release (i.e. v0.18.3) or a full release (i.e. v0.19). Last release (v0.18.2) was 19th May, with v0.18.0 on 6th May.

@pydata/xarray

Bug fixes:

- #5581 and the fix #5359 (this one needs to be released soon really)
- #5528
- Probably various smaller ones

New features:

- #4696
- #5514
- #5476
- #5464
- #5445

Internal:
- `master` -> `main` #5520
- #5506

Nice to merge first?:

- [x] #5568 and #5561
- [ ] #5571
- [x] #5586
- [ ] #5493
- [x] #4909
- [ ] #5580
- [ ] #4863
- [ ] #5501

**Comment by keewis** [comment]
> is there a way to tag only the core dev team?

as long as you're a member you can use @pydata/xarray

**Comment by dcherian** [comment]
There's a breaking change so it should be 0.19.0: https://xarray.pydata.org/en/latest/whats-new.html

**Comment by keewis** [comment]
we were also wondering whether a renamed kwarg went through a deprecation cycle, but I can't find that PR. Has it been merged, yet?

**Comment by dcherian** [comment]
@keewis See #4696 . that whats-new note is in the wrong place which is why I couldn't find it yesterday

**Comment by keewis** [comment]
there are also a few deprecations scheduled for removal in `0.19`

**Comment by TomNicholas** [comment]
I know I volunteered to do this release, but some of the PRs I wanted to include have taken longer than I thought, and now I'm going to be away from a computer from tomorrow until near the end of next week.

Should we do the release soon anyway?

**Comment by dcherian** [comment]
> Should we do the release soon anyway?

Yes!

**Comment by max-sixty** [comment]
I basically think we should never wait for PRs, or spend time "rounding them up" before doing a release. Stuff is going to go in at some point, and exactly when doesn't matter as much as reducing the burden of doing releases. Indeed — even if we're only attempting to reduce the time between code merging and being released — we'd arguably reduce that more by forgoing this rounding up effort, making releases easier and more frequent.

The only argument I can see is that it's some "call to action" that helps motivate people to push something over the edge.

(but not super confident and realize I am maybe contra-consensus, so weigh appropriately)

**Comment by TomNicholas** [comment]
@max-sixty I think it somewhat depends on the intended purpose of the
release: new features or bug fixes? Here the primary motivation was a bug
fix so I agree with you in this case.

**Comment by shoyer** [comment]
I'd like to consider rolling back the addition of typing-extensions as a required dependency before issuing the release: https://github.com/pydata/xarray/issues/5495

**Comment by TomNicholas** [comment]
Is this just blocking on #5495? What did we decide to do there?

**Comment by tlvu** [comment]
Is it possible to make quick release of xarray?  Without a release containing PR https://github.com/pydata/xarray/pull/5359, we are forced to pin pandas below 1.3.0.  Thanks !

**Comment by dcherian** [comment]
Just merged the blocker. @TomNicholas we should be good to release.

**Comment by TomNicholas** [comment]
Good news everyone! The release is done.

**Comment by shoyer** [comment]
Thanks Tom and everyone else who helped out!
