### ISSUE TITLE
`xr.where()` does not work like `np.where()`on meshgrids

### ISSUE THREAD

**Issue by meteoDaniel** [pydata/xarray#5620]
In case of selecting 2D data, the `xarray.where()` does not work like `numpy.where()` . In the documentation you have mentioned that `np.where()`  is the corresponding function for `xr.where()` but it seems that they are working totally different. 

Here is my code: 

```python
data = xarray.open_dataset('path_to_attached_file')
minLat, minLon, maxLat, maxLon = (45.08903556483102, 5.625000000000013, 48.92249926375824, 11.249999999999993)
latitudes = data.lat.values
longitudes = data.lon.values
slice_mask = np.where(
        (latitudes <= maxLat)
        & (latitudes > minLat)
        & (longitudes <= maxLon)
        & (longitudes > minLon)
    )
_sliced_data = data.where(
    (data.lat <= maxLat)
    & (data.lat > minLat)
    & (data.lon <= maxLon)
    & (data.lon > minLon),
    drop=True,
)
_sliced_data.latitude.values.max()
# 49.305596
latitudes[slice_mask].max()
# 48.922172
``` 
I have also tried to translate the numpy result into a boolen DataArray:

```python
mask_array = data.copy()
mask_array.update({'air_temperature_2m': (("y", "x"), (latitudes <= maxLat)
        & (latitudes > minLat)
        & (longitudes <= maxLon)
        & (longitudes > minLon))})

_sliced_data = data.where(
    mask_array.air_temperature_2m,
    drop=True,
)

```
There we have the same result. It seems that the masking step does not really works correctly. 

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.1 (default, Feb  9 2021, 07:55:26) 
[GCC 8.3.0]
python-bits: 64
OS: Linux
OS-release: 5.10.0-1033-oem
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.12.0
libnetcdf: 4.7.4

xarray: 0.16.2
pandas: 1.2.1
numpy: 1.20.0
scipy: 1.6.0
netCDF4: 1.5.5.1
pydap: None
h5netcdf: 0.8.0
h5py: 3.2.1
Nio: None
zarr: None
cftime: 1.5.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.8.4
iris: None
bottleneck: None
dask: 2021.05.0
distributed: None
matplotlib: 3.3.4
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 53.0.0
pip: 21.0.1
conda: None
pytest: 6.1.1
IPython: 7.21.0
sphinx: None

</details>

[harmonie_knmi_grid_fixture.zip](https://github.com/pydata/xarray/files/6842196/harmonie_knmi_grid_fixture.zip)

**Comment by max-sixty** [comment]
Hi @meteoDaniel — please could you add a minimal example as per the link in the issue template?

**Comment by meteoDaniel** [comment]
@max-sixty I do not know what you want? You can download the file and I have copied all the code you need to run into this issue.

**Comment by max-sixty** [comment]
No stress — I know it can be unclear at first — but can you show the same result without requiring downloading data and with a smaller example? Here's the link in the issue template I was referred to: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by meteoDaniel** [comment]
@max-sixty it will take approx. 1 hour for me to slice the data and check out if the data runs into the issue, and for you it is 1 click and 1,8 MB of download.

I guess the problem is, that the coordinates are 2D and not 1D. My second example shows that it has more to do with masking than with the `where` function.

**Comment by meteoDaniel** [comment]
Btw.: I do not know where the problem is to use my example code and the attached file (1.8 MB). It took me 6 hours to find this bug, 30 min to create this issue and now I should provide a more tiny solution that took me +1 hour and safes you 1-2 minutes. This is not efficient.  I can recommend to read this book on this topic: [Lean Start Up](https://www.amazon.de/-/en/Eric-Ries/dp/0307887898).

**Comment by keewis** [comment]
@meteoDaniel, it ultimately comes down to how much time a maintainer is willing to spend on a single issue, with self-contained, small examples being much easier to debug (and there are a few other reasons in the blog post linked to by @max-sixty).

That said, I can reproduce your issue, which apparently is independent of the way the mask is constructed:
```python
mask = (
    (latitudes <= maxLat)
    & (latitudes > minLat)
    & (longitudes <= maxLon)
    & (longitudes > minLon)
)

ds.where(xr.DataArray(mask, dims=("y", "x")), drop=True).latitude.max()  # 49.30
latitudes[mask].max()  # 48.92
```

However, if I do
```python
subset = ds.latitude.where(xr.DataArray(mask, dims=("y", "x")), drop=True)
subset.max()
```
I get the same result as with pure `numpy`.

Interestingly, `xr.testing.assert_identical(subset, subset.latitude)` raises...

**Comment by keewis** [comment]
Actually, I can reproduce this with the example `"rasm"` dataset:
```python
In [2]: import xarray as xr
   ...: 
   ...: rasm = xr.tutorial.open_dataset("rasm").load()
   ...: 
   ...: min_lat = 17
   ...: max_lat = 18
   ...: min_lon = 189
   ...: max_lon = 190
   ...: 
   ...: mask = (
   ...:     (rasm.xc <= max_lon) & (rasm.xc > min_lon)
   ...:     & (rasm.yc <= max_lat) & (rasm.yc > min_lat)
   ...: )
   ...: 
   ...: subset = rasm.xc.where(mask, drop=True)
   ...: display(subset.max(), subset.xc.max())
   ...: display(subset, subset.xc)
<xarray.DataArray 'xc' ()>
array(189.89982737)
<xarray.DataArray 'xc' ()>
array(190.07286203)
<xarray.DataArray 'xc' (y: 3, x: 4)>
array([[189.55836619, 189.72833384, 189.89982737,          nan],
       [189.30253733, 189.47184886, 189.64270151, 189.81509531],
       [189.04515208, 189.21383799, 189.38403452,          nan]])
Coordinates:
    xc       (y, x) float64 189.6 189.7 189.9 190.1 ... 189.0 189.2 189.4 189.6
    yc       (y, x) float64 17.02 17.27 17.51 17.76 ... 17.34 17.59 17.84 18.08
Dimensions without coordinates: y, x
Attributes:
    long_name:  longitude of grid cell center
    units:      degrees_east
<xarray.DataArray 'xc' (y: 3, x: 4)>
array([[189.55836619, 189.72833384, 189.89982737, 190.07286203],
       [189.30253733, 189.47184886, 189.64270151, 189.81509531],
       [189.04515208, 189.21383799, 189.38403452, 189.55578745]])
Coordinates:
    xc       (y, x) float64 189.6 189.7 189.9 190.1 ... 189.0 189.2 189.4 189.6
    yc       (y, x) float64 17.02 17.27 17.51 17.76 ... 17.34 17.59 17.84 18.08
Dimensions without coordinates: y, x
Attributes:
    long_name:  longitude of grid cell center
    units:      degrees_east
```

which makes it pretty obvious why this fails: `drop=True` drops as much as possible, but to really drop everything we would have to return ragged arrays. To work around that, `.where` sets the data to `nan` where necessary, but only for data variables (as coordinates still need to reference the masked values).

**Comment by meteoDaniel** [comment]
@keewis thanks for your further explanation. 
In the mean time I have built a work-around because I recognized that xarray tries to keep the 2D arrays. nump reverts a 1D index array. 
Thanks
