### ISSUE TITLE
ValueError: unrecognized engine cfgrib must be one of: ['netcdf4', 'scipy', 'store'] while opening grib data

### ISSUE THREAD

**Issue by krishnaap** [pydata/xarray#5623]
I could read grib2 files using xarray and cfgrib before with the same code on another PC. 

```
import xarray as xr
import cfgrib
ds = xr.open_dataset('/home//dataset.grib',engine='cfgrib')


```
but it is showing an error in the current system as follows

> ValueError: unrecognized engine cfgrib must be one of: ['netcdf4', 'scipy', 'store']

> Traceback (most recent call last):
> 
>   File "/home/Grib_task3.py", line 11, in <module>
>     ds = xr.open_dataset('/home/dataset.grib',engine='cfgrib')
> 
>   File "/home/krishna/anaconda3/envs/ide/lib/python3.9/site-packages/xarray/backends/api.py", line 482, in open_dataset
>     backend = plugins.get_backend(engine)
> 
>   File "/home/krishna/anaconda3/envs/ide/lib/python3.9/site-packages/xarray/backends/plugins.py", line 134, in get_backend
>     raise ValueError(
> 
> ValueError: unrecognized engine cfgrib must be one of: ['netcdf4', 'scipy', 'store']

**Environment**: ide

xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 5.8.0-59-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_IN
LOCALE: ('en_IN', 'ISO8859-1')
libhdf5: 1.10.6
libnetcdf: 4.8.0

xarray: 0.18.2
pandas: 1.2.5
numpy: 1.20.2
scipy: 1.7.0
netCDF4: 1.5.7
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.9.0
iris: None
bottleneck: 1.3.2
dask: 2021.06.2
distributed: 2021.06.2
matplotlib: 3.4.2
cartopy: 0.19.0.post1
seaborn: None
numbagg: None
pint: 0.17
setuptools: 52.0.0.post20210125
pip: 21.1.3
conda: None
pytest: None
IPython: 7.22.0
sphinx: 3.2.1

**Comment by keewis** [comment]
that's usually because of an `ImportError` for `cfgrib`. Does `import cfgrib` succeed for you?

**Comment by krishnaap** [comment]
@keewis Yes, importing cfgrib working just fine.

**Comment by krishnaap** [comment]
I tried to run the same thing in jupyter-notebook, on jupyter-notebook it's working fine. I previously tried on Spyder IDE with the same conda environment. Is it an issue with Spyder? Anyway, I can open it on Jupyter-notebook.

**Comment by keewis** [comment]
closing as a environment issue
