### ISSUE TITLE
Add 'construct' method to Coarsen objects

### ISSUE THREAD

**Issue by ACHMartin** [pydata/xarray#5625]
**Is your feature request related to a problem? Please describe.**

Similarly to the 'construct' method for Rolling objects, I think it will make sense to have the same for Coarsen objects.

My use will be for my da:
da(lon, lat, time) of dimension (2000, 1600, 240)
I wish to coarsen the data by a factor 4 in lon and lat (Lon and Lat), but wish to keep the data in a new dimension, it would be:
da(Lon, Lat, time, samples) of dim (500, 400, 240, 16)

my aim is to do da.median(dim=['time','samples'])

**Describe the solution you'd like**

da.coarsen(lon=4, lat=4, , boundary="trim").construct('samples')

**Describe alternatives you've considered**

I am using Rolling objects, but it increases the size of the matrix.

Many thanks for your work

**Comment by dcherian** [comment]
=) This is implemented on the main branch and will be released soon. See #5476
