### ISSUE TITLE
Issue on page /generated/xarray.open_rasterio.html

### ISSUE THREAD

**Issue by gabrieldernbach** [pydata/xarray#5637]
After some modifications I would like to write my xarray back to tif. However I couldn't find `xarray.write_rasterio`. What is the recommended way to go here?

**Comment by keewis** [comment]
have a look at `rioxarray`, especially [`Dataset.rio.to_raster`](https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray-rio-accessors), for this. If that's not what you're looking for, or if you need help with it, I would try asking on their issue tracker / discussions.
