### ISSUE TITLE
Best way to find data variables by standard_name

### ISSUE THREAD

**Issue by rsignell-usgs** [pydata/xarray#567]
Is there a way to return the data variables that match a specified `standard_name`?

I came up with this, but maybe the functionality already exists or there is a better way.

```
def get_std_name_vars(ds,std_name):
    return {k: v for k, v in ds.data_vars.iteritems() if 'standard_name' in v.attrs.keys() and std_name in v.standard_name}
```
as in this example: 
http://nbviewer.ipython.org/gist/rsignell-usgs/5b263906e92ce47bf05e

**Comment by shoyer** [comment]
I would probably make this return an xray.Dataset object instead of a plain dict, but otherwise this looks about right:
```python
def get_std_name_vars(ds,std_name):
    return ds[[k for k, v in ds.data_vars.iteritems() if 'standard_name' in v.attrs and std_name in v.standard_name]]
```

I don't think there's a better way to do this currently. Hypothetically, we could add this to a CF-specific API for xray, e.g., as discussed in #461.

**Comment by rsignell-usgs** [comment]
I was thinking that the data variables that matched a specified `standard_name` would be a subset of the variables in the `data_vars` object.

**Comment by ocefpaf** [comment]
How about the function below?  (Stolen from [pyaxiom](https://github.com/axiom-data-science/pyaxiom/blob/master/pyaxiom/netcdf/dataset.py#L10-L47).)

```python
def get_variables_by_attributes(ds, strict=False, **kwargs):
    """
    Returns variables that match specific conditions.
    * Can pass in key=value parameters and variables are returned that
      contain all of the matches.
      ex.:
          vs = nc.get_variables_by_attributes(axis='X')
    * Can pass in key=callable parameter and if the callable returns
      True.  The callable should accept a single parameter, the attribute
      value.  None is returned as the attribute valuewhen the attribute
      does not exist on the variable.
      ex.:
          # Get Axis variables
          vs = nc.get_variables_by_attributes(axis=lambda v: v in ['X', 'Y', 'Z', 'T'])
          # Get variable that don't have a "axis" attribute
          vs = nc.get_variables_by_attributes(axis=lambda v: v is None)
          # Get variable that have a "grid_mapping" attribute
          vs = nc.get_variables_by_attributes(axis=lambda v: v is not None)
    
    * strict : True/False
        If True will return only 1 variable if only one is found. Default is False.
    """
    vs = []

    has_value_flag  = False
    for vname, var in ds.iteritems():
        for k, v in kwargs.items():
            if callable(v):
                has_value_flag = v(getattr(var, k, None))
                if has_value_flag is False:
                    break
            elif hasattr(var, k) and getattr(var, k) == v:
                has_value_flag = True
            else:
                has_value_flag = False
                break

        if has_value_flag is True:
            vs.append(ds[vname])

    if strict:
        if len(vs) == 1:
            vs = vs[0]
        else:
            msg = "Expected only one variable.  Got {!r}".format
            raise ValueError(msg(vs))
    return vs
```

See it in action [here](http://nbviewer.ipython.org/gist/ocefpaf/1633cb2f61b61db35ad0).

**Comment by ocefpaf** [comment]
@shoyer this made into `netcdf4` and some people in my group would like to have this in `xarray` too. If you think it is worth it I can put a PR together for this.

**Comment by rsignell-usgs** [comment]
:+1:  -- I think this would be super-useful general functionality for the xarray community that doesn't come with any downside.

**Comment by shoyer** [comment]
`get_variables_by_attributes` does seem generic enough that we can safely add it to xarray. For our version, I would make this a Dataset method and always return another Dataset (no `strict` flag). Pulling out the single variable of a Dataset as a DataArray should be a separate method, e.g., `.item()` like the NumPy method.
