### ISSUE TITLE
Use of `force_to_top` for `isort`

### ISSUE THREAD

**Issue by jrbourbeau** [pydata/xarray#5675]
In https://github.com/dask/distributed/pull/5170, @fjetter pointed out that `distributed` was incorrectly using `force_to_top` in our `isort` configuration (we should have been using `float_to_top` instead). Just a minor point, but since `xarray`s `isort` configuration influenced what we did over in `dask` and `distributed`, I thought it was worth letting the Xarray devs know about it

https://github.com/pydata/xarray/blob/8f5b4a185b304ab68723c390b1ad88e57f9a60d6/setup.cfg#L164

**Comment by max-sixty** [comment]
Thanks @jrbourbeau , agree.

Would take a PR if anyone is up for a short one...
