### ISSUE TITLE
Do not require on pkg_resources as it drastically increases import time.

### ISSUE THREAD

**Issue by marscher** [pydata/xarray#5676]
**Is your feature request related to a problem? Please describe.**
Most of the import time of xarray is wasted by importing pkg_resources. As far as I could see, the module is used to set the version number of xarray. So importing xarray takes like 0.275s (old machine) and of this 0.17s are just spent in importing pkg_resources.

**Describe the solution you'd like**
There are better approaches to set the version number than to use this heavy weight module. For instance `setuptools_scm`.

**Describe alternatives you've considered**

**Additional context**
xarray-version 0.19.0

**Comment by benbovy** [comment]
> There are better approaches to set the version number than to use this heavy weight module. For instance setuptools_scm.

Looks like it is still required to [retrieve the version number at runtime](https://github.com/pypa/setuptools_scm#retrieving-package-version-at-runtime) for python version < 3.8, unless we agree to temporarily depend on the [importlib_metada](https://pypi.org/project/importlib-metadata/) backport.

> As far as I could see, the module is used to set the version number of xarray

It is also used for the backend entry-points and for loading a couple of static css/html files for the html reprs. I don't know if there are better approaches for this, though.

**Comment by keewis** [comment]
we had a lengthy discussion about a related topic in #4295. Long story short: we will be able to switch to `importlib.metadata` once we can drop support for `py37` (and we can already use `importlib.resources` for the CSS and HTML files, feel free to send in a PR for that).

For the backends, we could use the separate `entrypoints` library (which I believe is faster), but as far as I can tell we will only make that switch once we can drop the dependency on `pkg_resources` entirely.

For reference, [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) allows dropping support for `py37` after Dec 26.
