### ISSUE TITLE
DOC: remove suggestion to install pytest-xdist in docs

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#5679]
In http://xarray.pydata.org/en/stable/contributing.html#running-the-test-suite

The suggestion is 

> Using pytest-xdist, one can speed up local testing on multicore machines. To use this feature, you will need to install pytest-xdist via:
pip install pytest-xdist
Then, run pytest with the optional -n argument:
pytest xarray -n 4

pytest-xdist is in the environment (https://github.com/pydata/xarray/blob/main/ci/requirements/environment.yml#L39) no need to reinstall

**Comment by max-sixty** [comment]
Agree! 

It would actually be good to slim that page down; it could be focused on xarray-specific material and provide links to GitHub documentation, rather than explaining very general tasks, like how to make a commit... :)
