### ISSUE TITLE
Coerce the labels passed to Index.query to array-like objects

### ISSUE THREAD

**Issue by benbovy** [pydata/xarray#5697]
When looking at #5691 I noticed that the labels are sometimes coerced to arrays (i.e., #3153) but not always.

Later in `PandasIndex.query` those may again be coerced to arrays (i.e., `_as_array_tuplesafe`). In #5692 (https://github.com/pydata/xarray/pull/5692/commits/a551c7f05abf90a492fb59068b59ebb2bac8cb4c) they are always coerced to arrays before maybe be converted as scalars.

Shouldn't we therefore make things easier and ensure that the labels given to `xarray.Index.query()` always have an array interface? This would also yield a more predictable behavior to anyone who wants to implement custom xarray indexes.

**Comment by benbovy** [comment]
> In #5692 (a551c7f) they are always coerced to arrays before maybe be converted as scalars.

This is not exactly true: slices are kept as-is.

#3153 is actually a workaround specific to Pandas index limitations (only `float64` floating -point labels supported), so it would make sense to move this within `PandasIndex`.

Other use-cases like [xoak](https://github.com/xarray-contrib/xoak) point-wise indexing only support `Variable` or `DataArray` objects as indexers (to ensure that all indexers have the same dimensions).

So it would probably be better to leave indexers untouched and let `Index` objects do the validation and conversion.

**Comment by dcherian** [comment]
>  leave indexers untouched and let Index objects do the validation and conversion.

So does this mean custom indexes have to implement vectorized or pointwise indexing on their own?

**Comment by benbovy** [comment]
> So does this mean custom indexes have to implement vectorized or pointwise indexing on their own?

No I don't think so (sorry my thoughts are still confusing), we would still use the current implementation in Xarray for positional (vectorized, pointwise, etc.) indexing.

Currently label-based indexers go through these normalization steps before passing them to `Index.query`:

1. cast floating-point labels to coordinate dtype (`maybe_cast_to_coords_dtype()`)
2. convert `DataArray` objects to unlabelled data (via `.variable.data`)

The dimension (positional) indexers returned by `Index.query` may be also converted before passing them to `.isel`:

3. back to `Variable` or `DataArray` objects for advanced indexing

I think that `PandasIndex` should take care of 1. Casting floating-point labels (casting any object to a numpy array as a side effect) may be undesirable for other, custom indexes.

For 2 and 3, I'm not exactly sure what to do. We should probably avoid 2 since dimension labels are useful (e.g., it is used in `.xoak.sel`) and let the indexes handle that. This means that indexes should also handle 3. For pandas multi-indexes, this would allow us raising a more meaningful error message since they don't support `DataArray` or `Variable` objects as level indexers. It is also better to handle 2 and 3 in a per-case basis since a general solution for 3 is tricky with the new data model (non-dimensional indexes).

This means a lot of flexibility for custom indexes but also a great responsibility.
