### ISSUE TITLE
Show what options are enabled.

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#5698]
As far as I know, there's no way to see what options are enabled.

It'd be nice to add either `xr.get_options` or `xr.show_options` or `xr.options` so that users can see what is enabled.

I think it would be nice to have a one-line description under each option

```
"arithmetic_join": "outer"
    controls DataArray/Dataset alignment in binary operations.
```

**Comment by pkopparla** [comment]
Hello,

I'd like to take a crack at this, if no one else is already working on it. Would the idea be to use `xarray/xarray/core/options.py` as the template for options that can exist/ have been set and create a get method?

**Comment by dcherian** [comment]
Thanks @pkopparla 

Yes, the easiest would be to have a `get_method` that just returned the OPTIONS dict in `core/options.py`
