### ISSUE TITLE
Broken conda-forge release xarray-0.19.0-pyhd8ed1ab_0.tar.bz2 

### ISSUE THREAD

**Issue by kim-barker** [pydata/xarray#5711]
Bad release of [xarray-0.19.0](https://anaconda.org/conda-forge/xarray/0.19.0/download/noarch/xarray-0.19.0-pyhd8ed1ab_0.tar.bz2) is broken on conda-forge and resolving to py36 instead of py37.

This causes failure to import future annotations as below:
```
  File "/opt/conda/lib/python3.6/site-packages/xarray/core/computation.py", line 4
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined
```

This probably needs to be fixed via https://conda-forge.org/docs/maintainer/updating_pkgs.html#maint-fix-broken-packages

**Comment by keewis** [comment]
This should already have been fixed by conda-forge/xarray-feedstock#66 and conda-forge/conda-forge-repodata-patches-feedstock#161. Not sure why you still get the broken build? Any ideas, @dopplershift?

**Comment by mathause** [comment]
Are you trying to install xarray in a python 3.6 environment? We might have to mark it as broken.

**Comment by dopplershift** [comment]
The metadata for that package has been patched in conda-forge/conda-forge-repodata-patches-feedstock#161 to depend on `python >=3.7`, so this shouldn't be an issue any more. @kim-barker How are you installing xarray/setting up your environment? What `conda` commands are you running? What OS/platform architecture?

**Comment by max-sixty** [comment]
Closing, please reopen if still an issue
