### ISSUE TITLE
pandas deprecates Index.get_loc with method

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#5721]
pandas deprecates the `method` keyword in `Index.get_loc`, see pandas-dev/pandas#42269. Therefore we end up with about 5000 warnings in our upstream tests:

`FutureWarning: Passing method to Index.get_loc is deprecated and will raise in a future version. Use index.get_indexer([item], method=...) instead`

We should fix this before pandas releases because the warning will not be silent (`FutureWarning`) or ask pandas to give us more time and use a `DeprecationWarning` at the moment.

<details>

We use this here:

https://github.com/pydata/xarray/blob/4bb9d9c6df77137f05e85c7cc6508fe7a93dc0e4/xarray/core/indexes.py#L233-L235

Is this only ever called with one item? Then we might be able to use 

```python
 indexer = self.index.get_indexer( 
     [label_value], method=method, tolerance=tolerance 
 ).item()
if indexer == -1:
    raise KeyError(label_value)
```

---

https://github.com/pydata/xarray/blob/3956b73a7792f41e4410349f2c40b9a9a80decd2/xarray/core/missing.py#L571-L572
This one could be easy to fix (replace with `imin = index.get_indexer([minval], method="nearest").item()`)

---

It is also defined in `CFTimeIndex`, which complicates things:

https://github.com/pydata/xarray/blob/eea76733770be03e78a0834803291659136bca31/xarray/coding/cftimeindex.py#L461-L466

because `get_indexer` expects an iterable and thus the `if isinstance(key, str)` test no longer works.

</details>

@benbovy @spencerkclark

**Comment by spencerkclark** [comment]
Thanks for the heads up @mathause.  We'll need to think carefully about this with respect to partial datetime string indexing. `DatetimeIndex.get_indexer` and `DatetimeIndex.get_loc` behave differently with respect to datetime strings.  `get_indexer` interprets strings as specific dates, while `get_loc` interprets them as ranges:
```
>>> import pandas as pd
>>> times = pd.date_range("2000", periods=5)
>>> times.get_indexer(["2000"])
array([0])
>>> times.get_loc("2000")
slice(0, 5, None)
```
In other words -- at least for partial datetime string indexing -- it may not be as simple as swapping in `get_indexer` for `get_loc`.

Perhaps @jbrockmendel has thoughts on how we should approach this?

**Comment by shoyer** [comment]
These lines seem to be the problematic place?
https://github.com/pydata/xarray/blob/e26aec9500e04f3b926b248988b976dbfcb9c632/xarray/core/indexes.py#L233-L235

We might be able to do something like:
```python
if method is not None:
    indexer = get_indexer_nd(self.index, label, method, tolerance)
else:
    indexer = self.index.get_loc(label_value)
```

**Comment by spencerkclark** [comment]
Exactly, yeah, those are the problematic lines.  That's an elegant solution.  I think it will work with the minor modification to raise a `KeyError` if any of the indices returned by `get_indexer_nd` are less than zero:
```python
if method is not None:
    indexer = get_indexer_nd(self.index, label, method, tolerance)
    if np.any(indexer < 0):
        raise KeyError(f"not all values found in index {coord_name!r}")
else:
    indexer = self.index.get_loc(label_value)
```

**Comment by jbrockmendel** [comment]
The "if method is not None" approach seems reasonable.

**Comment by benbovy** [comment]
👍 I can take care of it in #5692 or in a separate PR.

**Comment by mathause** [comment]
> 👍 I can take care of it in #5692 or in a separate PR.

I don't have a strong opinion but would be good to do this before the next release.

**Comment by benbovy** [comment]
Not sure that #5692 will be ready for the next release so I'll do this in a separate PR.
