### ISSUE TITLE
1D line plot with data on the x axis

### ISSUE THREAD

**Issue by rabernat** [pydata/xarray#575]
Consider the following Dataset, representing a function f = cos(z)

``` python
z = np.arange(10)
ds = xray.Dataset( {'f': ('z', np.cos(z))}, coords={'z': z})
```

If I call

``` python
ds.f.plot()
```

xray naturally puts "z" on the x-axis.

However, since z represents the vertical dimension, it would be more natural do put it on the y-axis, i.e. 

``` python
plt.plot(ds.f, ds.z)
```

This is conventional in atmospheric science and oceanography for buoy data or balloon data.

Is there an easy way to do this with xray's plotting functions? I scanned the code and didn't see an obvious solution, but maybe I missed it.

**Comment by shoyer** [comment]
I don't think we have an easy way to do this now.

Seaborn uses the keyword argument `orient='h'` or `orient='v'` to control orientation for categorical plots like [`violinplot`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.violinplot.html#seaborn.violinplot). That might be a reasonable API to emulate here.

**Comment by clarkfitzg** [comment]
Not possible now. Wouldn't be much trouble to add it though. @drewokane has been working on generalizing the 1d plotting in #566. This might be a nice thing to include.

**Comment by drewokane** [comment]
I agree `orient` would be a natural keyword to use for this situation.

**Comment by rabernat** [comment]
Yes, :+1: ``orient``.

**Comment by jhamman** [comment]
I'm fine with `orient={h, v}` but I will offer a few other alternatives.

- *Explicit is better than implicit.* I know what `h` and `v` mean but it is more explicit to say `horizontal` or `vertical`.  These keywords also require less in terms of documentation.
- Can we only imagine two options for the orientation?  If so, maybe a `True/False` keyword is a better way to go (`orient_horizontal=True`)? Maybe not?

I'm not married to either of the opinions I just mentioned, just a few thoughts.

**Comment by kuchaale** [comment]
Would it make sense to have such minimalisti `line` function:
`def line(darray, orient_horizontal = True, *args, **kwargs):
    """
    Line plot of 1 dimensional DataArray index against values
    Wraps matplotlib.pyplot.plot
    Parameters
    ----------
    darray : DataArray
        Must be 1 dimensional
    figsize : tuple, optional
        A tuple (width, height) of the figure in inches.
        Mutually exclusive with ``size`` and ``ax``.
    aspect : scalar, optional
        Aspect ratio of plot, so that ``aspect * size`` gives the width in
        inches. Only used if a ``size`` is provided.
    size : scalar, optional
        If provided, create a new figure for the plot with the given size.
        Height (in inches) of each plot. See also: ``aspect``.
    ax : matplotlib axes object, optional
        Axis on which to plot this figure. By default, use the current axis.
        Mutually exclusive with ``size`` and ``figsize``.
    *args, **kwargs : optional
        Additional arguments to matplotlib.pyplot.plot
    """
    #plt = import_matplotlib_pyplot()

    ndims = len(darray.dims)
    if ndims != 1:
        raise ValueError('Line plots are for 1 dimensional DataArrays. '
                         'Passed DataArray has {ndims} '
                         'dimensions'.format(ndims=ndims))

    # Ensures consistency with .plot method
    figsize = kwargs.pop('figsize', None)
    aspect = kwargs.pop('aspect', None)
    size = kwargs.pop('size', None)
    ax = kwargs.pop('ax', None)

    ax = get_axis(figsize, size, aspect, ax)

    xlabel, = darray.dims
    x = darray.coords[xlabel]    

    _ensure_plottable(x)
    
    if x.attrs['units'] is not None:
        units_str = ' [{}]'.format(x.attrs['units'])
    else:
        units_str = ''
    
    if orient_horizontal:
        primitive = ax.plot(x, darray, *args, **kwargs)
        ax.set_xlabel(xlabel+units_str)
    else:
        primitive = ax.plot(darray, x, *args, **kwargs)
        ax.set_ylabel(xlabel+units_str)
    
    ax.set_title(darray._title_for_slice())

    if darray.name is not None:
        if orient_horizontal:
            ax.set_ylabel(darray.name)
        else:
            ax.set_xlabel(darray.name)

    # Rotate dates on xlabels
    if np.issubdtype(x.dtype, np.datetime64):
        if orient_horizontal:
            plt.gcf().autofmt_xdate()
       
    return primitive`

**Comment by shoyer** [comment]
I wonder if it makes more sense to make `.plot()` a Dataset method as well, so we could write things like `ds.plot.line(x='f', y='z')` and `ds.plot.scatter(x='f', y='z')`. Writing `ds.f.plot(orient='h')` is much less self-explanatory.

**Comment by fmaussion** [comment]
In a first step at least, we could add the `x` and `y` arguments to the ``line`` plot method to make the API consistent with the 2d plot methods (http://xarray.pydata.org/en/latest/api.html#plotting). But now that I think of it, they should be kwargs, not args

> I wonder if it makes more sense to make .plot() a Dataset method as well

Yes. This might be a bit of an undertaking as there will be several possible cases to handle but this is a good idea!

**Comment by shoyer** [comment]
> In a first step at least, we could add the x and y arguments to the line plot method to make the API consistent with the 2d plot methods

If an argument is a 1D DataArray, how do we indicate this array's data? The best I can think of is to use some sort of sentinel value, maybe `None`: `df.f.plot(x=None, y='z')`

**Comment by kuchaale** [comment]
I think plotting two 1D variables from one Dataset against each other may be useful. However, I was not able to figure out yet how to proceed with it (see my amateur PR).

**Comment by dcherian** [comment]
@kuchaale  I see you have an open PR. Are you planning to revisit this soon? If not, I'd like to build off what you started and tackle this bit (not the Dataset method)

> In a first step at least, we could add the x and y arguments to the line plot method to make the API consistent with the 2d plot methods (http://xarray.pydata.org/en/latest/api.html#plotting).

**Comment by kuchaale** [comment]
@dcherian go ahead. I planned to revisit it, but it would not be definitely soon.

**Comment by dcherian** [comment]
@kuchaale Thanks!
