### ISSUE TITLE
define fill value for where

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#576]
It would be nice if `where` accepts an `other` argument:

```
def where(self, cond, other=np.NaN):
    pass
```

**Comment by shoyer** [comment]
Agreed. I didn't add this only because we don't yet have three-argument broadcasting operations working yet.

For now, a work around (at a slight cost in efficiency) is to use `where` followed by `fillna`.

**Comment by MaximilianR** [comment]
This would be great to add - we just hit this (CC @justinkuosixty). 

>For now, a work around (at a slight cost in efficiency) is to use where followed by fillna.

This works, although if there are already `NaN`s, it requires another `where` to add those back

**Comment by jhamman** [comment]
@shoyer - what do we need in order to get the 3-argument broadcasting working. I'd really like to get this into xarray.

**Comment by shoyer** [comment]
It should already work with apply_ufunc -- we just need to adjust where to
use it. Take a look at the latest version of fillna for an example.
