### ISSUE TITLE
wrap lon coordinates to 360

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#577]
Assume I have two datasets with the same lat/ lon grid. However, one has `lon = 0...359`and the other `lon = -180...179`. How can I wrap around one of them?

**Comment by mathause** [comment]
I found a way, leaving this here for reference. Or is there something better?

    def wrap360(ds, lon='lon'):
        """
        wrap longitude coordinates to 0..360

        Parameters
        ----------
        ds : Dataset
            object with longitude coordinates
        lon : string
            name of the longitude ('lon', 'longitude', ...)

        Returns
        -------
        wrapped : Dataset
            Another dataset array wrapped around.
        """

        # wrap -180..179 to 0..359    
        ds.coords[lon] = np.mod(ds[lon], 360)
        
        # sort the data
        return ds.reindex({ lon : np.sort(ds[lon])})

**Comment by shoyer** [comment]
Yes, this is similar to how I've done this in the past. Your function works fine, but I would probably use `ds = ds.assign(**{lon: mod(ds[lon], 360})` to avoid modifying the existing coordinates in-place.

Also, it would be nice if we supported `ds.sort_index(lon)` instead of requiring an explicit reindex.

**Comment by max-sixty** [comment]
Closing as stale, please reopen if still relevant

(Does `.roll` do this now?)

**Comment by mathause** [comment]
I don't think `.roll` actually handles this, as wrapping changes the coordinate values. But as xarray does not support domain-specific it's good to close this.
