### ISSUE TITLE
Custom Backend Implementation - Error in Documentation? 

### ISSUE THREAD

**Issue by JoOtto** [pydata/xarray#5777]
Hi guys,

thanks for the nice package!
I have some issues getting a custom backend implementation running. I started with the code given in the [documentation](http://xarray.pydata.org/en/stable/internals/how-to-add-new-backend.html) as
```python
from xarray.backends import BackendEntrypoint
class MyBackendEntrypoint(BackendEntrypoint):
    def open_dataset(
        filename_or_obj,
        *,
        drop_variables=None,
        # other backend specific keyword arguments
        # `chunks` and `cache` DO NOT go here, they are handled by xarray
    ):
        return my_open_dataset(filename_or_obj, drop_variables=drop_variables)`
```
However, I think in the function definition, the argument `self` is missing in the documentation. It could be, that I'm wrong - my assumption is based on two things:

1. How the backend is called in `backends\api.py`  in the definition of `open_dataset`:
```python
backend = plugins.get_backend(engine)
# some other code
backend_ds = backend.open_dataset(
        filename_or_obj,
        drop_variables=drop_variables,
        **decoders,
        **kwargs,
    )
```
which suggest to me, that in the function definition of open_dataset in my own backend `self` needs to be included.

2. In your own backend, you also use `self` as for example in `backends/netCDF4_.py` 
```python
def open_dataset(
        self,
        filename_or_obj,
        #..,many other arguments
    ):`
```
Did I miss something?

Thanks

Johannes

**Comment by keewis** [comment]
we removed this in #5532 because it seemed to break something. cc @Illviljan 

Does it work for you if you add `self`? Also, what version of `xarray` are you using?

**Comment by JoOtto** [comment]
In my example I was on 0.18.2. I now upgraded to 0.19.0 `(xarray.__version__` returns `'0.19.0'`). However, I'm afraid that I still have the issue. It works, when I add `self`. :)

**Comment by keewis** [comment]
great, thanks. The base class also has the `self` (which I guess makes sense because you're supposed to be able to access the `open_dataset_parameters` attribute), so I'd say this is a documentation bug.

It seems the backend entrypoints are handled differently when passing them to the `engine` parameter of e.g. `open_dataset`, which I think is a bug we should fix, in addition to rolling back the documentation change. Out of curiosity (if you have the time): does it still work if you pass the class as `open_dataset(..., engine=MyBackendEntrypoint)`?

**Comment by kmuehlbauer** [comment]
@keewis I'm using it with `self` in my `BackendEntrypoint` subclasses, too. 

The below works 

```python
import xarray as xr
import numpy as np
expected = xr.Dataset(
    dict(a=2 * np.arange(5)), coords=dict(x=("x", np.arange(5), dict(units="s")))
)

from xarray.backends.common import BACKEND_ENTRYPOINTS

class CustomBackend(xr.backends.BackendEntrypoint):
    available = True
    def open_dataset(
        self,
        filename_or_obj,
        *,
        drop_variables=None,
    ):
        return expected.copy(deep=True)

BACKEND_ENTRYPOINTS["mybackend"] = CustomBackend
    
xr.open_dataset("fake_filename", engine="mybackend")
```

A good example is the internal `StoreBackendEntrypoint`.

**Comment by keewis** [comment]
thanks for the example, with that I can confirm that
```python
BACKEND_ENTRYPOINTS["mybackend"] = CustomBackend

xr.open_dataset("fake_filename", engine="mybackend")
```
works but
```python
xr.open_dataset("fake", engine=CustomBackend)
```
doesn't. We also already have a open PR to fix that: #5684.

So as a summary: yes, the `self` is necessary and we should update the documentation, and passing entrypoint classes directly should work once we merge the PR mentioned above.

**Comment by keewis** [comment]
#5778 should fix the documentation

**Comment by JoOtto** [comment]
Thanks guys!
