### ISSUE TITLE
Issue on page /user-guide/dask.html

### ISSUE THREAD

**Issue by rmcsqrd** [pydata/xarray#5810]
At http://xarray.pydata.org/en/stable/user-guide/dask.html the link to the [Pangeo project’s use-cases](http://pangeo.io/use_cases/index.html) is dead. I looked at Pangeo's website and I think that they moved the use-cases section to the [Gallery](http://gallery.pangeo.io/) (which does have a dask section).

I'm opening an issue to confirm that this link should be pointing to the Pangeo gallery page. If this is correct I can submit a PR with an updated link.

**Comment by dcherian** [comment]
A PR  is very welcome. Thank you!
