### ISSUE TITLE
Confusing assertion message when comparing datasets with differing coordinates

### ISSUE THREAD

**Issue by benbovy** [pydata/xarray#5814]
**What happened**:
When two datasets `a` and `b` have only differing coordinates, `xr.testing.assert_*` may output a confusing message that also reports differing data variables (although strictly equal/identical) sharing common dimensions with those differing coordinates. I guess it is because when comparing the data variables we compare `DataArray` objects (thus including the coordinates).

**What you expected to happen**:
An output assertion error message that shows only the differing coordinates.

**Minimal Complete Verifiable Example**:

```python
>>> import xarray as xr
>>> a = xr.Dataset(data_vars={"var": ("x", [10.0, 11.0])}, coords={"x": [0, 1]})
>>> b = xr.Dataset(data_vars={"var": ("x", [10.0, 11.0])}, coords={"x": [2, 3]})
>>> xr.testing.assert_equal(a, b)
```
```
AssertionError: Left and right Dataset objects are not equal

Differing coordinates:
L * x        (x) int64 0 1
R * x        (x) int64 2 3
Differing data variables:
L   var      (x) float64 10.0 11.0
R   var      (x) float64 10.0 11.0
```

I would rather expect:

```python
>>> xr.testing.assert_equal(a, b)
```
```
AssertionError: Left and right Dataset objects are not equal

Differing coordinates:
L * x        (x) int64 0 1
R * x        (x) int64 2 3
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15) 
[Clang 11.1.0 ]
python-bits: 64
OS: Darwin
OS-release: 20.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: (None, 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.19.1.dev72+ga8d84c703.d20210901
pandas: 1.3.2
numpy: 1.21.2
scipy: 1.7.1
netCDF4: 1.5.6
pydap: installed
h5netcdf: 0.8.1
h5py: 3.3.0
Nio: None
zarr: 2.6.1
cftime: 1.5.0
nc_time_axis: 1.2.0
PseudoNetCDF: installed
rasterio: 1.2.1
cfgrib: 0.9.8.5
iris: 3.0.4
bottleneck: 1.3.2
dask: 2021.01.1
distributed: 2021.01.1
matplotlib: 3.4.3
cartopy: 0.18.0
seaborn: 0.11.1
numbagg: None
fsspec: 0.8.5
cupy: None
pint: 0.16.1
sparse: 0.11.2
setuptools: 57.4.0
pip: 20.2.4
conda: None
pytest: 6.2.5
IPython: 7.27.0
sphinx: 3.3.1

</details>

**Comment by kmuehlbauer** [comment]
@benbovy I've stumbled over this every once in a while. Currently I'm just dropping the known "bad" coordinates before comparison.

**Comment by dcherian** [comment]
Fixed on main

```
AssertionError: Left and right Dataset objects are not equal

Differing coordinates:
L * x        (x) int64 16B 0 1
R * x        (x) int64 16B 2 3
```
