### ISSUE TITLE
Inconsistent dropping of `DatetimeIndex.freq` attribute from `DataArray`s index.

### ISSUE THREAD

**Issue by hrzn** [pydata/xarray#5815]
**What happened**:

Indexing on `DataArray`s sometimes produce inconsistent behaviors on `DataArray`s indexed with a `DatetimeIndex`.
There are cases (see code below) where copied versions of the array obtained with `DataArray.copy()` loose the index's `freq` attribute when calling `isel()`, whereas copied versions obtained using `DataArray.sortby()` do not.

**What you expected to happen**:

I would expect the `freq` not to be dropped from the axis when indexing the `DataArray`. Or at least, if it is dropped, it should _always_ be dropped, and not depend on how the `DataArray` has been obtained (i.e., it should not depend on whether it's a `copy()` of another array).

**Minimal Complete Verifiable Example**:

```python
import xarray as xr
import pandas as pd
import numpy as np
from pandas.tseries.frequencies import to_offset

freq = to_offset('MS')
time_index = pd.DatetimeIndex([pd.Timestamp('20130101') + i * freq for i in range(10)])

xa_orig = xr.DataArray(np.random.randn(10), 
                       dims=('time'), 
                       coords={'time': time_index})

xa_copy = xa_orig.copy()

xa_sorted = xa_orig.sortby('time')

# Set freq on all DataArrays:
xa_orig.get_index('time').freq = freq
xa_copy.get_index('time').freq = freq
xa_sorted.get_index('time').freq = freq

# Print to confirm the freq is set correctly:
print(xa_orig.get_index('time').freq)
print(xa_copy.get_index('time').freq)
print(xa_sorted.get_index('time').freq)
```

Output (OK - as expected)
```
> <MonthBegin>
> <MonthBegin>
> <MonthBegin>
```

Now, try some indexing using `isel()` on slices:
```python
print(xa_orig.isel({'time': slice(0, 5, None)}).get_index('time').freq)
print(xa_copy.isel({'time': slice(0, 5, None)}).get_index('time').freq)  # freq is dropped!
print(xa_sorted.isel({'time': slice(0, 5, None)}).get_index('time').freq)
```

Output (Not as expected: `freq` is dropped inconsistently, only on the _copied_ DataArray)
```
> <MonthBegin>
> None
> <MonthBegin>
```

Now, try the same using `isel()` on lists:
```python
print(xa_orig.isel({'time': [0, 1, 2, 3, 4]}).get_index('time').freq)
print(xa_copy.isel({'time': [0, 1, 2, 3, 4]}).get_index('time').freq)
print(xa_sorted.isel({'time': [0, 1, 2, 3, 4]}).get_index('time').freq)
```

Output (Not as expected: `freq` always dropped)
```
> None
> None
> None
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]
python-bits: 64
OS: Darwin
OS-release: 20.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: (None, 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 0.19.0
pandas: 1.2.3
numpy: 1.19.5
scipy: 1.6.2
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.4.1
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20200814
pip: 21.1.3
conda: None
pytest: None
IPython: 7.22.0
sphinx: 3.2.1

</details>

**Comment by benbovy** [comment]
This is the behavior that we get when directly indexing the `pandas.DatetimeIndex`:

```python
>>> idx = xa_orig.get_index('time')
>>> idx
DatetimeIndex(['2013-01-01', '2013-02-01', '2013-03-01', '2013-04-01',
               '2013-05-01', '2013-06-01', '2013-07-01', '2013-08-01',
               '2013-09-01', '2013-10-01'],
              dtype='datetime64[ns]', name='time', freq='MS')
>>> idx[0:2]       # slice of ints -> preserve freq
DatetimeIndex(['2013-01-01', '2013-02-01'], dtype='datetime64[ns]', name='time', freq='MS')
>>> idx[[0, 1]]    # list of ints ->  drop freq
DatetimeIndex(['2013-01-01', '2013-02-01'], dtype='datetime64[ns]', name='time', freq=None)
```

I think that this behavior makes sense since indexing the index with an arbitrary list of integer positions may not yield labels with a meaningful, unique frequency. With a slice it can be updated easily (pandas does it), e.g.,

```python
>>> idx[0:2:4]
DatetimeIndex(['2013-01-01'], dtype='datetime64[ns]', name='time', freq='4MS')
```

Not sure what's happening with the copy of the DataArray, though.

**Comment by benbovy** [comment]
Beware when you set index attributes in place like `xa_copy.get_index('time').freq = freq`. Currently, Xarray internals are such that depending on how you access the index it may return distinct (although intially identical) objects, e.g.,

```python
>>> xa_copy.get_index('time').freq = freq
>>> xa_copy._indexes['time'].index         # freq set here
DatetimeIndex(['2013-01-01', '2013-02-01', '2013-03-01', '2013-04-01',
               '2013-05-01', '2013-06-01', '2013-07-01', '2013-08-01',
               '2013-09-01', '2013-10-01'],
              dtype='datetime64[ns]', name='time', freq='MS')
>>> xa_copy._coords['time']._data.array    # freq not set here
DatetimeIndex(['2013-01-01', '2013-02-01', '2013-03-01', '2013-04-01',
               '2013-05-01', '2013-06-01', '2013-07-01', '2013-08-01',
               '2013-09-01', '2013-10-01'],
              dtype='datetime64[ns]', name='time', freq=None)
>>> xa_copy._coords['time']._data.array is xa_copy._indexes['time'].index
False
```

Hopefully, this will become less likely after the ongoing explicit index refactor in Xarray. But in general I would not advise changing in-place pandas indexes that are already bound to xarray objects. In your example it is safer to set `freq` when creating `time_index`.

**Comment by benbovy** [comment]
> In your example it is safer to set freq when creating time_index.

Hmm `time_index.freq` seem to be ignored when passing the index to the DataArray constructor. We should probably fix that.

**Comment by hrzn** [comment]
Yes this is a good point. In fact I'm not really willing to change the index in place, but I'm doing so because I've observed that the `freq` attribute of the index is dropped after sorting the array (see: https://github.com/pydata/xarray/issues/5466), so I use this hack to restore it.

Btw, we have recently switched to using `DataArray` as the core data structure underlying the `TimeSeries` class of Darts (https://github.com/unit8co/darts/), and it's working great for us. Thanks a lot for this super nice lib :)

**Comment by dcherian** [comment]
> we have recently switched to using DataArray as the core data structure underlying the TimeSeries class of Darts (unit8co/darts)

We'd be happy to add this to https://xarray.pydata.org/en/stable/ecosystem.html if you can send in a PR!

**Comment by hrzn** [comment]
> > we have recently switched to using DataArray as the core data structure underlying the TimeSeries class of Darts (unit8co/darts)
> 
> We'd be happy to add this to https://xarray.pydata.org/en/stable/ecosystem.html if you can send in a PR!

Done! https://github.com/pydata/xarray/pull/5819
Thanks.

**Comment by benbovy** [comment]
@hrzn I'm going to close this issue as I checked your example with the last release v2023.08.0 and the results are now consistent (using slices `freq` is not dropped even on the copied DataArray and using lists `freq` is always dropped like with pandas).

Feel free to re-open it if the problem persists.
