### ISSUE TITLE
to_zarr returns <xarray.backends.zarr.ZarrStore at ...>

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#5836]
**What happened**:

When doing to zarr it returns `<xarray.backends.zarr.ZarrStore at ...>`

**What you expected to happen**:

Returns None. Same behaviour as pandas.to_parquet()

**Minimal Complete Verifiable Example**:

```python
import xarray as xr

ds = xr.tutorial.open_dataset("air_temperature")
ds.to_zarr("ds.zarr")

ds.to_dataframe().to_parquet("ds.parquet")
```

<img width="492" alt="Screen Shot 2021-10-01 at 9 52 31 PM" src="https://user-images.githubusercontent.com/17162724/135700198-13c0942b-a606-4a3a-b2a9-314d954dfbec.png">

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 | packaged by conda-forge | (default, Sep 23 2021, 07:31:23) 
[Clang 11.1.0 ]
python-bits: 64
OS: Darwin
OS-release: 20.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.8.0

xarray: 0.19.0
pandas: 1.3.3
numpy: 1.21.2
scipy: 1.7.1
netCDF4: 1.5.7
pydap: installed
h5netcdf: 0.11.0
h5py: 3.3.0
Nio: None
zarr: 2.10.0
cftime: 1.5.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.6
cfgrib: 0.9.9.0
iris: None
bottleneck: 1.3.2
dask: 2021.09.1
distributed: 2021.09.1
matplotlib: 3.4.3
cartopy: 0.20.0
seaborn: 0.11.2
numbagg: None
pint: 0.17
setuptools: 58.0.2
pip: 21.2.4
conda: None
pytest: 6.2.5
IPython: 7.27.0
sphinx: None

</details>

**Comment by raybellwaves** [comment]
I see this is probably intentional

https://github.com/pydata/xarray/blob/main/xarray/backends/api.py#L1436

**Comment by headtr1ck** [comment]
This is indeed intentional (Now with type hints even more obvious).
I agree that in a jupyter notebook that automatically displays the last return value, this might look confusing.
