### ISSUE TITLE
AttributeError when importing xarray

### ISSUE THREAD

**Issue by NBloemendaal** [pydata/xarray#5837]
Hi all, 

I am trying to import xarray (import xarray as xr) in a script that up until now worked like a charm. But since this morning I've been getting the following error:

AttributeError: type object '_yaml.Mark' has no attribute '__reduce_cython__' 

I have xarray version 0.19.0 installed. 

Following some suggestions on internet, I tried updating cython to version 0.29.24 but that has not resolved the issue.

**Comment by TomNicholas** [comment]
Hi @NBloemendaal - it would be helpful to know the wider python environment you are using - can you show us the output of `conda list`? (If you're using conda?)

**Comment by NBloemendaal** [comment]
Hi @TomNicholas, sure! I have added the list in the attached excel sheet, it was a bit too much to simply copy-paste. 

[conda_list_Bloemendaal.xlsx](https://github.com/pydata/xarray/files/7278462/conda_list_Bloemendaal.xlsx)

**Comment by shoyer** [comment]
can you share the full traceback you see with the error?

**Comment by NBloemendaal** [comment]
Hi @shoyer and @TomNicholas I tried xarray again this morning and now it seems to work fine again ... I hope it stays this way! Apologies for the fuss!
