### ISSUE TITLE
Release v0.20?

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#5889]
We should do another release soon. The last one was v0.19 on July 23rd, so it's been 3 months.

(In particular I personally want to get some small pint compatibility fixes released such as https://github.com/pydata/xarray/pull/5571 and https://github.com/pydata/xarray/pull/5886, so that the code in [this blog post](https://github.com/xarray-contrib/pint-xarray/pull/142) advertising pint-xarray integration all works.)

There's been plenty of changes since then, and there are more we could merge quite quickly. It's a breaking release because we changed some dependencies, so should be called `v0.20.0`.

@benbovy how does the ongoing index refactor stuff affect this release? Do we need to wait so it can all be announced? Can we release with merged index refactor stuff just silently sitting there? 

Small additions we could merge, feel free to suggest more @pydata/xarray :
- https://github.com/pydata/xarray/pull/5834
- https://github.com/pydata/xarray/pull/5662
- #5233
- #5900
- #5365
- #5845
- #5904
- #5911 
- #5905
- #5847
- #5916

**Comment by keewis** [comment]
do we know where the failures in #5919 are coming from? It would probably be good to fix those before the release...

**Comment by TomNicholas** [comment]
> Update the docs. Login to https://readthedocs.org/projects/xray/versions/ and switch your new release tag (at the bottom) from "Inactive" to "Active". It should now build automatically.

I did all the other steps, but I don't see the v0.20.0 release tag on readthedocs :confused: 

I cancelled [a workflow that I thought was superfluous](https://github.com/pydata/xarray/actions/runs/1413422184) - was it actually needed?

**Comment by dcherian** [comment]
I see it. Activating...

**Comment by TomNicholas** [comment]
Oh I see it now too.

Are we done then? Is `v0.20.0` supposed to appear in the dropdown menu in the lower-right of the [main docs page](http://xarray.pydata.org/en/stable/)?
