### ISSUE TITLE
Add a method .shift() for shifting coordinate labels

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#590]
This would be useful as a preprocessing step for building predictive models.

**Comment by MaximilianR** [comment]
Is the current implementation enough to close this?

Current implementation doesn't create new space on indexes that can be extended (such as DTI / PI), but otherwise is similar to pandas. And not sure if it works on 2D coords

**Comment by shoyer** [comment]
Yeah, let's close this. I no longer remember exactly what I was thinking of here and in any case this was before we had the `.shift` method.
