### ISSUE TITLE
Spurious lines of the pcolormesh example

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#5901]
**What happened**:
The [example](http://xarray.pydata.org/en/stable/examples/multidimensional-coords.html) of plotting data using pcolormesh has some spurious lines:
![image](https://user-images.githubusercontent.com/30388627/139136728-3873cb79-6fb9-416b-87b5-fa9a61b1b169.png)

**What you expected to happen**:
No spurious lines.

**Minimal Complete Verifiable Example**:

```python
%matplotlib inline
import numpy as np
import pandas as pd
import xarray as xr
import cartopy.crs as ccrs
from matplotlib import pyplot as plt

ds = xr.tutorial.open_dataset('rasm').load()

plt.figure(figsize=(14,6))

ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_global()

ds.Tair[0].plot.pcolormesh(ax=ax,
                           transform=ccrs.PlateCarree(),
                           x='xc',
                           y='yc',
                           shading='auto',
                           add_colorbar=False)

ax.coastlines()
ax.set_ylim([0,90]);
```

**Anything else we need to know?**:
[pcolormesh doc](https://matplotlib.org/devdocs/gallery/images_contours_and_fields/pcolormesh_grids.html)

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.10 | packaged by conda-forge | (default, Sep 13 2021, 21:46:58) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.11.0-34-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.19.0
pandas: 1.3.3
numpy: 1.21.2
scipy: 1.7.1
netCDF4: 1.5.7
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2021.10.0
distributed: 2021.10.0
matplotlib: 3.4.3
cartopy: 0.19.0.post1
seaborn: None
numbagg: None
pint: None
setuptools: 58.0.4
pip: 21.2.4
conda: None
pytest: None
IPython: 7.28.0
sphinx: None

</details>

**Comment by mathause** [comment]
I am closing this as fixed upstream.
