### ISSUE TITLE
open_dataset fails with the valid rasterio filename protocol zip+s3:// when chunks=True

### ISSUE THREAD

**Issue by artttt** [pydata/xarray#5923]
given a path to a zip file of a raster stored on s3
(sorry I dont have a public example of such a file handy)

```
path_to_zip_on_s3 = 'zip+s3://bucket/the_zip.zip/the_zipped_file.asc'
this_works = xarray.open_dataset(path_to_zip_on_s3)
this_fails = xarray.open_dataset(path_to_zip_on_s3,chunks=True)
```

The error is `FileNotFoundError: [Errno 2] No such file or directory:`

My exploring of the issue is that xarray.backends.api.is_remote_uri returns that this is a local uri as it doesnt recognise the "+" sign in the protocol as being valid. Other functions then fail when trying to access this as a local file.

This doesn't fail in the unchunked version because it doesn't need to run the is_remote_uri function.

This type of multiple protocol specification is documented as being valid in rasterio https://rasterio.readthedocs.io/en/latest/topics/datasets.html#dataset-identifiers

Here is a potential fix
```
#edit the regex to allow a plus sign in the protocol specfication which is valid for rasterio
def is_remote_uri(path: str) -> bool:
    """Finds URLs of the form protocol:// or protocol:: or protocol+protocol:// or  protocol+protocol::
    This also matches for http[s]://, which were the only remote URLs
    supported in <=v0.16.2.
    """
    return bool(re.search(r"^[a-z][a-z0-9\+]*(\://|\:\:)", path))
```

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 4.14.248-189.473.amzn2.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.4
libnetcdf: 4.7.3

xarray: 0.19.0
pandas: 1.3.4
numpy: 1.19.5
scipy: 1.7.1
netCDF4: 1.5.8
pydap: installed
h5netcdf: 0.11.0
h5py: 3.1.0
Nio: None
zarr: 2.10.2
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2021.09.0
distributed: 2021.09.0
matplotlib: 3.4.3
cartopy: 0.18.0
seaborn: 0.11.2
numbagg: None
pint: None
setuptools: 58.3.0
pip: 21.3.1
conda: None
pytest: 6.2.5
IPython: 7.29.0
sphinx: 4.2.0

</details>

**Comment by Illviljan** [comment]
Hello, @artttt

Looks to me you've already figured this one out. Would you like to create a PR for this?
