### ISSUE TITLE
Relax GitHub Actions first time contributor approval?

### ISSUE THREAD

**Issue by Illviljan** [pydata/xarray#5928]
A while back GitHub made it so that new contributors cannot trigger GitHub Actions workflows and a maintainer has to hit "Approve and Run" every time they push a commit to their PR. This is rather annoying for both the contributor and the maintainer as the back and forth takes time.

It however seems possible to relax this constraint:
https://twitter.com/metcalfc/status/1448414192285806592?t=maeChQZTSUh2Ph0YFk-hGA&s=19

Shall we relax this constraint?

ref:
https://github.com/dask/community/issues/191

**Comment by max-sixty** [comment]
Yes agree! The "...who are new to GH" seems v reasonable

**Comment by keewis** [comment]
I just changed that setting. In the first place, that restriction was put in place to avoid cryptominers being run in CI, so if we get any strange PRs we'll have to revert.
