### ISSUE TITLE
Refresh on issue bots

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#5940]
Currently we have two bots which comment on issues, I'd propose we remove them both
- The "Unit Test Results". I don't find this that useful — do others? I thought it would be listing the tests that failed (I had thought it might even be doing duration changes etc), but it seems to just list the number of tests that failed, which isn't that useful. Or are we not using it correctly?
- pep8speaks — I think this would be dominated by pre-commit.ci

I'd propose we add:
- pre-commit.ci. This autofixes PRs! e.g. here's a test PR with a black error from pytest-accept: https://github.com/max-sixty/pytest-accept/pull/24. This could also replace the pre-commit GHA (though it's no great cost to duplicate it)

**Comment by TomNicholas** [comment]
I agree with all 3 suggestions

**Comment by Illviljan** [comment]
I like pep8speaks because it's faster than the current linting CI. But if we start using the autofixer than that would make pep8speaks redundant.

**Comment by keewis** [comment]
the only issues I have with `pre-commit.ci` is that it autofixes PRs so I have to remember to pull before adding new changes (but I think I can live with that, and the advantage is that lots of new contributors don't have to fight with our CI).

In any case, I'd vote to remove the `pre-commit autoupdate` CI as that has some quirks that make it difficult to use for everyone other than me.

**Comment by max-sixty** [comment]
Thanks for the thoughts. I enabled `pre-commit.ci` so we can see how that goes and remove the others if it's successful.

**Comment by andersy005** [comment]
> In any case, I'd vote to remove the pre-commit autoupdate CI as that has some quirks that make it difficult to use for everyone other than me.

Once we're satisfied with `pre-commit.ci`, we should remove https://github.com/pydata/xarray/blob/main/.github/workflows/ci-pre-commit.yml workflow as well.
