### ISSUE TITLE
Aggregating NetCDF files

### ISSUE THREAD

**Issue by monkeybutter** [pydata/xarray#597]
I have a collection of NetCDF files containing satellite data for different time ranges and geographical areas. Is there any example where the dimensions of several NetCDF files are aggregated (ie using and external index) giving the impression that all the data is contained in a single file. I'm thinking about using xray at a collection level but I haven't found any information or previous examples in this regard apart from the "Combining data" section in the docs.

Any idea you might have on providing aggregations at a collection level will be highly appreciated. Thanks for your help.

**Comment by shoyer** [comment]
What do these different time range and geographical regions look like?

If they are adjacent and non-overlapping, then xray could be a very good fit and I can help whip up an example to get you started. If this is not the case (and I know that can be an issue with satellite data), then it's going to be more awkward to put them together into a single logical Dataset. It might make more sense to work with individual Datasets, e.g., at the level of an individual satellite image.

**Comment by shoyer** [comment]
It would probably be helpful to show the results of printing the several of these datasets when opened via `open_dataset`.

**Comment by monkeybutter** [comment]
I have created the NetCDF files myself from geotiffs and I have made them so that there is no geographical overlapping between them. Basically each file contains a 1x1 degree area and a year worth of satellite data. The only problem that I can see with this approach is that the time dimension is different between files (the satellite covers different areas at different times). This might be problem when aggregating a big area because if the time dimension has to be homogenised it will be filled with basically no data over the whole area (sparse arrays). Depending how this sparsity is implemented it can fill memory pretty quickly. 

Some of these files can be found at:
http://dapds00.nci.org.au/thredds/catalog/uc0/rs0_dev/gdf_trial/20150709/LS5TM/catalog.html

A sample of `open_dataset` for a file is:
<xray.Dataset>
Dimensions:    (latitude: 4000, longitude: 4000, time: 11)
Coordinates:
  * time       (time) datetime64[ns] 1987-05-27T23:26:36 1987-08-31T23:29:21 ...
  * latitude   (latitude) float64 -33.0 -33.0 -33.0 -33.0 -33.0 -33.0 -33.0 ...
  * longitude  (longitude) float64 147.0 147.0 147.0 147.0 147.0 147.0 147.0 ...
Data variables:
    crs        int32 ...
    B10        (time, latitude, longitude) float64 ...
    B20        (time, latitude, longitude) float64 ...
    B30        (time, latitude, longitude) float64 ...
    B40        (time, latitude, longitude) float64 ...
    B50        (time, latitude, longitude) float64 ...
    B70        (time, latitude, longitude) float64 ...
Attributes:
    history: NetCDF-CF file created 20150709.
    license: Generalised Data Framework NetCDF-CF Test File
    spatial_coverage: 1.000000 degrees grid
    featureType: grid
    geospatial_lat_min: -34.0
    geospatial_lat_max: -33.0
    geospatial_lat_units: degrees_north
    geospatial_lat_resolution: -0.00025
    geospatial_lon_min: 147.0
    geospatial_lon_max: 148.0
    geospatial_lon_units: degrees_east
    geospatial_lon_resolution: 0.00025

Thanks you very much for your help.

**Comment by shoyer** [comment]
So unfortunately there isn't an easy way to handle irregular data like this with xray. Before you put this stuff in a single dataset, you would need to align the time variables, probably by doing `.reindex` with the [`method` argument](http://xray.readthedocs.org/en/stable/indexing.html#nearest-neighbor-lookups), which lets you do nearest-neighbor interpolation, or by using [`.resample`](http://xray.readthedocs.org/en/stable/time-series.html#resampling-and-grouped-operations). That way, you could make, for example, a dataset with the latest image for each location at the start of each month.

The other option (probably also useful) is to only concatenate one spatial tile along time, so you don't need to do any interpolation or resampling. The should work out of the box with `open_mfdataset`.

**Comment by j08lue** [comment]
Can't this be closed?
