### ISSUE TITLE
Typing of dim in concat.py does not include Hashable

### ISSUE THREAD

**Issue by LunarLanding** [pydata/xarray#5975]
i.e.
https://github.com/pydata/xarray/blob/5871637873cd83c3a656ee6f4df86ea6628cf68a/xarray/core/concat.py#L46

Arent' dims supposed to be any Hashable? In other xarray methods they generally are.

**Comment by max-sixty** [comment]
I'd be open to changing this, though I'm not sure everything supports non-str dims. IIRC there is an issue around using tuples, for example. Does anyone have a more informed view?

TBC, we should support non-dim variable names in datasets already.
