### ISSUE TITLE
Should str.format() work on xarray scalars?

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#5976]
Consider:

```python
da = xr.DataArray([1, 2, 3])
print(f'{da[0]}')
print(f'{da[0]:d}')
```

Which outputs:

```
<xarray.DataArray ()>
array(1)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-9cd7dc76455b> in <module>
      1 da = xr.DataArray([1, 2, 3])
      2 print(f'{da[0]}')
----> 3 print(f'{da[0]:d}')

TypeError: unsupported format string passed to DataArray.__format__
```
And the numpy equivalent:

```python
da = xr.DataArray([1, 2, 3]).data
print(f'{da[0]}')
print(f'{da[0]:d}')
1
1
```

I always found the xarray scalar output to be a bit unfriendly for beginners. In my classes very often scalars are the last output of a computation, and the fact that we can't format the relatively verbose xarray output without resulting to the `.data` trick is a bit confusing for students (but I agree this is a detail). 

Is there a way to get `print(f'{da[0]:d}')` to work? Thoughts?

**Comment by max-sixty** [comment]
Allowing `__format__` to work could be a nice way of letting us having easy ways to represent scalars, while retaining the benefits of always returning an array.

Separate point but FWIW I generally use `.item()` to get the value out of a scalar array.

**Comment by max-sixty** [comment]
@fmaussion how would you envision this working for non-scalar arrays? Would it just raise?

**Comment by fmaussion** [comment]
> @fmaussion how would you envision this working for non-scalar arrays? Would it just raise?

Yes, similar to numpy:

```python
da = xr.DataArray([1, 2, 3]).data
print(f'{da}')
print(f'{da:d}')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-93-e6dbd8f1cf00> in <module>
      1 da = xr.DataArray([1, 2, 3]).data
      2 print(f'{da}')
----> 3 print(f'{da:d}')

TypeError: unsupported format string passed to numpy.ndarray.__format__
```
