### ISSUE TITLE
xarray dataset or dataarray html display failed in jupyter notebook

### ISSUE THREAD

**Issue by Jing25** [pydata/xarray#5977]
### Discussed in https://github.com/pydata/xarray/discussions/5974

<div type='discussions-op-text'>

<sup>Originally posted by **Jing25** November 10, 2021</sup>
I cannot have xarray dataset or dataarray displayed in jupyter notebook (I'm actually using jupyterhub). It shows blank.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/27107288/141218794-ac3a1172-f83f-4a94-b3c9-3b9aec1ba071.png">

'text' style works: 
<img width="630" alt="image" src="https://user-images.githubusercontent.com/27107288/141218759-c4d339cd-e615-42d8-a756-d095cb37e2a3.png">

I checked my jupyter notebook HTML display and it works great:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/27107288/141218972-792df902-4abf-4c60-b844-bc5f3b12431e.png">

No problem with displaying pandas dataframe also. 

So I excluded jupyter notebook as the source of the issue. 

I'm not sure if this is a bug of xarray but does anyone know how I can solve this problem?

My xarray version is 0.19.0, Ubuntu 20.04.3. 
</div>

**Comment by max-sixty** [comment]
@Jing25 please could you fill out the issue template, including a reproducible example?

**Comment by Jing25** [comment]
Hi @max-sixty, thank you for asking. @andersy005 found an issue similar to mine here: https://github.com/executablebooks/sphinx-book-theme/issues/238, and I think this issue is being addressed: https://github.com/pydata/xarray/pull/5880#issue-1031724989
I'm just curious when this can be done. I can't view the xarray dask array which is a pain.

**Comment by max-sixty** [comment]
@Jing25 if you'd like to speed it along a couple of ways you could contribute:
- Try out that branch
- Understand the existing concern in that PR and add your thoughts on the best approach

**Comment by Jing25** [comment]
OK. I will try it out, thank you!
