### ISSUE TITLE
Plotting interpolated data causes artefacts

### ISSUE THREAD

**Issue by huaracheguarache** [pydata/xarray#5987]
**What happened**:

I'm trying to do some analysis of CMIP6 model data, and I want to plot multi-model ensembles. In order to do that I need to regrid all of the models to a common grid. Whenever I try to plot data from a regridded model there's a white line along the central longitude and the poles. I use the PlateCarree projection and it doesn't matter what I choose as the central longitude; there's always a white line there.

The code I've included below produces 4 plots. The first one is of data that hasn't been interpolated and there's no white line:

![mpi_ok](https://user-images.githubusercontent.com/33153877/141679217-9eb74a1e-b4da-458b-8e35-313066a2ab15.png)

The next three are with interpolated data and with different central longitudes. They all have a white line at the central longitude.

**central_longitude=0**

![mpi_bad_1](https://user-images.githubusercontent.com/33153877/141679424-b976cffc-5601-453d-a44a-1edee6741a25.png)

**central_longitude=33**

![mpi_bad_2](https://user-images.githubusercontent.com/33153877/141679434-05f1b1f5-cfec-4d27-a293-9f582ee8e098.png)

**central_longitude=164**

![mpi_bad_3](https://user-images.githubusercontent.com/33153877/141679443-9673d8f1-d018-44dc-8975-18581f077f3d.png)

**What you expected to happen**:

No plot artefacts.

**Minimal Complete Verifiable Example**:

```python
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

cesm2_waccm = xr.open_dataset('pr_day_CESM2-WACCM_ssp245_r2i1p1f1_gn_20750101-20841231.nc')
mpi = xr.open_dataset('pr_day_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_20750101-20941231.nc')

cesm2_waccm_subset = cesm2_waccm.sel(time=slice('2075-01-01', '2075-12-31')).mean(dim='time')
mpi_subset = mpi.sel(time=slice('2075-01-01', '2075-12-31')).mean(dim='time')

map_proj = ccrs.PlateCarree()

# This works.
plot = mpi_subset.pr.plot(subplot_kws={'projection': map_proj})
plot.axes.coastlines()
plt.show()

mpi_interp = mpi_subset.interp(lat=cesm2_waccm_subset['lat'], lon=cesm2_waccm_subset['lon'])

# A randomly chosen set of central longitudes for plots.
longitudes = [0, 33, 164]

for lon in longitudes:
   map_proj = ccrs.PlateCarree(central_longitude=lon)

   # Has a white line at the central longitude.
   plot = mpi_interp.pr.plot(subplot_kws={'projection': map_proj})
   plot.axes.coastlines()
   plt.show()

```

**Anything else we need to know?**:

Here's the data I used for plotting:

https://climate.uiogeo-apps.sigma2.no/ESGF/CMIP6/ScenarioMIP/NCAR/CESM2-WACCM/ssp245/r2i1p1f1/day/pr/gn/v20200224/pr_day_CESM2-WACCM_ssp245_r2i1p1f1_gn_20750101-20841231.nc

https://climate.uiogeo-apps.sigma2.no/ESGF/CMIP6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_20750101-20941231.nc

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

```
In [3]: xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:11) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.14.16-301.fc35.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: None

xarray: 0.20.1
pandas: 1.3.4
numpy: 1.21.4
scipy: 1.7.2
netCDF4: None
pydap: None
h5netcdf: 0.11.0
h5py: 3.4.0
Nio: None
zarr: None
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.3.2
cartopy: 0.20.1
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
setuptools: 58.5.3
pip: 21.3.1
conda: None
pytest: None
IPython: 7.29.0
sphinx: None
```

</details>

**Comment by huaracheguarache** [comment]
I decided to also look at what happens when you plot with contourf. In this case both the plot of the original data and the interpolated data have a white line at the central longitude, but the interpolated data also has white lines at the poles:

**Original MPI-ESM**

![contour_subset](https://user-images.githubusercontent.com/33153877/141683012-a4a003e6-d9f0-4003-8c9c-64fe20809a88.png)

**Interpolated MPI-ESM**

![contour_interp](https://user-images.githubusercontent.com/33153877/141683016-9de823d3-517e-4b2a-907f-fc541846ff79.png)

Here's the code that produced the plots:

```python
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

cesm2_waccm = xr.open_dataset('pr_day_CESM2-WACCM_ssp245_r2i1p1f1_gn_20750101-20841231.nc')
mpi = xr.open_dataset('pr_day_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_20750101-20941231.nc')

cesm2_waccm_subset = cesm2_waccm.sel(time=slice('2075-01-01', '2075-12-31')).mean(dim='time')
mpi_subset = mpi.sel(time=slice('2075-01-01', '2075-12-31')).mean(dim='time')

map_proj = ccrs.PlateCarree()

# Now this also produces a white line.
plot = mpi_subset.pr.plot.contourf(subplot_kws={'projection': map_proj})
plot.axes.coastlines()
plt.show()

mpi_interp = mpi_subset.interp(lat=cesm2_waccm_subset['lat'], lon=cesm2_waccm_subset['lon'])

# Has a white line at the central longitude.
plot = mpi_interp.pr.plot.contourf(subplot_kws={'projection': map_proj})
plot.axes.coastlines()
plt.show()
```

**Comment by spencerkclark** [comment]
Xarray's built-in interpolation method does not know how to handle periodic coordinates, which is why you see the blank center line.  I would recommend using [xESMF](https://pangeo-xesmf.readthedocs.io/en/latest/index.html), which is an xarray wrapper of some code specifically written to interpolate from one geospatial grid to another, and knows how to handle periodic coordinates (see the `periodic` flag in [the constructor of the `Regridder` object](https://pangeo-xesmf.readthedocs.io/en/latest/user_api.html#regridder)).  It also provides multiple different interpolating methods which, depending on your application, might be more applicable than xarray's options.

**Comment by huaracheguarache** [comment]
@spencerkclark Thanks for the suggestion! I made any serious tests yet, but my initial tests worked fine =)

**Comment by mathause** [comment]
If this solves your issue all is fine. However, I am a bit surprised that the `pcolormesh` creates a white line - can you print the lon coords? For the `contourf` you may need to add a [cyclic point](https://scitools.org.uk/cartopy/docs/v0.15/cartopy/util/util.html).

**Comment by spencerkclark** [comment]
@mathause I think the issue is that non-periodic interpolation introduces NaNs into the dataset, which get plotted as a white line.

**Comment by TomNicholas** [comment]
As an aside, this is something that we might want to try and fix via a `PeriodicIndex`, once the [explicit indexes refactor](https://github.com/pydata/xarray/projects/1) is complete.

**Comment by mathause** [comment]
@huaracheguarache can I convert this issue to a discussion? I think it would better fit there.

**Comment by huaracheguarache** [comment]
@mathause Sorry for the late reply! I've been very busy lately, but yes, please move it to a discussion.
