### ISSUE TITLE
Issue reading different variables from a grib file that have different stepType

### ISSUE THREAD

**Issue by McNomarr** [pydata/xarray#5996]
In the code below, I'm trying to open a grib file and read several variabls (t,prate,soilw,tmin,tmax,dswrf). Because they all have have different stepType from one another the code crashes:
> - stepType: 'instant' variables: t, sde, t2m, prate
> - stepType: 'avg' variables: prate,dsrwf
> - stepType: 'min' variable: tmin
> - stepType: 'max' variable: tmax
-----------------------------------------------------------------------------------------------------------------------------------------------
Because 'prate' appears to be in 'avg' and 'instant' the code gets confused and gives the following traceback:

cfgrib.dataset.DatasetBuildError: multiple values for unique key, try re-open the file with one of:
    filter_by_keys={'stepType': 'instant', 'shortName': 'prate'}
    filter_by_keys={'stepType': 'avg', 'shortName': 'prate'}
---------------------------------------------------------------------------------------------------------------------------------------
Has anyone managed to overcome this issue and read all variables using xr.opendataset properly?

Here's the excerpt of the code I'm running:

        if fh == 0:
            vars_to_extract = ['t']
        else:
            vars_to_extract = ['prate','soilw','sde','tmin','tmax','dswrf']

        push = []
        for var in vars_to_extract:
            logging.info('Extract vars {}'.format(var))
            logging.info('fh: {} - var: {}'.format(fh, var))
            **arr = xr.open_dataset(target_file,
                                engine='cfgrib',
                                    backend_kwargs={'filter_by_keys': {'shortName': '{}'.format(var)}}**
                                )

**Comment by dcherian** [comment]
Hi @McNomarr would you mind moving this issue to https://github.com/ecmwf/cfgrib instead. I think you'll get a better answer there.

**Comment by keewis** [comment]
the issue on `cfgrib` is ecmwf/cfgrib#268 so I'm closing this here
