### ISSUE TITLE
Memory leak with `open_zarr` default chunking option

### ISSUE THREAD

**Issue by slevang** [pydata/xarray#6013]
**What happened**:
I've been using xarray to open zarr datasets within a Flask app, and spent some time debugging a memory leak. What I found is that `open_zarr()` defaults to `chunks='auto'`, rather than `chunks=None` which is the default for `open_dataset()`. The result is that `open_zarr()` ends up calling `_maybe_chunk()` on the dataset's variables by default. 

For whatever reason this function is generating dask items that are not easily cleared from memory within the context of a Flask route, and memory usage continues to grow within my app, at least towards some plateau. This memory growth isn't reproducible outside of a Flask route, so it's a bit of a niche problem.

First proposal would be to simply align the default `chunks` argument between `open_zarr()` and `open_dataset()`. I'm happy to submit a PR there if this makes sense to others. The other more challenging piece would be to figure out whats going on in `_maybe_chunk()` to cause memory growth. The problem is specific to this function rather than any particular storage backend (other than the difference in default chunk args). 

**What you expected to happen**:
Memory usage should not grow when opening a zarr dataset within a Flask route.

**Minimal Complete Verifiable Example**:

```python
from flask import Flask
import xarray as xr
import gc
import dask.array as da

# save a test dataset to zarr locally
ds_test = xr.Dataset({"foo": (["x", "y", "z"], da.random.random(size=(300,300,300)))})
ds_test.to_zarr('test.zarr', mode='w')

app = Flask(__name__)

# ping this route repeatedly to see memory increase
@app.route('/open_zarr')
def open_zarr():
    # with default chunks='auto', memory grows, with chunks=None, memory is ok
    ds = xr.open_zarr('test.zarr', chunks='auto').compute()
    # Try to explicity clear memory but this doesn't help
    del ds
    gc.collect()
    return 'check memory'

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.11.0-40-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.20.1
pandas: 1.3.4
numpy: 1.19.5
scipy: 1.7.2
netCDF4: 1.5.8
pydap: None
h5netcdf: 0.11.0
h5py: 3.1.0
Nio: None
zarr: 2.10.1
cftime: 1.5.1.1
nc_time_axis: 1.4.0
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: 0.9.9.1
iris: None
bottleneck: 1.3.2
dask: 2021.11.1
distributed: 2021.11.1
matplotlib: 3.4.3
cartopy: 0.20.1
seaborn: None
numbagg: None
fsspec: 2021.11.0
cupy: None
pint: 0.18
sparse: None
setuptools: 58.5.3
pip: 21.3.1
conda: None
pytest: None
IPython: 7.29.0
sphinx: None

</details>

**Comment by max-sixty** [comment]
Sorry this didn't get a reply @slevang ...

I'm not sure there's likely to be much activity on the flask route issue — as you say, it is quite niche. To pursue, we'd probably need a way of reproducing with only xarray, unless someone is specifically motivated to take it up.

---

There are some docs on the difference between chunks' value of `{}` / `None` / `auto` now, though admittedly it doesn't seem crystal clear to me. But possibly that belong is a separate issue with some links to how we got where we are.

Otherwise I'll plan to close this, consistent with our attempt to maintain a reasonable backlog...

**Comment by slevang** [comment]
No problem, I forgot about this as well. Just tried my MCVE on latest versions and the issue seems to be resolved anyways, so I will go ahead and close.

**Comment by max-sixty** [comment]
Awesome, great to hear!
