### ISSUE TITLE
`xr.infer_freq` month bug for `freq='6MS'` starting Jan becomes `freq='2QS-OCT'`

### ISSUE THREAD

**Issue by aaronspring** [pydata/xarray#6045]
**What happened**:

@dougiesquire brought up https://github.com/pangeo-data/climpred/issues/698. During debugging I discovered unexpected behaviour in `xr.infer_freq`: `freq='6MS'` starting Jan becomes `freq='2QS-OCT'`

**What you expected to happen**:
`freq='6MS'` starting Jan becomes `freq='2QS-Jan'`

**Minimal Complete Verifiable Example**:

Creating an `6MS` index starting in Jan with pandas and xarray yields different `freq`. `2QS` and `6MS` are equivalent for quarter starting months but the `month` offset in `CFTimeIndex.freq` is wrong.

```python
import pandas as pd
i_pd = pd.date_range(start="2000-01-01", end="2002-01-01", freq="6MS")
i_pd
DatetimeIndex(['2000-01-01', '2000-07-01', '2001-01-01', '2001-07-01',
               '2002-01-01'],
              dtype='datetime64[ns]', freq='6MS')

pd.infer_freq(i_pd)
'2QS-OCT'

import xarray as xr
xr.cftime_range(start="2000-01-01", end="2002-01-01", freq="6MS")

CFTimeIndex([2000-01-01 00:00:00, 2000-07-01 00:00:00, 2001-01-01 00:00:00,
             2001-07-01 00:00:00, 2002-01-01 00:00:00],
            dtype='object', length=5, calendar='gregorian', freq='2QS-OCT')
```

**Anything else we need to know?**:

outline how to solve: https://github.com/pangeo-data/climpred/issues/698#issuecomment-985899966

**Comment by aaronspring** [comment]
the same happens also in `pandas`...
```python
import pandas as pd
i_pd = pd.date_range(start="2000-01-01", end="2002-01-01", freq="6MS")
i_pd
DatetimeIndex(['2000-01-01', '2000-07-01', '2001-01-01', '2001-07-01',
               '2002-01-01'],
              dtype='datetime64[ns]', freq='6MS')

pd.infer_freq(i_pd)
'2QS-OCT'
```

**Comment by aaronspring** [comment]
code in xarray is nearly identical to pandas. probably I misunderstood the documentation/explanation

**Comment by dcherian** [comment]
Closing since this seems to be a misunderstanding. 

@aaronspring please reopen if there is indeed a bug.
