### ISSUE TITLE
Import hangs when matplotlib installed but no display available

### ISSUE THREAD

**Issue by jaicher** [pydata/xarray#6062]
**What happened**: On a device with no display available, importing xarray without setting the matplotlib backend hangs on import of matplotlib.pyplot since #5794 was merged.

**What you expected to happen**: I expect to be able to run `import xarray` without needing to mess with environment variables or import matplotlib and change the default backend.

**Comment by Illviljan** [comment]
What do you mean with "no display available"? You haven't installed matplotlib? 
The CI runs without mpl as well and works fine there.

**Comment by mathause** [comment]
Can you let us know your OS and `xr.show_versions()`. 

Could be a bug of the `"MacOSX"` backend: matplotlib/matplotlib#19197 & matplotlib/matplotlib#19268. (However, we test on macos in our CI.)
