### ISSUE TITLE
<https://xarray.pydata.org> redirects to <http://xarray.pydata.org/en/stable/>

### ISSUE THREAD

**Issue by zmoon** [pydata/xarray#6063]
(https -> http), which seems not ideal

**Comment by max-sixty** [comment]
Thanks @zmoon . Do you happen to know whether this is a recent change? (Understandable if not!)

**Comment by zmoon** [comment]
Sorry, not sure. I don't *recall* noticing it before.

**Comment by max-sixty** [comment]
Thanks @zmoon .

Does anyone who's more familiar with the docs know whether this is expected? I don't recall seeing this either.

**Comment by keewis** [comment]
not sure when this happened or if it ever did not redirect, but in any case I enabled RTD's "always use HTTPS for this domain" setting, so it should redirect `http://xarray.pydata.org` to HTTPS, too.

**Comment by max-sixty** [comment]
Perfect, thanks @keewis !
