### ISSUE TITLE
odo support

### ISSUE THREAD

**Issue by femtotrader** [pydata/xarray#607]
Hello,

I'm totally new to xray.
I wonder if xray have odo support
http://odo.readthedocs.org/

Kind regards

**Comment by shoyer** [comment]
@mrocklin, @cpcloud, @izaid and myself have discussed this, a little bit [online](https://github.com/blaze/dask/issues/326#issuecomment-113478480) and mostly offline.

The trouble is figuring out how to map the xray datamodel into odo. The [datashape](https://github.com/blaze/datashape) project, which odo relies on, currently lacks any support for named axes, which makes fitting xray objects into datashape a little awkward. Likewise, xray has tick labels, which don't exist in most odo datatypes. I'm certainly not opposed to adding xray to odo, but it would need some opinionated design choices which are not immediately obvious to me.

Generally, I recommend taking a look at [xray's tools for converting to/from pandas](http://xray.readthedocs.org/en/stable/pandas.html) and using pandas as intermediate data structure for converting to and from other formats.

**Comment by max-sixty** [comment]
Closing as stale, please reopen if still relevant
