### ISSUE TITLE
xarray.DataArray does not maintain attributes upon addition of two likewise DataArrays

### ISSUE THREAD

**Issue by ajcost** [pydata/xarray#6080]
**Problem Statement**
xarray.DataArray does not maintain attributes if two DataArrays with same attributes are added or subtracted. **Please note, I can understand this being necessary to operations like multiply or divide and therefore not implemented.** 

However, attributes are commonly used to hold unit values and other useful information and it becomes tiresome and slightly un-pythonic to have to add back attributes to a result DataArray from an addition or subtraction operation.

I'm unsure if there is a way to keep `attrs` upon addition or subtraction or other operations but would like to learn how to do so, so that I don't have to keep a custom function to write parameters back to a resulting array after each operation.

`attrs` dict is also dropped under a divide or multiply operation from a non-parametrized values e.g `int`, `float` etc.

**Expected Result**
Added array with the common `attrs` retained between the two `xr.DataArrays`.

**Minimal Complete Verifiable Example**:
```python
import numpy as np
import xarray as xr

elevation = 10 * np.random.randn(2, 2, 3)
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]
time = [2014, 2015, 2016]

elevation_1 = xr.DataArray(
    data=elevation,
    dims=["x", "y", "time"],
    coords=dict(
        lon=(["x", "y"], lon),
        lat=(["x", "y"], lat),
        time=time,
    ),
    attrs=dict(
        description="Elevation",
        units="mm",
    ),
)

elevation_2 = xr.DataArray(
    data=elevation,
    dims=["x", "y", "time"],
    coords=dict(
        lon=(["x", "y"], lon),
        lat=(["x", "y"], lat),
        time=time,
    ),
    attrs=dict(
        description="Elevation",
        units="mm",
    ),
)

elevation_1 + elevation_2 # Drops attrs dict

elevation_1 / 2  # Drops attrs dict


## Requires user to do this
temp = elevation_1.attrs
eg = elevation_1 + elevation_2
eg.attrs = temp
```

Again this may be expected behavior, and I recognize that this just might be the case. Yet, if the use of `units` is advertised in documentation examples, there is some expectation that they might work upon `+` ,`-` and other operations.

Furthermore, the attributes are maintained under `interpolate_na` and other "reflexive" operations.

**Comment by keewis** [comment]
did you try setting `xr.set_options(keep_attrs=True)`? That should work for attributes in general, but for units in particular you could also use [pint-xarray](https://github.com/xarray-contrib/pint-xarray).

**Comment by ajcost** [comment]
@keewis I think you're right I'm looking for functionality included in pint-xarray.  And yes `xr.set_options(keep_attrs=True)` works. Apologies for opening the issue.
