### ISSUE TITLE
Missing linked coordinates of subgroup variable

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#6085]
**What happened**:

I have a [NetCDF file](https://data-portal.s5p-pal.com/browser/item/BXADeFDHwTQ3o8nrrhTDZSMwnfrWHe16d/2JM1fiAU7vaLzQZSRP3o4uRznddN4VH4NGpp4dfkKSnZV4hzrZifph/eX91ZTvd7bADysky6BArSuuZDRDyS1Va6ZSSSaUkw4PxEXiYyc3ZYZ1vNcwo/xdDvwjHCFDzMnS3V2LdCjo3DPbiMR3LiLiz79gzQibo1ebTmhymGartDy3faKioX/2RU2DwH5yvwhdKJrx5pfNf1FLnnGDvfwrtn7eX1XxCuDH7RVftpZfUXTHRVEFtagV6syF/cA42MuC47K24cXuCNNjhLQcYkrKqf9YgPPXVFFVXWWY7SmuTFWY8gcBbGcg1trTsa65vhci8WPV5AMH7nVpJ9C8U1taG5J9NvTmUp9A6BQ635uFqrXY9VnXnzTVwa86vQHyRiZm11u72xYpmsQhVPRgrxHdaR8sNBT2kUQKwrcE9) that has groups like this:

```
--/PRODUCT/
--/PRODUCT/SUPPORT_DATA/DETAILED_RESULTS
.....
```

**Screenshots**

![image](https://user-images.githubusercontent.com/30388627/146638398-8ea1a6da-f6d5-452b-84c8-573b7f0df435.png)

![image](https://user-images.githubusercontent.com/30388627/146638407-9f33fc01-7ff9-41a2-9cd3-a5ae69dca272.png)

When I read the variable named `air_mass_factor_clear` inside `/PRODUCT/SUPPORT_DATA/DETAILED_RESULTS`, the coordinates are missing. But, it works for variable named `nitrogendioxide_tropospheric_column` in the `/PRODUCT/` group.

**What you expected to happen**:

Coordinates of variables in subgroups are loaded.

**Minimal Complete Verifiable Example**:

```python
xr.open_dataset('./201908/S5P_PAL__L2__NO2____20190811T022605_20190811T040734_09459_01_020301_20211110T023157.nc',
                group='PRODUCT/')['nitrogendioxide_tropospheric_column']
```

![image](https://user-images.githubusercontent.com/30388627/146638383-e66ef713-3a04-410b-a17e-65e76f1ae209.png)

```python
xr.open_dataset('./201908/S5P_PAL__L2__NO2____20190811T022605_20190811T040734_09459_01_020301_20211110T023157.nc',
                group='PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/')['air_mass_factor_clear']
```

![image](https://user-images.githubusercontent.com/30388627/146638413-cf6572ed-dcc7-4fe7-8df5-a583e9561df8.png)

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.11.0-40-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.20.1
pandas: 1.3.4
numpy: 1.20.3
scipy: 1.7.3
netCDF4: 1.5.8
pydap: None
h5netcdf: None
h5py: 3.6.0
Nio: None
zarr: 2.10.3
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: None
iris: None
bottleneck: None
dask: 2021.11.2
distributed: 2021.11.2
matplotlib: 3.5.0
cartopy: 0.20.1
seaborn: None
numbagg: None
fsspec: 2021.11.1
cupy: None
pint: 0.18
sparse: None
setuptools: 59.4.0
pip: 21.3.1
conda: 4.11.0
pytest: None
IPython: 7.30.0
sphinx: None

</details>

**Comment by TomNicholas** [comment]
Hi @zxdawn, thanks for the report. Would you say your issue is the same as the one in https://github.com/pydata/xarray/issues/1982 ?

**Comment by zxdawn** [comment]
Hi @TomNicholas, thanks and yes that's the same issue. Shall we close this duplicated one?

**Comment by TomNicholas** [comment]
Yes I think we should close this as a duplicate. By the way, this isn't a quick fix in `xarray.Dataset` as it is (see https://github.com/pydata/xarray/issues/1982#issuecomment-437990188 as for why), so if we do ever support this behaviour it's likely to be via the `DataTree` route described in #4118.
