### ISSUE TITLE
DeprecationWarning regarding use of distutils Version classes

### ISSUE THREAD

**Issue by djhoese** [pydata/xarray#6092]
**What happened**:

While working on some tests that catch and check for warnings in my library I found that xarray with new versions of Python (I think this is the trigger) causes a ton of DeprecationWarnings on import:

```python
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pycompat.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion(duck_array_module.__version__)
```

**What you expected to happen**:

No warnings.

**Minimal Complete Verifiable Example**:

```python
import warnings
warnings.simplefilter("always")

import xarray as xr
```

Results in:

```
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pycompat.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion(duck_array_module.__version__)
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/npcompat.py:82: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(np.__version__) >= "1.20.0":
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pdcompat.py:45: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(pd.__version__) < "0.25.0":
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

```
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/_distutils_hack/__init__.py:35: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/asyncio/base_events.py:681: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.15.5-76051505-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.20.2
pandas: 1.3.5
numpy: 1.20.3
scipy: 1.7.3
netCDF4: 1.5.8
pydap: None
h5netcdf: 0.12.0
h5py: 3.6.0
Nio: None
zarr: 2.10.3
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2021.12.0
distributed: 2021.12.0
matplotlib: 3.5.1
cartopy: 0.20.1
seaborn: None
numbagg: None
fsspec: 2021.11.1
cupy: None
pint: None
sparse: None
setuptools: 60.0.3
pip: 21.3.1
conda: None
pytest: 6.2.5
IPython: 7.30.1
sphinx: 4.3.2
```

</details>

**Comment by max-sixty** [comment]
Thanks @djhoese . Looks like we can update `LooseVersion` to `packaging.version`...

**Comment by Illviljan** [comment]
It's started to show up in the xarray CI as well now: 
https://github.com/pydata/xarray/runs/4600524127?check_suite_focus=true

**Comment by mathause** [comment]
We currently use `from distutils.version import LooseVersion` - any opinion if we should replace this by `version.parse` or by `version.Version`?

```python
from distutils.version import LooseVersion
from packaging import version

LooseVersion(xr.__version__)
version.parse(xr.__version__)
version.Version(xr.__version__)

# currently:
if LooseVersion(mod.__version__) < LooseVersion(minversion):
    pass

# options:
if version.parse(mod.__version__) < version.parse(minversion):
    pass

if version.Version(mod.__version__) < version.Version(minversion):
    pass

if Version(mod.__version__) < Version(minversion):
    pass
```

See https://packaging.pypa.io/en/latest/version.html

(I think `version.parse` either returns a `Version` or a `LegacyVersion`. A five minute search suggests this is the preferred method but probably someone has a more informed opinion.)

**Comment by djhoese** [comment]
@mathause I agree that `.parse` is the preferred method when you are taking a version string from an outside source. If you were using a static/constant string then it would probably be fine to use Version.

I wasn't sure what the best approach would be for xarray given that LooseVersion is a public property on the duck array wrapper, right? I'm not sure if packaging's Version is backwards compatible and whether or not that matters inside xarray.

**Comment by mathause** [comment]
> I agree that .parse is the preferred method when you are taking a version string from an outside source. If you were using a static/constant string then it would probably be fine to use Version.

True we could potentially use `version.parse(h5netcdf.core.h5py.__version__) >= version.Version("3.0.0")` in #6096.

> I wasn't sure what the best approach would be for xarray given that LooseVersion is a public property on the duck array wrapper, right? I'm not sure if packaging's Version is backwards compatible and whether or not that matters inside xarray.

Good point. It's not really backwards compatible. packagings Version cannot be compared to a string (while LooseVersion can). However, `DuckArrayModule` is probably not meant as a public interface - or were you referring to something else?

https://github.com/pydata/xarray/blob/5e8de55321171f95ed9684c33aa47112bb2519ac/xarray/core/pycompat.py#L11-L13

**Comment by djhoese** [comment]
Yes, sorry, I meant `DuckArrayModule`.

**Comment by esegal** [comment]
This also happens in seaborn

**Comment by AppaAppa** [comment]
assert LooseVersion(tf.__version__) >= LooseVersion("2.0")
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

How do resolve it?

**Comment by jhamman** [comment]
@AppaAppa - this is quite an old ticket. If you are running into something similar with Xarray, can you open a new issue and include the relevant information about versions and your environment?

**Comment by AppaAppa** [comment]
Hi, i am running Mask RCNN file from github. In the model file , it shows
the error
assert LooseVersion(tf.__version__) >= LooseVersion("2.0")
DeprecationWarning: distutils Version classes are deprecated. Use
packaging.version instead.

How cal i fix it?
