### ISSUE TITLE
Issue on page /examples/multidimensional-coords.html

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#6095]
The `Groupby` example focuses on lat_bin. Then the `xc` in the `groupby_bins` function should be `yc`.

**Comment by zxdawn** [comment]
Old figure:
![image](https://user-images.githubusercontent.com/30388627/146970209-de71c29a-51f5-4f7e-b6da-dc3817e4fcd3.png)


New figure:
![image](https://user-images.githubusercontent.com/30388627/146970195-278ca107-8cb2-43b9-a2d0-f4eeaf3ebcba.png)

**Comment by VeckoTheGecko** [comment]
This should be closed. Looks fixed in latest docs

https://docs.xarray.dev/en/stable/examples/multidimensional-coords.html#Multidimensional-Groupby
