### ISSUE TITLE
Xarray.to_netcdf encoding option not working for complevel and shuffle

### ISSUE THREAD

**Issue by chiaweh2** [pydata/xarray#6167]
### What happened?

The complevel and shuffle do not work on outputting file after updating the variable encoding. I set the variable encoding through `ds_test.net_heating.encoding.update({'complevel': 2, 'shuffle': True})` but the output nc file does not have _Shuffle and _DeflateLevel shown in the `ncdump -hs test.nc`. 

I, then, read in the output test.nc and check the encoding of the same variable and find the complevel = 0 and shuffle = False.

### What did you expect to happen?

1. The output file.nc shows correct _Shuffle and _DeflateLevel through ncdump -hs file.nc. 
2. Read in the output file.nc through Xarray and check the encoding of the same variable should show complevel = 2 and shuffle = True.

### Minimal Complete Verifiable Example

```python
>> ds_test.var.encoding
{'zlib': False,
 'shuffle': False,
 'complevel': 0,
 'fletcher32': False,
 'contiguous': False,
 'chunksizes': (1, 1500, 3600),
 'source': 'file.nc',
 'original_shape': (336, 1500, 3600),
 'dtype': dtype('float32'),
 'missing_value': -1e+20,
 '_FillValue': -1e+20}
>> ds_test.var.encoding.update({'complevel': 2, 'shuffle': True})
>> ds_test.var.encoding
{'zlib': False,
 'shuffle': True,
 'complevel': 2,
 'fletcher32': False,
 'contiguous': False,
 'chunksizes': (1, 1500, 3600),
 'source': 'file.nc',
 'original_shape': (336, 1500, 3600),
 'dtype': dtype('float32'),
 'missing_value': -1e+20,
 '_FillValue': -1e+20}
>> ds_test.to_netcdf('test.nc')
>> ds_read = xr.open_dataset('test.nc')
>> ds_read.var.encoding
{'zlib': False,
 'shuffle': False,
 'complevel': 0,
 'fletcher32': False,
 'contiguous': False,
 'chunksizes': (1, 1500, 3600),
 'source': 'test.nc',
 'original_shape': (336, 1500, 3600),
 'dtype': dtype('float32'),
 'missing_value': -1e+20,
 '_FillValue': -1e+20}
```

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 4.18.0-348.7.1.el8_5.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1
xarray: 0.20.2
pandas: 1.3.5
numpy: 1.20.3
scipy: 1.7.3
netCDF4: 1.5.8
pydap: None
bottleneck: 1.3.2
dask: 2021.12.0
distributed: 2021.12.0
matplotlib: 3.5.1
cartopy: 0.20.1
seaborn: None
numbagg: None
fsspec: 2021.11.1
cupy: None
pint: None
sparse: 0.13.0
setuptools: 58.0.4
pip: 21.2.4
conda: None
pytest: None
IPython: 7.31.0
sphinx: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None

**Comment by kmuehlbauer** [comment]
@chiaweh2 This only works if you set `zlib=True`. The two keywords are ignored if `zlib=False`. Please refer to the netcdf4-python docs https://unidata.github.io/netcdf4-python/#Dataset.createVariable.

**Comment by chiaweh2** [comment]
@kmuehlbauer Sorry for reporting this as bug and thank you so much for the explanation and help changing the tag! After changing the zlib=True, it works perfectly now. 

Is there a possibility of including the link or adding a brief explanation of all encoding options in https://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_netcdf.html ? I think this would be most helpful! However, I understand if the team consider this as a backend related setting and would not want to put too much info on the Xarray docstring.

**Comment by jhamman** [comment]
@chiaweh2 - a PR to improve the documentation would certainly be welcome. Do you think it makes sense to add this to the docstring or to the user guide page on IO (https://xarray.pydata.org/en/stable/user-guide/io.html#chunk-based-compression)?

**Comment by chiaweh2** [comment]
@jhamman Thank you for the link! I think listing all options for encoding without explanation would already be very useful. A reference to this page or the netcdf4 page provided by @kmuehlbauer  in the docstring would be very nice. I will certainly see if I can submit a PR for the document improvement if this is something the Xarray team also consider to add. Thank you again for the links and helps above from the team!
