### ISSUE TITLE
upstream dev CI: enable bottleneck again

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#6186]
bottleneck cannot be built with python 3.10. See https://github.com/pydata/xarray/actions/runs/1731371015

**Comment by Illviljan** [comment]
```
   gcc -pthread -B /usr/share/miniconda/envs/xarray-tests/compiler_compat -E -I/usr/share/miniconda/envs/xarray-tests/include/python3.1 -I/usr/share/miniconda/envs/xarray-tests/include/python3.1 -o _configtest.i _configtest.c
  _configtest.c:1:10: fatal error: Python.h: No such file or directory
      1 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
```
python3.1 huh?

I think https://github.com/pydata/bottleneck/pull/378 might fix but this PR has been sitting around since march.

**Comment by mathause** [comment]
#6193 disabled installing bottleneck from master in the upstream CI (because it does not work for python 3.10). Enable it again once it can be installed/ built for python 3.10.
