### ISSUE TITLE
Remove stable branch?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#6206]
### Is your feature request related to a problem?

Currently https://github.com/pydata/xarray/blob/main/HOW_TO_RELEASE.md has a few steps around the stable branch

### Describe the solution you'd like

In our dev call, we discussed the possibility of using `main` in place of `stable` and removing the stable branch

IIRC there's something we can do on RTD to make that replacement. (If anyone knows to hand, comment here; otherwise I can search for it).

Is there anything else we need to do apart from RTD?

**Comment by mathause** [comment]
I think it's described here: https://docs.readthedocs.io/en/stable/versions.html

> we also create a stable version, tracking your most recent release

If I understand it correctly the "stable" docs is built from the release.

**Comment by keewis** [comment]
this should work pretty much automatically: you remove `stable` from the repository, and RTD will use the most recent release tag instead (it will filter out pre-release and other tags using the rules from PEP440). See this section: https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working

In any case, I'd volunteer to debug RTD if any kind of error does come up during the migration.

**Comment by max-sixty** [comment]
`stable` has been removed!

FWIW we now have two branches: `main` and `pr/jhamman/5759`! Maybe we delete that too CC @jhamman :)
