### ISSUE TITLE
An iris cube converter?

### ISSUE THREAD

**Issue by DamienIrving** [pydata/xarray#621]
Would it be possible to include a function to convert from an `xray.DataArray` to an `iris.cube`? 

For weather/climate/ocean science, xray is by far the best library for general data processing, while [iris and cartopy](http://scitools.org.uk/) are the best for geospatial plotting. At the moment I usually write the results of my xray data processing out to a netCDF file, then read that file in with iris for plotting. I'm assuming many other people do the same, so a `.to_cube()` function might allow people to skip that extra input/output step.

**Comment by shoyer** [comment]
Yes, this would certainly be a welcome addition (see #37). If you're interested in working on this, #236 is reasonable template.
