### ISSUE TITLE
Get pyupgrade to update the typing

### ISSUE THREAD

**Issue by Illviljan** [pydata/xarray#6244]
### Is your feature request related to a problem?

Use more up-to-date typing styles on all files. Will reduce number of imports and avoids big diffs when doing relatively minor changes because pre-commit/pyupgrade has been triggered somehow.

Related to #6240

### Describe the solution you'd like

Add `from __future__ import annotations` on files with a lot of typing.
Let pyupgrade do the rest.

**Comment by mathause** [comment]
You could go the other way round and run

```bash
find . -name "*.py" -exec pyupgrade --py39-plus {} \;
```

and then manually add `from __future__ import annotations` to files that were updated. Could also update

https://github.com/pydata/xarray/blob/d47cf0c850cb70429373782b3c1e0329d14fd05a/.pre-commit-config.yaml#L26

to `--py38-plus`.

**Comment by headtr1ck** [comment]
Almost all files have `from __future__ import annotations` now and pyupgrade is doing its thing :)
