### ISSUE TITLE
failing docs builds because the `scipy` intersphinx registry is unreachable

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#6250]
### What happened?

`scipy` seems to have some trouble with their documentation host setup, which means that trying to fetch its intersphinx registry returns a 404.

There's nothing we can do to really fix this, but we can try to the avoid docs build failures by disabling that intersphinx entry (not sure if that results in other errors, though)

### Relevant log output

```python
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.scipy.org/doc/scipy/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.scipy.org/doc/scipy/objects.inv
```

### Environment

See RTD

**Comment by keewis** [comment]
update: the 404 is gone, but now it is returning a HTML document instead of `objects.inv`

**Comment by mathause** [comment]
Did it move?

```diff
-https://docs.scipy.org/doc/scipy/objects.inv
+https://docs.scipy.org/doc/scipy/reference/objects.inv
```

**Comment by keewis** [comment]
that does seem to work, but I'm not sure what the official path is. We can temporarily use this to avoid failing the builds, though.

**Comment by mathause** [comment]
Found by chance: pandas-dev/pandas#5878 & https://github.com/scipy/scipy/issues/15545#issuecomment-1032825234 - so `'scipy': ('https://docs.scipy.org/doc/scipy/', None),` seems to be the new link.

**Comment by keewis** [comment]
are you sure the pandas issue is the correct one? The `scipy` issue does indeed suggest that we're already using the correct link, and the most recent build do pass. So I guess we can close this?

**Comment by mathause** [comment]
You are right! The docs build again.
