### ISSUE TITLE
`Dataset.to_zarr()` does not preserve CRS information

### ISSUE THREAD

**Issue by gcaria** [pydata/xarray#6288]
### What happened?

When writing a DataArray with CRS information to zarr, after converting it to a Dataset, the CRS is not readable from the zarr file.

### What did you expect to happen?

To be able to retrieve the CRS information from the zarr file.

### Minimal Complete Verifiable Example

```python
da = xr.DataArray(np.arange(9).reshape(3,3),
                  coords={'x':range(3), 'y':range(3)}
                 )

da = da.rio.write_crs(4326)
da.to_dataset(name='var').to_zarr('var.zarr')
xr.open_zarr('var.zarr')['var'].rio.crs == None # returns True
```

### Anything else we need to know?

I'd be happy to have a look at this if it is indeed a bug.

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.0 (default, Jan 17 2022, 21:57:22) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 5.11.0-1028-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: None

xarray: 0.20.1
pandas: 1.3.4
numpy: 1.21.4
scipy: 1.7.3
netCDF4: None
pydap: None
h5netcdf: None
h5py: 3.6.0
Nio: None
zarr: 2.11.0
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: None
iris: None
bottleneck: None
dask: 2022.01.0
distributed: 2022.01.0
matplotlib: 3.5.1
cartopy: None
seaborn: None
numbagg: None
fsspec: 2021.11.1
cupy: None
pint: None
sparse: None
setuptools: 60.2.0
pip: 21.3.1
conda: None
pytest: 6.2.5
IPython: 8.0.0
sphinx: None
​

**Comment by dcherian** [comment]
cc @snowman2

**Comment by snowman2** [comment]
https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html#xarray

Are you able to use `decode_coords="all"` when opening?

**Comment by gcaria** [comment]
Thanks @snowman2, that makes the CRS readable

**Comment by gcaria** [comment]
By the way, the docstring of `open_zarr` fails to mention that `decode_coords` could be a string too (and what the accepted string values mean)

https://github.com/pydata/xarray/blob/fed852073eee883c0ed1e13e28e508ff0cf9d5c1/xarray/backends/zarr.py#L687-L689

Should I open a separate issue for this?

**Comment by dcherian** [comment]
That would be great. Thanks @gcaria

**Comment by crawld** [comment]
i had the same problem (missing crs) but adding decode_coords='all' did not fix it. the difference in my case from the above minimal example might be i have several variables in the zarr group. the fix was to add the grid_mapping attribute to each variable:

`z['group1']['var1]['grid_mapping'] = 'spatial_ref'
`

once i did this (and decode_coords='all') it worked.

**Comment by prasotis** [comment]
Adding the related issue for future reference https://github.com/pydata/xarray/issues/6405

**Comment by prasotis** [comment]
Adding here the related issue for future reference https://github.com/pydata/xarray/issues/6405
