### ISSUE TITLE
Confusing error (or lack thereof) when coordinate and variable share the same name

### ISSUE THREAD

**Issue by anntzer** [pydata/xarray#631]
It probably makes sense to prevent dataset to have variables sharing the names of coordinates (what would `dataset.varname` return?) but currently

```
Dataset({"a": DataArray(np.zeros((3, 4)), dims=["a", "b"],
                        coords={"a": list("xyz"), "b": list("xyzt")})})
```

fails with `ValueError: an index variable must be defined with 1-dimensional data`, and

```
Dataset({"a": DataArray(np.zeros(3), coords={"a": list("xyz")})})
```

actually creates an empty dataset using `[0, 0, 0]` as values for the `a` coordinate instead of `x y z`:

```
<xray.Dataset>
Dimensions:  (a: 3)
Coordinates:
  * a        (a) float64 0.0 0.0 0.0
Data variables:
    *empty*
```

**Comment by shoyer** [comment]
Oh my, this certainly does look like a bug (or several).

**Comment by markelg** [comment]
This is related to #457. In the first case, I think that the error message must be improved, but I do not think that Error is itself is a bug. From the netCDF data model point of view, it does not make sense to define a two dimensional variable sharing the name with a one-dimensional coordinate.

The second example does look like a bug, as it should raise an error too, in my opinion, as the function Dataset is given contradictory information (two different sets of values for the same variable "a"). In netCDF files you cannot have two variables with the same name, and coordinate variables are just regular variables.

**Comment by shoyer** [comment]
Yes, @markelg I think you describe each of these issues correctly. They should each result in more informative errors.

**Comment by jhamman** [comment]
The first example here was fixed in #1539.

The second issue still exists but now requires `dims` to be specified explicitly. 

```Python
In [9]: Dataset({"a": DataArray(np.zeros(3), dims='a', coords={"a": list("xyz")})})
   ...: 
   ...: 
Out[9]: 
<xarray.Dataset>
Dimensions:  (a: 3)
Coordinates:
  * a        (a) float64 0.0 0.0 0.0
Data variables:
    *empty*
```

Do we agree it is safe to say that no key should be repeated between `data` and `coords`?

**Comment by max-sixty** [comment]
Adding a v confusing error message which my colleague just hit (not exactly the same as this, but thought it wasn't worth a whole new issue):

```

In [10]: xr.DataArray(
    ...:     data=1,
    ...:     coords={
    ...:         'test':[1]#,
    ...:     },
    ...:     dims=['test']
    ...: )
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-41a019d49aae> in <module>
      4         'test':[1]#,
      5     },
----> 6     dims=['test']
      7 )

~/workspace/xarray/xarray/core/dataarray.py in __init__(self, data, coords, dims, name, attrs, encoding, indexes, fastpath)
    228
    229             data = as_compatible_data(data)
--> 230             coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
    231             variable = Variable(dims, data, attrs, encoding, fastpath=True)
    232

~/workspace/xarray/xarray/core/dataarray.py in _infer_coords_and_dims(shape, coords, dims)
     76
     77         for d, s in zip(v.dims, v.shape):
---> 78             if s != sizes[d]:
     79                 raise ValueError('conflicting sizes for dimension %r: '
     80                                  'length %s on the data but length %s on '

KeyError: 'test'
```

...nothing to do with the `test` entry, it's that data is a scalar

**Comment by kmuehlbauer** [comment]
All given examples work in recent xarray 2024.10.0. Please reopen with updated examples, if this is still an issue.
