### ISSUE TITLE
Handle scipy fitting errors in `xarray.curve_fit`

### ISSUE THREAD

**Issue by StanczakDominik** [pydata/xarray#6317]
### Is your feature request related to a problem?

I'm trying to fit a bunch of exponential decays to a dataset of dimensions `(Time, experimental_index)`, along the `Time` dimension. This works nicely... except in some cases, `scipy.optimize` raises an error such as `RuntimeError: Optimal parameters not found: The maximum number of function evaluations is exceeded.`. That's, of course, reasonable, except in my use case I'm fine with a bunch of `experimental_index` failing to fit, and I'd still like to access the fits that made it through.

### Describe the solution you'd like

I'm proposing adding a flag for `xarray.curvefit`, for example `allow_failures: bool = False`, that would take this part:

https://github.com/pydata/xarray/blob/f9037c41e36254bfe7efa9feaedd3eae5512bd11/xarray/core/dataset.py#L7738-L7752

and, if active, wrap `popt, pcov = curve_fit(func, x, y, **kwargs)` in a `try/except` block that would output `nan` just as the `not len(y)` conditional clause does if `scipy.optimize.curve_fit` fails with a `RuntimeError`.

### Describe alternatives you've considered

At the moment, I sidestep the issue like this:

```python
fits = []
for experimental_index in timetraces.experimental_index:
    trace = traces.sel(experimental_index=experimental_index)
                                                           
    try:
        fit = trace.curvefit(
            "Time",
            fitfunc,
            p0=(...),
            bounds={...},
        )
    except (RuntimeError, TypeError) as e:
        logger.debug(...)
        continue

    fits.append(fit)

fits = xarray.concat(fits, dim="experimental_index", coords="all")
```
but that seems like a pretty ugly hack...	

### Additional context

I would of course be happy to implement this!

**Comment by slevang** [comment]
These errors can often be eliminated by passing appropriate initial guesses for each parameter through the `p0` argument (which it looks like you're already doing), and/or by passing additional kwargs through to `scipy.optimize.leastsq()`, like `ftol` and `maxfev` which set the fit tolerance and max number of iterations. 

Even so, there will be cases where some of your data just doesn't fit the desired function and you want to move on and return a result anyway. Your proposal seems fine as long as errors are raised by default and the documentation adequately describes the behavior when set to True.
