### ISSUE TITLE
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4']. 

### ISSUE THREAD

**Issue by morestart** [pydata/xarray#6335]
### What is your issue?

ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:

but i installed nedCDF4 use  pip install netCDF4

**Comment by dangnguyen1004** [comment]
i have the same issue. How do u solve it

**Comment by morestart** [comment]
emmm first,make sure the data is nc,second you must install netCDF4

**Comment by mlp6** [comment]
Since folks have asked questions since this was closed (and I had a similar issue), this `ValueError` exception can be raised in a misleading way if the file being specified does not exist.  The exception implies that it is a file format error, but it may just not exist.

**Comment by davidshumway** [comment]
> Since folks have asked questions since this was closed (and I had a similar issue), this `ValueError` exception can be raised in a misleading way if the file being specified does not exist. The exception implies that it is a file format error, but it may just not exist.

An empty file will raise the same `ValueError`.
