### ISSUE TITLE
failing flaky test: rasterio vrt

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6363]
### What happened?

This test is failing with a 404 error:

https://github.com/pydata/xarray/blob/95bb9ae4233c16639682a532c14b26a3ea2728f3/xarray/tests/test_backends.py#L4778-L4802

### Environment

N/A

**Comment by scottyhq** [comment]
Well, I changed that URL back in https://github.com/pydata/xarray/pull/3162 . But maybe it's best to just remove that test now that VRT and other GDAL/rasterio functionality is integrated with rioxarray? 

Unfortunately the AWS "landsat-pds" (public data set) was deprecated and not supported any longer, so maybe those images are finally being deleted  https://lists.osgeo.org/pipermail/landsat-pds/2020-December/000178.html "

**Comment by dcherian** [comment]
:+1: sounds good to me. Thanks @scottyhq
