### ISSUE TITLE
Zarr backend should avoid checking for invalid encodings

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6373]
### What is your issue?

The zarr backend has a list of "valid" encodings that needs to be updated any time zarr adds something new (e.g. https://github.com/pydata/xarray/pull/6348)

https://github.com/pydata/xarray/blob/53172cb1e03a98759faf77ef48efaa64676ad24a/xarray/backends/zarr.py#L215-L234

Can we get rid of this? I don't know the backends code well, but won't all our encoding parameters have been removed by this stage? The `raise_on_invalid` kwarg suggests so.

@tomwhite points out that zarr will raise a warning:
``` python
>>> zarr.create((1,), blah=1)
/Users/tom/miniconda/envs/sgkit-3.8/lib/python3.8/site-packages/zarr/creation.py:221: UserWarning: ignoring keyword argument 'blah'
  warn('ignoring keyword argument %r' % k)
<zarr.core.Array (1,) float64>
```

**Comment by dcherian** [comment]
Thanks @jhamman

**Comment by tomwhite** [comment]
Thanks for confirming @jhamman
