### ISSUE TITLE
broken link to pydap

### ISSUE THREAD

**Issue by thomasastanley** [pydata/xarray#6378]
### What happened?

at https://xarray.pydata.org/en/stable/user-guide/io.html#opendap, [Pydap’s cas module](http://pydap.readthedocs.io/en/latest/client.html#authentication) is broken

### What did you expect to happen?

it should point to https://www.pydap.org/en/latest/client.html#authentication

### Environment

en/stable

**Comment by max-sixty** [comment]
Thanks @thomasastanley ! If you'd be up for making the PR, that would be super.

**Comment by thomasastanley** [comment]
@max-sixty looking at this, https://docs.xarray.dev/en/latest/contributing.html#contributing-to-the-documentation, it seems like an awful lot of work to update one link. I'll leave it to someone who's doing the next documentation version.

**Comment by max-sixty** [comment]
You can also edit in GitHub directly!

**Comment by thomasastanley** [comment]
looks like it's fixed in [latest](https://xarray.pydata.org/en/latest/user-guide/io.html#opendap), just not stable. So close because this will sort itself out?

**Comment by keewis** [comment]
this has been fixed in #6262. It should have already sorted itself out because we released `2022.03.0` in the meantime, so there is something wrong with `stable`.

**Comment by keewis** [comment]
it seems `stable` timed out when we released (even though the tag itself completed successfully), so it was actually still pointing to `0.21.1`. I've triggered a new build which will hopefully succeed.

**Comment by keewis** [comment]
it succeeded, which means that this should be fixed. Thanks for the report, @thomasastanley!

**Comment by max-sixty** [comment]
Thanks @keewis !
