### ISSUE TITLE
apply_ufunc and Datasets with variables without the core dimension

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6391]
### Is your feature request related to a problem?

Consider this example 

```python
ds = xr.Dataset({"a": ("x", [1, 2, 3]), "b": ("y", [1, 2, 3])})
xr.apply_ufunc(np.mean, ds, input_core_dims=[["x"]])
```

This raises 
```
ValueError: operand to apply_ufunc has required core dimensions ['x'], but some of these dimensions are absent on an input variable: ['x']
```

because core dimension `x` is missing on variable `b`. This behaviour makes it annoying to use `apply_ufunc` on Datasets.

### Describe the solution you'd like

Add a new kwarg to `apply_ufunc` called `missing_core_dim` that controls how to handle variables without *all* input core dimensions. This kwarg could take one of two values:
1. `"raise"` - raise an error, current behaviour
2. `"copy"` - skip applying the function and copy the variable from input to output.
3. `"drop"`- skip applying the function and drop the variable.

**Comment by headtr1ck** [comment]
I would like to have a "ignore" option as well, such that I can do `input_core_dims=[["x","y"]]` in your example.

**Comment by dcherian** [comment]
The logic in `Dataset.reduce` is a bit nuanced, it keeps coordinate variables but runs the function on variables without core dimensions.

https://github.com/pydata/xarray/blob/e2b6f3468ef829b8a83637965d34a164bf3bca78/xarray/core/dataset.py#L6740-L6751

**Comment by shoyer** [comment]
Belatedly -- I like this idea!

**Comment by max-sixty** [comment]
Check out #8138 for a draft impl!
