### ISSUE TITLE
two Dataset objects reference the same numpy array memory block upon creation.

### ISSUE THREAD

**Issue by zoj613** [pydata/xarray#6395]
### What happened?

I tried creating two new `Dataset` objects using empty numpy arrays that I would later populate with values using integer indexing. To my surprise, I got output that was identical to for both datasets. After digging around, I discovered that the underlying numpy arrays of the two `Dataset` objects were identical. This confused me because I did not make a copy of one to create the other.

### What did you expect to happen?

Getting two separate objects with non-identical memory addresses for the numpy arrays they contain.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import pandas as pd
import numpy as np

def xarray_dataset():
    rng = np.random.default_rng(0)
    data_map = {
        "Tmin": rng.uniform(-1, 1, size=(3, 2, 2)),
        "Tmax": rng.uniform(-1, 1, size=(3, 2, 2)),
    }
    lon = [-99.83, -99.32]
    lat = [42.25, 42.21]
    time = pd.date_range("2014-09-06", "2016-09-06", periods=3)
    var_map = {"time": time, "lat": lat, "lon": lon}
    out_map = {name: (tuple(var_map), data_map[name]) for name in data_map}
    return xr.Dataset(data_vars=out_map, coords=var_map)


base = xarray_dataset()
dims = tuple(base.dims)
base_shape = (base.time.size, base.lat.size, base.lon.size)
var_map = {var: (dims, np.empty(base_shape)) for var in ("var_a", "var_b")}
coord_map = {
    "time": (("time",), base.time.values),
    "lon": (("lon",), base.lon.values),
    "lat": (("lat",), base.lat.values),
}
out1 = xr.Dataset(var_map, coords=coord_map)
out2 = xr.Dataset(var_map, coords=coord_map)

print(out1 is out2)   # False
print(out1.var_a.values is out2.var_a.values)  # True......but HOW?!
```

### Relevant log output

```Python
print(out1 is out2)   # False
print(out1.var_a.values is out2.var_a.values)  # True......but HOW?!
```

### Anything else we need to know?

It seems as though changing the lines:
```python
out1 = xr.Dataset(var_map, coords=coord_map)
out2 = xr.Dataset(var_map, coords=coord_map)
```
to
```python
out1  = xr.Dataset(var_map, coords=coord_map)
out2 = out1.copy(deep=True)
```

fixes the issue.

### Environment
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 5.15.25-1-lts
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.0
libnetcdf: 4.7.4

xarray: 0.21.1
pandas: 1.1.5
numpy: 1.22.0
scipy: 1.6.2
netCDF4: 1.5.8
pydap: None
h5netcdf: None
h5py: 3.6.0
Nio: None
zarr: 2.10.3
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.5.1
cartopy: None
seaborn: None
numbagg: None
fsspec: 2022.01.0
cupy: None
pint: None
sparse: None
setuptools: 60.0.4
pip: 21.3.1
conda: 4.11.0
pytest: 6.2.5
IPython: 8.0.1
sphinx: 4.4.0
```

**Comment by benbovy** [comment]
This is expected behavior: Xarray variable objects can wrap numpy arrays but generally they don't make copies of the underlying data. So it is possible that two different variables wrap the same numpy array, like in your example and in the example below. 

```python
data = np.array([1, 2, 3])

v1 = xr.Variable("x", data)
v2 = xr.Variable("x", data)

print(v1)
# <xarray.Variable (x: 3)>
# array([1, 2, 3])

print(v2)
# <xarray.Variable (x: 3)>
# array([1, 2, 3])

data[0] = 10

print(v1)
# <xarray.Variable (x: 3)>
# array([10, 2, 3])

print(v2)
# <xarray.Variable (x: 3)>
# array([10, 2, 3])
```

`Dataset.copy(deep=True)` makes a deep copy, thus copying the underlying data.

**Comment by zoj613** [comment]
> This is expected behavior: Xarray variable objects can wrap numpy arrays but generally they don't make copies of the underlying data. So it is possible that two different variables wrap the same numpy array, like in your example and in the example below.
> 
> ```python
> data = np.array([1, 2, 3])
> 
> v1 = xr.Variable("x", data)
> v2 = xr.Variable("x", data)
> 
> print(v1)
> # <xarray.Variable (x: 3)>
> # array([1, 2, 3])
> 
> print(v2)
> # <xarray.Variable (x: 3)>
> # array([1, 2, 3])
> 
> data[0] = 10
> 
> print(v1)
> # <xarray.Variable (x: 3)>
> # array([10, 2, 3])
> 
> print(v2)
> # <xarray.Variable (x: 3)>
> # array([10, 2, 3])
> ```
> 
> `Dataset.copy(deep=True)` makes a deep copy, thus copying the underlying data.

Thanks for the quick response. I wasn't aware of this. I had assumed a new Dataset object will have data that is a copy of the underlying `var_map` data pass into it. Maybe this could be mentioned as a note in the docstring somewhere?

**Comment by benbovy** [comment]
> Maybe this could be mentioned as a note in the docstring somewhere?

Yes that's a good idea. There's a brief mention in the docs here: https://docs.xarray.dev/en/stable/user-guide/data-structures.html#dictionary-like-methods, but I agree we could make it clearer.
