### ISSUE TITLE
DataArray.plot.pcolormesh with kwarg shading='gouraud'

### ISSUE THREAD

**Issue by miniufo** [pydata/xarray#6399]
### What happened?

Given a DataArray `da`, I try to plot with
```python
da.plot.pcolormesh(shading='flat')
```
and it works well.  But if I change shading to 'gouraud', it reports
``` python
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py in _pcolorargs(self, funcname, shading, *args, **kwargs)
   5709         else:    # ['nearest', 'gouraud']:
   5710             if (Nx, Ny) != (ncols, nrows):
-> 5711                 raise TypeError('Dimensions of C %s are incompatible with'
   5712                                 ' X (%d) and/or Y (%d); see help(%s)' % (
   5713                                     C.shape, Nx, Ny, funcname))

TypeError: Dimensions of C (256, 512) are incompatible with X (513) and/or Y (257); see help(pcolormesh)
```

Not sure if this relates to `xarray` or `matplotlib`.

### What did you expect to happen?

```python
da.plot.pcolormesh(shading='gouraud')
```
should works well as
```python
da.plot.pcolormesh(shading='flat')
```

### Minimal Complete Verifiable Example

```Python
import xarray as xr

ds = xr.tutorial.open_dataset('air_temperature')
ds.air[0].plot.pcolormesh(shading='gouraud')
```

### Relevant log output

```Python
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py in _pcolorargs(self, funcname, shading, *args, **kwargs)
   5709         else:    # ['nearest', 'gouraud']:
   5710             if (Nx, Ny) != (ncols, nrows):
-> 5711                 raise TypeError('Dimensions of C %s are incompatible with'
   5712                                 ' X (%d) and/or Y (%d); see help(%s)' % (
   5713                                     C.shape, Nx, Ny, funcname))

TypeError: Dimensions of C (25, 53) are incompatible with X (54) and/or Y (26); see help(pcolormesh)
```

### Anything else we need to know?

No

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('Chinese (Simplified)_China', '936')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.19.0
pandas: 1.3.1
numpy: 1.20.3
scipy: 1.6.2
netCDF4: 1.5.8
pydap: installed
h5netcdf: 0.12.0
h5py: 3.4.0
Nio: None
zarr: 2.8.1
cftime: 1.6.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.9.1
iris: None
bottleneck: 1.3.2
dask: 2021.08.0
distributed: 2021.08.0
matplotlib: 3.4.2
cartopy: 0.18.0
seaborn: 0.11.2
numbagg: None
pint: None
setuptools: 52.0.0.post20210125
pip: 21.0.1
conda: 4.11.0
pytest: 6.2.4
IPython: 7.26.0
sphinx: 4.0.2

**Comment by mathause** [comment]
Untested but can you try:

```python
da.plot.pcolormesh(shading='flat', infer_intervals=False)
```

**Comment by miniufo** [comment]
Thanks @mathause , that works well.  After searching the doc on `infer_intervals`, I still don't know why this is happening.

**Comment by mathause** [comment]
Yes, this may indeed not be entirely clear from the docstring. So if you have coordinates `[1, 2, 3]` and set `infer_interval=True` it assumes these are the center of the grid and it will infer the intervals, i.e. it will pass `[0.5, 1.5, 2.5, 3.5]` to `plt.pcolormesh`. For `shading='gouraud'` it however requires that the coordinates are the corners.

**Comment by miniufo** [comment]
OK, thanks again.  This is clear to me now.  So this should be a `matplotlib` problem.  I am closing this now.
