### ISSUE TITLE
Use pytest to simplify unit tests

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#640]
xray's unit testing system uses Python's standard `unittest` framework.  [pytest](http://pytest.org/latest/) offers a more flexible framework requiring less boilerplate code.  I recently (#638) introduced pytest into xray's CI builds.  This issue proposes incrementally migrating and simplifying xray's unit testing framework to pytest.

**Comment by MaximilianR** [comment]
Can this be closed @shoyer ?

We might want a policy for new tests to be more like pytests (functions, fixtures, `assert`) and less like unittests (inheritance, loops, `.assertX`) - probably as a preference rather than a mandate?

**Comment by shoyer** [comment]
> We might want a policy for new tests to be more like pytests (functions, fixtures, assert) and less like unittests (inheritance, loops, .assertX) - probably as a preference rather than a mandate?

Agreed. This could be good material for a contributor guide (e.g., `CONTRIBUTING.md`) if anyone wants to start on that.
