### ISSUE TITLE
add rolling_apply method or function

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#641]
Pandas has a generic [`rolling_apply`](http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.rolling_apply.html) function.  It would be nice to support a similar api on xray objects.  The api I have in mind is something like:

```Python
# DataArray.rolling_apply(window, func, min_periods=None, freq=None,
#                         center=False, args=(), kwargs={})
da.rolling_apply(7, np.mean)

**Comment by shoyer** [comment]
Yeah, I've been thinking about this one for a while (see also https://github.com/xray/xray/issues/130)

One possibly improved API over pandas is to make a rolling a method that produces `Rolling` object (similar to a `GroupBy`). You could write something like `array.rolling(time=7).mean()` to do aggregation and could also iterate like `for label, windowed in array.rolling(time=7)`.

**Comment by jhamman** [comment]
I like the idea of a `Rolling` object. It would great if we could leverage that option from the Pandas api when it comes around.

**Comment by shoyer** [comment]
Don't hold your breathe on the pandas API changes :). This will take some dedicated effort to make it happen in pandas. Frankly, it's probably easier to do it from scratch in xray where we don't have an old API with which to worry about retaining compatibility.

**Comment by jhamman** [comment]
@shoyer - I'm going to give creating a `Rolling` object a go. I have a paper I want to write using this functionality so there is a carrot motivating me.

**Comment by shoyer** [comment]
@jhamman  Great, looking forward to it!

**Comment by jreback** [comment]
@shoyer breath holding :) https://github.com/pydata/pandas/pull/11603

**Comment by jreback** [comment]
ohh, @shoyer you are thinking about defining ``__iter__`` on the ``Rolling``, for a custom aggregation? or other reason

**Comment by shoyer** [comment]
@jreback yes, for custom iteration like how you can use `__iter__` on groupby. It's not hard to do and it seems like it makes sense for consistency.

**Comment by jreback** [comment]
right, I think I will open a new issue for that. its actually a bit tricky as the iteration is done in cython itself, and its a marginal calculation anyhow (e.g. you just keep adding the new value, subtracting values that fall off the window).

**Comment by shoyer** [comment]
@jreback probably should move discussion here back to the pandas issue :). I don't see any reason why the iteration for moving windows (with `__iter__`) should be to be done in Cython. Basically it is just repeated slicing in a loop, e.g., something like
```
def __iter__(self):
   for n in range(...):
       yield self.obj[n : n + self.window] 
```

**Comment by jreback** [comment]
it's not how it's implemented

that is MUCH slower that marginal calculations

**Comment by shoyer** [comment]
Yes, of course :). Sometimes still a useful way to think about things,
though maybe it's better not to encourage it. I think it's a similar
situation for an explicit Python loop vs Cython for groupby aggregations,
but the Python loop actually works OK much of the time (e.g., we use it in
xray because we haven't written nd grouped aggregated in Cython or Numba
yet).

**Comment by jreback** [comment]
yep, agreed. anyhow I created a new issue for it https://github.com/pydata/pandas/issues/11704
