### ISSUE TITLE
FacetGrid padding goes very bad when cartopy projection specified

### ISSUE THREAD

**Issue by mjwillson** [pydata/xarray#6429]
### What happened?

When doing a faceted plot and specifying a projection (via e.g. `subplot_kws=dict(projection=ccrs.PlateCarree())`), the padding becomes very weird (often unusable) and strangely unstable to changes in `size` and `aspect`. For example this produces very bad results:

```python
data = xarray.DataArray(
    dims=('lat', 'lon', 'row', 'col'),
    data=np.ones((180, 360, 2, 2)),
    coords={'lon': np.arange(360), 'lat': np.arange(-90, 90)}
)
xarray.plot.pcolormesh(
    data,
    row='row',
    col='col',
    size=5,
    aspect=1.5,
    subplot_kws=dict(projection=ccrs.PlateCarree()),
)
```

![image](https://user-images.githubusercontent.com/4502/161090986-6dd7fd6b-5950-40aa-a78e-7699061b3a15.png)

whereas if you change `size` from 5 to 4, you suddenly get a much better (although still not quite right) layout:

![image](https://user-images.githubusercontent.com/4502/161091130-7e6b9580-d39c-4a89-9756-932bafff9ff0.png)

### What did you expect to happen?

I expected a layout closer to what you get if you comment out `subplot_kws=dict(projection=ccrs.PlateCarree()),` above:

![image](https://user-images.githubusercontent.com/4502/161091524-8993534f-efd7-45d3-9b4c-8e25099fb53e.png)

### Minimal Complete Verifiable Example

```Python
import xarray
import cartopy.crs as ccrs
import numpy as np

data = xarray.DataArray(
    dims=('lat', 'lon', 'row', 'col'),
    data=np.ones((180, 360, 2, 2)),
    coords={'lon': np.arange(360), 'lat': np.arange(-90, 90)}
)
xarray.plot.pcolormesh(
    data,
    row='row',
    col='col',
    size=5,
    aspect=1.5,
    subplot_kws=dict(projection=ccrs.PlateCarree()),
)
```

### Relevant log output

In the case where the layout isn't (as) broken, I see a warning: 

`.../xarray/plot/facetgrid.py:394: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations`

It seems that when tight_layout does manage to get applied, things really go wrong.
Perhaps at a minimum we could have a way to disable tight_layout? (which currently seems to be mandatory)

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.10 (stable, redacted, redacted) 
[Clang google3-trunk (e5b1b9edb8b6f6cd926c2ba3e1ad1b6f767021d6)]
python-bits: 64
OS: Linux
OS-release: 4.15.0-smp-920.39.0.0
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.UTF-8
LANG: None
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.6.1

xarray: 0.18.2
pandas: 1.1.5
numpy: 1.21.5
scipy: 1.2.1
netCDF4: 1.4.1
pydap: None
h5netcdf: 0.11.0
h5py: 3.2.1
Nio: None
zarr: 2.7.0
cftime: 1.0.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.3.4
cartopy: 0+unknown
seaborn: 0.11.1
numbagg: None
pint: None
setuptools: unknown
pip: None
conda: None
pytest: None
IPython: 3.2.3
sphinx: None

**Comment by mjwillson** [comment]
For now I am working around this using:

```python
  orig_tight_layout = mpl.figure.Figure.tight_layout
  mpl.figure.Figure.tight_layout = lambda *a: None
  try:
    xarray.plot.pcolormesh(...args...)
  finally:
    mpl.figure.Figure.tight_layout = orig_tight_layout
```

obviously you don't get a tight layout this way, but the proportions are a lot better.

**Comment by kmuehlbauer** [comment]
It looks like this is no issue any more with recent versions of the stack. At least I can't reproduce this. @mjwillson Please reopen, if you still encounter problems while plotting.
