### ISSUE TITLE
workaround to implement groupby_bins along dimension

### ISSUE THREAD

**Issue by nicrie** [pydata/xarray#6450]
### What is your issue?

There are several related issues dealing with `groupby` operations along individual/multiple dimensions (e.g. #1056 #924 ). I understand that this is work in progress. In the meantime, however, I'm looking for a quick solution to group over bins along a single dimension. Grouping over all dimensions works, e.g.:

```py
>>> da = xr.DataArray(np.random.randint(9, size=(5, 2, 3)), dims=['time', 'x', 'y'])
>>> da

xarray.DataArraytime: 5x: 2y: 3
array([[[1, 1, 5],
        [5, 6, 0]],

       [[3, 2, 4],
        [2, 8, 4]],

       [[0, 0, 2],
        [6, 3, 5]],

       [[4, 6, 4],
        [8, 2, 4]],

       [[6, 5, 3],
        [5, 2, 6]]])
Coordinates: (0)
Attributes: (0)

>>> da.groupby_bins(da, bins=[0, 5, 10]).count()

xarray.DataArray 'group' group_bins: 2
array([20,  7])
Coordinates: (1)
Attributes: (0)
```

However, it fails when trying to apply the operator only along a specific dimension, e.g.:
```py
>>> da.groupby_bins(da, bins=[0, 5, 10]).count('time')

ValueError: cannot reduce over dimensions ['time']. expected either '...' to reduce over all dimensions or one or more of ('stacked_time_x_y',).
```
I don't mind if the workaround is a bit ugly as long as it works ;)

**Comment by dcherian** [comment]
Use [xhistogram](https://xhistogram.readthedocs.io/en/latest/) or [flox](https://flox.readthedocs.io/en/latest/generated/flox.xarray.xarray_reduce.html).
