### ISSUE TITLE
Writing a a dataset to .zarr in a loop makes all the data NaNs

### ISSUE THREAD

**Issue by tbloch1** [pydata/xarray#6456]
### What happened?

I have lots (61) pickled pandas dataframes that I'm trying to convert from pickle/pandas to zarr/xarray. Since the dataframes are large (10000x2048) I can't load them all into memory. To get around this I'm (MCVE below) looping through the pickle files, reading them into dataframes, constructing DataArrays and then Datasets from the data, concatinating the dataset with the previous dataset and updating the dataset to point to this new concatenated dataset.

Since I didn't want to use up too much memory, I'm also periodically writing the Dataset to .zarr in the loop and reopening it (hoping to make use of dask storing data on disk?).

When I do this however, the final dataset ends up being all NaNs.

### What did you expect to happen?

I expected the final dataset to contain all the concatenated data.

### Minimal Complete Verifiable Example

```Python
import pandas as pd
import numpy as np
import glob
import xarray as xr
from tqdm import tqdm

# Creating pkl files
[pd.DataFrame(np.random.randint(0,10, (1000,500))).astype(object).to_pickle('df{}.pkl'.format(i)) for i in range(4)]

fnames = glob.glob('*.pkl')

df = pd.read_pickle(fnames[0])
df.columns = np.arange(0,500).astype(object) # the real pkl files contain all objects
df.index = np.arange(0,1000).astype(object)
df = df.astype(np.float32)

ds = xr.DataArray(df.values, dims=['fname', 'res_dim'],
                  coords={'fname': df.index.values, 'res_dim': df.columns.values})
ds = ds.to_dataset(name='low_dim')

for idx, fname in enumerate(tqdm(fnames[1:])):
    df = pd.read_pickle(fname)
    df.columns = np.arange(0,500).astype(object)
    df.index = np.arange(0,1000).astype(object)
    df = df.astype(np.float32)


    ds2 = xr.DataArray(df.values, dims=['fname', 'res_dim'],
                  coords={'fname': df.index.values, 'res_dim': df.columns.values})
    ds2 = ds2.to_dataset(name='low_dim')

    ds = xr.concat([ds, ds2], dim='fname')
    ds['fname'] = ds.fname.astype(str)
    if (idx%2 == 0) & (idx !=0):
        ds.to_zarr('zarr_bug.zarr', mode='w')
        ds = xr.open_zarr('zarr_bug.zarr')

ds.to_zarr('zarr_bug.zarr', mode='w')
ds = xr.open_zarr('zarr_bug.zarr')

print(ds.low_dim.values)
```

### Relevant log output

```Python
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
```

### Anything else we need to know?

If I get rid of the loop saving, everything works normally.

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.11 (main, Mar 28 2022, 10:10:35) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 5.11.0-27-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.0
libnetcdf: 4.7.4

xarray: 2022.3.0
pandas: 1.4.1
numpy: 1.21.0
scipy: 1.8.0
netCDF4: 1.5.8
pydap: installed
h5netcdf: 1.0.0
h5py: 3.6.0
Nio: None
zarr: 2.11.1
cftime: 1.6.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: 0.9.10.1
iris: None
bottleneck: None
dask: 2022.03.0
distributed: 2022.3.0
matplotlib: 3.5.1
cartopy: None
seaborn: 0.11.2
numbagg: None
fsspec: 2022.02.0
cupy: None
pint: None
sparse: None
setuptools: 58.0.4
pip: 21.2.4
conda: None
pytest: None
IPython: 8.1.1
sphinx: None

**Comment by max-sixty** [comment]
Hi @tbloch1 — thanks for the issue

So I understand — is this loading the existing dataset, adding one a slice, and then writing the whole result? Have you considered using `mode='a'` if you want to write from different processes?

For the example — would it be possible to slim that down a bit further? Does it happen with with one read & write after the initial one?

**Comment by delgadom** [comment]
@tbloch1 following up on Max's suggestion - it looks like you might be overwriting the file with every iteration. See the docs on [ds.to_zarr](https://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_zarr.html) - `mode='w'` will overwrite the file while `mode='a'` will append. That said, you still would need your indices to not overlap. How are you distinguishing between the files? is each one a different point in time?

To me, this doesn't seem likely to be a bug, but is more of a usage question. Have you tried asking on stackoverflow with the xarray tag?

**Comment by max-sixty** [comment]
> Have you tried asking on stackoverflow with the xarray tag?

Or GH Discussions! But it would need a smaller MCVE

**Comment by tbloch1** [comment]
@max-sixty - I've tried to slim it down below (no loop, and only one save). From the print statements, it's clear that before overwriting the .zarr `ds3` is working correctly, but once `ds3` is saved it breaks the data corresponding to the initial save (now all NaNs). I am guessing this is due to trying to read from and save over the same data, but I wouldn't have expected it to be a problem if it was loading the chunks into memory during the saving.

```
df1 = pd.read_pickle(fnames[0])
df1.columns = np.arange(0,500).astype(object) # the real pkl files contain all objects
df1.index = np.arange(0,1000).astype(object)
df1 = df1.astype(np.float32)

ds = xr.DataArray(df1.values, dims=['fname', 'res_dim'],
                  coords={'fname': df1.index.values, 'res_dim': df1.columns.values})
ds = ds.to_dataset(name='low_dim')

ds.to_zarr('zarr_bug.zarr', mode='w')
ds1 = xr.open_zarr('zarr_bug.zarr')


df2 = pd.read_pickle(fnames[1])
df2.columns = np.arange(0,500).astype(object)
df2.index = np.arange(0,1000).astype(object)
df2 = df2.astype(np.float32)

ds2 = xr.DataArray(df2.values, dims=['fname', 'res_dim'],
                coords={'fname': df2.index.values, 'res_dim': df2.columns.values})
ds2 = ds2.to_dataset(name='low_dim')

ds3 = xr.concat([ds1, ds2], dim='fname')

ds3['fname'] = ds3.fname.astype(str)

print(ds3.low_dim.values)

ds3.to_zarr('zarr_bug.zarr', mode='w')

print(ds3.low_dim.values)
```

The output:

```
[[7. 8. 4. ... 9. 6. 7.]
 [0. 4. 5. ... 9. 7. 6.]
 [3. 4. 3. ... 1. 6. 1.]
 ...
 [4. 0. 4. ... 5. 6. 9.]
 [5. 2. 5. ... 1. 7. 1.]
 [8. 9. 7. ... 4. 4. 1.]]
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [ 4.  0.  4. ...  5.  6.  9.]
 [ 5.  2.  5. ...  1.  7.  1.]
 [ 8.  9.  7. ...  4.  4.  1.]]
```

**Comment by tbloch1** [comment]
@delgadom - In the example it's saving every iteration, but in my actual code it's much less frequent. I figured there was probably a better way to achieve the same thing, but it still doesn't seem like the expected behaviour, which is why I thought I should raise the issue here.

The files are just sequentially names (as in my example), but the indices of the resulting dataframes are a bunch of unique strings (file-paths, not dates).

If I try `mode='a', append_dim='fname'` in my MCVE I get a TypeError:

`TypeError: ufunc 'rint' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

**Comment by max-sixty** [comment]
@tbloch1 it doesn't copy in to someone else's python atm — that's the "C" part of MCVE...

**Comment by tbloch1** [comment]
@max-sixty could you explain which bit isn't working for you? The initial example I shared works fine in colab for me, so that might be a you problem. The second one required specifying the chunks when making the datasets (I've editted above).

[Here's a link to the colab](https://colab.research.google.com/drive/1H6ugbz9Ug208x5fLpmvNxIBdKgASjz7V?usp=sharing).

It's worth noting that the way in which the dataset is broken does seem to be slightly different in each of these examples - in the former example all data becomes NaN, in the latter example only the initially saved data becomes NaN.

**Comment by delgadom** [comment]
> In the example it's saving every iteration, but in my actual code it's much less frequent

when I said "you're overwriting the file every iteration" I meant to put the emphasis on  _overwiting_. by using `mode='w'` instead of `mode='a'` you're telling zarr to delete the file if it exists and the re-create it every time `to_zarr` is executed.

See the docs on [`xr.Dataset.to_zarr`](https://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_zarr.html):

> **mode** (`{"w", "w-", "a", "r+", None}`, *optional*) – Persistence mode: “w” means create (overwrite if exists); “w-” means create (fail if exists); “a” means override existing variables (create if does not exist); “r+” means modify existing array values only (raise an error if any metadata or shapes would change). The default mode is “a” if `append_dim` is set. Otherwise, it is “r+” if `region` is set and `w-` otherwise.

This interpretation of mode is consistent across all of python - see the docs for [python builtins: open](https://docs.python.org/3/library/functions.html#open)

Change your writes to `ds3.to_zarr('zarr_bug.zarr', mode='a')` as Max suggested :)

**Comment by tbloch1** [comment]
@delgadom thanks! This did help with my actual code, and I've now done my processing.

But this bug report was more about the fact that overwriting was converting data to NaNs (in two different ways depending on the code apparently).

In my case there is no longer any need to do the overwriting, but this doesn't seem like the expected behaviour of overwriting, and I'm sure there are some valid reasons to overwrite data - hence me opening the bug report.

If overwriting is supposed to convert data to NaNs then I guess we could close this issue, but I'm not sure that's intended?

**Comment by max-sixty** [comment]
> @max-sixty could you explain which bit isn't working for you? The initial example I shared works fine in colab for me, so that might be a you problem. The second one required specifying the chunks when making the datasets (I've editted above).

Right, you changed the example after I responded


> But this bug report was more about the fact that overwriting was converting data to NaNs (in two different ways depending on the code apparently).
> 
> In my case there is no longer any need to do the overwriting, but this doesn't seem like the expected behaviour of overwriting, and I'm sure there are some valid reasons to overwrite data - hence me opening the bug report.

Something surprising is indeed going on here. To focus on the surprising part;

```python
print(ds3.low_dim.values)

ds3.to_zarr('zarr_bug.zarr', mode='w')

print(ds3.low_dim.values)
```

returns:

```
[[2. 3. 2. ... 8. 0. 9.]
 [6. 2. 6. ... 2. 4. 3.]
 [0. 8. 8. ... 6. 5. 4.]
 ...
 [1. 0. 5. ... 2. 0. 3.]
 [5. 5. 7. ... 9. 6. 2.]
 [5. 7. 8. ... 4. 8. 9.]]
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [ 1.  0.  5. ...  2.  0.  3.]
 [ 5.  5.  7. ...  9.  6.  2.]
 [ 5.  7.  8. ...  4.  8.  9.]]
```

Similarly:

```python

In [50]: ds3.low_dim.count().compute()
Out[50]:
<xarray.DataArray 'low_dim' ()>
array(1000000)

In [51]: ds3.to_zarr('zarr_bug.zarr', mode='w')
Out[51]: <xarray.backends.zarr.ZarrStore at 0x16a27c6d0>

In [55]: ds3.low_dim.count().compute()
Out[55]:
<xarray.DataArray 'low_dim' ()>
array(500000)
```

So it's changing the result in memory just from writing to the Zarr store. I'm not sure what the cause is.

We can still massively reduce the size of this example — it's currently doing pickling, got a bunch of repeated code, etc. Does it work without the pickling? What if `ds3 = xr.concat([ds1, ds1.copy(deep=True)])`, etc.

**Comment by max-sixty** [comment]
Closing as no MCVE, but feel free to reopen with one
