### ISSUE TITLE
restrict stale bot

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6497]
### What is your issue?

We have some stale issue but not that many.

Can we restrict the bot to only issues that  are  untagged, or tagged as "usage  question" or  are not  assigned to a "project" instead?  This might reduce a lot of the noise.

**Comment by max-sixty** [comment]
Let me look. 

We can also push the time back out to 700 days. I tried to "wake it up" by changing the configs — it seemed to have stopped. But that means we get 2 issues / hour until the issues from 600-700 days stale are all marked.

It is a bit noisy. Though OTOH I have been more engaged this weekend than in a while!
