### ISSUE TITLE
Added `automerge`

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#6499]
### What is your issue?

@pydata/xarray 

Because our pipeline takes a while, it can be helpful to have an option to "merge when tests pass" — I've now set that up. So you can click here and it'll do just that.

Someone annoyingly / confusingly, the "required checks" need to be specified manually, in https://github.com/pydata/xarray/settings/branch_protection_rules/2465574 — there's no option for just "all checks".

So if we change the checks — e.g. add Python 3.11 — that list needs to be updated. If we remove a check from the our CI and don't update the list, it won't be possible to merge the PR without clicking the red "Admin Override" box — so we should keep it up to date.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/5635139/163838836-62ae9859-51d2-44af-b246-d3a09f95b11d.png">

**Comment by max-sixty** [comment]
Once it's clicked it looks like: 

<img width="936" alt="image" src="https://user-images.githubusercontent.com/5635139/163839628-ba21fdc1-748b-4537-9dfd-473f115848cd.png">

**Comment by TomNicholas** [comment]
Oh that's awesome!
