### ISSUE TITLE
DOC: minor break in doc build?

### ISSUE THREAD

**Issue by maxim-lian** [pydata/xarray#651]
http://xray.readthedocs.org/en/stable/generated/xray.DataArray.count.html

`name` doesn't seem to be working correctly:

```
Dimension(s) over which to apply {name}.
```

**Comment by shoyer** [comment]
This is actually still an issue: http://xray.readthedocs.org/en/stable/generated/xarray.DataArray.count.html

**Comment by MaximilianR** [comment]
Ah whoops. Thanks for reopening

**Comment by maxim-lian** [comment]
fixed
