### ISSUE TITLE
Opening a grib file leaves a .idx in the directory

### ISSUE THREAD

**Issue by isodrosotherm** [pydata/xarray#6512]
### What is your issue?

I don't remember this being an issue before, but when I open a .grib2 file a .idx file remains in the directory when the script is finished running. I'm using:

```
with xr.open_dataset(filepath) as ds:
    ...
```

I'm using `xarray version 0.19.0` on `python version 3.8.13`

**Comment by max-sixty** [comment]
Please could you confirm on the latest release of xarray, include the `xr.show_versions()`, and a MCVE?

**Comment by isodrosotherm** [comment]
here is the `xr.show_versions()`
```
>>> xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:06:49) 
[Clang 12.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 21.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.19.0
pandas: 1.3.2
numpy: 1.20.3
scipy: 1.7.1
netCDF4: 1.5.7
pydap: installed
h5netcdf: 1.0.0
h5py: 3.6.0
Nio: None
zarr: 2.11.3
cftime: 1.5.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.9
cfgrib: 0.9.9.1
iris: None
bottleneck: None
dask: 2021.10.0
distributed: 2021.10.0
matplotlib: 3.4.3
cartopy: 0.20.0
seaborn: None
numbagg: None
pint: None
setuptools: 52.0.0.post20210125
pip: 21.0.1
conda: None
pytest: None
IPython: 8.1.1
sphinx: None
```


Here's [2022.grib.zip](https://github.com/pydata/xarray/files/8559356/2022.grib.zip) a file you can use for testing. And I believe this code should satisfy the MCVE request
```
import xarray as xr

fp = '2022.grib'

with xr.open_dataset(fp, backend_kwargs={'filter_by_keys': {'shortName': 'i10fg'}}) as ds:
    m = ds.sel(time=ds.time.dt.month.isin([3]))
```

this code produced this [2022.grib.02ccc.idx.zip](https://github.com/pydata/xarray/files/8559372/2022.grib.02ccc.idx.zip) file and it didn't delete it once the code finished running.

Please let me know if you need any more info!

**Comment by max-sixty** [comment]
I can repro, thanks @isodrosotherm .

It looks like we're passing this through to `cfgrib.open_file`: https://github.com/pydata/xarray/blob/main/xarray/backends/cfgrib_.py#L118.

Is this an xarray issue though? Or should upstream be cleaning up that file, assuming it should be cleaned up?

**Comment by dcherian** [comment]
cc @alexamici

**Comment by kmuehlbauer** [comment]
You could point the index-file location to a temporary-folder, something along the lines of https://github.com/ecmwf/cfgrib/issues/275#issuecomment-1010002087.

**Comment by alexamici** [comment]
@isodrosotherm setting `indexpath==''` will suppress the use of the external index file.

**Comment by max-sixty** [comment]
Should we by default use a temp file? or is there some benefit to retaining the index file locally? (asking as someone with very little context{

**Comment by alexamici** [comment]
> Should we by default use a temp file? or is there some benefit to retaining the index file locally? (asking as someone with very little context

Opening the a GRIB for the first time requires reading the whole file and saving the index to disk makes all subsequent open much faster. I took the decision to default to writing, but IMO the real issue is that it is not well documented how to switch it off 😅

**Comment by max-sixty** [comment]
Cool, if you think we should document it better (or write to a temp file by default, less surprising perhaps?), then that's great, let's add the issue; it doesn't have to be you who implements.

**Comment by mabhijithn** [comment]
> @isodrosotherm setting `indexpath=''` will suppress the use of the external index file.

Unfortunately, even with this argument, the following command seems to be looking for the indexfile? I am unable to read the file for the second time. 
I get the following error:
```
raise EOFError("No valid message found in file: %r" % self.path)
EOFError: No valid message found in file:
```
My versions are `cfgrib==0.9.9.0` and `xarray==0.16.2`.
I am not using the latest version as I found [here](https://github.com/ecmwf/cfgrib/issues/292) that the newer combination has this issue. Kindly advise.
```python
ds_sea = xr.open_dataset(
            filename,
            engine="cfgrib",
            backend_kwargs={
                "filter_by_keys": {"typeOfLevel": "meanSea"},
                "indexpath": "",
            },
        )
```

**Comment by chiaral** [comment]
I confirm having bumped into this issue of `idx` file not playing nicely. I ended up adding a little function to remove the idx before doing any new downloads. 

In particular what happened to me was something slightly different.

It happened to me when I was crawling through GFS files, those grib files don't have the date in the file name but the date is in the folder  (i.e. https://ftpprd.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.20230923/00/atmos/). so I can have multiple files named `gfs.t00z.pgrb2.0p25.f058` coming from different dates.

My workflow was: downloading - opening grib (either xarray or cfgrib)- compute whatever - delete file. When I then moved to the next date,  the `idx` file that was present in the folder would not play nicely. Sometimes even if I used `filterbykeys` and the `shortname` I'd get the wrong variable. it was very intermittent and not consistent. It was reusing the idx file because it was there and the idx file was wrong because it had been generated for another file. 

Just reporting it as a FYI. Since probably my behaviour was expected (since the idx file had been generated based on another grib file), but I am reporting it since it took me a bit to figure it out.

**Comment by mabhijithn** [comment]
> I confirm having bumped into this issue of `idx` file not playing nicely. I ended up adding a little function to remove the idx before doing any new downloads.
> 
> In particular what happened to me was something slightly different.
> 
> It happened to me when I was crawling through GFS files, those grib files don't have the date in the file name but the date is in the folder (i.e. https://ftpprd.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.20230923/00/atmos/). so I can have multiple files named `gfs.t00z.pgrb2.0p25.f058` coming from different dates.
> 
> My workflow was: downloading - opening grib (either xarray or cfgrib)- compute whatever - delete file. When I then moved to the next date, the `idx` file that was present in the folder would not play nicely. Sometimes even if I used `filterbykeys` and the `shortname` I'd get the wrong variable. it was very intermittent and not consistent. It was reusing the idx file because it was there and the idx file was wrong because it had been generated for another file.
> 
> Just reporting it as a FYI. Since probably my behaviour was expected (since the idx file had been generated based on another grib file), but I am reporting it since it took me a bit to figure it out.

How did you get around to solve this? If you have to re-open the same file without any issues?

**Comment by dcherian** [comment]
This is a `cfgrib` issue that we can't do much about.
