### ISSUE TITLE
Mypy workflow failing

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#6551]
### What is your issue?

I can't work out what is causing this, and can't repro locally, though I've tried to ensure the same things are installed.

The bisect is:
- Passes: https://github.com/pydata/xarray/runs/6233389985?check_suite_focus=true
- Fails: https://github.com/pydata/xarray/runs/6237267544?check_suite_focus=true

Probably we have to skip it in the meantime, which is a shame

Is there a better way of locking the dependency versions so we can rule that out? I generally don't use conda, and poetry is great at this. Is there a conda equivalent?

**Comment by headtr1ck** [comment]
This is resolved, right?

**Comment by andersy005** [comment]
It appears to have been fixed in 

- https://github.com/pydata/xarray/pull/6581

Closing this. Feel free to reopen if I missed something....

**Comment by max-sixty** [comment]
Thanks for spotting @headtr1ck & @andersy005
