### ISSUE TITLE
processing errror when using xr.dataset[:,::-10,::10]

### ISSUE THREAD

**Issue by jesieleo** [pydata/xarray#6553]
### What happened?

These two should equals , but not . The coords of latitude are right , but the data is wrong.

### What did you expect to happen?

> these two should equals ,but not , latitude was wrong
> 
 ```
> import numpy as np
> import xarray as xr
> data1 = xr.open_dataset('test1111111.nc')
 ```
> ! ! ! Note，important: After running the second sentence and running the first sentence again, the result will change so that the first sentence is normal! ! ! !
> ```
> #wrong code
> In[37]: np.array(data1.sel(time='1990-1' , isobaricInhPa=200 ).z[: , ::-10 , ::10])
> Out[37]: 
> array([[[109890.25, 109890.75, 109890.75, ..., 109888.25, 109889.25,
> 109889.75],
> [110014.75, 110017.75, 110020.75, ..., 110006.75, 110009.75,
> 110012.25],
> [110109.75, 110115.25, 110119.75, ..., 110098.25, 110101.75,
> 110106.25],
> ...,
> [107800.25, 107824.75, 107845.75, ..., 107719.75, 107747.25,
> 107775.25],
> [107684.25, 107697.75, 107709.75, ..., 107641.25, 107656.25,
> 107670.25],
> [107585.75, 107587.75, 107589.75, ..., 107578.75, 107581.25,
> 107583.25]]], dtype=float32)
> ```
> 
> ```
> #right code
> In[38]: np.array( data1.sel(time='1990-1' , isobaricInhPa=200 ).z)[: , ::-10 , ::10]
> Out[38]: 
> array([[[109798.75, 109798.75, 109798.75, ..., 109798.75, 109798.75,
>          109798.75],
>         [109915.75, 109916.75, 109917.25, ..., 109912.75, 109914.25,
>          109915.25],
>         [110037.75, 110040.25, 110043.75, ..., 110028.25, 110030.25,
>          110034.25],
>         ...,
>         [107776.25, 107797.25, 107818.75, ..., 107702.75, 107727.25,
>          107753.25],
>         [107662.25, 107673.25, 107683.25, ..., 107626.75, 107638.75,
>          107650.75],
>         [107571.25, 107571.25, 107571.25, ..., 107571.25, 107571.25,
>          107571.25]]], dtype=float32)
> ```
> 
> The latitude is really messed up. [test1111111.zip](https://github.com/pydata/xarray/files/8596782/test1111111.zip)
> 

I think it is caused by a logic error, this code sometimes works fine, however when reading this file an exception occurs, although the coords are correct, the internal data is completely wrong, please check the processing logic.

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: en
LOCALE: ('Chinese (Simplified)_China', '936')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 2022.3.0
pandas: 1.4.2
numpy: 1.22.3
scipy: 1.7.3
netCDF4: 1.5.7
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: 0.9.10.1
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.5.1
cartopy: 0.20.2
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
setuptools: 56.0.0
pip: 22.0.4
conda: None
pytest: None
IPython: 8.3.0
sphinx: 4.5.0

</details>

**Comment by headtr1ck** [comment]
`isobaricInhPa` is a scalar coordinate, so the `sel` is not working for me.
If I remove it, I cannot reproduce the result, I get the correct result both times.

**Comment by max-sixty** [comment]
@jesieleo I appreciate your interest in xarray. But please read the instructions in the bug report and produce an MVCE in a new issue. I understand that requires some work on your end, but please recognize that we're all volunteers here, and so have set up a system to allow the greatest number of issues to be addressed.

ref https://github.com/pydata/xarray/issues/6547

**Comment by jesieleo** [comment]
> `isobaricInhPa`是一个标量坐标，所以不适合我。如果我删除它，我无法重现结果，我两次都得到正确的结果。`sel`

First of all thanks for your answer.
In fact, this was originally a vector coordinate, but I chose one to send u. This time I upload a version of isobaricInhPa which is a vector coordinate, please select.

The latitude should be 73 but 72 ,but,when I try to check latitude by itself, it works fine again, which makes me think it's a bug.
```
import xarray as xr
data3 = xr.open_dataset('test0001.nc')
# correct
a = data3.sel(time='1979-1',isobaricInhPa=200).z[:, The latitude in ::10,::10]

##### The latitude should be 73 but 72
# wrong (latitude wrong,latituede is 72)
b = data3.sel(time='1979-1',isobaricInhPa=200).z[:, The latitude in ::-10,::10]
# correct(latitude wrong,latituede is 73)
b = data3.sel(time='1979-1',isobaricInhPa=200).z[:, The latitude in ::-10,::10].latitude
```

latitude should be 73, but this is 72, and the coordinates do not correspond to the data

[test0001.zip](https://github.com/pydata/xarray/files/8600812/test0001.zip)
