### ISSUE TITLE
sortby with ascending=False should create an index

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#6555]
### Is your feature request related to a problem?

When using `sortby` with `ascending=False` on a DataArray/Dataset **without** an explicit index, the data gets correctly reversed, but it is not possible to tell anymore which ordering the data has.

If an explicit index (like [0, 1, 2]) exists, it gets correctly reordered and allowes correct aligning.

### Describe the solution you'd like

For consistency with aligning xarray should create a new index that indicates that the data has been reordered, i.e. [2, 1, 0].

Only downside: this will break code that relies on non-existent indexes.

**Comment by max-sixty** [comment]
Would we then have a different schema for different values of `ascending`?

If that's correct I would vote against this; I empathize with the confusion, but then the caller can add an index, and generally we don't want different values of arguments to create different schema without a very obvious and explicit connection between them.

Tbh even if the proposal is to add the index for any value of `ascending`, I'd be marginally against; it's not what I'd expect as a user. But open-minded on this.

(Thanks for adding the issue @headtr1ck , hope this comes across as constructive)

**Comment by headtr1ck** [comment]
I guess my understanding of indexes was: "no index" == "default index ~range(0,n)".

Therefore, if no index exists and ascending=True, no index in the output is correct.

But then again I agree that it is easy for users to add an index.

**Comment by max-sixty** [comment]
> I guess my understanding of indexes was: "no index" == "default index ~range(0,n)".

Yeah — that is the case in pandas. But in xarray, we can have dims without indexes, so adding one is making a change...

**Comment by headtr1ck** [comment]
Ok, then I'm fine with the current state.
