### ISSUE TITLE
`DataArray.nbytes` listed twice in API doc block

### ISSUE THREAD

**Issue by zmoon** [pydata/xarray#6565]
Here: https://github.com/pydata/xarray/blame/708204370ef168f35f250ca75e666246ae1420f6/doc/api.rst#L289-L295

**Comment by zmoon** [comment]
Also, I guess it is pretty self-explanatory, but perhaps some documentation could be added, maybe at least a reference to `numpy.ndarray.nbytes`.

**Comment by dcherian** [comment]
See also #4842 . This would be a nice and fairly simple PR if you're up for it :)

**Comment by zmoon** [comment]
References:
* not listed in [array API attributes](https://data-apis.org/array-api/latest/API_specification/array_object.html#attributes)
* documented [in numpy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.nbytes.html)
* slightly documented [in dask](https://docs.dask.org/en/stable/generated/dask.array.Array.nbytes.html)
* slightly more documented [in cupy](https://docs.cupy.dev/en/stable/reference/generated/cupy.ndarray.html#cupy.ndarray.nbytes)
