### ISSUE TITLE
are there methods to abstract coordinate variables?

### ISSUE THREAD

**Issue by rafa-guedes** [pydata/xarray#658]
Hi guys,

just wondering if there are, or if you plan to implement, some methods similar to cdms2's getLongitude(), getLatitude(), getTime(), getLevel(), which allow reading these coordinate variables without knowing a prior how they are called in the netcdf files?

Thanks

**Comment by shoyer** [comment]
The short answer is that this is out of scope for xarray, but could be implemented in a library that wraps xarray to add additional processing of CF-conventions.
