### ISSUE TITLE
docs: broken link at https://xarray.pydata.org/en/stable/user-guide/terminology.html

### ISSUE THREAD

**Issue by phil-blain** [pydata/xarray#6582]
### What happened?

The link to https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_data_set_components.html#variables in the "Variables" heading is broken, I think it should now link to the NetCDF user guide: https://docs.unidata.ucar.edu/nug/current/netcdf_data_set_components.html#variables

### What did you expect to happen?

Link works

### Minimal Complete Verifiable Example

```Python
1. Click on the  "NetCDF-like variable" link on page https://xarray.pydata.org/en/stable/user-guide/terminology.html. 
2. 404
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
N.A.
```

### Environment

<details>

N.A.
</details>

**Comment by dcherian** [comment]
Thanks @phil-blain This should be a really easy fix if you're up for contributing: See https://github.com/pydata/xarray/blob/main/doc/user-guide/terminology.rst for the source and https://docs.xarray.dev/en/stable/contributing.html#contributing-to-the-documentation for instructions

**Comment by phil-blain** [comment]
Yeah, I just wanted to confirm this was indeed the intended link target:)

**Comment by phil-blain** [comment]
Closing, I forgot the "Closes" trailer when I authored my commit and PR.
