### ISSUE TITLE
xr.polyval: return nan when evaluating a curve with nan coefficients

### ISSUE THREAD

**Issue by FRidh** [pydata/xarray#6619]
### What happened?

Evaluating the coefficients from a polyfit that happened to be none results in a polyval evaluation of zeros.

### What did you expect to happen?

 I expect the result to be nan when an input is nan as well. Note passing in `skipna=True` to `polyfit` does not make a difference.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np
arr = xr.DataArray(np.ones(100)*np.nan, dims=["time"], coords={"time": np.arange(100)})
xr.polyval(arr.time, arr.polyfit(dim="time", deg=1))
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>
: None
seaborn: None
numbagg: None
fsspec: 2022.01.0
cupy: None
pint: None
sparse: None
setuptools: 61.2.0.post0
pip: None
conda: None
pytest: 7.1.1
IPython: 8.2.0
sphinx: 4.5.0
</details>

**Comment by dcherian** [comment]
Fixed on main thanks to @headtr1ck !

<img width="812" alt="image" src="https://user-images.githubusercontent.com/2448579/169077234-fba893bf-9655-4085-ac18-fd6ae1a81406.png">
