### ISSUE TITLE
Why am I getting 'Passing method to Float64Index.get_loc is deprecated' error when using the .sel method to extract some data, and how do I solve it?

### ISSUE THREAD

**Issue by choochipastol** [pydata/xarray#6625]
### What is your issue?

`climateModels['CSIRO-QCCCE-CSIRO-Mk3-6']['RCP 45'][2]['tasmax'].sel(lon = 74, lat= 31, time = '2041-06-16', method='nearest').data[0]`

`\anaconda3\lib\site-packages\xarray\core\indexes.py:234: FutureWarning: Passing method to Float64Index.get_loc is deprecated and will raise in a future version. Use index.get_indexer([item], method=...) instead.

I don't know much about how to solve this issue, can anyone help me out please?

**Comment by keewis** [comment]
what version of `xarray` are you using? If I remember correctly, we fixed this a few versions ago so you should be able to upgrade to resolve this.

**Comment by son-ra** [comment]
I am also getting the same error message using a `.sel` , my version of xarray is '0.20.1'.  Should this issue be fixed in that version?

**Comment by max-sixty** [comment]
I'm not sure on the exact version — but do we see this in the latest release? https://github.com/pydata/xarray/releases/tag/v2022.03.0

**Comment by max-sixty** [comment]
I'll close but please open an bug report if we do see it.

**Comment by zrxdaly** [comment]
i got the same warning using `Va_Dataset.interp(x = section)`. 

`lib/python3.9/site-packages/xarray/core/missing.py:562: FutureWarning: Passing method to Float64Index.get_loc is deprecated and will raise in a future version. Use index.get_indexer([item], method=...) instead.`

should we do sm about it?
