### ISSUE TITLE
`restore_coord_dims=True` not work for `resample`

### ISSUE THREAD

**Issue by kongdd** [pydata/xarray#6627]
### What happened?

The original dimension is [lon, lat, time]. But applied resample, the dimension becomes [time, lon, lat]. 
Is this normal?

```python
import xarray as xr
f = "ERA5_202205_Asia_prcp.nc"
ds_raw = xr.open_dataset(f)

ds_raw.resample(time = "6h", restore_coord_dims = True).sum()
```

### What did you expect to happen?
> Dimension in the same order.

**Comment by max-sixty** [comment]
Is this still an issue? Could we have an MCVE if so?
