### ISSUE TITLE
Literal type of engine argument incompatible with custom backends

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#6632]
### What is your issue?

In the recent typing improvements the `engine` argument for `open_dataset` was changed from Str to a Literal of xarrays internal engines.
This will cause problems for all third party backend plugins.

We have several possibilities:

1. I don't know if there is a way to know installed backends at type checking time. Then we could add this support. (I doubt this is possible seeing how dynamic these imports are)
2. Is it possible for these plugins to tell type checkers that their engine is valid, i.e. change the type signature of xarrays function? Then we should add a how-to in the docu.
3. Else we should probably revert to using Str.

Any typing experts here that could help?

**Comment by TomNicholas** [comment]
I don't think we should be using a `Literal` for something that a user is supposed to be able to extend anyway surely? IIUC a user is supposed to be define their own backend and use it to open a dataset, all without ever needing to add it to any official list within the xarray repo?

**Comment by TomNicholas** [comment]
Or we could just have a global variable like
`SUPPORTED_BACKENDS: List[str] = Literal['netcdf4', 'zarr']`
which is appended to when a user registers a new backend?

**Comment by headtr1ck** [comment]
> Or we could just have a global variable like
> `SUPPORTED_BACKENDS: List[str] = Literal['netcdf4', 'zarr']`
> which is appended to when a user registers a new backend?

If you know how that works statically, I don't see a way to do that.
You can only get dynamic content from static types and not the other way around.

**Comment by Illviljan** [comment]
Yeah, reverting to Str seems to be the most straightforward way. It's unfortunate though Literals are really nice.

**Comment by headtr1ck** [comment]
Ok, let's keep this issue open for a bit in case someone still finds a solution.
But we should go back to Str before releasing the next version.
