### ISSUE TITLE
pre-release for v2022.06.0

### ISSUE THREAD

**Issue by keewis** [pydata/xarray#6645]
There's a few unreleased and potentially breaking changes in `main`, most importantly the index refactor and the new `groupby` using `numpy-groupies` and `flox`. During the meeting on Wednesday we decided to release a preview version to get feedback before releasing a full version, especially from those who don't run their tests against our `main` branch.

I am planning to create the pre-release tomorrow, but if there's any big changes that should be included please post here.

cc @TomNicholas

Edit: the version will be called `2022.05.0.dev0`, which will ensure that e.g. `pip` will require the `--pre` flag to install it.

**Comment by headtr1ck** [comment]
If someone manages to fix https://github.com/pydata/xarray/pull/6624
That would be a good candidate.

**Comment by dcherian** [comment]
Doing a pre-release sounds good to me.

But we know of at least [three regressions](https://github.com/pydata/xarray/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Arelease-blocker) (tagged under "release-blocker"). Should we fix them first?

**Comment by headtr1ck** [comment]
This should be also merged: https://github.com/pydata/xarray/pull/6651

**Comment by keewis** [comment]
the `cftime` issues (#6624, #6613) look like they would be good to be fixed first, but since the remaining one (#6607) is also in `2022.3.0` so I don't think we need to wait on that for the pre-release.

Something to remember, though, is that this is *not* a full release, so I don't think we need to have fixed every known bug.

**Comment by dcherian** [comment]
The MVCE in #6607 does work on v2022.03.0. #6229 OTOH was broken earlier so "technically" not a regression

**Comment by keewis** [comment]
right, I misunderstood that MVCE. I still think that we don't need to wait on a fix to do the pre-release, though.

As far as I understand PEP440, to create a pre-release we just need add a `rcN` suffix (i.e. `2022.06.0rc0`) or `.devN` (i.e. `2022.06.0.dev0`. Do we need to update `whats-new.rst` for this?

**Comment by dcherian** [comment]
> Do we need to update whats-new.rst for this

👍🏾 It'd be nice to point to "known regressions" to prevent a bunch of duplicate bug reports.

**Comment by kmuehlbauer** [comment]
I'm wondering if it would be possible to publish every commit to main on https://test.pypi.org/project/xarray/?

**Comment by keewis** [comment]
As far as I remember the only reason we don't do that already is that `setuptools_scm` creates nightly versions that are not compliant to PEP440. The version scheme appears to be configurable, but I couldn't find documentation on how to do that. As such, if anyone can figure out how to create PEP440 (and thus PyPI) compatible development versions I think we can have a CI publish every commit on `main` to TestPyPI.

**Comment by keewis** [comment]
I just published the pre-release, it can be installed from PyPI:
```python
mamba create -n <name> python=3.10 xarray
python -m pip install --pre --upgrade --no-deps xarray
```
(the `--no-deps` is important, otherwise we pull the pre-releases of other packages)

**Comment by TomNicholas** [comment]
Thanks @keewis !

I just tried making a [PR in datatree](https://github.com/xarray-contrib/datatree/pull/41) depend on this release, but the [CI environment installation fails](https://github.com/xarray-contrib/datatree/runs/6816624856?check_suite_focus=true). I'm not sure if that's my fault or not :confused: Any ideas?

**Comment by dcherian** [comment]
I added pre-release install instructions to whats-new and scheduled a tweet for 45 minutes from now (giving RTD enough time to build)

**Comment by dcherian** [comment]
I'll issue the release once #6798 goes in.
