### ISSUE TITLE
`dim` vs `dims`

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#6646]
### What is your issue?

I've recently been hit with this when experimenting with `xr.dot` and `xr.corr` — `xr.dot` takes `dims`, and `xr.cov` takes `dim`. Because they each take multiple arrays as positional args, kwargs are more conventional.

Should we standardize on one of these?

**Comment by TomNicholas** [comment]
I've noticed this before and do find it a bit annoying.

**Comment by shoyer** [comment]
It would be helpful to understand if there are also other uses of `dim`/dims` that are inconsistent. Which is the most common pattern?

**Comment by max-sixty** [comment]
As discussed on the dev call — we can plan to move to `dim`, with the exception of constructors!
