### ISSUE TITLE
Publish nightly releases to TestPyPI

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6659]
### Is your feature request related to a problem?

From @keewis in #6645 

> if anyone can figure out how to create PEP440 (and thus PyPI) compatible development versions I think we can have a CI publish every commit on main to TestPyPI.

**Comment by kmuehlbauer** [comment]
It's more a workaround. Maybe it's suitable for xarray.

In a project I maintain I'm doing the following before creation of tarball and wheels when uploading to TestPyPI.

```bash
# remove local appendix (+gXXXXXXXX)
$ echo 'local_scheme =  "no-local-version"' >> pyproject.toml
# prevent dirty-flag
$ git update-index --assume-unchanged pyproject.toml
```

**Comment by keewis** [comment]
oh, that looks great!

To make updating `pyproject.toml` less of a hack we can probably read the file with `tomli`, add that setting and write it back using `tomli_w`.

**Comment by kmuehlbauer** [comment]
> To make updating `pyproject.toml` less of a hack (the `setuptools_scm` section might not be the last section in the future) we can probably read the file with `tomli`, add that setting and write it back using `tomli_w`.

That's for sure more reliable. Didn't think about that in the first place.

**Comment by keewis** [comment]
apparently, `local_scheme = "no-local-scheme"` is broken when using `setuptools>=60`. I'll pin `setuptools<60` in CI, hopefully that helps

**Comment by kmuehlbauer** [comment]
@keewis `git restore -SW .` will remove the changes to `pyproject.toml`.
