### ISSUE TITLE
Trouble with Gill_Matsuno

### ISSUE THREAD

**Issue by PovedaGerman** [pydata/xarray#6681]
### What is your issue?

Hi,  I have been trying to run your codes on the Gill-Matsuno problem. Specifically, for the classical Gill example I get the following error message:

AttributeError                            Traceback (most recent call last)
<ipython-input-130-8c87009c16fe> in <module>
----> 1 h1, u1, v1 = invert_GillMatsuno(Q, dims=['lat,'lon'], BCs=['fixed', 'periodic'],
      2                                 optArg=1.4, mxLoop=600, cal_flow=True,
      3                                 epsilon=1e-5, Phi=5000)

~/opt/anaconda3/lib/python3.8/site-packages/xinvert/apps.py in invert_GillMatsuno(Q, dims, BCs, coords, Phi, epsilon, f0, beta, undef, mxLoop, tolerance, optArg, cal_flow, printInfo, debug)
    505 
    506     if np.isnan(undef):
--> 507         forcing = Q.fill(_undeftmp)
    508     else:
    509         forcing = Q.where(Q!=undef, other=_undeftmp)

AttributeError: 'numpy.ndarray' object has no attribute 'fillna'

I appreciate your help. Many thanks in advance.

**Comment by andersy005** [comment]
@PovedaGerman, this doesn't appear to be an Xarray issue. Do you mind asking on the `xinvert` issue tracker: https://github.com/miniufo/xinvert
