### ISSUE TITLE
When a raster is modified, it cannot be read correctly.

### ISSUE THREAD

**Issue by JiangtaoLiud** [pydata/xarray#6693]
### What happened?

As the following code shows, when I read this raster for the first time, xarray can read its content correctly. When this raster is modified, it can't be read correctly.

### Minimal Complete Verifiable Example

```Python
import rasterio
import xarray as xr
import numpy as np
import os

data = np.arange(10*10.).reshape(10, 10)
inp_rs = "demo.tif"

def generate_raster(data):
    with rasterio.open(
        inp_rs,
        'w',
        driver='GTiff',
        height=data.shape[0],
        width=data.shape[1],
        count=1,
        dtype=data.dtype,
        crs='+proj=latlong',
    ) as dst:
        dst.write(data, 1)

generate_raster(data)

rs1 = rasterio.open(inp_rs)
print("rasterio :", rs1.shape)
rs2 = xr.open_dataset(inp_rs)
print("xarray: ", rs2.band_data.shape)

# modify it
os.remove(inp_rs)
data_new = np.arange(9*9.).reshape(9, 9)
generate_raster(data_new)

rs1 = rasterio.open(inp_rs)
print("rasterio :", rs1.shape)
rs2 = xr.open_dataset(inp_rs)
print("xarray: ", rs2.band_data.shape)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Read correctly the first time：
rasterio : (10, 10)
xarray:  (1, 10, 10)

Incorrectly read the second time：
rasterio : (9, 9)
xarray:  (1, 10, 10)
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.3.0-7625-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.0
libnetcdf: 4.7.4
xarray: 2022.3.0
pandas: 1.4.2
numpy: 1.22.3
scipy: 1.8.0
netCDF4: 1.5.8
pydap: None
h5netcdf: None
h5py: 3.6.0
Nio: None
zarr: None
cftime: 1.6.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: None
iris: None
bottleneck: None
dask: 2022.02.1
distributed: 2022.2.1
matplotlib: 3.3.2
cartopy: None
seaborn: None
numbagg: None
fsspec: 2022.3.0
cupy: None
pint: None
sparse: None
setuptools: 59.8.0
pip: 22.0.4
conda: None
pytest: None
IPython: 8.1.1
sphinx: None

</details>

**Comment by keewis** [comment]
If you open the changed file in a new session, you get the result you expected. This indicates that this issue is a due to file caching, and if you call
```python
xr.backends.file_manager.FILE_CACHE.clear()
```
in between the `xarray` calls I can confirm that the calls are loaded as expected (don't use that in your code, though, that is a implementation detail).

If you actually use the dataset (e.g. by calling `.load()`), the file cache seems to reset and the subsequent open also has the expected shape.

The same happens if you pass `lock=False`, so if you can make sure to have closed the file (`ds.close()`) before the next open you should be able to use that.

In general I think it would be best to avoid rewriting files, but I'm not an expert on backends so there might be a way to handle that.

**Comment by JiangtaoLiud** [comment]
No, it doesn't work. It is still the wrong result. 

Before modifying this raster, I used 
```
rs1.close()
rs2.close()
```
To be more precise, I deleted the old raster first and then generated a new one later.

**Comment by keewis** [comment]
can you post what exactly you tried that didn't work? For me this works:
```python
In [1]: import rasterio
   ...: import xarray as xr
   ...: import numpy as np
   ...: import os
   ...: 
   ...: data = np.arange(10 * 10.0).reshape(10, 10)
   ...: inp_rs = "demo.tif"
   ...: 
   ...: 
   ...: def generate_raster(data):
   ...:     with rasterio.open(
   ...:         inp_rs,
   ...:         "w",
   ...:         driver="GTiff",
   ...:         height=data.shape[0],
   ...:         width=data.shape[1],
   ...:         count=1,
   ...:         dtype=data.dtype,
   ...:         crs="+proj=latlong",
   ...:     ) as dst:
   ...:         dst.write(data, 1)
   ...: 
   ...: 
   ...: generate_raster(data)
   ...: 
   ...: with xr.open_dataset(inp_rs, cache=False, engine="rasterio", lock=False) as rs2:
   ...:     print("xarray: ", rs2.band_data.shape)
   ...: rs1 = rasterio.open(inp_rs)
   ...: print("rasterio :", rs1.shape)
   ...: 
   ...: # modify it
   ...: os.remove(inp_rs)
   ...: data_new = np.arange(9 * 9.0).reshape(9, 9)
   ...: generate_raster(data_new)
   ...: 
   ...: with xr.open_dataset(inp_rs, cache=False, engine="rasterio", lock=False) as rs2:
   ...:     print("xarray: ", rs2.band_data.shape)
   ...: rs1 = rasterio.open(inp_rs)
   ...: print("rasterio :", rs1.shape)
xarray:  (1, 10, 10)
rasterio : (10, 10)
xarray:  (1, 9, 9)
rasterio : (9, 9)
```

**Comment by JiangtaoLiud** [comment]
I forgot to add `lock=False`. It works now. Thanks!
