### ISSUE TITLE
Support `skipna` in `.where()`

### ISSUE THREAD

**Issue by zxdawn** [pydata/xarray#6713]
### Is your feature request related to a problem?

Sometimes, the mask used in `.where(mask)` may have nan values. In the current stage, xarray just neglects them. But, it also makes sense that users want to mask data with nan values.

### Describe the solution you'd like

This option can be achieved by adding `skipna=bool`.

if `skipna=False`, the nan values in mask will be replaced by 0:`mask.fillna(0)`.
By default, it's `skipna=True` which is current function.

**Comment by zxdawn** [comment]
Thanks for the tip! It works well.

Is it better to raise a warning or something else to remind users there're nan values in the mask?

**Comment by dcherian** [comment]
I guess we could raise a warning if `mask.dtype` is not bool; but that would be annoying if you passed an integer array with only 0, 1. IMO we should avoid the warning.
