### ISSUE TITLE
outdated reference link for dataset.resample

### ISSUE THREAD

**Issue by pierre-manchon** [pydata/xarray#6734]
### What is your issue?

The link of the reference [1] ([this one](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)) in [dataset.resample](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.resample.html) as well as [dataarray.resample](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases) is outdated and thus, redirects to the entire timeseries documentation and not specifically to the dateoffset-object headline which should be [this link](https://pandas.pydata.org/docs/user_guide/timeseries.html#dateoffset-objects)

**Comment by keewis** [comment]
thanks for the report, @pierre-manchon. The link is defined here: https://github.com/pydata/xarray/blob/787a96c15161c9025182291b672b3d3c5548a6c7/xarray/core/common.py#L1203 PRs welcome!

**Comment by pierre-manchon** [comment]
thanks, will try to do a PR later this evening!
