### ISSUE TITLE
some private imports broken on main

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6741]
### What happened?

Seen over in [cf_xarray](https://github.com/xarray-contrib/cf-xarray/pull/343)

Using `xr.core.resample.Resample` worked prior to https://github.com/pydata/xarray/pull/6702. 

Now we need to use `from xarray.core.resample import Resample`

I don't know if this is something that needs to be fixed or only worked coincidentally earlier. But I thought it was worth discussing prior to release.

Thanks to @aulemahal for spotting

**Comment by aulemahal** [comment]
To add details, I suspect this commit as the culprit: 
https://github.com/headtr1ck/xarray/commit/cd2f2b247cf6e1c68c7db6e92100898272fb0e1a

It removes a direct import of the `core.resample` submodule in `core.dataarray` and moves it to the "Type checking" imports. Thus, importing xarray (`import xarray as xr`), does not trigger an explicit import of `resample` anymore.

**Comment by headtr1ck** [comment]
It was a  semi-incidential change.
These modules are now only imported when required (i.e. calling DataArray.rolling ), I didn't think anyone would actually use these classes directly.

The modules can either be imported at DataArray/set module level directly again, or we could add a breaking change note.

**Comment by headtr1ck** [comment]
On the plus side, with the current implementation we probably save a few ms import time xD.

**Comment by headtr1ck** [comment]
> Another example is that `asfreq` has moved downstream a little and is no longer available on `Resample` either, can probably break something as well.

It was moved because it actually didn't work in the baseclass ;)
So I don't think anyone has ever used that.
