### ISSUE TITLE
same python script (using xr.to_netcdf) produces different files

### ISSUE THREAD

**Issue by jinqj** [pydata/xarray#6747]
### What is your issue?

Dear all,

I have a question about producing netcdf files using xr.to_netcdf(). I used the same script to process MODIS data but got some files of different sizes and other files of same size. Here is the screenshot of the results of "ls -all". You can see that some files of the same name have the same size, but other do not. I am sure my script is the same. I am wondering if anyone here encountered the similar problem. This issue is really annoying. BTW, I run the script in the same conda environment.

Thank you,
Qinjian

<img width="681" alt="Screen Shot 2022-07-02 at 11 45 46 PM" src="https://user-images.githubusercontent.com/40441097/177025092-9de1fe70-4ebc-4a61-91f6-1c6091a95ed9.png">

<img width="681" alt="Screen Shot 2022-07-02 at 11 45 28 PM" src="https://user-images.githubusercontent.com/40441097/177025100-d8daa675-bfa3-492b-a4cc-6accb10e1c8d.png">

**Comment by dcherian** [comment]
Hmm.... are they being compressed and is some of the more NaN cells so it compresses better?

**Comment by kmuehlbauer** [comment]
@jinqj Did you find an explanation to the different sizes? 

Is there pure data the files? How about metadata? Is write order of variables consistent? Possible padding issue? Filesystem issues?

I'll close for now. Please reopen if needed.
