### ISSUE TITLE
to_array to create a dimension as last axis

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#6754]
### Is your feature request related to a problem?

I do `ds.to_array(dim="variable").transpose("latitude", "longitude", "variable")`. I would like to avoid the extra transpose call.

### Describe the solution you'd like

`ds.to_array(dim="variable", new_axis="last")` where `new_axis` is `Literal["first", "last"] = "first"` or
`ds.to_array(dim="variable", new_axis=0)` where `new_axis` is `Literal[0, -1] = 0`

code to change: https://github.com/pydata/xarray/blob/main/xarray/core/dataset.py#L5770

### Additional context

I imagine `new_axis` could be of type int to place the new axis where you would like but the proposal above may be a good first step.

For reference, i'm doing deep learning and want to shape the data as width (latitude), height (longitude), channel (feature)

**Comment by dcherian** [comment]
We could follow the `axis` kwarg to `DataArray.expand_dims` as precedent. It specifies the axis number for the new dimension.

**Comment by raybellwaves** [comment]
> We could follow the `axis` kwarg to `DataArray.expand_dims` as precedent. It specifies the axis number for the new dimension.

Thanks. Made a PR before seeing your comment. Welcome to chime in on the PR

**Comment by max-sixty** [comment]
What's the advantage of this over the transpose call?

The transpose approach is more modular, since it takes advantage of the orthogonality of the methods — i.e. we have one method for all usages, rather than kwargs in lots of methods.

We've also managed to have `axis` as a hidden implentation detail, and this would start exposing it.

**Comment by dcherian** [comment]
@max-sixty yeah that's valid.

@raybellwaves `ds.to_array(dim="variable").transpose("latitude", "longitude", "variable")` could be written as `ds.to_array(dim="variable").transpose(..., "variable")` which generalizes better

**Comment by raybellwaves** [comment]
> What's the advantage of this over the transpose call?

I would say very little. I'm a lazy programmer.

I appreciate the arguments here of not blending methods which could make them more prone to bugs. I doubt there's any noticeable overhead of computation cost with the extra `transpose` call.

Welcome to close.

**Comment by max-sixty** [comment]
> I would say very little. I'm a lazy programmer.

Haha, us both Ray!

I do think that part of laziness is not having to remember too much — so hopefully I can trade you the costs of an extra method call for more consistency!
