### ISSUE TITLE
simple groupby_bins 10x slower than numpy

### ISSUE THREAD

**Issue by vnoel** [pydata/xarray#6758]
I am finding that groupby_bins is 10x slower than numpy in what I consider to be a simple implementation.

In the screenshot below, you can see me opening a netCDF file containing two variables with the same single dimension. One variable is the latitude. I want to aggregate (sum) the other variable in bins of latitude. The xarray approach using groupby_bins takes ~314ms per loop, the numpy approach less than 30ms per loop. 

I need to do this kind of computation on many more variables, on data spanning several years, and following the xarray approach leads to many more hours of processing :-/

Am I doing something wrong here?

![Capture d’écran 2022-07-06 à 16 28 23](https://user-images.githubusercontent.com/731499/177574951-6fe8a4c5-e6a8-4231-ad7b-40157dd2eb6b.png)

**Comment by dcherian** [comment]
On xarray main with [flox](https://flox.readthedocs.io) installed:

``` python
import numpy as np
import xarray as xr
display(xr.__version__)

N = 3728
ds = xr.Dataset()
ds["latitude"] = ("x", 0 + 20 * np.random.standard_normal(N))
ds["data"] = ("x", 0 + 100 * np.random.standard_normal(N))

%timeit ds.groupby_bins("latitude", np.arange(-40, 40, 0.1)).sum()
```
50.3 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

You could try it on our pre-release (https://docs.xarray.dev/en/latest/whats-new.html#v2022-06-0rc0-9-june-2022) or use xhistogram which should be faster even.

**Comment by dcherian** [comment]
Yes that's right.

For this simple problem you could combine `np.digitize` and `np.bincount` to do it much quicker.

``` python
group_idx = np.digitize(latitude, bins)
sums = np.bincount(group_idx, weights=array)
```

And then wrap this using apply_ufunc. See https://github.com/ml31415/numpy-groupies/blob/412be938dcdfd74c6d673dd29012d18dc25dc94f/numpy_groupies/aggregate_numpy.py#L8-L28 for inspiration.

**Comment by vnoel** [comment]
thanks a lot for the suggestions!

**Comment by vnoel** [comment]
@dcherian I just tested your numpy suggestions, and I'm getting 100x speedups compared to my naive numpy approach (~200µs vs ~20ms). Thankyouthankyouthankyou!
I've been doing this for years, I can't believe I've never run into that particular solution. It's like the IDL histogram function but in numpy. I'm going to use this like crazy
Thanks again

**Comment by dcherian** [comment]
> the IDL histogram function but in numpy. 

Apparently  [not](https://github.com/numpy/numpy/issues/9032) as [awesome!](http://www.idlcoyote.com/tips/histogram_tutorial.html)

**Comment by kmuehlbauer** [comment]
I'm getting a bit off topic now, but ...

> Apparently [not](https://github.com/numpy/numpy/issues/9032) as [awesome!](http://www.idlcoyote.com/tips/histogram_tutorial.html)

@dcherian Thanks for bringing back fond memories of the past. I still have @davidwfanning's IDL books on the shelf. And for sure it was a great pleasure reading @jdtsmith's IDL tricks and trying to understand those helped a lot. Great stuff.

**Comment by vnoel** [comment]
> > the IDL histogram function but in numpy.
> 
> Apparently [not](https://github.com/numpy/numpy/issues/9032) as [awesome!](http://www.idlcoyote.com/tips/histogram_tutorial.html)

Yeah, the present solution is less general, but most of the time I'm just counting stuff, and this is much faster than what I was doing, so I'm happy ;-)

**Comment by vnoel** [comment]
@dcherian Just to be complete, I thought the following one-liner would work as well:

```sums, x = np.histogram(latitude, bins, weights=array)```

but apparently it produces slightly different results for reasons I don't understand
