### ISSUE TITLE
DataArray.rolling.reduce() does not apply correctly numpy.nanpercentile

### ISSUE THREAD

**Issue by AlxndrLhr** [pydata/xarray#6759]
### What is your issue?

I stumbled upon the issue of not having a simple `DataArray.rolling.quantile()` or `Dataset.rolling.quantile()`, so I tried using the `rolling.reduce()` alternative, which seems to alter the normal functioning of functions like `numpy.nanpercentile`. Namely, `nanpercentile` act like `percentile` i.e create huge missing chunks the size of `rolling` as soon as `nan`  are found within the window. Is there a fix to that ?

Here is the code I used to test it out:
``` python
import xarray as xr, numpy as np

m,n = 30,56
tab = np.random.uniform(0, 100, size=(m,n))
ds = xr.DataArray(tab)
ds.plot.imshow(center=False)

nb_nan = 8
tab.ravel()[np.random.choice(tab.size, nb_nan, replace=False)] = np.nan
ds_nan = xr.DataArray(tab)
ds_nan.plot.imshow(center=False)

w = 4
roll = ds_nan.rolling({name: w for name in ['dim_0', 'dim_1']}, center = True)

roll_perc = roll.reduce(np.percentile, q=90)
roll_perc.plot.imshow(center=False)

roll_perc_nan = roll.reduce(np.nanpercentile, q=90)
roll_perc_nan.plot.imshow(center=False)

**Comment by dcherian** [comment]
Can you try passing `min_periods=1` in `rolling()`?

**Comment by AlxndrLhr** [comment]
Wow, I should really dig deeper in the documentation sometimes. Thanks a lot, it fixed it. Although it does remove the original `nan`, which can be reintroduced using a mask.
Thank you again for your time.
