### ISSUE TITLE
xr.open_dataset(url) gives NetCDF4 (lru_cache.py) error "oc_open: Could not read url"

### ISSUE THREAD

**Issue by DanCodigaMWRA** [pydata/xarray#6766]
### What is your issue?

This code I use was working about a year ago but today gives me an error:

```
import xarray as xr
url = 'http://psl.noaa.gov/thredds/dodsC/Datasets/NARR/monolevel/uwnd.10m.2000.nc'
ds = xr. open_dataset(url)
```
The Traceback includes the following:
```
File "C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ\lib\site-packages\xarray\backends\lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
```
and
```
OSError: [Errno -68] NetCDF: I/O failure: b'http://psl.noaa.gov/thredds/dodsC/Datasets/NARR/monolevel/uwnd.10m.2000.nc'

Note:Caching=1
Error:curl error: SSL connect error
curl error details: 
Warning:oc_open: Could not read url
```
I have confirmed that the file I am trying to read is on the server and the server is not requiring a password (nothing I am aware of, about the server, has changed since my code used to work successfully).

I am on Windows using a conda virtual env (no pip). 
My xarray is 0.20.2 and my netCDF4 is 1.6.0-- these are almost certainly more recent than the ones I was using when my code used to succeed, but I didn't record which version(s) used to work.

It was suggested that I pin netcdf4 to 1.5.8, so I tried this but got the same error.

Recently I had to update security certificates locally here, and this could be related, but I'm not sure.

Any suggestions for how I should troubleshoot this? 

Also, should I post an issue at https://github.com/Unidata/netcdf4-python instead of, and/or in addition to, this one?

I found these issues, which seem possibly related, but don't seem to be resolved well yet:
https://github.com/Unidata/netcdf4-python/issues/755 
https://github.com/pydata/xarray/issues/4925

(I also opened 'discussion' #6742 but so far there has been little response there.)

**Comment by dcherian** [comment]
Works for me with these versions. Can you compare with your versions using `xr.show_versions()`
<details>
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1127.18.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 2022.3.0
pandas: 1.4.3
numpy: 1.22.4
scipy: 1.8.1
netCDF4: 1.6.0
pydap: None
h5netcdf: None
h5py: 3.7.0
Nio: None
zarr: 2.12.0
cftime: 1.6.0
nc_time_axis: 1.4.1
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.4
dask: 2022.6.1
distributed: 2022.6.1
matplotlib: 3.5.2
cartopy: 0.20.3
seaborn: 0.11.2
numbagg: None
fsspec: 0.8.4
cupy: None
pint: None
sparse: None
setuptools: 62.6.0
pip: 22.1.2
conda: None
pytest: None
IPython: 8.4.0
sphinx: None
```
</details>

**Comment by dcherian** [comment]
OH I see your xarray and netCDF versions. Hmmm... 

perhaps @dopplershift has tips for debugging this.

One thing to try is to skip xarray and use netcdf directly
```
import netCDF4

netCDF4.Dataset(url)
```

Does that succeed? If not, let's move this to netcdf4-python

**Comment by DanCodigaMWRA** [comment]
Thanks for the quick response. 
Result from `xr.show_versions() `is below.
I tried `netCDF4.Dataset(url) `and it gave the same error.

Just a thought: I still wonder if this could be related to certification... which is something that did change on my system recently. 
I looked for information as to where netCDF4 would check for its certificate chain, but wasn't able to find something useful so far.


INSTALLED VERSIONS
------------------
commit: None
python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:37:49) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: (None, None)
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.20.2
pandas: 1.3.5
numpy: 1.21.6
scipy: 1.7.3
netCDF4: 1.6.0
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: 0.9.10.1
iris: None
bottleneck: 1.3.4
dask: None
distributed: None
matplotlib: 3.5.2
cartopy: 0.20.2
seaborn: 0.11.2
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
setuptools: 59.8.0
pip: 22.1.2
conda: None
pytest: None
IPython: 7.33.0
sphinx: 4.3.2

**Comment by dopplershift** [comment]
I just created a new Python 3.7 environment on my Mac and that worked fine. What do these show?
```
❯ conda list curl
# packages in environment at /Users/rmay/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
curl                      7.83.1               h23f1065_0    conda-forge
libcurl                   7.83.1               h23f1065_0    conda-forge
❯ conda list certifi
# packages in environment at /Users/rmay/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
ca-certificates           2022.6.15            h033912b_0    conda-forge
certifi                   2022.6.15        py37hf985489_0    conda-forge
```
Though I agree this is not an xarray problem at this point. Does it work if you do (with the env active):
```
ncdump -h http://psl.noaa.gov/thredds/dodsC/Datasets/NARR/monolevel/uwnd.10m.2000.nc
```
?

**Comment by DanCodigaMWRA** [comment]
Thanks for these suggestions, very helpful. See below, for details, but as far as I can tell it looks like:
* my conda env ("EQ") has the same curl, libcurl, ca-certificates, and certifi as your system.
* the ncdump commands gives same error (as netcdf4 and xarray).

I should post an issue at netcdf4, correct?


```
(EQ) PS C:\Users\Codiga_D> conda list curl
# packages in environment at C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ:
#
# Name                    Version                   Build  Channel
curl                      7.83.1               h789b8ee_0    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge

(EQ) PS C:\Users\Codiga_D> conda list certifi
# packages in environment at C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ:
#
# Name                    Version                   Build  Channel
ca-certificates           2022.6.15            h5b45459_0    conda-forge
certifi                   2022.6.15        py37h03978a9_0    conda-forge

(EQ) PS C:\Users\Codiga_D> ncdump -h http://psl.noaa.gov/thredds/dodsC/Datasets/NARR/monolevel/uwnd.10m.2000.nc
Error:curl error: SSL connect error
curl error details:
Warning:oc_open: Could not read url
C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ\Library\bin\ncdump.exe: http://psl.noaa.gov/thredds/dodsC/Datasets/NARR/monolevel/uwnd.10m.2000.nc: NetCDF: I/O failure
```

**Comment by DanCodigaMWRA** [comment]
Or maybe I should add to this issue https://github.com/Unidata/netcdf4-python/issues/812 rather than starting a new one? Guidance welcome thanks.

**Comment by su123454321** [comment]
guys,i meet this problem now,on my ubuntun computer,when i use pyinstaller to package an executable for downloading gfs data,the executable can work normall. However,when i copy the exectable and its all reliable files to another ubuntun computer,it did not work and says:
Error:curl error: Problem with the SSL CA cert (path? access rights?)
curl error details:
Warning:oc_open: Could not read url
how can i fix this?
