### ISSUE TITLE
Save to netCDF with record dimension?

### ISSUE THREAD

**Issue by darothen** [pydata/xarray#678]
Is it currently possible in xray to identify a coordinate as a record dimension when saving to netCDF? Saving a Dataset to disk - even when it's a Dataset that was directly read in from a netCDF file with a record dimension - seems to destroy any indication that there was a record dimension. For instance, reading in CESM output tapes and then immediately saving them to disk demotes "time" from being a record dimension.

**Comment by jhamman** [comment]
We've noticed this as well and it is something we find out how to do.

@shoyer - Any thoughts on how to make this happen?  In `netCDF4`, this is done by setting the size of a dimension to `None`.

cc @lizaclark

**Comment by shoyer** [comment]
We could certainly add an option to `to_netcdf` to explicitly indicate record dimensions. In principle, we could probably also save this information via some flag in the `encoding` dict associated with the coordinate variables.

**Comment by jhamman** [comment]
I'd like to keep the solution out of `to_netcdf` if possible.  To me, not maintaining the kind of dimension means that we are not "round tripping" netCDF4 files faithfully. Thinking about the `encoding` option, IIRC, `encoding` just exists on `DataArrays` and `DataSets`, it would be nice to have something on the dimension itself. Would it may fit better in the `Variable.dim` space?

**Comment by shoyer** [comment]
`encoding` only exists on `Variable` objects, with the user facing API exposed via `DataArray`. We don't even have it on `Dataset` objects, though I suppose that could be a logical addition.

Currently dimensions are just strings. I would be reluctant to use some sort of more complex object instead.

**Comment by gerritholl** [comment]
Is this fixed by #1170?

**Comment by jhamman** [comment]
Yes, thanks @gerritholl.
