### ISSUE TITLE
Convert upstream-dev CI scripts to github Action

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6810]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

If possible, I think it'd be nice to move a lot of the upstream-dev CI scripting to its own github action like "ci-trigger". This will make it easier to use in other projects (like those under xarray-contrib). I'd like to use it for flox, cf-xarray.

**Comment by keewis** [comment]
I just created a small github action for this: [xarray-contrib/issue-from-pytest-log](https://github.com/xarray-contrib/issue-from-pytest-log). There's also a small test repo here: [keewis/reportlog-test](https://github.com/keewis/reportlog-test) (I can .

Documentation and features are a bit minimal at the moment, though.
