### ISSUE TITLE
Success of DataArray.plot() depends on object's history. 

### ISSUE THREAD

**Issue by grahamfindlay** [pydata/xarray#6826]
### What happened?

I have the following 2D DataArray
```
ldda
````
![image](https://user-images.githubusercontent.com/4753005/180890862-b32001c5-bd39-44b7-9219-52300c9c3eca.png)

I can select a portion of it like so
```
da1 = ldda.sel(component=0)
da1
```
![image](https://user-images.githubusercontent.com/4753005/180890956-27897555-2711-479e-a5cf-155ff2958929.png)

I can get what *seems* like an equivalent array (equal values, matching dtypes, etc.) in the following way:
```
da2 = ldda.to_dataset(dim="component")[0]
da2
```
![image](https://user-images.githubusercontent.com/4753005/180891056-b965a138-71b4-4761-b13f-fda9d0a7238b.png)

And yet, while I can successfully plot `da1`...
```
da1.plot()
```
![image](https://user-images.githubusercontent.com/4753005/180891132-281b0c4d-1364-45ef-846c-8cc6bb71d293.png)

Trying to do the same with `da2` results in the following error...
```
da2.plot()
```
> AttributeError: 'int' object has no attribute 'startswith'

See below for full traceback and minimal working example. 

### What did you expect to happen?

I expected `da1` and `da2` to be functionally equivalent. 

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np

da = xr.DataArray(
    data=np.asarray([[1, 2], [3, 4], [5, 6]]),
    dims=["x", "y"],
)

da.sel(x=0).plot() # Succeeds
da.to_dataset(dim='x')[0].plot() # Fails
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Volumes/scratch/neuropixels/t2_shared_projects/discoflow_v2/discoflow/analysis/ANPIX30/discoflow-day2/get_senzai_ic_loadings.ipynb Cell 18 in <cell line: 1>()
----> 1 da2.plot()

File /Volumes/scratch/neuropixels/t2_shared_envs/discoflow_v2/lib/python3.8/site-packages/xarray/plot/plot.py:866, in _PlotMethods.__call__(self, **kwargs)
    865 def __call__(self, **kwargs):
--> 866     return plot(self._da, **kwargs)

File /Volumes/scratch/neuropixels/t2_shared_envs/discoflow_v2/lib/python3.8/site-packages/xarray/plot/plot.py:332, in plot(darray, row, col, col_wrap, ax, hue, rtol, subplot_kws, **kwargs)
    328     plotfunc = hist
    330 kwargs["ax"] = ax
--> 332 return plotfunc(darray, **kwargs)

File /Volumes/scratch/neuropixels/t2_shared_envs/discoflow_v2/lib/python3.8/site-packages/xarray/plot/plot.py:436, in line(darray, row, col, figsize, aspect, size, ax, hue, x, y, xincrease, yincrease, xscale, yscale, xticks, yticks, xlim, ylim, add_legend, _labels, *args, **kwargs)
    432 xplt_val, yplt_val, x_suffix, y_suffix, kwargs = _resolve_intervals_1dplot(
    433     xplt.to_numpy(), yplt.to_numpy(), kwargs
    434 )
    435 xlabel = label_from_attrs(xplt, extra=x_suffix)
--> 436 ylabel = label_from_attrs(yplt, extra=y_suffix)
    438 _ensure_plottable(xplt_val, yplt_val)
    440 primitive = ax.plot(xplt_val, yplt_val, *args, **kwargs)

File /Volumes/scratch/neuropixels/t2_shared_envs/discoflow_v2/lib/python3.8/site-packages/xarray/plot/utils.py:491, in label_from_attrs(da, extra)
    488 units = _get_units_from_attrs(da)
...
    493         textwrap.wrap(name + extra + units, 60, break_long_words=False)
    494     )
    495 else:

AttributeError: 'int' object has no attribute 'startswith'
```

### Anything else we need to know?

Thank you for one of my favorite packages!

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-122-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: None

xarray: 2022.3.0
pandas: 1.4.3
numpy: 1.21.0
scipy: 1.8.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: 3.7.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2022.7.0
distributed: None
matplotlib: 3.5.1
cartopy: None
seaborn: 0.11.2
numbagg: None
fsspec: 2022.5.0
cupy: None
pint: None
sparse: None
setuptools: 63.2.0
pip: 22.2
conda: None
pytest: 7.1.2
IPython: 8.4.0
sphinx: None

</details>

**Comment by max-sixty** [comment]
The difference is that one has a name of `0`:

```python

In [7]: da.sel(x=0)
Out[7]:
<xarray.DataArray (y: 2)>
array([1, 2])
Dimensions without coordinates: y

In [8]: da.to_dataset(dim='x')[0]
Out[8]:
<xarray.DataArray 0 (y: 2)>
array([1, 2])
Dimensions without coordinates: y

In [9]: da.to_dataset(dim='x')[0].name
Out[9]: 0

```

This shouldn't prevent the plotting from working — that is indeed a bug....
