### ISSUE TITLE
Store xray.Dataset to MongoDB

### ISSUE THREAD

**Issue by femtotrader** [pydata/xarray#683]
Hello,

it will be nice if xray Datasets could be stored easily to MongoDB.

Maybe Monary (not Pymongo) should be considered https://monary.readthedocs.org/

Kind regards

**Comment by shoyer** [comment]
Sure, I would definitely be open to this.

However, I don't have any experience with MongoDB, so this would need to come from an outside contribution -- maybe you?

It might also make more sense to put this in a separate package.

**Comment by femtotrader** [comment]
I don't know really if it should be on xray side, on monary or in a separate package. I waiting https://bitbucket.org/djcbeach/ opinion about this.

**Comment by hugo-pires** [comment]
I have the same problem. Thank you for all your help. I will leave some ideas here:
https://groups.google.com/forum/#!topic/xarray/a91YItgHzrc

**Comment by hugo-pires** [comment]
Is it possible that using an assync library could improve performance?

**Comment by keewis** [comment]
@crusaderky, can we close this by pointing to https://xarray-mongodb.readthedocs.io/en/latest/?

**Comment by dcherian** [comment]
We could add a list of these projects under the IO section to make them more visible: https://xarray.pydata.org/en/stable/io.html#

**Comment by crusaderky** [comment]
Indeed we can. Strong +1 for having a note in the main xarray documentation too!
