### ISSUE TITLE
update numpy version requirement

### ISSUE THREAD

**Issue by smoors** [pydata/xarray#6875]
### What happened?

in the latest xarray version 2022.06.0, xarray.DataArray.quantile supports 9 methods:
https://docs.xarray.dev/en/latest/generated/xarray.DataArray.quantile.html

however, those methods are only implemented starting from numpy  1.22.0 
https://numpy.org/doc/stable/reference/generated/numpy.quantile.html

whereas the current numpy requirement is only numpy >= 1.19

### What did you expect to happen?

that the numpy requirement is updated to numpy >= 1.22

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

</details>

**Comment by headtr1ck** [comment]
What exactly is the problem?
As clearly stated in the documentation that you linked the supported methods depend on your installed numpy version.

The oldest numpys version that will be supported is at least 18 month old, so 1.19 is still correct.

**Comment by keewis** [comment]
we could probably have a nicer error message, the one from `numpy` might be a bit confusing:
```
ValueError: interpolation can only be 'linear', 'lower' 'higher', 'midpoint', or 'nearest'
```

**Comment by smoors** [comment]
> As clearly stated in the documentation that you linked the supported methods depend on your installed numpy version.

indeed, I should have read the docs more carefully.

it's a bit annoying though: from the requirements I expected that numpy 1.19 would provide full support for all methods that xarray provides. maybe you could add a comment to the setup.cfg file along the lines of  "recommended numpy version  >= 1.22" to better indicate this?

I am not a direct user of this package, I just install it for our HPC users, but your suggestions to improve the error message and docs seem good to me.

**Comment by headtr1ck** [comment]
> maybe you could add a comment to the setup.cfg file along the lines of "recommended numpy version >= 1.22" to better indicate this?

Do people really look into the `setup.cfg` file when installing a package? I would assume >99% of the people simply do `pip/conda install xarray`
But I guess a comment does not hurt anyone.

**Comment by smoors** [comment]
> Do people really look into the `setup.cfg` file when installing a package?

yes, especially people like me who do central software installations in a HPC cluster (for example with EasyBuild) and who want to have full control over the package versions that are installed (which is essential for scientific reproducibility).
this is indeed a small minority, but note that a lot of people are using our centrally installed packages.
