### ISSUE TITLE
interpolate_na documentation

### ISSUE THREAD

**Issue by bertcoerver** [pydata/xarray#6899]
### What is your issue?

According to the documentation for [`xarray.Dataset.interpolate_na`](https://xarray.pydata.org/en/stable/generated/xarray.Dataset.interpolate_na.html?highlight=interpolate_na), additional keywords are passed on to `numpy.interp` when `method="linear"`. In one of the examples one such additional keyword is `fill_value` (`="extrapolate"`). 

But according the the linked documentation for [`numpy.interp`](https://numpy.org/doc/stable/reference/generated/numpy.interp.html#numpy.interp), that function only takes `left`, `right` and `period` as keyword arguments. 

The given example does work though... Does it really use `numpy.interp` or does it perhaps use [`scipy.interpolate.interp1d`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d), which does have a keyword called `fill_value`?

**Comment by alrho007** [comment]
From what I was able to gather,  numpy.interp only takes three keyword arguments as **kwargs i.e. left, right, and period but not fill_value. So when passing fill_value as a keyword argument to xarray.Dataset.interpolate_na with method="linear", it does not use numpy.interp but it uses scipy.interpolate.interp1d(), which provides the fill_value parameter.

**Comment by alrho007** [comment]
I'll like to update this in the documentation @TomNicholas

**Comment by TomNicholas** [comment]
@alrho007 great! We would welcome a pull request to update this :)
