### ISSUE TITLE
Italic not working in top of Terminology page

### ISSUE THREAD

**Issue by zmoon** [pydata/xarray#6932]
### What happened?

Looks like the intention is for the text to be all italic, but [where the source breaks](https://github.com/pydata/xarray/blame/98deab5458d7cab87325dae330675b7ef9ce0425/doc/user-guide/terminology.rst#L8) it is not working.

![image](https://user-images.githubusercontent.com/15079414/185498017-508aaf88-331f-43d0-99aa-7eadf8451b69.png)

**Comment by mathause** [comment]
Thanks for noticing.
