### ISSUE TITLE
Unable to import xarray after installing "io" extras in Python 3.10.*

### ISSUE THREAD

**Issue by grahamfindlay** [pydata/xarray#6960]
### What happened?

When installed into a Python 3.10 environment with a basic `pip install xarray`, there are no issues importing xarray. But when installing with `pip install xarray[io]`, the following error results upon import:
```
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray as xr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gfindlay/miniconda3/envs/foo/lib/python3.10/site-packages/xarray/__init__.py", line 1, in <module>
    from . import testing, tutorial
  File "/home/gfindlay/miniconda3/envs/foo/lib/python3.10/site-packages/xarray/tutorial.py", line 13, in <module>
    from .backends.api import open_dataset as _open_dataset
  File "/home/gfindlay/miniconda3/envs/foo/lib/python3.10/site-packages/xarray/backends/__init__.py", line 14, in <module>
    from .pydap_ import PydapDataStore
  File "/home/gfindlay/miniconda3/envs/foo/lib/python3.10/site-packages/xarray/backends/pydap_.py", line 20, in <module>
    import pydap.client
  File "/home/gfindlay/miniconda3/envs/foo/lib/python3.10/site-packages/pydap/client.py", line 50, in <module>
    from .model import DapType
  File "/home/gfindlay/miniconda3/envs/foo/lib/python3.10/site-packages/pydap/model.py", line 175, in <module>
    from collections import OrderedDict, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/home/gfindlay/miniconda3/envs/foo/lib/python3.10/collections/__init__.py)
``` 
It appears that having the extras installed causes an alternate series of imports within xarray that have not been updated for Python 3.10 (`from collections import Mapping` should be `from collections.abc import Mapping`). 

### Minimal Complete Verifiable Example

```Python
>>> mamba create -n foo python=3
>>> mamba activate foo
>>> pip install xarray[io]
>>> python

> import xarray as xr
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>
N/A
</details>

**Comment by headtr1ck** [comment]
Seems to come from pydap. Might be this issue: https://github.com/pydap/pydap/issues/267

**Comment by mathause** [comment]
I think we could not install pydap if for python versions 3.10 and up:

```diff
-pydap
+pydap;python_version<"3.10"
```
in
https://github.com/pydata/xarray/blob/3d3b236df3f8f5982760e68e064eb0db2aacc4a2/setup.cfg#L87

**Comment by mathause** [comment]
Turns out pydap 3.3 (which fixes this problem) is [released on conda](https://anaconda.org/conda-forge/pydap) but [not on pypi](https://pypi.org/project/Pydap/) - I opened an issue on this pydap/pydap#268 & also opened #6965 to work around this in the meantime
