### ISSUE TITLE
calculating slope between sliding window of two xarray

### ISSUE THREAD

**Issue by mohseniaref** [pydata/xarray#6983]
### What is your issue?

I am trying two calculate slope between sliding window(3x4) of two xarray dataset.you can imagine we want to calculate slope of dx and dy and put the value in the center of sliding window for x=3,y=4. I really appreciate if someone could help me to calculate slope or any function between sliding window of xarray in x,y dimension. Finally ,I want to interpolate the slope results into similar grid dataset of original dataset like dv

```
dv = xr.tutorial.open_dataset('air_temperature_gradient')
dx=dv.Tair.mean(dim='time')
de = dv.dTdx
def linear_trend(x, y):
    pf = np.polyfit(x, y, 1)
    return xr.DataArray(pf[0])
slopes = xr.apply_ufunc(linear_trend,
                        de.rolling(lat=3, lon=4, center=True), dx.rolling(lat=3, lon=4, center=True),
                        vectorize=True,
                        )
```

**Comment by mathause** [comment]
Closing in favour of #6984
