### ISSUE TITLE
FutureWarning for pandas date_range

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#6985]
### What is your issue?

Xarray raises a FutureWarning in its date_range, also observable in your tests.
The precise warning is:
> xarray/coding/cftime_offsets.py:1130: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.

You should discuss if you will adapt the new `inclusive` argument or add a workaround.

**Comment by spencerkclark** [comment]
Thanks for pinging this issue again in #7266 -- apologies for missing it earlier.  I think we should adapt to the new `inclusive` argument and implement it for the `cftime_range` function as well.
