### ISSUE TITLE
New MultiIndex dimension behaviours

### ISSUE THREAD

**Issue by ConnorSwales** [pydata/xarray#6990]
### What is your issue?

As of the latest release (2022.6.0), the behaviour of MultiIndex coordinates and their constituents appears to have changed. 

Creating a simple multi-indexed DataSet:

```
ds1 = xr.Dataset({'foo': (('x',), [1, 2, 3])}, {'x': [1, 2, 3], 'y': 'a'})
ds2 = xr.Dataset({'foo': (('x',), [4, 5, 6])}, {'x': [1, 2, 3], 'y': 'b'})

mult = xr.concat([ds1, ds2], dim='y').stack(yx=['y', 'x'])
```

Printing the DataSet and the coordinate indices on version 2022.3.0:
```
mult
<xarray.Dataset>
Dimensions:  (yx: 6)
Coordinates:
  * yx       (yx) MultiIndex
  - y        (yx) object 'a' 'a' 'a' 'b' 'b' 'b'
  - x        (yx) int64 1 2 3 1 2 3
Data variables:
    foo      (yx) int64 1 2 3 4 5 6
```

```
mult.coords.indexes
yx: MultiIndex([('a', 1),
                ('a', 2),
                ('a', 3),
                ('b', 1),
                ('b', 2),
                ('b', 3)],
               names=['y', 'x'])
```

Printing the DataSet and the coordinate indices on version 2022.6.0:
```
mult
<xarray.Dataset>
Dimensions:  (yx: 6)
Coordinates:
  * yx       (yx) object MultiIndex
  * y        (yx) <U1 'a' 'a' 'a' 'b' 'b' 'b'
  * x        (yx) int64 1 2 3 1 2 3
Data variables:
    foo      (yx) int64 1 2 3 4 5 6
```

```
mult.coords.indexes
Indexes:
yx: MultiIndex([('a', 1),
                ('a', 2),
                ('a', 3),
                ('b', 1),
                ('b', 2),
                ('b', 3)],
               name='yx')
y: MultiIndex([('a', 1),
               ('a', 2),
               ('a', 3),
               ('b', 1),
               ('b', 2),
               ('b', 3)],
              name='yx')
x: MultiIndex([('a', 1),
               ('a', 2),
               ('a', 3),
               ('b', 1),
               ('b', 2),
               ('b', 3)],
              name='yx')
```

On the latest version (2022.6.0), the constituent coordinates (```x,y```) of the multi-indexed coordinate (```yx```) have asterisks next to them, implying that they are dimensional (despite the them not being named equal to their sole dimension, as stated in the docs' **coordinates** section).
>dimension coordinates are one dimensional coordinates with a name equal to their sole dimension (marked by * when printing a dataset or data array) 

Further, looking into the ```.coords.indexes``` shows that each constituent coordinate is also indexed by an instance of the same MultiIndex.

I was wondering if this change been made design and whether the documentation just need updating, or I have misunderstood something along the way.

**Comment by benbovy** [comment]
Hi @ConnorSwales,

Yes this is an intentional change part of the ongoing explicit indexes refactor. There's still some work to do on the documentation. For more details, see:

- #6752
- #6293
- https://docs.xarray.dev/en/stable/roadmap.html#flexible-indexes
- https://github.com/pydata/xarray/projects/1

**Comment by headtr1ck** [comment]
Closing for now.
Feel free to reopen or better to comment in the linked issues above.
