### ISSUE TITLE
attrs are now views, not copies

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#6996]
### What is your issue?

I'm not sure yet if this is a feature or a bug - I would tend to the latter. Apologies if this has been discussed before.

Objects originating from operations such as `y = x > 2` are now sharing the same `attrs`, which leads to things like:

```python
import numpy as np
import xarray as xr
xr.__version__
'2022.6.0'

x = xr.DataArray(
    0.1 * np.arange(10),
    dims=["lat"],
    coords={"lat": np.arange(10)},
    name="sst",
)
x.lat.attrs['long_name'] = 'latitude'
x.lat.attrs
{'long_name': 'latitude'}

y = x > 2
y.lat.attrs
{'long_name': 'latitude'}

y.lat.attrs = {}
x.lat.attrs  # x is changed as well!
{}
```

I think this is rather a non-intuitive behavior but I'm happy to discuss!

**Comment by benbovy** [comment]
I thought #6857 would have fixed it but apparently not.

**Comment by fmaussion** [comment]
Yes sorry I also tested on `main` and this still occurs. Tagging this as bug.

**Comment by benbovy** [comment]
This happens with previous versions too (e.g., 0.21.0). Is there an older version where it returned copies?

**Comment by fmaussion** [comment]
> Is there an older version where it returned copies?

Yes, tests started to fail on [salem](https://github.com/fmaussion/salem) which I haven't maintained in quite a long time.

**Comment by fmaussion** [comment]
Sorry false alarm the bug that caused salem tests to fail is indeed solved by https://github.com/pydata/xarray/pull/6857 

Sorry for the noise.
