### ISSUE TITLE
`ffill` does not spread chunks when used with dask.array

### ISSUE THREAD

**Issue by eserie** [pydata/xarray#6997]
### What is your issue?

When using xarray with dask.array as in the following example:
```
import numpy as np
import xarray as xr
import dask
ds_ = xr.Dataset()
ds_["test"] = ("dim_0",), dask.array.from_array(
    [0, 1, np.nan, np.nan, np.nan], chunks=2
)
```
then the `ffill` method does not seem to propagate through the underlying chunks used by dask.array.
In the example above, this means that
```
 ds_.ffill("dim_0").compute().test.values
```
gives
```
>>> array([ 0., 1., 1., 1., nan])
```
where 
```
ds_.compute().ffill("dim_0").test.values
```
gives
```
>>> array([0., 1., 1., 1., 1., 1.])
```

Is it an expected behavior ?

**Comment by mathause** [comment]
What version of xarray are you using? I think this should have been fixed in #5187 (i.e. in v0.18.0).

**Comment by eserie** [comment]
Hi @mathause, I'm in version 0.18.2.

**Comment by eserie** [comment]
Ok, thanks, that solves the problem!

**Comment by mathause** [comment]
> Ok, thanks, that solves the problem!

Great to hear!
