### ISSUE TITLE
xarray fails to locate files via OpeNDAP

### ISSUE THREAD

**Issue by samanthastevenson** [pydata/xarray#7034]
### What is your issue?

Hi there,

I'm having an odd issue with xarray: it doesn't seem to be able to read in any files using opendap. I'm running xarray version 0.19.0, and xarray is failing to read in every file I've tried so far, even when those data exist online and - interestingly - are accessible via Opendap in Matlab.

An example: I'd like to read in data from the NOAA OISSTv2, and tried the 2013 netCDF file:
```python
import xarray as xr
sst_2013=xr.open_dataset("https://psl.noaa.gov/thredds/dodsC/Datasets/noaa.oisst.v2.highres/sst.day.mean.2013.v2.nc")
```
This results in the following error message:
```pytb
FileNotFoundError: [Errno 2] No such file or directory: 'https://psl.noaa.gov/thredds/dodsC/Datasets/noaa.oisst.v2.highres/sst.day.mean.2013.v2.nc'
```

Yet in Matlab, I am able to successfully read in the exact same file:
```matlab
nc=netcdf('https://psl.noaa.gov/thredds/dodsC/Datasets/noaa.oisst.v2.highres/sst.day.mean.2013.v2.nc');
>> nc
 
nc =
 
          NetCDF_File: 'https://psl.noaa.gov/thredds/dodsC/Datasets/noaa.oisst.v2.highres/sst.day.mean.2013.v2.nc'
          nDimensions: 3
           nVariables: 4
    nGlobalAttributes: 9
      RecordDimension: 'time'
             nRecords: 365
           Permission: 'nowrite'
           DefineMode: 'data'
             FillMode: 'fill'
           MaxNameLen: 0
```

Does anyone have any idea what might be causing this? My Python code ran just fine a few months ago, so I am mystified as to why the failure suddenly began.

**Comment by dopplershift** [comment]
That just worked fine for me. What version of libnetcdf and netcdf4 do you have installed?

**Comment by samanthastevenson** [comment]
Aha! I somehow managed to install xarray without either netcdf4 or libnetcdf, reinstalling with dependencies included fixed the problem. Thanks!
