### ISSUE TITLE
Complete renaming xray -> xarray

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#704]
This is a blocker for the 0.7 release.

**Comment by shoyer** [comment]
As part of this rename, we need to decide the recommended way to important xarray. Maybe `import xarray as xr` or `import xarray as xry`? Any opinions?

**Comment by ocefpaf** [comment]
:-1:

But I am just one user...  And if the renaming really happens I guess that `import xarray as xr` is better than `xry`

(I like the pun: See the data under x rays :smile:)

**Comment by shoyer** [comment]
I know renaming causes pain. But it is a pretty serious name conflict with xray science, and in the long terms, I think the future is bright enough that it's worth the short term pain. The name xarray will hopefully minimize confusion.

**Comment by clarkfitzg** [comment]
Wow, going for it! Great. Given the other common imports are
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
```
My vote goes for
```
import xarray as xr
```

Just curious, is `xarray` already decided on? You could call it `namedarray` or `labelarray`...

**Comment by shoyer** [comment]
The name `xarray` is not final until we make a release :). But we've been tossing around names for a while (e.g., see [this Twitter discussion](https://twitter.com/shoyer/status/609138080507768832))and I do think it's probably the best choice, given that we are starting from `xray` rather than a blank slate.

**Comment by MaximilianR** [comment]
This stuff is not my forte, but how about `nray`, as in n-ray? Like array, but n dimensions. And still four characters. 
But then maybe people will think it's one syllable 'nr-ay'.

**Comment by kjordahl** [comment]
`import xarray as xray`
:smiley:

**Comment by danielballan** [comment]
This is going to make life less confusing at BNL. Thanks, @shoyer.

**Comment by darothen** [comment]
I also like `import xarray as xr`.

**Comment by bsmoliak** [comment]
I find `xarray` to be a nice blend of old and new that should reduce confusion. As for importing, I think that `import xarray as xr` is a good two letter 'as' name. A three letter 'as' name may be slightly more memorable, and I'd suggest `import xarray as xra` for its similar sound when pronounced.

**Comment by rabernat** [comment]
:+1: for the renaming. Hard to believe in retrospect, but I never even got the xray / array reference until now.

I like `import xarray as xr`.

**Comment by tacaswell** [comment]
@shoyer Thank you :beers: 

`import xarray as xy` ?

**Comment by spencerahill** [comment]
One more vote for `import xarray as xr`.  It mimics `import numpy as np`, in terms of retaining the first consonant of each syllable.  

Also, it is clearly not pronounceable other than as the individual letters sequentially, i.e. as 'ex-are', which is a good thing. `xy`, `xra`, and `xry` all have ambiguous pronunciations.

**Comment by rsignell-usgs** [comment]
Yet another vote for `import xray as xr`

**Comment by shoyer** [comment]
Making some progress on this...

<img src="https://cloud.githubusercontent.com/assets/1217238/12151756/93b7c264-b465-11e5-9edc-629d53605d15.png" width="300">

**Comment by MaximilianR** [comment]
Nice!

**Comment by MaximilianR** [comment]
If you're really particular, you could line up the 'line' (the one that looks like a V, representing dims) with the boxes / planes

**Comment by shoyer** [comment]
I think that's beyond the limits of my graphical design talent :). I actually whipped up the logo in LaTeX!

<img src="https://cloud.githubusercontent.com/assets/1217238/12154831/ae9e5528-b476-11e5-8e4d-87fb4531e256.png" width="300">

**Comment by MaximilianR** [comment]
TBC, I meant something like this re the line (you'd need to change the spacing so it doesn't overlap)
![image](https://cloud.githubusercontent.com/assets/5635139/12155798/25903494-b495-11e5-9cdf-7e3ec07145a5.png)

OK, enough graphic design from me

**Comment by shoyer** [comment]
Ah, I see

<img src="https://cloud.githubusercontent.com/assets/1217238/12156080/a2aad492-b47d-11e5-9565-65166e1c4a18.png" width="300">

**Comment by MaximilianR** [comment]
Probably better uses of our time - but now it doesn't align to the rightmost plane (the red one)!

**Comment by rsignell-usgs** [comment]
I think it would be nicer to get rid of the floating black lines (axis) altogether

**Comment by jhamman** [comment]
@shoyer - this is great.  My vote is also for `import xarray as xr`.

**Comment by hainm** [comment]
:+1:  for `import xarray as xr`

**Comment by shoyer** [comment]
Looks like `import xarray as xr` it is!

My plan here is to follow IPython's example and simultaneously release version 0.7 of xray and xarray. The former will include a deprecation warning when you import xray advising you to update your code.
