### ISSUE TITLE
Merge wrongfully creating NaN

### ISSUE THREAD

**Issue by guidocioni** [pydata/xarray#7065]
### What happened?

I'm trying to merge the following datasets, which have exactly the same coordinates and extents (not sure why it could cause any conflict).

<img width="711" alt="Screen Shot 2022-09-22 at 09 10 40" src="https://user-images.githubusercontent.com/12760310/191681709-7186eb4b-91f5-44b5-abba-bb6f5b25a70b.png">
<img width="711" alt="Screen Shot 2022-09-22 at 09 10 49" src="https://user-images.githubusercontent.com/12760310/191681727-10facc85-ed98-482d-97fd-87273ee06fdf.png">

After merging them, with `xr.merge([ds, alt])` (the order does not matter), the resulting altitude has NaNs all over the place. I could tell that something wrong was going on because the merge took too long (about 30s, while it should be pretty much instantaneous given the dimensions).

<img width="723" alt="Screen Shot 2022-09-22 at 09 14 01" src="https://user-images.githubusercontent.com/12760310/191682303-771d5503-fd0a-4db4-9325-7cab78593709.png">

Here is a comparison of the altitude before and after the merge

![2d0a1170-0563-420f-8211-086b0ab8d0ae](https://user-images.githubusercontent.com/12760310/191682482-c7aae9c5-d673-492b-9230-8161816aa1cd.png)

![00925051-e64e-4743-afd9-360b2bea50dd](https://user-images.githubusercontent.com/12760310/191682490-f7a9936f-4429-4d91-94ca-bf8c7ab6e33e.png)

If I try to create the `DataArray` manually, that is 

```python
ds['altitude'] = xr.DataArray(data=alt.altitude.values, dims=("lat","lon"))
```
everythign works fine.

### What did you expect to happen?

Normal broadcasting rules should apply and the resulting array should not have NaNs. 

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:43:44) [Clang 13.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: (None, 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.8.1

xarray: 2022.6.0
pandas: 1.5.0
numpy: 1.22.4
scipy: 1.9.1
netCDF4: 1.6.1
pydap: None
h5netcdf: None
h5py: 3.7.0
Nio: None
zarr: 2.12.0
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.3.2
cfgrib: 0.9.10.1
iris: None
bottleneck: 1.3.5
dask: 2022.9.1
distributed: 2022.9.1
matplotlib: 3.6.0
cartopy: 0.21.0
seaborn: 0.12.0
numbagg: None
fsspec: 2022.8.2
cupy: None
pint: 0.19.2
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.3.0
pip: 21.3.1
conda: None
pytest: None
IPython: 8.5.0
sphinx: None

</details>

**Comment by benbovy** [comment]
Hi @guidocioni.

I see that the longitude and latitude coordinates both have different `dtype` in the two input datasets, which likely explains why you have many NaNs and larger sizes (almost 2x) for the `lat` and `lon` dimensions in the resulting datasets.

Here's a small reproducible example:

```python
import numpy as np
import xarray as xr


lat = np.random.uniform(0, 40, size=100)
lon = np.random.uniform(0, 180, size=100)

ds1 = xr.Dataset(
    coords={"lon": lon.astype(np.float32), "lat": lat.astype(np.float32)}
)
ds2 = xr.Dataset(
    coords={"lon": lon, "lat": lat}
)

ds1.indexes["lat"].equals(ds2.indexes["lat"])
# False

xr.merge([ds1, ds2], join="exact")
# ValueError: cannot align objects with join='exact' where index/labels/sizes
# are not equal along these coordinates (dimensions): 'lon' ('lon',)
```

If coordinates labels differ only by their encoding, you could use `xr.merge([ds1, ds2], join="override")`, which will take the coordinates from the 1st object.

**Comment by guidocioni** [comment]
@benbovy you have no idea how much time I spent trying to understand what the difference between the two different datasets was....and I completely missed the `dtype` difference.
That could definitely explain the problem. 

The problem is that I tried to merge with `join='override'` but it was still taking a long time. Probably I wasn't using the right order.

Before closing, just a curiosity: in this corner case shouldn't `xarray` cast automatically the `lat`,`lon` coordinate arrays to the same `dtype` or is it a dangerous assumption?

**Comment by benbovy** [comment]
> The problem is that I tried to merge with join='override' but it was still taking a long time. Probably I wasn't using the right order.

Not 100% sure but maybe `xr.merge` loads all the data from your datasets and performs some equality checks. Perhaps you could see how much time it takes after loading all the data, or try different `xr.merge(compat=)` values?

> Before closing, just a curiosity: in this corner case shouldn't xarray cast automatically the lat,lon coordinate arrays to the same dtype or is it a dangerous assumption?

We already do this for label indexers that are passed to `.sel()`. However, for alignment I think that it would require re-building an index for every cast coordinate, which may be expensive and is probably no ideal if done automatically.

**Comment by benbovy** [comment]
> As my latitude and longitude arrays in both datasets have a resolution of 0.1 degrees, wouldn't it make sense to use np.float16 for both arrays?

I don't think so (at least not currently). The numpy arrays are by default converted to `pandas.Index` objects for each dimension coordinate, and for floats there's only `pandas.Float64Index`. It looks like it will be depreciated in favor of `pandas.NumericIndex` that supports more dtypes, but still [I don't see support for 16 bits floats](https://github.com/pandas-dev/pandas/blob/main/pandas/core/indexes/numeric.py#L95-L108).

Regarding your nearest lat/lon point data selection problem, this is something that could probably be better solved using more specific  (custom) indexes like the ones available in [xoak](https://xoak.readthedocs.io/en/latest/). Xoak only supports point-wise selection at the moment, though.

**Comment by guidocioni** [comment]
> Actually there's another conversion when you reuse an xarray dimension coordinate in array-like computations:
> 
> ```python
> ds = xr.Dataset(coords={"x": np.array([1.2, 1.3, 1.4], dtype=np.float16)})
> 
> # coordinate data is a wrapper around a pandas.Index object
> # (it keeps track of the original array dtype)
> ds.variables["x"]._data
> # PandasIndexingAdapter(array=Float64Index([1.2001953125, 1.2998046875, 1.400390625], dtype='float64', name='x'), dtype=dtype('float16'))
> 
> # This coerces the pandas.Index back as a numpy array
> np.asarray(ds.x)
> # array([1.2, 1.3, 1.4], dtype=float16)
> 
> # which is equivalent to
> ds.variables["x"]._data.__array__()
> # array([1.2, 1.3, 1.4], dtype=float16)
> ```
> 
> The round-trip conversion preserves the original dtype so different execution times may be expected.
> 
> I can't tell much why the results are different (how much are they different?), but I wouldn't be surprised if it's caused by rounding errors accumulated through the computation of a complex formula like haversine.

The difference are larger than I would expect (order of 0.1 in some variables) but could be related to the fact that, when using different precisions, the closest grid points to the target point could change. This would eventually lead to a different value of the variable extracted from the original dataset. 

Unfortunately I didn't have time to verify if it was the case, but I think this is the only valid explanation because the variables of the dataset are untouched. 

It is still puzzling because, as the target points have a precision of e.g. (45.820497820, 13.003510004), I would expect the cast of the dataset coordinates from e.g. (45.8, 13.0) to preserve the 0 (45.800000000, 13.00000000), so that the closest point should not change.

Anyway, I think we're getting off-topic, thanks for the help :)

**Comment by guidocioni** [comment]
Hey @benbovy, sorry for resurrect again this post but today I'm seeing the same issue and for the love of me I cannot understand what is the difference in this dataset that is causing the latitude and longitude arrays to be duplicated...
 
<img width="743" alt="Screen Shot 2022-09-28 at 15 13 27" src="https://user-images.githubusercontent.com/12760310/192788105-524f6d18-4b95-4b2e-bd5a-0513f99c4f39.png">

If I try to merge these two datasets I get one with lat lon doubled in size.
