### ISSUE TITLE
Get ndarray values according dims?

### ISSUE THREAD

**Issue by zhangailin** [pydata/xarray#707]
Suppose the following piece of code:

    import xray
    import numpy as np
    a = xray.DataArray(np.arange(4), dims='x')
    b = xray.DataArray(np.arange(0, 40, 10), dims='y')
    sab = a+b    # 4x4 shape
    sba = b+a    # 4x4 shape
    sab_v = sab.values
    sba_v = sba.values

Here `sab.equals(sba)` will return `False` because of dims order difference(`('x', 'y')` <=> `('y', 'x')`), also `sab_v` and `sba_v` are different. But I guess maybe we can get `values` from `DataArray` according dims? such like:

    sab_v1 = sab.get_values(dims=('x', 'y'))
    sba_v1 = sba.get_values(dims=('x', 'y'))    # explicitly specified dims rather than swap_dims

thus, `sab_v1` and `sba_v1` are equal.

Thanks.

**Comment by shoyer** [comment]
You can use `transpose` for this, e.g., `sba.transpose('x', 'y')` to ensure the order of dimensions is `('x', 'y')`.

**Comment by zhangailin** [comment]
Great!
