### ISSUE TITLE
cannot set figsize when plotting map with cartopy

### ISSUE THREAD

**Issue by Hem-W** [pydata/xarray#7078]
### What happened?

I wish to set the figsize when plotting the map using the `DataArray.plot`, but it would throw `ValueError: cannot use subplot_kws with existing ax`. It seems that `figsize` would generate a tradictional Cartesian axes and refrain `subplot_kws` from setting GeoAxes with cartopy projections. 

### What did you expect to happen?

A map plot with its figsize adjustable. 

Nevertheless, I could bypass this problem around by separately setting a new figure at first with `matplotlib.pyplot.figure` and then plotting with DataArray.
```
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

air = xr.tutorial.open_dataset("air_temperature").air
fig = plt.figure(figsize=(8, 3))
p = air.isel(time=0).plot.pcolormesh(
    subplot_kws=dict(projection=ccrs.PlateCarree(), facecolor="gray"),
    transform=ccrs.PlateCarree(),
)
```
![image](https://user-images.githubusercontent.com/38481514/192086060-4a180068-9d61-40cc-bacd-07a765a911c0.png)

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import cartopy.crs as ccrs

air = xr.tutorial.open_dataset("air_temperature").air
p = air.isel(time=0).plot.pcolormesh(
    figsize=(7, 3.5),
    subplot_kws=dict(projection=ccrs.PlateCarree(), facecolor="gray"),
    transform=ccrs.PlateCarree(),
)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 5>()
      2 import cartopy.crs as ccrs
      4 air = xr.tutorial.open_dataset("air_temperature").air
----> 5 p = air.isel(time=0).plot.pcolormesh(
      6     figsize=(7, 3.5),
      7     subplot_kws=dict(projection=ccrs.PlateCarree(), facecolor="gray"),
      8     transform=ccrs.PlateCarree(),
      9 )

File /srv/conda/envs/notebook/lib/python3.9/site-packages/xarray/plot/plot.py:1310, in _plot2d.<locals>.plotmethod(_PlotMethods_obj, x, y, figsize, size, aspect, ax, row, col, col_wrap, xincrease, yincrease, add_colorbar, add_labels, vmin, vmax, cmap, colors, center, robust, extend, levels, infer_intervals, subplot_kws, cbar_ax, cbar_kwargs, xscale, yscale, xticks, yticks, xlim, ylim, norm, **kwargs)
   1308 for arg in ["_PlotMethods_obj", "newplotfunc", "kwargs"]:
   1309     del allargs[arg]
-> 1310 return newplotfunc(**allargs)

File /srv/conda/envs/notebook/lib/python3.9/site-packages/xarray/plot/plot.py:1210, in _plot2d.<locals>.newplotfunc(darray, x, y, figsize, size, aspect, ax, row, col, col_wrap, xincrease, yincrease, add_colorbar, add_labels, vmin, vmax, cmap, center, robust, extend, levels, infer_intervals, colors, subplot_kws, cbar_ax, cbar_kwargs, xscale, yscale, xticks, yticks, xlim, ylim, norm, **kwargs)
   1206 if "imshow" == plotfunc.__name__ and isinstance(aspect, str):
   1207     # forbid usage of mpl strings
   1208     raise ValueError("plt.imshow's `aspect` kwarg is not available in xarray")
-> 1210 ax = get_axis(figsize, size, aspect, ax, **subplot_kws)
   1212 primitive = plotfunc(
   1213     xplt,
   1214     yplt,
   (...)
   1221     **kwargs,
   1222 )
   1224 # Label the plot with metadata

File /srv/conda/envs/notebook/lib/python3.9/site-packages/xarray/plot/utils.py:443, in get_axis(figsize, size, aspect, ax, **kwargs)
    440     raise ValueError("cannot provide `aspect` argument without `size`")
    442 if kwargs and ax is not None:
--> 443     raise ValueError("cannot use subplot_kws with existing ax")
    445 if ax is None:
    446     ax = _maybe_gca(**kwargs)

ValueError: cannot use subplot_kws with existing ax
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0]
python-bits: 64
OS: Linux
OS-release: 5.14.0-1051-oem
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.8.1

xarray: 2022.6.0
pandas: 1.5.0
numpy: 1.22.4
scipy: 1.9.1
netCDF4: 1.6.1
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.5
dask: 2022.9.1
distributed: 2022.9.1
matplotlib: 3.6.0
cartopy: 0.21.0
seaborn: 0.12.0
numbagg: None
fsspec: 2022.8.2
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.3.0
pip: 22.2.2
conda: None
pytest: None
IPython: 8.5.0
sphinx: None

</details>

**Comment by headtr1ck** [comment]
Thank you for the report.
That is indeed a bug, happens also with other kwargs, not only cartopy.
