### ISSUE TITLE
'to_array' creates a read-only numpy array

### ISSUE THREAD

**Issue by MaximilianR** [pydata/xarray#708]
Is this intended? It's creating some problems downstream with pandas, but maybe that's a pandas issue?

Note the `WRITEABLE : False` here:
```python
In [126]: ds=xray.Dataset({'a':xray.DataArray(pd.np.random.rand(5,3))}, coords={'b': xray.DataArray(pd.np.random.rand(5))})

In [127]: ds.to_array('d').b.values.flags
Out[127]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False
```

Without the `to_array`, it's fine:
```python
In [128]: ds.b.values.flags
Out[128]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```
xref https://github.com/pydata/pandas/issues/11502

**Comment by shoyer** [comment]
Hmm. I can't reproduce this on my machine (using numpy 1.10.2 and the dev version of xray):
```
In [21]: ds.to_array('d').b.values.flags
Out[21]:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

Which version of numpy do you have installed?

My best guess is that this might be someone related to `broadcast_to`, which can create read only numpy arrays. But nothing should be happening to the coordinate arrays at all with `to_array`...

**Comment by MaximilianR** [comment]
You're right - it's on 0.6.1 only. (Apologies...)
