### ISSUE TITLE
Reshaping doc intro looks incomplete

### ISSUE THREAD

**Issue by zmoon** [pydata/xarray#7091]
https://github.com/pydata/xarray/blame/404a6e268d3d83e8bad04768971ba1bc207a155d/doc/user-guide/reshaping.rst#L7

Even though it is a complete sentence, it is missing a period, and probably should be expanded. Or just removed if it's not going to say anything beyond the title ("Reshaping and reorganizing data").

**Comment by mathause** [comment]
Indeed, this looks incomplete. As always - PR very welcome 😁

**Comment by nishtha981** [comment]
Hey!
I'm an outreachy intern, can I be appointed this issue?

**Comment by Amisha2778** [comment]
Hey!
I'm an Outreachy intern, I would love to work on this issue?
