### ISSUE TITLE
Add rename_variables argument to xr.open_dataset() to workaround vars with same names as dims

### ISSUE THREAD

**Issue by veenstrajelmer** [pydata/xarray#7121]
### Is your feature request related to a problem?

Yes, xarray not being able to open netcdf files with non-unique variable/dimension names is an issue for many people. Me personally have come across several files where this is an issue. As a not so nice workaround I use ``drop_variables`` for variables x/y before reading the file with xarray, and then adding them again under a different name with help of the netCDF4 library. It would be very convenient to have a ``rename_variables`` argument for ``xr.open_dataset()`` (and ``xr.open_mfdataset()``).

This suggestion was also made by others in other issues but I cannot find a feature request for it:
_by @jthielen in https://github.com/pydata/xarray/issues/2233#issuecomment-782188310_
_by @markelg in https://github.com/pydata/xarray/issues/2368#issuecomment-415402600_

### Describe the solution you'd like

``rename_variables`` argument for ``xr.open_dataset()`` (and ``xr.open_mfdataset()``).

**Comment by benbovy** [comment]
Hi @veenstrajelmer,

In principle with the recent explicit indexes refactor there is no need anymore to have this restriction. Although we still need to relax this constraint (see #6293 point 2), hopefully this shouldn't be hard work now.

**Comment by veenstrajelmer** [comment]
Thanks for pointing me there
