### ISSUE TITLE
copy of custom index does not align with original

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#7162]
### What happened?

MY prototype CRSIndex is broken on the release version: https://github.com/dcherian/crsindex/blob/main/crsindex.ipynb under heading "BROKEN: Successfully align with a copy of itself"

The cell's code is : 
```
copy = newds.copy(deep=True)
xr.align(copy, newds)
```

which should always work.

@headtr1ck is https://github.com/pydata/xarray/pull/7140 to blame?

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:43:44) [Clang 13.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.8.1

xarray: 2022.10.0
pandas: 1.5.0
numpy: 1.23.3
scipy: 1.9.1
netCDF4: 1.6.0
pydap: None
h5netcdf: 1.0.2
h5py: 3.7.0
Nio: None
zarr: 2.13.3
cftime: 1.6.2
nc_time_axis: 1.4.1
PseudoNetCDF: 3.2.2
rasterio: 1.3.2
cfgrib: 0.9.10.2
iris: 3.3.1
bottleneck: 1.3.5
dask: 2022.9.2
distributed: 2022.9.2
matplotlib: 3.6.1
cartopy: 0.21.0
seaborn: 0.12.0
numbagg: 0.2.1
fsspec: 2022.8.2
cupy: None
pint: 0.19.2
sparse: 0.13.0
flox: 0.6.0
numpy_groupies: 0.9.19
setuptools: 65.5.0
pip: 22.2.2
conda: None
pytest: 7.1.3
IPython: 8.5.0
sphinx: None

</details>

**Comment by headtr1ck** [comment]
I don't think there is anything wrong with the deep copy implementation. Only before it was not deep copying the indexes and now it is.
Can you check if `index1.equals(index2)` works if they are created the same?

**Comment by headtr1ck** [comment]
Now that I think about it, `Indexes.copy_indexes` might also require some update that includes the `memo` argument.
But not sure if that will solve the issue here.

**Comment by benbovy** [comment]
>  Indexes.copy_indexes might also require some update that includes the memo argument. But not sure if that will solve the issue here.

That's a possible cause. Alignment may fail early because `.xindexes` returns different mappings of coordinates vs. index objects. It's worth checking if after copying the dataset, `copy.xindexes` returns the same CRSIndex object for its "x", "y" and "spatial_ref" coordinates.

**Comment by benbovy** [comment]
The refactored alignment logic could be improved (cf. #7002). The error raised in the method below is not very helpful.

https://github.com/pydata/xarray/blob/ab726c536464fbf4d8878041f950d2b0ae09b862/xarray/core/alignment.py#L294-L333

**Comment by headtr1ck** [comment]
Could you create a MVCE without a custom index that I can use for debugging?

**Comment by scottyhq** [comment]
Reviving this exploration with `xarray   : 2023.3.0` and I'm no longer seeing the traceback linked above, so I think this can be closed

```pytb
`File ~/mambaforge/envs/xarray-release/lib/python3.10/site-packages/xarray/core/indexes.py:490, in PandasIndex.equals(self, other)
    488 if not isinstance(other, PandasIndex):
    489     return False
--> 490 return self.index.equals(other.index) and self.dim == other.dim

AttributeError: 'PandasIndex' object has no attribute 'index'
```

**Comment by dcherian** [comment]
Thanks @scottyhq
