### ISSUE TITLE
Release file lock with h5netcdf engine after close

### ISSUE THREAD

**Issue by schwemro** [pydata/xarray#7187]
### What is your issue?

Even after closing a dataset, the file lock is not released which causes a BlockingIOError. It would be great to release the file lock automatically after closing the dataset connection.

**Comment by kmuehlbauer** [comment]
Could you please provide an MVCE? It would also help, if you could add the output of `xr.show_versions()`.

**Comment by dcherian** [comment]
@schwemro Please reopen with a minimal reproducible example when possible. Thanks!
