### ISSUE TITLE
Deprecate cfgrib backend

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#7199]
### What is your issue?

Since cfgrib 0.9.9 (04/2021) it comes with its own xarray backend plugin (looks mainly like a copy of our internal version).
We should deprecate our internal plugin.

The deprecation is complicated since we usually bind the minimum version to a minor step, but cfgrib seems to be on 0.9 since 4 years already. Maybye an exception like for netCDF4?

Anyway, if we decide to leave it as it is for now, this ticket is just a reminder to remove it someday :)

**Comment by dcherian** [comment]
cc @alexamici

**Comment by headtr1ck** [comment]
Any ideas on how to deprecate this?
Do we raise a Deprecation warning if someone uses the open_dataset method of the internal backend?
And then remove it some versions down the line?

**Comment by dcherian** [comment]
cc @alexamici

**Comment by alexamici** [comment]
@dcherian note that _cfgrib_ is now maintained by @iainrussell, anyway I agree that the in-tree driver can be safely removed.

@headtr1ck I don't think any deprecation is needed, the `engine="cfgrib"` should select the external backend if available and fall back on the internal one only for ancient versions of _cfgrib_.
