### ISSUE TITLE
The new NON_NANOSECOND_WARNING is not very nice to end users

### ISSUE THREAD

**Issue by hmaarrfk** [pydata/xarray#7237]
### What is your issue?

The new nanosecond warning doesn't really point anybody to where they should change their code.

Nor does it really tell them how to fix it.

```
import xarray as xr
import numpy as np
xr.DataArray(np.zeros(1, dtype='datetime64[us]'))
```
yields

```
xarray/core/variable.py:194: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values.
```

https://github.com/pydata/xarray/blob/f32d354e295c05fb5c5ece7862f77f19d82d5894/xarray/core/variable.py#L194

I think at the very least, the stacklevel should be specified when calling the `warn` function.

It isn't really pretty, but I've been passing a parameter when I expect to pass up a warning to the end user:
eg. https://github.com/vispy/vispy/pull/2405

However, others have not liked that approach.

**Comment by spencerkclark** [comment]
For the time being xarray *should* behave as it always has, converting any non-nanosecond precision times to nanosecond-precision before being used internally.

**Comment by djhoese** [comment]
And with new pandas (which I understand as being the thing/library that is changing) and new xarray, what will happen? What happens between nano and non-nano times?

**Comment by spencerkclark** [comment]
Xarray will convert any non-nanosecond precision times to nanosecond precision (or an error will be raised if this is not possible).
