### ISSUE TITLE
include/exclude lists in Dataset.expand_dims

### ISSUE THREAD

**Issue by hmaarrfk** [pydata/xarray#7239]
### Is your feature request related to a problem?

I would like to be able to expand the dimensions of a dataset, but most of the time, I only want to expand the datasets of a few key variables.

It would be nice if there were some kind of filter mechanism.

### Describe the solution you'd like

```python
import xarray as xr
dataset = xr.Dataset(data_vars={'foo': 1, 'bar': 2})
dataset.expand_dims("zar", include_variables=["foo"])
# Only foo is expanded, bar is left alone.
```

### Describe alternatives you've considered

Writing my own function. I'll probably do this.

Subclassing. Too confusing and easy to "diverge" from you all when you do decide to implment this.

### Additional context

For large datasets, you likely just want some key parameters expanded, and not all parameters expanded.

xarray version: 2022.10.0

**Comment by headtr1ck** [comment]
If it's only a single variable you could do:
```
dataset["foo"] = dataset["foo"].expand_dims("zar")
```

**Comment by dcherian** [comment]
You can also generalize to
```
dataset = dataset.update(dataset[[vars_to_expand]].expand_dims(...))
```

**Comment by keewis** [comment]
note that the return value of `update` is deprecated, since `update` is one of the few in-place operations `xarray` has. Going forward it should be:
```python
dataset.update(dataset[[vars_to_expand]].expand_dims(...))
```

**Comment by hmaarrfk** [comment]
I think these are good alternatives.

From my experiments (and I'm still trying to create a minimum reproducible code that shows the real problem behind the slowdowns) reindexing can be quite an expensive. We used to have many coordinates (to ensure that critical metdata stays with data_variables) and those coordinates were causing slowdowns on reindexing operations.

Thus the two calls `update` and `expand_dims` might cause two reindex merges to occur. 

However, for this particular issue, I think that documenting the strategies proposed in the docstring is good enough. I have a feeling if one can get to the bottom of 7224, the performance concerns here will be mitigated too.

We can leave the performance discussion to: https://github.com/pydata/xarray/issues/7224

**Comment by akanshajais** [comment]
a workaround for achieving this would be to use the apply method of xarray data structures along with the expand_dims method. Here's an example of how we can use it:

```
import xarray as xr
dataset = xr.Dataset(data_vars={'foo': 1, 'bar': 2})

# Define a function that expands the given variable along a new dimension
def expand_variable(da):
    if da.name == 'foo':
        return da.expand_dims('zar')
    else:
        return da

# Use the apply method to apply the function to only the desired variables
expanded_dataset = dataset.apply(expand_variable, keep_attrs=True)

print(expanded_dataset)

```
Here, the expand_variable function is defined to only expand the variable with the name 'foo' along a new dimension. The apply method is used to apply this function to each data variable in the dataset, but only 'foo' is actually modified.

**Comment by max-sixty** [comment]
> note that the return value of `update` is deprecated, since `update` is one of the few in-place operations `xarray` has. Going forward it should be:

Assign should work well here to avoid mutating the original object!

```python
ds = ds.assign(**dataset[[vars_to_expand]].expand_dims(...))
```

---

Is there anything to do here or should we close?
