### ISSUE TITLE
Behavior of ds.rename when old and new name are the same

### ISSUE THREAD

**Issue by spencerahill** [pydata/xarray#724]
Before #648, passing `Dataset.rename` a `name_dict` whose keys and values were identical did not raise an exception.  Now, however, it raises a ValueError:
```python
arr = xr.DataArray(range(2), name='arrname')
ds = arr.to_dataset()
ds.rename({'dim_0':'dim_0'})
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-a5b851f9fb10> in <module>()
----> 1 ds.rename({'dim_0':'dim_0'})

/Users/spencerahill/anaconda/lib/python2.7/site-packages/xarray/core/dataset.pyc in rename(self, name_dict, inplace)
   1245                                  "variable in this dataset" % k)
   1246             if v in self:
-> 1247                 raise ValueError('the new name %r already exists' % v)
   1248
   1249         variables = OrderedDict()

ValueError: the new name 'dim_0' already exists
```

This is easy enough to handle with a try/except clause in my own code, but it would be nice (for me at least) for `rename` to not raise anything for these cases.  Since the result is simply the original Dataset unchanged, this could be implemented by replacing line 1246 with `if v in self and k != v:`

The use case is that we have data coming from multiple sources, often with differing internal names for coordinates and variables, and we're programmatically forcing them to have consistent names via `rename`.  Sometimes, a piece of data already has the name that we are after, hence the non-rename `rename`.  Thanks!

**Comment by shoyer** [comment]
I agree, this should be OK.

A pull request with this fix would be greatly appreciated! Be sure to add an appropriate test in `xarray/test/test_dataset.py`.

**Comment by spencerahill** [comment]
Sure, will do in the coming days or over the weekend.  Thanks.
