### ISSUE TITLE
open_dataset class doesn't respond to groupstr kwarg

### ISSUE THREAD

**Issue by NilsHoebe** [pydata/xarray#7256]
### What is your issue?

To begin with I'm an absolute noob concerning GitHub repos so forgive me in advance.  I'm using some xarray classes in an IDE (Spyder) to analyse climate data. In the process I've decided to write my own NetCDF4 dataset using rooted groups for all different climate models. My entire code is based on reading and computing the .nc files using xr.open_dataset, however, I've come to find that besides not displaying the groups from the parent group (known issue), it doesn't load the requested group neither.  Looks like the class always loads the first available group in the NetCDF4 data set that is available/listed.

**Comment by keewis** [comment]
I'm not sure if this is a typo, but `open_dataset` does not / should not have have a kwarg named `groupstr`, it should be `group` (so you *should* get an error, if not this is a bug?). If that's not it, could you post the code you're using to open the dataset, and also the output of `xr.show_versions`?

If you have multiple groups in your files, you might also be interested in [`datatree`](https://github.com/xarray-contrib/datatree), which will open *all* groups from the file in a tree structure.

**Comment by NilsHoebe** [comment]
Grateful for your fast reply, I'm aware that the kwarg is 'group', however this neither works (some documentation refers to it as 'groupstr' thats why I mentioned it that way, I will continue with 'group'). The `datatree` class you mentioned is very interesting, is it yet available for me to use as a package? Anytime soon I will elaborate on my problem with some piece of code, however for now it seems like most developers are aware of the problem concerning loading nested groups in xarray.

**Comment by keewis** [comment]
you can install it using `xarray-datatree`, and my experience with it so far is good. As far as I can tell, it's still experimental, though (correct me if I'm wrong, @TomNicholas)

**Comment by mathause** [comment]
For context: the `group` / `groupstr`confusion may stem from our (quite) old docs, where the type hints were not rendered nicely: https://docs.xarray.dev/en/v0.12.3/generated/xarray.open_dataset.html

**Comment by TomNicholas** [comment]
@NilsHoebe to clarify, are you still unable to open the desired group even when you use `group` as the kwarg? If so a [minimal example](https://github.com/pydata/xarray/discussions/5404#discussion-3388275) would help us to help you!

**Comment by TomNicholas** [comment]
> The datatree class you mentioned is very interesting, is it yet available for me to use as a package?

Also yes you can [find datatree here](https://github.com/xarray-contrib/datatree), though it's a bit experimental compared to the rest of xarray.
