### ISSUE TITLE
mypy complaint about `.to_netcdf` `encoding`

### ISSUE THREAD

**Issue by zmoon** [pydata/xarray#7258]
### What happened?

```
error: Argument "encoding" to "to_netcdf" of "Dataset" has incompatible type "Dict[str, Dict[str, int]]";
expected "Optional[Mapping[Hashable, Mapping[str, Any]]]"
```
Those sound compatible to me, so I am a bit confused.

I am using something like
```python
encoding = {"variable_name": {"zlib": True, "complevel": 5}}
ds.to_netcdf(..., encoding=encoding)
```

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

mypy 0.982, xarray 2022.10.0

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('English_United States', '1252')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 2022.10.0
pandas: 1.5.1
numpy: 1.23.4
scipy: 1.9.3
netCDF4: 1.6.0
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.3.2
cfgrib: None
iris: None
bottleneck: None
dask: 2022.8.1
distributed: None
matplotlib: 3.6.1
cartopy: 0.21.0
seaborn: 0.11.2
numbagg: None
fsspec: 2022.7.1
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.2.0
pip: 22.3
conda: None
pytest: 7.2.0
IPython: 8.4.0
sphinx: 4.5.0
</details>

**Comment by headtr1ck** [comment]
Invariance strikes again...

Could you check if it is fixed if you annotate your dict as `dict[typing.Hashable, dict[str, typing.Any]]`?

**Comment by zmoon** [comment]
Yes mypy is pleased with `encoding: Dict[Hashable, Dict[str, Any]]` (or if pass `encoding` as dict literal instead of creating a variable beforehand).

**Comment by headtr1ck** [comment]
I think we have to change the typing to `Mapping[Any, Mapping[str, Any] | None`

This should be a simple PR, could I interest you in submitting one?

**Comment by headtr1ck** [comment]
The problem is that a dict is invariant in it's keys so your variable is a `dict[str, Any]` but the function was typed as `dict[Hashable, Any]`. Now the problem is that a dict is mutable and the function could modify the dict, but it might write non-str keys, which you might not expect.

Why it does not work with a `Mapping` that in principle is read-only, I don't know.

**Comment by zmoon** [comment]
Ah, I thought it might be something like that when you mentioned invariance earlier. Thanks!
