### ISSUE TITLE
groupby and mean on a MultiIndex level raises ValueError

### ISSUE THREAD

**Issue by jjpr-mit** [pydata/xarray#7282]
### What happened?

After using `set_index` to create a `MultiIndex`, calling `groupby` on a `MultiIndex` level and then `mean` raises an error.  

### What did you expect to happen?

Apply mean to groups, no error.  

### Minimal Complete Verifiable Example

```Python
d = DataArray(
    data=[
        [0, 1, 2, 3, 4, 5, 6],
        [7, 8, 9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]
    ],
    coords={
        "greek": ("a", ['alpha', 'beta', 'gamma']),
        "colors": ("a", ['red', 'green', 'blue']),
        "compass": ("b", ['north', 'south', 'east', 'west', 'northeast', 'southeast', 'southwest']),
        "integer": ("b", [0, 1, 2, 3, 4, 5, 6]),
    },
    dims=("a", "b")
)
d = d.set_index(a=['greek', 'colors'], b=['compass', 'integer'])
g = d.groupby('greek')
m = g.mean(...)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/xarray/core/_aggregations.py", line 5698, in mean
    return self.reduce(
  File "/usr/local/lib/python3.10/site-packages/xarray/core/groupby.py", line 1201, in reduce
    return self.map(reduce_array, shortcut=shortcut)
  File "/usr/local/lib/python3.10/site-packages/xarray/core/groupby.py", line 1104, in map
    return self._combine(applied, shortcut=shortcut)
  File "/usr/local/lib/python3.10/site-packages/xarray/core/groupby.py", line 1136, in _combine
    index, index_vars = create_default_index_implicit(coord)
  File "/usr/local/lib/python3.10/site-packages/xarray/core/indexes.py", line 1045, in create_default_index_implicit
    index = PandasMultiIndex(array, name)
  File "/usr/local/lib/python3.10/site-packages/xarray/core/indexes.py", line 615, in __init__
    raise ValueError(
ValueError: conflicting multi-index level name 'greek' with dimension 'greek'
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.7 (main, Sep 13 2022, 14:31:33) [GCC 10.2.1 20210110]
python-bits: 64
OS: Linux
OS-release: 5.15.49-linuxkit
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2022.11.0
pandas: 1.5.1
numpy: 1.23.4
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 63.2.0
pip: 22.2.2
conda: None
pytest: None
IPython: None
sphinx: None

</details>

**Comment by mschrimpf** [comment]
This error occurs in versions `2022.6` through `2022.11`. The code worked fine in previous versions, e.g. in `2022.3.0` it executes as expected.
Related: https://github.com/pydata/xarray/issues/6836.

**Comment by benbovy** [comment]
Thanks @jjpr-mit and @mschrimpf for the report. See https://github.com/pydata/xarray/issues/6836#issuecomment-1313739883.

**Comment by benbovy** [comment]
The example above now works (v2023.8.0) without flox:

```python
with xr.set_options(use_flox=False):
    m = g.mean(...)
```

```
<xarray.DataArray (greek: 3)>
array([ 3., 10., 17.])
Coordinates:
  * greek    (greek) object 'alpha' 'beta' 'gamma'
```

But it still fails with flox:

```python
with xr.set_options(use_flox=True):
    m = g.mean(...)
```

```
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
```



cc @dcherian

**Comment by dcherian** [comment]
This example is working with flox  0.7.2. I'm going to close  but feel free to reopen if it doesn't work for you.

**Comment by mschrimpf** [comment]
@dcherian Still fails for me
```bash
>>> xarray.__version__
'2023.1.0'
>>> g = d.groupby('greek')
>>> g.mean(...)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".....lib/python3.8/site-packages/xarray/core/_aggregations.py", line 5698, in mean
    return self.reduce(
  File ".....lib/python3.8/site-packages/xarray/core/groupby.py", line 1210, in reduce
    return self.map(reduce_array, shortcut=shortcut)
  File ".....lib/python3.8/site-packages/xarray/core/groupby.py", line 1113, in map
    return self._combine(applied, shortcut=shortcut)
  File ".....lib/python3.8/site-packages/xarray/core/groupby.py", line 1145, in _combine
    index, index_vars = create_default_index_implicit(coord)
  File ".....lib/python3.8/site-packages/xarray/core/indexes.py", line 1057, in create_default_index_implicit
    index = PandasMultiIndex(array, name)
  File ".....lib/python3.8/site-packages/xarray/core/indexes.py", line 627, in __init__
    raise ValueError(
ValueError: conflicting multi-index level name 'greek' with dimension 'greek'
```
