### ISSUE TITLE
einops integration?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#7295]
### Is your feature request related to a problem?

I've been following https://github.com/arogozhnikov/einops with interest, and thought it would be worth raising whether we could offer an xarray integration, eventually inspired by the `reshape` discussion at https://github.com/pydata/xarray/discussions/7217#discussioncomment-4150613. (I thought there might have been a discussion / issue already, but couldn't find one).

Einops offers a string query to do common array operations. There's a good intro at https://github.com/arogozhnikov/einops/blob/master/docs/1-einops-basics.ipynb

The

### Describe the solution you'd like

Because our dimension names are full names, it wouldn't be quite as terse, and it has lots of overlap with our existing operations. But I find string queries are often easy to understand, particularly for those who have less experience with xarray but are familiar with einsum & frends [^1].

### Applying einops to xarray

The einops example, (no xarray yet):

```python
rearrange(ims, 'b h w c -> h (b w) c')
```

This could likely be something like, noting that we don't need the string before the `->`, as our names are already defined:

```python
rearrange(ims, '-> height (batch width) color')
```

...or, if we wanted to name the new dimension rather than take an implicit dimension name like `batch_width`, at the cost of new einops syntax:

```python
rearrange(ims, '-> height width=(batch width) color')
```

...or if we wanted a method on a DataArray:

```python
ims.einops.rearrange('height width=(batch width) color')
```

Sometimes we would want the lvalue; e.g. to unstack:

```python
rearrange(ims, 'batch (height height2) color -> height (batch width) color', height2=2)
```

...and the same principles apply for reductions such as `mean`, for example

```python
ims.einops.reduce('-> height width color', 'mean')
```

...would be equivalent to:

```python
ims.mean('batch')

# or

ims.groupby(['height', 'width', 'color']).mean(...)
```

[^1]: I frequently find myself using `.query`, or `pd.eval`, also string queries, and these are great with tools that take user input and folks can pass a string

### Additional context

This probably needs a champion to drive, and realistically that's probably not me for quite a while. But if we can get consensus that this would be interesting, and someone is up for doing it, I think this could be a v cool feature.

I'll also tag @arogozhnikov for info

**Comment by dcherian** [comment]
See https://einstats.python.arviz.org/en/latest/tutorials/einops-basics-port.html

cc @OriolAbril

**Comment by OriolAbril** [comment]
I would be happy to integrate einops functionality better with xarray. Also feedback and contributions for xarray-einstats will be very welcome.

That being said, I haven't worked with accessors yet, so I would need some help to try and add this.

**Comment by dcherian** [comment]
Here's our documentation on accessors: https://docs.xarray.dev/en/stable/internals/extending-xarray.html#extending-xarray

It's surprisingly easy. But please let us know if/where the docs are confusing and ask any questions here.

**Comment by OriolAbril** [comment]
Finally had some time to play around with the accessors, I have opened a PR adding them: https://github.com/arviz-devs/xarray-einstats/pull/51

**Comment by dcherian** [comment]
Very nice!
