### ISSUE TITLE
DataArray.reindex of empty array changes dtype from float32 to float64

### ISSUE THREAD

**Issue by eugene57** [pydata/xarray#7299]
### What happened?

When I reindex an empty DataArray with float32 dtype, result's dtype is actually float64. Note that this does not happen when the original DataArray is not empty.

### What did you expect to happen?

Dtype of `reindex` result should match dtype of the original DataArray.

### Minimal Complete Verifiable Example

```Python
import xarray as xr

x = xr.DataArray([], dims=('x',), coords={'x': []}).astype('float32')
y = x.reindex(x=[1., 2.])
print(x.dtype, y.dtype)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.12 (main, Mar 23 2022, 21:36:19) 
[GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 4.14.13-1.el7.elrepo.x86_64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 2022.3.0
pandas: 1.4.2
numpy: 1.21.5
scipy: 1.8.0
netCDF4: 1.5.8
pydap: None
h5netcdf: None
h5py: 3.6.0
Nio: None
zarr: 2.11.1
cftime: 1.6.0
nc_time_axis: 1.4.1
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.4
dask: 2022.02.1
distributed: 2022.2.1
matplotlib: 3.5.2
cartopy: None
seaborn: 0.11.2
numbagg: 0.2.1
fsspec: 2022.3.0
cupy: None
pint: None
sparse: 0.13.0
setuptools: 61.2.0.post0
pip: 22.0.4
conda: None
pytest: 7.1.1
IPython: 8.4.0
sphinx: 4.5.0

</details>

**Comment by eugene57** [comment]
Difference between empty and non-empty arrays comes from different logic used for empty arrays in `Variable._getitem_with_mask`.

The problem itself can be solved by fixing `dtypes.maybe_promote` to return `fill_value=np.float32('nan')` instead of `fill_value=np.nan` on `dtype('float32')` input.

**Comment by dcherian** [comment]
> The problem itself can be solved by fixing dtypes.maybe_promote to return fill_value=np.float32('nan') instead of fill_value=np.nan on dtype('float32') input.

This seems like better behaviour to me. @shoyer, what do you think?

**Comment by shoyer** [comment]
> Difference between empty and non-empty arrays comes from different logic used for empty arrays in `Variable._getitem_with_mask`.
> 
> The problem itself can be solved by fixing `dtypes.maybe_promote` to return `fill_value=np.float32('nan')` instead of `fill_value=np.nan` on `dtype('float32')` input.

Thanks for the excellent report!

I agree, this sounds like a good fix to me.

I think something like the following would work: Replace the return line of `maybe_promote`
```python
    return np.dtype(dtype), fill_value
```
with
```python
    dtype = np.dtype(dtype)
    fill_value = dtype.type(fill_value)
    return dtype, fill_value
```
