### ISSUE TITLE
Support for python 3.11

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#7316]
### Is your feature request related to a problem?

Now that python 3.11 has been released, we should start to support it officially.

### Describe the solution you'd like

I guess the first step would be to replace python 3.10 as a maximum version in the tests and see what crashes (and get lucky).

**Comment by sxwebster** [comment]
@dcherian Numba is looking at having a Python 3.11 RC ready by [end of year](https://github.com/numba/numba/issues/8304), hopefully. It would be lovely to see Numba + Xarray catch up as 3.11 (and 3.12) look to have some big speed improvements.
