### ISSUE TITLE
0.7 missing Python 3.3 conda package

### ISSUE THREAD

**Issue by richardotis** [pydata/xarray#732]
```
$ conda info xarray
Fetching package metadata: ....

xarray 0.7.0 py35_0
-------------------
file name   : xarray-0.7.0-py35_0.tar.bz2
name        : xarray
version     : 0.7.0
build number: 0
build string: py35_0
channel     : defaults
size        : 317 KB
date        : 2016-01-26
license     : Apache
md5         : b7d2c2e88f370bc701c44307772615ce
installed environments:
    /home/rotis/anaconda/envs/calphadpy3
dependencies:
    numpy
    pandas >=0.15
    python 3.5*
    setuptools

xarray 0.7.0 py34_0
-------------------
file name   : xarray-0.7.0-py34_0.tar.bz2
name        : xarray
version     : 0.7.0
build number: 0
build string: py34_0
channel     : defaults
size        : 319 KB
date        : 2016-01-26
license     : Apache
md5         : 784da1f14fd7b9b7c09b7229558abcd4
installed environments:
dependencies:
    numpy
    pandas >=0.15
    python 3.4*
    setuptools

xarray 0.7.0 py27_0
-------------------
file name   : xarray-0.7.0-py27_0.tar.bz2
name        : xarray
version     : 0.7.0
build number: 0
build string: py27_0
channel     : defaults
size        : 308 KB
date        : 2016-01-26
license     : Apache
md5         : bd9f94bcc78b18aac44be0340cc30913
installed environments:
dependencies:
    numpy
    pandas >=0.15
    python 2.7*
    setuptools
```

And for the legacy xray package
```
$ conda info xray==0.7
Fetching package metadata: ....

xray 0.7.0 py35_0
-----------------
file name   : xray-0.7.0-py35_0.tar.bz2
name        : xray
version     : 0.7.0
build number: 0
build string: py35_0
channel     : defaults
size        : 318 KB
date        : 2016-01-26
license     : Apache
md5         : 1aedbfacd688558f4f003b38498264c3
installed environments:
dependencies:
    pandas
    python 3.5*
    setuptools

xray 0.7.0 py34_0
-----------------
file name   : xray-0.7.0-py34_0.tar.bz2
name        : xray
version     : 0.7.0
build number: 0
build string: py34_0
channel     : defaults
size        : 319 KB
date        : 2016-01-26
license     : Apache
md5         : b3e4e00c5b19fa92c97781444b298cf2
installed environments:
dependencies:
    pandas
    python 3.4*
    setuptools

xray 0.7.0 py27_0
-----------------
file name   : xray-0.7.0-py27_0.tar.bz2
name        : xray
version     : 0.7.0
build number: 0
build string: py27_0
channel     : defaults
size        : 308 KB
date        : 2016-01-26
license     : Apache
md5         : 0af8b0e23e579d79363193d52827cccd
installed environments:
dependencies:
    pandas
    python 2.7*
    setuptools
```

**Comment by ocefpaf** [comment]
@richardotis any special reason for wanting a Python 3.3 version?  The migration to >=3.4 is highly recommended. (And I don't think continuum and the community building stuff for Python 3.3 lately.)

If you cannot upgrade you can use [this](https://github.com/ioos/conda-recipes/blob/master/xarray/meta.yaml) recipe to build you own Python 3.3 `xarray`.

If you clone the whole repo you can then type:

```shell
export CONDA_PY=33
export CONDA_NPY=110 # (or any other numpy version series you need 18, 19...)
conda build xarray
```

If you issue the last command from the repo root directory conda will build dependencies for you.

**Comment by richardotis** [comment]
I run py35 personally but my library pycalphad supports py27 and py33+. I noticed this issue when I updated my CI configuration to use "xarray" and only the py33 builds were failing.

**Comment by richardotis** [comment]
So it appears that xray hasn't pushed a py33 conda release since 0.5.2, and I didn't notice because conda happily installed that version in my py33 tests and everything worked. With the name change, it can't find a compatible version anymore.

For dependency resolution purposes I would appreciate an official py33 release of xarray 0.7, or even "xarray 0.5.2" if there's been some kind of breaking change just so that conda can find the package.

**Comment by ocefpaf** [comment]
The use of "official release" can be confusing in this case.  I believe that the latest xarray works OK in Python 3.3. But note that the project is not tested on Python 3.3 since PR https://github.com/pydata/xarray/pull/583. I believe that the official PyPI source dist will install OK in Python 3.3 BTW.

On the other hand, Continuum does seem to be abandoning Python 3.3, there are hardly new conda packages being built for it.

**Comment by richardotis** [comment]
That's true. I just looked and saw numpy's last Python 3.3 build was 1.9.2. On the other hand, I feel that the xarray package rename has created a special case. Without the rename, pycalphad could continue its py33 support indefinitely as long as nothing happened to the relevant xarray APIs (not guaranteed, I understand that).

I'm happy to drop support for deprecated versions when I have to, but with xarray being a pure Python package and seemingly happily running on the latest py33 versions of its dependencies, I don't think it's too much to ask for one more py33 build after the rename.

**Comment by richardotis** [comment]
It occurs to me that, since xarray is in the "defaults" channel, this probably has to do with a policy at Continuum and so I might be better off just hosting a py33 version of xarray in my own conda channel.

**Comment by ocefpaf** [comment]
> I don't think it's too much to ask for one more py33 build after the rename.

Yes and no. If you want the full optional dependencies, `xarray` can be a little bit hard to build (with `pynio` support, etc).  If you want just the basics then it is relatively easy.

You should make the conda package request in https://github.com/ContinuumIO/anaconda-issues/issues/635, and other continuum communication channels (mailing list, gitter, etc).

**Comment by jhamman** [comment]
> but with xarray being a pure Python package and seemingly happily running on the latest py33 versions of its dependencies

It would probably be just as easy for you to build xarray from source then.  Or use pip.  Both options should work with 3.3.

**Comment by richardotis** [comment]
That's what I'm going to do. Thanks for the help.

**Comment by richardotis** [comment]
For anyone else who runs into this, I built a minimal conda package for xarray 0.7 for Python 3.3. It's in the `richardotis` channel on anaconda.org. Since I make no promises it will be indefinitely maintained, here is the conda.yaml. Put the file in a directory by itself, cd into it and use `conda build . --python 3.3` to build.
```yaml
package:
    name: xarray
    version: 0.7.0
source:
    git_url: https://github.com/pydata/xarray.git
    git_tag: v0.7.0
requirements:
    build:
        - python
        - setuptools
        - pandas
    run:
        - python
        - pandas

build:
    script: python setup.py install
test:
    imports:
        - xarray
about:
    home: https://github.com/pydata/xarray
    license: Apache
    summary: 'N-Dimensional Labeled Arrays'
```
