### ISSUE TITLE
Memory issues arising when trying to make dataArray values JSON serializable

### ISSUE THREAD

**Issue by adanb13** [pydata/xarray#7324]
### What is your issue?

Need to return the data values in a JSON serializable format, calling `.tolist` and `.to_dict` consume so much memory that it produces a `Memory Error`

When trying to get the data values via the 2 methods above from a dataset the size of `831 MiBs` the system memory being used jumped to `43 G` before crashing (on a system of `64 G` memory capacity). Producing a `Memory Error`

Need more memory efficient way of returning final data values.

Addressed in the following PR: https://github.com/pydata/xarray/pull/7323

**Comment by jhamman** [comment]
@adanb13 - thanks for opening this issue. It would be helpful if you can share a sample workflow that produces the memory error that you mention above.

**Comment by jhamman** [comment]
Closing due to lack of response. @adanb13 - please feel free to reopen this if you would like to discuss this topic more.
