### ISSUE TITLE
Zarr groups (grouped) loader and operations

### ISSUE THREAD

**Issue by itsgifnotjiff** [pydata/xarray#7341]
### Is your feature request related to a problem?

I work in geospatial sciences and use Zarr, Xarray, NetCDF etc. but it is at the moment very hard to create a Xarray Dataset that contains multiple grids and dimensions.

### Describe the solution you'd like

Ideally I would love to be able to open Zarr store with groups where attributes are preserved and identified by Xarray for easier interoperability with HoloViz and others. 

### Describe alternatives you've considered

Right now I try and add the groups of a Zarr store one by one as variables but that is hacky and does not necessarily preserve attributes.

**Comment by TomNicholas** [comment]
@keewis https://github.com/pydata/xarray/pull/7338 mentions datatree, so we could refer people back to there from now on?
