### ISSUE TITLE
`xr.DataArray.plot.pcolormesh(robust="col/row")`

### ISSUE THREAD

**Issue by aaronspring** [pydata/xarray#7342]
### Is your feature request related to a problem?

I often want to get a quick view from multi-dimensional data from an `xr.Dataset` with multiple variables at once in a one-liner. I really like the `robust=True` feature and think it could also allow `"col"` and `"row"` to be robust only across columns or rows.

### Describe the solution you'd like

```python
ds = xr.tutorial.load_dataset("eraint_uvz")
ds.mean("month").to_array().plot(col="level", row="variable", robust="row")
```
What I get and do not like because it apply robust either to all data or nothing:
![image](https://user-images.githubusercontent.com/12237157/205099862-a74d2a75-c91f-4b01-b667-be367d01d01c.png)

What I would like to see, see below in alternative what I always do

### Describe alternatives you've considered

```python
ds = xr.tutorial.load_dataset("eraint_uvz")
for v in ds.data_vars:
    ds[v].mean("month").plot(col="level", robust=True)
    plt.show()
```
![image](https://user-images.githubusercontent.com/12237157/205099760-7fc2f7b5-c473-4818-9e9f-6d541f2712e6.png)

**Comment by shoyer** [comment]
The "robust" part is really just a modification to how the limits for color scales are chosen, i.e., ignoring the bottom and top 2% of the dtaa from the color scale. So it sounds like what you're hoping for is separate per-column or per-row color scaling?

**Comment by aaronspring** [comment]
True. 

> So it sounds like what you're hoping for is separate per-column or per-row color scaling?

Exactly.

**Comment by aaronspring** [comment]
Closing in favour of https://github.com/pydata/xarray/issues/7369
