### ISSUE TITLE
Implement vnorm for xarray with dask support

### ISSUE THREAD

**Issue by deanpospisil** [pydata/xarray#735]
Similarly to  #723 I'd like to see if I can port vnorm from Dask into xarray. This a useful quick operation to have handy for linear models. 
Previously as I work around I tried:
`n = da.reduce(np.linalg.norm, ['shapes', 'x'] )`
but it quickly explodes (eats up all ram) for large DaskArrays

**Comment by shoyer** [comment]
I would be OK adding a `norm` method, although I don't think there's a super strong need for it -- usually I've been happy writing expressions like `(x ** 2).sum(['shapes', 'x']) ** 0.5` instead.

You would either need to implement this all in xarray, or preferably write `da.linalg.norm` in dask and use that take. Take a look at [the scipy source code](https://github.com/numpy/numpy/blob/v1.10.0/numpy/linalg/linalg.py#L1976-L2221) for this function -- I suspect you should port this almost directly to dask.

**Comment by deanpospisil** [comment]
> 
I would be OK adding a norm method, although I don't think there's a super strong need for it -- usually I've been happy writing expressions like (x ** 2).sum(['shapes', 'x']) ** 0.5 instead.

When using large dask arrays that operation tended to fill up ram. I'm not sure why, but it made the dask objects very large, I don't have a good understanding of how those graphs are constructed so I was unable to track down the problem.

I tried out `da.std(['shapes', 'x'])` and it worked like a charm, but it felt a little silly rescaling it to get the norm.

> 
You would either need to implement this all in xarray, or preferably write da.linalg.norm in dask and use that take. Take a look at the scipy source code for this function -- I suspect you could port this almost directly to dask.

`dask` has a `vnorm`, 
http://dask.pydata.org/en/latest/array-api.html?highlight=norm#dask.array.core.Array.vnorm
which I am currently trying to make use of, using the very helpful:
 `ops._dask_or_eager_func('vnorm', n_array_args=1)`
unfortunately numpy calls their norm `norm` as opposed to `vnorm` so I think I'll need to put in a switch depending on the array type before hitting `_dask_or_eager_func`

**Comment by shoyer** [comment]
Looks like it would be worth writing a cross-compatible `vnorm` in `xarray/core/ops.py`. Take a look at that module for [examples](https://github.com/pydata/xarray/blob/v0.7.0/xarray/core/ops.py#L161-L165) of how we wrote custom wrapper -- this should be pretty straightforward
