### ISSUE TITLE
Coordinate variable gains coordinate on subset

### ISSUE THREAD

**Issue by dopplershift** [pydata/xarray#7350]
### What happened?

When subsetting a DataArray along a dimension down to a single item, the other coordinate variables gain this scalar coordinate.

### What did you expect to happen?

Coordinate variables should not have their coordinates changed.

### Minimal Complete Verifiable Example

```Python
import numpy as np
import xarray as xr

lat = np.array([25, 35, 45])
lon = np.array([-105, -95, -85, -75])
time = np.array([0, 1])

data = np.arange(lat.size * lon.size * time.size)
test_data = xr.DataArray(data.reshape((time.size, lat.size, lon.size)),
                         coords=dict(lat=lat, lon=lon, time=time),
                         dims=('time', 'lat', 'lon'))

print(test_data.lat.coords)  # Only 'lat'
print(test_data.isel(time=0).lat.coords)  # Has both 'lat' and 'time'
pritn(test_data.isel(time=[0, 1]).lat.coords)  # Only 'lat'
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Anything else we need to know?

This occurs with both the latest 2022.11.0 release and current main.

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:31:57) [Clang 14.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.8.1

xarray: 2022.11.0
pandas: 1.5.2
numpy: 1.23.5
scipy: 1.9.3
netCDF4: 1.6.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.10.2
iris: None
bottleneck: 1.3.5
dask: 2022.6.1
distributed: 2022.6.1
matplotlib: 3.6.2
cartopy: 0.21.0
seaborn: None
numbagg: None
fsspec: 2022.11.0
cupy: None
pint: 0.20.1
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.5.1
pip: 22.3.1
conda: None
pytest: 7.2.0
IPython: 8.6.0
sphinx: 5.3.0
</details>

**Comment by shoyer** [comment]
This was an intentional design choice, back in the early days of Xarray.

The rule Xarray uses for choosing which coordinates to associate with a DataArray created from a Dataset or DataArray is "every coordinate whose dimensions are still present on the new DataArray." This includes scalar coordinates, which are always kept around (because their dimensions are always included).

What rule would you suggest instead? I agree that the behavior in this case "feels" wrong, but keep in mind that once `time` because a scalar coordinate, Xarray doesn't have any way of knowing that it used to have its own dimension.

**Comment by dopplershift** [comment]
IMO, it's not correctly implementing the rule as you phrased it. You said "still present", which isn't the case here since the coordinate wasn't present before.

The behavior I'd advocate for is that a subsetting/selection operation should never add new coordinates that weren't previously present. That by itself would be less surprising. It would also help make things more sensible given that the coordinate is only added currently in the scalar case--if you ask for more data, the coordinate isn't added, which is also unexpected given the scalar case.

**Comment by dcherian** [comment]
One way to fix this would be to never associate non-dim coords when creating a DataArray for a dimension coordinate. But I think it may be better to encourage users to use `.variable` instead.

> The behavior I'd advocate for is that a subsetting/selection operation should never add new coordinates that weren't previously present. 

What do you mean by "previously present"? We'd have to track state. Alternatively, the user could use `.sel(time=[0])`. That would preserve the identity of time as a dimension coordinate (of size 1), and it would not get associated when extracting `lat`

**Comment by dopplershift** [comment]
So I'll say that taking my dataset and running `nc.squeeze()` was illustrative to the problem here. I see now that if a `Dataset` has scalar coordinates, they apply to every `DataArray`/`Variable` inside. So I see what prompts the current behavior.

I think the mismatch in my mental model is due to me coming from netCDF CF land, where coordinates for a variable are based on:
1. Other variables that match relevant shared dimension names
2. Those explicitly listed in the `coordinates` attribute

I see now that xarray does NOT implement that model.

This was provoked by challenges creating a new `DataArray`, but I see those can be solved by passing in both `dims` and `coords` (when coords contains some scalar coords).
