### ISSUE TITLE
getting confused by xarray not reporting the netCDF ```_FillValue``` attribute in jupyter notebooks: add ```_FillValue``` to the "report"?

### ISSUE THREAD

**Issue by jerabaul29** [pydata/xarray#7372]
### What is your issue?

I love to use xarray to look at / explore / work with netCDF files in notebooks. There is one point that has confused me quite a bit though: the fact that the "report" provided by xarray does not seem to include the ```_FillValue``` attribute. For me it is a quite important attribute to know of (I have seen some issues in some files due to poorly chosen ```_FillValue``` for example). It looks like xarray is handling ```_FillValue``` just fine, but I wonder if being just a bit more explicit rather than implicit, ie showing ```_FillValue``` in the report, could be useful? At least this would lift some confusions I have myself regularly ^^ :) .

To illustrate what I say, a screenshot (this is on VSC, a notebook is available at https://github.com/jerabaul29/illustrations/blob/main/inconsistencies/xarray/xarray_fillvalue/xr_fillvalue_issue_base.ipynb , though at the moment the "xarray report" part does not seem to be fully rendered by the github online view: what I mean by "the report" is the html interactive output after the 6 at the bottom):

![xarray_FillValue](https://user-images.githubusercontent.com/8382834/206740857-32a68705-776c-4ee6-ac8d-bb8646b4d7e5.png)

the "normal" attribute is shown (```some_attribute```) but the ```_FilledValue``` attribute is not shown. I thought / was worried it was dropped when re-dumping to netCDF, though the following of the notebook shows that xarray handles it just fine and re-dumps it when writing again a new netCDF file; still, I often get confused because of this attribute not being reported.

Would it be possible to make the ```_FillValue``` attribute visible in the html report to avoid people like me getting confused? :)

**Comment by keewis** [comment]
this information is available in the encoding, i.e. `xr_initial.dummy_variable.encoding`.

It's not in the `attrs` because `xarray` used it to replace elements with the exactly same value as `_FillValue` with `np.nan`, making it redundant and quickly become outdated on operations. If you were to pass `mask_and_scale=False` to `open_dataset` you should see it in the `attrs`.

A different question would be whether or not to display the encoding in the HTML `repr`.

**Comment by dcherian** [comment]
> be whether or not to display the encoding in the HTML repr.

I think so. See https://github.com/pydata/xarray/issues/4817

**Comment by headtr1ck** [comment]
Then let's close this issue in favor of #4817
