### ISSUE TITLE
Support pandas.Series in the Dataset constructor

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#740]
Follow up on #677

cc @MaximilianR

**Comment by MaximilianR** [comment]
I think this is why it doesn't currently work: http://stackoverflow.com/questions/35442924/how-does-pythons-dict-constructor-handle-mappings

Tangentially related to: https://github.com/pydata/pandas/issues/12056 - i.e. from the pandas side, should Series be Mappings?

We could add a separate path for `Series` in the dataset constructor, or even monkey patch `ChainMap`. Neither seems that elegant

**Comment by shoyer** [comment]
I would be perfectly happy with adding something like this to the Dataset constructor:
```
if isinstance(data_vars, pd.Series):
    data_vars = dict(data_vars)
```
