### ISSUE TITLE
Opening a variable as several chunks works fine, but opening it "fully" crashes

### ISSUE THREAD

**Issue by jerabaul29** [pydata/xarray#7421]
### What happened?

I have set up a ipynb notebook that may be a clear explanation:

https://github.com/jerabaul29/misc/blob/main/BugReports/OpeningIssueXarray/issue_opening_2018_03_b.ipynb

Short report:

- I have a netcdf file that is not specially big (around 1.6GB)
- When I try to fully open one of its variables, it crashes, ie this crashes:

```
# for some reason, this does not work; crash
xr_file["accD"][0, 0:3235893].data
```

but opening in several passes works, i.e. this works:

```
xr_file["accD"][0, 1000000:2000000].data
xr_file["accD"][0, 2000000:3000000].data
xr_file["accD"][0, 3000000:3235893].data
```

Any idea why?

### What did you expect to happen?

Opening the variable in full should work.

### Minimal Complete Verifiable Example

https://github.com/jerabaul29/misc/blob/main/BugReports/OpeningIssueXarray/issue_opening_2018_03_b.ipynb

### MVCE confirmation

- [x] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [x] Complete example — the example is self-contained, including all data and the text of any traceback.
- [x] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [x] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Anything else we need to know?

The netcdf file uses unlimited dimensions, can this be a problem? I am not the author of the file, but I think it was generated from some Matlab netCDF package.

### Environment

Ubuntu 20.04, python 3.8.10, xarray 0.20.2.

**Comment by jerabaul29** [comment]
I got help to extract more information in gdb; converting the ipynb to a py file and running it in gdb context:

```
> jupyter nbconvert --to script issue_opening_2018_03_b.ipynb [NbConvertApp] Converting notebook issue_opening_2018_03_b.ipynb to script
[NbConvertApp] Writing 1313 bytes to issue_opening_2018_03_b.py
> gdb --args python3 issue_opening_2018_03_b.py 
[...]
(gdb) run
Starting program: /usr/bin/python3 issue_opening_2018_03_b.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[...]
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
__memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:314
314	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:314
#1  0x00007ffff6af4bdc in NC4_get_vars () from /home/jrmet/.local/lib/python3.8/site-packages/netCDF4/.libs/libnetcdf-5e98d7e6.so.15.0.0
#2  0x00007ffff6af337d in NC4_get_vara () from /home/jrmet/.local/lib/python3.8/site-packages/netCDF4/.libs/libnetcdf-5e98d7e6.so.15.0.0
#3  0x00007ffff6a959aa in NC_get_vara () from /home/jrmet/.local/lib/python3.8/site-packages/netCDF4/.libs/libnetcdf-5e98d7e6.so.15.0.0
#4  0x00007ffff6a96b9b in nc_get_vara () from /home/jrmet/.local/lib/python3.8/site-packages/netCDF4/.libs/libnetcdf-5e98d7e6.so.15.0.0
#5  0x00007ffff6ec24bc in ?? () from /home/jrmet/.local/lib/python3.8/site-packages/netCDF4/_netCDF4.cpython-38-x86_64-linux-gnu.so
#6  0x00000000005f5b39 in PyCFunction_Call ()
```

which seems to be originating in libnetcdf?

**Comment by jerabaul29** [comment]
@keewis interesting. Just to be sure: I am able to open the dataset just fine too, the issue arises when trying to actually read the field, i.e.:

```python
xr_file = xr.open_dataset(input_file, decode_times=False)
```

is just fine, but

```python
xr_file["accD"][0, 0:3235893].data
```

is what segfaults; just to be sure there is no misunderstanding, are you actually able to run the last command without isse? :)

**Comment by jerabaul29** [comment]
@keewis regarding the engine: I have netcdf4 installed and I do not provide a dedicated engine in the ```open_dataset``` command, so I guess this is using the netcdf4 engine by default? Anyway I can run a command to double check and confirm to you? :)

**Comment by keewis** [comment]
This is what I'm doing:
```python
In [1]: import xarray as xr
   ...: 
   ...: ds = xr.open_dataset("2018_03_b.nc", decode_times=False)
   ...: ds["accD"].data
Out[1]: 
array([[-9.625633e+00, -9.587038e+00, -9.601438e+00, ..., -9.543669e+00,
        -9.519094e+00, -9.509479e+00],
       [-9.705109e+00, -9.658272e+00, -9.672318e+00, ...,  9.969210e+36,
         9.969210e+36,  9.969210e+36]], dtype=float32)
```

**Comment by jerabaul29** [comment]
Ok, thanks, this does crash too on my machine. Then likely something to do with my software stack somewhere, I will try with a new mamba / conda environment and check if this fixes things.

**Comment by keewis** [comment]
> I do not provide a dedicated engine in the open_dataset command, so I guess this is using the netcdf4 engine by default? 

Depends on the file format, but in general, I'd recommend passing the engine kwarg explicitly.

**Comment by jerabaul29** [comment]
Creating a conda environment as you suggest, I am fully able to read etc the file, so this solves my issue. Many thanks! Then I guess this means there is some weird issue leading to segfaults on this file with some of the older libnetcdf versions. Closing as using a conda env and a more recent stack fixes things.
