### ISSUE TITLE
`plot.scatter` only works for declared arguments

### ISSUE THREAD

**Issue by iuryt** [pydata/xarray#7422]
### What happened?

```python
ds.plot.scatter("x","y")
```

returns:

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /autofs/nas1/home/isimoesdesousa/programs/mambaforge/envs/coringa/lib/python3.9/site-packages/xarray/core/dataset.py:1340, in Dataset._construct_dataarray(self, name)
   1339 try:
-> 1340     variable = self._variables[name]
   1341 except KeyError:

KeyError: None

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
Cell In[60], line 1
----> 1 ds.plot.scatter("x","y")

File /autofs/nas1/home/isimoesdesousa/programs/mambaforge/envs/coringa/lib/python3.9/site-packages/xarray/plot/accessor.py:1071, in DatasetPlotAccessor.scatter(self, *args, **kwargs)
   1069 @functools.wraps(dataset_plot.scatter)
   1070 def scatter(self, *args, **kwargs) -> PathCollection | FacetGrid[DataArray]:
-> 1071     return dataset_plot.scatter(self._ds, *args, **kwargs)

File /autofs/nas1/home/isimoesdesousa/programs/mambaforge/envs/coringa/lib/python3.9/site-packages/xarray/plot/dataset_plot.py:914, in scatter(ds, x, y, z, hue, hue_style, markersize, linewidth, figsize, size, aspect, ax, row, col, col_wrap, xincrease, yincrease, add_legend, add_colorbar, add_labels, add_title, subplot_kws, xscale, yscale, xticks, yticks, xlim, ylim, cmap, vmin, vmax, norm, extend, levels, *args, **kwargs)
    912 del locals_["ds"]
    913 locals_.update(locals_.pop("kwargs", {}))
--> 914 da = _temp_dataarray(ds, y, locals_)
    916 return da.plot.scatter(*locals_.pop("args", ()), **locals_)

File /autofs/nas1/home/isimoesdesousa/programs/mambaforge/envs/coringa/lib/python3.9/site-packages/xarray/plot/dataset_plot.py:740, in _temp_dataarray(ds, y, locals_)
    736         coords[key] = ds[key]
    738 # The dataarray has to include all the dims. Broadcast to that shape
    739 # and add the additional coords:
--> 740 _y = ds[y].broadcast_like(ds)
    742 return DataArray(_y, coords=coords)

File /autofs/nas1/home/isimoesdesousa/programs/mambaforge/envs/coringa/lib/python3.9/site-packages/xarray/core/dataset.py:1431, in Dataset.__getitem__(self, key)
   1429     return self.isel(**key)
   1430 if utils.hashable(key):
-> 1431     return self._construct_dataarray(key)
   1432 if utils.iterable_of_hashable(key):
   1433     return self._copy_listed(key)

File /autofs/nas1/home/isimoesdesousa/programs/mambaforge/envs/coringa/lib/python3.9/site-packages/xarray/core/dataset.py:1342, in Dataset._construct_dataarray(self, name)
   1340     variable = self._variables[name]
   1341 except KeyError:
-> 1342     _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
   1344 needed_dims = set(variable.dims)
   1346 coords: dict[Hashable, Variable] = {}

File /autofs/nas1/home/isimoesdesousa/programs/mambaforge/envs/coringa/lib/python3.9/site-packages/xarray/core/dataset.py:174, in _get_virtual_variable(variables, key, dim_sizes)
    171     return key, key, variable
    173 if not isinstance(key, str):
--> 174     raise KeyError(key)
    176 split_key = key.split(".", 1)
    177 if len(split_key) != 2:

KeyError: None
```

### What did you expect to happen?

To plot the figure:

![image](https://user-images.githubusercontent.com/5797727/210827438-d784828d-2496-427e-8485-9471d3ee5e6c.png)

### Minimal Complete Verifiable Example

```Python
import pandas as pd

n = 1000
df = pd.DataFrame()
df["x"] = np.random.randn(n)
df["y"] = np.random.randn(n)
ds = df.to_xarray()

#this works
ds.plot.scatter(x="x",y="y")

#this doesn't work
ds.plot.scatter("x","y")
```

### MVCE confirmation

- [x] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>
NSTALLED VERSIONS
------------------
commit: None
python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03) 
[GCC 10.4.0]
python-bits: 64
OS: Linux
OS-release: 5.15.0-50-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.8.1

xarray: 2022.12.0
pandas: 1.5.2
numpy: 1.24.0
scipy: 1.9.3
netCDF4: 1.6.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.5
dask: 2022.12.1
distributed: 2022.12.1
matplotlib: 3.6.2
cartopy: None
seaborn: None
numbagg: None
fsspec: 2022.11.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.6.3
pip: 22.3.1
conda: None
pytest: None
mypy: None
IPython: 8.7.0
sphinx: None

</details>

**Comment by Illviljan** [comment]
Hmm, this worked at some point. Must've gotten lost somewhere in one of the bigger plot refactors.

Positional arguments have been deprecated though, so you should start getting used to using keyword arguments:
https://docs.xarray.dev/en/stable/whats-new.html#v2022-11-0-nov-4-2022

**Comment by iuryt** [comment]
Ok, that makes sense. I suspected that that was the case, but wanted to create an issue just in case. I think that we can close this now.
