### ISSUE TITLE
unit support?

### ISSUE THREAD

**Issue by arsenovic** [pydata/xarray#747]
i was curious is there is any thoughts to incorperate 'units' with xarray?

[pint](http://pint.readthedocs.org/en/0.6/) is a package that implements this.

**Comment by arsenovic** [comment]
@hgrecco

**Comment by jhamman** [comment]
We have an open issue regarding adding units to `xarray` in #525. I'm going to close this issue in favor of that one but please feel free to contribute to the other issue.
