### ISSUE TITLE
Refresh list of backends (engines)?

### ISSUE THREAD

**Issue by alimanfoo** [pydata/xarray#7478]
### What is your issue?

If a user is working in an environment where zarr is not initially installed (e.g., colab), then imports xarray, the list of available backends (engines) will not include zarr, as expected.

If the user subsequently installs zarr, then tries to open a zarr dataset via `open_zarr()` without restarting their kernel, they will get an error like:

```
ValueError: unrecognized engine zarr must be one of: ['netcdf4', 'scipy', 'store']
```

This can also be triggered in a more subtle way, because importing other packages like pandas will also trigger xarray to inspect and then fix this list of available engines. 

Obviously this can be resolved by instructing users to restart their kernel after any install commands, or by telling them to always run install commands before any imports. 

But I was wondering if there is a way to tell xarray to refresh its information about available engines?

I have been able to hack it by running:

```
xarray.backends.zarr.ZarrBackendEntrypoint.available = module_available("zarr")
xarray.backends.list_engines.cache_clear()
```

...but maybe there is a better way?
 
Thanks :heart:

**Comment by jhamman** [comment]
Hi @alimanfoo! I agree that the current behavior is a bit annoying for users. We may need to develop a `refresh_engines` function that:

- updates the `BACKEND_ENTRYPOINTS` dict (it would be nice if entrypoints could help us here)
- clears the `list_engines` cache
- reinstates the `list_engines` cache
