### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by MM-cyi** [pydata/xarray#7487]
### What is your issue?

Hi. 

The data linked from 
`https://docs.xarray.dev/en/stable/examples/ROMS_ocean_model.html`
at
`http://barataria.tamu.edu/thredds/catalog.html?dataset=txla_hindcast_agg `
are unavailable. 

Any chance this could be fixed? 

Thanks. 
Marco

**Comment by keewis** [comment]
this looks like a duplicate of #7486. Closing, but feel free to follow the discussion there.
