### ISSUE TITLE
Concat of multiple DataArrays reverses the y dimension

### ISSUE THREAD

**Issue by ZachKeskinen** [pydata/xarray#7501]
### What is your issue?

Hey all,

I suspect I am just doing something incorrectly but haven't been able to solve this problem, so hoping someone can point me in the right direction.

I have a list of two data arrays with y dimensions (high -> low) of:
```
# check y values of the first DataArray
dataArrays[0].y
```
array([43.099756, 43.099413, 43.09907 , ..., 43.001019, 43.000676, 43.000333])

```
# check y values of the second DataArray
dataArrays[1].y
```
array([43.099682, 43.09935 , 43.099019, ..., 43.000869, 43.000537, 43.000206])

and when I try to concatenate this list into a DataSet, the resulting y dimension is reversed from my expectation.
Actual y values (low -> high):
```
# combine list of dataArrays and check y- values of dataset
ds = xarray.concat(dataArrays, dim = 'time')
ds.y
```
array([43.000206, 43.000333, 43.000537, ..., 43.099413, 43.099682, 43.099756])

Expected y-values (high -> low) would match the ordering of the input DataArrays:
```
ds = xarray.concat(dataArrays, dim = 'time')
ds.y
```
array([43.099756, 43.099682, 43.099413, ..., 43.000537, 43.000333,43.000206])

How can I combine these DataArrays and get the same direction of ordering of y-values as the input arrays? When I plot the data array vs a band of the dataset they look alright but when I check the bounds of the dataset the latitudes are reversed with a smaller maximum latitude than minimum latitude in the concatenated dataset:

```
dataArrays[0].rio.bounds()
```
(-114.40003329796458, 43.000039804222375, -114.29989382915689, 43.099847685385)

```
ds.isel(time = 0)
```
(-114.40003892276228,43.099584649180755,-114.29988008526641, 43.00037701666514) # smaller top latitude, 43.00037701666514, than bottom latitude, 43.099584649180755.

Thanks in advance, and sorry if this isn't the right format or place for this.

--------------------------------------------

Xarray version information:

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.0 | packaged by conda-forge | (main, Jan 15 2023, 05:44:48) [Clang 14.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: (None, 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2023.1.0
pandas: 1.5.3
numpy: 1.24.1
scipy: 1.10.0
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.3.4
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.6.3
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 66.1.1
pip: 22.3.1
conda: None
pytest: None
mypy: None
IPython: 8.8.0
sphinx: None

**Comment by ZachKeskinen** [comment]
Of course, you figure out the answer as soon as you ask a question.

I needed to use the rioxarray merge_array function instead to get this result.

```
from rioxarray.merge import merge_arrays
ds = merge_arrays(dataArrays)
ds.y
```
array([44.40802298, 44.40768014, 44.4073373 , ..., 42.01844741,
       42.01810457, 42.01776174])

and for bounds.
```
ds.rio.bounds()
```
(-114.40003892276228,43.099584649180755,-114.29988008526641, 43.00037701666514)

Sorry about that.

**Comment by ZachKeskinen** [comment]
Thought I fixed this with rioxarray.merge.merge_dataset but it doesn't create a dataset merged on time but just creates one dataset at one time.

**Comment by ZachKeskinen** [comment]
Thought I fixed this with rioxarray.merge.merge_dataset but it doesn't create a dataset merged on time but just creates one dataset at one time.

**Comment by headtr1ck** [comment]
Not an expert on this topic, also I don't know how your dataset looks exactly.
Assuming that `y` is a dimension coordinate:
Because your `y` values differ xarray will align them for you but it does not know which direction should be preferred, it uses ascending.
You could simply sort your resulting dataset using `ds.sortby("y", ascending=False)`

**Comment by ZachKeskinen** [comment]
That worked. Thanks for the help!
