### ISSUE TITLE
String type conversion when saving netCDF

### ISSUE THREAD

**Issue by bnaul** [pydata/xarray#751]
I would call this a bug but perhaps it's just some quirk of netCDF3? Curious to hear what you think.

```
import xarray as xr

ds = xr.Dataset(coords={'x': ['test']})

# When saving with scipy, strings are re-loaded as binary
ds.to_netcdf('/tmp/scipy.nc', engine='scipy')
xr.open_dataset('/tmp/scipy.nc').x.values == ds.x.values #  False

# When saving with netCDF4, strings are re-loaded as strings
ds.to_netcdf('/tmp/netcdf4.nc', engine='netcdf4')
xr.open_dataset('/tmp/netcdf4.nc').x.values == ds.x.values #  array([ True], dtype=bool)
```

The latter behavior is what I'd expect; the former is a bit annoying e.g. when testing since loaded values can't be directly compared to those being written.

**Comment by shoyer** [comment]
You're using Python 3, yes?

Netcdf3 doesn't support Unicode so strings get read back as bytes. There were plans to fix this in numpy by adding an ascii string dtype, but that seems to have stalled for now.

**Comment by bnaul** [comment]
Yep, this is under Python3. Doesn't look like anything is going to change on the numpy front (https://github.com/numpy/numpy/issues/4162) so I guess the solution is just to avoid mixing {netCDF,Python}3...
