### ISSUE TITLE
Selecting variables from Dataset with view on dict keys is of type DataArray

### ISSUE THREAD

**Issue by derhintze** [pydata/xarray#7519]
### What happened?

When selecting variables from a Dataset using a view on dict keys, the type returned is a DataArray, whereas the same using a list is a Dataset.

### What did you expect to happen?

The type returned should be a Dataset.

### Minimal Complete Verifiable Example

```Python
import xarray as xr

d = {"a": ("dim", range(1, 4)), "b": ("dim", range(2, 5))}

data = xr.Dataset(d)
select_dict = data[d.keys()]
select_list = data[list(d)]

reveal_type(select_dict)
reveal_type(select_list)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [x] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
$ mypy test.py
test.py:9: note: Revealed type is "xarray.core.dataarray.DataArray"
test.py:10: note: Revealed type is "xarray.core.dataset.Dataset"
Success: no issues found in 1 source file
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.10 (main, Mar 15 2022, 15:56:56) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.49.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.0

xarray: 2022.12.0
pandas: 1.5.2
numpy: 1.23.5
scipy: 1.10.0
netCDF4: 1.6.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.6.3
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 58.1.0
pip: 23.0
conda: None
pytest: 7.2.1
mypy: 0.991
IPython: 8.8.0
sphinx: None

</details>

**Comment by jhamman** [comment]
Thanks for the report @derhintze. I agree this seems like a bug. I'm a bit confused by this actually. Our `__getitem__` implementation is here:

https://github.com/pydata/xarray/blob/7683442774c8036e0b13851df62bda067b2a65d5/xarray/core/dataset.py#L1418-L1441

and the keys view of a dataset is not hashable:

```python
isinstance(d.keys(), typing.Hashable)
False
```

Which should be triggering the second `@overload` in the code above. So I'm not sure what's going on!

**Comment by derhintze** [comment]
The only obvious difference being that one overload annotates `self`, while the other doesn't. But apart from this, the annotations look straightforward (and correct) to me.

**Comment by headtr1ck** [comment]
Thats a weird issue. I don't think we are at fault here, since apparently mypy thinks that dict_keys is Hashable (and pylance as well).

```
def f(a: Hashable) -> int
    pass
f({}.keys())  # does not raise an error
```

I guess I will raise an issue over at mypy, but probably they will simply claim that Hashable support is not good yet...

**Comment by headtr1ck** [comment]
See https://github.com/python/mypy/issues/14674

**Comment by dcherian** [comment]
Should we special case a solution? Seems user-friendly to do so.

**Comment by headtr1ck** [comment]
> Should we special case a solution? Seems user-friendly to do so.

I think dict_keys is its own type so with some type ignore there could work.

**Comment by max-sixty** [comment]
This is fixed in latest xarray:

```
Runtime type is 'Dataset'
Runtime type is 'Dataset'
```
