### ISSUE TITLE
Passing colorbar axis argument in plot statement 

### ISSUE THREAD

**Issue by dgergel** [pydata/xarray#752]
I am wondering if it would be possible to add a feature similar to the `seaborn` `heatmap` plotting feature where `cbar_ax=cbar_ax` could be passed in as an argument for da.plot(), such that I could create a separate colorbar axis and use that axis for the `add_colorbar` option.

**Comment by shoyer** [comment]
Yes, contributions to add this feature would be very welcome!

**Comment by fmaussion** [comment]
I just opened a PR for this: https://github.com/pydata/xarray/pull/872

**Comment by jhamman** [comment]
close via #872.
