### ISSUE TITLE
contiguous time axis 

### ISSUE THREAD

**Issue by danhamill** [pydata/xarray#7525]
### What is your issue?

I have a [dataset](https://github.com/pydata/xarray/files/10726921/precMerge.zip) I created using `xarray`.  When I am using `netcdf-java` to read the time axis, I am getting edges that aren't the same values as the time axis coordinates.

The xarray-developed dataset looks like:

![image](https://user-images.githubusercontent.com/11522898/218593264-619f8005-5245-40db-8646-ed93c3677c29.png)

From `netcdf-java` I see the [CoordinateAxis1DTime](https://docs.unidata.ucar.edu/netcdf-java/current/javadoc/ucar/nc2/dataset/CoordinateAxis1D.html) axis with the following attributes:

![image](https://user-images.githubusercontent.com/11522898/218595339-c7c3e1ea-47d2-4f51-bdd1-12fbfb490f3c.png)

The edge array is offset by -0.5 days.  After a little digging through the java docs, I found the `CoordinateAxis1DTime.edge` array will only be the same as the `CoordinateAxis1DTime.coords` array when the [`ContiniousAxis1DTime.isContiguous()`](https://docs.unidata.ucar.edu/netcdf-java/current/javadoc/ucar/nc2/dataset/CoordinateAxis1D.html#isContiguous--) evaluates as True.  But the java docs indicate:

![image](https://user-images.githubusercontent.com/11522898/218594368-a991b668-4741-427f-b823-44a4991f6f14.png)

How can I write a netcdf file using xarray where the time axis would be considered contiguous?

**Comment by dopplershift** [comment]
@ethanrd @haileyajohnson @tdrwenski any thoughts on the above question?

**Comment by ethanrd** [comment]
If cell bounds/edges are not provided with a coordinate variable, the coordinate values are assumed to represent the center points of a set of contiguous cells. In this default case, the cell edges can be represented as an (n+1) sized array with all but the first and last values shared between neighboring cells. In the non-contiguous case, the bounds/edges must be represented as an (n,2) sized array.

Looks like there's already an xarray issue (#1475 ) on handling cell bounds.

**Comment by ethanrd** [comment]
So, I believe the results you are seeing above are the expected results with the edge value half way between neighboring coordinate values.

**Comment by dcherian** [comment]
Thanks @dopplershift and @ethanrd . It seems like it's interpreting the absence of an attribute (!).

**Comment by danhamill** [comment]
Hey!  

Thanks for the thoughts.  Took me a wile to realize the edge array and the time coordinates aren't the same thing.  The time coordinates are really labels and the edge array is calculated from it.  

Not sure I agree with the default calculation as the mid point of the time coordinate labels, but I think that is a battle I won't take up.  

+1 for supporting this kind of coordinate attribute in xarray.  Based on the other issues linked here, it seems it still has not been implemented?
