### ISSUE TITLE
SVG version of xarray logo

### ISSUE THREAD

**Issue by ncclementi** [pydata/xarray#7529]
### What is your issue?

Hi folks, We are trying to use the xarray logo in one of our Coiled pages and we would like a vectorized form. I saw there is a script to generate the logo using LaTex but I do not have things set up to run LateX at the moment. 

https://github.com/pydata/xarray/blob/main/doc/_static/dataset-diagram-logo.tex

Is there any way I can get a vectorized version of the logo. Or can someone run the script and export it as SVG?

**Comment by dcherian** [comment]
Here's a link: https://github.com/pydata/xarray/blob/main/doc/_static/dataset-diagram-logo.svg . Thanks for thinking to use the logo. Let us know if you need anything else!

Closed by #7530
