### ISSUE TITLE
Expose testing methods

### ISSUE THREAD

**Issue by spencerahill** [pydata/xarray#754]
Similar to numpy's [numpy.testing](http://docs.scipy.org/doc/numpy/reference/routines.testing.html) module, I would find it useful for xarray to expose some of its testing methods, particularly those in its base [TestCase](https://github.com/pydata/xarray/blob/master/xarray/test/__init__.py#L129).

I imagine other folks whose packages and/or modules derive heavily from xarray would find this useful too.  For now I am just copy-pasting xarray's code for these methods into my testing modules.

**Comment by jhamman** [comment]
:+1:

**Comment by shoyer** [comment]
Most of these are as simple as `assert d1.identical(d2)` or `assert d1.equals(d2)` (see [here](http://xarray.pydata.org/en/stable/combining.html#equals-and-identical) for more details on these methods). I'd be OK with adding these methods in a dedicated testing module, though.

**Comment by spencerahill** [comment]
Indeed.  I'm happy to do this sometime (eventually...), but if somebody ends up with a pressing need for this in the meantime, go for it.  Thanks!

**Comment by jhamman** [comment]
@spencerahill - have you made any progress here?  If not we (@dgergel) may be able to help out.

**Comment by spencerahill** [comment]
Thanks for the ping.  Sorry, I haven't.  I'm actually submitting my PhD thesis in ~2 months and then defending it this summer, so I won't be able to help much until August or September.  So by all means, go for it.

**Comment by fmaussion** [comment]
I'd be willing to prepare a PR, if this is still actual. Today I needed the *AllClose methods for my tests, I think it would be great to have these methods exposed.

I think I have an idea on how to proceed, but maybe I am underestimating the required amount of work.

Numpy for example has the `np.allclose` and `np.testing.assert_allclose` functions. Should xarray also have a `xr.allclose` function or are we happy with a `xr.testing.assert_allclose` alone? Also, the current xarray implementation has a different function for variables, datasets and coordinates: could these be merged in a generic `assert_allclose` which takes decisions on what to do based on the input type?
