### ISSUE TITLE
DatasetGroupBy.mean discards attributes on coordinate

### ISSUE THREAD

**Issue by eendebakpt** [pydata/xarray#7546]
### What happened?

When using `DatasetGroupBy.mean` with the option `keep_attrs=True` the information on the attributes is discarded.

Update: this happens when the flox package is _not_ installed.

### What did you expect to happen?

The attributes for the grouped coordinate should be in the result

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import pandas as pd
import numpy as np

da = xr.DataArray(
    np.array([1, 2, 3, 1, 2, np.nan]),
    dims="time",
    coords=dict(
        time=("time", pd.date_range("01-01-2001", freq="M", periods=6)),
        labels=("time", np.array(["a", "b", "c", "c", "b", "a"])),
    ),
)
da.labels.attrs['units']='a.u.'

ds = xr.Dataset(dict(da=da))
ds.attrs['units']='V'
ds

m=ds.groupby("labels").mean(keep_attrs=True)
print(m) # dataset has attribute for units
print()
print(m.labels) # labels has attribute for units
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: ('Dutch_Netherlands', '1252')
libhdf5: 1.12.2
libnetcdf: None

xarray: 2022.12.0
pandas: 1.5.1
numpy: 1.24.1
scipy: 1.9.2
netCDF4: None
pydap: None
h5netcdf: 1.0.2
h5py: 3.7.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.6.2
cartopy: None
seaborn: 0.12.1
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.3.0
pip: 22.3.1
conda: None
pytest: 7.1.3
mypy: 0.990
IPython: 7.34.0
sphinx: 5.3.0
```

</details>

**Comment by eendebakpt** [comment]
@keewis I get different output. This is with xarray 2022.12.0

![image](https://user-images.githubusercontent.com/883786/220397408-55be5624-4ad5-4935-a37a-156f93e7b8c7.png)

**Comment by eendebakpt** [comment]
@keewis The problem only occurs if flox is _not_ installed.

**Comment by max-sixty** [comment]
This seems to work now, even without flox installed. Please reopen if not!
