### ISSUE TITLE
count docstring mistakenly includes skipna

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#755]
Is this a mistake or am I missing something?

http://xray.readthedocs.org/en/stable/generated/xarray.DataArray.count.html?highlight=count#xarray.DataArray.count

> skipna : bool, optional
> If True, skip missing values (as marked by NaN). By default, only skips missing values for float dtypes; other dtypes either do not have a sentinel missing value (int) or skipna=True has not been implemented (object, datetime64 or timedelta64).

**Comment by shoyer** [comment]
Yes, this is a mistake. We shouldn't be using this same template to generate the docstring for count.
