### ISSUE TITLE
broken documentation link

### ISSUE THREAD

**Issue by arfriedman** [pydata/xarray#7556]
### What is your issue?

Hi,

I found [this broken link](https://docs.xarray.dev/en/stable/user-guide/datetime_component_indexing) at the bottom of the [Datetime Indexing](https://docs.xarray.dev/en/stable/user-guide/time-series.html#datetime-indexing) subsection in the User Guide.

**Comment by TomNicholas** [comment]
Thanks for reporting @arfriedman .

The link is supposed to be referring to the section immediately following the Datetime Indexing subsection. I think the underscores in `datetime_component_indexing` might be what's breaking the link.

If anyone wants to make their first small contribution to xarray this would be a great start!

**Comment by JoyNyuguto** [comment]
@TomNicholas I think this issue of the broken link may have been caused by the removal of the page from the website without redirecting the URLS due to the 404 error being displayed.

**Comment by JoyNyuguto** [comment]
@TomNicholas I amJoy Nyuguto from Outreachy
It appears that the link you provided is no longer available on the xarray documentation site. It's possible that the page has been removed or the URL has been updated.

I recommend checking the xarray documentation home page or using the search bar to locate the page you're looking for.

**Comment by keewis** [comment]
Since the label exists and the spelling is correct, I *think* the only thing we need to do here is use the appropriate `sphinx` role. To figure out which one, we can either manually search the `intersphinx` registry using
```bash
$ python -m sphinx.ext.intersphinx https://docs.xarray.dev/en/latest/objects.inv | less
```
(which is a bit tedious because that particular section is pretty big, and we need to have `sphinx` installed)

or we can use [`sphobjinv`](https://sphobjinv.readthedocs.io/en/stable/):
```bash
$ sphobjinv suggest -u https://docs.xarray.dev/en/latest/ datetime_component_indexing
 
Attempting https://docs.xarray.dev/en/latest ...
  ... no recognized inventory.
Attempting "https://docs.xarray.dev/en/latest/objects.inv" ...
  ... inventory found.
 
------------------------------------------------------------------------------------------------------------------------------

The intersphinx_mapping for this docset is LIKELY:

  (https://docs.xarray.dev/en/latest/, None)

------------------------------------------------------------------------------------------------------------------------------

Project: xarray
Version: 2023.2.1.dev19

7468 objects in inventory.

------------------------------------------------------------------------------------------------------------------------------

1 result found at/above current threshold of 75.

:std:label:`datetime_component_indexing`
```
which helpfully tells us the correct link (though I think we can use `:label:` instead of `:std:label:`)

**Comment by nashira26** [comment]
I am an Outreachy intern and I would love to contribute by updating this documentation.
