### ISSUE TITLE
doc: link dead

### ISSUE THREAD

**Issue by dacoex** [pydata/xarray#756]
Link in this section 

> 
pandas, thanks to its unrivaled speed and flexibility, has emerged as the premier python package for working with labeled arrays. So why are we contributing to further fragmentation in the ecosystem for working with data arrays in Python?

[fragmentation](http://wesmckinney.com/blog/?p=77)

is dead.

http://wesmckinney.com/archives.htm

**Comment by shoyer** [comment]
Thanks for pointing this out.

This is the new link: http://wesmckinney.com/blog/a-roadmap-for-rich-scientific-data-structures-in-python/

**Comment by dacoex** [comment]
say you want a PR to correct the link?

**Comment by shoyer** [comment]
that would be great!
