### ISSUE TITLE
Type of `datetime` changes depending on the method to access the value

### ISSUE THREAD

**Issue by fernandascovino** [pydata/xarray#7568]
### What happened?

I have a dataframe containing a date column in string format. I converted it using:

```python
df.data = df.data.apply(pd.to_datetime)
df.data.head(1)
>>> 0   2023-02-11
>>> Name: data, dtype: datetime64[ns]
```

Then I try to list the values and access the `weekday` of each, but I got this error:

```python
def date_type(x): 
    return "Dia Útil" if x < 6 else "Sabado" if x == 6 else "Domingo"

{d: date_type(d.weekday()) for d in df.data.values}

>>> AttributeError: 'numpy.datetime64' object has no attribute 'weekday'
```

### What did you expect to happen?

I expected it to be a `datetime` object, not a `numpy.datetime64`. When accessing the value with `.loc`, I get the expected behavior:

```python
df.data.loc[0] # expected
>>> Timestamp('2023-02-11 00:00:00')
df.data.values[0] # not expected
>>> numpy.datetime64('2023-02-11T00:00:00.000000000')
```

Is this actually the correct behavior? 

### Minimal Complete Verifiable Example

```Python
import pandas as pd

df.data = df.data.apply(pd.to_datetime)

def date_type(x): 
    return "Dia Útil" if x < 6 else "Sabado" if x == 6 else "Domingo"

{d: date_type(d.weekday()) for d in df.data.values}
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 (default, Oct 13 2021, 06:45:31) 
[Clang 13.0.0 (clang-1300.0.29.3)]
python-bits: 64
OS: Darwin
OS-release: 22.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: pt_BR.UTF-8
LOCALE: ('pt_BR', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2022.12.0
pandas: 1.5.2
numpy: 1.24.1
scipy: 1.6.0
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.3.4
cfgrib: None
iris: None
bottleneck: None
dask: 2021.11.2
distributed: 2021.11.2
matplotlib: 3.3.4
cartopy: None
seaborn: 0.11.2
numbagg: None
fsspec: 2021.11.1
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 62.6.0
pip: 22.3.1
conda: None
pytest: 6.0.2
mypy: None
IPython: 7.29.0
sphinx: None

</details>

**Comment by dcherian** [comment]
Hi,

I think you've posted this to Xarray by mistake. Please post to the pandas issue tracker: https://github.com/pandas-dev/pandas/

Thanks!
