### ISSUE TITLE
Ordered Groupby Keys

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#757]
The current behavior of the xarray's `Groupby.groups` property provides a standard (unordered) dictionary.  This is fine for most cases but leads to odd orderings in use cases like this one where I am using xarray's FacetGrid plotting: 

``` Python
plot_kwargs = dict(col='season', vmin=15, vmax=35, levels=12, extend='both')

da_obs = ds_obs.SALT.isel(depth=0).groupby('time.season').mean('time')
da_obs.plot(**plot_kwargs)
```

![index](https://cloud.githubusercontent.com/assets/2443309/12956558/791d70fa-cfdd-11e5-80b6-8ca0bb564d36.png)
_Note that MAM and JJA are out of order._

I think this could be easily fixed by using an `OrderedDict` in [`xarray.core.Groupby.groups`](https://github.com/pydata/xarray/blob/master/xarray/core/groupby.py#L162-L168).

**Comment by shoyer** [comment]
I agree this is annoying, but I don't think your diagnosis is correct here. The `groups` property isn't used by any internal routines AFAICT. The issue is that groups *are* sorted, but as text rather than ordered categorical -- notice that the labels are ordered alphabetically.

**Comment by jhamman** [comment]
Hmmm, a mystery.  I'll look into this a bit more.

**Comment by shoyer** [comment]
For what it's worth, I don't think we have any good solutions short of
adding our own array type do to Categorical in xarray. We could set
sort=False in some cases when we call pd.factorize but that's not a great
alternative.

**Comment by tdihp** [comment]
Ahh, so it's sorted, instead of keeping the original order.

I was expecting `DataArray.groupby().reduce` would work like `np.apply_along_axis`, and used the `data` of the result directly.

**Comment by jbusecke** [comment]
Just stumbled across this issue. Is there a recommended workaround? 

I am usually doing this (specific to seasons):
```
import xarray as xr
ds = xr.tutorial.open_dataset('air_temperature')
airtemp_seasonal = ds.groupby('time.season').mean('time').sortby(xr.DataArray(['DJF','MAM','JJA', 'SON'],dims=['season']))
```
Thought this might help some folks who need to solve this problem.

**Comment by dcherian** [comment]
I use `reindex` instead of `sortby`

**Comment by max-sixty** [comment]
Closing as stale, please reopen with an updated summary if relevant

**Comment by dcherian** [comment]
Hehe, I'm so close to actually fixing this! :)

**Comment by dcherian** [comment]
In the next release of Xarray use `SeasonGrouper` for this, and additional features!

```python
from xarray.groupers import SeasonGrouper

ds.groupby(time=SeasonGrouper(["DJF", "MAM", "JJA", "SON"])).mean()
```

https://docs.xarray.dev/en/latest/user-guide/time-series.html#handling-seasons
