### ISSUE TITLE
`test_open_nczarr` failing

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#7572]
### What is your issue?

In the latest CI runs it seems that `test_backends.py::TestNCZarr::test_open_nczarr` is failing with
> KeyError: 'Zarr object is missing the attribute `_ARRAY_DIMENSIONS` and the NCZarr metadata, which are required for xarray to determine variable dimensions.'

I don't see an obvious reason for this, especially since the zarr version has not changed compared to some runs that were successful (2.13.6).

**Comment by malmans2** [comment]
The problem comes from `libnetcdf`. It bumped from `4.8.1` to `4.9.1`.
I'll look into it.

**Comment by malmans2** [comment]
See: https://github.com/Unidata/netcdf-c/issues/2647

The problem is that with `netcdf-c=4.9.1` dimension names are lost when writing pure nczarr files. We only need it to make sure that xarray is able to read from pure nczarr.

**Comment by malmans2** [comment]
Slightly different issue related to the new release.

Looks like nczarr attribute key changed from `"_NCZARR_ARRAY"` to `"_nczarr_array"` (see https://github.com/Unidata/netcdf-c/pull/2492), so we would have to take care of this if we want to keep supporting pure nczarr.

https://github.com/pydata/xarray/blob/6531b57f8c5cb7f3c564ff895c2e4b6573bb5521/xarray/backends/zarr.py#L202
