### ISSUE TITLE
Add optional min versions to conda-forge recipe (`run_constrained`)

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#7573]
### Is your feature request related to a problem?

I opened this PR to add minimum versions for our optional dependencies: https://github.com/conda-forge/xarray-feedstock/pull/84/files to prevent issues like #7467 

I think we'd need a policy to choose which ones to list. Here's the current list:
```
run_constrained:
    - bottleneck >=1.3
    - cartopy >=0.20
    - cftime >=1.5
    - dask-core >=2022.1
    - distributed >=2022.1
    - flox >=0.5
    - h5netcdf >=0.13
    - h5py >=3.6
    - hdf5 >=1.12
    - iris >=3.1
    - matplotlib-base >=3.5
    - nc-time-axis >=1.4
    - netcdf4 >=1.5.7
    - numba >=0.55
    - pint >=0.18
    - scipy >=1.7
    - seaborn >=0.11
    - sparse >=0.13
    - toolz >=0.11
    - zarr >=2.10
```

Some examples to think about:
1. `iris` seems like a bad one to force. It seems like people might use Iris and Xarray independently and Xarray shouldn't force a minimum version.
2. For backends, I arbitrarily kept `netcdf4`, `h5netcdf` and `zarr`. 
3. It seems like we should keep array types: so `dask`, `sparse`, `pint`.

**Comment by kmuehlbauer** [comment]
If it helps to minimize interoperability issues I'm all in for the change. One thing I would maybe do is wait for the next version. With the current PR we would end up with two different build numbers with differing behaviour, which might confuse folks.

But I'd rely on @ocefpaf's expertise.

**Comment by ocefpaf** [comment]
> With the current PR we would end up with two different build numbers with differing behaviour, which might confuse folks.

+1

> But I'd rely on @ocefpaf's expertise.

The PR is a good idea and we, conda-forge, even though about making something like that for all packages. The problem is that optional packages metadata in Python-land is super unreliable. So, doing it on a package bases and with the original authors as part of it, it is super safe and recommended.

**Comment by dcherian** [comment]
This was done in https://github.com/conda-forge/xarray-feedstock/pull/93
