### ISSUE TITLE
Consider adding xCDAT to list of Xarray related projects

### ISSUE THREAD

**Issue by tomvothecoder** [pydata/xarray#7577]
### What is your issue?

Hello, my name is Tom and I'm a core developer for [xCDAT](https://github.com/xCDAT/xcdat) (Xarray Climate Data Analysis Tools). xCDAT is an extension of xarray for climate data analysis on structured grids. It serves as a modern successor to the Community Data Analysis Tools ([CDAT](https://github.com/CDAT/cdat)) library.

I've had a [GH Issue](https://github.com/xCDAT/xcdat/issues/126) to try to get xCDAT added to the ["Xarray related projects" ](https://docs.xarray.dev/en/stable/ecosystem.html) list. It would be awesome xCDAT if can be included on there while the project and community continues to grow!

**Comment by jhamman** [comment]
@tomvothecoder - We would welcome a PR to add xCDAT project to the page linked above.
