### ISSUE TITLE
No check for dimension compatibility on DataArray creation

### ISSUE THREAD

**Issue by jcrist** [pydata/xarray#758]
When creating a DataArray with an iterable of coordinates, no check is made that the dimensions of the coordinates match the shape of the data. Unsure if there's a reason why this isn't checked in xarray or not (I'd expect it to be). This may also just me using xarray wrong. I got bit by this earlier with a typo in my code:

```python
In [1]: import xarray as xr

In [2]: import numpy as np

In [3]: a = np.arange(6).reshape((2, 3))

In [4]: x = np.arange(3)

In [5]: y = np.arange(2, 4)

In [6]: xa = xr.DataArray(a, coords=[x, x], dims=['x', 'y'])   # Oop, gave x twice, instead of [x, y]

In [7]: xa.shape
Out[7]: (2, 3)

In [8]: xa.coords
Out[8]:
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1 2
```

**Comment by shoyer** [comment]
This does look strange/buggy... I will investigate
