### ISSUE TITLE
`np.multiply` and `dask.array.multiply` trigger graph computation vs using `+` and `*` operators.

### ISSUE THREAD

**Issue by zoj613** [pydata/xarray#7584]
### What is your issue?

I was trying to implement a simple weighted average function using a few `xr.DataArray` objects via
```python
def weighted_avg(args, weights):
	return np.multiply(args, weights).sum() / sum(weights)
```

To my surprise a call to to this function causes the graph to be computed as I had to wait for quite a bit given the size of the DataArray's. I realised that the graph was being computed. Even replacing `np.multiply` with `dask.array.multiply` did not make a difference. So I decided to implement the function using built-in operators like

```python
def weighted_avg(args, weights):
	import operator as op
	return sum(map(op.mul, args, weights)) / sum(weights)
```
and to my surprise this implementation returns immediately suggesting that the graph computation is delayed. Is this expected behaviour? I thought numpy/dask array functions lazily evaluate so this seems odd to me.

**Comment by max-sixty** [comment]
Could you make an full MCVE please?

**Comment by zoj613** [comment]
Unfortunately I have long left the project I was working on when this behavior was discovered so I doubt I can come up with a MCVE. So closing
