### ISSUE TITLE
`DataArray.to_dataframe()` takes 100x longer when data is read from a S3 cloud bucket via `fsspec` vs a netcdf

### ISSUE THREAD

**Issue by xaviernogueira** [pydata/xarray#7606]
### What happened?

Maybe a bug, maybe expected behavior. Feel free to recommend that I re-label. But I've discovered that when I read from an S3 cloud bucket via `fsspec` (i.e. [Planet OS ERA5 data](https://github.com/planet-os/notebooks/blob/master/aws/era5-pds.md)), the `to_dataframe()` option takes extremely long to complete. 

For example, converting a 678x180 DataArray to dataframe took 4 minutes, however, if I save the same data to NetCDF first then run `to_dataframe()` the same operation took 2.8 seconds. In practice I may just save it first locally, but for the sake of enabling full cloud deployment or use on a distributed system this could be a relevant issue to address.

**Comment by max-sixty** [comment]
(trying to clear up old issues, keep us below 1K)

This needs an MCVE, and maybe better suited as a usage question in Discussions
