### ISSUE TITLE
How to parse a non-standard time unit format as `years since 850-01-01 0:0:0` in xarray library?

### ISSUE THREAD

**Issue by KervinWen** [pydata/xarray#7609]
### What is your issue?

 Recently, I have been working with some netCDF data that has a time dimension in the format of `years since 850-01-01 0:0:0`. However, I encountered some issues when using xarray to read in and analyze the data.
Specifically, I found that xarray is not able to parse this time format directly, and I also tried using other libraries like netcdf4 and cftime, but to no avail. 

`ValueError: In general, units must be one of 'microseconds', 'milliseconds', 'seconds', 'minutes', 'hours', or 'days' (or select abbreviated versions of these).  
For the '360_day' calendar, 'months' can also be used, or for the 'noleap' calendar 'common_years' can also be used. Got 'years' instead, which are not recognized.` 

I understand that xarray has been designed to handle various types of time formats, but I have not been able to find a solution for this particular format.
Thank you very much for your time and consideration.

**Comment by spencerkclark** [comment]
Answered in #7610.
