### ISSUE TITLE
Issue with building docs on Ubuntu 22.04.1 

### ISSUE THREAD

**Issue by steph237** [pydata/xarray#7614]
### What happened?

`make html` fails to build with the following error
Tips on how to fix this issue will be appreciated
![Screenshot from 2023-03-12 16-47-22](https://user-images.githubusercontent.com/43364084/224555958-029a47d4-733c-41e9-afc2-e2a37ac1849f.png)

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

</details>

**Comment by keewis** [comment]
as discussed on discord, the reason for that failure is that current versions of `numba` are incompatible with `numpy>=1.24`. Downgrading to `numpy<1.24` should get the docs to build successfully.
