### ISSUE TITLE
The documentation contains some non-descriptive link texts.

### ISSUE THREAD

**Issue by remigathoni** [pydata/xarray#7617]
### What is your issue?

I've been going through the docs and noticed some links could be more descriptive. 

Here are a few examples with options on how we could rewrite them:
- See the [user guide](https://docs.xarray.dev/en/stable/indexing.html) for more. -> Check out the [indexing section in the user guide](https://docs.xarray.dev/en/stable/indexing.html) for a detailed explanation.
- For more, see [the Xarray documentation](https://docs.xarray.dev/en/stable/user-guide/computation.html#automatic-alignment). ->  See the [documentation on automatic alignment](https://docs.xarray.dev/en/stable/user-guide/computation.html#automatic-alignment) to learn more.
- [This tutorial notebook](https://tutorial.xarray.dev/fundamentals/02.3_aligning_data_objects.html) also covers alignment and broadcasting (highly recommended)->  You can also check out this [tutorial notebook on alignment and broadcasting](https://tutorial.xarray.dev/fundamentals/02.3_aligning_data_objects.html) (highly recommended).
- For more see the [user guide](https://docs.xarray.dev/en/stable/plotting.html), the [gallery](https://docs.xarray.dev/en/stable/examples/visualization_gallery.html), and [the tutorial material](https://tutorial.xarray.dev/fundamentals/04.0_plotting.html). -> For more information, check out the following resources:
   * The [plotting documentation](https://docs.xarray.dev/en/stable/user-guide/plotting.html) in the user guide.
   * The [visualization gallery](https://docs.xarray.dev/en/stable/examples/visualization_gallery.html).
   * The [plotting and visualization tutorial materials](https://tutorial.xarray.dev/fundamentals/04.0_plotting.html).

With more specific link texts, you get a clearer idea of what to expect when you click on the link which improves the reading experience. It also makes the links more accessible.

**Comment by TomNicholas** [comment]
Thanks @remigathoni ! We would welcome a pull request that made these improvements :slightly_smiling_face:

**Comment by remigathoni** [comment]
> Thanks @remigathoni ! We would welcome a pull request that made these improvements 🙂

I'll open a PR thanks @TomNicholas !

**Comment by Amisha2778** [comment]
Hey @TomNicholas 
I am an Outreachy applicant. I would like to work on this issue.

**Comment by TomNicholas** [comment]
Hi @Amisha2778 - unfortunately this issue has already been resolved by pull request #7625. We just forgot to close this issue once it was resolved, sorry about that! (The closing normally happens automatically but apparently didn't this time.)

You are welcome to work on any other issue you like, but I will close this one now.
