### ISSUE TITLE
Y-axis flipped when reading data with Xarray

### ISSUE THREAD

**Issue by RY4GIT** [pydata/xarray#7621]
#### Update
Update on March 15, 2023
First posted on March 13, 2023

#### Description
When reading data with Xarray using a rasterio engine, the Y axis is flipped. This happens with a specific dataset, and the summary is as follows. 

| Data\Engine | NetCDF4 | Rasterio |
| ------------- | ------------- | ------------- |
| 1. NSIDC output | ✅  | ❌ (Y axis is flipped)  |
| 2. NASA download  | ✅   | ✅   |

i.e., The issue happens with SMAP L4 data, pre-processed on the NSIDC server, read with rasterio engine. The issue does not happen with NetCDF4 engine.  It did not happen with the one directly downloaded from NASA Earth Data. 

<del>When reading data with Xarray using both the netcdf4 engine and the rasterio engine, the Y axis is flipped. However, when reading the same data with the netcdf4 package, the issue doesn't seem to be occurring. </del> 

It's unclear whether the issue is with Xarray or the data itself. 

![image](https://user-images.githubusercontent.com/52061672/225391882-5b5e9466-2822-4ff0-8b1a-23bfcacca1dc.png)

#### Details
I have created a Jupyter notebook with the details of the issue, including the code used to analyze the data, which is available [here](https://github.com/RY4GIT/sharing/blob/main/2_code_to_analyze/check_SMAPL4data.ipynb)

#### Data
- The data is SMAP L4 Geophysical data, precipitation (https://nsidc.org/data/spl4smgp/versions/7). The issue happens <del> for different versions of the dataset and</del> files for any dates or times. I tested it with two different versions of datasets. 
  - Dataset 1 is pre-processed & subset on NSIDC server
  - Dataset 2 is directly downloaded from NASA Earth Data portal

The data can be downloaded from the links provided by NASA and NSIDC (the links are specified in the notebook), or from my [Google Drive](https://drive.google.com/drive/folders/1vZFkW-ERw6zNucDNgyYrBfUz4NtBNXHO?usp=sharing). 

#### Environment Information
 - xarray version  2023.2.0 (the issue happened with 2023.1.0 too)
 - rioxarray version  0.13.3
 - rasterio version 1.3.6 (the issue happened with 1.3.4 too)
 - GDAL version  3.6.2
 - Python version 3.11 
 - Windows 11 
 (But I remember I've encountered this issues since a few years ago for SMAP data with ver 3.9 on Win 10)

#### Installation method
 - conda forge

Please let me know if you need any further information or have any suggestions on resolving this issue.
I am cross-posting this to [the rioxarray repo](https://github.com/corteva/rioxarray/issues/650). 

Thank you!

**Comment by kmuehlbauer** [comment]
@RY4GIT You would need to assign cell_lat/cell_lon as coordinates of the dataset and then use x="cell_lon" and y="cell_lat" in the call to .plot().

Plotting without that, will use the dimension coordinates (x,y) and there might be a difference in origin (upper vs. lower).

**Comment by RY4GIT** [comment]
Thank you for checking the code, @kmuehlbauer.
However, I am still experiencing issues even after fixing it.

Regarding the coordinates:
- The y coordinate starts from the maximum values and decreases as you move down the array.
- The latitude values increase with increasing y-coordinate values.
  - i.e., The latitude corresponding to the maximum y coordinate is around 85, and the one corresponding to the minimum y coordinate is around -85.
![image](https://user-images.githubusercontent.com/52061672/224865724-c06d2dab-102d-4003-bbbe-7ae5b000d5ec.png)
![image](https://user-images.githubusercontent.com/52061672/224865758-1d3eb205-6714-490c-9634-ff41a8dfbdb4.png)

Regarding the precipitation data:
- The structure is the same as the cell_lat/cell_lon array.
- The y coordinate starts from the maximum values and decreases as you move down the array.
- If I plot the precipitation with the xy coordinate, it looks like this, indicating that the data is still inverted. Please refer to these images for further clarification:
![image](https://user-images.githubusercontent.com/52061672/224866894-f845fe4d-7c35-4950-a475-5352254c6916.png)
![image](https://user-images.githubusercontent.com/52061672/224866383-5493f85a-8865-4e6c-b27a-f821bf5f7004.png)
Note that the unit is read incorrectly as degrees_north and degrees_east; please ignore it. 

Here is the updated code:```


lons = ds_NSIDC_output_rasterio.cell_lon.load()
lons_array = lons[0][0]

lats = ds_NSIDC_output_rasterio.cell_lat.load()
lats_array = np.arange(lats[0][0][0], lats[0][-1][0], -1*(lats.max().values-lats.min().values)/ds_NSIDC_output.y.size)

ds_NSIDC_output_rasterio_xymanual = xr.DataArray(
    data=ds_NSIDC_output_rasterio.precipitation_total_surface_flux.sel(band=1).values,
    dims = ["y","x"],
    coords = dict(
        y = lats_array,
        x = lons_array.values
    )
)
ds_NSIDC_output_rasterio_xymanual.plot()
```

![image](https://user-images.githubusercontent.com/52061672/224867633-95467632-3ad0-4bdf-9b4b-887f3c713c63.png)

**Comment by kmuehlbauer** [comment]
First, I've found this on SO:
https://gis.stackexchange.com/questions/454543/fixing-the-flipped-inverted-y-axis-in-the-xarray-with-rasterio

For your data reading method 1, it works for me like this:

```python
# load root group with coordinates
ds_NSIDC_root = xr.open_dataset(os.path.join(input_path, fn_NSIDC_output), group="/", engine='netcdf4')
# load data from Geophysical_Data group
ds_NSIDC_precip = xr.open_dataset(os.path.join(input_path, fn_NSIDC_output), group="Geophysical_Data", engine='netcdf4')
# merge groups
ds_NSIDC = xr.merge([ds_NSIDC_root, ds_NSIDC_precip])
# plot
ds_NSIDC.precipitation_total_surface_flux.plot()
# the above is essentielly the same as 
# ds_NSIDC.precipitation_total_surface_flux.plot(x="x", y="y")
```
![7621_0](https://user-images.githubusercontent.com/5821660/224922044-c1dc911e-42dd-472a-880f-dec6703a1fb4.png)

This can be expanded to use the cell_lon/cell_lat:

```
# set lat/lon as coords
ds_NSIDC = ds_NSIDC.set_coords(["cell_lon", "cell_lat"])
ds_NSIDC.precipitation_total_surface_flux.plot(x="cell_lon", y="cell_lat")
```
![7621_1](https://user-images.githubusercontent.com/5821660/224922083-a462c64d-84b5-4a8e-a47e-b33dc38f670b.png)

**Comment by kmuehlbauer** [comment]
For the rasterio-approach:

```python

```

**Comment by kmuehlbauer** [comment]
@RY4GIT I forgot to add my package versions. I'll add them the next day. But I'm pretty sure to have the most recent one's installed in a Python 3.10 conda-forge environment.

**Comment by RY4GIT** [comment]
The post on SO is actually what I wrote. I didn't feel right about messing around with y coordinates, so I came here to figure out what was happening.

Thank you so much for taking the time out of your busy schedule to download the data and test it.

The Xarray Netcdf engine solution worked on my end as well. It was really helpful in exploring what works best for this specific data, where latitude and longitude are stored in different locations. I appreciate your code and will use it for my future processing.

As for the rasterio solution, the output is still flipped along the Y axis. I updated both the rasterio and xarray packages to the latest versions, but the results were still the same. I used the same lines of code that you provided, but with a different file (instead of direct NASA output, I used NSIDC output, as the filename was specified as a variable, fn_NSIDC_output).

![image](https://user-images.githubusercontent.com/52061672/225222592-24acc97d-2af0-41cd-83af-85af28605de7.png)

**Comment by kmuehlbauer** [comment]
@RY4GIT Glad you can use the code. And good there's a way to use the data as is without tampering.

Regarding the different rasterio-approaches, just to be on the same page. The code I provided above (with the `fn_NASA_Earthdata_download` file) works for you too, but with `fn_NSIDC_output` it does not? Out of the box, the second also doesn't work for me. Didn't check this.

I've no immediate idea, what's going on in that case. The only thing I can think of is, that in the conversion process something has gone wrong with the georeferencing and/or the image origin. I hope you can figure that out, eventually.

Here for reference my package versions:

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0]
python-bits: 64
OS: Linux
OS-release: 5.14.21-150400.24.46-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: ('de_DE', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.1

xarray: 2023.2.1.dev22+g49ae0f8d.d20230310
pandas: 1.4.2
numpy: 1.23.5
scipy: 1.9.1
netCDF4: 1.6.2
pydap: None
h5netcdf: 1.1.0
h5py: 3.8.0
Nio: None
zarr: 2.12.0
cftime: 1.5.1.1
nc_time_axis: 1.4.1
PseudoNetCDF: None
rasterio: 1.3.6
cfgrib: None
iris: 3.2.1
bottleneck: 1.3.5
dask: 2022.10.0
distributed: 2022.10.0
matplotlib: 3.6.3
cartopy: 0.21.1
seaborn: None
numbagg: None
fsspec: 2023.1.0
cupy: None
pint: 0.17
sparse: None
flox: None
numpy_groupies: None
setuptools: 59.2.0
pip: 21.3.1
conda: None
pytest: 7.1.2
mypy: None
IPython: 8.2.0
sphinx: None

rioxarray: 0.13.3
gdal: 3.6.2
pyproj: 3.4.1
PROJ: 9.1.1
</details>

**Comment by RY4GIT** [comment]
@kmuehlbauer
> The code I provided above (with the fn_NASA_Earthdata_download file) works for you too, but with fn_NSIDC_output it does not?  
You are right.

I've gone made updates to both the issue description (i.e., the first post) and the Jupyter notebook based on our discussion. So, there might be an issue with the data or the rasterio engine, but for now, we'll use the NetCDF engine for NSIDC data, and hope that someone figures out the problem. Also, thanks for your suggestion on SO; it's much appreciated!

**Comment by jhamman** [comment]
Closing this issue as it seems like we've settled on a path forward. Feel free to reopen if I have that wrong.
