### ISSUE TITLE
cf_decodetimes TAI93 conversion off by ~10 seconds

### ISSUE THREAD

**Issue by nlenssen2013** [pydata/xarray#7626]
### What happened?

Xarray imports nc_dataset, decode times==True. Output time does not match tai93 to utc calculator and doesn't match time_utc variable in file.

### What did you expect to happen?

Download this url: https://sounder.gesdisc.eosdis.nasa.gov/data/JPSS1_Sounder_Level2/SNDRJ1IML2CCPRET.2/2021/055/SNDR.J1.CRIMSS.20210224T0100.m06.g011.L2_CLIMCAPS_RET.std.v02_28.G.210331064430.nc

I expected seconds since 1993-1-1 at 888282009.983966 to convert to utc: 2021 - 02 - 24T00:59:59 .983966. Instead to conversion ends up being utc: 2021-02-24T01:00:09.983965952

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np
import netCDF4 as nc

GROUP_DELIM = '__'

def transform_grouped_dataset(nc_dataset: nc.Dataset, file_to_subset: str) -> nc.Dataset:
    nc_dataset.close()
    nc_dataset = nc.Dataset(file_to_subset, 'r+')

    dimensions = {}

    def walk(group_node, path):
        for key, item in group_node.items():
            group_path = f'{path}{GROUP_DELIM}{key}'

            # If there are variables in this group, copy to root group
            # and then delete from current group
            if item.variables:
                # Copy variables to root group with new name
                for var_name, var in item.variables.items():
                    var_group_name = f'{group_path}{GROUP_DELIM}{var_name}'
                    nc_dataset.variables[var_group_name] = var
                # Delete variables
                var_names = list(item.variables.keys())
                for var_name in var_names:
                    del item.variables[var_name]

            if item.dimensions:
                dims = list(item.dimensions.keys())
                for dim_name in dims:
                    new_dim_name = f'{group_path.replace("/", GROUP_DELIM)}{GROUP_DELIM}{dim_name}'
                    item.dimensions[new_dim_name] = item.dimensions[dim_name]
                    dimensions[new_dim_name] = item.dimensions[dim_name]
                    item.renameDimension(dim_name, new_dim_name)

            # If there are subgroups in this group, call this function
            # again on that group.
            if item.groups:
                walk(item.groups, group_path)

        # Delete non-root groups
        group_names = list(group_node.keys())
        for group_name in group_names:
            del group_node[group_name]

    for var_name in list(nc_dataset.variables.keys()):
        new_var_name = f'{GROUP_DELIM}{var_name}'
        nc_dataset.variables[new_var_name] = nc_dataset.variables[var_name]
        del nc_dataset.variables[var_name]

    walk(nc_dataset.groups, '')

    # Update the dimensions of the dataset in the root group
    nc_dataset.dimensions.update(dimensions)

    return nc_dataset

file = 'SNDR.J1.CRIMSS.20210224T0100.m06.g011.L2_CLIMCAPS_RET.std.v02_28.G.210331064430.nc'
nc_dataset = nc.Dataset('SNDR.J1.CRIMSS.20210224T0100.m06.g011.L2_CLIMCAPS_RET.std.v02_28.G.210331064430.nc')
nc_dataset_flattened = transform_grouped_dataset(nc_dataset, file)
print (np.array(nc_dataset_flattened.variables['__obs_time_tai93'])[0][0])

args = {
    'decode_coords': False,
    'mask_and_scale': False,
    'decode_times': True
}

with xr.open_dataset(
        xr.backends.NetCDF4DataStore(nc_dataset_flattened),
        **args
) as dataset:
    print (np.array(dataset.variables['__obs_time_tai93'])[0][0])
    print (np.array(dataset.variables['__obs_time_utc'])[0][0])
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Anything else we need to know?

Having an earthdata login for SNDR file

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.9 (main, Mar  8 2023, 04:44:36) [Clang 14.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 22.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.8.1

xarray: 2022.11.0
pandas: 1.5.3
numpy: 1.23.5
scipy: None
netCDF4: 1.6.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.5
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.6.3
pip: 23.0.1
conda: None
pytest: None
IPython: 8.11.0
sphinx: None

</details>

**Comment by dcherian** [comment]
`obs_time_tai93` is a floating point variable so this seems like some roundoff error

**Comment by richli** [comment]
There have also been 10 leap seconds inserted into UTC between 1993-01-01 and 2021-02-24, so it looks like it's not accounting for those

**Comment by max-sixty** [comment]
Is there anything to do here or should we close?
