### ISSUE TITLE
0.7.1 release coming tomorrow

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#763]
Just a heads up that I plan to issue the v0.7.1 release tomorrow. There should be basically no API breakage.

We have a quite a few bug fixes that have made it in recently and it would be nice to get these out to users. See here for a list:
http://xarray.pydata.org/en/latest/whats-new.html

**Comment by MaximilianR** [comment]
Thanks!

**Comment by shoyer** [comment]
I've pushed the release to pypi. I'll send out the announcement email to the mailing list tomorrow.
