### ISSUE TITLE
.loc[] cannot find a value that .sel() can find without problem

### ISSUE THREAD

**Issue by AlxndrLhr** [pydata/xarray#7630]
### What is your issue?

Hi all, 
Given the minimal working example bellow:

``` python
import pandas as pd
import xarray as xr

nc = xr.DataArray([[0]], dims=["x", "y"],
    coords=dict(
        lon=(["x"], [1]),
        lat=(["y"], [1])))

times_ = pd.date_range('2020-01-01', '2022-01-01', freq='1d')
dt = times_[0]
nc = nc.expand_dims(time=times_)

nc.sel(time=dt)
nc.loc['time' == dt]

```

The `nc.sel()` part works like a charm, but the `nc.loc[]` return
`KeyError: "not all values found in index 'time'. Try setting the 'method' keyword argument (example: method='nearest')."`. Any idea what is happening there ?
Considering I want to be able to edit the values of `nc` for certain sets of `[x,y,time]`, my understanding is that I have to use `loc[]`. But it does not find the value `dt` whereas `sel()` does. How can I solve that ?

**Comment by kmuehlbauer** [comment]
@AlxndrLhr `.loc` is positional. The correct invocation would be:

```python
nc.loc[dt]
```

This would try to locate `dt` in the first dimension of `nc`. 

If you would append your time-dimension to the end, this would look like:

```python
nc = nc.expand_dims(time=times_, axis=-1)
nc.loc[..., dt]
# or
nc.loc[:, :, dt]
```

A good first read: https://docs.xarray.dev/en/stable/user-guide/indexing.html#indexing-and-selecting-data

**Comment by keewis** [comment]
you can also pass a `dict`, so `nc.loc[{"time": dt}]` or `nc.loc[dict(time=dt)]` should work as well

**Comment by kmuehlbauer** [comment]
Everyday something new to learn, thanks @keewis!

**Comment by AlxndrLhr** [comment]
Thanks all, but  it returns the `ValueError: output array is read-only`. Apparently, this is caused by `.expand_dims()` (see https://github.com/pydata/xarray/issues/3813). The work-around seems to be 
```python
nc = nc.expand_dims(time=times_).copy()
```
Though I have no idea why.

**Comment by kmuehlbauer** [comment]
@AlxndrLhr I suppose your original issue is resolved. Please reopen or create a new issue if you still have problems with this.
