### ISSUE TITLE
merge

### ISSUE THREAD

**Issue by wangshuaicumt** [pydata/xarray#7647]
### What is your issue?

```python
da = xr.open_dataarray(r'D:\Projects\SARimage_mosaic\merge_data\vel_ll_41-140.grd')
db = xr.open_dataarray(r'D:\Projects\SARimage_mosaic\merge_data\vel_ll_143-141.grd')

dc = xr.merge([da, db], join="outer", compat='no_conflicts', combine_attrs='drop_conflicts')
dc.to_netcdf('a.grd')

ds = xr.open_dataarray('a.grd')

ds.plot()
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/117328108/226265899-2f513bbe-2d16-49fc-8c44-58e0b3462786.png)

Why are there gaps in the resulting images？

**Comment by iacopoff** [comment]
Hi @wangshuaicumt  I guess it would be easier to help out if you share the datasets (or a subset)?

**Comment by wangshuaicumt** [comment]
> Hi @wangshuaicumt I guess it would be easier to help out if you share the datasets (or a subset)?

Yeah. Thanks.

The first data:
<xarray.DataArray 'z' (lat: 4350, lon: 5050)>
[21967500 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 86.26 86.26 86.26 86.26 ... 89.76 89.76 89.76 89.76
  * lat      (lat) float64 43.2 43.2 43.2 43.2 43.2 ... 45.01 45.01 45.01 45.01
Attributes:
    long_name:     z
    actual_range:  [-896.26568604  361.07537842]

The second data:
<xarray.DataArray 'z' (lat: 4420, lon: 5060)>
[22365200 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 88.22 88.22 88.22 88.22 ... 91.73 91.73 91.73 91.73
  * lat      (lat) float64 43.59 43.59 43.59 43.59 ... 45.43 45.43 45.43 45.43
Attributes:
    long_name:     z
    actual_range:  [-536.39135742  304.35101318]

The merge data:
<xarray.Dataset>
Dimensions:  (lon: 10110, lat: 8769)
Coordinates:
  * lon      (lon) float64 86.26 86.26 86.26 86.26 ... 91.73 91.73 91.73 91.73
  * lat      (lat) float64 43.2 43.2 43.2 43.2 43.2 ... 45.43 45.43 45.43 45.43
Data variables:
    z        (lat, lon) float32 nan nan nan nan nan nan ... nan nan nan nan nan
Attributes:
    long_name:  z

**Comment by wangshuaicumt** [comment]
> Hi @wangshuaicumt I guess it would be easier to help out if you share the datasets (or a subset)?

Due to restrictions on uploading original data files, I can only upload the results read by the terminal, and whether the original data file is required？

**Comment by kmuehlbauer** [comment]
@wangshuaicumt To see what's going on this might be sufficient. It looks like the grids (or dimensions) of your two input datasets do not really match each other. 

In consequence the merge-algorithm aligns the two inputs and introduces NaN at the places where the data is not defined at the resulting points, leaving you with these gaps in the output. (You can observe this in the dimension-sizes).

As this doesn't happen in my workflows I have no immediate help at hand and hope others will chime with some more guidance.

**Comment by wangshuaicumt** [comment]
> @wangshuaicumt To see what's going on this might be sufficient. It looks like the grids (or dimensions) of your two input datasets do not really match each other.
> 
> In consequence the merge-algorithm aligns the two inputs and introduces NaN at the places where the data is not defined at the resulting points, leaving you with these gaps in the output. (You can observe this in the dimension-sizes).
> 
> As this doesn't happen in my workflows I have no immediate help at hand and hope others will chime with some more guidance.

Yeah, thanks. Do you have any good suggestions for using Xarray to merge two *. grd files?

**Comment by iacopoff** [comment]
Maybe I am wrong, but I think the two scenes should be geocoded on the same grid, and then you should decide how to combine the values from the two scenes on the overlapping area.

**Comment by wangshuaicumt** [comment]
> Maybe I am wrong, but I think the two scenes should be geocoded on the same grid, and then you should decide how to combine the values from the two scenes on the overlapping area.

I think you're absolutely right. I just want to splice two pieces of data together, and there is a common area between them. Since I am a newcomer in the Xarray application, can you give me more tips?  Thanks a lot.

**Comment by kmuehlbauer** [comment]
Closing this for now. Please feel free to reopen.
