### ISSUE TITLE
Saving and loading an array of strings changes datatype to object

### ISSUE THREAD

**Issue by basnijholt** [pydata/xarray#7652]
### What is your issue?

See the code below
```python
import xarray as xr
# Make an xarray with an array of strings
da = xr.DataArray(
    data=[["a", "b"], ["c", "d"]],
    dims=["x", "y"],
    coords={"x": [0, 1], "y": [0, 1]},
)
da.to_netcdf("test.nc", mode='w')
# Load the xarray back in
da_loaded = xr.load_dataarray("test.nc")
assert da.dtype == da_loaded.dtype, "Dtypes don't match"
```

Now `da_loaded.dtype` is `dtype('O')`.

Same happens with `engine="h5netcdf"`.

```
import xarray
xarray.show_versions()
```
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 22.3.0
machine: arm64
processor: arm
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: None

xarray: 2023.2.0
pandas: 1.5.3
numpy: 1.24.2
scipy: 1.10.0
netCDF4: None
pydap: None
h5netcdf: 1.1.0
h5py: 3.8.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.7.0
cartopy: None
seaborn: 0.12.2
numbagg: None
fsspec: 2023.1.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 67.3.2
pip: 23.0
conda: None
pytest: 7.2.1
mypy: 1.0.1
IPython: 8.10.0
sphinx: 5.3.0
```

**Comment by jbweston** [comment]
It seems that the "string" information is stored in the `encoding` of the loaded dataset (set in this block https://github.com/pydata/xarray/blob/f1ff956ff67f3c053a2514d93d35929059e17b07/xarray/backends/h5netcdf_.py#L208)

but this encoding is not "applied" to the dtype of the dataset's variable.

**Comment by basnijholt** [comment]
Similar problem where saving, loading, saving, loading changes the dtype:
```python
import xarray as xr
da = xr.DataArray(data=[True], dims=["x"], coords={"x": [0]})
da.to_netcdf("test.nc", engine="h5netcdf", mode="w")
da_loaded = xr.load_dataarray("test.nc", engine="h5netcdf")
da_loaded.to_netcdf("test.nc", engine="h5netcdf", mode="w")
da_loaded = xr.load_dataarray("test.nc", engine="h5netcdf")
assert da.dtype == da_loaded.dtype, "Dtypes don't match"
```

**Comment by basnijholt** [comment]
Another fun one where `int64` -> `int32`:
```python
import xarray as xr

da = xr.DataArray(data=[1], dims=["x"], coords={"x": [0]})
da.to_netcdf("test.nc", mode="w")
da2 = xr.load_dataarray("test.nc")
da.dtype, da2.dtype
```

**Comment by kmuehlbauer** [comment]
> A similar problem where saving, loading, saving, loading changes the dtype `bool` -> `int8`:

That's an issue with netcdf file format, too, it has no bool-dtype.
XRef: https://github.com/pydata/xarray/issues/1500

```python
data = np.array([True], dtype=bool)
with nc.Dataset("test-bool-netcdf4.nc", mode="w") as ds:
    ds.createDimension("x", size=1)
    var = ds.createVariable("da", data.dtype.str,  dimensions=("x"))
    var[:] = data
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[42], line 4
      2 with nc.Dataset("test-bool-netcdf4.nc", mode="w") as ds:
      3     ds.createDimension("x", size=1)
----> 4     var = ds.createVariable("da", data.dtype.str,  dimensions=("x"))
      5     var[:] = data

File src/netCDF4/_netCDF4.pyx:2945, in netCDF4._netCDF4.Dataset.createVariable()

File src/netCDF4/_netCDF4.pyx:4121, in netCDF4._netCDF4.Variable.__init__()

TypeError: illegal primitive data type, must be one of dict_keys(['S1', 'i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f4', 'f8']), got bool
```

**Comment by kmuehlbauer** [comment]
> Another fun one where `int64` -> `int32`:

Can't reproduce this one with my environment. See above for details.

**Comment by kmuehlbauer** [comment]
> A similar problem where saving, loading, saving, loading changes the dtype `bool` -> `int8`:

@basnijholt I'd appreciate if you could test #7654 for that particular case.

**Comment by basnijholt** [comment]
Thanks a lot @kmuehlbauer!

I replied in your PR :smile:

**Comment by kmuehlbauer** [comment]
Great, much appreciated, thanks! Let's iterate over there then.

**Comment by kmuehlbauer** [comment]
OK, I've finally gotten to the bottom of this, so I'm writing my findings here:

**`int64` -> `int32`**

This works with `h5netcdf`/`netcdf4`-backends in any case. That's a feature[^1] of `NETCDF3`-format which will be used if `scipy` is installed and `netCDF4` is not installed. It has not notion of `int64` so this is silently cast to `int32` on write.

[^1]: https://docs.unidata.ucar.edu/nug/current/md_types.html

**`<U1` -> object**
This works with the changes applied in #7654 for `h5netcdf`/`netcdf4`-backends in normal cases (writing out as VLEN string). Again, `NETCDF3` format does not have a notion of string so all strings have to be converted to an internal NC_CHAR representation. I'm not sure it will do any good to try to make this one work.

My suggestion would be, just use `NETCDF4`-format and one of the capable backends.

**Comment by dcherian** [comment]
@kmuehlbauer this is amazing!

It would be very valuable to convert this list of limitations to the documentation: https://docs.xarray.dev/en/stable/user-guide/io.html#netcdf

**Comment by basnijholt** [comment]
@kmuehlbauer, great! 

I can confirm that both problems are indeed fixed on my end when using `h5netcdf` and the code from your PR :tada:

**Comment by kmuehlbauer** [comment]
> @kmuehlbauer this is amazing!
> 
> It would be very valuable to add this list of limitations to the documentation: https://docs.xarray.dev/en/stable/user-guide/io.html#netcdf

I've added a bit to this over at #7654.
