### ISSUE TITLE
I would suggest rewriting some of the documentation, not very clear in many places

### ISSUE THREAD

**Issue by yucsong** [pydata/xarray#7658]
### What is your issue?

For example,  rolling(time=24, center=True) -  you put dim there, but not in the format of dim = window ...

**Comment by dcherian** [comment]
Thanks @yucsong 

It would be very helpful if you sent us your suggestions. See [here](https://docs.xarray.dev/en/latest/contributing.html#contributing-to-the-documentation) for instructions.
