### ISSUE TITLE
colormap with vmin vmax

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#766]
When specifying a negative vmin and a positive vmax the `viridis` colormap is used. Is this intentional?

    import xarray as xr
    airtemps = xr.tutorial.load_dataset('air_temperature')
    air2d = airtemps.isel(time=500) - 273.15

    # diverging colormap
    air2d.plot.pcolormesh()

    # viridis
    air2d.plot.pcolormesh(vmin=-24, vmax=24)
    plt.show()

**Comment by fmaussion** [comment]
Yes, see https://github.com/pydata/xarray/pull/655

We decided that setting both `vmin` and `vmax` always imply a diverging colormap. The reason is that testing for `vmax = -vmin` is not robust. You should do:

```python
air2d.plot.pcolormesh(vmin=-24, center=True)
```

**Comment by mathause** [comment]
Ah, yes center=0 does the trick. Thank you.

**Comment by fmaussion** [comment]
I forgot to mention that center is set to 0 by default ;-)
