### ISSUE TITLE
Add welcome bot?

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#7685]
### Is your feature request related to a problem?

Given all the outreachy interest (and perhaps just in general) it may be nice to enable a [welcome bot](https://github.com/apps/welcome) like on the Jupyter repos

**Comment by nishtha981** [comment]
Could you specifiy what kind of function you would like the bot to perform?

**Comment by TomNicholas** [comment]
Good idea @dcherian 

> Could you specifiy what kind of function you would like the bot to perform?

When a github user creates their first ever issue or pull request on the xarray repository, the bot would reply to them welcoming them with a friendly message, thanking them for their interest, and point them towards useful links like contributing guidelines and contact channels.

**Comment by nishtha981** [comment]
Sure!
I'm on it!

**Comment by dcherian** [comment]
Thanks @nishtha981 I installed the bot so now I think we just need a PR with `.github/config.yml` ([see instructions](https://probot.github.io/apps/welcome/))

**Comment by nishtha981** [comment]
Ahhh okay 
I've made a bot for the repo!

**Comment by nishtha981** [comment]
Hey!
@dcherian 
I've added the  `.github/config.yml` file.
