### ISSUE TITLE
Feature proposal: DataArray.to_zarr()

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#7692]
### Is your feature request related to a problem?

It would be nice to mimic the behavior of `DataArray.to_netcdf` for the Zarr backend.

### Describe the solution you'd like

This should be possible:
```python
xr.open_dataarray('file.nc').to_zarr('store.zarr')
```

### Describe alternatives you've considered

None.

### Additional context

xref `DataArray.to_netcdf` issue/PR: #915 / #990

**Comment by keewis** [comment]
I guess the alternative would be to go with `xr.save_dataset` / `xr.save_dataarray`, but that seems like a lot of work (*and* I agree that since we already have `Dataset.to_zarr` we can also have `DataArray.to_zarr`)

**Comment by jhamman** [comment]
I was once a fan of the `save_dataset` route but I think we've opted to stick with the format specific `to_` methods.

**Comment by keewis** [comment]
As far as I understand #5954 and the meeting notes, we didn't decide anything about that yet (I might be wrong, though). So I assume the only reason we don't have write backends and `save_dataset` / `save_dataarray` right now is that nobody got around to doing that yet.

**Comment by TomNicholas** [comment]
:+1: to not having to write `to_dataset` before saving things.

I think the `.to_X` vs e.g. `.save(engine='X')` is important enough that we should think about it a bit more. The response to #7496 doesn't seem conclusive to me (yet).

A twitter poll? Then a discussion in a meeting?
