### ISSUE TITLE
Using xarray in Docker on a mac fails with "No such file or directory: 'gdal-config'"

### ISSUE THREAD

**Issue by 28raining** [pydata/xarray#7705]
### What is your issue?

Hi,

This is my docker file "Dockerfile": 
```
FROM python:3.11.2-slim
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install xarray[io]
```

Which is built with this command:
`docker build -t "name:Dockerfile" .`

My docker version is:
`Docker version 20.10.23, build 7155243`

And I'm running macOS Ventura 13.3

Error message:
```
#6 11.79   Downloading rasterio-1.3.6.tar.gz (408 kB)
#6 11.83      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 408.5/408.5 kB 12.4 MB/s eta 0:00:00
#6 11.86   Installing build dependencies: started
#6 14.05   Installing build dependencies: finished with status 'done'
#6 14.05   Getting requirements to build wheel: started
#6 14.17   Getting requirements to build wheel: finished with status 'error'
#6 14.17   error: subprocess-exited-with-error
#6 14.17   
#6 14.17   × Getting requirements to build wheel did not run successfully.
#6 14.17   │ exit code: 1
#6 14.17   ╰─> [2 lines of output]
#6 14.17       WARNING:root:Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
#6 14.17       ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
#6 14.17       [end of output]
```

**Comment by 28raining** [comment]
Note that it works outside of docker on my mac, and it also works inside of Docker on Centos

**Comment by jhamman** [comment]
This doesn't seem like an issue with Xarray. If you change your dockerfile to:

```
FROM python:3.11.2-slim
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install xarray
RUN pip install rasterio
```

I suspect you will find that you get the same error on the rasterio line and not on the xarray line. 

A second note: Xarray and netcdf4 have not released complete support for python 3.11. For that reason, you may also want to use the python 3.10 image.

**Comment by 28raining** [comment]
Thanks. Note same error on Python 3.9.6.

I have filed a ticket on Rasterio then
https://github.com/rasterio/rasterio/issues/2801

**Comment by abunimeh** [comment]
run `RUN apt-get update && apt-get install --yes libgdal-dev` before pip

**Comment by psychemedia** [comment]
As well as `libgdal-dev` I noticed that `g++` was also required for the Fiona wheel build.
