### ISSUE TITLE
PyCharm warnings on numeric operations

### ISSUE THREAD

**Issue by MaximilianR** [pydata/xarray#771]
Currently PyCharm warns if a numeric operation is performed on an xarray object. We could suppress these by:
- Adding `__add__ = NotImplemented` onto the `BaseDataObject` (and all the other ops from `CMP_BINARY_OPS` & `NUM_BINARY_OPS`), so IDEs know about them
- Adding a set of skeletons here: https://github.com/JetBrains/python-skeletons. I haven't tried this, and the readme looks out of date. But it does seem to work for numpy objects
- Wait for IDEs to be able to recognize the monkey patching that is done here (not my preference)

**Comment by shoyer** [comment]
I'd be happy with the first option, although I'd rather we use a function that actually gives a sensible error message, i.e.,
```python
def _not_implemented(*args):
    return NotImplemented
__add__ = _not_implemented
```

This does seem to be a oint in favor of doing something more explicit rather than injecting numeric operations.
