### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by moraraba** [pydata/xarray#7711]
### Is your feature request related to a problem?

Document examples of using various xarray methods

### Describe the solution you'd like

Selecting a subset of data using xarray's `sel` method:

# Select data for a specific time and latitude/longitude range
ds_sel = ds.sel(time='2020-01-01', lat=slice(-30, 30), lon=slice(0, 100))

### Describe alternatives you've considered

Loading data from a NetCDF file using xarray's `open_dataset` method:

import xarray as xr

# Open a NetCDF file
ds = xr.open_dataset('data.nc')

**Comment by headtr1ck** [comment]
Not sure what you are proposing here.
We have extensive documentation on data indexing and selection here https://docs.xarray.dev/en/stable/user-guide/indexing.html

If this is not what you mean, please update your description and title to something more meaningful.
