### ISSUE TITLE
`Variable/IndexVariable` do not accept a tuple for data.

### ISSUE THREAD

**Issue by zoj613** [pydata/xarray#7713]
### What happened?

It appears that `Variable` and `IndexVariable` do not accept a tuple for the `data` parameter even though the docstring suggests it should be able to accept `array_like` objects (tuple falls under this type of object, right?).

### What did you expect to happen?

Successful instantiation of a `Variable/IndexVariable` object, but instead a `ValueError` exception is raised.

### Minimal Complete Verifiable Example

```Python
import xarray as xr

xr.Variable(data=(2, 3, 45), dims="day")
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [x] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
ValueError: dimensions ('day',) must have the same length as the number of data dimensions, ndim=0
```

### Anything else we need to know?

This error seems to be triggered by the `self._parse_dimensions(dims)` call inside the `Variable` class. This problem does not happen if I use a list. But I find it strange that the `array_like` data specifically needs to be a certain type of object for the call to work. Maybe if it _has_ to be a list then the docstring should reflect that.

### Environment

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55)
[GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 6.1.21-1-lts
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.8.1

xarray: 2023.1.0
pandas: 1.5.3
numpy: 1.23.5
scipy: 1.10.1
netCDF4: 1.6.2
pydap: None
h5netcdf: 1.1.0
h5py: 3.8.0
Nio: None
zarr: 2.14.2
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2023.3.2
distributed: 2023.3.2
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.3.0
cupy: None
pint: None
sparse: 0.14.0
flox: None
numpy_groupies: None
setuptools: 67.6.1
pip: 23.0.1
conda: None
pytest: 7.2.2
mypy: 1.1.1
IPython: 8.12.0
sphinx: None
```

</details>

**Comment by kmuehlbauer** [comment]
The code is there since #867 by @shoyer which was committed almost 7 years ago. 

I've no idea what's the purpose for packing tuples into 0d arrays but as there are also tests for it in the above PR I'm assuming there is one real reason. Maybe @shoyer can chime in here to shed some light?

**Comment by dcherian** [comment]
See  https://github.com/pydata/xarray/issues/4404 It seems like this is for MultiIndex support. A better error message  and  documentation  would be a great contribution!
