### ISSUE TITLE
Implement lshift and rshift operators

### ISSUE THREAD

**Issue by abrammer** [pydata/xarray#7727]
### Is your feature request related to a problem?

I've noticed that xarray does not support the lshift or rshift operators.  While this is workable by using the numpy array the addition of the operators also seem somewhat trivial and reduces friction for numpy users adopting xarray.   

Is the exclusion of these operators intentional or oversight or some other historic reason?

### Describe the solution you'd like

Implement the operators if it makes sense. 

### Additional context

I experimented with the potential edits here: https://github.com/abrammer/xarray/tree/feat/add_lshift_and_rshift_operators
but don't want to open a PR without an initial discussion.   I haven't delved into this area of xarray before so I probably missed something or did something wrong.

**Comment by dcherian** [comment]
I think we would gladly take a PR for this.
