### ISSUE TITLE
Inconsistency between xr.where() and da.where()

### ISSUE THREAD

**Issue by tbloch1** [pydata/xarray#7767]
### What is your issue?

`xr.where()` and `da.where()` behave in seemingly opposite ways.

Example:

```python
da = xr.DataArray(np.arange(10)
print(xr.where(da < 5, 0, da).values)
print(da.where(da < 5, 0).values)
```
```
[0 0 0 0 0 5 6 7 8 9]
[0 1 2 3 4 0 0 0 0 0]
```

It seems like these two methods with the same name _should_ have the same functionality, but they give inverse results.

**Comment by keewis** [comment]
to elaborate on that, `xr.DataArray.where` uses `self` as "then" and the second argument as "other", while for `xr.where` the second argument is "then" and the third argument is "other" (the condition is the first argument for both).

**Comment by tbloch1** [comment]
Thanks for the replies

So while `xr.where(cond, x, y)` is semantically, "where condition is true, x, else y", `da.where(cond, x)` is "where condition is true `da`, else x".

The latter feels quite unintuitive to me. Is the reason they're different only for the mask example you provided? Where NaN is returned as the default 'x' value?

**Comment by keewis** [comment]
According to #503, there's two reasons: the fact that for masking this is so much easier to write (including when method chaining), and it is also API inherited from `pandas`.

**Comment by SimonHeybrock** [comment]
> Thanks for the replies
> 
> So while `xr.where(cond, x, y)` is semantically, "where condition is true, x, else y", `da.where(cond, x)` is "where condition is true `da`, else x".
> 
> The latter feels quite unintuitive to me. Is the reason they're different only for the mask example you provided? Where NaN is returned as the default 'x' value?

I think `da.where(cond, x)` becomes a bit more intuitive when you compare to Python's ternary:

```python
# da.where(cond, x)
da if cond else x
```
