### ISSUE TITLE
Provide a public API for adding new backends

### ISSUE THREAD

**Issue by hmaarrfk** [pydata/xarray#7770]
### Is your feature request related to a problem?

I understand that this is a double edge sword. but we were relying on `BACKEND_ENTRYPOINTS` being a dictionary to a class and that broke in 

https://github.com/pydata/xarray/pull/7523

### Describe the solution you'd like

Some agreed upon way that we could create a new backend. This would allow users to provide more custom parameters to file creation attributes and other options that are currently not exposed via xarray.

I've used this  to overwrite some parameters like netcdf global variables.

I've also used this to add `alignment_threshold` and `alignment_interval` to h5netcdf.

I did it through a custom backend because it felt like a contentious feature at the time. (I really do think it helps performance).

### Describe alternatives you've considered

A deprecation cycle in the future??? 

Maybe this could have been acheived with the definition of `RELOADABLE_BACKEND_ENTRYPOINTS` and leaving the `BACKEND_ENTRYPOINTS` unchanged in signature.

### Additional context

We used this to define the alignment within a file. netcdf4 exposed this as a global variable so we have to somewhat hack around it just before creation time.

I mean, you can probably say:

"Doing this is too complicated, we don't want to give any guarantees on this front."

I would agree with you.....

**Comment by dcherian** [comment]
You should be using entrypoints:
- https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html
- https://tutorial.xarray.dev/advanced/backends/backends.html

**Comment by hmaarrfk** [comment]
Understood. Thank you for your prompt replies.

I'll read up on ask again if I have any questions.

I guess I was trying to accommodate in the past users that were not using our wrappers to `to_netcdf`
