### ISSUE TITLE
 Process getting killed due to high memory consumption of xarray's nbytes method

### ISSUE THREAD

**Issue by dabhicusp** [pydata/xarray#7772]
### What is your issue?

The `nbytes` method in `xarray` calculates the number of bytes used by a DataArray or Dataset object. However, I have noticed that this method can lead to high memory consumption, especially when dealing with large datasets.

When I call `nbytes` on a large dataset, it can take significant time and memory to compute. For example, when I tried to calculate the size of this dataset, the `nbytes` method consumed several gigabytes of memory and took a few minutes to complete.
Below is an example of the whole process::
 1. First we create a dataset
 2. Observe the memory consumption using the `nbytes` method
 
The code to generate the sample dataset is below:

    import netCDF4 as nc
    import numpy as np

    fn = '~/test_1.nc'
    ncfile = nc.Dataset(fn, 'w', format='NETCDF4')
    
    lat_dim = ncfile.createDimension('lat', 7210) # latitude axis
    lon_dim = ncfile.createDimension('lon', 7440) # longitude axis
    time_dim = ncfile.createDimension('time', None) 
    
    
    lat = ncfile.createVariable('lat', np.float32, ('lat',))
    lon = ncfile.createVariable('lon', np.float32, ('lon',))
    time = ncfile.createVariable('time', np.float64, ('time',))
    
    var_1 = ncfile.createVariable('var_1',np.float64,('time','lat','lon'), zlib=True) 
    var_2 =  ncfile.createVariable('var_2',np.float64,('time','lat','lon'), zlib=True) 
    var_3 =  ncfile.createVariable('var_3',np.float64,('time','lat','lon'), zlib=True) 
    var_4 =  ncfile.createVariable('var_4',np.float64,('time','lat','lon'), zlib=True) 
    
    nlats = len(lat_dim); nlons = len(lon_dim); ntimes = 5
    lat[:] = -90. + (180./nlats)*np.arange(nlats) 
    lon[:] = (180./nlats)*np.arange(nlons) 
    
    data_arr = np.random.uniform(low=100,high=330,size=(ntimes,nlats,nlons))
    var_1[:,:,:] = data_arr 
    var_2[:,:,:] = data_arr 
    var_3[:,:,:] = data_arr 
    var_4[:,:,:] = data_arr 
    
    ncfile.close(); 

After running the above code(`python <file_name>.py`), `test_1.nc` is generated with a compressed size of approximately 7.1 gigabytes and an actual size of approximately 8.6 gigabytes. To calculate the memory consumed by  `nbytes` method, we can use the following code:
```
import xarray as xa
from memory_profiler import profile

@profile
def get_dataset_size() :
    dataset = xa.open_dataset("test_1.nc")
    print(dataset.nbytes)
    
if __name__ == "__main__":
    get_dataset_size()
```
```
8582842640
Filename: demo.py
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     4     97.8 MiB     97.8 MiB           1   @profile
     5                                         def get_dataset_size() :
     6    160.4 MiB     62.6 MiB           1       dataset = xa.open_dataset("test_1.nc")
     7   8434.2 MiB   8273.8 MiB           1       print(dataset.nbytes)
```
We can observe that it is taking ~8.6GB RAM which is approx. equal to the actual size of the dataset (returned by the nbytes).

**Note: if the machine's memory size is only 8 gigabytes, this process will be killed.**

Instead, we can use another method to calculate the size of the file, which will not consume too much memory to compute and provide the same result as the nbytes method:

Other Method's code:
```
import xarray as xa
from memory_profiler import profile

@profile
def get_dataset_size() :
    dataset = xa.open_dataset("test_1.nc")
    print(sum(v.size * v.dtype.itemsize for v in dataset.variables.values()))

    
if __name__ == "__main__":
    get_dataset_size()
```
```
8582842640
Filename: demo.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     4     97.8 MiB     97.8 MiB           1   @profile
     5                                         def get_dataset_size() :
     6    160.5 MiB     62.7 MiB           1       dataset = xa.open_dataset("test_1.nc")
     7    160.5 MiB      0.0 MiB          17       print(sum(v.size * v.dtype.itemsize for v in dataset.variables.values()))
```
While exploring the code I found that at [line 396](https://github.com/pydata/xarray/blob/9ff932a564ec1e19918120bab0ec78f1f87df07b/xarray/core/variable.py#L396) it uses `self._data.nbytes` which is causing the memory issue. But in the next lines, it uses the method stated above.

So why have that `if` block at line 396?

**Comment by TomNicholas** [comment]
Thanks for raising this @dabhicusp !

> So why have that if block at line 396?

Because xarray can wrap many different type of numpy-like arrays, and for some of those types then the `self.size * self.dtype.itemsize` approach may not return the correct size. Think of a sparse matrix for example - its size in memory is designed to be much smaller than the size of the matrix would suggest. That's why in general we defer to the underlying array itself to tell us its size if it can (i.e. if it has a `.nbytes` attribute).

But you're not using an unusual type of array, you're just opening a netCDF file as a numpy array, in theory lazily. The memory usage you're seeing is not desired, so something weird must be happening in the `.nbytes` call. Going deeper into the stack at that point would be helpful.

**Comment by dabhicusp** [comment]
The first point that you mentioned does not seem to be correct. Please see the below code (we took the sparse matrix ) and output:
```
import xarray as xa
import numpy as np

def get_data():
    lat_dim = 7210
    lon_dim = 7440
    
    lat = [0] * lat_dim
    lon = [0] * lon_dim 
    time = [0] * 5
    
    nlats = lat_dim; nlons = lon_dim; ntimes = 5
    
    var_1 = np.empty((ntimes,nlats,nlons))
    var_2 = np.empty((ntimes,nlats,nlons))
    var_3 = np.empty((ntimes,nlats,nlons))
    var_4 = np.empty((ntimes,nlats,nlons))
    
    data_arr = np.random.uniform(low=0,high=0,size=(ntimes,nlats,nlons))
    data_arr[:,0,:] = 1
    data_arr[:,:,1] = 1

    var_1[:,:,:] = data_arr 
    var_2[:,:,:] = data_arr 
    var_3[:,:,:] = data_arr 
    var_4[:,:,:] = data_arr 
    
    dataset = xa.Dataset( 
            data_vars = {
                'var_1': (('time','lat','lon'), var_1),
                'var_2': (('time','lat','lon'), var_2),
                'var_3': (('time','lat','lon'), var_3),
                'var_4': (('time','lat','lon'), var_4)},
            coords = {
                'lat': lat,
                'lon': lon,
                'time':time})

    print(sum(v.size * v.dtype.itemsize for v in dataset.variables.values()))
    print(dataset.nbytes)
    
if __name__ == "__main__":
    get_data()
```

```
8582901240
8582901240
```
As we can observe here both `nbytes` and `self.size * self.dtype.itemsize` gives the same size.

And for the 2nd point can you share any solution for the nbytes for the `netCDF` or `grib` file as it takes too much memory and killed the process?

**Comment by keewis** [comment]
that's a numpy array with sparse data. What @TomNicholas was talking about is a array of type `sparse.COO` (from the [sparse](https://github.com/pydata/sparse/) package).

And as far as I can tell, our wrapper class (which is the reason why you don't get the memory error on open) does not define `nbytes`, so at the moment there's no way to do that. You could try using `dask`, though, which does allow working with bigger-than-memory data.

**Comment by dcherian** [comment]
I cannot reproduce this on `main`. What version are you running

```
(xarray-tests) 17:55:11 [cgdm-caguas] {~/python/xarray/devel}
──────> python lazy-nbytes.py
8582842640
Filename: /Users/dcherian/work/python/xarray/devel/lazy-nbytes.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     4    101.5 MiB    101.5 MiB           1   @profile
     5                                         def get_dataset_size() :
     6    175.9 MiB     74.4 MiB           1       dataset =     xa.open_dataset("test_1.nc")
     7    175.9 MiB      0.0 MiB           1       print(dataset.nbytes)
```

The BackendArray types define `shape` and `dtype` so we can calculate size without loading the data.

**Comment by dabhicusp** [comment]
Thank you @dcherian . I checked on `main` branch and it can't reproduce.

**Comment by dabhicusp** [comment]
Thank you @dcherian . I cannot reproduced this on `main`.
