### ISSUE TITLE
[FR] add support for rss and rss button to xarray blog

### ISSUE THREAD

**Issue by danieltomasz** [pydata/xarray#7805]
### Is your feature request related to a problem?

A easy way to subscribe to news from xarray blog

### Describe the solution you'd like

A support for publishing news and  button to subscribe to rss from blog (along twitter icon etcera)

**Comment by headtr1ck** [comment]
Thanks for the suggestion.
This issue should be over at https://github.com/xarray-contrib/xarray.dev, but I cannot transfer it.
Maybe you can reopen another issue there?

**Comment by jhamman** [comment]
I copy and pasted this issue on the web repo: https://github.com/xarray-contrib/xarray.dev/issues/550
