### ISSUE TITLE
Backend registration does not match docs, and is no longer specifiable in maturin pyproject toml

### ISSUE THREAD

**Issue by gauteh** [pydata/xarray#7816]
### What happened?

https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html#how-to-register-a-backend does not work with maturin any more. The format has changed to a tuple, from netcdf4 backend:

BACKEND_ENTRYPOINTS["netcdf4"] = ("netCDF4", NetCDF4BackendEntrypoint)

https://www.maturin.rs/metadata.html

is this specifiable by pyproject.toml anymore?

Affects: #7446 

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

</details>

**Comment by headtr1ck** [comment]
I am not sure what exactly is not working.
The BACKEND_ENTRYPOINTS is not a public API and is only used for xarrays internal backends.
In the documentation that you have linked it is explained on how to register your project, which is purely in the setup.cfg/project.toml, no need to manipulate xarray internal objects.

**Comment by gauteh** [comment]
If I do not manually add the backend to the array, but only have this line in https://github.com/gauteh/hidefix/blob/main/pyproject.toml#L29: 

```
[project.entry-points."xarray.backends"]
hidefix = "hidefix.xarray:HidefixBackendEntrypoint"
```

which is only what is supported by pyproject.toml/maturin I get an error where xarray expected a tuple and cannot parse the entrypoint, not just the adderss to the entrypoint - as it used to be (back in January at least).

**Comment by kmuehlbauer** [comment]
@gauteh You would probably have to delete this line:

https://github.com/gauteh/hidefix/blob/main/python/hidefix/xarray.py#L192

As @headtr1ck already explained, it is all handled via plugin system to be able to handle duplicate engine names on discovery by the python metadata.

**Comment by gauteh** [comment]
Hi,

Yes, I tried that, but I then got the same error as if I kept that line in the old format. I'll do a few tests and post the proper error here.

Gaute

**Comment by kmuehlbauer** [comment]
@gauteh Yes, please provide as much information as possible. It is also of interest, how you installed the package and what Python environment you are using (eg. system python, conda, venv etc.)

**Comment by gauteh** [comment]
Hi,

I forgot to rebuild the package after removing the BACKEND_... line. With only the line in pyproject.toml it works as it should! My mistake. Thanks for the patience.

Regards, Gaute

**Comment by kmuehlbauer** [comment]
@gauteh No worries, glad it works now!
