### ISSUE TITLE
Slow performance of concat()

### ISSUE THREAD

**Issue by alimanfoo** [pydata/xarray#7833]
### What is your issue?

In attempting to concatenate many datasets along a large dimension (total size ~100,000,000) I'm finding very slow performance, e.g., tens of seconds just to concatenate two datasets.

With some profiling, I find all the time is being spend in this list comprehension:

https://github.com/pydata/xarray/blob/51554f2638bc9e4a527492136fe6f54584ffa75d/xarray/core/concat.py#L584

I don't know exactly what's going on here, but it doesn't look right - e.g., if the size of the dimension to be concatenated is large, this list comprehension can run millions of loops, which doesn't seem related to the intended behaviour.

Sorry I don't have an MRE for this yet but please let me know if I can help further.

**Comment by Illviljan** [comment]
I've noticed this as well, see #7824.

**Comment by kmuehlbauer** [comment]
@alimanfoo The slow code stems from my changes in #7400. Obviously the performance drop did not manifest in the tests/ benchmarks.

In #7824 @Illviljan is tackling concat performance.

**Comment by alimanfoo** [comment]
Awesome, thanks @kmuehlbauer and @Illviljan 🙏🏻
