### ISSUE TITLE
Xarray docs showing tracebacks instead of plots

### ISSUE THREAD

**Issue by rbavery** [pydata/xarray#7841]
### What happened?

I think the docs on open_rasterio should be showing plots but show tracebacks instead: https://docs.xarray.dev/en/stable/examples/visualization_gallery.html#imshow()-and-rasterio-map-projections

### What did you expect to happen?

should show plots

### Minimal Complete Verifiable Example

```Python
https://docs.xarray.dev/en/stable/examples/visualization_gallery.html#imshow()-and-rasterio-map-projections
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

n/a

**Comment by dcherian** [comment]
We should migrate these to rioxarray if they aren't there already. 

cc @snowman2 @scottyhq @JessicaS11

**Comment by dcherian** [comment]
https://github.com/corteva/rioxarray/issues/676
