### ISSUE TITLE
 Freezing Issue When Accessing Precipitation Values with xarray

### ISSUE THREAD

**Issue by yanivgolds** [pydata/xarray#7854]
### What is your issue?

I am encountering a freezing issue in my project that utilizes xarray when trying to access precipitation values for a specific longitude-latitude position over a time period. This issue occurs on the slurm system but is not reproduced on my Jupyter Notebook setup. As a result, whenever I attempt to run the project, the job freezes. I would greatly appreciate your assistance in determining the cause of this problem.

Below is a figure showing the result from Jupyer Notebook (this works):

<img width="334" alt="image" src="https://github.com/pydata/xarray/assets/118670091/5671653b-a632-4ebb-8c51-7e06ebbf1afe">

**Comment by cerbaro** [comment]
Hi @yanivgolds, any updates on this issue? I am also facing a similar error. It ramdonly gets stuck when trying to access values, even if the dataarray is relatively small. Have you found anything?

**Comment by andersy005** [comment]
@yanivgolds / @cerbaro , it would be useful to know more about your code and the specific operations you're performing. can you provide more information about the steps leading up to the freeze (e.g. how are the data loaded, how much data, what resources (CPU, RAM) is your SLURM job using, etc)?

**Comment by yanivgolds** [comment]
Hi,
I resolved the freezing problem by increasing the CPU allocation per task. This solution proved effective in overcoming the issue. Thanks for your assistance.
