### ISSUE TITLE
reindex and netCDF indexing

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#786]
reindex can cause problems as long as the data is not loaded

    import xarray as xr
    data = xr.DataArray([1, 2, 3], dims='x').to_dataset('name')
    data.to_netcdf('tst.nc')

    # works fine
    a = xr.open_dataset('tst.nc')
    a.load()
    a.reindex(x=[2, 0, 1])

    # problem
    b = xr.open_dataset('tst.nc')
    b.reindex(x=[2, 0, 1])

**Comment by shoyer** [comment]
Which version of netCDF4-Python are you using? This was an issue for some recent versions of netCDF4-Python but was then fixed -- see https://github.com/Unidata/netcdf4-python/issues/467 for details.

**Comment by mathause** [comment]
This solves the problem - thank you very much!
