### ISSUE TITLE
Add Groupby and Rolling methods to docs

### ISSUE THREAD

**Issue by jhamman** [pydata/xarray#787]
The injected `apply`/`reduce` methods for the `Groupby` and `Rolling` objects are not shown in the api documentation page. While there is obviously a fair bit of overlap between the similar  `DataArray`/`Dataset` methods, it would help users to know what methods are available to the `Groupby` and `Rolling` methods if we explicitly listed them in the documentation. Suggestions on the best format to show these mehtods (e.g. `Rolling.mean`) are welcomed.

**Comment by keewis** [comment]
with #3602, the methods of any object can be found (and clicked on) on the object's API page (reachable from the main API page, but separate). This might not be ideal, but I'd say finding a better solution is out of scope for #3602.

**Comment by dcherian** [comment]
Fixed by #5903
