### ISSUE TITLE
Name collision with Pulsar Timing package 'PINT' 

### ISSUE THREAD

**Issue by vhaasteren** [pydata/xarray#7870]
### What is your issue?

In the astrophysics community of [pulsar timers](https://en.wikipedia.org/wiki/Pulsar_timing_array), there is an analysis package called `PINT`. PINT is widely used in that community. As you can see on their [github](https://github.com/nanograv/PINT), they have been aware of the name collision and on pip/conda the package is available as `pint-pulsar`. This has not been a problem so far, because most if not all astrophysicists use the great [astropy](https://www.astropy.org/) to keep track of units where necessary.

However, Bayesian modeling through PyMC is becoming more and more popular, meaning that arviz and xarray are now getting installed alongside pint-pulsar, giving obvious issues.

A very simple workaround would be to change line 37 in https://github.com/pydata/xarray/blob/main/xarray/core/pycompat.py to something like:

`except (ImportError, AttributeError):`

This means that `pint-pulsar` would get imported through `mod`), and the `AttributeError` gets caught, and all should be well. It fits the design of duck-typing, since the package doesn't Quack like pint should. Would xarray be willing to accommodate the pulsar timing community this way? As you are all aware, changing the name of a package that is integral in projects with many dependencies is kind of painful.

EDIT: fixed typo

**Comment by TomNicholas** [comment]
Thanks for raising this @vhaasteren ! We want to do what we can to support users from all fields of science :)

I would be okay with that change (especially as it's not really special-casing pint-pulsar, so much as generalizing an existing error-catching mechanism), but would defer to the opinion of @keewis on this.

**Comment by vhaasteren** [comment]
Thank you @TomNicholas, that is encouraging to hear. I will wait for @keewis to respond before filing a PR.

FWIW, I have tested the modification I suggest in [my fork](https://github.com/vhaasteren/xarray) of xarray, and it works well for our purposes. It just generalizes the exception catch.

**Comment by keewis** [comment]
I agree, this change should be fine.
