### ISSUE TITLE
Nan Values never get deleted

### ISSUE THREAD

**Issue by gkb999** [pydata/xarray#7871]
### What is your issue?

Hi team, 
This could be pretty basic, but I'm missing where I'm going wrong
My xarray dataset : 
``` python
<xarray.Dataset>
Dimensions:              (x: 171, y: 128, time: 3287, bnds: 2)
Coordinates:
  * x                    (x) float64 -5.344e+05 -5.281e+05 ... 5.281e+05
  * y                    (y) float64 -1.959e+06 -1.953e+06 ... -1.166e+06
  * time                 (time) datetime64[ns] 2013-01-01 ... 2021-12-31
Dimensions without coordinates: bnds
Data variables:
    polar_stereographic  int32 ...
    z                    (time, y, x) float32 nan nan nan nan ... nan nan nan
    x_bnds               (x, bnds) float64 ...
    time_bnds            (time, bnds) datetime64[ns] ...
Attributes:
    author:       University of Bremen, Gunnar Spreen [gunnar.spreen@uni-brem...
    Conventions:  CF-1.5
    GMT_version:  5.2.1 (r15220) [64-bit] [MP]
    history:      Mon Jan 21 19:54:59 2019: GDAL CreateCopy( /ssmi/www/htdocs...
    info:         AMSR2 sea ice concentration based on the ASI algorithm (Spr...
    title:        Produced by grdmath
    GDAL:         GDAL 2.1.3, released 2017/20/01
```
Converted to dataframe to drop "Nan" values
![image](https://github.com/pydata/xarray/assets/7091088/7863767d-74ac-4b83-9b57-49baf0f24e3e)

I used 
```python 
df = ds['z'].to_dataframe().dropna()
```
Looks fine now
![image](https://github.com/pydata/xarray/assets/7091088/2816369f-55da-4921-b8e1-0ba98d3518c4)

But, after saving it back to xarray
```python
ds = df.to_xarray()
```
the Nan values never dropped and can be seen.
![image](https://github.com/pydata/xarray/assets/7091088/9546f74d-33da-48fa-b307-a0aebe0fa8a7)

Where am I going wrong?

Also, I'm assuming dropna() would by default drop all nan's in all dimensions.
(Ref: 
1)https://www.digitalocean.com/community/tutorials/pandas-dropna-drop-null-na-values-from-dataframe
2) https://stackoverflow.com/questions/39128856/python-drop-row-if-two-columns-are-nan)

Also, if I'm trying to drop along column's,  
something like: 
```python
df2.dropna(subset=[1, 2], axis=1)
```
it rasies error.
Ref screenshot:
![image](https://github.com/pydata/xarray/assets/7091088/735e66bb-ee9b-4d52-a0da-6be92a6e687f)

Any help would be highly appreciated

**Comment by mathause** [comment]
What is the reason that you want to get rid of the nan values?

The reason they come back is that are needed to fill the grid again. The dataframe is 1D but the dataarray is 2D.

What you can try is to use `where`:

```python
da = ds['z']
da = da.where(da.isnull(), drop=True)
```
but it will only drop the values if the _entire_ row/ column is nan.

**Comment by gkb999** [comment]
Thanks alot for responding,
but, 

> ```python
> da = ds['z']
> da = da.where(da.isnull(), drop=True)
> ```
is for pciking nan values?
Because the data array has all 'nan' values 
![image](https://github.com/pydata/xarray/assets/7091088/d27b468a-bf29-442f-b03d-bf5701842e18)

when I plot: I get, 
![image](https://github.com/pydata/xarray/assets/7091088/748ab179-f377-4f19-a295-f46f958de1e8)

I need to use data that has no empty cells for further analysis.

**Comment by mathause** [comment]
Can you try `notnull` instead of `isnull` - I often get the boolean array wrong in `where`:

```python
da = ds['z']
da = da.where(da.notnull(), drop=True)
```

**Comment by gkb999** [comment]
> Can you try `notnull` instead of `isnull` - I often get the boolean array wrong in `where`:
> 
> ```python
> da = ds['z']
> da = da.where(da.notnull(), drop=True)
> ```

Yes, I did.
![image](https://github.com/pydata/xarray/assets/7091088/e7621150-402f-4d52-85d4-d780b232ef44)

**Comment by mathause** [comment]
Yes but there are less - so as mentioned it removes all columns/ rows with _only_ nans, if there is at least one non-nan value the row is kept.

What is the reason that you want to get rid of the nan values?

**Comment by gkb999** [comment]
Well, that does makes sense.
I want to calculate anomalies along x-y grids and I'm guessing the nan values are interfering with the results.
Also, I have another question which isn't regarding Nan's. if it is right here, I may proceed. (else tag/link to other places/forums relevant).
Assuming you must be knowing:
I reprojected my nc file from meters to degrees
Now, although the projection is right, the values of longitude aren't.
```python
x
(x)
float64
-179.2 -177.7 ... 177.7 179.2
array([-179.217367, -177.65215 , -176.086933, -174.521715, -172.956498,
       -171.391281, -169.826063, -168.260846, -166.695629, -165.130412,
       -163.565194, -161.999977, -160.43476 , -158.869542,  163.565218,
        165.130436,  166.695653,  168.26087 ,  169.826088,  171.391305,
        172.956522,  174.521739,  176.086957,  177.652174,  179.217391])
```
This is not how it is supposed to be:
It should fall with 160-200 longitudes (post wrapping 360)

Is there a way xarray can sort this automatically or do I need to manually reset the cordinates?

**Comment by mathause** [comment]
xarray handles nan values and ignores them per default - so you don't need to remove them. For example:
```python
import numpy as np
import xarray as xr

da = xr.DataArray([1, 2, 3, np.nan])
da.mean()
```
If you have precision problems - that might be because you have `float32` values. 

I don't know what goes wrong with your lon values - that is an issue in the reprojection. You could convert them to 0...360 by using 

```python

lon_dim = "x"
new_lon = np.mod(da[lon_dim], 360)
da = da.assign_coords(**{lon_dim: new_lon})
da.reindex(**{lon_dim : np.sort(da[lon_dim])})

```

**Comment by mathause** [comment]
Yes float64 should cause less imprecision. You can convert using `astype`:

```python
import numpy as np
import xarray as xr

da = xr.DataArray(np.array([1, 2], dtype=np.float32))

da = da.astype(float)
```

As for the other problems I think you are better of asking the people over at rioxarray. However, you should first gather all the steps you did to convert the data as code. This way it is easier to see what you are actually doing.

**Comment by gkb999** [comment]
> Yes float64 should cause less imprecision. You can convert using `astype`:
> 
> ```python
> import numpy as np
> import xarray as xr
> 
> da = xr.DataArray(np.array([1, 2], dtype=np.float32))
> 
> da = da.astype(float)
> ```
> 
> As for the other problems I think you are better of asking the people over at rioxarray. However, you should first gather all the steps you did to convert the data as code. This way it is easier to see what you are actually doing.

Thanks for getting back. I did post in rioxarray and yet, the last step I mentioned isn't successful there too.
I'll post the code maybe 8hrs from here(can reach out to my sys then). Thanks for all the helpful suggestions so far. Really helpful.

**Comment by mathause** [comment]
I am closing this. Feel free to re-open/ or open a new issue.
