### ISSUE TITLE
No `Xarray` conda package compatible with pandas>=2 for python 3.8

### ISSUE THREAD

**Issue by anmyachev** [pydata/xarray#7873]
### What is your issue?

Are there any plans to support this combination of packages?

**Comment by jhamman** [comment]
We dropped Python 3.8 support prior to the Pandas 2 release and have no plans to backport support at this time. 

xref: #7765

**Comment by anmyachev** [comment]
> We dropped Python 3.8 support prior to the Pandas 2 release and have no plans to backport support at this time.
> 
> xref: #7765

Thanks for the answer!
