### ISSUE TITLE
Reading .grib files with xarray

### ISSUE THREAD

**Issue by leamhowe** [pydata/xarray#7884]
### What happened?

![image](https://github.com/pydata/xarray/assets/48015835/89e5fe70-bd0b-4a58-a2d2-eedae59eee73)

### What did you expect to happen?

Be able to read in the file.

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('English_United Kingdom', '1252')
libhdf5: 1.10.6
libnetcdf: 4.8.1

xarray: 2023.5.0
pandas: 1.5.3
numpy: 1.24.3
scipy: None
netCDF4: 1.6.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: 1.3.5
dask: None
distributed: None
matplotlib: 3.7.1
cartopy: 0.21.1
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 67.8.0
pip: 23.0.1
conda: None
pytest: None
mypy: None
IPython: 8.12.0
sphinx: None

</details>

**Comment by keewis** [comment]
No, this should still work:
```sh
conda create -n test -c conda-forge xarray ipython python=3.11 cfgrib pooch
conda activate test
ipython
```
```python
import xarray as xr

xr.tutorial.open_dataset("era5-2mt-2019-03-uk.grib")
```
We somewhat recently dropped the builtin `cfgrib` engine in favor of the one provided by the `cfgrib` package (and that is also the reason why the example fails: `cfgrib` is not installed into the docs environment anymore, which is definitely an oversight).

Which version of `cfgrib` do you have? For reference, in the environment built with the command above I have `cfgrib=0.9.10.3`

**Comment by leamhowe** [comment]
The version of `cfgrib` i have is: `cfgrib=0.9.10.4`

I tried to update my own environment as you advised and have this error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File ~\Anaconda3\envs\doom_test\lib\site-packages\xarray\tutorial.py:151, in open_dataset(name, cache, cache_dir, engine, **kws)
    150 try:
--> 151     import cfgrib  # noqa
    152 except ImportError as e:

File ~\Anaconda3\envs\doom_test\lib\site-packages\cfgrib\__init__.py:20
     19 from .abc import Field, Fieldset, Index, MappingFieldset
---> 20 from .cfmessage import COMPUTED_KEYS
     21 from .dataset import (
     22     Dataset,
     23     DatasetBuildError,
   (...)
     27     open_from_index,
     28 )

File ~\Anaconda3\envs\doom_test\lib\site-packages\cfgrib\cfmessage.py:29
     27 import numpy as np
---> 29 from . import abc, messages
     31 LOG = logging.getLogger(__name__)

File ~\Anaconda3\envs\doom_test\lib\site-packages\cfgrib\messages.py:28
     27 import attr
---> 28 import eccodes  # type: ignore
     29 import numpy as np

File ~\Anaconda3\envs\doom_test\lib\site-packages\eccodes\__init__.py:13
      1 #
      2 # (C) Copyright 2017- ECMWF.
      3 #
   (...)
     10 #
     11 #
---> 13 from .eccodes import *  # noqa
     14 from .highlevel import *

File ~\Anaconda3\envs\doom_test\lib\site-packages\eccodes\eccodes.py:12
      1 #
      2 # (C) Copyright 2017- ECMWF.
      3 #
   (...)
     10 #
     11 #
---> 12 from gribapi import (
     13     CODES_PRODUCT_ANY,
     14     CODES_PRODUCT_BUFR,
     15     CODES_PRODUCT_GRIB,
     16     CODES_PRODUCT_GTS,
     17     CODES_PRODUCT_METAR,
     18 )
     19 from gribapi import GRIB_CHECK as CODES_CHECK

File ~\Anaconda3\envs\doom_test\lib\site-packages\gribapi\__init__.py:13
      1 #
      2 # (C) Copyright 2017- ECMWF.
      3 #
   (...)
     10 #
     11 #
---> 13 from .gribapi import *  # noqa
     14 from .gribapi import __version__, lib

File ~\Anaconda3\envs\doom_test\lib\site-packages\gribapi\gribapi.py:34
     32 import numpy as np
---> 34 from gribapi.errors import GribInternalError
     36 from . import errors

File ~\Anaconda3\envs\doom_test\lib\site-packages\gribapi\errors.py:16
     12 """
     13 Exception class hierarchy
     14 """
---> 16 from .bindings import ENC, ffi, lib
     19 class GribInternalError(Exception):

File ~\Anaconda3\envs\doom_test\lib\site-packages\gribapi\bindings.py:40
     38 ENC = "ascii"
---> 40 ffi = cffi.FFI()
     41 CDEF = pkgutil.get_data(__name__, "grib_api.h")

File ~\Anaconda3\envs\doom_test\lib\site-packages\cffi\api.py:48, in FFI.__init__(self, backend)
     45 if backend is None:
     46     # You need PyPy (>= 2.0 beta), or a CPython (>= 2.6) with
     47     # _cffi_backend.so compiled.
---> 48     import _cffi_backend as backend
     49     from . import __version__

ModuleNotFoundError: No module named '_cffi_backend'

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
Cell In[30], line 2
      1 import xarray as xr
----> 2 xr.tutorial.open_dataset("era5-2mt-2019-03-uk.grib")

File ~\Anaconda3\envs\doom_test\lib\site-packages\xarray\tutorial.py:153, in open_dataset(name, cache, cache_dir, engine, **kws)
    151                 import cfgrib  # noqa
    152             except ImportError as e:
--> 153                 raise ImportError(
    154                     "Reading this tutorial dataset requires the cfgrib package."
    155                 ) from e
    157     url = f"{base_url}/raw/{version}/{path.name}"
    159 # retrieve the file

ImportError: Reading this tutorial dataset requires the cfgrib package.
```

**Comment by keewis** [comment]
> No module named '_cffi_backend'

Does simply `import cfgrib` work for you? I suspect it doesn't, which would explain the error.

**Comment by dcherian** [comment]
Please ask over at the cfgrib repo. But it does look like a bad environment / bad install.
