### ISSUE TITLE
Time limitation (between years 1678 and 2262) restrictive to climate community

### ISSUE THREAD

**Issue by pwolfram** [pydata/xarray#789]
The restriction of

>    One unfortunate limitation of using datetime64[ns] is that it limits the native representation of dates to
>    those that fall between the years 1678 and 2262. When a netCDF file contains dates outside of these
>    bounds, dates will be returned as arrays of netcdftime.datetime objects.

is a potential roadblock inhibiting easy adoption of this library in the climate community.

**Comment by pwolfram** [comment]
@jhamman and @shoyer, do you know if more general support for times will be provided?

I would say this is a potential roadblock inhibiting easy adoption of this library within the climate community. For example, this is creating problems when we setup and analyze climate models (cc @akturner, @douglasjacobsen, @milenaveneziani). There are obvious work arounds, but they are hacks, e.g., I just add 1700 or some arbitrary year within my wrapper to MPAS at https://github.com/pwolfram/mpas_xarray_wrapper. However, this does not appear to be a viable long-term solution.

Does anyone have some advice on how to better deal with this problem?

**Comment by pwolfram** [comment]
See also https://github.com/pydata/xarray/issues/531 (cc @jsbj, @darothen, @jhamman); https://github.com/pydata/xarray/issues/521 (cc @rabernat, @jhamman)

It appears this is an issue with the numpy `datetime64` API (https://github.com/numpy/numpy/issues/6207).

**Comment by shoyer** [comment]
There are two issues here:

1. Support for years outside 1678-2262 -- blocked by pandas standardizing on nanosecond precision.
2. Support for custom calendars -- blocked by limitations of numpy's datetime64.

Unfortunately, I don't see easy fixes to either of these, though if I had to guess, adding support for other datetime precisions (perhaps only sub-second resolution) to pandas would be easier than fixing up NumPy's datetime64 itself (which is already pretty hacky).

**Comment by milenaveneziani** [comment]
Thank you, @pwolfram, for bringing this up. I just wanted to add that this limitation is important for analyzing so-called fixed-conditions climate model experiments, in which the model is run with fixed greenhouse gases conditions for a particular year (say, fixed levels of CO2 concentration representative of levels for the year 1850, for example). In these cases, time is simply measured with respect to start of simulation (year 0, or year 1) and each year is a no-leap year of 365 days.

**Comment by pwolfram** [comment]
Thank you very much @shoyer for your very fast reply.  If we fixed the issue in pandas (e.g., your 1) would that be sufficient to resolve the issue or do we also need to enhance `datetime64` also (e.g., your 2)?  What is your recommendation on the best way to proceed and is it even reasonable to do so?

**Comment by MaximilianR** [comment]
Periods can go back much further, depending on the precision you need:

```python
In [26]: pd.Period('1000', freq='D')
Out[26]: Period('1000-01-01', 'D')
```

**Comment by jhamman** [comment]
> This might make slightly more sense in a related but distinct project to xarray.

@shoyer - are you thinking `xarray` would fall back to a `CustomDatetimeIndex` for non-standard calendars?

I actually don't think it would be all that hard to do this.  @jswhit's [`netcdftime`](https://github.com/Unidata/netcdf4-python/blob/master/netcdftime/netcdftime.py) module is at least a good starting point. There's a lot to build on in `netcdftime` and `pandas.tseries.index`. I'd actually say this should be targeted at Pandas (probably as a side project) rather than `xarray`.  Ultimately, it would be nice to be able to move timeseries back and forth without any hassle. 

I'd be happy to help pull this together, although, I won't be able to make significant contributions until the summer. Is anyone chomping at the bit to work on something like this?

**Comment by brews** [comment]
Just curious, has anyone tried to open an issue in pandas for this?

**Comment by jhamman** [comment]
@brews - I think this issue (https://github.com/pydata/pandas/issues/7307) covers the main gist of what we're talking about here.

**Comment by spencerahill** [comment]
Pandas has created a poll on their mailing list about this issue...I encourage everybody to speak up there: https://groups.google.com/forum/#!topic/pydata/kk04maBGw1U

(Will blast this to xarray mailing list also)
