### ISSUE TITLE
`xarray.rolling_window` Converts `dims` Argument from Tuple to List Causing Issues for Cupy-Xarray

### ISSUE THREAD

**Issue by negin513** [pydata/xarray#7890]
### What is your issue?

Hello, 
I'm currently working on the development of cupy_xarray, and I've come across an issue with `xarray.rolling_window`. Specifically, it seems that the `dims` argument gets automatically converted to a list from a tuple.

While numpy.normalize_axis_tuple can handle lists, thereby not raising errors when using numpy-backed xarray objects, its cupy equivalent (cupy.core.internal._normalize_axis_indices) does not. When a list is passed, it raises the following error: 
```
File cupy/core/internal.pyx:424, in cupy.core.internal._normalize_axis_indices()
TypeError: 'list' object cannot be interpreted as an integer.
```

It seems the line that might fix this is L2487: 
https://github.com/pydata/xarray/blob/c9d89e2b51b6dfee34e371a9232024ec45cd2d9c/xarray/core/variable.py#L2487-L2494

For the time being, we've managed to devise a workaround in cupy, but I thought it would be worthwhile to bring this to your attention. 

Relevant Cupy PR: https://github.com/cupy/cupy/pull/7575
Contributor: @dcherian

**Comment by dcherian** [comment]
This seems like a real easy fix?
```
axis = tuple(self.get_axis_num(d) for d in dim)
```

**Comment by dcherian** [comment]
I think the only other one is dask, which *should* also work.

**Comment by headtr1ck** [comment]
@negin513 would you mind creating a PR for this?

**Comment by negin513** [comment]
@headtr1ck Thanks. I created the corresponding PR for this : https://github.com/pydata/xarray/pull/7938
