### ISSUE TITLE
metadata_key parameter for open_zarr

### ISSUE THREAD

**Issue by BGCMHou** [pydata/xarray#7897]
### What is your issue?

In zarr's [open_consolidated](https://zarr.readthedocs.io/en/stable/api/convenience.html#zarr.convenience.open_consolidated) function, there is a `metadata_key` parameter to specify the path. However, this parameter is inaccessible when using xarray's `open_zarr` function. 

Would it be possible to have `metadata_key` as a parameter in `open_zarr` or as a kwarg that can be passed to the open_consolidated?

**Comment by dcherian** [comment]
dupe of #3548
