### ISSUE TITLE
Test fail: AttributeError: module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by papoteur-mga** [pydata/xarray#7898]
### What happened?

I'm trying to package xarray for Mageia.
Since python-numpy has been updated to 1.24.3, tests fail.

### What did you expect to happen?

Test pass

### Minimal Complete Verifiable Example

```Python
Run pytest
```

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
/home/pterjan/rpmbuild/BUILD/xarray-2022.11.0/xarray/tests/test_rolling.py:234: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/pterjan/rpmbuild/BUILD/xarray-2022.11.0/xarray/core/rolling.py:155: in method
    return self._numpy_or_bottleneck_reduce(
/home/pterjan/rpmbuild/BUILD/xarray-2022.11.0/xarray/core/rolling.py:578: in _numpy_or_bottleneck_reduce
    return self._bottleneck_reduce(
/home/pterjan/rpmbuild/BUILD/xarray-2022.11.0/xarray/core/rolling.py:539: in _bottleneck_reduce
    values = func(
/usr/lib64/python3.10/site-packages/bottleneck/slow/move.py:49: in move_max
    return move_func(np.nanmax, a, window, min_count, axis=axis)
/usr/lib64/python3.10/site-packages/bottleneck/slow/move.py:150: in move_func
    idx = _mask(a, window, mc, axis)
/usr/lib64/python3.10/site-packages/bottleneck/slow/move.py:168: in _mask
    idx = np.empty(a.shape, dtype=np.bool)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

attr = 'bool'

    def __getattr__(attr):
        # Warn for expired attributes, and return a dummy function
        # that always raises an exception.
        import warnings
        try:
            msg = __expired_functions__[attr]
        except KeyError:
            pass
        else:
            warnings.warn(msg, DeprecationWarning, stacklevel=2)
    
            def _expired(*args, **kwds):
                raise RuntimeError(msg)
    
            return _expired
    
        # Emit warnings for deprecated attributes
        try:
            val, msg = __deprecated_attrs__[attr]
        except KeyError:
            pass
        else:
            warnings.warn(msg, DeprecationWarning, stacklevel=2)
            return val
    
        if attr in __future_scalars__:
            # And future warnings for those that will change, but also give
            # the AttributeError
            warnings.warn(
                f"In the future `np.{attr}` will be defined as the "
                "corresponding NumPy scalar.", FutureWarning, stacklevel=2)
    
        if attr in __former_attrs__:
>           raise AttributeError(__former_attrs__[attr])
E           AttributeError: module 'numpy' has no attribute 'bool'.
E           `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
E           The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E               https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

/usr/lib64/python3.10/site-packages/numpy/__init__.py:305: AttributeError
______ TestDataArrayRolling.test_rolling_reduce_nonnumeric[max-4-3-True] _______
```

### Environment

<details>

>>> xarray.show_versions()
/usr/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.11 (main, Apr 16 2023, 03:21:15) [GCC 12.2.1 20230415]
python-bits: 64
OS: Linux
OS-release: 6.3.5-desktop-1.mga9
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: ('fr_FR', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2022.11.0
pandas: 1.4.1
numpy: 1.24.2
scipy: 1.9.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: None                                                                                                                                                                                    
Nio: None                                                                                                                                                                                     
zarr: None                                                                                                                                                                                    
cftime: None                                                                                                                                                                                  
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: None
distributed: None
matplotlib: 3.6.2
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.5.0
pip: 23.0.1
conda: None
pytest: 7.2.1
IPython: None
sphinx: None

</details>

**Comment by papoteur-mga** [comment]
I have tried with 2023.5.0 for xarray, it fails in the same way.

**Comment by Illviljan** [comment]
And bottleneck? They have a 1.3.7 version out and it's in bottleneck the error occurs in.
