### ISSUE TITLE
`open_dataset` substantially slower with libnetcdf 4.9.2

### ISSUE THREAD

**Issue by w-k-jones** [pydata/xarray#7906]
### What is your issue?

Opening datasets is substantially slower with libnetcdf 4.9.2 than with 4.9.1. Oddly, loading netcdf files using the netCDF4 package directly is not affected by the change in libnetcdf version

See times below for loading 10 netcdf files with different package versions:

`xarray=2023.5.0`, `netcdf4=1.6.4`, `libnetcdf=4.9.2`:
xarray.open_dataset: 51.814434s
netCDF4.Dataset: 1.370544s

`xarray=2023.5.0`, `netcdf4=1.6.3`, `libnetcdf=4.9.2`:
xarray.open_dataset: 47.78837s
netCDF4.Dataset: 1.821116s

`xarray=2023.5.0`, `netcdf4=1.6.3`, `libnetcdf=4.9.1`:
xarray.open_dataset: 2.896161s
netCDF4.Dataset: 1.43984s

Script used to get loading times:
```
import pathlib
from datetime import datetime
import xarray as xr
from netCDF4 import Dataset

data_path = pathlib.Path('../data/GOES16')
files = list(data_path.rglob("*MCMIP*.nc"))[:10]

# Test xarray
start_time = datetime.now()
for file in files:
    _ = xr.open_dataset(file).CMI_C13.to_numpy()
print("xarray.open_dataset:", (datetime.now()-start_time).total_seconds())

# Test netCDF4
start_time = datetime.now()
for file in files:
    _ = Dataset(file)["CMI_C13"][:]
print("netCDF4.Dataset:", (datetime.now()-start_time).total_seconds())
```

**Comment by kmuehlbauer** [comment]
@w-k-jones Sorry for the delay here. 

As a first thing please check, if cf-decoding might be the culprit:

```python
xr.open_dataset(file, decode_cf=False)
```

We've come across reports of reduced performance which could be traced to problematic/non-standard time-units, which in turn are processed via cftime.

**Comment by kmuehlbauer** [comment]
I'm going to close this for now. Please feel free to reopen with additional information.
