### ISSUE TITLE
Incorrect error about conflicting sizes when resampling DataArray with underlying dask array data

### ISSUE THREAD

**Issue by kim366** [pydata/xarray#7922]
### What happened?

Hello,

While resampling data, I have encountered the following error:

```python
ValueError: conflicting sizes for dimension '__resample_dim__': length 25 on '__resample_dim__' and length 2 on {'__resample_dim__': <this-array>}
```
The first length refers to the number of generated buckets and the second length is the length of the input data array. As such, these are not at all expected to be equal. The error is thrown here: https://github.com/pydata/xarray/blob/276b6bf22fdd5d6abeb6236b8e3c63e63049d44a/xarray/core/variable.py#L3282-L3285.

This error occurs only in the specific conditions outlined in the MCVE. When one of the following is true, no error is encountered:
1. The time values fall into the same bucket, i.e., `time = np.array(['1970-01-01T00:00', '1970-01-01T00:30'], dtype=np.datetime64)` (although the result might be wrong; it is correct with the example data here)
2. The data is loaded in-memory, i.e., `data = np.zeros(2)`
3. `.reduce(da.max)` is used instead of `.max()`

It is also worth noting, that this error occurs in the `max` method rather than later at the actual `.compute()`.

### What did you expect to happen?

A result of `[ 0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,  0.]`. This result is given, as expected, when using in-memory data (case 2).

### Minimal Complete Verifiable Example

```Python
import numpy as np
import dask.array as da
import xarray

data = da.zeros(2)
time = np.array(['1970-01-01T00:00', '1970-01-02T00:00'], dtype=np.datetime64)

mcve = xarray.DataArray(data, coords={'time': time})
mcve.resample(time='1h').max()
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]
python-bits: 64
OS: Linux
OS-release: 4.18.0-425.3.1.el8.nci.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_AU.utf8
LANG: None
LOCALE: ('en_AU', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.8.1

xarray: 2023.4.2
pandas: 1.5.3
numpy: 1.23.5
scipy: 1.10.1
netCDF4: 1.6.0
pydap: installed
h5netcdf: 1.1.0
h5py: 3.8.0
Nio: None
zarr: 2.14.2
cftime: 1.6.2
nc_time_axis: 1.4.1
PseudoNetCDF: None
iris: 3.4.1
bottleneck: 1.3.7
dask: 2023.4.0
distributed: 2023.4.0
matplotlib: 3.5.3
cartopy: 0.21.0
seaborn: 0.12.2
numbagg: None
fsspec: 2023.4.0
cupy: 12.0.0
pint: 0.19.2
sparse: 0.14.0
flox: 0.6.10
numpy_groupies: 0.9.20
setuptools: 65.6.3
pip: 23.1.1
conda: 23.1.0
pytest: 7.3.1
mypy: None
IPython: 8.12.0
sphinx: 4.5.0

</details>

**Comment by dcherian** [comment]
Can you update `flox` to `0.7.2` and try again please?

**Comment by kim366** [comment]
Thank you. Updating fixed the issue
