### ISSUE TITLE
Deprecated function used in Tutorial for rasterio data parsing

### ISSUE THREAD

**Issue by paradx** [pydata/xarray#7927]
### What is your issue?

in the documentation tutorial section 
https://xarray.pydata.org/en/v2023.05.0/examples/visualization_gallery.html#Parsing-rasterio-geocoordinates 
the xarray.open_rasterio function is used, that is deprecated since v0.20.0. 
This causes the Jupiter notebook to throw an error message. 

It might be nice to either remove the example or adapt it to provide a way to parse rasterio data without the function in question.

**Comment by TomNicholas** [comment]
Hi @paradx , thanks for raising this.

The fix would be to use `open_dataset(file, engine='rasterio')` and ensure rioxarray is installed. (see https://github.com/pydata/xarray/issues/8003) Would be you be interested in submitting a small PR to fix this?

**Comment by kmuehlbauer** [comment]
Solved in #7671.
