### ISSUE TITLE
unstack() broken for large Dask Arrays

### ISSUE THREAD

**Issue by ska-incom** [pydata/xarray#7931]
### What happened?

When the underlying data is a large Dask Array, unstacking a MultiIndex is not possible. I've mimicked the issue by using a small `array.chunk-size` setting in Dask. 

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import dask.array as da
import pandas as pd
import dask


dask.config.set(
    **{"array.slicing.split_large_chunks": True, "array.chunk-size": "1KiB"}
)

(
    xr.DataArray(
        da.random.random((25, 100, 100)),
        dims=["time", "y", "x"],
        coords={
            "time": pd.date_range("2020-01-01", "2020-01-02", freq="1H"),
            "y": range(100),
            "x": range(100),
        },
    )
    .assign_coords(
        hour=lambda x: x.time.to_index() - x.time.to_index().floor("D"),
        day=lambda x: x.time.to_index().floor("D"),
    )
    .set_index({"time": ("day", "hour")})
    .unstack("time")
)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
/home/ska/libs/dask/dask/array/core.py:4830: PerformanceWarning: Increasing number of chunks by factor of 20
  result = blockwise(
Traceback (most recent call last):
  File "/home/ska/Meteo.Analytics/meteo_analytics/nowcasting/notebooks/xarray_unstack_bug.py", line 30, in <module>
    .unstack("time")
  File "/home/ska/libs/xarray/xarray/core/dataarray.py", line 2832, in unstack
    ds = self._to_temp_dataset().unstack(dim, fill_value, sparse)
  File "/home/ska/libs/xarray/xarray/core/dataset.py", line 4983, in unstack
    result = result._unstack_full_reindex(
  File "/home/ska/libs/xarray/xarray/core/dataset.py", line 4878, in _unstack_full_reindex
    variables[name] = var.unstack({dim: new_dim_sizes})
  File "/home/ska/libs/xarray/xarray/core/variable.py", line 1930, in unstack
    result = result._unstack_once_full(dims, old_dim)
  File "/home/ska/libs/xarray/xarray/core/variable.py", line 1822, in _unstack_once_full
    new_data = reordered.data.reshape(new_shape)
  File "/home/ska/libs/dask/dask/array/core.py", line 2218, in reshape
    return reshape(self, shape, merge_chunks=merge_chunks, limit=limit)
  File "/home/ska/libs/dask/dask/array/reshape.py", line 285, in reshape
    outchunks = normalize_chunks(
  File "/home/ska/libs/dask/dask/array/core.py", line 3094, in normalize_chunks
    chunks = auto_chunks(chunks, shape, limit, dtype, previous_chunks)
  File "/home/ska/libs/dask/dask/array/core.py", line 3217, in auto_chunks
    result = {a: np.median(previous_chunks[a]) for a in autos}
  File "/home/ska/libs/dask/dask/array/core.py", line 3217, in <dictcomp>
    result = {a: np.median(previous_chunks[a]) for a in autos}
IndexError: tuple index out of range
```

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-144-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2023.5.0
pandas: 2.0.2
numpy: 1.25.0
scipy: 1.10.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: 2.15.0
cftime: None
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.6.0+11.g499f4055d
distributed: 2023.6.0+20.g953f79a4
matplotlib: 3.7.1
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.6.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 67.7.2
pip: 23.1.2
conda: None
pytest: 7.3.2
mypy: None
IPython: 8.14.0
sphinx: None
</details>

**Comment by dcherian** [comment]
> new_data = reordered.data.reshape(new_shape)

This is the core dask-array step. Can you try to make a dask only reproducible example?

**Comment by ska-incom** [comment]
> This is the core dask-array step. Can you try to make a dask only reproducible example?

Yes, this is the exact computation that it fails on internally in the example above

`da.random.random((100, 100, 48)).rechunk((5, 5, 6)).reshape((100, 100, 2, 24))`

**Comment by dcherian** [comment]
And does that fail? If so, can you file an issue over at the dask then?

**Comment by ska-incom** [comment]
It fails. I'll file a Dask issue.

**Comment by max-sixty** [comment]
Closing as upstream issue
