### ISSUE TITLE
engine='cfgrib' no longer an option in xr.open_dataset() but works anyway

### ISSUE THREAD

**Issue by parsellsx** [pydata/xarray#7945]
### What is your issue?

Looking at the documentation for [xr.open_dataset()](https://docs.xarray.dev/en/stable/generated/xarray.open_dataset.html), the "engine" argument to that function is listed as accepting one of 7 different engines (or None), but the "cfgrib" engine is not among them. Looking at older versions of the documentation, I see that "cfgrib" was delisted starting with v2023.04.0 (it's still present in [v2023.03.0](https://docs.xarray.dev/en/v2023.03.0/generated/xarray.open_dataset.html)). 

In what I think is a related issue, [this tutorial](https://docs.xarray.dev/en/stable/examples/ERA5-GRIB-example.html) on reading in ERA5 GRIB files with the "engine='cfgrib'" option on xr.load_dataset() gives a ValueError in documentation versions starting with [v2023.04.0](https://docs.xarray.dev/en/v2023.04.0/examples/ERA5-GRIB-example.html) and going through [v2023.05.0](https://docs.xarray.dev/en/v2023.05.0/examples/ERA5-GRIB-example.html) and ['stable'](https://docs.xarray.dev/en/stable/examples/ERA5-GRIB-example.html) due to the unrecognized engine 'cfgrib', although it seems to have been fixed for [v2023.06.0](https://docs.xarray.dev/en/v2023.06.0/examples/ERA5-GRIB-example.html) and ['latest'](https://docs.xarray.dev/en/latest/examples/ERA5-GRIB-example.html). 

Given both of the above, I was surprised to find that using xr.open_dataset() on a GRIB file with engine='cfgrib' does work for me using xarray v2023.05.0. To me it seems that the documentation for xr.open_dataset() should be edited to include the 'cfgrib' option again, but I'd like to get an opinion from someone more familiar with xarray.

**Comment by dcherian** [comment]
Thanks for the report @parsellsx !

If you have `cfgrib` installed, it automatically registers `engine="cfgrib"` with xarray. That's why your code works.

The docs errors are because we didn't have `cfgrib` in the doc environment back then. 

I've kicked the `stable` version build. That *should* work once its done.

**Comment by parsellsx** [comment]
Thanks for the reply! I see the `stable` version of the tutorial works now. 

I also see now that the xr.open_dataset() documentation says you can use one of the 7 listed engines _or_ an "installed backend," so I guess `cfgrib` would be considered an installed backend in my case, and that's why it's not one of the explicitly listed engines?

**Comment by dcherian** [comment]
Yeah that's right
