### ISSUE TITLE
Better chunk manager error

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#7962]
### What happened?

I just ran in to this error in an environment without dask.
```
TypeError: Could not find a Chunk Manager which recognises type <class 'dask.array.core.Array'>
```

I think we could easily recommend the user to install a package that provides `dask` by looking at `type(array).__name__`.  This would make the message a lot friendlier

**Comment by TomNicholas** [comment]
How was an instance of `dask.array.core.Array` even created if you were in an environment without dask?

I agree that message could be clearer though - opened #7963.

**Comment by dcherian** [comment]
> How was an instance of dask.array.core.Array even created if you were in an environment without dask?

Yeah i realized that out 2 minutes later. Not sure what happened, may be bad editable install.

**Comment by TomNicholas** [comment]
Actually wait it's possible this might be a real bug - if `xarray.core.pycompat.is_duck_dask_array` returns False for an instance of `dask.array.core.Array`. We shouldn't see that type though, so if you can't reproduce it easily it's probably a bad install instead though.

**Comment by dcherian** [comment]
Closing as probable bad install
