### ISSUE TITLE
Clean up colormap code?

### ISSUE THREAD

**Issue by johnomotani** [pydata/xarray#7978]
In fixing some bugs with color bars (https://github.com/pydata/xarray/pull/3601), we had to do some clunky workarounds because of limitations of matplotlib's API for modifying colormaps - this prompted a matplotlib issue https://github.com/matplotlib/matplotlib/issues/16296#issuecomment-1629755861. That issue has now been closed, and apparently the limitations are now fixed, so it should be possible to tidy up some of the colorbar code (at least at some point, once the oldest xarray-supported matplotlib includes the new API).

I have no time to look into this myself, but opening this issue to flag the new matplotlib features in case someone is looking at refactoring colorbar or colormap code.

**Comment by headtr1ck** [comment]
See https://github.com/pydata/xarray/issues/7976

**Comment by kmuehlbauer** [comment]
Looks like this is resolved?
