### ISSUE TITLE
Existing chunks not being respected on to_zarr()

### ISSUE THREAD

**Issue by hansmohrmann** [pydata/xarray#7987]
### What is your issue?

Hi folks, I'm not sure what I'm doing wrong here. Context: I have a dataset, adding a coordinate variable with some specified chunking, and then that chunking is reset when writing to_zarr() and opening from disk. Even if I call unify_chunks() before writing or explicitly set the `preferred_chunks` encoding, the chunks get reset upon write. I have managed to force the chunks by explicitly setting `ds.end_date.encoding['chunks']= (2,)` before writing (note that before this, _no encoding was set_, so this isn't the old issue of previous encoding overwriting the dask chunks). It took a while to find this, and I don't understand why the existing behavior disregards the existing chunks on single-dimension variables or coordinates. The issue is that with this default behavior, the dataset written to disk has inconsistent dimensions on read, throws an error, and requires a call to unify_chunks() to be usable. 

Reproducer below:

versions: 
xarray 2023.6.0
dask 2023.6.0
zarr 2.14.2

```
import pandas as pd
import numpy as np
import xarray as xr
from datetime import datetime
import dask.array as da

from pandas.tseries.offsets import MonthEnd

# create toy dataset
dates = [datetime(2021, 1, 1), datetime(2021, 2, 1), datetime(2021, 3, 1), datetime(2021, 4, 1)]
ds = xr.Dataset(
    data_vars=dict(
        tas=(["time", "lat", "lon",], 
            np.array([300]) * np.ones((len(dates), 4, 4)),
        ),
    ),
    coords=dict(
        time=dates,
        lat=np.array([10, 11, 12, 13]),
        lon=np.array([20, 21, 22, 23]),
    ),
)

# chunk dataset
ds = ds.chunk(chunks={"lat": 2, "lon": 2, 'time': 2})

# add end date coordinate
time_df = pd.DataFrame({"time": list(ds['time'].values)})
time_df['end_date'] = time_df['time'] + MonthEnd(0)
ds = ds.assign_coords(
    end_date=("time", da.from_array(time_df['end_date'].values)))

print("---data before unify chunks--- \n", ds.end_date.data)
ds = ds.unify_chunks() # surely you'll respect my chunking
print("---data before writing to s3--- \n", ds.end_date.data)
ds.time.encoding['preferred_chunks']= {'time': 2} # please use this chunking?
ds.end_date.encoding['preferred_chunks']= {'time': 2} # pretty please use this chunking?


# write data to s3
data_path = "/tmp/mydata.zarr"
ds.to_zarr(data_path, mode='w')

# read data back from s3
ds_check = xr.open_zarr(data_path)

print("---data after writing to disk and reading back in--- \n", ds_check.end_date.data)
```

output from code above:
```
---data before unify chunks--- 
 dask.array<array, shape=(4,), dtype=datetime64[ns], chunksize=(4,), chunktype=numpy.ndarray>
---data before writing to s3--- 
 dask.array<rechunk-merge, shape=(4,), dtype=datetime64[ns], chunksize=(2,), chunktype=numpy.ndarray>
---data after writing to disk and reading back in--- 
 dask.array<open_dataset-end_date, shape=(4,), dtype=datetime64[ns], chunksize=(4,), chunktype=numpy.ndarray>
 ```

**Comment by rabernat** [comment]
Thanks for opening this detailed issue.

The problem is that `preferred_chunks` is not used when writing. This is a hint used when opening datasets only, mostly a [backend detail](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html#preferred-chunk-sizes).

As described in the [docs on specifying chunks in a Zarr store](https://docs.xarray.dev/en/stable/user-guide/io.html#specifying-chunks-in-a-zarr-store), the chunks must be specified via the `chunks` in encoding. The value needs to be an int or tuple of ints. 

Can you confirm that this fixes your problem?
```diff
- ds.time.encoding['preferred_chunks']= {'time': 2} # please use this chunking?
- ds.end_date.encoding['preferred_chunks']= {'time': 2} # pretty please use this chunking?
+ ds.time.encoding['chunks']= 2
+ ds.end_date.encoding['chunks']= 2
```

I'm curious where you got the idea to use `preferred_chunks` to specify this. Do you see a way we could improve the documentation or docstrings to clarify things?
