### ISSUE TITLE
Stable docs build not showing latest changes after release

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#7996]
### What happened?

I released xarray version v2023.07.0 last night, but I'm not seeing changes to the documentation reflected in the [`https://docs.xarray.dev/en/stable/`](https://docs.xarray.dev/en/stable/) build. (In particular the Internals section now should have an entire extra page on wrapping chunked arrays.) I can however see the newest additions on [`https://docs.xarray.dev/en/latest/`](https://docs.xarray.dev/en/latest/) build. Is that how it's supposed to work?

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

</details>

**Comment by keewis** [comment]
there appears to have been a random timeout / memory leak (not great, but it happens occasionally), which caused the `stable` build to fail. I requested a new build, hopefully that should fix it.

**Comment by TomNicholas** [comment]
Thanks both. Seems to be [working now.](https://docs.xarray.dev/en/stable/internals/chunked-arrays.html)
