### ISSUE TITLE
np.cumproduct deprecated

### ISSUE THREAD

**Issue by quantsnus** [pydata/xarray#8013]
### What is your issue?

Since numpy version 1.25.0 `np.cumproduct` is deprecated in favor of `np.cumprod`.

The coordinates to_index() method still uses it 
https://github.com/pydata/xarray/blob/971be103d6376d6572d1f12d32526f12f07ae2c7/xarray/core/coordinates.py#L144
which results in an unecessary DeprecationWarning.

**Comment by dcherian** [comment]
Thanks @quantsnus This should be a really easy Pull Request. Do you have time to fix it?

We have contributing instructions here: https://docs.xarray.dev/en/stable/contributing.html

**Comment by TomNicholas** [comment]
In particular see the section of the contributing guide on [explaining how to add a deprecation warning](https://docs.xarray.dev/en/stable/contributing.html#backwards-compatibility)

**Comment by keewis** [comment]
no need for a deprecation cycle since the `cumproduct` call is internal

**Comment by quantsnus** [comment]
> Thanks @quantsnus This should be a really easy Pull Request. Do you have time to fix it?

I'll give it try. Will be my first contribution, but for a one-line change I guess it won't be too difficult.
