### ISSUE TITLE
Different result for `@` and `xr.dot` with multiple matrices

### ISSUE THREAD

**Issue by cgahr** [pydata/xarray#8024]
### What happened?

I compute both products
```
da0 @ da1 @ da2 @ da3,
xr.dot(da0, da1, da2, da3, optimize=True)
```
which should have the same result. This is not the case, and I don't know why.

I was unable to create a MWE reproducing the issue with randomly generate matrices, so I attached the matrices that I used. 

### Minimal Complete Verifiable Example
Zip file containing the matrices:
[product.zip](https://github.com/pydata/xarray/files/12181675/product.zip)

```Python
import xarray as xr

ds = xr.open_dataset('product.h5')

da0 = ds['da0']
da1 = ds['da1']
da2 = ds['da2']
da3 = ds['da3']

# 2 factors: no error
xr.testing.assert_allclose(
    da0 @ da1,
    xr.dot(da0, da1, optimize=True)
)

# 3 factors: no error
xr.testing.assert_allclose(
    da0 @ da1 @ da2,
    xr.dot(da0, da1, da2, optimize=True)
)

# 4 factors: error
xr.testing.assert_allclose(
    da0 @ da1 @ da2 @ da3,
    xr.dot(da0, da1, da2, da3, optimize=True)
)
```

### MVCE confirmation

- [x] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [x] Complete example — the example is self-contained, including all data and the text of any traceback.
- [x] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [x] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 4.12.14-122.162-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.0
libnetcdf: None

xarray: 2023.6.0
pandas: 1.5.3
numpy: 1.25.0
scipy: 1.10.1
netCDF4: None
pydap: None
h5netcdf: 1.2.0
h5py: 3.8.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.4.1
distributed: 2023.4.1
matplotlib: 3.7.1
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.4.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 67.7.2
pip: 23.1.2
conda: None
pytest: 7.4.0
mypy: 1.4.1
IPython: 8.13.2
sphinx: None

</details>

**Comment by dcherian** [comment]
[einsum_path](https://numpy.org/devdocs/reference/generated/numpy.einsum_path.html) will tell you how the calculation is being run. There will be floating-point differences that result from the order of execution. Again, we just dispatch to `np.einsum` so we can't do much here.
