### ISSUE TITLE
non-deterministic ordering within "coordinates" attribute written by .to_netcdf

### ISSUE THREAD

**Issue by itcarroll** [pydata/xarray#8026]
### What is your issue?

Under the assumption that deterministic output is preferred whenever feasible, I'd like to point out that the variable names written into "coordinates" attributes with `.to_netcdf` are not ordered deterministically. For pipelines that depend on file hashes to validate dependencies, this can be a real headache.

Consider the dataset `xarray.Dataset({"x": ((), 0)}, coords={"a": 0, "b": 0})`. The NetCDF file XArray writes will include either:
```
variables:
	int64 x ;
		x:coordinates = "a b" ;
	int64 a ;
	int64 b ;
```
or
```
variables:
	int64 x ;
		x:coordinates = "b a" ;
	int64 a ;
	int64 b ;
```

My review of [`_encode_coordinates`](https://github.com/pydata/xarray/blob/52f5cf1fc521891008c4c968cee0b389211481c0/xarray/conventions.py#L631) leads me to think the behavior results from collecting names in a `set`. I'd be happy to offer a PR to make the coordinates attribute deterministic. I am not aware of a CF convention regarding any ordering, but would research and follow if it exists. If not, then I would probably `sort` at [L701](https://github.com/pydata/xarray/blob/52f5cf1fc521891008c4c968cee0b389211481c0/xarray/conventions.py#L701) and [L722](https://github.com/pydata/xarray/blob/52f5cf1fc521891008c4c968cee0b389211481c0/xarray/conventions.py#L722).

**Comment by dcherian** [comment]
Your proposal sounds good to me. A PR would be welcome!

**Comment by trexfeathers** [comment]
By coincidence I was just looking at this corner of the Iris code. Here is how we achieve ordering ([link](https://github.com/SciTools/iris/blob/3c1b3e6993ba1283b5630ea24ee450d2bd7f246f/lib/iris/fileformats/netcdf/saver.py#L989-L991)):

```python
            for element in sorted(
                coordlike_elements, key=lambda element: element.name()
            ):
```
