### ISSUE TITLE
Unable to reference variable

### ISSUE THREAD

**Issue by JoyMonteiro** [pydata/xarray#803]
Hello,

I was trying to use xarray to access the MERRA-2 monthly dataset. This dataset provides nc4 files, one for each month, with multiple analyzed variables (U,V,T, etc.,) in each file.

if I open one file and try to access the zonal wind (U) as 
```python
       data = xarray.open_dataset('/data/MERRA2/MERRA2_100.instM_3d_ana_Np.198001.nc4')
       data = data.U
```
This works just fine.

However, if I use 
```python
data = data.T
```
I get back the entire dataset, i.e, I then have data.T.T, and data.T.T.T etc.,
I can open a single file using netCDF4, and the values seem ok. 

This seems to happen only with the temperature (T) field. all other fields seem to
behave ok.

Any ideas as to what is happening?

TIA,
Joy

**Comment by shoyer** [comment]
xarray uses the `.T` attribute as an abbreviation for `.transpose()` (like numpy). You'll need to use `data['T']` to access the temperature variable.

**Comment by JoyMonteiro** [comment]
Yes, that makes sense. quite the corner case! works perfectly now, thanks again.
