### ISSUE TITLE
Compute multiple dask backed arrays at once

### ISSUE THREAD

**Issue by jcrist** [pydata/xarray#804]
In dask, a user can compute multiple arrays in a single scheduler run using the `dask.compute` function:

``` python
>>> a_computed, b_computed = dask.compute(a, b)
```

This is nice for when `a` and `b` might share intermediates. The same can be done currently in xarray if `a` and `b` are first put into a dataset:

``` python
>>> both = xr.Dataset(dict(a=a, b=b))
>>> both.load()    # Compute all the arrays in a single pass
```

This is fine, but it might also be nice to be able to do this without first putting everything into a dataset. I'm not sure what a good api is here, as xarray objects mutate when computed. Perhaps just adding an `xr.compute(*args)` function that fully realizes all dask backed variables.

``` python
>>> xr.compute(a, b)    # a and b now contain numpy arrays, not dask arrays
```

**Comment by shoyer** [comment]
It would be nice to be able to use `dask.compute()` for this, by defining a duck type system for dask objects such that xarray objects can participate. (xref https://github.com/dask/dask/issues/700)

> I'm not sure what a good api is here, as xarray objects mutate when computed.

Yeah, this is somewhat unfortunate, but convenient (though somewhat obsolete with dask's cachey). Perhaps adding a dedicated `.compute()` method that does not mutate would be a good idea.

**Comment by jcrist** [comment]
I'm fine with the duck typing, and could make that work fairly easily. The mutation is a bit trickier though. I see two good options here for what `b = dask.compute(a)` would do with `a` being an xarray object:

1. `b` is a new object with the computation performed, `a` still contains a dask array (uncomputed).
2. `b` is the same object as `a`, and the internals of `a` are mutated to contain evaluated data.

I'm slightly partial to option 2, as it seems to mesh more with how xarray currently uses dask. Thoughts?

**Comment by shoyer** [comment]
I would lean towards keeping `compute` a pure function. That seems more straightforward to implement with duck typing in dask, anyways. I guess we could go either way, though.

**Comment by jhamman** [comment]
I believe this should have been close by  #1674. Anyone object or am I missing something?

**Comment by shoyer** [comment]
agreed, this is fixed now by `dask.compute()`
