### ISSUE TITLE
pd.Period can't be used as a 1-element coord

### ISSUE THREAD

**Issue by khaeru** [pydata/xarray#805]
With xarray 0.7.2, following [this basic example from the docs](http://xarray.pydata.org/en/stable/data-structures.html#creating-a-dataset), but with a modification in the last line to use `pd.Period` instead of `pd.Timestamp`:

``` python
import numpy as np
import xarray as xr

temp = 15 + 8 * np.random.randn(2, 2, 3)
precip = 10 * np.random.rand(2, 2, 3)
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]

ds = xr.Dataset({'temperature': (['x', 'y', 'time'],  temp),
                 'precipitation': (['x', 'y', 'time'], precip)},
                 coords={'lon': (['x', 'y'], lon),
                         'lat': (['x', 'y'], lat),
                         'time': pd.date_range('2014-09-06', periods=3),
                         'reference_time': pd.Period('2014')})
```

This raises:

```
ValueError: dimensions ('reference_time',) must have the same length as the number of data dimensions, ndim=0
```

I noticed (#645) that there are other issues stemming from pandas' PeriodIndex & company, so if this is not a straightforward fix I will understand!

**Comment by jhamman** [comment]
It doesn't really seem like `reference_time` is a "coordinate" variable. Being a scalar, you are not going to use it as a coordinate in the same sense as lat/lon/time.  Nevertheless, your example works if  you cast the `Period` to a DataArray first:

```Python
ds = xr.Dataset({'temperature': (['x', 'y', 'time'],  temp),
                 'precipitation': (['x', 'y', 'time'], precip)},
                 coords={'lon': (['x', 'y'], lon),
                         'lat': (['x', 'y'], lat),
                         'time': pd.date_range('2014-09-06', periods=3),
                         'reference_time': xr.DataArray(pd.Period('2014'))})
```

**Comment by shoyer** [comment]
Thanks for the bug report -- this should definitely work. I'll take a look.

**Comment by khaeru** [comment]
@jhamman — you're right. In truth, I was working with some more complex code using a PeriodIndex and getting errors I couldn't decipher, so I pulled those lines from the docs and played with them to try to understand what was happening. I don't know why it's that way in the docs…maybe because `ds['reference_time']` or `ds.reference_time` is more concise than `ds.attrs['reference_time']`?

@shoyer — thanks!

**Comment by MaximilianR** [comment]
This now works, although as an object array rather than PI. Which is probably OK:


```python
In [6]: ds
Out[6]:
<xarray.Dataset>
Dimensions:         (time: 3, x: 2, y: 2)
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  object 2014
  * x               (x) int64 0 1
  * y               (y) int64 0 1
Data variables:
    temperature     (x, y, time) float64 12.29 8.305 10.63 16.6 2.823 16.29 ...
    precipitation   (x, y, time) float64 4.541 3.618 3.336 2.332 7.987 4.197 ...

In [7]: ds.reference_time
Out[7]:
<xarray.DataArray 'reference_time' ()>
array(Period('2014', 'A-DEC'), dtype=object)
Coordinates:
    reference_time  object 2014
```

@shoyer - to close?

**Comment by shoyer** [comment]
Yep, looks like this works now. There's no period dtype in NumPy, so object dtype is the best we can do.
