### ISSUE TITLE
data/coords alias

### ISSUE THREAD

**Issue by LecrisUT** [pydata/xarray#8054]
It would be nice to allow in dataset/dataarray to alias a coordinate/data. E.g. `ds['time'] == ds['t']`. This would be beneficial for midleware libraries to create more natural interface.

Implementation wise, this can be restricted to the indexers of the dataset/dataarray, and internally save a dictionary of aliases.

**Comment by LecrisUT** [comment]
Hmm, indeed that is quite neat. I don't like that it displays as a separate data so the fact that they are aliased is not obvious. But indeed I think this can be handled externally. Implementation wise that would mean to make a separate wrapper class for `attrs` and `dataset` and `dataarray`, unless, do you know of a method to inject/alter class definitions upon a module load?

**Comment by benbovy** [comment]
>  Implementation wise that would mean to make a separate wrapper class for attrs and dataset and dataarray, unless, do you know of a method to inject/alter class definitions upon a module load?

I was rather thinking about just using a dictionary of name aliases like

```python
names = {"time": "time", "t": "time"}

ds[names["time"]].identical(ds[names["t"]])
```

For a bit more convenience, you could create a [Dataset accessor](https://docs.xarray.dev/en/stable/internals/extending-xarray.html) to get the original item from the alias name:

```python
aliases = {"t": "time"}


@xr.register_dataset_accessor("aliases")
class AliasesAccessor:
    def __init__(self, xarray_obj):
        self._obj = xarray_obj
        self._aliases = aliases
    
    def __getitem__(self, key):
        return self._obj[self._aliases[key]]
```

```python
ds = xr.Dataset({"time": [1, 2, 3]})

ds.aliases["t"].identical(ds["time"])
# True
```

**Comment by LecrisUT** [comment]
Thanks, that's really interesting. I'll think about how to design along those lines

**Comment by keewis** [comment]
note that a big part of [cf-xarray](https://github.com/xarray-contrib/cf-xarray) is basically that: a way to look up aliases using standardized metadata (ie. metadata following the CF conventions)

**Comment by dcherian** [comment]
:+1: cf-xarray seems like the way to go
