### ISSUE TITLE
Documentation of `Dataset.count()` is ambiguous

### ISSUE THREAD

**Issue by Articoking** [pydata/xarray#8055]
### What is your issue?

Hello everyone!

I've noticed that the documentation for `Dataset.count` and `DataArray.count` is a little unclear with respect to what it actually does. In my experience, it's not immediately obvious when looking at [this site](https://docs.xarray.dev/en/latest/generated/xarray.DataArray.count.html#xarray.DataArray.count) whether zero values are counted or not.

The given example does not contain a 0 value that would clarify this, and what is worse is that the "see also" section points to `np.count` and to `dask.array.count` which do not exist. The closest NumPy equivalent is `np.count_nonzero`, which has a different behavior to the xarray `count` method. The xarray count is actually equivalent to Pandas DataFrame.count, which count all non-NA values including 0.

I would take a shot at writing a clearer docstring but I'm not sure how to do that using the `generate_aggregations.py` file...

**Comment by headtr1ck** [comment]
Thanks for the issue, many aggregations could indeed use some extra explanation.

Concerning the dead links, that's really not good. Probably we should look into letting sphinx report them.

**Comment by keewis** [comment]
that's what `nitpicky` is for, but we have a *lot* of these warnings the last time I checked, so we'd need to clean them up first (or mark them as ignored, some of them are descriptions where there should be type descriptions, which in many cases we inherit from `pandas` / `matplotlib` / `numpy`).
