### ISSUE TITLE
.mfdataset fail to open a kerchunked zarr file from an object-store bucket 

### ISSUE THREAD

**Issue by pl-marasco** [pydata/xarray#8065]
### What happened?

Trying to open a kerchunk .json through the open_mfdata a ValueError is raised.

### What did you expect to happen?

should be open a Dataset as described here below:
```
<xarray.Dataset>
Dimensions:  (lat: 15680, lon: 40320, time: 36)
Coordinates:
  * lat      (lat) float64 80.0 79.99 79.98 79.97 ... -59.97 -59.98 -59.99
  * lon      (lon) float64 -180.0 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0
  * time     (time) float64 nan 1.0 2.0 3.0 4.0 5.0 ... 31.0 32.0 33.0 34.0 35.0
Data variables:
    crs      object ...
    max      (time, lat, lon) float32 dask.array<chunksize=(1, 1207, 3102), meta=np.ndarray>
    mean     (time, lat, lon) float32 dask.array<chunksize=(1, 1207, 3102), meta=np.ndarray>
    median   (time, lat, lon) float32 dask.array<chunksize=(1, 1207, 3102), meta=np.ndarray>
    min      (time, lat, lon) float32 dask.array<chunksize=(1, 1207, 3102), meta=np.ndarray>
    nobs     (time, lat, lon) float32 dask.array<chunksize=(1, 1207, 3102), meta=np.ndarray>
    stdev    (time, lat, lon) float32 dask.array<chunksize=(1, 1207, 3102), meta=np.ndarray>
Attributes: (12/19)
    Conventions:          CF-1.6
    archive_facility:     VITO
    copyright:            Copernicus Service information 2021
    history:              2021-03-01 - Processing line NDVI LTS
    identifier:           urn:cgls:global:ndvi_stats_all:NDVI-LTS_1999-2019-0...
    institution:          VITO NV
    ...                   ...
    references:           https://land.copernicus.eu/global/products/ndvi
    sensor:               VEGETATION-1, VEGETATION-2, VEGETATION
    source:               Derived from EO satellite imagery
    time_coverage_end:    2019-12-31T23:59:59Z
    time_coverage_start:  1999-01-01T00:00:00Z
    title:                Normalized Difference Vegetation Index: Long Term S...
```
### Minimal Complete Verifiable Example

```python
import xarray as xr
catalogue="https://object-store.cloud.muni.cz/swift/v1/foss4g-catalogue/c_gls_NDVI-LTS_1999-2019.json"
LTS = xr.open_mfdataset(
    "reference://", engine="zarr",
    backend_kwargs={
        "storage_options": {
            "fo":catalogue
                    },
        "consolidated": False
    }
)
```

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
`ValueError: Cannot specify both fs and storage_options`
```

### Anything else we need to know?

Seems to be related to zarr's version: if tested with <= 2.12 it works but with the latest versions  > 2.12 it doesn't. 

### Environment

<details>
xarray version 2023.7.0
zarr >2.12 
</details>

**Comment by keewis** [comment]
cc @martindurant

**Comment by dcherian** [comment]
Interestingly, using `open_dataset` works and is more appropriate here.

**Comment by martindurant** [comment]
Indeed, this looks like only one dataset, so mf is the wrong abstraction - and is not typically used with zarr I think. In the top-level function it is apparently creating a filesystem and passing it, but then passing the storage_options through anywhere. I'm not sure if this is happening in xarray, zarr or fsspec!

**Comment by pl-marasco** [comment]
As @dcherian suggested the best solution is to use the `open_dataset` as there is no need to use mf. 
It is still fascinating that, up to 2.12, was working without any problem; anyhow there is no need to investigate more.
