### ISSUE TITLE
.to_zarr() error when using ABSStore

### ISSUE THREAD

**Issue by Baptiste-geosys** [pydata/xarray#8078]
### What is your issue?

Hello !

I'm currently trying to push a .zarr file to an Azure Blog Storage.
Following the documentation, I'm using the zarr.ABSStorage() to create a store connected to my blob storage.

The problem happens when I use the .to_zarr() method to push my xarray to my azure blob storage as a zarr.
From what I can tell, it uploads most of the files correctly except the .zmetadata and the errror I get is the following : 

```python
2023-08-17 17:02:37,131 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://*****/datacube/test?restype=REDACTED&comp=REDACTED&sp=REDACTED&st=REDACTED&se=REDACTED&spr=REDACTED&sv=REDACTED&sr=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.17.0 Python/3.11.4 (Windows-10-10.0.22621-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1a5f3696-3d0f-11ee-b045-00a55443e918'
No body was attached to the request

2023-08-17 17:02:37,281 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 400
Response headers:
    'Content-Length': '244'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8311e39b-f01e-0026-031b-d16988000000'
    'Date': 'Thu, 17 Aug 2023 15:02:36 GMT'
azure.core.exceptions.HttpResponseError: The requested URI does not represent any resource on the server.
RequestId:8311e39b-f01e-0026-031b-d16988000000
Time:2023-08-17T15:02:37.1719044Z
ErrorCode:InvalidUri
```
From what I can see, the only difference in the request from the others is the presence of 2 new parameters : "restype=REDACTED&comp=REDACTED". Removing them turns it back into a 404 and not a 400.

Here's my snippet of code containing my .to_zarr() call.

`container_client = azure.storage.blob.ContainerClient(account_url="https://****/",container_name="test")`
`store = zarr.ABSStore(client=container_client)`
`datacube.to_zarr(store=store,consolidated=True)`

and for the packages versions : 
zarr : 2.16.0
xarray : 2023.6.0
azure-storage-blob : 12.17.0

**Comment by dcherian** [comment]
cc @martindurant @TomAugspurger

**Comment by martindurant** [comment]
I don't know about ABSStore, but you might want to dry with fsspec's abfs: implementation ( https://github.com/fsspec/adlfs/ )

**Comment by Baptiste-geosys** [comment]
> Either `ABSStore` or `adlfs` should work. Can you confirm that your storage container exists?
> 
> ```
> >>> container_client.exists()
> ```
> 
> Edit: oh sorry, I just saw this line in your report:
> 
> > except the .zmetadata
> 
> I'm not sure why that would be failing... I'm not sure if this would help, but can you try specifying a `prefix` in the call to `zarr.ABSStore`?

I've tried adding the prefix field to the zarr.ABSStore but I get the same error, just with the prefix parameter added to the request.

2023-08-18 10:14:19,455 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://*****/datacube/test?restype=REDACTED&comp=REDACTED&prefix=REDACTED&sp=REDACTED&st=REDACTED&se=REDACTED&spr=REDACTED&sv=REDACTED&sr=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.17.0 Python/3.11.4 (Windows-10-10.0.22621-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3b083d31-3d9f-11ee-b6f7-00a55443e918'
No body was attached to the request

2023-08-18 10:14:19,590 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 400
Response headers:
    'Content-Length': '244'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '799199cd-c01e-00d9-33ab-d15915000000'
    'Date': 'Fri, 18 Aug 2023 08:14:19 GMT
azure.core.exceptions.HttpResponseError: The requested URI does not represent any resource on the server.
RequestId:799199cd-c01e-00d9-33ab-d15915000000
Time:2023-08-18T08:14:19.5279484Z
ErrorCode:InvalidUri

**Comment by Baptiste-geosys** [comment]
> I don't know about ABSStore, but you might want to dry with fsspec's abfs: implementation ( https://github.com/fsspec/adlfs/ )

Would it be possible to have a bit more details on how to use the fsspec as the store for the to_zarr() method please ?

**Comment by Baptiste-geosys** [comment]
Hello ! 

I've searched more informations about the Adlfs package and found out how to use it as the store for the to_zarr() method.
Works great ! No more error, and the zarr is complete.

    

    fs = adlfs.AzureBlobFileSystem(account_name="****",credential="****")
    
    zarr_path = f"/datacube/{order_id}/{feature_id}.zarr"
    
    store = fs.get_mapper(zarr_path)

    datacube.to_zarr(store=store,consolidated=True)`

Thank you for your help.
