### ISSUE TITLE
bottleneck version

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#808]
Not sure if this is possible to specify in the `setup.py` as bottleneck is not required. However, if bottleneck is used it should probably be in version 1.0. For version 0.8.0 I get the following error:

`>>> move_mean() got an unexpected keyword argument 'min_count'`

Feel free to close.

**Comment by jhamman** [comment]
Setuptools has the concept of `extras_require` but the application doesn't really work with our optional import of `bottleneck` ([ref](http://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)). I think what may work here is to check the `bottleneck` version on import and raise a warning if the version is not sufficient for all the functionality we use it for.

So [here](https://github.com/pydata/xarray/blob/master/xarray/core/ops.py#L20) may look something like:

```Python
try:
    import bottleneck as bn
    has_bottleneck = True
    if bn.__version__ < 1.0:
        warnings.warn('insufficient bottleneck version...')
except ImportError:
    # use numpy methods instead
    bn = np
    has_bottleneck = False
``` 

Alternatively, we could raise an error or fall back to use the numpy methods.

**Comment by shoyer** [comment]
At the least, we should probably list this requirement on the installation page.

**Comment by jhamman** [comment]
see #1190 for a belated fix for this issue.
