### ISSUE TITLE
xarray version on windows

### ISSUE THREAD

**Issue by harshitha1201** [pydata/xarray#8087]
### What happened?

(xarray-tests) C:\Users\harsh\xarray>python
>>> import xarray
>>> xarray.__version__
'0.1.dev4684+geceec5f'

### What did you expect to happen?

The actual version of xarray is 2023. something, but when doing on Windows this is the output shown **everytime**

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

</details>

**Comment by andersy005** [comment]
@harshitha1201, how did you install it? 

if you are installing it from a git clone, can you try 

```bash
git fetch --all
```

followed by re-installing it 

```bash
python -m pip install -e . 
python -c "import xarray as xr; xr.show_versions()"
```

**Comment by harshitha1201** [comment]
> @harshitha1201, how did you install it?
> 
> if you are installing it from a git clone, can you try
> 
> ```shell
> git fetch --all
> ```
> 
> followed by re-installing it
> 
> ```shell
> python -m pip install -e . 
> python -c "import xarray as xr; xr.show_versions()"
> ```

[traceback.txt](https://github.com/pydata/xarray/files/12385331/traceback.txt)

**Comment by kmuehlbauer** [comment]
Looks like no tags are fetched. Try fetching with `--tags` added.

**Comment by harshitha1201** [comment]
> Looks like no tags are fetched. Try fetching with `--tags` added.

(xarray-docs) C:\Users\harsh\xarray>git fetch --tags

(xarray-docs) C:\Users\harsh\xarray>python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray
>>> xarray.__version__
'0.1.dev4684+geceec5f'

**Comment by harshitha1201** [comment]
I'm able to see the entire code in my code editor. The only thing is the version is shown wrong.

**Comment by harshitha1201** [comment]
Error while doing ``make html``
[Uploading traceback.txt…]()
