### ISSUE TITLE
Opening netcdf dataset from OpenDAP server

### ISSUE THREAD

**Issue by GrumpyNounours** [pydata/xarray#809]
Hi,

First of, congrats and thank you guys for this amazing work. Xarray is wicked!

I am in the process of using your package in one of the suite of tool I am developing (i.e. [PySeidon](https://github.com/GrumpyNounours/PySeidon)). Unfortunately I am running into the following issue while opening netcdf datasets from our OpenDAP server.

Here is what's going on:
When I run
```python
import xarray as xr
remote_data = xr.open_dataset('http://ecoii.acadiau.ca/thredds/dodsC/ecoii/test/FVCOM3D_dngrid_BF_20130619_20130621.nc', decode_times=False, drop_variables=['siglay', 'siglev'])
```

I get the following error:
`RuntimeError: NetCDF: Unknown file format`

Yet when I run
```python
from pydap.client import open_url
remote_data = open_url('http://ecoii.acadiau.ca/thredds/dodsC/ecoii/test/FVCOM3D_dngrid_BF_20130619_20130621.nc')
```

It works like a charm.

Could you please tell me what I'm doing wrong?

Cheers and thanks again for Xarray,

**Comment by jhamman** [comment]
Can you let us know what version of `xarray`, `netCDF4`, and `pydap` you are running?  I just ran your example and it loaded without any errors.

**Comment by GrumpyNounours** [comment]
Here is the info I get with `pip show whatever-module | grep Version`
xarray:
Metadata-Version: 2.0
Version: 0.7.2

netCDF4
Metadata-Version: 1.1
Version: 1.0.5

pydap:
Metadata-Version: 1.1
Version: 3.1.1

**Comment by GrumpyNounours** [comment]
I updated the packages and it works now.

Thanks

**Comment by shoyer** [comment]
Note that by default, xarray using netCDF4 for opendap. To switch to pydap, add `engine='pydap'` to the open_dataset call.
