### ISSUE TITLE
additional option for ```dataset.plot.quiver``` : provide control over the arrows density through the native ```xarray``` quiver API

### ISSUE THREAD

**Issue by jerabaul29** [pydata/xarray#8093]
### Is your feature request related to a problem?

When plotting a dataset using ```.plot.quiver```, I usually end up having far too many, too small arrows. Looking both at the documentation of the xarray quiver API ( https://xarray.pydata.org/en/v0.17.0/generated/xarray.Dataset.plot.quiver.html ), and at the documentation of the matplotlib quiver API (that is "reachable" from the xarray quiver API through the **kwargs forwarding: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html ), I see ways to modify the arrows aspect and plotting properties, but not their densities. Adding ways to control it would be neat. This could be done at the xarray level (with the advantage that more "context knowledge" is available for being able to do it well), or at the matplotlib level (not sure if this is as well suited).

### Describe the solution you'd like

I would like to have some options to control the density of my quiver plot arrows directly from the xarray quiver function api. Something like (but open to better suggestions), ```skip=(skip_x, skip_y)``` to say how many of the actual data points to plot, or something like ```density=density``` to tell how much arrow density I would like on the figure.

### Describe alternatives you've considered

After looking into this in a bit of details, if I did not miss anything, it looks like the only option is to directly quiver plot with matplotlib, slicing / skipping by hand the input data: see for example https://stackoverflow.com/questions/33576572/python-quiver-options and similar options. This defeats the point of being able to call ```dataset.plot.quiver``` of course, as this forces doing quite a bit of manual operation and falling back to getting the data into numpy arrays and plotting them directly in matplotlib.

I also tried to check if it was possible to directly downsample the xarray dataset and then plot it, by calling a few ```reshaping``` (https://docs.xarray.dev/en/stable/user-guide/reshaping.html) commands first, i.e. something like:

```
my_df.sel(time=time_to_plot).coarsen(rlat=100, rlon=100).plot.quiver(x="longitude", y="latitude", u="data_u", v="data_v")
```

but that results in an error:

```
AttributeError: 'DatasetCoarsen' object has no attribute 'plot'
```

**Comment by dcherian** [comment]
Either use `coarsen.mean` to calculate the mean in 100 point windows
```
my_df.sel(time=time_to_plot).coarsen(rlat=100, rlon=100)
```

or use `isel` to "decimate" the data

```
my_df.sel(time=time_to_plot).isel(rlat=slice(None, None, 100), rlon=slice(None, None, 100))
```

**Comment by jerabaul29** [comment]
Many thanks @dcherian for the help :) .

---

Actually, I had tried the ```coarsen``` approach, though it failed. See the initial comment, repeated here:

```
xr_df_wam4_latloncoords.sel(time=time_to_plot).coarsen(rlat=100, rlon=100).plot.quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
plt.show()
```

gives

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-8d0c21beef6b> in <module>
----> 1 xr_df_wam4_latloncoords.sel(time=time_to_plot).coarsen(rlat=100, rlon=100).plot.quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
      2 plt.show()

AttributeError: 'DatasetCoarsen' object has no attribute 'plot'
```

and 

```
xr_df_wam4_latloncoords.sel(time=time_to_plot).coarsen(rlat=100, rlon=100).quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
plt.show()
```

gives:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-39ee8133b6f8> in <module>
----> 1 xr_df_wam4_latloncoords.sel(time=time_to_plot).coarsen(rlat=100, rlon=100).quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
      2 plt.show()

AttributeError: 'DatasetCoarsen' object has no attribute 'quiver'
```

Is this expected, or is this a bug?

---

but the ```isel``` way does work well, i.e. this works:

```
xr_df_wam4_latloncoords.sel(time=time_to_plot).isel(rlat=slice(None, None, 100), rlon=slice(None, None, 100)).plot.quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
plt.show()
```

---

So this can close the feature request (many thanks @dcherian for the pointers), though I wonder if the ```coarsen``` method I had tried and you had pointed to, should be reported as failing / a bug and asked fixed somehow? Or any other way to make this work with coarsen? :)

**Comment by keewis** [comment]
did you try this?
```python
xr_df_wam4_latloncoords.sel(time=time_to_plot).coarsen(rlat=100, rlon=100).mean().plot.quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
```
(note the `.mean()`)

**Comment by jerabaul29** [comment]
@keewis thanks for the recommendation, closer, but still no luck:

```
xr_df_wam4_latloncoords.sel(time=time_to_plot).coarsen(rlat=100, rlon=100).mean().plot.quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
plt.show()
```

gives:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-8a6d0c536a3a> in <module>
----> 1 xr_df_wam4_latloncoords.sel(time=time_to_plot).coarsen(rlat=100, rlon=100).mean().plot.quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
      2 plt.show()

~/.local/lib/python3.8/site-packages/xarray/core/rolling.py in wrapped_func(self, keep_attrs, **kwargs)
   1104             reduced = {}
   1105             for key, da in self.obj.data_vars.items():
-> 1106                 reduced[key] = da.variable.coarsen(
   1107                     self.windows,
   1108                     func,

~/.local/lib/python3.8/site-packages/xarray/core/variable.py in coarsen(self, windows, func, boundary, side, keep_attrs, **kwargs)
   2455             return self._replace(attrs=_attrs)
   2456 
-> 2457         reshaped, axes = self.coarsen_reshape(windows, boundary, side)
   2458         if isinstance(func, str):
   2459             name = func

~/.local/lib/python3.8/site-packages/xarray/core/variable.py in coarsen_reshape(self, windows, boundary, side)
   2491             if boundary[d] == "exact":
   2492                 if n * window != size:
-> 2493                     raise ValueError(
   2494                         f"Could not coarsen a dimension of size {size} with "
   2495                         f"window {window} and boundary='exact'. Try a different 'boundary' option."

ValueError: Could not coarsen a dimension of size 1026 with window 100 and boundary='exact'. Try a different 'boundary' option.
```

**Comment by jerabaul29** [comment]
(I can check if I can share the full notebook, and post it online if so :) that should just take a few minutes :) .

**Comment by jerabaul29** [comment]
Here it is, if you want to "play around" with the exact same example (should be fully reproducible):

https://github.com/jerabaul29/public_bug_reports/blob/main/xarray/2023_08_22/illustration_situation_map_coarsen_quiver_issue.ipynb

See cell 20.

**Comment by keewis** [comment]
the array is not evenly divisible by 100, so we cannot use the default `boundary="exact"`. Instead, we have to choose either `trim` (remove excess length) or `pad` (pad the array to full length). For example:
```python
xr_df_wam4_latloncoords.sel(time=time_to_plot).coarsen(rlat=100, rlon=100, boundary="pad").mean().plot.quiver(x="longitude", y="latitude", u="thq_swell_u", v="thq_swell_v")
```

**Comment by jerabaul29** [comment]
Ahh, thanks, it does work now :) . Notebook example updated at: https://github.com/jerabaul29/public_bug_reports/blob/main/xarray/2023_08_22/illustration_situation_map_coarsen_quiver_issue.ipynb .

Question: this is quite a lot of steps to chain. Hopefully this issue / discussion will come up when people will look for how to "reduce density of quiver arrows when plotting in xarray", but do you think we should also document this / provide this as an easy to find example somehow? :) I think this is a quite common use case.

Apart from "how to document", ready to close to me - many thanks for the amazing help again :) .
