### ISSUE TITLE
Errors when saving PyObject coordinates

### ISSUE THREAD

**Issue by wkrasnicki** [pydata/xarray#8096]
### What happened?

Hi, I'm trying to create a `DataArray` with coordinates that are tuples and potentionally even more dimensional objects. The way I did it is to create an empty `numpy` array with `dtype=object` and then insert my tuples inside. This doesn't throw an error when creating a `DataArray` (as opposed to using a 2D ndarray or a list of lists). However, when trying to save it to `zarr` or `netcdf`. I get an error saying `ValueError: setting an array element with a sequence`

### What did you expect to happen?

I want to be able to save and load such coordinates without errors. Maybe there is a cleaner way to do it than the object dtype ndarray?

### Minimal Complete Verifiable Example

```Python
n = 5
x = np.empty(n, dtype=object)
for i in range(n):
    x[i] = (i, i)
xr.DataArray(np.arange(n), dims=("x"), coords={"x": x}).to_zarr("test")
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
File c:\Users\Wiktor\AppData\Local\pypoetry\Cache\virtualenvs\spin1-JGuolXDk-py3.11\Lib\site-packages\xarray\core\dataarray.py:4014, in DataArray.to_netcdf(self, path, mode, format, group, engine, encoding, unlimited_dims, compute, invalid_netcdf)
   4010 else:
   4011     # No problems with the name - so we're fine!
   4012     dataset = self.to_dataset()
-> 4014 return to_netcdf(  # type: ignore  # mypy cannot resolve the overloads:(
   4015     dataset,
   4016     path,
   4017     mode=mode,
   4018     format=format,
   4019     group=group,
   4020     engine=engine,
   4021     encoding=encoding,
   4022     unlimited_dims=unlimited_dims,
...
    101 result = np.empty(data.shape, dtype)
--> 102 result[...] = data
    103 return result

ValueError: setting an array element with a sequence.
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('Polish_Poland', '1250')
libhdf5: None
libnetcdf: None

xarray: 2023.8.0
pandas: 2.0.3
numpy: 1.25.2
scipy: 1.11.2
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: 2.16.0
cftime: None
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.7.2
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 68.0.0
pip: 23.2.1
conda: None
pytest: None
mypy: None
IPython: 8.14.0
sphinx: 7.1.2

</details>

**Comment by keewis** [comment]
this is basically telling you that it doesn't know how to serialize those arrays (even though the error message itself is not really helpful).

Is there a reason why you can't just create a new dimension for these? So instead of a 1D array of 2-tuples you'd get a 2D array with a second dimension of size 2 (if you absolutely need the tuples, you could also encode to 2D manually before writing to disk: `arr_with_tuples.pipe(encode_tuples).to_zarr(...)`).

If this doesn't help, can you provide a bit more information about what you're trying to encode?

**Comment by wkrasnicki** [comment]
Here is my use case:
I want to make a wrapper for others in my lab to perform parametric measurements (scans over multiple parameter configurations). To set it up, I accept a dictionary of parameters that would later be passed as Xarray coordinates inside of my wrapper. The reason I want multidimensional coordinates is that there are cases where we want to use parameter pairs, so insted of measuring a whole grid (waste of time and memory), we want to scan specific pairs that could be passed as multidimensional coordinates.

Now I'm not that focused on having tuples, I just gave an example. Any iterable will do and I can settle for one, but none of them work

**Comment by wkrasnicki** [comment]
I've managed to find a working solution. Instead of using generic PyObjects, I used structured arrays like so:

```
n = 5
x = np.empty(n, dtype=[("", "f8"), ("", "f8")])
for i in range(n):
    x[i] = (i, i)
xr.DataArray(np.arange(n), dims=("x"), coords={"x": x}).to_zarr("test")
```
