### ISSUE TITLE
Plotting accessor error for datasets with Dimension name matches coordinate names

### ISSUE THREAD

**Issue by blaylockbk** [pydata/xarray#8106]
### What happened?

I am working with NetCDF files produced from the [Model Evaluation Tools (MET)](https://[dtcenter.org](https://dtcenter.org/community-code/model-evaluation-tools-met)/community-code/model-evaluation-tools-met).

This feature in xarray v2023.8.0 

> allows reading of datasets where a dimension name is associated with a multidimensional variable

lets me read the file where the dimension names `lat` and `lon` match the coordinate names `lat` `lon` (see https://github.com/dtcenter/MET/issues/1246). This is wonderful! Thank you for this 🎉🙌🏻

```python
import urllib
import xarray as xr

# download a sample MET file
urllib.request.urlretrieve(
    "https://github.com/dtcenter/MET/raw/main_v11.1/data/poly/NCEP_masks/WEST_mask.nc",
    "WEST_mask.nc",
)

# open MET file
ds = xr.open_dataset(
    "WEST_mask.nc",
    engine="netcdf4",
)
ds
```
![image](https://github.com/pydata/xarray/assets/6249613/01b7bdf2-7c99-4a80-b994-418770113b82)

However, one issue I've run into is that the plotting accessor doesn't seem to work for this case

```python
ds.WEST.plot()

OUT:
ValueError: coordinate 'lat' is a DataArray dimension, but it has shape (110, 147) rather than expected shape 110 matching the dimension size
```

To overcome this, I had to rename the dims

```python
ds.rename_dims({"lat": "y", "lon": "x"}).WEST.plot()
```
![image](https://github.com/pydata/xarray/assets/6249613/5d95dcb1-390a-42be-b03e-ad6cb102aa50)

### What did you expect to happen?

I expected the plot accessor to work without needing to rename the dimensions.

### Minimal Complete Verifiable Example

```Python
import urllib
import xarray as xr

# download a sample MET file
urllib.request.urlretrieve(
    "https://github.com/dtcenter/MET/raw/main_v11.1/data/poly/NCEP_masks/WEST_mask.nc",
    "WEST_mask.nc",
)

ds = xr.open_dataset(
    "WEST_mask.nc",
    engine="netcdf4",
)
ds.WEST.plot()
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.53.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.1

xarray: 2023.8.0
pandas: 2.0.3
numpy: 1.25.2
scipy: 1.11.2
netCDF4: 1.6.3
pydap: None
h5netcdf: 1.2.0
h5py: 3.8.0
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.8.1
distributed: 2023.8.1
matplotlib: 3.7.2
cartopy: 0.22.0
seaborn: 0.12.2
numbagg: None
fsspec: 2023.6.0
cupy: None
pint: 0.22
sparse: None
flox: None
numpy_groupies: None
setuptools: 68.1.2
pip: 23.2.1
conda: None
pytest: 7.4.0
mypy: None
IPython: 8.7.0
sphinx: 4.5.0
/p/home/blaylock/miniconda3/envs/flight/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

</details>

**Comment by dcherian** [comment]
Thanks  looks like I only tested Variable creation and not DataArray.

See #8126. This capability is new  and mostly untested. It would help a lot if you could try some analysis with #8126 installed and let us  know how it goes.

**Comment by blaylockbk** [comment]
Thanks @dcherian! #8126 worked for me in the example I shared in the initial posting and also for my other MET output files.

Of course, my initial example was a poor sample, because the 'lon' coordinates cross over the prime meridian 😂

```python
import urllib
import xarray as xr

print("xarray version:", xr.__version__)

# download a sample MET file
urllib.request.urlretrieve(
    "https://github.com/dtcenter/MET/raw/main_v11.1/data/poly/NCEP_masks/WEST_mask.nc",
    "WEST_mask.nc",
)

# open MET file
ds = xr.open_dataset(
    "WEST_mask.nc",
    engine="netcdf4",
)
ds.WEST.plot()
```
> xarray version: 0.10.1.dev2530+gba555427
![image](https://github.com/pydata/xarray/assets/6249613/5a6106f8-a8fd-4e8e-989b-93e6742109c1)

So, had to use Cartopy anyways to plot this one right...

```python
import cartopy.crs as ccrs

ax = plt.axes(projection=ccrs.PlateCarree(central_longitude=-100))
ax.pcolormesh(ds.lon, ds.lat, ds.WEST, transform=ccrs.PlateCarree())
ax.coastlines()
```
![image](https://github.com/pydata/xarray/assets/6249613/234336f0-7b43-48fc-aede-692937245396)

But for my other MET output files, this now produces the expected result...

(This image is data from the ECMWF-open-data run through some of MET's tools)
```python
ds = xr.open_dataset("path/to/my/MET/file.nc")
ds["OBS_VGRD_P500_FULL"].plot()
```
![image](https://github.com/pydata/xarray/assets/6249613/0ca21dbf-5e21-4108-a78d-0b3971df29b7)

**Comment by dcherian** [comment]
Great, are you able to do all the analytical calculations you want without errors?
