### ISSUE TITLE
No-download mode needed for build

### ISSUE THREAD

**Issue by amckinstry** [pydata/xarray#8119]
### What is your issue?

I'm Debian maintainer for xarray.

https://tracker.debian.org/pkg/python-xarray

Debian/Ubuntu builds packages offline, from a frozen tarball (or possibly a small <5 number tarballs).
xarray requires external objects for both building documentation and testing (we can do testing on our own CI/CD pipelines).
Recent releases use pooch to download/cache test objects. We need a method of stating where the cache is (/home not an option -- that is directed to /non-existant on our build systems).

Can this be implemented, or how do you suggest we proceed?

Best regards
Alastair McKinstry

**Comment by keewis** [comment]
we use [`pooch.os_cache`](https://www.fatiando.org/pooch/latest/api/generated/pooch.os_cache.html#pooch.os_cache) to determine the cache directory, which on linux will make use of the `XDG_CACHE_HOME` environment variable. If you set `XDG_CACHE_HOME` such that `$XDG_CACHE_HOME/xarray_tutorial_data` contains the data files, `pooch` should not try to connect to the internet. The [default filenames](https://www.fatiando.org/pooch/latest/api/generated/pooch.retrieve.html#pooch.retrieve) appear to consist of a MD5 hash of the url plus the filename part of the url:
```python
url = "https://github.com/pydata/xarray-data/air_temperature.nc"
local_filename = "-".join([hash(url, algorithm="md5"), url.rsplit("/", 1)[1]])
```
(`hash` is fictional)

**Comment by keewis** [comment]
@amckinstry, did this resolve your issue? Can we close this?

**Comment by kmuehlbauer** [comment]
@amckinstry Please reopen, if this is still an issue.
