### ISSUE TITLE
failing tests with pandas  2.1

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#8125]
### What happened?

See  https://github.com/pydata/xarray/pull/8101

```
FAILED xarray/tests/test_missing.py::test_interpolate_pd_compat - ValueError: 'fill_value' is not a valid keyword for DataFrame.interpolate
FAILED xarray/tests/test_missing.py::test_interpolate_pd_compat_non_uniform_index - ValueError: 'fill_value' is not a valid keyword for DataFrame.interpolate
```

and this doctest
```
FAILED xarray/core/dataarray.py::xarray.core.dataarray.DataArray.to_unstacked_dataset
```
@pydata/xarray can someone take a look please?

**Comment by kmuehlbauer** [comment]
> ```
> FAILED xarray/tests/test_missing.py::test_interpolate_pd_compat - ValueError: 'fill_value' is not a valid keyword for DataFrame.interpolate
> FAILED xarray/tests/test_missing.py::test_interpolate_pd_compat_non_uniform_index - ValueError: 'fill_value' is not a valid keyword for DataFrame.interpolate
> ```

``fill_value`` - kwarg was removed upstream and raises error now -> https://github.com/pandas-dev/pandas/pull/53962

**Comment by kmuehlbauer** [comment]
> FAILED xarray/core/dataarray.py::xarray.core.dataarray.DataArray.to_unstacked_dataset

The doctest works for me locally, investigating package differences in the environment now. I

**Comment by mathause** [comment]
I think the doctest failure is unrelated to the removal of `fill_value`. I think this is pandas avoidint the cast of int to float when the nan value is added. The cheap solution is to convert the ints to floats

```diff
-         ...     coords=[("x", ["a", "b"]), ("y", [0, 1, 2])], 
+         ...     coords=[("x", ["a", "b"]), ("y", [0., 1, 2])],
```

in

https://github.com/pydata/xarray/blob/1043a9e13574e859ec08d19425341b2e359d2802/xarray/core/dataarray.py#L2893

**Comment by kmuehlbauer** [comment]
I`ve opened https://github.com/pandas-dev/pandas/issues/54920 upstream for the `fill_value`-issue.

**Comment by kmuehlbauer** [comment]
Upstream is already working on a fix for the fill_value-issue: https://github.com/pandas-dev/pandas/pull/54927

**Comment by kmuehlbauer** [comment]
Reopening until doc-test is fixed.

**Comment by benbovy** [comment]
There are also two pandas-related warnings when building the docs, which cause a "failure" for PR builds on RTD:

```
/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/8142/lib/python3.10/site-packages/pandas/core/indexes/base.py:docstring of pandas.core.indexes.base.Index.join:14: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/8142/lib/python3.10/site-packages/pandas/core/indexes/base.py:docstring of pandas.core.indexes.base.Index.join:15: WARNING: Inline literal start-string without end-string.
```

Not sure how to (temporarily) fix those, though.

**Comment by max-sixty** [comment]
> Reopening until doc-test is fixed.

Thanks (sorry this was an auto-close by GH, I hadn't meant to have it closed)

**Comment by kmuehlbauer** [comment]
No worries @max-sixty, that just happens. It would be great, if we could fine grain closing issues. :-)

**Comment by kmuehlbauer** [comment]
remaining things tracked in #8146
