### ISSUE TITLE
Can't Open GRIB file in Google CoLab

### ISSUE THREAD

**Issue by scottthomaswx** [pydata/xarray#8132]
### What is your issue?

I am attempting to open a GRIB2 file in google colab to plot meteorological data. I can't use the engines of  scipy/h5netcfd/gini/store as its the wrong file type and CFGRIB and PYNIO don't work. How am I supposed to open grib files in xarray in this environment?

**Comment by kmuehlbauer** [comment]
@scottthomaswx Thanks for the report. Please provide more details on what exactly you tried and additional information (follow the BUG-report template). It would also help, if you could share the file in question.

Did you report the issue to https://github.com/ecmwf/cfgrib/? If the file can be opened with recent `cfgrib` it should work for xarray too.

**Comment by scottthomaswx** [comment]
I actually figured it our using chatgpt of all things. I was missing this line

"!apt-get install -y libeccodes0"

Thanks for your response!
