### ISSUE TITLE
assign_coords changed its behaviour from v2023.07.0 to v2023.08.0

### ISSUE THREAD

**Issue by enekomartinmartinez** [pydata/xarray#8150]
### What happened?

assign_coords changed its behaviour in v2023.08.0 now, when trying to assign an existing coord, it doesn't do anything...

I was using it to reorder some xarray.DataArrays, keeping the coordinate names, f.e.:

```python
import xarray as xr
a = xr.DataArray([1, 2, 3], {'dim': ['A', 'B', 'C']})
new_order = [1, 0, 2]
a[new_order].assign_coords(a.coords)
```

returns
```
<xarray.DataArray (dim: 3)>
array([2, 1, 3])
Coordinates:
  * dim      (dim) <U1 'B' 'A' 'C'
```
I also tried to use a copy of the original coords `a[new_order].assign_coords(a.coords.copy())`, but it didn't work.

The behaviour is confusing and may lead to wrong results.

### What did you expect to happen?

The same code in version v2023.07.0 returned the coordinates as defined and only changed the position of the values:
```
<xarray.DataArray (dim: 3)>
array([2, 1, 3])
Coordinates:
  * dim      (dim) <U1 'A' 'B' 'C'
```

It also works properly passing a dictionary instead of the coords object, `a[new_order].assign_coords({'dim': ['A', 'B', 'C']})`.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
a = xr.DataArray([1, 2, 3], {'dim': ['A', 'B', 'C']})
new_order = [1, 0, 2]
a[new_order].assign_coords(a.coords)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 5.15.0-83-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.10.4
libnetcdf: 4.7.3

xarray: 2023.8.0
pandas: 2.1.0
numpy: 1.23.5
scipy: 1.10.0
netCDF4: 1.6.0
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.1.1
distributed: 2023.1.1
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.1.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 66.1.1
pip: 22.3.1
conda: None
pytest: 7.2.1
mypy: None
IPython: None
sphinx: None
</details>

**Comment by benbovy** [comment]
Hi @enekomartinmartinez, thanks for the report. This has been fixed in #8094 so the next release should restore the behavior in versions prior to v2023.08.0 (+ fix some other bugs). I'm going to close this issue but feel free to re-open it if the problem persists.
