### ISSUE TITLE
Doc build fails on pandas docstring

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#8157]
### What is your issue?

It looks like the doc build is [failing](https://readthedocs.org/projects/xray/builds/21845735/) on a pandas docstring:

```
/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/8156/lib/python3.10/site-packages/cartopy/io/__init__.py:241: DownloadWarning: Downloading: https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_coastline.zip
  warnings.warn(f'Downloading: {url}', DownloadWarning)
reading sources... [ 99%] user-guide/reshaping
reading sources... [ 99%] user-guide/terminology
reading sources... [ 99%] user-guide/time-series
reading sources... [ 99%] user-guide/weather-climate
reading sources... [100%] whats-new

/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/8156/lib/python3.10/site-packages/pandas/core/indexes/base.py:docstring of pandas.core.indexes.base.Index.join:14: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/8156/lib/python3.10/site-packages/pandas/core/indexes/base.py:docstring of pandas.core.indexes.base.Index.join:15: WARNING: Inline literal start-string without end-string.
looking for now-outdated files... none found
```

(also including the cartopy warning in case that's relevant)

Is this expected? Is anyone familiar enough with the doc build to know whether we can disable warnings from 3rd party modules?

**Comment by dcherian** [comment]
> Is anyone familiar enough with the doc build to know whether we can disable warnings from 3rd party modules?

We could pin pandas for now.

**Comment by kmuehlbauer** [comment]
Not sure if this helps in any way, but the culprit seems to be here:

https://github.com/pandas-dev/pandas/blob/faeedade7966d6f2a5b601c26205a71362913c47/pandas/core/indexes/base.py#L4560-L4561

**Comment by kmuehlbauer** [comment]
https://github.com/pandas-dev/pandas/pull/55050
