### ISSUE TITLE
groupby bug

### ISSUE THREAD

**Issue by Yefee** [pydata/xarray#8161]
### What happened?

Sometimes, when performing a groupby operation on a multidimensional data array, it can return unexpected results.

A copy of the test data could be found [here](https://miami.box.com/s/8cl45s01sbp7x503dyjhmi2wz96suzj9).

Code to reproduce the bug:
```
import xarray as xr
ds = xr.open_dataarray('test1.nc').load()
```
ds is a 100x86x25x66 array
![CleanShot 2023-09-09 at 00 26 51](https://github.com/pydata/xarray/assets/6420873/a0d49cec-02dd-46a3-801c-18aa778af112)

```
amoc1 = ds.isel(member_id=range(50)).stack(mb_time=['member_id', 'time'])
amoc1 = amoc1.groupby('mb_time').max(...)
amoc1 = amoc1.unstack()
amoc1
```
performing groupby on the first 50 members, results look fine.
![CleanShot 2023-09-09 at 00 28 24](https://github.com/pydata/xarray/assets/6420873/8581c226-1b0c-450f-9a4b-32fc99505582)

```
amoc2 = ds.isel(member_id=range(50, 100)).stack(mb_time=['member_id', 'time'])
amoc2 = amoc2.groupby('mb_time').max(...)
amoc2 = amoc2.unstack()
amoc2
```
performing groupby on the last 50 members, results look fine as well.
![CleanShot 2023-09-09 at 00 30 22](https://github.com/pydata/xarray/assets/6420873/a74242a1-e9a3-48f5-9adf-b1e5c9f146ab)

```
amoc = ds.isel(member_id=range(0, 100)).stack(mb_time=['member_id', 'time'])
amoc = amoc.groupby('mb_time').max(...)
amoc = amoc.unstack()
amoc
```
performing groupby on the whole 100 members, **results look weird**.
![CleanShot 2023-09-09 at 00 31 14](https://github.com/pydata/xarray/assets/6420873/d14c0292-517a-414b-8967-4f1be44e0bbe)

> 

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1127.18.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 2023.7.0
pandas: 1.5.3
numpy: 1.24.4
scipy: 1.10.1
netCDF4: 1.6.2
pydap: installed
h5netcdf: 1.0.0
h5py: 3.7.0
Nio: None
zarr: 2.12.0
cftime: 1.6.2
nc_time_axis: 1.4.1
PseudoNetCDF: None
iris: None
bottleneck: 1.3.7
dask: 2023.7.1
distributed: 2023.7.1
matplotlib: 3.4.3
cartopy: 0.20.2
seaborn: 0.11.2
numbagg: None
fsspec: 2022.11.0
cupy: None
pint: 0.19.2
sparse: None
flox: None
numpy_groupies: None
setuptools: 68.0.0
pip: 22.1.2
conda: 23.3.1
pytest: None
mypy: None
IPython: 7.33.0
sphinx: 5.0.1

</details>

**Comment by max-sixty** [comment]
Hi @yefee — we really would need a minimally reproducible example — with inline data — as per the issue template. I realize that will take some work, but with >1K issues, it's the only sustainable way of us to prioritize issues.

If you're up for doing that, please add here. Otherwise we can close until then.

**Comment by max-sixty** [comment]
Closing but feel free to reopen with an MCVE
