### ISSUE TITLE
Scalar coordinates should not be footloose

### ISSUE THREAD

**Issue by itcarroll** [pydata/xarray#8225]
### Is your feature request related to a problem?

A scalar coordinate has the counter-intuitive property of being able to hop from one data variable to another.
```
import xarray as xr

a = xr.Dataset(
    data_vars={"a": (("x",), [0, 0])},
    coords={
        "x": [0.1, 2.3],
        "y": 42,
    },
)
b = xr.Dataset(
    data_vars={"b": ("x", [1, 1])},
    coords={
        "x": [0.1, 2.3],
    },
)
c = xr.merge((a, b))
```
Only `a` had the scalar coordinate `y` before merging, but now `c["b"]` has caught it:
```
<xarray.DataArray 'b' (x: 2)>
array([1, 1])
Coordinates:
  * x        (x) float64 0.1 2.3
    y        int64 42
```
I think this is a bug in a way, because it does not reflect the NetCDF4 data model's ability to keep `y` as a coordinate on `a` alone. Note the "coordinates" attributes in the result of `c.to_netcdf`:
```
netcdf c {
dimensions:
	x = 2 ;
variables:
	int64 a(x) ;
		a:coordinates = "y" ;
	double x(x) ;
		x:_FillValue = NaN ;
	int64 y ;
	int64 b(x) ;
		b:coordinates = "y" ;       <----  Says who!?
```

### Describe the solution you'd like

I would like each data variable in a dataset to keep track of its own scalar coordinates (as they can, of course and absolutely essentially, do for dimension coordinates). To continue the example above, I think `c` should have a representation that would lead to the following serialization:
```
netcdf c {
dimensions:
	x = 2 ;
variables:
	int64 a(x) ;
		a:coordinates = "y" ;
	double x(x) ;
		x:_FillValue = NaN ;
	int64 y ;
	int64 b(x) ;
```

### Additional context

I think this feature could also help with #4501, wherein squeezing demotes a length-one non-dimensional coordinate to a scalar coordinate without tracking its own scalar coordinate. Egads, that's an ugly sentence. I'll elaborate over there.

Most importantly, this feature would solve a real problem I've encountered: model outputs, one for each combination of model parameters, that record parameters as a scalar coordinate *only on the data variables the parameter affects*. If you want to concatenate these together with XArray, you invariably get a lot of unncecessary data duplication. A contrived example with two outputs, in which the "temp" variable depends on parameter "time" but the "pressure" variable does not:
```
output_42 = xr.Dataset({
    "temp": xr.DataArray(
        data=[10, 9, 8],
        dims=("depth",),
        coords={
            "depth": [0, 5, 10],
            "time": 42,
        },
    ),
    "pressure": xr.DataArray(
        data=[0, 7, 14],
        coords={"depth": [0, 5, 10]},
    )
})
output_88 = xr.Dataset({
    "temp": xr.DataArray(
        data=[11, 10, 10],
        dims=("depth",),
        coords={
            "depth": [0, 5, 10],
            "time": 88,
        },
    ),
    "pressure": xr.DataArray(
        data=[0, 7, 14],
        coords={"depth": [0, 5, 10]},
    )
})
```
I think it should be possible to concatenate these datasets without duplicating "pressure", like so:
```
<xarray.Dataset>
Dimensions:   (depth: 3, time: 2)
Coordinates:
  * depth     (depth) int64 0 5 10
  * time      (time) int64 42 88
Data variables:
    temp      (time, depth) int64 10 9 8 11 10 10
    pressure  (depth) int64 0 7 14
```
I can't get to there with any variation on `xr.concat((output_42, output_88), dim="time", data_vars="minimal")`, which I guess can be explained by the fact that "time" is associated with both "temp" and "pressure" in XArray's internal representation.

**Comment by max-sixty** [comment]
Thanks for the issue. a brief (though not full) response:

Having coordinates shared throughout the dataset is a fairly fundamental feature of xarray's data model; that would be difficult to change. You could explore variable-specific `attrs` if that's helpful.

That said, the final example is a good one — I think that should be possible. How is that happening now? Having an example would be helpful in seeing whether it's possible to improve on.

**Comment by itcarroll** [comment]
Thank you for reading!

> Having coordinates shared throughout the dataset is a fairly fundamental feature of xarray's data model

"Shared" in the sense of available, absolutely, but not every data variable in a dataset shares *all* the available dimension coordinates. Scalar coordinates seem to be exceptional here.

Here is a radical change that maybe conveys what I'm suggesting better (note, I'm not actually suggesting this): think of scalar coordinates as a zero-length dimension coordinate.
```
ds = xr.Dataset({
    "a": xr.DataArray([0, 0], dims=("x", "y"), coords={"x": [0, 2], "y": 42}),
    "b": xr.DataArray([1, 1], dims=("x",), coords={"x": [0, 1]}),
})
ds
```
```
<xarray.Dataset>
Dimensions:  (x: 3, y: 0)                   <--- the feature request is to allow this in effect, without 
Coordinates:                                     actually changing xarray so much that y becomes a
  * x        (x) int64 0 1 2                     dimension coordinate/index.
    y        int64 42
Data variables:
    a        (x, y) float64 0.0 nan 0.0     <--- this part too 
    b        (x) float64 1.0 1.0 nan
```
But don't take that characterization too literally; zero length dimensions don't work. Take only from that the idea that y is a coordinate of `a` but not `b`.

> Having an example would be helpful in seeing whether it's possible to improve on.

Here's what you currently get with `xr.concat((output_42, output_88), dim="time")`:
```
<xarray.Dataset>
Dimensions:   (depth: 3, time: 2)
Coordinates:
  * depth     (depth) int64 0 5 10
  * time      (time) int64 42 88
Data variables:
    temp      (time, depth) int64 10 9 8 11 10 10
    pressure  (time, depth) int64 0 7 14 0 7 14      <--- no!
```

**Comment by max-sixty** [comment]
> "Shared" in the sense of available, absolutely, but not every data variable in a dataset shares _all_ the available dimension coordinates. Scalar coordinates seem to be exceptional here.

The example is helpful, and I think I see what you mean. 

FWIW I don't think there's an inconsistency in the data model — coordinates belong to the Dataset object, not the variable. For non-scalar coordinates: if they share a dimension, then they get carried along with the variable. And the same principle applies to scalar coordinates — they necessarily share the zero dimensions with each variable :)

If we had a coordinate with length 1 — and then some variables had the dimension, some didn't — would that work here?

> Here's what you currently get with `xr.concat((output_42, output_88), dim="time")`:

Yes; very much agree this is a good case. Were you doing anything to construct the "Good" object? Or that was just a handwritten example? 

I agree this sort of thing would be useful magic (though it would be magic — IIUC the only distinction between the two are whether the coords have equal values?). This isn't an area I have much experience in; but worth checking out the `.combine_by_coords` and related funcs...

**Comment by dcherian** [comment]
Thanks for the well written issue. Unfortunately this seems like a "wontfix".

[cf-xarray](https://cf-xarray.readthedocs.io/en/latest/selecting.html#associated-variables) will interpret the coordinates attribute when extracting a DataArray (though the docs don't clearly mention this).

For your concat issue, promote `pressure` to `coords` and then set `data_vars="all", coords="minimal", compat="override"` (I think)

**Comment by itcarroll** [comment]
I'll withdraw this feature request. I delved further into concat and combine_by_coords and learned that coordinates are shared across the dataset (as was stated in the original response, sorry!), in a way I don't quite fathom.

Thanks for the pointer to cf-xarray, I will take a look.
