### ISSUE TITLE
Disable lock=True in open_mfdataset when reading netCDF3 files

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#824]
This slows things down unnecessarily.

**Comment by pwolfram** [comment]
@shoyer, is this related to https://github.com/pydata/xarray/pull/800?  If I recall correctly based on https://github.com/pydata/xarray/issues/793 there may be some issues with dask/multithreading without the lock.  Am I missing something here?

It may make sense to just to set `lock=False` by default in https://github.com/pydata/xarray/blob/master/xarray/backends/api.py#L247 and if issues are encountered `lock=True` can be set by the user.  Is this what you are thinking?  If so, I can submit the super simple PR if that is helpful.

**Comment by shoyer** [comment]
The issues with multithreading without a lock come up only when using netCDF4/HDF5. With netCDF3, you don't need the lock when reading data.

I don't like changing to `lock=False` in all circumstances, because that will lead to segfaults and segfaults make for a bad new user experience! Instead, `lock=None` should do something smart.

**Comment by pwolfram** [comment]
@shoyer, makes sense.  Are you thinking of something like the following pseudo code?

```python
if lock is None:
    if type(file) is netCDF4/HDF5:
        lock=True
    else:
        lock=False
```

**Comment by pwolfram** [comment]
We could also just filter the other way too which is probably cleaner: 

```python
if lock is None and type(file) is netCDF3:
   lock=False
```

**Comment by jhamman** [comment]
@shoyer - this was addressed in the backend refactor this summer, no?

**Comment by shoyer** [comment]
Yes we did
