### ISSUE TITLE
Should `.reset_encoding` be `.drop_encoding`?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#8259]
### What is your issue?

Not the greatest issue facing the universe — but for the cause of consistency — should `.reset_encoding` be `.drop_encoding`, since it drops all encoding attributes?

For comparison:
- `.reset_coords` — "Given names of coordinates, reset them to become variables."
- '.drop_vars` — "Drop variables from this dataset."

Also ref #8258

**Comment by jhamman** [comment]
🤚 `.reset_encoding` was indeed by addition. In hindsight, `drop_encoding` would have been a better name. Very open to seeing this changed to align with the other `drop_foo` methods.
