### ISSUE TITLE
xarray accessor: `regrid`

### ISSUE THREAD

**Issue by BSchilperoort** [pydata/xarray#8260]
### What is your issue?

For regridding (rectilinear) geospatial data, we are working on an xarray plugin "[xarray-regrid](https://github.com/EXCITED-CO2/xarray-regrid)".

As accessor we use `regrid`.

Currently we have a few methods implemented:

- linear, nearest neighbor, cubic (simple wrappers around xr.interp)
- conservative (custom method, based on a comment by Stephan Hoyer [here](https://discourse.pangeo.io/t/conservative-region-aggregation-with-xarray-geopandas-and-sparse/2715/3))
  - It is compatible with `dask.distributed` and outperforms xESMF, on par with CDO.
- A "most common value" zonal statistics method.

On our repository we also have some notebooks benchmarking the results against xESMF and CDO.

I read I should let you know about using the accessor, hope you are interested!

**Comment by TomNicholas** [comment]
Thanks for pointing us to this! A performant replacement for xESMF would be extremely valuable!

Feel free to submit a PR adding a link to xarray-regrid to our [Ecosystem page](https://docs.xarray.dev/en/stable/ecosystem.html).
