### ISSUE TITLE
Attributes are currently kept when arrays are resampled, and not when datasets are resampled

### ISSUE THREAD

**Issue by mcgibbon** [pydata/xarray#828]
Because line 323 of groupby.py copies attributes from a DataArray to its resampling output (it shouldn't), attributes are kept in many cases when DataArrays are resampled (and not kept for similar cases when Datasets are resampled).

**Comment by shoyer** [comment]
I agree, this is a bug. We should make this consist and follow the `keep_attrs` argument.

**Comment by mcgibbon** [comment]
@shoyer I've corrected this in a PR I'll submit shortly.

**Comment by shoyer** [comment]
Awesome, thanks!

**Comment by shoyer** [comment]
Fixed by #829
