### ISSUE TITLE
`NamedArray.shape` does not support unknown dimensions

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#8291]
### What is your issue?

According to the array api standard, the `shape` property returns `tuple[int | None, ...]`.
Currently we only support `tuple[int, ...]`

This will actually raise some errors if a duckarray actually returns some None.
E.g. `NamedArray.size` will fail.

(On a side note: dask arrays actually use NaN instead of None for some reason.... Only advantage of this is that `NamedArray.size` will actually also return NaN instead of raising...)

**Comment by TomNicholas** [comment]
> (On a side note: dask arrays actually use NaN instead of None for some reason.... Only advantage of this is that NamedArray.size will actually also return NaN instead of raising...)

Linking to more info on this, and the connection to ragged arrays: https://github.com/pydata/xarray/issues/4285#issuecomment-1203256821
