### ISSUE TITLE
Different output for Dataset.groupby().mean() depending on whether flox is installed or not

### ISSUE THREAD

**Issue by eendebakpt** [pydata/xarray#8292]
### What happened?

We execute `ds.groupby('clifford').mean()`. The resulting `Dataset` is different depending whether the optional package flox is installed or not.

### What did you expect to happen?

The result should be the same

### Minimal Complete Verifiable Example

```Python
import xarray as xr
d={'coords': {'bit_index': {'dims': ('bit_index',),
   'attrs': {'name': 'bit_index',
    'units': 'a.u.',
    'standard_name': 'bit_index',
    'long_name': 'bit_index',
    'label': 'bit_index'},
   'data': [0, 1]},
  'index': {'dims': ('index',),
   'attrs': {'name': 'index',
    'units': '',
    'standard_name': 'index',
    'long_name': 'index',
    'label': 'index'},
   'data': [0, 6, 8, 10, 14]},
  'clifford': {'dims': ('index',), 'attrs': {}, 'data': [1, 1, 4, 10, 4]},
  'pauli': {'dims': ('index',), 'attrs': {}, 'data': [12, 12, 6, 12, 6]},
  'pauli_value': {'dims': ('index',), 'attrs': {}, 'data': [1, 1, 1, 1, 1]}},
 'attrs': {},
 'dims': {'bit_index': 2, 'index': 5},
 'data_vars': {'counts': {'dims': ('bit_index', 'index'),
   'attrs': {'name': 'counts',
    'units': '',
    'standard_name': 'Counts',
    'long_name': 'Counts',
    'label': 'Counts'},
   'data': [[18, 30, 45, 70, 38], [382, 370, 355, 330, 362]]}}}

ds=xr.Dataset.from_dict(d)   
ds.groupby('clifford').mean()
```

(execute with both flox installed and flox not installed)
```
""" With flox
<xarray.Dataset>
Dimensions:    (bit_index: 2, clifford: 3)
Coordinates:
  * bit_index  (bit_index) int32 0 1
  * clifford   (clifford) int64 1 4 10
Data variables:
    counts     (bit_index, clifford) float64 24.0 41.5 70.0 376.0 358.5 330.0
"""

""" No flox
<xarray.Dataset>
Dimensions:    (bit_index: 2, clifford: 3)
Coordinates:
  * bit_index  (bit_index) int32 0 1
  * clifford   (clifford) int64 1 4 10
Data variables:
    counts     (clifford, bit_index) float64 24.0 376.0 41.5 358.5 70.0 330.0
"""
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Anything else we need to know?

This is probably related to #7546

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: ('Dutch_Netherlands', '1252')
libhdf5: 1.12.2
libnetcdf: None

xarray: 2023.9.0
pandas: 1.5.3
numpy: 1.26.0
scipy: 1.11.3
netCDF4: None
pydap: None
h5netcdf: 1.2.0
h5py: 3.9.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.9.1
distributed: None
matplotlib: 3.8.0
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.9.0
cupy: None
pint: 0.22
sparse: None
flox: 0.7.2
numpy_groupies: 0.9.22
setuptools: 65.4.1
pip: 23.2
conda: None
pytest: 7.4.2
mypy: 1.5.1
IPython: 8.15.0
sphinx: 7.2.6

</details>

**Comment by headtr1ck** [comment]
By different, do you mean the order of dimension or the actual values?

**Comment by dcherian** [comment]
Thanks @eendebakpt .

This seems to be because Xarray reorders the dimensions for DataArrays only.
https://github.com/pydata/xarray/blob/75af56c33a29529269a73bdd00df2d3af17ee0f5/xarray/core/groupby.py#L1427-L1429

```python
print(ds.counts.dims)
with xr.set_options(use_flox=True):
    print(ds.groupby("clifford").mean().counts.dims)
with xr.set_options(use_flox=False):
    print(ds.groupby("clifford").mean().counts.dims)
with xr.set_options(use_flox=True):
    print(ds.counts.groupby("clifford").mean().dims)
with xr.set_options(use_flox=False):
    print(ds.counts.groupby("clifford").mean().dims)
```
```
('bit_index', 'index')
('bit_index', 'clifford')
('clifford', 'bit_index')
('bit_index', 'clifford')
('bit_index', 'clifford')
```

I bet if you stuck a `isinstance(obj, DataArray):` check in flox, this would be fixed. (PR very welcome!):
https://github.com/xarray-contrib/flox/blob/a897034b02e1c1445a8b7a25535120205d7df4d0/flox/xarray.py#L488-L496

**Comment by eendebakpt** [comment]
@dcherian Adding a `and isinstance(obj, DataArray):` is not working. The problem (if we want so solve things on the flox side) seems to be that in `_restore_dim_order` at https://github.com/xarray-contrib/flox/blob/a897034b02e1c1445a8b7a25535120205d7df4d0/flox/xarray.py#L31-L42 the proper reordering is not found. For the example about with flox enabled we end up with  `by.ndim=1`, ` by.name='clifford'` and ` result.dims=('bit_index', 'clifford')`, `obj.dims=('bit_index', 'index')`. The new order is then `new_order=['bit_index', 'clifford']`, where we should end up with `('clifford', 'bit_index')`.

**Comment by dcherian** [comment]
I just remembered https://github.com/pydata/xarray/blob/dcf5d743fc8ff66996ff73c08f6893b701ff6e02/xarray/core/groupby.py#L1064-L1070, does your fix remove the need for this block too?
