### ISSUE TITLE
Slicing using data.sel gives me an error: TypeError: get_loc() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by pramodadhikari** [pydata/xarray#8293]

**Comment by max-sixty** [comment]
This is likely an old version of xarray with a new version of pandas; please open a full bug report if not

**Comment by FiND-Tao** [comment]
I got the same error with "xarray version: 0.20.1, pandas version: 2.1.4". The error disappeared with "xarray version: 2024.5.0, pandas version: 2.2.1".

**Comment by hunterboerner** [comment]
I'm having this same issue with xarray 2024.6.0 and Pandas 2.2.2

**Comment by max-sixty** [comment]
@hunterboerner could you open a new issue with a dependency listing?
