### ISSUE TITLE
Coveralls is missing line-by-line report

### ISSUE THREAD

**Issue by mcgibbon** [pydata/xarray#833]
The report showing which lines are and aren't covered by tests is missing from coveralls ([example](https://coveralls.io/builds/5844958/source?filename=xarray%2Fcore%2Fcommon.py)). Others have also had this problem (example [1](https://github.com/lemurheavy/coveralls-public/issues/263), [2](https://github.com/statsmodels/statsmodels/issues/1502/)).

Let me know if it's there and I'm just not finding it.

**Comment by shoyer** [comment]
I'm not quite sure what was going on, but this seems to be working now, at least on the latest build: https://coveralls.io/builds/5853755/source?filename=xarray%2Fcore%2Fcommon.py
