### ISSUE TITLE
open_dataset error, "UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' .."

### ISSUE THREAD

**Issue by emiliom** [pydata/xarray#834]
I have a netcdf file I [downloaded](http://www.nodc.noaa.gov/archive/arc0082/0139360/1.1/data/0-data/Aragonite.nc). When I try to open it with `open_dataset` (using version 0.7.0, with Python 2.7, on a Jupyter notebook), I get this fatal error: `UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 752: ordinal not in range(128)` (the full stack trace is below)

I couldn't find any references to this error in xarray, either on this list or Google. The only somewhat/indirectly related github issue I found might be #681 (closed).

Using ncdump and the netCDF4 package, I'm almost certain the problem is a non-ascii long dash character in the "Abstract" global attribute. netCDF4 doesn't throw an error when opening the file or viewing the Abstract attribute.

None of the `open_dataset` parameters seem relevant to this issue.

Any tips? I can now get at the data using netCDF4, but I'd prefer to have the convenience of xarray datasets. The only way I can think of is to first create a new version of the nc file where I drop the offending global attribute.

```python
ds = xray.open_dataset(os.path.join(pth, 'Aragonite.nc'))

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    697                 type_pprinters=self.type_printers,
    698                 deferred_pprinters=self.deferred_printers)
--> 699             printer.pretty(obj)
    700             printer.flush()
    701             return stream.getvalue()

/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/IPython/lib/pretty.pyc in pretty(self, obj)
    381                             if callable(meth):
    382                                 return meth(obj, self, cycle)
--> 383             return _default_pprint(obj, self, cycle)
    384         finally:
    385             self.end_group()

/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _default_pprint(obj, p, cycle)
    501     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    502         # A user-provided repr. Find newlines and replace them with p.break_()
--> 503         _repr_pprint(obj, p, cycle)
    504         return
    505     p.begin_group(1, '<')

/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _repr_pprint(obj, p, cycle)
    692     """A pprint that just redirects to the normal repr function."""
    693     # Find newlines and replace them with p.break_()
--> 694     output = repr(obj)
    695     for idx,output_line in enumerate(output.splitlines()):
    696         if idx:

/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/xarray/core/dataset.pyc in __repr__(self)
    790 
    791     def __repr__(self):
--> 792         return formatting.dataset_repr(self)
    793 
    794     @property

/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/xarray/core/formatting.pyc in dataset_repr(ds)
    274     summary.append(vars_repr(ds.data_vars, col_width=col_width))
    275     if ds.attrs:
--> 276         summary.append(attrs_repr(ds.attrs))
    277 
    278     return '\n'.join(summary)

/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/xarray/core/formatting.pyc in _mapping_repr(mapping, title, summarizer, col_width)
    208     summary = ['%s:' % title]
    209     if mapping:
--> 210         summary += [summarizer(k, v, col_width) for k, v in mapping.items()]
    211     else:
    212         summary += [EMPTY_REPR]

/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/xarray/core/formatting.pyc in summarize_attr(key, value, col_width)
    191 def summarize_attr(key, value, col_width=None):
    192     # ignore col_width for now to more clearly distinguish attributes
--> 193     return '    %s: %s' % (key, _maybe_truncate(value))
    194 
    195 

/home/mayorga/miniconda/envs/bigcz/lib/python2.7/site-packages/xarray/core/formatting.pyc in _maybe_truncate(obj, maxlen)
    183 
    184 def _maybe_truncate(obj, maxlen=500):
--> 185     s = str(obj)
    186     if len(s) > maxlen:
    187         s = s[:(maxlen - 3)] + '...'

UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 752: ordinal not in range(128)
```

**Comment by shoyer** [comment]
This looks like a bug in our attribute pretty-printing code (on Python 2) -- we shouldn't be calling `str(obj)` but rather should be writing something that can always successfully cast to string `'%s' % obj`.

This should be a pretty straightforward bug fix, but as a work around for now, you could delete the offending attribute (which uses the character �) from the dataset:
```
ds = xray.open_dataset(os.path.join(pth, 'Aragonite.nc'))
del ds.attrs['bad_attr']
print ds
```

**Comment by emiliom** [comment]
Apologies! I just noticed that the error was not when using `open_dataset`, but rather when I "printed out" the dataset in the notebook:
```python
ds = xarray.open_dataset(os.path.join(pth, 'Aragonite.nc'))
ds
```
It turns out I can actually get at the dataset and even print out the offending attribute:
```python
ds.attrs['Abstract']
```
> u'This data set contains gridded data of the spatial distributions of aragonite saturation state across the global oceans (resolution: 1 degrees) at depth levels of 0m, 50m, 100m, 200m, 500m, 1000m, 2000m, 3000m and 4000m. Longitude used in this data set is from 20 to 380 degrees. If you want to convert to the -180 to 180 degrees system, please subtract longitude values that are larger than 180 with 360. Aragonite saturation state was corrected to the year of 2000. For more information about the data set, please read the below paper: Jiang, L.-Q., R. A. Feely, B. R. Carter, D. J. Greeley, D. K. Gledhill, and K. M. Arzayus (2015a), Climatological distribution of aragonite saturation state in the global oceans, Global Biogeochem. Cycles, 29, 1656\ufffdC1673, doi:10.1002/2015GB005198.'

So, the problem is not fundamentally with opening the dataset, but is much more limited and doesn't prevent the use of xarray with this nc file. Sorry for mischaracterizing the problem!

**Comment by emiliom** [comment]
@shoyer, thank you! Will do what you suggest. That solves my problem for sure.

**Comment by rabernat** [comment]
I just hit this bug with the following dataset:
ftp://podaac-ftp.jpl.nasa.gov/allData/avhrr/L3/pathfinder_v5/daily/night/04km/1985/006/1985006.s04d1pfv50-sst-16b.hdf

Some attributes appear to be encoded in unicode.
