### ISSUE TITLE
How does Xarray plot a bar chart?

### ISSUE THREAD

**Issue by hugo-pires** [pydata/xarray#836]
How can I plot a bar chart from a Python Xarray dataset (eg. rain data axis)?

I am already using this code to resize the plot

```
fig, ax = plt.subplots(figsize=(9, 9))
dsfanadia.rain.plot(ax=ax)
```

Thank you

**Comment by jhamman** [comment]
@hugo-pires -

xarray's plotting module does not have a bar chart method at this time ([api ref](http://xarray.pydata.org/en/stable/api.html#plotting)). You can, of course, export your data array to a pandas series and use the pandas bar chart. Psudo code...

```Python

fig, ax = plt.subplots(figsize=(9, 9))
rain_series = dsfanadia.rain.to_series()
rain_series.plot.bar(ax=ax)
```

**Comment by hugo-pires** [comment]
Thank you.
