### ISSUE TITLE
Type annotations for Dataset.where and DataArray.where are wrong when subclassed

### ISSUE THREAD

**Issue by aaronsarna** [pydata/xarray#8374]
### What is your issue?

I'm aware of the guidance of https://docs.xarray.dev/en/stable/internals/extending-xarray.html to avoid subclassing xarray datastructures, but it doesn't seem to outlaw it altogether, so I figured I'd file this issue anyway.

The [type annotations](https://github.com/pydata/xarray/blob/70c4ee73a7524526d58b8394d449d010720f205f/xarray/core/common.py#L1063) for both Dataset.where and DataArray.where claim that these methods will return the type of Self. In practice, though, if they are called on a subclass of either of these classes, they will actually return instances of either DataArray or Dataset, rather than the subclass.

Here's a trivial demonstration: https://colab.research.google.com/drive/1BiGptVUjyKifFI8PSye4v3ADAMXH6KSZ?usp=sharing

I'm not totally sure what the correct type annotations to add here would be, though. My preferred solution would actually be to make the current type hints correct and return instances of the subclass.

**Comment by max-sixty** [comment]
This is a case of https://github.com/pydata/xarray/issues/3980 IIUC. So we're very open to returning subclasses; someone needs to do the work on each method though. (and we're very happy to have marginal contributions which gradually support this, adding tests so we ratchet up the support)

Taking a quick look at `.where`, this runs through `.apply_ufunc`, which is one of the more difficult places to adjust — though would have widespread benefits if we could change it. We could start by trying something like this:

```diff
diff --git a/xarray/core/computation.py b/xarray/core/computation.py
index 9cb60e0c..633723c7 100644
--- a/xarray/core/computation.py
+++ b/xarray/core/computation.py
@@ -316,11 +316,11 @@ def apply_dataarray_vfunc(
     out: tuple[DataArray, ...] | DataArray
     if signature.num_outputs > 1:
         out = tuple(
-            DataArray(
+            arg.__class__(
                 variable, coords=coords, indexes=indexes, name=name, fastpath=True
             )
-            for variable, coords, indexes in zip(
-                result_var, result_coords, result_indexes
+            for variable, coords, indexes, arg in zip(
+                result_var, result_coords, result_indexes, args
             )
         )
     else:

```

We can leave this open for a bit, though I'd probably suggest folding into #3980 in time.

**Comment by aaronsarna** [comment]
Thanks! Glad to know that there's interest in supporting this use case.

Is there a reasonable way to fix the typehints in the meantime, since it sounds like returning the subclass might be tricky?

**Comment by max-sixty** [comment]
Very open to thoughts, but I worry that selecting the methods that do & do not respect subclasses will be almost as much work as making subclassing work.

...and almost intractable to oversee and test — is there a test that would have caught the `.where` case? And one that would also catch when we do get that method to work with subclasses?

**Comment by headtr1ck** [comment]
I don't think we test subclasses anywhere since it is still discouraged to do so and support is still considered experimental.
In this case the main culprit is `apply_ufunc` which still cannot deal with subclasses...

**Comment by max-sixty** [comment]
> It sounds to me like there are 2 different statements on this issue that are at odds with each other:
> 
>     1. "we're very open to returning subclasses; someone needs to do the work on each method though."
> 
>     2. "I don't think we test subclasses anywhere since it is still discouraged to do so and support is still considered experimental."

Yes, and I think it's helpful to surface this disagreement.

I agree with (1)

I would change (2) to "We don't yet have tests, but we could add them onto each method as we do the work from (1)". @headtr1ck how do you think about that?

**Comment by headtr1ck** [comment]
> I would change (2) to "We don't yet have tests, but we could add them onto each method as we do the work from (1)". @headtr1ck how do you think about that?

Yes ideally we should add tests for subclassing, not only static typing but also if the runtime behavior works as expected.

**Comment by max-sixty** [comment]
OK, sounds like we have consensus:
- We'd like subclassing to work. It's a tractable problem
- We'd accept contributions getting us closer there
  - Much of this is just changing `DataArray(...)` to `self.__class__(...)`, etc
  - Then there's also how to switch between `DataArray` & `Dataset`, I agree with @headtr1ck 's proposal at https://github.com/pydata/xarray/issues/3980#issuecomment-1449013427
- We'd accept tests ensuring methods work well with subclasses, that way we can ratchet support through the library

Let's fold into #3980
