### ISSUE TITLE
Zarr Chunks: Too many chunks created if there is one small initial chunk.

### ISSUE THREAD

**Issue by hameer-spire** [pydata/xarray#8382]
### What is your issue?

If the first Zarr chunk is small (a few items), every subsequent chunk created will be tiny, and this will cause massive issues reading back the dataset. Consider the following code (MCVE):

```python
import numpy as np
import xarray as xr

# Create and write a dataset with ONE tiny chunk per variable
ds = xr.Dataset()
ds.coords["x"] = "x", np.zeros((1,), dtype=np.uint64)
ds["data"] = "x", np.zeros((1,), dtype=np.bool_)
ds.to_zarr("/tmp/temp.zarr")

# Append to that dataset a larger amount of data
ds2 = xr.Dataset()
ds2.coords["x"] = "x", np.arange(1, 1000, dtype=np.uint64)
ds2["data"] = "x", np.zeros(999, dtype=np.bool_)
ds2.to_zarr("/tmp/temp.zarr", append_dim="x")

# These chunks should be MUCH larger, but they're one item each for me.
ds_read = xr.open_zarr("/tmp/temp.zarr")
for var in ds_read.variables:
    print(f"{var=}, {ds_read[var].encoding['chunks']=}")
```

Is there a way to change this behaviour by default, ideally within xarray (or zarr-python if it is responsible)? Perhaps, if only one chunk is present, the heuristic should consider appending to it instead of creating new chunks?

**Comment by max-sixty** [comment]
Does `ds2.chunk("auto").to_zarr...` suffice?

**Comment by hameer-spire** [comment]
> Does `ds2.chunk("auto").to_zarr...` suffice?

It does not. It still creates variables with a chunk size of `(1,)`

**Comment by max-sixty** [comment]
Zarr chunks need to all be the same size, so changing the chunk size would require rewriting the Zarr... But then I'd think that `"auto"` was sufficient?

**Comment by hameer-spire** [comment]
> Zarr chunks need to all be the same size, so changing the chunk size would require rewriting the Zarr... But then I'd think that `"auto"` was sufficient?

That's correct, except for the last chunk. Which is the only chunk in this case, so I'd think it could be extended.

**Comment by max-sixty** [comment]
> Which is the only chunk in this case, so I'd think it could be extended.

But this only applies if there are exactly two chunks, right? How would it know it's not getting a third? :)

**Comment by hameer-spire** [comment]
> But this only applies if there are exactly two chunks, right? How would it know it's not getting a third? :)

It's okay if it gets a third, as long as the first (and only) tiny chunk of size `(1,)` was extended so it was bigger. To be clear, my issue isn't that the dataset is all just one big chunk; my issue is that the chunks are all size `(1,)` with no way to change that **if** the **first and only** chunk is too small.

**Comment by hameer-spire** [comment]
For context, I load a lot of data into memory, apply a filtering operation, then move on to more data. If the initial set of data after filtering is too small after the first filtering pass; all subsequent chunks will be small (only a few items), and we run into huge performance bottlenecks unless we re-chunk the whole dataset.

**Comment by max-sixty** [comment]
> It's okay if it gets a third, as long as the first (and only) tiny chunk of size `(1,)` was extended so it was bigger.

Yes, but this is rechunking — rewriting existing data. That's not what the append operation does. It's very viable to do that, but I don't think it's tractable for the library to guess that's what the user wants to do...

Or lmk if I'm missing something...

**Comment by hameer-spire** [comment]
> Or lmk if I'm missing something...

I think it'd be sufficient to somehow specify the encoding chunk size if there was just one chunk per variable in the dataset. As I see it, there's no way to ensure the chunk size will be correct if `len < chunks`.

**Comment by max-sixty** [comment]
> > Or lmk if I'm missing something...
> 
> 
> 
> I think it'd be sufficient to somehow specify the encoding chunk size if there was just one chunk per variable in the dataset. As I see it, there's no way to ensure the chunk size will be correct if `dim < chunks`.

It isn't possible to have `dim < chunks`. How would this work when appending the second and third chunk, without implicitly rewriting?

**Comment by hameer-spire** [comment]
An implicit rewrite is what we want if there's just one tiny chunk along a dimension, right? We usually change the last chunk along a dimension when appending anyway, so in this case we'd change just the one, ensuring better future performance if the dataset is later appended to.

**Comment by max-sixty** [comment]
...but then that's a different operation from append, which doesn't change chunk sizes or rewrite existing data

Ofc we could change append so it did occasionally do those things, but my claim is that is too far from its current function and conventional meaning of "append" — others should comment if they see it differently...

We'd def accept a doc suggestion of rewriting data in these circumstances, to the extent you'd like to contribute to those.
