### ISSUE TITLE
Update cftime frequency strings in line with recent updates in pandas

### ISSUE THREAD

**Issue by spencerkclark** [pydata/xarray#8394]
### What is your issue?

Pandas has introduced some deprecations in how frequency strings are specified:

- Deprecating `"A"`, `"A-JAN"`, etc. in favor of `"Y"`, `"Y-JAN"`, etc. (https://github.com/pandas-dev/pandas/pull/55252)
- Deprecating `"AS"`, `"AS-JAN"`, etc. in favor of `"YS"`, `"YS-JAN"`, etc. (https://github.com/pandas-dev/pandas/pull/55479)
- Deprecating `"Q"`, `"Q-JAN"`, etc. in favor of `"QE"`, `"QE-JAN"`, etc.  (https://github.com/pandas-dev/pandas/pull/55553)
- Deprecating `"M"` in favor of `"ME"` (https://github.com/pandas-dev/pandas/pull/54061)
- Deprecating `"H"` in favor of `"h"` (https://github.com/pandas-dev/pandas/pull/54939)
- Deprecating `"T"`, `"S"`, `"L"`, and `"U"` in favor of `"min"`, `"s"`, `"ms"`, and `"us"` (https://github.com/pandas-dev/pandas/pull/54061).

It would be good to carry these deprecations out for cftime frequency specifications to remain consistent.

**Comment by aulemahal** [comment]
That's quite heavy a change... This move from pandas seems an unnecessary leap to me! 
I'll look into the PR, thanks for heads up!
