### ISSUE TITLE
Trying to download GFS data via Siphon-- Get an xarray error

### ISSUE THREAD

**Issue by Cjseng** [pydata/xarray#8426]
### What is your issue?

**I am attempting to follow this example code here:**
https://unidata.github.io/python-training/workshop/Bonus/downloading-gfs-with-siphon/

**However, when I run it, I get this error code:**
Traceback (most recent call last):

  File ~/anaconda3/lib/python3.10/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Downloads/untitled3.py:30
    data = xr.open_dataset(NetCDF4DataStore(data))

  File ~/anaconda3/lib/python3.10/site-packages/xarray/backends/netCDF4_.py:323 in __init__
    self.format = self.ds.data_model

  File ~/anaconda3/lib/python3.10/site-packages/xarray/backends/netCDF4_.py:385 in ds
    return self._acquire()

  File ~/anaconda3/lib/python3.10/site-packages/xarray/backends/netCDF4_.py:379 in _acquire
    with self._manager.acquire_context(needs_lock) as root:

AttributeError: 'bytes' object has no attribute 'acquire_context'

I have not changed anything from the code given from unidata, as I'm just learning how to do this in general, but from what I've read this might have something to do with python3? Any help would be appreciated in resolving this issue.

**Comment by jhamman** [comment]
@Cjseng - we'll need a reproducer and additional information about your system to help you here. Would you mind opening a new issue with the details filled out in our [Bug Report form](https://github.com/pydata/xarray/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=bugreport.yml).
