### ISSUE TITLE
Don't convert data with time units to timedeltas by default

### ISSUE THREAD

**Issue by ocefpaf** [pydata/xarray#843]
Don't convert data with time units to `timedeltas` by default. Most of the time this behavior is not desirable (e.g: wave period data).

@shoyer suggest:

> possibly we should add an explicit toggle for decoding `timedelta`s vs `datetime`s.

xref: https://github.com/pydata/xarray/pull/842#issuecomment-216933269

**Comment by ocefpaf** [comment]
@shoyer is this what you have in mid? Replacing `decode_time` for `decode_datetimes` and `decode_timedelta` and then:

```python
    if decode_datetimes and 'units' in attributes and 'since' in attributes['units']:
        units = pop_to(attributes, encoding, 'units')
        calendar = pop_to(attributes, encoding, 'calendar')
        data = DecodedCFDatetimeArray(data, units, calendar)

    if decode_timedelta and attributes['units'] in TIME_UNITS:
        units = pop_to(attributes, encoding, 'units')
        data = DecodedCFTimedeltaArray(data, units)
```

To be honest I cannot see why someone might want to convert time data to a `timedelta` and I would be inclined to remove `decode_timedelta` instead. However, that may be my [very biased view](http://nbviewer.jupyter.org/gist/ocefpaf/d4e06714df5154590744320d593ea373) since such transformation does not make sense with my data :smile: 

Do you have any advice? (I would like to try this before you release `v0.8.0`)

**Comment by shoyer** [comment]
It's too late for v0.8.0, I'm afraid! I already tagged/uploaded the release and am about to send out the announcement.

**Comment by ocefpaf** [comment]
No problem. I want to solve this anyways b/c it is quite awkward to keep converting back from `timedelta`s to time data. I will have a PR soon.

**Comment by shoyer** [comment]
To answer your original question: yes, separate `decode_timedeltas`and `decode_datetimes` options seems like a sane way to handle this.

**Comment by ocefpaf** [comment]
Prototype is ready http://nbviewer.jupyter.org/gist/ocefpaf/cabdcb27a5ef7da1b6110327a5f03e17

I will polish this and send a PR soon.

**Comment by ocefpaf** [comment]
@shoyer the more I think about this the more I don't like the addition of extra keywords. Even though I would like this behavior to be the default one I really do not like the complexity I added here.

Closing this...
