### ISSUE TITLE
inplace argument for fun like drop

### ISSUE THREAD

**Issue by ggrrll** [pydata/xarray#8470]
### Is your feature request related to a problem?

there should be a `inplace` arg , to avoid re assigning the variable

### Describe the solution you'd like

inplace=True argument, in functions like  `.drop` ...

### Additional context

related to #3260 , ...

**Comment by keewis** [comment]
considering that we deprecated and removed the `inplace` parameter a while ago (for example in the issue you linked to), I don't think we will add it back.

You can work around this by assigning the return value of `drop` to a name or by using call chains:
```python
(
    ds
    .drop_vars("variable")
    .sel(...)
    ...
)
# or
ds = ds.drop_vars("variable")
```

**Comment by ggrrll** [comment]
ok thanks -- well, that's exactly what I wanted to avoid , using the same rational as [pandas drop](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html)
