### ISSUE TITLE
variable with units of 'nannoseconds' gets rounded when read.

### ISSUE THREAD

**Issue by SmithB** [pydata/xarray#8486]
### What happened?

If I read a floating-point variable saved in a netcdf file that has units of nanoseconds, xarray reports the variable as having datatype 'timedelta64,' and reads integer values for the data.

### What did you expect to happen?

I would expect the variable to be read at full precision, and to have a datatype of 'float64'

### Minimal Complete Verifiable Example

```Python
import numpy as np
import netCDF4
# remove the output test file if it exists
! [ -f test.nc ] && rm test.nc

# generate an array of time values
t_vals=np.arange(0, 2, 0.1)

# write the array to an netcdf file with units 'nanoseconds':
fh_out=netCDF4.Dataset('test.nc', 'w', format="NETCDF4")
fh_out.setncattr('Conventions','CF-1.6')
delta_t_dim = fh_out.createDimension('delta_t', t_vals.size)
dsetvar = fh_out.createVariable('delta_t',
                                    'f8',
                                    ('delta_t'),
                                    zlib=True,
                                    fill_value=9999)
dsetvar[:] = t_vals.ravel()
dsetvar.setncattr('units', 'nanoseconds'.encode('utf-8'))
fh_out.close()

# report the input and show how the values are represented in xarray:
print('original values:')
print(t_vals)

import xarray as xr
ds=xr.open_dataset('test.nc')
print('values read by xarray:')
print(ds['delta_t'].values)

import h5py
with h5py.File('test.nc','r') as fh:
    dt_from_h5py=np.array(fh['delta_t'])
print('values read by h5py:')
print(dt_from_h5py)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
original values:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]
values read by xarray:
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
values read by h5py:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]
```

### Anything else we need to know?

in the example, 'delta_t' is created as a dimension. The same thing would happen if 'delta_t' were not a dimension, and were attached to a different dimension variable.

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
python-bits: 64
OS: Darwin
OS-release: 22.5.0
machine: arm64
processor: arm
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.2
libnetcdf: 4.9.2

xarray: 2023.10.1
pandas: 2.1.3
numpy: 1.26.0
scipy: 1.11.3
netCDF4: 1.6.5
pydap: None
h5netcdf: None
h5py: 3.10.0
Nio: None
zarr: None
cftime: 1.6.3
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.11.0
distributed: 2023.11.0
matplotlib: 3.8.1
cartopy: 0.22.0
seaborn: None
numbagg: None
fsspec: 2023.10.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 68.2.2
pip: 23.3.1
conda: 23.10.0
pytest: None
mypy: None
IPython: 8.17.2
sphinx: 7.2.6

</details>

**Comment by spencerkclark** [comment]
When opening a dataset, xarray will automatically try to decode any variables with time-like units (e.g. `"nanoseconds"`) into `timedelta64[ns]` values, making the assumption that this is what the user would like most of the time.  It is obviously problematic in this instance, however, not least due to xarray's rigid use of nanosecond-precision `timedelta64` values.  

Fortunately it is possible to turn this off by passing `decode_timedelta=False` to `open_dataset`:  

```python
ds = xr.open_dataset("test.nc", decode_timedelta=False)
```

In this case `"delta_t"` in your example should retain its precision and data type when read in.

**Comment by SmithB** [comment]
Great! That works perfectly, and in my actual code, where I also had a 'time' variable that _was_ supposed to be treated as a datetime, xarray made the right choice with that variable too.

Thanks for your help!
