### ISSUE TITLE
Test failures on `main`

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#8522]
### What is your issue?

Any ideas what could be causing these? I can't immediately reproduce locally.

https://github.com/pydata/xarray/actions/runs/7105414268/job/19342564583

```
Error: TestDataArray.test_computation_objects[int64-method_groupby_bins-data]

AssertionError: Left and right DataArray objects are not close

Differing values:
L
    <Quantity([[     nan      nan 1.       1.      ]
     [2.       2.       3.       3.      ]
     [4.       4.       5.       5.      ]
     [6.       6.       7.       7.      ]
     [8.       8.       9.       9.333333]], 'meter')>
R
    <Quantity([[0.       0.       1.       1.      ]
     [2.       2.       3.       3.      ]
     [4.       4.       5.       5.      ]
     [6.       6.       7.       7.      ]
     [8.       8.       9.       9.333333]], 'meter')>
```

**Comment by dcherian** [comment]
These test compare ops with and without units (pint arrays). Without units, we run with flox (& numbagg), with units, we run the for-loop.

Here sadly it appears to be numbagg, or really something bizarre with numba:
https://github.com/numbagg/numbagg/issues/213

**Comment by max-sixty** [comment]
![image](https://github.com/pydata/xarray/assets/5635139/59ae67de-c9fe-46d1-aa11-7f4f1a394d45)

https://github.com/numbagg/numbagg/releases/tag/v0.6.6 — should hit `main` when the cache refreshes. I'm still not satisfied that the bug is gone, and we really need fuzz tests given that the foundation isn't as stable as I thought.

I think if we find another of these, we should disable numbagg by default until we're satisfied — numerical errors are really insidious and basically have no tradeoff against perf...

**Comment by max-sixty** [comment]
> > we really need fuzz tests
> 
> Something like [`hypothesis.extra.numpy.floating_dtypes`](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.numpy.floating_dtypes)?

Yes! Though my message was unclear — I meant "we" as "numbagg". I'm much less worried that xarray is introducing numerical bugs.

**Comment by max-sixty** [comment]
Ah perfect, yes agree, thanks
