### ISSUE TITLE
Open PID with Xarray

### ISSUE THREAD

**Issue by Marco-DKRZ** [pydata/xarray#8528]
### Is your feature request related to a problem?

Is it possible to implement a feature, which enables intake-xarray to open a file based on its PID?

For example:

```
intake.open('hdl:21.14100/02c6b729-fff6-4f31-a8da-2cf590b544df')
```

In this example `hdl:21.14100/02c6b729-fff6-4f31-a8da-2cf590b544df` is a PID handle of a CMIP6 precipitation data set.

**Comment by max-sixty** [comment]
Should this be at https://github.com/intake/intake-xarray ?

**Comment by Marco-DKRZ** [comment]
Yes, I posted it there. Thanks!
