### ISSUE TITLE
nc file reading is not working when nc_path liking '\\\***á**\**\**' including 'á'

### ISSUE THREAD

**Issue by gitxiaobai667** [pydata/xarray#8529]
### What happened?

nc file reading is not working when nc_path liking '\\\***á**\**\**' including 'á'
such as :
dataset = xr.read_dataset(r'c:\admin\Paraná\data.nc')

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [ ] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>
import xarray as xr

dataset = xr.open_dataset(r'c:\admin\Paraná.nc')

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\admin\\Paraná.nc'

</details>

**Comment by max-sixty** [comment]
Please open an issue following the template
