### ISSUE TITLE
TST: Py.test

### ISSUE THREAD

**Issue by MaximilianR** [pydata/xarray#853]
What do we think about switching to py.test? 

Current tests pass with py.test. Then we can use its features for new tests, while the old ones will continue working.

**Comment by shoyer** [comment]
I think we already switched to pytest on Travis, though we don't use any pytest specific features currently. @jhamman was pretty excited about this if I recall correctly.

**Comment by jhamman** [comment]
@MaximilianR - pytest is great.  I prefer its test syntax to the standard `UnitTest` framework.  We can write tests using either right now.  Is your question about whether or not we want to start moving our syntax over?

**Comment by MaximilianR** [comment]
OK great, I will start using the py.test syntax from now. I had thought we were still on nosetests.
