### ISSUE TITLE
Cannot read a nc file  that contains  the diacritic mark tilde (á) in the path

### ISSUE THREAD

**Issue by gitxiaobai667** [pydata/xarray#8530]
### What is your issue?

When I use xarray to open a nc file that contains  the diacritic mark tilde (á) in the path, I get an error

import xarray as xr
dataset = xr.open_dataset(r'c:\admin\Paraná.nc')

FileNotFoundError: [Errno 2] No such file or directory: 'c:\admin\Paraná.nc'

**Comment by max-sixty** [comment]
@gitxiaobai667 please fill out the full bug report template. We're a friendly community — I really don't want to be closing issues that folks open — but you do need follow the instructions for bug reports. 

An example would involve saving a file with a diacritic and then attempting to open it, so others can copy & paste the example and see it reproduce. There are links in the template for more information on a good MCVE.
