### ISSUE TITLE
DataArray types must be strings

### ISSUE THREAD

**Issue by maresb** [pydata/xarray#8546]
### What happened?

While trying to understand the way dimensions are typed in `namedarray` I was confused by the requirement that dimension names must be strings:

```python
>>> da = xr.DataArray(data=[1,2,3], dims=[7])
TypeError: dimension 7 is not a string
```

However, the type hints suggest that dimension names can more generally be `Hashable`. According to @headtr1ck's [post](https://github.com/pydata/xarray/pull/8294#issuecomment-1852714645), the desired behavior is that `Hashable` dimension names should be allowed, so this `TypeError` may be considered a bug.

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 5.15.0-89-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.2
libnetcdf: 4.9.2

xarray: 2023.11.0
pandas: 1.5.3
numpy: 1.26.2
scipy: 1.11.4
netCDF4: 1.6.5
pydap: None
h5netcdf: 1.3.0
h5py: 3.10.0
Nio: None
zarr: 2.16.1
cftime: 1.6.3
nc_time_axis: None
iris: None
bottleneck: None
dask: 2023.11.0
distributed: 2023.11.0
matplotlib: 3.8.2
cartopy: 0.22.0
seaborn: 0.13.0
numbagg: None
fsspec: 2023.10.0
cupy: None
pint: None
sparse: 0.14.0
flox: 0.8.3
numpy_groupies: 0.10.2
setuptools: 68.2.2
pip: 23.3.1
conda: 23.10.0
pytest: 7.4.3
mypy: 1.7.1
IPython: 8.18.0
sphinx: None
[/opt/conda/lib/python3.11/site-packages/_distutils_hack/__init__.py:33](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f6d617265732f7265706f732f6174747269627574696f6e222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f686f6d652f6d617265732f7265706f732f6174747269627574696f6e2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f686f6d652f6d617265732f7265706f732f6174747269627574696f6e2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f686f6d652f6d617265732f7265706f732f6174747269627574696f6e2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/_distutils_hack/__init__.py:33): UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

</details>

**Comment by max-sixty** [comment]
Yes, I'm not sure why that check is there. Probably it should be replaced with a check for `Hashable` — at least we could make the change that and confirm nothing breaks.

PRs welcome!

Notably it is possible to make a Dataset with a non-string dim name:

```python
xr.Dataset(dict(x=((7,),[1,2,3])))
Out[4]:
<xarray.Dataset>
Dimensions:  (7: 3)
Dimensions without coordinates: 7
Data variables:
    x        (7) int64 1 2 3

```
