### ISSUE TITLE
Make _obj_repr public

### ISSUE THREAD

**Issue by BENR0** [pydata/xarray#8551]
### What is your issue?

We are using https://github.com/pydata/xarray/blob/2971994ef1dd67f44fe59e846c62b47e1e5b240b/xarray/core/formatting_html.py#L278

in the html representation of `AreaDefinitions` in https://github.com/pytroll/pyresample and don't like to import private functions.
Would it be OK to make `_obj_repr` public?

**Comment by max-sixty** [comment]
Does anyone have an objection to this? Otherwise I think we'd accept a PR doing this?

**Comment by dcherian** [comment]
I do. We should be free to freely change this stuff if/when we want to.

@BENR0 please copy this over if you like it :)

**Comment by BENR0** [comment]
@dcherian indeed we like it :-). We already discussed coping it over and decided not to in order to not repeat code and we think there is actually no need. We totally agree and understand that you want to retain freedom to change things and we are fine with it.

Just to add a little more context; what we basically want/do is the "official" html representation of a `DataArray`. The only reason we don't use the public https://github.com/pydata/xarray/blob/2971994ef1dd67f44fe59e846c62b47e1e5b240b/xarray/core/formatting_html.py#L300 is because we want to customize the header components and the sections a little bit.

I hope that this makes our intention a little bit clearer.
So in the unlikely case that any future changes of this should not be to our liking or should break something we would fix it on our side.
