### ISSUE TITLE
add py3.12 CI and update pyproject.toml

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#8580]
### What is your issue?

We haven't done this yet!
https://github.com/pydata/xarray/blob/d87ba61c957fc3af77251ca6db0f6bccca1acb82/pyproject.toml#L11-L15

**Comment by jhamman** [comment]
I think @keewis tried 3.12 back in Nov but it wasn't ready. https://github.com/pydata/xarray/pull/8416. Would be great to revisit.

**Comment by keewis** [comment]
:+1:

Typically it's `numba` that takes a while, so we'd need to remove it (and `sparse` / `numbagg`) from the environment. For 3.11 I created a separate environment file (two files, all and windows), we could do the same for 3.12
