### ISSUE TITLE
Don't overwrite indexes for region writes, always

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#8589]
### What happened?

Currently we don't overwrite indexes when `region="auto"`
https://github.com/pydata/xarray/blob/e6ccedb56ed4bc8d0b7c1f16ab325795330fb19a/xarray/backends/api.py#L1769-L1770

I propose we do this for all region writes and completely disallow modifying indexes with a region write.

This would match the `map_blocks` model, where all indexes are specified in the `template` and no changes by the mapped function are allowed.

**Comment by max-sixty** [comment]
Very much agree!

IIRC, currently it's disallowed to write indexes that don't contain the region (writing any var that doesn't contain the region is disallowed)

So this is only an issue for indexes which do contain the region. Historically the index would generally have been dropped manually; makes sense to exclude it.

---

(I also thought about whether this was an issue for other variables which had fewer bigger chunks. But actually this is disallowed in zarr, it's only the index that can have different chunks)

**Comment by slevang** [comment]
There was a bunch of discussion about this on #8434 - I'm in favor. I decided to take the smaller step on that PR for only `region="auto"` writes (where this is definitely not safe for distributed use) because I hadn't thought through all the edge cases.
