### ISSUE TITLE
What is standard way to avoid linter warning?

### ISSUE THREAD

**Issue by arafune** [pydata/xarray#8614]
### What is your issue?

I think the idea of "composition over inheritance" in Xarray is excellent, but please instruct me on the fundamental approach to address the following issue.

Prepare the following code as a library (this is the code directly from https://docs.xarray.dev/en/stable/internals/extending-xarray.html).

test_xarray_extension.py:
```python
import xarray as xr

@xr.register_dataset_accessor("geo")
class GeoAccessor:
    def __init__(self, xarray_obj):
        self._obj = xarray_obj
        self._center = None
    @property
    def center(self):
        """Return the geographic center point of this dataset."""
        if self._center is None:
            lon = self._obj.latitude
            lat = self._obj.longitude
            self._center = (float(lon.mean()), float(lat.mean()))
        return self._center


```

Then, prepare the following file using this library (this is also the code directly from https://docs.xarray.dev/en/stable/internals/extending-xarray.html).

test.py
```python
import test_xarray_extension
import xarray as xr
import numpy as np

ds = xr.Dataset({"longitude": np.linspace(0, 10), "latitude": np.linspace(0, 20)})
```

When applying a linter like 'ruff' to test.py, the error "F401 [*] test_xarray_extension imported but unused" is raised.

Is there a standard way to address this without using 

```python
import test_xarray_extension: #noqa F401?
```

**Comment by max-sixty** [comment]
You could do something like `_ = test_xarray_extension`... (but this isn't really an xarray question, so closing)
