### ISSUE TITLE
TypeError: invalid type promotion when reading multi-file dataset

### ISSUE THREAD

**Issue by mangecoeur** [pydata/xarray#864]
I'm trying to select data from a collection of weather files. Xarray opens the multifile dataset perfectly, but when I try the following selection:

``` python

cfsr_new = xr.open_mfdataset('*.grb2.nc')

lon_sel = np.array(cfsr_new.lon[np.array([3, 4, 8])])
lat_sel = np.array(cfsr_new.lat[np.array([2, 3, 4])])
time_sel = cfsr_new.time[100:200]

selection = cfsr_new.sel(lon=lon_sel, lat=lat_sel, time=time_sel)
selection.to_array()

```

I get:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-3f04c6458da2> in <module>()
----> 1 selection.to_array()

/Users/<user>/anaconda/lib/python3.5/site-packages/xarray/core/dataset.py in to_array(self, dim, name)
   1847         data_vars = [self.variables[k] for k in self.data_vars]
   1848         broadcast_vars = broadcast_variables(*data_vars)
-> 1849         data = ops.stack([b.data for b in broadcast_vars], axis=0)
   1850 
   1851         coords = dict(self.coords)

/Users/<user>//anaconda/lib/python3.5/site-packages/xarray/core/ops.py in f(*args, **kwargs)
     65             else:
     66                 module = eager_module
---> 67             return getattr(module, name)(*args, **kwargs)
     68     else:
     69         def f(data, *args, **kwargs):

/Users/<user>//anaconda/lib/python3.5/site-packages/dask/array/core.py in stack(seq, axis)
   1754 
   1755     if all(a._dtype is not None for a in seq):
-> 1756         dt = reduce(np.promote_types, [a._dtype for a in seq])
   1757     else:
   1758         dt = None

/Users/<user>//anaconda/lib/python3.5/site-packages/toolz/functoolz.py in __call__(self, *args, **kwargs)
    217     def __call__(self, *args, **kwargs):
    218         try:
--> 219             return self._partial(*args, **kwargs)
    220         except TypeError:
    221             # If there was a genuine TypeError

TypeError: invalid type promotion


```

**Comment by mangecoeur** [comment]
On further investigation, it appears the problem is the dataset contains a mix of string and float data - the strings are redundant representations of the time stamp, therefore they don't appear in the index query. Explicitly selecting on the desired data variable solves this: 

`selection = cfsr_new.TMP_L103.sel(lon=lon_sel, lat=lat_sel, time=time_sel)`

I think a clearer error message may be needed: when you do `sel` without indexing on certain dimensions, those are included in the resulting selection. It's possible for those to be of mixed incompatible types. Clearly  to do `to_array` you need a numpy-friendly uniform type. The error should make this clearer.

**Comment by shoyer** [comment]
What are the types of the incompatible arrays? This certainly is not desirable for xarray -- we'd like to be able to stack these arrays together, into a lowest compatible dtype (even if that's only object). I think the main issue here is actually in dask.array, but it would be nice to be able to provide them with a minimal example.
