### ISSUE TITLE
How to reduce the output size with to_netcdf?

### ISSUE THREAD

**Issue by simon3122** [pydata/xarray#865]
Hello, 

The options of the ds.to_netcdf method allow several netcdf modes and a control of several options (missing values, format...).

Our current options are as follows:

ds.to_netcdf(filenam,
                       'w',
                       'NETCDF4',
                       'netcdf4',
                       encoding={ vkey2:{'dtype': float32,'_FillValue':0}})

Whereas the input size is 6 GiB / variable, the output size reaches 23 GiB / variable.

What is the best strategy in the options to reduce the netcdf output size, other than changing the format (in my exercice we have float32)?
In particular, is there some interest in modifying the deprecated "missing_values" attribute?

Thank you in advance,

**Comment by fmaussion** [comment]
NetCDF and xarray support lossy compression (extremely efficient and fast with the cost of numerical precision loss) or gzip compression (without precision loss but with slower I/O - especially when reading chunks of data). You can have a look at the documentation about NetCDF I/O [here](http://xarray.pydata.org/en/stable/io.html#netcdf).

**Comment by marcosrdac** [comment]
How do I get lossy compression? I could not find it on the documentation :(

**Comment by dcherian** [comment]
Please read the [documentation](https://docs.xarray.dev/en/stable/user-guide/io.html#writing-encoded-data)

**Comment by marcosrdac** [comment]
Thanks, I thought there were some methods to choose from or something like that. For future readers, `scale_factor` seems to be used to control compression loss.

**Comment by dcherian** [comment]
You can also use [zlib=True](https://docs.xarray.dev/en/stable/user-guide/io.html#chunk-based-compression)

**Comment by marcosrdac** [comment]
> You can also use [zlib and complevel](https://docs.xarray.dev/en/stable/user-guide/io.html#chunk-based-compression)

Just making it clear: those would configure lossless compression of netcdf4 lib, not lossy compression.
