### ISSUE TITLE
dtype encoding ignored during IO?

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#8660]
### What happened?

When I set the `.encoding['dtype']` attribute before saving a to disk, the actual on-disk representation appears to store a record of the dtype encoding, but when opening it back up in xarray I get the same dtype I had before, not the one specified in the encoding. Is that what's supposed to happen? How does this work? (This happens with both zarr and netCDF.)

### What did you expect to happen?

I expected that setting `.encoding['dtype']` would mean that once I open the data back up, it would be in the new dtype that I set in the encoding.

### Minimal Complete Verifiable Example

```Python
air = xr.tutorial.open_dataset('air_temperature')

air['air'].dtype  # returns dtype('float32')

air['air'].encoding['dtype']  # returns dtype('int16'), which already seems weird

air.to_zarr('air.zarr')  # I would assume here that the encoding actually does something during IO

# now if I check the zarr `.zarray` metadata for the `air` variable it says 
`"dtype": `"<i2"`

air2 = xr.open_dataset('air.zarr', engine='zarr')  # open it back up

air2['air'].dtype  # returns dtype('float32'), but I expected dtype('int16')


(the same thing happens also with saving to netCDF instead of Zarr)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Anything else we need to know?

I know I didn't explicitly cast with `.asdtype`, but I'm still confused as to what the relation between the dtype encoding is supposed to be here.

I am probably just misunderstanding how this is supposed to work, but then this is arguably a docs issue, because [here it says]( https://xarray.pydata.org/en/v2024.01.1/user-guide/io.html#scaling-and-type-conversions) "[the encoding dtype field] controls the type of the data written on disk", which I would have thought also affects the data you get back when you open it up again?

### Environment

`main` branch of xarray

**Comment by kmuehlbauer** [comment]
This is packed data (floating point data packed into short int on disk). See also the compled `encoding`-dict for `scale_factor`. This is CF convention and triggers CF coding/decoding.

Packing/unpacking is done during cf-encoding/decoding. When saving you should get a SerializationError because no `_FillValue` is given.

So from what I can tell everything is good here.

**Comment by kmuehlbauer** [comment]
@TomNicholas Does my above comment shed some light here? Can this be closed then? I can get more into details if necessary.

**Comment by TomNicholas** [comment]
I think I get it now, thanks!
