### ISSUE TITLE
Typo for `variables` arg API docstring in `xarray.core.Dataset.sortby`

### ISSUE THREAD

**Issue by tomvothecoder** [pydata/xarray#8663]
### What is your issue?

Just something I caught while looking at the docs. I think this should be `variables`?

https://github.com/pydata/xarray/blob/d639d6e151bdeba070127aa7e286c5bfa6048194/xarray/core/dataset.py#L7925
https://github.com/pydata/xarray/blob/d639d6e151bdeba070127aa7e286c5bfa6048194/xarray/core/dataset.py#L7948-L7953

**Comment by max-sixty** [comment]
Thanks — a small PR would be v welcome!

**Comment by tomvothecoder** [comment]
@max-sixty Just opened in #8670
