### ISSUE TITLE
Wrong sum of boolean negation

### ISSUE THREAD

**Issue by gunnarvoet** [pydata/xarray#8685]
### What happened?

I get the wrong answer when I chain boolean negation with sum(). It works when I put parentheses around the negation, or when I first write the negation result to a new variable. See code example.

### Minimal Complete Verifiable Example

```Python
import numpy as np
import xarray as xr

data = np.array([True, False, True, False])
test = xr.DataArray(data, coords=dict(x=np.arange(4)))

assert np.sum(test) == 2
assert test.sum(dim="x") == 2

assert np.sum(~test) == 2
(~test).sum(dim="x") == 2
tmp = ~test
assert tmp.sum(dim="x") == 2
assert ~test.sum(dim="x") == 2, f"not 2: {~test.sum(dim='x').data}" # returns -3
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
AssertionError                            Traceback (most recent call last)
File example.py:14
     12 tmp = ~test
     13 assert tmp.sum(dim="x") == 2
---> 14 assert ~test.sum(dim="x") == 2, f"not 2: {~test.sum(dim='x').data}" # returns -3

AssertionError: not 2: -3
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 23.2.0
machine: arm64
processor: arm
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2024.1.1
pandas: 2.2.0
numpy: 1.26.3
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 69.0.3
pip: 23.3.2
conda: None
pytest: None
mypy: None
IPython: 8.20.0
sphinx: None

</details>

**Comment by Ockenfuss** [comment]
This is actually expected behaviour in python. If you do `~test.sum(dim="x")`, the call to `sum()` has a higher precedence than the bitwise invert operator, represented by `~`. Therefore, `test.sum(dim='x')` evaluates to `2` and then `~2` evaluates to `-3`. The latter is due to the way integers are represented as bits in python.

In general, it might be better to use `np.logical_not(test)` in order to invert the array. `logical_not` also works in case your data consists of integers instead of booleans:
```python
import numpy as np
import xarray as xr

data_int=np.array([1, 0, 1, 0])
test_int=xr.DataArray(data_int, coords=dict(x=np.arange(4)))
assert np.logical_not(test_int).sum(dim='x')==2 #works
assert (~test_int).sum(dim='x')==2 #fails
```

**Comment by gunnarvoet** [comment]
Thanks so much for explaining this in detail, @Ockenfuss and my apologies for taking up your time! I thought the expression would evaluate from left to right. Using `np.logical_not()` is a great suggestion.
