### ISSUE TITLE
open netCDF gives 'time' dim with 1969 change in timezone

### ISSUE THREAD

**Issue by brews** [pydata/xarray#869]
I'm on xarray version 0.7.2
netCDF4-python version 1.2.2
Python version via Conda: 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

The `time` dim on Datasets read in from netCDF files seems to change timezones in 1969. This is especially a pain for annual data because the bug causes annual indexes to shift by one year. I've seen this problem in reanalysis for NCEP/NCAR, Twentieth Century Reanalysis, and some reconstructed SST fields.

For example, if a read in a netCDF file. Take NCEP/NCAR Reanalysis 1 monthly mean geopotential height as an example (ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis.derived/pressure/hgt.mon.mean.nc ; a 278 MB file).

```python
import xarray as xr

ds = xr.open_dataset('~/Downloads/hgt.mon.mean.nc')
print(ds.time)
```

The interesting part of this printed time dim is always around 1969:

       ...
       '1969-09-01T00:00:00.000000000Z', '1969-10-01T00:00:00.000000000Z',
       '1969-11-01T00:00:00.000000000Z', '1969-12-01T00:00:00.000000000Z',
       '1969-12-31T17:00:00.000000000-0700',
       '1970-01-31T17:00:00.000000000-0700',
       '1970-02-28T17:00:00.000000000-0700',
        ...

You can see we go from `Z` to`-0700`. It also gives me an extra measure for Dec 1969 :-\

I don't think this is a hidden calendar or datetime-like feature that I'm unaware of...? Seems like a bug with you guys or upstream.

Thanks for your help!

**Comment by brews** [comment]
I can also get this to happen if I read in my own netCDF files

**Comment by fmaussion** [comment]
This is a guess, but I bet you have numpy 1.10. Try to update to 1.11:

http://docs.scipy.org/doc/numpy-dev/reference/arrays.datetime.html#changes-with-numpy-1-11

**Comment by brews** [comment]
@fmaussion Yes this solves the problem! Closed.

Now the problem is that my Basemap and Cartopy 0.14 in conda currently depend on numpy 1.10*. This puts me in Dependency Hell.

Does anyone happen to have a channel for these (or at least Cartopy 0.14) that will work with numpy 1.11*?

**Comment by fmaussion** [comment]
The best channel out there is definitely conda-forge: https://conda-forge.github.io/

Check it out!

**Comment by brews** [comment]
Wow. How did I not know about conda-forge?

They even have a windspharm for py3! I owe you a beer @fmaussion!

Thanks again.

**Comment by shoyer** [comment]
+1 for conda-forge. We should add a note about it to the install page.
