### ISSUE TITLE
Failing arithmetic operations with xarray.DataArray defined with chunks and lock=False

### ISSUE THREAD

**Issue by lesommer** [pydata/xarray#871]
Trying to understand what was raising an exception with several methods associated to oocgcm grid objects that have been sliced ([see](https://github.com/lesommer/oocgcm/issues/33)), I have identified what I think might be an **issue when slicing xarray.DataArray defined with dask chunks + lock=False**. 

A illustration of the issue can be found [in this notebook](https://github.com/lesommer/notebooks/blob/master/Chunking_with_dask_problem.ipynb). I am afraid my understanding of xarray/dask is not sufficient for me to suggest a fix.

**Comment by shoyer** [comment]
This is a likely regression in dask:
https://github.com/dask/dask/issues/1235

**Comment by shoyer** [comment]
This has now been fixed in dask! https://github.com/dask/dask/pull/1246
