### ISSUE TITLE
Error in examples/multidimensional-coords.html

### ISSUE THREAD

**Issue by pierre-manchon** [pydata/xarray#8722]
### What is your issue?

I noticed an error and a warning when reading this [page](https://docs.xarray.dev/en/latest/examples/multidimensional-coords.html) of the documentation:
- At the bottom of the page, there is an empty cell (below Note: This group-by-latitude approach...)
- The first cell with the imports outputs this warning message:
```
/tmp/ipykernel_3637/1780901418.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
```

**Comment by kmuehlbauer** [comment]
@pierre-manchon Sorry for the massive delay here. Thanks for spotting this. The first thing seems fixed. The additional cell is still there.
