### ISSUE TITLE
PRs requiring approval & merging main?

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#8726]
### What is your issue?

Sorry I haven't been on the calls at all recently (unfortunately the schedule is difficult for me). Maybe this was discussed there? 

PRs now seem to require a separate approval prior to merging. Is there an upside to this? Is there any difference between those who can approve and those who can merge? Otherwise it just seems like more clicking.

PRs also now seem to require merging the latest main prior to merging? I get there's some theoretical value to this, because changes can semantically conflict with each other. But it's extremely rare that this actually happens (can we point to cases?), and it limits the immediacy & throughput of PRs. If the bad outcome does ever happen, we find out quickly when main tests fail and can revert.

<img width="434" alt="image" src="https://github.com/pydata/xarray/assets/5635139/bc88bdb0-9418-4182-a563-b5c44697a4ea">

(fwiw I wrote a few principles around this down a while ago [here](https://prql-lang.org/book/project/contributing/development.html#merges); those are much stronger than what I'm suggesting in this issue though)

**Comment by keewis** [comment]
definitely not intentional, that was a side-effect of disabling the branch protection rule when the `datatree` merge happened last week. These options are on by default if you enable the branch protection again, and I simply forgot to disable them. They're off now, so we should be back to the old state.

**Comment by max-sixty** [comment]
Thanks so much @keewis !

**Comment by TomNicholas** [comment]
Are you happy to keep the old way we were doing things @max-sixty ? If so we can close this.

**Comment by max-sixty** [comment]
> Are you happy to keep the old way we were doing things @max-sixty ? If so we can close this now that @keewis has disabled the protections again.

Ofc!

Sorry for my slight diatribe above, I had thought just asking "did you really mean to do this" would be too oblique, but in fact sounds like no one did intend it :)
