### ISSUE TITLE
Passing datasets with different group hierarchy to open_mfdataset 

### ISSUE THREAD

**Issue by KareemShalabi** [pydata/xarray#8759]
### Is your feature request related to a problem?

When you want to open multiple datasets located at different nodes of group hierarchy in HDF file, you can't pass a list of group keys ( save_mfdataset offers 'groups' keyword; emphasis on the s). Add to that, the 'files' keyword argument does not accept 'datastore' as a valid input. 

### Describe alternatives you've considered

One, of course, can open_dataset each one in a loop and combine afterwards. One possible fix is to Modify the 'group' argument to accept a list the same length as paths list. Another could be changing "paths" keyword to accept datastore or h5py objects. Both are trivial in my opinion. Most of the code is already there in other functions (open_dataset, save_mfdataset).

**Comment by TomNicholas** [comment]
Would opening all the groups at once using [`xarray-datatree`](https://github.com/xarray-contrib/datatree) help with your use case?

**Comment by KareemShalabi** [comment]
> Would opening all the groups at once using [`xarray-datatree`](https://github.com/xarray-contrib/datatree) help with your use case?

Thank you! Datatree is exactly what I was looking for. This should be advertised more.

**Comment by TomNicholas** [comment]
Yeah we're working on that :)
