### ISSUE TITLE
xarray.ufuncs.maximum() between constant and dask array

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#876]
Take a dask-backed array:
`a = xarray.DataArray(dask.array.random.random(100 * 2**30, chunks=2**20))`
This works:
`b = xarray.ufuncs.maximum(a, 0)`
This will cripple your computer and force you to reboot:
`b = xarray.ufuncs.maximum(0, a)`

In the second case, xarray.ufuncs.maximum is resolving the dask array - in other wods, it's doing numpy.maximum(0, a.values)

**Comment by shoyer** [comment]
Yikes -- that's a bug. I'll take a look.
