### ISSUE TITLE
Bug Report: The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click here for more info. View Jupyter log for further details

### ISSUE THREAD

**Issue by silencesoup** [pydata/xarray#8779]
### What happened?

When I open a big nc file (about 20GB), my jupyter kernal crashed and reminds me that it needs more memory. But actually, I have enough MiB for it.
And when I downgrade my xarray version from 2024.1.1 to 2023.7.0, it fixed.
So there might be some bug in the new version of xarray.

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [ ] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<The useful version. I uninstall the new version, so i only get this>
INSTALLED VERSIONS
------------------
commit: None
python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-169-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.3-development

xarray: 2023.7.0
pandas: 1.5.3
numpy: 1.23.5
scipy: 1.11.4
netCDF4: 1.6.5
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.3
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2024.1.0
distributed: 2024.1.0
matplotlib: 3.5.3
cartopy: 0.22.0
seaborn: 0.12.2
numbagg: None
fsspec: 2023.12.2
cupy: None
pint: 0.23
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.5.1
pip: 23.3.1
conda: None
pytest: 7.4.4
mypy: None
IPython: 8.20.0
sphinx: None

</details>

**Comment by max-sixty** [comment]
Unfortunately we'd need much much more info to make progress here, including reproducible examples.
