### ISSUE TITLE
Difficult to convert `pd.DataFrame` to `Dataset` with multi-index

### ISSUE THREAD

**Issue by staadecker** [pydata/xarray#8794]
## No direct way to create multi-index dataset

Unless I'm missing something, there is no easy way to convert a Pandas dataframe to a dataset with a multi-index. For example, `xr.Dataset.from_dataframe` automatically converts any Pandas multi-index into separate dimensions.

## Workaround is inefficient

One workaround is doing `xr.Dataset.from_dataframe(df).stack(...)` however this is very inefficient for sparse multi-indices.

**Comment by max-sixty** [comment]
Does `xr.Dataset(df)` work?

**Comment by staadecker** [comment]
@max-sixty yes it does. Thank you! I submitted a pull request to add this to the documentation.
