### ISSUE TITLE
Python deprecation/ future missing dependency warning in documentation

### ISSUE THREAD

**Issue by paradx** [pydata/xarray#8805]
### What is your issue?

The documentation article [here](https://docs.xarray.dev/en/stable/examples/multidimensional-coords.html) is showing the following warning: 
```
/tmp/ipykernel_3629/1780901418.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
``` 
I guess the jupyter notebook under the hood of the EBP is missing this dependency. 
Just something to keep in mind when xarray is bumping the pandas version.

**Comment by max-sixty** [comment]
Thanks. We could add pyarrow to the docs' conda environment to silence this, would be a welcome small PR...

**Comment by BadakalaYashwanth** [comment]
In the next main version (pandas 3.0), the future release of pandas will include yarrow as a must-install library. It aims to have the Arrow string type quicker data types among others and improved interoperability with various libraries. The availability of Pyarrow on systems where Pandas is used may be essential for their normal functioning as it might raise problems with data conversion or compatibility.
