### ISSUE TITLE
ENH: Allow ds selection with callable?

### ISSUE THREAD

**Issue by MaximilianR** [pydata/xarray#883]
Inspired by: https://github.com/pydata/xarray/pull/844. This is a more general case for variable selection.

We could allow a selection of variables with a callable, similar (but not the same) as pandas' implementation:

```python
In [5]: ds=xr.Dataset({'a': (('x', 'y'), np.random.rand(10,2))})
Out[4]: 
<xarray.Dataset>
Dimensions:  (x: 10, y: 2)
Coordinates:
  * x        (x) int64 0 1 2 3 4 5 6 7 8 9
  * y        (y) int64 0 1
Data variables:
    a        (x, y) float64 0.5819 0.1214 0.2645 0.9053 0.6968 0.1608 0.3199 ...

In [9]: ds['a'].attrs['clean'] = True

# potentially:
In [10]: ds[lambda x: x.attrs['clean']]
#... would return ds['a']
```

This would mean functions wouldn't be able to be dataset keys - I don't think that's a big issue, but could arise with callable classes, for example.

Another option would be a `.filter` / `.select` method or indexer.

**Comment by shoyer** [comment]
There are possibly a few issues to work through here, I like the look of it!

**Comment by shoyer** [comment]
I would slightly rather put this in a generic `select` or `filter` method (xref https://github.com/pydata/xarray/issues/916) than overload indexing further. Mostly, I am concerned that this is slightly different from the way pandas handles callables in indexing, which is to apply the callable to the object being indexed.

I'm thinking a signature something like `Dataset.filter(func=None, like=None, regex=None)` (see [here](https://github.com/pydata/pandas/blob/136794524a8f8954c0b8bf8f0327870d83cbf8d4/pandas/core/generic.py#L2382) for how filter is implemented in pandas). This does have the downside that it departs from pandas syntax by combining filter and select, but these are very related ways of filtering a dataset so it seems better to keep them in one method.

**Comment by MaximilianR** [comment]
That makes sense. I'll close this and we can move to #916.
