### ISSUE TITLE
Get ready for pandas 3 copy-on-write

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#8843]
### What is your issue?

This line fails with `pd.set_options("mode.copy_on_write", True)`
https://github.com/pydata/xarray/blob/c9d3084e98d38a7a9488380789a8d0acfde3256f/xarray/tests/__init__.py#L329

We'll need to fix this before Pandas 3 is released in April: https://github.com/pydata/xarray/blob/c9d3084e98d38a7a9488380789a8d0acfde3256f/xarray/tests/__init__.py#L329

Here's a test
```python
def example():
    obj = Dataset()
    obj["dim2"] = ("dim2", 0.5 * np.arange(9))
    obj["time"] = ("time", pd.date_range("2000-01-01", periods=20)
    print({k: v.data.flags for k, v in obj.variables.items()})
    return obj

example()
pd.set_options("mode.copy_on_write", True)
example()
```

**Comment by phofl** [comment]
I would recommend to either copy the data they come from a pandas object or set the flags to writeable if you are ok with the implications or if you don't modify the data inplace anyway. That said, modifying the underlying data of an Index is a __really__ bad idea if you or your users want to re-use the Index. That can lead to segfaults among other things

Be aware if you set the flag to writeable, this is not possible in all scenarios, e.g.

```
idx = pd.Index([1, 2, 3], dtype="int64[pyarrow]")
vals = idx.to_numpy()
vals.flags.writeable = True
```

This will raise, arrow protects against this and does not allow you to set the flag to writeable

**Comment by dcherian** [comment]
Thanks @phofl  I suspect this assertion is overly broad and we didn't want to do it for Index-backed Xarray variables.
