### ISSUE TITLE
Docstring for Dataset.drop needs revision

### ISSUE THREAD

**Issue by mcgibbon** [pydata/xarray#885]
The docstring for [Dataset.drop](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.drop.html#xarray.Dataset.drop) indicates that the first argument, labels, should be a string indicating names of variables or index labels to drop. I'm not sure, but I'm guessing it either takes in several strings (in which case the docstring should say *labels), or it takes in either a string or an iterable (in which case the argument type should reflect this).

**Comment by shoyer** [comment]
Thanks for pointing this out -- fixed!
