### ISSUE TITLE
filterwarnings("ignore:invalid value encountered in sqrt") ?

### ISSUE THREAD

**Issue by cyschneck** [pydata/xarray#8863]
### What is your issue?

I am cleaning up some deprecation warnings on a repo and encountered:

`dask/core.py:127: RuntimeWarning: invalid value encountered in sqrt`

I believe the issue is arising within xarray, even though dask is triggering it. I noticed that in the xarray tests, [the same warning is being filtered out to be ignored](https://github.com/pydata/xarray/blob/84dc96136ce04d953746d9e251753ba61d0779f0/xarray/tests/test_weighted.py#L599). 

Do you know where this issue is arising and why is it being filtered?

Simple reproducible form: (Python 3.12, Linux)
```
import xarray as xr
import numpy as np
from geocat.comp import *

t1 = np.array([80, 80, 60, 30])
rh1 = np.array([40, 75, 90, 50])

t = xr.DataArray(t1).chunk(3)
rh = xr.DataArray(rh1).chunk(3)
out = heat_index(t, rh)
print(out.values)
```
Output
```
/home/user/miniconda3/envs/geocat_comp_build/lib/python3.12/site-packages/dask/core.py:127: RuntimeWarning: invalid value encountered in sqrt
  return func(*(_execute_task(a, cache) for a in args))
[79.79      83.5751104 59.965     30.       ]
```

**Comment by dcherian** [comment]
Unfortunately there's not much we can do with dask: https://github.com/dask/dask/issues/3245

aside from setting `np.errstate` inside dask (https://github.com/pydata/xarray/issues/5151 https://github.com/dask/dask/pull/8125)
