### ISSUE TITLE
Rolling reduction with a custom function generates an excesive use of memory that kills the workers

### ISSUE THREAD

**Issue by josephnowak** [pydata/xarray#8894]
### What happened?

Hi, I have been trying to use a custom function on the rolling reduction method, the original function tries to filter the nan values (any numpy function that I have used that handles nans generates the same problem) to later apply some simple aggregate functions, but it is killing all my workers even when the data is very small (I have 7 workers and all of them have 3 Gb of RAM).

### What did you expect to happen?

I would expect less use of memory taking into account the size of the rolling window, the simplicity of the function and the amount of data used on the example.

### Minimal Complete Verifiable Example

```Python
import numpy as np
import dask.array as da
import xarray as xr
import dask


def f(x, axis):
    # If I replace np.nansum by np.sum everything works perfectly and the amount of memory used is very small
    return np.nansum(x, axis=axis)

arr = xr.DataArray(
    dask.array.zeros(
        shape=(300, 30000),
        dtype=float,
        chunks=(30, 6000)
    ),
    dims=["a", "b"],
    coords={"a": list(range(300)), "b": list(range(30000))}
)

arr.rolling(a=252).reduce(f).chunk({"a": 252}).to_zarr("/data/test/test_write", mode="w")
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [ ] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
KilledWorker: Attempted to run task ('nansum-overlap-sum-aggregate-sum-aggregate-e732de6ad917d5f4084b05192ca671c4', 0, 0) on 4 different workers, but all those workers died while running it. The last worker that attempt to run the task was tcp://172.18.0.2:39937. Inspecting worker logs is often a good next step to diagnose what went wrong. For more information see https://distributed.dask.org/en/stable/killed.html.
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 4.14.275-207.503.amzn2.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.3
libnetcdf: None

xarray: 2024.1.0
pandas: 2.2.1
numpy: 1.26.3
scipy: 1.11.4
netCDF4: None
pydap: None
h5netcdf: None
h5py: 3.10.0
Nio: None
zarr: 2.16.1
cftime: None
nc_time_axis: None
iris: None
bottleneck: 1.3.7
dask: 2024.1.0
distributed: 2024.1.0
matplotlib: 3.8.2
cartopy: None
seaborn: 0.13.1
numbagg: 0.7.0
fsspec: 2023.12.2
cupy: None
pint: None
sparse: 0.15.1
flox: 0.8.9
numpy_groupies: 0.10.2
setuptools: 69.0.3
pip: 23.3.2
conda: 23.11.0
pytest: 7.4.4
mypy: None
IPython: 8.20.0
sphinx: None

</details>

**Comment by max-sixty** [comment]
Does it still run out of memory without dask?

**Comment by josephnowak** [comment]
I tried to run the example on a Jupyter notebook without using the Dask Cluster and it killed the kernel and I saw a big memory increase also. I also tried on another machine with 32 Gb of RAM (regularly I have like 16 Gb free) and it was able to process it but it consumed all the free memory, here is the result of the memory_usage function of the memory profiler package:

Memory usage (in chunks of .1 seconds): [246.31640625, 246.31640625, 602.6328125, 1150.5390625, 1789.0078125, 1888.203125, 1511.92578125, 1296.50390625, 1565.1484375, 1823.390625, 2025.6875, 2304.3125, 2706.73828125, 3887.546875, 5178.89453125, 6193.85546875, 7219.06640625, 8253.33203125, 9304.140625, 10351.60546875, 11411.53125, 12410.203125, 13292.63671875, 13770.1953125, 13784.63671875, 13784.63671875, 13784.63671875, 13784.6171875, 13761.09375, 13761.09375, 13761.09375, 13761.09375, 13766.8203125, 13776.703125, 13601.1875, 13417.3125, 13283.19140625, 13276.8046875, 13218.0625, 13042.3515625, 12917.93359375, 12714.50390625, 12666.5546875, 12671.796875, 12712.88671875, 12767.6796875, 12801.01171875, 12589.9140625, 12485.4375, 12385.5, 12373.0, 12319.39453125, 12309.60546875, 12285.734375, 12330.01171875, 12458.54296875, 12606.453125, 12740.640625, 12845.2109375, 12883.2265625, 12990.2890625, 13096.703125, 13193.58984375, 13285.7421875, 13402.71875, 13513.7578125, 13645.5625, 12831.83203125, 11979.36328125, 11036.71875, 11119.0546875, 11300.5859375, 11449.26953125, 10326.234375, 9076.390625, 7625.1953125, 6399.33203125, 5302.48046875, 5043.8984375, 5375.59375, 5729.92578125, 6166.53515625, 6595.8671875, 7056.74609375, 6804.97265625, 5494.52734375, 4114.66015625, 2318.25, 1032.25, 221.56640625, 166.93359375]

**Comment by dcherian** [comment]
It'll almost certainly die without dask.

`rolling.contruct` will 
1. first copy the data to pad with NaNs
2. create a giant virtual view of that copy (no additional memory)
3. now apply your function. `nan*` functions tend to copy data, so this is a copy of the giant virtual array. That is what you're observing. Your `f` needs to be careful about copying its inputs.

**Comment by josephnowak** [comment]
What would be the correct way to avoid copying the giant virtual array? my original function is very similar to the standard rolling sum but with the difference that it has to sum only the last N valid values, with N < window_size.

I was thinking in using the map_overlap function of Dask to simulate the rolling, but I'm not sure if something like that would work.

**Comment by max-sixty** [comment]
> 3\. `nan*` functions tend to copy data, so this is a copy of the giant virtual array.

Ah, thanks @dcherian , that explains the difference between the `nansum` & `sum`

> What would be the correct way to avoid copying the giant virtual array? my original function is very similar to the standard rolling sum but with the difference that it has to sum only the last N valid values, with N < window_size.

Ideally you want to compose existing functions. If that's not possible, you could use `numba`, or even run in a python loop over each item (which would be very slow but would finish).

I think the xarray question is answered so I'll close...

**Comment by josephnowak** [comment]
@max-sixty Sorry for bothering you with this closed issue, but I have tried to use Numba and also tried to run a simple Python loop but none of them works as expected if I'm using Dask (if I just use a regular Numpy array the memory use is normal), do you know if I'm doing something wrong? or do you think that it can be an error on Dask side?

Functions tested:

```py3
import numbagg as nba
import numpy as np
import numba as nb


def f(x, axis):
    def _f(x, axis):
        return nba.nansum(x, axis=axis)
    # Trying to use map blocks instead of apply along axis to see if there is any difference
    arr = x.map_blocks(_f, dtype=float, axis=axis, drop_axis=axis)
    return arr

def f(x, axis):
    # Using numba nansum directly with dask apply along axis
    return da.apply_along_axis(func1d=nb.nansum, arr=x, axis=axis, dtype=x.dtype)

def f(x, axis):
    return da.apply_along_axis(func1d=np.nansum, arr=x, axis=axis, dtype=x.dtype)

def f(x, axis):
    # Using numbagg nansum directly with dask apply along axis
    return da.apply_along_axis(func1d=nba.nansum, arr=x, axis=axis, dtype=x.dtype)
```

**Comment by max-sixty** [comment]
Can you get it to work on a small array without dask?

If you want to have a custom function we'll likely need to write it in numba, unless we can compose it from existing functions. 

We want a function that takes an array+window and returns an array, so it doesn't need to run for each position in the array. 

For example, `move_nan_sum` is the function in numbagg for calculating a moving sum — it runs once over an sequence.

Does that make sense at all?

**Comment by josephnowak** [comment]
Yes, I can make it work with small arrays without Dask, I replaced the Dask arrays with Numpy arrays and used the Numbagg nansum function and everything went well in terms of memory use (even the example that I sent uses 10x less memory).

Yes, that makes sense, thanks for the explanation. Now that I see it, it is a little bit harder to implement custom functions with the reduction function (at least for me). If this is useful for someone else I think that using the map_overlap function of Dask is a good workaround to some of the rolling functionalities (like the sum that can be converted into a cumsum with the map overlap), for me, it solved the memory issue and also made faster some specific calculations like the sum.
