### ISSUE TITLE
Is .persist in place or like .compute?

### ISSUE THREAD

**Issue by saschahofmann** [pydata/xarray#8901]
### What is your issue?

I am playing around with using `Dataset.persist` and assumed it would work like `.load`. I also just looked at the source code and it looks to me like it should indeed replace the original data *but* I can see both in performance and the dask dashboard that steps are recomputed if I don't use the object returned by `.persist` which points me towards `.persist` behaving more like `.compute`.

In either case, I would make a PR to clarify in the docs whether persists leaves the original data untouched or not.

**Comment by keewis** [comment]
in general, there are only very few in-place methods (`.load` and `.update` are the only examples I can think of). As far as the code goes: it creates a (shallow) copy, then replaces the arrays in that copy with the persisted ones. So yes, `persist` does not modify the original object.

A PR would be welcome, but I wonder how to best point this out... maybe by adding return value documentation?

**Comment by keewis** [comment]
see also #6837 for a discussion about the difference between `compute` and `load`.
