### ISSUE TITLE
Variable doesn't have an .expand_dims method

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#8905]
### Is your feature request related to a problem?

`DataArray` and `Dataset` have an `.expand_dims` method, but it looks like `Variable` doesn't. 

### Describe the solution you'd like

Variable should also have this method, the only difference being that it wouldn't create any coordinates or indexes.

**Comment by mobley-trent** [comment]
I'm very interested in working on this issue @TomNicholas

**Comment by TomNicholas** [comment]
You're welcome to open a PR @mobley-trent ! Bear in mind this issue is slightly tricker than I first thought it would be, because the main implementation is in `Dataset.expand_dims`, which would require some refactoring to separate just the code you would need for a single Variable.

**Comment by dcherian** [comment]
I thought @andersy005 added this to NamedArray/

**Comment by TomNicholas** [comment]
Well so he did! And it's inherited onto `Variable`... I must have been using an out-of-date branch or something.

The `Dataset.expand_dims` implementation does not call the `NamedArray` implementation, so maybe that could be refactored, but I guess that means this issue should be closed anyway. Sorry for the noise!
