### ISSUE TITLE
BUG: Test for dask version erroneously fails when calling xr.mfdataset()

### ISSUE THREAD

**Issue by dgoldwx2112** [pydata/xarray#891]
I have latest version of dask installed but get the following exception when using xr.mfdataset():
'ImportError: xarray requires dask version 0.6 or newer'

Problem appears to be due to the fact that the latest version is 0.10 (i.e., dask.__version__ =  '0.10.0') but exception is raised since 0.1 < 0.6

**Comment by shoyer** [comment]
Eep! This was an amateur mistake on our part!

I'll see if we can get a quick bug fix release out. I'm currently on vacation thought so I can't promise an immediate resolution.

**Comment by dgoldwx2112** [comment]
Thanks, Stephan! Enjoy your vacation! For now I am processing multiple files over an opendap connection using netCDF4.MFDataset and then building a DataArray or Dataset from the variables stored within the resulting MFDataset object. This appears much faster than the process recommend here when a lot of big files are involved: http://xarray.pydata.org/en/stable/io.html (i.e., using read_netcdfs). Once a bug fix is implemented, I'll try using the dask-optimized open_mfdataset().
