### ISSUE TITLE
Weird behavior of DataSet.where(... , drop=True)

### ISSUE THREAD

**Issue by johannespletzer** [pydata/xarray#8915]
### What happened?

I work with an aircraft emission dataset that is freely available online: [emission dataset](https://zenodo.org/records/10818082)

During my calculations I eventually convert the `DataSet` to a `DataFrame`. My motivation is to avoid unnecessary rows in the DataFrame. Doing some calculations my code returned unexpected results. Eventually I could narrow it down to a `DataSet.where(... , drop=True)` argument I added along the way, which introduces differences in the data. Here are two examples:

**Example 1:** Along some dimensions data points vanished if `drop=True`
![grafik](https://github.com/pydata/xarray/assets/22961670/a57f6c63-4927-442f-a7a0-71e1d524a706)

**Example 2:** For other dimensions (these?) data points appeared elsewhere if `drop=True`
![grafik](https://github.com/pydata/xarray/assets/22961670/6e80986a-f81f-4524-bc56-56d81ddf2bd9)

### What did you expect to happen?

I expect for my calculations to return the same results, regardless of whether drop=True is active or not.

### Minimal Complete Verifiable Example

```Python
!wget  "https://zenodo.org/records/10818082/files/Emission_Inventory_H2O_Optimized_v0.1_MR3_Fleet_BRU-MYA_2075.nc"

import matplotlib.pyplot as plt
import xarray as xr

nc_file = xr.open_dataset('Emission_Inventory_H2O_Optimized_v0.1_MR3_Fleet_BRU-MYA_2075.nc')

fig, axs = plt.subplots(1,2,figsize=(10,4))

nc_file.H2O.where(nc_file.H2O!=0, drop=True).sum(('lon','time')).plot.contour(x='lat',ax=axs[0])
axs[0].set_xlim(-50,90)
axs[0].set_title('With drop=True')

nc_file.H2O.where(nc_file.H2O!=0, drop=False).sum(('lon','time')).plot.contour(x='lat',ax=axs[1])
axs[1].set_xlim(-50,90)
axs[1].set_title('With drop=False')

plt.tight_layout()
plt.show()

fig, axs = plt.subplots(1,2,figsize=(10,4))

nc_file.H2O.where(nc_file.H2O!=0, drop=True).sum(('lat','time')).plot.contour(x='lon',ax=axs[0])
axs[0].set_title('With drop=True')

nc_file.H2O.where(nc_file.H2O!=0, drop=False).sum(('lat','time')).plot.contour(x='lon',ax=axs[1])
axs[1].set_title('With drop=False')

plt.tight_layout()
plt.show()
```

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [ ] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')
libhdf5: 1.14.0
libnetcdf: 4.9.2

xarray: 2022.11.0
pandas: 1.5.3
numpy: 1.23.5
scipy: 1.13.0
netCDF4: 1.6.5
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.5
dask: None
distributed: None
matplotlib: 3.7.0
cartopy: 0.21.1
seaborn: 0.12.2
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.6.3
pip: 22.3.1
conda: None
pytest: None
IPython: 8.10.0
sphinx: None

</details>

**Comment by max-sixty** [comment]
To minimize the example, could you drill down to where the data is different between the two cases? What is being dropped such that the final result is different?

**Comment by mathause** [comment]
`drop=True` removes all-nan rows and columns - so your figures look plausible.

For the first one some rows on the top seem removed. For the second one there are probably all-nan columns in the center. Now matplotlib connecs the lines.

What did you expect to happen?

**Comment by johannespletzer** [comment]
> `drop=True` removes all-nan rows and columns - so your figures look plausible.
> 
> For the first one some rows on the top seem removed. For the second one there are probably all-nan columns in the center. Now matplotlib connecs the lines.
> 
> What did you expect to happen?

Thank you for your two comments. Both, in particular the reference to matplotlib, helped to understand that the visualization caused me to misinterpret the issue. I'll look further where the issue comes from. Apparently not from xr.where(..., drop=True).
