### ISSUE TITLE
Using the xarray.Dataset.where() function takes up a lot of memory

### ISSUE THREAD

**Issue by isLiYang** [pydata/xarray#8919]
### What is your issue?

My python script was killed because it took up too much memory. After checking, I found that the problem is the ds.where() function.

The original netcdf file opened from the hard disk takes up about 10 Mb of storage, but when I mask the data that doesn't match according to the latitude and longitude location, the variable **ds** takes up a dozen GB of memory. When I deleted this variable using del ds, the memory occupied by the script immediately returned to normal.

```
# Open this netcdf file.
ds = xr.open_dataset(track)

# If longitude range is [-180, 180], then convert to [0, 360].
if np.any(ds[var_lon] < 0):
	ds[var_lon] = ds[var_lon] % 360
# Extract data by longitude and latitude.
ds = ds.where((ds[var_lon] >= region[0]) & (ds[var_lon] <= region[1]) &
				(ds[var_lat] >= region[2]) & (ds[var_lat] <= region[3]))

# Select data by range and value of some variables.
for key, value in range_select.items():
	ds = ds.where((ds[key] >= value[0]) & (ds[key] <= value[1]))
for key, value in value_select.items():
	ds = ds.where(ds[key].isin(value))
```

**Comment by isLiYang** [comment]
I tried to process the previous data and found that there was no such problem. There may be a problem with the netcdf file format published by the data agency. The following is the problem file.
[SWOT_L3_LR_SSH_Expert_003_170_20230906T235831_20230907T004958_v0.3.nc.zip](https://github.com/pydata/xarray/files/14903867/SWOT_L3_LR_SSH_Expert_003_170_20230906T235831_20230907T004958_v0.3.nc.zip)

**Comment by max-sixty** [comment]
Can you reduce this down to an MCVE? The issue template has some guidance. Without that, it's unlikely this will get traction here.

My guess is that one of the arrays has a different dimension name and that's causing it to explode the dims...

**Comment by isLiYang** [comment]
> Can you reduce this down to an MCVE? The issue template has some guidance. Without that, it's unlikely this will get traction here.
> 
> My guess is that one of the arrays has a different dimension name and that's causing it to explode the dims...

Yes, there is an extra dimension in the data set, and after removing some variables and dimensions using the ds.drop_dims() function, the memory explosion problem disappears.

Thank you so much for your comment, I plan to close this issue.
