### ISSUE TITLE
'Warm start' for open_mfdataset?

### ISSUE THREAD

**Issue by mangecoeur** [pydata/xarray#893]
I'm using xarray in ipython to do interactive/exploratory analysis on large multi-file datasets. To avoid having too many files open, I'm wrapping my file-open code in a `with` block. However, this means that every time I re-run the code the multi-file dataset is re-initialised, causing xarray to re-scan every input datafile to construct the Dataset.

It would be good to have some kind of 'warm start' or caching mechanism to make it easier to re-open multifile datasets without having to re-scan the input files, but equally without having to keep the dataset open which keeps all the file handles open (I've hit the OS max file limit because of this).

Not sure what API would suit this - since it while being a useful usecase it's also a bit wierd. Something like `open_cached_mfdataset` which closes input files after initialisation but caches the information collected and simply assumes that files don't move or change between accesses.

**Comment by shoyer** [comment]
Agreed, this could be useful. Potentially ncml would be a good way to save this information: http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/ncml/Aggregation.html

**Comment by dcherian** [comment]
Has this been fixed by the recent addition of caching?

**Comment by keewis** [comment]
has this been fixed by `xncml` and/or `kerchunk`?
