### ISSUE TITLE
Allow specification of figsize in plot methods

### ISSUE THREAD

**Issue by robintw** [pydata/xarray#897]
Pandas allows a call to `plot` like:

``` python
df.plot(x='var1', y='var2', figsize=(10, 6))
```

but this doesn't seem to be possible in xarray - but it would be handy if it were.

It looks like fixing this would require modifying the `@_plot2d` decorator, specifically around https://github.com/pydata/xarray/blob/master/xarray/plot/plot.py#L376 (although I can't seem to find how to do the equivalent of `gca()` but set a `figsize` too).

Any thoughts or ideas?

**Comment by shoyer** [comment]
I made some significant progress on this previously (https://github.com/pydata/xarray/pull/637), but stalled out when I wasn't happy with any of the API options. I would welcome someone else picking this up.
