### ISSUE TITLE
How to apply function to two (or more) variables simultaneously

### ISSUE THREAD

**Issue by dgoldwx2112** [pydata/xarray#900]
I have two datasets: fcst and obs, each with dimensions (time, lat, lon). The first contains predicted values on a lat x lon grid for a given lead time and the second the corresponding verifying observations. I want to compute skill scores at each time but this obviously involves applying a function involving variables from both datasets. Moreover, the two fields (fcst and obs) need to be cosine weighted first (involves coordinate 'lat'). Furthermore, I wish to align the forecasts and obs in time; there may be missing values of each at different times. I tried aligning the datasets using 'xr.align' but got all kinds of errors when trying to use the resulting new dataset. I suppose I could extract the values from each dataset, taking care to use indexing to extract the common times and then using standard numpy operations and the like but before I go that route is there a methodology for using xarray to do such a computation? If I were doing a single variable computation, it would be easy to use the groupby and apply methods. TIA for any advice!

**Comment by shoyer** [comment]
If you write a function that can take an `xarray.Dataset` as input, you can still use groupby and apply. So generally the pattern I would use is:
```
obs = obs.reindex_like(fcst)   # possibly using tolerance if the grid isn't exactly the same
combined = xarray.Dataset({'obs': obs, 'fcst': fcst})
combined.groupby('time').apply(calculate_skill)
```

It's hard to answer in more specifics without seeing your code/data, though.

If you need to do time shifts between reference time and (actual) time, it's pretty straightforward with xarray (we had some custom code to do that at my last job) but it isn't a one-liner.

**Comment by dgoldwx2112** [comment]
Thanks Stephan - that was very helpful! I was able to carry out the necessary computations with no problems after seeing your reply.

**Comment by shoyer** [comment]
Glad to help!
