### ISSUE TITLE
Pickle xarray.ufuncs

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#901]
It's currently impossible to pickle xarray.ufuncs.

import xarray.ufuncs, pickle
pickle.dumps(xarray.ufuncs.maximum)

AttributeError: Can't pickle local object '_create_op.<locals>.func'

**Comment by MaximilianR** [comment]
There was a similar issue in pandas; may be worth looking at what the solution there was

**Comment by shoyer** [comment]
Possible cloudpickle or dill (which I know dask has used) can handle pickling them.

**Comment by crusaderky** [comment]
cloudpickle seems to work. dill doesn't (similar message as pickle).
