### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#9018]
### What is your issue?

We should do another release - we last released on March 29th.

@keewis is there anything with numpy 2 preventing a release right now? Or can I just go ahead and do it?

**Comment by dcherian** [comment]
I'd like to get #8998 in. Can we release tomorrow please?

**Comment by keewis** [comment]
there isn't anything that would prevent a release. We simply need to issue a new release including the two PRs that are left to make `xarray` compatible _before_ `numpy=2.0` is out (and the release after that can drop `python=3.9`).

**Comment by dcherian** [comment]
Good to go IMO!

**Comment by TomNicholas** [comment]
Closed by #9021 and the [2024.5.0 release](https://github.com/pydata/xarray/releases/tag/v2024.05.0)

**Comment by max-sixty** [comment]
Thanks @TomNicholas !
