### ISSUE TITLE
Documentation Request: Clarity for __matmul__ operator

### ISSUE THREAD

**Issue by mthramann** [pydata/xarray#9023]
### What is your issue?

Currently [the __matmul__ documentation](https://github.com/pydata/xarray/blob/6fe12340165fe327a665d4c8759ef7c47fb715d3/doc/user-guide/computation.rst?plain=1#L53) states that the operator does "matrix multiplication". It's unclear if this means np.matmul semantics, [or xr.dot](https://github.com/pydata/xarray/issues/1053).

It's probably worth explicitly calling out the distinction inline between np.matmul and np.dot, with a short explanation why this isn't the np.matmul behavior.

**Comment by TomNicholas** [comment]
Thanks for pointing this out @mthramann ! We would happily accept a PR to clarify this :)
