### ISSUE TITLE
```_FillValue``` and ```missing_value``` attributes get removed when using ```open_dataset```

### ISSUE THREAD

**Issue by Whyborn** [pydata/xarray#9024]
### What is your issue?

When opening an NetCDF dataset using ```open_dataset```, the attributes ```_FillValue``` and ```missing_value``` of the underlying Datasets are removed (unless ```mask_and_scale = false```). It seems counterintuitive to lose information by default, especially information which is necessary to determine what exactly the input data looked like.

**Comment by kmuehlbauer** [comment]
@Whyborn The attributes are moved to `.encoding` attribute of the respective DataArray in case of decoding. Please also follow-up with #6323.

**Comment by kmuehlbauer** [comment]
@Whyborn Did my above comment shed some light? Please let us know if you need further information.

**Comment by kmuehlbauer** [comment]
I'll close this for now, please let us know, if you need more information.
