### ISSUE TITLE
Square Logos

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#9044]
### Is your feature request related to a problem?

I want to use an Xarray logo on a Coiled docs page.  I'd really like to have a square logo, like this one:

![image](https://github.com/pydata/xarray/assets/306380/c3a15c60-a8dc-4219-911e-2ee119bb7230)

But when I look at  https://github.com/pydata/xarray/tree/026aa7c073d03fb6d749c216be1d829816583fac/doc/_static/logos I only see logos like these:

![image](https://github.com/pydata/xarray/assets/306380/0c1fa52d-cde2-4a3f-9fe3-8a286f7cb85a)

Any tips?

**Comment by andersy005** [comment]
@mrocklin, I'm not sure if this meets your needs 💯, but we have a couple of square logos in this folder: [Xarray-assets/Icon](https://github.com/xarray-contrib/xarray.dev/tree/39975fdf087824c1a83b12a2c4eae15dcce2141e/public/Xarray-assets/Icon)

**Comment by mrocklin** [comment]
Yeah, I saw that, but I wanted an image with "Xarray" in the name, so the icon files don't quite do what I need.

**Comment by mrocklin** [comment]
(thanks for the response though)

**Comment by andersy005** [comment]
> Yeah, I saw that, but I wanted an image with "Xarray" in the name, so the icon files don't quite do what I need.


we missed this detail when we were redesigning the logo. we've got all the original designs/assets, so I thought putting together a new square logo would be pretty simple. I went ahead and tried it out :) 


![xarray-square-logo-full-color-inverse-rgb](https://github.com/pydata/xarray/assets/13301940/29a4d1e2-16d7-4343-b1b9-2392330ad544)


does this work for you?

**Comment by andersy005** [comment]
and here's same logo for light background:

![xarray-square-logo-full-color-rgb](https://github.com/pydata/xarray/assets/13301940/b641603f-e0c0-4927-84af-dc300b172e30)

**Comment by mrocklin** [comment]
Those look cool.  I'd happily use them in our assets.  

I'll say some generic things that would make these better (but I think you probably know all of this anyway).  These might be better if ...

1.  They live in the repo or on a webpage somewhere where we can link to them with more confidence (although I guess this github comment will likely live forever)
2. They're well cropped (especially the dark background one)
3. They have transparent backgrounds
4. They have SVG and PNG outputs

Also, at first I thought it was weird to left-justify the text (putting the x on the same line as the boxes) but now I see how it creates a nice stairstep pattern on the right.  👍

**Comment by andersy005** [comment]
@mrocklin, i was able to tweak the settings, such as cropping and background, and i have added four new logos to this [pull request in `xarray-contrib/xarray.dev` repo](https://github.com/xarray-contrib/xarray.dev/pull/674). when you get a chance i could use your feedback in case i missed something. 

thank you again for opening this issue. it gave me the motivation to finally work on this :)

**Comment by mrocklin** [comment]
Thanks @andersy005 !

also cc @scharlottej13 and @jrbourbeau who sometimes use xarray logos

**Comment by jrbourbeau** [comment]
Thanks as always @andersy005 : )
