### ISSUE TITLE
TypeError: 'S3File' object is not subscriptable when reading grib2 file on minio

### ISSUE THREAD

**Issue by forestbat** [pydata/xarray#9052]
### What happened?

with `engine='cfgrib'` parameter, crash report is: https://pastebin.com/uNxhUKhP
without `engine` parameter, crash report is: https://pastebin.com/K9YzSjKz

### What did you expect to happen?

I want to read grib2 file on my minio s3 server

### Minimal Complete Verifiable Example

```Python
# hdscc.FS is a S3FileSystem
test_mpath = 's3://era5-origin/era5/grib/single_levels_tp/2020/08/03/2020080301.grib'
test_ds = xr.open_dataset(hdscc.FS.open(test_mpath), engine='cfgrib')
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>
======================== 1 failed, 2 warnings in 9.51s =========================
INSTALLED VERSIONS
------------------
commit: None
python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-177-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.3-development

xarray: 2024.1.1
pandas: 2.2.2
numpy: 1.26.4
scipy: 1.13.0
netCDF4: 1.6.5
pydap: None
h5netcdf: 1.3.0
h5py: 3.11.0
zarr: 2.17.2
cftime: 1.6.3
nc_time_axis: None
iris: None
bottleneck: None
dask: 2024.4.2
distributed: 2024.4.2
matplotlib: 3.8.4
cartopy: 0.23.0
seaborn: 0.13.2
numbagg: None
fsspec: 2024.5.0
cupy: 13.1.0
pint: 0.23
sparse: None
flox: None
numpy_groupies: None
setuptools: 69.5.1
pip: 24.0
conda: None
pytest: 8.1.1
mypy: None
IPython: 8.23.0
sphinx: 7.3.7

</details>

**Comment by dcherian** [comment]
`cfgrib` needs a local download. `fsspec` with `simplecache::` is a common solution: https://stackoverflow.com/questions/66229140/xarray-read-remote-grib-file-on-s3-using-cfgrib
