### ISSUE TITLE
Histogram plot of DataArray can be extremely slow

### ISSUE THREAD

**Issue by maahn** [pydata/xarray#908]
The speed of plotting a histogram of a large DataArray depends a lot how you do it:

    import xarray as xr
    import numpy as np
    import matplotlib.pyplot as plt

    nPoints = 100000
    data = xr.DataArray(np.random.random(nPoints),dims=['time'],coords=[np.arange(nPoints)])

It take sonly some ms if you use

    plt.figure()
    %time data.plot.hist()

    plt.figure()
    %time plt.hist(data.values)

However, if you omit `.values` it takes extremely long:

    In [12]: %time plt.hist(data)
    CPU times: user 2min, sys: 9.73 s, total: 2min 9s
    Wall time: 2min 3s

Do if one forgets to add `.values` or to use xarray's plot routine, one can be stuck for a long time. I have to kill python 1-2 per day due to that issue.

**Comment by shoyer** [comment]
This might be something worth reporting on the matplotlib side. I don't know how what's going on internally when you try to histrogram a DataArray directly. Profiling (e.g., with `%prun` in IPython) would probably give some useful clues about what's going on.

**Comment by maahn** [comment]
OK, I reported it to the matplotlib team:
https://github.com/matplotlib/matplotlib/issues/6804

**Comment by shoyer** [comment]
This has been fixed upstream
