### ISSUE TITLE
`.sel()` and `.isel()` methods treat arguments of type `slice` differently 

### ISSUE THREAD

**Issue by AkasDutta** [pydata/xarray#9086]
### What is your issue?

The indexing methods `xarray.DataArray.sel()` and `xarray.DataArray.isel()` treat `slice` objects fundamentally differently carrying out inclusive indexing in the former case but not in the latter (where the index corresponding to the upper limit of the slice is dropped).
`da = xr.DataArray(np.arange(6), dims=["x"], coords={"x": [0, 10, 20, 30, 40, 50]})`
`print(da.sel({"x": slice(0,0)}))`

yields `array([0])`

whereas
`print(da.isel({"x": slice(0,0)}))`

yields `array([])`

This is particularly an issue when I have to extract part of a data array, between indices that are dynamically determined by user input. I would like to be able to work with either user-provided coordinate labels or with user-provided array indices, and choose `sel` or `isel` to use "under the hood" for either case and proceed with identical input. However, this asymmetry requires adding an annoying workaround.

Interestingly, the xarray documentation on [indexing](https://docs.xarray.dev/en/stable/user-guide/indexing.html)  only says:
_However, you don’t need to use `method` to do inexact slicing. Slicing already returns all values inside the range (inclusive), as long as the index labels are monotonic increasing_
Which seems misleading as it isn't true for `isel()`, though the example provided is only of `sel()`

Is it possible to bring the two operations in line?

**Comment by kmuehlbauer** [comment]
Thanks @AkasDutta for taking the time to report this. This was discussed in #4526, please refer to that open issue.
