### ISSUE TITLE
"invalid value encountered in cast" during groupby_bins

### ISSUE THREAD

**Issue by jonathanweiss1** [pydata/xarray#9091]
### What happened?

Hey all, I am new to xarray, so if this is not a bug or related to wrong usage from my side please let me know. When I try to use groupby_bins, it prints the following numpy runtime warning:
```
lib/python3.9/site-packages/numpy/core/numeric.py:407: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(res, fill_value, casting='unsafe')
```

This makes me wonder if this warning has any impact on the result that i get?
Thanks for your help!

### What did you expect to happen?

The groupby operation should run without printing a warning.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np

# Create example data
data = np.random.rand(3, 4, 5)  # Example data with dimensions (3, 4, 5)

# Create xarray dataset
ds = xr.Dataset(
    {
        'variable1': (['dim1', 'dim2', 'dim3'], data),  # Add variable with dimensions
        'variable2': (['dim1', 'dim2', 'dim3'], data),  # Add another variable with dimensions
    },
    coords={
        'dim1': np.arange(3),  # Define coordinates for dimension 1
        'dim2': np.arange(4),  # Define coordinates for dimension 2
        'dim3': np.arange(5),  # Define coordinates for dimension 3
    }
)
ds.groupby_bins('variable1', bins=[0., 0.5, 1.])
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
>>> ds.groupby_bins('variable1', bins=[0., 0.5, 1.])
/home/maia-user/envs/MRE_new2/lib/python3.9/site-packages/numpy/core/numeric.py:407: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(res, fill_value, casting='unsafe')
DatasetGroupBy, grouped over 'variable1_bins'
2 groups with labels (0.0,, 0.5], (0.5,, 1.0].
```

### Anything else we need to know?

Maybe this warning can simply be ignored? If so, can you give me a hint on how to hide the warning?

### Environment

<details>

/home/maia-user/envs/MRE_new2/lib/python3.9/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10) 
[GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 6.2.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.3
libnetcdf: 4.9.2

xarray: 2023.6.0
pandas: 2.2.1
numpy: 1.26.4
scipy: 1.13.0
netCDF4: 1.6.5
pydap: None
h5netcdf: 1.2.0
h5py: 3.11.0
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: 1.3.7
dask: 2023.11.0
distributed: 2023.11.0
matplotlib: 3.8.4
cartopy: None
seaborn: 0.12.2
numbagg: None
fsspec: 2024.3.1
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 69.5.1
pip: 24.0
conda: None
pytest: None
mypy: None
IPython: 8.15.0
sphinx: None

</details>

**Comment by dcherian** [comment]
> xarray: 2023.6.0

I don't see this on latest Xarray so I don't know what's raising it.

Can you set the [warnings filter](https://docs.python.org/3/library/warnings.html#the-warnings-filter) to `"error"` and post a stack trace please?

You can use the filter to `"ignore"` these warnings too.

**Comment by jonathanweiss1** [comment]
Okay a actually thought i had the latest version, so thanks for pointing that out. It works for me to just upgrade to the newest version which fixes it.
