### ISSUE TITLE
Speed up operations with xarray dataset

### ISSUE THREAD

**Issue by saulomeirelles** [pydata/xarray#912]
Hi all,

I've been recently having hard times to manipulate a `xarray` `dataset`. Not sure if I am making some awkward mistake, but it is taking an unacceptable amount of time to perform simple operations. 

Here is a piece of my code:

```
ncfile   = glob('*conc_size_12m.nc')
ds       = xray.open_dataset(ncfile[0])
ds
```

```
<xarray.Dataset>
Dimensions:          (burst: 2485, duration: 2400, z: 160)
Coordinates:
    zdist            (z) float64 0.01014 0.02027 0.03041 0.04054 0.05068 ...
    burst_nr         (burst) float64 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 ...
    time             (duration, burst) datetime64[ns] 2014-09-16T07:00:00 ...
  * burst            (burst) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 ...
  * duration         (duration) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ...
  * z                (z) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 ...
Data variables:
    conc_profs       (duration, z, burst) float32 3.99138e-05 4.23636e-05 ...
    burst_duration   (duration) float64 0.0 0.1246 0.2493 0.3739 0.4985 ...
    grainSize_profs  (duration, z, burst) float32 200.0 200.0 200.0 200.0 ...
```

`ds.nbytes * (2 ** -30)`

`7.15415246784687`

`%time conc_avg = ds.conc_profs.chunk(2400).mean(('z','duration'))`

```
CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 9.84 ms
```

`%time conc_avg.load()` 

`%time conc_avg = ds.conc_profs.isel(burst=0).mean(('z','duration'))`

```
CPU times: user 708 ms, sys: 2.87 s, total: 3.58 s
Wall time: 1min 56s
```

If I work with chunks, it is impossible to load back the array in a reasonable amount of time (I waited for more than 30 min).

Looping over the dimension `burst`, it takes about 2 minutes per loop which is also quite unreasonable.

I was wondering if the problem could stem from the creation of my `dataset` which I saved into this 7+GB netCDF file. Could that be the case?

I am working in a Linux Inter Core i5 which is supposed to handle these manipulations with no hicups. I use the IOOS environment to run `xarray` (vr '0.7.1').

Can someone provide me some advice on how to optimize my script? 

I am happy to supply with more details if needed.

Cheers,

**Comment by shoyer** [comment]
What do the original input files look like, before you join them together? This may be a case where the dask.array task scheduler does very poorly.

**Comment by saulomeirelles** [comment]
The input files are 2485 nested mat-files that come out from a measurement device. I read them in Python ( `loadmat(matfile)` ) and turn them into numpy arrays like this:

```
	matfiles = glob('*sed.mat')


	matfiles = sorted(matfiles ,key=lambda x: extract_number(x) )


	if matfiles:

		ts = 2400
		zs = 160		

		Burst        = np.empty(len(matfiles))
		Time         = np.empty((ts,len(matfiles)), dtype='datetime64[s]')
		ConcProf     = np.empty((ts,zs,len(matfiles)), dtype='float64')
		GsizeProf    = np.empty((ts,zs,len(matfiles)), dtype='float64')
```

Afterwards, I populate the matrices in a loop:

```
def f(i):	
	Dist, Burst[i], Time[:,i], ConcProf[:,:,i], GsizeProf[:,:,i] = getABSpars(matfiles[i])

```
where

```
def getABSpars(matfile):	

	ndata = loadmat(matfile) 

	Dist  = ndata['r']

	t_dic = ndata['BurstInfo']['StartTime']

	try:
	    t_dt  = dt.datetime.strptime(t_dic, '%d-%b-%Y %H:%M:%S')
	except:
	    t_dic = t_dic + ' 00:00:00'
	    t_dt  = dt.datetime.strptime(t_dic, '%d-%b-%Y %H:%M:%S')

	t_range   = date_range( t_dt,
	            periods = ndata['MassProfiles'].shape[1],
	            freq    = ndata['BurstInfo']['MassProfileInterval']+'L')     

	Burst         = int(ndata['BurstInfo']['BurstNumber'])
	Time          = t_range
	ConcProf      = np.asarray(ndata['MassProfiles'] ).T
	GsizeProf     = np.asarray(ndata['SizeProfiles']*1e6).T

	return Dist, Burst, Time, ConcProf, GsizeProf

```

Using the `multiprocessing ` package:

```
pool = ThreadPool(4)
pool.map(f, range(len(matfiles)))
pool.close() 
```
Finally I create the xarray dataset and then save into a nc-file:

```
ds = xray.Dataset( { 'conc_profs'      : ( ['duration', 'z', 'burst'], ConcProf  ),
                     'grainSize_profs' : ( ['duration', 'z', 'burst'], GsizeProf ),
                     'burst_duration'  : ( ['duration'], np.linspace(0,299, Time.shape[0]) ), },
                  coords = {'time'      : (['duration', 'burst'], Time) ,
                            'zdist'     : (['z'], Dist),
                            'burst_nr'  : (['burst'], Burst) } )

ds.to_netcdf('ABS_conc_size_12m.nc' , mode='w')

```
It costs me around 1 h to generate the nc-file.

Could this be the reason of my headaches?

Thanks!

**Comment by shoyer** [comment]
Thanks for describing that -- I misread your initial description and thought you were using `open_mfdataset` rather than `open_dataset` (the glob threw me off!). The source of these files shouldn't matter once you have it in a netCDF file.

**Comment by saulomeirelles** [comment]
I've tried to create individual nc-files and then read them all using `open_mfdataset` but I got an error for opening too many files which was reported here before.

The `glob` is just a (bad) habit because I normally read multiple files. O_0

Cheers,

**Comment by shoyer** [comment]
When you write `ds.conc_profs.chunk(2400)`, it sets up the data to be loaded in a giant chunk, almost the entire file at once. Even if you use `.isel()` afterwards, dask does not always manage to subset the data from the initial chunk. (Sometimes it does succeed, which makes this a little confusing.)

You will probably be more successful if you try something like `ds.conc_profs.chunk({'burst': 10})` instead, which keeps the intermediate chunks to a reasonable size.

**Comment by saulomeirelles** [comment]
Thanks, @shoyer !

Setting smaller chunks help, however my issue is the way back.

This is fine:

`%time conc_avg = ds.conc_profs.chunk({'burst': 10}).mean(('z','duration'))`

```
CPU times: user 24 ms, sys: 0 ns, total: 24 ms
Wall time: 23.8 ms
```

But this:

`%time result = conc_avg.load() `

takes an insane amount of time which intrigues me because is just a vector with 2845 points.

Is there another way to tackle this without `dask` like using a for-loop? 

If `dask` is the way to go, what would be the quickest way to convert to numpy array?

**Comment by shoyer** [comment]
It's worth noting that `conc_avg = ds.conc_profs.chunk({'burst': 10}).mean(('z','duration'))` doesn't actually do any computation -- that's why it's so fast. It just sets up the computation graph. No computation happens until you write `.load()`.

**Comment by saulomeirelles** [comment]
True.

I decided to wait for `.load()` to do the job but the kernel dies after a while.

**Comment by shoyer** [comment]
> I decided to wait for .load() to do the job but the kernel dies after a while.

Are you running out of memory? Can you tell what's going on? This is a little surprising to me.

**Comment by saulomeirelles** [comment]
No, not really. I got no error message whatsoever. Is there any test I can
do to tackle this?

**Comment by shoyer** [comment]
Just looking at a task manager while a task executes can give you a sense
of what's going on. Dask also has some diagnostics that may be helpful:
http://dask.pydata.org/en/latest/diagnostics.html

**Comment by jhamman** [comment]
@saulomeirelles - Hopefully, you were able to work through this issue. If not, feel free to reopen.
