### ISSUE TITLE
dtype changes after .load()

### ISSUE THREAD

**Issue by robintw** [pydata/xarray#913]
I've found that in some situations a `DataArray` using dask as the storage backend will report its `dtype` as `float32`, but then once the data has been loaded (eg. with `load()`) the `dtype` changes to `float64`.

This surprised me, and actually caught me out in a few situations where I was writing code to export a DataArray to a custom file format (where the metadata specification for the custom format needed to know the `dtype` but then complained when the actual `dtype` was difference). Is this desired behaviour, or a bug? (Or somewhere in between...?).

This only seems to occur with dask-backed DataArrays, and not 'normal' DataArrays.

**Example:**

Create the example netCDF file like this:

```python
xa = xr.DataArray(data=np.random.rand(10, 10).astype(np.float32))
xa.to_dataset(name='data').to_netcdf('test.nc')
```

Then doing some simple operations with normal DataArrays:

```python
normal_data = xr.open_dataset('test.nc')['data']
normal_data.dtype
    # => float32
normal_data.mean(dim='dim_0').dtype
    # => float32
```

But doing the same thing in dask:

```python
dask_data = xr.open_dataset('test.nc', chunks={'dim_0': 2})['data']
dask_data.mean(dim='dim_0').dtype
    # => float32
dask_data.mean(dim='dim_0').load().dtype
    # => float64
```

**Comment by shoyer** [comment]
This is a bug, though possibly a dask.array bug rather than an xarray bug.

**Comment by robintw** [comment]
I'm not really sure how to work out which one it is a bug in - do you have any advice? Or should I just report it on the dask issue tracker too and see what they think?

**Comment by shoyer** [comment]
I would try creating a dask array of the same dtype and shape as this array. Then, see what happens to the dtype when you call the `.mean(axis=0).compute()`.

**Comment by shoyer** [comment]
I just filed a report upstream with dask in https://github.com/dask/dask/issues/1394. This is definitely a dask bug, because I can reproduce it without xarray. Thanks for the report!
