### ISSUE TITLE
cupy_xarray import broken

### ISSUE THREAD

**Issue by openSourcerer9000** [pydata/xarray#9186]
### What happened?

```
...Lib\site-packages\cupy_xarray\accessors.py:8
      [1](file:///.../Lib/site-packages/cupy_xarray/accessors.py:1) import cupy as cp
      [2](file:///.../Lib/site-packages/cupy_xarray/accessors.py:2) from xarray import (
      [3](file:///.../Lib/site-packages/cupy_xarray/accessors.py:3)     DataArray,
      [4](file:///.../Lib/site-packages/cupy_xarray/accessors.py:4)     Dataset,
      [5](file:///.../Lib/site-packages/cupy_xarray/accessors.py:5)     register_dataarray_accessor,
      [6](file:///.../Lib/site-packages/cupy_xarray/accessors.py:6)     register_dataset_accessor,
      [7](file:///.../Lib/site-packages/cupy_xarray/accessors.py:7) )
----> [8](file:///.../Lib/site-packages/cupy_xarray/accessors.py:8) from xarray.core.pycompat import DuckArrayModule
     [10](file:///.../Lib/site-packages/cupy_xarray/accessors.py:10) dsk = DuckArrayModule("dask")
     [11](file:///.../Lib/site-packages/cupy_xarray/accessors.py:11) dask_array_type = dsk.type

ModuleNotFoundError: No module named 'xarray.core.pycompat'
```

### What did you expect to happen?

import the installed lib

### Minimal Complete Verifiable Example

```Python
Straight from your docs

## Import NumPy and CuPy
import cupy as cp
import numpy as np
import xarray as xr
import cupy_xarray  # Adds .cupy to Xarray objects

for versions

cuda-version              11.8                 h70ddcb2_3    conda-forge
cudatoolkit               11.8.0              h09e9e62_13    conda-forge
cupy                      13.2.0          py311h0508009_0    conda-forge
cupy-core                 13.2.0          py311ha6d0cfe_0    conda-forge
cupy-xarray               0.1.3              pyhd8ed1ab_0    conda-forge
dask                      2024.4.0           pyhd8ed1ab_0    conda-forge
dask-core                 2024.4.0           pyhd8ed1ab_0    conda-forge
dask-expr                 1.0.9              pyhd8ed1ab_0    conda-forge
xarray                    2024.3.0           pyhd8ed1ab_0    conda-forge
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('English_United States', '1252')
libhdf5: 1.14.3
libnetcdf: 4.9.2

xarray: 2024.3.0
pandas: 2.2.1
numpy: 1.26.4
scipy: 1.12.0
netCDF4: 1.6.5
pydap: None
h5netcdf: None
h5py: 3.10.0
Nio: None
zarr: 2.17.1
cftime: 1.6.3
nc_time_axis: None
iris: None
bottleneck: None
dask: 2024.4.0
distributed: 2024.4.0
matplotlib: 3.8.3
cartopy: 0.22.0
seaborn: None
numbagg: None
fsspec: 2024.3.1
cupy: 13.2.0
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 69.2.0
pip: 24.0
conda: 24.5.0
pytest: None
mypy: None
IPython: 8.22.2
sphinx: None

</details>

**Comment by dcherian** [comment]
This will be fixed soon in cupy-xarray

**Comment by openSourcerer9000** [comment]
Is there a separate github for cupy-xarray issues?

**Comment by keewis** [comment]
yes, there's https://github.com/xarray-contrib/cupy-xarray
