### ISSUE TITLE
Some complex aggregations broken with `numbagg` installed

### ISSUE THREAD

**Issue by slevang** [pydata/xarray#9209]
### What happened?

Some common aggregations (at least `min`, `max`, `var`, `std`) are broken with complex dtypes if `numbagg` is installed with the default `skipna=True`. Looks like this is the case since #8624.

### What did you expect to happen?

We either route to `bottleneck` or `numpy` [here](https://github.com/pydata/xarray/blob/main/xarray/core/nputils.py#L182) if these aggregation aren't supported in `numbagg`, or get them working with `numbagg`.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np
da = xr.DataArray(np.ones((2,), dtype=np.complex_), dims=["x"])
da.min(skipna=False) # works
da.min() # fails
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
TypeError: ufunc '__numbagg_transformed_func' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Anything else we need to know?

cc @max-sixty 

### Environment

<details>
xarray==2024.1.1
numbagg==0.8.1
</details>

**Comment by max-sixty** [comment]
Thanks @slevang ! This should be fixed now. When numba allows for dynamic compilation then it'll be free for numbagg to support these...
