### ISSUE TITLE
DataTree.identical should consider checking that coordinates are defined at the same level

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#9215]
### What is your issue?

Consider the following two data trees:
```python
one = DataTree.from_dict(
    {
        "/": xr.Dataset(coords={"a": 1}),
        "/b": xr.Dataset(coords={"a": 1}),
    }
)
two = DataTree.from_dict(
    {
        "/": xr.Dataset(coords={"a": 1}),
        "/b": xr.Dataset(),
    }
)
```

Currently, `DataTree.identical()` considers `one` and `two` to be identical, but the coordinate `a` is defined redundantly in the first tree.

For most purposes, these DataTree objects are identical, but are edge cases where it could be different, e.g., when wrting these trees to netCDF or Zarr.

It would be helpful if the `.identical()` checked for such discrepancies, e.g., to facilitate writing unit tests as in https://github.com/pydata/xarray/pull/9214.

**Comment by TomNicholas** [comment]
Can this be closed after the changes in https://github.com/pydata/xarray/pull/9555? That's what I understood from [this comment](https://github.com/pydata/xarray/pull/9588/files#r1791110146).

**Comment by shoyer** [comment]
Yes, we can close. These trees are neither equal nor identical now.
