### ISSUE TITLE
add relative tolerance `rtol` and absolut tolerance `atol` to `assert_equal`

### ISSUE THREAD

**Issue by mosc9575** [pydata/xarray#9228]
### Is your feature request related to a problem?

It would be create if `assert_equal` from `xarray.testing` has a parameter to allow a tolerance, like the testing [`assert_frame_equal`](https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html) from `pandas` does.

### Describe the solution you'd like

The minimal example below generates a `Dataset`, where the difference is very small.

```python
from xarray import Dataset
from xarray.testing import assert_equal

ds = Dataset(
    {
        "a": (["x", "time"], [[1,2],[3,4]]),
        "b": (["x", "time"], [[1+1e-8,2+1e-8],[3,4]]),
    },
    coords={
        "x": [1,2],
        "time": [0,1],
    },
)

assert_equal(ds['a'], ds['b']) # , rtol=1e5)
```

At the moment `assert_equals` returns

```
AssertionError                            Traceback (most recent call last)
Cell In[41], [line 1](vscode-notebook-cell:?execution_count=41&line=1)
----> [1](vscode-notebook-cell:?execution_count=41&line=1) assert_equal(ds['a'], ds['b'])

    [... skipping hidden 1 frame]

File c:\Users\mosc\envs\fbpinn\Lib\site-packages\xarray\testing\assertions.py:156, in assert_equal(a, b, from_root, check_dim_order)
    [154](file:///C:/Users/mosc/envs/fbpinn/Lib/site-packages/xarray/testing/assertions.py:154) b = maybe_transpose_dims(a, b, check_dim_order)
    [155](file:///C:/Users/mosc/envs/fbpinn/Lib/site-packages/xarray/testing/assertions.py:155) if isinstance(a, (Variable, DataArray)):
--> [156](file:///C:/Users/mosc/envs/fbpinn/Lib/site-packages/xarray/testing/assertions.py:156)     assert a.equals(b), formatting.diff_array_repr(a, b, "equals")
    [157](file:///C:/Users/mosc/envs/fbpinn/Lib/site-packages/xarray/testing/assertions.py:157) elif isinstance(a, Dataset):
    [158](file:///C:/Users/mosc/envs/fbpinn/Lib/site-packages/xarray/testing/assertions.py:158)     assert a.equals(b), formatting.diff_dataset_repr(a, b, "equals")

AssertionError: Left and right DataArray objects are not equal

Differing values:
L
    array([[1, 2],
           [3, 4]])
R
    array([[1.e+08, 1.e+08],
           [3.e+00, 4.e+00]])
```

This is correct but it would be nice to allow the user to set a tolerance.

### Describe alternatives you've considered

At the moment the working solution is

```python
assert_equal(ds['a'].round(5), ds['b'].round(5))
```
.

**Comment by keewis** [comment]
you might want to have a look at `xr.testing.assert_allclose`, which is built for floating-point comparisons

**Comment by mosc9575** [comment]
@keewis Thanks for your hint. This function I missed.

Short notice before closing this issue. If I run the [search in the docs for `assert_allclose`](https://docs.xarray.dev/en/stable/search.html?q=assert_allclose) this function is not listed in the results.

![grafik](https://github.com/pydata/xarray/assets/68053396/8134a855-4e83-4f28-8e03-5ba20d255c69)

**Comment by keewis** [comment]
I don't know why that is not included in the search: we do have a separate page for `assert_allclose`, so the search should pick it up. This might be a bug in the theme's implementation of the search (not sure, though).
