### ISSUE TITLE
Deprecate pseudonetcdf backend

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#9255]
### What is your issue?

With version [3.4](https://github.com/barronh/pseudonetcdf/releases/tag/v3.4.0) of pseudonetcdf they have included the xarray backend.

This means that we could start a deprecation cycle on our end. Possibly we should wait some month, then deprecate and remove it once 3.4 is the minimum supported version.

**Comment by jhamman** [comment]
We already deprecated (and removed) it! https://github.com/pydata/xarray/pull/8446

**Comment by headtr1ck** [comment]
> We already deprecated (and removed) it! https://github.com/pydata/xarray/pull/8446

Ok fail on my side then, haha! Thanks for spotting:)

**Comment by headtr1ck** [comment]
I guess this means this backend is back :)
