### ISSUE TITLE
DOC: copybutton does not copy complete example

### ISSUE THREAD

**Issue by mosc9575** [pydata/xarray#9263]
### What happened?

In the documentation sometimes the copy button fails to copy the complete example. One example can be seen in the [HDF section](https://docs.xarray.dev/en/stable/user-guide/io.html#hdf5)

![failing_copy_button](https://github.com/user-attachments/assets/196304f8-6efd-4bdc-b0d7-f4f0df624d61)

This is because the number of dots (4) are not matched by the regular expression of the copy button, this regular expression needs a small tweak.

To explain the problem in more detail, the [io page](https://docs.xarray.dev/en/stable/user-guide/io.html) uses ipython  to run the example code and there are many cells. The regular expression 

https://github.com/pydata/xarray/blob/10bb94c28b639369a66106fb1352b027b30719ee/doc/conf.py#L100

is working working for the first 9 cells. If there is a double digit cell with a multi line example, the copy button does not work.  
The regular expression looks for 3 dots ans a double dot. But for larger numbers there are the length of the number of the cell plus two dots.

**Comment by keewis** [comment]
interestingly enough, it looks like this has been in the ipython sphinx extension since 15 years ago, and which deviates from what the ipython shell itself does (which left-pads with spaces). At least the sphinx extension makes sure all code cells are consistent, even the verbatim ones.
