### ISSUE TITLE
Xarray now forces Pandas == 2.2.2 install

### ISSUE THREAD

**Issue by spaceswimmer** [pydata/xarray#9305]
### What is your issue?

So i've been using Xarray for a while, but some recent update made it so it now forces me to install pandas == 2.2.2. Thats contrary to what is said in Xarray documentation at https://docs.xarray.dev/en/stable/getting-started-guide/installing.html. Now Xarray refuses to work with any pandas lower than 2.2.2. Don't really know if this is an issue on my end or it is intended.

**Comment by spaceswimmer** [comment]
@kmuehlbauer Thank you for your answer, that makes sense. Some libraries I used, depended on pandas < 1.6, so they were incompatible with Xarray. I was just a little confused, on why that was happening. Everything is fixed now, thank you for your help!

**Comment by kmuehlbauer** [comment]
@spaceswimmer Glad you got this sorted out.
