### ISSUE TITLE
How to cite xarray in a research paper

### ISSUE THREAD

**Issue by andreas-h** [pydata/xarray#931]
It would be helpful if the documentation had an entry (for example, in the FAQ) about how to properly cite xarray for a scientific publication.  I personally like the way e.g. the ipython folks are doing it, they have bibtex code to copy'n'paste (see https://ipython.org/citing.html).

This issue is related to #290, but addresses the general problem and not a specific way.

**Comment by shoyer** [comment]
Yes, we should do this. @jhamman and I are actually in the final stages of preparing a manuscript for submission to JORS.

**Comment by jhamman** [comment]
Indeed. Once that paper is submitted, I'll put together a PR with documention on how to cite xarray.


Bibtex will look something like this:
```
@article{hoyer2016xarray,
  title={xarray: {N-D} labeled arrays and datasets in {Python}},
  author={Hoyer, S. and J. Hamman},
  journal={in prep, J. Open Res. Software},
  year={2016}
}
```

and there will also [Zenodo](https://zenodo.org) doi once 0.8 is officially released.

**Comment by fmaussion** [comment]
Once you'll have both (a DOI for the paper, a DOI from Zenodo), which one will you recommend? 

If I understand how Zenodo works, one possibility would be to always ask to cite the paper (for the citation records) and use Zenodo as an additional reference to a specific version of xarray?

**Comment by jhamman** [comment]
> If I understand how Zenodo works, one possibility would be to always ask to cite the paper (for the citation records) and use Zenodo as an additional reference to a specific version of xarray? 

Exactly!
