### ISSUE TITLE
Forbid path-like variable names in datatree

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#9339]
### What is your issue?

We should guard against possible path manipulation bugs if someone tries to name a group in a datatree something containing a forward slash. There is an existing issue and PR about this on the old repo https://github.com/xarray-contrib/datatree/issues/311 and https://github.com/xarray-contrib/datatree/pull/314. 

cc @etienneschalk

**Comment by kmuehlbauer** [comment]
resolved by #9378
