### ISSUE TITLE
Datatree: parent of new nodes is not assigned properly in update

### ISSUE THREAD

**Issue by flamingbear** [pydata/xarray#9345]
### What is your issue?

_Originally posted by @keewis in https://github.com/xarray-contrib/datatree/issues/203_

there's something weird happening when assigning nodes using `update`:
```python
In [1]: import datatree
   ...: import xarray as xr
   ...: 
   ...: tree1 = datatree.DataTree.from_dict({"/a/b": xr.Dataset()})
   ...: node = datatree.DataTree()
   ...: 
   ...: tree2 = tree1.copy()
   ...: tree2.update({"c": node})
   ...: 
   ...: for node in tree3.subtree:
   ...:     print(node.path, node.name, id(node.root))
/ None 140512169735136
/a a 140512169735136
/a/b b 140512169735136
/ c 140512169735248
```
(the parent of `node` is `None`, so its root is the node itself)

So it seems with `update` / `assign` you can end up with a inconsistent tree? With https://github.com/xarray-contrib/datatree/pull/201, that inconsistent tree fails to copy because `relative_to` raises an error.

**Comment by TomNicholas** [comment]
Is this still relevant?

**Comment by keewis** [comment]
I don't think it is, at least I can't reproduce the original issue with `xarray.core.datatree.DataTree`.

However, `tree.update({"a/b": node})` still does not work (it raises `ValueError: node names cannot contain forward slashes`), which may or may not be by design.

**Comment by TomNicholas** [comment]
Okay thanks. 

Not accepting node names with slashes seems reasonable to me, at least for now. If we generalize that later we can discuss it in a new issue / PR, so I think this one can be closed?
