### ISSUE TITLE
PyNIO backend doesn't play well with open_mfdataset

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#936]
As reported on StackOverflow: http://stackoverflow.com/questions/38711915/segmentation-fault-writing-xarray-datset-to-netcdf-or-dataframe/

It appears that we can only open a single file at a time with pynio?

Adding a thread lock via `lock=True` didn't solve the issue.

cc @david-ian-brown

**Comment by david-ian-brown** [comment]
Hi Stephan,

I will look into this issue.
 -dave

**Comment by david-ian-brown** [comment]
Hi Stephan,
I notice that you posted a solution of sorts on stackoverflow. Is this a
real fix or a bandaid for the problem? I ran a few tests with pynio by
itself where there was no problem opening e.g. a GRIB file for reading and
a NetCDF file for writing at the same time.
I am wondering if the issue involves using pynio and the netCDF4 modules at
the same time. Let me know if still think something in pynio is not working
correctly.
Thanks.
 -dave

**Comment by shoyer** [comment]
The fix I posted on stackoverflow is a bandaid solution -- it requires loading every file into memory all at once, which can be problematic if you have large amounts of data.

It occurs to me that the problem might be that we were attempting to concurrently load data from multiple variables in a single file at once. If this is the issue, then it's something we can work around pretty easily with xarray. I'll run some tests later to verify.
