### ISSUE TITLE
Update examples to use xarray.tutorial.load_dataset()

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#938]
This is cleaner than require users to separately download data, and it already works, for everything in the [xarray-data](https://github.com/pydata/xarray-data) repository!
```
ds = xr.tutorial.load_dataset('RASM_example_data')
```

We might want to rename the file to simply "rasm" to keep things shorter.

CC @rabernat @jhamman

**Comment by jhamman** [comment]
I'm good with this change.  Happy to rename the dataset too!

**Comment by jhamman** [comment]
Done for the RASM dataset.  Still need to do the "Multidimensional Coordinates" example.

**Comment by jhamman** [comment]
closed via #982, #983, and https://github.com/pydata/xarray-data/issues/5
