### ISSUE TITLE
Support `.groupby(['foo', 'bar'])` as sugar for `.groupby(foo=UniqueGrouper(), bar=UniqueGrouper())`

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#9396]
Once #9372 goes in we will support grouping by multiple variables.

@max-sixty makes a good point re: ergonomics:

> I missed previous discussions / can decide this later — but do we want to have `da.groupby(['foo', 'bar'])` as sugar for `da.groupby(foo=UniqueGrouper(), bar=UniqueGrouper())`?

_Originally posted by @max-sixty in https://github.com/pydata/xarray/issues/9372#issuecomment-2294938165_

I think this would be great. `da.groupby(foo=UniqueGrouper(), bar=UniqueGrouper())` is a bit too much typing for a very simple expression.

**Comment by dcherian** [comment]
@max-sixty are you able to do this?

**Comment by max-sixty** [comment]
I can try to have a look at the weekend

(I realize I'm in your debt but generally when I commit to things, I end up not doing them, so I won't commit here. But would like to reciprocate some of your recent work and agree it makes sense for me to take it)

**Comment by dcherian** [comment]
no pressure! ;)
