### ISSUE TITLE
HTML representation of collabsible sections and "show/hide attributes/data repr" is not keyboard accessible

### ISSUE THREAD

**Issue by srijan55** [pydata/xarray#9397]
### What is your issue?

The HTML representation of xarray has some clickable areas -
![image](https://github.com/user-attachments/assets/fb5b5386-63a3-40e8-bb22-341c04ea776e)
But these are not keyboard accessible / tabbable.

**Comment by srijan55** [comment]
I've a potential (css only) fix for this which I can submit a PR for.

**Comment by dcherian** [comment]
Yes a PR would be great. Thank you!

**Comment by srijan55** [comment]
PR is merged
