### ISSUE TITLE
Resample no longer works with Pandas DateOffset or Timedelta objects

### ISSUE THREAD

**Issue by oliverhiggs** [pydata/xarray#9408]
### What is your issue?

Since version 2024.07.0, resampling raises an error when used with a Pandas `DateOffset` or `Timedelta` object. Resampling using these can be done by first creating a `TimeResampler` object, but this is an extra step and is inconsistent with the way resampling works in Pandas; `resample` in Pandas accepts objects of these types as arguments.

Would the maintainers consider supporting DateOffset and Timedelta objects directly in `resample`?

**Comment by dcherian** [comment]
Thanks I agree this should be fixed 

Are you able to send in a PR with a fix?
