### ISSUE TITLE
Filtering by data variable name

### ISSUE THREAD

**Issue by benbovy** [pydata/xarray#942]
Given #844 and #916, maybe it might be useful to also have a `Dataset.filter_by_name` method?

I currently deal with datasets that have many data variables with names like:

```
...
reference__HONO         (rlevel) float64 3.16e-15 1e-14 1e-14 1e-14 ...
reference__NO           (rlevel) float64 2.16e-05 3.57e-06 9.3e-07 ...
reference__HO2NO2       (rlevel) float64 9.58e-20 7.32e-19 4.63e-18 ...
...
retrieved__O3           (level) float64 1.552e-06 5.618e-07 ...
retrieved__N2O          (level) float64 4.714e-11 9.905e-11 ...
retrieved__CO2          (level) float64 0.0002816 0.0003592 ...
...
```

Using `ds.filter_by_name(like='reference__')` would be less verbose than, e.g., `xr.Dataset({name: ds[name] for name in ds.keys() if 'reference__' in name})`, unless there is already a more convenient way that I'm missing?

**Comment by MaximilianR** [comment]
I think a `.filter` is for sure worthwhile, so your example becomes: `xr.Dataset.filter(lambda x: 'reference__' in x)`.

I'm -0 on `filter_by_name` given it's another method and adds just a little bit to `filter`

**Comment by shoyer** [comment]
I would suggest `ds.filter(like='reference__')`, which is how pandas handles this.

**Comment by benbovy** [comment]
My mistake, it definitely makes no sense to add a `filter_by_name` method! When opening this issue I actually didn't fully get the way `.filter` would work. I close this.
