### ISSUE TITLE
idxmin / idxmax is not parallel friendly

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#9425]
### Discussed in https://github.com/pydata/xarray/discussions/9421

<div type='discussions-op-text'>

<sup>Originally posted by **KBodolai** September  2, 2024</sup>
Hi there! I have a question about the chunking behaviour when using idxmin / idxmax for a chunked array.

What is the expected behaviour for the chunks after we run `idxmin` over one of the dimensions?  Naively I'd expect it to keep the chunks along the other dimensions, but that doesn't seem to be what happens: (Example below with time, x, y)

```python
import numpy as np
import xarray as xr

# create some dummy data and chunk
x, y, t = 1000, 1000, 57
rang = np.arange(t*x*y)
da = xr.DataArray(rang.reshape(t, x, y), coords={'time':range(t), 'x': range(x), 'y':range(y)})
da = da.chunk(dict(time=-1, x=256, y=256))
```

Now when I look at the array, it looks something like this:

<img width="542" alt="Screenshot 2024-09-02 at 17 06 22" src="https://github.com/user-attachments/assets/846fec75-3b45-4219-b38c-3119a933e05b">

```python
da.idxmin('time')
```

But after doing `idxmin` I get the outputs below
<img width="478" alt="Screenshot 2024-09-02 at 17 00 17" src="https://github.com/user-attachments/assets/cf4e701f-c015-45ce-979b-ab43656649c3">

My understanding is that it seems to be trying to keep the number of chunks. But oddly, when we do it for floats:

```python
da = da.astype('float32')
```

before and after doing the `idxmin` looks like this:

<img width="542" alt="Screenshot 2024-09-02 at 17 10 25" src="https://github.com/user-attachments/assets/9623c28b-b605-43d7-ad9a-8325c972d240">
<img width="477" alt="Screenshot 2024-09-02 at 17 10 11" src="https://github.com/user-attachments/assets/eab09f05-fb01-4243-8b7b-36064181b9d7">

Is this the expected behavour for this operation? I'm guessing the reshaping in the source code happens [here](https://github.com/pydata/xarray/blob/12d8cfa317b1a08748cb6a0a1b10a6efe3a7d3d2/xarray/core/computation.py#L2180), but I haven't been able to figure out how yet.

Thanks!
K.
</div>

**Comment by dcherian** [comment]
Yes, this looks bad. 

The code *should* use `.vindex`. Though I think the best approach is to use `Variable.__getitem__` and it will handle all the complexity.
https://github.com/pydata/xarray/blob/a8c989673d0ea0cd099ede136efa117eaeb7ae1d/xarray/core/computation.py#L2180-L2187

**Comment by KBodolai** [comment]
Hey, I absolutely missed this issue! I haven't yet had the pleasure to contribute to xarray - but do let me know if there's anything I can help with here @dcherian, I'd love to give a hand.
