### ISSUE TITLE
Deep copying a datatree somehow duplicates data onto child nodes

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#9454]
### What happened?

Deep copying a DataTree object somehow duplicates data onto a child node (!)

### What did you expect to happen?

Copying to return an identical subtree.

### Minimal Complete Verifiable Example

```Python
In [15]: dt = DataTree(data=xr.Dataset(coords={'x': ('x', [0, 1])}))

In [16]: print(dt)
<xarray.DataTree>
Group: /
    Dimensions:  (x: 2)
    Coordinates:
      * x        (x) int64 16B 0 1
    Data variables:
        *empty*

In [17]: dt['c'] = DataTree()

In [18]: print(dt)
<xarray.DataTree>
Group: /
│   Dimensions:  (x: 2)
│   Coordinates:
│     * x        (x) int64 16B 0 1
│   Data variables:
│       *empty*
└── Group: /c

In [19]: dt.copy(deep=True)
Out[19]: 
<xarray.DataTree>
Group: /
│   Dimensions:  (x: 2)
│   Coordinates:
│     * x        (x) int64 16B 0 1
│   Data variables:
│       *empty*
└── Group: /c
        Dimensions:  (x: 2)
        Coordinates:
          * x        (x) int64 16B 0 1
        Data variables:
            *empty*
```

### Environment

`main`

**Comment by TomNicholas** [comment]
Wait I'm being an idiot - the coordinates appearing in both groups is expected behaviour now that we have coordinate inheritance.

What's weird is that they don't appear in the child node when we `print(dt)`! This implies some bug with coordinate inheritance / handling of empty nodes (cc @shoyer).

**Comment by shoyer** [comment]
I think I know what's going on... stay tuned for a fix
