### ISSUE TITLE
List of projects using xarray

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#946]
I'm particularly interested in projects that we should highlight in our docs and other publications, either as evidence of the impact of xarray or because other xarray users would find it useful to know about them. We could put together an "Xarray ecosystem" docs page [like pandas](http://pandas.pydata.org/pandas-docs/stable/ecosystem.html).

What I have so far falls into three categories:

Tools for analyzing global climate model output with xarray:
- [xgcm](https://github.com/xgcm/xgcm): for analyzing general circulation model output data
- [oocgcm](https://github.com/lesommer/oocgcm): analysis of large gridded geophysical dataset
- [mpas_xarray](https://github.com/pwolfram/mpas_xarray): wrapper to allow input of mpas data into xarray
- [marc_analysis](https://github.com/darothen/marc_analysis): Analysis package for CESM/MARC experiments and output

Other weather/climate specific tools:
- [windspharm](http://ajdawson.github.io/windspharm/): wind spherical harmonics
- [eofs](http://ajdawson.github.io/eofs/): empirical orthogonal functions
- [infinite-diff](https://github.com/spencerahill/infinite-diff): xarray-based finite-differencing
- [aospy](https://github.com/spencerahill/aospy): Climate data analysis, database, and visualization

Non-climate:
- [Datashader](https://github.com/bokeh/datashader/): visualization for large data
- [cesium](http://cesium.ml/): machine learning for time series analysis
- [ptsa](http://ptsa.readthedocs.io/en/latest/): EEG Time Series Analysis
- [pyGDX](http://pygdx.readthedocs.io/): GDX file data access
- [pycalphad](http://pycalphad.readthedocs.io): Computational Thermodynamics in Python

**Comment by benbovy** [comment]
I'm currently developing [spyfit](https://github.com/girpas-ulg/spyfit), which is based on xarray and which is for handling data related to FTIR spectroscopy of the atmosphere. I hope to release it soon. It may fall into the 2nd category I think.

Depending on my position, I'd like to use xarray in other projects related either to atmospheric chemistry modeling or earth surface dynamics modeling!

**Comment by pwolfram** [comment]
@shoyer, we are in the nascent stage of development for an analysis package for MPAS-Ocean (https://github.com/MPAS-Dev/MPAS-Analysis) that will be leveraged for analysis in ACME (http://climatemodeling.science.energy.gov/projects/accelerated-climate-modeling-energy).

**Comment by bladwig1** [comment]
@shoyer I work in the NCL team at NCAR and am developing the soon-to-be released wrf-python package, which gives Python users the same functionality found in WRF-NCL.  The metadata is managed using xarray.

**Comment by neuromusic** [comment]
does anyone know of projects doing declarative visualization on top of xarray (like seaborn and altair have on pandas)?

**Comment by shoyer** [comment]
@neuromusic we have some basic stuff in our own plotting module (though mostly a matplotlib wrapper), but also take a look at HoloViews which recently added xarray support.

**Comment by neuromusic** [comment]
@shoyer ahhh good to know. just stumbled on holoviews recently. thanks!!

**Comment by neuromusic** [comment]
(and definitely highlight HoloViews in the docs update)

**Comment by mathause** [comment]
I wrote [regionmask](https://github.com/mathause/regionmask) to automatically create mask of regions defined by polygons (#501). Arbitrary longitude/ latitude grids can be passed. Handles xarray input and output.

**Comment by shoyer** [comment]
[Salem](http://salem.readthedocs.io/) extends xarray to add geolocalised subsetting, masking, and plotting

(It definitely has some overlap with other tools on this list!)

If anyone wants to put together a PR to add a mention of this list to the docs, that would be appreciated. I'm happy to highlight any packages that make use of or integrate with xarray, but obvious let's highlight those projects that would be relevant to the largest slices of xarray users.
