### ISSUE TITLE
Using `Dataset.where()` with `drop=True` causes Boolean variables (dtype `bool`) to revert to Float (dtype `float64`)

### ISSUE THREAD

**Issue by JamieTaylor-TUOS** [pydata/xarray#9461]
### What happened?

If one uses the `.where()` method to drop elements from a Dataset, any variable of dtype `bool` becomes dtype `float64`

### What did you expect to happen?

Any boolean variables should remain boolean in the resulting Dataset

### Minimal Complete Verifiable Example

```Python
import numpy as np
import pandas as pd
import xarray as xr

mydata = xr.Dataset(
    data_vars=dict(
        myvar=xr.DataArray(
            np.array([
                [False, False, True, False],
                [True, False, False, True],
            ]),
            coords={
                "category": ["A", "B"],
                "time": pd.to_datetime([
                    "2024-08-02T11:00:00+00:00",
                    "2024-08-02T12:00:00+00:00",
                    "2024-08-02T13:00:00+00:00",
                    "2024-08-02T14:00:00+00:00"
                ])
            },
        )
    )
)
print(mydata)
print("---------------------------")
print(f"myvar dtype before calling `.where()`: {mydata.myvar.dtype}")
print("---------------------------")
# The following will use remove some elements using `.where()`
subset = mydata.where(mydata.category.isin(["A",]), drop=True)
print("---------------------------")
print(subset)
print("---------------------------")
print(f"myvar dtype after calling `.where()`: {subset.myvar.dtype}")
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
<xarray.Dataset> Size: 48B
Dimensions:   (category: 2, time: 4)
Coordinates:
  * category  (category) <U1 8B 'A' 'B'
  * time      (time) object 32B 1722596400000000000 ... 1722607200000000000
Data variables:
    myvar     (category, time) bool 8B False False True ... False False True
---------------------------
myvar dtype before calling `.where()`: bool
---------------------------
---------------------------
<xarray.Dataset> Size: 68B
Dimensions:   (category: 1, time: 4)
Coordinates:
  * category  (category) <U1 4B 'A'
  * time      (time) object 32B 1722596400000000000 ... 1722607200000000000
Data variables:
    myvar     (category, time) float64 32B 0.0 0.0 1.0 0.0
---------------------------
myvar dtype after calling `.where()`: float64
```

### Anything else we need to know?

Possibly linked to #3570 ?

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]
python-bits: 64
OS: Linux
OS-release: 5.15.0-1064-azure
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.2
libnetcdf: 4.9.3-development

xarray: 2024.3.0
pandas: 2.2.2
numpy: 1.26.4
scipy: 1.14.1
netCDF4: 1.7.1.post2
pydap: None
h5netcdf: 1.3.0
h5py: 3.11.0
Nio: None
zarr: None
cftime: 1.6.4
nc_time_axis: None
iris: None
bottleneck: 1.4.0
dask: 2024.8.0
distributed: None
matplotlib: 3.9.2
cartopy: None
seaborn: 0.13.2
numbagg: None
fsspec: 2023.10.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 72.1.0
pip: 24.2
conda: None
pytest: None
mypy: None
IPython: 8.26.0
sphinx: None

</details>

**Comment by shoyer** [comment]
This is (unfortunately) intended behavior.

The `where()` method (even with `drop=True`) does not assume that it can remove all NA values, because it supports conditions with any number of dimensions, which could result in ragged arrays.

Instead, you could achieve the result in your example using array indexing, e.g., `subset = mydata.isel(category=mydata.category.isin(["A",]))`
