### ISSUE TITLE
out-of-core capabilities

### ISSUE THREAD

**Issue by sambarluc** [pydata/xarray#951]
I am having a close look at xarray, which I am finding very interesting (so thank you very much for your work). I see you are not considering any out-of-core capability, and I understand this is not the focus of the library. I was wandering if you are just not interested in this, or if you want to wait for upstream numpy development (which, I believe, sooner or later will deal better with larger-than-memory arrays).
Andrea

**Comment by fmaussion** [comment]
Hi, do you expect something else than the available out-of-core computation with dask? 
http://xarray.pydata.org/en/stable/dask.html

**Comment by sambarluc** [comment]
Very embarassing. I was using too much the search function instead of just browsing the docs... Sorry! And thanks for the reply.
