### ISSUE TITLE
ENH: Throw informative error if missing optional dependency

### ISSUE THREAD

**Issue by scott-huberty** [pydata/xarray#9554]
This ticket proposes two separate but overlapping ideas. 

### 1. When trying to write/read Zarr files, throw an informative error if the user does not have `zarr` installed

 just as Xarray does for other optional dependencies like Matplotlib.

<details><summary>Reproducible Code</summary>

Assuming you only have the base Xarray deps installed:
```python
import xarray as xr


da = xr.DataArray([1, 2, 3],
                  dims='x',
                  coords={'x': [10, 20, 30]}
                  )
da.plot() # Raises a more informative ImportError
da.to_zarr('./test.zarr') # Does not raise an informative ImportError
```
</details>

### 2. Create a utility function to handle optional dependency imports across the Xarray code base. 

Doing `git grep "raise ImportError"` or `git grep "raise ModuleNotFoundError"` reveals that currently there is a piecemeal approach to handling optional dependencies. It would probably be helpful to have a dedicated function to handle soft dependencies across the code base, and I would be happy to add this If I am going to be adding a PR for point 1 anyways. 

### Describe the solution you'd like

I work on an applied neuroscience package named [MNE-Python](https://github.com/mne-tools/mne-python), where we have a lot of optional dependencies that are only needed for specific MNE functionalities. So [borrowing](https://github.com/mne-tools/mne-python/blob/5492174fc0e64762056b5b99a330129ca6eefca4/mne/utils/check.py#L388) from MNE, I think something like this would be nice:

```python
# xarray.util.check.py

import importlib


def _soft_import(name, reason, strict=True):
    """Import optional dependencies, providing informative errors on failure."""
    _INSTALL_MAPPING = dict(nc_time_axis="nc-time-axis")
    package_name = _INSTALL_MAPPING.get(name, name)
    try:
        return importlib.import_module(name)
    except (ImportError, ModuleNotFoundError):
        if strict:
            raise ImportError(
                f"for {reason}, the {package_name} package is required. "
                f"Please install it via pip or conda."
            )
        else:
            return None
```

Then, for example, [here](https://github.com/pydata/xarray/blob/cde720f21788a1dbff2bdb0775a56b3ee6da6b1a/xarray/backends/zarr.py#L1394), we can instead do:

```python

zarr = _soft_import("zarr", reason="writing zarr files")
```

And if we don't have `zarr` installed we'd get:

```console

ImportError: for writing zarr files, the zarr package is required. Please install it via pip or conda.
```

### Describe alternatives you've considered

Open to any ideas 🙂 

### Additional context

What do folks think about this idea? Is a PR welcome?

**Comment by max-sixty** [comment]
Yes this sounds like a really nice contribution!

**Comment by kmuehlbauer** [comment]
I'm totally supporting this idea.

Just to get this into the discussion: in one of the packages I maintain this was extended to allow such scheme for global imports:

https://github.com/wradlib/wradlib/blob/c27369667fbbe771fd0af8db7f4b0cc0066e61c4/wradlib/util.py#L50-L128

**Comment by kmuehlbauer** [comment]
Found this while researching other options

https://scientific-python.org/specs/spec-0001/

**Comment by scott-huberty** [comment]
I think that lazy loading and optional dependency handling are separate issues, at least as far as how it is implemented in `lazy_loader`. For example with `lazy_loader` I think that top level imports of optional dependencies will still raise an error (if that package is not installed).

For what it's worth MNE-Python is trying out `lazy_loader`, and my current understanding is that the development team has not reached consensus on it ( see https://github.com/mne-tools/mne-python/pull/12059 )
