### ISSUE TITLE
Setting var._attrs = None creates an empty dictionary?

### ISSUE THREAD

**Issue by allen-adastra** [pydata/xarray#9560]
### What is your issue?

If I do the following in repl, I get the weird behavior (described in comments).

```
>> import xarray as xr
>> import numpy as np
>> foo=xr.Variable(('x',), np.ones(10))
>> foo._attrs = None
>> print(foo._attrs) # Gives a None
>> foo
>> print(foo._attrs) # Gives a {}
```

Wondering what might be the cause of this? I know I am not using it as intended; this is for the xarray_jax experiment.

@shoyer would be good to get your perspective

**Comment by keewis** [comment]
`Variable` (or rather, its base class `NamedArray`) uses `xarray.core.formatting.array_repr` to format the array, which accesses the `attrs` property: https://github.com/pydata/xarray/blob/7bdc6d4ccc6359143cb6b8d6a7642ca38c3ff550/xarray/namedarray/core.py#L524-L529 Since `_attrs` is `None` at that point, it is replaced by an empty `dict`.

**Comment by allen-adastra** [comment]
Gotcha, if this is expected behavior, then perhaps in the context of `xarray_jax` the following is the solution
```
def _flatten_variable(
    v: xarray.Variable,
) -> Tuple[Tuple[jax.typing.ArrayLike], Tuple[Hashable, ...]]:
    children = (v._data,)
    aux = (
        v._dims,
        # Xarray will sometimes turn None into empty dictionaries. To maintain consistent tree structures, we convert None to empty dictionaries.
        # https://github.com/pydata/xarray/issues/9560
        {} if v._attrs is None else v._attrs,
    )
    return children, aux
```

**Comment by keewis** [comment]
also, interestingly, if you look at the setter you'll notice that we're storing `None` instead of an empty `dict`: https://github.com/pydata/xarray/blob/7bdc6d4ccc6359143cb6b8d6a7642ca38c3ff550/xarray/namedarray/core.py#L531-L533

**Comment by shoyer** [comment]
> aux = (

I would suggest using public APIs to side-step Xarray's caching layer is possible, e.g., `v.data`, `v.dims`, `v.attrs`.

**Comment by allen-adastra** [comment]
> > aux = (
> 
> I would suggest using public APIs to side-step Xarray's caching layer is possible, e.g., `v.data`, `v.dims`, `v.attrs`.

Nice, seems to work for `.attrs`. I've made a list of the places where the public API works and does not work on flattening (seems to be .data, .coords and .indexes that cause problems) https://github.com/allen-adastra/xarray_jax/pull/14
