### ISSUE TITLE
Discrepancy between `.chunk` and provided encoding with `to_zarr`

### ISSUE THREAD

**Issue by moradology** [pydata/xarray#9565]
### What happened?

While attempting to reverse engineer the chunking behavior of `to_zarr`, I came across (I think) an unexpected difference between two ways of defining the chunking behavior. Here's a short illustration:

via `.chunk`:
```python
chunk_scheme = {
    'time': 1000,
    'lat': 90,
    'lon': 180
}
ds_chunked = ds.chunk(chunk_scheme)
ds_chunked.to_zarr(zarr_path, mode='w')
```
A sample of what is written by the `.chunk` strategy: 
<img width="715" alt="image" src="https://github.com/user-attachments/assets/14c133ae-f4a9-4fd3-a647-2384e93c548e">

via provided `encoding`:
```python
encoding = {'time': {'chunks': (1000,)}, 'lat': {'chunks': (90,)}, 'lon': {'chunks': (180,)}}
ds.to_zarr('/tmp/output_zarr_store_cf', encoding=encoding)
```
A sample of what is written by the supplied `encoding` strategy: 
<img width="671" alt="image" src="https://github.com/user-attachments/assets/9d81e22e-48b0-487e-b14e-8aad813d955a">

Obviously, the above look different from one another.

### What did you expect to happen?

 'time' is a coordinate variable, and these seem to be handled differently in the `.chunk` case than one might expect. The `encoding` case has the chunking one might expect while `.chunk` hasn't been chunked at all here. This, from `.info`:
```
default (chunk) method
Name               : /time
Type               : zarr.core.Array
Data type          : float64
Shape              : (29200,)
Chunk shape        : (29200,)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 233600 (228.1K)
No. bytes stored   : 4692 (4.6K)
Storage ratio      : 49.8
Chunks initialized : 1/1

encoding-based method
Name               : /time
Type               : zarr.core.Array
Data type          : int64
Shape              : (29200,)
Chunk shape        : (1000,)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 233600 (228.1K)
No. bytes stored   : 14686 (14.3K)
Storage ratio      : 15.9
Chunks initialized : 30/30
```

Data variables, too, have significant differences. `pr` is one such variable. For reasons that are pretty unclear, the `.chunk` path is producing what I'd hoped for while the `encoding` path (which does chunk as expected for coordinates, as seen above) appears to be choosing (perhaps sensible) chunks which neatly divide up the shape of this dimension.
```
default (chunk) method
Name               : /pr
Type               : zarr.core.Array
Data type          : float32
Shape              : (29200, 192, 288)
Chunk shape        : (1000, 90, 180)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 6458572800 (6.0G)
No. bytes stored   : 5906005659 (5.5G)
Storage ratio      : 1.1
Chunks initialized : 180/180

encoding-based method
Name               : /pr
Type               : zarr.core.Array
Data type          : float32
Shape              : (29200, 192, 288)
Chunk shape        : (1825, 12, 36)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 6458572800 (6.0G)
No. bytes stored   : 5753062918 (5.4G)
Storage ratio      : 1.1
Chunks initialized : 2048/2048
```

I expected these two approaches to produce the same thing in the end. That seems to be what's suggested [here](https://github.com/pydata/xarray/blob/main/xarray/core/dataset.py#L2421-L2422)

### Minimal Complete Verifiable Example

```Python
import xarray as xr

ds = xr.tutorial.open_dataset('air_temperature')

# `.chunk` path
chunk_scheme = {'lat': 3, 'lon': 5, 'time': 100}
ds_chunked = ds.chunk(chunk_scheme)
ds_chunked.to_zarr('/tmp/output_zarr_store_dot-chunk', mode='w')

# encoding path
encoding = {'lat': {'chunks': (3,)}, 'lon': {'chunks': (5,), 'time': {'chunks': (100,)}
ds.to_zarr('/tmp/output_zarr_store_encoding', encoding=encoding)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [x] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.9 (main, May 22 2024, 12:34:58) [Clang 15.0.0 (clang-1500.3.9.4)]
python-bits: 64
OS: Darwin
OS-release: 23.4.0
machine: arm64
processor: arm
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: None

xarray: 2024.6.0
pandas: 2.2.2
numpy: 2.0.0
scipy: 1.14.0
netCDF4: None
pydap: None
h5netcdf: 1.3.0
h5py: 3.11.0
zarr: 2.18.2
cftime: 1.6.4
nc_time_axis: None
iris: None
bottleneck: None
dask: 2024.8.0
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: 2024.6.1
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.5.0
pip: 24.2
conda: None
pytest: 8.2.2
mypy: None
IPython: 8.26.0
sphinx: None
</details>

**Comment by TomNicholas** [comment]
Thanks for the thorough issue. FYI you could easily make your example into an actual MVCE using `xr.tutorial.open_dataset('air_temperature')`

**Comment by adkinsjd** [comment]
We have noticed this issue, and have found that it occurs when there is an existing zarr group that is being overwritten (even when `mode='w'`). 

Does chunking work properly when you manually delete the existing zarr group at your storage location?

**Comment by max-sixty** [comment]
Closing as inactive with no MCVE but please reopen if there's still something here
