### ISSUE TITLE
open_datatree `group` parameter does not support Iterable[str] 

### ISSUE THREAD

**Issue by aladinor** [pydata/xarray#9597]
### What is your issue?

The annotation typing for the  `group` parameter in the `open_datatree` function receives `str | Iterable[str] | Callable | None = None` for all backends. for example

https://github.com/pydata/xarray/blob/f01096fef402485092c7132dfd042cc8f467ed09/xarray/backends/zarr.py#L1285

However, the current implementation does not support `Iterable[str]`; Therefore, it should be removed in all backends

**Comment by headtr1ck** [comment]
Maybe we should support it instead?
No idea if that makes any sense or how difficult it would be.

**Comment by keewis** [comment]
that's definitely possible (and potentially useful), but since we're trying to get a release out in the next few days, I'd postpone that for now.
