### ISSUE TITLE
Subclassing Dataset for reading a specific netcdf format

### ISSUE THREAD

**Issue by sambarluc** [pydata/xarray#960]
Hi, I decided to give xarray a try. To begin with, I would like to subclass Dataset in order to have an interface to the netcdf output of a specific model. At the moment, I do this by subclassing scipy.io.netcdf_file. What I would like to do is something along these lines:

    class myncfile(Dataset):
       
       def __init__(*args, **kwargs):
          load_somehow_ncfile

However, probably due to my poor programming skills, I have to resort to the following cheap trick:

    class myncfile(Dataset):
   
        def mymethods():
           do_stuff

    def helper(*args, **kwargs):
       ds = xr.open_dataset(*args, **kwargs)
       return myncfile(ds)

Is this the only option, or is there a more elegant and straightforward way to do this?
Thanks.

**Comment by sambarluc** [comment]
Sorry, I'm having trouble with my keyboard! I'll try tro get tge whole story online...

**Comment by sambarluc** [comment]
The initial comment got published before I could actually finish writing as my keybord started pressing tab on its own. I now finished the initial post, sorry for the confusion.

**Comment by shoyer** [comment]
We currently don't expose any interface for overloading `open_dataset` anything other than a `xarray.Dataset`. In theory we could, but I'm not sure we have much to gain here. Calling `xr.Dataset(dataset)` is pretty fast, and we use some slightly messy private API to initialize the dataset created by `open_dataset`.

So I actually like your current approach, except I would probably call `helper` something like `open_myncfile`. The one downside is that the new dataset (with your custom subclass) does not propagate a reference to any file objects, so you can't write `my_ds.close()` or use it with a `with` statement.

(Currently, we save a reference to the opened file in the private `Dataset._file` attribute.)

One thing we *could* do is propagate `_file` from the argument to `Dataset` if found, e.g., switch [this line](https://github.com/pydata/xarray/blob/master/xarray/core/dataset.py#L198) to something like `self._file = getattr(data_vars, '_file', None)`. This could be a pretty easy first pull request (with associated tests).

**Comment by sambarluc** [comment]
I see, at the moment my git skills are rather limited (never worked much on projects with other developers) but I will try to see if I can get up to date and contribute something on these lines. I definitely see the value of keeping a reference to the file for what I need to do with my model data, and it may be valuable to others too.
