### ISSUE TITLE
Pre-commit hook no longer working in my local development environment

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#9605]
### What is your issue?

When I try to run after updating my `main` branch, I get the following error:
```
$ git commit
An error has occurred: InvalidManifestError:
==> File /Users/shoyer/.cache/pre-commit/repowogdr8oo/.pre-commit-hooks.yaml
==> At Hook(id='check-added-large-files')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
Check the log at /Users/shoyer/.cache/pre-commit/pre-commit.log
```

Does anyone more familiar with pre-commit hooks know what changed? I tried updating the `pre-commit` package (`pip install --upgrade pre-commit`) but that didn't seem to help.

**Comment by keewis** [comment]
maybe try running `pre-commit install` again? Otherwise, is there any additional information in `pre-commit.log` (full path at the bottom of what you posted)?

**Comment by max-sixty** [comment]
FWIW it does work on my end. Maybe a `pre-commit` version issue? I'm on 3.8.0

**Comment by headtr1ck** [comment]
Maybe start over by deleting everything: `pre-commit clean` followed by `pre-commit install`

**Comment by shoyer** [comment]
> Maybe start over by deleting everything: `pre-commit clean` followed by `pre-commit install`

This worked, thanks!

**Comment by diego898** [comment]
Hm. Im experiecing this now as well, clean and install does not work

**Comment by max-sixty** [comment]
What's the precise error?
