### ISSUE TITLE
contributing steps for building docs result in file not found: my_file.grib.5b7b6.idx

### ISSUE THREAD

**Issue by rbavery** [pydata/xarray#9639]
### What happened?

I went through the steps in https://docs.xarray.dev/en/stable/contributing.html#how-to-build-the-xarray-documentation

```
conda env create -f ci/requirements/doc.yml
conda activate xarray-docs
pip install -e .
cd doc
make html
```

and when I ran `make html` partway through I get this error. the build still finishes.

```
updating environment: [new config] 1468 added, 0 changed, 0 removed
Can't create file 'my_file.grib.5b7b6.idx'                                                                                        
Traceback (most recent call last):
  File "/home/rave/miniforge3/envs/xarray-docs/lib/python3.12/site-packages/cfgrib/messages.py", line 538, in from_indexpath_or_filestream
    self = cls.from_fieldset(filestream, index_keys, computed_keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rave/miniforge3/envs/xarray-docs/lib/python3.12/site-packages/cfgrib/messages.py", line 378, in from_fieldset
    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rave/miniforge3/envs/xarray-docs/lib/python3.12/site-packages/cfgrib/messages.py", line 391, in from_fieldset_and_iteritems
    for field_id, raw_field in iteritems:
                               ^^^^^^^^^
  File "/home/rave/miniforge3/envs/xarray-docs/lib/python3.12/site-packages/cfgrib/messages.py", line 291, in __iter__
    for message in self.itervalues():
                   ^^^^^^^^^^^^^^^^^
  File "/home/rave/miniforge3/envs/xarray-docs/lib/python3.12/site-packages/cfgrib/messages.py", line 267, in itervalues
    with open(self.filestream.path, "rb") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'my_file.grib'
Can't read index file 'my_file.grib.5b7b6.idx'
Traceback (most recent call last):
  File "/home/rave/miniforge3/envs/xarray-docs/lib/python3.12/site-packages/cfgrib/messages.py", line 547, in from_indexpath_or_filestream
    index_mtime = os.path.getmtime(indexpath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 67, in getmtime
FileNotFoundError: [Errno 2] No such file or directory: 'my_file.grib.5b7b6.idx'
/home/rave/miniforge3/envs/xarray-docs/lib/python3.12/site-packages/cartopy/io/__init__.py:241: DownloadWarning: Downloading: https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_coastline.zip
```

### What did you expect to happen?

no errors during make html

### Minimal Complete Verifiable Example

```Python
# after a fresh clone

conda env create -f ci/requirements/doc.yml
conda activate xarray-docs
pip install -e .
cd doc
make html
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: de3fce8b9e6926994a52617a8976fe3e29ce2fd8
python: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
python-bits: 64
OS: Linux
OS-release: 6.8.0-45-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.3
libnetcdf: 4.9.2

xarray: 2024.9.1.dev69+gde3fce8b
pandas: 2.2.3
numpy: 2.0.2
scipy: 1.14.1
netCDF4: 1.7.1
pydap: None
h5netcdf: 1.4.0
h5py: 3.12.1
zarr: 2.18.3
cftime: 1.6.4
nc_time_axis: None
iris: 3.9.0
bottleneck: 1.4.1
dask: 2024.9.1
distributed: None
matplotlib: 3.9.2
cartopy: 0.24.0
seaborn: 0.13.2
numbagg: None
fsspec: 2024.9.0
cupy: None
pint: None
sparse: 0.15.4
flox: None
numpy_groupies: None
setuptools: 75.1.0
pip: 24.2
conda: None
pytest: None
mypy: None
IPython: 8.28.0
sphinx: 5.3.0

</details>

**Comment by TomNicholas** [comment]
I also see this when building the docs locally. I can't tell from the message if this is our fault or the fault of cfgrib upstream?

**Comment by kmuehlbauer** [comment]
The error is also raised in RTD. The issue is something along the lines of #6512. We could check if any of the suggested solutions would help.

**Comment by kmuehlbauer** [comment]
Discussion in cfgrib: https://github.com/ecmwf/cfgrib/issues/275
