### ISSUE TITLE
Multiple preprocessing functions in open_mfdataset?

### ISSUE THREAD

**Issue by NicWayand** [pydata/xarray#970]
I would like to have multiple functions applied during a open_mfdataset call. 

Using one works great:

```Python
ds = xr.open_mfdataset(files,concat_dim='time',engine='pynio',
    preprocess=lambda x: x.load())
```

Does the current behavior include multiple calls? (apologizes if this is defined somewhere, I couldn't find any multiple calls examples)

Something like:

```Python
ds = xr.open_mfdataset(files,concat_dim='time',engine='pynio',
    preprocess=[lambda x: x.load(),lambda y: y['time']=100])
```

**Comment by jhamman** [comment]
@NicWayand - 

I would think that you could define your own function:

```Python
def preprocess(x):
    x.load()

    x['time'] += 100

    return x
```

Then you could use that in your `lambda` function:


```Python
ds = xr.open_mfdataset(files, concat_dim='time', engine='pynio',
    preprocess=lambda x: preprocess(x))
```

**Comment by NicWayand** [comment]
Yes, that is a perfect solution, thank you!

**Comment by shoyer** [comment]
In @jhamman's solution, you could also just pass the function directly -- there's no need to use a lambda function in preprocess.
