### ISSUE TITLE
Release v0.8.2

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#973]
Once we merge #972, I'd like to release v0.8.2.

It fixes several bugs likely to impact users and is almost completely backwards compatible (except for now automatically aligning in broadcast when we previously raised an error).

CC @jhamman in case he has time to try doing the release process sometime in the next few days.

**Comment by shoyer** [comment]
I'm starting on this now.

**Comment by shoyer** [comment]
Done! Just waiting on CI before I merge https://github.com/conda-forge/xarray-feedstock/pull/9 and send out the release announcement.

**Comment by jhamman** [comment]
Thanks @shoyer.  Apologies for being MIA on this one.
