### ISSUE TITLE
align() should align chunks

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#979]
In the xarray docs I read

> With the current version of dask, there is no automatic alignment of chunks when performing operations between dask arrays with different chunk sizes. If your computation involves multiple dask arrays with different chunks, you may need to explicitly rechunk each array to ensure compatibility. 

While chunk auto-alignment could be done within the dask library, that would be limited to arrays with the same dimensionality and same dims order. For example it would not be possible to have a dask library call to align the chunks on xarrays with the following dims:
- (time, latitude, longitude)
- (time)
- (longitude, latitude)

even if it makes perfect sense in xarray.

I think xarray.align() should take care of it automatically.

A safe algorithm would be to always scale down the chunksize when in conflict. This would prevent having chunks larger than expected, and should minimise (in a greedy way) the number of operations. It's also a good idea on dask.distributed, where merging two chunks could cause one of them to travel on the network - which is very expensive.

e.g. to reconcile chunksizes 
a: (5, 10, 6) 
b: (5, 7, 9)
the algorithm would rechunk both arrays to (5, 7, 3, 6).

Finally, when served with a numpy-based array and a dask-based array, align() should convert the numpy array to dask. The critical use case that would benefit from this behaviour is when align() is invoked inside a broadcast() between a tiny constant you just loaded from csv/pandas/pure python list/whatever - e.g. dims=(time, ) shape=(100, ) - and a huge dask-backed array e.g. dims=(time, scenario) shape=(100, 2\*\*30) chunks=(25, 2\*\*20).

**Comment by shoyer** [comment]
I agree that it would make sense for `xarray.align` to unify chunks in dask arrays, but the documentation is actually a little out of date here: dask.array does now do some minimal automatic rechunking (see [`unify_chunks`](https://github.com/dask/dask/blob/112b541cbb81db04a5753d80da0217aa7f31feeb/dask/array/core.py#L1629) for details). Also, dask array functions, at least those that use [`elemwise`](https://github.com/dask/dask/blob/112b541cbb81db04a5753d80da0217aa7f31feeb/dask/array/core.py#L2195), do automatically coerce NumPy arrays into dask arrays. So adding a tiny numpy array to a huge dask array *does* currently do the right thing.

As you can see, the automatic rechunking algorithm that dask.array currently uses is super simple:  it only reconciles chunks when one array is unchunked. I'm certainly open to more sophisticated options for automatic rechunking (see https://github.com/dask/dask/issues/111), but either way I'd prefer to keep as much of this logic on the dask side as possible. Ideally, we'd simply call `dask.array.unify_chunks` passing in the named dimensions for each array.

**Comment by clarkfitzg** [comment]
As an end user, it would be really nice to not have to worry about chunks at all. I'd like to write the same code in xarray using Numpy and have it do the right thing in dask transparently.

It seems like dask is moving in this direction (see Automatic blocksize for read_csv dask/dask#1147).

Agree with @shoyer that these features belong in dask.

**Comment by shoyer** [comment]
I think dask.array handles this differing chunk sizes better these days, so perhaps this is no longer necessary.
