### ISSUE TITLE
Taking a list of `ds.dims` does not raise warning

### ISSUE THREAD

**Issue by hoxbro** [pydata/xarray#9799]
### What is your issue?

Take the following example:

``` python
import xarray as xr
ds = xr.tutorial.open_dataset('air_temperature')

ds.dims["time"]  # Emits: The return type of `Dataset.dims` will be changed to return a set of ...
list(ds.dims)  # Does not emit a warning
```

I think `__iter__` should also emit a warning, but I'm unsure if the decision not to do it is deliberate.

**Comment by keewis** [comment]
I think that's deliberate: we're trying to transition `ds.dims` from a `dict` to a `set`. The warning should thus only be emitted when trying to interact with `ds.dims` as a `dict` (such as when accessing the data through `__getitem__`), while `__iter__` is also defined on a `set` and thus will continue to work after completing the deprecation cycle – although the question of reproducing the ordering remains for `set`s.

**Comment by shoyer** [comment]
In principle, we could return an ordered set object from `ds.dims` in the future. We already use own wrapper objects for other dict-like properties in Xarray, mostly to add immutability.

**Comment by TomNicholas** [comment]
The relevant PR was https://github.com/pydata/xarray/pull/8500. Which was almost a year ago, so maybe we should think about completing this deprecation cycle soon? I believe @keewis is correct, but agree with @shoyer that we might actually prefer to return an `OrderedSet`.

**Comment by keewis** [comment]
I also think we should use a `OrderedSet`, as otherwise maintaining doctests for `Dataset` will become very tricky.
