### ISSUE TITLE
Split xarray.concat into two functions: xarray.stack and xarray.concat?

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#981]
Currently, `xarray.concat` can do two different things:
- It can concatenate along an existing dimension.
- It can stack along a new dimension.

This seemed convenient when I wrote `concat`, but now seems too automagical.

For example, we need rules to decide which coordinates to expand when stacking (the confusingly named `coords` and `data_vars` arguments), but not when concatenating. Currently we use the heuristics in both cases, which leads to undesirable behavior (#899).

Even if we don't split the public API function, we should split it internally.

**Comment by forman** [comment]
I'd vote for having two functions but still have an option in `xarray.concat` that allows for stacking of variables by adding the new concat dimension. Same option should be available for `xarray.open_mfdataset`.
