### ISSUE TITLE
open_mfdataset and concat of datasets consisting of single data point along a dimension in datetime64 format on python 3.8.5

### ISSUE THREAD

**Issue by nina-caldarella** [pydata/xarray#9830]
### What is your issue?

The described functionality didn't work. It somehow worked on my other computer in Python 3.8.1. I tried matching up the xarray versions. 

It throwed the following warning:

/tmp/ipykernel_175396/3369060392.py:11: SerializationWarning: saving variable time_UTC with floating point data as an integer dtype without any _FillValue to use for NaNs
  ds_combined.to_netcdf(os.path.join(netcdf_path, "combined.nc"), engine="netcdf4")

**Comment by max-sixty** [comment]
xarray's minimum supported python version is now 3.10, so the version running on 3.8 is probably not a recent version of xarray. Please open a full bug report if that's not the reason
