### ISSUE TITLE
ValueError: buffer size must be a multiple of element size

### ISSUE THREAD

**Issue by mgalusha4** [pydata/xarray#9831]
### What is your issue?

Using xr.open_dataset to read .nc files that I am looping through. The loop works for for first 20 or so files and then I get the error "ValueError: buffer size must be a multiple of element size". I already have a check to see if the .nc is an empty file and I am opening the file with "dataset = xr.open_dataset(fsspec.open(filename).open(), chunks={})"

**Comment by mgalusha4** [comment]
sample code:
xr.set_options(file_cache_maxsize=10)
for gcm_folder in GCM_files:
        filename = glob.glob('ClimateProjections/LOCA/LOCA2_downloads/' + gcm_folder + '/*')[0]
        if os.path.getsize(filename) == 0:
            print(gcm_folder, 'is an empty file')
            continue
        dataset = xr.open_dataset(fsspec.open(filename).open(), chunks={})

**Comment by max-sixty** [comment]
Please fill out a bug report, including an MCVE
