### ISSUE TITLE
Functions fail to link within documentation

### ISSUE THREAD

**Issue by JanukanS** [pydata/xarray#9843]
### What is your issue?

# Documentation Issue
When functions and tutorial links are present within the "See Also" section, the functions are not linked to their respective documentation page.

 The example shown is from documentation for the Dataset.sel function built from the repo (also can be seen on the [hosted documentation](https://docs.xarray.dev/en/latest/generated/xarray.Dataset.sel.html))
![sel_link_example](https://github.com/user-attachments/assets/beac6533-5c45-4ee6-9ec0-5cfd88cd2183)

# Possible Solution
I've been able to fix it by using the numpydoc notation for explicitly hyperlinking to other functions i.e.
``:func:`Dataset.isel <xarray.Dataset.isel>` ``
``:func:`DataArray.sel <xarray.DataArray.sel>` ``
![sel_fixed](https://github.com/user-attachments/assets/84c22329-8a09-4849-91b3-273e26bd94d7)

Some other functions with link issues are:
- [DataArray.sel](https://docs.xarray.dev/en/latest/generated/xarray.DataArray.sel.html#xarray.DataArray.sel)
- [DataArray.isel](https://docs.xarray.dev/en/latest/generated/xarray.DataArray.isel.html#xarray.DataArray.isel)
- [Dataset.isel](https://docs.xarray.dev/en/latest/generated/xarray.Dataset.isel.html#xarray.Dataset.isel)

If this issue isn't already being addressed, I can make a list of affected functions and prepare a PR.

**Comment by max-sixty** [comment]
That's a good spot, thank you!

Definitely would take a PR for these...
