### ISSUE TITLE
numpy formatting change breaks tests

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#9873]
### What is your issue?

Numpy 2.2.0 added `shape` to the printed representation of arrays (xref https://github.com/numpy/numpy/pull/27482), which breaks our printed output.

https://github.com/pydata/xarray/actions/runs/12246221251/job/34161706916#step:10:410

The fix should be to "use the print option legacy=2.1 to get the old behaviour", but I think ideally we would do that through a global flag.

**Comment by max-sixty** [comment]
Good spot, thanks. Would be +1 on having the test work with both outputs, seems the closest way of getting this to work?
