### ISSUE TITLE
Appending to zarr along time dimension is not working with grib load from AWS

### ISSUE THREAD

**Issue by snath-xoc** [pydata/xarray#9902]
### What happened?

When loading in multiple timesteps as xarrays from the AWS using Herbie, appending to a single local zarr file results in either overwriting (when using mode = 'a') or not appending at all (when using mode='a-')

### What did you expect to happen?

All timesteps are stored in the zarr file without overwriting

### Minimal Complete Verifiable Example

```Python
from herbie import Herbie
import xarray as xr

ds_20210101 = Herbie(
    "2021-01-01",
    model="gefs",
    fxx=36,
    product="atmos.25",
    member="mean",
).xarray("PRMSL")

ds_20210102 = Herbie(
    "2021-01-02",
    model="gefs",
    fxx=36,
    product="atmos.25",
    member="mean",
).xarray("PRMSL")


ds_20210101.to_zarr('test.zarr',mode='w')
ds_20210102.to_zarr('test.zarr',mode='a-',append_dim='time')


xr.open_zarr('test.zarr').time.values
```

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [ ] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
numpy.datetime64('2021-01-01T00:00:00.000000000')
```
```


### Anything else we need to know?

_No response_

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-200-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.14.3
libnetcdf: 4.9.2

xarray: 2024.9.0
pandas: 2.2.3
numpy: 1.26.4
scipy: 1.14.1
netCDF4: 1.7.1
pydap: None
h5netcdf: None
h5py: 3.11.0
zarr: 2.18.3
cftime: 1.6.4
nc_time_axis: None
iris: None
bottleneck: None
dask: 2024.9.1
distributed: 2024.9.1
matplotlib: 3.9.2
cartopy: 0.24.0
seaborn: 0.13.2
numbagg: None
fsspec: 2024.9.0
cupy: None
pint: 0.24.4
sparse: 0.15.4
flox: None
numpy_groupies: None
setuptools: 75.1.0
pip: 24.2
conda: None
pytest: None
mypy: None
IPython: 8.28.0
sphinx: None


</details>

**Comment by max-sixty** [comment]
This needs to be a much smaller example — please review the instructions
