### ISSUE TITLE
explicit configuration file missing in readthedocs.yml

### ISSUE THREAD

**Issue by kmuehlbauer** [pydata/xarray#9905]
### What is your issue?

According to https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/ 

`configuration: doc/conf.py`

needs to be added to .readthedocs.yaml:

https://github.com/pydata/xarray/blob/76120781f2b2205cc37bd97d0b4ed13d78521d75/.readthedocs.yaml#L17-L19

**Comment by kmuehlbauer** [comment]
This needs to be fixed before January 6 to be on the safe side.

**Comment by shoyer** [comment]
See https://github.com/pydata/xarray/pull/9908
