### ISSUE TITLE
concat() documentation has a wrong keyword

### ISSUE THREAD

**Issue by ceridwen** [pydata/xarray#999]
In https://xray.readthedocs.io/en/stable/combining.html, concat() is called with name='new_dim', but that's not a valid keyword any more.

**Comment by shoyer** [comment]
The `name` argument in the example is actually passed to `pd.Index` instead -- `pd.Index([-90, -100], name='new_dim')`. So I think the example is correct.

**Comment by ceridwen** [comment]
You're right, my mistake.  I admit, I'm finding the concat documentation confusing (which is how I misread that) and can't figure out how to do something (create a new dimension with a given name), but that's a separate issue.

**Comment by shoyer** [comment]
OK, definitely open to feedback here, especially if you have ideas on how to improve either the docs or the interface once you've figured it out!

**Comment by ceridwen** [comment]
I admit, I gave up on figuring out the interface, just did it by concatenating the underlying numpy arrays and then calling DataArray on the resulting array.
